/-
Copyright (c) 2024 Xavier Roblot. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Xavier Roblot
-/
module

public import Mathlib.Algebra.Module.ZLattice.Covolume
public import Mathlib.LinearAlgebra.Matrix.Determinant.Misc
public import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem

/-!
# Regulator of a number field

We define and prove basic results about the regulator of a number field `K`.

## Main definitions and results

* `NumberField.Units.regOfFamily`: the regulator of a family of units of `K`.

* `NumberField.Units.regulator`: the regulator of the number field `K`.

* `Number.Field.Units.regOfFamily_eq_det`: For any infinite place `w'`, the regulator of the
  family `u` is equal to the absolute value of the determinant of the matrix
  `(mult w * log w (u i)))_i, w` where `w` runs through the infinite places distinct from `w'`.

* `Number.Field.Units.regOfFamily_div_regOfFamily`: Let `u` and `v` be two families of units. Assume
  that the subgroup `U` generated by `u` and `torsion K` is contained in the subgroup `V` generated
  by `v` and `torsion K`. Then the ratio `regOfFamily u / regOfFamily v` is equal to the
  index of `U` inside `V`.

## Tags
number field, units, regulator
-/

@[expose] public section

open scoped NumberField

noncomputable section

namespace NumberField.Units

variable (K : Type*) [Field K]

open MeasureTheory NumberField.InfinitePlace Module Submodule
  NumberField NumberField.Units.dirichletUnitTheorem

variable [NumberField K]

set_option backward.isDefEq.respectTransparency false in
open scoped Classical in
/--
Definition of `equivFinRank` / `equivFinRank` 的定义

English:
definition equivFinRank
  signature: : Fin (rank K) ≃ {w : InfinitePlace K // w != w₀}
  body: Fintype.equivOfCardEq by
    rw [Fintype.card_subtype_compl]; rw [Fintype.card_ofSubsingleton]; rw [Fintype.card_fin]; rw [rank]

中文:
定义 equivFinRank
  签名: : 有限集 (rank K) ≃ {w : InfinitePlace K // w != w₀}
  定义体: Fintype.equivOfCardEq by
    rw [Fintype.card_subtype_compl]; rw [Fintype.card_ofSubsingleton]; rw [Fintype.card_fin]; rw [rank]

Depends on / 依赖: Fintype, Fintype.card_fin, Fintype.card_ofSubsingleton, Fintype.card_subtype_compl, Fintype.equivOfCardEq, card_fin, card_ofSubsingleton, card_subtype_compl, equivOfCardEq
-/
def equivFinRank : Fin (rank K) ≃ {w : InfinitePlace K // w != w₀} :=
Fintype.equivOfCardEq by
    rw [Fintype.card_subtype_compl]; rw [Fintype.card_ofSubsingleton]; rw [Fintype.card_fin]; rw [rank]

section regOfFamily

open Matrix

variable {K}

/--
Definition of `IsMaxRank` / `IsMaxRank` 的定义

English:
abbreviation IsMaxRank
  signature: (u : Fin (rank K) -> (𝓞 K)ˣ)
  body: LinearIndependent Real (fun i => logEmbedding K (Additive.ofMul (u i)))

中文:
缩写 IsMaxRank
  签名: (u : 有限集 (rank K) -> (𝓞 K)ˣ)
  定义体: LinearIndependent Real (fun i => logEmbedding K (Additive.ofMul (u i)))

Depends on / 依赖: Additive, Additive.ofMul, LinearIndependent, logEmbedding
-/
abbrev IsMaxRank (u : Fin (rank K) -> (𝓞 K)ˣ) : Prop :=
  LinearIndependent Real (fun i => logEmbedding K (Additive.ofMul (u i)))

open scoped Classical in
/--
Definition of `basisOfIsMaxRank` / `basisOfIsMaxRank` 的定义

English:
definition basisOfIsMaxRank
  signature: {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u)
  body: (basisOfPiSpaceOfLinearIndependent
    ((linearIndependent_equiv (equivFinRank K).symm).mpr hu)).reindex (equivFinRank K).symm

@[simp]

中文:
定义 basisOfIsMaxRank
  签名: {u : 有限集 (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u)
  定义体: (basisOfPiSpaceOfLinearIndependent
    ((linearIndependent_equiv (equivFinRank K).symm).mpr hu)).reindex (equivFinRank K).symm

@[simp]

Depends on / 依赖: basisOfPiSpaceOfLinearIndependent, equivFinRank, linearIndependent_equiv, reindex
-/
def basisOfIsMaxRank {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u) :
    Basis (Fin (rank K)) Real (logSpace K) :=
  (basisOfPiSpaceOfLinearIndependent
    ((linearIndependent_equiv (equivFinRank K).symm).mpr hu)).reindex (equivFinRank K).symm

@[simp]
/--
theorem `basisOfIsMaxRank_apply` / 定理 `basisOfIsMaxRank_apply`

English:
theorem basisOfIsMaxRank_apply
  given: {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u) (i : Fin (rank K))
  proof: by
  simp [basisOfIsMaxRank, Basis.coe_reindex, Equiv.symm_symm, Function.comp_apply,
    coe_basisOfPiSpaceOfLinearIndependent]

中文:
定理 basisOfIsMaxRank_apply
  条件: {u : 有限集 (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u) (i : 有限集 (rank K))
  证明: by
  simp [basisOfIsMaxRank, Basis.coe_reindex, Equiv.symm_symm, Function.comp_apply,
    coe_basisOfPiSpaceOfLinearIndependent]

Depends on / 依赖: Basis.coe_reindex, Equiv.symm_symm, Function, Function.comp_apply, basisOfIsMaxRank, coe_basisOfPiSpaceOfLinearIndependent, coe_reindex, comp_apply, symm_symm
-/
theorem basisOfIsMaxRank_apply {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u) (i : Fin (rank K)) :
    (basisOfIsMaxRank hu) i = logEmbedding K (Additive.ofMul (u i)) := by
  simp [basisOfIsMaxRank, Basis.coe_reindex, Equiv.symm_symm, Function.comp_apply,
    coe_basisOfPiSpaceOfLinearIndependent]

/--
theorem `span_basisOfIsMaxRank` / 定理 `span_basisOfIsMaxRank`

English:
theorem span_basisOfIsMaxRank
  given: {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u)
  proof: by
  rw [Subgroup.toAddSubgroup_closure]; rw [AddMonoidHom.map_closure]; rw [← span_int_eq_addSubgroupClosure]
  congr; ext; simp

中文:
定理 span_basisOfIsMaxRank
  条件: {u : 有限集 (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u)
  证明: by
  rw [Subgroup.toAddSubgroup_closure]; rw [AddMonoidHom.map_closure]; rw [← span_int_eq_addSubgroupClosure]
  congr; ext; simp

Depends on / 依赖: AddMonoidHom, AddMonoidHom.map_closure, Subgroup, Subgroup.toAddSubgroup_closure, map_closure, span_int_eq_addSubgroupClosure, toAddSubgroup_closure
-/
theorem span_basisOfIsMaxRank {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u) :
    (span Int (Set.range (basisOfIsMaxRank hu))).toAddSubgroup =
      AddSubgroup.map (logEmbedding K) (Subgroup.closure (Set.range u)).toAddSubgroup := by
  rw [Subgroup.toAddSubgroup_closure]; rw [AddMonoidHom.map_closure]; rw [← span_int_eq_addSubgroupClosure]
  congr; ext; simp

/--
theorem `finiteIndex_iff_sup_torsion_finiteIndex` / 定理 `finiteIndex_iff_sup_torsion_finiteIndex`

English:
theorem finiteIndex_iff_sup_torsion_finiteIndex
  given: (s : Subgroup (𝓞 K)ˣ)
  proof: by
  refine ⟨fun h => Subgroup.finiteIndex_of_le le_sup_left, fun h => ?_⟩
  rw [Subgroup.finiteIndex_iff]; rw [← Subgroup.relIndex_mul_index (le_sup_left : s <= s ⊔ torsion K)]
  refine Nat.mul_ne_zero ?_ (Subgroup.finiteIndex_iff.mp h)
  rw [Subgroup.relIndex_sup_left]
  exact Subgroup.FiniteIndex

中文:
定理 finiteIndex_iff_sup_torsion_finiteIndex
  条件: (s : 子群 (𝓞 K)ˣ)
  证明: by
  refine ⟨fun h => Subgroup.finiteIndex_of_le le_sup_left, fun h => ?_⟩
  rw [Subgroup.finiteIndex_iff]; rw [← Subgroup.relIndex_mul_index (le_sup_left : s <= s ⊔ torsion K)]
  refine Nat.mul_ne_zero ?_ (Subgroup.finiteIndex_iff.mp h)
  rw [Subgroup.relIndex_sup_left]
  exact Subgroup.FiniteIndex

Depends on / 依赖: FiniteIndex, Nat.mul_ne_zero, Subgroup, Subgroup.FiniteIndex.index_ne_zero, Subgroup.finiteIndex_iff, Subgroup.finiteIndex_iff.mp, Subgroup.finiteIndex_of_le, Subgroup.relIndex_mul_index, Subgroup.relIndex_sup_left, finiteIndex_iff, finiteIndex_of_le, index_ne_zero, le_sup_left, mul_ne_zero, relIndex_mul_index, relIndex_sup_left, torsion
-/
theorem finiteIndex_iff_sup_torsion_finiteIndex (s : Subgroup (𝓞 K)ˣ) :
    s.FiniteIndex ↔ (s ⊔ torsion K).FiniteIndex := by
  refine ⟨fun h => Subgroup.finiteIndex_of_le le_sup_left, fun h => ?_⟩
  rw [Subgroup.finiteIndex_iff]; rw [← Subgroup.relIndex_mul_index (le_sup_left : s <= s ⊔ torsion K)]
  refine Nat.mul_ne_zero ?_ (Subgroup.finiteIndex_iff.mp h)
  rw [Subgroup.relIndex_sup_left]
  exact Subgroup.FiniteIndex.index_ne_zero

set_option backward.isDefEq.respectTransparency false in
open Subgroup in
/--
theorem `isMaxRank_iff_closure_finiteIndex` / 定理 `isMaxRank_iff_closure_finiteIndex`

English:
theorem isMaxRank_iff_closure_finiteIndex
  given: {u : Fin (rank K) -> (𝓞 K)ˣ}
  proof: by
  classical
  have h₁ : (closure (Set.range u) ⊔ torsion K).index != 0 ↔
      Finite (unitLattice K ⧸ span Int (Set.range ((logEmbeddingEquiv K) ∘ Additive.toMul.symm ∘
        QuotientGroup.mk ∘ u))) := by
    change _ ↔ Finite ((unitLattice K).toAddSubgroup ⧸ (span Int (Set.range _)).toAddSubg

中文:
定理 isMaxRank_iff_closure_finiteIndex
  条件: {u : 有限集 (rank K) -> (𝓞 K)ˣ}
  证明: by
  classical
  have h₁ : (closure (Set.range u) ⊔ torsion K).index != 0 ↔
      Finite (unitLattice K ⧸ span Int (Set.range ((logEmbeddingEquiv K) ∘ Additive.toMul.symm ∘
        QuotientGroup.mk ∘ u))) := by
    change _ ↔ Finite ((unitLattice K).toAddSubgroup ⧸ (span Int (Set.range _)).toAddSubg

Depends on / 依赖: AddSubgroup, AddSubgroup.index_ne_zero_iff_finite, Additive, Additive.toMul.symm, Finite, QuotientGroup, QuotientGroup.ker_mk, QuotientGroup.mk, QuotientGroup.range_mk, Set.range, classical, closure, index_map, index_ne_zero_iff_finite, index_top, ker_mk, logEmbeddingEquiv, mul_one, range_mk, toAddSubgroup
-/
theorem isMaxRank_iff_closure_finiteIndex {u : Fin (rank K) -> (𝓞 K)ˣ} :
    IsMaxRank u ↔ (closure (Set.range u)).FiniteIndex := by
  classical
  have h₁ : (closure (Set.range u) ⊔ torsion K).index != 0 ↔
      Finite (unitLattice K ⧸ span Int (Set.range ((logEmbeddingEquiv K) ∘ Additive.toMul.symm ∘
        QuotientGroup.mk ∘ u))) := by
    change _ ↔ Finite ((unitLattice K).toAddSubgroup ⧸ (span Int (Set.range _)).toAddSubgroup)
    rw [← AddSubgroup.index_ne_zero_iff_finite]
    have := index_map (closure (Set.range u)) (QuotientGroup.mk' (torsion K))
    rw [QuotientGroup.ker_mk']; rw [QuotientGroup.range_mk']; rw [index_top]; rw [mul_one] at this
    rw [← this]; rw [← index_toAddSubgroup]; rw [← AddSubgroup.index_map_equiv
        _ (logEmbeddingEquiv K).toAddEquiv]; rw [Set.range_comp]; rw [← LinearEquiv.coe_coe]; rw [← map_span (logEmbeddingEquiv K).toLinearMap]; rw [map_toAddSubgroup]; rw [span_int_eq_addSubgroupClosure]; rw [MonoidHom.map_closure]; rw [toAddSubgroup_closure]; rw [Set.range_comp]; rw [Set.range_comp]; rw [QuotientGroup.coe_mk']; rw [← Equiv.image_symm_eq_preimage]
    rfl
  have h₂ : DiscreteTopology
      (span Int (Set.range fun i => (logEmbedding K) (Additive.ofMul (u i)))) := by
    rw [← SetLike.isDiscrete_iff_discreteTopology]
    refine (inferInstance : DiscreteTopology (unitLattice K)).isDiscrete.mono ?_
    rw [SetLike.coe_subset_coe]; rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    exact ⟨Additive.ofMul (u i), mem_top, rfl⟩
  rw [finiteIndex_iff_sup_torsion_finiteIndex]; rw [finiteIndex_iff]; rw [h₁]; rw [finiteQuotient_iff]; rw [unitLattice_rank]; rw [← Set.finrank]; rw [IsMaxRank]; rw [linearIndependent_iff_card_eq_finrank_span]; rw [Real.finrank_eq_int_finrank_of_discrete h₂]; rw [Set.finrank]; rw [Set.finrank]; rw [← finrank_map_subtype_eq]; rw [map_span]; rw [← Set.range_comp']; rw [eq_comm]
  simp

open scoped Classical in
/--
Definition of `regOfFamily` / `regOfFamily` 的定义

English:
definition regOfFamily
  signature: (u : Fin (rank K) -> (𝓞 K)ˣ)
  body: if hu : IsMaxRank u then
    ZLattice.covolume (span Int (Set.range (basisOfIsMaxRank hu)))
  else 0

中文:
定义 regOfFamily
  签名: (u : 有限集 (rank K) -> (𝓞 K)ˣ)
  定义体: if hu : IsMaxRank u then
    ZLattice.covolume (span Int (Set.range (basisOfIsMaxRank hu)))
  else 0

Depends on / 依赖: IsMaxRank, Set.range, ZLattice, ZLattice.covolume, basisOfIsMaxRank, covolume
-/
def regOfFamily (u : Fin (rank K) -> (𝓞 K)ˣ) : Real :=
  if hu : IsMaxRank u then
    ZLattice.covolume (span Int (Set.range (basisOfIsMaxRank hu)))
  else 0

/--
theorem `regOfFamily_eq_zero` / 定理 `regOfFamily_eq_zero`

English:
theorem regOfFamily_eq_zero
  given: {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : ¬ IsMaxRank u)
  proof: by
  rw [regOfFamily]; rw [dif_neg hu]

中文:
定理 regOfFamily_eq_zero
  条件: {u : 有限集 (rank K) -> (𝓞 K)ˣ} (hu : ¬ IsMaxRank u)
  证明: by
  rw [regOfFamily]; rw [dif_neg hu]

Depends on / 依赖: dif_neg, regOfFamily
-/
theorem regOfFamily_eq_zero {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : ¬ IsMaxRank u) :
    regOfFamily u = 0 := by
  rw [regOfFamily]; rw [dif_neg hu]

open scoped Classical in
/--
theorem `regOfFamily_of_isMaxRank` / 定理 `regOfFamily_of_isMaxRank`

English:
theorem regOfFamily_of_isMaxRank
  given: {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u)
  proof: by
  rw [regOfFamily]; rw [dif_pos hu]

中文:
定理 regOfFamily_of_isMaxRank
  条件: {u : 有限集 (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u)
  证明: by
  rw [regOfFamily]; rw [dif_pos hu]

Depends on / 依赖: dif_pos, regOfFamily
-/
theorem regOfFamily_of_isMaxRank {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u) :
    regOfFamily u = ZLattice.covolume (span Int (Set.range (basisOfIsMaxRank hu))) := by
  rw [regOfFamily]; rw [dif_pos hu]

/--
theorem `regOfFamily_pos` / 定理 `regOfFamily_pos`

English:
theorem regOfFamily_pos
  given: {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u)
  proof: by
  classical
  rw [regOfFamily_of_isMaxRank hu]
  exact ZLattice.covolume_pos _ volume

中文:
定理 regOfFamily_pos
  条件: {u : 有限集 (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u)
  证明: by
  classical
  rw [regOfFamily_of_isMaxRank hu]
  exact ZLattice.covolume_pos _ volume

Depends on / 依赖: ZLattice, ZLattice.covolume_pos, classical, covolume_pos, regOfFamily_of_isMaxRank, volume
-/
theorem regOfFamily_pos {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u) :
    0 < regOfFamily u := by
  classical
  rw [regOfFamily_of_isMaxRank hu]
  exact ZLattice.covolume_pos _ volume

/--
theorem `regOfFamily_ne_zero` / 定理 `regOfFamily_ne_zero`

English:
theorem regOfFamily_ne_zero
  given: {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u)
  proof: (regOfFamily_pos hu).ne'

中文:
定理 regOfFamily_ne_zero
  条件: {u : 有限集 (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u)
  证明: (regOfFamily_pos hu).ne'

Depends on / 依赖: regOfFamily_pos
-/
theorem regOfFamily_ne_zero {u : Fin (rank K) -> (𝓞 K)ˣ} (hu : IsMaxRank u) :
    regOfFamily u != 0 := (regOfFamily_pos hu).ne'

/--
theorem `regOfFamily_ne_zero_iff` / 定理 `regOfFamily_ne_zero_iff`

English:
theorem regOfFamily_ne_zero_iff
  given: {u : Fin (rank K) -> (𝓞 K)ˣ}
  proof: ⟨by simpa using (fun hu => regOfFamily_eq_zero hu).mt, fun hu => regOfFamily_ne_zero hu⟩

中文:
定理 regOfFamily_ne_zero_iff
  条件: {u : 有限集 (rank K) -> (𝓞 K)ˣ}
  证明: ⟨by simpa using (fun hu => regOfFamily_eq_zero hu).mt, fun hu => regOfFamily_ne_zero hu⟩

Depends on / 依赖: regOfFamily_eq_zero, regOfFamily_ne_zero
-/
theorem regOfFamily_ne_zero_iff {u : Fin (rank K) -> (𝓞 K)ˣ} :
    regOfFamily u != 0 ↔ IsMaxRank u :=
  ⟨by simpa using (fun hu => regOfFamily_eq_zero hu).mt, fun hu => regOfFamily_ne_zero hu⟩

open scoped Classical in
/--
theorem `regOfFamily_eq_det'` / 定理 `regOfFamily_eq_det'`

English:
theorem regOfFamily_eq_det'
  given: (u : Fin (rank K) -> (𝓞 K)ˣ)
  proof: by
  by_cases hu : IsMaxRank u
  · rw [regOfFamily_of_isMaxRank hu, ZLattice.covolume_eq_det _
      (((basisOfIsMaxRank hu).restrictScalars Int).reindex (equivFinRank K)), Basis.coe_reindex]
    congr 3 with i
    simp [basisOfIsMaxRank_apply hu]
  · rw [regOfFamily_eq_zero hu, det_eq_zero_of_not_l

中文:
定理 regOfFamily_eq_det'
  条件: (u : 有限集 (rank K) -> (𝓞 K)ˣ)
  证明: by
  by_cases hu : IsMaxRank u
  · rw [regOfFamily_of_isMaxRank hu, ZLattice.covolume_eq_det _
      (((basisOfIsMaxRank hu).restrictScalars Int).reindex (equivFinRank K)), Basis.coe_reindex]
    congr 3 with i
    simp [basisOfIsMaxRank_apply hu]
  · rw [regOfFamily_eq_zero hu, det_eq_zero_of_not_l

Depends on / 依赖: Basis.coe_reindex, IsMaxRank, ZLattice, ZLattice.covolume_eq_det, abs_zero, basisOfIsMaxRank, basisOfIsMaxRank_apply, coe_reindex, covolume_eq_det, det_eq_zero_of_not_linearIndependent_rows, equivFinRank, linearIndependent_equiv, regOfFamily_eq_zero, regOfFamily_of_isMaxRank, reindex, restrictScalars
-/
theorem regOfFamily_eq_det' (u : Fin (rank K) -> (𝓞 K)ˣ) :
    regOfFamily u =
      |(of fun i => logEmbedding K (Additive.ofMul (u ((equivFinRank K).symm i)))).det| := by
  by_cases hu : IsMaxRank u
  · rw [regOfFamily_of_isMaxRank hu, ZLattice.covolume_eq_det _
      (((basisOfIsMaxRank hu).restrictScalars Int).reindex (equivFinRank K)), Basis.coe_reindex]
    congr 3 with i
    simp [basisOfIsMaxRank_apply hu]
  · rw [regOfFamily_eq_zero hu, det_eq_zero_of_not_linearIndependent_rows, abs_zero]
    rwa [IsMaxRank, ← linearIndependent_equiv (equivFinRank K).symm] at hu

open scoped Classical in
/--
theorem `abs_det_eq_abs_det` / 定理 `abs_det_eq_abs_det`

English:
theorem abs_det_eq_abs_det
  statement: (u : Fin (rank K) -> (𝓞 K)ˣ)
  proof: by
  -- We construct an equiv `Fin (rank K + 1) ≃ InfinitePlace K` from `e₂.symm`
  let f : Fin (rank K + 1) ≃ InfinitePlace K :=
    (finSuccEquiv _).trans ((Equiv.optionSubtype _).symm e₁.symm).val
  -- And `g` corresponds to the restriction of `f⁻¹` to `{w // w ≠ w₂}`
  let g : {w // w != w₂} ≃ F

中文:
定理 abs_det_eq_abs_det
  结论: (u : 有限集 (rank K) -> (𝓞 K)ˣ)
  证明: by
  -- We construct an equiv `Fin (rank K + 1) ≃ InfinitePlace K` from `e₂.symm`
  let f : Fin (rank K + 1) ≃ InfinitePlace K :=
    (finSuccEquiv _).trans ((Equiv.optionSubtype _).symm e₁.symm).val
  -- And `g` corresponds to the restriction of `f⁻¹` to `{w // w ≠ w₂}`
  let g : {w // w != w₂} ≃ F
-/
theorem abs_det_eq_abs_det (u : Fin (rank K) -> (𝓞 K)ˣ)
    {w₁ w₂ : InfinitePlace K} (e₁ : {w // w != w₁} ≃ Fin (rank K))
    (e₂ : {w // w != w₂} ≃ Fin (rank K)) :
    |(of fun i w : {w // w != w₁} => (mult w.val : Real) * (w.val (u (e₁ i) : K)).log).det| =
    |(of fun i w : {w // w != w₂} => (mult w.val : Real) * (w.val (u (e₂ i) : K)).log).det| := by
  -- We construct an equiv `Fin (rank K + 1) ≃ InfinitePlace K` from `e₂.symm`
  let f : Fin (rank K + 1) ≃ InfinitePlace K :=
    (finSuccEquiv _).trans ((Equiv.optionSubtype _).symm e₁.symm).val
  -- And `g` corresponds to the restriction of `f⁻¹` to `{w // w ≠ w₂}`
  let g : {w // w != w₂} ≃ Fin (rank K) :=
    (Equiv.subtypeEquiv f.symm (fun _ => by simp [f])).trans
      (finSuccAboveEquiv (f.symm w₂)).symm
have h_col := congr_arg abs det_permute (g.trans e₂.symm)
    (of fun i w : {w // w != w₂} => (mult w.val : Real) * (w.val (u (e₂ i) : K)).log)
  rw [abs_mul]; rw [← Int.cast_abs]; rw [Equiv.Perm.sign_abs]; rw [Int.cast_one]; rw [one_mul] at h_col
  rw [← h_col]
have h := congr_arg abs submatrix_succAbove_det_eq_negOnePow_submatrix_succAbove_det'
    (of fun i w => (mult (f w) : Real) * ((f w) (u i)).log) ?_ 0 (f.symm w₂)
  · rw [← det_reindex_self e₁, ← det_reindex_self g]
    · rw [Units.smul_def, abs_zsmul, Int.abs_negOnePow, one_smul] at h
      convert! h
      · ext; simp only [ne_eq, reindex_apply, submatrix_apply, of_apply, Equiv.apply_symm_apply,
          Equiv.trans_apply, Fin.succAbove_zero, id_eq, finSuccEquiv_succ,
          Equiv.optionSubtype_symm_apply_apply_coe, f]
      · ext; simp only [ne_eq, Equiv.coe_trans, reindex_apply, submatrix_apply, Function.comp_apply,
          Equiv.apply_symm_apply, id_eq, of_apply]; rfl
  · intro _
    simp_rw [of_apply, ← Real.log_pow]
    rw [← Real.log_prod]; rw [Equiv.prod_comp f (fun w => (w (u _) ^ (mult w)))]; rw [prod_eq_abs_norm]; rw [Units.norm]; rw [Rat.cast_one]; rw [Real.log_one]
exact fun _ _ => pow_ne_zero _ (map_ne_zero _).mpr (coe_ne_zero _)

open scoped Classical in
/--
theorem `regOfFamily_eq_det` / 定理 `regOfFamily_eq_det`

English:
theorem regOfFamily_eq_det
  statement: (u : Fin (rank K) -> (𝓞 K)ˣ) (w' : InfinitePlace K)
  proof: by
  simp [regOfFamily_eq_det', abs_det_eq_abs_det u e (equivFinRank K).symm, logEmbedding]

中文:
定理 regOfFamily_eq_det
  结论: (u : 有限集 (rank K) -> (𝓞 K)ˣ) (w' : InfinitePlace K)
  证明: by
  simp [regOfFamily_eq_det', abs_det_eq_abs_det u e (equivFinRank K).symm, logEmbedding]

Depends on / 依赖: abs_det_eq_abs_det, equivFinRank, logEmbedding, regOfFamily_eq_det
-/
theorem regOfFamily_eq_det (u : Fin (rank K) -> (𝓞 K)ˣ) (w' : InfinitePlace K)
    (e : {w // w != w'} ≃ Fin (rank K)) :
    regOfFamily u =
      |(of fun i w : {w // w != w'} => (mult w.val : Real) * Real.log (w.val (u (e i) : K))).det| := by
  simp [regOfFamily_eq_det', abs_det_eq_abs_det u e (equivFinRank K).symm, logEmbedding]

open scoped Classical in
/--
theorem `finrank_mul_regOfFamily_eq_det` / 定理 `finrank_mul_regOfFamily_eq_det`

English:
theorem finrank_mul_regOfFamily_eq_det
  statement: (u : Fin (rank K) -> (𝓞 K)ˣ) (w' : InfinitePlace K)
  proof: by
  let f : Fin (rank K + 1) ≃ InfinitePlace K :=
    (finSuccEquiv _).trans ((Equiv.optionSubtype _).symm e.symm).val
  let g : {w // w != w'} ≃ Fin (rank K) :=
    (Equiv.subtypeEquiv f.symm (fun _ => by simp [f])).trans (finSuccAboveEquiv (f.symm w')).symm
  rw [← det_reindex_self f.symm]; rw [d

中文:
定理 finrank_mul_regOfFamily_eq_det
  结论: (u : 有限集 (rank K) -> (𝓞 K)ˣ) (w' : InfinitePlace K)
  证明: by
  let f : Fin (rank K + 1) ≃ InfinitePlace K :=
    (finSuccEquiv _).trans ((Equiv.optionSubtype _).symm e.symm).val
  let g : {w // w != w'} ≃ Fin (rank K) :=
    (Equiv.subtypeEquiv f.symm (fun _ => by simp [f])).trans (finSuccAboveEquiv (f.symm w')).symm
  rw [← det_reindex_self f.symm]; rw [d

Depends on / 依赖: Equiv.optionSubtype, Equiv.subtypeEquiv, InfinitePlace, abs_mul, abs_neg_one_pow, det_eq_sum_row_mul_submatrix_succAbove_succAbove_det, det_reindex_self, e.symm, f.sym, f.symm, f.symm.sum_comp, finSuccAboveEquiv, finSuccEquiv, one_mul, optionSubtype, reindex_apply, simp_rw, submatrix_submatrix, subtypeEquiv, sum_comp
-/
theorem finrank_mul_regOfFamily_eq_det (u : Fin (rank K) -> (𝓞 K)ˣ) (w' : InfinitePlace K)
    (e : {w // w != w'} ≃ Fin (rank K)) :
    finrank Rat K * regOfFamily u =
      |(of (fun i w : InfinitePlace K =>
        if h : i = w' then (w.mult : Real) else w.mult * (w (u (e ⟨i, h⟩))).log)).det| := by
  let f : Fin (rank K + 1) ≃ InfinitePlace K :=
    (finSuccEquiv _).trans ((Equiv.optionSubtype _).symm e.symm).val
  let g : {w // w != w'} ≃ Fin (rank K) :=
    (Equiv.subtypeEquiv f.symm (fun _ => by simp [f])).trans (finSuccAboveEquiv (f.symm w')).symm
  rw [← det_reindex_self f.symm]; rw [det_eq_sum_row_mul_submatrix_succAbove_succAbove_det _ (f.symm w')
    (f.symm w')]; rw [abs_mul]; rw [abs_mul]; rw [abs_neg_one_pow]; rw [one_mul]
  · simp_rw [reindex_apply, submatrix_submatrix, ← f.symm.sum_comp, f.symm_symm, submatrix_apply,
      Function.comp_def, Equiv.apply_symm_apply, of_apply, dif_pos, ← Nat.cast_sum, sum_mult_eq,
      Nat.abs_cast]
    rw [regOfFamily_eq_det u w' e]; rw [← Matrix.det_reindex_self g]
    congr with i j
    rw [reindex_apply]; rw [submatrix_apply]; rw [submatrix_apply]; rw [of_apply]; rw [of_apply]; rw [dif_neg]
    rfl
  · simp_rw [Equiv.forall_congr_left f, ← f.symm.sum_comp, reindex_apply, submatrix_apply,
      of_apply, f.symm_symm, f.apply_symm_apply, Finset.sum_dite_irrel, ne_eq,
      EmbeddingLike.apply_eq_iff_eq]
    intro _ h
    rw [dif_neg h]; rw [sum_mult_mul_log]

end regOfFamily

section regulator

open scoped Classical in
/--
Definition of `regulator` / `regulator` 的定义

English:
definition regulator
  signature: : Real
  body: ZLattice.covolume (unitLattice K)

中文:
定义 regulator
  签名: : 实数
  定义体: ZLattice.covolume (unitLattice K)

Depends on / 依赖: ZLattice, ZLattice.covolume, covolume, unitLattice
-/
def regulator : Real := ZLattice.covolume (unitLattice K)

/--
theorem `isMaxRank_fundSystem` / 定理 `isMaxRank_fundSystem`

English:
theorem isMaxRank_fundSystem
  proof: by
  classical
  convert! ((basisUnitLattice K).ofZLatticeBasis Real (unitLattice K)).linearIndependent
  rw [logEmbedding_fundSystem]; rw [Basis.ofZLatticeBasis_apply]

中文:
定理 isMaxRank_fundSystem
  证明: by
  classical
  convert! ((basisUnitLattice K).ofZLatticeBasis Real (unitLattice K)).linearIndependent
  rw [logEmbedding_fundSystem]; rw [Basis.ofZLatticeBasis_apply]

Depends on / 依赖: Basis.ofZLatticeBasis_apply, basisUnitLattice, classical, convert, linearIndependent, logEmbedding_fundSystem, ofZLatticeBasis, ofZLatticeBasis_apply, unitLattice
-/
theorem isMaxRank_fundSystem :
    IsMaxRank (fundSystem K) := by
  classical
  convert! ((basisUnitLattice K).ofZLatticeBasis Real (unitLattice K)).linearIndependent
  rw [logEmbedding_fundSystem]; rw [Basis.ofZLatticeBasis_apply]

open scoped Classical in
/--
theorem `basisOfIsMaxRank_fundSystem` / 定理 `basisOfIsMaxRank_fundSystem`

English:
theorem basisOfIsMaxRank_fundSystem
  proof: by
  ext
  rw [Basis.ofZLatticeBasis_apply]; rw [basisOfIsMaxRank_apply]; rw [logEmbedding_fundSystem]

中文:
定理 basisOfIsMaxRank_fundSystem
  证明: by
  ext
  rw [Basis.ofZLatticeBasis_apply]; rw [basisOfIsMaxRank_apply]; rw [logEmbedding_fundSystem]

Depends on / 依赖: Basis.ofZLatticeBasis_apply, basisOfIsMaxRank_apply, logEmbedding_fundSystem, ofZLatticeBasis_apply
-/
theorem basisOfIsMaxRank_fundSystem :
    basisOfIsMaxRank (isMaxRank_fundSystem K) = (basisUnitLattice K).ofZLatticeBasis Real := by
  ext
  rw [Basis.ofZLatticeBasis_apply]; rw [basisOfIsMaxRank_apply]; rw [logEmbedding_fundSystem]

/--
theorem `regulator_eq_regOfFamily_fundSystem` / 定理 `regulator_eq_regOfFamily_fundSystem`

English:
theorem regulator_eq_regOfFamily_fundSystem
  proof: by
  classical
  rw [regOfFamily_of_isMaxRank (isMaxRank_fundSystem K)]; rw [regulator]; rw [← (basisUnitLattice K).ofZLatticeBasis_span Real]; rw [basisOfIsMaxRank_fundSystem]

中文:
定理 regulator_eq_regOfFamily_fundSystem
  证明: by
  classical
  rw [regOfFamily_of_isMaxRank (isMaxRank_fundSystem K)]; rw [regulator]; rw [← (basisUnitLattice K).ofZLatticeBasis_span Real]; rw [basisOfIsMaxRank_fundSystem]

Depends on / 依赖: basisOfIsMaxRank_fundSystem, basisUnitLattice, classical, isMaxRank_fundSystem, ofZLatticeBasis_span, regOfFamily_of_isMaxRank, regulator
-/
theorem regulator_eq_regOfFamily_fundSystem :
    regulator K = regOfFamily (fundSystem K) := by
  classical
  rw [regOfFamily_of_isMaxRank (isMaxRank_fundSystem K)]; rw [regulator]; rw [← (basisUnitLattice K).ofZLatticeBasis_span Real]; rw [basisOfIsMaxRank_fundSystem]

/--
theorem `regulator_pos` / 定理 `regulator_pos`

English:
theorem regulator_pos
  statement: 0 < regulator K
  proof: regulator_eq_regOfFamily_fundSystem K ▸ regOfFamily_pos (isMaxRank_fundSystem K)

中文:
定理 regulator_pos
  结论: 0 < regulator K
  证明: regulator_eq_regOfFamily_fundSystem K ▸ regOfFamily_pos (isMaxRank_fundSystem K)

Depends on / 依赖: isMaxRank_fundSystem, regOfFamily_pos, regulator_eq_regOfFamily_fundSystem
-/
theorem regulator_pos : 0 < regulator K :=
  regulator_eq_regOfFamily_fundSystem K ▸ regOfFamily_pos (isMaxRank_fundSystem K)

/--
theorem `regulator_ne_zero` / 定理 `regulator_ne_zero`

English:
theorem regulator_ne_zero
  statement: regulator K != 0
  proof: (regulator_pos K).ne'

中文:
定理 regulator_ne_zero
  结论: regulator K != 0
  证明: (regulator_pos K).ne'

Depends on / 依赖: regulator_pos
-/
theorem regulator_ne_zero : regulator K != 0 :=
  (regulator_pos K).ne'

open scoped Classical in
/--
theorem `regulator_eq_det'` / 定理 `regulator_eq_det'`

English:
theorem regulator_eq_det'
  proof: by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [regOfFamily_eq_det']

中文:
定理 regulator_eq_det'
  证明: by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [regOfFamily_eq_det']

Depends on / 依赖: regOfFamily_eq_det, regulator_eq_regOfFamily_fundSystem
-/
theorem regulator_eq_det' :
    regulator K = |(Matrix.of fun i =>
      logEmbedding K (Additive.ofMul (fundSystem K ((equivFinRank K).symm i)))).det| := by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [regOfFamily_eq_det']

open scoped Classical in
/--
theorem `regulator_eq_det` / 定理 `regulator_eq_det`

English:
theorem regulator_eq_det
  given: (w' : InfinitePlace K) (e : {w // w != w'} ≃ Fin (rank K))
  proof: by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [regOfFamily_eq_det]

中文:
定理 regulator_eq_det
  条件: (w' : InfinitePlace K) (e : {w // w != w'} ≃ 有限集 (rank K))
  证明: by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [regOfFamily_eq_det]

Depends on / 依赖: regOfFamily_eq_det, regulator_eq_regOfFamily_fundSystem
-/
theorem regulator_eq_det (w' : InfinitePlace K) (e : {w // w != w'} ≃ Fin (rank K)) :
    regulator K =
      |(Matrix.of fun i w : {w // w != w'} => (mult w.val : Real) *
        Real.log (w.val (fundSystem K (e i) : K))).det| := by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [regOfFamily_eq_det]

open scoped Classical in
/--
theorem `finrank_mul_regulator_eq_det` / 定理 `finrank_mul_regulator_eq_det`

English:
theorem finrank_mul_regulator_eq_det
  given: (w' : InfinitePlace K) (e : {w // w != w'} ≃ Fin (rank K))
  proof: by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [finrank_mul_regOfFamily_eq_det]

中文:
定理 finrank_mul_regulator_eq_det
  条件: (w' : InfinitePlace K) (e : {w // w != w'} ≃ 有限集 (rank K))
  证明: by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [finrank_mul_regOfFamily_eq_det]

Depends on / 依赖: finrank_mul_regOfFamily_eq_det, regulator_eq_regOfFamily_fundSystem
-/
theorem finrank_mul_regulator_eq_det (w' : InfinitePlace K) (e : {w // w != w'} ≃ Fin (rank K)) :
    finrank Rat K * regulator K =
      |(Matrix.of (fun i w : InfinitePlace K =>
        if h : i = w' then (w.mult : Real) else w.mult * (w (fundSystem K (e ⟨i, h⟩))).log)).det| := by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [finrank_mul_regOfFamily_eq_det]

end regulator

section index

open ZLattice

variable {K}

/--
theorem `regOfFamily_div_regOfFamily` / 定理 `regOfFamily_div_regOfFamily`

English:
theorem regOfFamily_div_regOfFamily
  statement: {u v : Fin (rank K) -> (𝓞 K)ˣ} (hv : IsMaxRank v)
  proof: by
  classical
  by_cases hu : IsMaxRank u
  · have : span Int (Set.range (basisOfIsMaxRank hu)) <= span Int (Set.range (basisOfIsMaxRank hv)) := by
      rw [← toAddSubgroup_le]; rw [span_basisOfIsMaxRank hu]; rw [span_basisOfIsMaxRank hv]; rw [← map_logEmbedding_sup_torsion (Subgroup.closure (Set.

中文:
定理 regOfFamily_div_regOfFamily
  结论: {u v : 有限集 (rank K) -> (𝓞 K)ˣ} (hv : IsMaxRank v)
  证明: by
  classical
  by_cases hu : IsMaxRank u
  · have : span Int (Set.range (basisOfIsMaxRank hu)) <= span Int (Set.range (basisOfIsMaxRank hv)) := by
      rw [← toAddSubgroup_le]; rw [span_basisOfIsMaxRank hu]; rw [span_basisOfIsMaxRank hv]; rw [← map_logEmbedding_sup_torsion (Subgroup.closure (Set.

Depends on / 依赖: AddSubgroup, AddSubgroup.map_mono, IsMaxRank, OrderIso, OrderIso.le_iff_le, Set.range, Subgroup, Subgroup.closure, SupHomClass, SupHomClass.map_sup, basisOfIsMaxRank, classical, closure, le_iff_le, map_logEmbedding_sup_torsion, map_mono, map_sup, span_basisOfIsMaxRank, toAddSubgroup, toAddSubgroup_le
-/
theorem regOfFamily_div_regOfFamily {u v : Fin (rank K) -> (𝓞 K)ˣ} (hv : IsMaxRank v)
    (h : Subgroup.closure (Set.range u) ⊔ torsion K <= Subgroup.closure (Set.range v) ⊔ torsion K) :
    regOfFamily u / regOfFamily v = (Subgroup.closure (Set.range u) ⊔ (torsion K)).relIndex
      (Subgroup.closure (Set.range v) ⊔ (torsion K)) := by
  classical
  by_cases hu : IsMaxRank u
  · have : span Int (Set.range (basisOfIsMaxRank hu)) <= span Int (Set.range (basisOfIsMaxRank hv)) := by
      rw [← toAddSubgroup_le]; rw [span_basisOfIsMaxRank hu]; rw [span_basisOfIsMaxRank hv]; rw [← map_logEmbedding_sup_torsion (Subgroup.closure (Set.range u)).toAddSubgroup]; rw [← map_logEmbedding_sup_torsion (Subgroup.closure (Set.range v)).toAddSubgroup]; rw [← SupHomClass.map_sup]; rw [← SupHomClass.map_sup]
exact AddSubgroup.map_mono (OrderIso.le_iff_le Subgroup.toAddSubgroup).mpr h
    rw [regOfFamily_of_isMaxRank hu]; rw [regOfFamily_of_isMaxRank hv]; rw [covolume_div_covolume_eq_relIndex _ _ this]; rw [span_basisOfIsMaxRank hu]; rw [span_basisOfIsMaxRank hv]; rw [AddSubgroup.relIndex_map_map]; rw [logEmbedding_ker]; rw [← OrderIso.map_sup]; rw [← OrderIso.map_sup]; rw [← Subgroup.relIndex_toAddSubgroup]
  · rw [regOfFamily_eq_zero hu, zero_div, eq_comm, Nat.cast_eq_zero]
    have : (Subgroup.closure (Set.range v) ⊔ torsion K).index != 0 := by
      rw [← Subgroup.finiteIndex_iff]; rw [← finiteIndex_iff_sup_torsion_finiteIndex]
      exact isMaxRank_iff_closure_finiteIndex.mp hv
    rwa [← mul_eq_zero_iff_right this, Subgroup.relIndex_mul_index h,
      ← Subgroup.not_finiteIndex_iff, ← finiteIndex_iff_sup_torsion_finiteIndex,
      ← isMaxRank_iff_closure_finiteIndex.not]

/--
theorem `regOfFamily_div_regulator` / 定理 `regOfFamily_div_regulator`

English:
theorem regOfFamily_div_regulator
  given: (u : Fin (rank K) -> (𝓞 K)ˣ)
  proof: by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [regOfFamily_div_regOfFamily (isMaxRank_fundSystem K)
    (by simp only [closure_fundSystem_sup_torsion_eq_top]; rw [le_top]),
    closure_fundSystem_sup_torsion_eq_top, Subgroup.relIndex_top_right]

中文:
定理 regOfFamily_div_regulator
  条件: (u : 有限集 (rank K) -> (𝓞 K)ˣ)
  证明: by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [regOfFamily_div_regOfFamily (isMaxRank_fundSystem K)
    (by simp only [closure_fundSystem_sup_torsion_eq_top]; rw [le_top]),
    closure_fundSystem_sup_torsion_eq_top, Subgroup.relIndex_top_right]

Depends on / 依赖: Subgroup, Subgroup.relIndex_top_right, closure_fundSystem_sup_torsion_eq_top, isMaxRank_fundSystem, le_top, regOfFamily_div_regOfFamily, regulator_eq_regOfFamily_fundSystem, relIndex_top_right
-/
theorem regOfFamily_div_regulator (u : Fin (rank K) -> (𝓞 K)ˣ) :
    regOfFamily u / regulator K = (Subgroup.closure (Set.range u) ⊔ (torsion K)).index := by
  rw [regulator_eq_regOfFamily_fundSystem]; rw [regOfFamily_div_regOfFamily (isMaxRank_fundSystem K)
    (by simp only [closure_fundSystem_sup_torsion_eq_top]; rw [le_top]),
    closure_fundSystem_sup_torsion_eq_top, Subgroup.relIndex_top_right]

end index

end Units

end NumberField
