/-
Copyright (c) 2024 Joël Riou. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joël Riou
-/
module

public import Mathlib.Algebra.Category.Grp.Abelian
public import Mathlib.Algebra.Category.Grp.Adjunctions
public import Mathlib.Algebra.Homology.DerivedCategory.Ext.Basic
public import Mathlib.CategoryTheory.Sites.Abelian
public import Mathlib.CategoryTheory.Sites.ConstantSheaf
public import Mathlib.Algebra.Homology.DerivedCategory.Ext.EnoughInjectives
public import Mathlib.Algebra.Category.Grp.Zero
public import Mathlib.CategoryTheory.Adjunction.Additive

/-!
# Sheaf cohomology

Let `C` be a category equipped with a Grothendieck topology `J`.
We define the cohomology types `Sheaf.H F n` of an abelian
sheaf `F` on the site `(C, J)` for all `n : ℕ`. These abelian
groups are defined as the `Ext`-groups from the constant abelian
sheaf with values `ℤ` (actually `ULift ℤ`) to `F`.

We also define `Sheaf.cohomologyPresheaf F n : Cᵒᵖ ⥤ AddCommGrpCat`
which is the presheaf which sends `U` to the `n`th `Ext`-group
from the free abelian sheaf generated by the presheaf
of sets `yoneda.obj U` to `F`.

## TODO
* if `U` is a terminal object of `C`, define an isomorphism
  `(F.cohomologyPresheaf n).obj (Opposite.op U) ≃+ Sheaf.H F n`.
* if `U : C`, define an isomorphism
  `(F.cohomologyPresheaf n).obj (Opposite.op U) ≃+ Sheaf.H (F.over U) n`.

-/

@[expose] public noncomputable section

assert_not_exists TwoSidedIdeal

universe w' w v u

namespace CategoryTheory

open Abelian

variable {C : Type u} [Category.{v} C] {J : GrothendieckTopology C}

namespace Sheaf

section

variable (F : Sheaf J AddCommGrpCat.{w})
  [HasSheafify J AddCommGrpCat.{w}] [HasExt.{w'} (Sheaf J AddCommGrpCat.{w})]

/-- The cohomology of an abelian sheaf in degree `n`. -/
/-
**CategoryTheory.Sheaf.H** 是 Mathlib 中的一个缩写定义，位于命名空间 `CategoryTheory.Sheaf`。
形式化陈述：H (n : Nat) : Type w'
参数：n : Nat。
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `CategoryTheory.instHasWeakSheafifyOfHasSheafify`：∀ {C : Type u₁} [inst :
 CategoryTheory.Category.{v₁, u₁} C] (J : CategoryTheory.GrothendieckTopology C)
 (A : Type u₂)   [inst_1 : CategoryTh…

--- 原说明 ---
The cohomology of an abelian sheaf in degree `n`.
-/
abbrev H (n : ℕ) : Type w' :=
  Ext ((constantSheaf J AddCommGrpCat.{w}).obj (AddCommGrpCat.of (ULift ℤ))) F n

end

section

variable [HasSheafify J AddCommGrpCat.{v}] [HasExt.{w'} (Sheaf J AddCommGrpCat.{v})]

variable (J) in
/-- The bifunctor which sends an abelian sheaf `F` and an object `U` to the
`n`th Ext-group from the free abelian sheaf generated by the
presheaf of sets `yoneda.obj U` to `F`. -/
/-
**CategoryTheory.Sheaf.cohomologyPresheafFunctor** 是 Mathlib 中的一个定义，位于命名空间 `Cate
goryTheory.Sheaf`。
形式化陈述：cohomologyPresheafFunctor (n : Nat) : Sheaf J AddCommGrpCat.{v} ⥤ Cᵒᵖ ⥤ Ad
dCommGrpCat.{w'}
参数：n : Nat。
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `CategoryTheory.instHasWeakSheafifyOfHasSheafify`：∀ {C : Type u₁} [inst :
 CategoryTheory.Category.{v₁, u₁} C] (J : CategoryTheory.GrothendieckTopology C)
 (A : Type u₂)   [inst_1 : CategoryTh…

--- 原说明 ---
The bifunctor which sends an abelian sheaf `F` and an object `U` to the
`n`th Ext-group from the free abelian sheaf generated by the
presheaf of sets `yoneda.obj U` to `F`.
-/
def cohomologyPresheafFunctor (n : ℕ) :
    Sheaf J AddCommGrpCat.{v} ⥤ Cᵒᵖ ⥤ AddCommGrpCat.{w'} :=
  Functor.flip
    (Functor.op (yoneda ⋙ (Functor.whiskeringRight _ _ _).obj
      AddCommGrpCat.free ⋙ presheafToSheaf _ _) ⋙ extFunctor n)

/-- Given an abelian sheaf `F`, this is the presheaf which sends `U`
to the `n`th Ext-group from the free abelian sheaf generated by the
presheaf of sets `yoneda.obj U` to `F`. -/
/-
**CategoryTheory.Sheaf.cohomologyPresheaf** 是 Mathlib 中的一个缩写定义，位于命名空间 `CategoryT
heory.Sheaf`。
形式化陈述：cohomologyPresheaf (F : Sheaf J AddCommGrpCat.{v}) (n : Nat) : Cᵒᵖ ⥤ AddCo
mmGrpCat.{w'}
参数：F : Sheaf J AddCommGrpCat.{v}；n : Nat。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given an abelian sheaf `F`, this is the presheaf which sends `U`
to the `n`th Ext-group from the free abelian sheaf generated by the
presheaf of sets `yoneda.obj U` to `F`.
-/
abbrev cohomologyPresheaf (F : Sheaf J AddCommGrpCat.{v}) (n : ℕ) :
    Cᵒᵖ ⥤ AddCommGrpCat.{w'} :=
  (cohomologyPresheafFunctor J n).obj F

/-- Given an abelian sheaf `F` on `(C, J)`, `n : ℕ` and `X : C`, this is
the degree-`n` sheaf cohomology of `X` with values in `F`. -/
/-
**CategoryTheory.Sheaf.H'** 是 Mathlib 中的一个缩写定义，位于命名空间 `CategoryTheory.Sheaf`。
形式化陈述：H' (F : Sheaf J AddCommGrpCat.{v}) (n : Nat) (X : C) : AddCommGrpCat.{w'}
参数：F : Sheaf J AddCommGrpCat.{v}；n : Nat；X : C。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given an abelian sheaf `F` on `(C, J)`, `n : ℕ` and `X : C`, this is
the degree-`n` sheaf cohomology of `X` with values in `F`.
-/
abbrev H' (F : Sheaf J AddCommGrpCat.{v}) (n : ℕ) (X : C) :
    AddCommGrpCat.{w'} :=
  (F.cohomologyPresheaf n).obj (Opposite.op X)

end

section

variable [HasSheafify J AddCommGrpCat.{w}] [HasExt.{w'} (Sheaf J AddCommGrpCat.{w})]

/-
**CategoryTheory.Sheaf.** 是 Mathlib 中的一个实例，位于命名空间 `CategoryTheory.Sheaf`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance (F : Sheaf J AddCommGrpCat.{w}) {n : ℕ} [Injective F] : Subsingleton (H F (n + 1)) :=
  subsingleton_of_forall_eq 0 fun x ↦ (Ext.eq_zero_of_injective x)

variable (F : Sheaf J AddCommGrpCat.{w}) {T : C} (hT : Limits.IsTerminal T)

open AddCommGrpCat Opposite

/-- The additive equivalence between `H F 0` and the evaluation of `F` at a terminal object -/
/-
**CategoryTheory.Sheaf.H.equiv** 是 Mathlib 中的一个定义，位于命名空间 `CategoryTheory.Sheaf`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The additive equivalence between `H F 0` and the evaluation of `F` at a terminal
 object
-/
noncomputable def H.equiv₀ : H F 0 ≃+ F.obj.obj (op T) :=
  AddEquiv.trans Ext.addEquiv₀ <|
    AddEquiv.trans ((constantSheafAdj J AddCommGrpCat hT).homAddEquiv _ F)
      (uliftZMultiplesAddEquiv _)

variable {F G : Sheaf J AddCommGrpCat.{w}} (f : F ⟶ G)

/-- Given a morphism of sheaves `f : F ⟶ G`, `H.map f n` is the induced additive map on cohomology
groups `H F n →+ H G n` -/
/-
**CategoryTheory.Sheaf.H.map** 是 Mathlib 中的一个定义，位于命名空间 `CategoryTheory.Sheaf.H`。
形式化陈述：{C : Type u} →   [inst : CategoryTheory.Category.{v, u} C] →     {J : Cate
goryTheory.GrothendieckTopology C} →       [inst_1 : CategoryTheory.HasSheafify 
J AddCommGrpCat] →         [inst_2 : CategoryTheory.HasExt (CategoryTheory.Sheaf
 J AddCommGrpCat)] →           {F G : CategoryTheory.Sheaf J AddCommGrpCat} → (F
 ⟶ G) → (n : ℕ) → F.H n →+ G.H n
参数：CategoryTheory.Sheaf J AddCommGrpCat；F ⟶ G；n : ℕ。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `CategoryTheory.instHasWeakSheafifyOfHasSheafify`：∀ {C : Type u₁} [inst :
 CategoryTheory.Category.{v₁, u₁} C] (J : CategoryTheory.GrothendieckTopology C)
 (A : Type u₂)   [inst_1 : CategoryTh…

--- 原说明 ---
Given a morphism of sheaves `f : F ⟶ G`, `H.map f n` is the induced additive map
 on cohomology
groups `H F n →+ H G n`
-/
noncomputable def H.map (n : ℕ) : H F n →+ H G n :=
  (Ext.mk₀ f).postcomp ((constantSheaf J AddCommGrpCat).obj (of (ULift ℤ))) (add_zero n)

@[reassoc]
/-
**CategoryTheory.Sheaf.H.addEquiv** 是 Mathlib 中的一个引理，位于命名空间 `CategoryTheory.Shea
f`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma H.addEquiv₀_map (x : H F 0) : Ext.addEquiv₀ (H.map f 0 x) = Ext.addEquiv₀ x ≫ f := by
  delta Ext.addEquiv₀
  apply (Ext.mk₀_bijective _ G).injective
  simp only [AddEquiv.coe_mk, Ext.mk₀_homEquiv₀_apply, Ext.mk₀_homEquiv₀_apply, ← Ext.mk₀_comp_mk₀]
  rfl

/-- `H.equiv₀` is natural -/
/-
**CategoryTheory.Sheaf.H.equiv** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory.Sheaf`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
`H.equiv₀` is natural
-/
theorem H.equiv₀_naturality (x : H F 0) :
    f.hom.app (op T) (H.equiv₀ F hT x) = H.equiv₀ G hT (H.map f 0 x) := by
  simp only [equiv₀, AddEquiv.trans_apply, addEquiv₀_map f x]
  rfl
/-
**CategoryTheory.Sheaf.H.equiv** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory.Sheaf`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem H.equiv₀_symm_naturality (x : F.obj.obj (op T)) :
    H.map f 0 ((H.equiv₀ F hT).symm x) = (H.equiv₀ G hT).symm (f.hom.app (op T) x) := by
  apply (H.equiv₀ G hT).injective
  simp [← H.equiv₀_naturality]
/-
**CategoryTheory.Sheaf.H.map_apply** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory.She
af.H`。
形式化陈述：∀ {C : Type u} [inst : CategoryTheory.Category.{v, u} C] {J : CategoryTheo
ry.GrothendieckTopology C}   [inst_1 : CategoryTheory.HasSheafify J AddCommGrpCa
t]   [inst_2 : CategoryTheory.HasExt (CategoryTheory.Sheaf J AddCommGrpCat)] {F 
G : CategoryTheory.Sheaf J AddCommGrpCat}   (f : F ⟶ G) {n : ℕ} (x : F.H n),   (
CategoryTheory.Sheaf.H.map f n) x = CategoryTheory.Abelian.Ext.comp x (CategoryT
heory.Abelian.Ext.mk₀ f) ⋯
参数：CategoryTheory.Sheaf J AddCommGrpCat；f : F ⟶ G；x : F.H n；CategoryTheory.Sheaf
.H.map f n；CategoryTheory.Abelian.Ext.mk₀ f。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `CategoryTheory.instHasWeakSheafifyOfHasSheafify`：∀ {C : Type u₁} [inst :
 CategoryTheory.Category.{v₁, u₁} C] (J : CategoryTheory.GrothendieckTopology C)
 (A : Type u₂)   [inst_1 : CategoryTh…
-/
lemma H.map_apply {n : ℕ} (x : H F n) :
    H.map f n x = x.comp (Ext.mk₀ f) (add_zero n) := rfl

@[simp]
/-
**CategoryTheory.Sheaf.H.map_id_apply** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory.
Sheaf.H`。
形式化陈述：∀ {C : Type u} [inst : CategoryTheory.Category.{v, u} C] {J : CategoryTheo
ry.GrothendieckTopology C}   [inst_1 : CategoryTheory.HasSheafify J AddCommGrpCa
t]   [inst_2 : CategoryTheory.HasExt (CategoryTheory.Sheaf J AddCommGrpCat)] {F 
: CategoryTheory.Sheaf J AddCommGrpCat}   {n : ℕ} (x : F.H n), (CategoryTheory.S
heaf.H.map (CategoryTheory.CategoryStruct.id F) n) x = x
参数：CategoryTheory.Sheaf J AddCommGrpCat；x : F.H n；CategoryTheory.Sheaf.H.map (Ca
tegoryTheory.CategoryStruct.id F) n。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `CategoryTheory.instHasWeakSheafifyOfHasSheafify`：∀ {C : Type u₁} [inst :
 CategoryTheory.Category.{v₁, u₁} C] (J : CategoryTheory.GrothendieckTopology C)
 (A : Type u₂)   [inst_1 : CategoryTh…
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用引理 `CategoryTheory.Abelian.Ext.comp_mk₀_id`：comp_mk₀_id (α : Ext X Y n) : α.
comp (mk₀ (𝟙 Y)) (add_zero n) = α
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma H.map_id_apply {n : ℕ} (x : H F n) : H.map (𝟙 F) n x = x := by
  simp [H.map_apply]
/-
**CategoryTheory.Sheaf.H.map_comp_apply** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheor
y.Sheaf.H`。
形式化陈述：∀ {C : Type u} [inst : CategoryTheory.Category.{v, u} C] {J : CategoryTheo
ry.GrothendieckTopology C}   [inst_1 : CategoryTheory.HasSheafify J AddCommGrpCa
t]   [inst_2 : CategoryTheory.HasExt (CategoryTheory.Sheaf J AddCommGrpCat)] {F 
G : CategoryTheory.Sheaf J AddCommGrpCat}   (f : F ⟶ G) {n : ℕ} {G' : CategoryTh
eory.Sheaf J AddCommGrpCat} (g : G ⟶ G') (x : F.H n),   (CategoryTheory.Sheaf.H.
map (CategoryTheory.CategoryStruct.comp f g) n) x =     (CategoryTheory.Sheaf.H.
map g n) ((CategoryTheory.Sheaf.H.map f n) x)
参数：CategoryTheory.Sheaf J AddCommGrpCat；f : F ⟶ G；g : G ⟶ G'；x : F.H n；CategoryT
heory.Sheaf.H.map (CategoryTheory.CategoryStruct.comp f g) n；CategoryTheory.Shea
f.H.map g n；(CategoryTheory.Sheaf.H.map f n) x。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `CategoryTheory.instHasWeakSheafifyOfHasSheafify`：∀ {C : Type u₁} [inst :
 CategoryTheory.Category.{v₁, u₁} C] (J : CategoryTheory.GrothendieckTopology C)
 (A : Type u₂)   [inst_1 : CategoryTh…
· 使用定理 `add_zero`：∀ {M : Type u} [inst : AddZeroClass M] (a : M), a + 0 = a
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `zero_add`：∀ {M : Type u} [inst : AddZeroClass M] (a : M), 0 + a = a
· 使用引理 `CategoryTheory.Abelian.Ext.comp_assoc_of_second_deg_zero`：comp_assoc_of_
second_deg_zero {a₁ a₃ a₁₃ : Nat} (α : Ext X Y a₁) (β : Ext Y Z 0) (γ : Ext Z T 
a₃) (h₁₃ : a₁ + a₃ = a₁₃) : (α.comp β (add_zer…
· 使用定理 `CategoryTheory.Abelian.Ext.comp.congr_simp`：∀ {C : Type u} [inst : Categ
oryTheory.Category.{v, u} C] [inst_1 : CategoryTheory.Abelian C]   [inst_2 : Cat
egoryTheory.HasExt C] {X Y Z : C…
· 使用引理 `CategoryTheory.Abelian.Ext.mk₀_comp_mk₀`：mk₀_comp_mk₀ (f : X ⟶ Y) (g : Y
 ⟶ Z) : (mk₀ f).comp (mk₀ g) (zero_add 0) = mk₀ (f ≫ g)
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma H.map_comp_apply {n : ℕ} {G' : Sheaf J AddCommGrpCat.{w}} (g : G ⟶ G') (x : H F n) :
    H.map (f ≫ g) n x = H.map g n (H.map f n x) := by
  simp [H.map_apply]

@[simp]
/-
**CategoryTheory.Sheaf.H.map_add_apply** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory
.Sheaf.H`。
形式化陈述：∀ {C : Type u} [inst : CategoryTheory.Category.{v, u} C] {J : CategoryTheo
ry.GrothendieckTopology C}   [inst_1 : CategoryTheory.HasSheafify J AddCommGrpCa
t]   [inst_2 : CategoryTheory.HasExt (CategoryTheory.Sheaf J AddCommGrpCat)] {F 
G : CategoryTheory.Sheaf J AddCommGrpCat}   {n : ℕ} (f g : F ⟶ G) (x : F.H n),  
 (CategoryTheory.Sheaf.H.map (f + g) n) x = (CategoryTheory.Sheaf.H.map f n) x +
 (CategoryTheory.Sheaf.H.map g n) x
参数：CategoryTheory.Sheaf J AddCommGrpCat；f g : F ⟶ G；x : F.H n；CategoryTheory.She
af.H.map (f + g) n；CategoryTheory.Sheaf.H.map f n；CategoryTheory.Sheaf.H.map g n
。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `CategoryTheory.instHasWeakSheafifyOfHasSheafify`：∀ {C : Type u₁} [inst :
 CategoryTheory.Category.{v₁, u₁} C] (J : CategoryTheory.GrothendieckTopology C)
 (A : Type u₂)   [inst_1 : CategoryTh…
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `CategoryTheory.Abelian.Ext.postcomp.congr_simp`：∀ {C : Type u} [inst : C
ategoryTheory.Category.{v, u} C] [inst_1 : CategoryTheory.Abelian C]   [inst_2 :
 CategoryTheory.HasExt C] {Y Z : C} …
· 使用引理 `CategoryTheory.Abelian.Ext.mk₀_add`：mk₀_add (f g : X ⟶ Y) : mk₀ (f + g) 
= mk₀ f + mk₀ g
· 使用定理 `map_add`：∀ {M : Type u_4} {N : Type u_5} {F : Type u_9} [inst : Add M] [
inst_1 : Add N] [inst_2 : FunLike F M N]   [AddHomClass F M N] (f : F) (x y :…
· 使用定理 `AddMonoidHomClass.toAddHomClass`：∀ {F : Type u_10} {M : outParam (Type u
_11)} {N : outParam (Type u_12)} {inst : AddZero M} {inst_1 : AddZero N}   {inst
_2 : FunLike F M N} […
· 使用定理 `AddMonoidHom.instAddMonoidHomClass`：∀ {M : Type u_4} {N : Type u_5} [ins
t : AddZero M] [inst_1 : AddZero N], AddMonoidHomClass (M →+ N) M N
· 使用定理 `CategoryTheory.Abelian.Ext.bilinearComp_apply_apply`：∀ {C : Type u} [ins
t : CategoryTheory.Category.{v, u} C] [inst_1 : CategoryTheory.Abelian C]   [ins
t_2 : CategoryTheory.HasExt C] (X Y Z : C…
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma H.map_add_apply {n : ℕ} (f g : F ⟶ G) (x : H F n) :
    H.map (f + g) n x = H.map f n x + H.map g n x := by
  simp [map, Ext.mk₀_add]

attribute [local simp] H.map_comp_apply in
variable (J) in
/-- `H` as a functor. -/
@[simps]
/-
**CategoryTheory.Sheaf.functorH** 是 Mathlib 中的一个定义，位于命名空间 `CategoryTheory.Sheaf`
。
形式化陈述：functorH (n : Nat) : Sheaf J AddCommGrpCat.{w} ⥤ AddCommGrpCat.{w'} where 
obj F
参数：n : Nat。
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `CategoryTheory.instHasWeakSheafifyOfHasSheafify`：∀ {C : Type u₁} [inst :
 CategoryTheory.Category.{v₁, u₁} C] (J : CategoryTheory.GrothendieckTopology C)
 (A : Type u₂)   [inst_1 : CategoryTh…

--- 原说明 ---
`H` as a functor.
-/
noncomputable def functorH (n : ℕ) : Sheaf J AddCommGrpCat.{w} ⥤ AddCommGrpCat.{w'} where
  obj F := .of (H F n)
  map f := AddCommGrpCat.ofHom (H.map f n)
/-
**CategoryTheory.Sheaf.** 是 Mathlib 中的一个实例，位于命名空间 `CategoryTheory.Sheaf`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance (n : ℕ) : (functorH J n).Additive where
/-
**CategoryTheory.Sheaf.subsingleton_H_of_isZero** 是 Mathlib 中的一个引理，位于命名空间 `Categ
oryTheory.Sheaf`。
形式化陈述：subsingleton_H_of_isZero {F : Sheaf J AddCommGrpCat.{w}} (h : Limits.IsZer
o F) (n : Nat) : Subsingleton (F.H n)
参数：h : Limits.IsZero F；n : Nat。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `CategoryTheory.Sheaf.functorH_obj_coe`：∀ {C : Type u} [inst : CategoryTh
eory.Category.{v, u} C] (J : CategoryTheory.GrothendieckTopology C)   [inst_1 : 
CategoryTheory.HasSheafify …
· 使用定理 `AddCommGrpCat.subsingleton_of_isZero`：∀ {G : AddCommGrpCat}, CategoryThe
ory.Limits.IsZero G → Subsingleton ↑G
· 使用引理 `CategoryTheory.Functor.map_isZero`：map_isZero (F : C ⥤ D) [PreservesZero
Morphisms F] {X : C} (hX : IsZero X) : IsZero (F.obj X)
· 使用定理 `CategoryTheory.Functor.preservesZeroMorphisms_of_additive`：∀ {C : Type u
_1} {D : Type u_2} [inst : CategoryTheory.Category.{v_1, u_1} C]   [inst_1 : Cat
egoryTheory.Category.{v_2, u_2} D] [inst_2 : Ca…
· 使用定理 `CategoryTheory.Sheaf.instAdditiveAddCommGrpCatFunctorH`：∀ {C : Type u} [
inst : CategoryTheory.Category.{v, u} C] {J : CategoryTheory.GrothendieckTopolog
y C}   [inst_1 : CategoryTheory.HasSheafify …
-/
lemma subsingleton_H_of_isZero {F : Sheaf J AddCommGrpCat.{w}} (h : Limits.IsZero F) (n : ℕ) :
    Subsingleton (F.H n) := by
  rw [← functorH_obj_coe]
  apply AddCommGrpCat.subsingleton_of_isZero
  exact Functor.map_isZero (functorH J n) h

@[deprecated (since := "2026-05-05")] noncomputable alias cohomologyFunctor := functorH

end

end Sheaf

end CategoryTheory

