/-
Copyright (c) 2022 Anne Baanen. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anne Baanen
-/
module

public import Mathlib.LinearAlgebra.FreeModule.Finite.Quotient

/-! # Ideals in free modules over PIDs

## Main results

- `Ideal.quotientEquivPiSpan`: `S ⧸ I`, if `S` is finite free as a module over a PID `R`,
  can be written as a product of quotients of `R` by principal ideals.

-/

@[expose] public section

open Module
open scoped DirectSum

namespace Ideal


variable {ι R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
variable [IsDomain R] [IsPrincipalIdealRing R] [IsDomain S] [Finite ι]

/-- We can write the quotient of an ideal over a PID as a product of quotients by principal ideals.
-/
/-
**Ideal.quotientEquivPiSpan** 是 Mathlib 中的一个定义，位于命名空间 `Ideal`。
形式化陈述：quotientEquivPiSpan (I : Ideal S) (b : Basis ι R S) (hI : I != ⊥) : (S ⧸ I
) ≃ₗ[R] forall i, R ⧸ span ({I.smithCoeffs b hI i} : Set R)
参数：I : Ideal S；b : Basis ι R S；hI : I != ⊥。
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `Ideal.finrank_eq_finrank`：Ideal.finrank_eq_finrank [Finite ι] (b : Basis
 ι R S) (I : Ideal S) (hI : I != ⊥) : Module.finrank R (restrictScalars R I) = M
odule.finrank …

--- 原说明 ---
We can write the quotient of an ideal over a PID as a product of quotients by pr
incipal ideals.
-/
noncomputable def quotientEquivPiSpan (I : Ideal S) (b : Basis ι R S) (hI : I ≠ ⊥) :
    (S ⧸ I) ≃ₗ[R] ∀ i, R ⧸ span ({I.smithCoeffs b hI i} : Set R) :=
  Submodule.quotientEquivPiSpan (I.restrictScalars R) b <| finrank_eq_finrank b I hI

/-- Ideal quotients over a free finite extension of `ℤ` are isomorphic to a direct product of
`ZMod`. -/
/-
**Ideal.quotientEquivPiZMod** 是 Mathlib 中的一个定义，位于命名空间 `Ideal`。
形式化陈述：quotientEquivPiZMod (I : Ideal S) (b : Basis ι Int S) (hI : I != ⊥) : S ⧸ 
I ≃+ forall i, ZMod (I.smithCoeffs b hI i).natAbs
参数：I : Ideal S；b : Basis ι Int S；hI : I != ⊥。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Ideal quotients over a free finite extension of `ℤ` are isomorphic to a direct p
roduct of
`ZMod`.
-/
noncomputable def quotientEquivPiZMod (I : Ideal S) (b : Basis ι ℤ S) (hI : I ≠ ⊥) :
    S ⧸ I ≃+ ∀ i, ZMod (I.smithCoeffs b hI i).natAbs :=
  Submodule.quotientEquivPiZMod (I.restrictScalars ℤ) b <| finrank_eq_finrank b I hI

/--
A nonzero ideal over a free finite extension of `ℤ` has a finite quotient.
It can't be an instance because of the side condition `I ≠ ⊥`.
-/
/-
**Ideal.finiteQuotientOfFreeOfNeBot** 是 Mathlib 中的一个定理，位于命名空间 `Ideal`。
形式化陈述：finiteQuotientOfFreeOfNeBot [Module.Free Int S] [Module.Finite Int S] (I :
 Ideal S) (hI : I != ⊥) : Finite (S ⧸ I)
参数：I : Ideal S；hI : I != ⊥。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Submodule.finiteQuotientOfFreeOfRankEq`：finiteQuotientOfFreeOfRankEq [Mo
dule.Free Int M] [Module.Finite Int M] (N : Submodule Int M) (h : Module.finrank
 Int N = Module.finrank Int …
· 使用定理 `IsScalarTower.right`：∀ {R : Type u} {A : Type w} [inst : CommSemiring R]
 [inst_1 : Semiring A] [inst_2 : Algebra R A], IsScalarTower R A A
· 使用定理 `Ideal.finrank_eq_finrank`：Ideal.finrank_eq_finrank [Finite ι] (b : Basis
 ι R S) (I : Ideal S) (hI : I != ⊥) : Module.finrank R (restrictScalars R I) = M
odule.finrank …
· 使用定理 `Int.instIsDomain`：IsDomain ℤ
· 使用定理 `EuclideanDomain.to_principal_ideal_domain`：∀ {R : Type u} [inst : Euclid
eanDomain R], IsPrincipalIdealRing R
· 使用定理 `Finite.of_fintype`：∀ (α : Type u_4) [Fintype α], Finite α

--- 原说明 ---
A nonzero ideal over a free finite extension of `ℤ` has a finite quotient.
It can't be an instance because of the side condition `I ≠ ⊥`.
-/
theorem finiteQuotientOfFreeOfNeBot [Module.Free ℤ S] [Module.Finite ℤ S]
    (I : Ideal S) (hI : I ≠ ⊥) : Finite (S ⧸ I) :=
  let b := Module.Free.chooseBasis ℤ S
  Submodule.finiteQuotientOfFreeOfRankEq (I.restrictScalars ℤ) <| finrank_eq_finrank b I hI

variable (F : Type*) [CommRing F] [Algebra F R] [Algebra F S] [IsScalarTower F R S]
  (b : Basis ι R S) {I : Ideal S} (hI : I ≠ ⊥)

/-- Decompose `S⧸I` as a direct sum of cyclic `R`-modules
  (quotients by the ideals generated by Smith coefficients of `I`). -/
/-
**Ideal.quotientEquivDirectSum** 是 Mathlib 中的一个定义，位于命名空间 `Ideal`。
形式化陈述：quotientEquivDirectSum : (S ⧸ I) ≃ₗ[F] ⨁ i, R ⧸ span ({I.smithCoeffs b hI 
i} : Set R)
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `Ideal.finrank_eq_finrank`：Ideal.finrank_eq_finrank [Finite ι] (b : Basis
 ι R S) (I : Ideal S) (hI : I != ⊥) : Module.finrank R (restrictScalars R I) = M
odule.finrank …

--- 原说明 ---
Decompose `S⧸I` as a direct sum of cyclic `R`-modules
  (quotients by the ideals generated by Smith coefficients of `I`).
-/
noncomputable def quotientEquivDirectSum :
    (S ⧸ I) ≃ₗ[F] ⨁ i, R ⧸ span ({I.smithCoeffs b hI i} : Set R) :=
  Submodule.quotientEquivDirectSum F b (N := (I.restrictScalars R)) <| finrank_eq_finrank b I hI
/-
**Ideal.finrank_quotient_eq_sum** 是 Mathlib 中的一个定理，位于命名空间 `Ideal`。
形式化陈述：finrank_quotient_eq_sum {ι} [Fintype ι] (b : Basis ι R S) [Nontrivial F] [
forall i, Module.Free F (R ⧸ span ({I.smithCoeffs b hI i} : Set R))] [forall i, 
Module.Finite F (R ⧸ span ({I.smithCoeffs b hI i} : Set R))] : Module.finrank F 
(S ⧸ I) = ∑ i, Module.finrank F (R ⧸ span ({I.smithCoeffs b hI i} : Set R))
参数：b : Basis ι R S；R ⧸ span ({I.smithCoeffs b hI i} : Set R)；R ⧸ span ({I.smithC
oeffs b hI i} : Set R)。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Finite.of_fintype`：∀ (α : Type u_4) [Fintype α], Finite α
· 使用定理 `IsScalarTower.right`：∀ {R : Type u} {A : Type w} [inst : CommSemiring R]
 [inst_1 : Semiring A] [inst_2 : Algebra R A], IsScalarTower R A A
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `LinearEquiv.finrank_eq`：finrank_eq (f : M ≃ₗ[R] N) : finrank R M = finra
nk R N
· 使用定理 `Module.finrank_directSum`：finrank_directSum {ι : Type v} [Fintype ι] (M 
: ι -> Type w) [forall i : ι, AddCommMonoid (M i)] [forall i : ι, Module R (M i)
] [forall i : …
· 使用定理 `commRing_strongRankCondition`：∀ (R : Type u_1) [inst : CommRing R] [Nont
rivial R], StrongRankCondition R
-/
theorem finrank_quotient_eq_sum {ι} [Fintype ι] (b : Basis ι R S) [Nontrivial F]
    [∀ i, Module.Free F (R ⧸ span ({I.smithCoeffs b hI i} : Set R))]
    [∀ i, Module.Finite F (R ⧸ span ({I.smithCoeffs b hI i} : Set R))] :
    Module.finrank F (S ⧸ I) =
      ∑ i, Module.finrank F (R ⧸ span ({I.smithCoeffs b hI i} : Set R)) := by
  -- slow, and dot notation doesn't work
  rw [LinearEquiv.finrank_eq <| quotientEquivDirectSum F b hI, Module.finrank_directSum]

end Ideal

