/-
Copyright (c) 2017 Johannes Hölzl. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Johannes Hölzl, Mario Carneiro, Kevin Buzzard, Yury Kudryashov, Frédéric Dupuis,
  Heather Macbeth
-/
module

public import Mathlib.Algebra.Module.Submodule.Lattice
public import Mathlib.Algebra.Group.Pointwise.Set.Basic

/-!
# The span of a set of vectors, as a submodule

* `Submodule.span s` is defined to be the smallest submodule containing the set `s`.

## Notation

* We introduce the notation `R ∙ v` for the span of a singleton, `Submodule.span R {v}`. This is
  `\span`, not the same as the scalar multiplication `•`/`\bub`.

-/

@[expose] public section

assert_not_exists Field

variable {R R₂ K M M₂ V S : Type*}

namespace Submodule

open Function Set

open scoped Pointwise

section AddCommMonoid

variable [Semiring R] [AddCommMonoid M] [Module R M]
variable {x : M} (p p' : Submodule R M)
variable [Semiring R₂] {σ₁₂ : R ->+* R₂}
variable [AddCommMonoid M₂] [Module R₂ M₂]
variable {F : Type*} [FunLike F M M₂] [SemilinearMapClass F σ₁₂ M M₂]

section

variable (R) in
/--
Definition of `span` / `span` 的定义

English:
definition span
  signature: (s : Set M)
  body: sInf { p | s subseteq p }

中文:
定义 span
  签名: (s : 集合 M)
  定义体: sInf { p | s subseteq p }

Depends on / 依赖: subseteq
-/
def span (s : Set M) : Submodule R M :=
  sInf { p | s subseteq p }

/-- An `R`-submodule of `M` is principal if it is generated by one element. -/
@[mk_iff, wikidata Q44382]
/--
Definition of `IsPrincipal` / `IsPrincipal` 的定义

English:
class IsPrincipal
  parameters: (S : Submodule R M)
  axioms and operations (1):
    - principal((S)) : exists a, S = span R {a}

中文:
类 是Principal
  参数: (S : 子模 R M)
  公理与运算 (1 个):
    - principal((S)) : 存在 a, S = span R {a}
-/
class IsPrincipal (S : Submodule R M) : Prop where
  principal (S) : exists a, S = span R {a}

instance (x : R) : (span R {x}).IsPrincipal := ⟨x, rfl⟩

namespace IsPrincipal

/--
Definition of `generator` / `generator` 的定义

English:
definition generator
  signature: (S : Submodule R M) [S.IsPrincipal]
  body: Classical.choose (principal S)

中文:
定义 generator
  签名: (S : 子模 R M) [S.是Principal]
  定义体: Classical.choose (principal S)

Depends on / 依赖: Classical, Classical.choose, principal
-/
noncomputable def generator (S : Submodule R M) [S.IsPrincipal] : M :=
  Classical.choose (principal S)

/--
theorem `span_singleton_generator` / 定理 `span_singleton_generator`

English:
theorem span_singleton_generator
  given: (S : Submodule R M) [S.IsPrincipal]
  statement: span R {generator S} = S
  proof: (Classical.choose_spec (principal S)).symm

中文:
定理 span_singleton_generator
  条件: (S : 子模 R M) [S.是Principal]
  结论: span R {generator S} = S
  证明: (Classical.choose_spec (principal S)).symm

Depends on / 依赖: Classical, Classical.choose_spec, choose_spec, principal
-/
theorem span_singleton_generator (S : Submodule R M) [S.IsPrincipal] : span R {generator S} = S :=
  (Classical.choose_spec (principal S)).symm

end IsPrincipal

end

variable {s t : Set M}

/--
theorem `mem_span` / 定理 `mem_span`

English:
theorem mem_span
  statement: x in span R s ↔ forall p : Submodule R M, s subseteq p -> x in p
  proof: mem_iInter₂

@[simp, aesop safe 20 (rule_sets := [SetLike])]

中文:
定理 mem_span
  结论: x in span R s ↔ 对任意 p : 子模 R M, s subseteq p -> x in p
  证明: mem_iInter₂

@[simp, aesop safe 20 (rule_sets := [SetLike])]
-/
theorem mem_span : x in span R s ↔ forall p : Submodule R M, s subseteq p -> x in p :=
  mem_iInter₂

@[simp, aesop safe 20 (rule_sets := [SetLike])]
/--
theorem `subset_span` / 定理 `subset_span`

English:
theorem subset_span
  statement: s subseteq span R s
  proof: fun _ h => mem_span.2 fun _ hp => hp h

@[aesop 80% (rule_sets := [SetLike])]

中文:
定理 subset_span
  结论: s subseteq span R s
  证明: fun _ h => mem_span.2 fun _ hp => hp h

@[aesop 80% (rule_sets := [SetLike])]

Depends on / 依赖: mem_span
-/
theorem subset_span : s subseteq span R s := fun _ h => mem_span.2 fun _ hp => hp h

@[aesop 80% (rule_sets := [SetLike])]
/--
theorem `mem_span_of_mem` / 定理 `mem_span_of_mem`

English:
theorem mem_span_of_mem
  given: {s : Set M} {x : M} (hx : x in s)
  statement: x in span R s
  proof: subset_span hx

中文:
定理 mem_span_of_mem
  条件: {s : 集合 M} {x : M} (hx : x in s)
  结论: x in span R s
  证明: subset_span hx

Depends on / 依赖: subset_span
-/
theorem mem_span_of_mem {s : Set M} {x : M} (hx : x in s) : x in span R s := subset_span hx

/--
theorem `span_le` / 定理 `span_le`

English:
theorem span_le
  given: {p}
  statement: span R s <= p ↔ s subseteq p
  proof: ⟨Subset.trans subset_span, fun ss _ h => mem_span.1 h _ ss⟩

中文:
定理 span_le
  条件: {p}
  结论: span R s <= p ↔ s subseteq p
  证明: ⟨Subset.trans subset_span, fun ss _ h => mem_span.1 h _ ss⟩

Depends on / 依赖: Subset, Subset.trans, mem_span, subset_span
-/
theorem span_le {p} : span R s <= p ↔ s subseteq p :=
  ⟨Subset.trans subset_span, fun ss _ h => mem_span.1 h _ ss⟩

/--
theorem `span_mono` / 定理 `span_mono`

English:
theorem span_mono
  given: (h : s subseteq t)
  statement: span R s <= span R t
  proof: span_le.2 Subset.trans h subset_span

中文:
定理 span_mono
  条件: (h : s subseteq t)
  结论: span R s <= span R t
  证明: span_le.2 Subset.trans h subset_span
-/
@[gcongr] theorem span_mono (h : s subseteq t) : span R s <= span R t :=
span_le.2 Subset.trans h subset_span

/--
theorem `span_monotone` / 定理 `span_monotone`

English:
theorem span_monotone
  statement: Monotone (span R : Set M -> Submodule R M)
  proof: fun _ _ => span_mono

中文:
定理 span_monotone
  结论: 递增 (span R : 集合 M -> 子模 R M)
  证明: fun _ _ => span_mono

Depends on / 依赖: span_mono
-/
theorem span_monotone : Monotone (span R : Set M -> Submodule R M) := fun _ _ => span_mono

/--
theorem `span_eq_of_le` / 定理 `span_eq_of_le`

English:
theorem span_eq_of_le
  given: (h₁ : s subseteq p) (h₂ : p <= span R s)
  statement: span R s = p
  proof: le_antisymm (span_le.2 h₁) h₂

中文:
定理 span_eq_of_le
  条件: (h₁ : s subseteq p) (h₂ : p <= span R s)
  结论: span R s = p
  证明: le_antisymm (span_le.2 h₁) h₂

Depends on / 依赖: le_antisymm, span_le
-/
theorem span_eq_of_le (h₁ : s subseteq p) (h₂ : p <= span R s) : span R s = p :=
  le_antisymm (span_le.2 h₁) h₂

/--
theorem `span_eq` / 定理 `span_eq`

English:
theorem span_eq
  statement: span R (p : Set M) = p
  proof: span_eq_of_le _ (Subset.refl _) subset_span

中文:
定理 span_eq
  结论: span R (p : 集合 M) = p
  证明: span_eq_of_le _ (Subset.refl _) subset_span

Depends on / 依赖: Subset, Subset.refl, span_eq_of_le, subset_span
-/
theorem span_eq : span R (p : Set M) = p :=
  span_eq_of_le _ (Subset.refl _) subset_span

/--
theorem `span_eq_span` / 定理 `span_eq_span`

English:
theorem span_eq_span
  given: (hs : s subseteq span R t) (ht : t subseteq span R s)
  statement: span R s = span R t
  proof: le_antisymm (span_le.2 hs) (span_le.2 ht)

中文:
定理 span_eq_span
  条件: (hs : s subseteq span R t) (ht : t subseteq span R s)
  结论: span R s = span R t
  证明: le_antisymm (span_le.2 hs) (span_le.2 ht)

Depends on / 依赖: le_antisymm, span_le
-/
theorem span_eq_span (hs : s subseteq span R t) (ht : t subseteq span R s) : span R s = span R t :=
  le_antisymm (span_le.2 hs) (span_le.2 ht)

/--
lemma `coe_span_eq_self` / 引理 `coe_span_eq_self`

English:
lemma coe_span_eq_self
  given: [SetLike S M] [AddSubmonoidClass S M] [SMulMemClass S R M] (s : S)
  proof: by
  refine le_antisymm ?_ subset_span
  let s' : Submodule R M :=
    { carrier := s
      add_mem' := add_mem
      zero_mem' := zero_mem _
      smul_mem' := SMulMemClass.smul_mem }
.mpr le_rfl exact span_le (p := s')

@[simp]

中文:
引理 coe_span_eq_self
  条件: [集合状 S M] [加法子幺半群类 S M] [SMulMem类 S R M] (s : S)
  证明: by
  refine le_antisymm ?_ subset_span
  let s' : Submodule R M :=
    { carrier := s
      add_mem' := add_mem
      zero_mem' := zero_mem _
      smul_mem' := SMulMemClass.smul_mem }
.mpr le_rfl exact span_le (p := s')

@[simp]

Depends on / 依赖: SMulMemClass, SMulMemClass.smul_mem, Submodule, add_mem, carrier, le_antisymm, le_rfl, smul_mem, span_le, subset_span, zero_mem
-/
lemma coe_span_eq_self [SetLike S M] [AddSubmonoidClass S M] [SMulMemClass S R M] (s : S) :
    (span R (s : Set M) : Set M) = s := by
  refine le_antisymm ?_ subset_span
  let s' : Submodule R M :=
    { carrier := s
      add_mem' := add_mem
      zero_mem' := zero_mem _
      smul_mem' := SMulMemClass.smul_mem }
.mpr le_rfl exact span_le (p := s')

@[simp]
/--
theorem `span_insert_zero` / 定理 `span_insert_zero`

English:
theorem span_insert_zero
  statement: span R (insert (0 : M) s) = span R s
  proof: by
  refine le_antisymm ?_ (Submodule.span_mono (Set.subset_insert 0 s))
  rw [span_le]; rw [Set.insert_subset_iff]
  exact ⟨by simp only [SetLike.mem_coe, Submodule.zero_mem], Submodule.subset_span⟩

@[simp]

中文:
定理 span_insert_zero
  结论: span R (insert (0 : M) s) = span R s
  证明: by
  refine le_antisymm ?_ (Submodule.span_mono (Set.subset_insert 0 s))
  rw [span_le]; rw [Set.insert_subset_iff]
  exact ⟨by simp only [SetLike.mem_coe, Submodule.zero_mem], Submodule.subset_span⟩

@[simp]

Depends on / 依赖: Set.insert_subset_iff, Set.subset_insert, SetLike, SetLike.mem_coe, Submodule, Submodule.span_mono, Submodule.subset_span, Submodule.zero_mem, insert_subset_iff, le_antisymm, mem_coe, span_le, span_mono, subset_insert, subset_span, zero_mem
-/
theorem span_insert_zero : span R (insert (0 : M) s) = span R s := by
  refine le_antisymm ?_ (Submodule.span_mono (Set.subset_insert 0 s))
  rw [span_le]; rw [Set.insert_subset_iff]
  exact ⟨by simp only [SetLike.mem_coe, Submodule.zero_mem], Submodule.subset_span⟩

@[simp]
/--
lemma `span_sdiff_singleton_zero` / 引理 `span_sdiff_singleton_zero`

English:
lemma span_sdiff_singleton_zero
  statement: span R (s \ {0}) = span R s
  proof: by
  by_cases h : 0 in s
  · rw [← span_insert_zero, show insert 0 (s \ {0}) = s by simp [h]]
  · simp [h]

中文:
引理 span_sdiff_singleton_zero
  结论: span R (s \ {0}) = span R s
  证明: by
  by_cases h : 0 in s
  · rw [← span_insert_zero, show insert 0 (s \ {0}) = s by simp [h]]
  · simp [h]

Depends on / 依赖: insert, span_insert_zero
-/
lemma span_sdiff_singleton_zero : span R (s \ {0}) = span R s := by
  by_cases h : 0 in s
  · rw [← span_insert_zero, show insert 0 (s \ {0}) = s by simp [h]]
  · simp [h]

/--
theorem `closure_subset_span` / 定理 `closure_subset_span`

English:
theorem closure_subset_span
  given: {s : Set M}
  statement: (AddSubmonoid.closure s : Set M) subseteq span R s
  proof: (@AddSubmonoid.closure_le _ _ _ (span R s).toAddSubmonoid).mpr subset_span

中文:
定理 closure_subset_span
  条件: {s : 集合 M}
  结论: (加法子幺半群.closure s : 集合 M) subseteq span R s
  证明: (@AddSubmonoid.closure_le _ _ _ (span R s).toAddSubmonoid).mpr subset_span

Depends on / 依赖: AddSubmonoid, AddSubmonoid.closure_le, closure_le, subset_span, toAddSubmonoid
-/
theorem closure_subset_span {s : Set M} : (AddSubmonoid.closure s : Set M) subseteq span R s :=
  (@AddSubmonoid.closure_le _ _ _ (span R s).toAddSubmonoid).mpr subset_span

/--
theorem `closure_le_toAddSubmonoid_span` / 定理 `closure_le_toAddSubmonoid_span`

English:
theorem closure_le_toAddSubmonoid_span
  given: {s : Set M}
  proof: closure_subset_span

@[simp]

中文:
定理 closure_le_toAddSubmonoid_span
  条件: {s : 集合 M}
  证明: closure_subset_span

@[simp]

Depends on / 依赖: closure_subset_span
-/
theorem closure_le_toAddSubmonoid_span {s : Set M} :
    AddSubmonoid.closure s <= (span R s).toAddSubmonoid :=
  closure_subset_span

@[simp]
/--
theorem `span_closure` / 定理 `span_closure`

English:
theorem span_closure
  given: {s : Set M}
  statement: span R (AddSubmonoid.closure s : Set M) = span R s
  proof: le_antisymm (span_le.mpr closure_subset_span) (span_mono AddSubmonoid.subset_closure)

中文:
定理 span_closure
  条件: {s : 集合 M}
  结论: span R (加法子幺半群.closure s : 集合 M) = span R s
  证明: le_antisymm (span_le.mpr closure_subset_span) (span_mono AddSubmonoid.subset_closure)

Depends on / 依赖: AddSubmonoid, AddSubmonoid.subset_closure, closure_subset_span, le_antisymm, span_le, span_le.mpr, span_mono, subset_closure
-/
theorem span_closure {s : Set M} : span R (AddSubmonoid.closure s : Set M) = span R s :=
  le_antisymm (span_le.mpr closure_subset_span) (span_mono AddSubmonoid.subset_closure)

/-- An induction principle for span membership. If `p` holds for 0 and all elements of `s`, and is
preserved under addition and scalar multiplication, then `p` holds for all elements of the span of
`s`. -/
@[elab_as_elim]
/--
theorem `span_induction` / 定理 `span_induction`

English:
theorem span_induction
  statement: {p : (x : M) -> x in span R s -> Prop}
  proof: by
  let p : Submodule R M :=
    { carrier := { x | exists hx, p x hx }
      add_mem' := fun ⟨_, hpx⟩ ⟨_, hpy⟩ => ⟨_, add _ _ _ _ hpx hpy⟩
      zero_mem' := ⟨_, zero⟩
      smul_mem' := fun r => fun ⟨_, hpx⟩ => ⟨_, smul r _ _ hpx⟩ }
.elim fun _ => id .mpr (fun y hy => ⟨subset_span hy, mem y hy⟩) 

中文:
定理 span_induction
  结论: {p : (x : M) -> x in span R s -> 命题}
  证明: by
  let p : Submodule R M :=
    { carrier := { x | exists hx, p x hx }
      add_mem' := fun ⟨_, hpx⟩ ⟨_, hpy⟩ => ⟨_, add _ _ _ _ hpx hpy⟩
      zero_mem' := ⟨_, zero⟩
      smul_mem' := fun r => fun ⟨_, hpx⟩ => ⟨_, smul r _ _ hpx⟩ }
.elim fun _ => id .mpr (fun y hy => ⟨subset_span hy, mem y hy⟩) 

Depends on / 依赖: Submodule, add_mem, carrier, smul_mem, span_le, subset_span, zero_mem
-/
theorem span_induction {p : (x : M) -> x in span R s -> Prop}
    (mem : forall (x) (h : x in s), p x (subset_span h))
    (zero : p 0 (Submodule.zero_mem _))
    (add : forall x y hx hy, p x hx -> p y hy -> p (x + y) (Submodule.add_mem _ ‹_› ‹_›))
    (smul : forall (a : R) (x hx), p x hx -> p (a • x) (Submodule.smul_mem _ _ ‹_›)) {x}
    (hx : x in span R s) : p x hx := by
  let p : Submodule R M :=
    { carrier := { x | exists hx, p x hx }
      add_mem' := fun ⟨_, hpx⟩ ⟨_, hpy⟩ => ⟨_, add _ _ _ _ hpx hpy⟩
      zero_mem' := ⟨_, zero⟩
      smul_mem' := fun r => fun ⟨_, hpx⟩ => ⟨_, smul r _ _ hpx⟩ }
.elim fun _ => id .mpr (fun y hy => ⟨subset_span hy, mem y hy⟩) hx exact span_le (p := p)

/--
theorem `span_induction₂` / 定理 `span_induction₂`

English:
theorem span_induction₂
  statement: {N : Type*} [AddCommMonoid N] [Module R N] {t : Set N}
  proof: by
  induction hb using span_induction with
  | mem z hz => induction ha using span_induction with
    | mem _ h => exact mem_mem _ _ h hz
    | zero => exact zero_left _ _
    | add _ _ _ _ h₁ h₂ => exact add_left _ _ _ _ _ _ h₁ h₂
    | smul _ _ _ h => exact smul_left _ _ _ _ _ h
  | zero => exact

中文:
定理 span_induction₂
  结论: {N : 类型} [加法交换幺半群 N] [模 R N] {t : 集合 N}
  证明: by
  induction hb using span_induction with
  | mem z hz => induction ha using span_induction with
    | mem _ h => exact mem_mem _ _ h hz
    | zero => exact zero_left _ _
    | add _ _ _ _ h₁ h₂ => exact add_left _ _ _ _ _ _ h₁ h₂
    | smul _ _ _ h => exact smul_left _ _ _ _ _ h
  | zero => exact

Depends on / 依赖: add_left, add_right, mem_mem, smul_left, smul_right, span_induction, zero_left, zero_right
-/
theorem span_induction₂ {N : Type*} [AddCommMonoid N] [Module R N] {t : Set N}
    {p : (x : M) -> (y : N) -> x in span R s -> y in span R t -> Prop}
    (mem_mem : forall (x) (y) (hx : x in s) (hy : y in t), p x y (subset_span hx) (subset_span hy))
    (zero_left : forall y hy, p 0 y (zero_mem _) hy) (zero_right : forall x hx, p x 0 hx (zero_mem _))
    (add_left : forall x y z hx hy hz, p x z hx hz -> p y z hy hz -> p (x + y) z (add_mem hx hy) hz)
    (add_right : forall x y z hx hy hz, p x y hx hy -> p x z hx hz -> p x (y + z) hx (add_mem hy hz))
    (smul_left : forall (r : R) x y hx hy, p x y hx hy -> p (r • x) y (smul_mem _ r hx) hy)
    (smul_right : forall (r : R) x y hx hy, p x y hx hy -> p x (r • y) hx (smul_mem _ r hy))
    {a : M} {b : N} (ha : a in Submodule.span R s)
    (hb : b in Submodule.span R t) : p a b ha hb := by
  induction hb using span_induction with
  | mem z hz => induction ha using span_induction with
    | mem _ h => exact mem_mem _ _ h hz
    | zero => exact zero_left _ _
    | add _ _ _ _ h₁ h₂ => exact add_left _ _ _ _ _ _ h₁ h₂
    | smul _ _ _ h => exact smul_left _ _ _ _ _ h
  | zero => exact zero_right a ha
  | add _ _ _ _ h₁ h₂ => exact add_right _ _ _ _ _ _ h₁ h₂
  | smul _ _ _ h => exact smul_right _ _ _ _ _ h

open AddSubmonoid in
/--
theorem `span_eq_closure` / 定理 `span_eq_closure`

English:
theorem span_eq_closure
  given: {s : Set M}
  statement: (span R s).toAddSubmonoid = closure (@univ R • s)
  proof: by
  refine le_antisymm (fun x (hx : x in span R s) => ?of_mem_span) (fun x hx => ?of_mem_closure)
  case of_mem_span =>
    induction hx using span_induction with
    | mem x hx => exact subset_closure ⟨1, trivial, x, hx, one_smul R x⟩
    | zero => exact zero_mem _
    | add _ _ _ _ h₁ h₂ => exact

中文:
定理 span_eq_closure
  条件: {s : 集合 M}
  结论: (span R s).toAddSubmonoid = closure (@univ R • s)
  证明: by
  refine le_antisymm (fun x (hx : x in span R s) => ?of_mem_span) (fun x hx => ?of_mem_closure)
  case of_mem_span =>
    induction hx using span_induction with
    | mem x hx => exact subset_closure ⟨1, trivial, x, hx, one_smul R x⟩
    | zero => exact zero_mem _
    | add _ _ _ _ h₁ h₂ => exact

Depends on / 依赖: add_mem, closure_induction, le_antisymm, mul_smul, of_mem_closure, of_mem_span, one_smul, smul_ze, span_induction, subset_closure, zero_mem
-/
theorem span_eq_closure {s : Set M} : (span R s).toAddSubmonoid = closure (@univ R • s) := by
  refine le_antisymm (fun x (hx : x in span R s) => ?of_mem_span) (fun x hx => ?of_mem_closure)
  case of_mem_span =>
    induction hx using span_induction with
    | mem x hx => exact subset_closure ⟨1, trivial, x, hx, one_smul R x⟩
    | zero => exact zero_mem _
    | add _ _ _ _ h₁ h₂ => exact add_mem h₁ h₂
    | smul r₁ y _h hy =>
      clear _h
      induction hy using closure_induction with
      | mem _ h =>
        obtain ⟨r₂, -, x, hx, rfl⟩ := h
        exact subset_closure ⟨r₁ * r₂, trivial, x, hx, mul_smul ..⟩
      | zero => simp only [smul_zero, zero_mem]
      | add _ _ _ _ h₁ h₂ => simpa only [smul_add] using add_mem h₁ h₂
  case of_mem_closure =>
    refine closure_le.2 ?_ hx
    rintro - ⟨r, -, x, hx, rfl⟩
    exact smul_mem _ _ (subset_span hx)

open AddSubmonoid in
/-- A variant of `span_induction` that combines `∀ x ∈ s, p x` and `∀ r x, p x → p (r • x)`
into a single condition `∀ r, ∀ x ∈ s, p (r • x)`, which can be easier to verify. -/
@[elab_as_elim]
/--
theorem `closure_induction` / 定理 `closure_induction`

English:
theorem closure_induction
  statement: {p : (x : M) -> x in span R s -> Prop}
  proof: by
  have key {v} : v in span R s ↔ v in closure (@univ R • s) := by simp [← span_eq_closure]
  refine AddSubmonoid.closure_induction (motive := fun x hx => p x (key.mpr hx))
    ?_ zero (by simpa only [key] using add) (key.mp hx)
  rintro - ⟨r, -, x, hx, rfl⟩
  exact smul_mem r x hx

@[simp]

中文:
定理 closure_induction
  结论: {p : (x : M) -> x in span R s -> 命题}
  证明: by
  have key {v} : v in span R s ↔ v in closure (@univ R • s) := by simp [← span_eq_closure]
  refine AddSubmonoid.closure_induction (motive := fun x hx => p x (key.mpr hx))
    ?_ zero (by simpa only [key] using add) (key.mp hx)
  rintro - ⟨r, -, x, hx, rfl⟩
  exact smul_mem r x hx

@[simp]

Depends on / 依赖: AddSubmonoid, AddSubmonoid.closure_induction, closure, closure_induction, key.mp, key.mpr, motive, smul_mem, span_eq_closure
-/
theorem closure_induction {p : (x : M) -> x in span R s -> Prop}
    (zero : p 0 (Submodule.zero_mem _))
    (add : forall x y hx hy, p x hx -> p y hy -> p (x + y) (Submodule.add_mem _ ‹_› ‹_›))
    (smul_mem : forall (r x) (h : x in s), p (r • x) (Submodule.smul_mem _ _ <| subset_span h)) {x}
    (hx : x in span R s) : p x hx := by
  have key {v} : v in span R s ↔ v in closure (@univ R • s) := by simp [← span_eq_closure]
  refine AddSubmonoid.closure_induction (motive := fun x hx => p x (key.mpr hx))
    ?_ zero (by simpa only [key] using add) (key.mp hx)
  rintro - ⟨r, -, x, hx, rfl⟩
  exact smul_mem r x hx

@[simp]
/--
theorem `span_span_coe_preimage` / 定理 `span_span_coe_preimage`

English:
theorem span_span_coe_preimage
  statement: span R (((↑) : span R s -> M) ⁻¹' s) = ⊤
  proof: eq_top_iff.2 fun x _ => Subtype.recOn x fun _ hx' =>
    span_induction (fun _ h => subset_span h) (zero_mem _) (fun _ _ _ _ => add_mem)
      (fun _ _ _ => smul_mem _ _) hx'

@[simp]

中文:
定理 span_span_coe_preimage
  结论: span R (((↑) : span R s -> M) ⁻¹' s) = ⊤
  证明: eq_top_iff.2 fun x _ => Subtype.recOn x fun _ hx' =>
    span_induction (fun _ h => subset_span h) (zero_mem _) (fun _ _ _ _ => add_mem)
      (fun _ _ _ => smul_mem _ _) hx'

@[simp]

Depends on / 依赖: Subtype, Subtype.recOn, add_mem, eq_top_iff, smul_mem, span_induction, subset_span, zero_mem
-/
theorem span_span_coe_preimage : span R (((↑) : span R s -> M) ⁻¹' s) = ⊤ :=
  eq_top_iff.2 fun x _ => Subtype.recOn x fun _ hx' =>
    span_induction (fun _ h => subset_span h) (zero_mem _) (fun _ _ _ _ => add_mem)
      (fun _ _ _ => smul_mem _ _) hx'

@[simp]
/--
lemma `span_setOfPred_mem_eq_top` / 引理 `span_setOfPred_mem_eq_top`

English:
lemma span_setOfPred_mem_eq_top
  proof: span_span_coe_preimage

@[deprecated (since := "2026-07-09")] alias span_setOf_mem_eq_top := span_setOfPred_mem_eq_top

中文:
引理 span_setOfPred_mem_eq_top
  证明: span_span_coe_preimage

@[deprecated (since := "2026-07-09")] alias span_setOf_mem_eq_top := span_setOfPred_mem_eq_top

Depends on / 依赖: span_span_coe_preimage
-/
lemma span_setOfPred_mem_eq_top :
    span R {x : span R s | (x : M) in s} = ⊤ :=
  span_span_coe_preimage

@[deprecated (since := "2026-07-09")] alias span_setOf_mem_eq_top := span_setOfPred_mem_eq_top

/--
theorem `span_nat_eq_addSubmonoidClosure` / 定理 `span_nat_eq_addSubmonoidClosure`

English:
theorem span_nat_eq_addSubmonoidClosure
  given: (s : Set M)
  proof: by
  refine Eq.symm (AddSubmonoid.closure_eq_of_le subset_span ?_)
  apply (OrderIso.to_galoisConnection (AddSubmonoid.toNatSubmodule (M := M)).symm).l_le
     (a := span Nat s) (b := AddSubmonoid.closure s)
  rw [span_le]
  exact AddSubmonoid.subset_closure

@[simp]

中文:
定理 span_nat_eq_addSubmonoidClosure
  条件: (s : 集合 M)
  证明: by
  refine Eq.symm (AddSubmonoid.closure_eq_of_le subset_span ?_)
  apply (OrderIso.to_galoisConnection (AddSubmonoid.toNatSubmodule (M := M)).symm).l_le
     (a := span Nat s) (b := AddSubmonoid.closure s)
  rw [span_le]
  exact AddSubmonoid.subset_closure

@[simp]

Depends on / 依赖: AddSubmonoid, AddSubmonoid.closure, AddSubmonoid.closure_eq_of_le, AddSubmonoid.subset_closure, AddSubmonoid.toNatSubmodule, Eq.symm, OrderIso, OrderIso.to_galoisConnection, closure, closure_eq_of_le, l_le, span_le, subset_closure, subset_span, toNatSubmodule, to_galoisConnection
-/
theorem span_nat_eq_addSubmonoidClosure (s : Set M) :
    (span Nat s).toAddSubmonoid = AddSubmonoid.closure s := by
  refine Eq.symm (AddSubmonoid.closure_eq_of_le subset_span ?_)
  apply (OrderIso.to_galoisConnection (AddSubmonoid.toNatSubmodule (M := M)).symm).l_le
     (a := span Nat s) (b := AddSubmonoid.closure s)
  rw [span_le]
  exact AddSubmonoid.subset_closure

@[simp]
/--
theorem `span_nat_eq` / 定理 `span_nat_eq`

English:
theorem span_nat_eq
  given: (s : AddSubmonoid M)
  statement: (span Nat (s : Set M)).toAddSubmonoid = s
  proof: by
  rw [span_nat_eq_addSubmonoidClosure]; rw [s.closure_eq]

中文:
定理 span_nat_eq
  条件: (s : 加法子幺半群 M)
  结论: (span 自然数 (s : 集合 M)).toAddSubmonoid = s
  证明: by
  rw [span_nat_eq_addSubmonoidClosure]; rw [s.closure_eq]

Depends on / 依赖: closure_eq, s.closure_eq, span_nat_eq_addSubmonoidClosure
-/
theorem span_nat_eq (s : AddSubmonoid M) : (span Nat (s : Set M)).toAddSubmonoid = s := by
  rw [span_nat_eq_addSubmonoidClosure]; rw [s.closure_eq]

/--
theorem `span_int_eq_addSubgroupClosure` / 定理 `span_int_eq_addSubgroupClosure`

English:
theorem span_int_eq_addSubgroupClosure
  given: {M : Type*} [AddCommGroup M] (s : Set M)
  proof: Eq.symm
    AddSubgroup.closure_eq_of_le _ subset_span fun _ hx =>
      span_induction (fun _ hx => AddSubgroup.subset_closure hx) (AddSubgroup.zero_mem _)
        (fun _ _ _ _ => AddSubgroup.add_mem _) (fun _ _ _ _ => AddSubgroup.zsmul_mem _ ‹_› _) hx

@[simp]

中文:
定理 span_int_eq_addSubgroupClosure
  条件: {M : 类型} [加法交换群 M] (s : 集合 M)
  证明: Eq.symm
    AddSubgroup.closure_eq_of_le _ subset_span fun _ hx =>
      span_induction (fun _ hx => AddSubgroup.subset_closure hx) (AddSubgroup.zero_mem _)
        (fun _ _ _ _ => AddSubgroup.add_mem _) (fun _ _ _ _ => AddSubgroup.zsmul_mem _ ‹_› _) hx

@[simp]

Depends on / 依赖: AddSubgroup, AddSubgroup.add_mem, AddSubgroup.closure_eq_of_le, AddSubgroup.subset_closure, AddSubgroup.zero_mem, AddSubgroup.zsmul_mem, Eq.symm, add_mem, closure_eq_of_le, span_induction, subset_closure, subset_span, zero_mem, zsmul_mem
-/
theorem span_int_eq_addSubgroupClosure {M : Type*} [AddCommGroup M] (s : Set M) :
    (span Int s).toAddSubgroup = AddSubgroup.closure s :=
Eq.symm
    AddSubgroup.closure_eq_of_le _ subset_span fun _ hx =>
      span_induction (fun _ hx => AddSubgroup.subset_closure hx) (AddSubgroup.zero_mem _)
        (fun _ _ _ _ => AddSubgroup.add_mem _) (fun _ _ _ _ => AddSubgroup.zsmul_mem _ ‹_› _) hx

@[simp]
/--
theorem `span_int_eq` / 定理 `span_int_eq`

English:
theorem span_int_eq
  given: {M : Type*} [AddCommGroup M] (s : AddSubgroup M)
  proof: by rw [span_int_eq_addSubgroupClosure, s.closure_eq]

中文:
定理 span_int_eq
  条件: {M : 类型} [加法交换群 M] (s : 加法子群 M)
  证明: by rw [span_int_eq_addSubgroupClosure, s.closure_eq]

Depends on / 依赖: closure_eq, s.closure_eq, span_int_eq_addSubgroupClosure
-/
theorem span_int_eq {M : Type*} [AddCommGroup M] (s : AddSubgroup M) :
    (span Int (s : Set M)).toAddSubgroup = s := by rw [span_int_eq_addSubgroupClosure, s.closure_eq]

/--
theorem `_root_.Disjoint.of_span` / 定理 `_root_.Disjoint.of_span`

English:
theorem _root_.Disjoint.of_span
  given: (hst : Disjoint (span R s) (span R t))
  proof: by
  rw [disjoint_iff_forall_ne]
  rintro v ⟨hvs, hv0 : v != 0⟩ _ hvt rfl
exact hv0 (disjoint_def.1 hst) v (subset_span hvs) (subset_span hvt)

中文:
定理 _root_.Disjoint.of_span
  条件: (hst : Disjoint (span R s) (span R t))
  证明: by
  rw [disjoint_iff_forall_ne]
  rintro v ⟨hvs, hv0 : v != 0⟩ _ hvt rfl
exact hv0 (disjoint_def.1 hst) v (subset_span hvs) (subset_span hvt)

Depends on / 依赖: disjoint_def, disjoint_iff_forall_ne, subset_span
-/
theorem _root_.Disjoint.of_span (hst : Disjoint (span R s) (span R t)) :
    Disjoint (s \ {0}) t := by
  rw [disjoint_iff_forall_ne]
  rintro v ⟨hvs, hv0 : v != 0⟩ _ hvt rfl
exact hv0 (disjoint_def.1 hst) v (subset_span hvs) (subset_span hvt)

/--
theorem `_root_.Disjoint.of_span₀` / 定理 `_root_.Disjoint.of_span₀`

English:
theorem _root_.Disjoint.of_span₀
  given: (hst : Disjoint (span R s) (span R t)) (h0s : 0 ∉ s)
  proof: by
  rw [← sdiff_singleton_eq_self h0s]
  exact hst.of_span

中文:
定理 _root_.Disjoint.of_span₀
  条件: (hst : Disjoint (span R s) (span R t)) (h0s : 0 ∉ s)
  证明: by
  rw [← sdiff_singleton_eq_self h0s]
  exact hst.of_span

Depends on / 依赖: hst.of_span, of_span, sdiff_singleton_eq_self
-/
theorem _root_.Disjoint.of_span₀ (hst : Disjoint (span R s) (span R t)) (h0s : 0 ∉ s) :
    Disjoint s t := by
  rw [← sdiff_singleton_eq_self h0s]
  exact hst.of_span

section

variable (R M)

/--
Definition of `gi` / `gi` 的定义

English:
definition gi
  signature: : GaloisInsertion (@span R M _ _ _) (↑) where
  body: span R s
  gc _ _ := span_le
  le_l_u _ := subset_span
  choice_eq _ _ := rfl

中文:
定义 gi
  签名: : Galois嵌入 (@span R M _ _ _) (↑) where
  定义体: span R s
  gc _ _ := span_le
  le_l_u _ := subset_span
  choice_eq _ _ := rfl
-/
protected def gi : GaloisInsertion (@span R M _ _ _) (↑) where
  choice s _ := span R s
  gc _ _ := span_le
  le_l_u _ := subset_span
  choice_eq _ _ := rfl

end

@[simp]
/--
theorem `span_empty` / 定理 `span_empty`

English:
theorem span_empty
  statement: span R (∅ : Set M) = ⊥
  proof: (Submodule.gi R M).gc.l_bot

@[simp]

中文:
定理 span_empty
  结论: span R (∅ : 集合 M) = ⊥
  证明: (Submodule.gi R M).gc.l_bot

@[simp]

Depends on / 依赖: Submodule, Submodule.gi, gc.l_bot, l_bot
-/
theorem span_empty : span R (∅ : Set M) = ⊥ :=
  (Submodule.gi R M).gc.l_bot

@[simp]
/--
theorem `span_univ` / 定理 `span_univ`

English:
theorem span_univ
  statement: span R (univ : Set M) = ⊤
  proof: eq_top_iff.2 SetLike.le_def.2 subset_span

@[simp]

中文:
定理 span_univ
  结论: span R (univ : 集合 M) = ⊤
  证明: eq_top_iff.2 SetLike.le_def.2 subset_span

@[simp]

Depends on / 依赖: SetLike, SetLike.le_def, eq_top_iff, le_def, subset_span
-/
theorem span_univ : span R (univ : Set M) = ⊤ :=
eq_top_iff.2 SetLike.le_def.2 subset_span

@[simp]
/--
theorem `span_inter` / 定理 `span_inter`

English:
theorem span_inter
  given: (S S' : Submodule R M)
  statement: span R (S inter S') = S ⊓ S'
  proof: (Submodule.gi R M).l_inf_u S S'

中文:
定理 span_inter
  条件: (S S' : 子模 R M)
  结论: span R (S inter S') = S ⊓ S'
  证明: (Submodule.gi R M).l_inf_u S S'

Depends on / 依赖: Submodule, Submodule.gi, l_inf_u
-/
theorem span_inter (S S' : Submodule R M) : span R (S inter S') = S ⊓ S' :=
  (Submodule.gi R M).l_inf_u S S'

/--
theorem `span_sInf_le` / 定理 `span_sInf_le`

English:
theorem span_sInf_le
  given: (s : Set (Set M))
  statement: span R (⋂₀ s) <= sInf (span R '' s)
  proof: le_sInf fun _ ⟨_, hTs, h⟩ => h ▸ span_mono (sInter_subset_of_mem hTs)

中文:
定理 span_sInf_le
  条件: (s : 集合 (集合 M))
  结论: span R (⋂₀ s) <= sInf (span R '' s)
  证明: le_sInf fun _ ⟨_, hTs, h⟩ => h ▸ span_mono (sInter_subset_of_mem hTs)

Depends on / 依赖: le_sInf, sInter_subset_of_mem, span_mono
-/
theorem span_sInf_le (s : Set (Set M)) : span R (⋂₀ s) <= sInf (span R '' s) :=
  le_sInf fun _ ⟨_, hTs, h⟩ => h ▸ span_mono (sInter_subset_of_mem hTs)

/--
theorem `span_sInf` / 定理 `span_sInf`

English:
theorem span_sInf
  given: (s : Set (Submodule R M))
  statement: span R (sInf s : Submodule R M) = sInf s
  proof: span_eq (sInf s)

中文:
定理 span_sInf
  条件: (s : 集合 (子模 R M))
  结论: span R (sInf s : 子模 R M) = sInf s
  证明: span_eq (sInf s)

Depends on / 依赖: span_eq
-/
theorem span_sInf (s : Set (Submodule R M)) : span R (sInf s : Submodule R M) = sInf s :=
  span_eq (sInf s)

/--
theorem `span_biInter` / 定理 `span_biInter`

English:
theorem span_biInter
  given: (s : Set (Submodule R M))
  statement: span R (⋂ S in s, S) = sInf s
  proof: by
  rw [← Submodule.coe_sInf]; rw [span_eq]

@[simp]

中文:
定理 span_bi整数er
  条件: (s : 集合 (子模 R M))
  结论: span R (⋂ S in s, S) = sInf s
  证明: by
  rw [← Submodule.coe_sInf]; rw [span_eq]

@[simp]

Depends on / 依赖: Submodule, Submodule.coe_sInf, coe_sInf, span_eq
-/
theorem span_biInter (s : Set (Submodule R M)) : span R (⋂ S in s, S) = sInf s := by
  rw [← Submodule.coe_sInf]; rw [span_eq]

@[simp]
/--
theorem `span_union` / 定理 `span_union`

English:
theorem span_union
  given: (s t : Set M)
  statement: span R (s union t) = span R s ⊔ span R t
  proof: (Submodule.gi R M).gc.l_sup

中文:
定理 span_union
  条件: (s t : 集合 M)
  结论: span R (s union t) = span R s ⊔ span R t
  证明: (Submodule.gi R M).gc.l_sup

Depends on / 依赖: Submodule, Submodule.gi, gc.l_sup, l_sup
-/
theorem span_union (s t : Set M) : span R (s union t) = span R s ⊔ span R t :=
  (Submodule.gi R M).gc.l_sup

/--
theorem `span_sSup` / 定理 `span_sSup`

English:
theorem span_sSup
  given: (s : Set (Set M))
  statement: span R (⋃₀ s) = sSup (span R '' s)
  proof: by
  refine le_antisymm ?_ (sSup_le fun P ⟨t, ht, h⟩ => h ▸ span_mono (subset_sUnion_of_mem ht))
  rw [span_le]
  exact fun x ⟨t, hts, hxt⟩ => le_sSup (mem_image_of_mem (span R) hts) (subset_span hxt)

中文:
定理 span_sSup
  条件: (s : 集合 (集合 M))
  结论: span R (⋃₀ s) = sSup (span R '' s)
  证明: by
  refine le_antisymm ?_ (sSup_le fun P ⟨t, ht, h⟩ => h ▸ span_mono (subset_sUnion_of_mem ht))
  rw [span_le]
  exact fun x ⟨t, hts, hxt⟩ => le_sSup (mem_image_of_mem (span R) hts) (subset_span hxt)

Depends on / 依赖: le_antisymm, le_sSup, mem_image_of_mem, sSup_le, span_le, span_mono, subset_sUnion_of_mem, subset_span
-/
theorem span_sSup (s : Set (Set M)) : span R (⋃₀ s) = sSup (span R '' s) := by
  refine le_antisymm ?_ (sSup_le fun P ⟨t, ht, h⟩ => h ▸ span_mono (subset_sUnion_of_mem ht))
  rw [span_le]
  exact fun x ⟨t, hts, hxt⟩ => le_sSup (mem_image_of_mem (span R) hts) (subset_span hxt)

/--
theorem `span_sSup'` / 定理 `span_sSup'`

English:
theorem span_sSup'
  given: (s : Set (Submodule R M))
  proof: Submodule.span_eq (sSup s)

中文:
定理 span_sSup'
  条件: (s : 集合 (子模 R M))
  证明: Submodule.span_eq (sSup s)

Depends on / 依赖: Submodule, Submodule.span_eq, span_eq
-/
theorem span_sSup' (s : Set (Submodule R M)) :
    span R (sSup s : Submodule R M) = sSup s := Submodule.span_eq (sSup s)

/--
theorem `span_iUnion` / 定理 `span_iUnion`

English:
theorem span_iUnion
  given: {ι} (s : ι -> Set M)
  statement: span R (⋃ i, s i) = ⨆ i, span R (s i)
  proof: (Submodule.gi R M).gc.l_iSup

中文:
定理 span_iUnion
  条件: {ι} (s : ι -> 集合 M)
  结论: span R (⋃ i, s i) = ⨆ i, span R (s i)
  证明: (Submodule.gi R M).gc.l_iSup

Depends on / 依赖: Submodule, Submodule.gi, gc.l_iSup, l_iSup
-/
theorem span_iUnion {ι} (s : ι -> Set M) : span R (⋃ i, s i) = ⨆ i, span R (s i) :=
  (Submodule.gi R M).gc.l_iSup

/--
theorem `span_iUnion₂` / 定理 `span_iUnion₂`

English:
theorem span_iUnion₂
  given: {ι} {κ : ι -> Sort*} (s : forall i, κ i -> Set M)
  proof: (Submodule.gi R M).gc.l_iSup₂

中文:
定理 span_iUnion₂
  条件: {ι} {κ : ι -> 类型层*} (s : 对任意 i, κ i -> 集合 M)
  证明: (Submodule.gi R M).gc.l_iSup₂

Depends on / 依赖: Submodule, Submodule.gi, gc.l_iSup
-/
theorem span_iUnion₂ {ι} {κ : ι -> Sort*} (s : forall i, κ i -> Set M) :
    span R (⋃ (i) (j), s i j) = ⨆ (i) (j), span R (s i j) :=
  (Submodule.gi R M).gc.l_iSup₂

/--
theorem `span_biUnion` / 定理 `span_biUnion`

English:
theorem span_biUnion
  given: (s : Set (Submodule R M))
  statement: span R (⋃ S in s, S) = sSup s
  proof: by
  simpa using (Submodule.gi R M).l_sSup_u_image s

中文:
定理 span_biUnion
  条件: (s : 集合 (子模 R M))
  结论: span R (⋃ S in s, S) = sSup s
  证明: by
  simpa using (Submodule.gi R M).l_sSup_u_image s

Depends on / 依赖: Submodule, Submodule.gi, l_sSup_u_image
-/
theorem span_biUnion (s : Set (Submodule R M)) : span R (⋃ S in s, S) = sSup s := by
  simpa using (Submodule.gi R M).l_sSup_u_image s

/--
theorem `span_attach_biUnion` / 定理 `span_attach_biUnion`

English:
theorem span_attach_biUnion
  given: [DecidableEq M] {α : Type*} (s : Finset α) (f : s -> Finset M)
  proof: by simp [span_iUnion]

中文:
定理 span_attach_biUnion
  条件: [DecidableEq M] {α : 类型} (s : 有限集 α) (f : s -> 有限集 M)
  证明: by simp [span_iUnion]

Depends on / 依赖: span_iUnion
-/
theorem span_attach_biUnion [DecidableEq M] {α : Type*} (s : Finset α) (f : s -> Finset M) :
    span R (s.attach.biUnion f : Set M) = ⨆ x, span R (f x) := by simp [span_iUnion]

/--
theorem `sup_span` / 定理 `sup_span`

English:
theorem sup_span
  statement: p ⊔ span R s = span R (p union s)
  proof: by rw [Submodule.span_union, p.span_eq]

中文:
定理 sup_span
  结论: p ⊔ span R s = span R (p union s)
  证明: by rw [Submodule.span_union, p.span_eq]

Depends on / 依赖: Submodule, Submodule.span_union, p.span_eq, span_eq, span_union
-/
theorem sup_span : p ⊔ span R s = span R (p union s) := by rw [Submodule.span_union, p.span_eq]

/--
theorem `span_sup` / 定理 `span_sup`

English:
theorem span_sup
  statement: span R s ⊔ p = span R (s union p)
  proof: by rw [Submodule.span_union, p.span_eq]

中文:
定理 span_sup
  结论: span R s ⊔ p = span R (s union p)
  证明: by rw [Submodule.span_union, p.span_eq]

Depends on / 依赖: Submodule, Submodule.span_union, p.span_eq, span_eq, span_union
-/
theorem span_sup : span R s ⊔ p = span R (s union p) := by rw [Submodule.span_union, p.span_eq]

/- Note that the character `∙` U+2219 used below is different from the scalar multiplication
character `•` U+2022. -/
notation:70 R:70 " ∙ " x:70 => span R (singleton x)

/-- Unexpander for `R ∙ x` notation. This needs to be defined separately because the `{_}`
notation is ambiguous, so we have to specify that it is the `«term{_}»` notation. -/
@[app_unexpander span]
meta def span.unexpander : Lean.PrettyPrinter.Unexpander
  | `($_ $R $s) => match s with
    | `(«term{_}»| {$a}) => `($R ∙ $a)
    | _ => throw ()
  | _ => throw ()

/--
theorem `span_eq_iSup_of_singleton_spans` / 定理 `span_eq_iSup_of_singleton_spans`

English:
theorem span_eq_iSup_of_singleton_spans
  given: (s : Set M)
  statement: span R s = ⨆ x in s, R ∙ x
  proof: by
  simp only [← span_iUnion, Set.biUnion_of_singleton s]

中文:
定理 span_eq_iSup_of_singleton_spans
  条件: (s : 集合 M)
  结论: span R s = ⨆ x in s, R ∙ x
  证明: by
  simp only [← span_iUnion, Set.biUnion_of_singleton s]

Depends on / 依赖: Set.biUnion_of_singleton, biUnion_of_singleton, span_iUnion
-/
theorem span_eq_iSup_of_singleton_spans (s : Set M) : span R s = ⨆ x in s, R ∙ x := by
  simp only [← span_iUnion, Set.biUnion_of_singleton s]

/--
theorem `span_range_eq_iSup` / 定理 `span_range_eq_iSup`

English:
theorem span_range_eq_iSup
  given: {ι : Sort*} {v : ι -> M}
  statement: span R (range v) = ⨆ i, R ∙ v i
  proof: by
  rw [span_eq_iSup_of_singleton_spans]; rw [iSup_range]

中文:
定理 span_range_eq_iSup
  条件: {ι : 类型层*} {v : ι -> M}
  结论: span R (range v) = ⨆ i, R ∙ v i
  证明: by
  rw [span_eq_iSup_of_singleton_spans]; rw [iSup_range]

Depends on / 依赖: iSup_range, span_eq_iSup_of_singleton_spans
-/
theorem span_range_eq_iSup {ι : Sort*} {v : ι -> M} : span R (range v) = ⨆ i, R ∙ v i := by
  rw [span_eq_iSup_of_singleton_spans]; rw [iSup_range]

/--
theorem `span_smul_le` / 定理 `span_smul_le`

English:
theorem span_smul_le
  given: (s : Set M) (r : R)
  statement: span R (r • s) <= span R s
  proof: by
  rw [span_le]
  rintro _ ⟨x, hx, rfl⟩
  exact smul_mem (span R s) r (subset_span hx)

中文:
定理 span_smul_le
  条件: (s : 集合 M) (r : R)
  结论: span R (r • s) <= span R s
  证明: by
  rw [span_le]
  rintro _ ⟨x, hx, rfl⟩
  exact smul_mem (span R s) r (subset_span hx)

Depends on / 依赖: smul_mem, span_le, subset_span
-/
theorem span_smul_le (s : Set M) (r : R) : span R (r • s) <= span R s := by
  rw [span_le]
  rintro _ ⟨x, hx, rfl⟩
  exact smul_mem (span R s) r (subset_span hx)

/--
theorem `subset_span_trans` / 定理 `subset_span_trans`

English:
theorem subset_span_trans
  statement: {U V W : Set M} (hUV : U subseteq Submodule.span R V)
  proof: (Submodule.gi R M).gc.le_u_l_trans hUV hVW

@[simp]

中文:
定理 subset_span_trans
  结论: {U V W : 集合 M} (hUV : U subseteq 子模.span R V)
  证明: (Submodule.gi R M).gc.le_u_l_trans hUV hVW

@[simp]

Depends on / 依赖: Submodule, Submodule.gi, gc.le_u_l_trans, le_u_l_trans
-/
theorem subset_span_trans {U V W : Set M} (hUV : U subseteq Submodule.span R V)
    (hVW : V subseteq Submodule.span R W) : U subseteq Submodule.span R W :=
  (Submodule.gi R M).gc.le_u_l_trans hUV hVW

@[simp]
/--
theorem `coe_iSup_of_directed` / 定理 `coe_iSup_of_directed`

English:
theorem coe_iSup_of_directed
  statement: {ι} [Nonempty ι] (S : ι -> Submodule R M)
  proof: let s : Submodule R M :=
    { __ := AddSubmonoid.copy _ _ (AddSubmonoid.coe_iSup_of_directed H).symm
      smul_mem' := fun r _ hx => have ⟨i, hi⟩ := Set.mem_iUnion.mp hx
        Set.mem_iUnion.mpr ⟨i, (S i).smul_mem' r hi⟩ }
  have : iSup S = s := le_antisymm
    (iSup_le fun i => le_iSup (fun i =

中文:
定理 coe_iSup_of_directed
  结论: {ι} [非空 ι] (S : ι -> 子模 R M)
  证明: let s : Submodule R M :=
    { __ := AddSubmonoid.copy _ _ (AddSubmonoid.coe_iSup_of_directed H).symm
      smul_mem' := fun r _ hx => have ⟨i, hi⟩ := Set.mem_iUnion.mp hx
        Set.mem_iUnion.mpr ⟨i, (S i).smul_mem' r hi⟩ }
  have : iSup S = s := le_antisymm
    (iSup_le fun i => le_iSup (fun i =

Depends on / 依赖: AddSubmonoid, AddSubmonoid.coe_iSup_of_directed, AddSubmonoid.copy, Set.iUnion_subset, Set.mem_iUnion.mp, Set.mem_iUnion.mpr, Submodule, coe_iSup_of_directed, iSup_le, iUnion_subset, le_antisymm, le_iSup, mem_iUnion, smul_mem, this.symm
-/
theorem coe_iSup_of_directed {ι} [Nonempty ι] (S : ι -> Submodule R M)
    (H : Directed (· <= ·) S) : ((iSup S : Submodule R M) : Set M) = ⋃ i, S i :=
  let s : Submodule R M :=
    { __ := AddSubmonoid.copy _ _ (AddSubmonoid.coe_iSup_of_directed H).symm
      smul_mem' := fun r _ hx => have ⟨i, hi⟩ := Set.mem_iUnion.mp hx
        Set.mem_iUnion.mpr ⟨i, (S i).smul_mem' r hi⟩ }
  have : iSup S = s := le_antisymm
    (iSup_le fun i => le_iSup (fun i => (S i : Set M)) i) (Set.iUnion_subset fun _ => le_iSup S _)
  this.symm ▸ rfl

@[simp]
/--
theorem `mem_iSup_of_directed` / 定理 `mem_iSup_of_directed`

English:
theorem mem_iSup_of_directed
  given: {ι} [Nonempty ι] (S : ι -> Submodule R M) (H : Directed (· <= ·) S) {x}
  proof: by
  rw [← SetLike.mem_coe]; rw [coe_iSup_of_directed S H]; rw [mem_iUnion]
  rfl

中文:
定理 mem_iSup_of_directed
  条件: {ι} [非空 ι] (S : ι -> 子模 R M) (H : Directed (· <= ·) S) {x}
  证明: by
  rw [← SetLike.mem_coe]; rw [coe_iSup_of_directed S H]; rw [mem_iUnion]
  rfl

Depends on / 依赖: SetLike, SetLike.mem_coe, coe_iSup_of_directed, mem_coe, mem_iUnion
-/
theorem mem_iSup_of_directed {ι} [Nonempty ι] (S : ι -> Submodule R M) (H : Directed (· <= ·) S) {x} :
    x in iSup S ↔ exists i, x in S i := by
  rw [← SetLike.mem_coe]; rw [coe_iSup_of_directed S H]; rw [mem_iUnion]
  rfl

/--
theorem `mem_sSup_of_directed` / 定理 `mem_sSup_of_directed`

English:
theorem mem_sSup_of_directed
  statement: {s : Set (Submodule R M)} {z} (hs : s.Nonempty)
  proof: by
  have : Nonempty s := hs.to_subtype
  simp only [sSup_eq_iSup', mem_iSup_of_directed _ hdir.directed_val, SetCoe.exists,
    exists_prop]

@[norm_cast, simp]

中文:
定理 mem_sSup_of_directed
  结论: {s : 集合 (子模 R M)} {z} (hs : s.非空)
  证明: by
  have : Nonempty s := hs.to_subtype
  simp only [sSup_eq_iSup', mem_iSup_of_directed _ hdir.directed_val, SetCoe.exists,
    exists_prop]

@[norm_cast, simp]

Depends on / 依赖: Nonempty, SetCoe, SetCoe.exists, directed_val, exists_prop, hdir.directed_val, hs.to_subtype, mem_iSup_of_directed, sSup_eq_iSup, to_subtype
-/
theorem mem_sSup_of_directed {s : Set (Submodule R M)} {z} (hs : s.Nonempty)
    (hdir : DirectedOn (· <= ·) s) : z in sSup s ↔ exists y in s, z in y := by
  have : Nonempty s := hs.to_subtype
  simp only [sSup_eq_iSup', mem_iSup_of_directed _ hdir.directed_val, SetCoe.exists,
    exists_prop]

@[norm_cast, simp]
/--
theorem `coe_iSup_of_chain` / 定理 `coe_iSup_of_chain`

English:
theorem coe_iSup_of_chain
  given: (a : Nat ->o Submodule R M)
  statement: (↑(⨆ k, a k) : Set M) = ⋃ k, (a k : Set M)
  proof: coe_iSup_of_directed a a.monotone.directed_le

@[simp]

中文:
定理 coe_iSup_of_chain
  条件: (a : 自然数 ->o 子模 R M)
  结论: (↑(⨆ k, a k) : 集合 M) = ⋃ k, (a k : 集合 M)
  证明: coe_iSup_of_directed a a.monotone.directed_le

@[simp]

Depends on / 依赖: a.monotone.directed_le, coe_iSup_of_directed, directed_le, monotone
-/
theorem coe_iSup_of_chain (a : Nat ->o Submodule R M) : (↑(⨆ k, a k) : Set M) = ⋃ k, (a k : Set M) :=
  coe_iSup_of_directed a a.monotone.directed_le

@[simp]
/--
theorem `mem_iSup_of_chain` / 定理 `mem_iSup_of_chain`

English:
theorem mem_iSup_of_chain
  given: (a : Nat ->o Submodule R M) (m : M)
  statement: (m in ⨆ k, a k) ↔ exists k, m in a k
  proof: mem_iSup_of_directed a a.monotone.directed_le

中文:
定理 mem_iSup_of_chain
  条件: (a : 自然数 ->o 子模 R M) (m : M)
  结论: (m in ⨆ k, a k) ↔ 存在 k, m in a k
  证明: mem_iSup_of_directed a a.monotone.directed_le

Depends on / 依赖: a.monotone.directed_le, directed_le, mem_iSup_of_directed, monotone
-/
theorem mem_iSup_of_chain (a : Nat ->o Submodule R M) (m : M) : (m in ⨆ k, a k) ↔ exists k, m in a k :=
  mem_iSup_of_directed a a.monotone.directed_le

section

variable {p p'}

/--
theorem `mem_sup` / 定理 `mem_sup`

English:
theorem mem_sup
  statement: x in p ⊔ p' ↔ exists y in p, exists z in p', y + z = x
  proof: ⟨fun h => by
    rw [← span_eq p]; rw [← span_eq p']; rw [← span_union] at h
    refine span_induction ?_ ?_ ?_ ?_ h
    · rintro y (h | h)
      · exact ⟨y, h, 0, by simp, by simp⟩
      · exact ⟨0, by simp, y, h, by simp⟩
    · exact ⟨0, by simp, 0, by simp⟩
    · rintro _ _ - - ⟨y₁, hy₁, z₁, hz₁,

中文:
定理 mem_sup
  结论: x in p ⊔ p' ↔ 存在 y in p, 存在 z in p', y + z = x
  证明: ⟨fun h => by
    rw [← span_eq p]; rw [← span_eq p']; rw [← span_union] at h
    refine span_induction ?_ ?_ ?_ ?_ h
    · rintro y (h | h)
      · exact ⟨y, h, 0, by simp, by simp⟩
      · exact ⟨0, by simp, y, h, by simp⟩
    · exact ⟨0, by simp, 0, by simp⟩
    · rintro _ _ - - ⟨y₁, hy₁, z₁, hz₁,

Depends on / 依赖: add_assoc, add_comm, add_mem, smul_mem, span_eq, span_induction, span_union
-/
theorem mem_sup : x in p ⊔ p' ↔ exists y in p, exists z in p', y + z = x :=
  ⟨fun h => by
    rw [← span_eq p]; rw [← span_eq p']; rw [← span_union] at h
    refine span_induction ?_ ?_ ?_ ?_ h
    · rintro y (h | h)
      · exact ⟨y, h, 0, by simp, by simp⟩
      · exact ⟨0, by simp, y, h, by simp⟩
    · exact ⟨0, by simp, 0, by simp⟩
    · rintro _ _ - - ⟨y₁, hy₁, z₁, hz₁, rfl⟩ ⟨y₂, hy₂, z₂, hz₂, rfl⟩
      exact ⟨_, add_mem hy₁ hy₂, _, add_mem hz₁ hz₂, by
        rw [add_assoc]; rw [add_assoc]; rw [← add_assoc y₂]; rw [← add_assoc z₁]; rw [add_comm y₂]⟩
    · rintro a - _ ⟨y, hy, z, hz, rfl⟩
      exact ⟨_, smul_mem _ a hy, _, smul_mem _ a hz, by simp [smul_add]⟩, by
    rintro ⟨y, hy, z, hz, rfl⟩
    exact add_mem ((le_sup_left : p <= p ⊔ p') hy) ((le_sup_right : p' <= p ⊔ p') hz)⟩

/--
theorem `mem_sup'` / 定理 `mem_sup'`

English:
theorem mem_sup'
  statement: x in p ⊔ p' ↔ exists (y : p) (z : p'), (y : M) + z = x
  proof: mem_sup.trans by simp only [Subtype.exists, exists_prop]

中文:
定理 mem_sup'
  结论: x in p ⊔ p' ↔ 存在 (y : p) (z : p'), (y : M) + z = x
  证明: mem_sup.trans by simp only [Subtype.exists, exists_prop]

Depends on / 依赖: Subtype, Subtype.exists, exists_prop, mem_sup, mem_sup.trans
-/
theorem mem_sup' : x in p ⊔ p' ↔ exists (y : p) (z : p'), (y : M) + z = x :=
mem_sup.trans by simp only [Subtype.exists, exists_prop]

/--
theorem `codisjoint_iff_exists_add_eq` / 定理 `codisjoint_iff_exists_add_eq`

English:
theorem codisjoint_iff_exists_add_eq
  proof: by
  rw [codisjoint_iff]; rw [eq_top_iff']
  exact forall_congr' (fun z => mem_sup.trans <| by simp)

中文:
定理 codisjoint_iff_存在_add_eq
  证明: by
  rw [codisjoint_iff]; rw [eq_top_iff']
  exact forall_congr' (fun z => mem_sup.trans <| by simp)

Depends on / 依赖: codisjoint_iff, eq_top_iff, forall_congr, mem_sup, mem_sup.trans
-/
theorem codisjoint_iff_exists_add_eq :
    Codisjoint p p' ↔ forall z, exists x y, x in p ∧ y in p' ∧ x + y = z := by
  rw [codisjoint_iff]; rw [eq_top_iff']
  exact forall_congr' (fun z => mem_sup.trans <| by simp)

variable (p p')

/--
theorem `coe_sup` / 定理 `coe_sup`

English:
theorem coe_sup
  statement: ↑(p ⊔ p') = (p + p' : Set M)
  proof: by
  ext
  rw [SetLike.mem_coe]; rw [mem_sup]; rw [Set.mem_add]
  simp

中文:
定理 coe_sup
  结论: ↑(p ⊔ p') = (p + p' : 集合 M)
  证明: by
  ext
  rw [SetLike.mem_coe]; rw [mem_sup]; rw [Set.mem_add]
  simp

Depends on / 依赖: Set.mem_add, SetLike, SetLike.mem_coe, mem_add, mem_coe, mem_sup
-/
theorem coe_sup : ↑(p ⊔ p') = (p + p' : Set M) := by
  ext
  rw [SetLike.mem_coe]; rw [mem_sup]; rw [Set.mem_add]
  simp

/--
theorem `sup_toAddSubmonoid` / 定理 `sup_toAddSubmonoid`

English:
theorem sup_toAddSubmonoid
  statement: (p ⊔ p').toAddSubmonoid = p.toAddSubmonoid ⊔ p'.toAddSubmonoid
  proof: by
  ext x
  rw [mem_toAddSubmonoid]; rw [mem_sup]; rw [AddSubmonoid.mem_sup]
  rfl

中文:
定理 sup_toAddSubmonoid
  结论: (p ⊔ p').toAddSubmonoid = p.toAddSubmonoid ⊔ p'.toAddSubmonoid
  证明: by
  ext x
  rw [mem_toAddSubmonoid]; rw [mem_sup]; rw [AddSubmonoid.mem_sup]
  rfl

Depends on / 依赖: AddSubmonoid, AddSubmonoid.mem_sup, mem_sup, mem_toAddSubmonoid
-/
theorem sup_toAddSubmonoid : (p ⊔ p').toAddSubmonoid = p.toAddSubmonoid ⊔ p'.toAddSubmonoid := by
  ext x
  rw [mem_toAddSubmonoid]; rw [mem_sup]; rw [AddSubmonoid.mem_sup]
  rfl

/--
theorem `sup_eq_top_iff` / 定理 `sup_eq_top_iff`

English:
theorem sup_eq_top_iff
  statement: p ⊔ p' = ⊤ ↔ forall m : M, exists u in p, exists v in p', m = u + v
  proof: by
  rw [eq_top_iff']
  refine forall_congr' fun m => ?_
  rw [mem_sup]
  tauto

中文:
定理 sup_eq_top_iff
  结论: p ⊔ p' = ⊤ ↔ 对任意 m : M, 存在 u in p, 存在 v in p', m = u + v
  证明: by
  rw [eq_top_iff']
  refine forall_congr' fun m => ?_
  rw [mem_sup]
  tauto

Depends on / 依赖: eq_top_iff, forall_congr, mem_sup
-/
theorem sup_eq_top_iff : p ⊔ p' = ⊤ ↔ forall m : M, exists u in p, exists v in p', m = u + v := by
  rw [eq_top_iff']
  refine forall_congr' fun m => ?_
  rw [mem_sup]
  tauto

variable {P : M -> Prop}

@[simp high]
/--
lemma `forall_mem_sup` / 引理 `forall_mem_sup`

English:
lemma forall_mem_sup
  statement: (forall x in p ⊔ p', P x) ↔ (forall x₁ in p, forall x₂ in p', P (x₁ + x₂))
  proof: by
  simp [mem_sup]
  aesop

@[simp high]

中文:
引理 对任意_mem_sup
  结论: (对任意 x in p ⊔ p', P x) ↔ (对任意 x₁ in p, 对任意 x₂ in p', P (x₁ + x₂))
  证明: by
  simp [mem_sup]
  aesop

@[simp high]

Depends on / 依赖: mem_sup
-/
lemma forall_mem_sup : (forall x in p ⊔ p', P x) ↔ (forall x₁ in p, forall x₂ in p', P (x₁ + x₂)) := by
  simp [mem_sup]
  aesop

@[simp high]
/--
lemma `exists_mem_sup` / 引理 `exists_mem_sup`

English:
lemma exists_mem_sup
  statement: (exists x in p ⊔ p', P x) ↔ (exists x₁ in p, exists x₂ in p', P (x₁ + x₂))
  proof: by
  simp [mem_sup]

中文:
引理 存在_mem_sup
  结论: (存在 x in p ⊔ p', P x) ↔ (存在 x₁ in p, 存在 x₂ in p', P (x₁ + x₂))
  证明: by
  simp [mem_sup]

Depends on / 依赖: mem_sup
-/
lemma exists_mem_sup : (exists x in p ⊔ p', P x) ↔ (exists x₁ in p, exists x₂ in p', P (x₁ + x₂)) := by
  simp [mem_sup]

end

@[simp]
/--
theorem `mem_span_singleton_self` / 定理 `mem_span_singleton_self`

English:
theorem mem_span_singleton_self
  given: (x : M)
  statement: x in R ∙ x
  proof: subset_span rfl

中文:
定理 mem_span_singleton_self
  条件: (x : M)
  结论: x in R ∙ x
  证明: subset_span rfl

Depends on / 依赖: subset_span
-/
theorem mem_span_singleton_self (x : M) : x in R ∙ x :=
  subset_span rfl

/--
theorem `nontrivial_span_singleton` / 定理 `nontrivial_span_singleton`

English:
theorem nontrivial_span_singleton
  given: {x : M} (h : x != 0)
  statement: Nontrivial (R ∙ x)
  proof: ⟨by
    use 0, ⟨x, Submodule.mem_span_singleton_self x⟩
    intro H
    rw [eq_comm]; rw [Submodule.mk_eq_zero] at H
    exact h H⟩

中文:
定理 nontrivial_span_singleton
  条件: {x : M} (h : x != 0)
  结论: 非平凡 (R ∙ x)
  证明: ⟨by
    use 0, ⟨x, Submodule.mem_span_singleton_self x⟩
    intro H
    rw [eq_comm]; rw [Submodule.mk_eq_zero] at H
    exact h H⟩

Depends on / 依赖: Submodule, Submodule.mem_span_singleton_self, Submodule.mk_eq_zero, eq_comm, mem_span_singleton_self, mk_eq_zero
-/
theorem nontrivial_span_singleton {x : M} (h : x != 0) : Nontrivial (R ∙ x) :=
  ⟨by
    use 0, ⟨x, Submodule.mem_span_singleton_self x⟩
    intro H
    rw [eq_comm]; rw [Submodule.mk_eq_zero] at H
    exact h H⟩

/--
theorem `mem_span_singleton` / 定理 `mem_span_singleton`

English:
theorem mem_span_singleton
  given: {y : M}
  statement: x in R ∙ y ↔ exists a : R, a • y = x
  proof: ⟨fun h => by
    refine span_induction ?_ ?_ ?_ ?_ h
    · rintro y (rfl | ⟨⟨_⟩⟩)
      exact ⟨1, by simp⟩
    · exact ⟨0, by simp⟩
    · rintro _ _ - - ⟨a, rfl⟩ ⟨b, rfl⟩
      exact ⟨a + b, by simp [add_smul]⟩
    · rintro a _ - ⟨b, rfl⟩
      exact ⟨a * b, by simp [smul_smul]⟩, by
    rintro ⟨a, y

中文:
定理 mem_span_singleton
  条件: {y : M}
  结论: x in R ∙ y ↔ 存在 a : R, a • y = x
  证明: ⟨fun h => by
    refine span_induction ?_ ?_ ?_ ?_ h
    · rintro y (rfl | ⟨⟨_⟩⟩)
      exact ⟨1, by simp⟩
    · exact ⟨0, by simp⟩
    · rintro _ _ - - ⟨a, rfl⟩ ⟨b, rfl⟩
      exact ⟨a + b, by simp [add_smul]⟩
    · rintro a _ - ⟨b, rfl⟩
      exact ⟨a * b, by simp [smul_smul]⟩, by
    rintro ⟨a, y

Depends on / 依赖: add_smul, smul_mem, smul_smul, span_induction, subset_span
-/
theorem mem_span_singleton {y : M} : x in R ∙ y ↔ exists a : R, a • y = x :=
  ⟨fun h => by
    refine span_induction ?_ ?_ ?_ ?_ h
    · rintro y (rfl | ⟨⟨_⟩⟩)
      exact ⟨1, by simp⟩
    · exact ⟨0, by simp⟩
    · rintro _ _ - - ⟨a, rfl⟩ ⟨b, rfl⟩
      exact ⟨a + b, by simp [add_smul]⟩
    · rintro a _ - ⟨b, rfl⟩
      exact ⟨a * b, by simp [smul_smul]⟩, by
    rintro ⟨a, y, rfl⟩; exact smul_mem _ _ (subset_span <| by simp)⟩

/--
theorem `le_span_singleton_iff` / 定理 `le_span_singleton_iff`

English:
theorem le_span_singleton_iff
  given: {s : Submodule R M} {v₀ : M}
  proof: by simp_rw [SetLike.le_def, mem_span_singleton]

中文:
定理 le_span_singleton_iff
  条件: {s : 子模 R M} {v₀ : M}
  证明: by simp_rw [SetLike.le_def, mem_span_singleton]

Depends on / 依赖: SetLike, SetLike.le_def, le_def, mem_span_singleton, simp_rw
-/
theorem le_span_singleton_iff {s : Submodule R M} {v₀ : M} :
    s <= R ∙ v₀ ↔ forall v in s, exists r : R, r • v₀ = v := by simp_rw [SetLike.le_def, mem_span_singleton]

/--
theorem `eq_span_singleton_of_surjective` / 定理 `eq_span_singleton_of_surjective`

English:
theorem eq_span_singleton_of_surjective
  statement: {s : Submodule R M}
  proof: by
  refine le_antisymm (fun x hx => mem_span_singleton.mpr ?_)
    (span_le.mpr <| by rintro _ rfl; exact (f 1).2)
  have ⟨r, eq⟩ := hf ⟨x, hx⟩
  exact ⟨r, by rw [← coe_smul, ← map_smul, smul_eq_mul, mul_one, eq]⟩

中文:
定理 eq_span_singleton_of_surjective
  结论: {s : 子模 R M}
  证明: by
  refine le_antisymm (fun x hx => mem_span_singleton.mpr ?_)
    (span_le.mpr <| by rintro _ rfl; exact (f 1).2)
  have ⟨r, eq⟩ := hf ⟨x, hx⟩
  exact ⟨r, by rw [← coe_smul, ← map_smul, smul_eq_mul, mul_one, eq]⟩

Depends on / 依赖: coe_smul, le_antisymm, map_smul, mem_span_singleton, mem_span_singleton.mpr, mul_one, smul_eq_mul, span_le, span_le.mpr
-/
theorem eq_span_singleton_of_surjective {s : Submodule R M}
    {f : R ->ₗ[R] s} (hf : Surjective f) : s = span R {(f 1 : M)} := by
  refine le_antisymm (fun x hx => mem_span_singleton.mpr ?_)
    (span_le.mpr <| by rintro _ rfl; exact (f 1).2)
  have ⟨r, eq⟩ := hf ⟨x, hx⟩
  exact ⟨r, by rw [← coe_smul, ← map_smul, smul_eq_mul, mul_one, eq]⟩

variable (R)

/--
theorem `span_singleton_eq_top_iff` / 定理 `span_singleton_eq_top_iff`

English:
theorem span_singleton_eq_top_iff
  given: (x : M)
  statement: R ∙ x = ⊤ ↔ forall v, exists r : R, r • x = v
  proof: by
  rw [eq_top_iff]; rw [le_span_singleton_iff]
  tauto

@[simp]

中文:
定理 span_singleton_eq_top_iff
  条件: (x : M)
  结论: R ∙ x = ⊤ ↔ 对任意 v, 存在 r : R, r • x = v
  证明: by
  rw [eq_top_iff]; rw [le_span_singleton_iff]
  tauto

@[simp]

Depends on / 依赖: eq_top_iff, le_span_singleton_iff
-/
theorem span_singleton_eq_top_iff (x : M) : R ∙ x = ⊤ ↔ forall v, exists r : R, r • x = v := by
  rw [eq_top_iff]; rw [le_span_singleton_iff]
  tauto

@[simp]
/--
theorem `span_zero_singleton` / 定理 `span_zero_singleton`

English:
theorem span_zero_singleton
  statement: R ∙ (0 : M) = ⊥
  proof: by
  ext
  simp [mem_span_singleton, eq_comm]

中文:
定理 span_zero_singleton
  结论: R ∙ (0 : M) = ⊥
  证明: by
  ext
  simp [mem_span_singleton, eq_comm]

Depends on / 依赖: eq_comm, mem_span_singleton
-/
theorem span_zero_singleton : R ∙ (0 : M) = ⊥ := by
  ext
  simp [mem_span_singleton, eq_comm]

/--
theorem `span_singleton_eq_range` / 定理 `span_singleton_eq_range`

English:
theorem span_singleton_eq_range
  given: (y : M)
  statement: R ∙ y = range ((· • y) : R -> M)
  proof: Set.ext fun _ => mem_span_singleton

中文:
定理 span_singleton_eq_range
  条件: (y : M)
  结论: R ∙ y = range ((· • y) : R -> M)
  证明: Set.ext fun _ => mem_span_singleton

Depends on / 依赖: Set.ext, mem_span_singleton
-/
theorem span_singleton_eq_range (y : M) : R ∙ y = range ((· • y) : R -> M) :=
  Set.ext fun _ => mem_span_singleton

/--
theorem `span_singleton_smul_le` / 定理 `span_singleton_smul_le`

English:
theorem span_singleton_smul_le
  statement: {S} [SMul S R] [SMul S M] [IsScalarTower S R M]
  proof: by
  rw [span_le]; rw [Set.singleton_subset_iff]; rw [SetLike.mem_coe]
  exact smul_of_tower_mem _ _ (mem_span_singleton_self _)

中文:
定理 span_singleton_smul_le
  结论: {S} [标量乘法 S R] [标量乘法 S M] [标量塔 S R M]
  证明: by
  rw [span_le]; rw [Set.singleton_subset_iff]; rw [SetLike.mem_coe]
  exact smul_of_tower_mem _ _ (mem_span_singleton_self _)

Depends on / 依赖: Set.singleton_subset_iff, SetLike, SetLike.mem_coe, mem_coe, mem_span_singleton_self, singleton_subset_iff, smul_of_tower_mem, span_le
-/
theorem span_singleton_smul_le {S} [SMul S R] [SMul S M] [IsScalarTower S R M]
    (r : S) (x : M) : R ∙ r • x <= R ∙ x := by
  rw [span_le]; rw [Set.singleton_subset_iff]; rw [SetLike.mem_coe]
  exact smul_of_tower_mem _ _ (mem_span_singleton_self _)

/--
theorem `span_singleton_group_smul_eq` / 定理 `span_singleton_group_smul_eq`

English:
theorem span_singleton_group_smul_eq
  statement: {G} [Group G] [SMul G R] [MulAction G M] [IsScalarTower G R M]
  proof: by
  refine le_antisymm (span_singleton_smul_le R g x) ?_
  convert! span_singleton_smul_le R g⁻¹ (g • x)
  exact (inv_smul_smul g x).symm

中文:
定理 span_singleton_group_smul_eq
  结论: {G} [群 G] [标量乘法 G R] [乘法作用 G M] [标量塔 G R M]
  证明: by
  refine le_antisymm (span_singleton_smul_le R g x) ?_
  convert! span_singleton_smul_le R g⁻¹ (g • x)
  exact (inv_smul_smul g x).symm

Depends on / 依赖: convert, inv_smul_smul, le_antisymm, span_singleton_smul_le
-/
theorem span_singleton_group_smul_eq {G} [Group G] [SMul G R] [MulAction G M] [IsScalarTower G R M]
    (g : G) (x : M) : R ∙ g • x = R ∙ x := by
  refine le_antisymm (span_singleton_smul_le R g x) ?_
  convert! span_singleton_smul_le R g⁻¹ (g • x)
  exact (inv_smul_smul g x).symm

variable {R}

/--
theorem `span_singleton_smul_eq` / 定理 `span_singleton_smul_eq`

English:
theorem span_singleton_smul_eq
  given: {r : R} (hr : IsUnit r) (x : M)
  statement: R ∙ r • x = R ∙ x
  proof: by
  lift r to Rˣ using hr
  rw [← Units.smul_def]
  exact span_singleton_group_smul_eq R r x

中文:
定理 span_singleton_smul_eq
  条件: {r : R} (hr : 是单位 r) (x : M)
  结论: R ∙ r • x = R ∙ x
  证明: by
  lift r to Rˣ using hr
  rw [← Units.smul_def]
  exact span_singleton_group_smul_eq R r x

Depends on / 依赖: Units.smul_def, smul_def, span_singleton_group_smul_eq
-/
theorem span_singleton_smul_eq {r : R} (hr : IsUnit r) (x : M) : R ∙ r • x = R ∙ x := by
  lift r to Rˣ using hr
  rw [← Units.smul_def]
  exact span_singleton_group_smul_eq R r x

/--
theorem `mem_span_singleton_trans` / 定理 `mem_span_singleton_trans`

English:
theorem mem_span_singleton_trans
  given: {x y z : M} (hxy : x in R ∙ y) (hyz : y in R ∙ z)
  statement: x in R ∙ z
  proof: by
  rw [← SetLike.mem_coe]; rw [← singleton_subset_iff] at *
  exact Submodule.subset_span_trans hxy hyz

中文:
定理 mem_span_singleton_trans
  条件: {x y z : M} (hxy : x in R ∙ y) (hyz : y in R ∙ z)
  结论: x in R ∙ z
  证明: by
  rw [← SetLike.mem_coe]; rw [← singleton_subset_iff] at *
  exact Submodule.subset_span_trans hxy hyz

Depends on / 依赖: SetLike, SetLike.mem_coe, Submodule, Submodule.subset_span_trans, mem_coe, singleton_subset_iff, subset_span_trans
-/
theorem mem_span_singleton_trans {x y z : M} (hxy : x in R ∙ y) (hyz : y in R ∙ z) : x in R ∙ z := by
  rw [← SetLike.mem_coe]; rw [← singleton_subset_iff] at *
  exact Submodule.subset_span_trans hxy hyz

/--
theorem `span_insert` / 定理 `span_insert`

English:
theorem span_insert
  given: (x) (s : Set M)
  statement: span R (insert x s) = R ∙ x ⊔ span R s
  proof: by
  rw [insert_eq]; rw [span_union]

中文:
定理 span_insert
  条件: (x) (s : 集合 M)
  结论: span R (insert x s) = R ∙ x ⊔ span R s
  证明: by
  rw [insert_eq]; rw [span_union]

Depends on / 依赖: insert_eq, span_union
-/
theorem span_insert (x) (s : Set M) : span R (insert x s) = R ∙ x ⊔ span R s := by
  rw [insert_eq]; rw [span_union]

/--
theorem `span_insert_eq_span` / 定理 `span_insert_eq_span`

English:
theorem span_insert_eq_span
  given: (h : x in span R s)
  statement: span R (insert x s) = span R s
  proof: span_eq_of_le _ (Set.insert_subset_iff.mpr ⟨h, subset_span⟩) (span_mono <| subset_insert _ _)

中文:
定理 span_insert_eq_span
  条件: (h : x in span R s)
  结论: span R (insert x s) = span R s
  证明: span_eq_of_le _ (Set.insert_subset_iff.mpr ⟨h, subset_span⟩) (span_mono <| subset_insert _ _)

Depends on / 依赖: Set.insert_subset_iff.mpr, insert_subset_iff, span_eq_of_le, span_mono, subset_insert, subset_span
-/
theorem span_insert_eq_span (h : x in span R s) : span R (insert x s) = span R s :=
  span_eq_of_le _ (Set.insert_subset_iff.mpr ⟨h, subset_span⟩) (span_mono <| subset_insert _ _)

/--
theorem `span_span` / 定理 `span_span`

English:
theorem span_span
  statement: span R (span R s : Set M) = span R s
  proof: span_eq _

中文:
定理 span_span
  结论: span R (span R s : 集合 M) = span R s
  证明: span_eq _

Depends on / 依赖: span_eq
-/
theorem span_span : span R (span R s : Set M) = span R s :=
  span_eq _

/--
theorem `mem_span_insert` / 定理 `mem_span_insert`

English:
theorem mem_span_insert
  given: {y}
  proof: by
  simp [span_insert, mem_sup, mem_span_singleton, eq_comm (a := x)]

中文:
定理 mem_span_insert
  条件: {y}
  证明: by
  simp [span_insert, mem_sup, mem_span_singleton, eq_comm (a := x)]

Depends on / 依赖: eq_comm, mem_span_singleton, mem_sup, span_insert
-/
theorem mem_span_insert {y} :
    x in span R (insert y s) ↔ exists a : R, exists z in span R s, x = a • y + z := by
  simp [span_insert, mem_sup, mem_span_singleton, eq_comm (a := x)]

/--
theorem `mem_span_pair` / 定理 `mem_span_pair`

English:
theorem mem_span_pair
  given: {x y z : M}
  proof: by
  simp_rw [mem_span_insert, mem_span_singleton, exists_exists_eq_and, eq_comm]

中文:
定理 mem_span_pair
  条件: {x y z : M}
  证明: by
  simp_rw [mem_span_insert, mem_span_singleton, exists_exists_eq_and, eq_comm]

Depends on / 依赖: eq_comm, exists_exists_eq_and, mem_span_insert, mem_span_singleton, simp_rw
-/
theorem mem_span_pair {x y z : M} :
    z in span R ({x, y} : Set M) ↔ exists a b : R, a • x + b • y = z := by
  simp_rw [mem_span_insert, mem_span_singleton, exists_exists_eq_and, eq_comm]

/--
theorem `mem_span_triple` / 定理 `mem_span_triple`

English:
theorem mem_span_triple
  given: {w x y z : M}
  proof: by
  rw [mem_span_insert]
  simp_rw [mem_span_pair]
  refine exists_congr fun a => ⟨?_, ?_⟩
  · rintro ⟨u, ⟨b, c, rfl⟩, rfl⟩
    exact ⟨b, c, by rw [add_assoc]⟩
  · rintro ⟨b, c, rfl⟩
    exact ⟨b • y + c • z, ⟨b, c, rfl⟩, by rw [add_assoc]⟩

@[simp]

中文:
定理 mem_span_triple
  条件: {w x y z : M}
  证明: by
  rw [mem_span_insert]
  simp_rw [mem_span_pair]
  refine exists_congr fun a => ⟨?_, ?_⟩
  · rintro ⟨u, ⟨b, c, rfl⟩, rfl⟩
    exact ⟨b, c, by rw [add_assoc]⟩
  · rintro ⟨b, c, rfl⟩
    exact ⟨b • y + c • z, ⟨b, c, rfl⟩, by rw [add_assoc]⟩

@[simp]

Depends on / 依赖: add_assoc, exists_congr, mem_span_insert, mem_span_pair, simp_rw
-/
theorem mem_span_triple {w x y z : M} :
    w in span R ({x, y, z} : Set M) ↔ exists a b c : R, a • x + b • y + c • z = w := by
  rw [mem_span_insert]
  simp_rw [mem_span_pair]
  refine exists_congr fun a => ⟨?_, ?_⟩
  · rintro ⟨u, ⟨b, c, rfl⟩, rfl⟩
    exact ⟨b, c, by rw [add_assoc]⟩
  · rintro ⟨b, c, rfl⟩
    exact ⟨b • y + c • z, ⟨b, c, rfl⟩, by rw [add_assoc]⟩

@[simp]
/--
theorem `span_eq_bot` / 定理 `span_eq_bot`

English:
theorem span_eq_bot
  statement: span R (s : Set M) = ⊥ ↔ forall x in s, (x : M) = 0
  proof: eq_bot_iff.trans
⟨fun H _ h => (mem_bot R).1 H subset_span h, fun H =>
span_le.2 fun x h => (mem_bot R).2 H x h⟩

中文:
定理 span_eq_bot
  结论: span R (s : 集合 M) = ⊥ ↔ 对任意 x in s, (x : M) = 0
  证明: eq_bot_iff.trans
⟨fun H _ h => (mem_bot R).1 H subset_span h, fun H =>
span_le.2 fun x h => (mem_bot R).2 H x h⟩

Depends on / 依赖: eq_bot_iff, eq_bot_iff.trans, mem_bot, span_le, subset_span
-/
theorem span_eq_bot : span R (s : Set M) = ⊥ ↔ forall x in s, (x : M) = 0 :=
  eq_bot_iff.trans
⟨fun H _ h => (mem_bot R).1 H subset_span h, fun H =>
span_le.2 fun x h => (mem_bot R).2 H x h⟩

/--
theorem `span_singleton_eq_bot` / 定理 `span_singleton_eq_bot`

English:
theorem span_singleton_eq_bot
  statement: R ∙ x = ⊥ ↔ x = 0
  proof: by simp

@[simp]

中文:
定理 span_singleton_eq_bot
  结论: R ∙ x = ⊥ ↔ x = 0
  证明: by simp

@[simp]
-/
theorem span_singleton_eq_bot : R ∙ x = ⊥ ↔ x = 0 := by simp

@[simp]
/--
theorem `span_zero` / 定理 `span_zero`

English:
theorem span_zero
  statement: span R (0 : Set M) = ⊥
  proof: by rw [← singleton_zero, span_singleton_eq_bot]

@[simp]

中文:
定理 span_zero
  结论: span R (0 : 集合 M) = ⊥
  证明: by rw [← singleton_zero, span_singleton_eq_bot]

@[simp]

Depends on / 依赖: singleton_zero, span_singleton_eq_bot
-/
theorem span_zero : span R (0 : Set M) = ⊥ := by rw [← singleton_zero, span_singleton_eq_bot]

@[simp]
/--
theorem `span_singleton_le_iff_mem` / 定理 `span_singleton_le_iff_mem`

English:
theorem span_singleton_le_iff_mem
  given: (m : M) (p : Submodule R M)
  statement: R ∙ m <= p ↔ m in p
  proof: by
  rw [span_le]; rw [singleton_subset_iff]; rw [SetLike.mem_coe]

中文:
定理 span_singleton_le_iff_mem
  条件: (m : M) (p : 子模 R M)
  结论: R ∙ m <= p ↔ m in p
  证明: by
  rw [span_le]; rw [singleton_subset_iff]; rw [SetLike.mem_coe]

Depends on / 依赖: SetLike, SetLike.mem_coe, mem_coe, singleton_subset_iff, span_le
-/
theorem span_singleton_le_iff_mem (m : M) (p : Submodule R M) : R ∙ m <= p ↔ m in p := by
  rw [span_le]; rw [singleton_subset_iff]; rw [SetLike.mem_coe]

/--
theorem `iSup_span` / 定理 `iSup_span`

English:
theorem iSup_span
  given: {ι : Sort*} (p : ι -> Set M)
  statement: ⨆ i, span R (p i) = span R (⋃ i, p i)
  proof: le_antisymm (iSup_le fun i => span_mono <| subset_iUnion _ i)
span_le.mpr iUnion_subset fun i _ hm => mem_iSup_of_mem i subset_span hm

中文:
定理 iSup_span
  条件: {ι : 类型层*} (p : ι -> 集合 M)
  结论: ⨆ i, span R (p i) = span R (⋃ i, p i)
  证明: le_antisymm (iSup_le fun i => span_mono <| subset_iUnion _ i)
span_le.mpr iUnion_subset fun i _ hm => mem_iSup_of_mem i subset_span hm

Depends on / 依赖: iSup_le, iUnion_subset, le_antisymm, mem_iSup_of_mem, span_le, span_le.mpr, span_mono, subset_iUnion, subset_span
-/
theorem iSup_span {ι : Sort*} (p : ι -> Set M) : ⨆ i, span R (p i) = span R (⋃ i, p i) :=
le_antisymm (iSup_le fun i => span_mono <| subset_iUnion _ i)
span_le.mpr iUnion_subset fun i _ hm => mem_iSup_of_mem i subset_span hm

/--
theorem `iSup_eq_span` / 定理 `iSup_eq_span`

English:
theorem iSup_eq_span
  given: {ι : Sort*} (p : ι -> Submodule R M)
  statement: ⨆ i, p i = span R (⋃ i, ↑(p i))
  proof: by
  simp_rw [← iSup_span, span_eq]

中文:
定理 iSup_eq_span
  条件: {ι : 类型层*} (p : ι -> 子模 R M)
  结论: ⨆ i, p i = span R (⋃ i, ↑(p i))
  证明: by
  simp_rw [← iSup_span, span_eq]

Depends on / 依赖: iSup_span, simp_rw, span_eq
-/
theorem iSup_eq_span {ι : Sort*} (p : ι -> Submodule R M) : ⨆ i, p i = span R (⋃ i, ↑(p i)) := by
  simp_rw [← iSup_span, span_eq]

/--
theorem `iSup_eq_span'` / 定理 `iSup_eq_span'`

English:
theorem iSup_eq_span'
  given: {ι : Sort*} (p : ι -> Submodule R M) (h : ι -> Prop)
  proof: by
  simp_rw [← Submodule.iSup_span, Submodule.span_eq]

中文:
定理 iSup_eq_span'
  条件: {ι : 类型层*} (p : ι -> 子模 R M) (h : ι -> 命题)
  证明: by
  simp_rw [← Submodule.iSup_span, Submodule.span_eq]

Depends on / 依赖: Submodule, Submodule.iSup_span, Submodule.span_eq, iSup_span, simp_rw, span_eq
-/
theorem iSup_eq_span' {ι : Sort*} (p : ι -> Submodule R M) (h : ι -> Prop) :
    (⨆ (i : ι) (_ : h i), p i) = Submodule.span R (⋃ (i : ι) (_ : h i), ↑(p i)) := by
  simp_rw [← Submodule.iSup_span, Submodule.span_eq]

/--
theorem `submodule_eq_sSup_le_nonzero_spans` / 定理 `submodule_eq_sSup_le_nonzero_spans`

English:
theorem submodule_eq_sSup_le_nonzero_spans
  given: (p : Submodule R M)
  proof: by
  let S := { T : Submodule R M | exists m in p, m != 0 ∧ T = span R {m} }
  apply le_antisymm
  · intro m hm
    by_cases h : m = 0
    · rw [h]
      simp
    · exact @le_sSup _ _ S _ ⟨m, ⟨hm, ⟨h, rfl⟩⟩⟩ m (mem_span_singleton_self m)
  · rw [sSup_le_iff]
    rintro S ⟨_, ⟨_, ⟨_, rfl⟩⟩⟩
    rwa [

中文:
定理 submodule_eq_sSup_le_nonzero_spans
  条件: (p : 子模 R M)
  证明: by
  let S := { T : Submodule R M | exists m in p, m != 0 ∧ T = span R {m} }
  apply le_antisymm
  · intro m hm
    by_cases h : m = 0
    · rw [h]
      simp
    · exact @le_sSup _ _ S _ ⟨m, ⟨hm, ⟨h, rfl⟩⟩⟩ m (mem_span_singleton_self m)
  · rw [sSup_le_iff]
    rintro S ⟨_, ⟨_, ⟨_, rfl⟩⟩⟩
    rwa [

Depends on / 依赖: Submodule, le_antisymm, le_sSup, mem_span_singleton_self, sSup_le_iff, span_singleton_le_iff_mem
-/
theorem submodule_eq_sSup_le_nonzero_spans (p : Submodule R M) :
    p = sSup { T : Submodule R M | exists m in p, m != 0 ∧ T = span R {m} } := by
  let S := { T : Submodule R M | exists m in p, m != 0 ∧ T = span R {m} }
  apply le_antisymm
  · intro m hm
    by_cases h : m = 0
    · rw [h]
      simp
    · exact @le_sSup _ _ S _ ⟨m, ⟨hm, ⟨h, rfl⟩⟩⟩ m (mem_span_singleton_self m)
  · rw [sSup_le_iff]
    rintro S ⟨_, ⟨_, ⟨_, rfl⟩⟩⟩
    rwa [span_singleton_le_iff_mem]

/--
theorem `lt_sup_iff_notMem` / 定理 `lt_sup_iff_notMem`

English:
theorem lt_sup_iff_notMem
  given: {I : Submodule R M} {a : M}
  statement: I < I ⊔ R ∙ a ↔ a ∉ I
  proof: by simp

中文:
定理 lt_sup_iff_notMem
  条件: {I : 子模 R M} {a : M}
  结论: I < I ⊔ R ∙ a ↔ a ∉ I
  证明: by simp
-/
theorem lt_sup_iff_notMem {I : Submodule R M} {a : M} : I < I ⊔ R ∙ a ↔ a ∉ I := by simp

/--
theorem `mem_iSup` / 定理 `mem_iSup`

English:
theorem mem_iSup
  given: {ι : Sort*} (p : ι -> Submodule R M) {m : M}
  proof: by
  rw [← span_singleton_le_iff_mem]; rw [le_iSup_iff]
  simp only [span_singleton_le_iff_mem]

中文:
定理 mem_iSup
  条件: {ι : 类型层*} (p : ι -> 子模 R M) {m : M}
  证明: by
  rw [← span_singleton_le_iff_mem]; rw [le_iSup_iff]
  simp only [span_singleton_le_iff_mem]

Depends on / 依赖: le_iSup_iff, span_singleton_le_iff_mem
-/
theorem mem_iSup {ι : Sort*} (p : ι -> Submodule R M) {m : M} :
    (m in ⨆ i, p i) ↔ forall N, (forall i, p i <= N) -> m in N := by
  rw [← span_singleton_le_iff_mem]; rw [le_iSup_iff]
  simp only [span_singleton_le_iff_mem]

/--
theorem `mem_sSup` / 定理 `mem_sSup`

English:
theorem mem_sSup
  given: {s : Set (Submodule R M)} {m : M}
  proof: by
  simp_rw [sSup_eq_iSup, Submodule.mem_iSup, iSup_le_iff]

中文:
定理 mem_sSup
  条件: {s : 集合 (子模 R M)} {m : M}
  证明: by
  simp_rw [sSup_eq_iSup, Submodule.mem_iSup, iSup_le_iff]

Depends on / 依赖: Submodule, Submodule.mem_iSup, iSup_le_iff, mem_iSup, sSup_eq_iSup, simp_rw
-/
theorem mem_sSup {s : Set (Submodule R M)} {m : M} :
    (m in sSup s) ↔ forall N, (forall p in s, p <= N) -> m in N := by
  simp_rw [sSup_eq_iSup, Submodule.mem_iSup, iSup_le_iff]

section

/--
theorem `mem_span_finite_of_mem_span` / 定理 `mem_span_finite_of_mem_span`

English:
theorem mem_span_finite_of_mem_span
  given: {S : Set M} {x : M} (hx : x in span R S)
  proof: by
  classical
  refine span_induction (fun x hx => ?_) ?_ ?_ ?_ hx
  · refine ⟨{x}, ?_, ?_⟩
    · rwa [Finset.coe_singleton, Set.singleton_subset_iff]
    · rw [Finset.coe_singleton]
      exact Submodule.mem_span_singleton_self x
  · use ∅
    simp
  · rintro x y - - ⟨X, hX, hxX⟩ ⟨Y, hY, hyY⟩
    

中文:
定理 mem_span_finite_of_mem_span
  条件: {S : 集合 M} {x : M} (hx : x in span R S)
  证明: by
  classical
  refine span_induction (fun x hx => ?_) ?_ ?_ ?_ hx
  · refine ⟨{x}, ?_, ?_⟩
    · rwa [Finset.coe_singleton, Set.singleton_subset_iff]
    · rw [Finset.coe_singleton]
      exact Submodule.mem_span_singleton_self x
  · use ∅
    simp
  · rintro x y - - ⟨X, hX, hxX⟩ ⟨Y, hY, hyY⟩
    

Depends on / 依赖: Finset, Finset.coe_singleton, Finset.coe_union, Set.singleton_subset_iff, Set.union_subset, Submodule, Submodule.mem_span_singleton_self, classical, coe_singleton, coe_union, mem_span_singleton_self, mem_sup, singleton_subset_iff, smul_mem, span_induction, span_union, union_subset
-/
theorem mem_span_finite_of_mem_span {S : Set M} {x : M} (hx : x in span R S) :
    exists T : Finset M, ↑T subseteq S ∧ x in span R (T : Set M) := by
  classical
  refine span_induction (fun x hx => ?_) ?_ ?_ ?_ hx
  · refine ⟨{x}, ?_, ?_⟩
    · rwa [Finset.coe_singleton, Set.singleton_subset_iff]
    · rw [Finset.coe_singleton]
      exact Submodule.mem_span_singleton_self x
  · use ∅
    simp
  · rintro x y - - ⟨X, hX, hxX⟩ ⟨Y, hY, hyY⟩
    refine ⟨X union Y, ?_, ?_⟩
    · rw [Finset.coe_union]
      exact Set.union_subset hX hY
    rw [Finset.coe_union]; rw [span_union]; rw [mem_sup]
    exact ⟨x, hxX, y, hyY, rfl⟩
  · rintro a x - ⟨T, hT, h2⟩
    exact ⟨T, hT, smul_mem _ _ h2⟩

/--
theorem `subset_span_finite_of_subset_span` / 定理 `subset_span_finite_of_subset_span`

English:
theorem subset_span_finite_of_subset_span
  given: {s : Set M} {t : Finset M} (ht : (t : Set M) subseteq span R s)
  proof: by
  classical
  induction t using Finset.induction_on with
  | empty => exact ⟨∅, by simp⟩
  | insert a t hat IH =>
    obtain ⟨T, hTs, htT⟩ := IH (by simp_all [Set.insert_subset_iff])
    obtain ⟨T', hT's, haT'⟩ := mem_span_finite_of_mem_span (ht (Finset.mem_insert_self _ _))
    refine ⟨T union T

中文:
定理 subset_span_finite_of_subset_span
  条件: {s : 集合 M} {t : 有限集 M} (ht : (t : 集合 M) subseteq span R s)
  证明: by
  classical
  induction t using Finset.induction_on with
  | empty => exact ⟨∅, by simp⟩
  | insert a t hat IH =>
    obtain ⟨T, hTs, htT⟩ := IH (by simp_all [Set.insert_subset_iff])
    obtain ⟨T', hT's, haT'⟩ := mem_span_finite_of_mem_span (ht (Finset.mem_insert_self _ _))
    refine ⟨T union T

Depends on / 依赖: Finset, Finset.coe_insert, Finset.coe_union, Finset.induction_on, Finset.mem_insert_self, Set.insert_subset_iff, SetLike, SetLike.mem_coe, classical, coe_insert, coe_union, htT.trans, induction_on, insert, insert_subset_iff, le_sup_left, mem_coe, mem_insert_self, mem_span_finite_of_mem_span, mem_sup_right
-/
theorem subset_span_finite_of_subset_span {s : Set M} {t : Finset M} (ht : (t : Set M) subseteq span R s) :
    exists T : Finset M, ↑T subseteq s ∧ (t : Set M) subseteq span R (T : Set M) := by
  classical
  induction t using Finset.induction_on with
  | empty => exact ⟨∅, by simp⟩
  | insert a t hat IH =>
    obtain ⟨T, hTs, htT⟩ := IH (by simp_all [Set.insert_subset_iff])
    obtain ⟨T', hT's, haT'⟩ := mem_span_finite_of_mem_span (ht (Finset.mem_insert_self _ _))
    refine ⟨T union T', by simp_all, ?_⟩
    simp only [Finset.coe_insert, Finset.coe_union, span_union, insert_subset_iff, SetLike.mem_coe]
    exact ⟨mem_sup_right haT', htT.trans (le_sup_left (a := span R _))⟩

end

end AddCommMonoid

section AddCommGroup

variable [Ring R] [AddCommGroup M] [Module R M] {ι : Type*} [DecidableEq ι] {i j : ι}

/--
lemma `sup_toAddSubgroup` / 引理 `sup_toAddSubgroup`

English:
lemma sup_toAddSubgroup
  given: (p p' : Submodule R M)
  proof: by
  ext x
  rw [mem_toAddSubgroup]; rw [mem_sup]; rw [AddSubgroup.mem_sup]
  rfl

中文:
引理 sup_toAddSubgroup
  条件: (p p' : 子模 R M)
  证明: by
  ext x
  rw [mem_toAddSubgroup]; rw [mem_sup]; rw [AddSubgroup.mem_sup]
  rfl

Depends on / 依赖: AddSubgroup, AddSubgroup.mem_sup, mem_sup, mem_toAddSubgroup
-/
lemma sup_toAddSubgroup (p p' : Submodule R M) :
    (p ⊔ p').toAddSubgroup = p.toAddSubgroup ⊔ p'.toAddSubgroup := by
  ext x
  rw [mem_toAddSubgroup]; rw [mem_sup]; rw [AddSubgroup.mem_sup]
  rfl

/--
theorem `mem_span_insert'` / 定理 `mem_span_insert'`

English:
theorem mem_span_insert'
  given: {x y} {s : Set M}
  proof: by
  rw [mem_span_insert]; constructor
  · rintro ⟨a, z, hz, rfl⟩
    exact ⟨-a, by simp [hz, add_assoc]⟩
  · rintro ⟨a, h⟩
    exact ⟨-a, _, h, by simp [add_comm]⟩

中文:
定理 mem_span_insert'
  条件: {x y} {s : 集合 M}
  证明: by
  rw [mem_span_insert]; constructor
  · rintro ⟨a, z, hz, rfl⟩
    exact ⟨-a, by simp [hz, add_assoc]⟩
  · rintro ⟨a, h⟩
    exact ⟨-a, _, h, by simp [add_comm]⟩

Depends on / 依赖: add_assoc, add_comm, mem_span_insert
-/
theorem mem_span_insert' {x y} {s : Set M} :
    x in span R (insert y s) ↔ exists a : R, x + a • y in span R s := by
  rw [mem_span_insert]; constructor
  · rintro ⟨a, z, hz, rfl⟩
    exact ⟨-a, by simp [hz, add_assoc]⟩
  · rintro ⟨a, h⟩
    exact ⟨-a, _, h, by simp [add_comm]⟩

/--
lemma `span_range_update_add_smul` / 引理 `span_range_update_add_smul`

English:
lemma span_range_update_add_smul
  given: (hij : i != j) (v : ι -> M) (r : R)
  proof: by
  refine le_antisymm ?_ ?_ <;> simp only [span_le, Set.range_subset_iff, SetLike.mem_coe] <;>
    intro k <;> obtain rfl | hjk := eq_or_ne j k
  · rw [update_self]
exact add_mem (subset_span ⟨j, rfl⟩) smul_mem _ _ subset_span ⟨i, rfl⟩
  · exact subset_span ⟨k, (update_of_ne hjk.symm ..).symm⟩
  ·

中文:
引理 span_range_update_add_smul
  条件: (hij : i != j) (v : ι -> M) (r : R)
  证明: by
  refine le_antisymm ?_ ?_ <;> simp only [span_le, Set.range_subset_iff, SetLike.mem_coe] <;>
    intro k <;> obtain rfl | hjk := eq_or_ne j k
  · rw [update_self]
exact add_mem (subset_span ⟨j, rfl⟩) smul_mem _ _ subset_span ⟨i, rfl⟩
  · exact subset_span ⟨k, (update_of_ne hjk.symm ..).symm⟩
  ·

Depends on / 依赖: Set.range_subset_iff, SetLike, SetLike.mem_coe, add_mem, add_sub_cancel_right, eq_or_ne, hjk.symm, le_antisymm, mem_coe, nth_rw, range_subset_iff, smul_mem, span_le, sub_mem, subset_span, update_of_ne, update_self
-/
lemma span_range_update_add_smul (hij : i != j) (v : ι -> M) (r : R) :
    span R (Set.range (Function.update v j (v j + r • v i))) = span R (Set.range v) := by
  refine le_antisymm ?_ ?_ <;> simp only [span_le, Set.range_subset_iff, SetLike.mem_coe] <;>
    intro k <;> obtain rfl | hjk := eq_or_ne j k
  · rw [update_self]
exact add_mem (subset_span ⟨j, rfl⟩) smul_mem _ _ subset_span ⟨i, rfl⟩
  · exact subset_span ⟨k, (update_of_ne hjk.symm ..).symm⟩
  · nth_rw 2 [← add_sub_cancel_right (v j) (r • v i)]
    exact sub_mem (subset_span ⟨j, update_self ..⟩)
      (smul_mem _ _ (subset_span ⟨i, update_of_ne hij ..⟩))
  · exact subset_span ⟨k, update_of_ne hjk.symm ..⟩

/--
lemma `span_range_update_sub_smul` / 引理 `span_range_update_sub_smul`

English:
lemma span_range_update_sub_smul
  given: (hij : i != j) (v : ι -> M) (r : R)
  proof: by
  rw [sub_eq_add_neg]; rw [← neg_smul]; rw [span_range_update_add_smul hij]

中文:
引理 span_range_update_sub_smul
  条件: (hij : i != j) (v : ι -> M) (r : R)
  证明: by
  rw [sub_eq_add_neg]; rw [← neg_smul]; rw [span_range_update_add_smul hij]

Depends on / 依赖: neg_smul, span_range_update_add_smul, sub_eq_add_neg
-/
lemma span_range_update_sub_smul (hij : i != j) (v : ι -> M) (r : R) :
    span R (Set.range (Function.update v j (v j - r • v i))) = span R (Set.range v) := by
  rw [sub_eq_add_neg]; rw [← neg_smul]; rw [span_range_update_add_smul hij]

end AddCommGroup

end Submodule

variable (R M) [Semiring R] [AddCommMonoid M] [Module R M] [AddCommMonoid M₂] [Module R M₂]

/--
Definition of `Module.IsPrincipal` / `Module.IsPrincipal` 的定义

English:
abbreviation Module.IsPrincipal
  body: (⊤ : Submodule R M).IsPrincipal

中文:
缩写 模.是Principal
  定义体: (⊤ : Submodule R M).IsPrincipal

Depends on / 依赖: IsPrincipal, Submodule
-/
abbrev Module.IsPrincipal := (⊤ : Submodule R M).IsPrincipal

variable {R M}

/--
theorem `Module.isPrincipal_def` / 定理 `Module.isPrincipal_def`

English:
theorem Module.isPrincipal_def
  statement: IsPrincipal R M ↔ (⊤ : Submodule R M).IsPrincipal
  proof: .rfl

中文:
定理 模.isPrincipal_def
  结论: 是Principal R M ↔ (⊤ : 子模 R M).是Principal
  证明: .rfl
-/
theorem Module.isPrincipal_def : IsPrincipal R M ↔ (⊤ : Submodule R M).IsPrincipal := .rfl

open Submodule

/--
theorem `Module.isPrincipal_submodule_iff` / 定理 `Module.isPrincipal_submodule_iff`

English:
theorem Module.isPrincipal_submodule_iff
  given: {p : Submodule R M}
  proof: by
  simp_rw [IsPrincipal, isPrincipal_iff]
  constructor <;> rintro ⟨a, ha⟩
· refine ⟨a, le_antisymm (fun m hm => ?_) (span_singleton_le_iff_mem ..).mpr a.2⟩
    have ⟨r, hr⟩ := mem_span_singleton.mp (ha ▸ (trivial : (⟨m, hm⟩ : p) in ⊤))
    exact mem_span_singleton.mpr ⟨r, congr($hr)⟩
· refine ⟨⟨a

中文:
定理 模.isPrincipal_submodule_iff
  条件: {p : 子模 R M}
  证明: by
  simp_rw [IsPrincipal, isPrincipal_iff]
  constructor <;> rintro ⟨a, ha⟩
· refine ⟨a, le_antisymm (fun m hm => ?_) (span_singleton_le_iff_mem ..).mpr a.2⟩
    have ⟨r, hr⟩ := mem_span_singleton.mp (ha ▸ (trivial : (⟨m, hm⟩ : p) in ⊤))
    exact mem_span_singleton.mpr ⟨r, congr($hr)⟩
· refine ⟨⟨a

Depends on / 依赖: IsPrincipal, Subtype, Subtype.ext, ha.le, isPrincipal_iff, le_antisymm, mem_span_singleton, mem_span_singleton.mp, mem_span_singleton.mpr, mem_span_singleton_self, simp_rw, span_singleton_le_iff_mem, top_unique
-/
theorem Module.isPrincipal_submodule_iff {p : Submodule R M} :
    IsPrincipal R p ↔ p.IsPrincipal := by
  simp_rw [IsPrincipal, isPrincipal_iff]
  constructor <;> rintro ⟨a, ha⟩
· refine ⟨a, le_antisymm (fun m hm => ?_) (span_singleton_le_iff_mem ..).mpr a.2⟩
    have ⟨r, hr⟩ := mem_span_singleton.mp (ha ▸ (trivial : (⟨m, hm⟩ : p) in ⊤))
    exact mem_span_singleton.mpr ⟨r, congr($hr)⟩
· refine ⟨⟨a, ha ▸ mem_span_singleton_self a⟩, .symm top_unique fun x _ => ?_⟩
    have ⟨r, hr⟩ := mem_span_singleton.mp (ha.le x.2)
    exact mem_span_singleton.mpr ⟨r, Subtype.ext hr⟩

set_option backward.isDefEq.respectTransparency false in
/--
theorem `Module.IsPrincipal.of_surjective` / 定理 `Module.IsPrincipal.of_surjective`

English:
theorem Module.IsPrincipal.of_surjective
  statement: (f : M ->ₗ[R] M₂) (hf : Function.Surjective f)
  proof: by
    have ⟨m, hm⟩ := IsPrincipal.principal (⊤ : Submodule R M)
refine ⟨f m, .symm top_unique fun y _ => ?_⟩
    obtain ⟨x, rfl⟩ := hf y
    obtain ⟨r, rfl⟩ := mem_span_singleton.mp (hm.le (trivial : x in ⊤))
    simpa only [map_smul] using smul_mem _ r (mem_span_singleton_self _)

中文:
定理 模.是Principal.of_surjective
  结论: (f : M ->ₗ[R] M₂) (hf : 函数.满射 f)
  证明: by
    have ⟨m, hm⟩ := IsPrincipal.principal (⊤ : Submodule R M)
refine ⟨f m, .symm top_unique fun y _ => ?_⟩
    obtain ⟨x, rfl⟩ := hf y
    obtain ⟨r, rfl⟩ := mem_span_singleton.mp (hm.le (trivial : x in ⊤))
    simpa only [map_smul] using smul_mem _ r (mem_span_singleton_self _)

Depends on / 依赖: IsPrincipal, IsPrincipal.principal, Submodule, hm.le, map_smul, mem_span_singleton, mem_span_singleton.mp, mem_span_singleton_self, principal, smul_mem, top_unique
-/
theorem Module.IsPrincipal.of_surjective (f : M ->ₗ[R] M₂) (hf : Function.Surjective f)
    [IsPrincipal R M] : IsPrincipal R M₂ where
  principal := by
    have ⟨m, hm⟩ := IsPrincipal.principal (⊤ : Submodule R M)
refine ⟨f m, .symm top_unique fun y _ => ?_⟩
    obtain ⟨x, rfl⟩ := hf y
    obtain ⟨r, rfl⟩ := mem_span_singleton.mp (hm.le (trivial : x in ⊤))
    simpa only [map_smul] using smul_mem _ r (mem_span_singleton_self _)

/--
theorem `LinearEquiv.isPrincipal_iff` / 定理 `LinearEquiv.isPrincipal_iff`

English:
theorem LinearEquiv.isPrincipal_iff
  given: (e : M ≃ₗ[R] M₂)
  proof: (·.of_surjective _ e.surjective)
  mpr := (·.of_surjective _ e.symm.surjective)

中文:
定理 线性等价.isPrincipal_iff
  条件: (e : M ≃ₗ[R] M₂)
  证明: (·.of_surjective _ e.surjective)
  mpr := (·.of_surjective _ e.symm.surjective)

Depends on / 依赖: e.surjective, of_surjective, surjective
-/
theorem LinearEquiv.isPrincipal_iff (e : M ≃ₗ[R] M₂) :
    Module.IsPrincipal R M ↔ Module.IsPrincipal R M₂ where
  mp := (·.of_surjective _ e.surjective)
  mpr := (·.of_surjective _ e.symm.surjective)

section NonUnitalAlgebra

open Submodule

variable {R A : Type*} [Semiring R] [NonUnitalNonAssocSemiring A] [Module R A]
  [IsScalarTower R A A] [SMulCommClass R A A]

/--
theorem `Commute.span_left` / 定理 `Commute.span_left`

English:
theorem Commute.span_left
  given: {s : Set A} {x : A} (h : forall y in s, Commute y x)
  proof: by
  intro y hy
  induction hy using span_induction with
  | mem _ _ => aesop
  | zero => exact .zero_left _
  | add _ _ _ _ h₁ h₂ => exact h₁.add_left h₂
  | smul _ _ _ h => exact h.smul_left _

中文:
定理 Commute.span_left
  条件: {s : 集合 A} {x : A} (h : 对任意 y in s, Commute y x)
  证明: by
  intro y hy
  induction hy using span_induction with
  | mem _ _ => aesop
  | zero => exact .zero_left _
  | add _ _ _ _ h₁ h₂ => exact h₁.add_left h₂
  | smul _ _ _ h => exact h.smul_left _

Depends on / 依赖: add_left, h.smul_left, smul_left, span_induction, zero_left
-/
theorem Commute.span_left {s : Set A} {x : A} (h : forall y in s, Commute y x) :
    forall y in span R s, Commute y x := by
  intro y hy
  induction hy using span_induction with
  | mem _ _ => aesop
  | zero => exact .zero_left _
  | add _ _ _ _ h₁ h₂ => exact h₁.add_left h₂
  | smul _ _ _ h => exact h.smul_left _

/--
theorem `Commute.span_right` / 定理 `Commute.span_right`

English:
theorem Commute.span_right
  given: {s : Set A} {x : A} (h : forall y in s, Commute x y)
  proof: by
  simp only [Commute.symm_iff (a := x)] at *
  exact .span_left h

中文:
定理 Commute.span_right
  条件: {s : 集合 A} {x : A} (h : 对任意 y in s, Commute x y)
  证明: by
  simp only [Commute.symm_iff (a := x)] at *
  exact .span_left h

Depends on / 依赖: Commute, Commute.symm_iff, span_left, symm_iff
-/
theorem Commute.span_right {s : Set A} {x : A} (h : forall y in s, Commute x y) :
    forall y in span R s, Commute x y := by
  simp only [Commute.symm_iff (a := x)] at *
  exact .span_left h

end NonUnitalAlgebra
