/-
Copyright (c) 2020 Kenny Lau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau
-/
module

public import Mathlib.Data.Multiset.Fintype
public import Mathlib.FieldTheory.IsAlgClosed.Basic
public import Mathlib.FieldTheory.SplittingField.Construction

/-!
# Algebraic Closure

In this file we construct the algebraic closure of a field

## Main Definitions

- `AlgebraicClosure k` is an algebraic closure of `k` (in the same universe).
  It is constructed by taking the polynomial ring generated by indeterminates
  $X_{f,1}, \dots, X_{f,\deg f}$ corresponding to roots of monic irreducible
  polynomials `f` with coefficients in `k`, and quotienting out by a maximal
  ideal containing every $f - \prod_i (X - X_{f,i})$. The proof follows
  https://kconrad.math.uconn.edu/blurbs/galoistheory/algclosureshorter.pdf.

## Tags

algebraic closure, algebraically closed
-/

@[expose] public section

universe u v w

noncomputable section

open Polynomial

variable (k : Type u) [Field k]

namespace AlgebraicClosure

/--
Definition of `Monics` / `Monics` 的定义

English:
definition Monics
  signature: : Type u
  body: {f : k[X] // f.Monic}

中文:
定义 Monics
  签名: : 类型u
  定义体: {f : k[X] // f.Monic}

Depends on / 依赖: f.Monic
-/
def Monics : Type u := {f : k[X] // f.Monic}

/--
Definition of `Vars` / `Vars` 的定义

English:
definition Vars
  signature: : Type u
  body: Σ f : Monics k, Fin f.1.natDegree

中文:
定义 Vars
  签名: : 类型u
  定义体: Σ f : Monics k, Fin f.1.natDegree

Depends on / 依赖: Monics, natDegree
-/
def Vars : Type u := Σ f : Monics k, Fin f.1.natDegree

variable {k} in
/--
Definition of `subProdXSubC` / `subProdXSubC` 的定义

English:
definition subProdXSubC
  signature: (f : Monics k)
  body: f.1.map (algebraMap _ _) - ∏ i : Fin f.1.natDegree, (X - C (MvPolynomial.X ⟨f, i⟩))

中文:
定义 subProdXSubC
  签名: (f : Monics k)
  定义体: f.1.map (algebraMap _ _) - ∏ i : Fin f.1.natDegree, (X - C (MvPolynomial.X ⟨f, i⟩))

Depends on / 依赖: MvPolynomial, MvPolynomial.X, algebraMap, natDegree
-/
def subProdXSubC (f : Monics k) : (MvPolynomial (Vars k) k)[X] :=
  f.1.map (algebraMap _ _) - ∏ i : Fin f.1.natDegree, (X - C (MvPolynomial.X ⟨f, i⟩))

/--
Definition of `spanCoeffs` / `spanCoeffs` 的定义

English:
definition spanCoeffs
  signature: : Ideal (MvPolynomial (Vars k) k)
  body: Ideal.span Set.range fun fn : Monics k × Nat => (subProdXSubC fn.1).coeff fn.2

中文:
定义 spanCoeffs
  签名: : 理想 (多元多项式 (Vars k) k)
  定义体: Ideal.span Set.range fun fn : Monics k × Nat => (subProdXSubC fn.1).coeff fn.2

Depends on / 依赖: Ideal.span, Monics, Set.range, subProdXSubC
-/
def spanCoeffs : Ideal (MvPolynomial (Vars k) k) :=
Ideal.span Set.range fun fn : Monics k × Nat => (subProdXSubC fn.1).coeff fn.2

variable {k}

/--
Definition of `finEquivRoots` / `finEquivRoots` 的定义

English:
definition finEquivRoots
  signature: {K} [Field K] [DecidableEq K] {i : k ->+* K} {f : Monics k}
  body: .symm Finset.equivFinOfCardEq by
    rwa [splits_iff_card_roots,
      ← Multiset.card_toEnumFinset, f.2.natDegree_map] at hf

中文:
定义 finEquivRoots
  签名: {K} [域 K] [DecidableEq K] {i : k ->+* K} {f : Monics k}
  定义体: .symm Finset.equivFinOfCardEq by
    rwa [splits_iff_card_roots,
      ← Multiset.card_toEnumFinset, f.2.natDegree_map] at hf

Depends on / 依赖: Finset, Finset.equivFinOfCardEq, Multiset, Multiset.card_toEnumFinset, card_toEnumFinset, equivFinOfCardEq, natDegree_map, splits_iff_card_roots
-/
def finEquivRoots {K} [Field K] [DecidableEq K] {i : k ->+* K} {f : Monics k}
    (hf : (f.1.map i).Splits) : Fin f.1.natDegree ≃ (f.1.map i).roots.toEnumFinset :=
.symm Finset.equivFinOfCardEq by
    rwa [splits_iff_card_roots,
      ← Multiset.card_toEnumFinset, f.2.natDegree_map] at hf

/--
lemma `Monics.splits_finsetProd` / 引理 `Monics.splits_finsetProd`

English:
lemma Monics.splits_finsetProd
  given: {s : Finset (Monics k)} {f : Monics k} (hf : f in s)
  proof: (splits_prod_iff fun j _ => map_ne_zero j.2.ne_zero).mp
    (by simpa [Polynomial.map_prod] using SplittingField.splits (∏ f in s, f.1)) f hf

中文:
引理 Monics.splits_finsetProd
  条件: {s : 有限集 (Monics k)} {f : Monics k} (hf : f in s)
  证明: (splits_prod_iff fun j _ => map_ne_zero j.2.ne_zero).mp
    (by simpa [Polynomial.map_prod] using SplittingField.splits (∏ f in s, f.1)) f hf

Depends on / 依赖: Polynomial, Polynomial.map_prod, SplittingField, SplittingField.splits, map_ne_zero, map_prod, ne_zero, splits, splits_prod_iff
-/
lemma Monics.splits_finsetProd {s : Finset (Monics k)} {f : Monics k} (hf : f in s) :
    (f.1.map (algebraMap k (SplittingField (∏ f in s, f.1)))).Splits :=
  (splits_prod_iff fun j _ => map_ne_zero j.2.ne_zero).mp
    (by simpa [Polynomial.map_prod] using SplittingField.splits (∏ f in s, f.1)) f hf

open scoped Classical in
/--
Definition of `toSplittingField` / `toSplittingField` 的定义

English:
definition toSplittingField
  signature: (s : Finset (Monics k))
  body: MvPolynomial.aeval fun fi =>
    if hf : fi.1 in s then (finEquivRoots (Monics.splits_finsetProd hf) fi.2).1.1 else 37

中文:
定义 toSplittingField
  签名: (s : 有限集 (Monics k))
  定义体: MvPolynomial.aeval fun fi =>
    if hf : fi.1 in s then (finEquivRoots (Monics.splits_finsetProd hf) fi.2).1.1 else 37

Depends on / 依赖: Monics, Monics.splits_finsetProd, MvPolynomial, MvPolynomial.aeval, finEquivRoots, splits_finsetProd
-/
def toSplittingField (s : Finset (Monics k)) :
    MvPolynomial (Vars k) k ->ₐ[k] SplittingField (∏ f in s, f.1) :=
  MvPolynomial.aeval fun fi =>
    if hf : fi.1 in s then (finEquivRoots (Monics.splits_finsetProd hf) fi.2).1.1 else 37

set_option backward.isDefEq.respectTransparency.types false in
/--
theorem `toSplittingField_coeff` / 定理 `toSplittingField_coeff`

English:
theorem toSplittingField_coeff
  given: {s : Finset (Monics k)} {f} (h : f in s) (n)
  proof: by
  classical
  simp_rw [← AlgHom.coe_toRingHom, ← coeff_map, subProdXSubC, Polynomial.map_sub,
    Polynomial.map_prod, Polynomial.map_sub, map_X, map_C, toSplittingField,
    AlgHom.coe_toRingHom, MvPolynomial.aeval_X, dif_pos h,
    ← (finEquivRoots (Monics.splits_finsetProd h)).symm.prod_comp, 

中文:
定理 toSplittingField_coeff
  条件: {s : 有限集 (Monics k)} {f} (h : f in s) (n)
  证明: by
  classical
  simp_rw [← AlgHom.coe_toRingHom, ← coeff_map, subProdXSubC, Polynomial.map_sub,
    Polynomial.map_prod, Polynomial.map_sub, map_X, map_C, toSplittingField,
    AlgHom.coe_toRingHom, MvPolynomial.aeval_X, dif_pos h,
    ← (finEquivRoots (Monics.splits_finsetProd h)).symm.prod_comp, 

Depends on / 依赖: AlgHom, AlgHom.coe_toRingHom, Equiv.apply_symm_apply, Finset, Finset.prod_coe_sort, Function, Function.comp_def, Monics, Monics.splits_finsetProd, Multiset, Multiset.map_map, Multiset.toEnumFinset, MvPolynomial, MvPolynomial.aeval_X, Polynomial, Polynomial.map_prod, Polynomial.map_sub, Prod.fst, aeval_X, apply_symm_apply
-/
theorem toSplittingField_coeff {s : Finset (Monics k)} {f} (h : f in s) (n) :
    toSplittingField s ((subProdXSubC f).coeff n) = 0 := by
  classical
  simp_rw [← AlgHom.coe_toRingHom, ← coeff_map, subProdXSubC, Polynomial.map_sub,
    Polynomial.map_prod, Polynomial.map_sub, map_X, map_C, toSplittingField,
    AlgHom.coe_toRingHom, MvPolynomial.aeval_X, dif_pos h,
    ← (finEquivRoots (Monics.splits_finsetProd h)).symm.prod_comp, Equiv.apply_symm_apply]
  rw [Finset.prod_coe_sort (f := fun x : _ × Nat => X - C x.1)]; rw [(Multiset.toEnumFinset _)
.prod_eq_multiset_prod]; rw [← Function.comp_def (X - C ·) Prod.fst]; rw [← Multiset.map_map]; rw [Multiset.map_toEnumFinset_fst]; rw [map_map]; rw [AlgHom.comp_algebraMap]
  conv in map _ _ => rw [Splits.eq_prod_roots (Monics.splits_finsetProd h)]
  rw [leadingCoeff_map]; rw [f.2]; rw [map_one]; rw [C_1]; rw [one_mul]; rw [sub_self]; rw [coeff_zero]

variable (k)

/--
theorem `spanCoeffs_ne_top` / 定理 `spanCoeffs_ne_top`

English:
theorem spanCoeffs_ne_top
  statement: spanCoeffs k != ⊤
  proof: by
  rw [Ideal.ne_top_iff_one]; rw [spanCoeffs]; rw [Ideal.span]; rw [← Set.image_univ]; rw [Finsupp.mem_span_image_iff_linearCombination]
  rintro ⟨v, _, hv⟩
  classical
  replace hv := congr_arg (toSplittingField <| v.support.image Prod.fst) hv
  rw [map_one]; rw [Finsupp.linearCombination_apply];

中文:
定理 spanCoeffs_ne_top
  结论: spanCoeffs k != ⊤
  证明: by
  rw [Ideal.ne_top_iff_one]; rw [spanCoeffs]; rw [Ideal.span]; rw [← Set.image_univ]; rw [Finsupp.mem_span_image_iff_linearCombination]
  rintro ⟨v, _, hv⟩
  classical
  replace hv := congr_arg (toSplittingField <| v.support.image Prod.fst) hv
  rw [map_one]; rw [Finsupp.linearCombination_apply];

Depends on / 依赖: Finset, Finset.mem_image_of_mem, Finset.sum_eq_zero, Finsupp, Finsupp.linearCombination_apply, Finsupp.mem_span_image_iff_linearCombination, Finsupp.sum, Ideal.ne_top_iff_one, Ideal.span, Prod.fst, Set.image_univ, classical, congr_arg, image_univ, linearCombination_apply, map_mul, map_one, map_sum, mem_image_of_mem, mem_span_image_iff_linearCombination
-/
theorem spanCoeffs_ne_top : spanCoeffs k != ⊤ := by
  rw [Ideal.ne_top_iff_one]; rw [spanCoeffs]; rw [Ideal.span]; rw [← Set.image_univ]; rw [Finsupp.mem_span_image_iff_linearCombination]
  rintro ⟨v, _, hv⟩
  classical
  replace hv := congr_arg (toSplittingField <| v.support.image Prod.fst) hv
  rw [map_one]; rw [Finsupp.linearCombination_apply]; rw [Finsupp.sum]; rw [map_sum]; rw [Finset.sum_eq_zero] at hv
  · exact zero_ne_one hv
  intro j hj
  rw [smul_eq_mul]; rw [map_mul]; rw [toSplittingField_coeff (Finset.mem_image_of_mem _ hj)]; rw [mul_zero]

/--
Definition of `maxIdeal` / `maxIdeal` 的定义

English:
definition maxIdeal
  signature: : Ideal (MvPolynomial (Vars k) k)
  body: Classical.choose Ideal.exists_le_maximal _ spanCoeffs_ne_top k

中文:
定义 maxIdeal
  签名: : 理想 (多元多项式 (Vars k) k)
  定义体: Classical.choose Ideal.exists_le_maximal _ spanCoeffs_ne_top k

Depends on / 依赖: Classical, Classical.choose, Ideal.exists_le_maximal, exists_le_maximal, spanCoeffs_ne_top
-/
def maxIdeal : Ideal (MvPolynomial (Vars k) k) :=
Classical.choose Ideal.exists_le_maximal _ spanCoeffs_ne_top k

/--
Instance `maxIdeal.isMaximal` / 实例 `maxIdeal.isMaximal`

English:
instance maxIdeal.isMaximal
  signature: : (maxIdeal k).IsMaximal
  body: (Classical.choose_spec <| Ideal.exists_le_maximal _ <| spanCoeffs_ne_top k).1

中文:
实例 maxIdeal.isMaximal
  签名: : (maxIdeal k).是极大
  定义体: (Classical.choose_spec <| Ideal.exists_le_maximal _ <| spanCoeffs_ne_top k).1

Depends on / 依赖: Classical, Classical.choose_spec, Ideal.exists_le_maximal, choose_spec, exists_le_maximal, spanCoeffs_ne_top
-/
instance maxIdeal.isMaximal : (maxIdeal k).IsMaximal :=
  (Classical.choose_spec <| Ideal.exists_le_maximal _ <| spanCoeffs_ne_top k).1

/--
theorem `le_maxIdeal` / 定理 `le_maxIdeal`

English:
theorem le_maxIdeal
  statement: spanCoeffs k <= maxIdeal k
  proof: (Classical.choose_spec <| Ideal.exists_le_maximal _ <| spanCoeffs_ne_top k).2

中文:
定理 le_maxIdeal
  结论: spanCoeffs k <= maxIdeal k
  证明: (Classical.choose_spec <| Ideal.exists_le_maximal _ <| spanCoeffs_ne_top k).2

Depends on / 依赖: Classical, Classical.choose_spec, Ideal.exists_le_maximal, choose_spec, exists_le_maximal, spanCoeffs_ne_top
-/
theorem le_maxIdeal : spanCoeffs k <= maxIdeal k :=
  (Classical.choose_spec <| Ideal.exists_le_maximal _ <| spanCoeffs_ne_top k).2

end AlgebraicClosure

open AlgebraicClosure in
/-- The canonical algebraic closure of a field, the direct limit of adding roots to the field for
each polynomial over the field. -/
@[stacks 09GT]
/--
Definition of `AlgebraicClosure` / `AlgebraicClosure` 的定义

English:
definition AlgebraicClosure
  signature: : Type u
  body: MvPolynomial (Vars k) k ⧸ maxIdeal k

中文:
定义 代数闭包
  签名: : 类型u
  定义体: MvPolynomial (Vars k) k ⧸ maxIdeal k

Depends on / 依赖: MvPolynomial, maxIdeal
-/
def AlgebraicClosure : Type u :=
  MvPolynomial (Vars k) k ⧸ maxIdeal k

namespace AlgebraicClosure

deriving instance Inhabited for AlgebraicClosure

instance {S : Type*} [DistribSMul S k] [IsScalarTower S k k] : SMul S (AlgebraicClosure k) :=
inferInstanceAs SMul S (_ ⧸ _)

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: CommRing (AlgebraicClosure k)
  body: letI := AlgebraicClosure.instSMulOfIsScalarTower k (S := Nat); (· • · )
  zsmul := letI := AlgebraicClosure.instSMulOfIsScalarTower k (S := Int); (· • · )
__ : CommRing (AlgebraicClosure k) := inferInstanceAs CommRing (_ ⧸ _)

中文:
实例 :
  签名: 交换环 (代数闭包 k)
  定义体: letI := AlgebraicClosure.instSMulOfIsScalarTower k (S := Nat); (· • · )
  zsmul := letI := AlgebraicClosure.instSMulOfIsScalarTower k (S := Int); (· • · )
__ : CommRing (AlgebraicClosure k) := inferInstanceAs CommRing (_ ⧸ _)

Depends on / 依赖: AlgebraicClosure, AlgebraicClosure.instSMulOfIsScalarTower, instSMulOfIsScalarTower
-/
instance : CommRing (AlgebraicClosure k) where
  nsmul := letI := AlgebraicClosure.instSMulOfIsScalarTower k (S := Nat); (· • · )
  zsmul := letI := AlgebraicClosure.instSMulOfIsScalarTower k (S := Int); (· • · )
__ : CommRing (AlgebraicClosure k) := inferInstanceAs CommRing (_ ⧸ _)

/--
Instance `instAlgebra` / 实例 `instAlgebra`

English:
instance instAlgebra
  signature: {R : Type*} [CommSemiring R] [Algebra R k]
  body: inferInstanceAs Algebra R (_ ⧸ _)

中文:
实例 instAlgebra
  签名: {R : 类型} [交换半环 R] [代数 R k]
  定义体: inferInstanceAs Algebra R (_ ⧸ _)

Depends on / 依赖: Algebra
-/
instance instAlgebra {R : Type*} [CommSemiring R] [Algebra R k] : Algebra R (AlgebraicClosure k) :=
inferInstanceAs Algebra R (_ ⧸ _)

instance {R S : Type*} [CommSemiring R] [CommSemiring S] [Algebra R S] [Algebra S k] [Algebra R k]
    [IsScalarTower R S k] : IsScalarTower R S (AlgebraicClosure k) :=
inferInstanceAs IsScalarTower R S (_ ⧸ _)

attribute [local instance] Ideal.Quotient.field in
/--
Instance `instGroupWithZero` / 实例 `instGroupWithZero`

English:
instance instGroupWithZero
  signature: : GroupWithZero (AlgebraicClosure k)
  body: inferInstanceAs GroupWithZero (_ ⧸ _)

中文:
实例 instGroupWithZero
  签名: : 带零群 (代数闭包 k)
  定义体: inferInstanceAs GroupWithZero (_ ⧸ _)

Depends on / 依赖: GroupWithZero
-/
instance instGroupWithZero : GroupWithZero (AlgebraicClosure k) :=
inferInstanceAs GroupWithZero (_ ⧸ _)

/--
Instance `instField` / 实例 `instField`

English:
instance instField
  signature: : Field (AlgebraicClosure k) where
  body: instCommRing _
  __ := instGroupWithZero _
  nnqsmul := (· • ·)
  qsmul := (· • ·)
  nnratCast q := algebraMap k _ q
  ratCast q := algebraMap k _ q
  nnratCast_def q := by change algebraMap k _ _ = _; simp_rw [NNRat.cast_def, map_div₀, map_natCast]
  ratCast_def q := by
    change algebraMap k _ _ 

中文:
实例 instField
  签名: : 域 (代数闭包 k) where
  定义体: instCommRing _
  __ := instGroupWithZero _
  nnqsmul := (· • ·)
  qsmul := (· • ·)
  nnratCast q := algebraMap k _ q
  ratCast q := algebraMap k _ q
  nnratCast_def q := by change algebraMap k _ _ = _; simp_rw [NNRat.cast_def, map_div₀, map_natCast]
  ratCast_def q := by
    change algebraMap k _ _ 

Depends on / 依赖: instCommRing
-/
instance instField : Field (AlgebraicClosure k) where
  __ := instCommRing _
  __ := instGroupWithZero _
  nnqsmul := (· • ·)
  qsmul := (· • ·)
  nnratCast q := algebraMap k _ q
  ratCast q := algebraMap k _ q
  nnratCast_def q := by change algebraMap k _ _ = _; simp_rw [NNRat.cast_def, map_div₀, map_natCast]
  ratCast_def q := by
    change algebraMap k _ _ = _; rw [Rat.cast_def, map_div₀, map_intCast, map_natCast]
nnqsmul_def q x := Quotient.inductionOn x fun p => congr_arg Quotient.mk'' by
    ext; simp [MvPolynomial.algebraMap_eq, NNRat.smul_def]
qsmul_def q x := Quotient.inductionOn x fun p => congr_arg Quotient.mk'' by
    ext; simp [MvPolynomial.algebraMap_eq, Rat.smul_def]

set_option backward.isDefEq.respectTransparency false in
/--
theorem `Monics.map_eq_prod` / 定理 `Monics.map_eq_prod`

English:
theorem Monics.map_eq_prod
  given: {f : Monics k}
  proof: by
  ext
  dsimp [AlgebraicClosure]
  rw [← Ideal.Quotient.mk_comp_algebraMap]; rw [← map_map]; rw [← Polynomial.map_prod]; rw [← sub_eq_zero]; rw [← coeff_sub]; rw [← Polynomial.map_sub]; rw [← subProdXSubC]; rw [coeff_map]; rw [Ideal.Quotient.eq_zero_iff_mem]
  refine le_maxIdeal _ (Ideal.subset_s

中文:
定理 Monics.map_eq_prod
  条件: {f : Monics k}
  证明: by
  ext
  dsimp [AlgebraicClosure]
  rw [← Ideal.Quotient.mk_comp_algebraMap]; rw [← map_map]; rw [← Polynomial.map_prod]; rw [← sub_eq_zero]; rw [← coeff_sub]; rw [← Polynomial.map_sub]; rw [← subProdXSubC]; rw [coeff_map]; rw [Ideal.Quotient.eq_zero_iff_mem]
  refine le_maxIdeal _ (Ideal.subset_s

Depends on / 依赖: AlgebraicClosure, Ideal.Quotient.eq_zero_iff_mem, Ideal.Quotient.mk_comp_algebraMap, Ideal.subset_span, Polynomial, Polynomial.map_prod, Polynomial.map_sub, Quotient, coeff_map, coeff_sub, eq_zero_iff_mem, le_maxIdeal, map_map, map_prod, map_sub, mk_comp_algebraMap, subProdXSubC, sub_eq_zero, subset_span
-/
theorem Monics.map_eq_prod {f : Monics k} :
    f.1.map (algebraMap k (AlgebraicClosure k)) =
      ∏ i, map (Ideal.Quotient.mk <| maxIdeal k) (X - C (MvPolynomial.X ⟨f, i⟩)) := by
  ext
  dsimp [AlgebraicClosure]
  rw [← Ideal.Quotient.mk_comp_algebraMap]; rw [← map_map]; rw [← Polynomial.map_prod]; rw [← sub_eq_zero]; rw [← coeff_sub]; rw [← Polynomial.map_sub]; rw [← subProdXSubC]; rw [coeff_map]; rw [Ideal.Quotient.eq_zero_iff_mem]
  refine le_maxIdeal _ (Ideal.subset_span ⟨⟨f, _⟩, rfl⟩)

set_option backward.isDefEq.respectTransparency false in
/--
Instance `isAlgebraic` / 实例 `isAlgebraic`

English:
instance isAlgebraic
  signature: : Algebra.IsAlgebraic k (AlgebraicClosure k)
  body: ⟨fun z =>
IsIntegral.isAlgebraic by
      let ⟨p, hp⟩ := Ideal.Quotient.mk_surjective z
      rw [← hp]
      induction p using MvPolynomial.induction_on generalizing z with
        | C => exact isIntegral_algebraMap
        | add _ _ ha hb => exact (ha _ rfl).add (hb _ rfl)
        | mul_X p fi ih 

中文:
实例 isAlgebraic
  签名: : 代数.是代数 k (代数闭包 k)
  定义体: ⟨fun z =>
IsIntegral.isAlgebraic by
      let ⟨p, hp⟩ := Ideal.Quotient.mk_surjective z
      rw [← hp]
      induction p using MvPolynomial.induction_on generalizing z with
        | C => exact isIntegral_algebraMap
        | add _ _ ha hb => exact (ha _ rfl).add (hb _ rfl)
        | mul_X p fi ih 

Depends on / 依赖: Finset, Finset.mem_univ, Finset.prod_eq_zero, Ideal.Quotient.mk_surjective, IsIntegral, IsIntegral.isAlgebraic, Monics, Monics.map_eq_prod, MvPolynomial, MvPolynomial.induction_on, Polynomial, Polynomial.map_sub, Quotient, eval_map, eval_prod, eval_sub, generalizing, induction_on, isAlgebraic, isIntegral_algebraMap
-/
instance isAlgebraic : Algebra.IsAlgebraic k (AlgebraicClosure k) :=
  ⟨fun z =>
IsIntegral.isAlgebraic by
      let ⟨p, hp⟩ := Ideal.Quotient.mk_surjective z
      rw [← hp]
      induction p using MvPolynomial.induction_on generalizing z with
        | C => exact isIntegral_algebraMap
        | add _ _ ha hb => exact (ha _ rfl).add (hb _ rfl)
        | mul_X p fi ih =>
          rw [map_mul]
          refine (ih _ rfl).mul ⟨_, fi.1.2, ?_⟩
          simp_rw [← eval_map, Monics.map_eq_prod, eval_prod, Polynomial.map_sub, eval_sub]
          apply Finset.prod_eq_zero (Finset.mem_univ fi.2)
          rw [map_C]
          -- The `erw` is needed here because the `R` in `eval` is `AlgebraicClosure k`,
          -- but this has been unfolded in the arguments of `eval`.
          erw [eval_C]
          simp⟩

set_option backward.isDefEq.respectTransparency.types false in
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: IsAlgClosure k (AlgebraicClosure k)
  body: .of_splits fun f hf _ => by
  rw [show f = (⟨f]; rw [hf⟩ : Monics k) from rfl]; rw [Monics.map_eq_prod]
  exact Splits.prod fun _ _ => (Splits.X_sub_C _).map _

中文:
实例 :
  签名: 是AlgClosure k (代数闭包 k)
  定义体: .of_splits fun f hf _ => by
  rw [show f = (⟨f]; rw [hf⟩ : Monics k) from rfl]; rw [Monics.map_eq_prod]
  exact Splits.prod fun _ _ => (Splits.X_sub_C _).map _

Depends on / 依赖: Monics, Monics.map_eq_prod, Splits, Splits.X_sub_C, Splits.prod, X_sub_C, map_eq_prod, of_splits
-/
instance : IsAlgClosure k (AlgebraicClosure k) := .of_splits fun f hf _ => by
  rw [show f = (⟨f]; rw [hf⟩ : Monics k) from rfl]; rw [Monics.map_eq_prod]
  exact Splits.prod fun _ _ => (Splits.X_sub_C _).map _

/--
Instance `isAlgClosed` / 实例 `isAlgClosed`

English:
instance isAlgClosed
  signature: : IsAlgClosed (AlgebraicClosure k)
  body: IsAlgClosure.isAlgClosed k

中文:
实例 isAlgClosed
  签名: : 是代数闭 (代数闭包 k)
  定义体: IsAlgClosure.isAlgClosed k

Depends on / 依赖: IsAlgClosure, IsAlgClosure.isAlgClosed, isAlgClosed
-/
instance isAlgClosed : IsAlgClosed (AlgebraicClosure k) := IsAlgClosure.isAlgClosed k

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [CharZero
  signature: k] : CharZero (AlgebraicClosure k)
  body: charZero_of_injective_algebraMap (RingHom.injective (algebraMap k (AlgebraicClosure k)))

中文:
实例 [特征零
  签名: k] : 特征零 (代数闭包 k)
  定义体: charZero_of_injective_algebraMap (RingHom.injective (algebraMap k (AlgebraicClosure k)))

Depends on / 依赖: AlgebraicClosure, RingHom, RingHom.injective, algebraMap, charZero_of_injective_algebraMap, injective
-/
instance [CharZero k] : CharZero (AlgebraicClosure k) :=
  charZero_of_injective_algebraMap (RingHom.injective (algebraMap k (AlgebraicClosure k)))

instance {p : Nat} [CharP k p] : CharP (AlgebraicClosure k) p :=
  charP_of_injective_algebraMap (RingHom.injective (algebraMap k (AlgebraicClosure k))) p

instance {L : Type*} [Field L] [Algebra k L] [Algebra.IsAlgebraic k L] :
    IsAlgClosure k (AlgebraicClosure L) where
  isAlgebraic := .trans k L _
  isAlgClosed := inferInstance

end AlgebraicClosure

namespace IntermediateField

variable {K L : Type*} [Field K] [Field L] [Algebra K L] (E : IntermediateField K L)

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [Algebra.IsAlgebraic
  signature: K E] : IsAlgClosure K (AlgebraicClosure E)
  body: ⟨AlgebraicClosure.isAlgClosed E, Algebra.IsAlgebraic.trans K E (AlgebraicClosure E)⟩

中文:
实例 [代数.是代数
  签名: K E] : 是AlgClosure K (代数闭包 E)
  定义体: ⟨AlgebraicClosure.isAlgClosed E, Algebra.IsAlgebraic.trans K E (AlgebraicClosure E)⟩

Depends on / 依赖: Algebra, Algebra.IsAlgebraic.trans, AlgebraicClosure, AlgebraicClosure.isAlgClosed, IsAlgebraic, isAlgClosed
-/
instance [Algebra.IsAlgebraic K E] : IsAlgClosure K (AlgebraicClosure E) :=
  ⟨AlgebraicClosure.isAlgClosed E, Algebra.IsAlgebraic.trans K E (AlgebraicClosure E)⟩

/--
theorem `AdjoinSimple.normal_algebraicClosure` / 定理 `AdjoinSimple.normal_algebraicClosure`

English:
theorem AdjoinSimple.normal_algebraicClosure
  given: {x : L} (hx : IsIntegral K x)
  proof: have : Algebra.IsAlgebraic K K⟮x⟯ := isAlgebraic_adjoin_simple hx
  IsAlgClosure.normal _ _

中文:
定理 AdjoinSimple.normal_algebraicClosure
  条件: {x : L} (hx : 是整 K x)
  证明: have : Algebra.IsAlgebraic K K⟮x⟯ := isAlgebraic_adjoin_simple hx
  IsAlgClosure.normal _ _

Depends on / 依赖: Algebra, Algebra.IsAlgebraic, IsAlgClosure, IsAlgClosure.normal, IsAlgebraic, isAlgebraic_adjoin_simple, normal
-/
theorem AdjoinSimple.normal_algebraicClosure {x : L} (hx : IsIntegral K x) :
    Normal K (AlgebraicClosure K⟮x⟯) :=
  have : Algebra.IsAlgebraic K K⟮x⟯ := isAlgebraic_adjoin_simple hx
  IsAlgClosure.normal _ _

/--
theorem `AdjoinDouble.normal_algebraicClosure` / 定理 `AdjoinDouble.normal_algebraicClosure`

English:
theorem AdjoinDouble.normal_algebraicClosure
  statement: {x y : L} (hx : IsIntegral K x)
  proof: have : Algebra.IsAlgebraic K K⟮x, y⟯ := isAlgebraic_adjoin_pair hx hy
  IsAlgClosure.normal _ _

中文:
定理 AdjoinDouble.normal_algebraicClosure
  结论: {x y : L} (hx : 是整 K x)
  证明: have : Algebra.IsAlgebraic K K⟮x, y⟯ := isAlgebraic_adjoin_pair hx hy
  IsAlgClosure.normal _ _

Depends on / 依赖: Algebra, Algebra.IsAlgebraic, IsAlgClosure, IsAlgClosure.normal, IsAlgebraic, isAlgebraic_adjoin_pair, normal
-/
theorem AdjoinDouble.normal_algebraicClosure {x y : L} (hx : IsIntegral K x)
    (hy : IsIntegral K y) : Normal K (AlgebraicClosure K⟮x, y⟯) :=
  have : Algebra.IsAlgebraic K K⟮x, y⟯ := isAlgebraic_adjoin_pair hx hy
  IsAlgClosure.normal _ _

end IntermediateField
