/-
Copyright (c) 2021 Alex Zhao. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Zhao, Daniel Buth, Sebastian Meier, Junyan Xu
-/
module

public import Mathlib.RingTheory.Ideal.NatInt

/-!
# Frobenius Number

In this file we first define a predicate for Frobenius numbers, then solve the 2-variable variant
of this problem. We also show the Frobenius number exists for any set of coprime natural numbers
that doesn't contain 1. This is closely related to the fact that all ideals of ℕ are finitely
generated, which we also prove in this file.

## Theorem Statement

Given a finite set of relatively prime integers all greater than 1, their Frobenius number is the
largest positive integer that cannot be expressed as a sum of nonnegative multiples of these
integers. Here we show the Frobenius number of two relatively prime integers `m` and `n` greater
than 1 is `m * n - m - n`. This result is also known as the Chicken McNugget Theorem.

## Implementation Notes

First we define Frobenius numbers in general using `IsGreatest` and `AddSubmonoid.closure`. Then
we proceed to compute the Frobenius number of `m` and `n`.

For the upper bound, we begin with an auxiliary lemma showing `m * n` is not attainable, then show
`m * n - m - n` is not attainable. Then for the construction, we create a `k_1` which is `k mod n`
and `0 mod m`, then show it is at most `k`. Then `k_1` is a multiple of `m`, so `(k-k_1)`
is a multiple of n, and we're done.

## Tags

frobenius number, chicken mcnugget, chinese remainder theorem, AddSubmonoid.closure
-/

@[expose] public section


open Nat

/-- A natural number `n` is the **Frobenius number** of a set of natural numbers `s` if it is an
upper bound on the complement of the additive submonoid generated by `s`.
In other words, it is the largest number that cannot be expressed as a sum of numbers in `s`. -/
/-
**FrobeniusNumber** 是 Mathlib 中的一个定义，位于命名空间 ``。
形式化陈述：FrobeniusNumber (n : Nat) (s : Set Nat) : Prop
参数：n : Nat；s : Set Nat。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
A natural number `n` is the **Frobenius number** of a set of natural numbers `s`
 if it is an
upper bound on the complement of the additive submonoid generated by `s`.
In other words, it is the largest number that cannot be expressed as a sum of nu
mbers in `s`.
-/
def FrobeniusNumber (n : ℕ) (s : Set ℕ) : Prop :=
  IsGreatest { k | k ∉ AddSubmonoid.closure s } n
/-
**frobeniusNumber_iff** 是 Mathlib 中的一个定理，位于命名空间 ``。
形式化陈述：frobeniusNumber_iff {n : Nat} {s : Set Nat} : FrobeniusNumber n s ↔ n ∉ Ad
dSubmonoid.closure s ∧ forall k > n, k in AddSubmonoid.closure s
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `funext`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, (∀ (x : α
), f x = g x) → f = g
· 使用定理 `forall_congr`：∀ {α : Sort u} {p q : α → Prop}, (∀ (a : α), p a = q a) → 
(∀ (a : α), p a) = ∀ (a : α), q a
· 使用定理 `implies_congr`：∀ {p₁ p₂ : Sort u} {q₁ q₂ : Sort v}, p₁ = p₂ → q₁ = q₂ → 
(p₁ → q₁) = (p₂ → q₂)
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `iff_self`：∀ (p : Prop), (p ↔ p) = True
-/
theorem frobeniusNumber_iff {n : ℕ} {s : Set ℕ} :
    FrobeniusNumber n s ↔ n ∉ AddSubmonoid.closure s ∧ ∀ k > n, k ∈ AddSubmonoid.closure s := by
  simp_rw [FrobeniusNumber, IsGreatest, upperBounds, Set.mem_ofPred, not_imp_comm, not_le]

variable {m n : ℕ}

/-- The **Chicken McNugget theorem** stating that the Frobenius number
  of positive numbers `m` and `n` is `m * n - m - n`. -/
/-
**frobeniusNumber_pair** 是 Mathlib 中的一个定理，位于命名空间 ``。
形式化陈述：frobeniusNumber_pair (cop : Coprime m n) (hm : 1 < m) (hn : 1 < n) : Frobe
niusNumber (m * n - m - n) {m, n}
参数：cop : Coprime m n；hm : 1 < m；hn : 1 < n。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `funext`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, (∀ (x : α
), f x = g x) → f = g
· 使用定理 `add_le_mul`：add_le_mul [ZeroLEOneClass R] [NeZero (1 : R)] [MulPosStrict
Mono R] [PosMulStrictMono R] [AddLeftMono R] (a2 : 2 <= a) (b2 : 2 <= b) : a + b
…
· 使用定理 `Nat.instNeZeroSucc`：∀ {n : ℕ}, NeZero (n + 1)
· 使用定理 `IsStrictOrderedRing.toMulPosStrictMono`：∀ {R : Type u_1} {inst : Semirin
g R} {inst_1 : PartialOrder R} [self : IsStrictOrderedRing R], MulPosStrictMono 
R
· 使用定理 `LinearOrderedCommMonoidWithZero.toPosMulStrictMono`：∀ {α : Type u_3} [se
lf : LinearOrderedCommMonoidWithZero α], PosMulStrictMono α
· 使用定理 `IsOrderedAddMonoid.toAddLeftMono`：∀ {α : Type u_1} [inst : AddCommMonoid
 α] [inst_1 : Preorder α] [IsOrderedAddMonoid α], AddLeftMono α
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `forall_congr`：∀ {α : Sort u} {p q : α → Prop}, (∀ (a : α), p a = q a) → 
(∀ (a : α), p a) = ∀ (a : α), q a
· 使用定理 `Nat.Coprime.mul_add_mul_ne_mul`：∀ {m n a b : ℕ}, m.Coprime n → a ≠ 0 → b
 ≠ 0 → a * m + b * n ≠ m * n
· 使用定理 `Nat.add_one_ne_zero`：∀ (n : ℕ), n + 1 ≠ 0
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `Nat.cast_add`：cast_add (m n : Nat) : ((m + n : Nat) : R) = m + n
· 使用定理 `Nat.cast_mul`：∀ {α : Type u_1} [inst : NonAssocSemiring α] (m n : ℕ), ↑(
m * n) = ↑m * ↑n
· 使用定理 `Nat.cast_one`：cast_one : ((1 : Nat) : R) = 1
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `sub_eq_zero`：∀ {G : Type u_3} [inst : AddGroup G] {a b : G}, a - b = 0 ↔
 a = b
· 使用定理 `Nat.cast_sub`：cast_sub {m n} (h : m <= n) : ((n - m : Nat) : R) = n - m
· 使用定理 `Nat.sub_sub`：∀ (n m k : ℕ), n - m - k = n - (m + k)
· 使用定理 `Mathlib.Tactic.Ring.of_eq`：∀ {α : Sort u_2} {a b c : α}, a = c → b = c →
 a = b
· 使用定理 `Mathlib.Tactic.Ring.Common.sub_congr`：∀ {R : Type u_2} [inst : CommRing 
R] {a a' b b' c : R}, a = a' → b = b' → a' - b' = c → a - b = c
· 使用定理 `Mathlib.Tactic.Ring.Common.add_congr`：∀ {R : Type u_1} [inst : CommSemir
ing R] {a a' b b' c : R}, a = a' → b = b' → a' + b' = c → a + b = c
· 使用定理 `Mathlib.Tactic.Ring.Common.mul_congr`：∀ {R : Type u_1} [inst : CommSemir
ing R] {a a' b b' c : R}, a = a' → b = b' → a' * b' = c → a * b = c
· 使用定理 `Mathlib.Tactic.Ring.Common.atom_pf`：∀ {R : Type u_1} [inst : CommSemirin
g R] {b : R} (a : R) {e : ℕ},   Nat.rawCast 1 = e → a ^ e * Nat.rawCast 1 = b → 
a = b + 0
· 使用定理 `Mathlib.Tactic.Ring.cast_pos`：∀ {R : Type u_1} [inst : CommSemiring R] {
a : R} {n : ℕ}, Mathlib.Meta.NormNum.IsNat a n → a = n.rawCast + 0
· 使用定理 `Mathlib.Meta.NormNum.isNat_ofNat`：isNat_ofNat (α : Type u) [AddMonoidWit
hOne α] {a : α} {n : Nat} (h : n = a) : IsNat a n
· 使用定理 `Mathlib.Tactic.Ring.Common.add_pf_add_gt`：∀ {R : Type u_1} [inst : CommS
emiring R] {a b₂ c : R} (b₁ : R), a + b₂ = c → a + (b₁ + b₂) = b₁ + c
· 使用定理 `Mathlib.Tactic.Ring.Common.add_pf_add_zero`：∀ {R : Type u_1} [inst : Com
mSemiring R] (a : R), a + 0 = a
· 使用定理 `Mathlib.Tactic.Ring.Common.add_mul`：∀ {R : Type u_1} [inst : CommSemirin
g R] {a₁ a₂ b c₁ c₂ d : R},   a₁ * b = c₁ → a₂ * b = c₂ → c₁ + c₂ = d → (a₁ + a₂
) * b = d
（共 58 条，此处仅展示前 30 条）

--- 原说明 ---
The **Chicken McNugget theorem** stating that the Frobenius number
  of positive numbers `m` and `n` is `m * n - m - n`.
-/
theorem frobeniusNumber_pair (cop : Coprime m n) (hm : 1 < m) (hn : 1 < n) :
    FrobeniusNumber (m * n - m - n) {m, n} := by
  simp_rw [FrobeniusNumber, AddSubmonoid.mem_closure_pair]
  have hmn : m + n ≤ m * n := add_le_mul hm hn
  constructor
  · push Not
    intro a b h
    apply cop.mul_add_mul_ne_mul (add_one_ne_zero a) (add_one_ne_zero b)
    simp only [Nat.sub_sub, smul_eq_mul] at h
    zify [hmn] at h ⊢
    rw [← sub_eq_zero] at h ⊢
    rw [← h]
    ring
  · intro k hk
    dsimp at hk
    contrapose! hk
    obtain ⟨a, b, h⟩ := exists_add_mul_eq_of_gcd_dvd_of_mul_pred_le m n k
      (by simp [cop.gcd_eq_one]) (by grind [pred_mul, mul_pred, pred_eq_sub_one])
    exact ⟨a, b, succ_inj.mp (congrArg succ h)⟩

namespace Nat

open Submodule.IsPrincipal

/-- The gcd of a set of natural numbers is defined to be the nonnegative generator
of the ideal of `ℤ` generated by them. -/
/-
**Nat.setGcd** 是 Mathlib 中的一个定义，位于命名空间 `Nat`。
形式化陈述：setGcd (s : Set Nat) : Nat
参数：s : Set Nat。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The gcd of a set of natural numbers is defined to be the nonnegative generator
of the ideal of `ℤ` generated by them.
-/
noncomputable def setGcd (s : Set ℕ) : ℕ :=
  (generator <| Ideal.span <| ((↑) : ℕ → ℤ) '' s).natAbs

variable {s t : Set ℕ} {n : ℕ}
/-
**Nat.setGcd_dvd_of_mem** 是 Mathlib 中的一个引理，位于命名空间 `Nat`。
形式化陈述：setGcd_dvd_of_mem (h : n in s) : setGcd s ∣ n
参数：h : n in s。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Nat.setGcd.eq_1`：∀ (s : Set ℕ), Nat.setGcd s = (Submodule.IsPrincipal.ge
nerator (Ideal.span (Nat.cast '' s))).natAbs
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用引理 `Int.dvd_natCast`：dvd_natCast {n : Nat} : m ∣ (n : Int) ↔ m.natAbs ∣ n
· 使用定理 `Submodule.IsPrincipal.mem_iff_generator_dvd`：mem_iff_generator_dvd (S : 
Ideal R) [S.IsPrincipal] {x : R} : x in S ↔ generator S ∣ x
· 使用定理 `Ideal.subset_span`：subset_span {s : Set α} : s subseteq span s
-/
lemma setGcd_dvd_of_mem (h : n ∈ s) : setGcd s ∣ n := by
  rw [setGcd, ← Int.dvd_natCast, ← mem_iff_generator_dvd]
  exact Ideal.subset_span ⟨n, h, rfl⟩
/-
**Nat.setGcd_dvd_of_mem_closure** 是 Mathlib 中的一个引理，位于命名空间 `Nat`。
形式化陈述：setGcd_dvd_of_mem_closure (h : n in AddSubmonoid.closure s) : setGcd s ∣ n
参数：h : n in AddSubmonoid.closure s。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `AddSubmonoid.closure_induction`：∀ {M : Type u_1} [inst : AddZeroClass M]
 {s : Set M} {motive : (x : M) → x ∈ AddSubmonoid.closure s → Prop},   (∀ (x : M
) (h : x ∈ s), motiv…
· 使用引理 `Nat.setGcd_dvd_of_mem`：setGcd_dvd_of_mem (h : n in s) : setGcd s ∣ n
· 使用定理 `dvd_zero`：dvd_zero (a : α) : a ∣ 0
· 使用定理 `dvd_add`：dvd_add [LeftDistribClass α] {a b c : α} (h₁ : a ∣ b) (h₂ : a ∣
 c) : a ∣ b + c
· 使用定理 `Distrib.leftDistribClass`：∀ (R : Type u_1) [inst : Distrib R], LeftDistr
ibClass R
-/
lemma setGcd_dvd_of_mem_closure (h : n ∈ AddSubmonoid.closure s) : setGcd s ∣ n :=
  AddSubmonoid.closure_induction (fun _ ↦ setGcd_dvd_of_mem) (dvd_zero _) (fun _ _ _ _ ↦ dvd_add) h

/-- The characterizing property of `Nat.setGcd`. -/
/-
**Nat.dvd_setGcd_iff** 是 Mathlib 中的一个引理，位于命名空间 `Nat`。
形式化陈述：dvd_setGcd_iff : n ∣ setGcd s ↔ forall m in s, n ∣ m
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `forall_congr`：∀ {α : Sort u} {p q : α → Prop}, (∀ (a : α), p a = q a) → 
(∀ (a : α), p a) = ∀ (a : α), q a
· 使用定理 `implies_congr`：∀ {p₁ p₂ : Sort u} {q₁ q₂ : Sort v}, p₁ = p₂ → q₁ = q₂ → 
(p₁ → q₁) = (p₂ → q₂)
· 使用定理 `iff_self`：∀ (p : Prop), (p ↔ p) = True

--- 原说明 ---
The characterizing property of `Nat.setGcd`.
-/
lemma dvd_setGcd_iff : n ∣ setGcd s ↔ ∀ m ∈ s, n ∣ m := by
  simp_rw [setGcd, ← Int.natCast_dvd, dvd_generator_span_iff,
    Set.forall_mem_image, Int.natCast_dvd_natCast]
/-
**Nat.setGcd_mono** 是 Mathlib 中的一个引理，位于命名空间 `Nat`。
形式化陈述：setGcd_mono (h : s subseteq t) : setGcd t ∣ setGcd s
参数：h : s subseteq t。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用引理 `Nat.dvd_setGcd_iff`：dvd_setGcd_iff : n ∣ setGcd s ↔ forall m in s, n ∣ m
· 使用引理 `Nat.setGcd_dvd_of_mem`：setGcd_dvd_of_mem (h : n in s) : setGcd s ∣ n
-/
lemma setGcd_mono (h : s ⊆ t) : setGcd t ∣ setGcd s :=
  dvd_setGcd_iff.mpr fun _m hm ↦ setGcd_dvd_of_mem (h hm)
/-
**Nat.dvdNotUnit_setGcd_insert** 是 Mathlib 中的一个引理，位于命名空间 `Nat`。
形式化陈述：dvdNotUnit_setGcd_insert (h : ¬ setGcd s ∣ n) : DvdNotUnit (setGcd (insert
 n s)) (setGcd s)
参数：h : ¬ setGcd s ∣ n。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `dvdNotUnit_of_dvd_of_not_dvd`：dvdNotUnit_of_dvd_of_not_dvd {a b : α} (hd
 : a ∣ b) (hnd : ¬b ∣ a) : DvdNotUnit a b
· 使用引理 `Nat.setGcd_mono`：setGcd_mono (h : s subseteq t) : setGcd t ∣ setGcd s
· 使用定理 `Set.subset_insert`：subset_insert (x : α) (s : Set α) : s subseteq insert
 x s
· 使用定理 `Iff.mp`：∀ {a b : Prop}, (a ↔ b) → a → b
· 使用引理 `Nat.dvd_setGcd_iff`：dvd_setGcd_iff : n ∣ setGcd s ↔ forall m in s, n ∣ m
· 使用定理 `Set.mem_insert`：mem_insert (x : α) (s : Set α) : x in insert x s
-/
lemma dvdNotUnit_setGcd_insert (h : ¬ setGcd s ∣ n) :
    DvdNotUnit (setGcd (insert n s)) (setGcd s) :=
  dvdNotUnit_of_dvd_of_not_dvd (setGcd_mono <| Set.subset_insert ..)
    fun dvd ↦ h <| dvd_setGcd_iff.mp dvd _ (Set.mem_insert ..)
/-
**Nat.setGcd_insert_of_dvd** 是 Mathlib 中的一个引理，位于命名空间 `Nat`。
形式化陈述：setGcd_insert_of_dvd (h : setGcd s ∣ n) : setGcd (insert n s) = setGcd s
参数：h : setGcd s ∣ n。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Dvd.dvd.antisymm`：∀ {α : Type u_1} [inst : CommMonoidWithZero α] [IsCanc
elMulZero α] {a b : α} [Subsingleton αˣ], a ∣ b → b ∣ a → a = b
· 使用定理 `Unique.instSubsingleton`：∀ {α : Sort u_1} [Unique α], Subsingleton α
· 使用引理 `Nat.setGcd_mono`：setGcd_mono (h : s subseteq t) : setGcd t ∣ setGcd s
· 使用定理 `Set.subset_insert`：subset_insert (x : α) (s : Set α) : s subseteq insert
 x s
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用引理 `Nat.dvd_setGcd_iff`：dvd_setGcd_iff : n ∣ setGcd s ↔ forall m in s, n ∣ m
· 使用引理 `Nat.setGcd_dvd_of_mem`：setGcd_dvd_of_mem (h : n in s) : setGcd s ∣ n
-/
lemma setGcd_insert_of_dvd (h : setGcd s ∣ n) : setGcd (insert n s) = setGcd s :=
  (setGcd_mono <| Set.subset_insert ..).antisymm <| dvd_setGcd_iff.mpr
    fun m ↦ by rintro (rfl | hm); exacts [h, setGcd_dvd_of_mem hm]
/-
**Nat.setGcd_eq_zero_iff** 是 Mathlib 中的一个引理，位于命名空间 `Nat`。
形式化陈述：setGcd_eq_zero_iff : setGcd s = 0 ↔ s subseteq {0}
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `forall_congr`：∀ {α : Sort u} {p q : α → Prop}, (∀ (a : α), p a = q a) → 
(∀ (a : α), p a) = ∀ (a : α), q a
· 使用定理 `implies_congr`：∀ {p₁ p₂ : Sort u} {q₁ q₂ : Sort v}, p₁ = p₂ → q₁ = q₂ → 
(p₁ → q₁) = (p₂ → q₂)
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `iff_self`：∀ (p : Prop), (p ↔ p) = True
-/
lemma setGcd_eq_zero_iff : setGcd s = 0 ↔ s ⊆ {0} := by
  simp_rw [setGcd, Int.natAbs_eq_zero, ← eq_bot_iff_generator_eq_zero, Ideal.span_eq_bot,
    Set.forall_mem_image, Int.natCast_eq_zero, Set.subset_def, Set.mem_singleton_iff]
/-
**Nat.exists_ne_zero_of_setGcd_ne_zero** 是 Mathlib 中的一个引理，位于命名空间 `Nat`。
形式化陈述：exists_ne_zero_of_setGcd_ne_zero (hs : setGcd s != 0) : exists n in s, n !
= 0
参数：hs : setGcd s != 0。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `Mathlib.Tactic.Contrapose.contrapose₂`：contrapose₂ {p q : Prop} : (¬ q -
> p) -> (¬ p -> q)
· 使用定理 `implies_congr`：∀ {p₁ p₂ : Sort u} {q₁ q₂ : Sort v}, p₁ = p₂ → q₁ = q₂ → 
(p₁ → q₁) = (p₂ → q₂)
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `forall_congr`：∀ {α : Sort u} {p q : α → Prop}, (∀ (a : α), p a = q a) → 
(∀ (a : α), p a) = ∀ (a : α), q a
· 使用定理 `Mathlib.Tactic.Push.not_and_eq`：not_and_eq : (¬ (p ∧ q)) = (p -> ¬ q)
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用引理 `Nat.setGcd_eq_zero_iff`：setGcd_eq_zero_iff : setGcd s = 0 ↔ s subseteq {
0}
-/
lemma exists_ne_zero_of_setGcd_ne_zero (hs : setGcd s ≠ 0) : ∃ n ∈ s, n ≠ 0 := by
  contrapose! hs
  exact setGcd_eq_zero_iff.mpr hs

variable (s)
/-
**Nat.span_singleton_setGcd** 是 Mathlib 中的一个引理，位于命名空间 `Nat`。
形式化陈述：span_singleton_setGcd : Ideal.span {(setGcd s : Int)} = Ideal.span (((↑) :
 Nat -> Int) '' s)
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Nat.setGcd.eq_1`：∀ (s : Set ℕ), Nat.setGcd s = (Submodule.IsPrincipal.ge
nerator (Ideal.span (Nat.cast '' s))).natAbs
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `Ideal.span_singleton_eq_span_singleton`：span_singleton_eq_span_singleton
 {α : Type u} [CommSemiring α] [IsDomain α] {x y : α} : span ({x} : Set α) = spa
n ({y} : Set α) ↔ Associated…
· 使用定理 `Int.instIsDomain`：IsDomain ℤ
· 使用定理 `Int.associated_natAbs`：Int.associated_natAbs (k : Int) : Associated k k.
natAbs
· 使用定理 `Ideal.span.eq_1`：∀ {α : Type u} [inst : Semiring α] (s : Set α), Ideal.s
pan s = Submodule.span α s
· 使用定理 `Submodule.IsPrincipal.span_singleton_generator`：span_singleton_generator
 (S : Submodule R M) [S.IsPrincipal] : span R {generator S} = S
-/
lemma span_singleton_setGcd : Ideal.span {(setGcd s : ℤ)} = Ideal.span (((↑) : ℕ → ℤ) '' s) := by
  rw [setGcd, ← Ideal.span_singleton_eq_span_singleton.mpr (Int.associated_natAbs _),
    Ideal.span, span_singleton_generator]
/-
**Nat.subset_span_setGcd** 是 Mathlib 中的一个引理，位于命名空间 `Nat`。
形式化陈述：subset_span_setGcd : s subseteq Ideal.span {setGcd s}
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `Ideal.mem_span_singleton`：mem_span_singleton {x y : α} : x in span ({y} 
: Set α) ↔ y ∣ x
· 使用引理 `Nat.setGcd_dvd_of_mem`：setGcd_dvd_of_mem (h : n in s) : setGcd s ∣ n
-/
lemma subset_span_setGcd : s ⊆ Ideal.span {setGcd s} :=
  fun _x hx ↦ Ideal.mem_span_singleton.mpr (setGcd_dvd_of_mem hx)

open Ideal in
/-
**Nat.exists_mem_span_nat_finset_of_ge** 是 Mathlib 中的一个定理，位于命名空间 `Nat`。
形式化陈述：exists_mem_span_nat_finset_of_ge : exists (t : Finset Nat) (n : Nat), ↑t s
ubseteq s ∧ forall m >= n, setGcd s ∣ m -> m in Ideal.span t
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Finset.coe_empty`：coe_empty : ((∅ : Finset α) : Set α) = ∅
· 使用定理 `Iff.mp`：∀ {a b : Prop}, (a ↔ b) → a → b
· 使用定理 `zero_dvd_iff`：zero_dvd_iff : 0 ∣ a ↔ a = 0
· 使用定理 `ZeroMemClass.zero_mem`：∀ {S : Type u_3} {M : outParam (Type u_4)} {inst 
: Zero M} {inst_1 : SetLike S M} [self : ZeroMemClass S M] (s : S),   0 ∈ s
· 使用定理 `AddSubmonoidClass.toZeroMemClass`：∀ {S : Type u_3} {M : outParam (Type u
_4)} {inst : AddZeroClass M} {inst_1 : SetLike S M}   [self : AddSubmonoidClass 
S M], ZeroMemClass S M
· 使用定理 `Submodule.mem_span_image_iff_exists_fun`：Submodule.mem_span_image_iff_ex
ists_fun {s : Set α} : x in span R (v '' s) ↔ exists t : Finset α, ↑t subseteq s
 ∧ exists c : t -> R, ∑ i, c …
· 使用定理 `Ideal.mem_span_singleton_self`：mem_span_singleton_self (x : α) : x in sp
an ({x} : Set α)
· 使用引理 `Nat.span_singleton_setGcd`：span_singleton_setGcd : Ideal.span {(setGcd s
 : Int)} = Ideal.span (((↑) : Nat -> Int) '' s)
· 使用引理 `Nat.exists_ne_zero_of_setGcd_ne_zero`：exists_ne_zero_of_setGcd_ne_zero (
hs : setGcd s != 0) : exists n in s, n != 0
· 使用定理 `Finset.coe_insert`：coe_insert (a : α) (s : Finset α) : ↑(insert a s) = (
insert a s : Set α)
· 使用定理 `ExistsAddOfLE.exists_add_of_le`：∀ {α : Type u} {inst : Add α} {inst_1 : 
LE α} [self : ExistsAddOfLE α] {a b : α}, a ≤ b → ∃ c, b = a + c
· 使用定理 `CanonicallyOrderedAdd.toExistsAddOfLE`：∀ {α : Type u_1} {inst : Add α} {
inst_1 : LE α} [self : CanonicallyOrderedAdd α], ExistsAddOfLE α
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `Nat.div_add_mod'`：∀ (a b : ℕ), a / b * b + a % b = a
· 使用定理 `add_comm`：∀ {G : Type u_1} [inst : AddCommMagma G] (a b : G), a + b = b 
+ a
· 使用定理 `add_assoc`：∀ {G : Type u_1} [inst : AddSemigroup G] (a b c : G), a + b +
 c = a + (b + c)
· 使用定理 `AddMemClass.add_mem`：∀ {S : Type u_3} {M : outParam (Type u_4)} {inst : 
Add M} {inst_1 : SetLike S M} [self : AddMemClass S M] {s : S}   {a b : M}, a ∈ 
s → b ∈ s…
· 使用定理 `AddSubmonoidClass.toAddMemClass`：∀ {S : Type u_3} {M : outParam (Type u_
4)} {inst : AddZeroClass M} {inst_1 : SetLike S M}   [self : AddSubmonoidClass S
 M], AddMemClass S M
· 使用定理 `Ideal.mul_mem_left`：mul_mem_left : b in I -> a * b in I
· 使用定理 `Ideal.subset_span`：subset_span {s : Set α} : s subseteq span s
· 使用定理 `Finset.mem_insert_self`：mem_insert_self (a : α) (s : Finset α) : a in in
sert a s
· 使用定理 `Submodule.span_mono`：∀ {R : Type u_1} {M : Type u_4} [inst : Semiring R]
 [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   {s t : Set M}, s ⊆ t 
→ Submodu…
· 使用定理 `Finset.subset_insert`：∀ {α : Type u_1} [inst : DecidableEq α] (a : α) (s
 : Finset α), s ⊆ insert a s
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `Nat.dvd_mod_iff`：∀ {k m n : ℕ}, k ∣ n → (k ∣ m % n ↔ k ∣ m)
· 使用引理 `Nat.setGcd_dvd_of_mem`：setGcd_dvd_of_mem (h : n in s) : setGcd s ∣ n
（共 64 条，此处仅展示前 30 条）
-/
theorem exists_mem_span_nat_finset_of_ge :
    ∃ (t : Finset ℕ) (n : ℕ), ↑t ⊆ s ∧ ∀ m ≥ n, setGcd s ∣ m → m ∈ Ideal.span t := by
  by_cases h0 : setGcd s = 0
  · refine ⟨∅, 0, by simp, fun _ _ dvd ↦ by cases zero_dvd_iff.mp (h0 ▸ dvd); exact zero_mem _⟩
  -- Write the gcd of `s` as a ℤ-linear combination of a finite subset `t`.
  have ⟨t, hts, a, eq⟩ := (Submodule.mem_span_image_iff_exists_fun _).mp
    (span_singleton_setGcd s ▸ mem_span_singleton_self _)
  -- Let `x` be an arbitrary nonzero element in `s`.
  have ⟨x, hxs, hx⟩ := exists_ne_zero_of_setGcd_ne_zero h0
  let n := (x / setGcd s) * ∑ i, (-a i).toNat * i
  refine ⟨insert x t, n, by simpa [Set.insert_subset_iff] using ⟨hxs, hts⟩, fun m ge dvd ↦ ?_⟩
  -- For `m ≥ n`, write `m = q * x + (r + n)` with 0 ≤ r < x.
  obtain ⟨c, rfl⟩ := exists_add_of_le ge
  rw [← c.div_add_mod' x]
  set q := c / x
  set r := c % x
  rw [add_comm, add_assoc]
  refine add_mem (mul_mem_left _ q (subset_span (Finset.mem_insert_self ..)))
    (Submodule.span_mono (s := t) (Finset.subset_insert ..) ?_)
  -- It suffices to show `r + n` lies in the ℕ-span of `t`.
  obtain ⟨rx, hrx⟩ : setGcd s ∣ r := (dvd_mod_iff (setGcd_dvd_of_mem hxs)).mpr <|
    (Nat.dvd_add_right <| dvd_mul_of_dvd_right (Finset.dvd_sum fun i _ ↦
      dvd_mul_of_dvd_right (setGcd_dvd_of_mem (hts i.2)) _) _).mp dvd
  convert!
    (sum_mem fun i _ ↦ mul_mem_left _ _ (subset_span i.2) :
      -- an explicit ℕ-linear combination of elements of `t` that is equal to `r + n`
       ∑ i : t, (if 0 ≤ a i then rx else x / setGcd s - rx) * (a i).natAbs * i ∈ span t)
  simp_rw [← Int.natCast_inj, hrx, n, Finset.mul_sum, mul_comm _ rx, cast_add, cast_sum, cast_mul,
    ← eq, Finset.mul_sum, smul_eq_mul, ← mul_assoc, ← Finset.sum_add_distrib, ← add_mul]
  congr! 2 with i
  split_ifs with hai
  · rw [Int.toNat_eq_zero.mpr (by lia), cast_zero, mul_zero, add_zero,
      Int.natCast_natAbs, abs_eq_self.mpr hai]
  · rw [cast_sub, Int.natCast_natAbs, abs_eq_neg_self.mpr (by lia), sub_mul,
      ← Int.eq_natCast_toNat.mpr (by lia), mul_neg (rx : ℤ), sub_neg_eq_add, add_comm]
    rw [← Nat.mul_le_mul_left_iff (pos_of_ne_zero h0), ← hrx,
      Nat.mul_div_cancel' (setGcd_dvd_of_mem hxs)]
    exact (c.mod_lt (pos_of_ne_zero hx)).le
/-
**Nat.exists_mem_closure_of_ge** 是 Mathlib 中的一个定理，位于命名空间 `Nat`。
形式化陈述：exists_mem_closure_of_ge : exists n, forall m >= n, setGcd s ∣ m -> m in A
ddSubmonoid.closure s
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Nat.exists_mem_span_nat_finset_of_ge`：exists_mem_span_nat_finset_of_ge :
 exists (t : Finset Nat) (n : Nat), ↑t subseteq s ∧ forall m >= n, setGcd s ∣ m 
-> m in Ideal.span t
· 使用定理 `Eq.le`：∀ {α : Type u_1} [inst : Preorder α] {a b : α}, a = b → a ≤ b
· 使用定理 `Submodule.span_nat_eq_addSubmonoidClosure`：span_nat_eq_addSubmonoidClosu
re (s : Set M) : (span Nat s).toAddSubmonoid = AddSubmonoid.closure s
· 使用定理 `Submodule.span_mono`：∀ {R : Type u_1} {M : Type u_4} [inst : Semiring R]
 [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   {s t : Set M}, s ⊆ t 
→ Submodu…
-/
theorem exists_mem_closure_of_ge : ∃ n, ∀ m ≥ n, setGcd s ∣ m → m ∈ AddSubmonoid.closure s :=
  have ⟨_t, n, hts, hn⟩ := exists_mem_span_nat_finset_of_ge s
  ⟨n, fun m ge dvd ↦ (Submodule.span_nat_eq_addSubmonoidClosure s).le
    (Submodule.span_mono hts (hn m ge dvd))⟩
/-
**Nat.finite_setOfPred_setGcd_dvd_and_mem_span** 是 Mathlib 中的一个定理，位于命名空间 `Nat`。
形式化陈述：finite_setOfPred_setGcd_dvd_and_mem_span : {n | setGcd s ∣ n ∧ n ∉ Ideal.s
pan s}.Finite
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Nat.exists_mem_closure_of_ge`：exists_mem_closure_of_ge : exists n, foral
l m >= n, setGcd s ∣ m -> m in AddSubmonoid.closure s
· 使用定理 `Set.Finite.subset`：∀ {α : Type u} {s : Set α}, s.Finite → ∀ {t : Set α},
 t ⊆ s → t.Finite
· 使用定理 `Finset.finite_toSet`：finite_toSet (s : Finset α) : (s : Set α).Finite
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `Finset.mem_range`：mem_range : m in range n ↔ m < n
· 使用定理 `lt_of_not_ge`：∀ {α : Type u_1} [inst : LinearOrder α] {a b : α}, ¬b ≤ a 
→ a < b
· 使用定理 `And.right`：∀ {a b : Prop}, a ∧ b → b
· 使用定理 `Eq.ge`：∀ {α : Type u_1} [inst : Preorder α] {a b : α}, a = b → b ≤ a
· 使用定理 `Submodule.span_nat_eq_addSubmonoidClosure`：span_nat_eq_addSubmonoidClosu
re (s : Set M) : (span Nat s).toAddSubmonoid = AddSubmonoid.closure s
· 使用定理 `And.left`：∀ {a b : Prop}, a ∧ b → a
-/
theorem finite_setOfPred_setGcd_dvd_and_mem_span :
    {n | setGcd s ∣ n ∧ n ∉ Ideal.span s}.Finite :=
  have ⟨n, hn⟩ := exists_mem_closure_of_ge s
  (Finset.range n).finite_toSet.subset fun m h ↦ Finset.mem_range.mpr <|
    lt_of_not_ge fun ge ↦ h.2 <| (Submodule.span_nat_eq_addSubmonoidClosure s).ge (hn m ge h.1)

@[deprecated (since := "2026-07-09")]
alias finite_setOf_setGcd_dvd_and_mem_span := finite_setOfPred_setGcd_dvd_and_mem_span

/-- `ℕ` is a Noetherian `ℕ`-module, i.e., `ℕ` is a Noetherian semiring. -/
/-
**Nat.** 是 Mathlib 中的一个实例，位于命名空间 `Nat`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
`ℕ` is a Noetherian `ℕ`-module, i.e., `ℕ` is a Noetherian semiring.
-/
instance : IsNoetherian ℕ ℕ where
  noetherian s := by
    have ⟨t, n, hts, hn⟩ := exists_mem_span_nat_finset_of_ge s
    classical
    refine ⟨t ∪ {m ∈ Finset.range n | m ∈ s}, (Submodule.span_le.mpr ?_).antisymm fun m hm ↦ ?_⟩
    · simpa using ⟨hts, fun _ ↦ And.right⟩
    obtain le | gt := le_or_gt n m
    · exact Submodule.span_mono (by simp) (hn m le (setGcd_dvd_of_mem hm))
    · exact Submodule.subset_span (by simpa using .inr ⟨gt, hm⟩)
/-
**Nat.addSubmonoid_fg** 是 Mathlib 中的一个定理，位于命名空间 `Nat`。
形式化陈述：addSubmonoid_fg (s : AddSubmonoid Nat) : s.FG
参数：s : AddSubmonoid Nat。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `AddSubmonoid.toNatSubmodule_toAddSubmonoid`：AddSubmonoid.toNatSubmodule_
toAddSubmonoid (S : AddSubmonoid M) : S.toNatSubmodule.toAddSubmonoid = S
· 使用定理 `Submodule.fg_iff_addSubmonoid_fg`：fg_iff_addSubmonoid_fg (P : Submodule 
Nat M) : P.FG ↔ P.toAddSubmonoid.FG
· 使用定理 `IsNoetherian.noetherian`：∀ {R : Type u_1} {M : Type u_2} {inst : Semirin
g R} {inst_1 : AddCommMonoid M} {inst_2 : _root_.Module R M}   [self : IsNoether
ian R M] (s :…
· 使用定理 `Nat.instIsNoetherian`：IsNoetherian ℕ ℕ
-/
theorem addSubmonoid_fg (s : AddSubmonoid ℕ) : s.FG := by
  rw [← s.toNatSubmodule_toAddSubmonoid, ← Submodule.fg_iff_addSubmonoid_fg]
  apply IsNoetherian.noetherian

end Nat

/-- A set of natural numbers has a Frobenius number iff their gcd is 1; if 1 is in the set,
the Frobenius number is -1, so the Frobenius number doesn't exist as a natural number.
[Wikipedia](https://en.wikipedia.org/wiki/Coin_problem#Statement) seems to attribute this to
Issai Schur, but [Schur's theorem](https://en.wikipedia.org/wiki/Schur%27s_theorem#Combinatorics)
is a more precise statement about asymptotics of the number of ℕ-linear combinations, and the
existence of the Frobenius number for a set with gcd 1 is probably well known before that. -/
/-
**exists_frobeniusNumber_iff** 是 Mathlib 中的一个定理，位于命名空间 ``。
形式化陈述：exists_frobeniusNumber_iff {s : Set Nat} : (exists n, FrobeniusNumber n s)
 ↔ setGcd s = 1 ∧ 1 ∉ s where mp
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.mp`：∀ {a b : Prop}, (a ↔ b) → a → b
· 使用定理 `Nat.dvd_one`：∀ {n : ℕ}, n ∣ 1 ↔ n = 1
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `Nat.dvd_add_iff_right`：∀ {k m n : ℕ}, k ∣ m → (k ∣ n ↔ k ∣ m + n)
· 使用引理 `Nat.setGcd_dvd_of_mem_closure`：setGcd_dvd_of_mem_closure (h : n in AddSu
bmonoid.closure s) : setGcd s ∣ n
· 使用定理 `And.right`：∀ {a b : Prop}, a ∧ b → b
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `frobeniusNumber_iff`：frobeniusNumber_iff {n : Nat} {s : Set Nat} : Frobe
niusNumber n s ↔ n ∉ AddSubmonoid.closure s ∧ forall k > n, k in AddSubmonoid.cl
osure s
· 使用定理 `And.left`：∀ {a b : Prop}, a ∧ b → a
· 使用定理 `AddSubmonoid.closure_mono`：∀ {M : Type u_1} [inst : AddZeroClass M] ⦃s t
 : Set M⦄, s ⊆ t → AddSubmonoid.closure s ≤ AddSubmonoid.closure t
· 使用定理 `Set.singleton_subset_iff`：singleton_subset_iff {a : α} {s : Set α} : {a}
 subseteq s ↔ a in s
· 使用定理 `Eq.ge`：∀ {α : Type u_1} [inst : Preorder α] {a b : α}, a = b → b ≤ a
· 使用定理 `Nat.addSubmonoidClosure_one`：AddSubmonoid.closure {1} = ⊤
· 使用定理 `Nat.exists_mem_closure_of_ge`：exists_mem_closure_of_ge : exists n, foral
l m >= n, setGcd s ∣ m -> m in AddSubmonoid.closure s
· 使用定理 `Nat.one_mem_closure_iff`：Nat.one_mem_closure_iff {s : Set Nat} : 1 in Ad
dSubmonoid.closure s ↔ 1 in s
· 使用引理 `Nat.findGreatest_spec`：findGreatest_spec (hmb : m <= n) (hm : P m) : P (
Nat.findGreatest P n)
· 使用引理 `le_of_not_gt`：le_of_not_gt (h : ¬b < a) : a <= b
· 使用定理 `LT.lt.le`：∀ {α : Type u_1} [inst : Preorder α] {a b : α}, a < b → a ≤ b
· 使用定理 `Eq.dvd`：∀ {α : Type u_1} [inst : Monoid α] {a b : α}, a = b → a ∣ b
· 使用定理 `le_total`：∀ {α : Type u_1} [inst : LinearOrder α] (a b : α), a ≤ b ∨ b ≤
 a
· 使用定理 `of_not_not`：of_not_not {a : Prop} : ¬¬a -> a
· 使用定理 `Nat.findGreatest_is_greatest`：findGreatest_is_greatest (hk : Nat.findGre
atest P n < k) (hkb : k <= n) : ¬P k
· 使用定理 `Dvd.dvd.trans`：∀ {α : Type u_1} [inst : Semigroup α] {a b c : α}, a ∣ b 
→ b ∣ c → a ∣ c
· 使用定理 `one_dvd`：one_dvd (a : α) : 1 ∣ a

--- 原说明 ---
A set of natural numbers has a Frobenius number iff their gcd is 1; if 1 is in t
he set,
the Frobenius number is -1, so the Frobenius number doesn't exist as a natural n
umber.
[Wikipedia](https://en.wikipedia.org/wiki/Coin_problem#Statement) seems to attri
bute this to
Issai Schur, but [Schur's theorem](https://en.wikipedia.org/wiki/Schur%27s_theor
em#Combinatorics)
is a more precise statement about asymptotics of the number of ℕ-linear combinat
ions, and the
existence of the Frobenius number for a set with gcd 1 is probably well known be
fore that.
-/
theorem exists_frobeniusNumber_iff {s : Set ℕ} :
    (∃ n, FrobeniusNumber n s) ↔ setGcd s = 1 ∧ 1 ∉ s where
  mp := fun ⟨n, hn⟩ ↦ by
    rw [frobeniusNumber_iff] at hn
    exact ⟨dvd_one.mp <| Nat.dvd_add_iff_right (setGcd_dvd_of_mem_closure (hn.2 (n + 1)
      (by lia))) (n := 1) |>.mpr (setGcd_dvd_of_mem_closure (hn.2 (n + 2) (by lia))),
      fun h ↦ hn.1 <| AddSubmonoid.closure_mono (Set.singleton_subset_iff.mpr h)
        (addSubmonoidClosure_one.ge ⟨⟩)⟩
  mpr h := by
    have ⟨n, hn⟩ := exists_mem_closure_of_ge s
    let P n := n ∉ AddSubmonoid.closure s
    have : P 1 := h.2 ∘ one_mem_closure_iff.mp
    classical
    refine ⟨findGreatest P n, frobeniusNumber_iff.mpr ⟨findGreatest_spec (P := P) (m := 1)
      (le_of_not_gt fun lt ↦ this (hn _ lt.le h.1.dvd)) this, fun k gt ↦ ?_⟩⟩
    obtain le | le := le_total k n
    · exact of_not_not (findGreatest_is_greatest gt le)
    · exact hn k le (h.1.dvd.trans <| one_dvd k)
