/-
Copyright (c) 2021 Anne Baanen. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anne Baanen, María Inés de Frutos-Fernández, Filippo A. E. Nuccio
-/
module

public import Mathlib.FieldTheory.RatFunc.Basic
public import Mathlib.RingTheory.DedekindDomain.AdicValuation
import Mathlib.RingTheory.Valuation.IsTrivialOn

/-!
# Generalities on the polynomial structure of rational functions

* Main evaluation properties
* Study of the X-adic valuation

## Main definitions
- `RatFunc.C` is the constant polynomial
- `RatFunc.X` is the indeterminate
- `RatFunc.eval` evaluates a rational function given a value for the indeterminate
- `idealX` is the principal ideal generated by `X` in the ring of polynomials over a field K,
  regarded as an element of the height-one-spectrum.
-/

@[expose] public section

noncomputable section

universe u

variable {K : Type u}

namespace RatFunc

section Eval

open scoped nonZeroDivisors Polynomial

open RatFunc

/-! ### Polynomial structure: `C`, `X`, `eval` -/

section Domain

variable [CommRing K] [IsDomain K]

/--
Definition of `C` / `C` 的定义

English:
definition C
  signature: : K ->+* K⟮X⟯
  body: algebraMap _ _

@[simp]

中文:
定义 C
  签名: : K ->+* K⟮X⟯
  定义体: algebraMap _ _

@[simp]

Depends on / 依赖: algebraMap
-/
def C : K ->+* K⟮X⟯ := algebraMap _ _

@[simp]
/--
theorem `algebraMap_eq_C` / 定理 `algebraMap_eq_C`

English:
theorem algebraMap_eq_C
  statement: algebraMap K K⟮X⟯ = C
  proof: rfl

@[simp]

中文:
定理 algebraMap_eq_C
  结论: algebraMap K K⟮X⟯ = C
  证明: rfl

@[simp]
-/
theorem algebraMap_eq_C : algebraMap K K⟮X⟯ = C :=
  rfl

@[simp]
/--
theorem `algebraMap_C` / 定理 `algebraMap_C`

English:
theorem algebraMap_C
  given: (a : K)
  statement: algebraMap K[X] K⟮X⟯ (Polynomial.C a) = C a
  proof: rfl

@[simp]

中文:
定理 algebraMap_C
  条件: (a : K)
  结论: algebraMap K[X] K⟮X⟯ (Polynomial.C a) = C a
  证明: rfl

@[simp]
-/
theorem algebraMap_C (a : K) : algebraMap K[X] K⟮X⟯ (Polynomial.C a) = C a :=
  rfl

@[simp]
/--
theorem `algebraMap_comp_C` / 定理 `algebraMap_comp_C`

English:
theorem algebraMap_comp_C
  statement: (algebraMap K[X] K⟮X⟯).comp Polynomial.C = C
  proof: rfl

中文:
定理 algebraMap_comp_C
  结论: (algebraMap K[X] K⟮X⟯).comp Polynomial.C = C
  证明: rfl
-/
theorem algebraMap_comp_C : (algebraMap K[X] K⟮X⟯).comp Polynomial.C = C :=
  rfl

/--
theorem `smul_eq_C_mul` / 定理 `smul_eq_C_mul`

English:
theorem smul_eq_C_mul
  given: (r : K) (x : K⟮X⟯)
  statement: r • x = C r * x
  proof: by
  rw [Algebra.smul_def]; rw [algebraMap_eq_C]

中文:
定理 smul_eq_C_mul
  条件: (r : K) (x : K⟮X⟯)
  结论: r • x = C r * x
  证明: by
  rw [Algebra.smul_def]; rw [algebraMap_eq_C]

Depends on / 依赖: Algebra, Algebra.smul_def, algebraMap_eq_C, smul_def
-/
theorem smul_eq_C_mul (r : K) (x : K⟮X⟯) : r • x = C r * x := by
  rw [Algebra.smul_def]; rw [algebraMap_eq_C]

/--
theorem `C_injective` / 定理 `C_injective`

English:
theorem C_injective
  statement: Function.Injective (RatFunc.C (K := K))
  proof: by
  rw [← algebraMap_comp_C]; rw [RingHom.coe_comp]
  exact Function.Injective.comp (algebraMap_injective K) (Polynomial.C_injective)

中文:
定理 C_injective
  结论: Function.Injective (RatFunc.C (K := K))
  证明: by
  rw [← algebraMap_comp_C]; rw [RingHom.coe_comp]
  exact Function.Injective.comp (algebraMap_injective K) (Polynomial.C_injective)

Depends on / 依赖: C_injective, Function, Function.Injective.comp, Injective, Polynomial, Polynomial.C_injective, RingHom, RingHom.coe_comp, algebraMap_comp_C, algebraMap_injective, coe_comp
-/
theorem C_injective : Function.Injective (RatFunc.C (K := K)) := by
  rw [← algebraMap_comp_C]; rw [RingHom.coe_comp]
  exact Function.Injective.comp (algebraMap_injective K) (Polynomial.C_injective)

/--
Definition of `X` / `X` 的定义

English:
definition X
  signature: : K⟮X⟯
  body: algebraMap K[X] K⟮X⟯ Polynomial.X

@[simp]

中文:
定义 X
  签名: : K⟮X⟯
  定义体: algebraMap K[X] K⟮X⟯ Polynomial.X

@[simp]

Depends on / 依赖: Polynomial, Polynomial.X, algebraMap
-/
def X : K⟮X⟯ :=
  algebraMap K[X] K⟮X⟯ Polynomial.X

@[simp]
/--
theorem `algebraMap_X` / 定理 `algebraMap_X`

English:
theorem algebraMap_X
  statement: algebraMap K[X] K⟮X⟯ Polynomial.X = X
  proof: rfl

@[simp]

中文:
定理 algebraMap_X
  结论: algebraMap K[X] K⟮X⟯ Polynomial.X = X
  证明: rfl

@[simp]
-/
theorem algebraMap_X : algebraMap K[X] K⟮X⟯ Polynomial.X = X :=
  rfl

@[simp]
/--
theorem `algebraMap_monomial` / 定理 `algebraMap_monomial`

English:
theorem algebraMap_monomial
  given: (n : Nat) (a : K)
  proof: by
  simp [← Polynomial.C_mul_X_pow_eq_monomial]

@[simp]

中文:
定理 algebraMap_monomial
  条件: (n : 自然数) (a : K)
  证明: by
  simp [← Polynomial.C_mul_X_pow_eq_monomial]

@[simp]

Depends on / 依赖: C_mul_X_pow_eq_monomial, Polynomial, Polynomial.C_mul_X_pow_eq_monomial
-/
theorem algebraMap_monomial (n : Nat) (a : K) :
    algebraMap K[X] K⟮X⟯ (Polynomial.monomial n a) = C a * X ^ n := by
  simp [← Polynomial.C_mul_X_pow_eq_monomial]

@[simp]
/--
theorem `aeval_X_left_eq_algebraMap` / 定理 `aeval_X_left_eq_algebraMap`

English:
theorem aeval_X_left_eq_algebraMap
  given: (p : K[X])
  proof: by
  induction p using Polynomial.induction_on' <;> simp_all

@[simp]

中文:
定理 aeval_X_left_eq_algebraMap
  条件: (p : K[X])
  证明: by
  induction p using Polynomial.induction_on' <;> simp_all

@[simp]

Depends on / 依赖: Polynomial, Polynomial.induction_on, induction_on
-/
theorem aeval_X_left_eq_algebraMap (p : K[X]) :
    p.aeval (X : K⟮X⟯) = algebraMap K[X] K⟮X⟯ p := by
  induction p using Polynomial.induction_on' <;> simp_all

@[simp]
/--
theorem `coePolynomial_eq_algebraMap` / 定理 `coePolynomial_eq_algebraMap`

English:
theorem coePolynomial_eq_algebraMap
  given: (p : K[X])
  proof: rfl

@[simp]

中文:
定理 coePolynomial_eq_algebraMap
  条件: (p : K[X])
  证明: rfl

@[simp]
-/
theorem coePolynomial_eq_algebraMap (p : K[X]) :
    (p : RatFunc K) = algebraMap (Polynomial K) (RatFunc K) p := rfl

@[simp]
/--
lemma `liftRingHom_C` / 引理 `liftRingHom_C`

English:
lemma liftRingHom_C
  given: {L : Type*} [Field L] (φ : K[X] ->+* L) (hφ : K[X]⁰ <= L⁰.comap φ) (x : K)
  proof: RatFunc.liftRingHom_algebraMap _ _ _

@[simp]

中文:
引理 liftRingHom_C
  条件: {L : 类型} [Field L] (φ : K[X] ->+* L) (hφ : K[X]⁰ <= L⁰.comap φ) (x : K)
  证明: RatFunc.liftRingHom_algebraMap _ _ _

@[simp]

Depends on / 依赖: RatFunc, RatFunc.liftRingHom_algebraMap, liftRingHom_algebraMap
-/
lemma liftRingHom_C {L : Type*} [Field L] (φ : K[X] ->+* L) (hφ : K[X]⁰ <= L⁰.comap φ) (x : K) :
    liftRingHom φ hφ (C x) = φ (.C x) :=
  RatFunc.liftRingHom_algebraMap _ _ _

@[simp]
/--
lemma `liftRingHom_X` / 引理 `liftRingHom_X`

English:
lemma liftRingHom_X
  given: {L : Type*} [Field L] (φ : K[X] ->+* L) (hφ : K[X]⁰ <= L⁰.comap φ)
  proof: RatFunc.liftRingHom_algebraMap _ _ _

中文:
引理 liftRingHom_X
  条件: {L : 类型} [Field L] (φ : K[X] ->+* L) (hφ : K[X]⁰ <= L⁰.comap φ)
  证明: RatFunc.liftRingHom_algebraMap _ _ _

Depends on / 依赖: RatFunc, RatFunc.liftRingHom_algebraMap, liftRingHom_algebraMap
-/
lemma liftRingHom_X {L : Type*} [Field L] (φ : K[X] ->+* L) (hφ : K[X]⁰ <= L⁰.comap φ) :
    RatFunc.liftRingHom φ hφ X = φ (.X) :=
  RatFunc.liftRingHom_algebraMap _ _ _

end Domain

section Field

variable [Field K]

@[simp]
/--
theorem `num_C` / 定理 `num_C`

English:
theorem num_C
  given: (c : K)
  statement: num (C c) = Polynomial.C c
  proof: num_algebraMap _

@[simp]

中文:
定理 num_C
  条件: (c : K)
  结论: num (C c) = Polynomial.C c
  证明: num_algebraMap _

@[simp]

Depends on / 依赖: num_algebraMap
-/
theorem num_C (c : K) : num (C c) = Polynomial.C c :=
  num_algebraMap _

@[simp]
/--
theorem `denom_C` / 定理 `denom_C`

English:
theorem denom_C
  given: (c : K)
  statement: denom (C c) = 1
  proof: denom_algebraMap _

@[simp]

中文:
定理 denom_C
  条件: (c : K)
  结论: denom (C c) = 1
  证明: denom_algebraMap _

@[simp]

Depends on / 依赖: denom_algebraMap
-/
theorem denom_C (c : K) : denom (C c) = 1 :=
  denom_algebraMap _

@[simp]
/--
theorem `num_X` / 定理 `num_X`

English:
theorem num_X
  statement: num (X : K⟮X⟯) = Polynomial.X
  proof: num_algebraMap _

@[simp]

中文:
定理 num_X
  结论: num (X : K⟮X⟯) = Polynomial.X
  证明: num_algebraMap _

@[simp]

Depends on / 依赖: num_algebraMap
-/
theorem num_X : num (X : K⟮X⟯) = Polynomial.X :=
  num_algebraMap _

@[simp]
/--
theorem `denom_X` / 定理 `denom_X`

English:
theorem denom_X
  statement: denom (X : K⟮X⟯) = 1
  proof: denom_algebraMap _

中文:
定理 denom_X
  结论: denom (X : K⟮X⟯) = 1
  证明: denom_algebraMap _

Depends on / 依赖: denom_algebraMap
-/
theorem denom_X : denom (X : K⟮X⟯) = 1 :=
  denom_algebraMap _

/--
theorem `X_ne_zero` / 定理 `X_ne_zero`

English:
theorem X_ne_zero
  statement: (X : K⟮X⟯) != 0
  proof: RatFunc.algebraMap_ne_zero Polynomial.X_ne_zero

中文:
定理 X_ne_zero
  结论: (X : K⟮X⟯) != 0
  证明: RatFunc.algebraMap_ne_zero Polynomial.X_ne_zero

Depends on / 依赖: Polynomial, Polynomial.X_ne_zero, RatFunc, RatFunc.algebraMap_ne_zero, X_ne_zero, algebraMap_ne_zero
-/
theorem X_ne_zero : (X : K⟮X⟯) != 0 :=
  RatFunc.algebraMap_ne_zero Polynomial.X_ne_zero

/--
theorem `eq_C_iff` / 定理 `eq_C_iff`

English:
theorem eq_C_iff
  given: (f : K⟮X⟯)
  proof: by
  refine ⟨by rintro ⟨c, rfl⟩; simp, ?_⟩
  rw [Polynomial.natDegree_eq_zero]; rw [Polynomial.natDegree_eq_zero]
  rintro ⟨⟨a, ha⟩, ⟨b, hb⟩⟩
  use a / b
  rw [← num_div_denom f]; rw [← ha]; rw [← hb]; rw [algebraMap_C]; rw [algebraMap_C]; rw [map_div₀]

中文:
定理 eq_C_iff
  条件: (f : K⟮X⟯)
  证明: by
  refine ⟨by rintro ⟨c, rfl⟩; simp, ?_⟩
  rw [Polynomial.natDegree_eq_zero]; rw [Polynomial.natDegree_eq_zero]
  rintro ⟨⟨a, ha⟩, ⟨b, hb⟩⟩
  use a / b
  rw [← num_div_denom f]; rw [← ha]; rw [← hb]; rw [algebraMap_C]; rw [algebraMap_C]; rw [map_div₀]

Depends on / 依赖: Polynomial, Polynomial.natDegree_eq_zero, algebraMap_C, natDegree_eq_zero, num_div_denom
-/
theorem eq_C_iff (f : K⟮X⟯) :
    (exists c, f = C c) ↔ f.num.natDegree = 0 ∧ f.denom.natDegree = 0 := by
  refine ⟨by rintro ⟨c, rfl⟩; simp, ?_⟩
  rw [Polynomial.natDegree_eq_zero]; rw [Polynomial.natDegree_eq_zero]
  rintro ⟨⟨a, ha⟩, ⟨b, hb⟩⟩
  use a / b
  rw [← num_div_denom f]; rw [← ha]; rw [← hb]; rw [algebraMap_C]; rw [algebraMap_C]; rw [map_div₀]

variable {L : Type u} [Field L]

/--
Definition of `eval` / `eval` 的定义

English:
definition eval
  signature: (f : K ->+* L) (a : L) (p : K⟮X⟯)
  body: (num p).eval₂ f a / (denom p).eval₂ f a

中文:
定义 eval
  签名: (f : K ->+* L) (a : L) (p : K⟮X⟯)
  定义体: (num p).eval₂ f a / (denom p).eval₂ f a
-/
def eval (f : K ->+* L) (a : L) (p : K⟮X⟯) : L :=
  (num p).eval₂ f a / (denom p).eval₂ f a

variable {f : K ->+* L} {a : L}

/--
theorem `eval_eq_zero_of_eval₂_denom_eq_zero` / 定理 `eval_eq_zero_of_eval₂_denom_eq_zero`

English:
theorem eval_eq_zero_of_eval₂_denom_eq_zero
  statement: {x : K⟮X⟯}
  proof: by rw [eval, h, div_zero]

中文:
定理 eval_eq_zero_of_eval₂_denom_eq_zero
  结论: {x : K⟮X⟯}
  证明: by rw [eval, h, div_zero]

Depends on / 依赖: div_zero
-/
theorem eval_eq_zero_of_eval₂_denom_eq_zero {x : K⟮X⟯}
    (h : Polynomial.eval₂ f a (denom x) = 0) : eval f a x = 0 := by rw [eval, h, div_zero]

/--
theorem `eval₂_denom_ne_zero` / 定理 `eval₂_denom_ne_zero`

English:
theorem eval₂_denom_ne_zero
  given: {x : K⟮X⟯} (h : eval f a x != 0)
  proof: mt eval_eq_zero_of_eval₂_denom_eq_zero h

中文:
定理 eval₂_denom_ne_zero
  条件: {x : K⟮X⟯} (h : eval f a x != 0)
  证明: mt eval_eq_zero_of_eval₂_denom_eq_zero h
-/
theorem eval₂_denom_ne_zero {x : K⟮X⟯} (h : eval f a x != 0) :
    Polynomial.eval₂ f a (denom x) != 0 :=
  mt eval_eq_zero_of_eval₂_denom_eq_zero h

variable (f a)

@[simp]
/--
theorem `eval_C` / 定理 `eval_C`

English:
theorem eval_C
  given: {c : K}
  statement: eval f a (C c) = f c
  proof: by simp [eval]

@[simp]

中文:
定理 eval_C
  条件: {c : K}
  结论: eval f a (C c) = f c
  证明: by simp [eval]

@[simp]
-/
theorem eval_C {c : K} : eval f a (C c) = f c := by simp [eval]

@[simp]
/--
theorem `eval_X` / 定理 `eval_X`

English:
theorem eval_X
  statement: eval f a X = a
  proof: by simp [eval]

@[simp]

中文:
定理 eval_X
  结论: eval f a X = a
  证明: by simp [eval]

@[simp]
-/
theorem eval_X : eval f a X = a := by simp [eval]

@[simp]
/--
theorem `eval_zero` / 定理 `eval_zero`

English:
theorem eval_zero
  statement: eval f a 0 = 0
  proof: by simp [eval]

@[simp]

中文:
定理 eval_zero
  结论: eval f a 0 = 0
  证明: by simp [eval]

@[simp]
-/
theorem eval_zero : eval f a 0 = 0 := by simp [eval]

@[simp]
/--
theorem `eval_one` / 定理 `eval_one`

English:
theorem eval_one
  statement: eval f a 1 = 1
  proof: by simp [eval]

@[simp]

中文:
定理 eval_one
  结论: eval f a 1 = 1
  证明: by simp [eval]

@[simp]
-/
theorem eval_one : eval f a 1 = 1 := by simp [eval]

@[simp]
/--
theorem `eval_algebraMap` / 定理 `eval_algebraMap`

English:
theorem eval_algebraMap
  given: {S : Type*} [CommSemiring S] [Algebra S K[X]] (p : S)
  proof: by
  simp [eval, IsScalarTower.algebraMap_apply S K[X] K⟮X⟯]

中文:
定理 eval_algebraMap
  条件: {S : 类型} [CommSemiring S] [Algebra S K[X]] (p : S)
  证明: by
  simp [eval, IsScalarTower.algebraMap_apply S K[X] K⟮X⟯]

Depends on / 依赖: IsScalarTower, IsScalarTower.algebraMap_apply, algebraMap_apply
-/
theorem eval_algebraMap {S : Type*} [CommSemiring S] [Algebra S K[X]] (p : S) :
    eval f a (algebraMap _ _ p) = (algebraMap _ K[X] p).eval₂ f a := by
  simp [eval, IsScalarTower.algebraMap_apply S K[X] K⟮X⟯]

/--
theorem `eval_add` / 定理 `eval_add`

English:
theorem eval_add
  statement: {x y : K⟮X⟯} (hx : Polynomial.eval₂ f a (denom x) != 0)
  proof: by
  unfold eval
  by_cases hxy : Polynomial.eval₂ f a (denom (x + y)) = 0
  · have := Polynomial.eval₂_eq_zero_of_dvd_of_eval₂_eq_zero f a (denom_add_dvd x y) hxy
    rw [Polynomial.eval₂_mul] at this
    cases mul_eq_zero.mp this <;> contradiction
  rw [div_add_div _ _ hx hy]; rw [eq_div_iff (mul_

中文:
定理 eval_add
  结论: {x y : K⟮X⟯} (hx : Polynomial.eval₂ f a (denom x) != 0)
  证明: by
  unfold eval
  by_cases hxy : Polynomial.eval₂ f a (denom (x + y)) = 0
  · have := Polynomial.eval₂_eq_zero_of_dvd_of_eval₂_eq_zero f a (denom_add_dvd x y) hxy
    rw [Polynomial.eval₂_mul] at this
    cases mul_eq_zero.mp this <;> contradiction
  rw [div_add_div _ _ hx hy]; rw [eq_div_iff (mul_

Depends on / 依赖: Polynomial, Polynomial.eval, denom_add_dvd, div_add_div, div_eq_iff, div_eq_mul_inv, eq_div_iff, mul_eq_zero, mul_eq_zero.mp, mul_ne_zero, mul_right_comm, num_denom_add
-/
theorem eval_add {x y : K⟮X⟯} (hx : Polynomial.eval₂ f a (denom x) != 0)
    (hy : Polynomial.eval₂ f a (denom y) != 0) : eval f a (x + y) = eval f a x + eval f a y := by
  unfold eval
  by_cases hxy : Polynomial.eval₂ f a (denom (x + y)) = 0
  · have := Polynomial.eval₂_eq_zero_of_dvd_of_eval₂_eq_zero f a (denom_add_dvd x y) hxy
    rw [Polynomial.eval₂_mul] at this
    cases mul_eq_zero.mp this <;> contradiction
  rw [div_add_div _ _ hx hy]; rw [eq_div_iff (mul_ne_zero hx hy)]; rw [div_eq_mul_inv]; rw [mul_right_comm]; rw [←
    div_eq_mul_inv]; rw [div_eq_iff hxy]
  simp only [← Polynomial.eval₂_mul, ← Polynomial.eval₂_add]
  congr 1
  apply num_denom_add

/--
theorem `eval_mul` / 定理 `eval_mul`

English:
theorem eval_mul
  statement: {x y : K⟮X⟯} (hx : Polynomial.eval₂ f a (denom x) != 0)
  proof: by
  unfold eval
  by_cases hxy : Polynomial.eval₂ f a (denom (x * y)) = 0
  · have := Polynomial.eval₂_eq_zero_of_dvd_of_eval₂_eq_zero f a (denom_mul_dvd x y) hxy
    rw [Polynomial.eval₂_mul] at this
    cases mul_eq_zero.mp this <;> contradiction
  rw [div_mul_div_comm]; rw [eq_div_iff (mul_ne_ze

中文:
定理 eval_mul
  结论: {x y : K⟮X⟯} (hx : Polynomial.eval₂ f a (denom x) != 0)
  证明: by
  unfold eval
  by_cases hxy : Polynomial.eval₂ f a (denom (x * y)) = 0
  · have := Polynomial.eval₂_eq_zero_of_dvd_of_eval₂_eq_zero f a (denom_mul_dvd x y) hxy
    rw [Polynomial.eval₂_mul] at this
    cases mul_eq_zero.mp this <;> contradiction
  rw [div_mul_div_comm]; rw [eq_div_iff (mul_ne_ze

Depends on / 依赖: Polynomial, Polynomial.eval, denom_mul_dvd, div_eq_iff, div_eq_mul_inv, div_mul_div_comm, eq_div_iff, mul_eq_zero, mul_eq_zero.mp, mul_ne_zero, mul_right_comm, num_denom_mul, repeat
-/
theorem eval_mul {x y : K⟮X⟯} (hx : Polynomial.eval₂ f a (denom x) != 0)
    (hy : Polynomial.eval₂ f a (denom y) != 0) : eval f a (x * y) = eval f a x * eval f a y := by
  unfold eval
  by_cases hxy : Polynomial.eval₂ f a (denom (x * y)) = 0
  · have := Polynomial.eval₂_eq_zero_of_dvd_of_eval₂_eq_zero f a (denom_mul_dvd x y) hxy
    rw [Polynomial.eval₂_mul] at this
    cases mul_eq_zero.mp this <;> contradiction
  rw [div_mul_div_comm]; rw [eq_div_iff (mul_ne_zero hx hy)]; rw [div_eq_mul_inv]; rw [mul_right_comm]; rw [←
    div_eq_mul_inv]; rw [div_eq_iff hxy]
  repeat' rw [← Polynomial.eval₂_mul]
  congr 1
  apply num_denom_mul

end Field

end Eval

section algEquivOfTranscendental

open Polynomial IntermediateField algebraAdjoinAdjoin

variable {K L : Type*} [Field K] [Field L] [Algebra K L] (f : L) (h : Transcendental K f)

/--
Definition of `algEquivOfTranscendental` / `algEquivOfTranscendental` 的定义

English:
definition algEquivOfTranscendental
  signature: : RatFunc K ≃ₐ[K] K⟮f⟯
  body: IsFractionRing.algEquivOfAlgEquiv (Polynomial.algEquivOfTranscendental K f h)

@[simp]

中文:
定义 algEquivOfTranscendental
  签名: : RatFunc K ≃ₐ[K] K⟮f⟯
  定义体: IsFractionRing.algEquivOfAlgEquiv (Polynomial.algEquivOfTranscendental K f h)

@[simp]

Depends on / 依赖: IsFractionRing, IsFractionRing.algEquivOfAlgEquiv, Polynomial, Polynomial.algEquivOfTranscendental, algEquivOfAlgEquiv, algEquivOfTranscendental
-/
noncomputable def algEquivOfTranscendental : RatFunc K ≃ₐ[K] K⟮f⟯ :=
  IsFractionRing.algEquivOfAlgEquiv (Polynomial.algEquivOfTranscendental K f h)

@[simp]
/--
theorem `algEquivOfTranscendental_algebraMap` / 定理 `algEquivOfTranscendental_algebraMap`

English:
theorem algEquivOfTranscendental_algebraMap
  given: (g : K[X])
  proof: by
  ext
  simp [algEquivOfTranscendental]

@[simp]

中文:
定理 algEquivOfTranscendental_algebraMap
  条件: (g : K[X])
  证明: by
  ext
  simp [algEquivOfTranscendental]

@[simp]

Depends on / 依赖: algEquivOfTranscendental
-/
theorem algEquivOfTranscendental_algebraMap (g : K[X]) :
    algEquivOfTranscendental f h (algebraMap K[X] (RatFunc K) g) =
    aeval (AdjoinSimple.gen K f) g := by
  ext
  simp [algEquivOfTranscendental]

@[simp]
/--
theorem `algEquivOfTranscendental_X` / 定理 `algEquivOfTranscendental_X`

English:
theorem algEquivOfTranscendental_X
  proof: by
  simp [← algebraMap_X]

中文:
定理 algEquivOfTranscendental_X
  证明: by
  simp [← algebraMap_X]

Depends on / 依赖: algebraMap_X
-/
theorem algEquivOfTranscendental_X :
    algEquivOfTranscendental f h (X : RatFunc K) = f := by
  simp [← algebraMap_X]

/--
theorem `algEquivOfTranscendental_apply` / 定理 `algEquivOfTranscendental_apply`

English:
theorem algEquivOfTranscendental_apply
  given: (u : RatFunc K)
  proof: by
  conv_lhs => rw [← num_div_denom u]
  simp [-num_div_denom]

@[simp]

中文:
定理 algEquivOfTranscendental_apply
  条件: (u : RatFunc K)
  证明: by
  conv_lhs => rw [← num_div_denom u]
  simp [-num_div_denom]

@[simp]

Depends on / 依赖: conv_lhs, num_div_denom
-/
theorem algEquivOfTranscendental_apply (u : RatFunc K) :
    algEquivOfTranscendental f h u = aeval f u.num / aeval f u.denom := by
  conv_lhs => rw [← num_div_denom u]
  simp [-num_div_denom]

@[simp]
/--
theorem `algEquivOfTranscendental_symm_aeval` / 定理 `algEquivOfTranscendental_symm_aeval`

English:
theorem algEquivOfTranscendental_symm_aeval
  given: (g : K[X])
  proof: by
  simp [algEquivOfTranscendental, ← algebraMap_eq_gen_self, aeval_algebraMap_apply]

@[simp]

中文:
定理 algEquivOfTranscendental_symm_aeval
  条件: (g : K[X])
  证明: by
  simp [algEquivOfTranscendental, ← algebraMap_eq_gen_self, aeval_algebraMap_apply]

@[simp]

Depends on / 依赖: aeval_algebraMap_apply, algEquivOfTranscendental, algebraMap_eq_gen_self
-/
theorem algEquivOfTranscendental_symm_aeval (g : K[X]) :
    (algEquivOfTranscendental f h).symm (aeval (AdjoinSimple.gen _ f) g) = algebraMap _ _ g := by
  simp [algEquivOfTranscendental, ← algebraMap_eq_gen_self, aeval_algebraMap_apply]

@[simp]
/--
theorem `algEquivOfTranscendental_symm_gen` / 定理 `algEquivOfTranscendental_symm_gen`

English:
theorem algEquivOfTranscendental_symm_gen
  proof: by
  simp [algEquivOfTranscendental, ← algebraMap_eq_gen_self]

中文:
定理 algEquivOfTranscendental_symm_gen
  证明: by
  simp [algEquivOfTranscendental, ← algebraMap_eq_gen_self]

Depends on / 依赖: algEquivOfTranscendental, algebraMap_eq_gen_self
-/
theorem algEquivOfTranscendental_symm_gen :
    (algEquivOfTranscendental f h).symm (AdjoinSimple.gen _ f) = (X : RatFunc K) := by
  simp [algEquivOfTranscendental, ← algebraMap_eq_gen_self]

end algEquivOfTranscendental

section Algebra

variable [CommRing K] [IsDomain K]

/--
lemma `transcendental_X` / 引理 `transcendental_X`

English:
lemma transcendental_X
  statement: Transcendental K (X : K⟮X⟯)
  proof: by
  rw [← RatFunc.algebraMap_X]; rw [transcendental_algebraMap_iff (algebraMap_injective K)]
  exact Polynomial.transcendental_X K

中文:
引理 transcendental_X
  结论: Transcendental K (X : K⟮X⟯)
  证明: by
  rw [← RatFunc.algebraMap_X]; rw [transcendental_algebraMap_iff (algebraMap_injective K)]
  exact Polynomial.transcendental_X K

Depends on / 依赖: Polynomial, Polynomial.transcendental_X, RatFunc, RatFunc.algebraMap_X, algebraMap_X, algebraMap_injective, transcendental_X, transcendental_algebraMap_iff
-/
lemma transcendental_X : Transcendental K (X : K⟮X⟯) := by
  rw [← RatFunc.algebraMap_X]; rw [transcendental_algebraMap_iff (algebraMap_injective K)]
  exact Polynomial.transcendental_X K

/--
Instance `transcendental` / 实例 `transcendental`

English:
instance transcendental
  signature: : Algebra.Transcendental K K⟮X⟯
  body: ⟨X, transcendental_X⟩

中文:
实例 transcendental
  签名: : Algebra.Transcendental K K⟮X⟯
  定义体: ⟨X, transcendental_X⟩

Depends on / 依赖: transcendental_X
-/
instance transcendental : Algebra.Transcendental K K⟮X⟯ := ⟨X, transcendental_X⟩

end Algebra

end RatFunc

section AdicValuation

variable (K : Type*) [Field K]

namespace Polynomial

open RatFunc

section HeightOneSpectrum

open IsDedekindDomain.HeightOneSpectrum WithZero

set_option linter.style.whitespace false in -- manual alignment is not recognised
/--
Definition of `idealX` / `idealX` 的定义

English:
definition idealX
  signature: : IsDedekindDomain.HeightOneSpectrum K[X] where
  body: Ideal.span {X}
  isPrime := by rw [Ideal.span_singleton_prime]; exacts [Polynomial.prime_X, Polynomial.X_ne_zero]
  ne_bot := by rw [ne_eq, Ideal.span_singleton_eq_bot]; exact Polynomial.X_ne_zero

@[simp]

中文:
定义 idealX
  签名: : IsDedekindDomain.HeightOneSpectrum K[X] where
  定义体: Ideal.span {X}
  isPrime := by rw [Ideal.span_singleton_prime]; exacts [Polynomial.prime_X, Polynomial.X_ne_zero]
  ne_bot := by rw [ne_eq, Ideal.span_singleton_eq_bot]; exact Polynomial.X_ne_zero

@[simp]

Depends on / 依赖: Ideal.span
-/
def idealX : IsDedekindDomain.HeightOneSpectrum K[X] where
  asIdeal := Ideal.span {X}
  isPrime := by rw [Ideal.span_singleton_prime]; exacts [Polynomial.prime_X, Polynomial.X_ne_zero]
  ne_bot := by rw [ne_eq, Ideal.span_singleton_eq_bot]; exact Polynomial.X_ne_zero

@[simp]
/--
theorem `idealX_span` / 定理 `idealX_span`

English:
theorem idealX_span
  statement: (idealX K).asIdeal = Ideal.span {X}
  proof: rfl

@[simp]

中文:
定理 idealX_span
  结论: (idealX K).asIdeal = Ideal.span {X}
  证明: rfl

@[simp]
-/
theorem idealX_span : (idealX K).asIdeal = Ideal.span {X} := rfl

@[simp]
/--
theorem `valuation_X_eq_neg_one` / 定理 `valuation_X_eq_neg_one`

English:
theorem valuation_X_eq_neg_one
  proof: by
  rw [← RatFunc.algebraMap_X]; rw [valuation_of_algebraMap]; rw [intValuation_singleton
      _ (Polynomial.X_ne_zero) (idealX_span K)]

中文:
定理 valuation_X_eq_neg_one
  证明: by
  rw [← RatFunc.algebraMap_X]; rw [valuation_of_algebraMap]; rw [intValuation_singleton
      _ (Polynomial.X_ne_zero) (idealX_span K)]

Depends on / 依赖: Polynomial, Polynomial.X_ne_zero, RatFunc, RatFunc.algebraMap_X, X_ne_zero, algebraMap_X, idealX_span, intValuation_singleton, valuation_of_algebraMap
-/
theorem valuation_X_eq_neg_one :
    (idealX K).valuation K⟮X⟯ RatFunc.X = exp (-1 : Int) := by
  rw [← RatFunc.algebraMap_X]; rw [valuation_of_algebraMap]; rw [intValuation_singleton
      _ (Polynomial.X_ne_zero) (idealX_span K)]

/--
theorem `valuation_of_mk` / 定理 `valuation_of_mk`

English:
theorem valuation_of_mk
  given: (f : Polynomial K) {g : Polynomial K} (hg : g != 0)
  proof: by
  simp only [RatFunc.mk_eq_mk' _ hg, valuation_of_mk']

中文:
定理 valuation_of_mk
  条件: (f : Polynomial K) {g : Polynomial K} (hg : g != 0)
  证明: by
  simp only [RatFunc.mk_eq_mk' _ hg, valuation_of_mk']

Depends on / 依赖: RatFunc, RatFunc.mk_eq_mk, mk_eq_mk, valuation_of_mk
-/
theorem valuation_of_mk (f : Polynomial K) {g : Polynomial K} (hg : g != 0) :
    (Polynomial.idealX K).valuation _ (RatFunc.mk f g) =
      (Polynomial.idealX K).intValuation f / (Polynomial.idealX K).intValuation g := by
  simp only [RatFunc.mk_eq_mk' _ hg, valuation_of_mk']

end HeightOneSpectrum

section TrivialOnConstants

variable {Γ : Type*} [LinearOrderedCommGroupWithZero Γ]

variable {v : Valuation K⟮X⟯ Γ} [hv : v.IsTrivialOn K]

open Valuation

/--
lemma `valuation_monomial_eq_valuation_X_pow` / 引理 `valuation_monomial_eq_valuation_X_pow`

English:
lemma valuation_monomial_eq_valuation_X_pow
  given: (n : Nat) {a : K} (ha : a != 0)
  proof: by
  simp_all [← RatFunc.algebraMap_eq_C, hv.eq_one]

中文:
引理 valuation_monomial_eq_valuation_X_pow
  条件: (n : 自然数) {a : K} (ha : a != 0)
  证明: by
  simp_all [← RatFunc.algebraMap_eq_C, hv.eq_one]

Depends on / 依赖: RatFunc, RatFunc.algebraMap_eq_C, algebraMap_eq_C, eq_one, hv.eq_one
-/
lemma valuation_monomial_eq_valuation_X_pow (n : Nat) {a : K} (ha : a != 0) :
    v (monomial n a) = v RatFunc.X ^ n := by
  simp_all [← RatFunc.algebraMap_eq_C, hv.eq_one]

/--
theorem `valuation_eq_valuation_X_pow_natDegree_of_one_lt_valuation_X` / 定理 `valuation_eq_valuation_X_pow_natDegree_of_one_lt_valuation_X`

English:
theorem valuation_eq_valuation_X_pow_natDegree_of_one_lt_valuation_X
  proof: by
  convert! valuation_aeval_eq_valuation_X_pow_natDegree_of_one_lt_valuation_X .X hlt hp
  ext p
  nth_rw 1 [RatFunc.X, ← aeval_X_left_apply p (R := K)]
  exact (aeval_algebraMap_apply K⟮X⟯ X p).symm

中文:
定理 valuation_eq_valuation_X_pow_natDegree_of_one_lt_valuation_X
  证明: by
  convert! valuation_aeval_eq_valuation_X_pow_natDegree_of_one_lt_valuation_X .X hlt hp
  ext p
  nth_rw 1 [RatFunc.X, ← aeval_X_left_apply p (R := K)]
  exact (aeval_algebraMap_apply K⟮X⟯ X p).symm

Depends on / 依赖: RatFunc, RatFunc.X, aeval_X_left_apply, aeval_algebraMap_apply, convert, nth_rw, valuation_aeval_eq_valuation_X_pow_natDegree_of_one_lt_valuation_X
-/
theorem valuation_eq_valuation_X_pow_natDegree_of_one_lt_valuation_X
     (hlt : 1 < v RatFunc.X) {p : K[X]} (hp : p != 0) : v p = v RatFunc.X ^ p.natDegree := by
  convert! valuation_aeval_eq_valuation_X_pow_natDegree_of_one_lt_valuation_X .X hlt hp
  ext p
  nth_rw 1 [RatFunc.X, ← aeval_X_left_apply p (R := K)]
  exact (aeval_algebraMap_apply K⟮X⟯ X p).symm


/--
theorem `valuation_le_one_of_valuation_X_le_one` / 定理 `valuation_le_one_of_valuation_X_le_one`

English:
theorem valuation_le_one_of_valuation_X_le_one
  given: (hle : v RatFunc.X <= 1) (p : K[X])
  statement: v p <= 1
  proof: by
  rw [as_sum_range p]; rw [RatFunc.coePolynomial]; rw [map_sum]
  apply map_sum_le v
  intro i
  by_cases h0 : p.coeff i = 0
  · simp_all
  · rw [← RatFunc.coePolynomial]
    simp_all [pow_le_one', ← RatFunc.algebraMap_eq_C, hv.eq_one _ h0]

中文:
定理 valuation_le_one_of_valuation_X_le_one
  条件: (hle : v RatFunc.X <= 1) (p : K[X])
  结论: v p <= 1
  证明: by
  rw [as_sum_range p]; rw [RatFunc.coePolynomial]; rw [map_sum]
  apply map_sum_le v
  intro i
  by_cases h0 : p.coeff i = 0
  · simp_all
  · rw [← RatFunc.coePolynomial]
    simp_all [pow_le_one', ← RatFunc.algebraMap_eq_C, hv.eq_one _ h0]

Depends on / 依赖: RatFunc, RatFunc.algebraMap_eq_C, RatFunc.coePolynomial, algebraMap_eq_C, as_sum_range, coePolynomial, eq_one, hv.eq_one, map_sum, map_sum_le, p.coeff, pow_le_one
-/
theorem valuation_le_one_of_valuation_X_le_one (hle : v RatFunc.X <= 1) (p : K[X]) : v p <= 1 := by
  rw [as_sum_range p]; rw [RatFunc.coePolynomial]; rw [map_sum]
  apply map_sum_le v
  intro i
  by_cases h0 : p.coeff i = 0
  · simp_all
  · rw [← RatFunc.coePolynomial]
    simp_all [pow_le_one', ← RatFunc.algebraMap_eq_C, hv.eq_one _ h0]

/--
lemma `valuation_inv_monomial_eq_valuation_X_zpow` / 引理 `valuation_inv_monomial_eq_valuation_X_zpow`

English:
lemma valuation_inv_monomial_eq_valuation_X_zpow
  given: (n : Nat) {a : K} (ha : a != 0)
  proof: by
  simp [← RatFunc.algebraMap_eq_C, hv.eq_one _ ha]

中文:
引理 valuation_inv_monomial_eq_valuation_X_zpow
  条件: (n : 自然数) {a : K} (ha : a != 0)
  证明: by
  simp [← RatFunc.algebraMap_eq_C, hv.eq_one _ ha]

Depends on / 依赖: RatFunc, RatFunc.algebraMap_eq_C, algebraMap_eq_C, eq_one, hv.eq_one
-/
lemma valuation_inv_monomial_eq_valuation_X_zpow (n : Nat) {a : K} (ha : a != 0) :
    v (1 / monomial n a) = v RatFunc.X ^ (-(n : Int)) := by
  simp [← RatFunc.algebraMap_eq_C, hv.eq_one _ ha]

end TrivialOnConstants

end Polynomial

namespace RatFunc

open scoped WithZero

open Polynomial

/--
Instance `valuedRatFunc` / 实例 `valuedRatFunc`

English:
instance valuedRatFunc
  signature: : Valued K⟮X⟯ Intᵐ⁰
  body: Valued.mk' ((idealX K).valuation _)

@[simp]

中文:
实例 valuedRatFunc
  签名: : Valued K⟮X⟯ 整数ᵐ⁰
  定义体: Valued.mk' ((idealX K).valuation _)

@[simp]

Depends on / 依赖: Valued, Valued.mk, idealX, valuation
-/
instance valuedRatFunc : Valued K⟮X⟯ Intᵐ⁰ := Valued.mk' ((idealX K).valuation _)

@[simp]
/--
theorem `v_def` / 定理 `v_def`

English:
theorem v_def
  given: {x : K⟮X⟯}
  proof: rfl

中文:
定理 v_def
  条件: {x : K⟮X⟯}
  证明: rfl
-/
theorem v_def {x : K⟮X⟯} :
    Valued.v x = (idealX K).valuation _ x := rfl

/--
lemma `valuation_surjective` / 引理 `valuation_surjective`

English:
lemma valuation_surjective
  statement: Function.Surjective (Valued.v (R := RatFunc K))
  proof: by
  intro n
  by_cases hn0 : n = 0
  · use 0; simp [hn0]
  · use (RatFunc.X ^ (-WithZero.log n))
    simp [WithZero.exp_log hn0]

中文:
引理 valuation_surjective
  结论: Function.Surjective (Valued.v (R := RatFunc K))
  证明: by
  intro n
  by_cases hn0 : n = 0
  · use 0; simp [hn0]
  · use (RatFunc.X ^ (-WithZero.log n))
    simp [WithZero.exp_log hn0]

Depends on / 依赖: RatFunc, RatFunc.X, WithZero, WithZero.exp_log, WithZero.log, exp_log
-/
lemma valuation_surjective : Function.Surjective (Valued.v (R := RatFunc K)) := by
  intro n
  by_cases hn0 : n = 0
  · use 0; simp [hn0]
  · use (RatFunc.X ^ (-WithZero.log n))
    simp [WithZero.exp_log hn0]

end RatFunc

end AdicValuation
