/-
Copyright (c) 2025 Joël Riou. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joël Riou
-/
module

public import Mathlib.CategoryTheory.Limits.Types.Pullbacks
public import Mathlib.CategoryTheory.Limits.Shapes.Pullback.IsPullback.Basic

/-!
# Pushouts in `Type`

We describe the pushout of two maps `f : S ⟶ X₁` and `g : S ⟶ X₂`
in the category of types as the quotient of `X₁ ⊕ X₂` by the
equivalence relation generated by a relation. We also study
the particular case when `f` is injective (in the file
`CategoryTheory.Types.Monomorphisms`, it is deduced that monomorphisms
are stable under cobase change in the category of types).

-/

@[expose] public section

universe u

namespace CategoryTheory.Limits.Types

/-
**CategoryTheory.Limits.Types.** 是 Mathlib 中的一个实例，位于命名空间 `CategoryTheory.Limits.
Types`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance : HasPushouts.{u} (Type u) :=
  hasPushouts_of_hasWidePushouts.{u} (Type u)

variable {S X₁ X₂ : Type u} (f : S ⟶ X₁) (g : S ⟶ X₂)

/-- The pushout of two maps `f : S ⟶ X₁` and `g : S ⟶ X₂` is the quotient
by the equivalence relation on `X₁ ⊕ X₂` generated by this relation. -/
/-
**CategoryTheory.Limits.Types.Pushout.Rel** 是 Mathlib 中的一个归纳类型，位于命名空间 `CategoryT
heory.Limits.Types.Pushout`。
形式化陈述：{S X₁ X₂ : Type u} → (S ⟶ X₁) → (S ⟶ X₂) → X₁ ⊕ X₂ → X₁ ⊕ X₂ → Prop
参数：S ⟶ X₁；S ⟶ X₂。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The pushout of two maps `f : S ⟶ X₁` and `g : S ⟶ X₂` is the quotient
by the equivalence relation on `X₁ ⊕ X₂` generated by this relation.
-/
inductive Pushout.Rel (f : S ⟶ X₁) (g : S ⟶ X₂) : X₁ ⊕ X₂ → X₁ ⊕ X₂ → Prop
  | inl_inr (s : S) : Pushout.Rel f g (Sum.inl (f s)) (Sum.inr (g s))

/-- Construction of the pushout in the category of types, as a quotient of `X₁ ⊕ X₂`. -/
/-
**CategoryTheory.Limits.Types.Pushout** 是 Mathlib 中的一个定义，位于命名空间 `CategoryTheory.
Limits.Types`。
形式化陈述：Pushout : Type u
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Construction of the pushout in the category of types, as a quotient of `X₁ ⊕ X₂`
.
-/
def Pushout : Type u := (_root_.Quot (Pushout.Rel f g))

/-- In case `f : S ⟶ X₁` is a monomorphism, this relation is the equivalence relation
generated by `Pushout.Rel f g`. -/
/-
**CategoryTheory.Limits.Types.Pushout.Rel'** 是 Mathlib 中的一个引理，位于命名空间 `CategoryTh
eory.Limits.Types.Pushout`。
形式化陈述：Rel'.symm {x y : X₁ oplus X₂} (h : Rel' f g x y) : Rel' f g y x
参数：h : Rel' f g x y。
该定理/引理描述了相关对象所满足的性质。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
In case `f : S ⟶ X₁` is a monomorphism, this relation is the equivalence relatio
n
generated by `Pushout.Rel f g`.
-/
inductive Pushout.Rel' : X₁ ⊕ X₂ → X₁ ⊕ X₂ → Prop
  | refl (x : X₁ ⊕ X₂) : Rel' x x
  | inl_inl (x₀ y₀ : S) (h : g x₀ = g y₀) : Rel' (Sum.inl (f x₀)) (Sum.inl (f y₀))
  | inl_inr (s : S) : Rel' (Sum.inl (f s)) (Sum.inr (g s))
  | inr_inl (s : S) : Rel' (Sum.inr (g s)) (Sum.inl (f s))

/-- The quotient of `X₁ ⊕ X₂` by the relation `PushoutRel' f g`. -/
/-
**CategoryTheory.Limits.Types.Pushout'** 是 Mathlib 中的一个定义，位于命名空间 `CategoryTheory
.Limits.Types`。
形式化陈述：Pushout' : Type u
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.Pushout.Rel'`：Rel'.symm {x y : X₁ oplus X₂} 
(h : Rel' f g x y) : Rel' f g y x

--- 原说明 ---
The quotient of `X₁ ⊕ X₂` by the relation `PushoutRel' f g`.
-/
def Pushout' : Type u := _root_.Quot (Pushout.Rel' f g)

namespace Pushout

/-- The left inclusion in the constructed pushout `Pushout f g`. -/
@[simp]
/-
**CategoryTheory.Limits.Types.Pushout.inl** 是 Mathlib 中的一个定义，位于命名空间 `CategoryThe
ory.Limits.Types.Pushout`。
形式化陈述：inl : X₁ ⟶ Pushout f g
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The left inclusion in the constructed pushout `Pushout f g`.
-/
def inl : X₁ ⟶ Pushout f g := ↾fun x => Quot.mk _ (Sum.inl x)

/-- The right inclusion in the constructed pushout `Pushout f g`. -/
@[simp]
/-
**CategoryTheory.Limits.Types.Pushout.inr** 是 Mathlib 中的一个定义，位于命名空间 `CategoryThe
ory.Limits.Types.Pushout`。
形式化陈述：inr : X₂ ⟶ Pushout f g
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The right inclusion in the constructed pushout `Pushout f g`.
-/
def inr : X₂ ⟶ Pushout f g := ↾fun x => Quot.mk _ (Sum.inr x)
/-
**CategoryTheory.Limits.Types.Pushout.condition** 是 Mathlib 中的一个引理，位于命名空间 `Categ
oryTheory.Limits.Types.Pushout`。
形式化陈述：condition : f ≫ inl f g = g ≫ inr f g
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `CategoryTheory.ConcreteCategory.ext`：∀ {C : Type u} [inst : CategoryTheo
ry.Category.{v, u} C] {FC : C → C → Type u_1} {CC : C → Type w}   [inst_1 : (X Y
 : C) → FunLike (FC X Y) …
· 使用定理 `TypeCat.Fun.ext`：∀ {X : Type u_1} {Y : Type u_2} {x y : TypeCat.Fun X Y}
, x.toFun = y.toFun → x = y
· 使用定理 `funext`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, (∀ (x : α
), f x = g x) → f = g
-/
lemma condition : f ≫ inl f g = g ≫ inr f g := by
  ext x
  exact Quot.sound (Rel.inl_inr x)

/-- The constructed pushout cocone in the category of types. -/
@[simps!]
/-
**CategoryTheory.Limits.Types.Pushout.cocone** 是 Mathlib 中的一个定义，位于命名空间 `Category
Theory.Limits.Types.Pushout`。
形式化陈述：cocone : PushoutCocone f g
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.Pushout.condition`：condition : f ≫ inl f g =
 g ≫ inr f g

--- 原说明 ---
The constructed pushout cocone in the category of types.
-/
def cocone : PushoutCocone f g := PushoutCocone.mk _ _ (condition f g)

/-- The cocone `cocone f g` is colimit. -/
/-
**CategoryTheory.Limits.Types.Pushout.isColimitCocone** 是 Mathlib 中的一个定义，位于命名空间 
`CategoryTheory.Limits.Types.Pushout`。
形式化陈述：isColimitCocone : IsColimit (cocone f g)
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.Pushout.condition`：condition : f ≫ inl f g =
 g ≫ inr f g

--- 原说明 ---
The cocone `cocone f g` is colimit.
-/
def isColimitCocone : IsColimit (cocone f g) :=
  PushoutCocone.IsColimit.mk _ (fun s => ↾(Quot.lift (fun x => match x with
      | Sum.inl x₁ => s.inl x₁
      | Sum.inr x₂ => s.inr x₂) (by
    rintro _ _ ⟨t⟩
    exact ConcreteCategory.congr_hom s.condition t))) (fun _ => rfl) (fun _ => rfl)
      (fun s m h₁ h₂ => by
      ext ⟨x₁ | x₂⟩
      · exact ConcreteCategory.congr_hom h₁ x₁
      · exact ConcreteCategory.congr_hom h₂ x₂)

@[simp]
/-
**CategoryTheory.Limits.Types.Pushout.inl_rel'_inl_iff** 是 Mathlib 中的一个定理，位于命名空间
 `CategoryTheory.Limits.Types.Pushout`。
形式化陈述：∀ {S X₁ X₂ : Type u} (f : S ⟶ X₁) (g : S ⟶ X₂) (x₁ y₁ : X₁),   CategoryThe
ory.Limits.Types.Pushout.Rel' f g (Sum.inl x₁) (Sum.inl y₁) ↔     x₁ = y₁ ∨     
  ∃ x₀ y₀,         ∃ (_ : (CategoryTheory.ConcreteCategory.hom g) x₀ = (Category
Theory.ConcreteCategory.hom g) y₀),           x₁ = (CategoryTheory.ConcreteCateg
ory.hom f) x₀ ∧ y₁ = (CategoryTheory.ConcreteCategory.hom f) y₀
参数：f : S ⟶ X₁；g : S ⟶ X₂；x₁ y₁ : X₁；Sum.inl x₁；Sum.inl y₁；_ : (CategoryTheory.Co
ncreteCategory.hom g) x₀ = (CategoryTheory.ConcreteCategory.hom g) y₀；CategoryTh
eory.ConcreteCategory.hom f；CategoryTheory.ConcreteCategory.hom f。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.Pushout.Rel'`：Rel'.symm {x y : X₁ oplus X₂} 
(h : Rel' f g x y) : Rel' f g y x
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `eq_of_heq`：∀ {α : Sort u} {a a' : α}, a ≍ a' → a = a'
· 使用定理 `noConfusion_of_Nat`：∀ {α : Sort u} (f : α → ℕ) {a b : α}, a = b → Bool.r
ec False True ((f a).beq (f b))
-/
lemma inl_rel'_inl_iff (x₁ y₁ : X₁) :
    Rel' f g (Sum.inl x₁) (Sum.inl y₁) ↔ x₁ = y₁ ∨
      ∃ (x₀ y₀ : S) (_ : g x₀ = g y₀), x₁ = f x₀ ∧ y₁ = f y₀ := by
  constructor
  · rintro (_ | ⟨_, _, h⟩)
    · exact Or.inl rfl
    · exact Or.inr ⟨_, _, h, rfl, rfl⟩
  · rintro (rfl | ⟨_, _, h, rfl, rfl⟩)
    · apply Rel'.refl
    · exact Rel'.inl_inl _ _ h

@[simp]
/-
**CategoryTheory.Limits.Types.Pushout.inl_rel'_inr_iff** 是 Mathlib 中的一个定理，位于命名空间
 `CategoryTheory.Limits.Types.Pushout`。
形式化陈述：∀ {S X₁ X₂ : Type u} (f : S ⟶ X₁) (g : S ⟶ X₂) (x₁ : X₁) (x₂ : X₂),   Cate
goryTheory.Limits.Types.Pushout.Rel' f g (Sum.inl x₁) (Sum.inr x₂) ↔     ∃ s, x₁
 = (CategoryTheory.ConcreteCategory.hom f) s ∧ x₂ = (CategoryTheory.ConcreteCate
gory.hom g) s
参数：f : S ⟶ X₁；g : S ⟶ X₂；x₁ : X₁；x₂ : X₂；Sum.inl x₁；Sum.inr x₂；CategoryTheory.Co
ncreteCategory.hom f；CategoryTheory.ConcreteCategory.hom g。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.Pushout.Rel'`：Rel'.symm {x y : X₁ oplus X₂} 
(h : Rel' f g x y) : Rel' f g y x
· 使用定理 `noConfusion_of_Nat`：∀ {α : Sort u} (f : α → ℕ) {a b : α}, a = b → Bool.r
ec False True ((f a).beq (f b))
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `eq_of_heq`：∀ {α : Sort u} {a a' : α}, a ≍ a' → a = a'
-/
lemma inl_rel'_inr_iff (x₁ : X₁) (x₂ : X₂) :
    Rel' f g (Sum.inl x₁) (Sum.inr x₂) ↔
      ∃ (s : S), x₁ = f s ∧ x₂ = g s := by
  constructor
  · rintro ⟨_⟩
    exact ⟨_, rfl, rfl⟩
  · rintro ⟨s, rfl, rfl⟩
    exact Rel'.inl_inr _

@[simp]
/-
**CategoryTheory.Limits.Types.Pushout.inr_rel'_inr_iff** 是 Mathlib 中的一个定理，位于命名空间
 `CategoryTheory.Limits.Types.Pushout`。
形式化陈述：∀ {S X₁ X₂ : Type u} (f : S ⟶ X₁) (g : S ⟶ X₂) (x₂ y₂ : X₂),   CategoryThe
ory.Limits.Types.Pushout.Rel' f g (Sum.inr x₂) (Sum.inr y₂) ↔ x₂ = y₂
参数：f : S ⟶ X₁；g : S ⟶ X₂；x₂ y₂ : X₂；Sum.inr x₂；Sum.inr y₂。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.Pushout.Rel'`：Rel'.symm {x y : X₁ oplus X₂} 
(h : Rel' f g x y) : Rel' f g y x
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `eq_of_heq`：∀ {α : Sort u} {a a' : α}, a ≍ a' → a = a'
· 使用定理 `noConfusion_of_Nat`：∀ {α : Sort u} (f : α → ℕ) {a b : α}, a = b → Bool.r
ec False True ((f a).beq (f b))
-/
lemma inr_rel'_inr_iff (x₂ y₂ : X₂) :
    Rel' f g (Sum.inr x₂) (Sum.inr y₂) ↔ x₂ = y₂ := by
  constructor
  · rintro ⟨_⟩
    rfl
  · rintro rfl
    apply Rel'.refl

variable {f g}
/-
**CategoryTheory.Limits.Types.Pushout.Rel'.symm** 是 Mathlib 中的一个定理，位于命名空间 `Categ
oryTheory.Limits.Types.Pushout.Rel'`。
形式化陈述：∀ {S X₁ X₂ : Type u} {f : S ⟶ X₁} {g : S ⟶ X₂} {x y : X₁ ⊕ X₂},   Category
Theory.Limits.Types.Pushout.Rel' f g x y → CategoryTheory.Limits.Types.Pushout.R
el' f g y x
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.Pushout.Rel'`：Rel'.symm {x y : X₁ oplus X₂} 
(h : Rel' f g x y) : Rel' f g y x
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
-/
lemma Rel'.symm {x y : X₁ ⊕ X₂} (h : Rel' f g x y) :
    Rel' f g y x := by
  obtain _ | ⟨_, _, h⟩ | _ | _ := h
  · apply Rel'.refl
  · exact Rel'.inl_inl _ _ h.symm
  · exact Rel'.inr_inl _
  · exact Rel'.inl_inr _

variable (f g)
/-
**CategoryTheory.Limits.Types.Pushout.equivalence_rel'** 是 Mathlib 中的一个引理，位于命名空间
 `CategoryTheory.Limits.Types.Pushout`。
形式化陈述：equivalence_rel' [Mono f] : _root_.Equivalence (Rel' f g) where refl
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.Pushout.Rel'`：Rel'.symm {x y : X₁ oplus X₂} 
(h : Rel' f g x y) : Rel' f g y x
· 使用定理 `CategoryTheory.Limits.Types.Pushout.Rel'.symm`：∀ {S X₁ X₂ : Type u} {f :
 S ⟶ X₁} {g : S ⟶ X₂} {x y : X₁ ⊕ X₂},   CategoryTheory.Limits.Types.Pushout.Rel
' f g x y → CategoryTheory.Limits.T…
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `CategoryTheory.Limits.Types.Pushout.inl_rel'_inl_iff`：∀ {S X₁ X₂ : Type 
u} (f : S ⟶ X₁) (g : S ⟶ X₂) (x₁ y₁ : X₁),   CategoryTheory.Limits.Types.Pushout
.Rel' f g (Sum.inl x₁) (Sum.inl y₁) ↔     …
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `Iff.mp`：∀ {a b : Prop}, (a ↔ b) → a → b
· 使用定理 `CategoryTheory.mono_iff_injective`：mono_iff_injective {X Y : Type u} (f 
: X ⟶ Y) : Mono f ↔ Function.Injective f
· 使用定理 `CategoryTheory.Limits.Types.Pushout.inl_rel'_inr_iff`：∀ {S X₁ X₂ : Type 
u} (f : S ⟶ X₁) (g : S ⟶ X₂) (x₁ : X₁) (x₂ : X₂),   CategoryTheory.Limits.Types.
Pushout.Rel' f g (Sum.inl x₁) (Sum.inr x₂)…
· 使用定理 `CategoryTheory.Limits.Types.Pushout.inr_rel'_inr_iff`：∀ {S X₁ X₂ : Type 
u} (f : S ⟶ X₁) (g : S ⟶ X₂) (x₂ y₂ : X₂),   CategoryTheory.Limits.Types.Pushout
.Rel' f g (Sum.inr x₂) (Sum.inr y₂) ↔ x₂ =…
-/
lemma equivalence_rel' [Mono f] : _root_.Equivalence (Rel' f g) where
  refl := Rel'.refl
  symm h := h.symm
  trans := by
    rintro x y z (_ | ⟨_, _, h⟩ | s | _) hyz
    · exact hyz
    · obtain z₁ | z₂ := z
      · rw [inl_rel'_inl_iff] at hyz
        obtain rfl | ⟨_, _, h', h'', rfl⟩ := hyz
        · exact Rel'.inl_inl _ _ h
        · obtain rfl := (mono_iff_injective f).1 inferInstance h''
          exact Rel'.inl_inl _ _ (h.trans h')
      · rw [inl_rel'_inr_iff] at hyz
        obtain ⟨s, hs, rfl⟩ := hyz
        obtain rfl := (mono_iff_injective f).1 inferInstance hs
        rw [← h]
        apply Rel'.inl_inr
    · obtain z₁ | z₂ := z
      · replace hyz := hyz.symm
        rw [inl_rel'_inr_iff] at hyz
        obtain ⟨s', rfl, hs'⟩ := hyz
        exact Rel'.inl_inl _ _ hs'
      · rw [inr_rel'_inr_iff] at hyz
        subst hyz
        apply Rel'.inl_inr
    · obtain z₁ | z₂ := z
      · rw [inl_rel'_inl_iff] at hyz
        obtain rfl | ⟨_, _, h, h', rfl⟩ := hyz
        · apply Rel'.inr_inl
        · obtain rfl := (mono_iff_injective f).1 inferInstance h'
          rw [h]
          apply Rel'.inr_inl
      · rw [inl_rel'_inr_iff] at hyz
        obtain ⟨s, hs, rfl⟩ := hyz
        obtain rfl := (mono_iff_injective f).1 inferInstance hs
        apply Rel'.refl

/-- The obvious equivalence `Pushout f g ≃ Pushout' f g`. -/
/-
**CategoryTheory.Limits.Types.Pushout.equivPushout'** 是 Mathlib 中的一个定义，位于命名空间 `C
ategoryTheory.Limits.Types.Pushout`。
形式化陈述：equivPushout' : Pushout f g ≃ Pushout' f g where toFun
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.Pushout.Rel'`：Rel'.symm {x y : X₁ oplus X₂} 
(h : Rel' f g x y) : Rel' f g y x

--- 原说明 ---
The obvious equivalence `Pushout f g ≃ Pushout' f g`.
-/
def equivPushout' : Pushout f g ≃ Pushout' f g where
  toFun := Quot.lift (Quot.mk _) (by
    rintro _ _ ⟨⟩
    apply Quot.sound
    apply Rel'.inl_inr)
  invFun := Quot.lift (Quot.mk _) (by
    rintro a b (_ | ⟨x₀, y₀, h⟩ | _ | _)
    · rfl
    · have h₀ : Rel f g _ _ := Rel.inl_inr x₀
      rw [Quot.sound h₀, h]
      symm
      apply Quot.sound
      apply Rel.inl_inr
    · apply Quot.sound
      apply Rel.inl_inr
    · symm
      apply Quot.sound
      apply Rel.inl_inr)
  left_inv := by rintro ⟨x⟩; rfl
  right_inv := by rintro ⟨x⟩; rfl
/-
**CategoryTheory.Limits.Types.Pushout.quot_mk_eq_iff** 是 Mathlib 中的一个引理，位于命名空间 `
CategoryTheory.Limits.Types.Pushout`。
形式化陈述：quot_mk_eq_iff [Mono f] (a b : X₁ oplus X₂) : (Quot.mk _ a : Pushout f g) 
= Quot.mk _ b ↔ Rel' f g a b
参数：a b : X₁ oplus X₂。
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.Pushout.Rel'`：Rel'.symm {x y : X₁ oplus X₂} 
(h : Rel' f g x y) : Rel' f g y x
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用引理 `Equivalence.quot_mk_eq_iff`：Equivalence.quot_mk_eq_iff {α : Type*} {r : 
α -> α -> Prop} (h : Equivalence r) (x y : α) : Quot.mk r x = Quot.mk r y ↔ r x 
y
· 使用引理 `CategoryTheory.Limits.Types.Pushout.equivalence_rel'`：equivalence_rel' [
Mono f] : _root_.Equivalence (Rel' f g) where refl
· 使用定理 `Equiv.injective`：∀ {α : Sort u} {β : Sort v} (e : α ≃ β), Function.Injec
tive ⇑e
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s
-/
lemma quot_mk_eq_iff [Mono f] (a b : X₁ ⊕ X₂) :
    (Quot.mk _ a : Pushout f g) = Quot.mk _ b ↔ Rel' f g a b := by
  rw [← (equivalence_rel' f g).quot_mk_eq_iff]
  exact ⟨fun h => (equivPushout' f g).symm.injective h,
    fun h => (equivPushout' f g).injective h⟩
/-
**CategoryTheory.Limits.Types.Pushout.inl_eq_inr_iff** 是 Mathlib 中的一个引理，位于命名空间 `
CategoryTheory.Limits.Types.Pushout`。
形式化陈述：inl_eq_inr_iff [Mono f] (x₁ : X₁) (x₂ : X₂) : (inl f g x₁ = inr f g x₂) ↔ 
exists (s : S), f s = x₁ ∧ g s = x₂
参数：x₁ : X₁；x₂ : X₂。
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.trans`：∀ {a b c : Prop}, (a ↔ b) → (b ↔ c) → (a ↔ c)
· 使用引理 `CategoryTheory.Limits.Types.Pushout.Rel'`：Rel'.symm {x y : X₁ oplus X₂} 
(h : Rel' f g x y) : Rel' f g y x
· 使用引理 `CategoryTheory.Limits.Types.Pushout.quot_mk_eq_iff`：quot_mk_eq_iff [Mono
 f] (a b : X₁ oplus X₂) : (Quot.mk _ a : Pushout f g) = Quot.mk _ b ↔ Rel' f g a
 b
· 使用定理 `noConfusion_of_Nat`：∀ {α : Sort u} (f : α → ℕ) {a b : α}, a = b → Bool.r
ec False True ((f a).beq (f b))
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `eq_of_heq`：∀ {α : Sort u} {a a' : α}, a ≍ a' → a = a'
-/
lemma inl_eq_inr_iff [Mono f] (x₁ : X₁) (x₂ : X₂) :
    (inl f g x₁ = inr f g x₂) ↔
      ∃ (s : S), f s = x₁ ∧ g s = x₂ := by
  refine (Pushout.quot_mk_eq_iff f g (Sum.inl x₁) (Sum.inr x₂)).trans ?_
  constructor
  · rintro ⟨⟩
    exact ⟨_, rfl, rfl⟩
  · rintro ⟨s, rfl, rfl⟩
    apply Rel'.inl_inr
/-
**CategoryTheory.Limits.Types.Pushout.mono_inr** 是 Mathlib 中的一个实例，位于命名空间 `Catego
ryTheory.Limits.Types.Pushout`。
形式化陈述：mono_inr [Mono f] : Mono (inr f g)
该定义给出了上述对象。
本声明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `CategoryTheory.mono_iff_injective`：mono_iff_injective {X Y : Type u} (f 
: X ⟶ Y) : Mono f ↔ Function.Injective f
· 使用引理 `CategoryTheory.Limits.Types.Pushout.Rel'`：Rel'.symm {x y : X₁ oplus X₂} 
(h : Rel' f g x y) : Rel' f g y x
· 使用定理 `Iff.mp`：∀ {a b : Prop}, (a ↔ b) → a → b
· 使用引理 `CategoryTheory.Limits.Types.Pushout.quot_mk_eq_iff`：quot_mk_eq_iff [Mono
 f] (a b : X₁ oplus X₂) : (Quot.mk _ a : Pushout f g) = Quot.mk _ b ↔ Rel' f g a
 b
-/
instance mono_inr [Mono f] : Mono (inr f g) := by
  rw [mono_iff_injective]
  intro x₂ y₂ h
  simpa using (Pushout.quot_mk_eq_iff f g (Sum.inr x₂) (Sum.inr y₂)).1 h

end Pushout

variable {f g}

/-
**CategoryTheory.Limits.Types.pushoutCocone_inl_eq_inr_imp_of_iso** 是 Mathlib 中的
一个引理，位于命名空间 `CategoryTheory.Limits.Types`。
形式化陈述：pushoutCocone_inl_eq_inr_imp_of_iso {c c' : PushoutCocone f g} (e : c ≅ c'
) (x₁ : X₁) (x₂ : X₂) (h : c.inl x₁ = c.inr x₂) : c'.inl x₁ = c'.inr x₂
参数：e : c ≅ c'；x₁ : X₁；x₂ : X₂；h : c.inl x₁ = c.inr x₂。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `eq_of_heq`：∀ {α : Sort u} {a a' : α}, a ≍ a' → a = a'
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `CategoryTheory.ConcreteCategory.congr_hom`：congr_hom {X Y : C} {f g : X 
⟶ Y} (h : f = g) (x : ToType X) : f x = g x
· 使用定理 `CategoryTheory.Limits.CoconeMorphism.w`：∀ {J : Type u₁} [inst : Category
Theory.Category.{v₁, u₁} J] {C : Type u₃} [inst_1 : CategoryTheory.Category.{v₃,
 u₃} C]   {F : CategoryTheor…
· 使用定理 `congr_arg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ 
→ f a₁ = f a₂
-/
lemma pushoutCocone_inl_eq_inr_imp_of_iso {c c' : PushoutCocone f g} (e : c ≅ c')
    (x₁ : X₁) (x₂ : X₂) (h : c.inl x₁ = c.inr x₂) :
    c'.inl x₁ = c'.inr x₂ := by
  convert! congr_arg e.hom.hom h
  · exact ConcreteCategory.congr_hom (e.hom.w WalkingSpan.left).symm x₁
  · exact ConcreteCategory.congr_hom (e.hom.w WalkingSpan.right).symm x₂
/-
**CategoryTheory.Limits.Types.pushoutCocone_inl_eq_inr_iff_of_iso** 是 Mathlib 中的
一个引理，位于命名空间 `CategoryTheory.Limits.Types`。
形式化陈述：pushoutCocone_inl_eq_inr_iff_of_iso {c c' : PushoutCocone f g} (e : c ≅ c'
) (x₁ : X₁) (x₂ : X₂) : c.inl x₁ = c.inr x₂ ↔ c'.inl x₁ = c'.inr x₂
参数：e : c ≅ c'；x₁ : X₁；x₂ : X₂。
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.pushoutCocone_inl_eq_inr_imp_of_iso`：pushout
Cocone_inl_eq_inr_imp_of_iso {c c' : PushoutCocone f g} (e : c ≅ c') (x₁ : X₁) (
x₂ : X₂) (h : c.inl x₁ = c.inr x₂) : c'.inl x₁ = c'.i…
-/
lemma pushoutCocone_inl_eq_inr_iff_of_iso {c c' : PushoutCocone f g} (e : c ≅ c')
    (x₁ : X₁) (x₂ : X₂) :
    c.inl x₁ = c.inr x₂ ↔ c'.inl x₁ = c'.inr x₂ := by
  constructor
  · apply pushoutCocone_inl_eq_inr_imp_of_iso e
  · apply pushoutCocone_inl_eq_inr_imp_of_iso e.symm

set_option backward.isDefEq.respectTransparency false in
/-
**CategoryTheory.Limits.Types.pushoutCocone_inl_eq_inr_iff_of_isColimit** 是 Math
lib 中的一个引理，位于命名空间 `CategoryTheory.Limits.Types`。
形式化陈述：pushoutCocone_inl_eq_inr_iff_of_isColimit {c : PushoutCocone f g} (hc : Is
Colimit c) (h₁ : Function.Injective f) (x₁ : X₁) (x₂ : X₂) : c.inl x₁ = c.inr x₂
 ↔ exists (s : S), f s = x₁ ∧ g s = x₂
参数：hc : IsColimit c；h₁ : Function.Injective f；x₁ : X₁；x₂ : X₂。
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用引理 `CategoryTheory.Limits.Types.pushoutCocone_inl_eq_inr_iff_of_iso`：pushout
Cocone_inl_eq_inr_iff_of_iso {c c' : PushoutCocone f g} (e : c ≅ c') (x₁ : X₁) (
x₂ : X₂) : c.inl x₁ = c.inr x₂ ↔ c'.inl x₁ = c'.inr x…
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `forall_congr`：∀ {α : Sort u} {p q : α → Prop}, (∀ (a : α), p a = q a) → 
(∀ (a : α), p a) = ∀ (a : α), q a
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `CategoryTheory.Limits.IsColimit.comp_coconePointUniqueUpToIso_hom`：∀ {J 
: Type u₁} [inst : CategoryTheory.Category.{v₁, u₁} J] {C : Type u₃} [inst_1 : C
ategoryTheory.Category.{v₃, u₃} C]   {F : CategoryTheor…
· 使用定理 `CategoryTheory.Limits.Types.Pushout.cocone_ι_app`：∀ {S X₁ X₂ : Type u} (
f : S ⟶ X₁) (g : S ⟶ X₂) (j : CategoryTheory.Limits.WalkingSpan),   (CategoryThe
ory.Limits.Types.Pushout.cocone f g).ι…
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
· 使用定理 `implies_true`：∀ (α : Sort u), (∀ (a : α), True) = True
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `CategoryTheory.mono_iff_injective`：mono_iff_injective {X Y : Type u} (f 
: X ⟶ Y) : Mono f ↔ Function.Injective f
· 使用引理 `CategoryTheory.Limits.Types.Pushout.inl_eq_inr_iff`：inl_eq_inr_iff [Mono
 f] (x₁ : X₁) (x₂ : X₂) : (inl f g x₁ = inr f g x₂) ↔ exists (s : S), f s = x₁ ∧
 g s = x₂
-/
lemma pushoutCocone_inl_eq_inr_iff_of_isColimit {c : PushoutCocone f g} (hc : IsColimit c)
    (h₁ : Function.Injective f) (x₁ : X₁) (x₂ : X₂) :
    c.inl x₁ = c.inr x₂ ↔ ∃ (s : S), f s = x₁ ∧ g s = x₂ := by
  rw [pushoutCocone_inl_eq_inr_iff_of_iso
    (Cocone.ext (IsColimit.coconePointUniqueUpToIso hc (Pushout.isColimitCocone f g))
    (by simp))]
  have := (mono_iff_injective f).2 h₁
  apply Pushout.inl_eq_inr_iff

set_option backward.isDefEq.respectTransparency false in
/-
**CategoryTheory.Limits.Types.pushoutCocone_inr_mono_of_isColimit** 是 Mathlib 中的
一个引理，位于命名空间 `CategoryTheory.Limits.Types`。
形式化陈述：pushoutCocone_inr_mono_of_isColimit {c : PushoutCocone f g} (hc : IsColimi
t c) [Mono f] : Mono c.inr
参数：hc : IsColimit c。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `forall_congr`：∀ {α : Sort u} {p q : α → Prop}, (∀ (a : α), p a = q a) → 
(∀ (a : α), p a) = ∀ (a : α), q a
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `CategoryTheory.Limits.IsColimit.comp_coconePointUniqueUpToIso_hom`：∀ {J 
: Type u₁} [inst : CategoryTheory.Category.{v₁, u₁} J] {C : Type u₃} [inst_1 : C
ategoryTheory.Category.{v₃, u₃} C]   {F : CategoryTheor…
· 使用定理 `CategoryTheory.Limits.Types.Pushout.cocone_ι_app`：∀ {S X₁ X₂ : Type u} (
f : S ⟶ X₁) (g : S ⟶ X₂) (j : CategoryTheory.Limits.WalkingSpan),   (CategoryThe
ory.Limits.Types.Pushout.cocone f g).ι…
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
· 使用定理 `implies_true`：∀ (α : Sort u), (∀ (a : α), True) = True
· 使用定理 `CategoryTheory.mono_comp`：∀ {C : Type u} [inst : CategoryTheory.Category
.{v, u} C] {X Y Z : C} (g : Z ⟶ Y) [CategoryTheory.Mono g] (f : Y ⟶ X)   [Catego
ryTheory.Mono …
· 使用定理 `CategoryTheory.StrongMono.mono`：∀ {C : Type u} {inst : CategoryTheory.Ca
tegory.{v, u} C} {P Q : C} {f : P ⟶ Q} [self : CategoryTheory.StrongMono f],   C
ategoryTheory.Mono f
· 使用定理 `CategoryTheory.strongMono_of_isIso`：∀ {C : Type u} [inst : CategoryTheor
y.Category.{v, u} C] {P Q : C} (f : Q ⟶ P) [CategoryTheory.IsIso f],   CategoryT
heory.StrongMono f
· 使用定理 `CategoryTheory.Iso.isIso_inv`：∀ {C : Type u} [inst : CategoryTheory.Cate
gory.{v, u} C] {X Y : C} (e : X ≅ Y), CategoryTheory.IsIso e.inv
-/
lemma pushoutCocone_inr_mono_of_isColimit {c : PushoutCocone f g} (hc : IsColimit c)
    [Mono f] : Mono c.inr := by
  change Mono ((Pushout.inr f g) ≫
    ((Cocone.forget _).mapIso
      (Cocone.ext (IsColimit.coconePointUniqueUpToIso hc
        (Pushout.isColimitCocone f g)) (by simp))).inv)
  infer_instance
/-
**CategoryTheory.Limits.Types.pushoutCocone_inr_injective_of_isColimit** 是 Mathl
ib 中的一个引理，位于命名空间 `CategoryTheory.Limits.Types`。
形式化陈述：pushoutCocone_inr_injective_of_isColimit {c : PushoutCocone f g} (hc : IsC
olimit c) (h₁ : Function.Injective f) : Function.Injective c.inr
参数：hc : IsColimit c；h₁ : Function.Injective f。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `CategoryTheory.mono_iff_injective`：mono_iff_injective {X Y : Type u} (f 
: X ⟶ Y) : Mono f ↔ Function.Injective f
· 使用引理 `CategoryTheory.Limits.Types.pushoutCocone_inr_mono_of_isColimit`：pushout
Cocone_inr_mono_of_isColimit {c : PushoutCocone f g} (hc : IsColimit c) [Mono f]
 : Mono c.inr
-/
lemma pushoutCocone_inr_injective_of_isColimit {c : PushoutCocone f g} (hc : IsColimit c)
    (h₁ : Function.Injective f) : Function.Injective c.inr := by
  rw [← mono_iff_injective] at h₁ ⊢
  exact pushoutCocone_inr_mono_of_isColimit hc
/-
**CategoryTheory.Limits.Types.mono_inl** 是 Mathlib 中的一个实例，位于命名空间 `CategoryTheory
.Limits.Types`。
形式化陈述：mono_inl [Mono g] : Mono (Pushout.inl f g)
该定义给出了上述对象。
本声明引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.pushoutCocone_inr_mono_of_isColimit`：pushout
Cocone_inr_mono_of_isColimit {c : PushoutCocone f g} (hc : IsColimit c) [Mono f]
 : Mono c.inr
-/
instance mono_inl [Mono g] : Mono (Pushout.inl f g) :=
  pushoutCocone_inr_mono_of_isColimit
    (PushoutCocone.flipIsColimit (Pushout.isColimitCocone f g))
/-
**CategoryTheory.Limits.Types.** 是 Mathlib 中的一个实例，位于命名空间 `CategoryTheory.Limits.
Types`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Mono f] : Mono (pushout.inr f g) :=
  (pushoutCocone_inr_mono_of_isColimit (pushoutIsPushout f g) :)
/-
**CategoryTheory.Limits.Types.** 是 Mathlib 中的一个实例，位于命名空间 `CategoryTheory.Limits.
Types`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Mono g] : Mono (pushout.inl f g) :=
  pushoutCocone_inr_mono_of_isColimit
    (PushoutCocone.flipIsColimit (pushoutIsPushout f g))

section

variable {X₁ X₂ X₃ X₄ X₅ : Type u} {t : X₁ ⟶ X₂} {r : X₂ ⟶ X₄}
  {l : X₁ ⟶ X₃} {b : X₃ ⟶ X₄}

/-
**CategoryTheory.Limits.Types.eq_or_eq_of_isPushout** 是 Mathlib 中的一个引理，位于命名空间 `C
ategoryTheory.Limits.Types`。
形式化陈述：eq_or_eq_of_isPushout (h : IsPushout t l r b) (x₄ : X₄) : (exists x₂, r x₂
 = x₄) ∨ exists x₃, b x₃ = x₄
参数：h : IsPushout t l r b；x₄ : X₄。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `CategoryTheory.Limits.Types.jointly_surjective_of_isColimit`：jointly_sur
jective_of_isColimit {F : J ⥤ Type u} {t : Cocone F} (h : IsColimit t) (x : t.pt
) : exists j y, t.ι.app j y = x
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `CategoryTheory.Limits.PushoutCocone.condition_zero`：condition_zero (t : 
PushoutCocone f g) : t.ι.app WalkingSpan.zero = f ≫ t.inl
-/
lemma eq_or_eq_of_isPushout (h : IsPushout t l r b)
    (x₄ : X₄) : (∃ x₂, r x₂ = x₄) ∨ ∃ x₃, b x₃ = x₄ := by
  obtain ⟨j, x, rfl⟩ := jointly_surjective_of_isColimit h.isColimit x₄
  obtain (_ | _ | _) := j
  · exact Or.inl ⟨t x, by simp; rfl⟩
  · exact Or.inl ⟨x, rfl⟩
  · exact Or.inr ⟨x, rfl⟩
/-
**CategoryTheory.Limits.Types.eq_or_eq_of_isPushout'** 是 Mathlib 中的一个引理，位于命名空间 `
CategoryTheory.Limits.Types`。
形式化陈述：eq_or_eq_of_isPushout' (h : IsPushout t l r b) (x₄ : X₄) : (exists x₂, r x
₂ = x₄) ∨ exists x₃, b x₃ = x₄ ∧ x₃ ∉ Set.range l
参数：h : IsPushout t l r b；x₄ : X₄。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.eq_or_eq_of_isPushout`：eq_or_eq_of_isPushout
 (h : IsPushout t l r b) (x₄ : X₄) : (exists x₂, r x₂ = x₄) ∨ exists x₃, b x₃ = 
x₄
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `CategoryTheory.ConcreteCategory.congr_hom`：congr_hom {X Y : C} {f g : X 
⟶ Y} (h : f = g) (x : ToType X) : f x = g x
· 使用定理 `CategoryTheory.CommSq.w`：∀ {C : Type u_1} [inst : CategoryTheory.Categor
y.{v_1, u_1} C] {W X Y Z : C} {f : W ⟶ X} {g : W ⟶ Y} {h : X ⟶ Z}   {i : Y ⟶ Z},
   CategoryTh…
· 使用定理 `CategoryTheory.IsPushout.toCommSq`：∀ {C : Type u₁} [inst : CategoryTheor
y.Category.{v₁, u₁} C] {Z X Y P : C} {f : Z ⟶ X} {g : Z ⟶ Y} {inl : X ⟶ P}   {in
r : Y ⟶ P}, CategoryThe…
-/
lemma eq_or_eq_of_isPushout' (h : IsPushout t l r b)
    (x₄ : X₄) : (∃ x₂, r x₂ = x₄) ∨ ∃ x₃, b x₃ = x₄ ∧ x₃ ∉ Set.range l := by
  obtain h₁ | ⟨x₃, hx₃⟩ := eq_or_eq_of_isPushout h x₄
  · exact Or.inl h₁
  · by_cases h₂ : x₃ ∈ Set.range l
    · obtain ⟨x₁, rfl⟩ := h₂
      exact Or.inl ⟨t x₁, by simpa only [← hx₃] using! ConcreteCategory.congr_hom h.w x₁⟩
    · exact Or.inr ⟨x₃, hx₃, h₂⟩

/-- A pushout square in `Type` where the top map is injective is a pullback square.
This is also essentially the lemma `isPullback_of_isPushout_of_mono_left`
from the file `CategoryTheory.Adhesive.Basic` in the case of the adhesive category of types. -/
/-
**CategoryTheory.Limits.Types.isPullback_of_isPushout** 是 Mathlib 中的一个引理，位于命名空间 
`CategoryTheory.Limits.Types`。
形式化陈述：isPullback_of_isPushout (h : IsPushout t l r b) (ht : Function.Injective t
) : IsPullback t l r b
参数：h : IsPushout t l r b；ht : Function.Injective t。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `CategoryTheory.Limits.Types.isPullback_iff`：∀ {X₁ X₂ X₃ X₄ : Type u} (t 
: X₁ ⟶ X₂) (r : X₂ ⟶ X₄) (l : X₁ ⟶ X₃) (b : X₃ ⟶ X₄),   CategoryTheory.IsPullbac
k t l r b ↔     CategoryTheory.C…
· 使用定理 `CategoryTheory.CommSq.w`：∀ {C : Type u_1} [inst : CategoryTheory.Categor
y.{v_1, u_1} C] {W X Y Z : C} {f : W ⟶ X} {g : W ⟶ Y} {h : X ⟶ Z}   {i : Y ⟶ Z},
   CategoryTh…
· 使用定理 `CategoryTheory.IsPushout.toCommSq`：∀ {C : Type u₁} [inst : CategoryTheor
y.Category.{v₁, u₁} C] {Z X Y P : C} {f : Z ⟶ X} {g : Z ⟶ Y} {inl : X ⟶ P}   {in
r : Y ⟶ P}, CategoryThe…
· 使用定理 `Iff.mp`：∀ {a b : Prop}, (a ↔ b) → a → b
· 使用引理 `CategoryTheory.Limits.Types.pushoutCocone_inl_eq_inr_iff_of_isColimit`：p
ushoutCocone_inl_eq_inr_iff_of_isColimit {c : PushoutCocone f g} (hc : IsColimit
 c) (h₁ : Function.Injective f) (x₁ : X₁) (x₂ : X₂) : c.inl…

--- 原说明 ---
A pushout square in `Type` where the top map is injective is a pullback square.
This is also essentially the lemma `isPullback_of_isPushout_of_mono_left`
from the file `CategoryTheory.Adhesive.Basic` in the case of the adhesive catego
ry of types.
-/
lemma isPullback_of_isPushout (h : IsPushout t l r b) (ht : Function.Injective t) :
    IsPullback t l r b := by
  rw [isPullback_iff]
  refine ⟨h.w, fun x₁ y₁ ⟨h₂, _⟩ ↦ ht h₂, fun x₂ x₃ hx ↦ ?_⟩
  have := (pushoutCocone_inl_eq_inr_iff_of_isColimit h.isColimit ht x₂ x₃).1 hx
  grind

/-- Consider a pushout square involving types `X₁`, `X₂`, `X₃` and `X₄`:
```
     t
 X₁  ⟶  X₂
l|     |r  \
 v   b  v   \ r'
 X₃  ⟶  X₄   \
  \       k\  |
   \ b'     v v
    \______> X₅
```
Let `k : X₄ ⟶ X₅`, `r' : X₂ ⟶ X₅` and `b' : X₃ ⟶ X₅` be such
that `r ≫ k = r'` and `b ≫ k = b'`. Assume that
the outer square is a pullback, that `r'` is a monomorphism
and that `b'` is injective on the complement of the range of `l`,
then `k : X₄ ⟶ X₅` is a monomorphism. -/
/-
**CategoryTheory.Limits.Types.mono_of_isPushout_of_isPullback** 是 Mathlib 中的一个引理
，位于命名空间 `CategoryTheory.Limits.Types`。
形式化陈述：mono_of_isPushout_of_isPullback {k : X₄ ⟶ X₅} (h₁ : IsPushout t l r b) {r'
 : X₂ ⟶ X₅} {b' : X₃ ⟶ X₅} (h₂ : IsPullback t l r' b') (facr : r ≫ k = r') (facb
 : b ≫ k = b') [hr' : Mono r'] (H : forall (x₃ y₃ : X₃) (_ : x₃ ∉ Set.range l) (
_ : y₃ ∉ Set.range l), b' x₃ = b' y₃ -> x₃ = y₃) : Mono k
参数：h₁ : IsPushout t l r b；h₂ : IsPullback t l r' b'；facr : r ≫ k = r'；facb : b ≫
 k = b'；H : forall (x₃ y₃ : X₃) (_ : x₃ ∉ Set.range l) (_ : y₃ ∉ Set.range l), b
' x₃ = b' y₃ -> x₃ = y₃。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `CategoryTheory.Limits.Types.ext_of_isPullback`：∀ {X₁ X₂ X₃ X₄ : Type u} 
{t : X₁ ⟶ X₂} {r : X₂ ⟶ X₄} {l : X₁ ⟶ X₃} {b : X₃ ⟶ X₄},   CategoryTheory.IsPull
back t l r b →     ∀ {x₁ y₁ : X₁}, …
· 使用定理 `Iff.mp`：∀ {a b : Prop}, (a ↔ b) → a → b
· 使用定理 `CategoryTheory.mono_iff_injective`：mono_iff_injective {X Y : Type u} (f 
: X ⟶ Y) : Mono f ↔ Function.Injective f
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `CategoryTheory.ConcreteCategory.congr_hom`：congr_hom {X Y : C} {f g : X 
⟶ Y} (h : f = g) (x : ToType X) : f x = g x
· 使用定理 `CategoryTheory.CommSq.w`：∀ {C : Type u_1} [inst : CategoryTheory.Categor
y.{v_1, u_1} C] {W X Y Z : C} {f : W ⟶ X} {g : W ⟶ Y} {h : X ⟶ Z}   {i : Y ⟶ Z},
   CategoryTh…
· 使用定理 `CategoryTheory.IsPullback.toCommSq`：∀ {C : Type u₁} [inst : CategoryTheo
ry.Category.{v₁, u₁} C] {P X Y Z : C} {fst : P ⟶ X} {snd : P ⟶ Y} {f : X ⟶ Z}   
{g : Y ⟶ Z}, CategoryThe…
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `CategoryTheory.comp_apply`：∀ {C : Type u} [inst : CategoryTheory.Categor
y.{v, u} C] {FC : C → C → Type u_1} {CC : C → Type w}   [inst_1 : (X Y : C) → Fu
nLike (FC X Y) …
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `CategoryTheory.IsPushout.toCommSq`：∀ {C : Type u₁} [inst : CategoryTheor
y.Category.{v₁, u₁} C] {Z X Y P : C} {f : Z ⟶ X} {g : Z ⟶ Y} {inl : X ⟶ P}   {in
r : Y ⟶ P}, CategoryThe…
· 使用引理 `CategoryTheory.Limits.Types.eq_or_eq_of_isPushout'`：eq_or_eq_of_isPushou
t' (h : IsPushout t l r b) (x₄ : X₄) : (exists x₂, r x₂ = x₄) ∨ exists x₃, b x₃ 
= x₄ ∧ x₃ ∉ Set.range l
· 使用定理 `CategoryTheory.Limits.Types.exists_of_isPullback`：∀ {X₁ X₂ X₃ X₄ : Type 
u} {t : X₁ ⟶ X₂} {r : X₂ ⟶ X₄} {l : X₁ ⟶ X₃} {b : X₃ ⟶ X₄},   CategoryTheory.IsP
ullback t l r b →     ∀ (x₂ : X₂) (x₃ …
· 使用定理 `forall_congr`：∀ {α : Sort u} {p q : α → Prop}, (∀ (a : α), p a = q a) → 
(∀ (a : α), p a) = ∀ (a : α), q a

--- 原说明 ---
Consider a pushout square involving types `X₁`, `X₂`, `X₃` and `X₄`:
```
     t
 X₁  ⟶  X₂
l|     |r  \
 v   b  v   \ r'
 X₃  ⟶  X₄   \
  \       k\  |
   \ b'     v v
    \______> X₅
```
Let `k : X₄ ⟶ X₅`, `r' : X₂ ⟶ X₅` and `b' : X₃ ⟶ X₅` be such
that `r ≫ k = r'` and `b ≫ k = b'`. Assume that
the outer square is a pullback, that `r'` is a monomorphism
and that `b'` is injective on the complement of the range of `l`,
then `k : X₄ ⟶ X₅` is a monomorphism.
-/
lemma mono_of_isPushout_of_isPullback {k : X₄ ⟶ X₅} (h₁ : IsPushout t l r b)
    {r' : X₂ ⟶ X₅} {b' : X₃ ⟶ X₅} (h₂ : IsPullback t l r' b')
    (facr : r ≫ k = r') (facb : b ≫ k = b') [hr' : Mono r']
    (H : ∀ (x₃ y₃ : X₃) (_ : x₃ ∉ Set.range l) (_ : y₃ ∉ Set.range l),
      b' x₃ = b' y₃ → x₃ = y₃) :
    Mono k := by
  subst facr facb
  have : Function.Injective l :=
    fun x₁ y₁ h ↦ ext_of_isPullback h₂ ((mono_iff_injective _).1 hr'
      ((ConcreteCategory.congr_hom h₂.w x₁).trans (Eq.trans (by simp [h])
      (ConcreteCategory.congr_hom h₂.w.symm y₁)))) h
  rw [mono_iff_injective] at hr' ⊢
  have w := ConcreteCategory.congr_hom h₁.w
  simp only [comp_apply] at w
  intro x₃ y₃ eq
  obtain (⟨x₂, rfl⟩ | ⟨x₃, rfl, hx₃⟩) := eq_or_eq_of_isPushout' h₁ x₃ <;>
  obtain (⟨y₂, rfl⟩ | ⟨y₃, rfl, hy₃⟩) := eq_or_eq_of_isPushout' h₁ y₃
  · obtain rfl : x₂ = y₂ := hr' eq
    rfl
  · obtain ⟨x₁, rfl, rfl⟩ := exists_of_isPullback h₂ x₂ y₃ eq
    rw [w]
  · obtain ⟨x₁, rfl, rfl⟩ := exists_of_isPullback h₂ y₂ x₃ eq.symm
    rw [w]
  · obtain rfl := H x₃ y₃ hx₃ hy₃ eq
    rfl

/-- Consider a diagram where the outer square involving types `X₁`, `X₂`, `X₃` and `X₅`
is a pullback, where the two bottom and right triangles commute:
```
     t
 X₁  ⟶  X₂
l|     |r  \
 v   b  v   \ r'
 X₃  ⟶  X₄   \
  \       k\  |
   \ b'     v v
    \______> X₅
```
Assume that `r'` and `k` are monomorphisms, that `r` and `b` are jointly surjective,
and that `b'` is injective on the complement of the range of `l`, then
the top-left square is a pushout. -/
/-
**CategoryTheory.Limits.Types.isPushout_of_isPullback_of_mono** 是 Mathlib 中的一个引理
，位于命名空间 `CategoryTheory.Limits.Types`。
形式化陈述：isPushout_of_isPullback_of_mono {k : X₄ ⟶ X₅} {r' : X₂ ⟶ X₅} {b' : X₃ ⟶ X₅
} (h₁ : IsPullback t l r' b') (facr : r ≫ k = r') (facb : b ≫ k = b') [Mono r'] 
[Mono k] (h₂ : Set.range r ⊔ Set.range b = Set.univ) (H : forall (x₃ y₃ : X₃) (_
 : x₃ ∉ Set.range l) (_ : y₃ ∉ Set.range l), b' x₃ = b' y₃ -> x₃ = y₃) : IsPusho
ut t l r b
参数：h₁ : IsPullback t l r' b'；facr : r ≫ k = r'；facb : b ≫ k = b'；h₂ : Set.range 
r ⊔ Set.range b = Set.univ；H : forall (x₃ y₃ : X₃) (_ : x₃ ∉ Set.range l) (_ : y
₃ ∉ Set.range l), b' x₃ = b' y₃ -> x₃ = y₃。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `UnivLE.small`：∀ [self : UnivLE.{u, v}] (α : Type u), Small.{v, u} α
· 使用定理 `CategoryTheory.Limits.pushout.exists_desc`：∀ {C : Type u} [inst : Catego
ryTheory.Category.{v, u} C] {W X Y Z : C} (f : X ⟶ Y) (g : X ⟶ Z)   [inst_1 : Ca
tegoryTheory.Limits.HasPushout …
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `CategoryTheory.cancel_mono`：∀ {C : Type u} [inst : CategoryTheory.Catego
ry.{v, u} C] {X Y Z : C} (f : Y ⟶ X) [CategoryTheory.Mono f] {g h : Z ⟶ Y},   Ca
tegoryTheory.Cat…
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `CategoryTheory.Category.assoc`：∀ {obj : Type u} [self : CategoryTheory.C
ategory.{v, u} obj] {W X Y Z : obj} (f : W ⟶ X) (g : X ⟶ Y) (h : Y ⟶ Z),   Categ
oryTheory.CategoryS…
· 使用定理 `CategoryTheory.CommSq.w`：∀ {C : Type u_1} [inst : CategoryTheory.Categor
y.{v_1, u_1} C] {W X Y Z : C} {f : W ⟶ X} {g : W ⟶ Y} {h : X ⟶ Z}   {i : Y ⟶ Z},
   CategoryTh…
· 使用定理 `CategoryTheory.IsPullback.toCommSq`：∀ {C : Type u₁} [inst : CategoryTheo
ry.Category.{v₁, u₁} C] {P X Y Z : C} {fst : P ⟶ X} {snd : P ⟶ Y} {f : X ⟶ Z}   
{g : Y ⟶ Z}, CategoryThe…
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
· 使用引理 `CategoryTheory.Limits.Types.mono_of_isPushout_of_isPullback`：mono_of_isP
ushout_of_isPullback {k : X₄ ⟶ X₅} (h₁ : IsPushout t l r b) {r' : X₂ ⟶ X₅} {b' :
 X₃ ⟶ X₅} (h₂ : IsPullback t l r' b') (facr : r ≫…
· 使用定理 `CategoryTheory.IsPushout.of_hasPushout`：of_hasPushout (f : Z ⟶ X) (g : Z
 ⟶ Y) [HasPushout f g] : IsPushout f g (pushout.inl f g) (pushout.inr f g)
· 使用定理 `CategoryTheory.isIso_iff_bijective`：isIso_iff_bijective {X Y : Type u} (
f : X ⟶ Y) : IsIso f ↔ Function.Bijective f
· 使用定理 `Iff.mp`：∀ {a b : Prop}, (a ↔ b) → a → b
· 使用定理 `CategoryTheory.mono_iff_injective`：mono_iff_injective {X Y : Type u} (f 
: X ⟶ Y) : Mono f ↔ Function.Injective f
· 使用定理 `CategoryTheory.mono_of_mono`：∀ {C : Type u} [inst : CategoryTheory.Categ
ory.{v, u} C] {X Y Z : C} (g : Z ⟶ Y) (f : Y ⟶ X)   [CategoryTheory.Mono (Catego
ryTheory.Category…
· 使用定理 `Set.mem_univ`：mem_univ (x : α) : x in @univ α
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `CategoryTheory.ConcreteCategory.congr_hom`：congr_hom {X Y : C} {f g : X 
⟶ Y} (h : f = g) (x : ToType X) : f x = g x
· 使用引理 `CategoryTheory.IsPushout.of_iso`：of_iso (h : IsPushout f g inl inr) {Z' 
X' Y' P' : C} {f' : Z' ⟶ X'} {g' : Z' ⟶ Y'} {inl' : X' ⟶ P'} {inr' : Y' ⟶ P'} (e
₁ : Z ≅ Z') (e₂ : X ≅…
· 使用定理 `CategoryTheory.Category.comp_id`：∀ {obj : Type u} [self : CategoryTheory
.Category.{v, u} obj] {X Y : obj} (f : X ⟶ Y),   CategoryTheory.CategoryStruct.c
omp f (CategoryTheory…
· 使用定理 `CategoryTheory.Category.id_comp`：∀ {obj : Type u} [self : CategoryTheory
.Category.{v, u} obj] {X Y : obj} (f : X ⟶ Y),   CategoryTheory.CategoryStruct.c
omp (CategoryTheory.C…

--- 原说明 ---
Consider a diagram where the outer square involving types `X₁`, `X₂`, `X₃` and `
X₅`
is a pullback, where the two bottom and right triangles commute:
```
     t
 X₁  ⟶  X₂
l|     |r  \
 v   b  v   \ r'
 X₃  ⟶  X₄   \
  \       k\  |
   \ b'     v v
    \______> X₅
```
Assume that `r'` and `k` are monomorphisms, that `r` and `b` are jointly surject
ive,
and that `b'` is injective on the complement of the range of `l`, then
the top-left square is a pushout.
-/
lemma isPushout_of_isPullback_of_mono {k : X₄ ⟶ X₅}
    {r' : X₂ ⟶ X₅} {b' : X₃ ⟶ X₅} (h₁ : IsPullback t l r' b')
    (facr : r ≫ k = r') (facb : b ≫ k = b') [Mono r'] [Mono k]
    (h₂ : Set.range r ⊔ Set.range b = Set.univ)
    (H : ∀ (x₃ y₃ : X₃) (_ : x₃ ∉ Set.range l) (_ : y₃ ∉ Set.range l),
      b' x₃ = b' y₃ → x₃ = y₃) :
    IsPushout t l r b := by
  obtain ⟨φ, hφ₁, hφ₂⟩ := pushout.exists_desc t l r b
    (by simp only [← cancel_mono k, Category.assoc, facr, facb, h₁.w])
  have := mono_of_isPushout_of_isPullback (IsPushout.of_hasPushout t l) h₁
    (k := φ ≫ k) (by cat_disch) (by cat_disch) H
  have : IsIso φ := by
    rw [isIso_iff_bijective]
    refine ⟨(mono_iff_injective _).1 (mono_of_mono φ k), fun x₄ ↦ ?_⟩
    have hx₄ := Set.mem_univ x₄
    simp only [← h₂, Set.sup_eq_union, Set.mem_union, Set.mem_range] at hx₄
    obtain (⟨x₂, rfl⟩ | ⟨x₃, rfl⟩) := hx₄
    · exact ⟨_, ConcreteCategory.congr_hom hφ₁ x₂⟩
    · exact ⟨_, ConcreteCategory.congr_hom hφ₂ x₃⟩
  exact IsPushout.of_iso (IsPushout.of_hasPushout t l)
    (Iso.refl _) (Iso.refl _) (Iso.refl _) (asIso φ) (by simp) (by simp)
    (by simpa) (by simpa)

/-- Consider a pullback square of types where the right map is a monomorphism.
If the right and bottom map are jointly surjective, and the bottom map
is injective on the complement on the range of the left map, then the square
is a pushout square. -/
/-
**CategoryTheory.Limits.Types.isPushout_of_isPullback_of_mono'** 是 Mathlib 中的一个引
理，位于命名空间 `CategoryTheory.Limits.Types`。
形式化陈述：isPushout_of_isPullback_of_mono' (h₁ : IsPullback t l r b) [Mono r] (h₂ : 
Set.range r ⊔ Set.range b = Set.univ) (H : forall (x₃ y₃ : X₃) (_ : x₃ ∉ Set.ran
ge l) (_ : y₃ ∉ Set.range l), b x₃ = b y₃ -> x₃ = y₃) : IsPushout t l r b
参数：h₁ : IsPullback t l r b；h₂ : Set.range r ⊔ Set.range b = Set.univ；H : forall 
(x₃ y₃ : X₃) (_ : x₃ ∉ Set.range l) (_ : y₃ ∉ Set.range l), b x₃ = b y₃ -> x₃ = 
y₃。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Limits.Types.isPushout_of_isPullback_of_mono`：isPushout_o
f_isPullback_of_mono {k : X₄ ⟶ X₅} {r' : X₂ ⟶ X₅} {b' : X₃ ⟶ X₅} (h₁ : IsPullbac
k t l r' b') (facr : r ≫ k = r') (facb : b ≫ k = …
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `CategoryTheory.Category.comp_id`：∀ {obj : Type u} [self : CategoryTheory
.Category.{v, u} obj] {X Y : obj} (f : X ⟶ Y),   CategoryTheory.CategoryStruct.c
omp f (CategoryTheory…
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
· 使用定理 `CategoryTheory.instMonoId`：∀ {C : Type u} [inst : CategoryTheory.Categor
y.{v, u} C] (X : C),   CategoryTheory.Mono (CategoryTheory.CategoryStruct.id X)

--- 原说明 ---
Consider a pullback square of types where the right map is a monomorphism.
If the right and bottom map are jointly surjective, and the bottom map
is injective on the complement on the range of the left map, then the square
is a pushout square.
-/
lemma isPushout_of_isPullback_of_mono'
    (h₁ : IsPullback t l r b) [Mono r]
    (h₂ : Set.range r ⊔ Set.range b = Set.univ)
    (H : ∀ (x₃ y₃ : X₃) (_ : x₃ ∉ Set.range l) (_ : y₃ ∉ Set.range l),
      b x₃ = b y₃ → x₃ = y₃) :
    IsPushout t l r b :=
  isPushout_of_isPullback_of_mono (k := 𝟙 _) h₁ (by simp) (by simp) h₂ H

end

end CategoryTheory.Limits.Types

