/-
Copyright (c) 2024 Joël Riou. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joël Riou
-/
module

public import Mathlib.CategoryTheory.Sites.Hypercover.One

/-!
# Characterization of sheaves using 1-hypercovers

In this file, given a Grothendieck topology `J` on a category `C`,
we define a type `J.OneHypercoverFamily` of families of 1-hypercovers.
When `H : J.OneHypercoverFamily`, we define a predicate `H.IsGenerating`
which means that any covering sieve contains the sieve generated by
the underlying covering of one of the 1-hypercovers in the family.
If this holds, we show in `OneHypercoverFamily.isSheaf_iff` that a
presheaf `P : Cᵒᵖ ⥤ A` is a sheaf iff for any 1-hypercover `E`
in the family, the multifork `E.multifork P` is a limit.

There is a universe parameter `w` attached to `OneHypercoverFamily` and
`OneHypercover`. This universe controls the "size" of the 1-hypercovers:
the index types involved in the 1-hypercovers have to be in `Type w`.
Then, we introduce a type class
`GrothendieckTopology.IsGeneratedByOneHypercovers.{w} J` as an abbreviation for
`OneHypercoverFamily.IsGenerating.{w} (J := J) ⊤`. We show
that if `C : Type u` and `Category.{v} C`, then
`GrothendieckTopology.IsGeneratedByOneHypercovers.{max u v} J` holds.

## TODO
* Show that functors which preserve 1-hypercovers are continuous.
* Refactor `DenseSubsite` using `1`-hypercovers.

-/

@[expose] public section

universe w v v' u u'

namespace CategoryTheory

open Category Limits

variable {C : Type u} [Category.{v} C] (J : GrothendieckTopology C)
  {A : Type u'} [Category.{v'} A]

namespace GrothendieckTopology

/--
Definition of `OneHypercoverFamily` / `OneHypercoverFamily` 的定义

English:
abbreviation OneHypercoverFamily
  body: forall ⦃X : C⦄, OneHypercover.{w} J X -> Prop

中文:
缩写 OneHypercoverFamily
  定义体: forall ⦃X : C⦄, OneHypercover.{w} J X -> Prop

Depends on / 依赖: OneHypercover
-/
abbrev OneHypercoverFamily := forall ⦃X : C⦄, OneHypercover.{w} J X -> Prop

namespace OneHypercoverFamily

variable {J}
variable (H : OneHypercoverFamily.{w} J)

/--
Definition of `IsGenerating` / `IsGenerating` 的定义

English:
class IsGenerating
  parameters: : Prop where
  axioms and operations (1):
    - le({X : C} (S : Sieve X) (hS : S in J X)) : exists (E : J.OneHypercover X) (_ : H E), E.sieve₀ <= S

中文:
类 是Generating
  参数: : 命题 where
  公理与运算 (1 个):
    - le({X : C} (S : 筛 X) (hS : S in J X)) : 存在 (E : J.OneHypercover X) (_ : H E), E.sieve₀ <= S
-/
class IsGenerating : Prop where
  le {X : C} (S : Sieve X) (hS : S in J X) :
    exists (E : J.OneHypercover X) (_ : H E), E.sieve₀ <= S

/--
lemma `exists_oneHypercover` / 引理 `exists_oneHypercover`

English:
lemma exists_oneHypercover
  given: [H.IsGenerating] {X : C} (S : Sieve X) (hS : S in J X)
  proof: IsGenerating.le _ hS

中文:
引理 存在_oneHypercover
  条件: [H.是Generating] {X : C} (S : 筛 X) (hS : S in J X)
  证明: IsGenerating.le _ hS

Depends on / 依赖: IsGenerating, IsGenerating.le
-/
lemma exists_oneHypercover [H.IsGenerating] {X : C} (S : Sieve X) (hS : S in J X) :
    exists (E : J.OneHypercover X) (_ : H E), E.sieve₀ <= S :=
  IsGenerating.le _ hS

variable (P : Cᵒᵖ ⥤ A)

namespace IsSheafIff

variable (hP : forall ⦃X : C⦄ (E : J.OneHypercover X) (_ : H E), Nonempty (IsLimit (E.multifork P)))

include hP in
/--
lemma `hom_ext` / 引理 `hom_ext`

English:
lemma hom_ext
  statement: [H.IsGenerating] {X : C} (S : Sieve X) (hS : S in J X) {T : A}
  proof: by
  obtain ⟨E, hE, le⟩ := H.exists_oneHypercover S hS
  exact Multifork.IsLimit.hom_ext (hP E hE).some (fun j => h _ (le _ (Sieve.ofArrows_mk _ _ _)))

中文:
引理 hom_ext
  结论: [H.是Generating] {X : C} (S : 筛 X) (hS : S in J X) {T : A}
  证明: by
  obtain ⟨E, hE, le⟩ := H.exists_oneHypercover S hS
  exact Multifork.IsLimit.hom_ext (hP E hE).some (fun j => h _ (le _ (Sieve.ofArrows_mk _ _ _)))

Depends on / 依赖: H.exists_oneHypercover, IsLimit, Multifork, Multifork.IsLimit.hom_ext, Sieve.ofArrows_mk, exists_oneHypercover, hom_ext, ofArrows_mk
-/
lemma hom_ext [H.IsGenerating] {X : C} (S : Sieve X) (hS : S in J X) {T : A}
    {x y : T ⟶ P.obj (Opposite.op X)}
    (h : forall ⦃Y : C⦄ (f : Y ⟶ X) (_ : S f), x ≫ P.map f.op = y ≫ P.map f.op) :
    x = y := by
  obtain ⟨E, hE, le⟩ := H.exists_oneHypercover S hS
  exact Multifork.IsLimit.hom_ext (hP E hE).some (fun j => h _ (le _ (Sieve.ofArrows_mk _ _ _)))

variable {P H}
variable {X : C} {S : Sieve X} {E : J.OneHypercover X} (hE : H E) (le : E.sieve₀ <= S)

section

variable (F : Multifork (Cover.index ⟨S, J.superset_covering le E.mem₀⟩ P))

/--
Definition of `lift` / `lift` 的定义

English:
definition lift
  signature: : F.pt ⟶ P.obj (Opposite.op X)
  body: Multifork.IsLimit.lift (hP E hE).some
    (fun i => F.ι ⟨_, E.f i, le _ (Sieve.ofArrows_mk _ _ _)⟩)
    (fun ⟨⟨i₁, i₂⟩, j⟩ =>
      F.condition {
        fst := { hf := le _ (Sieve.ofArrows_mk _ _ i₁), .. }
        snd := { hf := le _ (Sieve.ofArrows_mk _ _ i₂), .. }
        r := { w := E.w j, .. }
      })

@[reassoc]

中文:
定义 lift
  签名: : F.pt ⟶ P.obj (对偶.op X)
  定义体: Multifork.IsLimit.lift (hP E hE).some
    (fun i => F.ι ⟨_, E.f i, le _ (Sieve.ofArrows_mk _ _ _)⟩)
    (fun ⟨⟨i₁, i₂⟩, j⟩ =>
      F.condition {
        fst := { hf := le _ (Sieve.ofArrows_mk _ _ i₁), .. }
        snd := { hf := le _ (Sieve.ofArrows_mk _ _ i₂), .. }
        r := { w := E.w j, .. }
      })

@[reassoc]

Depends on / 依赖: F.condition, IsLimit, Multifork, Multifork.IsLimit.lift, Sieve.ofArrows_mk, condition, ofArrows_mk
-/
noncomputable def lift : F.pt ⟶ P.obj (Opposite.op X) :=
  Multifork.IsLimit.lift (hP E hE).some
    (fun i => F.ι ⟨_, E.f i, le _ (Sieve.ofArrows_mk _ _ _)⟩)
    (fun ⟨⟨i₁, i₂⟩, j⟩ =>
      F.condition {
        fst := { hf := le _ (Sieve.ofArrows_mk _ _ i₁), .. }
        snd := { hf := le _ (Sieve.ofArrows_mk _ _ i₂), .. }
        r := { w := E.w j, .. }
      })

@[reassoc]
/--
lemma `fac'` / 引理 `fac'`

English:
lemma fac'
  given: (i : E.I₀)
  proof: Multifork.IsLimit.fac (hP E hE).some _ _ i

中文:
引理 fac'
  条件: (i : E.I₀)
  证明: Multifork.IsLimit.fac (hP E hE).some _ _ i

Depends on / 依赖: IsLimit, Multifork, Multifork.IsLimit.fac
-/
lemma fac' (i : E.I₀) :
    lift hP hE le F ≫ P.map (E.f i).op =
      F.ι ⟨_, E.f i, le _ (Sieve.ofArrows_mk _ _ _)⟩ :=
  Multifork.IsLimit.fac (hP E hE).some _ _ i

/--
lemma `fac` / 引理 `fac`

English:
lemma fac
  given: [H.IsGenerating] {Y : C} (f : Y ⟶ X) (hf : S f)
  proof: by
  apply hom_ext H P hP _ (J.pullback_stable f E.mem₀)
  intro Z g
  rintro ⟨T, a, b, ⟨i⟩, fac⟩
  rw [assoc]; rw [← P.map_comp]; rw [← op_comp]; rw [← fac]; rw [op_comp]; rw [P.map_comp]; rw [fac'_assoc]
  exact F.condition {
    fst := { hf := le _ (Sieve.ofArrows_mk _ _ _), .. }
    snd := { hf := hf, .. }
    r := { w := fac, .. }
  }

中文:
引理 fac
  条件: [H.是Generating] {Y : C} (f : Y ⟶ X) (hf : S f)
  证明: by
  apply hom_ext H P hP _ (J.pullback_stable f E.mem₀)
  intro Z g
  rintro ⟨T, a, b, ⟨i⟩, fac⟩
  rw [assoc]; rw [← P.map_comp]; rw [← op_comp]; rw [← fac]; rw [op_comp]; rw [P.map_comp]; rw [fac'_assoc]
  exact F.condition {
    fst := { hf := le _ (Sieve.ofArrows_mk _ _ _), .. }
    snd := { hf := hf, .. }
    r := { w := fac, .. }
  }

Depends on / 依赖: E.mem, F.condition, J.pullback_stable, P.map_comp, Sieve.ofArrows_mk, _assoc, condition, hom_ext, map_comp, ofArrows_mk, op_comp, pullback_stable
-/
lemma fac [H.IsGenerating] {Y : C} (f : Y ⟶ X) (hf : S f) :
    lift hP hE le F ≫ P.map f.op = F.ι ⟨Y, f, hf⟩ := by
  apply hom_ext H P hP _ (J.pullback_stable f E.mem₀)
  intro Z g
  rintro ⟨T, a, b, ⟨i⟩, fac⟩
  rw [assoc]; rw [← P.map_comp]; rw [← op_comp]; rw [← fac]; rw [op_comp]; rw [P.map_comp]; rw [fac'_assoc]
  exact F.condition {
    fst := { hf := le _ (Sieve.ofArrows_mk _ _ _), .. }
    snd := { hf := hf, .. }
    r := { w := fac, .. }
  }

end

/--
Definition of `isLimit` / `isLimit` 的定义

English:
definition isLimit
  signature: [H.IsGenerating]
  body: Multifork.IsLimit.mk _
    (fun F => lift hP hE le F)
    (fun F => by
      rintro ⟨Y, f, hf⟩
      apply fac)
    (fun F m hm => by
      apply hom_ext H P hP S (J.superset_covering le E.mem₀)
      intro Y f hf
      rw [fac _ _ _ _ _ hf]
      exact hm ⟨_, _, hf⟩)

中文:
定义 isLimit
  签名: [H.是Generating]
  定义体: Multifork.IsLimit.mk _
    (fun F => lift hP hE le F)
    (fun F => by
      rintro ⟨Y, f, hf⟩
      apply fac)
    (fun F m hm => by
      apply hom_ext H P hP S (J.superset_covering le E.mem₀)
      intro Y f hf
      rw [fac _ _ _ _ _ hf]
      exact hm ⟨_, _, hf⟩)

Depends on / 依赖: E.mem, IsLimit, J.superset_covering, Multifork, Multifork.IsLimit.mk, hom_ext, superset_covering
-/
noncomputable def isLimit [H.IsGenerating] :
    IsLimit (Cover.multifork ⟨S, J.superset_covering le E.mem₀⟩ P) :=
  Multifork.IsLimit.mk _
    (fun F => lift hP hE le F)
    (fun F => by
      rintro ⟨Y, f, hf⟩
      apply fac)
    (fun F m hm => by
      apply hom_ext H P hP S (J.superset_covering le E.mem₀)
      intro Y f hf
      rw [fac _ _ _ _ _ hf]
      exact hm ⟨_, _, hf⟩)

end IsSheafIff

/--
lemma `isSheaf_iff` / 引理 `isSheaf_iff`

English:
lemma isSheaf_iff
  given: [H.IsGenerating]
  proof: by
  constructor
  · intro hP X E _
    exact ⟨E.isLimitMultifork ⟨_, hP⟩⟩
  · intro hP
    rw [Presheaf.isSheaf_iff_multifork]
    rintro X ⟨S, hS⟩
    obtain ⟨E, hE, le⟩ := H.exists_oneHypercover S hS
    exact ⟨IsSheafIff.isLimit hP hE le⟩

中文:
引理 isSheaf_iff
  条件: [H.是Generating]
  证明: by
  constructor
  · intro hP X E _
    exact ⟨E.isLimitMultifork ⟨_, hP⟩⟩
  · intro hP
    rw [Presheaf.isSheaf_iff_multifork]
    rintro X ⟨S, hS⟩
    obtain ⟨E, hE, le⟩ := H.exists_oneHypercover S hS
    exact ⟨IsSheafIff.isLimit hP hE le⟩

Depends on / 依赖: E.isLimitMultifork, H.exists_oneHypercover, IsSheafIff, IsSheafIff.isLimit, Presheaf, Presheaf.isSheaf_iff_multifork, exists_oneHypercover, isLimit, isLimitMultifork, isSheaf_iff_multifork
-/
lemma isSheaf_iff [H.IsGenerating] :
    Presheaf.IsSheaf J P ↔ forall ⦃X : C⦄ (E : J.OneHypercover X)
      (_ : H E), Nonempty (IsLimit (E.multifork P)) := by
  constructor
  · intro hP X E _
    exact ⟨E.isLimitMultifork ⟨_, hP⟩⟩
  · intro hP
    rw [Presheaf.isSheaf_iff_multifork]
    rintro X ⟨S, hS⟩
    obtain ⟨E, hE, le⟩ := H.exists_oneHypercover S hS
    exact ⟨IsSheafIff.isLimit hP hE le⟩

end OneHypercoverFamily

/--
Definition of `IsGeneratedByOneHypercovers` / `IsGeneratedByOneHypercovers` 的定义

English:
abbreviation IsGeneratedByOneHypercovers
  signature: : Prop
  body: OneHypercoverFamily.IsGenerating.{w} (J := J) ⊤

中文:
缩写 IsGeneratedByOneHypercovers
  签名: : 命题
  定义体: OneHypercoverFamily.IsGenerating.{w} (J := J) ⊤

Depends on / 依赖: IsGenerating, OneHypercoverFamily, OneHypercoverFamily.IsGenerating
-/
abbrev IsGeneratedByOneHypercovers : Prop :=
  OneHypercoverFamily.IsGenerating.{w} (J := J) ⊤

set_option backward.isDefEq.respectTransparency.types false in
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: IsGeneratedByOneHypercovers.{max u v} J
  body: ⟨Cover.oneHypercover ⟨S, hS⟩, by simp, by simp⟩

中文:
实例 :
  签名: IsGeneratedByOneHypercovers.{最大值 u v} J
  定义体: ⟨Cover.oneHypercover ⟨S, hS⟩, by simp, by simp⟩

Depends on / 依赖: Cover.oneHypercover, oneHypercover
-/
instance : IsGeneratedByOneHypercovers.{max u v} J where
  le S hS := ⟨Cover.oneHypercover ⟨S, hS⟩, by simp, by simp⟩

end GrothendieckTopology

namespace Presheaf

/--
lemma `isSheaf_iff_of_isGeneratedByOneHypercovers` / 引理 `isSheaf_iff_of_isGeneratedByOneHypercovers`

English:
lemma isSheaf_iff_of_isGeneratedByOneHypercovers
  proof: by
  simpa using GrothendieckTopology.OneHypercoverFamily.isSheaf_iff.{w} ⊤ P

中文:
引理 isSheaf_iff_of_isGeneratedByOneHypercovers
  证明: by
  simpa using GrothendieckTopology.OneHypercoverFamily.isSheaf_iff.{w} ⊤ P

Depends on / 依赖: GrothendieckTopology, GrothendieckTopology.OneHypercoverFamily.isSheaf_iff, OneHypercoverFamily, isSheaf_iff
-/
lemma isSheaf_iff_of_isGeneratedByOneHypercovers
    [GrothendieckTopology.IsGeneratedByOneHypercovers.{w} J] (P : Cᵒᵖ ⥤ A) :
    IsSheaf J P ↔ forall ⦃X : C⦄ (E : GrothendieckTopology.OneHypercover.{w} J X),
        Nonempty (IsLimit (E.multifork P)) := by
  simpa using GrothendieckTopology.OneHypercoverFamily.isSheaf_iff.{w} ⊤ P

end Presheaf

end CategoryTheory
