/-
Copyright (c) 2021 David Wärn. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Wärn, Eric Wieser, Joachim Breitner
-/
module

public import Mathlib.GroupTheory.FreeGroup.Basic

/-!
# Free groups structures on arbitrary types

This file defines the notion of free basis of a group, which induces an isomorphism between the
group and the free group generated by the basis.

It also introduced a type class for groups which are free groups, i.e., for which some free basis
exists.

For the explicit construction of free groups, see `GroupTheory/FreeGroup`.

## Main definitions

* `FreeGroupBasis ι G` : a function from `ι` to `G` such that `G` is free over its image.
  Equivalently, an isomorphism between `G` and `FreeGroup ι`.

* `IsFreeGroup G` : a typeclass to indicate that `G` is free over some generators
* `Generators G` : given a group satisfying `IsFreeGroup G`, some indexing type over
  which `G` is free.
* `IsFreeGroup.of` : the canonical injection of `G`'s generators into `G`
* `IsFreeGroup.lift` : the universal property of the free group

## Main results

* `FreeGroupBasis.isFreeGroup`: a group admitting a free group basis is free.
* `IsFreeGroup.toFreeGroup`: any free group with generators `A` is equivalent to `FreeGroup A`.
* `IsFreeGroup.unique_lift`: the universal property of a free group.
* `FreeGroupBasis.ofUniqueLift`: a group satisfying the universal property of a free group admits
  a free group basis.

-/

@[expose] public section


universe u

open Function Set

noncomputable section

/-- A free group basis `FreeAddGroupBasis ι G` is a structure recording the isomorphism between an
additive group `G` and the additive free group over `ι`. One may think of such a basis as a function
from `ι` to `G` (which is registered through a `FunLike` instance) together with the fact that the
morphism induced by this function from `FreeAddGroup ι` to `G` is an isomorphism. -/
/-
**FreeAddGroupBasis** 是 Mathlib 中的一个归纳类型，位于命名空间 ``。
形式化陈述：Type u_1 → (G : Type u_2) → [AddGroup G] → Type (max u_1 u_2)
参数：G : Type u_2；max u_1 u_2。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
A free group basis `FreeAddGroupBasis ι G` is a structure recording the isomorph
ism between an
additive group `G` and the additive free group over `ι`. One may think of such a
 basis as a function
from `ι` to `G` (which is registered through a `FunLike` instance) together with
 the fact that the
morphism induced by this function from `FreeAddGroup ι` to `G` is an isomorphism
.
-/
structure FreeAddGroupBasis (ι : Type*) (G : Type*) [AddGroup G] where
  /-- `FreeAddGroupBasis.ofRepr` constructs a basis given an equivalence with an additive free
  group. -/
  ofRepr ::
    /-- `repr` is the isomorphism between the additive group `G` and the additive free group
    generated by `ι`. -/
    repr : G ≃+ FreeAddGroup ι

/-- A free group basis `FreeGroupBasis ι G` is a structure recording the isomorphism between a
group `G` and the free group over `ι`. One may think of such a basis as a function from `ι` to `G`
(which is registered through a `FunLike` instance) together with the fact that the morphism induced
by this function from `FreeGroup ι` to `G` is an isomorphism. -/
@[to_additive]
/-
**FreeGroupBasis** 是 Mathlib 中的一个归纳类型，位于命名空间 ``。
形式化陈述：Type u_1 → (G : Type u_2) → [Group G] → Type (max u_1 u_2)
参数：G : Type u_2；max u_1 u_2。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
A free group basis `FreeGroupBasis ι G` is a structure recording the isomorphism
 between a
group `G` and the free group over `ι`. One may think of such a basis as a functi
on from `ι` to `G`
(which is registered through a `FunLike` instance) together with the fact that t
he morphism induced
by this function from `FreeGroup ι` to `G` is an isomorphism.
-/
structure FreeGroupBasis (ι : Type*) (G : Type*) [Group G] where
  /-- `FreeGroupBasis.ofRepr` constructs a basis given an equivalence with a free group. -/
  ofRepr ::
    /-- `repr` is the isomorphism between the group `G` and the free group generated by `ι`. -/
    repr : G ≃* FreeGroup ι

/-- An additive group is free if it admits an additive free group basis. In the definition, we
require the basis to be in the same universe as `G`, although this property follows from the
existence of a basis in any universe, see `FreeAddGroupBasis.isFreeAddGroup`. -/
/-
**IsFreeAddGroup** 是 Mathlib 中的一个归纳类型，位于命名空间 ``。
形式化陈述：(G : Type u) → [AddGroup G] → Prop
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
An additive group is free if it admits an additive free group basis. In the defi
nition, we
require the basis to be in the same universe as `G`, although this property foll
ows from the
existence of a basis in any universe, see `FreeAddGroupBasis.isFreeAddGroup`.
-/
class IsFreeAddGroup (G : Type u) [AddGroup G] : Prop where
  nonempty_basis : ∃ (ι : Type u), Nonempty (FreeAddGroupBasis ι G)

/-- A group is free if it admits a free group basis. In the definition, we require the basis to
be in the same universe as `G`, although this property follows from the existence of a basis in
any universe, see `FreeGroupBasis.isFreeGroup`. -/
@[to_additive]
/-
**IsFreeGroup** 是 Mathlib 中的一个归纳类型，位于命名空间 ``。
形式化陈述：(G : Type u) → [Group G] → Prop
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
A group is free if it admits a free group basis. In the definition, we require t
he basis to
be in the same universe as `G`, although this property follows from the existenc
e of a basis in
any universe, see `FreeGroupBasis.isFreeGroup`.
-/
class IsFreeGroup (G : Type u) [Group G] : Prop where
  nonempty_basis : ∃ (ι : Type u), Nonempty (FreeGroupBasis ι G)

namespace FreeGroupBasis

variable {ι ι' G H : Type*} [Group G] [Group H]

/-- A free group basis for `G` over `ι` is associated to a map `ι → G` recording the images of
the generators. -/
@[to_additive
/-- An additive free group basis for `G` over `ι` is associated to a map `ι → G` recording the
images of the generators. -/]
/-
**FreeGroupBasis.instFunLike** 是 Mathlib 中的一个实例，位于命名空间 `FreeGroupBasis`。
形式化陈述：instFunLike : FunLike (FreeGroupBasis ι G) ι G where coe b
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance instFunLike : FunLike (FreeGroupBasis ι G) ι G where
  coe b := fun i ↦ b.repr.symm (FreeGroup.of i)
  coe_injective := by
    rintro ⟨b⟩ ⟨b'⟩ hbb'
    have H : (b.symm : FreeGroup ι →* G) = (b'.symm : FreeGroup ι →* G) := by
      ext i; exact congr_fun hbb' i
    have : b.symm = b'.symm := by ext x; exact DFunLike.congr_fun H x
    rw [ofRepr.injEq, ← MulEquiv.symm_symm b, ← MulEquiv.symm_symm b', this]

@[to_additive (attr := simp)]
/-
**FreeGroupBasis.repr_apply_coe** 是 Mathlib 中的一个引理，位于命名空间 `FreeGroupBasis`。
形式化陈述：repr_apply_coe (b : FreeGroupBasis ι G) (i : ι) : b.repr (b i) = FreeGroup
.of i
参数：b : FreeGroupBasis ι G；i : ι。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `MulEquiv.apply_symm_apply`：apply_symm_apply (e : M ≃* N) (y : N) : e (e.
symm y) = y
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma repr_apply_coe (b : FreeGroupBasis ι G) (i : ι) : b.repr (b i) = FreeGroup.of i := by
  change b.repr (b.repr.symm (FreeGroup.of i)) = FreeGroup.of i
  simp

/-- The canonical basis of the free group over `X`. -/
@[to_additive /-- The canonical basis of the additive free group over `X`. -/]
/-
**FreeGroupBasis.ofFreeGroup** 是 Mathlib 中的一个定义，位于命名空间 `FreeGroupBasis`。
形式化陈述：ofFreeGroup (X : Type*) : FreeGroupBasis X (FreeGroup X)
参数：X : Type*。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The canonical basis of the free group over `X`.
-/
def ofFreeGroup (X : Type*) : FreeGroupBasis X (FreeGroup X) := ofRepr (MulEquiv.refl _)

@[to_additive (attr := simp)]
/-
**FreeGroupBasis.ofFreeGroup_apply** 是 Mathlib 中的一个引理，位于命名空间 `FreeGroupBasis`。
形式化陈述：ofFreeGroup_apply {X : Type*} (x : X) : FreeGroupBasis.ofFreeGroup X x = F
reeGroup.of x
参数：x : X。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma ofFreeGroup_apply {X : Type*} (x : X) :
    FreeGroupBasis.ofFreeGroup X x = FreeGroup.of x :=
  rfl

/-- Reindex a free group basis through a bijection of the indexing sets. -/
@[to_additive /-- Reindex an additive free group basis through a bijection of the indexing sets. -/]
/-
**FreeGroupBasis.reindex** 是 Mathlib 中的一个定义，位于命名空间 `FreeGroupBasis`。
形式化陈述：{ι : Type u_1} → {ι' : Type u_2} → {G : Type u_3} → [inst : Group G] → Fre
eGroupBasis ι G → ι ≃ ι' → FreeGroupBasis ι' G
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Reindex a free group basis through a bijection of the indexing sets.
-/
protected def reindex (b : FreeGroupBasis ι G) (e : ι ≃ ι') : FreeGroupBasis ι' G :=
  ofRepr (b.repr.trans (FreeGroup.freeGroupCongr e))

@[to_additive (attr := simp)]
/-
**FreeGroupBasis.reindex_apply** 是 Mathlib 中的一个引理，位于命名空间 `FreeGroupBasis`。
形式化陈述：reindex_apply (b : FreeGroupBasis ι G) (e : ι ≃ ι') (x : ι') : b.reindex e
 x = b (e.symm x)
参数：b : FreeGroupBasis ι G；e : ι ≃ ι'；x : ι'。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma reindex_apply (b : FreeGroupBasis ι G) (e : ι ≃ ι') (x : ι') :
    b.reindex e x = b (e.symm x) := rfl

/-- Pushing a free group basis through a group isomorphism. -/
@[to_additive /-- Pushing an additive free group basis through a group isomorphism. -/]
/-
**FreeGroupBasis.map** 是 Mathlib 中的一个定义，位于命名空间 `FreeGroupBasis`。
形式化陈述：{ι : Type u_1} →   {G : Type u_3} →     {H : Type u_4} → [inst : Group G] 
→ [inst_1 : Group H] → FreeGroupBasis ι G → G ≃* H → FreeGroupBasis ι H
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Pushing a free group basis through a group isomorphism.
-/
protected def map (b : FreeGroupBasis ι G) (e : G ≃* H) : FreeGroupBasis ι H :=
  ofRepr (e.symm.trans b.repr)

@[to_additive (attr := simp)]
/-
**FreeGroupBasis.map_apply** 是 Mathlib 中的一个引理，位于命名空间 `FreeGroupBasis`。
形式化陈述：map_apply (b : FreeGroupBasis ι G) (e : G ≃* H) (x : ι) : b.map e x = e (b
 x)
参数：b : FreeGroupBasis ι G；e : G ≃* H；x : ι。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma map_apply (b : FreeGroupBasis ι G) (e : G ≃* H) (x : ι) :
    b.map e x = e (b x) := rfl

@[to_additive]
/-
**FreeGroupBasis.injective** 是 Mathlib 中的一个定理，位于命名空间 `FreeGroupBasis`。
形式化陈述：∀ {ι : Type u_1} {G : Type u_3} [inst : Group G] (b : FreeGroupBasis ι G),
 Function.Injective ⇑b
参数：b : FreeGroupBasis ι G。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Function.Injective.comp`：∀ {α : Sort u_1} {β : Sort u_2} {γ : Sort u_3} 
{g : β → γ} {f : α → β},   Function.Injective g → Function.Injective f → Functio
n.Injective (…
· 使用定理 `MulEquiv.injective`：∀ {M : Type u_4} {N : Type u_5} [inst : Mul M] [inst
_1 : Mul N] (e : M ≃* N), Function.Injective ⇑e
· 使用定理 `FreeGroup.of_injective`：of_injective : Function.Injective (@of α)
-/
protected lemma injective (b : FreeGroupBasis ι G) : Injective b :=
  b.repr.symm.injective.comp FreeGroup.of_injective

/-- A group admitting a free group basis is a free group. -/
@[to_additive
/-- An additive group admitting an additive free group basis is an additive free group. -/]
/-
**FreeGroupBasis.isFreeGroup** 是 Mathlib 中的一个引理，位于命名空间 `FreeGroupBasis`。
形式化陈述：isFreeGroup (b : FreeGroupBasis ι G) : IsFreeGroup G
参数：b : FreeGroupBasis ι G。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `FreeGroupBasis.injective`：∀ {ι : Type u_1} {G : Type u_3} [inst : Group 
G] (b : FreeGroupBasis ι G), Function.Injective ⇑b
-/
lemma isFreeGroup (b : FreeGroupBasis ι G) : IsFreeGroup G :=
  ⟨range b, ⟨b.reindex (Equiv.ofInjective (↑b) b.injective)⟩⟩

@[to_additive]
/-
**FreeGroupBasis.** 是 Mathlib 中的一个实例，位于命名空间 `FreeGroupBasis`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance (X : Type*) : IsFreeGroup (FreeGroup X) :=
  (ofFreeGroup X).isFreeGroup

#adaptation_note
/-- `respectTransparency.types true` changes the auto-generated lemmas' signature -/
set_option backward.isDefEq.respectTransparency.types false in
/-- Given a free group basis of `G` over `ι`, there is a canonical bijection between maps from `ι`
to a group `H` and morphisms from `G` to `H`. -/
@[to_additive (attr := simps!)
/-- Given an additive free group basis of `G` over `ι`, there is a canonical bijection between
maps from `ι` to an additive group `H` and morphisms from `G` to `H`. -/]
/-
**FreeGroupBasis.lift** 是 Mathlib 中的一个定义，位于命名空间 `FreeGroupBasis`。
形式化陈述：lift (b : FreeGroupBasis ι G) : (ι -> H) ≃ (G ->* H)
参数：b : FreeGroupBasis ι G。
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.trans`：Equiv.trans {s t u : Computation α} : s ~ t -> t ~ u -> s ~
 u
-/
def lift (b : FreeGroupBasis ι G) : (ι → H) ≃ (G →* H) :=
  FreeGroup.lift.trans
    { toFun := fun f => f.comp b.repr.toMonoidHom
      invFun := fun f => f.comp b.repr.symm.toMonoidHom
      left_inv := fun f => by
        ext
        simp
      right_inv := fun f => by
        ext
        simp }

/-- If two morphisms on `G` coincide on the elements of a basis, then they coincide. -/
@[to_additive
/-- If two morphisms on `G` coincide on the elements of a basis, then they coincide. -/]
/-
**FreeGroupBasis.ext_hom** 是 Mathlib 中的一个引理，位于命名空间 `FreeGroupBasis`。
形式化陈述：ext_hom (b : FreeGroupBasis ι G) (f g : G ->* H) (h : forall i, f (b i) = 
g (b i)) : f = g
参数：b : FreeGroupBasis ι G；f g : G ->* H；h : forall i, f (b i) = g (b i)。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.injective`：∀ {α : Sort u} {β : Sort v} (e : α ≃ β), Function.Injec
tive ⇑e
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s
· 使用定理 `funext`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, (∀ (x : α
), f x = g x) → f = g
-/
lemma ext_hom (b : FreeGroupBasis ι G) (f g : G →* H) (h : ∀ i, f (b i) = g (b i)) : f = g :=
  b.lift.symm.injective <| funext h

/-- If a group satisfies the universal property of a free group with respect to a given type, then
it admits a free group basis based on this type. Here, the universal property is expressed as
in `IsFreeGroup.lift` and its properties. -/
@[to_additive
/-- If an additive group satisfies the universal property of an additive free group with respect to
a given type, then it admits an additive free group basis based on this type. Here, the universal
property is expressed as in `IsFreeAddGroup.lift` and its properties. -/]
/-
**FreeGroupBasis.ofLift** 是 Mathlib 中的一个定义，位于命名空间 `FreeGroupBasis`。
形式化陈述：ofLift {G : Type u} [Group G] (X : Type u) (of : X -> G) (lift : forall {H
 : Type u} [Group H], (X -> H) ≃ (G ->* H)) (lift_of : forall {H : Type u} [Grou
p H], forall (f : X -> H) (a), lift f (of a) = f a) : FreeGroupBasis X G where r
epr
参数：X : Type u；of : X -> G；lift : forall {H : Type u} [Group H], (X -> H) ≃ (G ->
* H)；lift_of : forall {H : Type u} [Group H], forall (f : X -> H) (a), lift f (o
f a) = f a。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
def ofLift {G : Type u} [Group G] (X : Type u) (of : X → G)
    (lift : ∀ {H : Type u} [Group H], (X → H) ≃ (G →* H))
    (lift_of : ∀ {H : Type u} [Group H], ∀ (f : X → H) (a), lift f (of a) = f a) :
    FreeGroupBasis X G where
  repr := MulEquiv.symm <| MonoidHom.toMulEquiv (FreeGroup.lift of) (lift FreeGroup.of)
      (by
        apply FreeGroup.ext_hom; intro x
        simp only [MonoidHom.coe_comp, Function.comp_apply, MonoidHom.id_apply,
          FreeGroup.lift_apply_of, lift_of])
      (by
        let lift_symm_of : ∀ {H : Type u} [Group H], ∀ (f : G →* H) (a),
          lift.symm f a = f (of a) := by intro H _ f a; simp [← lift_of (lift.symm f)]
        apply lift.symm.injective; ext x
        simp only [MonoidHom.coe_comp, Function.comp_apply, MonoidHom.id_apply,
          FreeGroup.lift_apply_of, lift_of, lift_symm_of])

/-- If a group satisfies the universal property of a free group with respect to a given type, then
it admits a free group basis based on this type. Here
the universal property is expressed as in `IsFreeGroup.unique_lift`. -/
@[to_additive
/-- If an additive group satisfies the universal property of an additive free group with respect to
a given type, then it admits an additive free group basis based on this type. Here
the universal property is expressed as in `IsFreeAddGroup.unique_lift`. -/]
/-
**FreeGroupBasis.ofUniqueLift** 是 Mathlib 中的一个定义，位于命名空间 `FreeGroupBasis`。
形式化陈述：ofUniqueLift {G : Type u} [Group G] (X : Type u) (of : X -> G) (h : forall
 {H : Type u} [Group H] (f : X -> H), exists! F : G ->* H, forall a, F (of a) = 
f a) : FreeGroupBasis X G
参数：X : Type u；of : X -> G；h : forall {H : Type u} [Group H] (f : X -> H), exists
! F : G ->* H, forall a, F (of a) = f a。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
def ofUniqueLift {G : Type u} [Group G] (X : Type u) (of : X → G)
    (h : ∀ {H : Type u} [Group H] (f : X → H), ∃! F : G →* H, ∀ a, F (of a) = f a) :
    FreeGroupBasis X G :=
  let lift {H : Type u} [Group H] : (X → H) ≃ (G →* H) :=
    { toFun := fun f => Classical.choose (h f)
      invFun := fun F => F ∘ of
      left_inv := fun f => funext (Classical.choose_spec (h f)).left
      right_inv := fun F => ((Classical.choose_spec (h (F ∘ of))).right F fun _ => rfl).symm }
  let lift_of {H : Type u} [Group H] (f : X → H) (a : X) : lift f (of a) = f a :=
    congr_fun (lift.symm_apply_apply f) a
  ofLift X of @lift @lift_of

end FreeGroupBasis

namespace IsFreeGroup

variable (G : Type*) [Group G] [IsFreeGroup G]

/-- A set of generators of a free group, chosen arbitrarily -/
@[to_additive /-- A set of generators of an additive free group, chosen arbitrarily -/]
/-
**IsFreeGroup.Generators** 是 Mathlib 中的一个定义，位于命名空间 `IsFreeGroup`。
形式化陈述：Generators : Type _
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `IsFreeGroup.nonempty_basis`：∀ {G : Type u} {inst : Group G} [self : IsFr
eeGroup G], ∃ ι, Nonempty (FreeGroupBasis ι G)

--- 原说明 ---
A set of generators of a free group, chosen arbitrarily
-/
def Generators : Type _ := (IsFreeGroup.nonempty_basis (G := G)).choose

/-- Any free group is isomorphic to "the" free group. -/
@[to_additive /-- Any additive free group is isomorphic to "the" additive free group. -/]
irreducible_def mulEquiv : FreeGroup (Generators G) ≃* G :=
  (IsFreeGroup.nonempty_basis (G := G)).choose_spec.some.repr.symm

/-- A free group basis of a free group `G`, over the set `Generators G`. -/
@[to_additive
/-- An additive free group basis of an additive free group `G`, over the set `Generators G`. -/]
/-
**IsFreeGroup.basis** 是 Mathlib 中的一个定义，位于命名空间 `IsFreeGroup`。
形式化陈述：basis : FreeGroupBasis (Generators G) G
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
def basis : FreeGroupBasis (Generators G) G := FreeGroupBasis.ofRepr (mulEquiv G).symm

/-- Any free group is isomorphic to "the" free group. -/
@[to_additive (attr := simps!)
/-- Any additive free group is isomorphic to "the" additive free group. -/]
/-
**IsFreeGroup.toFreeGroup** 是 Mathlib 中的一个定义，位于命名空间 `IsFreeGroup`。
形式化陈述：toFreeGroup : G ≃* FreeGroup (Generators G)
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
def toFreeGroup : G ≃* FreeGroup (Generators G) :=
  (mulEquiv G).symm

variable {G}

/-- The canonical injection of G's generators into G -/
@[to_additive /-- The canonical injection of G's generators into G -/]
/-
**IsFreeGroup.of** 是 Mathlib 中的一个定义，位于命名空间 `IsFreeGroup`。
形式化陈述：of : Generators G -> G
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The canonical injection of G's generators into G
-/
def of : Generators G → G :=
  (mulEquiv G).toFun ∘ FreeGroup.of

variable {H : Type*} [Group H]

/-- The equivalence between functions on the generators and group homomorphisms from a free group
given by those generators. -/
@[to_additive
/-- The equivalence between functions on the generators and additive group homomorphisms from an
additive free group given by those generators. -/]
/-
**IsFreeGroup.lift** 是 Mathlib 中的一个定义，位于命名空间 `IsFreeGroup`。
形式化陈述：lift : (Generators G -> H) ≃ (G ->* H)
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
def lift : (Generators G → H) ≃ (G →* H) :=
  (basis G).lift

@[to_additive (attr := simp)]
/-
**IsFreeGroup.lift_of** 是 Mathlib 中的一个定理，位于命名空间 `IsFreeGroup`。
形式化陈述：lift_of (f : Generators G -> H) (a : Generators G) : lift f (of a) = f a
参数：f : Generators G -> H；a : Generators G。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congr_fun`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, f = g 
→ ∀ (a : α), f a = g a
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s
· 使用定理 `Equiv.symm_apply_apply`：∀ {α : Sort u} {β : Sort v} (e : α ≃ β) (x : α),
 e.symm (e x) = x
-/
theorem lift_of (f : Generators G → H) (a : Generators G) : lift f (of a) = f a :=
  congr_fun (lift.symm_apply_apply f) a

@[to_additive (attr := simp)]
/-
**IsFreeGroup.lift_symm_apply** 是 Mathlib 中的一个定理，位于命名空间 `IsFreeGroup`。
形式化陈述：lift_symm_apply (f : G ->* H) (a : Generators G) : (lift.symm f) a = f (of
 a)
参数：f : G ->* H；a : Generators G。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s
-/
theorem lift_symm_apply (f : G →* H) (a : Generators G) : (lift.symm f) a = f (of a) :=
  rfl

/- Do not register this as an ext lemma, as `Generators G` is not canonical. -/
@[to_additive /- Do not register this as an ext lemma, as `Generators G` is not canonical. -/]
/-
**IsFreeGroup.ext_hom** 是 Mathlib 中的一个定理，位于命名空间 `IsFreeGroup`。
形式化陈述：ext_hom ⦃f g : G ->* H⦄ (h : forall a : Generators G, f (of a) = g (of a))
 : f = g
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.injective`：∀ {α : Sort u} {β : Sort v} (e : α ≃ β), Function.Injec
tive ⇑e
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s
· 使用定理 `funext`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, (∀ (x : α
), f x = g x) → f = g

--- 原说明 ---
Do not register this as an ext lemma, as `Generators G` is not canonical.
-/
theorem ext_hom ⦃f g : G →* H⦄ (h : ∀ a : Generators G, f (of a) = g (of a)) : f = g :=
  lift.symm.injective (funext h)

/-- The universal property of a free group: A function from the generators of `G` to another
group extends in a unique way to a homomorphism from `G`.

Note that since `IsFreeGroup.lift` is expressed as a bijection, it already
expresses the universal property. -/
@[to_additive
/-- The universal property of an additive free group: A function from the generators of `G` to
another additive group extends in a unique way to a homomorphism from `G`.

Note that since `IsFreeAddGroup.lift` is expressed as a bijection, it already
expresses the universal property. -/]
/-
**IsFreeGroup.unique_lift** 是 Mathlib 中的一个定理，位于命名空间 `IsFreeGroup`。
形式化陈述：unique_lift (f : Generators G -> H) : exists! F : G ->* H, forall a, F (of
 a) = f a
参数：f : Generators G -> H。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `funext`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, (∀ (x : α
), f x = g x) → f = g
· 使用定理 `Function.Bijective.existsUnique`：∀ {α : Sort u_1} {β : Sort u_2} {f : α 
→ β}, Function.Bijective f → ∀ (b : β), ∃! a, f a = b
· 使用定理 `Equiv.bijective`：∀ {α : Sort u} {β : Sort v} (e : α ≃ β), Function.Bijec
tive ⇑e
-/
theorem unique_lift (f : Generators G → H) : ∃! F : G →* H, ∀ a, F (of a) = f a := by
  simpa only [funext_iff] using! lift.symm.bijective.existsUnique f

/-- If a group satisfies the universal property of a free group with respect to a given type, then
it is free. Here, the universal property is expressed as in `IsFreeGroup.lift` and its
properties. -/
@[to_additive
/-- If an additive group satisfies the universal property of an additive free group with respect to
a given type, then it is free. Here, the universal property is expressed as in `IsFreeAddGroup.lift`
and its properties. -/]
/-
**IsFreeGroup.ofLift** 是 Mathlib 中的一个引理，位于命名空间 `IsFreeGroup`。
形式化陈述：ofLift {G : Type u} [Group G] (X : Type u) (of : X -> G) (lift : forall {H
 : Type u} [Group H], (X -> H) ≃ (G ->* H)) (lift_of : forall {H : Type u} [Grou
p H], forall (f : X -> H) (a), lift f (of a) = f a) : IsFreeGroup G
参数：X : Type u；of : X -> G；lift : forall {H : Type u} [Group H], (X -> H) ≃ (G ->
* H)；lift_of : forall {H : Type u} [Group H], forall (f : X -> H) (a), lift f (o
f a) = f a。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `FreeGroupBasis.isFreeGroup`：isFreeGroup (b : FreeGroupBasis ι G) : IsFre
eGroup G
-/
lemma ofLift {G : Type u} [Group G] (X : Type u) (of : X → G)
    (lift : ∀ {H : Type u} [Group H], (X → H) ≃ (G →* H))
    (lift_of : ∀ {H : Type u} [Group H], ∀ (f : X → H) (a), lift f (of a) = f a) :
    IsFreeGroup G :=
  (FreeGroupBasis.ofLift X of lift lift_of).isFreeGroup

/-- If a group satisfies the universal property of a free group with respect to a given type, then
it is free. Here the universal property is expressed as in `IsFreeGroup.unique_lift`. -/
@[to_additive
/-- If an additive group satisfies the universal property of an additive free group with respect to
a given type, then it is free. Here the universal property is expressed as in
`IsFreeAddGroup.unique_lift`. -/]
/-
**IsFreeGroup.ofUniqueLift** 是 Mathlib 中的一个引理，位于命名空间 `IsFreeGroup`。
形式化陈述：ofUniqueLift {G : Type u} [Group G] (X : Type u) (of : X -> G) (h : forall
 {H : Type u} [Group H] (f : X -> H), exists! F : G ->* H, forall a, F (of a) = 
f a) : IsFreeGroup G
参数：X : Type u；of : X -> G；h : forall {H : Type u} [Group H] (f : X -> H), exists
! F : G ->* H, forall a, F (of a) = f a。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `FreeGroupBasis.isFreeGroup`：isFreeGroup (b : FreeGroupBasis ι G) : IsFre
eGroup G
-/
lemma ofUniqueLift {G : Type u} [Group G] (X : Type u) (of : X → G)
    (h : ∀ {H : Type u} [Group H] (f : X → H), ∃! F : G →* H, ∀ a, F (of a) = f a) :
    IsFreeGroup G :=
  (FreeGroupBasis.ofUniqueLift X of h).isFreeGroup

@[to_additive]
/-
**IsFreeGroup.ofMulEquiv** 是 Mathlib 中的一个引理，位于命名空间 `IsFreeGroup`。
形式化陈述：ofMulEquiv (e : G ≃* H) : IsFreeGroup H
参数：e : G ≃* H。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `FreeGroupBasis.isFreeGroup`：isFreeGroup (b : FreeGroupBasis ι G) : IsFre
eGroup G
-/
lemma ofMulEquiv (e : G ≃* H) : IsFreeGroup H :=
  ((basis G).map e).isFreeGroup

end IsFreeGroup

