/-
Copyright (c) 2023 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz
-/
module

public import Mathlib.CategoryTheory.Sites.PrecoverageToGrothendieck
public import Mathlib.CategoryTheory.Sites.Sheaf

/-!

# Coverages

A coverage `K` on a category `C` is a set of presieves associated to every object `X : C`,
called "covering presieves".
This collection must satisfy a certain "pullback compatibility" condition, saying that
whenever `S` is a covering presieve on `X` and `f : Y ⟶ X` is a morphism, then there exists
some covering sieve `T` on `Y` such that `T` factors through `S` along `f`.

The main difference between a coverage and a Grothendieck pretopology is that we *do not*
require `C` to have pullbacks.
This is useful, for example, when we want to consider the Grothendieck topology on the category
of extremally disconnected sets in the context of condensed mathematics.

A more concrete example: If `ℬ` is a basis for a topology on a type `X` (in the sense of
`TopologicalSpace.IsTopologicalBasis`) then it naturally induces a coverage on `Opens X`
whose associated Grothendieck topology is the one induced by the topology
on `X` generated by `ℬ`. (Project: Formalize this!)

## Main Definitions and Results:

All definitions are in the `CategoryTheory` namespace.

- `Coverage C`: The type of coverages on `C`.
- `GrothendieckTopology.toCoverage C`: A function which associates a coverage to any Grothendieck
  topology.
- `Coverage.toGrothendieck C`: A function which associates a Grothendieck topology to any coverage.
- `Coverage.gi`: The two functions above form a Galois insertion.
- `Presieve.isSheaf_coverage`: Given `K : Coverage C` with associated
  Grothendieck topology `J`, a `Type*`-valued presheaf on `C` is a sheaf for `K` if and only if
  it is a sheaf for `J`.

## References
We don't follow any particular reference, but the arguments can probably be distilled from
the following sources:
- [Elephant]: *Sketches of an Elephant*, P. T. Johnstone: C2.1.
- [nLab, *Coverage*](https://ncatlab.org/nlab/show/coverage)
-/

@[expose] public section

namespace CategoryTheory

universe w w'

variable {C D : Type _} [Category* C] [Category* D]

open Limits

namespace Presieve

/--
Definition of `FactorsThruAlong` / `FactorsThruAlong` 的定义

English:
definition FactorsThruAlong
  signature: {X Y : C} (S : Presieve Y) (T : Presieve X) (f : Y ⟶ X)
  body: forall ⦃Z : C⦄ ⦃g : Z ⟶ Y⦄, S g ->
  exists (W : C) (i : Z ⟶ W) (e : W ⟶ X), T e ∧ i ≫ e = g ≫ f

中文:
定义 FactorsThruAlong
  签名: {X Y : C} (S : Presieve Y) (T : Presieve X) (f : Y ⟶ X)
  定义体: forall ⦃Z : C⦄ ⦃g : Z ⟶ Y⦄, S g ->
  exists (W : C) (i : Z ⟶ W) (e : W ⟶ X), T e ∧ i ≫ e = g ≫ f
-/
def FactorsThruAlong {X Y : C} (S : Presieve Y) (T : Presieve X) (f : Y ⟶ X) : Prop :=
  forall ⦃Z : C⦄ ⦃g : Z ⟶ Y⦄, S g ->
  exists (W : C) (i : Z ⟶ W) (e : W ⟶ X), T e ∧ i ≫ e = g ≫ f

/--
lemma `FactorsThruAlong.pullbackArrows` / 引理 `FactorsThruAlong.pullbackArrows`

English:
lemma FactorsThruAlong.pullbackArrows
  statement: {X Y : C} (f : X ⟶ Y)
  proof: by
  intro Z g ⟨W, b, hb⟩
  have := R.hasPullback f hb
  refine ⟨_, pullback.fst _ _, b, hb, pullback.condition⟩

中文:
引理 FactorsThruAlong.pullbackArrows
  结论: {X Y : C} (f : X ⟶ Y)
  证明: by
  intro Z g ⟨W, b, hb⟩
  have := R.hasPullback f hb
  refine ⟨_, pullback.fst _ _, b, hb, pullback.condition⟩

Depends on / 依赖: R.hasPullback, condition, hasPullback, pullback, pullback.condition, pullback.fst
-/
lemma FactorsThruAlong.pullbackArrows {X Y : C} (f : X ⟶ Y)
    (R : Presieve Y) [R.HasPullbacks f] :
    (Presieve.pullbackArrows f R).FactorsThruAlong R f := by
  intro Z g ⟨W, b, hb⟩
  have := R.hasPullback f hb
  refine ⟨_, pullback.fst _ _, b, hb, pullback.condition⟩

/--
Definition of `FactorsThru` / `FactorsThru` 的定义

English:
definition FactorsThru
  signature: {X : C} (S T : Presieve X)
  body: forall ⦃Z : C⦄ ⦃g : Z ⟶ X⦄, S g ->
  exists (W : C) (i : Z ⟶ W) (e : W ⟶ X), T e ∧ i ≫ e = g

@[simp]

中文:
定义 FactorsThru
  签名: {X : C} (S T : Presieve X)
  定义体: forall ⦃Z : C⦄ ⦃g : Z ⟶ X⦄, S g ->
  exists (W : C) (i : Z ⟶ W) (e : W ⟶ X), T e ∧ i ≫ e = g

@[simp]
-/
def FactorsThru {X : C} (S T : Presieve X) : Prop :=
  forall ⦃Z : C⦄ ⦃g : Z ⟶ X⦄, S g ->
  exists (W : C) (i : Z ⟶ W) (e : W ⟶ X), T e ∧ i ≫ e = g

@[simp]
/--
lemma `factorsThruAlong_id` / 引理 `factorsThruAlong_id`

English:
lemma factorsThruAlong_id
  given: {X : C} (S T : Presieve X)
  proof: by
  simp [FactorsThruAlong, FactorsThru]

中文:
引理 factorsThruAlong_id
  条件: {X : C} (S T : Presieve X)
  证明: by
  simp [FactorsThruAlong, FactorsThru]

Depends on / 依赖: FactorsThru, FactorsThruAlong
-/
lemma factorsThruAlong_id {X : C} (S T : Presieve X) :
    S.FactorsThruAlong T (𝟙 X) ↔ S.FactorsThru T := by
  simp [FactorsThruAlong, FactorsThru]

/--
lemma `factorsThru_of_le` / 引理 `factorsThru_of_le`

English:
lemma factorsThru_of_le
  given: {X : C} (S T : Presieve X) (h : S <= T)
  proof: fun Y g hg => ⟨Y, 𝟙 _, g, h _ _ hg, by simp⟩

中文:
引理 factorsThru_of_le
  条件: {X : C} (S T : Presieve X) (h : S <= T)
  证明: fun Y g hg => ⟨Y, 𝟙 _, g, h _ _ hg, by simp⟩
-/
lemma factorsThru_of_le {X : C} (S T : Presieve X) (h : S <= T) :
    S.FactorsThru T :=
  fun Y g hg => ⟨Y, 𝟙 _, g, h _ _ hg, by simp⟩

/--
lemma `le_of_factorsThru_sieve` / 引理 `le_of_factorsThru_sieve`

English:
lemma le_of_factorsThru_sieve
  given: {X : C} (S : Presieve X) (T : Sieve X) (h : S.FactorsThru T)
  proof: by
  rintro Y f hf
  obtain ⟨W, i, e, h1, rfl⟩ := h hf
  exact T.downward_closed h1 _

中文:
引理 le_of_factorsThru_sieve
  条件: {X : C} (S : Presieve X) (T : 筛 X) (h : S.FactorsThru T)
  证明: by
  rintro Y f hf
  obtain ⟨W, i, e, h1, rfl⟩ := h hf
  exact T.downward_closed h1 _

Depends on / 依赖: T.downward_closed, downward_closed
-/
lemma le_of_factorsThru_sieve {X : C} (S : Presieve X) (T : Sieve X) (h : S.FactorsThru T) :
    S <= T := by
  rintro Y f hf
  obtain ⟨W, i, e, h1, rfl⟩ := h hf
  exact T.downward_closed h1 _

/--
lemma `factorsThru_top` / 引理 `factorsThru_top`

English:
lemma factorsThru_top
  given: {X : C} (S : Presieve X)
  statement: S.FactorsThru ⊤
  proof: factorsThru_of_le _ _ le_top

中文:
引理 factorsThru_top
  条件: {X : C} (S : Presieve X)
  结论: S.FactorsThru ⊤
  证明: factorsThru_of_le _ _ le_top

Depends on / 依赖: factorsThru_of_le, le_top
-/
lemma factorsThru_top {X : C} (S : Presieve X) : S.FactorsThru ⊤ :=
  factorsThru_of_le _ _ le_top

/--
lemma `isSheafFor_of_factorsThru` / 引理 `isSheafFor_of_factorsThru`

English:
lemma isSheafFor_of_factorsThru
  proof: by
  simp only [← Presieve.isSeparatedFor_and_exists_isAmalgamation_iff_isSheafFor] at *
  choose W i e h1 h2 using H
  refine ⟨?_, fun x hx => ?_⟩
  · intro x y₁ y₂ h₁ h₂
    refine hS.1.ext (fun Y g hg => ?_)
    simp only [← h2 hg, op_comp, P.map_comp, types_comp_apply, h₁ _ (h1 _), h₂ _ (h1 _)]
  let y : S.FamilyOfElements P := fun Y g hg => P.map (i _).op (x (e hg) (h1 _))
  have hy : y.Compatible := by
    intro Y₁ Y₂ Z g₁ g₂ f₁ f₂ h₁ h₂ h
    rw [← types_comp_apply (P.map (i h₁).op) (P.map g₁.op)]; rw [← types_comp_apply (P.map (i h₂).op) (P.map g₂.op)]; rw [← P.map_comp]; rw [← op_comp]; rw [← P.map_comp]; rw [← op_comp]
    apply hx
    simp only [h2, h, Category.assoc]
  let ⟨_, h2'⟩ := hS
  obtain ⟨z, hz⟩ := h2' y hy
  refine ⟨z, fun Y g hg => ?_⟩
  obtain ⟨R, hR1, hR2⟩ := h hg
  choose WW ii ee hh1 hh2 using hR2
  refine hR1.ext (fun Q t ht => ?_)
  rw [← types_comp_apply (P.map g.op) (P.map t.op)]; rw [← P.map_comp]; rw [← op_comp]; rw [← hh2 ht]; rw [op_comp]; rw [P.map_comp]; rw [types_comp_apply]; rw [hz _ (hh1 _)]; rw [← types_comp_apply _ (P.map (ii ht).op)]; rw [← P.map_comp]; rw [← op_comp]
  apply hx
  simp only [Category.assoc, h2, hh2]

中文:
引理 isSheafFor_of_factorsThru
  证明: by
  simp only [← Presieve.isSeparatedFor_and_exists_isAmalgamation_iff_isSheafFor] at *
  choose W i e h1 h2 using H
  refine ⟨?_, fun x hx => ?_⟩
  · intro x y₁ y₂ h₁ h₂
    refine hS.1.ext (fun Y g hg => ?_)
    simp only [← h2 hg, op_comp, P.map_comp, types_comp_apply, h₁ _ (h1 _), h₂ _ (h1 _)]
  let y : S.FamilyOfElements P := fun Y g hg => P.map (i _).op (x (e hg) (h1 _))
  have hy : y.Compatible := by
    intro Y₁ Y₂ Z g₁ g₂ f₁ f₂ h₁ h₂ h
    rw [← types_comp_apply (P.map (i h₁).op) (P.map g₁.op)]; rw [← types_comp_apply (P.map (i h₂).op) (P.map g₂.op)]; rw [← P.map_comp]; rw [← op_comp]; rw [← P.map_comp]; rw [← op_comp]
    apply hx
    simp only [h2, h, Category.assoc]
  let ⟨_, h2'⟩ := hS
  obtain ⟨z, hz⟩ := h2' y hy
  refine ⟨z, fun Y g hg => ?_⟩
  obtain ⟨R, hR1, hR2⟩ := h hg
  choose WW ii ee hh1 hh2 using hR2
  refine hR1.ext (fun Q t ht => ?_)
  rw [← types_comp_apply (P.map g.op) (P.map t.op)]; rw [← P.map_comp]; rw [← op_comp]; rw [← hh2 ht]; rw [op_comp]; rw [P.map_comp]; rw [types_comp_apply]; rw [hz _ (hh1 _)]; rw [← types_comp_apply _ (P.map (ii ht).op)]; rw [← P.map_comp]; rw [← op_comp]
  apply hx
  simp only [Category.assoc, h2, hh2]

Depends on / 依赖: Compatible, FamilyOfElements, P.map, P.map_comp, Presieve, Presieve.isSeparatedFor_and_exists_isAmalgamation_iff_isSheafFor, S.FamilyOfElements, isSeparatedFor_and_exists_isAmalgamation_iff_isSheafFor, map_comp, op_comp, types_comp_, types_comp_apply, y.Compatible
-/
lemma isSheafFor_of_factorsThru
    {X : C} {S T : Presieve X}
    (P : Cᵒᵖ ⥤ Type*)
    (H : S.FactorsThru T) (hS : S.IsSheafFor P)
    (h : forall ⦃Y : C⦄ ⦃f : Y ⟶ X⦄, T f -> exists (R : Presieve Y),
      R.IsSeparatedFor P ∧ R.FactorsThruAlong S f) :
    T.IsSheafFor P := by
  simp only [← Presieve.isSeparatedFor_and_exists_isAmalgamation_iff_isSheafFor] at *
  choose W i e h1 h2 using H
  refine ⟨?_, fun x hx => ?_⟩
  · intro x y₁ y₂ h₁ h₂
    refine hS.1.ext (fun Y g hg => ?_)
    simp only [← h2 hg, op_comp, P.map_comp, types_comp_apply, h₁ _ (h1 _), h₂ _ (h1 _)]
  let y : S.FamilyOfElements P := fun Y g hg => P.map (i _).op (x (e hg) (h1 _))
  have hy : y.Compatible := by
    intro Y₁ Y₂ Z g₁ g₂ f₁ f₂ h₁ h₂ h
    rw [← types_comp_apply (P.map (i h₁).op) (P.map g₁.op)]; rw [← types_comp_apply (P.map (i h₂).op) (P.map g₂.op)]; rw [← P.map_comp]; rw [← op_comp]; rw [← P.map_comp]; rw [← op_comp]
    apply hx
    simp only [h2, h, Category.assoc]
  let ⟨_, h2'⟩ := hS
  obtain ⟨z, hz⟩ := h2' y hy
  refine ⟨z, fun Y g hg => ?_⟩
  obtain ⟨R, hR1, hR2⟩ := h hg
  choose WW ii ee hh1 hh2 using hR2
  refine hR1.ext (fun Q t ht => ?_)
  rw [← types_comp_apply (P.map g.op) (P.map t.op)]; rw [← P.map_comp]; rw [← op_comp]; rw [← hh2 ht]; rw [op_comp]; rw [P.map_comp]; rw [types_comp_apply]; rw [hz _ (hh1 _)]; rw [← types_comp_apply _ (P.map (ii ht).op)]; rw [← P.map_comp]; rw [← op_comp]
  apply hx
  simp only [Category.assoc, h2, hh2]


end Presieve

variable (C) in
/--
The type `Coverage C` of coverages on `C`.
A coverage is a collection of *covering* presieves on every object `X : C`,
which satisfies a *pullback compatibility* condition.
Explicitly, this condition says that whenever `S` is a covering presieve for `X` and
`f : Y ⟶ X` is a morphism, then there exists some covering presieve `T` for `Y`
such that `T` factors through `S` along `f`.
-/
@[ext]
/--
Definition of `Coverage` / `Coverage` 的定义

English:
structure Coverage
  parameters: extends Precoverage C
  extends: Precoverage C
  axioms and operations (1):
    - pullback : forall ⦃X Y : C⦄ (f : Y ⟶ X) (S : Presieve X) (_ : S in coverings X), exists (T : Presieve Y), T in coverings Y ∧ T.FactorsThruAlong S f

中文:
结构 余verage
  参数: extends Precoverage C
  继承: Precoverage C
  公理与运算 (1 个):
    - pullback : 对任意 ⦃X Y : C⦄ (f : Y ⟶ X) (S : Presieve X) (_ : S in coverings X), 存在 (T : Presieve Y), T in coverings Y ∧ T.FactorsThruAlong S f
-/
structure Coverage extends Precoverage C where
  /-- Given any covering sieve `S` on `X` and a morphism `f : Y ⟶ X`, there exists
  some covering sieve `T` on `Y` such that `T` factors through `S` along `f`. -/
  pullback : forall ⦃X Y : C⦄ (f : Y ⟶ X) (S : Presieve X) (_ : S in coverings X),
    exists (T : Presieve Y), T in coverings Y ∧ T.FactorsThruAlong S f

namespace Coverage

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: CoeFun (Coverage C) (fun _ => (X : C) -> Set (Presieve X))
  body: J.coverings

中文:
实例 :
  签名: CoeFun (余verage C) (fun _ => (X : C) -> 集合 (Presieve X))
  定义体: J.coverings

Depends on / 依赖: J.coverings, coverings
-/
instance : CoeFun (Coverage C) (fun _ => (X : C) -> Set (Presieve X)) where
  coe J := J.coverings

end Coverage

/--
Definition of `GrothendieckTopology.toCoverage` / `GrothendieckTopology.toCoverage` 的定义

English:
definition GrothendieckTopology.toCoverage
  signature: (J : GrothendieckTopology C)
  body: { S | Sieve.generate S in J X }
  pullback := by
    intro X Y f S (hS : Sieve.generate S in J X)
    refine ⟨(Sieve.generate S).pullback f, ?_, fun Z g h => h⟩
    dsimp
    rw [Sieve.generate_sieve]
    exact J.pullback_stable _ hS

中文:
定义 Grothendieck拓扑.toCoverage
  签名: (J : Grothendieck拓扑 C)
  定义体: { S | Sieve.generate S in J X }
  pullback := by
    intro X Y f S (hS : Sieve.generate S in J X)
    refine ⟨(Sieve.generate S).pullback f, ?_, fun Z g h => h⟩
    dsimp
    rw [Sieve.generate_sieve]
    exact J.pullback_stable _ hS

Depends on / 依赖: Sieve.generate, generate
-/
def GrothendieckTopology.toCoverage (J : GrothendieckTopology C) : Coverage C where
  coverings X := { S | Sieve.generate S in J X }
  pullback := by
    intro X Y f S (hS : Sieve.generate S in J X)
    refine ⟨(Sieve.generate S).pullback f, ?_, fun Z g h => h⟩
    dsimp
    rw [Sieve.generate_sieve]
    exact J.pullback_stable _ hS

/--
lemma `GrothendieckTopology.mem_toCoverage_iff` / 引理 `GrothendieckTopology.mem_toCoverage_iff`

English:
lemma GrothendieckTopology.mem_toCoverage_iff
  statement: {X : C} {S : Presieve X}
  proof: Iff.rfl

中文:
引理 Grothendieck拓扑.mem_toCoverage_iff
  结论: {X : C} {S : Presieve X}
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
lemma GrothendieckTopology.mem_toCoverage_iff {X : C} {S : Presieve X}
    (J : GrothendieckTopology C) :
    S in J.toCoverage X ↔ Sieve.generate S in J X := Iff.rfl

namespace Coverage

/--
Inductive type `Saturate` / 归纳类型 `Saturate`

English:
inductive Saturate
  parameters: (K : Coverage C)
  constructors (3):
    - of: (X : C) (S : Presieve X) (hS : S in K X) : Saturate K X (Sieve.generate S)
    - top: (X : C) : Saturate K X ⊤
    - transitive: (X : C) (R S : Sieve X) : Saturate K X R -> (forall ⦃Y : C⦄ ⦃f : Y ⟶ X⦄, R f -> Saturate K Y (S.pullback f)) -> Saturate K X S

中文:
归纳类型 Saturate
  参数: (K : 余verage C)
  构造子 (3 个):
    - of: (X : C) (S : Presieve X) (hS : S in K X) : Saturate K X (筛.generate S)
    - top: (X : C) : Saturate K X ⊤
    - transitive: (X : C) (R S : 筛 X) : Saturate K X R -> (对任意 ⦃Y : C⦄ ⦃f : Y ⟶ X⦄, R f -> Saturate K Y (S.pullback f)) -> Saturate K X S
-/
inductive Saturate (K : Coverage C) : (X : C) -> Sieve X -> Prop where
  | of (X : C) (S : Presieve X) (hS : S in K X) : Saturate K X (Sieve.generate S)
  | top (X : C) : Saturate K X ⊤
  | transitive (X : C) (R S : Sieve X) :
    Saturate K X R ->
    (forall ⦃Y : C⦄ ⦃f : Y ⟶ X⦄, R f -> Saturate K Y (S.pullback f)) ->
    Saturate K X S

/--
lemma `eq_top_pullback` / 引理 `eq_top_pullback`

English:
lemma eq_top_pullback
  given: {X Y : C} {S T : Sieve X} (h : S <= T) (f : Y ⟶ X) (hf : S f)
  proof: by
  ext Z g
  simp only [Sieve.pullback_apply, Sieve.top_apply, iff_true]
  apply h
  apply S.downward_closed
  exact hf

中文:
引理 eq_top_pullback
  条件: {X Y : C} {S T : 筛 X} (h : S <= T) (f : Y ⟶ X) (hf : S f)
  证明: by
  ext Z g
  simp only [Sieve.pullback_apply, Sieve.top_apply, iff_true]
  apply h
  apply S.downward_closed
  exact hf

Depends on / 依赖: S.downward_closed, Sieve.pullback_apply, Sieve.top_apply, downward_closed, iff_true, pullback_apply, top_apply
-/
lemma eq_top_pullback {X Y : C} {S T : Sieve X} (h : S <= T) (f : Y ⟶ X) (hf : S f) :
    T.pullback f = ⊤ := by
  ext Z g
  simp only [Sieve.pullback_apply, Sieve.top_apply, iff_true]
  apply h
  apply S.downward_closed
  exact hf

/--
lemma `saturate_of_superset` / 引理 `saturate_of_superset`

English:
lemma saturate_of_superset
  statement: (K : Coverage C) {X : C} {S T : Sieve X} (h : S <= T)
  proof: by
  apply Saturate.transitive _ _ _ hS
  intro Y g hg
  rw [eq_top_pullback (h := h)]
  · apply Saturate.top
  · assumption

@[grind .]

中文:
引理 saturate_of_superset
  结论: (K : 余verage C) {X : C} {S T : 筛 X} (h : S <= T)
  证明: by
  apply Saturate.transitive _ _ _ hS
  intro Y g hg
  rw [eq_top_pullback (h := h)]
  · apply Saturate.top
  · assumption

@[grind .]

Depends on / 依赖: Saturate, Saturate.top, Saturate.transitive, eq_top_pullback, transitive
-/
lemma saturate_of_superset (K : Coverage C) {X : C} {S T : Sieve X} (h : S <= T)
    (hS : Saturate K X S) : Saturate K X T := by
  apply Saturate.transitive _ _ _ hS
  intro Y g hg
  rw [eq_top_pullback (h := h)]
  · apply Saturate.top
  · assumption

@[grind .]
/--
lemma `Saturate.pullback` / 引理 `Saturate.pullback`

English:
lemma Saturate.pullback
  statement: (K : Coverage C) {X Y : C} (f : Y ⟶ X) {S : Sieve X}
  proof: by
  induction h with
  | of X S hS =>
    obtain ⟨R, hR1, hR2⟩ := K.pullback f S hS
    suffices Sieve.generate R <= (Sieve.generate S).pullback f from
      saturate_of_superset _ this (Saturate.of _ _ hR1)
    intro Z g ⟨W, i, e, h1, h2⟩
    obtain ⟨WW, ii, ee, hh1, hh2⟩ := hR2 h1
    refine ⟨WW, i ≫ ii, ee, hh1, ?_⟩
    simp [hh2, reassoc_of% h2]
  | top X => exact .top _
  | transitive X R S _ hS H1 _ =>
    refine (H1 f).transitive _ _ _ fun Z g hg => ?_
    rw [← Sieve.pullback_comp]
    exact hS hg

中文:
引理 Saturate.pullback
  结论: (K : 余verage C) {X Y : C} (f : Y ⟶ X) {S : 筛 X}
  证明: by
  induction h with
  | of X S hS =>
    obtain ⟨R, hR1, hR2⟩ := K.pullback f S hS
    suffices Sieve.generate R <= (Sieve.generate S).pullback f from
      saturate_of_superset _ this (Saturate.of _ _ hR1)
    intro Z g ⟨W, i, e, h1, h2⟩
    obtain ⟨WW, ii, ee, hh1, hh2⟩ := hR2 h1
    refine ⟨WW, i ≫ ii, ee, hh1, ?_⟩
    simp [hh2, reassoc_of% h2]
  | top X => exact .top _
  | transitive X R S _ hS H1 _ =>
    refine (H1 f).transitive _ _ _ fun Z g hg => ?_
    rw [← Sieve.pullback_comp]
    exact hS hg

Depends on / 依赖: K.pullback, Saturate, Saturate.of, Sieve.generate, Sieve.pullback_comp, generate, pullback, pullback_comp, reassoc_of, saturate_of_superset, transitive
-/
lemma Saturate.pullback (K : Coverage C) {X Y : C} (f : Y ⟶ X) {S : Sieve X}
    (h : Saturate K X S) : Saturate K Y (S.pullback f) := by
  induction h with
  | of X S hS =>
    obtain ⟨R, hR1, hR2⟩ := K.pullback f S hS
    suffices Sieve.generate R <= (Sieve.generate S).pullback f from
      saturate_of_superset _ this (Saturate.of _ _ hR1)
    intro Z g ⟨W, i, e, h1, h2⟩
    obtain ⟨WW, ii, ee, hh1, hh2⟩ := hR2 h1
    refine ⟨WW, i ≫ ii, ee, hh1, ?_⟩
    simp [hh2, reassoc_of% h2]
  | top X => exact .top _
  | transitive X R S _ hS H1 _ =>
    refine (H1 f).transitive _ _ _ fun Z g hg => ?_
    rw [← Sieve.pullback_comp]
    exact hS hg

/--
lemma `saturate_iff_saturate_toPrecoverage` / 引理 `saturate_iff_saturate_toPrecoverage`

English:
lemma saturate_iff_saturate_toPrecoverage
  given: (K : Coverage C) {X : C} {S : Sieve X}
  proof: by
  constructor <;> intro hS
  · induction hS <;> grind [Precoverage.Saturate]
  · induction hS <;> grind [Saturate]

中文:
引理 saturate_iff_saturate_toPrecoverage
  条件: (K : 余verage C) {X : C} {S : 筛 X}
  证明: by
  constructor <;> intro hS
  · induction hS <;> grind [Precoverage.Saturate]
  · induction hS <;> grind [Saturate]

Depends on / 依赖: Precoverage, Precoverage.Saturate, Saturate
-/
lemma saturate_iff_saturate_toPrecoverage (K : Coverage C) {X : C} {S : Sieve X} :
    K.Saturate X S ↔ K.toPrecoverage.Saturate X S := by
  constructor <;> intro hS
  · induction hS <;> grind [Precoverage.Saturate]
  · induction hS <;> grind [Saturate]

/--
Definition of `toGrothendieck` / `toGrothendieck` 的定义

English:
definition toGrothendieck
  signature: (K : Coverage C)
  body: K.toPrecoverage.toGrothendieck.copy (fun X => Set.ofPred (K.Saturate X)) by
    ext
    exact K.saturate_iff_saturate_toPrecoverage.symm

中文:
定义 toGrothendieck
  签名: (K : 余verage C)
  定义体: K.toPrecoverage.toGrothendieck.copy (fun X => Set.ofPred (K.Saturate X)) by
    ext
    exact K.saturate_iff_saturate_toPrecoverage.symm

Depends on / 依赖: K.Saturate, K.saturate_iff_saturate_toPrecoverage.symm, K.toPrecoverage.toGrothendieck.copy, Saturate, Set.ofPred, ofPred, saturate_iff_saturate_toPrecoverage, toGrothendieck, toPrecoverage
-/
def toGrothendieck (K : Coverage C) : GrothendieckTopology C :=
K.toPrecoverage.toGrothendieck.copy (fun X => Set.ofPred (K.Saturate X)) by
    ext
    exact K.saturate_iff_saturate_toPrecoverage.symm

/--
lemma `mem_toGrothendieck` / 引理 `mem_toGrothendieck`

English:
lemma mem_toGrothendieck
  given: {K : Coverage C} {X : C} {S : Sieve X}
  proof: .rfl

中文:
引理 mem_toGrothendieck
  条件: {K : 余verage C} {X : C} {S : 筛 X}
  证明: .rfl
-/
lemma mem_toGrothendieck {K : Coverage C} {X : C} {S : Sieve X} :
    S in K.toGrothendieck X ↔ Saturate K X S := .rfl

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: PartialOrder (Coverage C)
  body: A.coverings <= B.coverings
  le_refl _ _ := le_refl _
  le_trans _ _ _ h1 h2 X := le_trans (h1 X) (h2 X)
le_antisymm _ _ h1 h2 := Coverage.ext funext
    fun X => le_antisymm (h1 X) (h2 X)

中文:
实例 :
  签名: 偏序 (余verage C)
  定义体: A.coverings <= B.coverings
  le_refl _ _ := le_refl _
  le_trans _ _ _ h1 h2 X := le_trans (h1 X) (h2 X)
le_antisymm _ _ h1 h2 := Coverage.ext funext
    fun X => le_antisymm (h1 X) (h2 X)

Depends on / 依赖: A.coverings, B.coverings, coverings
-/
instance : PartialOrder (Coverage C) where
  le A B := A.coverings <= B.coverings
  le_refl _ _ := le_refl _
  le_trans _ _ _ h1 h2 X := le_trans (h1 X) (h2 X)
le_antisymm _ _ h1 h2 := Coverage.ext funext
    fun X => le_antisymm (h1 X) (h2 X)

variable (C) in
/--
Definition of `gi` / `gi` 的定义

English:
definition gi
  signature: : GaloisInsertion (toGrothendieck (C := C)) (GrothendieckTopology.toCoverage (C := C)) where
  body: toGrothendieck K
  choice_eq := fun _ _ => rfl
  le_l_u J X S hS := by
    rw [← Sieve.generate_sieve S]
    apply Saturate.of
    dsimp [GrothendieckTopology.toCoverage]
    rwa [Sieve.generate_sieve S]
  gc K J := by
    constructor
    · intro H X S hS
exact H _ Saturate.of _ _ hS
    · intro H X S hS
      induction hS with
      | of X S hS => exact H _ hS
      | top => apply J.top_mem
      | transitive X R S _ _ H1 H2 => exact J.transitive H1 _ H2

中文:
定义 gi
  签名: : Galois嵌入 (toGrothendieck (C := C)) (Grothendieck拓扑.toCoverage (C := C)) where
  定义体: toGrothendieck K
  choice_eq := fun _ _ => rfl
  le_l_u J X S hS := by
    rw [← Sieve.generate_sieve S]
    apply Saturate.of
    dsimp [GrothendieckTopology.toCoverage]
    rwa [Sieve.generate_sieve S]
  gc K J := by
    constructor
    · intro H X S hS
exact H _ Saturate.of _ _ hS
    · intro H X S hS
      induction hS with
      | of X S hS => exact H _ hS
      | top => apply J.top_mem
      | transitive X R S _ _ H1 H2 => exact J.transitive H1 _ H2

Depends on / 依赖: GrothendieckTopology, GrothendieckTopology.toCoverage, toCoverage
-/
def gi : GaloisInsertion (toGrothendieck (C := C)) (GrothendieckTopology.toCoverage (C := C)) where
  choice K _ := toGrothendieck K
  choice_eq := fun _ _ => rfl
  le_l_u J X S hS := by
    rw [← Sieve.generate_sieve S]
    apply Saturate.of
    dsimp [GrothendieckTopology.toCoverage]
    rwa [Sieve.generate_sieve S]
  gc K J := by
    constructor
    · intro H X S hS
exact H _ Saturate.of _ _ hS
    · intro H X S hS
      induction hS with
      | of X S hS => exact H _ hS
      | top => apply J.top_mem
      | transitive X R S _ _ H1 H2 => exact J.transitive H1 _ H2

/--
theorem `toGrothendieck_eq_sInf` / 定理 `toGrothendieck_eq_sInf`

English:
theorem toGrothendieck_eq_sInf
  given: (K : Coverage C)
  statement: toGrothendieck K =
  proof: by
  apply le_antisymm
  · apply le_sInf
    intro J hJ X S hS
    induction hS with
    | of X S hS => apply hJ; assumption
    | top => apply J.top_mem
    | transitive X R S _ _ H1 H2 => exact J.transitive H1 _ H2
  · apply sInf_le
    intro X S hS
    apply Saturate.of _ _ hS

中文:
定理 toGrothendieck_eq_sInf
  条件: (K : 余verage C)
  结论: toGrothendieck K =
  证明: by
  apply le_antisymm
  · apply le_sInf
    intro J hJ X S hS
    induction hS with
    | of X S hS => apply hJ; assumption
    | top => apply J.top_mem
    | transitive X R S _ _ H1 H2 => exact J.transitive H1 _ H2
  · apply sInf_le
    intro X S hS
    apply Saturate.of _ _ hS

Depends on / 依赖: J.top_mem, J.transitive, Saturate, Saturate.of, le_antisymm, le_sInf, sInf_le, top_mem, transitive
-/
theorem toGrothendieck_eq_sInf (K : Coverage C) : toGrothendieck K =
    sInf {J | K <= J.toCoverage } := by
  apply le_antisymm
  · apply le_sInf
    intro J hJ X S hS
    induction hS with
    | of X S hS => apply hJ; assumption
    | top => apply J.top_mem
    | transitive X R S _ _ H1 H2 => exact J.transitive H1 _ H2
  · apply sInf_le
    intro X S hS
    apply Saturate.of _ _ hS

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: SemilatticeSup (Coverage C)
  body: { coverings := fun B => x B union y B
    pullback := by
      rintro X Y f S (hx | hy)
      · obtain ⟨T, hT⟩ := x.pullback f S hx
        exact ⟨T, Or.inl hT.1, hT.2⟩
      · obtain ⟨T, hT⟩ := y.pullback f S hy
        exact ⟨T, Or.inr hT.1, hT.2⟩ }
  toPartialOrder := inferInstance
  le_sup_left _ _ _ := Set.subset_union_left
  le_sup_right _ _ _ := Set.subset_union_right
  sup_le _ _ _ hx hy X := Set.union_subset_iff.mpr ⟨hx X, hy X⟩

@[simp]

中文:
实例 :
  签名: SemilatticeSup (余verage C)
  定义体: { coverings := fun B => x B union y B
    pullback := by
      rintro X Y f S (hx | hy)
      · obtain ⟨T, hT⟩ := x.pullback f S hx
        exact ⟨T, Or.inl hT.1, hT.2⟩
      · obtain ⟨T, hT⟩ := y.pullback f S hy
        exact ⟨T, Or.inr hT.1, hT.2⟩ }
  toPartialOrder := inferInstance
  le_sup_left _ _ _ := Set.subset_union_left
  le_sup_right _ _ _ := Set.subset_union_right
  sup_le _ _ _ hx hy X := Set.union_subset_iff.mpr ⟨hx X, hy X⟩

@[simp]

Depends on / 依赖: Or.inl, Or.inr, Set.subset_union_left, Set.subset_union_right, Set.union_subset_iff.mpr, coverings, le_sup_left, le_sup_right, pullback, subset_union_left, subset_union_right, sup_le, toPartialOrder, union_subset_iff, x.pullback, y.pullback
-/
instance : SemilatticeSup (Coverage C) where
  sup x y :=
  { coverings := fun B => x B union y B
    pullback := by
      rintro X Y f S (hx | hy)
      · obtain ⟨T, hT⟩ := x.pullback f S hx
        exact ⟨T, Or.inl hT.1, hT.2⟩
      · obtain ⟨T, hT⟩ := y.pullback f S hy
        exact ⟨T, Or.inr hT.1, hT.2⟩ }
  toPartialOrder := inferInstance
  le_sup_left _ _ _ := Set.subset_union_left
  le_sup_right _ _ _ := Set.subset_union_right
  sup_le _ _ _ hx hy X := Set.union_subset_iff.mpr ⟨hx X, hy X⟩

@[simp]
/--
lemma `sup_covering` / 引理 `sup_covering`

English:
lemma sup_covering
  given: (x y : Coverage C) (B : C)
  proof: rfl

中文:
引理 sup_covering
  条件: (x y : 余verage C) (B : C)
  证明: rfl
-/
lemma sup_covering (x y : Coverage C) (B : C) :
    (x ⊔ y) B = x B union y B :=
  rfl

/--
theorem `mem_toGrothendieck_sieves_of_superset` / 定理 `mem_toGrothendieck_sieves_of_superset`

English:
theorem mem_toGrothendieck_sieves_of_superset
  statement: (K : Coverage C) {X : C} {S : Sieve X}
  proof: K.saturate_of_superset ((Sieve.generate_le_iff _ _).mpr h) (Coverage.Saturate.of X _ hR)

中文:
定理 mem_toGrothendieck_sieves_of_superset
  结论: (K : 余verage C) {X : C} {S : 筛 X}
  证明: K.saturate_of_superset ((Sieve.generate_le_iff _ _).mpr h) (Coverage.Saturate.of X _ hR)

Depends on / 依赖: Coverage, Coverage.Saturate.of, K.saturate_of_superset, Saturate, Sieve.generate_le_iff, generate_le_iff, saturate_of_superset
-/
theorem mem_toGrothendieck_sieves_of_superset (K : Coverage C) {X : C} {S : Sieve X}
    {R : Presieve X} (h : R <= S) (hR : R in K X) : S in K.toGrothendieck X :=
  K.saturate_of_superset ((Sieve.generate_le_iff _ _).mpr h) (Coverage.Saturate.of X _ hR)

end Coverage

/--
Definition of `Pretopology.toCoverage` / `Pretopology.toCoverage` 的定义

English:
definition Pretopology.toCoverage
  signature: [HasPullbacks C] (J : Pretopology C)
  body: J
  pullback _ _ f R hR := ⟨R.pullbackArrows f, J.pullbacks _ _ hR, .pullbackArrows f R⟩

@[simp]

中文:
定义 Pretopology.toCoverage
  签名: [有Pullbacks C] (J : Pretopology C)
  定义体: J
  pullback _ _ f R hR := ⟨R.pullbackArrows f, J.pullbacks _ _ hR, .pullbackArrows f R⟩

@[simp]
-/
def Pretopology.toCoverage [HasPullbacks C] (J : Pretopology C) : Coverage C where
  coverings := J
  pullback _ _ f R hR := ⟨R.pullbackArrows f, J.pullbacks _ _ hR, .pullbackArrows f R⟩

@[simp]
/--
lemma `Pretopology.mem_toCoverage` / 引理 `Pretopology.mem_toCoverage`

English:
lemma Pretopology.mem_toCoverage
  given: [HasPullbacks C] (J : Pretopology C) {X : C} (S : Presieve X)
  proof: .rfl

中文:
引理 Pretopology.mem_toCoverage
  条件: [有Pullbacks C] (J : Pretopology C) {X : C} (S : Presieve X)
  证明: .rfl
-/
lemma Pretopology.mem_toCoverage [HasPullbacks C] (J : Pretopology C) {X : C} (S : Presieve X) :
    S in J.toCoverage X ↔ S in J X := .rfl

/--
lemma `Pretopology.toGrothendieck_toCoverage` / 引理 `Pretopology.toGrothendieck_toCoverage`

English:
lemma Pretopology.toGrothendieck_toCoverage
  given: [HasPullbacks C] (J : Pretopology C)
  proof: by
  ext T S
  rw [mem_toGrothendieck]; rw [Coverage.mem_toGrothendieck]
  refine ⟨fun h => ?_, fun ⟨R, hR, hle⟩ => ?_⟩
  · induction h with
    | of X S hS => use S, hS, Sieve.le_generate S
    | top X => use Presieve.singleton (𝟙 X), J.has_isos (𝟙 X), le_top
    | transitive X R S hR hRS hle hfS =>
        obtain ⟨R', hR', hle⟩ := hle
        choose S' hS' hS'le using hfS
        refine ⟨Presieve.bind R' (fun Y f hf => S' (hle _ _ hf)), ?_, fun Z u hu => ?_⟩
        · exact J.transitive R' (fun Y f hf => S' (hle Y _ hf)) hR' fun Y f H => hS' (hle Y _ H)
        · obtain ⟨W, g, w, hw, hg, rfl⟩ := hu
          exact hS'le _ _ _ hg
  · refine Coverage.saturate_of_superset _ ?_ (.of _ _ hR)
    rwa [Sieve.generate_le_iff]

中文:
引理 Pretopology.toGrothendieck_toCoverage
  条件: [有Pullbacks C] (J : Pretopology C)
  证明: by
  ext T S
  rw [mem_toGrothendieck]; rw [Coverage.mem_toGrothendieck]
  refine ⟨fun h => ?_, fun ⟨R, hR, hle⟩ => ?_⟩
  · induction h with
    | of X S hS => use S, hS, Sieve.le_generate S
    | top X => use Presieve.singleton (𝟙 X), J.has_isos (𝟙 X), le_top
    | transitive X R S hR hRS hle hfS =>
        obtain ⟨R', hR', hle⟩ := hle
        choose S' hS' hS'le using hfS
        refine ⟨Presieve.bind R' (fun Y f hf => S' (hle _ _ hf)), ?_, fun Z u hu => ?_⟩
        · exact J.transitive R' (fun Y f hf => S' (hle Y _ hf)) hR' fun Y f H => hS' (hle Y _ H)
        · obtain ⟨W, g, w, hw, hg, rfl⟩ := hu
          exact hS'le _ _ _ hg
  · refine Coverage.saturate_of_superset _ ?_ (.of _ _ hR)
    rwa [Sieve.generate_le_iff]

Depends on / 依赖: Coverage, Coverage.mem_toGrothendieck, J.has_isos, J.transitive, Presieve, Presieve.bind, Presieve.singleton, Sieve.le_generate, has_isos, le_generate, le_top, mem_toGrothendieck, singleton, transitive
-/
lemma Pretopology.toGrothendieck_toCoverage [HasPullbacks C] (J : Pretopology C) :
    J.toCoverage.toGrothendieck = J.toGrothendieck := by
  ext T S
  rw [mem_toGrothendieck]; rw [Coverage.mem_toGrothendieck]
  refine ⟨fun h => ?_, fun ⟨R, hR, hle⟩ => ?_⟩
  · induction h with
    | of X S hS => use S, hS, Sieve.le_generate S
    | top X => use Presieve.singleton (𝟙 X), J.has_isos (𝟙 X), le_top
    | transitive X R S hR hRS hle hfS =>
        obtain ⟨R', hR', hle⟩ := hle
        choose S' hS' hS'le using hfS
        refine ⟨Presieve.bind R' (fun Y f hf => S' (hle _ _ hf)), ?_, fun Z u hu => ?_⟩
        · exact J.transitive R' (fun Y f hf => S' (hle Y _ hf)) hR' fun Y f H => hS' (hle Y _ H)
        · obtain ⟨W, g, w, hw, hg, rfl⟩ := hu
          exact hS'le _ _ _ hg
  · refine Coverage.saturate_of_superset _ ?_ (.of _ _ hR)
    rwa [Sieve.generate_le_iff]

/-- A precoverage with pullbacks defines a coverage. -/
@[simps toPrecoverage]
/--
Definition of `Precoverage.toCoverage` / `Precoverage.toCoverage` 的定义

English:
definition Precoverage.toCoverage
  signature: (J : Precoverage C) [J.HasPullbacks] [J.IsStableUnderBaseChange]
  body: J
  pullback X Y f S hS := by
    have : S.HasPullbacks f := J.hasPullbacks_of_mem _ hS
    exact ⟨S.pullbackArrows f, J.pullbackArrows_mem _ hS,
      Presieve.FactorsThruAlong.pullbackArrows f S⟩

中文:
定义 Precoverage.toCoverage
  签名: (J : Precoverage C) [J.有Pullbacks] [J.是StableUnderBaseChange]
  定义体: J
  pullback X Y f S hS := by
    have : S.HasPullbacks f := J.hasPullbacks_of_mem _ hS
    exact ⟨S.pullbackArrows f, J.pullbackArrows_mem _ hS,
      Presieve.FactorsThruAlong.pullbackArrows f S⟩
-/
def Precoverage.toCoverage (J : Precoverage C) [J.HasPullbacks] [J.IsStableUnderBaseChange] :
    Coverage C where
  __ := J
  pullback X Y f S hS := by
    have : S.HasPullbacks f := J.hasPullbacks_of_mem _ hS
    exact ⟨S.pullbackArrows f, J.pullbackArrows_mem _ hS,
      Presieve.FactorsThruAlong.pullbackArrows f S⟩

/--
lemma `Precoverage.toCoverage_le_toCoverage` / 引理 `Precoverage.toCoverage_le_toCoverage`

English:
lemma Precoverage.toCoverage_le_toCoverage
  statement: {J : Precoverage C} [J.HasPullbacks]
  proof: rfl

中文:
引理 Precoverage.toCoverage_le_toCoverage
  结论: {J : Precoverage C} [J.有Pullbacks]
  证明: rfl
-/
lemma Precoverage.toCoverage_le_toCoverage {J : Precoverage C} [J.HasPullbacks]
    [J.IsStableUnderBaseChange] (K : GrothendieckTopology C) :
    (J.toCoverage <= K.toCoverage) =
      (forall ⦃X : C⦄, forall S in J.coverings X, Sieve.generate S in K X) := rfl

/--
lemma `Precoverage.toGrothendieck_toCoverage` / 引理 `Precoverage.toGrothendieck_toCoverage`

English:
lemma Precoverage.toGrothendieck_toCoverage
  statement: {J : Precoverage C} [J.HasPullbacks]
  proof: by
  grind [toGrothendieck_eq_sInf, Coverage.toGrothendieck_eq_sInf,
    Precoverage.toCoverage_le_toCoverage]

中文:
引理 Precoverage.toGrothendieck_toCoverage
  结论: {J : Precoverage C} [J.有Pullbacks]
  证明: by
  grind [toGrothendieck_eq_sInf, Coverage.toGrothendieck_eq_sInf,
    Precoverage.toCoverage_le_toCoverage]

Depends on / 依赖: Coverage, Coverage.toGrothendieck_eq_sInf, Precoverage, Precoverage.toCoverage_le_toCoverage, RankFinite, finite, hI.isBase_restrict.finite, isBase_restrict, toCoverage_le_toCoverage, toGrothendieck_eq_sInf
-/
lemma Precoverage.toGrothendieck_toCoverage {J : Precoverage C} [J.HasPullbacks]
    [J.IsStableUnderBaseChange] :
    J.toCoverage.toGrothendieck = J.toGrothendieck := by
  grind [toGrothendieck_eq_sInf, Coverage.toGrothendieck_eq_sInf,
    Precoverage.toCoverage_le_toCoverage]

/--
lemma `Coverage.toGrothendieck_toPrecoverage` / 引理 `Coverage.toGrothendieck_toPrecoverage`

English:
lemma Coverage.toGrothendieck_toPrecoverage
  given: (J : Coverage C)
  proof: by
  rw [Coverage.toGrothendieck]; rw [GrothendieckTopology.copy_eq]

中文:
引理 余verage.toGrothendieck_toPrecoverage
  条件: (J : 余verage C)
  证明: by
  rw [Coverage.toGrothendieck]; rw [GrothendieckTopology.copy_eq]

Depends on / 依赖: Coverage, Coverage.toGrothendieck, GrothendieckTopology, GrothendieckTopology.copy_eq, copy_eq, toGrothendieck
-/
lemma Coverage.toGrothendieck_toPrecoverage (J : Coverage C) :
    J.toPrecoverage.toGrothendieck = J.toGrothendieck := by
  rw [Coverage.toGrothendieck]; rw [GrothendieckTopology.copy_eq]

open Coverage

namespace Presieve

/--
theorem `isSheaf_coverage` / 定理 `isSheaf_coverage`

English:
theorem isSheaf_coverage
  given: (K : Coverage C) (P : Cᵒᵖ ⥤ Type*)
  proof: by
  rw [← toGrothendieck_toPrecoverage]; rw [Precoverage.isSheaf_toGrothendieck_iff]
  constructor
  · intro H X S hS
    simpa [← Presieve.isSheafFor_iff_generate] using H (f := 𝟙 X) S hS
  · intro H X Y f S hS
    obtain ⟨T, hT1, hT2⟩ := K.pullback f S hS
    apply Presieve.isSheafFor_of_factorsThru (S := T)
    · intro Z g hg
      obtain ⟨W, i, e, h1, h2⟩ := hT2 hg
      exact ⟨Z, 𝟙 _, g, ⟨W, i, e, h1, h2⟩, by simp⟩
    · apply H; assumption
    · intro Z g _
      obtain ⟨R, hR1, hR2⟩ := K.pullback g _ hT1
      exact ⟨R, (H _ hR1).isSeparatedFor, hR2⟩

中文:
定理 isSheaf_coverage
  条件: (K : 余verage C) (P : Cᵒᵖ ⥤ 类型)
  证明: by
  rw [← toGrothendieck_toPrecoverage]; rw [Precoverage.isSheaf_toGrothendieck_iff]
  constructor
  · intro H X S hS
    simpa [← Presieve.isSheafFor_iff_generate] using H (f := 𝟙 X) S hS
  · intro H X Y f S hS
    obtain ⟨T, hT1, hT2⟩ := K.pullback f S hS
    apply Presieve.isSheafFor_of_factorsThru (S := T)
    · intro Z g hg
      obtain ⟨W, i, e, h1, h2⟩ := hT2 hg
      exact ⟨Z, 𝟙 _, g, ⟨W, i, e, h1, h2⟩, by simp⟩
    · apply H; assumption
    · intro Z g _
      obtain ⟨R, hR1, hR2⟩ := K.pullback g _ hT1
      exact ⟨R, (H _ hR1).isSeparatedFor, hR2⟩

Depends on / 依赖: K.pullback, Precoverage, Precoverage.isSheaf_toGrothendieck_iff, Presieve, Presieve.isSheafFor_iff_generate, Presieve.isSheafFor_of_factorsThru, isSeparatedF, isSheafFor_iff_generate, isSheafFor_of_factorsThru, isSheaf_toGrothendieck_iff, pullback, toGrothendieck_toPrecoverage
-/
theorem isSheaf_coverage (K : Coverage C) (P : Cᵒᵖ ⥤ Type*) :
    Presieve.IsSheaf K.toGrothendieck P ↔
    (forall {X : C} (R : Presieve X), R in K X -> Presieve.IsSheafFor P R) := by
  rw [← toGrothendieck_toPrecoverage]; rw [Precoverage.isSheaf_toGrothendieck_iff]
  constructor
  · intro H X S hS
    simpa [← Presieve.isSheafFor_iff_generate] using H (f := 𝟙 X) S hS
  · intro H X Y f S hS
    obtain ⟨T, hT1, hT2⟩ := K.pullback f S hS
    apply Presieve.isSheafFor_of_factorsThru (S := T)
    · intro Z g hg
      obtain ⟨W, i, e, h1, h2⟩ := hT2 hg
      exact ⟨Z, 𝟙 _, g, ⟨W, i, e, h1, h2⟩, by simp⟩
    · apply H; assumption
    · intro Z g _
      obtain ⟨R, hR1, hR2⟩ := K.pullback g _ hT1
      exact ⟨R, (H _ hR1).isSeparatedFor, hR2⟩

/--
theorem `isSheaf_sup` / 定理 `isSheaf_sup`

English:
theorem isSheaf_sup
  given: (K L : Coverage C) (P : Cᵒᵖ ⥤ Type*)
  proof: by
  refine ⟨fun h => ⟨Presieve.isSheaf_of_le _ ((gi C).gc.monotone_l le_sup_left) h,
      Presieve.isSheaf_of_le _ ((gi C).gc.monotone_l le_sup_right) h⟩, fun h => ?_⟩
  rw [isSheaf_coverage]; rw [isSheaf_coverage] at h
  rw [isSheaf_coverage]
  intro X R hR
  rcases hR with hR | hR
  · exact h.1 R hR
  · exact h.2 R hR

中文:
定理 isSheaf_sup
  条件: (K L : 余verage C) (P : Cᵒᵖ ⥤ 类型)
  证明: by
  refine ⟨fun h => ⟨Presieve.isSheaf_of_le _ ((gi C).gc.monotone_l le_sup_left) h,
      Presieve.isSheaf_of_le _ ((gi C).gc.monotone_l le_sup_right) h⟩, fun h => ?_⟩
  rw [isSheaf_coverage]; rw [isSheaf_coverage] at h
  rw [isSheaf_coverage]
  intro X R hR
  rcases hR with hR | hR
  · exact h.1 R hR
  · exact h.2 R hR

Depends on / 依赖: Presieve, Presieve.isSheaf_of_le, gc.monotone_l, isSheaf_coverage, isSheaf_of_le, le_sup_left, le_sup_right, monotone_l
-/
theorem isSheaf_sup (K L : Coverage C) (P : Cᵒᵖ ⥤ Type*) :
    (Presieve.IsSheaf (K ⊔ L).toGrothendieck) P ↔
    (Presieve.IsSheaf K.toGrothendieck) P ∧ (Presieve.IsSheaf L.toGrothendieck) P := by
  refine ⟨fun h => ⟨Presieve.isSheaf_of_le _ ((gi C).gc.monotone_l le_sup_left) h,
      Presieve.isSheaf_of_le _ ((gi C).gc.monotone_l le_sup_right) h⟩, fun h => ?_⟩
  rw [isSheaf_coverage]; rw [isSheaf_coverage] at h
  rw [isSheaf_coverage]
  intro X R hR
  rcases hR with hR | hR
  · exact h.1 R hR
  · exact h.2 R hR

end Presieve

/--
lemma `Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange` / 引理 `Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange`

English:
lemma Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange
  proof: by
  rw [← J.toCoverage_toPrecoverage]; rw [Coverage.toGrothendieck_toPrecoverage]; rw [Presieve.isSheaf_coverage]

中文:
引理 Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange
  证明: by
  rw [← J.toCoverage_toPrecoverage]; rw [Coverage.toGrothendieck_toPrecoverage]; rw [Presieve.isSheaf_coverage]

Depends on / 依赖: Coverage, Coverage.toGrothendieck_toPrecoverage, J.toCoverage_toPrecoverage, Presieve, Presieve.isSheaf_coverage, isSheaf_coverage, toCoverage_toPrecoverage, toGrothendieck_toPrecoverage
-/
lemma Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange
    {J : Precoverage C} [J.HasPullbacks] [J.IsStableUnderBaseChange] (P : Cᵒᵖ ⥤ Type*) :
    Presieve.IsSheaf J.toGrothendieck P ↔ forall ⦃X : C⦄ (R : Presieve X),
      R in J X -> Presieve.IsSheafFor P R := by
  rw [← J.toCoverage_toPrecoverage]; rw [Coverage.toGrothendieck_toPrecoverage]; rw [Presieve.isSheaf_coverage]

/--
lemma `Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange_of_small` / 引理 `Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange_of_small`

English:
lemma Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange_of_small
  statement: {J : Precoverage C}
  proof: by
  rw [Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange]
  refine ⟨fun h X E => h _ E.mem₀, fun h X R hR => ?_⟩
  obtain ⟨E₀, rfl⟩ := R.exists_eq_preZeroHypercover
  rw [Presieve.isSheafFor_iff_generate]
  let E : ZeroHypercover J X := ⟨E₀, hR⟩
  apply Presieve.isSheafFor_subsieve
      (S := .generate <| (ZeroHypercover.restrictIndexOfSmall.{w} E).presieve₀)
  · exact Sieve.generate_mono (by simp [E])
  · intro Y f
    rw [← Sieve.pullbackArrows_comm]; rw [← Presieve.isSheafFor_iff_generate]; rw [← PreZeroHypercover.presieve₀_pullback₁]; rw [← ZeroHypercover.pullback₂_toPreZeroHypercover]
    apply h

中文:
引理 Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange_of_small
  结论: {J : Precoverage C}
  证明: by
  rw [Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange]
  refine ⟨fun h X E => h _ E.mem₀, fun h X R hR => ?_⟩
  obtain ⟨E₀, rfl⟩ := R.exists_eq_preZeroHypercover
  rw [Presieve.isSheafFor_iff_generate]
  let E : ZeroHypercover J X := ⟨E₀, hR⟩
  apply Presieve.isSheafFor_subsieve
      (S := .generate <| (ZeroHypercover.restrictIndexOfSmall.{w} E).presieve₀)
  · exact Sieve.generate_mono (by simp [E])
  · intro Y f
    rw [← Sieve.pullbackArrows_comm]; rw [← Presieve.isSheafFor_iff_generate]; rw [← PreZeroHypercover.presieve₀_pullback₁]; rw [← ZeroHypercover.pullback₂_toPreZeroHypercover]
    apply h

Depends on / 依赖: E.mem, Precoverage, Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange, Presieve, Presieve.isSheafFor_iff_generate, Presieve.isSheafFor_subsieve, R.exists_eq_preZeroHypercover, Sieve.generate_mono, Sieve.pullbackArrows_comm, ZeroHypercover, ZeroHypercover.restrictIndexOfSmall, exists_eq_preZeroHypercover, generate, generate_mono, isSheafFor_iff_generate, isSheafFor_subsieve, isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange, pullbackArrows_comm, restrictIndexOfSmall
-/
lemma Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange_of_small {J : Precoverage C}
    [J.IsStableUnderBaseChange] [J.HasPullbacks] [Small.{w} J] (P : Cᵒᵖ ⥤ Type*) :
    Presieve.IsSheaf J.toGrothendieck P ↔
      forall ⦃X : C⦄ (E : ZeroHypercover.{w} J X), Presieve.IsSheafFor P E.presieve₀ := by
  rw [Precoverage.isSheaf_toGrothendieck_iff_of_isStableUnderBaseChange]
  refine ⟨fun h X E => h _ E.mem₀, fun h X R hR => ?_⟩
  obtain ⟨E₀, rfl⟩ := R.exists_eq_preZeroHypercover
  rw [Presieve.isSheafFor_iff_generate]
  let E : ZeroHypercover J X := ⟨E₀, hR⟩
  apply Presieve.isSheafFor_subsieve
      (S := .generate <| (ZeroHypercover.restrictIndexOfSmall.{w} E).presieve₀)
  · exact Sieve.generate_mono (by simp [E])
  · intro Y f
    rw [← Sieve.pullbackArrows_comm]; rw [← Presieve.isSheafFor_iff_generate]; rw [← PreZeroHypercover.presieve₀_pullback₁]; rw [← ZeroHypercover.pullback₂_toPreZeroHypercover]
    apply h

namespace Presheaf

/--
theorem `isSheaf_iff_isLimit_coverage` / 定理 `isSheaf_iff_isLimit_coverage`

English:
theorem isSheaf_iff_isLimit_coverage
  given: (K : Coverage C) (P : Cᵒᵖ ⥤ D)
  proof: by
  simp only [Presheaf.IsSheaf, Presieve.isSheaf_coverage, isLimit_iff_isSheafFor,
    ← Presieve.isSheafFor_iff_generate]
  aesop

中文:
定理 isSheaf_iff_isLimit_coverage
  条件: (K : 余verage C) (P : Cᵒᵖ ⥤ D)
  证明: by
  simp only [Presheaf.IsSheaf, Presieve.isSheaf_coverage, isLimit_iff_isSheafFor,
    ← Presieve.isSheafFor_iff_generate]
  aesop

Depends on / 依赖: IsSheaf, Presheaf, Presheaf.IsSheaf, Presieve, Presieve.isSheafFor_iff_generate, Presieve.isSheaf_coverage, isLimit_iff_isSheafFor, isSheafFor_iff_generate, isSheaf_coverage
-/
theorem isSheaf_iff_isLimit_coverage (K : Coverage C) (P : Cᵒᵖ ⥤ D) :
    Presheaf.IsSheaf K.toGrothendieck P ↔ forall ⦃X : C⦄ (R : Presieve X),
      R in K X ->
        Nonempty (IsLimit (P.mapCone (Sieve.generate R).arrows.cocone.op)) := by
  simp only [Presheaf.IsSheaf, Presieve.isSheaf_coverage, isLimit_iff_isSheafFor,
    ← Presieve.isSheafFor_iff_generate]
  aesop

/--
theorem `isSheaf_sup` / 定理 `isSheaf_sup`

English:
theorem isSheaf_sup
  given: (K L : Coverage C) (P : Cᵒᵖ ⥤ D)
  proof: ⟨fun h => ⟨fun E => ((Presieve.isSheaf_sup K L _).mp (h E)).1, fun E =>
    ((Presieve.isSheaf_sup K L _).mp (h E)).2⟩,
      fun ⟨h₁, h₂⟩ E => (Presieve.isSheaf_sup K L _).mpr ⟨h₁ E, h₂ E⟩⟩

中文:
定理 isSheaf_sup
  条件: (K L : 余verage C) (P : Cᵒᵖ ⥤ D)
  证明: ⟨fun h => ⟨fun E => ((Presieve.isSheaf_sup K L _).mp (h E)).1, fun E =>
    ((Presieve.isSheaf_sup K L _).mp (h E)).2⟩,
      fun ⟨h₁, h₂⟩ E => (Presieve.isSheaf_sup K L _).mpr ⟨h₁ E, h₂ E⟩⟩

Depends on / 依赖: Presieve, Presieve.isSheaf_sup, isSheaf_sup
-/
theorem isSheaf_sup (K L : Coverage C) (P : Cᵒᵖ ⥤ D) :
    (IsSheaf (K ⊔ L).toGrothendieck) P ↔
    (IsSheaf K.toGrothendieck) P ∧ (IsSheaf L.toGrothendieck) P :=
  ⟨fun h => ⟨fun E => ((Presieve.isSheaf_sup K L _).mp (h E)).1, fun E =>
    ((Presieve.isSheaf_sup K L _).mp (h E)).2⟩,
      fun ⟨h₁, h₂⟩ E => (Presieve.isSheaf_sup K L _).mpr ⟨h₁ E, h₂ E⟩⟩

end Presheaf

end CategoryTheory
