/-
Copyright (c) 2020 Adam Topaz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adam Topaz
-/
module

public import Mathlib.Algebra.FreeAlgebra
public import Mathlib.Algebra.TrivSqZeroExt.Basic
public import Mathlib.Algebra.Algebra.Operations
public import Mathlib.LinearAlgebra.Multilinear.Basic
public import Mathlib.RingTheory.Congruence.Hom

/-!
# Tensor Algebras

Given a commutative semiring `R`, and an `R`-module `M`, we construct the tensor algebra of `M`.
This is the free `R`-algebra generated (`R`-linearly) by the module `M`.

## Notation

1. `TensorAlgebra R M` is the tensor algebra itself. It is endowed with an R-algebra structure.
2. `TensorAlgebra.ι R` is the canonical R-linear map `M → TensorAlgebra R M`.
3. Given a linear map `f : M → A` to an R-algebra `A`, `lift R f` is the lift of `f` to an
  `R`-algebra morphism `TensorAlgebra R M → A`.

## Theorems

1. `ι_comp_lift` states that the composition `(lift R f) ∘ (ι R)` is identical to `f`.
2. `lift_unique` states that whenever an R-algebra morphism `g : TensorAlgebra R M → A` is
  given whose composition with `ι R` is `f`, then one has `g = lift R f`.
3. `hom_ext` is a variant of `lift_unique` in the form of an extensionality theorem.
4. `lift_comp_ι` is a combination of `ι_comp_lift` and `lift_unique`. It states that the lift
  of the composition of an algebra morphism with `ι` is the algebra morphism itself.

## Implementation details

As noted above, the tensor algebra of `M` is constructed as the free `R`-algebra generated by `M`,
modulo the additional relations making the inclusion of `M` into an `R`-linear map.
-/

@[expose] public section


variable (R : Type*) [CommSemiring R]
variable (M : Type*) [AddCommMonoid M] [Module R M]

namespace TensorAlgebra

/--
Inductive type `Rel` / 归纳类型 `Rel`

English:
inductive Rel
  parameters: : FreeAlgebra R M -> FreeAlgebra R M -> Prop
  constructors (2):
    - add: {a b : M} : Rel (FreeAlgebra.ι R (a + b)) (FreeAlgebra.ι R a + FreeAlgebra.ι R b)
    - smul: {r : R} {a : M} : Rel (FreeAlgebra.ι R (r • a)) (algebraMap R (FreeAlgebra R M) r * FreeAlgebra.ι R a)

中文:
归纳类型 Rel
  参数: : FreeAlgebra R M -> FreeAlgebra R M -> 命题
  构造子 (2 个):
    - add: {a b : M} : Rel (FreeAlgebra.ι R (a + b)) (FreeAlgebra.ι R a + FreeAlgebra.ι R b)
    - smul: {r : R} {a : M} : Rel (FreeAlgebra.ι R (r • a)) (algebraMap R (FreeAlgebra R M) r * FreeAlgebra.ι R a)
-/
inductive Rel : FreeAlgebra R M -> FreeAlgebra R M -> Prop
  -- force `ι` to be linear
  | add {a b : M} : Rel (FreeAlgebra.ι R (a + b)) (FreeAlgebra.ι R a + FreeAlgebra.ι R b)
  | smul {r : R} {a : M} :
    Rel (FreeAlgebra.ι R (r • a)) (algebraMap R (FreeAlgebra R M) r * FreeAlgebra.ι R a)

/--
Definition of `ringCon` / `ringCon` 的定义

English:
definition ringCon
  signature: : RingCon (FreeAlgebra R M)
  body: ringConGen (Rel R M)

中文:
定义 ringCon
  签名: : RingCon (FreeAlgebra R M)
  定义体: ringConGen (Rel R M)
-/
@[no_expose] def ringCon : RingCon (FreeAlgebra R M) := ringConGen (Rel R M)

end TensorAlgebra

/-- The tensor algebra of the module `M` over the commutative semiring `R`.
-/
.Quotient def TensorAlgebra := TensorAlgebra.ringCon R M
deriving Inhabited

namespace TensorAlgebra

-- This instance exists to avoid an nsmul diamond.
instance {R A M} [CommSemiring R] [AddCommMonoid M] [CommSemiring A]
    [Algebra R A] [Module A M] :
    SMul R (TensorAlgebra A M) :=
inferInstanceAs SMul R (RingCon.Quotient _)

deriving instance Semiring for TensorAlgebra

-- `IsScalarTower` is not needed, but the instance isn't really canonical without it.
@[nolint unusedArguments]
/--
Instance `instAlgebra` / 实例 `instAlgebra`

English:
instance instAlgebra
  signature: {R A M} [CommSemiring R] [AddCommMonoid M] [CommSemiring A]
  body: inferInstanceAs Algebra R (RingCon.Quotient _)

中文:
实例 instAlgebra
  签名: {R A M} [CommSemiring R] [AddCommMonoid M] [CommSemiring A]
  定义体: inferInstanceAs Algebra R (RingCon.Quotient _)

Depends on / 依赖: Algebra, Quotient, RingCon, RingCon.Quotient
-/
instance instAlgebra {R A M} [CommSemiring R] [AddCommMonoid M] [CommSemiring A]
    [Algebra R A] [Module R M] [Module A M]
    [IsScalarTower R A M] :
    Algebra R (TensorAlgebra A M) :=
inferInstanceAs Algebra R (RingCon.Quotient _)

-- verify there is no diamond
-- but doesn't work at `reducible_and_instances` https://github.com/leanprover-community/mathlib4/issues/10906
example : (Semiring.toNatAlgebra : Algebra Nat (TensorAlgebra R M)) = instAlgebra := rfl

instance {R S A M} [CommSemiring R] [CommSemiring S] [AddCommMonoid M] [CommSemiring A]
    [Algebra R A] [Algebra S A] [Module A M] :
    SMulCommClass R S (TensorAlgebra A M) :=
inferInstanceAs SMulCommClass R S (RingCon.Quotient _)

instance {R S A M} [CommSemiring R] [CommSemiring S] [AddCommMonoid M] [CommSemiring A]
    [SMul R S] [Algebra R A] [Algebra S A] [Module A M] [IsScalarTower R S A] :
    IsScalarTower R S (TensorAlgebra A M) :=
inferInstanceAs IsScalarTower R S (RingCon.Quotient _)

instance {S : Type*} [CommRing S] [Module S M] : Ring (TensorAlgebra S M) :=
inferInstanceAs Ring (RingCon.Quotient _)

-- verify there is no diamond
-- but doesn't work at `reducible_and_instances` https://github.com/leanprover-community/mathlib4/issues/10906
variable (S M : Type) [CommRing S] [AddCommGroup M] [Module S M] in
example : (Ring.toIntAlgebra _ : Algebra Int (TensorAlgebra S M)) = instAlgebra := rfl

variable {M}

set_option backward.isDefEq.respectTransparency false in
/-- The canonical linear map `M →ₗ[R] TensorAlgebra R M`.
-/
irreducible_def ι : M ->ₗ[R] TensorAlgebra R M :=
  { toFun := fun m => RingCon.toQuotient (FreeAlgebra.ι R m)
    map_add' := fun x y => by
      rw [← RingCon.coe_add]
exact Quotient.sound RingConGen.Rel.of _ _ Rel.add
    map_smul' := fun r x => by
      rw [← RingCon.coe_smul]
exact Quotient.sound RingConGen.Rel.of _ _ Rel.smul}

/--
theorem `ringQuot_mkAlgHom_freeAlgebra_ι_eq_ι` / 定理 `ringQuot_mkAlgHom_freeAlgebra_ι_eq_ι`

English:
theorem ringQuot_mkAlgHom_freeAlgebra_ι_eq_ι
  given: (m : M)
  proof: by
  rw [ι]
  rfl

中文:
定理 ringQuot_mkAlgHom_freeAlgebra_ι_eq_ι
  条件: (m : M)
  证明: by
  rw [ι]
  rfl
-/
theorem ringQuot_mkAlgHom_freeAlgebra_ι_eq_ι (m : M) :
    RingCon.mkₐ R (ringCon R M) (FreeAlgebra.ι R m) = ι R m := by
  rw [ι]
  rfl

set_option backward.isDefEq.respectTransparency.types false in
/-- Given a linear map `f : M → A` where `A` is an `R`-algebra, `lift R f` is the unique lift
of `f` to a morphism of `R`-algebras `TensorAlgebra R M → A`.
-/
@[simps symm_apply]
/--
Definition of `lift` / `lift` 的定义

English:
definition lift
  signature: {A : Type*} [Semiring A] [Algebra R A]
  body: { toFun f :=
RingCon.liftₐ (ringCon R M) (FreeAlgebra.lift R (f)) by
        grw [ringCon, RingCon.ringConGen_le]
        intro x y h
        induction h <;>
          simp [Algebra.smul_def, FreeAlgebra.lift_ι_apply,
            map_mul, AlgHom.commutes, map_add, RingCon.ker]
    invFun := fun F =>

中文:
定义 lift
  签名: {A : 类型} [Semiring A] [Algebra R A]
  定义体: { toFun f :=
RingCon.liftₐ (ringCon R M) (FreeAlgebra.lift R (f)) by
        grw [ringCon, RingCon.ringConGen_le]
        intro x y h
        induction h <;>
          simp [Algebra.smul_def, FreeAlgebra.lift_ι_apply,
            map_mul, AlgHom.commutes, map_add, RingCon.ker]
    invFun := fun F =>

Depends on / 依赖: AlgHom, AlgHom.commutes, Algebra, Algebra.smul_def, F.toLinearMap.comp, FreeAlgebra, FreeAlgebra.hom_ext, FreeAlgebra.lift, FreeAlgebra.lift_, Quotient, RingCon, RingCon.Quotient.hom_ext, RingCon.ker, RingCon.lift, RingCon.ringConGen_le, commutes, hom_ext, invFun, left_inv, map_add
-/
def lift {A : Type*} [Semiring A] [Algebra R A] : (M ->ₗ[R] A) ≃ (TensorAlgebra R M ->ₐ[R] A) :=
  { toFun f :=
RingCon.liftₐ (ringCon R M) (FreeAlgebra.lift R (f)) by
        grw [ringCon, RingCon.ringConGen_le]
        intro x y h
        induction h <;>
          simp [Algebra.smul_def, FreeAlgebra.lift_ι_apply,
            map_mul, AlgHom.commutes, map_add, RingCon.ker]
    invFun := fun F => F.toLinearMap.comp (ι R)
    left_inv := fun f => by
      rw [ι]
      ext1 x
      dsimp
      exact (RingCon.liftₐ_mk _ _ _ _).trans (FreeAlgebra.lift_ι_apply f x)
    right_inv := fun F =>
RingCon.Quotient.hom_extₐ
FreeAlgebra.hom_ext
          funext fun x => by
            rw [ι]
            simp
            rfl }

variable {R}

@[simp]
/--
theorem `ι_comp_lift` / 定理 `ι_comp_lift`

English:
theorem ι_comp_lift
  given: {A : Type*} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A)
  proof: by
  convert! (lift R).symm_apply_apply f

@[simp]

中文:
定理 ι_comp_lift
  条件: {A : 类型} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A)
  证明: by
  convert! (lift R).symm_apply_apply f

@[simp]

Depends on / 依赖: convert, symm_apply_apply
-/
theorem ι_comp_lift {A : Type*} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A) :
    (lift R f).toLinearMap.comp (ι R) = f := by
  convert! (lift R).symm_apply_apply f

@[simp]
/--
theorem `lift_ι_apply` / 定理 `lift_ι_apply`

English:
theorem lift_ι_apply
  given: {A : Type*} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A) (x)
  proof: by
  conv_rhs => rw [← ι_comp_lift f]
  rfl

中文:
定理 lift_ι_apply
  条件: {A : 类型} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A) (x)
  证明: by
  conv_rhs => rw [← ι_comp_lift f]
  rfl

Depends on / 依赖: conv_rhs
-/
theorem lift_ι_apply {A : Type*} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A) (x) :
    lift R f (ι R x) = f x := by
  conv_rhs => rw [← ι_comp_lift f]
  rfl

set_option backward.isDefEq.respectTransparency false in
@[simp]
/--
theorem `lift_unique` / 定理 `lift_unique`

English:
theorem lift_unique
  statement: {A : Type*} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A)
  proof: by
  rw [← (lift R).symm_apply_eq]
  simp only [lift, Equiv.coe_fn_symm_mk]

中文:
定理 lift_unique
  结论: {A : 类型} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A)
  证明: by
  rw [← (lift R).symm_apply_eq]
  simp only [lift, Equiv.coe_fn_symm_mk]

Depends on / 依赖: Equiv.coe_fn_symm_mk, coe_fn_symm_mk, symm_apply_eq
-/
theorem lift_unique {A : Type*} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A)
    (g : TensorAlgebra R M ->ₐ[R] A) : g.toLinearMap.comp (ι R) = f ↔ g = lift R f := by
  rw [← (lift R).symm_apply_eq]
  simp only [lift, Equiv.coe_fn_symm_mk]

-- Marking `TensorAlgebra` irreducible makes `Ring` instances inaccessible on quotients.
-- https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/algebra.2Esemiring_to_ring.20breaks.20semimodule.20typeclass.20lookup/near/212580241
-- For now, we avoid this by not marking it irreducible.
@[simp]
/--
theorem `lift_comp_ι` / 定理 `lift_comp_ι`

English:
theorem lift_comp_ι
  given: {A : Type*} [Semiring A] [Algebra R A] (g : TensorAlgebra R M ->ₐ[R] A)
  proof: by
  rw [← lift_symm_apply]
  exact (lift R).apply_symm_apply g

中文:
定理 lift_comp_ι
  条件: {A : 类型} [Semiring A] [Algebra R A] (g : TensorAlgebra R M ->ₐ[R] A)
  证明: by
  rw [← lift_symm_apply]
  exact (lift R).apply_symm_apply g

Depends on / 依赖: apply_symm_apply, lift_symm_apply
-/
theorem lift_comp_ι {A : Type*} [Semiring A] [Algebra R A] (g : TensorAlgebra R M ->ₐ[R] A) :
    lift R (g.toLinearMap.comp (ι R)) = g := by
  rw [← lift_symm_apply]
  exact (lift R).apply_symm_apply g

/-- See note [partially-applied ext lemmas]. -/
@[ext]
/--
theorem `hom_ext` / 定理 `hom_ext`

English:
theorem hom_ext
  statement: {A : Type*} [Semiring A] [Algebra R A] {f g : TensorAlgebra R M ->ₐ[R] A}
  proof: by
  rw [← lift_symm_apply]; rw [← lift_symm_apply] at w
  exact (lift R).symm.injective w

中文:
定理 hom_ext
  结论: {A : 类型} [Semiring A] [Algebra R A] {f g : TensorAlgebra R M ->ₐ[R] A}
  证明: by
  rw [← lift_symm_apply]; rw [← lift_symm_apply] at w
  exact (lift R).symm.injective w

Depends on / 依赖: injective, lift_symm_apply, symm.injective
-/
theorem hom_ext {A : Type*} [Semiring A] [Algebra R A] {f g : TensorAlgebra R M ->ₐ[R] A}
    (w : f.toLinearMap.comp (ι R) = g.toLinearMap.comp (ι R)) : f = g := by
  rw [← lift_symm_apply]; rw [← lift_symm_apply] at w
  exact (lift R).symm.injective w

-- This proof closely follows `FreeAlgebra.induction`
/-- If `C` holds for the `algebraMap` of `r : R` into `TensorAlgebra R M`, the `ι` of `x : M`,
and is preserved under addition and multiplication, then it holds for all of `TensorAlgebra R M`.
-/
@[elab_as_elim]
/--
theorem `induction` / 定理 `induction`

English:
theorem induction
  statement: {C : TensorAlgebra R M -> Prop}
  proof: by
  -- the arguments are enough to construct a subalgebra, and a mapping into it from M
  let s : Subalgebra R (TensorAlgebra R M) :=
    { carrier := {a | C a}
      mul_mem' := @mul
      add_mem' := @add
      algebraMap_mem' := algebraMap }
  let of : M ->ₗ[R] s := (TensorAlgebra.ι R).codRestri

中文:
定理 induction
  结论: {C : TensorAlgebra R M -> 命题}
  证明: by
  -- the arguments are enough to construct a subalgebra, and a mapping into it from M
  let s : Subalgebra R (TensorAlgebra R M) :=
    { carrier := {a | C a}
      mul_mem' := @mul
      add_mem' := @add
      algebraMap_mem' := algebraMap }
  let of : M ->ₗ[R] s := (TensorAlgebra.ι R).codRestri
-/
theorem induction {C : TensorAlgebra R M -> Prop}
    (algebraMap : forall r, C (algebraMap R (TensorAlgebra R M) r)) (ι : forall x, C (ι R x))
    (mul : forall a b, C a -> C b -> C (a * b)) (add : forall a b, C a -> C b -> C (a + b))
    (a : TensorAlgebra R M) : C a := by
  -- the arguments are enough to construct a subalgebra, and a mapping into it from M
  let s : Subalgebra R (TensorAlgebra R M) :=
    { carrier := {a | C a}
      mul_mem' := @mul
      add_mem' := @add
      algebraMap_mem' := algebraMap }
  let of : M ->ₗ[R] s := (TensorAlgebra.ι R).codRestrict (Subalgebra.toSubmodule s) ι
  have of_apply {x : M} : of x = (TensorAlgebra.ι R) x := by rfl
  -- the mapping through the subalgebra is the identity
  have of_id : AlgHom.id R (TensorAlgebra R M) = s.val.comp (lift R of) := by
    ext
    simp [of_apply]
  -- finding a proof is finding an element of the subalgebra
  rw [← AlgHom.id_apply (R := R) a]; rw [of_id]
  exact Subtype.prop (lift R of a)

@[simp]
/--
theorem `adjoin_range_ι` / 定理 `adjoin_range_ι`

English:
theorem adjoin_range_ι
  statement: Algebra.adjoin R (Set.range (ι R (M := M))) = ⊤
  proof: by
  refine top_unique fun x hx => ?_; clear hx
  induction x using induction with
  | algebraMap => exact algebraMap_mem _ _
  | add x y hx hy => exact add_mem hx hy
  | mul x y hx hy => exact mul_mem hx hy
  | ι x => exact Algebra.subset_adjoin (Set.mem_range_self _)

@[simp]

中文:
定理 adjoin_range_ι
  结论: Algebra.adjoin R (Set.range (ι R (M := M))) = ⊤
  证明: by
  refine top_unique fun x hx => ?_; clear hx
  induction x using induction with
  | algebraMap => exact algebraMap_mem _ _
  | add x y hx hy => exact add_mem hx hy
  | mul x y hx hy => exact mul_mem hx hy
  | ι x => exact Algebra.subset_adjoin (Set.mem_range_self _)

@[simp]

Depends on / 依赖: Algebra, Algebra.subset_adjoin, Set.mem_range_self, add_mem, algebraMap, algebraMap_mem, mem_range_self, mul_mem, subset_adjoin, top_unique
-/
theorem adjoin_range_ι : Algebra.adjoin R (Set.range (ι R (M := M))) = ⊤ := by
  refine top_unique fun x hx => ?_; clear hx
  induction x using induction with
  | algebraMap => exact algebraMap_mem _ _
  | add x y hx hy => exact add_mem hx hy
  | mul x y hx hy => exact mul_mem hx hy
  | ι x => exact Algebra.subset_adjoin (Set.mem_range_self _)

@[simp]
/--
theorem `range_lift` / 定理 `range_lift`

English:
theorem range_lift
  given: {A : Type*} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A)
  proof: by
  simp_rw [← Algebra.map_top, ← adjoin_range_ι, AlgHom.map_adjoin, ← Set.range_comp,
    Function.comp_def, lift_ι_apply]

中文:
定理 range_lift
  条件: {A : 类型} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A)
  证明: by
  simp_rw [← Algebra.map_top, ← adjoin_range_ι, AlgHom.map_adjoin, ← Set.range_comp,
    Function.comp_def, lift_ι_apply]

Depends on / 依赖: AlgHom, AlgHom.map_adjoin, Algebra, Algebra.map_top, Function, Function.comp_def, Set.range_comp, comp_def, map_adjoin, map_top, range_comp, simp_rw
-/
theorem range_lift {A : Type*} [Semiring A] [Algebra R A] (f : M ->ₗ[R] A) :
    (lift R f).range = Algebra.adjoin R (Set.range f) := by
  simp_rw [← Algebra.map_top, ← adjoin_range_ι, AlgHom.map_adjoin, ← Set.range_comp,
    Function.comp_def, lift_ι_apply]

/--
Definition of `algebraMapInv` / `algebraMapInv` 的定义

English:
definition algebraMapInv
  signature: : TensorAlgebra R M ->ₐ[R] R
  body: lift R (0 : M ->ₗ[R] R)

中文:
定义 algebraMapInv
  签名: : TensorAlgebra R M ->ₐ[R] R
  定义体: lift R (0 : M ->ₗ[R] R)
-/
def algebraMapInv : TensorAlgebra R M ->ₐ[R] R :=
  lift R (0 : M ->ₗ[R] R)

variable (M)

/--
theorem `algebraMap_leftInverse` / 定理 `algebraMap_leftInverse`

English:
theorem algebraMap_leftInverse
  proof: fun x => by
  simp [algebraMapInv]

@[simp]

中文:
定理 algebraMap_leftInverse
  证明: fun x => by
  simp [algebraMapInv]

@[simp]

Depends on / 依赖: algebraMapInv
-/
theorem algebraMap_leftInverse :
    Function.LeftInverse algebraMapInv (algebraMap R <| TensorAlgebra R M) := fun x => by
  simp [algebraMapInv]

@[simp]
/--
theorem `algebraMap_inj` / 定理 `algebraMap_inj`

English:
theorem algebraMap_inj
  given: (x y : R)
  proof: (algebraMap_leftInverse M).injective.eq_iff

@[simp]

中文:
定理 algebraMap_inj
  条件: (x y : R)
  证明: (algebraMap_leftInverse M).injective.eq_iff

@[simp]

Depends on / 依赖: algebraMap_leftInverse, eq_iff, injective, injective.eq_iff
-/
theorem algebraMap_inj (x y : R) :
    algebraMap R (TensorAlgebra R M) x = algebraMap R (TensorAlgebra R M) y ↔ x = y :=
  (algebraMap_leftInverse M).injective.eq_iff

@[simp]
/--
theorem `algebraMap_eq_zero_iff` / 定理 `algebraMap_eq_zero_iff`

English:
theorem algebraMap_eq_zero_iff
  given: (x : R)
  statement: algebraMap R (TensorAlgebra R M) x = 0 ↔ x = 0
  proof: map_eq_zero_iff (algebraMap _ _) (algebraMap_leftInverse _).injective

@[simp]

中文:
定理 algebraMap_eq_zero_iff
  条件: (x : R)
  结论: algebraMap R (TensorAlgebra R M) x = 0 ↔ x = 0
  证明: map_eq_zero_iff (algebraMap _ _) (algebraMap_leftInverse _).injective

@[simp]

Depends on / 依赖: algebraMap, algebraMap_leftInverse, injective, map_eq_zero_iff
-/
theorem algebraMap_eq_zero_iff (x : R) : algebraMap R (TensorAlgebra R M) x = 0 ↔ x = 0 :=
  map_eq_zero_iff (algebraMap _ _) (algebraMap_leftInverse _).injective

@[simp]
/--
theorem `algebraMap_eq_one_iff` / 定理 `algebraMap_eq_one_iff`

English:
theorem algebraMap_eq_one_iff
  given: (x : R)
  statement: algebraMap R (TensorAlgebra R M) x = 1 ↔ x = 1
  proof: map_eq_one_iff (algebraMap _ _) (algebraMap_leftInverse _).injective

中文:
定理 algebraMap_eq_one_iff
  条件: (x : R)
  结论: algebraMap R (TensorAlgebra R M) x = 1 ↔ x = 1
  证明: map_eq_one_iff (algebraMap _ _) (algebraMap_leftInverse _).injective

Depends on / 依赖: algebraMap, algebraMap_leftInverse, injective, map_eq_one_iff
-/
theorem algebraMap_eq_one_iff (x : R) : algebraMap R (TensorAlgebra R M) x = 1 ↔ x = 1 :=
  map_eq_one_iff (algebraMap _ _) (algebraMap_leftInverse _).injective

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [Nontrivial
  signature: R] : Nontrivial (TensorAlgebra R M)
  body: (algebraMap_leftInverse M).injective.nontrivial

中文:
实例 [Nontrivial
  签名: R] : Nontrivial (TensorAlgebra R M)
  定义体: (algebraMap_leftInverse M).injective.nontrivial

Depends on / 依赖: algebraMap_leftInverse, injective, injective.nontrivial, nontrivial
-/
instance [Nontrivial R] : Nontrivial (TensorAlgebra R M) :=
  (algebraMap_leftInverse M).injective.nontrivial

variable {M}

/--
Definition of `toTrivSqZeroExt` / `toTrivSqZeroExt` 的定义

English:
definition toTrivSqZeroExt
  signature: [Module Rᵐᵒᵖ M] [IsCentralScalar R M]
  body: lift R (TrivSqZeroExt.inrHom R M)

@[simp]

中文:
定义 toTrivSqZeroExt
  签名: [Module Rᵐᵒᵖ M] [IsCentralScalar R M]
  定义体: lift R (TrivSqZeroExt.inrHom R M)

@[simp]

Depends on / 依赖: TrivSqZeroExt, TrivSqZeroExt.inrHom, inrHom
-/
def toTrivSqZeroExt [Module Rᵐᵒᵖ M] [IsCentralScalar R M] :
    TensorAlgebra R M ->ₐ[R] TrivSqZeroExt R M :=
  lift R (TrivSqZeroExt.inrHom R M)

@[simp]
/--
theorem `toTrivSqZeroExt_ι` / 定理 `toTrivSqZeroExt_ι`

English:
theorem toTrivSqZeroExt_ι
  given: (x : M) [Module Rᵐᵒᵖ M] [IsCentralScalar R M]
  proof: lift_ι_apply _ _

中文:
定理 toTrivSqZeroExt_ι
  条件: (x : M) [Module Rᵐᵒᵖ M] [IsCentralScalar R M]
  证明: lift_ι_apply _ _
-/
theorem toTrivSqZeroExt_ι (x : M) [Module Rᵐᵒᵖ M] [IsCentralScalar R M] :
    toTrivSqZeroExt (ι R x) = TrivSqZeroExt.inr x :=
  lift_ι_apply _ _

/--
Definition of `ιInv` / `ιInv` 的定义

English:
definition ιInv
  signature: : TensorAlgebra R M ->ₗ[R] M
  body: by
  letI : Module Rᵐᵒᵖ M := Module.compHom _ ((RingHom.id R).fromOpposite mul_comm)
  haveI : IsCentralScalar R M := ⟨fun r m => rfl⟩
  exact (TrivSqZeroExt.sndHom R M).comp toTrivSqZeroExt.toLinearMap

中文:
定义 ιInv
  签名: : TensorAlgebra R M ->ₗ[R] M
  定义体: by
  letI : Module Rᵐᵒᵖ M := Module.compHom _ ((RingHom.id R).fromOpposite mul_comm)
  haveI : IsCentralScalar R M := ⟨fun r m => rfl⟩
  exact (TrivSqZeroExt.sndHom R M).comp toTrivSqZeroExt.toLinearMap

Depends on / 依赖: IsCentralScalar, Module, Module.compHom, RingHom, RingHom.id, TrivSqZeroExt, TrivSqZeroExt.sndHom, compHom, fromOpposite, mul_comm, sndHom, toLinearMap, toTrivSqZeroExt, toTrivSqZeroExt.toLinearMap
-/
def ιInv : TensorAlgebra R M ->ₗ[R] M := by
  letI : Module Rᵐᵒᵖ M := Module.compHom _ ((RingHom.id R).fromOpposite mul_comm)
  haveI : IsCentralScalar R M := ⟨fun r m => rfl⟩
  exact (TrivSqZeroExt.sndHom R M).comp toTrivSqZeroExt.toLinearMap

/--
theorem `ι_leftInverse` / 定理 `ι_leftInverse`

English:
theorem ι_leftInverse
  statement: Function.LeftInverse ιInv (ι R : M -> TensorAlgebra R M)
  proof: fun x => by
  simp [ιInv]

中文:
定理 ι_leftInverse
  结论: Function.LeftInverse ιInv (ι R : M -> TensorAlgebra R M)
  证明: fun x => by
  simp [ιInv]
-/
theorem ι_leftInverse : Function.LeftInverse ιInv (ι R : M -> TensorAlgebra R M) := fun x => by
  simp [ιInv]

variable (R)

@[simp]
/--
theorem `ι_inj` / 定理 `ι_inj`

English:
theorem ι_inj
  given: (x y : M)
  statement: ι R x = ι R y ↔ x = y
  proof: ι_leftInverse.injective.eq_iff

@[simp]

中文:
定理 ι_inj
  条件: (x y : M)
  结论: ι R x = ι R y ↔ x = y
  证明: ι_leftInverse.injective.eq_iff

@[simp]

Depends on / 依赖: _leftInverse.injective.eq_iff, eq_iff, injective
-/
theorem ι_inj (x y : M) : ι R x = ι R y ↔ x = y :=
  ι_leftInverse.injective.eq_iff

@[simp]
/--
theorem `ι_eq_zero_iff` / 定理 `ι_eq_zero_iff`

English:
theorem ι_eq_zero_iff
  given: (x : M)
  statement: ι R x = 0 ↔ x = 0
  proof: by rw [← ι_inj R x 0, map_zero]

中文:
定理 ι_eq_zero_iff
  条件: (x : M)
  结论: ι R x = 0 ↔ x = 0
  证明: by rw [← ι_inj R x 0, map_zero]

Depends on / 依赖: map_zero
-/
theorem ι_eq_zero_iff (x : M) : ι R x = 0 ↔ x = 0 := by rw [← ι_inj R x 0, map_zero]

variable {R}

@[simp]
/--
theorem `ι_eq_algebraMap_iff` / 定理 `ι_eq_algebraMap_iff`

English:
theorem ι_eq_algebraMap_iff
  given: (x : M) (r : R)
  statement: ι R x = algebraMap R _ r ↔ x = 0 ∧ r = 0
  proof: by
  refine ⟨fun h => ?_, ?_⟩
  · let : Module Rᵐᵒᵖ M := Module.compHom _ ((RingHom.id R).fromOpposite mul_comm)
    have : IsCentralScalar R M := ⟨fun r m => rfl⟩
    have hf0 : toTrivSqZeroExt (ι R x) = (0, x) := lift_ι_apply _ _
    rw [h]; rw [AlgHom.commutes] at hf0
    have : r = 0 ∧ 0 = x := 

中文:
定理 ι_eq_algebraMap_iff
  条件: (x : M) (r : R)
  结论: ι R x = algebraMap R _ r ↔ x = 0 ∧ r = 0
  证明: by
  refine ⟨fun h => ?_, ?_⟩
  · let : Module Rᵐᵒᵖ M := Module.compHom _ ((RingHom.id R).fromOpposite mul_comm)
    have : IsCentralScalar R M := ⟨fun r m => rfl⟩
    have hf0 : toTrivSqZeroExt (ι R x) = (0, x) := lift_ι_apply _ _
    rw [h]; rw [AlgHom.commutes] at hf0
    have : r = 0 ∧ 0 = x := 

Depends on / 依赖: AlgHom, AlgHom.commutes, Eq.symm, IsCentralScalar, Module, Module.compHom, Prod.ext_iff, RingHom, RingHom.id, commutes, compHom, ext_iff, fromOpposite, imp_left, map_zero, mul_comm, this.symm.imp_left, toTrivSqZeroExt
-/
theorem ι_eq_algebraMap_iff (x : M) (r : R) : ι R x = algebraMap R _ r ↔ x = 0 ∧ r = 0 := by
  refine ⟨fun h => ?_, ?_⟩
  · let : Module Rᵐᵒᵖ M := Module.compHom _ ((RingHom.id R).fromOpposite mul_comm)
    have : IsCentralScalar R M := ⟨fun r m => rfl⟩
    have hf0 : toTrivSqZeroExt (ι R x) = (0, x) := lift_ι_apply _ _
    rw [h]; rw [AlgHom.commutes] at hf0
    have : r = 0 ∧ 0 = x := Prod.ext_iff.1 hf0
    exact this.symm.imp_left Eq.symm
  · rintro ⟨rfl, rfl⟩
    rw [map_zero]; rw [map_zero]

@[simp]
/--
theorem `ι_ne_one` / 定理 `ι_ne_one`

English:
theorem ι_ne_one
  given: [Nontrivial R] (x : M)
  statement: ι R x != 1
  proof: by
  rw [← (algebraMap R (TensorAlgebra R M)).map_one]; rw [Ne]; rw [ι_eq_algebraMap_iff]
  exact one_ne_zero ∘ And.right

中文:
定理 ι_ne_one
  条件: [Nontrivial R] (x : M)
  结论: ι R x != 1
  证明: by
  rw [← (algebraMap R (TensorAlgebra R M)).map_one]; rw [Ne]; rw [ι_eq_algebraMap_iff]
  exact one_ne_zero ∘ And.right

Depends on / 依赖: And.right, TensorAlgebra, algebraMap, map_one, one_ne_zero
-/
theorem ι_ne_one [Nontrivial R] (x : M) : ι R x != 1 := by
  rw [← (algebraMap R (TensorAlgebra R M)).map_one]; rw [Ne]; rw [ι_eq_algebraMap_iff]
  exact one_ne_zero ∘ And.right

/--
theorem `ι_range_disjoint_one` / 定理 `ι_range_disjoint_one`

English:
theorem ι_range_disjoint_one
  proof: by
  rw [Submodule.disjoint_def]; rw [Submodule.one_eq_range]
  rintro _ ⟨x, hx⟩ ⟨r, rfl⟩
  rw [Algebra.linearMap_apply]; rw [ι_eq_algebraMap_iff] at hx
  rw [hx.2]; rw [map_zero]

中文:
定理 ι_range_disjoint_one
  证明: by
  rw [Submodule.disjoint_def]; rw [Submodule.one_eq_range]
  rintro _ ⟨x, hx⟩ ⟨r, rfl⟩
  rw [Algebra.linearMap_apply]; rw [ι_eq_algebraMap_iff] at hx
  rw [hx.2]; rw [map_zero]

Depends on / 依赖: Algebra, Algebra.linearMap_apply, Submodule, Submodule.disjoint_def, Submodule.one_eq_range, disjoint_def, linearMap_apply, map_zero, one_eq_range
-/
theorem ι_range_disjoint_one :
    Disjoint (LinearMap.range (ι R : M ->ₗ[R] TensorAlgebra R M))
      (1 : Submodule R (TensorAlgebra R M)) := by
  rw [Submodule.disjoint_def]; rw [Submodule.one_eq_range]
  rintro _ ⟨x, hx⟩ ⟨r, rfl⟩
  rw [Algebra.linearMap_apply]; rw [ι_eq_algebraMap_iff] at hx
  rw [hx.2]; rw [map_zero]

variable (R M)

/--
Definition of `tprod` / `tprod` 的定义

English:
definition tprod
  signature: (n : Nat)
  body: (MultilinearMap.mkPiAlgebraFin R n (TensorAlgebra R M)).compLinearMap fun _ => ι R

@[simp]

中文:
定义 tprod
  签名: (n : 自然数)
  定义体: (MultilinearMap.mkPiAlgebraFin R n (TensorAlgebra R M)).compLinearMap fun _ => ι R

@[simp]

Depends on / 依赖: MultilinearMap, MultilinearMap.mkPiAlgebraFin, TensorAlgebra, compLinearMap, mkPiAlgebraFin
-/
def tprod (n : Nat) : MultilinearMap R (fun _ : Fin n => M) (TensorAlgebra R M) :=
  (MultilinearMap.mkPiAlgebraFin R n (TensorAlgebra R M)).compLinearMap fun _ => ι R

@[simp]
/--
theorem `tprod_apply` / 定理 `tprod_apply`

English:
theorem tprod_apply
  given: {n : Nat} (x : Fin n -> M)
  statement: tprod R M n x = (List.ofFn fun i => ι R (x i)).prod
  proof: rfl

中文:
定理 tprod_apply
  条件: {n : 自然数} (x : Fin n -> M)
  结论: tprod R M n x = (List.ofFn fun i => ι R (x i)).prod
  证明: rfl
-/
theorem tprod_apply {n : Nat} (x : Fin n -> M) : tprod R M n x = (List.ofFn fun i => ι R (x i)).prod :=
  rfl

end TensorAlgebra

namespace FreeAlgebra

variable {R M}

/--
Definition of `toTensor` / `toTensor` 的定义

English:
definition toTensor
  signature: : FreeAlgebra R M ->ₐ[R] TensorAlgebra R M
  body: FreeAlgebra.lift R (TensorAlgebra.ι R)

@[simp]

中文:
定义 toTensor
  签名: : FreeAlgebra R M ->ₐ[R] TensorAlgebra R M
  定义体: FreeAlgebra.lift R (TensorAlgebra.ι R)

@[simp]

Depends on / 依赖: FreeAlgebra, FreeAlgebra.lift, TensorAlgebra
-/
def toTensor : FreeAlgebra R M ->ₐ[R] TensorAlgebra R M :=
  FreeAlgebra.lift R (TensorAlgebra.ι R)

@[simp]
/--
theorem `toTensor_ι` / 定理 `toTensor_ι`

English:
theorem toTensor_ι
  given: (m : M)
  statement: FreeAlgebra.toTensor (FreeAlgebra.ι R m) = TensorAlgebra.ι R m
  proof: by
  simp [toTensor]

中文:
定理 toTensor_ι
  条件: (m : M)
  结论: FreeAlgebra.toTensor (FreeAlgebra.ι R m) = TensorAlgebra.ι R m
  证明: by
  simp [toTensor]

Depends on / 依赖: toTensor
-/
theorem toTensor_ι (m : M) : FreeAlgebra.toTensor (FreeAlgebra.ι R m) = TensorAlgebra.ι R m := by
  simp [toTensor]

end FreeAlgebra
