/-
Copyright (c) 2020 Nicolò Cavalleri. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nicolò Cavalleri, Andrew Yang
-/
module

public import Mathlib.RingTheory.Derivation.ToSquareZero
public import Mathlib.RingTheory.Ideal.Cotangent
public import Mathlib.RingTheory.IsTensorProduct
public import Mathlib.RingTheory.EssentialFiniteness
public import Mathlib.Algebra.Exact.Basic
public import Mathlib.LinearAlgebra.TensorProduct.RightExactness
public import Mathlib.Tactic.SuppressCompilation

/-!
# The module of Kähler differentials

## Main results

- `KaehlerDifferential`: The module of Kähler differentials. For an `R`-algebra `S`, we provide
  the notation `Ω[S⁄R]` for `KaehlerDifferential R S`.
  Note that the slash is `\textfractionsolidus`.
- `KaehlerDifferential.D`: The derivation into the module of Kähler differentials.
- `KaehlerDifferential.span_range_derivation`: The image of `D` spans `Ω[S⁄R]` as an `S`-module.
- `KaehlerDifferential.linearMapEquivDerivation`:
  The isomorphism `Hom_R(Ω[S⁄R], M) ≃ₗ[S] Der_R(S, M)`.
- `KaehlerDifferential.quotKerTotalEquiv`: An alternative description of `Ω[S⁄R]` as `S` copies
  of `S` with kernel (`KaehlerDifferential.kerTotal`) generated by the relations:
  1. `dx + dy = d(x + y)`
  2. `x dy + y dx = d(x * y)`
  3. `dr = 0` for `r ∈ R`
- `KaehlerDifferential.map`: Given a map between the arrows `R →+* A` and `S →+* B`, we have an
  `A`-linear map `Ω[A⁄R] → Ω[B⁄S]`.
- `KaehlerDifferential.map_surjective`:
  The sequence `Ω[B⁄R] → Ω[B⁄A] → 0` is exact.
- `KaehlerDifferential.exact_mapBaseChange_map`:
  The sequence `B ⊗[A] Ω[A⁄R] → Ω[B⁄R] → Ω[B⁄A]` is exact.
- `KaehlerDifferential.exact_kerCotangentToTensor_mapBaseChange`:
  If `A → B` is surjective with kernel `I`, then
  the sequence `I/I² → B ⊗[A] Ω[A⁄R] → Ω[B⁄R]` is exact.
- `KaehlerDifferential.mapBaseChange_surjective`:
  If `A → B` is surjective, then the sequence `B ⊗[A] Ω[A⁄R] → Ω[B⁄R] → 0` is exact.

## Future project

- Define the `IsKaehlerDifferential` predicate.
-/

@[expose] public section

suppress_compilation

noncomputable section KaehlerDifferential

open scoped TensorProduct
open Algebra Finsupp

universe u v

variable (R : Type u) (S : Type v) [CommRing R] [CommRing S] [Algebra R S]

/--
Definition of `KaehlerDifferential.ideal` / `KaehlerDifferential.ideal` 的定义

English:
abbreviation KaehlerDifferential.ideal
  signature: : Ideal (S otimes[R] S)
  body: RingHom.ker (TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S)

中文:
缩写 KaehlerDifferential.ideal
  签名: : Ideal (S otimes[R] S)
  定义体: RingHom.ker (TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S)

Depends on / 依赖: RingHom, RingHom.ker, TensorProduct, TensorProduct.lmul, otimes
-/
abbrev KaehlerDifferential.ideal : Ideal (S otimes[R] S) :=
  RingHom.ker (TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S)

variable {S}

/--
theorem `KaehlerDifferential.one_smul_sub_smul_one_mem_ideal` / 定理 `KaehlerDifferential.one_smul_sub_smul_one_mem_ideal`

English:
theorem KaehlerDifferential.one_smul_sub_smul_one_mem_ideal
  given: (a : S)
  proof: by simp [RingHom.mem_ker]

中文:
定理 KaehlerDifferential.one_smul_sub_smul_one_mem_ideal
  条件: (a : S)
  证明: by simp [RingHom.mem_ker]

Depends on / 依赖: RingHom, RingHom.mem_ker, mem_ker
-/
theorem KaehlerDifferential.one_smul_sub_smul_one_mem_ideal (a : S) :
    (1 : S) otimesₜ[R] a - a otimesₜ[R] (1 : S) in KaehlerDifferential.ideal R S := by simp [RingHom.mem_ker]

variable {R}
variable {M : Type*} [AddCommGroup M] [Module R M] [Module S M] [IsScalarTower R S M]

/--
Definition of `Derivation.tensorProductTo` / `Derivation.tensorProductTo` 的定义

English:
definition Derivation.tensorProductTo
  signature: (D : Derivation R S M)
  body: TensorProduct.AlgebraTensorModule.lift ((LinearMap.lsmul S (S ->ₗ[R] M)).flip D.toLinearMap)

中文:
定义 Derivation.tensorProductTo
  签名: (D : Derivation R S M)
  定义体: TensorProduct.AlgebraTensorModule.lift ((LinearMap.lsmul S (S ->ₗ[R] M)).flip D.toLinearMap)

Depends on / 依赖: AlgebraTensorModule, D.toLinearMap, LinearMap, LinearMap.lsmul, TensorProduct, TensorProduct.AlgebraTensorModule.lift, toLinearMap
-/
def Derivation.tensorProductTo (D : Derivation R S M) : S otimes[R] S ->ₗ[S] M :=
  TensorProduct.AlgebraTensorModule.lift ((LinearMap.lsmul S (S ->ₗ[R] M)).flip D.toLinearMap)

/--
theorem `Derivation.tensorProductTo_tmul` / 定理 `Derivation.tensorProductTo_tmul`

English:
theorem Derivation.tensorProductTo_tmul
  given: (D : Derivation R S M) (s t : S)
  proof: rfl

中文:
定理 Derivation.tensorProductTo_tmul
  条件: (D : Derivation R S M) (s t : S)
  证明: rfl
-/
theorem Derivation.tensorProductTo_tmul (D : Derivation R S M) (s t : S) :
    D.tensorProductTo (s otimesₜ t) = s • D t := rfl

/--
theorem `Derivation.tensorProductTo_mul` / 定理 `Derivation.tensorProductTo_mul`

English:
theorem Derivation.tensorProductTo_mul
  given: (D : Derivation R S M) (x y : S otimes[R] S)
  proof: by
  refine TensorProduct.induction_on x ?_ ?_ ?_
  · rw [zero_mul, map_zero, map_zero, zero_smul, smul_zero, add_zero]
  swap
  · intro x₁ y₁ h₁ h₂
    rw [add_mul]; rw [map_add]; rw [map_add]; rw [map_add]; rw [add_smul]; rw [smul_add]; rw [h₁]; rw [h₂]; rw [add_add_add_comm]
  intro x₁ x₂
  refin

中文:
定理 Derivation.tensorProductTo_mul
  条件: (D : Derivation R S M) (x y : S otimes[R] S)
  证明: by
  refine TensorProduct.induction_on x ?_ ?_ ?_
  · rw [zero_mul, map_zero, map_zero, zero_smul, smul_zero, add_zero]
  swap
  · intro x₁ y₁ h₁ h₂
    rw [add_mul]; rw [map_add]; rw [map_add]; rw [map_add]; rw [add_smul]; rw [smul_add]; rw [h₁]; rw [h₂]; rw [add_add_add_comm]
  intro x₁ x₂
  refin

Depends on / 依赖: D.tensorProductTo, tensorProductTo
-/
theorem Derivation.tensorProductTo_mul (D : Derivation R S M) (x y : S otimes[R] S) :
    D.tensorProductTo (x * y) =
      TensorProduct.lmul' (S := S) R x • D.tensorProductTo y +
        TensorProduct.lmul' (S := S) R y • D.tensorProductTo x := by
  refine TensorProduct.induction_on x ?_ ?_ ?_
  · rw [zero_mul, map_zero, map_zero, zero_smul, smul_zero, add_zero]
  swap
  · intro x₁ y₁ h₁ h₂
    rw [add_mul]; rw [map_add]; rw [map_add]; rw [map_add]; rw [add_smul]; rw [smul_add]; rw [h₁]; rw [h₂]; rw [add_add_add_comm]
  intro x₁ x₂
  refine TensorProduct.induction_on y ?_ ?_ ?_
  · rw [mul_zero, map_zero, map_zero, zero_smul, smul_zero, add_zero]
  swap
  · intro x₁ y₁ h₁ h₂
    rw [mul_add]; rw [map_add]; rw [map_add]; rw [map_add]; rw [add_smul]; rw [smul_add]; rw [h₁]; rw [h₂]; rw [add_add_add_comm]
  intro x y
  simp only [TensorProduct.tmul_mul_tmul, Derivation.tensorProductTo,
    TensorProduct.AlgebraTensorModule.lift_apply,
    TensorProduct.lmul'_apply_tmul]
  dsimp
  rw [D.leibniz]
  simp only [smul_smul, smul_add, mul_comm (x * y) x₁, mul_right_comm x₁ x₂, ← mul_assoc]

variable (R S)

/--
theorem `KaehlerDifferential.submodule_span_range_eq_ideal` / 定理 `KaehlerDifferential.submodule_span_range_eq_ideal`

English:
theorem KaehlerDifferential.submodule_span_range_eq_ideal
  proof: by
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨s, rfl⟩
    exact KaehlerDifferential.one_smul_sub_smul_one_mem_ideal _ _
  · rintro x (hx : _ = _)
    have : x - TensorProduct.lmul' (S := S) R x otimesₜ[R] (1 : S) = x := by
      rw [hx]; rw [TensorProduct.zero_tmul]; rw [sub_zero]


中文:
定理 KaehlerDifferential.submodule_span_range_eq_ideal
  证明: by
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨s, rfl⟩
    exact KaehlerDifferential.one_smul_sub_smul_one_mem_ideal _ _
  · rintro x (hx : _ = _)
    have : x - TensorProduct.lmul' (S := S) R x otimesₜ[R] (1 : S) = x := by
      rw [hx]; rw [TensorProduct.zero_tmul]; rw [sub_zero]


Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.one_smul_sub_smul_one_mem_ideal, Submodule, Submodule.span_le, TensorProduct, TensorProduct.induction_on, TensorProduct.lmul, TensorProduct.zero_tmul, induction_on, le_antisymm, map_zero, one_smul_sub_smul_one_mem_ideal, otimes, span_le, sub_zero, zero_mem, zero_tmul
-/
theorem KaehlerDifferential.submodule_span_range_eq_ideal :
    Submodule.span S (Set.range fun s : S => (1 : S) otimesₜ[R] s - s otimesₜ[R] (1 : S)) =
      (KaehlerDifferential.ideal R S).restrictScalars S := by
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨s, rfl⟩
    exact KaehlerDifferential.one_smul_sub_smul_one_mem_ideal _ _
  · rintro x (hx : _ = _)
    have : x - TensorProduct.lmul' (S := S) R x otimesₜ[R] (1 : S) = x := by
      rw [hx]; rw [TensorProduct.zero_tmul]; rw [sub_zero]
    rw [← this]
    clear this hx
    refine TensorProduct.induction_on x ?_ ?_ ?_
    · rw [map_zero, TensorProduct.zero_tmul, sub_zero]; exact zero_mem _
    · intro x y
      have : x otimesₜ[R] y - (x * y) otimesₜ[R] (1 : S) = x • ((1 : S) otimesₜ y - y otimesₜ (1 : S)) := by
        simp_rw [smul_sub, TensorProduct.smul_tmul', smul_eq_mul, mul_one]
      rw [TensorProduct.lmul'_apply_tmul]; rw [this]
      refine Submodule.smul_mem _ x ?_
      apply Submodule.subset_span
      exact Set.mem_range_self y
    · intro x y hx hy
      rw [map_add]; rw [TensorProduct.add_tmul]; rw [← sub_add_sub_comm]
      exact add_mem hx hy

/--
theorem `KaehlerDifferential.span_range_eq_ideal` / 定理 `KaehlerDifferential.span_range_eq_ideal`

English:
theorem KaehlerDifferential.span_range_eq_ideal
  proof: by
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro _ ⟨s, rfl⟩
    exact KaehlerDifferential.one_smul_sub_smul_one_mem_ideal _ _
  · change (KaehlerDifferential.ideal R S).restrictScalars S <= (Ideal.span _).restrictScalars S
    rw [← KaehlerDifferential.submodule_span_range_eq_ideal]; rw [Ide

中文:
定理 KaehlerDifferential.span_range_eq_ideal
  证明: by
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro _ ⟨s, rfl⟩
    exact KaehlerDifferential.one_smul_sub_smul_one_mem_ideal _ _
  · change (KaehlerDifferential.ideal R S).restrictScalars S <= (Ideal.span _).restrictScalars S
    rw [← KaehlerDifferential.submodule_span_range_eq_ideal]; rw [Ide

Depends on / 依赖: Ideal.span, Ideal.span_le, KaehlerDifferential, KaehlerDifferential.ideal, KaehlerDifferential.one_smul_sub_smul_one_mem_ideal, KaehlerDifferential.submodule_span_range_eq_ideal, Submodule, Submodule.span_span_of_tower, Submodule.subset_span, conv_rhs, le_antisymm, one_smul_sub_smul_one_mem_ideal, restrictScalars, span_le, span_span_of_tower, submodule_span_range_eq_ideal, subset_span
-/
theorem KaehlerDifferential.span_range_eq_ideal :
    Ideal.span (Set.range fun s : S => (1 : S) otimesₜ[R] s - s otimesₜ[R] (1 : S)) =
      KaehlerDifferential.ideal R S := by
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro _ ⟨s, rfl⟩
    exact KaehlerDifferential.one_smul_sub_smul_one_mem_ideal _ _
  · change (KaehlerDifferential.ideal R S).restrictScalars S <= (Ideal.span _).restrictScalars S
    rw [← KaehlerDifferential.submodule_span_range_eq_ideal]; rw [Ideal.span]
    conv_rhs => rw [← Submodule.span_span_of_tower S]
    exact Submodule.subset_span

/--
Definition of `KaehlerDifferential` / `KaehlerDifferential` 的定义

English:
definition KaehlerDifferential
  signature: : Type v
  body: (KaehlerDifferential.ideal R S).Cotangent
deriving Inhabited

中文:
定义 KaehlerDifferential
  签名: : 类型v
  定义体: (KaehlerDifferential.ideal R S).Cotangent
deriving Inhabited

Depends on / 依赖: Cotangent, KaehlerDifferential, KaehlerDifferential.ideal
-/
def KaehlerDifferential : Type v :=
  (KaehlerDifferential.ideal R S).Cotangent
deriving Inhabited

-- The `SMul R'` instance exists to avoid a zsmul diamond.
variable {R' : Type*} [CommRing R'] [Algebra R' S] [SMulCommClass R R' S] in
deriving instance SMul R', AddCommGroup, Module R', Module (S otimes[R] S), IsScalarTower S (S otimes[R] S)
  for KaehlerDifferential R S

@[inherit_doc KaehlerDifferential]
notation "Ω[" S "⁄" R "]" => KaehlerDifferential R S

/--
Instance `KaehlerDifferential.isScalarTower_of_tower` / 实例 `KaehlerDifferential.isScalarTower_of_tower`

English:
instance KaehlerDifferential.isScalarTower_of_tower
  signature: {R₁ R₂ : Type*} [CommRing R₁] [CommRing R₂]
  body: Submodule.Quotient.isScalarTower _ _

中文:
实例 KaehlerDifferential.isScalarTower_of_tower
  签名: {R₁ R₂ : 类型} [CommRing R₁] [CommRing R₂]
  定义体: Submodule.Quotient.isScalarTower _ _

Depends on / 依赖: Quotient, Submodule, Submodule.Quotient.isScalarTower, isScalarTower
-/
instance KaehlerDifferential.isScalarTower_of_tower {R₁ R₂ : Type*} [CommRing R₁] [CommRing R₂]
    [Algebra R₁ S] [Algebra R₂ S] [SMul R₁ R₂]
    [SMulCommClass R R₁ S] [SMulCommClass R R₂ S] [IsScalarTower R₁ R₂ S] :
    IsScalarTower R₁ R₂ Ω[S⁄R] :=
  Submodule.Quotient.isScalarTower _ _

/--
Instance `KaehlerDifferential.isScalarTower'` / 实例 `KaehlerDifferential.isScalarTower'`

English:
instance KaehlerDifferential.isScalarTower'
  signature: : IsScalarTower R (S otimes[R] S) Ω[S⁄R]
  body: Submodule.Quotient.isScalarTower _ _

中文:
实例 KaehlerDifferential.isScalarTower'
  签名: : IsScalarTower R (S otimes[R] S) Ω[S⁄R]
  定义体: Submodule.Quotient.isScalarTower _ _

Depends on / 依赖: Quotient, Submodule, Submodule.Quotient.isScalarTower, isScalarTower
-/
instance KaehlerDifferential.isScalarTower' : IsScalarTower R (S otimes[R] S) Ω[S⁄R] :=
  Submodule.Quotient.isScalarTower _ _

/--
Definition of `KaehlerDifferential.fromIdeal` / `KaehlerDifferential.fromIdeal` 的定义

English:
definition KaehlerDifferential.fromIdeal
  signature: : KaehlerDifferential.ideal R S ->ₗ[S otimes[R] S] Ω[S⁄R]
  body: (KaehlerDifferential.ideal R S).toCotangent

中文:
定义 KaehlerDifferential.fromIdeal
  签名: : KaehlerDifferential.ideal R S ->ₗ[S otimes[R] S] Ω[S⁄R]
  定义体: (KaehlerDifferential.ideal R S).toCotangent

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.ideal, toCotangent
-/
def KaehlerDifferential.fromIdeal : KaehlerDifferential.ideal R S ->ₗ[S otimes[R] S] Ω[S⁄R] :=
  (KaehlerDifferential.ideal R S).toCotangent

/--
theorem `KaehlerDifferential.fromIdeal_surjective` / 定理 `KaehlerDifferential.fromIdeal_surjective`

English:
theorem KaehlerDifferential.fromIdeal_surjective
  statement: Function.Surjective (fromIdeal R S)
  proof: Ideal.toCotangent_surjective _

中文:
定理 KaehlerDifferential.fromIdeal_surjective
  结论: Function.Surjective (fromIdeal R S)
  证明: Ideal.toCotangent_surjective _

Depends on / 依赖: Ideal.toCotangent_surjective, toCotangent_surjective
-/
theorem KaehlerDifferential.fromIdeal_surjective : Function.Surjective (fromIdeal R S) :=
  Ideal.toCotangent_surjective _

/--
Definition of `KaehlerDifferential.DLinearMap` / `KaehlerDifferential.DLinearMap` 的定义

English:
definition KaehlerDifferential.DLinearMap
  signature: : S ->ₗ[R] Ω[S⁄R]
  body: ((KaehlerDifferential.fromIdeal R S).restrictScalars R).comp
    ((TensorProduct.includeRight.toLinearMap - TensorProduct.includeLeft.toLinearMap :
            S ->ₗ[R] S otimes[R] S).codRestrict
        ((KaehlerDifferential.ideal R S).restrictScalars R)
        (KaehlerDifferential.one_smul_sub_sm

中文:
定义 KaehlerDifferential.DLinearMap
  签名: : S ->ₗ[R] Ω[S⁄R]
  定义体: ((KaehlerDifferential.fromIdeal R S).restrictScalars R).comp
    ((TensorProduct.includeRight.toLinearMap - TensorProduct.includeLeft.toLinearMap :
            S ->ₗ[R] S otimes[R] S).codRestrict
        ((KaehlerDifferential.ideal R S).restrictScalars R)
        (KaehlerDifferential.one_smul_sub_sm

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.fromIdeal, KaehlerDifferential.ideal, KaehlerDifferential.one_smul_sub_smul_one_mem_ideal, TensorProduct, TensorProduct.includeLeft.toLinearMap, TensorProduct.includeRight.toLinearMap, codRestrict, fromIdeal, includeLeft, includeRight, one_smul_sub_smul_one_mem_ideal, otimes, restrictScalars, toLinearMap
-/
def KaehlerDifferential.DLinearMap : S ->ₗ[R] Ω[S⁄R] :=
  ((KaehlerDifferential.fromIdeal R S).restrictScalars R).comp
    ((TensorProduct.includeRight.toLinearMap - TensorProduct.includeLeft.toLinearMap :
            S ->ₗ[R] S otimes[R] S).codRestrict
        ((KaehlerDifferential.ideal R S).restrictScalars R)
        (KaehlerDifferential.one_smul_sub_smul_one_mem_ideal R) :
      _ ->ₗ[R] _)

/--
theorem `KaehlerDifferential.DLinearMap_apply` / 定理 `KaehlerDifferential.DLinearMap_apply`

English:
theorem KaehlerDifferential.DLinearMap_apply
  given: (s : S)
  proof: rfl

中文:
定理 KaehlerDifferential.DLinearMap_apply
  条件: (s : S)
  证明: rfl
-/
theorem KaehlerDifferential.DLinearMap_apply (s : S) :
    KaehlerDifferential.DLinearMap R S s =
      (KaehlerDifferential.ideal R S).toCotangent
        ⟨1 otimesₜ s - s otimesₜ 1, KaehlerDifferential.one_smul_sub_smul_one_mem_ideal R s⟩ := rfl

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/--
Definition of `KaehlerDifferential.D` / `KaehlerDifferential.D` 的定义

English:
definition KaehlerDifferential.D
  signature: : Derivation R S Ω[S⁄R]
  body: { toLinearMap := KaehlerDifferential.DLinearMap R S
    map_one_eq_zero' := by
      dsimp [KaehlerDifferential.DLinearMap_apply, Ideal.toCotangent_apply]
      congr
      rw [sub_self]
    leibniz' := fun a b => by
      have : LinearMap.CompatibleSMul { x // x in ideal R S } Ω[S⁄R] S (S otimes[R]

中文:
定义 KaehlerDifferential.D
  签名: : Derivation R S Ω[S⁄R]
  定义体: { toLinearMap := KaehlerDifferential.DLinearMap R S
    map_one_eq_zero' := by
      dsimp [KaehlerDifferential.DLinearMap_apply, Ideal.toCotangent_apply]
      congr
      rw [sub_self]
    leibniz' := fun a b => by
      have : LinearMap.CompatibleSMul { x // x in ideal R S } Ω[S⁄R] S (S otimes[R]

Depends on / 依赖: CompatibleSMul, DLinearMap, DLinearMap_apply, Ideal.toCotangent_apply, KaehlerDifferential, KaehlerDifferential.DLinearMap, KaehlerDifferential.DLinearMap_apply, LinearMap, LinearMap.CompatibleSMul, LinearMap.map_smul_of_tower, leibniz, map_add, map_one_eq_zero, map_smul_of_tower, otimes, sub_self, toCotangent, toCotangent_apply, toLinearMap
-/
def KaehlerDifferential.D : Derivation R S Ω[S⁄R] :=
  { toLinearMap := KaehlerDifferential.DLinearMap R S
    map_one_eq_zero' := by
      dsimp [KaehlerDifferential.DLinearMap_apply, Ideal.toCotangent_apply]
      congr
      rw [sub_self]
    leibniz' := fun a b => by
      have : LinearMap.CompatibleSMul { x // x in ideal R S } Ω[S⁄R] S (S otimes[R] S) := inferInstance
      dsimp [KaehlerDifferential.DLinearMap_apply]
      rw [← LinearMap.map_smul_of_tower (ideal R S).toCotangent]; rw [← LinearMap.map_smul_of_tower (ideal R S).toCotangent]; rw [← map_add (ideal R S).toCotangent]; rw [Ideal.toCotangent_eq]; rw [pow_two]
      convert!
        Submodule.mul_mem_mul (KaehlerDifferential.one_smul_sub_smul_one_mem_ideal R a :)
          (KaehlerDifferential.one_smul_sub_smul_one_mem_ideal R b :) using 1
      simp only [Submodule.coe_add,
        TensorProduct.tmul_mul_tmul, mul_sub, sub_mul, mul_comm b, Submodule.coe_smul_of_tower,
        smul_sub, TensorProduct.smul_tmul', smul_eq_mul, mul_one]
      ring_nf }

/--
theorem `KaehlerDifferential.D_apply` / 定理 `KaehlerDifferential.D_apply`

English:
theorem KaehlerDifferential.D_apply
  given: (s : S)
  proof: rfl

中文:
定理 KaehlerDifferential.D_apply
  条件: (s : S)
  证明: rfl
-/
theorem KaehlerDifferential.D_apply (s : S) :
    KaehlerDifferential.D R S s =
      (KaehlerDifferential.ideal R S).toCotangent
        ⟨1 otimesₜ s - s otimesₜ 1, KaehlerDifferential.one_smul_sub_smul_one_mem_ideal R s⟩ := rfl

/--
theorem `KaehlerDifferential.span_range_derivation` / 定理 `KaehlerDifferential.span_range_derivation`

English:
theorem KaehlerDifferential.span_range_derivation
  proof: by
  rw [_root_.eq_top_iff]
  rintro x -
  obtain ⟨⟨x, hx⟩, rfl⟩ := fromIdeal_surjective R S x
  rw [← Submodule.restrictScalars_mem S]; rw [← KaehlerDifferential.submodule_span_range_eq_ideal] at hx
  suffices exists hx,
      fromIdeal R S ⟨x, hx⟩ in Submodule.span S (Set.range <| KaehlerDifferent

中文:
定理 KaehlerDifferential.span_range_derivation
  证明: by
  rw [_root_.eq_top_iff]
  rintro x -
  obtain ⟨⟨x, hx⟩, rfl⟩ := fromIdeal_surjective R S x
  rw [← Submodule.restrictScalars_mem S]; rw [← KaehlerDifferential.submodule_span_range_eq_ideal] at hx
  suffices exists hx,
      fromIdeal R S ⟨x, hx⟩ in Submodule.span S (Set.range <| KaehlerDifferent

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.D, KaehlerDifferential.submodule_span_range_eq_ideal, Set.range, Submodule, Submodule.restrictScalars_mem, Submodule.span, _root_, _root_.eq_top_iff, eq_top_iff, fromIdeal, fromIdeal_surjective, restrictScalars_mem, submodule_span_range_eq_ideal, this.snd
-/
theorem KaehlerDifferential.span_range_derivation :
    Submodule.span S (Set.range <| KaehlerDifferential.D R S) = ⊤ := by
  rw [_root_.eq_top_iff]
  rintro x -
  obtain ⟨⟨x, hx⟩, rfl⟩ := fromIdeal_surjective R S x
  rw [← Submodule.restrictScalars_mem S]; rw [← KaehlerDifferential.submodule_span_range_eq_ideal] at hx
  suffices exists hx,
      fromIdeal R S ⟨x, hx⟩ in Submodule.span S (Set.range <| KaehlerDifferential.D R S) from
    this.snd
  -- TODO: this proof looks like we're reinventing `Submodule.span_le`.
  -- I'm not sure what's the RHS here though.
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hx
  · rintro _ ⟨x, rfl⟩
    refine ⟨KaehlerDifferential.one_smul_sub_smul_one_mem_ideal R x, ?_⟩
    apply Submodule.subset_span
    exact ⟨x, KaehlerDifferential.DLinearMap_apply R S x⟩
  · exact ⟨zero_mem _, Submodule.zero_mem _⟩
  · rintro x y - - ⟨hx₁, hx₂⟩ ⟨hy₁, hy₂⟩; exact ⟨add_mem hx₁ hy₁, Submodule.add_mem _ hx₂ hy₂⟩
  · rintro r x - ⟨hx₁, hx₂⟩
    exact ⟨((KaehlerDifferential.ideal R S).restrictScalars S).smul_mem r hx₁,
      Submodule.smul_mem _ r hx₂⟩

/--
lemma `KaehlerDifferential.subsingleton_of_surjective` / 引理 `KaehlerDifferential.subsingleton_of_surjective`

English:
lemma KaehlerDifferential.subsingleton_of_surjective
  given: (h : Function.Surjective (algebraMap R S))
  proof: by
  suffices (⊤ : Submodule S Ω[S⁄R]) <= ⊥ from
    (subsingleton_iff_forall_eq 0).mpr fun y => this trivial
  rw [← KaehlerDifferential.span_range_derivation]; rw [Submodule.span_le]
  rintro _ ⟨x, rfl⟩; obtain ⟨x, rfl⟩ := h x; simp

中文:
引理 KaehlerDifferential.subsingleton_of_surjective
  条件: (h : Function.Surjective (algebraMap R S))
  证明: by
  suffices (⊤ : Submodule S Ω[S⁄R]) <= ⊥ from
    (subsingleton_iff_forall_eq 0).mpr fun y => this trivial
  rw [← KaehlerDifferential.span_range_derivation]; rw [Submodule.span_le]
  rintro _ ⟨x, rfl⟩; obtain ⟨x, rfl⟩ := h x; simp

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.span_range_derivation, Submodule, Submodule.span_le, span_le, span_range_derivation, subsingleton_iff_forall_eq
-/
lemma KaehlerDifferential.subsingleton_of_surjective (h : Function.Surjective (algebraMap R S)) :
    Subsingleton Ω[S⁄R] := by
  suffices (⊤ : Submodule S Ω[S⁄R]) <= ⊥ from
    (subsingleton_iff_forall_eq 0).mpr fun y => this trivial
  rw [← KaehlerDifferential.span_range_derivation]; rw [Submodule.span_le]
  rintro _ ⟨x, rfl⟩; obtain ⟨x, rfl⟩ := h x; simp

variable {R S}

/--
Definition of `Derivation.liftKaehlerDifferential` / `Derivation.liftKaehlerDifferential` 的定义

English:
definition Derivation.liftKaehlerDifferential
  signature: (D : Derivation R S M)
  body: by
  refine LinearMap.comp ((((KaehlerDifferential.ideal R S) •
    (⊤ : Submodule (S otimes[R] S) (KaehlerDifferential.ideal R S))).restrictScalars S).liftQ ?_ ?_)
    (Submodule.Quotient.restrictScalarsEquiv S _).symm.toLinearMap
  · exact D.tensorProductTo.comp ((KaehlerDifferential.ideal R S).su

中文:
定义 Derivation.liftKaehlerDifferential
  签名: (D : Derivation R S M)
  定义体: by
  refine LinearMap.comp ((((KaehlerDifferential.ideal R S) •
    (⊤ : Submodule (S otimes[R] S) (KaehlerDifferential.ideal R S))).restrictScalars S).liftQ ?_ ?_)
    (Submodule.Quotient.restrictScalarsEquiv S _).symm.toLinearMap
  · exact D.tensorProductTo.comp ((KaehlerDifferential.ideal R S).su

Depends on / 依赖: D.tensorProductTo.comp, Derivatio, KaehlerDifferential, KaehlerDifferential.ideal, LinearMap, LinearMap.comp, LinearMap.mem_ker, Quotient, RingHom, RingHom.mem_ker, Submodule, Submodule.Quotient.restrictScalarsEquiv, Submodule.restrictScalars_mem, Submodule.smul_induction_on, mem_ker, otimes, restrictScalars, restrictScalarsEquiv, restrictScalars_mem, smul_induction_on
-/
def Derivation.liftKaehlerDifferential (D : Derivation R S M) : Ω[S⁄R] ->ₗ[S] M := by
  refine LinearMap.comp ((((KaehlerDifferential.ideal R S) •
    (⊤ : Submodule (S otimes[R] S) (KaehlerDifferential.ideal R S))).restrictScalars S).liftQ ?_ ?_)
    (Submodule.Quotient.restrictScalarsEquiv S _).symm.toLinearMap
  · exact D.tensorProductTo.comp ((KaehlerDifferential.ideal R S).subtype.restrictScalars S)
  · intro x hx
    rw [LinearMap.mem_ker]
    refine Submodule.smul_induction_on ((Submodule.restrictScalars_mem _ _ _).mp hx) ?_ ?_
    · rintro x hx y -
      rw [RingHom.mem_ker] at hx
      dsimp
      rw [Derivation.tensorProductTo_mul]; rw [hx]; rw [y.prop]; rw [zero_smul]; rw [zero_smul]; rw [zero_add]
    · intro x y ex ey; rw [map_add, ex, ey, zero_add]

/--
theorem `Derivation.liftKaehlerDifferential_apply` / 定理 `Derivation.liftKaehlerDifferential_apply`

English:
theorem Derivation.liftKaehlerDifferential_apply
  given: (D : Derivation R S M) (x)
  proof: rfl

中文:
定理 Derivation.liftKaehlerDifferential_apply
  条件: (D : Derivation R S M) (x)
  证明: rfl
-/
theorem Derivation.liftKaehlerDifferential_apply (D : Derivation R S M) (x) :
    D.liftKaehlerDifferential ((KaehlerDifferential.ideal R S).toCotangent x) =
      D.tensorProductTo x := rfl

/--
theorem `Derivation.liftKaehlerDifferential_comp` / 定理 `Derivation.liftKaehlerDifferential_comp`

English:
theorem Derivation.liftKaehlerDifferential_comp
  given: (D : Derivation R S M)
  proof: by
  ext a
  dsimp [KaehlerDifferential.D_apply]
  refine (D.liftKaehlerDifferential_apply _).trans ?_
  rw [Subtype.coe_mk]; rw [map_sub]; rw [Derivation.tensorProductTo_tmul]; rw [Derivation.tensorProductTo_tmul]; rw [one_smul]; rw [D.map_one_eq_zero]; rw [smul_zero]; rw [sub_zero]

@[simp]

中文:
定理 Derivation.liftKaehlerDifferential_comp
  条件: (D : Derivation R S M)
  证明: by
  ext a
  dsimp [KaehlerDifferential.D_apply]
  refine (D.liftKaehlerDifferential_apply _).trans ?_
  rw [Subtype.coe_mk]; rw [map_sub]; rw [Derivation.tensorProductTo_tmul]; rw [Derivation.tensorProductTo_tmul]; rw [one_smul]; rw [D.map_one_eq_zero]; rw [smul_zero]; rw [sub_zero]

@[simp]

Depends on / 依赖: D.liftKaehlerDifferential_apply, D.map_one_eq_zero, D_apply, Derivation, Derivation.tensorProductTo_tmul, KaehlerDifferential, KaehlerDifferential.D_apply, Subtype, Subtype.coe_mk, coe_mk, liftKaehlerDifferential_apply, map_one_eq_zero, map_sub, one_smul, smul_zero, sub_zero, tensorProductTo_tmul
-/
theorem Derivation.liftKaehlerDifferential_comp (D : Derivation R S M) :
    D.liftKaehlerDifferential.compDer (KaehlerDifferential.D R S) = D := by
  ext a
  dsimp [KaehlerDifferential.D_apply]
  refine (D.liftKaehlerDifferential_apply _).trans ?_
  rw [Subtype.coe_mk]; rw [map_sub]; rw [Derivation.tensorProductTo_tmul]; rw [Derivation.tensorProductTo_tmul]; rw [one_smul]; rw [D.map_one_eq_zero]; rw [smul_zero]; rw [sub_zero]

@[simp]
/--
theorem `Derivation.liftKaehlerDifferential_comp_D` / 定理 `Derivation.liftKaehlerDifferential_comp_D`

English:
theorem Derivation.liftKaehlerDifferential_comp_D
  given: (D' : Derivation R S M) (x : S)
  proof: Derivation.congr_fun D'.liftKaehlerDifferential_comp x

@[ext]

中文:
定理 Derivation.liftKaehlerDifferential_comp_D
  条件: (D' : Derivation R S M) (x : S)
  证明: Derivation.congr_fun D'.liftKaehlerDifferential_comp x

@[ext]

Depends on / 依赖: Derivation, Derivation.congr_fun, congr_fun, liftKaehlerDifferential_comp
-/
theorem Derivation.liftKaehlerDifferential_comp_D (D' : Derivation R S M) (x : S) :
    D'.liftKaehlerDifferential (KaehlerDifferential.D R S x) = D' x :=
  Derivation.congr_fun D'.liftKaehlerDifferential_comp x

@[ext]
/--
theorem `Derivation.liftKaehlerDifferential_unique` / 定理 `Derivation.liftKaehlerDifferential_unique`

English:
theorem Derivation.liftKaehlerDifferential_unique
  statement: (f f' : Ω[S⁄R] ->ₗ[S] M)
  proof: by
  apply LinearMap.ext
  intro x
  have : x in Submodule.span S (Set.range <| KaehlerDifferential.D R S) := by
    rw [KaehlerDifferential.span_range_derivation]; trivial
  refine Submodule.span_induction ?_ ?_ ?_ ?_ this
  · rintro _ ⟨x, rfl⟩; exact congr_arg (fun D : Derivation R S M => D x) hf


中文:
定理 Derivation.liftKaehlerDifferential_unique
  结论: (f f' : Ω[S⁄R] ->ₗ[S] M)
  证明: by
  apply LinearMap.ext
  intro x
  have : x in Submodule.span S (Set.range <| KaehlerDifferential.D R S) := by
    rw [KaehlerDifferential.span_range_derivation]; trivial
  refine Submodule.span_induction ?_ ?_ ?_ ?_ this
  · rintro _ ⟨x, rfl⟩; exact congr_arg (fun D : Derivation R S M => D x) hf


Depends on / 依赖: Derivation, KaehlerDifferential, KaehlerDifferential.D, KaehlerDifferential.span_range_derivation, LinearMap, LinearMap.ext, Set.range, Submodule, Submodule.span, Submodule.span_induction, congr_arg, map_add, map_zero, span_induction, span_range_derivation
-/
theorem Derivation.liftKaehlerDifferential_unique (f f' : Ω[S⁄R] ->ₗ[S] M)
    (hf : f.compDer (KaehlerDifferential.D R S) = f'.compDer (KaehlerDifferential.D R S)) :
    f = f' := by
  apply LinearMap.ext
  intro x
  have : x in Submodule.span S (Set.range <| KaehlerDifferential.D R S) := by
    rw [KaehlerDifferential.span_range_derivation]; trivial
  refine Submodule.span_induction ?_ ?_ ?_ ?_ this
  · rintro _ ⟨x, rfl⟩; exact congr_arg (fun D : Derivation R S M => D x) hf
  · rw [map_zero, map_zero]
  · intro x y _ _ hx hy; rw [map_add, map_add, hx, hy]
  · intro a x _ e; simp [e]

variable (R S)

/--
theorem `Derivation.liftKaehlerDifferential_D` / 定理 `Derivation.liftKaehlerDifferential_D`

English:
theorem Derivation.liftKaehlerDifferential_D
  proof: Derivation.liftKaehlerDifferential_unique _ _
    (KaehlerDifferential.D R S).liftKaehlerDifferential_comp

中文:
定理 Derivation.liftKaehlerDifferential_D
  证明: Derivation.liftKaehlerDifferential_unique _ _
    (KaehlerDifferential.D R S).liftKaehlerDifferential_comp

Depends on / 依赖: Derivation, Derivation.liftKaehlerDifferential_unique, KaehlerDifferential, KaehlerDifferential.D, liftKaehlerDifferential_comp, liftKaehlerDifferential_unique
-/
theorem Derivation.liftKaehlerDifferential_D :
    (KaehlerDifferential.D R S).liftKaehlerDifferential = LinearMap.id :=
  Derivation.liftKaehlerDifferential_unique _ _
    (KaehlerDifferential.D R S).liftKaehlerDifferential_comp

variable {R S}

/--
theorem `KaehlerDifferential.D_tensorProductTo` / 定理 `KaehlerDifferential.D_tensorProductTo`

English:
theorem KaehlerDifferential.D_tensorProductTo
  given: (x : KaehlerDifferential.ideal R S)
  proof: by
  rw [← Derivation.liftKaehlerDifferential_apply]; rw [Derivation.liftKaehlerDifferential_D]
  rfl

中文:
定理 KaehlerDifferential.D_tensorProductTo
  条件: (x : KaehlerDifferential.ideal R S)
  证明: by
  rw [← Derivation.liftKaehlerDifferential_apply]; rw [Derivation.liftKaehlerDifferential_D]
  rfl

Depends on / 依赖: Derivation, Derivation.liftKaehlerDifferential_D, Derivation.liftKaehlerDifferential_apply, liftKaehlerDifferential_D, liftKaehlerDifferential_apply
-/
theorem KaehlerDifferential.D_tensorProductTo (x : KaehlerDifferential.ideal R S) :
    (KaehlerDifferential.D R S).tensorProductTo x =
      (KaehlerDifferential.ideal R S).toCotangent x := by
  rw [← Derivation.liftKaehlerDifferential_apply]; rw [Derivation.liftKaehlerDifferential_D]
  rfl

variable (R S)

/--
theorem `KaehlerDifferential.tensorProductTo_surjective` / 定理 `KaehlerDifferential.tensorProductTo_surjective`

English:
theorem KaehlerDifferential.tensorProductTo_surjective
  proof: by
  intro x; obtain ⟨x, rfl⟩ := (KaehlerDifferential.ideal R S).toCotangent_surjective x
  exact ⟨x, KaehlerDifferential.D_tensorProductTo x⟩

中文:
定理 KaehlerDifferential.tensorProductTo_surjective
  证明: by
  intro x; obtain ⟨x, rfl⟩ := (KaehlerDifferential.ideal R S).toCotangent_surjective x
  exact ⟨x, KaehlerDifferential.D_tensorProductTo x⟩

Depends on / 依赖: D_tensorProductTo, KaehlerDifferential, KaehlerDifferential.D_tensorProductTo, KaehlerDifferential.ideal, toCotangent_surjective
-/
theorem KaehlerDifferential.tensorProductTo_surjective :
    Function.Surjective (KaehlerDifferential.D R S).tensorProductTo := by
  intro x; obtain ⟨x, rfl⟩ := (KaehlerDifferential.ideal R S).toCotangent_surjective x
  exact ⟨x, KaehlerDifferential.D_tensorProductTo x⟩

/-- The `S`-linear maps from `Ω[S⁄R]` to `M` are (`S`-linearly) equivalent to `R`-derivations
from `S` to `M`. -/
@[simps! symm_apply apply_apply]
/--
Definition of `KaehlerDifferential.linearMapEquivDerivation` / `KaehlerDifferential.linearMapEquivDerivation` 的定义

English:
definition KaehlerDifferential.linearMapEquivDerivation
  signature: : (Ω[S⁄R] ->ₗ[S] M) ≃ₗ[S] Derivation R S M
  body: { Derivation.llcomp.flip <| KaehlerDifferential.D R S with
    invFun := Derivation.liftKaehlerDifferential
    left_inv := fun _ =>
      Derivation.liftKaehlerDifferential_unique _ _ (Derivation.liftKaehlerDifferential_comp _)
    right_inv := Derivation.liftKaehlerDifferential_comp }

中文:
定义 KaehlerDifferential.linearMapEquivDerivation
  签名: : (Ω[S⁄R] ->ₗ[S] M) ≃ₗ[S] Derivation R S M
  定义体: { Derivation.llcomp.flip <| KaehlerDifferential.D R S with
    invFun := Derivation.liftKaehlerDifferential
    left_inv := fun _ =>
      Derivation.liftKaehlerDifferential_unique _ _ (Derivation.liftKaehlerDifferential_comp _)
    right_inv := Derivation.liftKaehlerDifferential_comp }

Depends on / 依赖: Derivation, Derivation.liftKaehlerDifferential, Derivation.liftKaehlerDifferential_comp, Derivation.liftKaehlerDifferential_unique, Derivation.llcomp.flip, KaehlerDifferential, KaehlerDifferential.D, invFun, left_inv, liftKaehlerDifferential, liftKaehlerDifferential_comp, liftKaehlerDifferential_unique, llcomp, right_inv
-/
def KaehlerDifferential.linearMapEquivDerivation : (Ω[S⁄R] ->ₗ[S] M) ≃ₗ[S] Derivation R S M :=
  { Derivation.llcomp.flip <| KaehlerDifferential.D R S with
    invFun := Derivation.liftKaehlerDifferential
    left_inv := fun _ =>
      Derivation.liftKaehlerDifferential_unique _ _ (Derivation.liftKaehlerDifferential_comp _)
    right_inv := Derivation.liftKaehlerDifferential_comp }

/--
Definition of `KaehlerDifferential.quotientCotangentIdealRingEquiv` / `KaehlerDifferential.quotientCotangentIdealRingEquiv` 的定义

English:
definition KaehlerDifferential.quotientCotangentIdealRingEquiv
  signature: :
  body: by
  have : Function.RightInverse (TensorProduct.includeLeft (R := R) (S := R) (A := S) (B := S))
      (↑(TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S) : S otimes[R] S ->+* S) := by
    intro x; rw [AlgHom.coe_toRingHom, ← AlgHom.comp_apply, TensorProduct.lmul'_comp_includeLeft]
    rfl
  refine 

中文:
定义 KaehlerDifferential.quotientCotangentIdealRingEquiv
  签名: :
  定义体: by
  have : Function.RightInverse (TensorProduct.includeLeft (R := R) (S := R) (A := S) (B := S))
      (↑(TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S) : S otimes[R] S ->+* S) := by
    intro x; rw [AlgHom.coe_toRingHom, ← AlgHom.comp_apply, TensorProduct.lmul'_comp_includeLeft]
    rfl
  refine 

Depends on / 依赖: AlgHom, AlgHom.coe_toRingHom, AlgHom.comp_apply, Function, Function.RightInverse, Ideal.quotCotangent, Ideal.quotEquivOfEq, RightInverse, RingHom, RingHom.quotientKerEquivOfRightInverse, TensorProduct, TensorProduct.includeLeft, TensorProduct.lmul, _comp_includeLeft, coe_toRingHom, comp_apply, includeLeft, otimes, quotCotangent, quotEquivOfEq
-/
def KaehlerDifferential.quotientCotangentIdealRingEquiv :
    (S otimes S ⧸ KaehlerDifferential.ideal R S ^ 2) ⧸ (KaehlerDifferential.ideal R S).cotangentIdeal ≃+*
      S := by
  have : Function.RightInverse (TensorProduct.includeLeft (R := R) (S := R) (A := S) (B := S))
      (↑(TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S) : S otimes[R] S ->+* S) := by
    intro x; rw [AlgHom.coe_toRingHom, ← AlgHom.comp_apply, TensorProduct.lmul'_comp_includeLeft]
    rfl
  refine (Ideal.quotCotangent _).trans ?_
  refine (Ideal.quotEquivOfEq ?_).trans (RingHom.quotientKerEquivOfRightInverse this)
  ext; rfl

/--
Definition of `KaehlerDifferential.quotientCotangentIdeal` / `KaehlerDifferential.quotientCotangentIdeal` 的定义

English:
definition KaehlerDifferential.quotientCotangentIdeal
  signature: :
  body: { KaehlerDifferential.quotientCotangentIdealRingEquiv R S with
    commutes' := (KaehlerDifferential.quotientCotangentIdealRingEquiv R S).apply_symm_apply }

中文:
定义 KaehlerDifferential.quotientCotangentIdeal
  签名: :
  定义体: { KaehlerDifferential.quotientCotangentIdealRingEquiv R S with
    commutes' := (KaehlerDifferential.quotientCotangentIdealRingEquiv R S).apply_symm_apply }

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.quotientCotangentIdealRingEquiv, apply_symm_apply, commutes, quotientCotangentIdealRingEquiv
-/
def KaehlerDifferential.quotientCotangentIdeal :
    ((S otimes S ⧸ KaehlerDifferential.ideal R S ^ 2) ⧸
        (KaehlerDifferential.ideal R S).cotangentIdeal) ≃ₐ[S] S :=
  { KaehlerDifferential.quotientCotangentIdealRingEquiv R S with
    commutes' := (KaehlerDifferential.quotientCotangentIdealRingEquiv R S).apply_symm_apply }

/--
theorem `KaehlerDifferential.End_equiv_aux` / 定理 `KaehlerDifferential.End_equiv_aux`

English:
theorem KaehlerDifferential.End_equiv_aux
  given: (f : S ->ₐ[R] S otimes S ⧸ KaehlerDifferential.ideal R S ^ 2)
  proof: by
  rw [AlgHom.ext_iff]; rw [AlgHom.ext_iff]
  apply forall_congr'
  intro x
  have e₁ : (TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S).kerSquareLift (f x) =
      KaehlerDifferential.quotientCotangentIdealRingEquiv R S
        (Ideal.Quotient.mk (KaehlerDifferential.ideal R S).cotangentIdeal <| 

中文:
定理 KaehlerDifferential.End_equiv_aux
  条件: (f : S ->ₐ[R] S otimes S ⧸ KaehlerDifferential.ideal R S ^ 2)
  证明: by
  rw [AlgHom.ext_iff]; rw [AlgHom.ext_iff]
  apply forall_congr'
  intro x
  have e₁ : (TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S).kerSquareLift (f x) =
      KaehlerDifferential.quotientCotangentIdealRingEquiv R S
        (Ideal.Quotient.mk (KaehlerDifferential.ideal R S).cotangentIdeal <| 

Depends on / 依赖: AlgHom, AlgHom.ext_iff, Ideal.Quotient.mk, Ideal.Quotient.mk_surjective, IsScalarTower, IsScalarTower.toAlgHom, KaehlerDifferential, KaehlerDifferential.ideal, KaehlerDifferential.quotientCotangentIdealRingEquiv, Quotient, TensorProduct, TensorProduct.lmul, cotangentIdeal, ext_iff, forall_congr, generalize, kerSquareLift, mk_surjective, mul_one, otimes
-/
theorem KaehlerDifferential.End_equiv_aux (f : S ->ₐ[R] S otimes S ⧸ KaehlerDifferential.ideal R S ^ 2) :
    (Ideal.Quotient.mkₐ R (KaehlerDifferential.ideal R S).cotangentIdeal).comp f =
        IsScalarTower.toAlgHom R S _ ↔
      (TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S).kerSquareLift.comp f = AlgHom.id R S := by
  rw [AlgHom.ext_iff]; rw [AlgHom.ext_iff]
  apply forall_congr'
  intro x
  have e₁ : (TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S).kerSquareLift (f x) =
      KaehlerDifferential.quotientCotangentIdealRingEquiv R S
        (Ideal.Quotient.mk (KaehlerDifferential.ideal R S).cotangentIdeal <| f x) := by
    generalize f x = y; obtain ⟨y, rfl⟩ := Ideal.Quotient.mk_surjective y; rfl
  have e₂ :
    x = KaehlerDifferential.quotientCotangentIdealRingEquiv R S (IsScalarTower.toAlgHom R S _ x) :=
    (mul_one x).symm
  constructor
  · intro e
    exact (e₁.trans (@RingEquiv.congr_arg _ _ _ _ _ _
      (KaehlerDifferential.quotientCotangentIdealRingEquiv R S) _ _ e)).trans e₂.symm
  · intro e; apply (KaehlerDifferential.quotientCotangentIdealRingEquiv R S).injective
    exact e₁.symm.trans (e.trans e₂)

/-- A shortcut instance to prevent timing out. Hopefully to be removed in the future. -/
local instance instR : Module R (KaehlerDifferential.ideal R S).cotangentIdeal :=
  Submodule.module' _

/--
Definition of `KaehlerDifferential.endEquivDerivation'` / `KaehlerDifferential.endEquivDerivation'` 的定义

English:
definition KaehlerDifferential.endEquivDerivation'
  signature: :
  body: LinearEquiv.compDer ((KaehlerDifferential.ideal R S).cotangentEquivIdeal.restrictScalars S)

中文:
定义 KaehlerDifferential.endEquivDerivation'
  签名: :
  定义体: LinearEquiv.compDer ((KaehlerDifferential.ideal R S).cotangentEquivIdeal.restrictScalars S)

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.ideal, LinearEquiv, LinearEquiv.compDer, compDer, cotangentEquivIdeal, cotangentEquivIdeal.restrictScalars, restrictScalars
-/
noncomputable def KaehlerDifferential.endEquivDerivation' :
    Derivation R S Ω[S⁄R] ≃ₗ[S] Derivation R S (ideal R S).cotangentIdeal :=
  LinearEquiv.compDer ((KaehlerDifferential.ideal R S).cotangentEquivIdeal.restrictScalars S)

/--
Definition of `KaehlerDifferential.endEquivAuxEquiv` / `KaehlerDifferential.endEquivAuxEquiv` 的定义

English:
definition KaehlerDifferential.endEquivAuxEquiv
  signature: :
  body: (Equiv.refl _).subtypeEquiv (KaehlerDifferential.End_equiv_aux R S)

中文:
定义 KaehlerDifferential.endEquivAuxEquiv
  签名: :
  定义体: (Equiv.refl _).subtypeEquiv (KaehlerDifferential.End_equiv_aux R S)

Depends on / 依赖: End_equiv_aux, Equiv.refl, KaehlerDifferential, KaehlerDifferential.End_equiv_aux, subtypeEquiv
-/
def KaehlerDifferential.endEquivAuxEquiv :
    { f //
        (Ideal.Quotient.mkₐ R (KaehlerDifferential.ideal R S).cotangentIdeal).comp f =
          IsScalarTower.toAlgHom R S _ } ≃
      { f // (TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S).kerSquareLift.comp f = AlgHom.id R S } :=
  (Equiv.refl _).subtypeEquiv (KaehlerDifferential.End_equiv_aux R S)

/--
Definition of `KaehlerDifferential.endEquiv` / `KaehlerDifferential.endEquiv` 的定义

English:
definition KaehlerDifferential.endEquiv
  signature: :
  body: (KaehlerDifferential.linearMapEquivDerivation R S).toEquiv.trans
(KaehlerDifferential.endEquivDerivation' R S).toEquiv.trans
      (derivationToSquareZeroEquivLift (KaehlerDifferential.ideal R S).cotangentIdeal
            (KaehlerDifferential.ideal R S).cotangentIdeal_square).trans <|
        Kaehl

中文:
定义 KaehlerDifferential.endEquiv
  签名: :
  定义体: (KaehlerDifferential.linearMapEquivDerivation R S).toEquiv.trans
(KaehlerDifferential.endEquivDerivation' R S).toEquiv.trans
      (derivationToSquareZeroEquivLift (KaehlerDifferential.ideal R S).cotangentIdeal
            (KaehlerDifferential.ideal R S).cotangentIdeal_square).trans <|
        Kaehl

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.endEquivAuxEquiv, KaehlerDifferential.endEquivDerivation, KaehlerDifferential.ideal, KaehlerDifferential.linearMapEquivDerivation, cotangentIdeal, cotangentIdeal_square, derivationToSquareZeroEquivLift, endEquivAuxEquiv, endEquivDerivation, linearMapEquivDerivation, toEquiv, toEquiv.trans
-/
noncomputable def KaehlerDifferential.endEquiv :
    Module.End S Ω[S⁄R] ≃
      { f // (TensorProduct.lmul' R : S otimes[R] S ->ₐ[R] S).kerSquareLift.comp f = AlgHom.id R S } :=
(KaehlerDifferential.linearMapEquivDerivation R S).toEquiv.trans
(KaehlerDifferential.endEquivDerivation' R S).toEquiv.trans
      (derivationToSquareZeroEquivLift (KaehlerDifferential.ideal R S).cotangentIdeal
            (KaehlerDifferential.ideal R S).cotangentIdeal_square).trans <|
        KaehlerDifferential.endEquivAuxEquiv R S

section Finiteness

/--
theorem `KaehlerDifferential.ideal_fg` / 定理 `KaehlerDifferential.ideal_fg`

English:
theorem KaehlerDifferential.ideal_fg
  given: [EssFiniteType R S]
  proof: by
  classical
  use (EssFiniteType.finset R S).image (fun s => (1 : S) otimesₜ[R] s - s otimesₜ[R] (1 : S))
  apply le_antisymm
  · rw [Finset.coe_image, Ideal.span_le]
    rintro _ ⟨x, _, rfl⟩
    exact KaehlerDifferential.one_smul_sub_smul_one_mem_ideal R x
  · rw [← KaehlerDifferential.span_rang

中文:
定理 KaehlerDifferential.ideal_fg
  条件: [EssFiniteType R S]
  证明: by
  classical
  use (EssFiniteType.finset R S).image (fun s => (1 : S) otimesₜ[R] s - s otimesₜ[R] (1 : S))
  apply le_antisymm
  · rw [Finset.coe_image, Ideal.span_le]
    rintro _ ⟨x, _, rfl⟩
    exact KaehlerDifferential.one_smul_sub_smul_one_mem_ideal R x
  · rw [← KaehlerDifferential.span_rang

Depends on / 依赖: EssFiniteType, EssFiniteType.finset, Finset, Finset.coe_image, Ideal.span, Ideal.span_le, IsScalarTower, KaehlerDifferential, KaehlerDifferential.one_smul_sub_smul_one_mem_ideal, KaehlerDifferential.span_range_eq_ideal, classical, coe_image, finset, le_antisymm, one_smul_sub_smul_one_mem_ideal, otimes, span_le, span_range_eq_ideal
-/
theorem KaehlerDifferential.ideal_fg [EssFiniteType R S] :
    (KaehlerDifferential.ideal R S).FG := by
  classical
  use (EssFiniteType.finset R S).image (fun s => (1 : S) otimesₜ[R] s - s otimesₜ[R] (1 : S))
  apply le_antisymm
  · rw [Finset.coe_image, Ideal.span_le]
    rintro _ ⟨x, _, rfl⟩
    exact KaehlerDifferential.one_smul_sub_smul_one_mem_ideal R x
  · rw [← KaehlerDifferential.span_range_eq_ideal, Ideal.span_le]
    rintro _ ⟨x, rfl⟩
    let I : Ideal (S otimes[R] S) := Ideal.span
      ((EssFiniteType.finset R S).image (fun s => (1 : S) otimesₜ[R] s - s otimesₜ[R] (1 : S)))
    change _ - _ in I
    have : (IsScalarTower.toAlgHom R (S otimes[R] S) (S otimes[R] S ⧸ I)).comp TensorProduct.includeRight =
        (IsScalarTower.toAlgHom R (S otimes[R] S) (S otimes[R] S ⧸ I)).comp TensorProduct.includeLeft := by
      apply EssFiniteType.algHom_ext
      intro a ha
      simp only [AlgHom.coe_comp, IsScalarTower.coe_toAlgHom', Ideal.Quotient.algebraMap_eq,
        Function.comp_apply, TensorProduct.includeLeft_apply, TensorProduct.includeRight_apply,
        Ideal.Quotient.mk_eq_mk_iff_sub_mem]
      refine Ideal.subset_span ?_
      simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe]
      exact ⟨a, ha, rfl⟩
    simpa [Ideal.Quotient.mk_eq_mk_iff_sub_mem] using AlgHom.congr_fun this x

/--
Instance `KaehlerDifferential.finite` / 实例 `KaehlerDifferential.finite`

English:
instance KaehlerDifferential.finite
  signature: [EssFiniteType R S]
  body: by
  classical
  let s := (EssFiniteType.finset R S).image (fun s => D R S s)
  refine ⟨⟨s, top_le_iff.mp ?_⟩⟩
  rw [← span_range_derivation]; rw [Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  have : forall x in adjoin R (EssFiniteType.finset R S : Set S),
      .D _ _ x in Submodule.span S (s : Set Ω[S⁄

中文:
实例 KaehlerDifferential.finite
  签名: [EssFiniteType R S]
  定义体: by
  classical
  let s := (EssFiniteType.finset R S).image (fun s => D R S s)
  refine ⟨⟨s, top_le_iff.mp ?_⟩⟩
  rw [← span_range_derivation]; rw [Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  have : forall x in adjoin R (EssFiniteType.finset R S : Set S),
      .D _ _ x in Submodule.span S (s : Set Ω[S⁄

Depends on / 依赖: EssFiniteType, EssFiniteType.finset, Finset, Finset.mem_image_of_mem, Submodule, Submodule.span, Submodule.span_le, Submodule.subset_span, add_mem, adjoin, adjoin_induction, classical, finset, map_add, mem_image_of_mem, span_le, span_range_derivation, subset_span, top_le_iff, top_le_iff.mp
-/
instance KaehlerDifferential.finite [EssFiniteType R S] :
    Module.Finite S Ω[S⁄R] := by
  classical
  let s := (EssFiniteType.finset R S).image (fun s => D R S s)
  refine ⟨⟨s, top_le_iff.mp ?_⟩⟩
  rw [← span_range_derivation]; rw [Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  have : forall x in adjoin R (EssFiniteType.finset R S : Set S),
      .D _ _ x in Submodule.span S (s : Set Ω[S⁄R]) := by
    intro x hx
    refine adjoin_induction ?_ ?_ ?_ ?_ hx
    · exact fun x hx => Submodule.subset_span (Finset.mem_image_of_mem _ hx)
    · simp
    · exact fun x y _ _ hx hy => (D R S).map_add x y ▸ add_mem hx hy
    · intro x y _ _ hx hy
      simp only [Derivation.leibniz]
      exact add_mem (Submodule.smul_mem _ _ hy) (Submodule.smul_mem _ _ hx)
  obtain ⟨t, ht, ht', hxt⟩ := (essFiniteType_cond_iff R S (EssFiniteType.finset R S)).mp
    EssFiniteType.cond.choose_spec x
  rw [show D R S x =
    ht'.unit⁻¹ • (D R S (x * t) - x • D R S t) by simp [smul_smul]; rw [Units.smul_def]]
  exact Submodule.smul_mem _ _ (sub_mem (this _ hxt) (Submodule.smul_mem _ _ (this _ ht)))

end Finiteness

section Presentation

open KaehlerDifferential (D)

open Finsupp (single)

/--
Definition of `KaehlerDifferential.kerTotal` / `KaehlerDifferential.kerTotal` 的定义

English:
definition KaehlerDifferential.kerTotal
  signature: : Submodule S (S ->₀ S)
  body: Submodule.span S
    (((Set.range fun x : S × S => single x.1 1 + single x.2 1 - single (x.1 + x.2) 1) union
        Set.range fun x : S × S => single x.2 x.1 + single x.1 x.2 - single (x.1 * x.2) 1) union
      Set.range fun x : R => single (algebraMap R S x) 1)

unsuppress_compilation in
local not

中文:
定义 KaehlerDifferential.kerTotal
  签名: : Submodule S (S ->₀ S)
  定义体: Submodule.span S
    (((Set.range fun x : S × S => single x.1 1 + single x.2 1 - single (x.1 + x.2) 1) union
        Set.range fun x : S × S => single x.2 x.1 + single x.1 x.2 - single (x.1 * x.2) 1) union
      Set.range fun x : R => single (algebraMap R S x) 1)

unsuppress_compilation in
local not

Depends on / 依赖: Set.range, Submodule, Submodule.span, Subset, Subset.trans, algebraMap, single
-/
noncomputable def KaehlerDifferential.kerTotal : Submodule S (S ->₀ S) :=
  Submodule.span S
    (((Set.range fun x : S × S => single x.1 1 + single x.2 1 - single (x.1 + x.2) 1) union
        Set.range fun x : S × S => single x.2 x.1 + single x.1 x.2 - single (x.1 * x.2) 1) union
      Set.range fun x : R => single (algebraMap R S x) 1)

unsuppress_compilation in
local notation3 x "𝖣" y => (KaehlerDifferential.kerTotal R S).mkQ (single y x)

/--
theorem `KaehlerDifferential.kerTotal_mkQ_single_add` / 定理 `KaehlerDifferential.kerTotal_mkQ_single_add`

English:
theorem KaehlerDifferential.kerTotal_mkQ_single_add
  given: (x y z)
  statement: (z𝖣x + y) = (z𝖣x) + z𝖣y
  proof: by
  rw [← map_add]; rw [eq_comm]; rw [← sub_eq_zero]; rw [← map_sub (Submodule.mkQ (kerTotal R S))]; rw [Submodule.mkQ_apply]; rw [Submodule.Quotient.mk_eq_zero]
  simp_rw [← Finsupp.smul_single_one _ z, ← smul_add, ← smul_sub]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Or.inl <| Or.inl

中文:
定理 KaehlerDifferential.kerTotal_mkQ_single_add
  条件: (x y z)
  结论: (z𝖣x + y) = (z𝖣x) + z𝖣y
  证明: by
  rw [← map_add]; rw [eq_comm]; rw [← sub_eq_zero]; rw [← map_sub (Submodule.mkQ (kerTotal R S))]; rw [Submodule.mkQ_apply]; rw [Submodule.Quotient.mk_eq_zero]
  simp_rw [← Finsupp.smul_single_one _ z, ← smul_add, ← smul_sub]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Or.inl <| Or.inl

Depends on / 依赖: Finsupp, Finsupp.smul_single_one, Or.inl, Quotient, Submodule, Submodule.Quotient.mk_eq_zero, Submodule.mkQ, Submodule.mkQ_apply, Submodule.smul_mem, Submodule.subset_span, eq_comm, kerTotal, map_add, map_sub, mkQ_apply, mk_eq_zero, simp_rw, smul_add, smul_mem, smul_single_one
-/
theorem KaehlerDifferential.kerTotal_mkQ_single_add (x y z) : (z𝖣x + y) = (z𝖣x) + z𝖣y := by
  rw [← map_add]; rw [eq_comm]; rw [← sub_eq_zero]; rw [← map_sub (Submodule.mkQ (kerTotal R S))]; rw [Submodule.mkQ_apply]; rw [Submodule.Quotient.mk_eq_zero]
  simp_rw [← Finsupp.smul_single_one _ z, ← smul_add, ← smul_sub]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Or.inl <| Or.inl <| ⟨⟨_, _⟩, rfl⟩))

/--
theorem `KaehlerDifferential.kerTotal_mkQ_single_mul` / 定理 `KaehlerDifferential.kerTotal_mkQ_single_mul`

English:
theorem KaehlerDifferential.kerTotal_mkQ_single_mul
  given: (x y z)
  proof: by
  rw [← map_add]; rw [eq_comm]; rw [← sub_eq_zero]; rw [← map_sub (Submodule.mkQ (kerTotal R S))]; rw [Submodule.mkQ_apply]; rw [Submodule.Quotient.mk_eq_zero]
  simp_rw [← Finsupp.smul_single_one _ z, ← @smul_eq_mul _ _ z, ← Finsupp.smul_single, ← smul_add,
    ← smul_sub]
  exact Submodule.smul

中文:
定理 KaehlerDifferential.kerTotal_mkQ_single_mul
  条件: (x y z)
  证明: by
  rw [← map_add]; rw [eq_comm]; rw [← sub_eq_zero]; rw [← map_sub (Submodule.mkQ (kerTotal R S))]; rw [Submodule.mkQ_apply]; rw [Submodule.Quotient.mk_eq_zero]
  simp_rw [← Finsupp.smul_single_one _ z, ← @smul_eq_mul _ _ z, ← Finsupp.smul_single, ← smul_add,
    ← smul_sub]
  exact Submodule.smul

Depends on / 依赖: Finsupp, Finsupp.smul_single, Finsupp.smul_single_one, Or.inl, Or.inr, Quotient, Submodule, Submodule.Quotient.mk_eq_zero, Submodule.mkQ, Submodule.mkQ_apply, Submodule.smul_mem, Submodule.subset_span, eq_comm, kerTotal, map_add, map_sub, mkQ_apply, mk_eq_zero, simp_rw, smul_add
-/
theorem KaehlerDifferential.kerTotal_mkQ_single_mul (x y z) :
    (z𝖣x * y) = ((z * x)𝖣y) + (z * y)𝖣x := by
  rw [← map_add]; rw [eq_comm]; rw [← sub_eq_zero]; rw [← map_sub (Submodule.mkQ (kerTotal R S))]; rw [Submodule.mkQ_apply]; rw [Submodule.Quotient.mk_eq_zero]
  simp_rw [← Finsupp.smul_single_one _ z, ← @smul_eq_mul _ _ z, ← Finsupp.smul_single, ← smul_add,
    ← smul_sub]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Or.inl <| Or.inr <| ⟨⟨_, _⟩, rfl⟩))

/--
theorem `KaehlerDifferential.kerTotal_mkQ_single_algebraMap` / 定理 `KaehlerDifferential.kerTotal_mkQ_single_algebraMap`

English:
theorem KaehlerDifferential.kerTotal_mkQ_single_algebraMap
  given: (x y)
  statement: (y𝖣algebraMap R S x) = 0
  proof: by
  rw [Submodule.mkQ_apply]; rw [Submodule.Quotient.mk_eq_zero]; rw [← Finsupp.smul_single_one _ y]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Or.inr <| ⟨_, rfl⟩))

中文:
定理 KaehlerDifferential.kerTotal_mkQ_single_algebraMap
  条件: (x y)
  结论: (y𝖣algebraMap R S x) = 0
  证明: by
  rw [Submodule.mkQ_apply]; rw [Submodule.Quotient.mk_eq_zero]; rw [← Finsupp.smul_single_one _ y]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Or.inr <| ⟨_, rfl⟩))

Depends on / 依赖: Finsupp, Finsupp.smul_single_one, Or.inr, Quotient, Submodule, Submodule.Quotient.mk_eq_zero, Submodule.mkQ_apply, Submodule.smul_mem, Submodule.subset_span, mkQ_apply, mk_eq_zero, smul_mem, smul_single_one, subset_span
-/
theorem KaehlerDifferential.kerTotal_mkQ_single_algebraMap (x y) : (y𝖣algebraMap R S x) = 0 := by
  rw [Submodule.mkQ_apply]; rw [Submodule.Quotient.mk_eq_zero]; rw [← Finsupp.smul_single_one _ y]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Or.inr <| ⟨_, rfl⟩))

/--
theorem `KaehlerDifferential.kerTotal_mkQ_single_algebraMap_one` / 定理 `KaehlerDifferential.kerTotal_mkQ_single_algebraMap_one`

English:
theorem KaehlerDifferential.kerTotal_mkQ_single_algebraMap_one
  given: (x)
  statement: (x𝖣1) = 0
  proof: by
  rw [← (algebraMap R S).map_one]; rw [KaehlerDifferential.kerTotal_mkQ_single_algebraMap]

中文:
定理 KaehlerDifferential.kerTotal_mkQ_single_algebraMap_one
  条件: (x)
  结论: (x𝖣1) = 0
  证明: by
  rw [← (algebraMap R S).map_one]; rw [KaehlerDifferential.kerTotal_mkQ_single_algebraMap]

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.kerTotal_mkQ_single_algebraMap, algebraMap, kerTotal_mkQ_single_algebraMap, map_one
-/
theorem KaehlerDifferential.kerTotal_mkQ_single_algebraMap_one (x) : (x𝖣1) = 0 := by
  rw [← (algebraMap R S).map_one]; rw [KaehlerDifferential.kerTotal_mkQ_single_algebraMap]

/--
theorem `KaehlerDifferential.kerTotal_mkQ_single_smul` / 定理 `KaehlerDifferential.kerTotal_mkQ_single_smul`

English:
theorem KaehlerDifferential.kerTotal_mkQ_single_smul
  given: (r : R) (x y)
  statement: (y𝖣r • x) = r • y𝖣x
  proof: by
  let : SMulZeroClass R S := inferInstance
  rw [Algebra.smul_def]; rw [KaehlerDifferential.kerTotal_mkQ_single_mul]; rw [KaehlerDifferential.kerTotal_mkQ_single_algebraMap]; rw [add_zero]; rw [← LinearMap.map_smul_of_tower]; rw [Finsupp.smul_single]; rw [mul_comm]; rw [Algebra.smul_def]

中文:
定理 KaehlerDifferential.kerTotal_mkQ_single_smul
  条件: (r : R) (x y)
  结论: (y𝖣r • x) = r • y𝖣x
  证明: by
  let : SMulZeroClass R S := inferInstance
  rw [Algebra.smul_def]; rw [KaehlerDifferential.kerTotal_mkQ_single_mul]; rw [KaehlerDifferential.kerTotal_mkQ_single_algebraMap]; rw [add_zero]; rw [← LinearMap.map_smul_of_tower]; rw [Finsupp.smul_single]; rw [mul_comm]; rw [Algebra.smul_def]

Depends on / 依赖: Algebra, Algebra.smul_def, Finsupp, Finsupp.smul_single, KaehlerDifferential, KaehlerDifferential.kerTotal_mkQ_single_algebraMap, KaehlerDifferential.kerTotal_mkQ_single_mul, LinearMap, LinearMap.map_smul_of_tower, SMulZeroClass, add_zero, kerTotal_mkQ_single_algebraMap, kerTotal_mkQ_single_mul, map_smul_of_tower, mul_comm, smul_def, smul_single
-/
theorem KaehlerDifferential.kerTotal_mkQ_single_smul (r : R) (x y) : (y𝖣r • x) = r • y𝖣x := by
  let : SMulZeroClass R S := inferInstance
  rw [Algebra.smul_def]; rw [KaehlerDifferential.kerTotal_mkQ_single_mul]; rw [KaehlerDifferential.kerTotal_mkQ_single_algebraMap]; rw [add_zero]; rw [← LinearMap.map_smul_of_tower]; rw [Finsupp.smul_single]; rw [mul_comm]; rw [Algebra.smul_def]

set_option backward.isDefEq.respectTransparency.types false in
/--
Definition of `KaehlerDifferential.derivationQuotKerTotal` / `KaehlerDifferential.derivationQuotKerTotal` 的定义

English:
definition KaehlerDifferential.derivationQuotKerTotal
  signature: :
  body: 1𝖣x
  map_add' _ _ := KaehlerDifferential.kerTotal_mkQ_single_add _ _ _ _ _
  map_smul' _ _ := KaehlerDifferential.kerTotal_mkQ_single_smul _ _ _ _ _
  map_one_eq_zero' := KaehlerDifferential.kerTotal_mkQ_single_algebraMap_one _ _ _
  leibniz' a b :=
    (KaehlerDifferential.kerTotal_mkQ_single_mul 

中文:
定义 KaehlerDifferential.derivationQuotKerTotal
  签名: :
  定义体: 1𝖣x
  map_add' _ _ := KaehlerDifferential.kerTotal_mkQ_single_add _ _ _ _ _
  map_smul' _ _ := KaehlerDifferential.kerTotal_mkQ_single_smul _ _ _ _ _
  map_one_eq_zero' := KaehlerDifferential.kerTotal_mkQ_single_algebraMap_one _ _ _
  leibniz' a b :=
    (KaehlerDifferential.kerTotal_mkQ_single_mul 
-/
noncomputable def KaehlerDifferential.derivationQuotKerTotal :
    Derivation R S ((S ->₀ S) ⧸ KaehlerDifferential.kerTotal R S) where
  toFun x := 1𝖣x
  map_add' _ _ := KaehlerDifferential.kerTotal_mkQ_single_add _ _ _ _ _
  map_smul' _ _ := KaehlerDifferential.kerTotal_mkQ_single_smul _ _ _ _ _
  map_one_eq_zero' := KaehlerDifferential.kerTotal_mkQ_single_algebraMap_one _ _ _
  leibniz' a b :=
    (KaehlerDifferential.kerTotal_mkQ_single_mul _ _ _ _ _).trans
      (by simp_rw [← Finsupp.smul_single_one _ (1 * _ : S)]; dsimp; simp)

/--
theorem `KaehlerDifferential.derivationQuotKerTotal_apply` / 定理 `KaehlerDifferential.derivationQuotKerTotal_apply`

English:
theorem KaehlerDifferential.derivationQuotKerTotal_apply
  given: (x)
  proof: rfl

中文:
定理 KaehlerDifferential.derivationQuotKerTotal_apply
  条件: (x)
  证明: rfl
-/
theorem KaehlerDifferential.derivationQuotKerTotal_apply (x) :
    KaehlerDifferential.derivationQuotKerTotal R S x = 1𝖣x :=
  rfl

/--
theorem `KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination` / 定理 `KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination`

English:
theorem KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination
  proof: by
  apply Finsupp.lhom_ext
  intro a b
  conv_rhs => rw [← Finsupp.smul_single_one a b, map_smul]
  simp [KaehlerDifferential.derivationQuotKerTotal_apply]

中文:
定理 KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination
  证明: by
  apply Finsupp.lhom_ext
  intro a b
  conv_rhs => rw [← Finsupp.smul_single_one a b, map_smul]
  simp [KaehlerDifferential.derivationQuotKerTotal_apply]

Depends on / 依赖: Finsupp, Finsupp.lhom_ext, Finsupp.smul_single_one, KaehlerDifferential, KaehlerDifferential.derivationQuotKerTotal_apply, conv_rhs, derivationQuotKerTotal_apply, lhom_ext, map_smul, smul_single_one
-/
theorem KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination :
    (KaehlerDifferential.derivationQuotKerTotal R S).liftKaehlerDifferential.comp
        (Finsupp.linearCombination S (KaehlerDifferential.D R S)) =
      Submodule.mkQ _ := by
  apply Finsupp.lhom_ext
  intro a b
  conv_rhs => rw [← Finsupp.smul_single_one a b, map_smul]
  simp [KaehlerDifferential.derivationQuotKerTotal_apply]

/--
theorem `KaehlerDifferential.kerTotal_eq` / 定理 `KaehlerDifferential.kerTotal_eq`

English:
theorem KaehlerDifferential.kerTotal_eq
  proof: by
  apply le_antisymm
  · conv_rhs => rw [← (KaehlerDifferential.kerTotal R S).ker_mkQ]
    rw [← KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination]
    exact LinearMap.ker_le_ker_comp _ _
  · rw [KaehlerDifferential.kerTotal, Submodule.span_le]
    rintro _ ((⟨⟨x, y⟩, rfl⟩ | ⟨

中文:
定理 KaehlerDifferential.kerTotal_eq
  证明: by
  apply le_antisymm
  · conv_rhs => rw [← (KaehlerDifferential.kerTotal R S).ker_mkQ]
    rw [← KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination]
    exact LinearMap.ker_le_ker_comp _ _
  · rw [KaehlerDifferential.kerTotal, Submodule.span_le]
    rintro _ ((⟨⟨x, y⟩, rfl⟩ | ⟨

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination, KaehlerDifferential.kerTotal, LinearMap, LinearMap.ker_le_ker_comp, LinearMap.mem_ker, Submodule, Submodule.span_le, conv_rhs, derivationQuotKerTotal_lift_comp_linearCombination, kerTotal, ker_le_ker_comp, ker_mkQ, le_antisymm, mem_ker, span_le
-/
theorem KaehlerDifferential.kerTotal_eq :
    LinearMap.ker (Finsupp.linearCombination S (KaehlerDifferential.D R S)) =
      KaehlerDifferential.kerTotal R S := by
  apply le_antisymm
  · conv_rhs => rw [← (KaehlerDifferential.kerTotal R S).ker_mkQ]
    rw [← KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination]
    exact LinearMap.ker_le_ker_comp _ _
  · rw [KaehlerDifferential.kerTotal, Submodule.span_le]
    rintro _ ((⟨⟨x, y⟩, rfl⟩ | ⟨⟨x, y⟩, rfl⟩) | ⟨x, rfl⟩) <;> simp [LinearMap.mem_ker]

/--
theorem `KaehlerDifferential.linearCombination_surjective` / 定理 `KaehlerDifferential.linearCombination_surjective`

English:
theorem KaehlerDifferential.linearCombination_surjective
  proof: by
  rw [← LinearMap.range_eq_top]; rw [range_linearCombination]; rw [span_range_derivation]

中文:
定理 KaehlerDifferential.linearCombination_surjective
  证明: by
  rw [← LinearMap.range_eq_top]; rw [range_linearCombination]; rw [span_range_derivation]

Depends on / 依赖: LinearMap, LinearMap.range_eq_top, range_eq_top, range_linearCombination, span_range_derivation
-/
theorem KaehlerDifferential.linearCombination_surjective :
    Function.Surjective (Finsupp.linearCombination S (KaehlerDifferential.D R S)) := by
  rw [← LinearMap.range_eq_top]; rw [range_linearCombination]; rw [span_range_derivation]

/-- `Ω[S⁄R]` is isomorphic to `S` copies of `S` with kernel `KaehlerDifferential.kerTotal`. -/
@[simps!]
/--
Definition of `KaehlerDifferential.quotKerTotalEquiv` / `KaehlerDifferential.quotKerTotalEquiv` 的定义

English:
definition KaehlerDifferential.quotKerTotalEquiv
  signature: :
  body: { (KaehlerDifferential.kerTotal R S).liftQ
      (Finsupp.linearCombination S (KaehlerDifferential.D R S))
      (KaehlerDifferential.kerTotal_eq R S).ge with
    invFun := (KaehlerDifferential.derivationQuotKerTotal R S).liftKaehlerDifferential
    left_inv := by
      intro x
      obtain ⟨x, rfl⟩

中文:
定义 KaehlerDifferential.quotKerTotalEquiv
  签名: :
  定义体: { (KaehlerDifferential.kerTotal R S).liftQ
      (Finsupp.linearCombination S (KaehlerDifferential.D R S))
      (KaehlerDifferential.kerTotal_eq R S).ge with
    invFun := (KaehlerDifferential.derivationQuotKerTotal R S).liftKaehlerDifferential
    left_inv := by
      intro x
      obtain ⟨x, rfl⟩

Depends on / 依赖: Finsupp, Finsupp.linearCombination, KaehlerDifferential, KaehlerDifferential.D, KaehlerDifferential.derivationQuotKerTotal, KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination, KaehlerDifferential.kerTotal, KaehlerDifferential.kerTotal_eq, KaehlerDifferential.linearCombination_surjective, LinearMap, LinearMap.congr_fun, Submodule, Submodule.mkQ_surjective, congr_fun, derivationQuotKerTotal, derivationQuotKerTotal_lift_comp_linearCombination, invFun, kerTotal, kerTotal_eq, left_inv
-/
noncomputable def KaehlerDifferential.quotKerTotalEquiv :
    ((S ->₀ S) ⧸ KaehlerDifferential.kerTotal R S) ≃ₗ[S] Ω[S⁄R] :=
  { (KaehlerDifferential.kerTotal R S).liftQ
      (Finsupp.linearCombination S (KaehlerDifferential.D R S))
      (KaehlerDifferential.kerTotal_eq R S).ge with
    invFun := (KaehlerDifferential.derivationQuotKerTotal R S).liftKaehlerDifferential
    left_inv := by
      intro x
      obtain ⟨x, rfl⟩ := Submodule.mkQ_surjective _ x
      exact
        LinearMap.congr_fun
          (KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination R S :) x
    right_inv := by
      intro x
      obtain ⟨x, rfl⟩ := KaehlerDifferential.linearCombination_surjective R S x
      have := LinearMap.congr_fun
        (KaehlerDifferential.derivationQuotKerTotal_lift_comp_linearCombination R S) x
      rw [LinearMap.comp_apply] at this
      rw [this]
      rfl }

/--
theorem `KaehlerDifferential.quotKerTotalEquiv_symm_comp_D` / 定理 `KaehlerDifferential.quotKerTotalEquiv_symm_comp_D`

English:
theorem KaehlerDifferential.quotKerTotalEquiv_symm_comp_D
  proof: by
  convert! (KaehlerDifferential.derivationQuotKerTotal R S).liftKaehlerDifferential_comp

中文:
定理 KaehlerDifferential.quotKerTotalEquiv_symm_comp_D
  证明: by
  convert! (KaehlerDifferential.derivationQuotKerTotal R S).liftKaehlerDifferential_comp

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.derivationQuotKerTotal, convert, derivationQuotKerTotal, liftKaehlerDifferential_comp
-/
theorem KaehlerDifferential.quotKerTotalEquiv_symm_comp_D :
    (KaehlerDifferential.quotKerTotalEquiv R S).symm.toLinearMap.compDer
        (KaehlerDifferential.D R S) =
      KaehlerDifferential.derivationQuotKerTotal R S := by
  convert! (KaehlerDifferential.derivationQuotKerTotal R S).liftKaehlerDifferential_comp

end Presentation

section ExactSequence

/- We have the commutative diagram
```
A --→ B
↑ ↑
| |
R --→ S
```
-/
variable (A B : Type*) [CommRing A] [CommRing B] [Algebra R A]
variable [Algebra A B] [Algebra S B]

unsuppress_compilation in
-- The map `(A →₀ A) →ₗ[A] (B →₀ B)`
local macro "finsupp_map" : term =>
  `((Finsupp.mapRange.linearMap (Algebra.linearMap A B)).comp
    (Finsupp.lmapDomain A A (algebraMap A B)))

/--
theorem `KaehlerDifferential.kerTotal_map` / 定理 `KaehlerDifferential.kerTotal_map`

English:
theorem KaehlerDifferential.kerTotal_map
  statement: [Algebra R B] [IsScalarTower R A B] [IsScalarTower R S B]
  proof: by
  rw [KaehlerDifferential.kerTotal]; rw [Submodule.map_span]; rw [KaehlerDifferential.kerTotal]; rw [Submodule.restrictScalars_span _ _ h]
  simp_rw [Set.image_union, Submodule.span_union, ← Set.image_univ, Set.image_image, Set.image_univ,
    map_sub, map_add]
  simp only [LinearMap.comp_apply, 

中文:
定理 KaehlerDifferential.kerTotal_map
  结论: [Algebra R B] [IsScalarTower R A B] [IsScalarTower R S B]
  证明: by
  rw [KaehlerDifferential.kerTotal]; rw [Submodule.map_span]; rw [KaehlerDifferential.kerTotal]; rw [Submodule.restrictScalars_span _ _ h]
  simp_rw [Set.image_union, Submodule.span_union, ← Set.image_univ, Set.image_image, Set.image_univ,
    map_sub, map_add]
  simp only [LinearMap.comp_apply, 

Depends on / 依赖: Algebra, Algebra.linearMap_apply, Finsupp, Finsupp.lmapDomain_apply, Finsupp.mapDomain_single, Finsupp.mapRange.linearMap_apply, Finsupp.mapRange_single, KaehlerDifferential, KaehlerDifferential.kerTotal, LinearMap, LinearMap.comp_apply, Set.image_image, Set.image_union, Set.image_univ, Submodule, Submodule.map_span, Submodule.restrictScalars_span, Submodule.span_union, comp_apply, h.prodMap
-/
theorem KaehlerDifferential.kerTotal_map [Algebra R B] [IsScalarTower R A B] [IsScalarTower R S B]
    (h : Function.Surjective (algebraMap A B)) :
    (KaehlerDifferential.kerTotal R A).map finsupp_map ⊔
        Submodule.span A (Set.range fun x : S => .single (algebraMap S B x) (1 : B)) =
      (KaehlerDifferential.kerTotal S B).restrictScalars _ := by
  rw [KaehlerDifferential.kerTotal]; rw [Submodule.map_span]; rw [KaehlerDifferential.kerTotal]; rw [Submodule.restrictScalars_span _ _ h]
  simp_rw [Set.image_union, Submodule.span_union, ← Set.image_univ, Set.image_image, Set.image_univ,
    map_sub, map_add]
  simp only [LinearMap.comp_apply, Finsupp.lmapDomain_apply, Finsupp.mapDomain_single,
    Finsupp.mapRange.linearMap_apply, Finsupp.mapRange_single, Algebra.linearMap_apply,
    map_one, map_add, map_mul]
  simp_rw [sup_assoc, ← (h.prodMap h).range_comp]
  congr!
  rw [sup_eq_right]
  apply Submodule.span_mono
  simp_rw [← IsScalarTower.algebraMap_apply R A B, IsScalarTower.algebraMap_apply R S B]
  exact Set.range_comp_subset_range (algebraMap R S)
    fun x => Finsupp.single (algebraMap S B x) (1 : B)

/--
theorem `KaehlerDifferential.kerTotal_map'` / 定理 `KaehlerDifferential.kerTotal_map'`

English:
theorem KaehlerDifferential.kerTotal_map'
  statement: [Algebra R B]
  proof: by
  rw [Submodule.map_sup]; rw [← kerTotal_map R R A B h]; rw [Submodule.map_span]; rw [← Set.range_comp]
  congr
  ext; simp [IsScalarTower.algebraMap_eq R A B]

中文:
定理 KaehlerDifferential.kerTotal_map'
  结论: [Algebra R B]
  证明: by
  rw [Submodule.map_sup]; rw [← kerTotal_map R R A B h]; rw [Submodule.map_span]; rw [← Set.range_comp]
  congr
  ext; simp [IsScalarTower.algebraMap_eq R A B]

Depends on / 依赖: IsScalarTower, IsScalarTower.algebraMap_eq, Set.range_comp, Submodule, Submodule.map_span, Submodule.map_sup, algebraMap_eq, kerTotal_map, map_span, map_sup, range_comp
-/
theorem KaehlerDifferential.kerTotal_map' [Algebra R B]
    [IsScalarTower R A B] (h : Function.Surjective (algebraMap A B)) :
    (KaehlerDifferential.kerTotal R A ⊔
      Submodule.span A (Set.range fun x => .single (algebraMap R A x) 1)).map finsupp_map =
      (KaehlerDifferential.kerTotal R B).restrictScalars _ := by
  rw [Submodule.map_sup]; rw [← kerTotal_map R R A B h]; rw [Submodule.map_span]; rw [← Set.range_comp]
  congr
  ext; simp [IsScalarTower.algebraMap_eq R A B]

section
variable [Algebra R B] [IsScalarTower R A B] [IsScalarTower R S B] [SMulCommClass S A B]

/--
Definition of `KaehlerDifferential.map` / `KaehlerDifferential.map` 的定义

English:
definition KaehlerDifferential.map
  signature: : Ω[A⁄R] ->ₗ[A] Ω[B⁄S]
  body: Derivation.liftKaehlerDifferential
    (((KaehlerDifferential.D S B).restrictScalars R).compAlgebraMap A)

中文:
定义 KaehlerDifferential.map
  签名: : Ω[A⁄R] ->ₗ[A] Ω[B⁄S]
  定义体: Derivation.liftKaehlerDifferential
    (((KaehlerDifferential.D S B).restrictScalars R).compAlgebraMap A)

Depends on / 依赖: Derivation, Derivation.liftKaehlerDifferential, KaehlerDifferential, KaehlerDifferential.D, compAlgebraMap, liftKaehlerDifferential, restrictScalars
-/
def KaehlerDifferential.map : Ω[A⁄R] ->ₗ[A] Ω[B⁄S] :=
  Derivation.liftKaehlerDifferential
    (((KaehlerDifferential.D S B).restrictScalars R).compAlgebraMap A)

/--
theorem `KaehlerDifferential.map_compDer` / 定理 `KaehlerDifferential.map_compDer`

English:
theorem KaehlerDifferential.map_compDer
  proof: Derivation.liftKaehlerDifferential_comp _

@[simp]

中文:
定理 KaehlerDifferential.map_compDer
  证明: Derivation.liftKaehlerDifferential_comp _

@[simp]

Depends on / 依赖: Derivation, Derivation.liftKaehlerDifferential_comp, liftKaehlerDifferential_comp
-/
theorem KaehlerDifferential.map_compDer :
    (KaehlerDifferential.map R S A B).compDer (KaehlerDifferential.D R A) =
      ((KaehlerDifferential.D S B).restrictScalars R).compAlgebraMap A :=
  Derivation.liftKaehlerDifferential_comp _

@[simp]
/--
theorem `KaehlerDifferential.map_D` / 定理 `KaehlerDifferential.map_D`

English:
theorem KaehlerDifferential.map_D
  given: (x : A)
  proof: Derivation.congr_fun (KaehlerDifferential.map_compDer R S A B) x

中文:
定理 KaehlerDifferential.map_D
  条件: (x : A)
  证明: Derivation.congr_fun (KaehlerDifferential.map_compDer R S A B) x

Depends on / 依赖: Derivation, Derivation.congr_fun, KaehlerDifferential, KaehlerDifferential.map_compDer, congr_fun, map_compDer
-/
theorem KaehlerDifferential.map_D (x : A) :
    KaehlerDifferential.map R S A B (KaehlerDifferential.D R A x) =
      KaehlerDifferential.D S B (algebraMap A B x) :=
  Derivation.congr_fun (KaehlerDifferential.map_compDer R S A B) x

/--
theorem `KaehlerDifferential.ker_map` / 定理 `KaehlerDifferential.ker_map`

English:
theorem KaehlerDifferential.ker_map
  proof: by
  rw [← Submodule.map_comap_eq_of_surjective (linearCombination_surjective R A) (LinearMap.ker _)]
  congr 1
  ext x
  simp only [Submodule.mem_comap, LinearMap.mem_ker, Finsupp.apply_linearCombination, ← kerTotal_eq,
    Submodule.restrictScalars_mem]
  simp only [linearCombination_apply, Functi

中文:
定理 KaehlerDifferential.ker_map
  证明: by
  rw [← Submodule.map_comap_eq_of_surjective (linearCombination_surjective R A) (LinearMap.ker _)]
  congr 1
  ext x
  simp only [Submodule.mem_comap, LinearMap.mem_ker, Finsupp.apply_linearCombination, ← kerTotal_eq,
    Submodule.restrictScalars_mem]
  simp only [linearCombination_apply, Functi

Depends on / 依赖: Finsupp, Finsupp.apply_linearCombination, Finsupp.mapRange.linearMap_apply, Finsupp.sum_mapDomain_index, Finsupp.sum_mapRange_index, Function, Function.comp_apply, LinearMap, LinearMap.coe_comp, LinearMap.ker, LinearMap.mem_ker, Submodule, Submodule.map_comap_eq_of_surjective, Submodule.mem_comap, Submodule.restrictScalars_mem, add_smul, apply_linearCombination, coe_comp, comp_apply, kerTotal_eq
-/
theorem KaehlerDifferential.ker_map :
    LinearMap.ker (KaehlerDifferential.map R S A B) =
      (((kerTotal S B).restrictScalars A).comap finsupp_map).map
        (Finsupp.linearCombination (M := Ω[A⁄R]) A (D R A)) := by
  rw [← Submodule.map_comap_eq_of_surjective (linearCombination_surjective R A) (LinearMap.ker _)]
  congr 1
  ext x
  simp only [Submodule.mem_comap, LinearMap.mem_ker, Finsupp.apply_linearCombination, ← kerTotal_eq,
    Submodule.restrictScalars_mem]
  simp only [linearCombination_apply, Function.comp_apply, LinearMap.coe_comp, lmapDomain_apply,
    Finsupp.mapRange.linearMap_apply]
  rw [Finsupp.sum_mapRange_index]; rw [Finsupp.sum_mapDomain_index]
  · simp
  · simp
  · simp [add_smul]
  · simp

/--
lemma `KaehlerDifferential.ker_map_of_surjective` / 引理 `KaehlerDifferential.ker_map_of_surjective`

English:
lemma KaehlerDifferential.ker_map_of_surjective
  given: (h : Function.Surjective (algebraMap A B))
  proof: by
  rw [ker_map]; rw [← kerTotal_map' R A B h]; rw [Submodule.comap_map_eq]; rw [Submodule.map_sup]; rw [Submodule.map_sup]; rw [← kerTotal_eq]; rw [← Submodule.comap_bot]; rw [Submodule.map_comap_eq_of_surjective (linearCombination_surjective _ _)]; rw [bot_sup_eq]; rw [Submodule.map_span]; rw [← 

中文:
引理 KaehlerDifferential.ker_map_of_surjective
  条件: (h : Function.Surjective (algebraMap A B))
  证明: by
  rw [ker_map]; rw [← kerTotal_map' R A B h]; rw [Submodule.comap_map_eq]; rw [Submodule.map_sup]; rw [Submodule.map_sup]; rw [← kerTotal_eq]; rw [← Submodule.comap_bot]; rw [Submodule.map_comap_eq_of_surjective (linearCombination_surjective _ _)]; rw [bot_sup_eq]; rw [Submodule.map_span]; rw [← 

Depends on / 依赖: Set.range_comp, Submodule, Submodule.comap_bot, Submodule.comap_map_eq, Submodule.map_comap_eq_of_surjective, Submodule.map_span, Submodule.map_sup, Submodule.span_eq_bot, bot_sup_eq, comap_bot, comap_map_eq, convert, kerTotal_eq, kerTotal_map, ker_map, linearCombination_surjective, map_comap_eq_of_surjective, map_span, map_sup, range_comp
-/
lemma KaehlerDifferential.ker_map_of_surjective (h : Function.Surjective (algebraMap A B)) :
    LinearMap.ker (map R R A B) =
      (LinearMap.ker finsupp_map).map (Finsupp.linearCombination A (D R A)) := by
  rw [ker_map]; rw [← kerTotal_map' R A B h]; rw [Submodule.comap_map_eq]; rw [Submodule.map_sup]; rw [Submodule.map_sup]; rw [← kerTotal_eq]; rw [← Submodule.comap_bot]; rw [Submodule.map_comap_eq_of_surjective (linearCombination_surjective _ _)]; rw [bot_sup_eq]; rw [Submodule.map_span]; rw [← Set.range_comp]
  convert! bot_sup_eq _
  rw [Submodule.span_eq_bot]; simp

open IsScalarTower (toAlgHom)

/--
theorem `KaehlerDifferential.map_surjective_of_surjective` / 定理 `KaehlerDifferential.map_surjective_of_surjective`

English:
theorem KaehlerDifferential.map_surjective_of_surjective
  proof: by
  rw [← LinearMap.range_eq_top]; rw [_root_.eq_top_iff]; rw [← @Submodule.restrictScalars_top A B]; rw [← span_range_derivation]; rw [Submodule.restrictScalars_span _ _ h]; rw [Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  obtain ⟨y, rfl⟩ := h x
  rw [← KaehlerDifferential.map_D R S A B]
  exact ⟨_, r

中文:
定理 KaehlerDifferential.map_surjective_of_surjective
  证明: by
  rw [← LinearMap.range_eq_top]; rw [_root_.eq_top_iff]; rw [← @Submodule.restrictScalars_top A B]; rw [← span_range_derivation]; rw [Submodule.restrictScalars_span _ _ h]; rw [Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  obtain ⟨y, rfl⟩ := h x
  rw [← KaehlerDifferential.map_D R S A B]
  exact ⟨_, r

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.map_D, LinearMap, LinearMap.range_eq_top, Submodule, Submodule.restrictScalars_span, Submodule.restrictScalars_top, Submodule.span_le, _root_, _root_.eq_top_iff, eq_top_iff, map_D, range_eq_top, restrictScalars_span, restrictScalars_top, span_le, span_range_derivation
-/
theorem KaehlerDifferential.map_surjective_of_surjective
    (h : Function.Surjective (algebraMap A B)) :
    Function.Surjective (KaehlerDifferential.map R S A B) := by
  rw [← LinearMap.range_eq_top]; rw [_root_.eq_top_iff]; rw [← @Submodule.restrictScalars_top A B]; rw [← span_range_derivation]; rw [Submodule.restrictScalars_span _ _ h]; rw [Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  obtain ⟨y, rfl⟩ := h x
  rw [← KaehlerDifferential.map_D R S A B]
  exact ⟨_, rfl⟩

/--
theorem `KaehlerDifferential.map_surjective` / 定理 `KaehlerDifferential.map_surjective`

English:
theorem KaehlerDifferential.map_surjective
  proof: map_surjective_of_surjective R S B B Function.surjective_id

中文:
定理 KaehlerDifferential.map_surjective
  证明: map_surjective_of_surjective R S B B Function.surjective_id

Depends on / 依赖: Function, Function.surjective_id, map_surjective_of_surjective, surjective_id
-/
theorem KaehlerDifferential.map_surjective :
    Function.Surjective (KaehlerDifferential.map R S B B) :=
  map_surjective_of_surjective R S B B Function.surjective_id

/--
Definition of `KaehlerDifferential.mapBaseChange` / `KaehlerDifferential.mapBaseChange` 的定义

English:
definition KaehlerDifferential.mapBaseChange
  signature: : B otimes[A] Ω[A⁄R] ->ₗ[B] Ω[B⁄R]
  body: (TensorProduct.isBaseChange A Ω[A⁄R] B).lift (KaehlerDifferential.map R R A B)

@[simp]

中文:
定义 KaehlerDifferential.mapBaseChange
  签名: : B otimes[A] Ω[A⁄R] ->ₗ[B] Ω[B⁄R]
  定义体: (TensorProduct.isBaseChange A Ω[A⁄R] B).lift (KaehlerDifferential.map R R A B)

@[simp]

Depends on / 依赖: KaehlerDifferential, KaehlerDifferential.map, TensorProduct, TensorProduct.isBaseChange, isBaseChange
-/
noncomputable def KaehlerDifferential.mapBaseChange : B otimes[A] Ω[A⁄R] ->ₗ[B] Ω[B⁄R] :=
  (TensorProduct.isBaseChange A Ω[A⁄R] B).lift (KaehlerDifferential.map R R A B)

@[simp]
/--
theorem `KaehlerDifferential.mapBaseChange_tmul` / 定理 `KaehlerDifferential.mapBaseChange_tmul`

English:
theorem KaehlerDifferential.mapBaseChange_tmul
  given: (x : B) (y : Ω[A⁄R])
  proof: by
  conv_lhs => rw [← mul_one x, ← smul_eq_mul, ← TensorProduct.smul_tmul', map_smul]
  congr 1
  exact IsBaseChange.lift_eq _ _ _

中文:
定理 KaehlerDifferential.mapBaseChange_tmul
  条件: (x : B) (y : Ω[A⁄R])
  证明: by
  conv_lhs => rw [← mul_one x, ← smul_eq_mul, ← TensorProduct.smul_tmul', map_smul]
  congr 1
  exact IsBaseChange.lift_eq _ _ _

Depends on / 依赖: IsBaseChange, IsBaseChange.lift_eq, TensorProduct, TensorProduct.smul_tmul, conv_lhs, lift_eq, map_smul, mul_one, smul_eq_mul, smul_tmul
-/
theorem KaehlerDifferential.mapBaseChange_tmul (x : B) (y : Ω[A⁄R]) :
    KaehlerDifferential.mapBaseChange R A B (x otimesₜ y) = x • KaehlerDifferential.map R R A B y := by
  conv_lhs => rw [← mul_one x, ← smul_eq_mul, ← TensorProduct.smul_tmul', map_smul]
  congr 1
  exact IsBaseChange.lift_eq _ _ _

/--
lemma `KaehlerDifferential.range_mapBaseChange` / 引理 `KaehlerDifferential.range_mapBaseChange`

English:
lemma KaehlerDifferential.range_mapBaseChange
  proof: by
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    induction x with
    | zero => simp
    | tmul r s =>
      obtain ⟨x, rfl⟩ := linearCombination_surjective _ _ s
      simp only [mapBaseChange_tmul, LinearMap.mem_ker, map_smul]
      induction x using Finsupp.induction_linear
      · simp
      · s

中文:
引理 KaehlerDifferential.range_mapBaseChange
  证明: by
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    induction x with
    | zero => simp
    | tmul r s =>
      obtain ⟨x, rfl⟩ := linearCombination_surjective _ _ s
      simp only [mapBaseChange_tmul, LinearMap.mem_ker, map_smul]
      induction x using Finsupp.induction_linear
      · simp
      · s

Depends on / 依赖: Finsupp, Finsupp.induction_linear, Finsupp.linearCombination, KaehlerDifferential, KaehlerDifferential.ker_map, LinearMap, LinearMap.mem_ker, Submodule, Submodule.comap_id, Submodule.ma, add_mem, comap_id, convert, convert_to, induction_linear, kerTotal, ker_map, le_antisymm, linearCombination, linearCombination_surjective
-/
lemma KaehlerDifferential.range_mapBaseChange :
    LinearMap.range (mapBaseChange R A B) = LinearMap.ker (map R A B B) := by
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    induction x with
    | zero => simp
    | tmul r s =>
      obtain ⟨x, rfl⟩ := linearCombination_surjective _ _ s
      simp only [mapBaseChange_tmul, LinearMap.mem_ker, map_smul]
      induction x using Finsupp.induction_linear
      · simp
      · simp [smul_add, *]
      · simp
    | add => rw [map_add]; exact add_mem ‹_› ‹_›
  · convert_to (kerTotal A B).map (Finsupp.linearCombination B (D R B)) <= _
    · rw [KaehlerDifferential.ker_map]
      congr 1
      convert! Submodule.comap_id _
      · ext; simp
    rw [Submodule.map_le_iff_le_comap]; rw [kerTotal]; rw [Submodule.span_le]
    rintro f ((⟨⟨x, y⟩, rfl⟩ | ⟨⟨x, y⟩, rfl⟩) | ⟨x, rfl⟩)
    · use 0; simp
    · use 0; simp
    · use 1 otimesₜ D _ _ x; simp

/--
lemma `KaehlerDifferential.exact_mapBaseChange_map` / 引理 `KaehlerDifferential.exact_mapBaseChange_map`

English:
lemma KaehlerDifferential.exact_mapBaseChange_map
  proof: SetLike.ext_iff.mp (range_mapBaseChange R A B).symm

中文:
引理 KaehlerDifferential.exact_mapBaseChange_map
  证明: SetLike.ext_iff.mp (range_mapBaseChange R A B).symm

Depends on / 依赖: SetLike, SetLike.ext_iff.mp, ext_iff, range_mapBaseChange
-/
lemma KaehlerDifferential.exact_mapBaseChange_map :
    Function.Exact (mapBaseChange R A B) (map R A B B) :=
  SetLike.ext_iff.mp (range_mapBaseChange R A B).symm

end

/-- The map `I → B ⊗[A] Ω[A⁄R]` where `I = ker(A → B)`. -/
@[simps]
noncomputable
/--
Definition of `KaehlerDifferential.kerToTensor` / `KaehlerDifferential.kerToTensor` 的定义

English:
definition KaehlerDifferential.kerToTensor
  signature: :
  body: 1 otimesₜ D R A x
  map_add' x y := by simp only [Submodule.coe_add, map_add, TensorProduct.tmul_add]
  map_smul' r x := by simp only [SetLike.val_smul, smul_eq_mul, Derivation.leibniz,
    TensorProduct.tmul_add, TensorProduct.tmul_smul, TensorProduct.smul_tmul', ←
    algebraMap_eq_smul_one, RingH

中文:
定义 KaehlerDifferential.kerToTensor
  签名: :
  定义体: 1 otimesₜ D R A x
  map_add' x y := by simp only [Submodule.coe_add, map_add, TensorProduct.tmul_add]
  map_smul' r x := by simp only [SetLike.val_smul, smul_eq_mul, Derivation.leibniz,
    TensorProduct.tmul_add, TensorProduct.tmul_smul, TensorProduct.smul_tmul', ←
    algebraMap_eq_smul_one, RingH
-/
def KaehlerDifferential.kerToTensor :
    RingHom.ker (algebraMap A B) ->ₗ[A] B otimes[A] Ω[A⁄R] where
  toFun x := 1 otimesₜ D R A x
  map_add' x y := by simp only [Submodule.coe_add, map_add, TensorProduct.tmul_add]
  map_smul' r x := by simp only [SetLike.val_smul, smul_eq_mul, Derivation.leibniz,
    TensorProduct.tmul_add, TensorProduct.tmul_smul, TensorProduct.smul_tmul', ←
    algebraMap_eq_smul_one, RingHom.mem_ker.mp x.prop, TensorProduct.zero_tmul, add_zero,
    RingHom.id_apply]

/-- The map `I/I² → B ⊗[A] Ω[A⁄R]` where `I = ker(A → B)`. -/
noncomputable
/--
Definition of `KaehlerDifferential.kerCotangentToTensor` / `KaehlerDifferential.kerCotangentToTensor` 的定义

English:
definition KaehlerDifferential.kerCotangentToTensor
  signature: :
  body: Submodule.liftQ _ (kerToTensor R A B) by
    rw [Submodule.smul_eq_map₂]
    apply iSup_le_iff.mpr
    simp only [Submodule.map_le_iff_le_comap, Subtype.forall]
    rintro x hx y -
    simp only [Submodule.mem_comap, LinearMap.lsmul_apply, LinearMap.mem_ker, map_smul,
      kerToTensor_apply, Tensor

中文:
定义 KaehlerDifferential.kerCotangentToTensor
  签名: :
  定义体: Submodule.liftQ _ (kerToTensor R A B) by
    rw [Submodule.smul_eq_map₂]
    apply iSup_le_iff.mpr
    simp only [Submodule.map_le_iff_le_comap, Subtype.forall]
    rintro x hx y -
    simp only [Submodule.mem_comap, LinearMap.lsmul_apply, LinearMap.mem_ker, map_smul,
      kerToTensor_apply, Tensor

Depends on / 依赖: LinearMap, LinearMap.lsmul_apply, LinearMap.mem_ker, RingHom, RingHom.mem_ker.mp, Submodule, Submodule.liftQ, Submodule.map_le_iff_le_comap, Submodule.mem_comap, Submodule.smul_eq_map, Subtype, Subtype.forall, TensorProduct, TensorProduct.smul_tmul, TensorProduct.zero_tmul, algebraMap_eq_smul_one, iSup_le_iff, iSup_le_iff.mpr, kerToTensor, kerToTensor_apply
-/
def KaehlerDifferential.kerCotangentToTensor :
    (RingHom.ker (algebraMap A B)).Cotangent ->ₗ[A] B otimes[A] Ω[A⁄R] :=
Submodule.liftQ _ (kerToTensor R A B) by
    rw [Submodule.smul_eq_map₂]
    apply iSup_le_iff.mpr
    simp only [Submodule.map_le_iff_le_comap, Subtype.forall]
    rintro x hx y -
    simp only [Submodule.mem_comap, LinearMap.lsmul_apply, LinearMap.mem_ker, map_smul,
      kerToTensor_apply, TensorProduct.smul_tmul', ← algebraMap_eq_smul_one,
      RingHom.mem_ker.mp hx, TensorProduct.zero_tmul]

@[simp]
/--
lemma `KaehlerDifferential.kerCotangentToTensor_toCotangent` / 引理 `KaehlerDifferential.kerCotangentToTensor_toCotangent`

English:
lemma KaehlerDifferential.kerCotangentToTensor_toCotangent
  given: (x)
  proof: rfl

中文:
引理 KaehlerDifferential.kerCotangentToTensor_toCotangent
  条件: (x)
  证明: rfl
-/
lemma KaehlerDifferential.kerCotangentToTensor_toCotangent (x) :
    kerCotangentToTensor R A B (Ideal.toCotangent _ x) = 1 otimesₜ D _ _ x.1 := rfl

variable [Algebra R B] [IsScalarTower R A B]

/--
theorem `KaehlerDifferential.range_kerCotangentToTensor` / 定理 `KaehlerDifferential.range_kerCotangentToTensor`

English:
theorem KaehlerDifferential.range_kerCotangentToTensor
  proof: by
  classical
  ext x
  constructor
  · rintro ⟨x, rfl⟩
    obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective _ x
    simp only [kerCotangentToTensor_toCotangent, Submodule.restrictScalars_mem, LinearMap.mem_ker,
      mapBaseChange_tmul, map_D, RingHom.mem_ker.mp x.2, map_zero, smul_zero]
  · intro 

中文:
定理 KaehlerDifferential.range_kerCotangentToTensor
  证明: by
  classical
  ext x
  constructor
  · rintro ⟨x, rfl⟩
    obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective _ x
    simp only [kerCotangentToTensor_toCotangent, Submodule.restrictScalars_mem, LinearMap.mem_ker,
      mapBaseChange_tmul, map_D, RingHom.mem_ker.mp x.2, map_zero, smul_zero]
  · intro 

Depends on / 依赖: Algebra, Algebra.linearMap, Ideal.toCotangent_surjective, KaehlerDifferential, KaehlerDifferential.map, LinearMap, LinearMap.ker, LinearMap.mem_ker, LinearMap.rTensor_surjective, RingHom, RingHom.mem_ker.mp, Submodule, Submodule.restrictScalars_mem, TensorProduct, TensorProduct.lid, classical, kerCotangentToTensor_toCotangent, linearMap, mapBaseChange_tmul, map_D
-/
theorem KaehlerDifferential.range_kerCotangentToTensor
    (h : Function.Surjective (algebraMap A B)) :
    LinearMap.range (kerCotangentToTensor R A B) =
      (LinearMap.ker (KaehlerDifferential.mapBaseChange R A B)).restrictScalars A := by
  classical
  ext x
  constructor
  · rintro ⟨x, rfl⟩
    obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective _ x
    simp only [kerCotangentToTensor_toCotangent, Submodule.restrictScalars_mem, LinearMap.mem_ker,
      mapBaseChange_tmul, map_D, RingHom.mem_ker.mp x.2, map_zero, smul_zero]
  · intro hx
    obtain ⟨x, rfl⟩ := LinearMap.rTensor_surjective Ω[A⁄R] (g := Algebra.linearMap A B) h x
    obtain ⟨x, rfl⟩ := (TensorProduct.lid _ _).symm.surjective x
    replace hx : x in LinearMap.ker (KaehlerDifferential.map R R A B) := by simpa using hx
    rw [KaehlerDifferential.ker_map_of_surjective R A B h] at hx
    obtain ⟨x, hx, rfl⟩ := hx
    simp only [TensorProduct.lid_symm_apply, LinearMap.rTensor_tmul,
      Algebra.linearMap_apply, map_one]
    rw [← Finsupp.sum_single x]; rw [Finsupp.sum]; rw [← Finset.sum_fiberwise_of_maps_to
      (fun _ => Finset.mem_image_of_mem (algebraMap A B))]
    simp only [map_sum (s := x.support.image (algebraMap A B)),
      TensorProduct.tmul_sum]
    apply sum_mem
    intro c _
    simp only [LinearMap.mem_range]
    simp only [map_sum, Finsupp.linearCombination_single]
    have : ∑ i in x.support with algebraMap A B i = c, x i in RingHom.ker (algebraMap A B) := by
      simpa [Finsupp.mapDomain, Finsupp.sum, Finsupp.finsetSum_apply, RingHom.mem_ker,
        Finsupp.single_apply, ← Finset.sum_filter] using DFunLike.congr_fun hx c
    obtain ⟨a, ha⟩ := h c
    use ∑ i in {i in x.support | algebraMap A B i = c}.attach, x i • Ideal.toCotangent _ ⟨i - a, ?_⟩
    · simp only [map_sum, LinearMapClass.map_smul, kerCotangentToTensor_toCotangent, map_sub]
      simp_rw [← TensorProduct.tmul_smul]
      -- TODO: was `simp [kerCotangentToTensor_toCotangent, RingHom.mem_ker.mp x.2]` and very slow
      -- (https://github.com/leanprover-community/mathlib4/issues/19751)
      simp only [smul_sub, TensorProduct.tmul_sub, Finset.sum_sub_distrib, ← TensorProduct.tmul_sum,
        ← Finset.sum_smul, Finset.sum_attach, sub_eq_self,
        Finset.sum_attach (f := fun i => x i • KaehlerDifferential.D R A i)]
      rw [← TensorProduct.smul_tmul]; rw [← Algebra.algebraMap_eq_smul_one]; rw [RingHom.mem_ker.mp this]; rw [TensorProduct.zero_tmul]
    · have : x i != 0 ∧ algebraMap A B i = c := by
        convert! i.prop
        simp_rw [Finset.mem_filter, Finsupp.mem_support_iff]
      simp [RingHom.mem_ker, ha, this.2]

/--
theorem `KaehlerDifferential.exact_kerCotangentToTensor_mapBaseChange` / 定理 `KaehlerDifferential.exact_kerCotangentToTensor_mapBaseChange`

English:
theorem KaehlerDifferential.exact_kerCotangentToTensor_mapBaseChange
  proof: SetLike.ext_iff.mp (range_kerCotangentToTensor R A B h).symm

中文:
定理 KaehlerDifferential.exact_kerCotangentToTensor_mapBaseChange
  证明: SetLike.ext_iff.mp (range_kerCotangentToTensor R A B h).symm

Depends on / 依赖: SetLike, SetLike.ext_iff.mp, ext_iff, range_kerCotangentToTensor
-/
theorem KaehlerDifferential.exact_kerCotangentToTensor_mapBaseChange
    (h : Function.Surjective (algebraMap A B)) :
    Function.Exact (kerCotangentToTensor R A B) (KaehlerDifferential.mapBaseChange R A B) :=
  SetLike.ext_iff.mp (range_kerCotangentToTensor R A B h).symm

/--
lemma `KaehlerDifferential.mapBaseChange_surjective` / 引理 `KaehlerDifferential.mapBaseChange_surjective`

English:
lemma KaehlerDifferential.mapBaseChange_surjective
  proof: by
  have := subsingleton_of_surjective A B h
  rw [← LinearMap.range_eq_top]; rw [range_mapBaseChange]; rw [← top_le_iff]
  exact fun x _ => Subsingleton.elim _ _

中文:
引理 KaehlerDifferential.mapBaseChange_surjective
  证明: by
  have := subsingleton_of_surjective A B h
  rw [← LinearMap.range_eq_top]; rw [range_mapBaseChange]; rw [← top_le_iff]
  exact fun x _ => Subsingleton.elim _ _

Depends on / 依赖: LinearMap, LinearMap.range_eq_top, Subsingleton, Subsingleton.elim, range_eq_top, range_mapBaseChange, subsingleton_of_surjective, top_le_iff
-/
lemma KaehlerDifferential.mapBaseChange_surjective
    (h : Function.Surjective (algebraMap A B)) :
    Function.Surjective (KaehlerDifferential.mapBaseChange R A B) := by
  have := subsingleton_of_surjective A B h
  rw [← LinearMap.range_eq_top]; rw [range_mapBaseChange]; rw [← top_le_iff]
  exact fun x _ => Subsingleton.elim _ _

end ExactSequence

end KaehlerDifferential
