/-
Copyright (c) 2026 Antoine Chambert-Loir & María Inés de Frutos—Fernández. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Antoine Chambert-Loir, María Inés de Frutos—Fernández
-/
module

public import Mathlib.Algebra.MvPolynomial.Eval
public import Mathlib.RingTheory.Congruence.Hom
public import Mathlib.RingTheory.Congruence.BigOperators
public import Mathlib.RingTheory.DividedPowers.Basic

/-!
# The universal divided power algebra

Let `R` be a (commutative) semiring and `M` be an `R`-module. In this file we define `Γ_R(M)`,
the universal divided power algebra of `M`, as the ring quotient of the polynomial ring
in the variables `ℕ × M` by the relation `DividedPowerAlgebra.Rel`.

`DividedPowerAlgebra R M` satisfies a weak universal property for morphisms to rings with
divided powers (`DividedPowerAlgebra.lift`).

## Main definitions

* `DividedPowerAlgebra.Rel`: the type coding the basic relations that will give rise to the
  divided power algebra.

* `DividedPowerAlgebra R M`: the universal divided power algebra of the `R`-module `M`,
  defined as `RingCon.Quotient` of `DividedPowerAlgebra.ringCon R M`.

* `DividedPowerAlgebra.dp R n m`: for `n : ℕ` and `m : M`, this is the equivalence class of
  `MvPolynomial.X (⟨n, m⟩)` in `DividedPowerAlgebra R M`.

  When that algebra is endowed with its canonical divided power structure (to be defined),
  the image of `MvPolynomial.X (n, m)`, for any `n : ℕ` and `m : M`, is equal to
  the `n`th divided power of the image of `m`.

  The API will be setup so that it is never (never say never…) necessary to lift to `MvPolynomial`.

* `DividedPowerAlgebra.lift`: the weak universal property of `DividedPowerAlgebra R M`.

* `DividedPowerAlgebra.map`: the functoriality map between divided power algebras
  associated with a linear map of the underlying modules.
  Given an `R`-algebra `S`, an `S`-module `N` and an `R`-linear map `f : M →ₗ[R] N`,
  this is the map `DividedPowerAlgebra R M →ₐ[R] DividedPowerAlgebra S N`
  sending `dp R n m` to `dp S n (f m)`.

## References

* [P. Berthelot (1974), *Cohomologie cristalline des schémas de
  caractéristique $p$ > 0*][Berthelot-1974]

* [P. Berthelot and A. Ogus (1978), *Notes on crystalline
  cohomology*][BerthelotOgus-1978]

* [N. Roby (1963), *Lois polynomes et lois formelles en théorie des
  modules*][Roby-1963]

* [N. Roby (1965), *Les algèbres à puissances dividées*][Roby-1965]

## TODO

* Show in upcoming files that `DividedPowerAlgebra R M` has divided powers.


-/

@[expose] public section

noncomputable section

open Finset Ideal MvPolynomial

variable (α R M : Type*) [CommSemiring R] [AddCommMonoid M] [Module R M]

namespace DividedPowerAlgebra

/-- The type coding the basic relations that will give rise to the divided power algebra.
  The class of `MvPolynomial.X (n, a)` will be equal to `dpow n a`, for `a ∈ M`. -/
/-
**DividedPowerAlgebra.Rel** 是 Mathlib 中的一个归纳类型，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：(R : Type u_2) →   (M : Type u_3) →     [inst : CommSemiring R] →       [i
nst_1 : AddCommMonoid M] → [_root_.Module R M] → MvPolynomial (ℕ × M) R → MvPoly
nomial (ℕ × M) R → Prop
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The type coding the basic relations that will give rise to the divided power alg
ebra.
  The class of `MvPolynomial.X (n, a)` will be equal to `dpow n a`, for `a ∈ M`.
-/
inductive Rel : MvPolynomial (ℕ × M) R → MvPolynomial (ℕ × M) R → Prop
  | rfl_zero : Rel 0 0 -- Needed for technical reasons.
  | zero {a : M} : Rel (X (0, a)) 1
  | smul {r : R} {n : ℕ} {a : M} : Rel (X (n, r • a)) (r ^ n • X (n, a))
  | mul {m n : ℕ} {a : M} : Rel (X (m, a) * X (n, a)) (Nat.choose (m + n) m • X (m + n, a))
  | add {n : ℕ} {a b : M} :
    Rel (X (n, a + b)) ((Finset.antidiagonal n).sum fun k ↦ X (k.1, a) * X (k.2, b))

/-- The ideal of `MvPolynomial (ℕ × M) R` generated by `Rel`. -/
/-
**DividedPowerAlgebra.RelI** 是 Mathlib 中的一个定义，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：RelI : Ideal (MvPolynomial (Nat × M) R)
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The ideal of `MvPolynomial (ℕ × M) R` generated by `Rel`.
-/
def RelI : Ideal (MvPolynomial (ℕ × M) R) := ofRel (DividedPowerAlgebra.Rel R M)

/-- The congruence generated by `Rel`. -/
/-
**DividedPowerAlgebra.ringCon** 是 Mathlib 中的一个定义，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：ringCon : RingCon (MvPolynomial (Nat × M) R)
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The congruence generated by `Rel`.
-/
def ringCon : RingCon (MvPolynomial (ℕ × M) R) := ringConGen (DividedPowerAlgebra.Rel R M)

end DividedPowerAlgebra

/-- The divided power algebra of a module M is defined as the ring quotient of the polynomial ring
  in the variables `ℕ × M` by the ring relation defined by `DividedPowerAlgebra.Rel`.
  We will later show that that `DividedPowerAlgebra R M` has divided powers.
  It satisfies a weak universal property for morphisms to rings with divided powers. -/
/-
**DividedPowerAlgebra** 是 Mathlib 中的一个定义，位于命名空间 ``。
形式化陈述：(R : Type u_2) →   (M : Type u_3) → [inst : CommSemiring R] → [inst_1 : Ad
dCommMonoid M] → [_root_.Module R M] → Type (max u_2 u_3)
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The divided power algebra of a module M is defined as the ring quotient of the p
olynomial ring
  in the variables `ℕ × M` by the ring relation defined by `DividedPowerAlgebra.
Rel`.
  We will later show that that `DividedPowerAlgebra R M` has divided powers.
  It satisfies a weak universal property for morphisms to rings with divided pow
ers.
-/
abbrev DividedPowerAlgebra := DividedPowerAlgebra.ringCon R M |>.Quotient

namespace DividedPowerAlgebra

open MvPolynomial

variable {R M}

/-
**DividedPowerAlgebra.mkAlgHom_surjective** 是 Mathlib 中的一个引理，位于命名空间 `DividedPowe
rAlgebra`。
形式化陈述：mkAlgHom_surjective : Function.Surjective (RingCon.mkₐ R (ringCon R M))
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Quotient.mk_surjective`：Quotient.mk_surjective {s : Setoid α} : Function
.Surjective (Quotient.mk s)
-/
lemma mkAlgHom_surjective : Function.Surjective (RingCon.mkₐ R (ringCon R M)) :=
  Quotient.mk_surjective

@[simp]
/-
**DividedPowerAlgebra.coe_C** 是 Mathlib 中的一个引理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：coe_C (a : R) : ↑(C (σ
参数：a : R。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `MvPolynomial.algebraMap_eq`：algebraMap_eq : algebraMap R (MvPolynomial σ
 R) = C
· 使用定理 `RingCon.coe_algebraMap`：coe_algebraMap (c : RingCon R) (s : α) : (algebr
aMap α R s : c.Quotient) = algebraMap α c.Quotient s
-/
lemma coe_C (a : R) :
    ↑(C (σ := ℕ × M) a) = algebraMap R (DividedPowerAlgebra R M) a := by
  rw [← MvPolynomial.algebraMap_eq, RingCon.coe_algebraMap]

@[deprecated coe_C (since := "2026-06-19")]
/-
**DividedPowerAlgebra.mkAlgHom_C** 是 Mathlib 中的一个引理，位于命名空间 `DividedPowerAlgebra`
。
形式化陈述：mkAlgHom_C (a : R) : RingCon.mkₐ R (ringCon R M) (C a) = algebraMap R (Div
idedPowerAlgebra R M) a
参数：a : R。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `MvPolynomial.algebraMap_eq`：algebraMap_eq : algebraMap R (MvPolynomial σ
 R) = C
· 使用定理 `AlgHom.commutes`：commutes (r : R) : φ (algebraMap R A r) = algebraMap R 
B r
-/
lemma mkAlgHom_C (a : R) :
    RingCon.mkₐ R (ringCon R M) (C a) = algebraMap R (DividedPowerAlgebra R M) a := by
  rw [← MvPolynomial.algebraMap_eq, AlgHom.commutes]

@[deprecated coe_C (since := "2026-06-19")]
/-
**DividedPowerAlgebra.mkRingHom_C** 是 Mathlib 中的一个引理，位于命名空间 `DividedPowerAlgebra
`。
形式化陈述：mkRingHom_C (a : R) : RingCon.mk' (ringCon R M) (C a) = algebraMap R (Divi
dedPowerAlgebra R M) a
参数：a : R。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `DividedPowerAlgebra.mkAlgHom_C`：mkAlgHom_C (a : R) : RingCon.mkₐ R (ring
Con R M) (C a) = algebraMap R (DividedPowerAlgebra R M) a
-/
lemma mkRingHom_C (a : R) :
    RingCon.mk' (ringCon R M) (C a) = algebraMap R (DividedPowerAlgebra R M) a :=
  mkAlgHom_C _

variable (R) in
/-- `dp R n m` is the equivalence class of `X (⟨n, m⟩)` in `DividedPowerAlgebra R M`. -/
/-
**DividedPowerAlgebra.dp** 是 Mathlib 中的一个定义，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：dp (n : Nat) (m : M) : DividedPowerAlgebra R M
参数：n : Nat；m : M。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
`dp R n m` is the equivalence class of `X (⟨n, m⟩)` in `DividedPowerAlgebra R M`
.
-/
def dp (n : ℕ) (m : M) : DividedPowerAlgebra R M := ↑(X (n, m) : MvPolynomial (ℕ × M) R)
/-
**DividedPowerAlgebra.dp_def** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：dp_def (n : Nat) (m : M) : dp R n m = ↑(X (n, m) : MvPolynomial (Nat × M) 
R)
参数：n : Nat；m : M。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem dp_def (n : ℕ) (m : M) :
  dp R n m = ↑(X (n, m) : MvPolynomial (ℕ × M) R) := rfl
/-
**DividedPowerAlgebra.induction_on'** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgeb
ra`。
形式化陈述：∀ {R : Type u_2} {M : Type u_3} [inst : CommSemiring R] [inst_1 : AddCommM
onoid M] [inst_2 : _root_.Module R M]   {P : DividedPowerAlgebra R M → Prop} (f 
: DividedPowerAlgebra R M),   (∀ (a : R), P ↑(MvPolynomial.C a)) →     (∀ (f g :
 DividedPowerAlgebra R M), P f → P g → P (f + g)) →       (∀ (f : DividedPowerAl
gebra R M) (n : ℕ) (m : M), P f → P (f * DividedPowerAlgebra.dp R n m)) → P f
参数：f : DividedPowerAlgebra R M；∀ (a : R), P ↑(MvPolynomial.C a)；∀ (f g : Divided
PowerAlgebra R M), P f → P g → P (f + g)；∀ (f : DividedPowerAlgebra R M) (n : ℕ)
 (m : M), P f → P (f * DividedPowerAlgebra.dp R n m)。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Quot.induction_on`：∀ {α : Sort u_4} {r : α → α → Prop} {β : Quot r → Pro
p} (q : Quot r), (∀ (a : α), β (Quot.mk r a)) → β q
· 使用定理 `MvPolynomial.induction_on`：induction_on {motive : MvPolynomial σ R -> Pr
op} (p : MvPolynomial σ R) (C : forall a, motive (C a)) (add : forall p q, motiv
e p -> motive q…
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `RingCon.coe_add`：coe_add (x y : R) : (↑(x + y) : c.Quotient) = ↑x + ↑y
· 使用定理 `RingCon.coe_mul`：coe_mul (x y : R) : (↑(x * y) : c.Quotient) = ↑x * ↑y
-/
protected theorem induction_on' {P : DividedPowerAlgebra R M → Prop} (f : DividedPowerAlgebra R M)
    (h_C : ∀ a, P (C a : MvPolynomial (ℕ × M) R)) (h_add : ∀ f g, P f → P g → P (f + g))
    (h_dp : ∀ (f : DividedPowerAlgebra R M) (n : ℕ) (m : M), P f → P (f * dp R n m)) : P f := by
  induction f using Quot.induction_on with | _ F
  dsimp
  induction F using MvPolynomial.induction_on with
  | C a => exact h_C a
  | add g1 g2 hg1 hg2 =>
    rw [RingCon.coe_add]
    exact h_add _ _ hg1 hg2
  | mul_X g nm h =>
    rw [RingCon.coe_mul]
    exact h_dp _ _ _ h

@[elab_as_elim]
/-
**DividedPowerAlgebra.induction_on** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebr
a`。
形式化陈述：∀ {R : Type u_2} {M : Type u_3} [inst : CommSemiring R] [inst_1 : AddCommM
onoid M] [inst_2 : _root_.Module R M]   {P : DividedPowerAlgebra R M → Prop} (f 
: DividedPowerAlgebra R M),   (∀ (a : R), P ((algebraMap R (DividedPowerAlgebra 
R M)) a)) →     (∀ (f g : DividedPowerAlgebra R M), P f → P g → P (f + g)) →    
   (∀ (f : DividedPowerAlgebra R M) (n : ℕ) (m : M), P f → P (f * DividedPowerAl
gebra.dp R n m)) → P f
参数：f : DividedPowerAlgebra R M；∀ (a : R), P ((algebraMap R (DividedPowerAlgebra 
R M)) a)；∀ (f g : DividedPowerAlgebra R M), P f → P g → P (f + g)；∀ (f : Divided
PowerAlgebra R M) (n : ℕ) (m : M), P f → P (f * DividedPowerAlgebra.dp R n m)。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `DividedPowerAlgebra.induction_on'`：∀ {R : Type u_2} {M : Type u_3} [inst
 : CommSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   {P 
: DividedPowerAlgebra R…
-/
protected theorem induction_on {P : DividedPowerAlgebra R M → Prop} (f : DividedPowerAlgebra R M)
    (C : ∀ a, P (algebraMap R _ a)) (add : ∀ f g, P f → P g → P (f + g))
    (dp : ∀ (f : DividedPowerAlgebra R M) (n : ℕ) (m : M), P f → P (f * dp R n m)) : P f :=
  DividedPowerAlgebra.induction_on' f C add dp
/-
**DividedPowerAlgebra.dp_zero** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：dp_zero {m : M} : dp R 0 m = 1
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.dp_def`：dp_def (n : Nat) (m : M) : dp R n m = ↑(X (n
, m) : MvPolynomial (Nat × M) R)
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `RingCon.coe_one`：coe_one : (↑(1 : R) : c.Quotient) = 1
· 使用定理 `Quotient.sound`：∀ {α : Sort u} {s : Setoid α} {a b : α}, a ≈ b → ⟦a⟧ = ⟦
b⟧
· 使用定理 `RingCon.le_ringConGen`：le_ringConGen {r : R -> R -> Prop} : r <= ⇑(ringC
onGen r)
-/
theorem dp_zero {m : M} : dp R 0 m = 1 := by
  rw [dp_def, ← RingCon.coe_one]
  exact Quotient.sound <| RingCon.le_ringConGen _ _ Rel.zero
/-
**DividedPowerAlgebra.dp_smul** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：dp_smul {r : R} {n : Nat} {m : M} : dp R n (r • m) = r ^ n • dp R n m
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `IsScalarTower.right`：∀ {R : Type u} {A : Type w} [inst : CommSemiring R]
 [inst_1 : Semiring A] [inst_2 : Algebra R A], IsScalarTower R A A
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.dp_def`：dp_def (n : Nat) (m : M) : dp R n m = ↑(X (n
, m) : MvPolynomial (Nat × M) R)
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `RingCon.coe_smul`：coe_smul (a : α) (x : R) : (↑(a • x) : c.Quotient) = a
 • (x : c.Quotient)
· 使用定理 `Quotient.sound`：∀ {α : Sort u} {s : Setoid α} {a b : α}, a ≈ b → ⟦a⟧ = ⟦
b⟧
· 使用定理 `RingCon.le_ringConGen`：le_ringConGen {r : R -> R -> Prop} : r <= ⇑(ringC
onGen r)
-/
theorem dp_smul {r : R} {n : ℕ} {m : M} : dp R n (r • m) = r ^ n • dp R n m := by
  rw [dp_def, dp_def, ← RingCon.coe_smul]
  exact Quotient.sound <| RingCon.le_ringConGen _ _ Rel.smul
/-
**DividedPowerAlgebra.dp_null** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：dp_null {n : Nat} : dp R n (0 : M) = if n = 0 then 1 else 0
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Nat.eq_zero_or_pos`：∀ (n : ℕ), n = 0 ∨ n > 0
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `if_pos`：∀ {c : Prop} {h : Decidable c}, c → ∀ {α : Sort u} {t e : α}, (i
f c then t else e) = t
· 使用定理 `DividedPowerAlgebra.dp_zero`：dp_zero {m : M} : dp R 0 m = 1
· 使用定理 `if_neg`：∀ {c : Prop} {h : Decidable c}, ¬c → ∀ {α : Sort u} {t e : α}, (
if c then t else e) = e
· 使用定理 `ne_of_gt`：∀ {α : Type u_1} [inst : Preorder α] {a b : α}, b < a → a ≠ b
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `zero_smul`：zero_smul (m : A) : (0 : M₀) • m = 0
· 使用定理 `IsScalarTower.right`：∀ {R : Type u} {A : Type w} [inst : CommSemiring R]
 [inst_1 : Semiring A] [inst_2 : Algebra R A], IsScalarTower R A A
· 使用定理 `DividedPowerAlgebra.dp_smul`：dp_smul {r : R} {n : Nat} {m : M} : dp R n 
(r • m) = r ^ n • dp R n m
· 使用定理 `zero_pow`：zero_pow {b : Nat} (_ : 0 < b) : (0 : R) ^ b = 0
· 使用定理 `Iff.mp`：∀ {a b : Prop}, (a ↔ b) → a → b
· 使用定理 `Nat.pos_iff_ne_zero`：∀ {n : ℕ}, 0 < n ↔ n ≠ 0
-/
theorem dp_null {n : ℕ} : dp R n (0 : M) = if n = 0 then 1 else 0 := by
  cases Nat.eq_zero_or_pos n with
  | inl hn =>
    rw [if_pos hn, hn, dp_zero]
  | inr hn =>
    rw [if_neg (ne_of_gt hn), ← zero_smul R (0 : M), dp_smul]
    rw [zero_pow (Nat.pos_iff_ne_zero.mp hn), zero_smul]
/-
**DividedPowerAlgebra.dp_null_of_ne_zero** 是 Mathlib 中的一个定理，位于命名空间 `DividedPower
Algebra`。
形式化陈述：dp_null_of_ne_zero {n : Nat} (hn : n != 0) : dp R n (0 : M) = 0
参数：hn : n != 0。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.dp_null`：dp_null {n : Nat} : dp R n (0 : M) = if n =
 0 then 1 else 0
· 使用定理 `if_neg`：∀ {c : Prop} {h : Decidable c}, ¬c → ∀ {α : Sort u} {t e : α}, (
if c then t else e) = e
-/
theorem dp_null_of_ne_zero {n : ℕ} (hn : n ≠ 0) : dp R n (0 : M) = 0 := by
  rw [dp_null, if_neg hn]
/-
**DividedPowerAlgebra.dp_mul** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：dp_mul {n p : Nat} {m : M} : dp R n m * dp R p m = (n + p).choose n • dp R
 (n + p) m
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Quotient.sound`：∀ {α : Sort u} {s : Setoid α} {a b : α}, a ≈ b → ⟦a⟧ = ⟦
b⟧
· 使用定理 `RingCon.le_ringConGen`：le_ringConGen {r : R -> R -> Prop} : r <= ⇑(ringC
onGen r)
-/
theorem dp_mul {n p : ℕ} {m : M} :
    dp R n m * dp R p m = (n + p).choose n • dp R (n + p) m := by
  simp only [dp_def, ← RingCon.coe_mul, ← RingCon.coe_nsmul]
  exact Quotient.sound <| RingCon.le_ringConGen _ _ Rel.mul
/-
**DividedPowerAlgebra.dp_add** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：dp_add {n : Nat} {x y : M} : dp R n (x + y) = (antidiagonal n).sum fun k =
> dp R k.1 x * dp R k.2 y
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Quotient.sound`：∀ {α : Sort u} {s : Setoid α} {a b : α}, a ≈ b → ⟦a⟧ = ⟦
b⟧
· 使用定理 `RingCon.le_ringConGen`：le_ringConGen {r : R -> R -> Prop} : r <= ⇑(ringC
onGen r)
-/
theorem dp_add {n : ℕ} {x y : M} :
    dp R n (x + y) = (antidiagonal n).sum fun k ↦ dp R k.1 x * dp R k.2 y := by
  simp_rw [dp_def, ← RingCon.coe_mul, ← RingCon.coe_finsetSum]
  exact Quotient.sound <| RingCon.le_ringConGen _ _ Rel.add
/-
**DividedPowerAlgebra.dp_sum** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：dp_sum {ι : Type*} [DecidableEq ι] (s : Finset ι) (q : Nat) (x : ι -> M) :
 dp R q (s.sum x) = (Finset.sym s q).sum fun k => s.prod fun i => dp R (Multiset
.count i k) (x i)
参数：s : Finset ι；q : Nat；x : ι -> M。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `DividedPowers.dpow_sum'`：dpow_sum' {M : Type*} [AddCommMonoid M] {I : Ad
dSubmonoid M} (dpow : Nat -> M -> A) (dpow_zero : forall {x}, x in I -> dpow 0 x
 = 1) (dpow_a…
· 使用定理 `DividedPowerAlgebra.dp_zero`：dp_zero {m : M} : dp R 0 m = 1
· 使用定理 `DividedPowerAlgebra.dp_add`：dp_add {n : Nat} {x y : M} : dp R n (x + y) 
= (antidiagonal n).sum fun k => dp R k.1 x * dp R k.2 y
· 使用定理 `DividedPowerAlgebra.dp_null_of_ne_zero`：dp_null_of_ne_zero {n : Nat} (hn
 : n != 0) : dp R n (0 : M) = 0
· 使用定理 `trivial`：True
-/
theorem dp_sum {ι : Type*} [DecidableEq ι] (s : Finset ι) (q : ℕ) (x : ι → M) :
    dp R q (s.sum x) =
      (Finset.sym s q).sum fun k ↦ s.prod fun i ↦ dp R (Multiset.count i k) (x i) :=
  DividedPowers.dpow_sum' (I := ⊤) _ (fun _ ↦ dp_zero)
    (fun _ _ ↦ dp_add) dp_null_of_ne_zero (fun _ _ ↦ trivial)
/-
**DividedPowerAlgebra.dp_sum_smul** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra
`。
形式化陈述：dp_sum_smul {ι : Type*} [DecidableEq ι] (s : Finset ι) (q : Nat) (a : ι ->
 R) (x : ι -> M) : dp R q (s.sum fun i => a i • x i) = (Finset.sym s q).sum fun 
k => (s.prod fun i => a i ^ Multiset.count i k) • s.prod fun i => dp R (Multiset
.count i k) (x i)
参数：s : Finset ι；q : Nat；a : ι -> R；x : ι -> M。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `IsScalarTower.right`：∀ {R : Type u} {A : Type w} [inst : CommSemiring R]
 [inst_1 : Semiring A] [inst_2 : Algebra R A], IsScalarTower R A A
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.dp_sum`：dp_sum {ι : Type*} [DecidableEq ι] (s : Fins
et ι) (q : Nat) (x : ι -> M) : dp R q (s.sum x) = (Finset.sym s q).sum fun k => 
s.prod fun i => …
· 使用定理 `Finset.sum_congr`：∀ {ι : Type u_1} {M : Type u_4} {s₁ s₂ : Finset ι} [in
st : AddCommMonoid M] {f g : ι → M},   s₁ = s₂ → (∀ x ∈ s₂, f x = g x) → s₁.sum 
f = s₂…
· 使用定理 `Finset.prod_congr`：prod_congr (h : s₁ = s₂) : (forall x in s₂, f x = g x
) -> s₁.prod f = s₂.prod g
· 使用定理 `DividedPowerAlgebra.dp_smul`：dp_smul {r : R} {n : Nat} {m : M} : dp R n 
(r • m) = r ^ n • dp R n m
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `Algebra.smul_def`：smul_def (r : R) (x : A) : r • x = algebraMap R A r * 
x
· 使用定理 `map_prod`：map_prod [CommMonoid M] [CommMonoid N] {G : Type*} [FunLike G 
M N] [MonoidHomClass G M N] (g : G) (f : ι -> M) (s : Finset ι) : g (∏ x in s,…
· 使用定理 `MonoidWithZeroHomClass.toMonoidHomClass`：∀ {F : Type u_7} {α : outParam 
(Type u_8)} {β : outParam (Type u_9)} {inst : MulZeroOneClass α}   {inst_1 : Mul
ZeroOneClass β} {inst_2 : Fun…
· 使用定理 `RingHomClass.toMonoidWithZeroHomClass`：∀ {F : Type u_5} {α : outParam (T
ype u_6)} {β : outParam (Type u_7)} [inst : NonAssocSemiring α]   [inst_1 : NonA
ssocSemiring β] [inst_2 : F…
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
theorem dp_sum_smul {ι : Type*} [DecidableEq ι] (s : Finset ι) (q : ℕ) (a : ι → R) (x : ι → M) :
    dp R q (s.sum fun i ↦ a i • x i) =
      (Finset.sym s q).sum fun k ↦
        (s.prod fun i ↦ a i ^ Multiset.count i k) •
          s.prod fun i ↦ dp R (Multiset.count i k) (x i) := by
  simp_rw [dp_sum, dp_smul, Algebra.smul_def, map_prod, ← Finset.prod_mul_distrib]

open Nat in
/-
**DividedPowerAlgebra.prod_dp** 是 Mathlib 中的一个引理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：prod_dp {ι : Type*} {s : Finset ι} {n : ι -> Nat} {m : M} : ∏ i in s, (dp 
R (n i) m) = (Nat.multinomial s n) * dp R (s.sum n) m
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Finset.induction`：∀ {α : Type u_3} {motive : Finset α → Prop} [inst : De
cidableEq α],   motive ∅ → (∀ (a : α) (s : Finset α), a ∉ s → motive s → motive 
(inser…
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `Nat.multinomial_empty`：∀ {α : Type u_1} (f : α → ℕ), Nat.multinomial ∅ f
 = 1
· 使用定理 `Nat.cast_one`：cast_one : ((1 : Nat) : R) = 1
· 使用定理 `DividedPowerAlgebra.dp_zero`：dp_zero {m : M} : dp R 0 m = 1
· 使用定理 `one_mul`：one_mul : forall a : M, 1 * a = a
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
· 使用定理 `Finset.prod_insert`：prod_insert [DecidableEq ι] : a ∉ s -> ∏ x in insert
 a s, f x = f a * ∏ x in s, f x
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `mul_assoc`：mul_assoc : forall a b c : G, a * b * c = a * (b * c)
· 使用定理 `mul_comm`：mul_comm : forall a b : G, a * b = b * a
· 使用定理 `DividedPowerAlgebra.dp_mul`：dp_mul {n p : Nat} {m : M} : dp R n m * dp R
 p m = (n + p).choose n • dp R (n + p) m
· 使用定理 `Finset.sum_insert`：∀ {ι : Type u_1} {M : Type u_4} {s : Finset ι} {a : ι
} [inst : AddCommMonoid M] {f : ι → M} [inst_1 : DecidableEq ι],   a ∉ s → ∑ x ∈
 insert…
· 使用定理 `nsmul_eq_mul`：∀ {α : Type u} [inst : NonAssocSemiring α] (n : ℕ) (a : α)
, n • a = ↑n * a
· 使用引理 `Nat.multinomial_insert`：multinomial_insert [DecidableEq α] (ha : a ∉ s) 
(f : α -> Nat) : multinomial (insert a s) f = (f a + ∑ i in s, f i).choose (f a)
 * multinomi…
· 使用定理 `Nat.cast_mul`：∀ {α : Type u_1} [inst : NonAssocSemiring α] (m n : ℕ), ↑(
m * n) = ↑m * ↑n
-/
lemma prod_dp {ι : Type*} {s : Finset ι} {n : ι → ℕ} {m : M} :
    ∏ i ∈ s, (dp R (n i) m) = (Nat.multinomial s n) * dp R (s.sum n) m := by
  classical
  induction s using Finset.induction with
  | empty =>
    simp only [prod_empty, multinomial_empty, cast_one, sum_empty, one_mul, dp_zero]
  | insert _ _ hi hrec =>
    rw [prod_insert hi, hrec, ← mul_assoc, mul_comm (dp R (n _) m),
      mul_assoc, dp_mul, ← sum_insert hi, nsmul_eq_mul, ← mul_assoc]
    congr 1
    rw [multinomial_insert hi, mul_comm, cast_mul, sum_insert hi]

open scoped Nat
/-
**DividedPowerAlgebra.natFactorial_mul_dp_eq** 是 Mathlib 中的一个定理，位于命名空间 `DividedP
owerAlgebra`。
形式化陈述：natFactorial_mul_dp_eq (n : Nat) (x : M) : n ! * dp R n x = (dp R 1 x) ^ n
参数：n : Nat；x : M。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Nat.cast_one`：cast_one : ((1 : Nat) : R) = 1
· 使用定理 `DividedPowerAlgebra.dp_zero`：dp_zero {m : M} : dp R 0 m = 1
· 使用定理 `mul_one`：mul_one : forall a : M, a * 1 = a
· 使用定理 `pow_zero`：pow_zero (a : M) : a ^ 0 = 1
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
· 使用定理 `pow_succ`：pow_succ (a : M) (n : Nat) : a ^ (n + 1) = a ^ n * a
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `mul_assoc`：mul_assoc : forall a b c : G, a * b * c = a * (b * c)
· 使用定理 `DividedPowerAlgebra.dp_mul`：dp_mul {n p : Nat} {m : M} : dp R n m * dp R
 p m = (n + p).choose n • dp R (n + p) m
· 使用定理 `nsmul_eq_mul`：∀ {α : Type u} [inst : NonAssocSemiring α] (n : ℕ) (a : α)
, n • a = ↑n * a
· 使用定理 `Nat.cast_mul`：∀ {α : Type u_1} [inst : NonAssocSemiring α] (m n : ℕ), ↑(
m * n) = ↑m * ↑n
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `Nat.cast_add`：cast_add (m n : Nat) : ((m + n : Nat) : R) = m + n
· 使用定理 `Nat.choose_succ_self_right`：∀ (n : ℕ), (n + 1).choose n = n + 1
· 使用定理 `mul_comm`：mul_comm : forall a b : G, a * b = b * a
-/
theorem natFactorial_mul_dp_eq (n : ℕ) (x : M) :
    n ! * dp R n x = (dp R 1 x) ^ n := by
  induction n with
  | zero => simp [dp_zero]
  | succ n h =>
    rw [pow_succ, ← h, mul_assoc, dp_mul, nsmul_eq_mul, ← mul_assoc, ← Nat.cast_mul]
    simp [mul_comm _ (n + 1), Nat.factorial_succ]

variable (R M) in
/-- The canonical linear map `M →ₗ[R] DividedPowerAlgebra R M`. -/
/-
**DividedPowerAlgebra.embed** 是 Mathlib 中的一个定义，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：embed : M ->ₗ[R] DividedPowerAlgebra R M where toFun m
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The canonical linear map `M →ₗ[R] DividedPowerAlgebra R M`.
-/
def embed : M →ₗ[R] DividedPowerAlgebra R M where
  toFun m := dp R 1 m
  map_add' _ _ := by simp [dp_add, Nat.antidiagonal_succ, dp_zero, add_comm]
  map_smul' _ _ := by simp [dp_smul, pow_one, RingHom.id_apply]
/-
**DividedPowerAlgebra.embed_def** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：embed_def (m : M) : embed R M m = dp R 1 m
参数：m : M。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem embed_def (m : M) : embed R M m = dp R 1 m := rfl
/-
**DividedPowerAlgebra.algHom_ext_iff** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlge
bra`。
形式化陈述：algHom_ext_iff {A : Type*} [CommSemiring A] [Algebra R A] {f g : DividedPo
werAlgebra R M ->ₐ[R] A} : f = g ↔ forall n m, f (dp R n m) = g (dp R n m)
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DFunLike.ext'_iff`：∀ {F : Sort u_1} {α : Sort u_2} {β : α → Sort u_3} [i
 : DFunLike F α β] {f g : F}, f = g ↔ ⇑f = ⇑g
· 使用定理 `Function.Surjective.injective_comp_right`：∀ {α : Sort u_1} {β : Sort u_2
} {γ : Sort u_3} {f : α → β}, Function.Surjective f → Function.Injective fun g =
> g ∘ f
· 使用引理 `DividedPowerAlgebra.mkAlgHom_surjective`：mkAlgHom_surjective : Function.
Surjective (RingCon.mkₐ R (ringCon R M))
· 使用定理 `MvPolynomial.algHom_ext`：algHom_ext {A : Type*} [Semiring A] [Algebra R 
A] {f g : MvPolynomial σ R ->ₐ[R] A} (hf : forall i : σ, f (X i) = g (X i)) : f 
= g
-/
theorem algHom_ext_iff {A : Type*} [CommSemiring A] [Algebra R A]
    {f g : DividedPowerAlgebra R M →ₐ[R] A} :
    f = g ↔ ∀ n m, f (dp R n m) = g (dp R n m) := by
  refine ⟨fun h _ _ ↦ by rw [h], fun h ↦ ?_⟩
  rw [DFunLike.ext'_iff]
  apply Function.Surjective.injective_comp_right mkAlgHom_surjective
  simpa [← AlgHom.coe_comp] using MvPolynomial.algHom_ext fun ⟨n, m⟩ ↦ h n m

@[ext]
/-
**DividedPowerAlgebra.algHom_ext** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`
。
形式化陈述：algHom_ext {A : Type*} [CommSemiring A] [Algebra R A] {f g : DividedPowerA
lgebra R M ->ₐ[R] A} (h : forall n m, f (dp R n m) = g (dp R n m)) : f = g
参数：h : forall n m, f (dp R n m) = g (dp R n m)。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `DividedPowerAlgebra.algHom_ext_iff`：algHom_ext_iff {A : Type*} [CommSemi
ring A] [Algebra R A] {f g : DividedPowerAlgebra R M ->ₐ[R] A} : f = g ↔ forall 
n m, f (dp R n m) = g (d…
-/
theorem algHom_ext {A : Type*} [CommSemiring A] [Algebra R A]
    {f g : DividedPowerAlgebra R M →ₐ[R] A}
    (h : ∀ n m, f (dp R n m) = g (dp R n m)) : f = g :=
  algHom_ext_iff.mpr h

section

open Submodule

variable {R M ι : Type*} [CommRing R] [AddCommGroup M] [Module R M] {v : ι → M}

/- If the `R`-module is spanned by elements `v i`, then `DividedPowerAlgebra R M`
is linearly spanned by the finite products `∏ i, dp R (k i) (v i)`.

When these `v i` form a `Module.Basis`, these elements are linearly independent,
hence form a `Module.Basis` of `DividedPowerAlgebra R M`, see `DividedPowers.DPAlgebra.Free`. -/
/-
**DividedPowerAlgebra.submodule_span_prod_dp_eq_top** 是 Mathlib 中的一个定理，位于命名空间 `D
ividedPowerAlgebra`。
形式化陈述：submodule_span_prod_dp_eq_top (hv : span R (Set.range v) = ⊤) : span R (Se
t.range fun (n : ι ->₀ Nat) => n.prod fun i k => dp R k (v i)) = ⊤
参数：hv : span R (Set.range v) = ⊤。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `eq_top_iff`：eq_top_iff : a = ⊤ ↔ ⊤ <= a
· 使用定理 `DividedPowerAlgebra.induction_on`：∀ {R : Type u_2} {M : Type u_3} [inst 
: CommSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   {P :
 DividedPowerAlgebra R…
· 使用定理 `Algebra.algebraMap_eq_smul_one`：algebraMap_eq_smul_one (r : R) : algebra
Map R A r = r • (1 : A)
· 使用定理 `Submodule.smul_mem`：smul_mem (r : R) (h : x in p) : r • x in p
· 使用定理 `Submodule.subset_span`：subset_span : s subseteq span R s
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
· 使用定理 `Submodule.add_mem`：∀ {R : Type u} {M : Type v} [inst : Semiring R] [inst
_1 : AddCommMonoid M] {module_M : _root_.Module R M}   (p : Submodule R M) {x y 
: M}, x…
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `Submodule.span_induction`：span_induction {p : (x : M) -> x in span R s -
> Prop} (mem : forall (x) (h : x in s), p x (subset_span h)) (zero : p 0 (Submod
ule.zero_mem _…
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `Finsupp.mul_prod_erase'`：mul_prod_erase' (f : α ->₀ M) (y : α) (g : α ->
 M -> N) (hg : forall i : α, g i 0 = 1) : g y (f y) * (erase y f).prod g = f.pro
d g
· 使用定理 `DividedPowerAlgebra.dp_zero`：dp_zero {m : M} : dp R 0 m = 1
· 使用定理 `mul_comm`：mul_comm : forall a b : G, a * b = b * a
· 使用定理 `mul_assoc`：mul_assoc : forall a b c : G, a * b * c = a * (b * c)
· 使用定理 `DividedPowerAlgebra.dp_mul`：dp_mul {n p : Nat} {m : M} : dp R n m * dp R
 p m = (n + p).choose n • dp R (n + p) m
· 使用定理 `nsmul_eq_mul`：∀ {α : Type u} [inst : NonAssocSemiring α] (n : ℕ) (a : α)
, n • a = ↑n * a
· 使用定理 `Submodule.smul_of_tower_mem`：smul_of_tower_mem [SMul S R] [SMul S M] [Is
ScalarTower S R M] (r : S) (h : x in p) : r • x in p
· 使用定理 `Submodule.mem_span_of_mem`：mem_span_of_mem {s : Set M} {x : M} (hx : x i
n s) : x in span R s
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `Finsupp.single_eq_same`：single_eq_same : (single a b : α ->₀ M) a = b
· 使用引理 `Finsupp.erase_add`：erase_add (a : ι) (f f' : ι ->₀ M) : erase a (f + f')
 = erase a f + erase a f'
· 使用定理 `Finsupp.erase_single`：erase_single {a : α} {b : M} : erase a (single a b
) = 0
· 使用定理 `zero_add`：∀ {M : Type u} [inst : AddZeroClass M] (a : M), 0 + a = a
· 使用定理 `MulZeroClass.zero_mul`：∀ {M₀ : Type u} [self : MulZeroClass M₀] (a : M₀)
, 0 * a = 0
· 使用定理 `AddSubmonoidClass.toZeroMemClass`：∀ {S : Type u_3} {M : outParam (Type u
_4)} {inst : AddZeroClass M} {inst_1 : SetLike S M}   [self : AddSubmonoidClass 
S M], ZeroMemClass S M
· 使用定理 `add_mul`：add_mul {d : R} (_ : (a₁ : R) * b = c₁) (_ : a₂ * b = c₂) (_ : 
c₁ + c₂ = d) : (a₁ + a₂) * b = d
· 使用定理 `Distrib.rightDistribClass`：∀ (R : Type u_1) [inst : Distrib R], RightDis
tribClass R
（共 43 条，此处仅展示前 30 条）

--- 原说明 ---
If the `R`-module is spanned by elements `v i`, then `DividedPowerAlgebra R M`
is linearly spanned by the finite products `∏ i, dp R (k i) (v i)`.

When these `v i` form a `Module.Basis`, these elements are linearly independent,
hence form a `Module.Basis` of `DividedPowerAlgebra R M`, see `DividedPowers.DPA
lgebra.Free`.
-/
theorem submodule_span_prod_dp_eq_top (hv : span R (Set.range v) = ⊤) :
    span R (Set.range fun (n : ι →₀ ℕ) ↦ n.prod fun i k ↦ dp R k (v i)) = ⊤ := by
  rw [eq_top_iff]
  intro p hp
  clear hp
  induction p using DividedPowerAlgebra.induction_on with
  | C r =>
    simp only [Algebra.algebraMap_eq_smul_one]
    exact smul_mem _ _ (subset_span ⟨0, by simp⟩)
  | add x y hx hy => exact Submodule.add_mem _ hx hy
  | dp x k m hx =>
    have hm : m ∈ span R (Set.range v) := by simp [hv, mem_top]
    induction hm using span_induction generalizing x k with
    | zero => rw [dp_null]; split_ifs <;> simp [hx]
    | smul r m hm h => simp [dp_smul, smul_mem _ _ (h x k hx)]
    | mem y hy =>
      obtain ⟨i, rfl⟩ := hy
      induction hx using span_induction with
      | zero => simp
      | mem x hx =>
        obtain ⟨n, rfl⟩ := hx
        simp only
        rw [← n.mul_prod_erase' i _ (fun i ↦ dp_zero (m := v i)), mul_comm,
          ← mul_assoc, dp_mul, nsmul_eq_mul, mul_assoc, ← nsmul_eq_mul]
        refine smul_of_tower_mem _ _ (mem_span_of_mem ⟨Finsupp.single i k + n, ?_⟩)
        simp only
        rw [← (Finsupp.single i k + n).mul_prod_erase' i _ (fun i ↦ dp_zero (m := v i))]
        simp
      | add x y hxmem hymem hx hy =>
        rw [add_mul]
        exact Submodule.add_mem _ hx hy
      | smul r x hxmem hx =>
        rw [smul_mul_assoc]
        exact smul_mem _ _ hx
    | add m n hm_mem hn_mem hm hn =>
      rw [dp_add, mul_sum]
      apply sum_mem (fun c hc ↦ ?_)
      rw [← mul_assoc]
      exact hn (x * dp R c.1 m) c.2 (hm x c.1 hx)
/-
**DividedPowerAlgebra.pow_dp** 是 Mathlib 中的一个引理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：pow_dp (n : Nat) (m : M) (k : Nat) : (dp R n m) ^ k = (Multiset.multinomia
l (k • {n})) * dp R (k * n) m
参数：n : Nat；m : M；k : Nat。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Multiset.multinomial_nsmul_singleton`：multinomial_nsmul_singleton (k n :
 Nat) : (k • {n} : Multiset Nat).multinomial = Nat.multinomial (Finset.range k) 
(fun _ => n)
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `Fin.prod_const`：prod_const (n : Nat) (x : M) : ∏ _i : Fin n, x = x ^ n
· 使用引理 `DividedPowerAlgebra.prod_dp`：prod_dp {ι : Type*} {s : Finset ι} {n : ι -
> Nat} {m : M} : ∏ i in s, (dp R (n i) m) = (Nat.multinomial s n) * dp R (s.sum 
n) m
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `Finset.sum_congr`：∀ {ι : Type u_1} {M : Type u_4} {s₁ s₂ : Finset ι} [in
st : AddCommMonoid M] {f g : ι → M},   s₁ = s₂ → (∀ x ∈ s₂, f x = g x) → s₁.sum 
f = s₂…
· 使用定理 `Finset.sum_const`：∀ {ι : Type u_1} {M : Type u_4} {s : Finset ι} [inst :
 AddCommMonoid M] (b : M), ∑ _x ∈ s, b = s.card • b
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `Fintype.card_fin`：Fintype.card_fin (n : Nat) : Fintype.card (Fin n) = n
· 使用定理 `Finset.prod_congr`：prod_congr (h : s₁ = s₂) : (forall x in s₂, f x = g x
) -> s₁.prod f = s₂.prod g
· 使用定理 `Finset.prod_const`：prod_const (b : M) : ∏ _x in s, b = b ^ #s
· 使用定理 `Finset.card_range`：card_range (n : Nat) : #(range n) = n
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma pow_dp (n : ℕ) (m : M) (k : ℕ) :
    (dp R n m) ^ k = (Multiset.multinomial (k • {n})) * dp R (k * n) m := by
  rw [Multiset.multinomial_nsmul_singleton, ← Fin.prod_const, prod_dp]
  simp [Nat.multinomial]

end

section UniversalProperty

variable (R M)

variable {A : Type*} [CommSemiring A] [Algebra R A]

/-
**DividedPowerAlgebra.lift'_imp** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
private theorem lift'_imp {f : ℕ × M → A} (hf_zero : ∀ m, f (0, m) = 1)
    (hf_smul : ∀ (n : ℕ) (r : R) (m : M), f ⟨n, r • m⟩ = r ^ n • f ⟨n, m⟩)
    (hf_mul : ∀ n p m, f ⟨n, m⟩ * f ⟨p, m⟩ = (n + p).choose n • f ⟨n + p, m⟩)
    (hf_add : ∀ n u v, f ⟨n, u + v⟩ = (antidiagonal n).sum fun (k, l) ↦ f ⟨k, u⟩ * f ⟨l, v⟩)
    (p q : MvPolynomial (ℕ × M) R) (h : (Rel R M) p q) :
    eval₂AlgHom R f p = eval₂AlgHom R f q := by
  rcases h <;>
  simp_all

variable {R M}

/-- The weak universal property of `DividedPowerAlgebra R M`. -/
/-
**DividedPowerAlgebra.lift'** 是 Mathlib 中的一个定义，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：lift' {f : Nat × M -> A} (hf_zero : forall m, f (0, m) = 1) (hf_smul : for
all (n : Nat) (r : R) (m : M), f ⟨n, r • m⟩ = r ^ n • f ⟨n, m⟩) (hf_mul : forall
 n p m, f ⟨n, m⟩ * f ⟨p, m⟩ = (n + p).choose n • f ⟨n + p, m⟩) (hf_add : forall 
n u v, f ⟨n, u + v⟩ = (antidiagonal n).sum fun (k, l) => f ⟨k, u⟩ * f ⟨l, v⟩) : 
DividedPowerAlgebra R M ->ₐ[R] A
参数：hf_zero : forall m, f (0, m) = 1；hf_smul : forall (n : Nat) (r : R) (m : M), 
f ⟨n, r • m⟩ = r ^ n • f ⟨n, m⟩；hf_mul : forall n p m, f ⟨n, m⟩ * f ⟨p, m⟩ = (n 
+ p).choose n • f ⟨n + p, m⟩；hf_add : forall n u v, f ⟨n, u + v⟩ = (antidiagonal
 n).sum fun (k, l) => f ⟨k, u⟩ * f ⟨l, v⟩。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The weak universal property of `DividedPowerAlgebra R M`.
-/
def lift' {f : ℕ × M → A} (hf_zero : ∀ m, f (0, m) = 1)
    (hf_smul : ∀ (n : ℕ) (r : R) (m : M), f ⟨n, r • m⟩ = r ^ n • f ⟨n, m⟩)
    (hf_mul : ∀ n p m, f ⟨n, m⟩ * f ⟨p, m⟩ = (n + p).choose n • f ⟨n + p, m⟩)
    (hf_add : ∀ n u v, f ⟨n, u + v⟩ = (antidiagonal n).sum fun (k, l) ↦ f ⟨k, u⟩ * f ⟨l, v⟩) :
    DividedPowerAlgebra R M →ₐ[R] A :=
  RingCon.liftₐ _ (eval₂AlgHom R f) <| by
    grw [ringCon, RingCon.ringConGen_le]
    exact lift'_imp R M hf_zero hf_smul hf_mul hf_add

@[simp]
/-
**DividedPowerAlgebra.lift'_apply** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra
`。
形式化陈述：∀ {R : Type u_2} {M : Type u_3} [inst : CommSemiring R] [inst_1 : AddCommM
onoid M] [inst_2 : _root_.Module R M]   {A : Type u_4} [inst_3 : CommSemiring A]
 [inst_4 : Algebra R A] {f : ℕ × M → A} (hf_zero : ∀ (m : M), f (0, m) = 1)   (h
f_smul : ∀ (n : ℕ) (r : R) (m : M), f (n, r • m) = r ^ n • f (n, m))   (hf_mul :
 ∀ (n p : ℕ) (m : M), f (n, m) * f (p, m) = (n + p).choose n • f (n + p, m))   (
hf_add :     ∀ (n : ℕ) (u v : M),       f (n, u + v) =         ∑ x ∈ Finset.HasA
ntidiagonal.antidiagonal n,           match x with           | (k, l) => f (k, u
) * f (l, v))   (p : MvPolynomial (ℕ × M) R), (DividedPowerAlgebra.lift' hf_zero
 hf_smul hf_mul hf_add) ↑p = (MvPolynomial.aeval f) p
参数：hf_zero : ∀ (m : M), f (0, m) = 1；hf_smul : ∀ (n : ℕ) (r : R) (m : M), f (n, 
r • m) = r ^ n • f (n, m)；hf_mul : ∀ (n p : ℕ) (m : M), f (n, m) * f (p, m) = (n
 + p).choose n • f (n + p, m)；hf_add :     ∀ (n : ℕ) (u v : M),       f (n, u + 
v) =         ∑ x ∈ Finset.HasAntidiagonal.antidiagonal n,           match x with
           | (k, l) => f (k, u) * f (l, v)；p : MvPolynomial (ℕ × M) R；DividedPow
erAlgebra.lift' hf_zero hf_smul hf_mul hf_add；MvPolynomial.aeval f。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
theorem lift'_apply {f : ℕ × M → A} (hf_zero : ∀ m, f (0, m) = 1)
    (hf_smul : ∀ (n : ℕ) (r : R) (m : M), f ⟨n, r • m⟩ = r ^ n • f ⟨n, m⟩)
    (hf_mul : ∀ n p m, f ⟨n, m⟩ * f ⟨p, m⟩ = (n + p).choose n • f ⟨n + p, m⟩)
    (hf_add : ∀ n u v, f ⟨n, u + v⟩ = (antidiagonal n).sum fun (k, l) ↦ f ⟨k, u⟩ * f ⟨l, v⟩)
    (p : MvPolynomial (ℕ × M) R) :
    lift' hf_zero hf_smul hf_mul hf_add ↑p = aeval f p := by
  simp [lift', aeval_eq_eval₂Hom]

@[simp]
/-
**DividedPowerAlgebra.lift'_apply_dp** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlge
bra`。
形式化陈述：∀ {R : Type u_2} {M : Type u_3} [inst : CommSemiring R] [inst_1 : AddCommM
onoid M] [inst_2 : _root_.Module R M]   {A : Type u_4} [inst_3 : CommSemiring A]
 [inst_4 : Algebra R A] {f : ℕ × M → A} (hf_zero : ∀ (m : M), f (0, m) = 1)   (h
f_smul : ∀ (n : ℕ) (r : R) (m : M), f (n, r • m) = r ^ n • f (n, m))   (hf_mul :
 ∀ (n p : ℕ) (m : M), f (n, m) * f (p, m) = (n + p).choose n • f (n + p, m))   (
hf_add :     ∀ (n : ℕ) (u v : M),       f (n, u + v) =         ∑ x ∈ Finset.HasA
ntidiagonal.antidiagonal n,           match x with           | (k, l) => f (k, u
) * f (l, v))   (n : ℕ) (m : M), (DividedPowerAlgebra.lift' hf_zero hf_smul hf_m
ul hf_add) (DividedPowerAlgebra.dp R n m) = f (n, m)
参数：hf_zero : ∀ (m : M), f (0, m) = 1；hf_smul : ∀ (n : ℕ) (r : R) (m : M), f (n, 
r • m) = r ^ n • f (n, m)；hf_mul : ∀ (n p : ℕ) (m : M), f (n, m) * f (p, m) = (n
 + p).choose n • f (n + p, m)；hf_add :     ∀ (n : ℕ) (u v : M),       f (n, u + 
v) =         ∑ x ∈ Finset.HasAntidiagonal.antidiagonal n,           match x with
           | (k, l) => f (k, u) * f (l, v)；n : ℕ；m : M；DividedPowerAlgebra.lift'
 hf_zero hf_smul hf_mul hf_add；DividedPowerAlgebra.dp R n m；n, m。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.dp_def`：dp_def (n : Nat) (m : M) : dp R n m = ↑(X (n
, m) : MvPolynomial (Nat × M) R)
· 使用定理 `DividedPowerAlgebra.lift'_apply`：∀ {R : Type u_2} {M : Type u_3} [inst :
 CommSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   {A : 
Type u_4} [inst_3 : C…
· 使用定理 `MvPolynomial.aeval_X`：aeval_X (s : σ) : aeval f (X s : MvPolynomial σ R)
 = f s
-/
theorem lift'_apply_dp {f : ℕ × M → A} (hf_zero : ∀ m, f (0, m) = 1)
    (hf_smul : ∀ (n : ℕ) (r : R) (m : M), f ⟨n, r • m⟩ = r ^ n • f ⟨n, m⟩)
    (hf_mul : ∀ n p m, f ⟨n, m⟩ * f ⟨p, m⟩ = (n + p).choose n • f ⟨n + p, m⟩)
    (hf_add : ∀ n u v, f ⟨n, u + v⟩ = (antidiagonal n).sum fun (k, l) ↦ f ⟨k, u⟩ * f ⟨l, v⟩)
    (n : ℕ) (m : M) :
    lift' hf_zero hf_smul hf_mul hf_add (dp R n m) = f ⟨n, m⟩ := by
  rw [dp_def, lift'_apply hf_zero hf_smul hf_mul hf_add, aeval_X]

variable {I : Ideal A} (hI : DividedPowers I) (g : M →ₗ[R] A) (hg : ∀ m, g m ∈ I)

/-- The weak universal property of a divided power algebra for morphisms to divided power rings -/
/-
**DividedPowerAlgebra.lift** 是 Mathlib 中的一个定义，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：lift : DividedPowerAlgebra R M ->ₐ[R] A
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The weak universal property of a divided power algebra for morphisms to divided 
power rings
-/
def lift : DividedPowerAlgebra R M →ₐ[R] A :=
  lift' (f := fun nm ↦ hI.dpow nm.1 (g nm.2))
    (fun m ↦ hI.dpow_zero (hg m))
    (fun n r m ↦ by
      dsimp only
      rw [LinearMap.map_smulₛₗ, RingHom.id_apply, ← algebraMap_smul A r (g m), smul_eq_mul,
        hI.dpow_mul (hg m), ← smul_eq_mul, ← map_pow, algebraMap_smul])
    (fun n p m ↦ by rw [hI.mul_dpow (hg m), ← nsmul_eq_mul])
    (fun n u v ↦ by simp [hI.dpow_add (hg u) (hg v)])

variable {g}

@[simp]
/-
**DividedPowerAlgebra.lift_apply** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`
。
形式化陈述：lift_apply (p : MvPolynomial (Nat × M) R) : lift hI g hg ↑p = aeval (fun n
m : Nat × M => hI.dpow nm.1 (g nm.2)) p
参数：p : MvPolynomial (Nat × M) R。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.lift.eq_1`：∀ {R : Type u_2} {M : Type u_3} [inst : C
ommSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   {A : Ty
pe u_4} [inst_3 : C…
· 使用定理 `DividedPowerAlgebra.lift'_apply`：∀ {R : Type u_2} {M : Type u_3} [inst :
 CommSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   {A : 
Type u_4} [inst_3 : C…
-/
theorem lift_apply (p : MvPolynomial (ℕ × M) R) :
    lift hI g hg ↑p = aeval (fun nm : ℕ × M ↦ hI.dpow nm.1 (g nm.2)) p := by
  rw [lift, lift'_apply]

@[simp]
/-
**DividedPowerAlgebra.lift_apply_dp** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgeb
ra`。
形式化陈述：lift_apply_dp (n : Nat) (m : M) : lift hI g hg (dp R n m) = hI.dpow n (g m
)
参数：n : Nat；m : M。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.lift.eq_1`：∀ {R : Type u_2} {M : Type u_3} [inst : C
ommSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   {A : Ty
pe u_4} [inst_3 : C…
· 使用定理 `DividedPowerAlgebra.lift'_apply_dp`：∀ {R : Type u_2} {M : Type u_3} [ins
t : CommSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   {A
 : Type u_4} [inst_3 : C…
-/
theorem lift_apply_dp (n : ℕ) (m : M) :
    lift hI g hg (dp R n m) = hI.dpow n (g m) := by rw [lift, lift'_apply_dp]
/-
**DividedPowerAlgebra.lift_unique** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra
`。
形式化陈述：lift_unique {f : DividedPowerAlgebra R M ->ₐ[R] A} (hf : forall n m, f (dp
 R n m) = hI.dpow n (g m)) : f = lift hI g hg
参数：hf : forall n m, f (dp R n m) = hI.dpow n (g m)。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `DividedPowerAlgebra.algHom_ext`：algHom_ext {A : Type*} [CommSemiring A] 
[Algebra R A] {f g : DividedPowerAlgebra R M ->ₐ[R] A} (h : forall n m, f (dp R 
n m) = g (dp R n m))…
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.lift_apply_dp`：lift_apply_dp (n : Nat) (m : M) : lif
t hI g hg (dp R n m) = hI.dpow n (g m)
-/
theorem lift_unique {f : DividedPowerAlgebra R M →ₐ[R] A}
    (hf : ∀ n m, f (dp R n m) = hI.dpow n (g m)) : f = lift hI g hg :=
  algHom_ext (fun _ _ ↦ by rw [lift_apply_dp, hf])

@[simp]
/-
**DividedPowerAlgebra.lift_embed_apply** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAl
gebra`。
形式化陈述：lift_embed_apply (m : M) : lift hI g hg (embed R M m) = g m
参数：m : M。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.lift_apply_dp`：lift_apply_dp (n : Nat) (m : M) : lif
t hI g hg (dp R n m) = hI.dpow n (g m)
· 使用定理 `DividedPowers.dpow_one`：∀ {A : Type u_1} [inst : CommSemiring A] {I : Id
eal A} (self : DividedPowers I) {x : A}, x ∈ I → self.dpow 1 x = x
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
theorem lift_embed_apply (m : M) : lift hI g hg (embed R M m) = g m := by
  simp [embed_def, hI.dpow_one (hg m)]

@[simp]
/-
**DividedPowerAlgebra.embed_comp_lift** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlg
ebra`。
形式化陈述：embed_comp_lift : (lift hI g hg).toLinearMap.comp (embed R M) = g
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `LinearMap.ext`：ext {f g : M ->ₛₗ[σ] M₃} (h : forall x, f x = g x) : f = 
g
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.lift_embed_apply`：lift_embed_apply (m : M) : lift hI
 g hg (embed R M m) = g m
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
theorem embed_comp_lift : (lift hI g hg).toLinearMap.comp (embed R M) = g := by
  ext; simp

end UniversalProperty

section Functoriality

section Map

variable {S : Type*} [CommSemiring S] {N : Type*} [AddCommMonoid N] [Module R N] [Module S N]
  (f : M →ₗ[R] N)

namespace LinearMap

@[simp]
/-
**DividedPowerAlgebra.LinearMap.dp_zero** 是 Mathlib 中的一个引理，位于命名空间 `DividedPowerA
lgebra.LinearMap`。
形式化陈述：dp_zero {a : M} : dp S 0 (f a) = 1
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `DividedPowerAlgebra.dp_zero`：dp_zero {m : M} : dp R 0 m = 1
-/
lemma dp_zero {a : M} : dp S 0 (f a) = 1 := DividedPowerAlgebra.dp_zero
/-
**DividedPowerAlgebra.LinearMap.dp_mul** 是 Mathlib 中的一个引理，位于命名空间 `DividedPowerAl
gebra.LinearMap`。
形式化陈述：dp_mul {m n : Nat} {a : M} : dp S m (f a) * dp S n (f a) = (Nat.choose (m 
+ n) m) • dp S (m + n) (f a)
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `DividedPowerAlgebra.dp_mul`：dp_mul {n p : Nat} {m : M} : dp R n m * dp R
 p m = (n + p).choose n • dp R (n + p) m
-/
lemma dp_mul {m n : ℕ} {a : M} :
    dp S m (f a) * dp S n (f a) = (Nat.choose (m + n) m) • dp S (m + n) (f a) :=
  DividedPowerAlgebra.dp_mul
/-
**DividedPowerAlgebra.LinearMap.dp_add** 是 Mathlib 中的一个引理，位于命名空间 `DividedPowerAl
gebra.LinearMap`。
形式化陈述：dp_add {n : Nat} {a b : M} : dp S n (f (a + b)) = (Finset.antidiagonal n).
sum fun k => dp S k.1 (f a) * dp S k.2 (f b)
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `map_add`：∀ {M : Type u_4} {N : Type u_5} {F : Type u_9} [inst : Add M] [
inst_1 : Add N] [inst_2 : FunLike F M N]   [AddHomClass F M N] (f : F) (x y :…
· 使用定理 `SemilinearMapClass.toAddHomClass`：∀ {F : Type u_14} {R : outParam (Type 
u_15)} {S : outParam (Type u_16)} {inst : Semiring R} {inst_1 : Semiring S}   {σ
 : outParam (R →+* S)}…
· 使用定理 `DividedPowerAlgebra.dp_add`：dp_add {n : Nat} {x y : M} : dp R n (x + y) 
= (antidiagonal n).sum fun k => dp R k.1 x * dp R k.2 y
-/
lemma dp_add {n : ℕ} {a b : M} :
    dp S n (f (a + b)) = (Finset.antidiagonal n).sum fun k ↦ dp S k.1 (f a) * dp S k.2 (f b) := by
  rw [map_add, DividedPowerAlgebra.dp_add]

end LinearMap

section IsScalarTower

variable (S)

variable [Algebra R S] [IsScalarTower R S N]

/-
**DividedPowerAlgebra.LinearMap.dp_smul** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerA
lgebra.LinearMap`。
形式化陈述：∀ {R : Type u_2} {M : Type u_3} [inst : CommSemiring R] [inst_1 : AddCommM
onoid M] [inst_2 : _root_.Module R M]   (S : Type u_4) [inst_3 : CommSemiring S]
 {N : Type u_5} [inst_4 : AddCommMonoid N] [inst_5 : _root_.Module R N]   [inst_
6 : _root_.Module S N] (f : M →ₗ[R] N) [inst_7 : Algebra R S] [IsScalarTower R S
 N] {n : ℕ} {r : R} {a : M},   DividedPowerAlgebra.dp S n (f (r • a)) = r ^ n • 
DividedPowerAlgebra.dp S n (f a)
参数：S : Type u_4；f : M →ₗ[R] N；f (r • a)；f a。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `IsScalarTower.right`：∀ {R : Type u} {A : Type w} [inst : CommSemiring R]
 [inst_1 : Semiring A] [inst_2 : Algebra R A], IsScalarTower R A A
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `LinearMap.map_smul`：∀ {R : Type u_1} {M : Type u_8} {M₂ : Type u_10} [in
st : Semiring R] [inst_1 : AddCommMonoid M]   [inst_2 : AddCommMonoid M₂] [inst_
3 : _roo…
· 使用定理 `algebra_compatible_smul`：algebra_compatible_smul (r : R) (m : M) : r • m
 = (algebraMap R A) r • m
· 使用定理 `DividedPowerAlgebra.dp_smul`：dp_smul {r : R} {n : Nat} {m : M} : dp R n 
(r • m) = r ^ n • dp R n m
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `map_pow`：∀ {G : Type u_7} {H : Type u_8} {F : Type u_9} [inst : FunLike 
F G H] [inst_1 : Monoid G] [inst_2 : Monoid H]   [MonoidHomClass F G H] (f : …
· 使用定理 `MonoidWithZeroHomClass.toMonoidHomClass`：∀ {F : Type u_7} {α : outParam 
(Type u_8)} {β : outParam (Type u_9)} {inst : MulZeroOneClass α}   {inst_1 : Mul
ZeroOneClass β} {inst_2 : Fun…
· 使用定理 `RingHomClass.toMonoidWithZeroHomClass`：∀ {F : Type u_5} {α : outParam (T
ype u_6)} {β : outParam (Type u_7)} [inst : NonAssocSemiring α]   [inst_1 : NonA
ssocSemiring β] [inst_2 : F…
· 使用定理 `algebraMap_smul`：algebraMap_smul (r : R) (m : M) : (algebraMap R A) r • 
m = r • m
· 使用定理 `RingCon.instIsScalarTowerQuotient`：∀ {α : Type u_1} {β : Type u_2} {R : 
Type u_3} [inst : Add R] [inst_1 : MulOneClass R] [inst_2 : SMul α R]   [inst_3 
: IsScalarTower α R R] …
· 使用定理 `AddMonoidAlgebra.isScalarTower`：∀ {R : Type u_1} {M : Type u_4} {N : Typ
e u_5} {O : Type u_6} [inst : Semiring R] [inst_1 : SMulZeroClass N R]   [inst_2
 : SMulZeroClass O R…
-/
lemma LinearMap.dp_smul {n : ℕ} {r : R} {a : M} : dp S n (f (r • a)) = r ^ n • dp S n (f a) := by
  rw [f.map_smul, algebra_compatible_smul S r (f a),
    DividedPowerAlgebra.dp_smul, ← map_pow, algebraMap_smul]

/-- The functoriality map between divided power algebras associated with a linear map of the
  underlying modules.
  Given an `R`-algebra `S`, an `S`-module `N` and an `R`-linear map `f : M →ₗ[R] N`,
  this is the map `DividedPowerAlgebra R M →ₐ[R] DividedPowerAlgebra S N`
  sending `dp R n m` to `dp S n (f m)`. -/
/-
**DividedPowerAlgebra.map** 是 Mathlib 中的一个定义，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：map : DividedPowerAlgebra R M ->ₐ[R] DividedPowerAlgebra S N
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The functoriality map between divided power algebras associated with a linear ma
p of the
  underlying modules.
  Given an `R`-algebra `S`, an `S`-module `N` and an `R`-linear map `f : M →ₗ[R]
 N`,
  this is the map `DividedPowerAlgebra R M →ₐ[R] DividedPowerAlgebra S N`
  sending `dp R n m` to `dp S n (f m)`.
-/
def map : DividedPowerAlgebra R M →ₐ[R] DividedPowerAlgebra S N :=
  DividedPowerAlgebra.lift' (f := fun nm ↦ dp S nm.fst (f nm.snd))
    (fun _ ↦ LinearMap.dp_zero f)
    (fun _ _ _ ↦ LinearMap.dp_smul S f)
    (fun _ _ _ ↦ LinearMap.dp_mul f)
    (fun _ _ _ ↦ LinearMap.dp_add f)

@[simp]
/-
**DividedPowerAlgebra.map_apply** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：map_apply {p : MvPolynomial (Nat × M) R} : map S f ↑p = aeval (fun nm => d
p S nm.fst (f nm.snd)) p
参数：Nat × M。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.map.eq_1`：∀ {R : Type u_2} {M : Type u_3} [inst : Co
mmSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   (S : Typ
e u_4) [inst_3 : C…
· 使用定理 `DividedPowerAlgebra.lift'_apply`：∀ {R : Type u_2} {M : Type u_3} [inst :
 CommSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   {A : 
Type u_4} [inst_3 : C…
-/
theorem map_apply {p : MvPolynomial (ℕ × M) R} :
    map S f ↑p = aeval (fun nm ↦ dp S nm.fst (f nm.snd)) p := by
  rw [map, lift'_apply]

@[simp]
/-
**DividedPowerAlgebra.map_apply_dp** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgebr
a`。
形式化陈述：map_apply_dp {n : Nat} {a : M} : map S f (dp R n a) = dp S n (f a)
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.map.eq_1`：∀ {R : Type u_2} {M : Type u_3} [inst : Co
mmSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   (S : Typ
e u_4) [inst_3 : C…
· 使用定理 `DividedPowerAlgebra.lift'_apply_dp`：∀ {R : Type u_2} {M : Type u_3} [ins
t : CommSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M]   {A
 : Type u_4} [inst_3 : C…
-/
theorem map_apply_dp {n : ℕ} {a : M} : map S f (dp R n a) = dp S n (f a) := by
  rw [map, lift'_apply_dp]

@[simp]
/-
**DividedPowerAlgebra.map_embed_apply** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlg
ebra`。
形式化陈述：map_embed_apply {m : M} : map S f (embed R M m) = embed S N (f m)
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.map_apply_dp`：map_apply_dp {n : Nat} {a : M} : map S
 f (dp R n a) = dp S n (f a)
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
theorem map_embed_apply {m : M} : map S f (embed R M m) = embed S N (f m) := by
  simp [embed_def, map_apply_dp]
/-
**DividedPowerAlgebra.lift_comp_embed** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlg
ebra`。
形式化陈述：lift_comp_embed : (map S f).toLinearMap.comp (embed R M) = ((embed S N).re
strictScalars R).comp f
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `LinearMap.ext`：ext {f g : M ->ₛₗ[σ] M₃} (h : forall x, f x = g x) : f = 
g
· 使用定理 `LinearMap.IsScalarTower.compatibleSMul`：∀ {M : Type u_8} {M₂ : Type u_10
} [inst : AddCommMonoid M] [inst_1 : AddCommMonoid M₂] {R : Type u_14} {S : Type
 u_15}   [inst_2 : Semiring …
· 使用定理 `RingCon.instIsScalarTowerQuotient`：∀ {α : Type u_1} {β : Type u_2} {R : 
Type u_3} [inst : Add R] [inst_1 : MulOneClass R] [inst_2 : SMul α R]   [inst_3 
: IsScalarTower α R R] …
· 使用定理 `IsScalarTower.right`：∀ {R : Type u} {A : Type w} [inst : CommSemiring R]
 [inst_1 : Semiring A] [inst_2 : Algebra R A], IsScalarTower R A A
· 使用定理 `AddMonoidAlgebra.isScalarTower`：∀ {R : Type u_1} {M : Type u_4} {N : Typ
e u_5} {O : Type u_6} [inst : Semiring R] [inst_1 : SMulZeroClass N R]   [inst_2
 : SMulZeroClass O R…
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.map_embed_apply`：map_embed_apply {m : M} : map S f (
embed R M m) = embed S N (f m)
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
theorem lift_comp_embed :
    (map S f).toLinearMap.comp (embed R M) = ((embed S N).restrictScalars R).comp f := by
  ext; simp
/-
**DividedPowerAlgebra.lift_surjective** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlg
ebra`。
形式化陈述：lift_surjective {f : M ->ₗ[R] N} (hf : Function.Surjective f) : Function.S
urjective (map R f)
参数：hf : Function.Surjective f。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `AlgHom.range_eq_top`：∀ {R : Type u} {A : Type v} {B : Type w} [inst : Co
mmSemiring R] [inst_1 : Semiring A] [inst_2 : Algebra R A]   [inst_3 : Semiring 
B] [inst_…
· 使用定理 `Algebra.map_top`：map_top (f : A ->ₐ[R] B) : (⊤ : Subalgebra R A).map f =
 f.range
· 使用定理 `eq_top_iff`：eq_top_iff : a = ⊤ ↔ ⊤ <= a
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用引理 `DividedPowerAlgebra.mkAlgHom_surjective`：mkAlgHom_surjective : Function.
Surjective (RingCon.mkₐ R (ringCon R M))
· 使用定理 `GaloisConnection.le_iff_le`：le_iff_le {a : α} {b : β} : l a <= b ↔ a <= 
u b
· 使用定理 `Subalgebra.gc_map_comap`：gc_map_comap (f : A ->ₐ[R] B) : GaloisConnectio
n (map f) (comap f)
· 使用定理 `MvPolynomial.adjoin_range_X`：adjoin_range_X : Algebra.adjoin R (range (X
 : σ -> MvPolynomial σ R)) = ⊤
· 使用定理 `Algebra.adjoin_le_iff`：adjoin_le_iff {S : Subalgebra R A} : adjoin R s <
= S ↔ s subseteq S
· 使用定理 `implies_congr`：∀ {p₁ p₂ : Sort u} {q₁ q₂ : Sort v}, p₁ = p₂ → q₁ = q₂ → 
(p₁ → q₁) = (p₂ → q₂)
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `Subalgebra.coe_comap`：∀ {R : Type u} {A : Type v} {B : Type w} [inst : C
ommSemiring R] [inst_1 : Semiring A] [inst_2 : Algebra R A]   [inst_3 : Semiring
 B] [inst_…
· 使用定理 `AlgHom.coe_range`：∀ {R : Type u} {A : Type v} {B : Type w} [inst : CommS
emiring R] [inst_1 : Semiring A] [inst_2 : Algebra R A]   [inst_3 : Semiring B] 
[inst_…
· 使用定理 `RingCon.mkₐ_apply`：∀ (α : Type u_1) {R : Type u_3} [inst : CommSemiring 
α] [inst_1 : Semiring R] [inst_2 : Algebra α R] (c : RingCon R)   (r : R), (Ring
Con.mkₐ…
· 使用定理 `DividedPowerAlgebra.map_apply_dp`：map_apply_dp {n : Nat} {a : M} : map S
 f (dp R n a) = dp S n (f a)
· 使用定理 `DividedPowerAlgebra.dp.eq_1`：∀ (R : Type u_2) {M : Type u_3} [inst : Com
mSemiring R] [inst_1 : AddCommMonoid M] [inst_2 : _root_.Module R M] (n : ℕ)   (
m : M), DividedPo…
-/
theorem lift_surjective {f : M →ₗ[R] N} (hf : Function.Surjective f) :
    Function.Surjective (map R f) := by
  rw [← AlgHom.range_eq_top, ← Algebra.map_top (map R f), eq_top_iff,
    ← (AlgHom.range_eq_top (RingCon.mkₐ R (ringCon R N))).mpr mkAlgHom_surjective,
    ← Algebra.map_top, (Subalgebra.gc_map_comap _).le_iff_le, ← MvPolynomial.adjoin_range_X,
    Algebra.adjoin_le_iff]
  intro
  simp only [Set.mem_range, Prod.exists]
  rintro ⟨n, m, rfl⟩
  obtain ⟨l, rfl⟩ := hf m
  simp only [Algebra.map_top, Subalgebra.coe_comap, AlgHom.coe_range, Set.mem_preimage,
    Set.mem_range, RingCon.mkₐ_apply]
  use dp R n l
  rw [map_apply_dp, dp]

end IsScalarTower

end Map

variable (S : Type*) [CommSemiring S] {N : Type*} [AddCommMonoid N] [Module R N] [Module S N]
  (f : M →ₗ[R] N)

section IsScalarTower

variable [Algebra R S] [IsScalarTower R S N] {P : Type*} [AddCommMonoid P] [Module R P]

/-
**DividedPowerAlgebra.map_comp** 是 Mathlib 中的一个引理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：map_comp (f : M ->ₗ[R] N) (g : N ->ₗ[R] P) : map R (g.comp f) = (map R g).
comp (map R f)
参数：f : M ->ₗ[R] N；g : N ->ₗ[R] P。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.algHom_ext_iff`：algHom_ext_iff {A : Type*} [CommSemi
ring A] [Algebra R A] {f g : DividedPowerAlgebra R M ->ₐ[R] A} : f = g ↔ forall 
n m, f (dp R n m) = g (d…
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `DividedPowerAlgebra.map_apply_dp`：map_apply_dp {n : Nat} {a : M} : map S
 f (dp R n a) = dp S n (f a)
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma map_comp (f : M →ₗ[R] N) (g : N →ₗ[R] P) :
    map R (g.comp f) = (map R g).comp (map R f) := by
  rw [algHom_ext_iff]
  intros; simp [map_apply_dp]

@[simp]
/-
**DividedPowerAlgebra.map_id** 是 Mathlib 中的一个引理，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：map_id : map R (LinearMap.id (R
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `DividedPowerAlgebra.algHom_ext_iff`：algHom_ext_iff {A : Type*} [CommSemi
ring A] [Algebra R A] {f g : DividedPowerAlgebra R M ->ₐ[R] A} : f = g ↔ forall 
n m, f (dp R n m) = g (d…
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `DividedPowerAlgebra.map_apply_dp`：map_apply_dp {n : Nat} {a : M} : map S
 f (dp R n a) = dp S n (f a)
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma map_id : map R (LinearMap.id (R := R) (M := M)) = AlgHom.id R _ := by
  rw [algHom_ext_iff]
  intros
  simp [map_apply_dp]

/-- The functoriality map between divided power algebras associated with a linear equivalence of
  the underlying modules. Given an `R`-algebra `S`, an `S`-module `N` and an `R`-linear equivalence
  `f : M →ₗ[R] N`, this is the map `DividedPowerAlgebra R M →ₐ[R] DividedPowerAlgebra S N`
  sending `dp R n m` to `dp S n (f m)`. -/
@[simps!]
/-
**DividedPowerAlgebra.mapEquiv** 是 Mathlib 中的一个定义，位于命名空间 `DividedPowerAlgebra`。
形式化陈述：mapEquiv (g : M ≃ₗ[R] N) : DividedPowerAlgebra R M ≃ₐ[R] DividedPowerAlgeb
ra R N
参数：g : M ≃ₗ[R] N。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The functoriality map between divided power algebras associated with a linear eq
uivalence of
  the underlying modules. Given an `R`-algebra `S`, an `S`-module `N` and an `R`
-linear equivalence
  `f : M →ₗ[R] N`, this is the map `DividedPowerAlgebra R M →ₐ[R] DividedPowerAl
gebra S N`
  sending `dp R n m` to `dp S n (f m)`.
-/
def mapEquiv (g : M ≃ₗ[R] N) :
    DividedPowerAlgebra R M ≃ₐ[R] DividedPowerAlgebra R N :=
  AlgEquiv.ofAlgHom (map R g.toLinearMap) (map R g.symm.toLinearMap)
    (by simp [← map_comp, map_id]) (by simp [← map_comp, map_id])
/-
**DividedPowerAlgebra.mapEquiv_symm** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgeb
ra`。
形式化陈述：mapEquiv_symm (g : M ≃ₗ[R] N) : (mapEquiv g).symm = mapEquiv g.symm
参数：g : M ≃ₗ[R] N。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem mapEquiv_symm (g : M ≃ₗ[R] N) : (mapEquiv g).symm = mapEquiv g.symm := rfl
/-
**DividedPowerAlgebra.LinearEquiv.coe_lift** 是 Mathlib 中的一个定理，位于命名空间 `DividedPow
erAlgebra.LinearEquiv`。
形式化陈述：∀ {R : Type u_2} {M : Type u_3} [inst : CommSemiring R] [inst_1 : AddCommM
onoid M] [inst_2 : _root_.Module R M]   {N : Type u_5} [inst_3 : AddCommMonoid N
] [inst_4 : _root_.Module R N] (g : M ≃ₗ[R] N),   ↑(DividedPowerAlgebra.mapEquiv
 g) = DividedPowerAlgebra.map R ↑g
参数：g : M ≃ₗ[R] N；DividedPowerAlgebra.mapEquiv g。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem LinearEquiv.coe_lift (g : M ≃ₗ[R] N) : mapEquiv g = map R g.toLinearMap := rfl
/-
**DividedPowerAlgebra.LinearEquiv.coe_lift_symm** 是 Mathlib 中的一个定理，位于命名空间 `Divid
edPowerAlgebra.LinearEquiv`。
形式化陈述：∀ {R : Type u_2} {M : Type u_3} [inst : CommSemiring R] [inst_1 : AddCommM
onoid M] [inst_2 : _root_.Module R M]   {N : Type u_5} [inst_3 : AddCommMonoid N
] [inst_4 : _root_.Module R N] (g : M ≃ₗ[R] N),   ↑(DividedPowerAlgebra.mapEquiv
 g).symm = DividedPowerAlgebra.map R ↑g.symm
参数：g : M ≃ₗ[R] N；DividedPowerAlgebra.mapEquiv g。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem LinearEquiv.coe_lift_symm (g : M ≃ₗ[R] N) :
    (mapEquiv g).symm = map R g.symm.toLinearMap := rfl
/-
**DividedPowerAlgebra.mapEquiv_refl** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlgeb
ra`。
形式化陈述：mapEquiv_refl : mapEquiv (LinearEquiv.refl R M) = AlgEquiv.refl
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `AlgEquiv.coe_toAlgHom_injective`：coe_toAlgHom_injective : Function.Injec
tive ((↑) : (A₁ ≃ₐ[R] A₂) -> A₁ ->ₐ[R] A₂)
· 使用引理 `DividedPowerAlgebra.map_id`：map_id : map R (LinearMap.id (R
-/
theorem mapEquiv_refl : mapEquiv (LinearEquiv.refl R M) = AlgEquiv.refl :=
  AlgEquiv.coe_toAlgHom_injective map_id
/-
**DividedPowerAlgebra.mapEquiv_trans** 是 Mathlib 中的一个定理，位于命名空间 `DividedPowerAlge
bra`。
形式化陈述：mapEquiv_trans (g : M ≃ₗ[R] N) (h : N ≃ₗ[R] P) : (mapEquiv g).trans (mapEq
uiv h) = mapEquiv (g.trans h)
参数：g : M ≃ₗ[R] N；h : N ≃ₗ[R] P。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `AlgEquiv.coe_toAlgHom_injective`：coe_toAlgHom_injective : Function.Injec
tive ((↑) : (A₁ ≃ₐ[R] A₂) -> A₁ ->ₐ[R] A₂)
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用引理 `DividedPowerAlgebra.map_comp`：map_comp (f : M ->ₗ[R] N) (g : N ->ₗ[R] P)
 : map R (g.comp f) = (map R g).comp (map R f)
-/
theorem mapEquiv_trans (g : M ≃ₗ[R] N) (h : N ≃ₗ[R] P) :
    (mapEquiv g).trans (mapEquiv h) = mapEquiv (g.trans h) :=
  AlgEquiv.coe_toAlgHom_injective (map_comp _ _).symm

end IsScalarTower

end Functoriality

end DividedPowerAlgebra

