/-
Copyright (c) 2024 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne
-/
module

public import Mathlib.MeasureTheory.MeasurableSpace.CountablyGenerated
public import Mathlib.Probability.Process.Filtration

/-!
# Filtration built from the finite partitions of a countably generated measurable space

In a countably generated measurable space `α`, we can build a sequence of finer and finer finite
measurable partitions of the space such that the measurable space is generated by the union of all
partitions.
This sequence of partitions is defined in `MeasureTheory.MeasurableSpace.CountablyGenerated`.

Here, we build the filtration of the measurable spaces generated by `countablePartition α n` for all
`n : ℕ`, which we call `countableFiltration α`.
Since each measurable space in the filtration is finite, we can easily build measurable functions on
those spaces. A potential application of `countableFiltration α` is to build a martingale with
respect to that filtration and use the martingale convergence theorems to define a measurable
function on `α`.

## Main definitions

* `ProbabilityTheory.partitionFiltration`: for a sequence of sets `t : ℕ → Set α`, a filtration
  built from the measurable spaces generated by `memPartition t n` for all `n : ℕ`.
* `ProbabilityTheory.countableFiltration`: A filtration built from the measurable spaces generated
  by `countablePartition α n` for all `n : ℕ`.

## Main statements

* `ProbabilityTheory.iSup_partitionFiltration`: `⨆ n, partitionFiltration α n` is the measurable
  space on `α`.

-/

@[expose] public section

open MeasureTheory MeasurableSpace

namespace ProbabilityTheory

section MemPartition

variable {α : Type*} [m : MeasurableSpace α] {t : Nat -> Set α}

/--
Definition of `partitionFiltration` / `partitionFiltration` 的定义

English:
definition partitionFiltration
  signature: (ht : forall n, MeasurableSet (t n))
  body: generateFrom (memPartition t n)
  mono' := monotone_nat_of_le_succ (generateFrom_memPartition_le_succ _)
  le' := generateFrom_memPartition_le ht

中文:
定义 partitionFiltration
  签名: (ht : 对任意 n, 可测集 (t n))
  定义体: generateFrom (memPartition t n)
  mono' := monotone_nat_of_le_succ (generateFrom_memPartition_le_succ _)
  le' := generateFrom_memPartition_le ht

Depends on / 依赖: generateFrom, memPartition
-/
def partitionFiltration (ht : forall n, MeasurableSet (t n)) :
    Filtration Nat m where
  seq n := generateFrom (memPartition t n)
  mono' := monotone_nat_of_le_succ (generateFrom_memPartition_le_succ _)
  le' := generateFrom_memPartition_le ht

/--
lemma `measurableSet_partitionFiltration_of_mem` / 引理 `measurableSet_partitionFiltration_of_mem`

English:
lemma measurableSet_partitionFiltration_of_mem
  statement: (ht : forall n, MeasurableSet (t n)) (n : Nat) {s : Set α}
  proof: measurableSet_generateFrom hs

中文:
引理 measurableSet_partitionFiltration_of_mem
  结论: (ht : 对任意 n, 可测集 (t n)) (n : 自然数) {s : 集合 α}
  证明: measurableSet_generateFrom hs

Depends on / 依赖: measurableSet_generateFrom
-/
lemma measurableSet_partitionFiltration_of_mem (ht : forall n, MeasurableSet (t n)) (n : Nat) {s : Set α}
    (hs : s in memPartition t n) :
    MeasurableSet[partitionFiltration ht n] s :=
  measurableSet_generateFrom hs

/--
lemma `measurableSet_partitionFiltration_memPartitionSet` / 引理 `measurableSet_partitionFiltration_memPartitionSet`

English:
lemma measurableSet_partitionFiltration_memPartitionSet
  statement: (ht : forall n, MeasurableSet (t n))
  proof: measurableSet_partitionFiltration_of_mem ht n (memPartitionSet_mem t n a)

中文:
引理 measurableSet_partitionFiltration_memPartitionSet
  结论: (ht : 对任意 n, 可测集 (t n))
  证明: measurableSet_partitionFiltration_of_mem ht n (memPartitionSet_mem t n a)

Depends on / 依赖: measurableSet_partitionFiltration_of_mem, memPartitionSet_mem
-/
lemma measurableSet_partitionFiltration_memPartitionSet (ht : forall n, MeasurableSet (t n))
    (n : Nat) (a : α) :
    MeasurableSet[partitionFiltration ht n] (memPartitionSet t n a) :=
  measurableSet_partitionFiltration_of_mem ht n (memPartitionSet_mem t n a)

/--
lemma `measurable_memPartitionSet_subtype` / 引理 `measurable_memPartitionSet_subtype`

English:
lemma measurable_memPartitionSet_subtype
  statement: (ht : forall n, MeasurableSet (t n)) (n : Nat)
  proof: by
  refine @measurable_to_countable' (memPartition t n) α m _
    (partitionFiltration ht n) _ (fun s => ?_)
  rcases s with ⟨s, hs⟩
  suffices MeasurableSet[partitionFiltration ht n] {x | memPartitionSet t n x = s} by
    convert! this
    ext x
    simp
  simp_rw [memPartitionSet_eq_iff _ hs]
  e

中文:
引理 measurable_memPartitionSet_subtype
  结论: (ht : 对任意 n, 可测集 (t n)) (n : 自然数)
  证明: by
  refine @measurable_to_countable' (memPartition t n) α m _
    (partitionFiltration ht n) _ (fun s => ?_)
  rcases s with ⟨s, hs⟩
  suffices MeasurableSet[partitionFiltration ht n] {x | memPartitionSet t n x = s} by
    convert! this
    ext x
    simp
  simp_rw [memPartitionSet_eq_iff _ hs]
  e

Depends on / 依赖: MeasurableSet, convert, measurableSet_partitionFiltration_of_mem, measurable_to_countable, memPartition, memPartitionSet, memPartitionSet_eq_iff, partitionFiltration, simp_rw
-/
lemma measurable_memPartitionSet_subtype (ht : forall n, MeasurableSet (t n)) (n : Nat)
    (m : MeasurableSpace (memPartition t n)) :
    @Measurable α (memPartition t n) (partitionFiltration ht n) m
      (fun a => ⟨memPartitionSet t n a, memPartitionSet_mem t n a⟩) := by
  refine @measurable_to_countable' (memPartition t n) α m _
    (partitionFiltration ht n) _ (fun s => ?_)
  rcases s with ⟨s, hs⟩
  suffices MeasurableSet[partitionFiltration ht n] {x | memPartitionSet t n x = s} by
    convert! this
    ext x
    simp
  simp_rw [memPartitionSet_eq_iff _ hs]
  exact measurableSet_partitionFiltration_of_mem _ _ hs

/--
lemma `measurable_partitionFiltration_memPartitionSet` / 引理 `measurable_partitionFiltration_memPartitionSet`

English:
lemma measurable_partitionFiltration_memPartitionSet
  given: (ht : forall n, MeasurableSet (t n)) (n : Nat)
  proof: measurable_subtype_coe.comp (measurable_memPartitionSet_subtype ht _ _)

中文:
引理 measurable_partitionFiltration_memPartitionSet
  条件: (ht : 对任意 n, 可测集 (t n)) (n : 自然数)
  证明: measurable_subtype_coe.comp (measurable_memPartitionSet_subtype ht _ _)

Depends on / 依赖: measurable_memPartitionSet_subtype, measurable_subtype_coe, measurable_subtype_coe.comp
-/
lemma measurable_partitionFiltration_memPartitionSet (ht : forall n, MeasurableSet (t n)) (n : Nat) :
    Measurable[partitionFiltration ht n] (memPartitionSet t n) :=
  measurable_subtype_coe.comp (measurable_memPartitionSet_subtype ht _ _)

/--
lemma `measurable_memPartitionSet` / 引理 `measurable_memPartitionSet`

English:
lemma measurable_memPartitionSet
  given: (ht : forall n, MeasurableSet (t n)) (n : Nat)
  proof: (measurable_partitionFiltration_memPartitionSet ht n).mono ((partitionFiltration ht).le n) le_rfl

中文:
引理 measurable_memPartitionSet
  条件: (ht : 对任意 n, 可测集 (t n)) (n : 自然数)
  证明: (measurable_partitionFiltration_memPartitionSet ht n).mono ((partitionFiltration ht).le n) le_rfl

Depends on / 依赖: le_rfl, measurable_partitionFiltration_memPartitionSet, partitionFiltration
-/
lemma measurable_memPartitionSet (ht : forall n, MeasurableSet (t n)) (n : Nat) :
    Measurable (memPartitionSet t n) :=
  (measurable_partitionFiltration_memPartitionSet ht n).mono ((partitionFiltration ht).le n) le_rfl

/--
lemma `iSup_partitionFiltration_eq_generateFrom_range` / 引理 `iSup_partitionFiltration_eq_generateFrom_range`

English:
lemma iSup_partitionFiltration_eq_generateFrom_range
  given: (ht : forall n, MeasurableSet (t n))
  proof: by
  conv_rhs => rw [← generateFrom_iUnion_memPartition t, ← iSup_generateFrom]
  rfl

中文:
引理 iSup_partitionFiltration_eq_generateFrom_range
  条件: (ht : 对任意 n, 可测集 (t n))
  证明: by
  conv_rhs => rw [← generateFrom_iUnion_memPartition t, ← iSup_generateFrom]
  rfl

Depends on / 依赖: conv_rhs, generateFrom_iUnion_memPartition, iSup_generateFrom
-/
lemma iSup_partitionFiltration_eq_generateFrom_range (ht : forall n, MeasurableSet (t n)) :
    ⨆ n, partitionFiltration ht n = generateFrom (Set.range t) := by
  conv_rhs => rw [← generateFrom_iUnion_memPartition t, ← iSup_generateFrom]
  rfl

/--
lemma `iSup_partitionFiltration` / 引理 `iSup_partitionFiltration`

English:
lemma iSup_partitionFiltration
  statement: (ht : forall n, MeasurableSet (t n))
  proof: by
  rw [iSup_partitionFiltration_eq_generateFrom_range ht]; rw [ht_range]

中文:
引理 iSup_partitionFiltration
  结论: (ht : 对任意 n, 可测集 (t n))
  证明: by
  rw [iSup_partitionFiltration_eq_generateFrom_range ht]; rw [ht_range]

Depends on / 依赖: ht_range, iSup_partitionFiltration_eq_generateFrom_range
-/
lemma iSup_partitionFiltration (ht : forall n, MeasurableSet (t n))
    (ht_range : generateFrom (Set.range t) = m) :
    ⨆ n, partitionFiltration ht n = m := by
  rw [iSup_partitionFiltration_eq_generateFrom_range ht]; rw [ht_range]

end MemPartition

section CountableFiltration

variable {α : Type*} [MeasurableSpace α] [CountablyGenerated α]

-- Note: `Set` has no computational content, but Lean still attempts to compile it.
-- See https://github.com/leanprover/lean4/issues/14084.
/--
Definition of `countableFiltration` / `countableFiltration` 的定义

English:
definition countableFiltration
  signature: (α : Type*) [m : MeasurableSpace α] [CountablyGenerated α]
  body: generateFrom (countablePartition α n)
  mono' := monotone_nat_of_le_succ (generateFrom_countablePartition_le_succ _)
  le' := generateFrom_countablePartition_le α

中文:
定义 countableFiltration
  签名: (α : 类型) [m : 可测空间 α] [余untablyGenerated α]
  定义体: generateFrom (countablePartition α n)
  mono' := monotone_nat_of_le_succ (generateFrom_countablePartition_le_succ _)
  le' := generateFrom_countablePartition_le α

Depends on / 依赖: countablePartition, generateFrom
-/
noncomputable def countableFiltration (α : Type*) [m : MeasurableSpace α] [CountablyGenerated α] :
    Filtration Nat m where
  seq n := generateFrom (countablePartition α n)
  mono' := monotone_nat_of_le_succ (generateFrom_countablePartition_le_succ _)
  le' := generateFrom_countablePartition_le α

/--
lemma `measurableSet_countableFiltration_of_mem` / 引理 `measurableSet_countableFiltration_of_mem`

English:
lemma measurableSet_countableFiltration_of_mem
  statement: (n : Nat) {s : Set α}
  proof: measurableSet_generateFrom hs

中文:
引理 measurableSet_countableFiltration_of_mem
  结论: (n : 自然数) {s : 集合 α}
  证明: measurableSet_generateFrom hs

Depends on / 依赖: measurableSet_generateFrom
-/
lemma measurableSet_countableFiltration_of_mem (n : Nat) {s : Set α}
    (hs : s in countablePartition α n) :
    MeasurableSet[countableFiltration α n] s :=
  measurableSet_generateFrom hs

/--
lemma `measurableSet_countableFiltration_countablePartitionSet` / 引理 `measurableSet_countableFiltration_countablePartitionSet`

English:
lemma measurableSet_countableFiltration_countablePartitionSet
  given: (n : Nat) (t : α)
  proof: measurableSet_countableFiltration_of_mem n (countablePartitionSet_mem n t)

中文:
引理 measurableSet_countableFiltration_countablePartitionSet
  条件: (n : 自然数) (t : α)
  证明: measurableSet_countableFiltration_of_mem n (countablePartitionSet_mem n t)

Depends on / 依赖: countablePartitionSet_mem, measurableSet_countableFiltration_of_mem
-/
lemma measurableSet_countableFiltration_countablePartitionSet (n : Nat) (t : α) :
    MeasurableSet[countableFiltration α n] (countablePartitionSet n t) :=
  measurableSet_countableFiltration_of_mem n (countablePartitionSet_mem n t)

/--
lemma `measurable_countablePartitionSet_subtype` / 引理 `measurable_countablePartitionSet_subtype`

English:
lemma measurable_countablePartitionSet_subtype
  statement: (n : Nat)
  proof: measurable_memPartitionSet_subtype
    (measurableSet_enumerateCountable_countableGeneratingSet (α := α)) n m

中文:
引理 measurable_countablePartitionSet_subtype
  结论: (n : 自然数)
  证明: measurable_memPartitionSet_subtype
    (measurableSet_enumerateCountable_countableGeneratingSet (α := α)) n m

Depends on / 依赖: measurableSet_enumerateCountable_countableGeneratingSet, measurable_memPartitionSet_subtype
-/
lemma measurable_countablePartitionSet_subtype (n : Nat)
    (m : MeasurableSpace (countablePartition α n)) :
    @Measurable α (countablePartition α n) (countableFiltration α n) m
      (fun a => ⟨countablePartitionSet n a, countablePartitionSet_mem n a⟩) :=
  measurable_memPartitionSet_subtype
    (measurableSet_enumerateCountable_countableGeneratingSet (α := α)) n m

/--
lemma `measurable_countableFiltration_countablePartitionSet` / 引理 `measurable_countableFiltration_countablePartitionSet`

English:
lemma measurable_countableFiltration_countablePartitionSet
  statement: (α : Type*)
  proof: measurable_subtype_coe.comp (measurable_countablePartitionSet_subtype _ _)

中文:
引理 measurable_countableFiltration_countablePartitionSet
  结论: (α : 类型)
  证明: measurable_subtype_coe.comp (measurable_countablePartitionSet_subtype _ _)

Depends on / 依赖: measurable_countablePartitionSet_subtype, measurable_subtype_coe, measurable_subtype_coe.comp
-/
lemma measurable_countableFiltration_countablePartitionSet (α : Type*)
    [MeasurableSpace α] [CountablyGenerated α] (n : Nat) :
    Measurable[countableFiltration α n] (countablePartitionSet n) :=
  measurable_subtype_coe.comp (measurable_countablePartitionSet_subtype _ _)

/--
lemma `measurable_countablePartitionSet` / 引理 `measurable_countablePartitionSet`

English:
lemma measurable_countablePartitionSet
  statement: (α : Type*) [MeasurableSpace α] [CountablyGenerated α]
  proof: (measurable_countableFiltration_countablePartitionSet α n).mono ((countableFiltration α).le n)
    le_rfl

中文:
引理 measurable_countablePartitionSet
  结论: (α : 类型) [可测空间 α] [余untablyGenerated α]
  证明: (measurable_countableFiltration_countablePartitionSet α n).mono ((countableFiltration α).le n)
    le_rfl
-/
lemma measurable_countablePartitionSet (α : Type*) [MeasurableSpace α] [CountablyGenerated α]
    (n : Nat) :
    Measurable (countablePartitionSet (α := α) n) :=
  (measurable_countableFiltration_countablePartitionSet α n).mono ((countableFiltration α).le n)
    le_rfl

/--
lemma `iSup_countableFiltration` / 引理 `iSup_countableFiltration`

English:
lemma iSup_countableFiltration
  given: (α : Type*) [m : MeasurableSpace α] [CountablyGenerated α]
  proof: by
  conv_rhs => rw [← generateFrom_iUnion_countablePartition α, ← iSup_generateFrom]
  rfl

中文:
引理 iSup_countableFiltration
  条件: (α : 类型) [m : 可测空间 α] [余untablyGenerated α]
  证明: by
  conv_rhs => rw [← generateFrom_iUnion_countablePartition α, ← iSup_generateFrom]
  rfl

Depends on / 依赖: conv_rhs, generateFrom_iUnion_countablePartition, iSup_generateFrom
-/
lemma iSup_countableFiltration (α : Type*) [m : MeasurableSpace α] [CountablyGenerated α] :
    ⨆ n, countableFiltration α n = m := by
  conv_rhs => rw [← generateFrom_iUnion_countablePartition α, ← iSup_generateFrom]
  rfl

end CountableFiltration

end ProbabilityTheory
