/-
Copyright (c) 2025 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/

module

public import Mathlib.NumberTheory.ModularForms.EisensteinSeries.E2.Summable
public import Mathlib.LinearAlgebra.Matrix.FixedDetMatrices

/-!
# Slash action on E2

## Overview

This file proves how the weight-2 Eisenstein series `E2` (and `G2`) transforms under the
slash action of `SL₂(ℤ)`. Unlike modular forms of weight `k ≥ 4`, the
functions `G2` and `E2` are **not** modular forms because they acquire a correction term under
the action of `S = [[0, -1], [1, 0]]`.

## Main Results

* **`G2_T_transform`**: `G2` is invariant under `T = [[1, 1], [0, 1]]`:
  `G₂|[2] T = G₂`


* **`G2_S_transform`**: The transformation under `S` involves a correction term:
  `G₂(z) = z⁻² G₂(-1/z) - 2πi/z`

  Equivalently: `G₂|[2] S = G₂ - D₂(S)`

* **`G2_slash_action`**: For any `γ ∈ SL₂(ℤ)`:
  `G₂|[2] γ = G₂ - D₂(γ)`

  where `D₂(γ)` is a correction term satisfying a cocycle condition.

* **`E2_slash_action`**: The normalized version:
  `E₂|[2] γ = E₂ - (1/(2ζ(2))) D₂(γ)`

## Proof Strategy

The proof of `G2_S_transform` is the heart of this file. The strategy is:

1. **Write as absolutely convergent series**: Express `G2` as an absolutely convergent double sum
   by adding and subtracting telescoping terms:
   `G₂(z) = 2ζ(2) + ∑' m n, 1/((mz+n)²(mz+n+1)) + δ(m,n)`
   where `δ` is a correction for boundary terms.

2. **Swapping summation order**: The S-action on `G2` corresponds to swapping the roles of
   `m` and `n`. After writing as an abs. conv. series, we can legitimately swap the order because
   the series is absolutely convergent.

3. **The correction term**: The difference between the two orderings of summation
   is precisely the term `-2πi/z`, which comes from the results in the Summable file
   (`tsum_symmetricIco_tsum_sub_eq` vs `tsum_tsum_symmetricIco_sub_eq`).

4. **General γ**: Since `SL₂(ℤ)` is generated by `S` and `T`, and we've
   computed the transformation under both generators, we can deduce the transformation under
   any element using the cocycle property of `D₂`.

## References
* P. Bruin and S. Dahmen, Modular Forms, https://www.few.vu.nl/~sdn249/modularforms16/notes.pdf

-/

open UpperHalfPlane hiding I

open ModularForm ModularGroup Filter Complex MatrixGroups Set SummationFilter

open scoped Real Topology

noncomputable section

namespace EisensteinSeries

/--
Definition of `δ` / `δ` 的定义

English:
definition δ
  signature: (x : Fin 2 -> Int)
  body: if x = ![0, 0] then 1 else if x = ![0, -1] then 2 else 0

@[simp]

中文:
定义 δ
  签名: (x : 有限集 2 -> 整数)
  定义体: if x = ![0, 0] then 1 else if x = ![0, -1] then 2 else 0

@[simp]
-/
def δ (x : Fin 2 -> Int) : Complex := if x = ![0, 0] then 1 else if x = ![0, -1] then 2 else 0

@[simp]
/--
lemma `δ_eq` / 引理 `δ_eq`

English:
lemma δ_eq
  statement: δ ![0, 0] = 1
  proof: by simp [δ]

@[simp]

中文:
引理 δ_eq
  结论: δ ![0, 0] = 1
  证明: by simp [δ]

@[simp]
-/
lemma δ_eq : δ ![0, 0] = 1 := by simp [δ]

@[simp]
/--
lemma `δ_eq_two` / 引理 `δ_eq_two`

English:
lemma δ_eq_two
  statement: δ ![0, -1] = 2
  proof: by simp [δ]

中文:
引理 δ_eq_two
  结论: δ ![0, -1] = 2
  证明: by simp [δ]
-/
lemma δ_eq_two : δ ![0, -1] = 2 := by simp [δ]

/--
lemma `δ_eventually_cofinite` / 引理 `δ_eventually_cofinite`

English:
lemma δ_eventually_cofinite
  statement: δ =ᶠ[cofinite] 0
  proof: by
  filter_upwards [eventually_cofinite_ne ![0, 0], eventually_cofinite_ne ![0, -1]] with x hx hx'
  simp_all [δ]

中文:
引理 δ_eventually_cofinite
  结论: δ =ᶠ[cofinite] 0
  证明: by
  filter_upwards [eventually_cofinite_ne ![0, 0], eventually_cofinite_ne ![0, -1]] with x hx hx'
  simp_all [δ]

Depends on / 依赖: eventually_cofinite_ne, filter_upwards
-/
lemma δ_eventually_cofinite : δ =ᶠ[cofinite] 0 := by
  filter_upwards [eventually_cofinite_ne ![0, 0], eventually_cofinite_ne ![0, -1]] with x hx hx'
  simp_all [δ]

/--
Definition of `G2Term` / `G2Term` 的定义

English:
abbreviation G2Term
  signature: (z : ℍ) (m : Fin 2 -> Int)
  body: (((m 0 : Complex) * z + m 1) ^ 2 * (m 0 * z + m 1 + 1))⁻¹ + δ m

中文:
缩写 G2Term
  签名: (z : ℍ) (m : 有限集 2 -> 整数)
  定义体: (((m 0 : Complex) * z + m 1) ^ 2 * (m 0 * z + m 1 + 1))⁻¹ + δ m
-/
abbrev G2Term (z : ℍ) (m : Fin 2 -> Int) : Complex :=
    (((m 0 : Complex) * z + m 1) ^ 2 * (m 0 * z + m 1 + 1))⁻¹ + δ m

/--
lemma `G2Term_summable` / 引理 `G2Term_summable`

English:
lemma G2Term_summable
  given: (z : ℍ)
  statement: Summable (G2Term z)
  proof: by
  have H : Summable fun m => G2Term z m - δ m := by
    simp_rw [G2Term, add_sub_cancel_right]
    apply summable_of_isBigO_rpow_norm (a := 3) (by linarith)
    simpa [pow_three, pow_two, ← mul_assoc] using ((isBigO_linear_add_const_vec z 0 1).mul
      (isBigO_linear_add_const_vec z 0 0)).mul (isBigO_linear_add_const_vec z 0 0)
exact H.congr_cofinite δ_eventually_cofinite.mp .of_forall by simp +contextual

中文:
引理 G2Term_summable
  条件: (z : ℍ)
  结论: Summable (G2Term z)
  证明: by
  have H : Summable fun m => G2Term z m - δ m := by
    simp_rw [G2Term, add_sub_cancel_right]
    apply summable_of_isBigO_rpow_norm (a := 3) (by linarith)
    simpa [pow_three, pow_two, ← mul_assoc] using ((isBigO_linear_add_const_vec z 0 1).mul
      (isBigO_linear_add_const_vec z 0 0)).mul (isBigO_linear_add_const_vec z 0 0)
exact H.congr_cofinite δ_eventually_cofinite.mp .of_forall by simp +contextual

Depends on / 依赖: G2Term, H.congr_cofinite, Summable, _eventually_cofinite.mp, add_sub_cancel_right, congr_cofinite, contextual, isBigO_linear_add_const_vec, mul_assoc, of_forall, pow_three, pow_two, simp_rw, summable_of_isBigO_rpow_norm
-/
lemma G2Term_summable (z : ℍ) : Summable (G2Term z) := by
  have H : Summable fun m => G2Term z m - δ m := by
    simp_rw [G2Term, add_sub_cancel_right]
    apply summable_of_isBigO_rpow_norm (a := 3) (by linarith)
    simpa [pow_three, pow_two, ← mul_assoc] using ((isBigO_linear_add_const_vec z 0 1).mul
      (isBigO_linear_add_const_vec z 0 0)).mul (isBigO_linear_add_const_vec z 0 0)
exact H.congr_cofinite δ_eventually_cofinite.mp .of_forall by simp +contextual

--This is the version we use the most.
/--
lemma `G2Term_prod_summable` / 引理 `G2Term_prod_summable`

English:
lemma G2Term_prod_summable
  given: (z : ℍ)
  statement: Summable (fun p : Int × Int => G2Term z ![p.1, p.2])
  proof: by
  apply (finTwoArrowEquiv _).symm.summable_iff.mpr (G2Term_summable z)

中文:
引理 G2Term_prod_summable
  条件: (z : ℍ)
  结论: Summable (fun p : 整数 × 整数 => G2Term z ![p.1, p.2])
  证明: by
  apply (finTwoArrowEquiv _).symm.summable_iff.mpr (G2Term_summable z)

Depends on / 依赖: G2Term_summable, finTwoArrowEquiv, summable_iff, symm.summable_iff.mpr
-/
lemma G2Term_prod_summable (z : ℍ) : Summable (fun p : Int × Int => G2Term z ![p.1, p.2]) := by
  apply (finTwoArrowEquiv _).symm.summable_iff.mpr (G2Term_summable z)

/--
lemma `aux_identity` / 引理 `aux_identity`

English:
lemma aux_identity
  given: (z : ℍ) (b n : Int)
  statement: ((b : Complex) * z + n + 1)⁻¹ * (((b : Complex) * z + n) ^ 2)⁻¹ +
  proof: by
  by_cases h : b = 0 ∧ n = 0
  · simp [h.1, h.2]
  · simp only [not_and] at h
    by_cases hb : b = 0
    · by_cases hn : n = -1
      · simp [hb, hn, δ_eq_two]
        ring
      · have hn0 : (n : Complex) != 0 := by aesop
        have hn1 : (n : Complex) + 1 != 0 := by norm_cast; grind
        simp [δ, h, hb, hn]
        grind
    · have h0 : (b : Complex) * z + n + 1 != 0 := by
        simpa [add_assoc] using linear_ne_zero (cd := ![b, n + 1]) z (by aesop)
      have h1 : (b : Complex) * z + n != 0 := linear_ne_zero (cd := ![b, n]) z (by aesop)
      simp [δ]
      grind

中文:
引理 aux_identity
  条件: (z : ℍ) (b n : 整数)
  结论: ((b : 复形) * z + n + 1)⁻¹ * (((b : 复形) * z + n) ^ 2)⁻¹ +
  证明: by
  by_cases h : b = 0 ∧ n = 0
  · simp [h.1, h.2]
  · simp only [not_and] at h
    by_cases hb : b = 0
    · by_cases hn : n = -1
      · simp [hb, hn, δ_eq_two]
        ring
      · have hn0 : (n : Complex) != 0 := by aesop
        have hn1 : (n : Complex) + 1 != 0 := by norm_cast; grind
        simp [δ, h, hb, hn]
        grind
    · have h0 : (b : Complex) * z + n + 1 != 0 := by
        simpa [add_assoc] using linear_ne_zero (cd := ![b, n + 1]) z (by aesop)
      have h1 : (b : Complex) * z + n != 0 := linear_ne_zero (cd := ![b, n]) z (by aesop)
      simp [δ]
      grind

Depends on / 依赖: add_assoc, linear_ne_zero, not_and
-/
lemma aux_identity (z : ℍ) (b n : Int) : ((b : Complex) * z + n + 1)⁻¹ * (((b : Complex) * z + n) ^ 2)⁻¹ +
    (δ ![b, n]) + (((b : Complex) * z + n)⁻¹ - ((b : Complex) * z + n + 1)⁻¹) = (((b : Complex) * z + n) ^ 2)⁻¹ := by
  by_cases h : b = 0 ∧ n = 0
  · simp [h.1, h.2]
  · simp only [not_and] at h
    by_cases hb : b = 0
    · by_cases hn : n = -1
      · simp [hb, hn, δ_eq_two]
        ring
      · have hn0 : (n : Complex) != 0 := by aesop
        have hn1 : (n : Complex) + 1 != 0 := by norm_cast; grind
        simp [δ, h, hb, hn]
        grind
    · have h0 : (b : Complex) * z + n + 1 != 0 := by
        simpa [add_assoc] using linear_ne_zero (cd := ![b, n + 1]) z (by aesop)
      have h1 : (b : Complex) * z + n != 0 := linear_ne_zero (cd := ![b, n]) z (by aesop)
      simp [δ]
      grind

/--
lemma `G2_eq_tsum_G2Term` / 引理 `G2_eq_tsum_G2Term`

English:
lemma G2_eq_tsum_G2Term
  given: (z : ℍ)
  statement: G2 z = ∑' m, ∑' n, G2Term z ![m, n]
  proof: by
  set t := ∑' m, ∑' n, (G2Term z ![m, n])
  rw [G2]; rw [show t = t + 0 by ring]; rw [← tsum_tsum_symmetricIco_sub_eq z]; rw [← Summable.tsum_add]
  · rw [← tsum_eq_of_summable_unconditional (L := symmetricIcc Int)]
    · congr with a
      rw [e2Summand]; rw [tsum_eq_of_summable_unconditional
        (summable_right_one_div_linear_sub_one_div_linear_succ z a)]; rw [← Summable.tsum_add
        ((G2Term_prod_summable z).prod_factor _)
        (summable_right_one_div_linear_sub_one_div_linear_succ z a)]
      exact tsum_congr (fun b => by simp [eisSummand, G2Term, aux_identity z a b, zpow_ofNat])
    · simpa only [tsum_symmetricIco_linear_sub_linear_add_one_eq_zero z, add_zero]
        using (G2Term_prod_summable z).prod
  · exact (G2Term_prod_summable z).prod
  · exact summable_zero.congr
      fun b => by simp [← tsum_symmetricIco_linear_sub_linear_add_one_eq_zero z b]

中文:
引理 G2_eq_tsum_G2Term
  条件: (z : ℍ)
  结论: G2 z = ∑' m, ∑' n, G2Term z ![m, n]
  证明: by
  set t := ∑' m, ∑' n, (G2Term z ![m, n])
  rw [G2]; rw [show t = t + 0 by ring]; rw [← tsum_tsum_symmetricIco_sub_eq z]; rw [← Summable.tsum_add]
  · rw [← tsum_eq_of_summable_unconditional (L := symmetricIcc Int)]
    · congr with a
      rw [e2Summand]; rw [tsum_eq_of_summable_unconditional
        (summable_right_one_div_linear_sub_one_div_linear_succ z a)]; rw [← Summable.tsum_add
        ((G2Term_prod_summable z).prod_factor _)
        (summable_right_one_div_linear_sub_one_div_linear_succ z a)]
      exact tsum_congr (fun b => by simp [eisSummand, G2Term, aux_identity z a b, zpow_ofNat])
    · simpa only [tsum_symmetricIco_linear_sub_linear_add_one_eq_zero z, add_zero]
        using (G2Term_prod_summable z).prod
  · exact (G2Term_prod_summable z).prod
  · exact summable_zero.congr
      fun b => by simp [← tsum_symmetricIco_linear_sub_linear_add_one_eq_zero z b]

Depends on / 依赖: G2Term, G2Term_prod_summable, Summable, Summable.tsum_add, e2Summand, prod_factor, summable_right_one_div_linear_sub_one_div_linear_succ, symmetricIcc, tsum_add, tsum_congr, tsum_eq_of_summable_unconditional, tsum_tsum_symmetricIco_sub_eq
-/
lemma G2_eq_tsum_G2Term (z : ℍ) : G2 z = ∑' m, ∑' n, G2Term z ![m, n] := by
  set t := ∑' m, ∑' n, (G2Term z ![m, n])
  rw [G2]; rw [show t = t + 0 by ring]; rw [← tsum_tsum_symmetricIco_sub_eq z]; rw [← Summable.tsum_add]
  · rw [← tsum_eq_of_summable_unconditional (L := symmetricIcc Int)]
    · congr with a
      rw [e2Summand]; rw [tsum_eq_of_summable_unconditional
        (summable_right_one_div_linear_sub_one_div_linear_succ z a)]; rw [← Summable.tsum_add
        ((G2Term_prod_summable z).prod_factor _)
        (summable_right_one_div_linear_sub_one_div_linear_succ z a)]
      exact tsum_congr (fun b => by simp [eisSummand, G2Term, aux_identity z a b, zpow_ofNat])
    · simpa only [tsum_symmetricIco_linear_sub_linear_add_one_eq_zero z, add_zero]
        using (G2Term_prod_summable z).prod
  · exact (G2Term_prod_summable z).prod
  · exact summable_zero.congr
      fun b => by simp [← tsum_symmetricIco_linear_sub_linear_add_one_eq_zero z b]

/--
lemma `G2_S_action_eq_tsum_G2Term` / 引理 `G2_S_action_eq_tsum_G2Term`

English:
lemma G2_S_action_eq_tsum_G2Term
  given: (z : ℍ)
  statement: ((z : Complex) ^ 2)⁻¹ * G2 (S • z) - -2 * π * I / z =
  proof: by
  rw [← tsum_symmetricIco_tsum_sub_eq z]; rw [← tsum_symmetricIco_tsum_eq_S_act z]; rw [← tsum_eq_of_summable_unconditional (L := symmetricIco Int)]; rw [← Summable.tsum_sub]
  · apply tsum_congr (fun N => ?_)
    rw [← Summable.tsum_sub]
    · apply tsum_congr (fun M => ?_)
      simp only [one_div, G2Term, Fin.isValue, Matrix.cons_val_zero, Matrix.cons_val_one,
        Matrix.cons_val_fin_one, mul_inv_rev]
      nth_rw 1 [← aux_identity z M N]
      ring
    · simpa using! linear_left_summable (ne_zero z) N le_rfl
    · simpa [add_assoc] using! summable_left_one_div_linear_sub_one_div_linear z N (N + 1)
  · apply HasSum.summable (a := (z.1 ^ 2)⁻¹ * G2 (S • z))
    rw [hasSum_symmetricIco_int_iff]
    apply (tendsto_double_sum_S_act z).congr (fun x => ?_)
    rw [Summable.tsum_finsetSum (fun i hi => ?_)]
    simpa using! linear_left_summable (ne_zero z) i (k := 2) (by norm_num)
  · apply HasSum.summable (a := -2 * π * I / z)
    rw [hasSum_symmetricIco_int_iff]; rw [← tendsto_comp_val_Ioi_atTop]
    exact tendsto_tsum_one_div_linear_sub_succ_eq z
  · have := G2Term_summable z
    rw [← ((finTwoArrowEquiv _).trans (.prodComm ..)).symm.summable_iff] at this
    exact this.prod

中文:
引理 G2_S_action_eq_tsum_G2Term
  条件: (z : ℍ)
  结论: ((z : 复形) ^ 2)⁻¹ * G2 (S • z) - -2 * π * I / z =
  证明: by
  rw [← tsum_symmetricIco_tsum_sub_eq z]; rw [← tsum_symmetricIco_tsum_eq_S_act z]; rw [← tsum_eq_of_summable_unconditional (L := symmetricIco Int)]; rw [← Summable.tsum_sub]
  · apply tsum_congr (fun N => ?_)
    rw [← Summable.tsum_sub]
    · apply tsum_congr (fun M => ?_)
      simp only [one_div, G2Term, Fin.isValue, Matrix.cons_val_zero, Matrix.cons_val_one,
        Matrix.cons_val_fin_one, mul_inv_rev]
      nth_rw 1 [← aux_identity z M N]
      ring
    · simpa using! linear_left_summable (ne_zero z) N le_rfl
    · simpa [add_assoc] using! summable_left_one_div_linear_sub_one_div_linear z N (N + 1)
  · apply HasSum.summable (a := (z.1 ^ 2)⁻¹ * G2 (S • z))
    rw [hasSum_symmetricIco_int_iff]
    apply (tendsto_double_sum_S_act z).congr (fun x => ?_)
    rw [Summable.tsum_finsetSum (fun i hi => ?_)]
    simpa using! linear_left_summable (ne_zero z) i (k := 2) (by norm_num)
  · apply HasSum.summable (a := -2 * π * I / z)
    rw [hasSum_symmetricIco_int_iff]; rw [← tendsto_comp_val_Ioi_atTop]
    exact tendsto_tsum_one_div_linear_sub_succ_eq z
  · have := G2Term_summable z
    rw [← ((finTwoArrowEquiv _).trans (.prodComm ..)).symm.summable_iff] at this
    exact this.prod

Depends on / 依赖: Fin.isValue, G2Term, Matrix, Matrix.cons_val_fin_one, Matrix.cons_val_one, Matrix.cons_val_zero, Summable, Summable.tsum_sub, add_asso, aux_identity, cons_val_fin_one, cons_val_one, cons_val_zero, isValue, le_rfl, linear_left_summable, mul_inv_rev, ne_zero, nth_rw, one_div
-/
lemma G2_S_action_eq_tsum_G2Term (z : ℍ) : ((z : Complex) ^ 2)⁻¹ * G2 (S • z) - -2 * π * I / z =
    ∑' n : Int, ∑' m : Int, G2Term z ![m, n] := by
  rw [← tsum_symmetricIco_tsum_sub_eq z]; rw [← tsum_symmetricIco_tsum_eq_S_act z]; rw [← tsum_eq_of_summable_unconditional (L := symmetricIco Int)]; rw [← Summable.tsum_sub]
  · apply tsum_congr (fun N => ?_)
    rw [← Summable.tsum_sub]
    · apply tsum_congr (fun M => ?_)
      simp only [one_div, G2Term, Fin.isValue, Matrix.cons_val_zero, Matrix.cons_val_one,
        Matrix.cons_val_fin_one, mul_inv_rev]
      nth_rw 1 [← aux_identity z M N]
      ring
    · simpa using! linear_left_summable (ne_zero z) N le_rfl
    · simpa [add_assoc] using! summable_left_one_div_linear_sub_one_div_linear z N (N + 1)
  · apply HasSum.summable (a := (z.1 ^ 2)⁻¹ * G2 (S • z))
    rw [hasSum_symmetricIco_int_iff]
    apply (tendsto_double_sum_S_act z).congr (fun x => ?_)
    rw [Summable.tsum_finsetSum (fun i hi => ?_)]
    simpa using! linear_left_summable (ne_zero z) i (k := 2) (by norm_num)
  · apply HasSum.summable (a := -2 * π * I / z)
    rw [hasSum_symmetricIco_int_iff]; rw [← tendsto_comp_val_Ioi_atTop]
    exact tendsto_tsum_one_div_linear_sub_succ_eq z
  · have := G2Term_summable z
    rw [← ((finTwoArrowEquiv _).trans (.prodComm ..)).symm.summable_iff] at this
    exact this.prod

/--
lemma `tsum_G2Term_eq_tsum` / 引理 `tsum_G2Term_eq_tsum`

English:
lemma tsum_G2Term_eq_tsum
  given: (z : ℍ)
  statement: ∑' (m : Fin 2 -> Int), G2Term z m =
  proof: by
  rw [← (finTwoArrowEquiv _).symm.tsum_eq]
  exact Summable.tsum_prod' (G2Term_prod_summable z) ((G2Term_prod_summable z).prod_factor)

中文:
引理 tsum_G2Term_eq_tsum
  条件: (z : ℍ)
  结论: ∑' (m : 有限集 2 -> 整数), G2Term z m =
  证明: by
  rw [← (finTwoArrowEquiv _).symm.tsum_eq]
  exact Summable.tsum_prod' (G2Term_prod_summable z) ((G2Term_prod_summable z).prod_factor)

Depends on / 依赖: G2Term_prod_summable, Summable, Summable.tsum_prod, finTwoArrowEquiv, prod_factor, symm.tsum_eq, tsum_eq, tsum_prod
-/
lemma tsum_G2Term_eq_tsum (z : ℍ) : ∑' (m : Fin 2 -> Int), G2Term z m =
    ∑' m : Int, ∑' n : Int, G2Term z ![m, n] := by
  rw [← (finTwoArrowEquiv _).symm.tsum_eq]
  exact Summable.tsum_prod' (G2Term_prod_summable z) ((G2Term_prod_summable z).prod_factor)

/--
lemma `tsum_G2Term_eq_tsum'` / 引理 `tsum_G2Term_eq_tsum'`

English:
lemma tsum_G2Term_eq_tsum'
  given: (z : ℍ)
  statement: ∑' (m : Fin 2 -> Int), G2Term z m =
  proof: by
  rw [Summable.tsum_comm']; rw [tsum_G2Term_eq_tsum]
  · exact G2Term_prod_summable z
  · exact (G2Term_prod_summable z).prod_factor
  · have H := G2Term_summable z
    rw [← ((finTwoArrowEquiv _).trans (.prodComm ..)).symm.summable_iff] at H
    exact H.prod_factor


@[expose] public section

中文:
引理 tsum_G2Term_eq_tsum'
  条件: (z : ℍ)
  结论: ∑' (m : 有限集 2 -> 整数), G2Term z m =
  证明: by
  rw [Summable.tsum_comm']; rw [tsum_G2Term_eq_tsum]
  · exact G2Term_prod_summable z
  · exact (G2Term_prod_summable z).prod_factor
  · have H := G2Term_summable z
    rw [← ((finTwoArrowEquiv _).trans (.prodComm ..)).symm.summable_iff] at H
    exact H.prod_factor


@[expose] public section

Depends on / 依赖: G2Term_prod_summable, G2Term_summable, H.prod_factor, Summable, Summable.tsum_comm, finTwoArrowEquiv, prodComm, prod_factor, summable_iff, symm.summable_iff, tsum_G2Term_eq_tsum, tsum_comm
-/
lemma tsum_G2Term_eq_tsum' (z : ℍ) : ∑' (m : Fin 2 -> Int), G2Term z m =
    ∑' n : Int, ∑' m : Int, G2Term z ![m, n] := by
  rw [Summable.tsum_comm']; rw [tsum_G2Term_eq_tsum]
  · exact G2Term_prod_summable z
  · exact (G2Term_prod_summable z).prod_factor
  · have H := G2Term_summable z
    rw [← ((finTwoArrowEquiv _).trans (.prodComm ..)).symm.summable_iff] at H
    exact H.prod_factor


@[expose] public section

section transform

/--
lemma `G2_S_transform` / 引理 `G2_S_transform`

English:
lemma G2_S_transform
  given: (z : ℍ)
  statement: G2 z = ((z : Complex) ^ 2)⁻¹ * G2 (S • z) - -2 * π * I / z
  proof: by
  rw [G2_S_action_eq_tsum_G2Term]; rw [G2_eq_tsum_G2Term z]; rw [← tsum_G2Term_eq_tsum']; rw [tsum_G2Term_eq_tsum]

中文:
引理 G2_S_transform
  条件: (z : ℍ)
  结论: G2 z = ((z : 复形) ^ 2)⁻¹ * G2 (S • z) - -2 * π * I / z
  证明: by
  rw [G2_S_action_eq_tsum_G2Term]; rw [G2_eq_tsum_G2Term z]; rw [← tsum_G2Term_eq_tsum']; rw [tsum_G2Term_eq_tsum]

Depends on / 依赖: G2_S_action_eq_tsum_G2Term, G2_eq_tsum_G2Term, tsum_G2Term_eq_tsum
-/
lemma G2_S_transform (z : ℍ) : G2 z = ((z : Complex) ^ 2)⁻¹ * G2 (S • z) - -2 * π * I / z := by
  rw [G2_S_action_eq_tsum_G2Term]; rw [G2_eq_tsum_G2Term z]; rw [← tsum_G2Term_eq_tsum']; rw [tsum_G2Term_eq_tsum]

set_option backward.isDefEq.respectTransparency.types false in
/--
lemma `G2_T_transform` / 引理 `G2_T_transform`

English:
lemma G2_T_transform
  statement: G2 ∣[(2 : Int)] T = G2
  proof: by
  ext z
  simp_rw [SL_slash_def, modular_T_smul z]
  simp [G2_eq_tsum_cexp, T, denom_apply, ← exp_periodic.nat_mul 1 (2 * π * I * z)]
  grind

中文:
引理 G2_T_transform
  结论: G2 ∣[(2 : 整数)] T = G2
  证明: by
  ext z
  simp_rw [SL_slash_def, modular_T_smul z]
  simp [G2_eq_tsum_cexp, T, denom_apply, ← exp_periodic.nat_mul 1 (2 * π * I * z)]
  grind

Depends on / 依赖: G2_eq_tsum_cexp, SL_slash_def, denom_apply, exp_periodic, exp_periodic.nat_mul, modular_T_smul, nat_mul, simp_rw
-/
lemma G2_T_transform : G2 ∣[(2 : Int)] T = G2 := by
  ext z
  simp_rw [SL_slash_def, modular_T_smul z]
  simp [G2_eq_tsum_cexp, T, denom_apply, ← exp_periodic.nat_mul 1 (2 * π * I * z)]
  grind

/--
lemma `G2_slash_action` / 引理 `G2_slash_action`

English:
lemma G2_slash_action
  given: (γ : SL(2, Int))
  statement: G2 ∣[(2 : Int)] γ = G2 - D2 γ
  proof: by
  have : γ in Subgroup.closure {S, T} := by simp [SpecialLinearGroup.SL2Z_generators]
  induction this using Subgroup.closure_induction with
  | one => simp only [SlashAction.slash_one, D2_one, sub_zero]
  | mem g hg =>
      simp only [mem_insert_iff, mem_singleton_iff] at hg
      rcases hg with (h1 | h2)
      · ext z
        simp only [Pi.sub_apply, h1, D2_S z, SlashInvariantForm.slash_S_apply G2 2 z, mul_comm,
          G2_S_transform z, modular_S_smul]
        ring_nf
        aesop
      · simpa only [h2, D2_T, sub_zero] using G2_T_transform
  | mul g h _ _ ig ih =>
      rw [D2_mul]; rw [SlashAction.slash_mul]; rw [ig]; rw [sub_eq_add_neg]; rw [SlashAction.add_slash]; rw [ih]
      grind [SlashAction.neg_slash, SL_slash]
  | inv g _ ig =>
      have H1 : (G2 ∣[(2 : Int)] g) ∣[(2 : Int)] g⁻¹ = (G2 - D2 g) ∣[(2 : Int)] g⁻¹ := by
        rw [ig]
      simp_rw [← SlashAction.slash_mul, sub_eq_add_neg, SlashAction.add_slash, mul_inv_cancel,
        SlashAction.slash_one, SL_slash, SlashAction.neg_slash] at H1
      nth_rw 2 [H1]
      have := D2_inv g
      simp only [SL_slash] at this
      rw [← sub_eq_add_neg]; rw [this]; rw [SL_slash]; rw [sub_neg_eq_add]; rw [add_sub_cancel_right]

中文:
引理 G2_slash_action
  条件: (γ : SL(2, 整数))
  结论: G2 ∣[(2 : 整数)] γ = G2 - D2 γ
  证明: by
  have : γ in Subgroup.closure {S, T} := by simp [SpecialLinearGroup.SL2Z_generators]
  induction this using Subgroup.closure_induction with
  | one => simp only [SlashAction.slash_one, D2_one, sub_zero]
  | mem g hg =>
      simp only [mem_insert_iff, mem_singleton_iff] at hg
      rcases hg with (h1 | h2)
      · ext z
        simp only [Pi.sub_apply, h1, D2_S z, SlashInvariantForm.slash_S_apply G2 2 z, mul_comm,
          G2_S_transform z, modular_S_smul]
        ring_nf
        aesop
      · simpa only [h2, D2_T, sub_zero] using G2_T_transform
  | mul g h _ _ ig ih =>
      rw [D2_mul]; rw [SlashAction.slash_mul]; rw [ig]; rw [sub_eq_add_neg]; rw [SlashAction.add_slash]; rw [ih]
      grind [SlashAction.neg_slash, SL_slash]
  | inv g _ ig =>
      have H1 : (G2 ∣[(2 : Int)] g) ∣[(2 : Int)] g⁻¹ = (G2 - D2 g) ∣[(2 : Int)] g⁻¹ := by
        rw [ig]
      simp_rw [← SlashAction.slash_mul, sub_eq_add_neg, SlashAction.add_slash, mul_inv_cancel,
        SlashAction.slash_one, SL_slash, SlashAction.neg_slash] at H1
      nth_rw 2 [H1]
      have := D2_inv g
      simp only [SL_slash] at this
      rw [← sub_eq_add_neg]; rw [this]; rw [SL_slash]; rw [sub_neg_eq_add]; rw [add_sub_cancel_right]

Depends on / 依赖: D2_S, D2_T, D2_one, G2_S_transform, G2_T_transform, Pi.sub_apply, SL2Z_generators, SlashAction, SlashAction.slash_one, SlashInvariantForm, SlashInvariantForm.slash_S_apply, SpecialLinearGroup, SpecialLinearGroup.SL2Z_generators, Subgroup, Subgroup.closure, Subgroup.closure_induction, closure, closure_induction, mem_insert_iff, mem_singleton_iff
-/
lemma G2_slash_action (γ : SL(2, Int)) : G2 ∣[(2 : Int)] γ = G2 - D2 γ := by
  have : γ in Subgroup.closure {S, T} := by simp [SpecialLinearGroup.SL2Z_generators]
  induction this using Subgroup.closure_induction with
  | one => simp only [SlashAction.slash_one, D2_one, sub_zero]
  | mem g hg =>
      simp only [mem_insert_iff, mem_singleton_iff] at hg
      rcases hg with (h1 | h2)
      · ext z
        simp only [Pi.sub_apply, h1, D2_S z, SlashInvariantForm.slash_S_apply G2 2 z, mul_comm,
          G2_S_transform z, modular_S_smul]
        ring_nf
        aesop
      · simpa only [h2, D2_T, sub_zero] using G2_T_transform
  | mul g h _ _ ig ih =>
      rw [D2_mul]; rw [SlashAction.slash_mul]; rw [ig]; rw [sub_eq_add_neg]; rw [SlashAction.add_slash]; rw [ih]
      grind [SlashAction.neg_slash, SL_slash]
  | inv g _ ig =>
      have H1 : (G2 ∣[(2 : Int)] g) ∣[(2 : Int)] g⁻¹ = (G2 - D2 g) ∣[(2 : Int)] g⁻¹ := by
        rw [ig]
      simp_rw [← SlashAction.slash_mul, sub_eq_add_neg, SlashAction.add_slash, mul_inv_cancel,
        SlashAction.slash_one, SL_slash, SlashAction.neg_slash] at H1
      nth_rw 2 [H1]
      have := D2_inv g
      simp only [SL_slash] at this
      rw [← sub_eq_add_neg]; rw [this]; rw [SL_slash]; rw [sub_neg_eq_add]; rw [add_sub_cancel_right]

/--
lemma `E2_slash_action` / 引理 `E2_slash_action`

English:
lemma E2_slash_action
  given: (γ : SL(2, Int))
  statement: E2 ∣[(2 : Int)] γ = E2 - (1 / (2 * riemannZeta 2)) • D2 γ
  proof: by
  ext z
  simp [E2, SL_smul_slash, G2_slash_action γ, mul_sub]

中文:
引理 E2_slash_action
  条件: (γ : SL(2, 整数))
  结论: E2 ∣[(2 : 整数)] γ = E2 - (1 / (2 * riemannZeta 2)) • D2 γ
  证明: by
  ext z
  simp [E2, SL_smul_slash, G2_slash_action γ, mul_sub]

Depends on / 依赖: G2_slash_action, SL_smul_slash, mul_sub
-/
lemma E2_slash_action (γ : SL(2, Int)) : E2 ∣[(2 : Int)] γ = E2 - (1 / (2 * riemannZeta 2)) • D2 γ := by
  ext z
  simp [E2, SL_smul_slash, G2_slash_action γ, mul_sub]

end transform

end

end EisensteinSeries
