/-
Copyright (c) 2018 Johannes Hölzl. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Johannes Hölzl, Kenny Lau, Johan Commelin, Mario Carneiro, Kevin Buzzard,
Amelia Livingston, Yury Kudryashov
-/
module

public import Mathlib.Algebra.Group.Submonoid.Pointwise
public import Mathlib.Algebra.Module.Defs
public import Mathlib.Data.Nat.Cast.Basic

/-!
# Elementwise monoid structure of additive submonoids

These definitions are a cut-down versions of the ones around `Submodule.mul`, as that API is
usually more useful.

`SMul (AddSubmonoid R) (AddSubmonoid A)` is also provided given `DistribSMul R A`,
and when `R = A` it is definitionally equal to the multiplication on `AddSubmonoid R`.

These are all available in the `Pointwise` locale.

Additionally, it provides various degrees of monoid structure:
* `AddSubmonoid.one`
* `AddSubmonoid.mul`
* `AddSubmonoid.mulOneClass`
* `AddSubmonoid.semigroup`
* `AddSubmonoid.monoid`

which is available globally to match the monoid structure implied by `Submodule.idemSemiring`.

## Implementation notes

Many results about multiplication are derived from the corresponding results about scalar
multiplication, but results requiring right distributivity do not have SMul versions,
due to the lack of a suitable typeclass (unless one goes all the way to `Module`).
-/

@[expose] public section

open AddSubmonoid Set
open scoped Pointwise

variable {M R A : Type*}

namespace AddSubmonoid
section AddMonoidWithOne
variable [AddMonoidWithOne R]

/-- If `R` is an additive monoid with one (e.g., a semiring), then `1 : AddSubmonoid R` is the range
of `Nat.cast : ℕ → R`. -/
@[instance_reducible]
/--
Definition of `one` / `one` 的定义

English:
definition one
  signature: : One (AddSubmonoid R)
  body: ⟨AddMonoidHom.mrange (Nat.castAddMonoidHom R)⟩

scoped[Pointwise] attribute [instance] AddSubmonoid.one

中文:
定义 one
  签名: : 幺 (加法子幺半群 R)
  定义体: ⟨AddMonoidHom.mrange (Nat.castAddMonoidHom R)⟩

scoped[Pointwise] attribute [instance] AddSubmonoid.one
-/
protected def one : One (AddSubmonoid R) := ⟨AddMonoidHom.mrange (Nat.castAddMonoidHom R)⟩

scoped[Pointwise] attribute [instance] AddSubmonoid.one

/--
lemma `one_eq_mrange` / 引理 `one_eq_mrange`

English:
lemma one_eq_mrange
  statement: (1 : AddSubmonoid R) = AddMonoidHom.mrange (Nat.castAddMonoidHom R)
  proof: rfl

中文:
引理 one_eq_mrange
  结论: (1 : 加法子幺半群 R) = 加法幺半群态射.mrange (自然数.castAddMonoidHom R)
  证明: rfl
-/
lemma one_eq_mrange : (1 : AddSubmonoid R) = AddMonoidHom.mrange (Nat.castAddMonoidHom R) := rfl

/--
lemma `natCast_mem_one` / 引理 `natCast_mem_one`

English:
lemma natCast_mem_one
  given: (n : Nat)
  statement: (n : R) in (1 : AddSubmonoid R)
  proof: ⟨_, rfl⟩

中文:
引理 natCast_mem_one
  条件: (n : 自然数)
  结论: (n : R) in (1 : 加法子幺半群 R)
  证明: ⟨_, rfl⟩
-/
lemma natCast_mem_one (n : Nat) : (n : R) in (1 : AddSubmonoid R) := ⟨_, rfl⟩

/--
lemma `mem_one` / 引理 `mem_one`

English:
lemma mem_one
  given: {x : R}
  statement: x in (1 : AddSubmonoid R) ↔ exists n : Nat, ↑n = x
  proof: .rfl

中文:
引理 mem_one
  条件: {x : R}
  结论: x in (1 : 加法子幺半群 R) ↔ 存在 n : 自然数, ↑n = x
  证明: .rfl
-/
@[simp] lemma mem_one {x : R} : x in (1 : AddSubmonoid R) ↔ exists n : Nat, ↑n = x := .rfl

/--
lemma `one_eq_closure` / 引理 `one_eq_closure`

English:
lemma one_eq_closure
  statement: (1 : AddSubmonoid R) = closure {1}
  proof: by
  rw [closure_singleton_eq]; rw [one_eq_mrange]; congr 1; ext; simp

中文:
引理 one_eq_closure
  结论: (1 : 加法子幺半群 R) = closure {1}
  证明: by
  rw [closure_singleton_eq]; rw [one_eq_mrange]; congr 1; ext; simp

Depends on / 依赖: closure_singleton_eq, one_eq_mrange
-/
lemma one_eq_closure : (1 : AddSubmonoid R) = closure {1} := by
  rw [closure_singleton_eq]; rw [one_eq_mrange]; congr 1; ext; simp

/--
lemma `one_eq_closure_one_set` / 引理 `one_eq_closure_one_set`

English:
lemma one_eq_closure_one_set
  statement: (1 : AddSubmonoid R) = closure 1
  proof: one_eq_closure

中文:
引理 one_eq_closure_one_set
  结论: (1 : 加法子幺半群 R) = closure 1
  证明: one_eq_closure

Depends on / 依赖: one_eq_closure
-/
lemma one_eq_closure_one_set : (1 : AddSubmonoid R) = closure 1 := one_eq_closure

end AddMonoidWithOne

section SMul
variable [AddMonoid R] [AddMonoid A] [DistribSMul R A]

/-- For `M : Submonoid R` and `N : AddSubmonoid A`, `M • N` is the additive submonoid
generated by all `m • n` where `m ∈ M` and `n ∈ N`. -/
@[instance_reducible]
/--
Definition of `smul` / `smul` 的定义

English:
definition smul
  signature: : SMul (AddSubmonoid R) (AddSubmonoid A) where
  body: ⨆ s : M, N.map (DistribSMul.toAddMonoidHom A s.1)

scoped[Pointwise] attribute [instance] AddSubmonoid.smul

中文:
定义 smul
  签名: : 标量乘法 (加法子幺半群 R) (加法子幺半群 A) where
  定义体: ⨆ s : M, N.map (DistribSMul.toAddMonoidHom A s.1)

scoped[Pointwise] attribute [instance] AddSubmonoid.smul
-/
protected def smul : SMul (AddSubmonoid R) (AddSubmonoid A) where
  smul M N := ⨆ s : M, N.map (DistribSMul.toAddMonoidHom A s.1)

scoped[Pointwise] attribute [instance] AddSubmonoid.smul

variable {M M' : AddSubmonoid R} {N P : AddSubmonoid A} {m : R} {n : A}

/--
lemma `smul_mem_smul` / 引理 `smul_mem_smul`

English:
lemma smul_mem_smul
  given: (hm : m in M) (hn : n in N)
  statement: m • n in M • N
  proof: (le_iSup _ ⟨m, hm⟩ : _ <= M • N) ⟨n, hn, by rfl⟩

中文:
引理 smul_mem_smul
  条件: (hm : m in M) (hn : n in N)
  结论: m • n in M • N
  证明: (le_iSup _ ⟨m, hm⟩ : _ <= M • N) ⟨n, hn, by rfl⟩

Depends on / 依赖: le_iSup
-/
lemma smul_mem_smul (hm : m in M) (hn : n in N) : m • n in M • N :=
  (le_iSup _ ⟨m, hm⟩ : _ <= M • N) ⟨n, hn, by rfl⟩

/--
lemma `smul_le` / 引理 `smul_le`

English:
lemma smul_le
  statement: M • N <= P ↔ forall m in M, forall n in N, m • n in P
  proof: ⟨fun H _m hm _n hn => H smul_mem_smul hm hn, fun H =>
    iSup_le fun ⟨m, hm⟩ => map_le_iff_le_comap.2 fun n hn => H m hm n hn⟩

@[elab_as_elim]

中文:
引理 smul_le
  结论: M • N <= P ↔ 对任意 m in M, 对任意 n in N, m • n in P
  证明: ⟨fun H _m hm _n hn => H smul_mem_smul hm hn, fun H =>
    iSup_le fun ⟨m, hm⟩ => map_le_iff_le_comap.2 fun n hn => H m hm n hn⟩

@[elab_as_elim]

Depends on / 依赖: iSup_le, map_le_iff_le_comap, smul_mem_smul
-/
lemma smul_le : M • N <= P ↔ forall m in M, forall n in N, m • n in P :=
⟨fun H _m hm _n hn => H smul_mem_smul hm hn, fun H =>
    iSup_le fun ⟨m, hm⟩ => map_le_iff_le_comap.2 fun n hn => H m hm n hn⟩

@[elab_as_elim]
/--
lemma `smul_induction_on` / 引理 `smul_induction_on`

English:
lemma smul_induction_on
  statement: {C : A -> Prop} {a : A} (ha : a in M • N)
  proof: (@smul_le _ _ _ _ _ _ _ ⟨⟨Set.ofPred C, hadd _ _⟩, by
    simpa only [smul_zero] using! hm _ (zero_mem _) _ (zero_mem _)⟩).2 hm ha

@[simp]

中文:
引理 smul_induction_on
  结论: {C : A -> 命题} {a : A} (ha : a in M • N)
  证明: (@smul_le _ _ _ _ _ _ _ ⟨⟨Set.ofPred C, hadd _ _⟩, by
    simpa only [smul_zero] using! hm _ (zero_mem _) _ (zero_mem _)⟩).2 hm ha

@[simp]
-/
protected lemma smul_induction_on {C : A -> Prop} {a : A} (ha : a in M • N)
    (hm : forall m in M, forall n in N, C (m • n)) (hadd : forall x y, C x -> C y -> C (x + y)) : C a :=
  (@smul_le _ _ _ _ _ _ _ ⟨⟨Set.ofPred C, hadd _ _⟩, by
    simpa only [smul_zero] using! hm _ (zero_mem _) _ (zero_mem _)⟩).2 hm ha

@[simp]
/--
lemma `addSubmonoid_smul_bot` / 引理 `addSubmonoid_smul_bot`

English:
lemma addSubmonoid_smul_bot
  given: (S : AddSubmonoid R)
  statement: S • (⊥ : AddSubmonoid A) = ⊥
  proof: eq_bot_iff.2 smul_le.2 fun m _ n hn => by
    rw [AddSubmonoid.mem_bot] at hn ⊢; rw [hn, smul_zero]

中文:
引理 addSubmonoid_smul_bot
  条件: (S : 加法子幺半群 R)
  结论: S • (⊥ : 加法子幺半群 A) = ⊥
  证明: eq_bot_iff.2 smul_le.2 fun m _ n hn => by
    rw [AddSubmonoid.mem_bot] at hn ⊢; rw [hn, smul_zero]

Depends on / 依赖: AddSubmonoid, AddSubmonoid.mem_bot, eq_bot_iff, mem_bot, smul_le, smul_zero
-/
lemma addSubmonoid_smul_bot (S : AddSubmonoid R) : S • (⊥ : AddSubmonoid A) = ⊥ :=
eq_bot_iff.2 smul_le.2 fun m _ n hn => by
    rw [AddSubmonoid.mem_bot] at hn ⊢; rw [hn, smul_zero]

/--
lemma `smul_le_smul` / 引理 `smul_le_smul`

English:
lemma smul_le_smul
  given: (h : M <= M') (hnp : N <= P)
  statement: M • N <= M' • P
  proof: smul_le.2 fun _m hm _n hn => smul_mem_smul (h hm) (hnp hn)

中文:
引理 smul_le_smul
  条件: (h : M <= M') (hnp : N <= P)
  结论: M • N <= M' • P
  证明: smul_le.2 fun _m hm _n hn => smul_mem_smul (h hm) (hnp hn)

Depends on / 依赖: smul_le, smul_mem_smul
-/
lemma smul_le_smul (h : M <= M') (hnp : N <= P) : M • N <= M' • P :=
  smul_le.2 fun _m hm _n hn => smul_mem_smul (h hm) (hnp hn)

/--
lemma `smul_le_smul_left` / 引理 `smul_le_smul_left`

English:
lemma smul_le_smul_left
  given: (h : M <= M')
  statement: M • P <= M' • P
  proof: smul_le_smul h le_rfl

中文:
引理 smul_le_smul_left
  条件: (h : M <= M')
  结论: M • P <= M' • P
  证明: smul_le_smul h le_rfl

Depends on / 依赖: le_rfl, smul_le_smul
-/
lemma smul_le_smul_left (h : M <= M') : M • P <= M' • P := smul_le_smul h le_rfl
/--
lemma `smul_le_smul_right` / 引理 `smul_le_smul_right`

English:
lemma smul_le_smul_right
  given: (h : N <= P)
  statement: M • N <= M • P
  proof: smul_le_smul le_rfl h

中文:
引理 smul_le_smul_right
  条件: (h : N <= P)
  结论: M • N <= M • P
  证明: smul_le_smul le_rfl h

Depends on / 依赖: le_rfl, smul_le_smul
-/
lemma smul_le_smul_right (h : N <= P) : M • N <= M • P := smul_le_smul le_rfl h

/--
lemma `smul_subset_smul` / 引理 `smul_subset_smul`

English:
lemma smul_subset_smul
  statement: (↑M : Set R) • (↑N : Set A) subseteq (↑(M • N) : Set A)
  proof: smul_subset_iff.2 fun _i hi _j hj => smul_mem_smul hi hj

中文:
引理 smul_subset_smul
  结论: (↑M : 集合 R) • (↑N : 集合 A) subseteq (↑(M • N) : 集合 A)
  证明: smul_subset_iff.2 fun _i hi _j hj => smul_mem_smul hi hj

Depends on / 依赖: smul_mem_smul, smul_subset_iff
-/
lemma smul_subset_smul : (↑M : Set R) • (↑N : Set A) subseteq (↑(M • N) : Set A) :=
  smul_subset_iff.2 fun _i hi _j hj => smul_mem_smul hi hj

/--
lemma `addSubmonoid_smul_sup` / 引理 `addSubmonoid_smul_sup`

English:
lemma addSubmonoid_smul_sup
  statement: M • (N ⊔ P) = M • N ⊔ M • P
  proof: le_antisymm (smul_le.mpr fun m hm np hnp => by
    refine closure_induction (motive := (fun _ => _ • · in _)) ?_ ?_ ?_ (sup_eq_closure N P ▸ hnp)
    · rintro x (hx | hx)
      exacts [le_sup_left (a := M • N) (smul_mem_smul hm hx),
        le_sup_right (a := M • N) (smul_mem_smul hm hx)]
    · apply (smul_zero (A := A) m).symm ▸ (M • N ⊔ M • P).zero_mem
    · intro _ _ _ _ h1 h2; rw [smul_add]; exact add_mem h1 h2)
  (sup_le (smul_le_smul_right le_sup_left) <| smul_le_smul_right le_sup_right)

中文:
引理 addSubmonoid_smul_sup
  结论: M • (N ⊔ P) = M • N ⊔ M • P
  证明: le_antisymm (smul_le.mpr fun m hm np hnp => by
    refine closure_induction (motive := (fun _ => _ • · in _)) ?_ ?_ ?_ (sup_eq_closure N P ▸ hnp)
    · rintro x (hx | hx)
      exacts [le_sup_left (a := M • N) (smul_mem_smul hm hx),
        le_sup_right (a := M • N) (smul_mem_smul hm hx)]
    · apply (smul_zero (A := A) m).symm ▸ (M • N ⊔ M • P).zero_mem
    · intro _ _ _ _ h1 h2; rw [smul_add]; exact add_mem h1 h2)
  (sup_le (smul_le_smul_right le_sup_left) <| smul_le_smul_right le_sup_right)

Depends on / 依赖: add_mem, closure_induction, exacts, le_antisymm, le_sup_left, le_sup_right, motive, smul_add, smul_le, smul_le.mpr, smul_le_smul_right, smul_mem_smul, smul_zero, sup_eq_closure, sup_le, zero_mem
-/
lemma addSubmonoid_smul_sup : M • (N ⊔ P) = M • N ⊔ M • P :=
  le_antisymm (smul_le.mpr fun m hm np hnp => by
    refine closure_induction (motive := (fun _ => _ • · in _)) ?_ ?_ ?_ (sup_eq_closure N P ▸ hnp)
    · rintro x (hx | hx)
      exacts [le_sup_left (a := M • N) (smul_mem_smul hm hx),
        le_sup_right (a := M • N) (smul_mem_smul hm hx)]
    · apply (smul_zero (A := A) m).symm ▸ (M • N ⊔ M • P).zero_mem
    · intro _ _ _ _ h1 h2; rw [smul_add]; exact add_mem h1 h2)
  (sup_le (smul_le_smul_right le_sup_left) <| smul_le_smul_right le_sup_right)

variable {ι : Sort*}

/--
lemma `smul_iSup` / 引理 `smul_iSup`

English:
lemma smul_iSup
  given: (T : AddSubmonoid R) (S : ι -> AddSubmonoid A)
  statement: (T • ⨆ i, S i) = ⨆ i, T • S i
  proof: le_antisymm (smul_le.mpr fun t ht s hs => iSup_induction _ (motive := (t • · in _)) hs
    (fun i s hs => mem_iSup_of_mem i <| smul_mem_smul ht hs)
    (by simp_rw [smul_zero]; apply zero_mem) fun x y => by simp_rw [smul_add]; apply add_mem)
  (iSup_le fun i => smul_le_smul_right <| le_iSup _ i)

中文:
引理 smul_iSup
  条件: (T : 加法子幺半群 R) (S : ι -> 加法子幺半群 A)
  结论: (T • ⨆ i, S i) = ⨆ i, T • S i
  证明: le_antisymm (smul_le.mpr fun t ht s hs => iSup_induction _ (motive := (t • · in _)) hs
    (fun i s hs => mem_iSup_of_mem i <| smul_mem_smul ht hs)
    (by simp_rw [smul_zero]; apply zero_mem) fun x y => by simp_rw [smul_add]; apply add_mem)
  (iSup_le fun i => smul_le_smul_right <| le_iSup _ i)

Depends on / 依赖: add_mem, iSup_induction, iSup_le, le_antisymm, le_iSup, mem_iSup_of_mem, motive, simp_rw, smul_add, smul_le, smul_le.mpr, smul_le_smul_right, smul_mem_smul, smul_zero, zero_mem
-/
lemma smul_iSup (T : AddSubmonoid R) (S : ι -> AddSubmonoid A) : (T • ⨆ i, S i) = ⨆ i, T • S i :=
  le_antisymm (smul_le.mpr fun t ht s hs => iSup_induction _ (motive := (t • · in _)) hs
    (fun i s hs => mem_iSup_of_mem i <| smul_mem_smul ht hs)
    (by simp_rw [smul_zero]; apply zero_mem) fun x y => by simp_rw [smul_add]; apply add_mem)
  (iSup_le fun i => smul_le_smul_right <| le_iSup _ i)

end SMul

section NonUnitalNonAssocSemiring
variable [NonUnitalNonAssocSemiring R] {M N P : AddSubmonoid R}

/-- Multiplication of additive submonoids of a semiring R. The additive submonoid `S * T` is the
smallest R-submodule of `R` containing the elements `s * t` for `s ∈ S` and `t ∈ T`. -/
@[instance_reducible]
/--
Definition of `mul` / `mul` 的定义

English:
definition mul
  signature: : Mul (AddSubmonoid R)
  body: ⟨fun M N => ⨆ s : M, N.map (AddMonoidHom.mul s.1)⟩

scoped[Pointwise] attribute [instance] AddSubmonoid.mul

中文:
定义 mul
  签名: : 乘法 (加法子幺半群 R)
  定义体: ⟨fun M N => ⨆ s : M, N.map (AddMonoidHom.mul s.1)⟩

scoped[Pointwise] attribute [instance] AddSubmonoid.mul
-/
protected def mul : Mul (AddSubmonoid R) := ⟨fun M N => ⨆ s : M, N.map (AddMonoidHom.mul s.1)⟩

scoped[Pointwise] attribute [instance] AddSubmonoid.mul

/--
lemma `mul_mem_mul` / 引理 `mul_mem_mul`

English:
lemma mul_mem_mul
  given: {m n : R} (hm : m in M) (hn : n in N)
  statement: m * n in M * N
  proof: smul_mem_smul hm hn

中文:
引理 mul_mem_mul
  条件: {m n : R} (hm : m in M) (hn : n in N)
  结论: m * n in M * N
  证明: smul_mem_smul hm hn

Depends on / 依赖: smul_mem_smul
-/
lemma mul_mem_mul {m n : R} (hm : m in M) (hn : n in N) : m * n in M * N := smul_mem_smul hm hn

/--
lemma `mul_le` / 引理 `mul_le`

English:
lemma mul_le
  statement: M * N <= P ↔ forall m in M, forall n in N, m * n in P
  proof: smul_le

@[elab_as_elim]

中文:
引理 mul_le
  结论: M * N <= P ↔ 对任意 m in M, 对任意 n in N, m * n in P
  证明: smul_le

@[elab_as_elim]

Depends on / 依赖: smul_le
-/
lemma mul_le : M * N <= P ↔ forall m in M, forall n in N, m * n in P := smul_le

@[elab_as_elim]
/--
lemma `mul_induction_on` / 引理 `mul_induction_on`

English:
lemma mul_induction_on
  statement: {C : R -> Prop} {r : R} (hr : r in M * N)
  proof: AddSubmonoid.smul_induction_on hr hm ha

中文:
引理 mul_induction_on
  结论: {C : R -> 命题} {r : R} (hr : r in M * N)
  证明: AddSubmonoid.smul_induction_on hr hm ha
-/
protected lemma mul_induction_on {C : R -> Prop} {r : R} (hr : r in M * N)
    (hm : forall m in M, forall n in N, C (m * n)) (ha : forall x y, C x -> C y -> C (x + y)) : C r :=
  AddSubmonoid.smul_induction_on hr hm ha

-- need `add_smul` to generalize to `SMul`
/--
lemma `closure_mul_closure` / 引理 `closure_mul_closure`

English:
lemma closure_mul_closure
  given: (S T : Set R)
  statement: closure S * closure T = closure (S * T)
  proof: by
  apply le_antisymm
  · refine mul_le.2 fun a ha b hb => ?_
    rw [← AddMonoidHom.mulRight_apply]; rw [← AddSubmonoid.mem_comap]
    refine (closure_le.2 fun a' ha' => ?_) ha
    change b in (closure (S * T)).comap (AddMonoidHom.mulLeft a')
    refine (closure_le.2 fun b' hb' => ?_) hb
    change a' * b' in closure (S * T)
    exact subset_closure (Set.mul_mem_mul ha' hb')
  · rw [closure_le]
    rintro _ ⟨a, ha, b, hb, rfl⟩
    exact mul_mem_mul (subset_closure ha) (subset_closure hb)

中文:
引理 closure_mul_closure
  条件: (S T : 集合 R)
  结论: closure S * closure T = closure (S * T)
  证明: by
  apply le_antisymm
  · refine mul_le.2 fun a ha b hb => ?_
    rw [← AddMonoidHom.mulRight_apply]; rw [← AddSubmonoid.mem_comap]
    refine (closure_le.2 fun a' ha' => ?_) ha
    change b in (closure (S * T)).comap (AddMonoidHom.mulLeft a')
    refine (closure_le.2 fun b' hb' => ?_) hb
    change a' * b' in closure (S * T)
    exact subset_closure (Set.mul_mem_mul ha' hb')
  · rw [closure_le]
    rintro _ ⟨a, ha, b, hb, rfl⟩
    exact mul_mem_mul (subset_closure ha) (subset_closure hb)

Depends on / 依赖: AddMonoidHom, AddMonoidHom.mulLeft, AddMonoidHom.mulRight_apply, AddSubmonoid, AddSubmonoid.mem_comap, Set.mul_mem_mul, closure, closure_le, le_antisymm, mem_comap, mulLeft, mulRight_apply, mul_le, mul_mem_mul, subset_closure
-/
lemma closure_mul_closure (S T : Set R) : closure S * closure T = closure (S * T) := by
  apply le_antisymm
  · refine mul_le.2 fun a ha b hb => ?_
    rw [← AddMonoidHom.mulRight_apply]; rw [← AddSubmonoid.mem_comap]
    refine (closure_le.2 fun a' ha' => ?_) ha
    change b in (closure (S * T)).comap (AddMonoidHom.mulLeft a')
    refine (closure_le.2 fun b' hb' => ?_) hb
    change a' * b' in closure (S * T)
    exact subset_closure (Set.mul_mem_mul ha' hb')
  · rw [closure_le]
    rintro _ ⟨a, ha, b, hb, rfl⟩
    exact mul_mem_mul (subset_closure ha) (subset_closure hb)

/--
lemma `mul_eq_closure_mul_set` / 引理 `mul_eq_closure_mul_set`

English:
lemma mul_eq_closure_mul_set
  given: (M N : AddSubmonoid R)
  statement: M * N = closure (M * N : Set R)
  proof: by
  rw [← closure_mul_closure]; rw [closure_eq]; rw [closure_eq]

中文:
引理 mul_eq_closure_mul_set
  条件: (M N : 加法子幺半群 R)
  结论: M * N = closure (M * N : 集合 R)
  证明: by
  rw [← closure_mul_closure]; rw [closure_eq]; rw [closure_eq]

Depends on / 依赖: closure_eq, closure_mul_closure
-/
lemma mul_eq_closure_mul_set (M N : AddSubmonoid R) : M * N = closure (M * N : Set R) := by
  rw [← closure_mul_closure]; rw [closure_eq]; rw [closure_eq]

/--
lemma `mul_bot` / 引理 `mul_bot`

English:
lemma mul_bot
  given: (S : AddSubmonoid R)
  statement: S * ⊥ = ⊥
  proof: addSubmonoid_smul_bot S

中文:
引理 mul_bot
  条件: (S : 加法子幺半群 R)
  结论: S * ⊥ = ⊥
  证明: addSubmonoid_smul_bot S
-/
@[simp] lemma mul_bot (S : AddSubmonoid R) : S * ⊥ = ⊥ := addSubmonoid_smul_bot S

-- need `zero_smul` to generalize to `SMul`
@[simp]
/--
lemma `bot_mul` / 引理 `bot_mul`

English:
lemma bot_mul
  given: (S : AddSubmonoid R)
  statement: ⊥ * S = ⊥
  proof: eq_bot_iff.2 mul_le.2 fun m hm n _ => by rw [AddSubmonoid.mem_bot] at hm ⊢; rw [hm, zero_mul]

中文:
引理 bot_mul
  条件: (S : 加法子幺半群 R)
  结论: ⊥ * S = ⊥
  证明: eq_bot_iff.2 mul_le.2 fun m hm n _ => by rw [AddSubmonoid.mem_bot] at hm ⊢; rw [hm, zero_mul]

Depends on / 依赖: AddSubmonoid, AddSubmonoid.mem_bot, eq_bot_iff, mem_bot, mul_le, zero_mul
-/
lemma bot_mul (S : AddSubmonoid R) : ⊥ * S = ⊥ :=
eq_bot_iff.2 mul_le.2 fun m hm n _ => by rw [AddSubmonoid.mem_bot] at hm ⊢; rw [hm, zero_mul]

variable {M N P Q : AddSubmonoid R}

/--
lemma `mul_le_mul` / 引理 `mul_le_mul`

English:
lemma mul_le_mul
  given: (hmp : M <= P) (hnq : N <= Q)
  statement: M * N <= P * Q
  proof: smul_le_smul hmp hnq

中文:
引理 mul_le_mul
  条件: (hmp : M <= P) (hnq : N <= Q)
  结论: M * N <= P * Q
  证明: smul_le_smul hmp hnq
-/
@[mono, gcongr] lemma mul_le_mul (hmp : M <= P) (hnq : N <= Q) : M * N <= P * Q := smul_le_smul hmp hnq

/--
lemma `mul_le_mul_left` / 引理 `mul_le_mul_left`

English:
lemma mul_le_mul_left
  given: (h : M <= N)
  statement: M * P <= N * P
  proof: smul_le_smul_left h

中文:
引理 mul_le_mul_left
  条件: (h : M <= N)
  结论: M * P <= N * P
  证明: smul_le_smul_left h

Depends on / 依赖: smul_le_smul_left
-/
lemma mul_le_mul_left (h : M <= N) : M * P <= N * P := smul_le_smul_left h
/--
lemma `mul_le_mul_right` / 引理 `mul_le_mul_right`

English:
lemma mul_le_mul_right
  given: (h : N <= P)
  statement: M * N <= M * P
  proof: smul_le_smul_right h

中文:
引理 mul_le_mul_right
  条件: (h : N <= P)
  结论: M * N <= M * P
  证明: smul_le_smul_right h

Depends on / 依赖: smul_le_smul_right
-/
lemma mul_le_mul_right (h : N <= P) : M * N <= M * P := smul_le_smul_right h

/--
lemma `mul_subset_mul` / 引理 `mul_subset_mul`

English:
lemma mul_subset_mul
  statement: (↑M : Set R) * (↑N : Set R) subseteq (↑(M * N) : Set R)
  proof: smul_subset_smul

中文:
引理 mul_subset_mul
  结论: (↑M : 集合 R) * (↑N : 集合 R) subseteq (↑(M * N) : 集合 R)
  证明: smul_subset_smul

Depends on / 依赖: smul_subset_smul
-/
lemma mul_subset_mul : (↑M : Set R) * (↑N : Set R) subseteq (↑(M * N) : Set R) := smul_subset_smul

/--
lemma `mul_sup` / 引理 `mul_sup`

English:
lemma mul_sup
  statement: M * (N ⊔ P) = M * N ⊔ M * P
  proof: addSubmonoid_smul_sup

中文:
引理 mul_sup
  结论: M * (N ⊔ P) = M * N ⊔ M * P
  证明: addSubmonoid_smul_sup

Depends on / 依赖: addSubmonoid_smul_sup, infer_instance, morphismRestrict
-/
lemma mul_sup : M * (N ⊔ P) = M * N ⊔ M * P := addSubmonoid_smul_sup

-- need `zero_smul` and `add_smul` to generalize to `SMul`
/--
lemma `sup_mul` / 引理 `sup_mul`

English:
lemma sup_mul
  statement: (M ⊔ N) * P = M * P ⊔ N * P
  proof: le_antisymm (mul_le.mpr fun mn hmn p hp => by
    obtain ⟨m, hm, n, hn, rfl⟩ := mem_sup.mp hmn
rw [right_distrib]; exact add_mem_sup (mul_mem_mul hm hp) mul_mem_mul hn hp)
    (sup_le (mul_le_mul_left le_sup_left) <| mul_le_mul_left le_sup_right)

中文:
引理 sup_mul
  结论: (M ⊔ N) * P = M * P ⊔ N * P
  证明: le_antisymm (mul_le.mpr fun mn hmn p hp => by
    obtain ⟨m, hm, n, hn, rfl⟩ := mem_sup.mp hmn
rw [right_distrib]; exact add_mem_sup (mul_mem_mul hm hp) mul_mem_mul hn hp)
    (sup_le (mul_le_mul_left le_sup_left) <| mul_le_mul_left le_sup_right)

Depends on / 依赖: add_mem_sup, le_antisymm, le_sup_left, le_sup_right, mem_sup, mem_sup.mp, mul_le, mul_le.mpr, mul_le_mul_left, mul_mem_mul, right_distrib, sup_le
-/
lemma sup_mul : (M ⊔ N) * P = M * P ⊔ N * P :=
  le_antisymm (mul_le.mpr fun mn hmn p hp => by
    obtain ⟨m, hm, n, hn, rfl⟩ := mem_sup.mp hmn
rw [right_distrib]; exact add_mem_sup (mul_mem_mul hm hp) mul_mem_mul hn hp)
    (sup_le (mul_le_mul_left le_sup_left) <| mul_le_mul_left le_sup_right)

variable {ι : Sort*}

-- need `zero_smul` and `add_smul` to generalize to `SMul`
/--
lemma `iSup_mul` / 引理 `iSup_mul`

English:
lemma iSup_mul
  given: (S : ι -> AddSubmonoid R) (T : AddSubmonoid R)
  statement: (⨆ i, S i) * T = ⨆ i, S i * T
  proof: le_antisymm (mul_le.mpr fun s hs t ht => iSup_induction _ (motive := (· * t in _)) hs
      (fun i s hs => mem_iSup_of_mem i <| mul_mem_mul hs ht) (by simp_rw [zero_mul]; apply zero_mem)
      fun _ _ => by simp_rw [right_distrib]; apply add_mem) <|
    iSup_le fun i => mul_le_mul_left (le_iSup _ i)

中文:
引理 iSup_mul
  条件: (S : ι -> 加法子幺半群 R) (T : 加法子幺半群 R)
  结论: (⨆ i, S i) * T = ⨆ i, S i * T
  证明: le_antisymm (mul_le.mpr fun s hs t ht => iSup_induction _ (motive := (· * t in _)) hs
      (fun i s hs => mem_iSup_of_mem i <| mul_mem_mul hs ht) (by simp_rw [zero_mul]; apply zero_mem)
      fun _ _ => by simp_rw [right_distrib]; apply add_mem) <|
    iSup_le fun i => mul_le_mul_left (le_iSup _ i)

Depends on / 依赖: add_mem, iSup_induction, iSup_le, le_antisymm, le_iSup, mem_iSup_of_mem, motive, mul_le, mul_le.mpr, mul_le_mul_left, mul_mem_mul, right_distrib, simp_rw, zero_mem, zero_mul
-/
lemma iSup_mul (S : ι -> AddSubmonoid R) (T : AddSubmonoid R) : (⨆ i, S i) * T = ⨆ i, S i * T :=
  le_antisymm (mul_le.mpr fun s hs t ht => iSup_induction _ (motive := (· * t in _)) hs
      (fun i s hs => mem_iSup_of_mem i <| mul_mem_mul hs ht) (by simp_rw [zero_mul]; apply zero_mem)
      fun _ _ => by simp_rw [right_distrib]; apply add_mem) <|
    iSup_le fun i => mul_le_mul_left (le_iSup _ i)

/--
lemma `mul_iSup` / 引理 `mul_iSup`

English:
lemma mul_iSup
  given: (T : AddSubmonoid R) (S : ι -> AddSubmonoid R)
  statement: (T * ⨆ i, S i) = ⨆ i, T * S i
  proof: smul_iSup T S

中文:
引理 mul_iSup
  条件: (T : 加法子幺半群 R) (S : ι -> 加法子幺半群 R)
  结论: (T * ⨆ i, S i) = ⨆ i, T * S i
  证明: smul_iSup T S

Depends on / 依赖: smul_iSup
-/
lemma mul_iSup (T : AddSubmonoid R) (S : ι -> AddSubmonoid R) : (T * ⨆ i, S i) = ⨆ i, T * S i :=
  smul_iSup T S

/--
lemma `mul_comm_of_commute` / 引理 `mul_comm_of_commute`

English:
lemma mul_comm_of_commute
  given: (h : forall m in M, forall n in N, Commute m n)
  statement: M * N = N * M
  proof: le_antisymm (mul_le.mpr fun m hm n hn => h m hm n hn ▸ mul_mem_mul hn hm)
    (mul_le.mpr fun n hn m hm => h m hm n hn ▸ mul_mem_mul hm hn)

中文:
引理 mul_comm_of_commute
  条件: (h : 对任意 m in M, 对任意 n in N, Commute m n)
  结论: M * N = N * M
  证明: le_antisymm (mul_le.mpr fun m hm n hn => h m hm n hn ▸ mul_mem_mul hn hm)
    (mul_le.mpr fun n hn m hm => h m hm n hn ▸ mul_mem_mul hm hn)

Depends on / 依赖: le_antisymm, mul_le, mul_le.mpr, mul_mem_mul
-/
lemma mul_comm_of_commute (h : forall m in M, forall n in N, Commute m n) : M * N = N * M :=
  le_antisymm (mul_le.mpr fun m hm n hn => h m hm n hn ▸ mul_mem_mul hn hm)
    (mul_le.mpr fun n hn m hm => h m hm n hn ▸ mul_mem_mul hm hn)

end NonUnitalNonAssocSemiring

section NonUnitalNonAssocRing
variable [NonUnitalNonAssocRing R]

/-- `AddSubmonoid.neg` distributes over multiplication.

This is available as an instance in the `Pointwise` locale. -/
@[instance_reducible]
/--
Definition of `hasDistribNeg` / `hasDistribNeg` 的定义

English:
definition hasDistribNeg
  signature: : HasDistribNeg (AddSubmonoid R) where
  body: by
    refine le_antisymm (mul_le.2 fun m hm n hn => ?_)
      ((AddSubmonoid.neg_le _ _).2 <| mul_le.2 fun m hm n hn => ?_) <;>
        simp only [AddSubmonoid.mem_neg, ← neg_mul] at *
    · exact mul_mem_mul hm hn
    · exact mul_mem_mul (neg_mem_neg.2 hm) hn
  mul_neg x y := by
    refine le_antisymm (mul_le.2 fun m hm n hn => ?_)
      ((AddSubmonoid.neg_le _ _).2 <| mul_le.2 fun m hm n hn => ?_) <;>
        simp only [AddSubmonoid.mem_neg, ← mul_neg] at *
    · exact mul_mem_mul hm hn
    · exact mul_mem_mul hm (neg_mem_neg.2 hn)

scoped[Pointwise] attribute [instance] AddSubmonoid.hasDistribNeg

中文:
定义 hasDistribNeg
  签名: : 有DistribNeg (加法子幺半群 R) where
  定义体: by
    refine le_antisymm (mul_le.2 fun m hm n hn => ?_)
      ((AddSubmonoid.neg_le _ _).2 <| mul_le.2 fun m hm n hn => ?_) <;>
        simp only [AddSubmonoid.mem_neg, ← neg_mul] at *
    · exact mul_mem_mul hm hn
    · exact mul_mem_mul (neg_mem_neg.2 hm) hn
  mul_neg x y := by
    refine le_antisymm (mul_le.2 fun m hm n hn => ?_)
      ((AddSubmonoid.neg_le _ _).2 <| mul_le.2 fun m hm n hn => ?_) <;>
        simp only [AddSubmonoid.mem_neg, ← mul_neg] at *
    · exact mul_mem_mul hm hn
    · exact mul_mem_mul hm (neg_mem_neg.2 hn)

scoped[Pointwise] attribute [instance] AddSubmonoid.hasDistribNeg
-/
protected def hasDistribNeg : HasDistribNeg (AddSubmonoid R) where
  neg_mul x y := by
    refine le_antisymm (mul_le.2 fun m hm n hn => ?_)
      ((AddSubmonoid.neg_le _ _).2 <| mul_le.2 fun m hm n hn => ?_) <;>
        simp only [AddSubmonoid.mem_neg, ← neg_mul] at *
    · exact mul_mem_mul hm hn
    · exact mul_mem_mul (neg_mem_neg.2 hm) hn
  mul_neg x y := by
    refine le_antisymm (mul_le.2 fun m hm n hn => ?_)
      ((AddSubmonoid.neg_le _ _).2 <| mul_le.2 fun m hm n hn => ?_) <;>
        simp only [AddSubmonoid.mem_neg, ← mul_neg] at *
    · exact mul_mem_mul hm hn
    · exact mul_mem_mul hm (neg_mem_neg.2 hn)

scoped[Pointwise] attribute [instance] AddSubmonoid.hasDistribNeg

end NonUnitalNonAssocRing

section NonAssocSemiring
variable [NonAssocSemiring R]

/-- A `MulOneClass` structure on additive submonoids of a (possibly, non-associative) semiring. -/
@[instance_reducible]
/--
Definition of `mulOneClass` / `mulOneClass` 的定义

English:
definition mulOneClass
  signature: : MulOneClass (AddSubmonoid R) where
  body: by rw [one_eq_closure_one_set, ← closure_eq M, closure_mul_closure, one_mul]
  mul_one M := by rw [one_eq_closure_one_set, ← closure_eq M, closure_mul_closure, mul_one]

scoped[Pointwise] attribute [instance] AddSubmonoid.mulOneClass

中文:
定义 mulOneClass
  签名: : MulOne类 (加法子幺半群 R) where
  定义体: by rw [one_eq_closure_one_set, ← closure_eq M, closure_mul_closure, one_mul]
  mul_one M := by rw [one_eq_closure_one_set, ← closure_eq M, closure_mul_closure, mul_one]

scoped[Pointwise] attribute [instance] AddSubmonoid.mulOneClass
-/
protected def mulOneClass : MulOneClass (AddSubmonoid R) where
  one_mul M := by rw [one_eq_closure_one_set, ← closure_eq M, closure_mul_closure, one_mul]
  mul_one M := by rw [one_eq_closure_one_set, ← closure_eq M, closure_mul_closure, mul_one]

scoped[Pointwise] attribute [instance] AddSubmonoid.mulOneClass

end NonAssocSemiring

section NonUnitalSemiring
variable [NonUnitalSemiring R]

/-- Semigroup structure on additive submonoids of a (possibly, non-unital) semiring. -/
@[instance_reducible]
/--
Definition of `semigroup` / `semigroup` 的定义

English:
definition semigroup
  signature: : Semigroup (AddSubmonoid R) where
  body: le_antisymm
      (mul_le.2 fun _mn hmn p hp => AddSubmonoid.mul_induction_on hmn
        (fun m hm n hn => mul_assoc m n p ▸ mul_mem_mul hm <| mul_mem_mul hn hp)
        fun x y => (add_mul x y p).symm ▸ add_mem)
      (mul_le.2 fun m hm _np hnp => AddSubmonoid.mul_induction_on hnp
        (fun n hn p hp => mul_assoc m n p ▸ mul_mem_mul (mul_mem_mul hm hn) hp)
        fun x y => (mul_add m x y) ▸ add_mem)

scoped[Pointwise] attribute [instance] AddSubmonoid.semigroup

中文:
定义 semigroup
  签名: : 半群 (加法子幺半群 R) where
  定义体: le_antisymm
      (mul_le.2 fun _mn hmn p hp => AddSubmonoid.mul_induction_on hmn
        (fun m hm n hn => mul_assoc m n p ▸ mul_mem_mul hm <| mul_mem_mul hn hp)
        fun x y => (add_mul x y p).symm ▸ add_mem)
      (mul_le.2 fun m hm _np hnp => AddSubmonoid.mul_induction_on hnp
        (fun n hn p hp => mul_assoc m n p ▸ mul_mem_mul (mul_mem_mul hm hn) hp)
        fun x y => (mul_add m x y) ▸ add_mem)

scoped[Pointwise] attribute [instance] AddSubmonoid.semigroup
-/
protected def semigroup : Semigroup (AddSubmonoid R) where
  mul_assoc _M _N _P :=
    le_antisymm
      (mul_le.2 fun _mn hmn p hp => AddSubmonoid.mul_induction_on hmn
        (fun m hm n hn => mul_assoc m n p ▸ mul_mem_mul hm <| mul_mem_mul hn hp)
        fun x y => (add_mul x y p).symm ▸ add_mem)
      (mul_le.2 fun m hm _np hnp => AddSubmonoid.mul_induction_on hnp
        (fun n hn p hp => mul_assoc m n p ▸ mul_mem_mul (mul_mem_mul hm hn) hp)
        fun x y => (mul_add m x y) ▸ add_mem)

scoped[Pointwise] attribute [instance] AddSubmonoid.semigroup

end NonUnitalSemiring

section Semiring
variable [Semiring R]

/-- Monoid structure on additive submonoids of a semiring. -/
@[instance_reducible]
/--
Definition of `monoid` / `monoid` 的定义

English:
definition monoid
  signature: : Monoid (AddSubmonoid R) where

中文:
定义 monoid
  签名: : 幺半群 (加法子幺半群 R) where
-/
protected def monoid : Monoid (AddSubmonoid R) where

scoped[Pointwise] attribute [instance] AddSubmonoid.monoid

/--
lemma `closure_pow` / 引理 `closure_pow`

English:
lemma closure_pow
  given: (s : Set R)
  statement: forall n : Nat, closure s ^ n = closure (s ^ n)

中文:
引理 closure_pow
  条件: (s : 集合 R)
  结论: 对任意 n : 自然数, closure s ^ n = closure (s ^ n)
-/
lemma closure_pow (s : Set R) : forall n : Nat, closure s ^ n = closure (s ^ n)
  | 0 => by rw [pow_zero, pow_zero, one_eq_closure_one_set]
  | n + 1 => by rw [pow_succ, pow_succ, closure_pow s n, closure_mul_closure]

/--
lemma `pow_eq_closure_pow_set` / 引理 `pow_eq_closure_pow_set`

English:
lemma pow_eq_closure_pow_set
  given: (s : AddSubmonoid R) (n : Nat)
  proof: by
  rw [← closure_pow]; rw [closure_eq]

中文:
引理 pow_eq_closure_pow_set
  条件: (s : 加法子幺半群 R) (n : 自然数)
  证明: by
  rw [← closure_pow]; rw [closure_eq]

Depends on / 依赖: closure_eq, closure_pow
-/
lemma pow_eq_closure_pow_set (s : AddSubmonoid R) (n : Nat) :
    s ^ n = closure ((s : Set R) ^ n) := by
  rw [← closure_pow]; rw [closure_eq]

/--
lemma `pow_subset_pow` / 引理 `pow_subset_pow`

English:
lemma pow_subset_pow
  given: {s : AddSubmonoid R} {n : Nat}
  statement: (↑s : Set R) ^ n subseteq ↑(s ^ n)
  proof: (pow_eq_closure_pow_set s n).symm ▸ subset_closure

中文:
引理 pow_subset_pow
  条件: {s : 加法子幺半群 R} {n : 自然数}
  结论: (↑s : 集合 R) ^ n subseteq ↑(s ^ n)
  证明: (pow_eq_closure_pow_set s n).symm ▸ subset_closure

Depends on / 依赖: pow_eq_closure_pow_set, subset_closure
-/
lemma pow_subset_pow {s : AddSubmonoid R} {n : Nat} : (↑s : Set R) ^ n subseteq ↑(s ^ n) :=
  (pow_eq_closure_pow_set s n).symm ▸ subset_closure

end Semiring
end AddSubmonoid
