/-
Copyright (c) 2025 Amelia Livingston. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Amelia Livingston
-/
module

public import Mathlib.Algebra.Homology.ShortComplex.ModuleCat
public import Mathlib.RepresentationTheory.Rep.Res
public import Mathlib.RepresentationTheory.Rep.Iso

/-!
# Coinvariants of a group representation

Given a commutative ring `k` and a monoid `G`, this file introduces the coinvariants of a
`k`-linear `G`-representation `(V, ρ)`.

We first define `Representation.Coinvariants.ker`, the submodule of `V` generated by elements
of the form `ρ g x - x` for `x : V`, `g : G`. Then the coinvariants of `(V, ρ)` are the quotient of
`V` by this submodule. We show that the functor sending a representation to its coinvariants is
left adjoint to the functor equipping a module with the trivial representation.

## Main definitions

* `Representation.Coinvariants ρ`: the coinvariants of a representation `ρ`.
* `Representation.coinvariantsFinsuppLEquiv ρ α`: given a type `α`, this is the `k`-linear
  equivalence between `(α →₀ V)_G` and `α →₀ V_G`.
* `Representation.coinvariantsTprodLeftRegularLEquiv ρ`: the `k`-linear equivalence between
  `(V ⊗ k[G])_G` and `V` sending `⟦v ⊗ single g r⟧ ↦ r • ρ(g⁻¹)(v)`.
* `Rep.coinvariantsAdjunction k G`: the adjunction between the functor sending a representation to
  its coinvariants and the functor equipping a module with the trivial representation.
* `Rep.coinvariantsTensor k G`: the functor sending representations `A, B` to `(A ⊗[k] B)_G`. This
  is naturally isomorphic to the functor sending `A, B` to `A ⊗[k[G]] B`, where we give `A` the
  `k[G]ᵐᵒᵖ`-module structure defined by `g • a := A.ρ g⁻¹ a`.
* `Rep.coinvariantsTensorFreeLEquiv A α`: given a representation `A` and a type `α`, this is the
  `k`-linear equivalence between `(A ⊗ (α →₀ k[G]))_G` and `α →₀ A` sending
  `⟦a ⊗ single x (single g r)⟧ ↦ single x (r • ρ(g⁻¹)(a))`. This is useful for group homology.

-/

@[expose] public section

open scoped MonoidAlgebra

universe w w' u u' v v'

namespace Representation

variable {k G V W X : Type*} [CommRing k] [Monoid G] [AddCommGroup V] [Module k V]
  [AddCommGroup W] [Module k W] [AddCommGroup X] [Module k X]
  (ρ : Representation k G V) (τ : Representation k G W) (υ : Representation k G X)

/-- The submodule of a representation generated by elements of the form `ρ g x - x`. -/
/-
**Representation.Coinvariants.ker** 是 Mathlib 中的一个定义，位于命名空间 `Representation.Coin
variants`。
形式化陈述：{k : Type u_1} →   {G : Type u_2} →     {V : Type u_3} →       [inst : Com
mRing k] →         [inst_1 : Monoid G] →           [inst_2 : AddCommGroup V] → [
inst_3 : _root_.Module k V] → Representation k G V → Submodule k V
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The submodule of a representation generated by elements of the form `ρ g x - x`.
-/
def Coinvariants.ker : Submodule k V :=
  Submodule.span k (Set.range fun (gv : G × V) => ρ gv.1 gv.2 - gv.2)

/-- The coinvariants of a representation, `V ⧸ ⟨{ρ g x - x | g ∈ G, x ∈ V}⟩`. -/
/-
**Representation.Coinvariants** 是 Mathlib 中的一个定义，位于命名空间 `Representation`。
形式化陈述：Coinvariants
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The coinvariants of a representation, `V ⧸ ⟨{ρ g x - x | g ∈ G, x ∈ V}⟩`.
-/
def Coinvariants := V ⧸ Coinvariants.ker ρ

namespace Coinvariants

/-
**Representation.Coinvariants.** 是 Mathlib 中的一个实例，位于命名空间 `Representation.Coinvar
iants`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance : AddCommGroup (Coinvariants ρ) := inferInstanceAs <| AddCommGroup (_ ⧸ _)
/-
**Representation.Coinvariants.** 是 Mathlib 中的一个实例，位于命名空间 `Representation.Coinvar
iants`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance : Module k (Coinvariants ρ) := inferInstanceAs <| Module k (_ ⧸ _)
/-
**Representation.Coinvariants.** 是 Mathlib 中的一个实例，位于命名空间 `Representation.Coinvar
iants`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Module.Finite k V] : Module.Finite k (Coinvariants ρ) :=
  inferInstanceAs <| Module.Finite k (V ⧸ Coinvariants.ker ρ)

variable {ρ}
/-
**Representation.Coinvariants.sub_mem_ker** 是 Mathlib 中的一个引理，位于命名空间 `Representat
ion.Coinvariants`。
形式化陈述：sub_mem_ker (g : G) (x : V) : ρ g x - x in Coinvariants.ker ρ
参数：g : G；x : V。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Submodule.subset_span`：subset_span : s subseteq span R s
· 使用定理 `Set.mem_range_self`：∀ {α : Type u} {ι : Sort u_1} {f : ι → α} (i : ι), f
 i ∈ Set.range f
-/
lemma sub_mem_ker (g : G) (x : V) : ρ g x - x ∈ Coinvariants.ker ρ :=
  Submodule.subset_span <| Set.mem_range_self (g, x)
/-
**Representation.Coinvariants.mem_ker_of_eq** 是 Mathlib 中的一个引理，位于命名空间 `Represent
ation.Coinvariants`。
形式化陈述：mem_ker_of_eq (g : G) (x : V) (a : V) (h : ρ g x - x = a) : a in ker ρ
参数：g : G；x : V；a : V；h : ρ g x - x = a。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Submodule.subset_span`：subset_span : s subseteq span R s
-/
lemma mem_ker_of_eq (g : G) (x : V) (a : V) (h : ρ g x - x = a) : a ∈ ker ρ :=
  Submodule.subset_span ⟨(g, x), h⟩

variable (ρ)

/-- The quotient map from a representation to its coinvariants as a linear map. -/
/-
**Representation.Coinvariants.mk** 是 Mathlib 中的一个定义，位于命名空间 `Representation.Coinv
ariants`。
形式化陈述：mk : V ->ₗ[k] Coinvariants ρ
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The quotient map from a representation to its coinvariants as a linear map.
-/
def mk : V →ₗ[k] Coinvariants ρ := Submodule.mkQ (ker ρ)
/-
**Representation.Coinvariants.mk_eq_iff** 是 Mathlib 中的一个定理，位于命名空间 `Representatio
n.Coinvariants`。
形式化陈述：mk_eq_iff {x y : V} : mk ρ x = mk ρ y ↔ x - y in Coinvariants.ker ρ
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Submodule.Quotient.eq`：∀ {R : Type u_1} {M : Type u_2} [inst : Ring R] [
inst_1 : AddCommGroup M] [inst_2 : _root_.Module R M]   (p : Submodule R M) {x y
 : M}, Subm…
-/
theorem mk_eq_iff {x y : V} :
    mk ρ x = mk ρ y ↔ x - y ∈ Coinvariants.ker ρ :=
  Submodule.Quotient.eq _
/-
**Representation.Coinvariants.mk_eq_zero** 是 Mathlib 中的一个定理，位于命名空间 `Representati
on.Coinvariants`。
形式化陈述：mk_eq_zero {x : V} : mk ρ x = 0 ↔ x in Coinvariants.ker ρ
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Submodule.Quotient.mk_eq_zero`：mk_eq_zero : (mk x : M ⧸ p) = 0 ↔ x in p
-/
theorem mk_eq_zero {x : V} :
    mk ρ x = 0 ↔ x ∈ Coinvariants.ker ρ :=
  Submodule.Quotient.mk_eq_zero _
/-
**Representation.Coinvariants.mk_surjective** 是 Mathlib 中的一个定理，位于命名空间 `Represent
ation.Coinvariants`。
形式化陈述：mk_surjective : Function.Surjective (mk ρ)
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Submodule.Quotient.mk_surjective`：mk_surjective : Function.Surjective (@
mk _ _ _ _ _ p)
-/
theorem mk_surjective : Function.Surjective (mk ρ) :=
  Submodule.Quotient.mk_surjective _

@[simp]
/-
**Representation.Coinvariants.mk_self_apply** 是 Mathlib 中的一个引理，位于命名空间 `Represent
ation.Coinvariants`。
形式化陈述：mk_self_apply (g : G) (x : V) : mk ρ (ρ g x) = mk ρ x
参数：g : G；x : V。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `Representation.Coinvariants.mk_eq_iff`：mk_eq_iff {x y : V} : mk ρ x = mk
 ρ y ↔ x - y in Coinvariants.ker ρ
· 使用引理 `Representation.Coinvariants.mem_ker_of_eq`：mem_ker_of_eq (g : G) (x : V)
 (a : V) (h : ρ g x - x = a) : a in ker ρ
-/
lemma mk_self_apply (g : G) (x : V) :
    mk ρ (ρ g x) = mk ρ x :=
  (mk_eq_iff _).2 <| mem_ker_of_eq g x _ rfl

variable {ρ} in
@[elab_as_elim]
/-
**Representation.Coinvariants.induction_on** 是 Mathlib 中的一个定理，位于命名空间 `Representa
tion.Coinvariants`。
形式化陈述：induction_on {motive : Coinvariants ρ -> Prop} (x : Coinvariants ρ) (h : f
orall v : V, motive (mk ρ v)) : motive x
参数：x : Coinvariants ρ；h : forall v : V, motive (mk ρ v)。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Submodule.Quotient.induction_on`：induction_on {C : M ⧸ p -> Prop} (x : M
 ⧸ p) (H : forall z, C (Submodule.Quotient.mk z)) : C x
-/
theorem induction_on {motive : Coinvariants ρ → Prop} (x : Coinvariants ρ)
    (h : ∀ v : V, motive (mk ρ v)) :
    motive x :=
  Submodule.Quotient.induction_on _ x h

/-- A `G`-invariant linear map induces a linear map out of the coinvariants of a
`G`-representation. -/
/-
**Representation.Coinvariants.lift** 是 Mathlib 中的一个定义，位于命名空间 `Representation.Coi
nvariants`。
形式化陈述：lift (f : V ->ₗ[k] W) (h : forall (x : G), f ∘ₗ ρ x = f) : ρ.Coinvariants 
->ₗ[k] W
参数：f : V ->ₗ[k] W；h : forall (x : G), f ∘ₗ ρ x = f。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
A `G`-invariant linear map induces a linear map out of the coinvariants of a
`G`-representation.
-/
def lift (f : V →ₗ[k] W) (h : ∀ (x : G), f ∘ₗ ρ x = f) :
    ρ.Coinvariants →ₗ[k] W :=
  Submodule.liftQ _ f <| Submodule.span_le.2 fun x ⟨⟨g, y⟩, hy⟩ => by
    simpa only [← hy, SetLike.mem_coe, LinearMap.mem_ker, map_sub, sub_eq_zero, LinearMap.coe_comp,
      Function.comp_apply] using LinearMap.ext_iff.1 (h g) y

@[simp]
/-
**Representation.Coinvariants.lift_comp_mk** 是 Mathlib 中的一个定理，位于命名空间 `Representa
tion.Coinvariants`。
形式化陈述：lift_comp_mk (f : V ->ₗ[k] W) (h : forall (x : G), f ∘ₗ ρ x = f) : lift ρ 
f h ∘ₗ mk ρ = f
参数：f : V ->ₗ[k] W；h : forall (x : G), f ∘ₗ ρ x = f。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem lift_comp_mk (f : V →ₗ[k] W) (h : ∀ (x : G), f ∘ₗ ρ x = f) :
    lift ρ f h ∘ₗ mk ρ = f := rfl

@[simp]
/-
**Representation.Coinvariants.lift_mk** 是 Mathlib 中的一个定理，位于命名空间 `Representation.
Coinvariants`。
形式化陈述：lift_mk (f : V ->ₗ[k] W) (h : forall (x : G), f ∘ₗ ρ x = f) (x : V) : lift
 ρ f h (mk _ x) = f x
参数：f : V ->ₗ[k] W；h : forall (x : G), f ∘ₗ ρ x = f；x : V。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem lift_mk (f : V →ₗ[k] W) (h : ∀ (x : G), f ∘ₗ ρ x = f) (x : V) :
    lift ρ f h (mk _ x) = f x := rfl

variable {ρ} in
@[ext high]
/-
**Representation.Coinvariants.hom_ext** 是 Mathlib 中的一个引理，位于命名空间 `Representation.
Coinvariants`。
形式化陈述：hom_ext {f g : Coinvariants ρ ->ₗ[k] W} (H : f ∘ₗ mk ρ = g ∘ₗ mk ρ) : f = 
g
参数：H : f ∘ₗ mk ρ = g ∘ₗ mk ρ。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Submodule.linearMap_qext`：linearMap_qext ⦃f g : M ⧸ p ->ₛₗ[τ₁₂] M₂⦄ (h :
 f.comp p.mkQ = g.comp p.mkQ) : f = g
-/
lemma hom_ext {f g : Coinvariants ρ →ₗ[k] W} (H : f ∘ₗ mk ρ = g ∘ₗ mk ρ) : f = g :=
  Submodule.linearMap_qext _ H

/-- Given `G`-representations on `k`-modules `V, W`, a linear map `V →ₗ[k] W` commuting with
the representations induces a `k`-linear map between the coinvariants. -/
/-
**Representation.Coinvariants.map** 是 Mathlib 中的一个定义，位于命名空间 `Representation.Coin
variants`。
形式化陈述：map (f : IntertwiningMap ρ τ) : Coinvariants ρ ->ₗ[k] Coinvariants τ
参数：f : IntertwiningMap ρ τ。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given `G`-representations on `k`-modules `V, W`, a linear map `V →ₗ[k] W` commut
ing with
the representations induces a `k`-linear map between the coinvariants.
-/
noncomputable def map (f : IntertwiningMap ρ τ) :
    Coinvariants ρ →ₗ[k] Coinvariants τ :=
  lift _ (mk _ ∘ₗ f) fun g => LinearMap.ext fun x => (mk_eq_iff _).2 <|
    mem_ker_of_eq g (f x) _ <| by simpa using congr($((f.isIntertwining' g).symm) x)

variable {ρ τ}

@[simp]
/-
**Representation.Coinvariants.map_comp_mk** 是 Mathlib 中的一个引理，位于命名空间 `Representat
ion.Coinvariants`。
形式化陈述：map_comp_mk (f : IntertwiningMap ρ τ) : map ρ τ f ∘ₗ mk ρ = mk τ ∘ₗ f
参数：f : IntertwiningMap ρ τ。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma map_comp_mk (f : IntertwiningMap ρ τ) : map ρ τ f ∘ₗ mk ρ = mk τ ∘ₗ f := rfl

@[simp]
/-
**Representation.Coinvariants.map_mk** 是 Mathlib 中的一个引理，位于命名空间 `Representation.C
oinvariants`。
形式化陈述：map_mk (f : IntertwiningMap ρ τ) (x : V) : map ρ τ f (mk _ x) = mk _ (f x)
参数：f : IntertwiningMap ρ τ；x : V。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma map_mk (f : IntertwiningMap ρ τ) (x : V) : map ρ τ f (mk _ x) = mk _ (f x) := rfl

@[simp]
/-
**Representation.Coinvariants.map_id** 是 Mathlib 中的一个引理，位于命名空间 `Representation.C
oinvariants`。
形式化陈述：map_id (ρ : Representation k G V) : map ρ ρ (IntertwiningMap.id ρ) = Linea
rMap.id
参数：ρ : Representation k G V。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `Representation.Coinvariants.hom_ext`：hom_ext {f g : Coinvariants ρ ->ₗ[k
] W} (H : f ∘ₗ mk ρ = g ∘ₗ mk ρ) : f = g
· 使用定理 `LinearMap.ext`：ext {f g : M ->ₛₗ[σ] M₃} (h : forall x, f x = g x) : f = 
g
-/
lemma map_id (ρ : Representation k G V) : map ρ ρ (IntertwiningMap.id ρ) = LinearMap.id := by
  ext; rfl

@[simp]
/-
**Representation.Coinvariants.map_comp** 是 Mathlib 中的一个引理，位于命名空间 `Representation
.Coinvariants`。
形式化陈述：map_comp (φ : IntertwiningMap ρ τ) (ψ : IntertwiningMap τ υ) : map τ υ ψ ∘
ₗ map ρ τ φ = map ρ υ (ψ.comp φ)
参数：φ : IntertwiningMap ρ τ；ψ : IntertwiningMap τ υ。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `Representation.Coinvariants.hom_ext`：hom_ext {f g : Coinvariants ρ ->ₗ[k
] W} (H : f ∘ₗ mk ρ = g ∘ₗ mk ρ) : f = g
-/
lemma map_comp (φ : IntertwiningMap ρ τ) (ψ : IntertwiningMap τ υ) :
    map τ υ ψ ∘ₗ map ρ τ φ = map ρ υ (ψ.comp φ) :=
  hom_ext rfl

end Coinvariants
section

open Coinvariants

variable {k G V : Type*} [CommRing k] [Group G] [AddCommGroup V] [Module k V]
variable (ρ : Representation k G V) (S : Subgroup G) [S.Normal]

/-
**Representation.Coinvariants.le_comap_ker** 是 Mathlib 中的一个定理，位于命名空间 `Representa
tion.Coinvariants`。
形式化陈述：∀ {k : Type u_6} {G : Type u_7} {V : Type u_8} [inst : CommRing k] [inst_1
 : Group G] [inst_2 : AddCommGroup V]   [inst_3 : _root_.Module k V] (ρ : Repres
entation k G V) (S : Subgroup G) [S.Normal] (g : G),   Representation.Coinvarian
ts.ker (MonoidHom.comp ρ S.subtype) ≤     Submodule.comap (ρ g) (Representation.
Coinvariants.ker (MonoidHom.comp ρ S.subtype))
参数：ρ : Representation k G V；S : Subgroup G；g : G；MonoidHom.comp ρ S.subtype；ρ g；
Representation.Coinvariants.ker (MonoidHom.comp ρ S.subtype)。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `Submodule.span_le`：span_le {p} : span R s <= p ↔ s subseteq p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `map_sub`：∀ {G : Type u_7} {H : Type u_8} {F : Type u_9} [inst : FunLike 
F G H] [inst_1 : AddGroup G]   [inst_2 : SubtractionMonoid H] [AddMonoidHomCl…
· 使用定理 `DistribMulActionSemiHomClass.toAddMonoidHomClass`：∀ {F : Type u_10} {M :
 outParam (Type u_11)} {N : outParam (Type u_12)} {φ : outParam (M → N)}   {A : 
outParam (Type u_13)} {B : outParam (T…
· 使用定理 `SemilinearMapClass.distribMulActionSemiHomClass`：∀ {R : Type u_1} {S : T
ype u_5} {M : Type u_8} {M₃ : Type u_11} (F : Type u_14) [inst : Semiring R]   [
inst_1 : Semiring S] [inst_2 : AddCom…
· 使用引理 `Representation.Coinvariants.mem_ker_of_eq`：mem_ker_of_eq (g : G) (x : V)
 (a : V) (h : ρ g x - x = a) : a in ker ρ
· 使用定理 `Subgroup.Normal.conj_mem`：∀ {G : Type u_1} [inst : Group G] {H : Subgrou
p G}, H.Normal → ∀ n ∈ H, ∀ (g : G), g * n * g⁻¹ ∈ H
· 使用定理 `Subtype.property`：∀ {α : Sort u} {p : α → Prop} (self : Subtype p), p ↑s
elf
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `map_mul`：map_mul [MulHomClass F M N] (f : F) (x y : M) : f (x * y) = f x
 * f y
· 使用定理 `MonoidHomClass.toMulHomClass`：∀ {F : Type u_10} {M : outParam (Type u_11
)} {N : outParam (Type u_12)} {inst : MulOne M} {inst_1 : MulOne N}   {inst_2 : 
FunLike F M N} [se…
· 使用定理 `Representation.inv_self_apply`：inv_self_apply (g : G) (x : V) : ρ g⁻¹ (ρ
 g x) = x
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma Coinvariants.le_comap_ker (g : G) :
    ker (ρ.comp S.subtype) ≤ (ker <| ρ.comp S.subtype).comap (ρ g) :=
  Submodule.span_le.2 fun _ ⟨⟨s, x⟩, hs⟩ => by
    simpa [← hs] using mem_ker_of_eq
      ⟨g * s * g⁻¹, Subgroup.Normal.conj_mem ‹_› s.1 s.2 g⟩ (ρ g x) _ <| by simp

/-- Given a normal subgroup `S ≤ G`, a `G`-representation `ρ` restricts to a `G`-representation on
the kernel of the quotient map to the coinvariants of `ρ|_S`. -/
/-
**Representation.toCoinvariantsKer** 是 Mathlib 中的一个缩写定义，位于命名空间 `Representation`。
形式化陈述：toCoinvariantsKer : Representation k G (ker <| ρ.comp S.subtype)
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `Representation.Coinvariants.le_comap_ker`：∀ {k : Type u_6} {G : Type u_7
} {V : Type u_8} [inst : CommRing k] [inst_1 : Group G] [inst_2 : AddCommGroup V
]   [inst_3 : _root_.Module k …

--- 原说明 ---
Given a normal subgroup `S ≤ G`, a `G`-representation `ρ` restricts to a `G`-rep
resentation on
the kernel of the quotient map to the coinvariants of `ρ|_S`.
-/
noncomputable abbrev toCoinvariantsKer :
    Representation k G (ker <| ρ.comp S.subtype) :=
  subrepresentation ρ (ker <| ρ.comp S.subtype) fun g => le_comap_ker ρ S g

/-- Given a normal subgroup `S ≤ G`, a `G`-representation `ρ` induces a `G`-representation on the
coinvariants of `ρ|_S`. -/
/-
**Representation.toCoinvariants** 是 Mathlib 中的一个定义，位于命名空间 `Representation`。
形式化陈述：toCoinvariants : Representation k G (Coinvariants <| ρ.comp S.subtype)
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `Representation.Coinvariants.le_comap_ker`：∀ {k : Type u_6} {G : Type u_7
} {V : Type u_8} [inst : CommRing k] [inst_1 : Group G] [inst_2 : AddCommGroup V
]   [inst_3 : _root_.Module k …

--- 原说明 ---
Given a normal subgroup `S ≤ G`, a `G`-representation `ρ` induces a `G`-represen
tation on the
coinvariants of `ρ|_S`.
-/
noncomputable def toCoinvariants :
    Representation k G (Coinvariants <| ρ.comp S.subtype) :=
  quotient ρ (ker <| ρ.comp S.subtype) fun g => le_comap_ker ρ S g

@[simp]
/-
**Representation.toCoinvariants_mk** 是 Mathlib 中的一个引理，位于命名空间 `Representation`。
形式化陈述：toCoinvariants_mk (g : G) (x : V) : toCoinvariants ρ S g (Coinvariants.mk 
_ x) = Coinvariants.mk _ (ρ g x)
参数：g : G；x : V。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma toCoinvariants_mk (g : G) (x : V) :
    toCoinvariants ρ S g (Coinvariants.mk _ x) = Coinvariants.mk _ (ρ g x) := rfl

/-- The morphism from `ρ` to `toCoinvariants ρ S` induced by the quotient map. -/
/-
**Representation.toCoinvariantsMkQ** 是 Mathlib 中的一个缩写定义，位于命名空间 `Representation`。
形式化陈述：toCoinvariantsMkQ : ρ.IntertwiningMap (toCoinvariants ρ S) where __
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The morphism from `ρ` to `toCoinvariants ρ S` induced by the quotient map.
-/
abbrev toCoinvariantsMkQ : ρ.IntertwiningMap (toCoinvariants ρ S) where
  __ := Coinvariants.mk _
  isIntertwining' _ := rfl
/-
**Representation.** 是 Mathlib 中的一个实例，位于命名空间 `Representation`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance : IsTrivial ((toCoinvariants ρ S).comp S.subtype) where
  out g := by
    ext x
    exact (Coinvariants.mk_eq_iff _).2 <| mem_ker_of_eq g x _ rfl

/-- Given a normal subgroup `S ≤ G`, a `G`-representation `ρ` induces a `G ⧸ S`-representation on
the coinvariants of `ρ|_S`. -/
/-
**Representation.quotientToCoinvariants** 是 Mathlib 中的一个缩写定义，位于命名空间 `Representat
ion`。
形式化陈述：quotientToCoinvariants : Representation k (G ⧸ S) (Coinvariants (ρ.comp S.
subtype))
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `Representation.instIsTrivialSubtypeMemSubgroupCoinvariantsCompLinearMapI
dSubtypeToCoinvariants`：∀ {k : Type u_6} {G : Type u_7} {V : Type u_8} [inst : C
ommRing k] [inst_1 : Group G] [inst_2 : AddCommGroup V]   [inst_3 : _root_.Modul
e k …

--- 原说明 ---
Given a normal subgroup `S ≤ G`, a `G`-representation `ρ` induces a `G ⧸ S`-repr
esentation on
the coinvariants of `ρ|_S`.
-/
noncomputable abbrev quotientToCoinvariants :
    Representation k (G ⧸ S) (Coinvariants (ρ.comp S.subtype)) :=
  ofQuotient (toCoinvariants ρ S) S

end


section Finsupp

open Finsupp Coinvariants

variable {k G V : Type*} [CommRing k] [Group G] [AddCommGroup V] [Module k V]
  (ρ : Representation k G V) (α : Type*)

/-- Given a `G`-representation `(V, ρ)` and a type `α`, this is the map `(α →₀ V)_G →ₗ (α →₀ V_G)`
sending `⟦single a v⟧ ↦ single a ⟦v⟧`. -/
/-
**Representation.coinvariantsToFinsupp** 是 Mathlib 中的一个定义，位于命名空间 `Representation
`。
形式化陈述：coinvariantsToFinsupp : Coinvariants (ρ.finsupp α) ->ₗ[k] α ->₀ Coinvarian
ts ρ
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a `G`-representation `(V, ρ)` and a type `α`, this is the map `(α →₀ V)_G 
→ₗ (α →₀ V_G)`
sending `⟦single a v⟧ ↦ single a ⟦v⟧`.
-/
noncomputable def coinvariantsToFinsupp :
    Coinvariants (ρ.finsupp α) →ₗ[k] α →₀ Coinvariants ρ :=
  Coinvariants.lift _ (mapRange.linearMap (Coinvariants.mk _)) <| fun _ => by ext; simp

variable {ρ α}

@[simp]
/-
**Representation.coinvariantsToFinsupp_mk_single** 是 Mathlib 中的一个引理，位于命名空间 `Repr
esentation`。
形式化陈述：coinvariantsToFinsupp_mk_single (x : α) (a : V) : coinvariantsToFinsupp ρ 
α (Coinvariants.mk _ (single x a)) = single x (Coinvariants.mk _ a)
参数：x : α；a : V。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `LinearMap.map_zero`：∀ {R : Type u_1} {S : Type u_5} {M : Type u_8} {M₃ :
 Type u_11} [inst : Semiring R] [inst_1 : Semiring S]   [inst_2 : AddCommMonoid 
M] [inst…
· 使用定理 `Finsupp.mapRange.linearMap_apply`：∀ {α : Type u_1} {M : Type u_2} {N : T
ype u_3} {R : Type u_5} {R₂ : Type u_6} [inst : Semiring R] [inst_1 : Semiring R
₂]   [inst_2 : AddComm…
· 使用定理 `Finsupp.mapRange_single`：mapRange_single {f : M -> N} {hf : f 0 = 0} {a 
: α} {b : M} : mapRange f hf (single a b) = single a (f b)
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma coinvariantsToFinsupp_mk_single (x : α) (a : V) :
    coinvariantsToFinsupp ρ α (Coinvariants.mk _ (single x a)) =
      single x (Coinvariants.mk _ a) := by
  simp [coinvariantsToFinsupp]

variable (ρ α) in
/-- Given a `G`-representation `(V, ρ)` and a type `α`, this is the map `(α →₀ V_G) →ₗ (α →₀ V)_G`
sending `single a ⟦v⟧ ↦ ⟦single a v⟧`. -/
/-
**Representation.finsuppToCoinvariants** 是 Mathlib 中的一个定义，位于命名空间 `Representation
`。
形式化陈述：finsuppToCoinvariants : (α ->₀ Coinvariants ρ) ->ₗ[k] Coinvariants (ρ.fins
upp α)
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a `G`-representation `(V, ρ)` and a type `α`, this is the map `(α →₀ V_G) 
→ₗ (α →₀ V)_G`
sending `single a ⟦v⟧ ↦ ⟦single a v⟧`.
-/
noncomputable def finsuppToCoinvariants :
    (α →₀ Coinvariants ρ) →ₗ[k] Coinvariants (ρ.finsupp α) :=
  lsum (R := k) k fun a => Coinvariants.lift _ (Coinvariants.mk _ ∘ₗ lsingle a) fun g =>
    LinearMap.ext fun x => (mk_eq_iff _).2 <| mem_ker_of_eq g (single a x) _ <| by simp

@[simp]
/-
**Representation.finsuppToCoinvariants_single_mk** 是 Mathlib 中的一个引理，位于命名空间 `Repr
esentation`。
形式化陈述：finsuppToCoinvariants_single_mk (a : α) (x : V) : finsuppToCoinvariants ρ 
α (single a <| Coinvariants.mk _ x) = Coinvariants.mk _ (single a x)
参数：a : α；x : V。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Finsupp.sum_single_index`：∀ {α : Type u_1} {M : Type u_8} {N : Type u_10
} [inst : Zero M] [inst_1 : AddCommMonoid N] {a : α} {b : M}   {h : α → M → N}, 
h a 0 = 0 → (f…
· 使用定理 `map_zero`：∀ {M : Type u_4} {N : Type u_5} {F : Type u_9} [inst : Zero M]
 [inst_1 : Zero N] [inst_2 : FunLike F M N]   [ZeroHomClass F M N] (f : F), f …
· 使用定理 `AddMonoidHomClass.toZeroHomClass`：∀ {F : Type u_10} {M : outParam (Type 
u_11)} {N : outParam (Type u_12)} {inst : AddZero M} {inst_1 : AddZero N}   {ins
t_2 : FunLike F M N} […
· 使用定理 `DistribMulActionSemiHomClass.toAddMonoidHomClass`：∀ {F : Type u_10} {M :
 outParam (Type u_11)} {N : outParam (Type u_12)} {φ : outParam (M → N)}   {A : 
outParam (Type u_13)} {B : outParam (T…
· 使用定理 `SemilinearMapClass.distribMulActionSemiHomClass`：∀ {R : Type u_1} {S : T
ype u_5} {M : Type u_8} {M₃ : Type u_11} (F : Type u_14) [inst : Semiring R]   [
inst_1 : Semiring S] [inst_2 : AddCom…
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma finsuppToCoinvariants_single_mk (a : α) (x : V) :
    finsuppToCoinvariants ρ α (single a <| Coinvariants.mk _ x) =
      Coinvariants.mk _ (single a x) := by
  simp [finsuppToCoinvariants]

variable (ρ α) in
/-- Given a `G`-representation `(V, ρ)` and a type `α`, this is the linear equivalence
`(α →₀ V)_G ≃ₗ (α →₀ V_G)` sending `⟦single a v⟧ ↦ single a ⟦v⟧`. -/
@[simps! symm_apply]
/-
**Representation.coinvariantsFinsuppLEquiv** 是 Mathlib 中的一个定义，位于命名空间 `Representa
tion`。
形式化陈述：coinvariantsFinsuppLEquiv : Coinvariants (ρ.finsupp α) ≃ₗ[k] α ->₀ Coinvar
iants ρ
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a `G`-representation `(V, ρ)` and a type `α`, this is the linear equivalen
ce
`(α →₀ V)_G ≃ₗ (α →₀ V_G)` sending `⟦single a v⟧ ↦ single a ⟦v⟧`.
-/
noncomputable def coinvariantsFinsuppLEquiv :
    Coinvariants (ρ.finsupp α) ≃ₗ[k] α →₀ Coinvariants ρ :=
  LinearEquiv.ofLinearMap (coinvariantsToFinsupp ρ α) (finsuppToCoinvariants ρ α)
    (by ext; simp) (by ext; simp)

@[simp]
/-
**Representation.coinvariantsFinsuppLEquiv_apply** 是 Mathlib 中的一个引理，位于命名空间 `Repr
esentation`。
形式化陈述：coinvariantsFinsuppLEquiv_apply (x : Coinvariants (ρ.finsupp α)) : coinvar
iantsFinsuppLEquiv ρ α x = coinvariantsToFinsupp ρ α x
参数：x : Coinvariants (ρ.finsupp α)。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma coinvariantsFinsuppLEquiv_apply (x : Coinvariants (ρ.finsupp α)) :
    coinvariantsFinsuppLEquiv ρ α x = coinvariantsToFinsupp ρ α x := by rfl

end Finsupp

section TensorProduct

open Coinvariants Finsupp

variable {k G V W : Type*} [CommRing k] [Group G] [AddCommGroup V] [Module k V]
  [AddCommGroup W] [Module k W] (ρ : Representation k G V) (τ : Representation k G W)

-- the next two lemmas eliminate inverses

@[simp]
/-
**Representation.Coinvariants.mk_inv_tmul** 是 Mathlib 中的一个定理，位于命名空间 `Representat
ion.Coinvariants`。
形式化陈述：∀ {k : Type u_6} {G : Type u_7} {V : Type u_8} {W : Type u_9} [inst : Comm
Ring k] [inst_1 : Group G]   [inst_2 : AddCommGroup V] [inst_3 : _root_.Module k
 V] [inst_4 : AddCommGroup W] [inst_5 : _root_.Module k W]   (ρ : Representation
 k G V) (τ : Representation k G W) (x : V) (y : W) (g : G),   (Representation.Co
invariants.mk (ρ.tprod τ)) ((ρ g⁻¹) x ⊗ₜ[k] y) =     (Representation.Coinvariant
s.mk (ρ.tprod τ)) (x ⊗ₜ[k] (τ g) y)
参数：ρ : Representation k G V；τ : Representation k G W；x : V；y : W；g : G；Represent
ation.Coinvariants.mk (ρ.tprod τ)；(ρ g⁻¹) x ⊗ₜ[k] y；Representation.Coinvariants.
mk (ρ.tprod τ)；x ⊗ₜ[k] (τ g) y。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `Representation.Coinvariants.mk_eq_iff`：mk_eq_iff {x y : V} : mk ρ x = mk
 ρ y ↔ x - y in Coinvariants.ker ρ
· 使用引理 `Representation.Coinvariants.mem_ker_of_eq`：mem_ker_of_eq (g : G) (x : V)
 (a : V) (h : ρ g x - x = a) : a in ker ρ
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Representation.inv_self_apply`：inv_self_apply (g : G) (x : V) : ρ g⁻¹ (ρ
 g x) = x
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma Coinvariants.mk_inv_tmul (x : V) (y : W) (g : G) :
    Coinvariants.mk (ρ.tprod τ) (ρ g⁻¹ x ⊗ₜ[k] y) = Coinvariants.mk (ρ.tprod τ) (x ⊗ₜ[k] τ g y) :=
  (mk_eq_iff _).2 <| mem_ker_of_eq g⁻¹ (x ⊗ₜ[k] τ g y) _ <| by simp

@[simp]
/-
**Representation.Coinvariants.mk_tmul_inv** 是 Mathlib 中的一个定理，位于命名空间 `Representat
ion.Coinvariants`。
形式化陈述：∀ {k : Type u_6} {G : Type u_7} {V : Type u_8} {W : Type u_9} [inst : Comm
Ring k] [inst_1 : Group G]   [inst_2 : AddCommGroup V] [inst_3 : _root_.Module k
 V] [inst_4 : AddCommGroup W] [inst_5 : _root_.Module k W]   (ρ : Representation
 k G V) (τ : Representation k G W) (x : V) (y : W) (g : G),   (Representation.Co
invariants.mk (ρ.tprod τ)) (x ⊗ₜ[k] (τ g⁻¹) y) =     (Representation.Coinvariant
s.mk (ρ.tprod τ)) ((ρ g) x ⊗ₜ[k] y)
参数：ρ : Representation k G V；τ : Representation k G W；x : V；y : W；g : G；Represent
ation.Coinvariants.mk (ρ.tprod τ)；x ⊗ₜ[k] (τ g⁻¹) y；Representation.Coinvariants.
mk (ρ.tprod τ)；(ρ g) x ⊗ₜ[k] y。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `Representation.Coinvariants.mk_eq_iff`：mk_eq_iff {x y : V} : mk ρ x = mk
 ρ y ↔ x - y in Coinvariants.ker ρ
· 使用引理 `Representation.Coinvariants.mem_ker_of_eq`：mem_ker_of_eq (g : G) (x : V)
 (a : V) (h : ρ g x - x = a) : a in ker ρ
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Representation.inv_self_apply`：inv_self_apply (g : G) (x : V) : ρ g⁻¹ (ρ
 g x) = x
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma Coinvariants.mk_tmul_inv (x : V) (y : W) (g : G) :
    Coinvariants.mk (ρ.tprod τ) (x ⊗ₜ[k] τ g⁻¹ y) = Coinvariants.mk (ρ.tprod τ) (ρ g x ⊗ₜ[k] y) :=
  (mk_eq_iff _).2 <| mem_ker_of_eq g⁻¹ (ρ g x ⊗ₜ[k] y) _ <| by simp

/-- Given a `k`-linear `G`-representation `V, ρ`, this is the map `(V ⊗ k[G])_G →ₗ[k] V` sending
`⟦v ⊗ single g r⟧ ↦ r • ρ(g⁻¹)(v)`. -/
/-
**Representation.ofCoinvariantsTprodLeftRegular** 是 Mathlib 中的一个定义，位于命名空间 `Repre
sentation`。
形式化陈述：ofCoinvariantsTprodLeftRegular : Coinvariants (ρ.tprod (leftRegular k G)) 
->ₗ[k] V
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a `k`-linear `G`-representation `V, ρ`, this is the map `(V ⊗ k[G])_G →ₗ[k
] V` sending
`⟦v ⊗ single g r⟧ ↦ r • ρ(g⁻¹)(v)`.
-/
noncomputable def ofCoinvariantsTprodLeftRegular :
    Coinvariants (ρ.tprod (leftRegular k G)) →ₗ[k] V :=
  Coinvariants.lift _ (TensorProduct.lift ((Finsupp.linearCombination _ fun g => ρ g⁻¹) ∘ₗ
    (MonoidAlgebra.coeffLinearEquiv k).toLinearMap) ∘ₗ
    (_root_.TensorProduct.comm _ _ _).toLinearMap) fun _ => by ext; simp

@[simp]
/-
**Representation.ofCoinvariantsTprodLeftRegular_mk_tmul_single** 是 Mathlib 中的一个引
理，位于命名空间 `Representation`。
形式化陈述：ofCoinvariantsTprodLeftRegular_mk_tmul_single (x : V) (g : G) (r : k) : of
CoinvariantsTprodLeftRegular ρ (Coinvariants.mk _ (x otimesₜ .single g r)) = r •
 ρ g⁻¹ x
参数：x : V；g : G；r : k。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Finsupp.linearCombination_single`：linearCombination_single (c : R) (a : 
α) : linearCombination R v (single a c) = c • v a
-/
lemma ofCoinvariantsTprodLeftRegular_mk_tmul_single (x : V) (g : G) (r : k) :
    ofCoinvariantsTprodLeftRegular ρ (Coinvariants.mk _ (x ⊗ₜ .single g r)) = r • ρ g⁻¹ x :=
  congr($(Finsupp.linearCombination_single k (v := fun g => ρ g⁻¹) r g) x)

/-- Given a `k`-linear `G`-representation `(V, ρ)`, this is the linear equivalence
`(V ⊗ k[G])_G ≃ₗ[k] V` sending `⟦v ⊗ single g r⟧ ↦ r • ρ(g⁻¹)(v)`. -/
@[simps! symm_apply]
/-
**Representation.coinvariantsTprodLeftRegularLEquiv** 是 Mathlib 中的一个定义，位于命名空间 `R
epresentation`。
形式化陈述：coinvariantsTprodLeftRegularLEquiv : Coinvariants (ρ.tprod (leftRegular k 
G)) ≃ₗ[k] V
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a `k`-linear `G`-representation `(V, ρ)`, this is the linear equivalence
`(V ⊗ k[G])_G ≃ₗ[k] V` sending `⟦v ⊗ single g r⟧ ↦ r • ρ(g⁻¹)(v)`.
-/
noncomputable def coinvariantsTprodLeftRegularLEquiv :
    Coinvariants (ρ.tprod (leftRegular k G)) ≃ₗ[k] V :=
  LinearEquiv.ofLinearMap (ofCoinvariantsTprodLeftRegular ρ)
    (Coinvariants.mk _ ∘ₗ (TensorProduct.mk k V k[G]).flip (.single 1 1))
    (by ext; simp) (by ext; simp)

@[simp]
/-
**Representation.coinvariantsTprodLeftRegularLEquiv_apply** 是 Mathlib 中的一个引理，位于命
名空间 `Representation`。
形式化陈述：coinvariantsTprodLeftRegularLEquiv_apply (x : (ρ.tprod (leftRegular k G)).
Coinvariants) : coinvariantsTprodLeftRegularLEquiv ρ x = ofCoinvariantsTprodLeft
Regular ρ x
参数：x : (ρ.tprod (leftRegular k G)).Coinvariants。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma coinvariantsTprodLeftRegularLEquiv_apply (x : (ρ.tprod (leftRegular k G)).Coinvariants) :
    coinvariantsTprodLeftRegularLEquiv ρ x = ofCoinvariantsTprodLeftRegular ρ x := by
  rfl

end TensorProduct
end Representation

namespace Rep

open CategoryTheory Representation

variable {k : Type u} {G : Type v} [CommRing k]

noncomputable section

variable [Group G] (A : Rep.{w} k G) (S : Subgroup G) [S.Normal]

/-- Given a normal subgroup `S ≤ G`, a `G`-representation `A` restricts to a `G`-representation on
the kernel of the quotient map to the `S`-coinvariants `A_S`. -/
/-
**Rep.toCoinvariantsKer** 是 Mathlib 中的一个缩写定义，位于命名空间 `Rep`。
形式化陈述：toCoinvariantsKer : Rep k G
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a normal subgroup `S ≤ G`, a `G`-representation `A` restricts to a `G`-rep
resentation on
the kernel of the quotient map to the `S`-coinvariants `A_S`.
-/
abbrev toCoinvariantsKer : Rep k G := Rep.of (A.ρ.toCoinvariantsKer S)

/-- Given a normal subgroup `S ≤ G`, a `G`-representation `A` induces a `G`-representation on
the `S`-coinvariants `A_S`. -/
/-
**Rep.toCoinvariants** 是 Mathlib 中的一个缩写定义，位于命名空间 `Rep`。
形式化陈述：toCoinvariants : Rep k G
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a normal subgroup `S ≤ G`, a `G`-representation `A` induces a `G`-represen
tation on
the `S`-coinvariants `A_S`.
-/
abbrev toCoinvariants : Rep k G := Rep.of (A.ρ.toCoinvariants S)

/-- The quotient map `A → A_S` as a representation morphism. -/
/-
**Rep.toCoinvariantsMkQ** 是 Mathlib 中的一个缩写定义，位于命名空间 `Rep`。
形式化陈述：toCoinvariantsMkQ : A ⟶ toCoinvariants A S
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The quotient map `A → A_S` as a representation morphism.
-/
abbrev toCoinvariantsMkQ : A ⟶ toCoinvariants A S :=
  Rep.ofHom (Representation.toCoinvariantsMkQ _ _)

/-- Given a normal subgroup `S ≤ G`, a `G`-representation `ρ` induces a `G ⧸ S`-representation on
the coinvariants of `ρ|_S`. -/
/-
**Rep.quotientToCoinvariants** 是 Mathlib 中的一个缩写定义，位于命名空间 `Rep`。
形式化陈述：quotientToCoinvariants : Rep k (G ⧸ S)
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a normal subgroup `S ≤ G`, a `G`-representation `ρ` induces a `G ⧸ S`-repr
esentation on
the coinvariants of `ρ|_S`.
-/
abbrev quotientToCoinvariants : Rep k (G ⧸ S) := Rep.ofQuotient (Rep.toCoinvariants A S) S

set_option backward.isDefEq.respectTransparency.types false in
/-- Given a normal subgroup `S ≤ G`, a `G`-representation `A` induces a short exact sequence of
`G`-representations `0 ⟶ Ker(mk) ⟶ A ⟶ A_S ⟶ 0` where `mk` is the quotient map to the
`S`-coinvariants `A_S`. -/
@[simps X₁ X₂ X₃ f g]
/-
**Rep.coinvariantsShortComplex** 是 Mathlib 中的一个定义，位于命名空间 `Rep`。
形式化陈述：coinvariantsShortComplex : ShortComplex (Rep.{w} k G) where X₁
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a normal subgroup `S ≤ G`, a `G`-representation `A` induces a short exact 
sequence of
`G`-representations `0 ⟶ Ker(mk) ⟶ A ⟶ A_S ⟶ 0` where `mk` is the quotient map t
o the
`S`-coinvariants `A_S`.
-/
def coinvariantsShortComplex : ShortComplex (Rep.{w} k G) where
  X₁ := toCoinvariantsKer A S
  X₂ := A
  X₃ := toCoinvariants A S
  f := ofHom ⟨Submodule.subtype _, fun g ↦ by ext; simp⟩
  g := toCoinvariantsMkQ A S
  zero := by ext x; exact (Submodule.Quotient.mk_eq_zero _).2 x.2
/-
**Rep.coinvariantsShortComplex_shortExact** 是 Mathlib 中的一个引理，位于命名空间 `Rep`。
形式化陈述：coinvariantsShortComplex_shortExact : (coinvariantsShortComplex.{w} A S).S
hortExact where exact
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `CategoryTheory.Functor.reflects_exact_of_faithful`：reflects_exact_of_fai
thful [F.Faithful] (S : ShortComplex C) (hS : (S.map F).Exact) : S.Exact
· 使用定理 `CategoryTheory.Functor.preservesZeroMorphisms_of_additive`：∀ {C : Type u
_1} {D : Type u_2} [inst : CategoryTheory.Category.{v_1, u_1} C]   [inst_1 : Cat
egoryTheory.Category.{v_2, u_2} D] [inst_2 : Ca…
· 使用定理 `Rep.instAdditiveModuleCatForget₂IntertwiningMapVρLinearMapIdCarrier`：∀ (
k : Type u) (G : Type v) [inst : Ring k] [inst_1 : Monoid G],   (CategoryTheory.
forget₂ (Rep.{w, u, v} k G) (ModuleCat k)).Additive
· 使用定理 `Rep.instFaithfulModuleCatForget₂IntertwiningMapVρLinearMapIdCarrier`：∀ {
k : Type u} {G : Type v} [inst : Ring k] [inst_1 : Monoid G],   (CategoryTheory.
forget₂ (Rep.{w, u, v} k G) (ModuleCat k)).Faithful
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用引理 `CategoryTheory.ShortComplex.moduleCat_exact_iff`：moduleCat_exact_iff : S
.Exact ↔ forall (x₂ : S.X₂) (_ : S.g x₂ = 0), exists (x₁ : S.X₁), S.f x₁ = x₂
· 使用定理 `Iff.mp`：∀ {a b : Prop}, (a ↔ b) → a → b
· 使用定理 `Submodule.Quotient.mk_eq_zero`：mk_eq_zero : (mk x : M ⧸ p) = 0 ↔ x in p
· 使用定理 `Rep.mono_iff_injective`：mono_iff_injective (f : A ⟶ B) : Mono f ↔ Functi
on.Injective f.hom
· 使用定理 `Subtype.ext`：∀ {α : Sort u} {p : α → Prop} {a1 a2 : { x // p x }}, ↑a1 =
 ↑a2 → a1 = a2
· 使用定理 `Rep.epi_iff_surjective`：epi_iff_surjective (f : A ⟶ B) : Epi f ↔ Functio
n.Surjective f.hom
· 使用定理 `Submodule.mkQ_surjective`：mkQ_surjective : Function.Surjective p.mkQ
-/
lemma coinvariantsShortComplex_shortExact : (coinvariantsShortComplex.{w} A S).ShortExact where
  exact := (forget₂ (Rep.{w} k G) (ModuleCat k)).reflects_exact_of_faithful _ <|
    (ShortComplex.moduleCat_exact_iff _).2
    fun x hx => ⟨(⟨x, (Submodule.Quotient.mk_eq_zero _).1 hx⟩ : Representation.Coinvariants.ker <|
      A.ρ.comp S.subtype), rfl⟩
  mono_f := (Rep.mono_iff_injective _).2 fun _ _ h => Subtype.ext h
  epi_g := (Rep.epi_iff_surjective _).2 <| Submodule.mkQ_surjective _

end

variable (k G) [Monoid G] (A B : Rep.{w} k G)

/-- The functor sending a representation to its coinvariants. -/
@[implicit_reducible, simps! obj_carrier map_hom]
/-
**Rep.coinvariantsFunctor** 是 Mathlib 中的一个定义，位于命名空间 `Rep`。
形式化陈述：coinvariantsFunctor : Rep.{w} k G ⥤ ModuleCat k where obj A
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The functor sending a representation to its coinvariants.
-/
noncomputable def coinvariantsFunctor : Rep.{w} k G ⥤ ModuleCat k where
  obj A := ModuleCat.of k A.ρ.Coinvariants
  map f := ModuleCat.ofHom (Representation.Coinvariants.map _ _ f.hom)
  map_id _ := by simp
  map_comp _ _ := by ext; simp

/-- The quotient map from a representation to its coinvariants induces a natural transformation
from the forgetful functor `Rep k G ⥤ ModuleCat k` to the coinvariants functor. -/
@[simps! app_hom]
/-
**Rep.coinvariantsMk** 是 Mathlib 中的一个定义，位于命名空间 `Rep`。
形式化陈述：coinvariantsMk : forget₂ (Rep k G) (ModuleCat k) ⟶ coinvariantsFunctor k G
 where app (X : Rep k G)
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The quotient map from a representation to its coinvariants induces a natural tra
nsformation
from the forgetful functor `Rep k G ⥤ ModuleCat k` to the coinvariants functor.
-/
noncomputable def coinvariantsMk : forget₂ (Rep k G) (ModuleCat k) ⟶ coinvariantsFunctor k G where
  app (X : Rep k G) := ModuleCat.ofHom <| Representation.Coinvariants.mk X.ρ
/-
**Rep.** 是 Mathlib 中的一个实例，位于命名空间 `Rep`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance (X : Rep k G) : Epi ((coinvariantsMk k G).app X) :=
  (ModuleCat.epi_iff_surjective _).2 <| Representation.Coinvariants.mk_surjective X.ρ

variable {k G A B}

@[ext]
/-
**Rep.coinvariantsFunctor_hom_ext** 是 Mathlib 中的一个引理，位于命名空间 `Rep`。
形式化陈述：coinvariantsFunctor_hom_ext {M : ModuleCat k} {f g : (coinvariantsFunctor 
k G).obj A ⟶ M} (hfg : (coinvariantsMk k G).app A ≫ f = (coinvariantsMk k G).app
 A ≫ g) : f = g
参数：coinvariantsFunctor k G；hfg : (coinvariantsMk k G).app A ≫ f = (coinvariantsM
k k G).app A ≫ g。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.mp`：∀ {a b : Prop}, (a ↔ b) → a → b
· 使用定理 `CategoryTheory.cancel_epi`：cancel_epi (f : X ⟶ Y) [Epi f] {g h : Y ⟶ Z} 
: f ≫ g = f ≫ h ↔ g = h
· 使用定理 `Rep.instEpiModuleCatAppCoinvariantsMk`：∀ (k : Type u) (G : Type v) [inst
 : CommRing k] [inst_1 : Monoid G] (X : Rep.{u_1, u, v} k G),   CategoryTheory.E
pi ((Rep.coinvariantsMk k G…
-/
lemma coinvariantsFunctor_hom_ext {M : ModuleCat k} {f g : (coinvariantsFunctor k G).obj A ⟶ M}
    (hfg : (coinvariantsMk k G).app A ≫ f = (coinvariantsMk k G).app A ≫ g) :
    f = g := (cancel_epi _).1 hfg

/-- The linear map underlying a `G`-representation morphism `A ⟶ B`, where `B` has the trivial
representation, factors through `A_G`. -/
/-
**Rep.desc** 是 Mathlib 中的一个缩写定义，位于命名空间 `Rep`。
形式化陈述：desc [B.ρ.IsTrivial] (f : A ⟶ B) : (coinvariantsFunctor k G).obj A ⟶ Modul
eCat.of k B.V
参数：f : A ⟶ B。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The linear map underlying a `G`-representation morphism `A ⟶ B`, where `B` has t
he trivial
representation, factors through `A_G`.
-/
noncomputable abbrev desc [B.ρ.IsTrivial] (f : A ⟶ B) :
    (coinvariantsFunctor k G).obj A ⟶ ModuleCat.of k B.V :=
  ModuleCat.ofHom <| Representation.Coinvariants.lift _ f.hom.toLinearMap <| by simp [f.hom.2]

variable (k G)
/-
**Rep.** 是 Mathlib 中的一个实例，位于命名空间 `Rep`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance : (coinvariantsFunctor k G).Additive where
/-
**Rep.** 是 Mathlib 中的一个实例，位于命名空间 `Rep`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance : (coinvariantsFunctor k G).Linear k where

set_option backward.defeqAttrib.useBackward true in
/-- The adjunction between the functor sending a representation to its coinvariants and the functor
equipping a module with the trivial representation. -/
@[simps]
/-
**Rep.coinvariantsAdjunction** 是 Mathlib 中的一个定义，位于命名空间 `Rep`。
形式化陈述：coinvariantsAdjunction : coinvariantsFunctor.{w} k G ⊣ trivialFunctor k G 
where unit
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The adjunction between the functor sending a representation to its coinvariants 
and the functor
equipping a module with the trivial representation.
-/
noncomputable def coinvariantsAdjunction : coinvariantsFunctor.{w} k G ⊣ trivialFunctor k G where
  unit := { app X := Rep.ofHom ⟨((coinvariantsMk k G).app X).hom, fun g ↦ by ext; simp ⟩}
  counit := { app X := desc (B := trivial k G X) (𝟙 _) }

@[simp]
/-
**Rep.coinvariantsAdjunction_homEquiv_apply_hom** 是 Mathlib 中的一个定理，位于命名空间 `Rep`。
形式化陈述：coinvariantsAdjunction_homEquiv_apply_hom {X : Rep.{w} k G} {Y : ModuleCat
 k} (f : (coinvariantsFunctor k G).obj X ⟶ Y) : ((coinvariantsAdjunction k G).ho
mEquiv X Y f).hom.toLinearMap = ((coinvariantsMk k G).app X ≫ f).hom
参数：f : (coinvariantsFunctor k G).obj X ⟶ Y。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem coinvariantsAdjunction_homEquiv_apply_hom {X : Rep.{w} k G} {Y : ModuleCat k}
    (f : (coinvariantsFunctor k G).obj X ⟶ Y) :
    ((coinvariantsAdjunction k G).homEquiv X Y f).hom.toLinearMap =
    ((coinvariantsMk k G).app X ≫ f).hom := by
  rfl

set_option backward.defeqAttrib.useBackward true in
@[simp]
/-
**Rep.coinvariantsAdjunction_homEquiv_symm_apply_hom** 是 Mathlib 中的一个定理，位于命名空间 `
Rep`。
形式化陈述：coinvariantsAdjunction_homEquiv_symm_apply_hom {X : Rep.{w} k G} {Y : Modu
leCat k} (f : X ⟶ (trivialFunctor k G).obj Y) : ((coinvariantsAdjunction k G).ho
mEquiv X Y).symm f = desc f
参数：f : X ⟶ (trivialFunctor k G).obj Y。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `Rep.coinvariantsFunctor_hom_ext`：coinvariantsFunctor_hom_ext {M : Module
Cat k} {f g : (coinvariantsFunctor k G).obj A ⟶ M} (hfg : (coinvariantsMk k G).a
pp A ≫ f = (coinvaria…
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s
· 使用定理 `Rep.instIsTrivialObjModuleCatTrivialFunctor`：∀ {k : Type u} {G : Type v}
 [inst : Ring k] [inst_1 : Monoid G] (X : ModuleCat k),   ((Rep.trivialFunctor k
 G).obj X).IsTrivial
· 使用引理 `ModuleCat.hom_ext`：hom_ext {M N : ModuleCat.{v} R} {f g : M ⟶ N} (hf : f
.hom = g.hom) : f = g
· 使用定理 `LinearMap.ext`：ext {f g : M ->ₛₗ[σ] M₃} (h : forall x, f x = g x) : f = 
g
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `LinearMap.comp.congr_simp`：∀ {R₁ : Type u_2} {R₂ : Type u_3} {R₃ : Type 
u_4} {M₁ : Type u_9} {M₂ : Type u_10} {M₃ : Type u_11} [inst : Semiring R₁]   [i
nst_1 : Semirin…
· 使用定理 `CategoryTheory.ConcreteCategory.hom_ofHom`：∀ {C : Type u} {inst : Catego
ryTheory.Category.{v, u} C} {FC : outParam (C → C → Type u_1)} {CC : outParam (C
 → Type w)}   {inst_1 : outPara…
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
theorem coinvariantsAdjunction_homEquiv_symm_apply_hom {X : Rep.{w} k G} {Y : ModuleCat k}
    (f : X ⟶ (trivialFunctor k G).obj Y) :
    ((coinvariantsAdjunction k G).homEquiv X Y).symm f = desc f := by
  ext
  simp [coinvariantsAdjunction, Adjunction.homEquiv_symm_apply]
/-
**Rep.** 是 Mathlib 中的一个实例，位于命名空间 `Rep`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance : (coinvariantsFunctor k G).PreservesZeroMorphisms where
/-
**Rep.** 是 Mathlib 中的一个实例，位于命名空间 `Rep`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance : (coinvariantsFunctor k G).IsLeftAdjoint := (coinvariantsAdjunction k G).isLeftAdjoint

/-- The functor sending `A, B` to `(A ⊗[k] B)_G`. This is naturally isomorphic to the functor
sending `A, B` to `A ⊗[k[G]] B`, where we give `A` the `k[G]ᵐᵒᵖ`-module structure defined by
`g • a := A.ρ g⁻¹ a`. -/
/-
**Rep.coinvariantsTensor** 是 Mathlib 中的一个缩写定义，位于命名空间 `Rep`。
形式化陈述：coinvariantsTensor : Rep k G ⥤ Rep k G ⥤ ModuleCat k
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The functor sending `A, B` to `(A ⊗[k] B)_G`. This is naturally isomorphic to th
e functor
sending `A, B` to `A ⊗[k[G]] B`, where we give `A` the `k[G]ᵐᵒᵖ`-module structur
e defined by
`g • a := A.ρ g⁻¹ a`.
-/
noncomputable abbrev coinvariantsTensor : Rep k G ⥤ Rep k G ⥤ ModuleCat k :=
  (Functor.postcompose₂.obj (coinvariantsFunctor k G)).obj (MonoidalCategory.curriedTensor _)

variable {k G} (A B)

/-- The bilinear map sending `a : A, b : B` to `⟦a ⊗ₜ b⟧` in `(A ⊗[k] B)_G`. -/
/-
**Rep.coinvariantsTensorMk** 是 Mathlib 中的一个缩写定义，位于命名空间 `Rep`。
形式化陈述：coinvariantsTensorMk (A B : Rep.{u} k G) : A ->ₗ[k] B ->ₗ[k] ((coinvariant
sTensor k G).obj A).obj B
参数：A B : Rep.{u} k G。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The bilinear map sending `a : A, b : B` to `⟦a ⊗ₜ b⟧` in `(A ⊗[k] B)_G`.
-/
noncomputable abbrev coinvariantsTensorMk (A B : Rep.{u} k G) :
    A →ₗ[k] B →ₗ[k] ((coinvariantsTensor k G).obj A).obj B :=
  (TensorProduct.mk k A B).compr₂ (Coinvariants.mk (A.ρ.tprod B.ρ))

variable {A B}
/-
**Rep.coinvariantsTensorMk_apply** 是 Mathlib 中的一个引理，位于命名空间 `Rep`。
形式化陈述：coinvariantsTensorMk_apply {A B : Rep.{u} k G} (a : A) (b : B) : coinvaria
ntsTensorMk A B a b = Coinvariants.mk _ (a otimesₜ[k] b)
参数：a : A；b : B。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma coinvariantsTensorMk_apply {A B : Rep.{u} k G} (a : A) (b : B) :
    coinvariantsTensorMk A B a b = Coinvariants.mk _ (a ⊗ₜ[k] b) := rfl

@[ext]
/-
**Rep.coinvariantsTensor_hom_ext** 是 Mathlib 中的一个引理，位于命名空间 `Rep`。
形式化陈述：coinvariantsTensor_hom_ext {A B : Rep.{u} k G} {M : ModuleCat k} {f g : ((
coinvariantsTensor k G).obj A).obj B ⟶ M} (hfg : (coinvariantsTensorMk A B).comp
r₂ f.hom = (coinvariantsTensorMk A B).compr₂ g.hom) : f = g
参数：(coinvariantsTensor k G).obj A；hfg : (coinvariantsTensorMk A B).compr₂ f.hom 
= (coinvariantsTensorMk A B).compr₂ g.hom。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `Rep.coinvariantsFunctor_hom_ext`：coinvariantsFunctor_hom_ext {M : Module
Cat k} {f g : (coinvariantsFunctor k G).obj A ⟶ M} (hfg : (coinvariantsMk k G).a
pp A ≫ f = (coinvaria…
· 使用引理 `ModuleCat.hom_ext`：hom_ext {M N : ModuleCat.{v} R} {f g : M ⟶ N} (hf : f
.hom = g.hom) : f = g
· 使用定理 `TensorProduct.ext`：ext {g h : M otimes N ->ₛₗ[σ₁₂] P₂} (H : (mk R M N).c
ompr₂ₛₗ g = (mk R M N).compr₂ₛₗ h) : g = h
-/
lemma coinvariantsTensor_hom_ext {A B : Rep.{u} k G} {M : ModuleCat k}
    {f g : ((coinvariantsTensor k G).obj A).obj B ⟶ M}
    (hfg : (coinvariantsTensorMk A B).compr₂ f.hom = (coinvariantsTensorMk A B).compr₂ g.hom) :
    f = g := coinvariantsFunctor_hom_ext <| ModuleCat.hom_ext <| TensorProduct.ext <| hfg
/-
**Rep.** 是 Mathlib 中的一个实例，位于命名空间 `Rep`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance (A : Rep.{u} k G) : ((coinvariantsTensor k G).obj A).Additive where
/-
**Rep.** 是 Mathlib 中的一个实例，位于命名空间 `Rep`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance (A : Rep.{u} k G) : ((coinvariantsTensor k G).obj A).Linear k where

section

variable (k : Type u) {G : Type v} [CommRing k] [Group G]

/-- Given a normal subgroup `S ≤ G`, this is the functor sending a `G`-representation `A` to the
`G ⧸ S`-representation it induces on `A_S`. -/
@[simps! obj_V map_hom_toLinearMap]
/-
**Rep.quotientToCoinvariantsFunctor** 是 Mathlib 中的一个定义，位于命名空间 `Rep`。
形式化陈述：quotientToCoinvariantsFunctor (S : Subgroup G) [S.Normal] : Rep.{w} k G ⥤ 
Rep k (G ⧸ S) where obj X
参数：S : Subgroup G。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a normal subgroup `S ≤ G`, this is the functor sending a `G`-representatio
n `A` to the
`G ⧸ S`-representation it induces on `A_S`.
-/
noncomputable def quotientToCoinvariantsFunctor (S : Subgroup G) [S.Normal] :
    Rep.{w} k G ⥤ Rep k (G ⧸ S) where
  obj X := X.quotientToCoinvariants S
  map {X Y} f := Rep.ofHom ⟨((coinvariantsFunctor k S).map ((resFunctor S.subtype).map f)).hom,
    fun g ↦ QuotientGroup.induction_on g fun g ↦ by ext; simp [hom_comm_apply]⟩
  map_id X := by ext; simp
  map_comp f g := by ext; simp

section Finsupp


open MonoidalCategory Finsupp

variable {k G : Type u} [CommRing k] [Group G] (A : Rep.{u} k G) (α : Type u) [DecidableEq α]

/-- Given a `k`-linear `G`-representation `(A, ρ)` and a type `α`, this is the map
`(A ⊗ (α →₀ k[G]))_G →ₗ[k] (α →₀ A)` sending
`⟦a ⊗ single x (single g r)⟧ ↦ single x (r • ρ(g⁻¹)(a)).` -/
/-
**Rep.coinvariantsTensorFreeToFinsupp** 是 Mathlib 中的一个定义，位于命名空间 `Rep`。
形式化陈述：coinvariantsTensorFreeToFinsupp : (A otimes free.{u, u, u} k G α).ρ.Coinva
riants.{u, u, u} ->ₗ[k] (α ->₀ A)
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.refl`：Equiv.refl (s : Computation α) : s ~ s

--- 原说明 ---
Given a `k`-linear `G`-representation `(A, ρ)` and a type `α`, this is the map
`(A ⊗ (α →₀ k[G]))_G →ₗ[k] (α →₀ A)` sending
`⟦a ⊗ single x (single g r)⟧ ↦ single x (r • ρ(g⁻¹)(a)).`
-/
noncomputable def coinvariantsTensorFreeToFinsupp :
    (A ⊗ free.{u, u, u} k G α).ρ.Coinvariants.{u, u, u} →ₗ[k] (α →₀ A) :=
  (coinvariantsFinsuppLEquiv _ α ≪≫ₗ lcongr (Equiv.refl α) (coinvariantsTprodLeftRegularLEquiv
    A.ρ)).toLinearMap ∘ₗ Coinvariants.map _ _
    (Representation.finsuppTensorRight _ _ _).toIntertwiningMap

variable {α}

@[simp]
/-
**Rep.coinvariantsTensorFreeToFinsupp_mk_tmul_single** 是 Mathlib 中的一个引理，位于命名空间 `
Rep`。
形式化陈述：coinvariantsTensorFreeToFinsupp_mk_tmul_single (x : A) (i : α) (g : G) (r 
: k) : DFunLike.coe (F
参数：x : A；i : α；g : G；r : k。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Equiv.refl`：Equiv.refl (s : Computation α) : s ~ s
· 使用引理 `TensorProduct.finsuppRight_tmul_single`：finsuppRight_tmul_single (i : ι)
 (m : M) (n : N) : finsuppRight R S M N ι (m otimesₜ[R] Finsupp.single i n) = Fi
nsupp.single i (m otimesₜ[R]…
· 使用引理 `Representation.coinvariantsFinsuppLEquiv_apply`：coinvariantsFinsuppLEqui
v_apply (x : Coinvariants (ρ.finsupp α)) : coinvariantsFinsuppLEquiv ρ α x = coi
nvariantsToFinsupp ρ α x
· 使用引理 `Representation.coinvariantsToFinsupp_mk_single`：coinvariantsToFinsupp_mk
_single (x : α) (a : V) : coinvariantsToFinsupp ρ α (Coinvariants.mk _ (single x
 a)) = single x (Coinvariants.mk _ a…
· 使用定理 `Finsupp.lcongr_single`：lcongr_single {ι κ : Sort _} (e₁ : ι ≃ κ) (e₂ : M
 ≃ₛₗ[σ] N) (i : ι) (m : M) : lcongr e₁ e₂ (Finsupp.single i m) = Finsupp.single 
(e₁ i) (e₂ …
· 使用引理 `Representation.coinvariantsTprodLeftRegularLEquiv_apply`：coinvariantsTpr
odLeftRegularLEquiv_apply (x : (ρ.tprod (leftRegular k G)).Coinvariants) : coinv
ariantsTprodLeftRegularLEquiv ρ x = ofCoinvar…
· 使用引理 `Representation.ofCoinvariantsTprodLeftRegular_mk_tmul_single`：ofCoinvari
antsTprodLeftRegular_mk_tmul_single (x : V) (g : G) (r : k) : ofCoinvariantsTpro
dLeftRegular ρ (Coinvariants.mk _ (x otimesₜ .sing…
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma coinvariantsTensorFreeToFinsupp_mk_tmul_single (x : A) (i : α) (g : G) (r : k) :
    DFunLike.coe (F := (A.ρ.tprod (Representation.free k G α)).Coinvariants →ₗ[k] α →₀ A.V)
      (coinvariantsTensorFreeToFinsupp A α) (Coinvariants.mk _ (x ⊗ₜ single i (.single g r))) =
      single i (r • A.ρ g⁻¹ x) := by
  simp [coinvariantsTensorFreeToFinsupp, Representation.finsuppTensorRight]

variable (α)

/-- Given a `k`-linear `G`-representation `(A, ρ)` and a type `α`, this is the map
`(α →₀ A) →ₗ[k] (A ⊗ (α →₀ k[G]))_G` sending `single x a ↦ ⟦a ⊗ₜ single x 1⟧.` -/
/-
**Rep.finsuppToCoinvariantsTensorFree** 是 Mathlib 中的一个定义，位于命名空间 `Rep`。
形式化陈述：finsuppToCoinvariantsTensorFree : (α ->₀ A) ->ₗ[k] Coinvariants (A.ρ.tprod
 (free k G α).ρ)
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.refl`：Equiv.refl (s : Computation α) : s ~ s

--- 原说明 ---
Given a `k`-linear `G`-representation `(A, ρ)` and a type `α`, this is the map
`(α →₀ A) →ₗ[k] (A ⊗ (α →₀ k[G]))_G` sending `single x a ↦ ⟦a ⊗ₜ single x 1⟧.`
-/
noncomputable def finsuppToCoinvariantsTensorFree :
    (α →₀ A) →ₗ[k] Coinvariants (A.ρ.tprod (free k G α).ρ) :=
  Coinvariants.map _ _ (Representation.finsuppTensorRight _ _ _).symm.toIntertwiningMap ∘ₗ
  (coinvariantsFinsuppLEquiv _ α ≪≫ₗ lcongr (Equiv.refl α)
    (coinvariantsTprodLeftRegularLEquiv A.ρ)).symm.toLinearMap

variable {A α}

@[simp]
/-
**Rep.finsuppToCoinvariantsTensorFree_single** 是 Mathlib 中的一个引理，位于命名空间 `Rep`。
形式化陈述：finsuppToCoinvariantsTensorFree_single (i : α) (x : A) : DFunLike.coe (F
参数：i : α；x : A。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `LinearEquiv.isIntertwining_symm_isIntertwining`：∀ {A : Type u_1} {G : Ty
pe u_2} {V : Type u_3} {W : Type u_4} [inst : Semiring A] [inst_1 : Monoid G]   
[inst_2 : AddCommMonoid V] [inst_3 :…
· 使用定理 `Equiv.refl`：Equiv.refl (s : Computation α) : s ~ s
· 使用定理 `LinearMap.comp.congr_simp`：∀ {R₁ : Type u_2} {R₂ : Type u_3} {R₃ : Type 
u_4} {M₁ : Type u_9} {M₂ : Type u_10} {M₃ : Type u_11} [inst : Semiring R₁]   [i
nst_1 : Semirin…
· 使用定理 `LinearEquiv.trans.congr_simp`：∀ {R₁ : Type u_2} {R₂ : Type u_3} {R₃ : Ty
pe u_4} {M₁ : Type u_8} {M₂ : Type u_9} {M₃ : Type u_10} [inst : Semiring R₁]   
[inst_1 : Semiring…
· 使用定理 `Finsupp.lcongr_symm`：lcongr_symm {ι κ : Sort _} (e₁ : ι ≃ κ) (e₂ : M ≃ₛₗ
[σ] N) : (lcongr e₁ e₂).symm = lcongr e₁.symm e₂.symm
· 使用定理 `Finsupp.lcongr_single`：lcongr_single {ι κ : Sort _} (e₁ : ι ≃ κ) (e₂ : M
 ≃ₛₗ[σ] N) (i : ι) (m : M) : lcongr e₁ e₂ (Finsupp.single i m) = Finsupp.single 
(e₁ i) (e₂ …
· 使用定理 `Representation.coinvariantsTprodLeftRegularLEquiv_symm_apply`：∀ {k : Typ
e u_6} {G : Type u_7} {V : Type u_8} [inst : CommRing k] [inst_1 : Group G] [ins
t_2 : AddCommGroup V]   [inst_3 : _root_.Module k …
· 使用定理 `Representation.coinvariantsFinsuppLEquiv_symm_apply`：∀ {k : Type u_6} {G
 : Type u_7} {V : Type u_8} [inst : CommRing k] [inst_1 : Group G] [inst_2 : Add
CommGroup V]   [inst_3 : _root_.Module k …
· 使用引理 `Representation.finsuppToCoinvariants_single_mk`：finsuppToCoinvariants_si
ngle_mk (a : α) (x : V) : finsuppToCoinvariants ρ α (single a <| Coinvariants.mk
 _ x) = Coinvariants.mk _ (single a …
· 使用引理 `TensorProduct.finsuppRight_symm_apply_single`：finsuppRight_symm_apply_si
ngle (i : ι) (m : M) (n : N) : (finsuppRight R S M N ι).symm (Finsupp.single i (
m otimesₜ[R] n)) = m otimesₜ[R] Fi…
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma finsuppToCoinvariantsTensorFree_single (i : α) (x : A) :
    DFunLike.coe (F := (α →₀ A.V) →ₗ[k] (A.ρ.tprod (Representation.free k G α)).Coinvariants)
      (finsuppToCoinvariantsTensorFree A α) (single i x) =
      Coinvariants.mk _ (x ⊗ₜ single i (.single (1 : G) (1 : k))) := by
  simp [finsuppToCoinvariantsTensorFree, Representation.finsuppTensorRight, Equiv.mk_symm]

variable (A α)

/-- Given a `k`-linear `G`-representation `(A, ρ)` and a type `α`, this is the linear equivalence
`(A ⊗ (α →₀ k[G]))_G ≃ₗ[k] (α →₀ A)` sending
`⟦a ⊗ single x (single g r)⟧ ↦ single x (r • ρ(g⁻¹)(a)).` -/
@[simps! symm_apply]
/-
**Rep.coinvariantsTensorFreeLEquiv** 是 Mathlib 中的一个缩写定义，位于命名空间 `Rep`。
形式化陈述：coinvariantsTensorFreeLEquiv : Coinvariants (A otimes free k G α).ρ ≃ₗ[k] 
(α ->₀ A)
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a `k`-linear `G`-representation `(A, ρ)` and a type `α`, this is the linea
r equivalence
`(A ⊗ (α →₀ k[G]))_G ≃ₗ[k] (α →₀ A)` sending
`⟦a ⊗ single x (single g r)⟧ ↦ single x (r • ρ(g⁻¹)(a)).`
-/
noncomputable abbrev coinvariantsTensorFreeLEquiv :
    Coinvariants (A ⊗ free k G α).ρ ≃ₗ[k] (α →₀ A) :=
  .ofLinearMap (coinvariantsTensorFreeToFinsupp A α) (finsuppToCoinvariantsTensorFree A α)
    (lhom_ext fun i x => by
      simp [finsuppToCoinvariantsTensorFree_single,
        coinvariantsTensorFreeToFinsupp_mk_tmul_single]) <|
    Coinvariants.hom_ext <| TensorProduct.ext <| LinearMap.ext fun a => lhom_ext' fun i =>
      MonoidAlgebra.lhom_ext' fun g => LinearMap.ext fun r => by
        simp [coinvariantsTensorFreeToFinsupp_mk_tmul_single _,
          finsuppToCoinvariantsTensorFree_single (A := A) i, TensorProduct.smul_tmul]

@[simp]
/-
**Rep.coinvariantsTensorFreeLEquiv_apply** 是 Mathlib 中的一个引理，位于命名空间 `Rep`。
形式化陈述：coinvariantsTensorFreeLEquiv_apply (x : (A otimes free k G α).ρ.Coinvarian
ts) : DFunLike.coe (F
参数：x : (A otimes free k G α).ρ.Coinvariants。
该定理/引理描述了相关对象所满足的性质。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma coinvariantsTensorFreeLEquiv_apply (x : (A ⊗ free k G α).ρ.Coinvariants) :
    DFunLike.coe (F := (A.ρ.tprod (Representation.free k G α)).Coinvariants →ₗ[k] α →₀ A)
      (A.coinvariantsTensorFreeToFinsupp α) x = coinvariantsTensorFreeToFinsupp A α x := by
  rfl

end Finsupp

end

end Rep

