/-
Copyright (c) 2024 Yakov Pechersky. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yakov Pechersky
-/
module

public import Mathlib.Algebra.Order.Group.Units
public import Mathlib.Algebra.Order.Monoid.LocallyFiniteOrder
public import Mathlib.Data.Int.Interval
public import Mathlib.GroupTheory.Archimedean
public import Mathlib.GroupTheory.OrderOfElement
public import Mathlib.GroupTheory.SpecificGroups.Cyclic
public import Mathlib.Order.Interval.Finset.DenselyOrdered

/-!
# Archimedean groups are either discrete or densely ordered

This file proves a few additional facts about linearly ordered additive groups which satisfy the
`Archimedean` property -- they are either order-isomorphic and additively isomorphic to the
integers, or they are densely ordered.

They are placed here in a separate file (rather than incorporated as a continuation of
`GroupTheory.Archimedean`) because they rely on some imports from pointwise lemmas.
-/

@[expose] public section

open Set
open scoped WithZero

-- no earlier file imports the necessary requirements for the next three

/--
theorem `exists_pow_lt₀` / 定理 `exists_pow_lt₀`

English:
theorem exists_pow_lt₀
  statement: {G : Type*} [LinearOrderedCommGroupWithZero G] [MulArchimedean G]
  proof: by
  rcases eq_or_ne a 0 with rfl | ha'
  · use 1
    simp
  · lift a to Gˣ using IsUnit.mk0 _ ha'
    simpa using! exists_pow_lt ha b

中文:
定理 存在_pow_lt₀
  结论: {G : 类型} [带零LinearOrderedComm群 G] [MulArchimedean G]
  证明: by
  rcases eq_or_ne a 0 with rfl | ha'
  · use 1
    simp
  · lift a to Gˣ using IsUnit.mk0 _ ha'
    simpa using! exists_pow_lt ha b

Depends on / 依赖: IsUnit, IsUnit.mk0, eq_or_ne, exists_pow_lt
-/
theorem exists_pow_lt₀ {G : Type*} [LinearOrderedCommGroupWithZero G] [MulArchimedean G]
    {a : G} (ha : a < 1) (b : Gˣ) : exists n : Nat, a ^ n < b := by
  rcases eq_or_ne a 0 with rfl | ha'
  · use 1
    simp
  · lift a to Gˣ using IsUnit.mk0 _ ha'
    simpa using! exists_pow_lt ha b

/-- The subgroup generated by an element of a group equals the set of
integer powers of the element, such that each power is a unique element.
This is the stronger version of `Subgroup.mem_closure_singleton`. -/
@[to_additive /-- The additive subgroup generated by an element of an additive group equals the set
of integer multiples of the element, such that each multiple is a unique element.
This is the stronger version of `AddSubgroup.mem_closure_singleton`. -/]
/--
lemma `Subgroup.mem_closure_singleton_iff_existsUnique_zpow` / 引理 `Subgroup.mem_closure_singleton_iff_existsUnique_zpow`

English:
lemma Subgroup.mem_closure_singleton_iff_existsUnique_zpow
  statement: {G : Type*}
  proof: by
  rw [mem_closure_singleton]
  constructor
  · suffices Function.Injective (a ^ · : Int -> G) by
      rintro ⟨m, rfl⟩
      exact ⟨m, rfl, fun k hk => this hk⟩
    rcases ha.lt_or_gt with ha | ha
    · exact (zpow_right_strictAnti ha).injective
    · exact (zpow_right_strictMono ha).injective
  · exact fun h => h.exists

中文:
引理 子群.mem_closure_singleton_iff_存在Unique_zpow
  结论: {G : 类型}
  证明: by
  rw [mem_closure_singleton]
  constructor
  · suffices Function.Injective (a ^ · : Int -> G) by
      rintro ⟨m, rfl⟩
      exact ⟨m, rfl, fun k hk => this hk⟩
    rcases ha.lt_or_gt with ha | ha
    · exact (zpow_right_strictAnti ha).injective
    · exact (zpow_right_strictMono ha).injective
  · exact fun h => h.exists

Depends on / 依赖: Function, Function.Injective, Injective, h.exists, ha.lt_or_gt, injective, lt_or_gt, mem_closure_singleton, zpow_right_strictAnti, zpow_right_strictMono
-/
lemma Subgroup.mem_closure_singleton_iff_existsUnique_zpow {G : Type*}
    [CommGroup G] [LinearOrder G] [IsOrderedMonoid G] {a b : G} (ha : a != 1) :
    b in closure {a} ↔ exists! k : Int, a ^ k = b := by
  rw [mem_closure_singleton]
  constructor
  · suffices Function.Injective (a ^ · : Int -> G) by
      rintro ⟨m, rfl⟩
      exact ⟨m, rfl, fun k hk => this hk⟩
    rcases ha.lt_or_gt with ha | ha
    · exact (zpow_right_strictAnti ha).injective
    · exact (zpow_right_strictMono ha).injective
  · exact fun h => h.exists

/--
lemma `Int.addEquiv_eq_refl_or_neg` / 引理 `Int.addEquiv_eq_refl_or_neg`

English:
lemma Int.addEquiv_eq_refl_or_neg
  given: (e : Int ≃+ Int)
  statement: e = .refl _ ∨ e = .neg _
  proof: by
  suffices e 1 = 1 ∨ -e 1 = 1 by simpa [AddEquiv.ext_int_iff, neg_eq_iff_eq_neg]
  have he : ¬IsOfFinAddOrder (e 1) :=
    not_isOfFinAddOrder_of_isAddTorsionFree ((AddEquiv.map_ne_zero_iff e).mpr Int.one_ne_zero)
  rw [← AddSubgroup.zmultiples_eq_zmultiples_iff he]
  simpa [e.surjective, eq_comm] using (e : Int ->+ Int).map_zmultiples 1

中文:
引理 整数.addEquiv_eq_refl_or_neg
  条件: (e : 整数 ≃+ 整数)
  结论: e = .refl _ ∨ e = .neg _
  证明: by
  suffices e 1 = 1 ∨ -e 1 = 1 by simpa [AddEquiv.ext_int_iff, neg_eq_iff_eq_neg]
  have he : ¬IsOfFinAddOrder (e 1) :=
    not_isOfFinAddOrder_of_isAddTorsionFree ((AddEquiv.map_ne_zero_iff e).mpr Int.one_ne_zero)
  rw [← AddSubgroup.zmultiples_eq_zmultiples_iff he]
  simpa [e.surjective, eq_comm] using (e : Int ->+ Int).map_zmultiples 1

Depends on / 依赖: AddEquiv, AddEquiv.ext_int_iff, AddEquiv.map_ne_zero_iff, AddSubgroup, AddSubgroup.zmultiples_eq_zmultiples_iff, Int.one_ne_zero, IsOfFinAddOrder, e.surjective, eq_comm, ext_int_iff, map_ne_zero_iff, map_zmultiples, neg_eq_iff_eq_neg, not_isOfFinAddOrder_of_isAddTorsionFree, one_ne_zero, surjective, zmultiples_eq_zmultiples_iff
-/
lemma Int.addEquiv_eq_refl_or_neg (e : Int ≃+ Int) : e = .refl _ ∨ e = .neg _ := by
  suffices e 1 = 1 ∨ -e 1 = 1 by simpa [AddEquiv.ext_int_iff, neg_eq_iff_eq_neg]
  have he : ¬IsOfFinAddOrder (e 1) :=
    not_isOfFinAddOrder_of_isAddTorsionFree ((AddEquiv.map_ne_zero_iff e).mpr Int.one_ne_zero)
  rw [← AddSubgroup.zmultiples_eq_zmultiples_iff he]
  simpa [e.surjective, eq_comm] using (e : Int ->+ Int).map_zmultiples 1

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: Fintype (Int ≃+ Int)
  body: .cons (.neg _) ({.refl _}) (by simp [AddEquiv.ext_int_iff])
  complete x := by
    obtain rfl | rfl := Int.addEquiv_eq_refl_or_neg x <;>
    simp

@[simp]

中文:
实例 :
  签名: 有限类型 (整数 ≃+ 整数)
  定义体: .cons (.neg _) ({.refl _}) (by simp [AddEquiv.ext_int_iff])
  complete x := by
    obtain rfl | rfl := Int.addEquiv_eq_refl_or_neg x <;>
    simp

@[simp]

Depends on / 依赖: AddEquiv, AddEquiv.ext_int_iff, ext_int_iff
-/
instance : Fintype (Int ≃+ Int) where
  elems := .cons (.neg _) ({.refl _}) (by simp [AddEquiv.ext_int_iff])
  complete x := by
    obtain rfl | rfl := Int.addEquiv_eq_refl_or_neg x <;>
    simp

@[simp]
/--
lemma `Int.univ_addEquiv` / 引理 `Int.univ_addEquiv`

English:
lemma Int.univ_addEquiv
  proof: rfl

中文:
引理 整数.univ_addEquiv
  证明: rfl
-/
lemma Int.univ_addEquiv :
    (Finset.univ : Finset (Int ≃+ Int)) = .cons (.neg Int) {.refl Int} (by simp [AddEquiv.ext_int_iff]) :=
  rfl

/--
lemma `Int.card_fintype_addEquiv` / 引理 `Int.card_fintype_addEquiv`

English:
lemma Int.card_fintype_addEquiv
  statement: Fintype.card (Int ≃+ Int) = 2
  proof: rfl

中文:
引理 整数.card_fintype_addEquiv
  结论: 有限类型.card (整数 ≃+ 整数) = 2
  证明: rfl
-/
@[simp] lemma Int.card_fintype_addEquiv : Fintype.card (Int ≃+ Int) = 2 := rfl

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: Unique (Int ≃+o Int)
  body: OrderAddMonoidIso.toAddEquiv_injective
.resolve_right fun H => by Int.addEquiv_eq_refl_or_neg e
      replace H : e 1 = -1 := congr($H 1)
      have h1 : 0 < e 1 := by
        rw [← map_zero e]; rw [map_lt_map_iff]
        simp
      simp [H] at h1

中文:
实例 :
  签名: 唯一 (整数 ≃+o 整数)
  定义体: OrderAddMonoidIso.toAddEquiv_injective
.resolve_right fun H => by Int.addEquiv_eq_refl_or_neg e
      replace H : e 1 = -1 := congr($H 1)
      have h1 : 0 < e 1 := by
        rw [← map_zero e]; rw [map_lt_map_iff]
        simp
      simp [H] at h1

Depends on / 依赖: OrderAddMonoidIso, OrderAddMonoidIso.toAddEquiv_injective, toAddEquiv_injective
-/
instance : Unique (Int ≃+o Int) where
uniq e := OrderAddMonoidIso.toAddEquiv_injective
.resolve_right fun H => by Int.addEquiv_eq_refl_or_neg e
      replace H : e 1 = -1 := congr($H 1)
      have h1 : 0 < e 1 := by
        rw [← map_zero e]; rw [map_lt_map_iff]
        simp
      simp [H] at h1

open OrderDual in
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: Unique (Int ≃+o Intᵒᵈ)
  body: ⟨AddEquiv.neg Int
uniq e := OrderAddMonoidIso.toAddEquiv_injective by
    simp only [OrderAddMonoidIso.toAddEquiv_eq_coe]
    refine Int.addEquiv_eq_refl_or_neg ((e : Int ≃+ Intᵒᵈ).trans ⟨toDual, toDual_add⟩)
.resolve_left fun H => by
      replace H : e 1 = 1 := congr($H 1)
      have h1 : 0 < e 1 := by
        rw [← map_zero e]; rw [map_lt_map_iff]
        simp
      simp [H, ← ofDual_lt_ofDual] at h1

中文:
实例 :
  签名: 唯一 (整数 ≃+o 整数ᵒᵈ)
  定义体: ⟨AddEquiv.neg Int
uniq e := OrderAddMonoidIso.toAddEquiv_injective by
    simp only [OrderAddMonoidIso.toAddEquiv_eq_coe]
    refine Int.addEquiv_eq_refl_or_neg ((e : Int ≃+ Intᵒᵈ).trans ⟨toDual, toDual_add⟩)
.resolve_left fun H => by
      replace H : e 1 = 1 := congr($H 1)
      have h1 : 0 < e 1 := by
        rw [← map_zero e]; rw [map_lt_map_iff]
        simp
      simp [H, ← ofDual_lt_ofDual] at h1

Depends on / 依赖: AddEquiv, AddEquiv.neg
-/
instance : Unique (Int ≃+o Intᵒᵈ) where
.trans ⟨toDual, toDual_add⟩, by simp⟩ default := ⟨AddEquiv.neg Int
uniq e := OrderAddMonoidIso.toAddEquiv_injective by
    simp only [OrderAddMonoidIso.toAddEquiv_eq_coe]
    refine Int.addEquiv_eq_refl_or_neg ((e : Int ≃+ Intᵒᵈ).trans ⟨toDual, toDual_add⟩)
.resolve_left fun H => by
      replace H : e 1 = 1 := congr($H 1)
      have h1 : 0 < e 1 := by
        rw [← map_zero e]; rw [map_lt_map_iff]
        simp
      simp [H, ← ofDual_lt_ofDual] at h1

open Subgroup in
/-- In two linearly ordered groups, the closure of an element of one group
is isomorphic (and order-isomorphic) to the closure of an element in the other group. -/
@[to_additive /-- In two linearly ordered additive groups, the closure of an element of one group
is isomorphic (and order-isomorphic) to the closure of an element in the other group. -/]
/--
Definition of `LinearOrderedCommGroup.closure_equiv_closure` / `LinearOrderedCommGroup.closure_equiv_closure` 的定义

English:
definition LinearOrderedCommGroup.closure_equiv_closure
  signature: {G G' : Type*}
  body: if hx : x = 1 then by
    refine ⟨⟨⟨fun _ => ⟨1, by simp [hxy.mp hx]⟩, fun _ => ⟨1, by simp [hx]⟩, ?_, ?_⟩, ?_⟩, ?_⟩
    · intro ⟨a, ha⟩
      simpa [hx, closure_singleton_one, eq_comm] using ha
    · intro ⟨a, ha⟩
      simpa [hxy.mp hx, closure_singleton_one, eq_comm] using ha
    · intros
      simp
    · intro ⟨a, ha⟩ ⟨b, hb⟩
      simp only [hx, closure_singleton_one, mem_bot] at ha hb
      simp [ha, hb]
  else by
    set x' := max x x⁻¹ with hx'
    have xpos : 1 < x' := by
      simp [hx', eq_comm, hx]
    set y' := max y y⁻¹ with hy'
    have ypos : 1 < y' := by
      simp [hy', eq_comm, ← hxy, hx]
    have hxc : closure {x} = closure {x'} := by rcases max_cases x x⁻¹ <;> simp_all
    have hyc : closure {y} = closure {y'} := by rcases max_cases y y⁻¹ <;> simp_all
    have Hx : forall (z : closure {x}), z in zpowers ⟨x', by simp [hxc]⟩ := by
      simp_rw [Subtype.forall, hxc, ← zpowers_eq_closure, mem_zpowers_iff, Subtype.ext_iff,
        SubgroupClass.coe_zpow, imp_self, implies_true]
    have Hy : forall (z : closure {y}), z in zpowers ⟨y', by simp [hyc]⟩ := by
      simp_rw [Subtype.forall, hyc, ← zpowers_eq_closure, mem_zpowers_iff, Subtype.ext_iff,
        SubgroupClass.coe_zpow, imp_self, implies_true]
    refine OrderMonoidIso.mk (mulEquivOfOrderOfEq Hx Hy ?_) ?_
    · rw [orderOf_mk, orderOf_mk]
      grind [orderOf_eq_one_iff, IsMulTorsionFree.orderOf_le_one]
    · intro a b
      obtain ⟨m, rfl⟩ := Hx a
      obtain ⟨n, rfl⟩ := Hx b
      simp only [MulEquiv.toEquiv_eq_coe, Equiv.toFun_as_coe, EquivLike.coe_coe, map_zpow,
        mulEquivOfOrderOfEq_apply_gen]
      simp_all [zpow_le_zpow_iff_right, ← Subtype.coe_lt_coe]

中文:
定义 LinearOrderedCommGroup.closure_equiv_closure
  签名: {G G' : 类型}
  定义体: if hx : x = 1 then by
    refine ⟨⟨⟨fun _ => ⟨1, by simp [hxy.mp hx]⟩, fun _ => ⟨1, by simp [hx]⟩, ?_, ?_⟩, ?_⟩, ?_⟩
    · intro ⟨a, ha⟩
      simpa [hx, closure_singleton_one, eq_comm] using ha
    · intro ⟨a, ha⟩
      simpa [hxy.mp hx, closure_singleton_one, eq_comm] using ha
    · intros
      simp
    · intro ⟨a, ha⟩ ⟨b, hb⟩
      simp only [hx, closure_singleton_one, mem_bot] at ha hb
      simp [ha, hb]
  else by
    set x' := max x x⁻¹ with hx'
    have xpos : 1 < x' := by
      simp [hx', eq_comm, hx]
    set y' := max y y⁻¹ with hy'
    have ypos : 1 < y' := by
      simp [hy', eq_comm, ← hxy, hx]
    have hxc : closure {x} = closure {x'} := by rcases max_cases x x⁻¹ <;> simp_all
    have hyc : closure {y} = closure {y'} := by rcases max_cases y y⁻¹ <;> simp_all
    have Hx : forall (z : closure {x}), z in zpowers ⟨x', by simp [hxc]⟩ := by
      simp_rw [Subtype.forall, hxc, ← zpowers_eq_closure, mem_zpowers_iff, Subtype.ext_iff,
        SubgroupClass.coe_zpow, imp_self, implies_true]
    have Hy : forall (z : closure {y}), z in zpowers ⟨y', by simp [hyc]⟩ := by
      simp_rw [Subtype.forall, hyc, ← zpowers_eq_closure, mem_zpowers_iff, Subtype.ext_iff,
        SubgroupClass.coe_zpow, imp_self, implies_true]
    refine OrderMonoidIso.mk (mulEquivOfOrderOfEq Hx Hy ?_) ?_
    · rw [orderOf_mk, orderOf_mk]
      grind [orderOf_eq_one_iff, IsMulTorsionFree.orderOf_le_one]
    · intro a b
      obtain ⟨m, rfl⟩ := Hx a
      obtain ⟨n, rfl⟩ := Hx b
      simp only [MulEquiv.toEquiv_eq_coe, Equiv.toFun_as_coe, EquivLike.coe_coe, map_zpow,
        mulEquivOfOrderOfEq_apply_gen]
      simp_all [zpow_le_zpow_iff_right, ← Subtype.coe_lt_coe]

Depends on / 依赖: closure_singleton_one, eq_comm, hxy.mp, intros, mem_bot
-/
noncomputable def LinearOrderedCommGroup.closure_equiv_closure {G G' : Type*}
    [CommGroup G] [LinearOrder G] [IsOrderedMonoid G]
    [CommGroup G'] [LinearOrder G'] [IsOrderedMonoid G'] (x : G) (y : G') (hxy : x = 1 ↔ y = 1) :
    closure ({x} : Set G) ≃*o closure ({y} : Set G') :=
  if hx : x = 1 then by
    refine ⟨⟨⟨fun _ => ⟨1, by simp [hxy.mp hx]⟩, fun _ => ⟨1, by simp [hx]⟩, ?_, ?_⟩, ?_⟩, ?_⟩
    · intro ⟨a, ha⟩
      simpa [hx, closure_singleton_one, eq_comm] using ha
    · intro ⟨a, ha⟩
      simpa [hxy.mp hx, closure_singleton_one, eq_comm] using ha
    · intros
      simp
    · intro ⟨a, ha⟩ ⟨b, hb⟩
      simp only [hx, closure_singleton_one, mem_bot] at ha hb
      simp [ha, hb]
  else by
    set x' := max x x⁻¹ with hx'
    have xpos : 1 < x' := by
      simp [hx', eq_comm, hx]
    set y' := max y y⁻¹ with hy'
    have ypos : 1 < y' := by
      simp [hy', eq_comm, ← hxy, hx]
    have hxc : closure {x} = closure {x'} := by rcases max_cases x x⁻¹ <;> simp_all
    have hyc : closure {y} = closure {y'} := by rcases max_cases y y⁻¹ <;> simp_all
    have Hx : forall (z : closure {x}), z in zpowers ⟨x', by simp [hxc]⟩ := by
      simp_rw [Subtype.forall, hxc, ← zpowers_eq_closure, mem_zpowers_iff, Subtype.ext_iff,
        SubgroupClass.coe_zpow, imp_self, implies_true]
    have Hy : forall (z : closure {y}), z in zpowers ⟨y', by simp [hyc]⟩ := by
      simp_rw [Subtype.forall, hyc, ← zpowers_eq_closure, mem_zpowers_iff, Subtype.ext_iff,
        SubgroupClass.coe_zpow, imp_self, implies_true]
    refine OrderMonoidIso.mk (mulEquivOfOrderOfEq Hx Hy ?_) ?_
    · rw [orderOf_mk, orderOf_mk]
      grind [orderOf_eq_one_iff, IsMulTorsionFree.orderOf_le_one]
    · intro a b
      obtain ⟨m, rfl⟩ := Hx a
      obtain ⟨n, rfl⟩ := Hx b
      simp only [MulEquiv.toEquiv_eq_coe, Equiv.toFun_as_coe, EquivLike.coe_coe, map_zpow,
        mulEquivOfOrderOfEq_apply_gen]
      simp_all [zpow_le_zpow_iff_right, ← Subtype.coe_lt_coe]

variable {G : Type*} [CommGroup G] [LinearOrder G] [IsOrderedMonoid G] [MulArchimedean G]

@[to_additive]
/--
lemma `Subgroup.isLeast_of_closure_iff_eq_mabs` / 引理 `Subgroup.isLeast_of_closure_iff_eq_mabs`

English:
lemma Subgroup.isLeast_of_closure_iff_eq_mabs
  given: {a b : G}
  proof: by
  constructor <;> intro h
  · have := Subgroup.cyclic_of_min h
    have ha : a in closure ({b} : Set G) := by
      simp [← this]
    rw [mem_closure_singleton] at ha
    obtain ⟨n, rfl⟩ := ha
    have := h.left
    simp only [mem_closure_singleton, mem_ofPred_eq] at this
    obtain ⟨m, hm⟩ := this.left
    have key : m * n = 1 := by
      rw [← zpow_right_inj this.right]; rw [zpow_mul']; rw [hm]; rw [zpow_one]
    rw [Int.mul_eq_one_iff_eq_one_or_neg_one] at key
    rw [eq_comm]
    rcases key with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;>
    simp [this.right.le, this.right, mabs]
  · wlog ha : 1 <= a generalizing a
    · convert! @this (a⁻¹) ?_ (by simpa using le_of_not_ge ha) using 4
      · simp
      · rwa [mabs_inv]
    rw [mabs]; rw [sup_eq_left.mpr ((inv_le_one'.mpr ha).trans ha)] at h
    rcases h with ⟨rfl, h⟩
    refine ⟨?_, ?_⟩
    · simp [h]
    · intro x
      simp only [mem_closure_singleton, mem_ofPred_eq, and_imp, forall_exists_index]
      rintro k rfl hk
      rw [← zpow_one b]; rw [← zpow_mul]; rw [one_mul]; rw [zpow_le_zpow_iff_right h]; rw [← zero_add 1]; rw [← Int.lt_iff_add_one_le]
      contrapose! hk
      rw [← Left.one_le_inv_iff]; rw [← zpow_neg]
      exact one_le_zpow ha (by simp [hk])

中文:
引理 子群.isLeast_of_closure_iff_eq_mabs
  条件: {a b : G}
  证明: by
  constructor <;> intro h
  · have := Subgroup.cyclic_of_min h
    have ha : a in closure ({b} : Set G) := by
      simp [← this]
    rw [mem_closure_singleton] at ha
    obtain ⟨n, rfl⟩ := ha
    have := h.left
    simp only [mem_closure_singleton, mem_ofPred_eq] at this
    obtain ⟨m, hm⟩ := this.left
    have key : m * n = 1 := by
      rw [← zpow_right_inj this.right]; rw [zpow_mul']; rw [hm]; rw [zpow_one]
    rw [Int.mul_eq_one_iff_eq_one_or_neg_one] at key
    rw [eq_comm]
    rcases key with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;>
    simp [this.right.le, this.right, mabs]
  · wlog ha : 1 <= a generalizing a
    · convert! @this (a⁻¹) ?_ (by simpa using le_of_not_ge ha) using 4
      · simp
      · rwa [mabs_inv]
    rw [mabs]; rw [sup_eq_left.mpr ((inv_le_one'.mpr ha).trans ha)] at h
    rcases h with ⟨rfl, h⟩
    refine ⟨?_, ?_⟩
    · simp [h]
    · intro x
      simp only [mem_closure_singleton, mem_ofPred_eq, and_imp, forall_exists_index]
      rintro k rfl hk
      rw [← zpow_one b]; rw [← zpow_mul]; rw [one_mul]; rw [zpow_le_zpow_iff_right h]; rw [← zero_add 1]; rw [← Int.lt_iff_add_one_le]
      contrapose! hk
      rw [← Left.one_le_inv_iff]; rw [← zpow_neg]
      exact one_le_zpow ha (by simp [hk])

Depends on / 依赖: Int.mul_eq_one_iff_eq_one_or_neg_one, Subgroup, Subgroup.cyclic_of_min, closure, cyclic_of_min, eq_comm, h.left, mem_closure_singleton, mem_ofPred_eq, mul_eq_one_iff_eq_one_or_neg_one, this.left, this.right, this.right.le, zpow_mul, zpow_one, zpow_right_inj
-/
lemma Subgroup.isLeast_of_closure_iff_eq_mabs {a b : G} :
    IsLeast {y : G | y in closure ({a} : Set G) ∧ 1 < y} b ↔ b = |a|ₘ ∧ 1 < b := by
  constructor <;> intro h
  · have := Subgroup.cyclic_of_min h
    have ha : a in closure ({b} : Set G) := by
      simp [← this]
    rw [mem_closure_singleton] at ha
    obtain ⟨n, rfl⟩ := ha
    have := h.left
    simp only [mem_closure_singleton, mem_ofPred_eq] at this
    obtain ⟨m, hm⟩ := this.left
    have key : m * n = 1 := by
      rw [← zpow_right_inj this.right]; rw [zpow_mul']; rw [hm]; rw [zpow_one]
    rw [Int.mul_eq_one_iff_eq_one_or_neg_one] at key
    rw [eq_comm]
    rcases key with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ <;>
    simp [this.right.le, this.right, mabs]
  · wlog ha : 1 <= a generalizing a
    · convert! @this (a⁻¹) ?_ (by simpa using le_of_not_ge ha) using 4
      · simp
      · rwa [mabs_inv]
    rw [mabs]; rw [sup_eq_left.mpr ((inv_le_one'.mpr ha).trans ha)] at h
    rcases h with ⟨rfl, h⟩
    refine ⟨?_, ?_⟩
    · simp [h]
    · intro x
      simp only [mem_closure_singleton, mem_ofPred_eq, and_imp, forall_exists_index]
      rintro k rfl hk
      rw [← zpow_one b]; rw [← zpow_mul]; rw [one_mul]; rw [zpow_le_zpow_iff_right h]; rw [← zero_add 1]; rw [← Int.lt_iff_add_one_le]
      contrapose! hk
      rw [← Left.one_le_inv_iff]; rw [← zpow_neg]
      exact one_le_zpow ha (by simp [hk])

/--
Definition of `LinearOrderedAddCommGroup.int_orderAddMonoidIso_of_isLeast_pos` / `LinearOrderedAddCommGroup.int_orderAddMonoidIso_of_isLeast_pos` 的定义

English:
definition LinearOrderedAddCommGroup.int_orderAddMonoidIso_of_isLeast_pos
  signature: {G : Type*}
  body: by
  have : IsLeast {y : G | y in (⊤ : AddSubgroup G) ∧ 0 < y} x := by simpa using h
  replace this := AddSubgroup.cyclic_of_min this
  let e : G ≃+o (⊤ : AddSubgroup G) := ⟨AddSubsemigroup.topEquiv.symm,
    (AddEquiv.strictMono_symm AddSubsemigroup.strictMono_topEquiv).le_iff_le⟩
  let e' : (⊤ : AddSubgroup G) ≃+o AddSubgroup.closure {x} :=
    ⟨AddEquiv.subsemigroupCongr (by simp [this]),
     (AddEquiv.strictMono_subsemigroupCongr _).le_iff_le⟩
  let g : (⊤ : AddSubgroup Int) ≃+o Int := ⟨AddSubsemigroup.topEquiv,
    (AddSubsemigroup.strictMono_topEquiv).le_iff_le⟩
  let g' : AddSubgroup.closure ({1} : Set Int) ≃+o (⊤ : AddSubgroup Int) :=
    ⟨(.subsemigroupCongr (by simp)),
     (AddEquiv.strictMono_subsemigroupCongr _).le_iff_le⟩
  let f := closure_equiv_closure x (1 : Int) (by simp [h.left.ne'])
  exact ((((e.trans e').trans f).trans g').trans g : G ≃+o Int)

中文:
定义 LinearOrderedAddCommGroup.int_orderAddMonoidIso_of_isLeast_pos
  签名: {G : 类型}
  定义体: by
  have : IsLeast {y : G | y in (⊤ : AddSubgroup G) ∧ 0 < y} x := by simpa using h
  replace this := AddSubgroup.cyclic_of_min this
  let e : G ≃+o (⊤ : AddSubgroup G) := ⟨AddSubsemigroup.topEquiv.symm,
    (AddEquiv.strictMono_symm AddSubsemigroup.strictMono_topEquiv).le_iff_le⟩
  let e' : (⊤ : AddSubgroup G) ≃+o AddSubgroup.closure {x} :=
    ⟨AddEquiv.subsemigroupCongr (by simp [this]),
     (AddEquiv.strictMono_subsemigroupCongr _).le_iff_le⟩
  let g : (⊤ : AddSubgroup Int) ≃+o Int := ⟨AddSubsemigroup.topEquiv,
    (AddSubsemigroup.strictMono_topEquiv).le_iff_le⟩
  let g' : AddSubgroup.closure ({1} : Set Int) ≃+o (⊤ : AddSubgroup Int) :=
    ⟨(.subsemigroupCongr (by simp)),
     (AddEquiv.strictMono_subsemigroupCongr _).le_iff_le⟩
  let f := closure_equiv_closure x (1 : Int) (by simp [h.left.ne'])
  exact ((((e.trans e').trans f).trans g').trans g : G ≃+o Int)

Depends on / 依赖: AddEquiv, AddEquiv.strictMono_subsemigroupCongr, AddEquiv.strictMono_symm, AddEquiv.subsemigroupCongr, AddSubgroup, AddSubgroup.closure, AddSubgroup.cyclic_of_min, AddSubsemigroup, AddSubsemigroup.strictMono_topEquiv, AddSubsemigroup.topEquiv, AddSubsemigroup.topEquiv.symm, IsLeast, closure, cyclic_of_min, le_iff_le, replace, strictMono_subsemigroupCongr, strictMono_symm, strictMono_topEquiv, subsemigroupCongr
-/
noncomputable def LinearOrderedAddCommGroup.int_orderAddMonoidIso_of_isLeast_pos {G : Type*}
    [AddCommGroup G] [LinearOrder G] [IsOrderedAddMonoid G] [Archimedean G] {x : G}
    (h : IsLeast {y : G | 0 < y} x) : G ≃+o Int := by
  have : IsLeast {y : G | y in (⊤ : AddSubgroup G) ∧ 0 < y} x := by simpa using h
  replace this := AddSubgroup.cyclic_of_min this
  let e : G ≃+o (⊤ : AddSubgroup G) := ⟨AddSubsemigroup.topEquiv.symm,
    (AddEquiv.strictMono_symm AddSubsemigroup.strictMono_topEquiv).le_iff_le⟩
  let e' : (⊤ : AddSubgroup G) ≃+o AddSubgroup.closure {x} :=
    ⟨AddEquiv.subsemigroupCongr (by simp [this]),
     (AddEquiv.strictMono_subsemigroupCongr _).le_iff_le⟩
  let g : (⊤ : AddSubgroup Int) ≃+o Int := ⟨AddSubsemigroup.topEquiv,
    (AddSubsemigroup.strictMono_topEquiv).le_iff_le⟩
  let g' : AddSubgroup.closure ({1} : Set Int) ≃+o (⊤ : AddSubgroup Int) :=
    ⟨(.subsemigroupCongr (by simp)),
     (AddEquiv.strictMono_subsemigroupCongr _).le_iff_le⟩
  let f := closure_equiv_closure x (1 : Int) (by simp [h.left.ne'])
  exact ((((e.trans e').trans f).trans g').trans g : G ≃+o Int)

set_option backward.isDefEq.respectTransparency false in
/--
Definition of `LinearOrderedCommGroup.multiplicative_int_orderMonoidIso_of_isLeast_one_lt` / `LinearOrderedCommGroup.multiplicative_int_orderMonoidIso_of_isLeast_one_lt` 的定义

English:
definition LinearOrderedCommGroup.multiplicative_int_orderMonoidIso_of_isLeast_one_lt
  body: by
  have : IsLeast {y : Additive G | 0 < y} (.ofMul x) := h
  let f' := LinearOrderedAddCommGroup.int_orderAddMonoidIso_of_isLeast_pos (G := Additive G) this
  exact f'.toMultiplicativeRight

中文:
定义 LinearOrderedCommGroup.multiplicative_int_orderMonoidIso_of_isLeast_one_lt
  定义体: by
  have : IsLeast {y : Additive G | 0 < y} (.ofMul x) := h
  let f' := LinearOrderedAddCommGroup.int_orderAddMonoidIso_of_isLeast_pos (G := Additive G) this
  exact f'.toMultiplicativeRight

Depends on / 依赖: Additive, IsLeast, LinearOrderedAddCommGroup, LinearOrderedAddCommGroup.int_orderAddMonoidIso_of_isLeast_pos, int_orderAddMonoidIso_of_isLeast_pos, toMultiplicativeRight
-/
noncomputable def LinearOrderedCommGroup.multiplicative_int_orderMonoidIso_of_isLeast_one_lt
    {x : G} (h : IsLeast {y : G | 1 < y} x) : G ≃*o Multiplicative Int := by
  have : IsLeast {y : Additive G | 0 < y} (.ofMul x) := h
  let f' := LinearOrderedAddCommGroup.int_orderAddMonoidIso_of_isLeast_pos (G := Additive G) this
  exact f'.toMultiplicativeRight

/--
lemma `Archimedean.of_locallyFiniteOrder` / 引理 `Archimedean.of_locallyFiniteOrder`

English:
lemma Archimedean.of_locallyFiniteOrder
  statement: {G : Type*} [AddCommGroup G] [LinearOrder G]
  proof: .comap (LocallyFiniteOrder.addMonoidHom G) LocallyFiniteOrder.orderAddMonoidHom_strictMono

中文:
引理 阿基米德.of_locallyFiniteOrder
  结论: {G : 类型} [加法交换群 G] [线性序 G]
  证明: .comap (LocallyFiniteOrder.addMonoidHom G) LocallyFiniteOrder.orderAddMonoidHom_strictMono

Depends on / 依赖: LocallyFiniteOrder, LocallyFiniteOrder.addMonoidHom, LocallyFiniteOrder.orderAddMonoidHom_strictMono, addMonoidHom, orderAddMonoidHom_strictMono
-/
lemma Archimedean.of_locallyFiniteOrder {G : Type*} [AddCommGroup G] [LinearOrder G]
    [IsOrderedAddMonoid G] [LocallyFiniteOrder G] :
    Archimedean G :=
  .comap (LocallyFiniteOrder.addMonoidHom G) LocallyFiniteOrder.orderAddMonoidHom_strictMono

/-- Any locally finite linear group is mul-archimedean. -/
@[to_additive existing]
/--
lemma `MulArchimedean.of_locallyFiniteOrder` / 引理 `MulArchimedean.of_locallyFiniteOrder`

English:
lemma MulArchimedean.of_locallyFiniteOrder
  statement: {G : Type*} [CommGroup G] [LinearOrder G]
  proof: .comap (LocallyFiniteOrder.orderMonoidHom G).toMonoidHom
    LocallyFiniteOrder.orderMonoidHom_strictMono

中文:
引理 MulArchimedean.of_locallyFiniteOrder
  结论: {G : 类型} [交换群 G] [线性序 G]
  证明: .comap (LocallyFiniteOrder.orderMonoidHom G).toMonoidHom
    LocallyFiniteOrder.orderMonoidHom_strictMono

Depends on / 依赖: LocallyFiniteOrder, LocallyFiniteOrder.orderMonoidHom, LocallyFiniteOrder.orderMonoidHom_strictMono, orderMonoidHom, orderMonoidHom_strictMono, toMonoidHom
-/
lemma MulArchimedean.of_locallyFiniteOrder {G : Type*} [CommGroup G] [LinearOrder G]
    [IsOrderedMonoid G] [LocallyFiniteOrder G] :
    MulArchimedean G :=
  .comap (LocallyFiniteOrder.orderMonoidHom G).toMonoidHom
    LocallyFiniteOrder.orderMonoidHom_strictMono

/--
lemma `LinearOrderedAddCommGroup.discrete_or_denselyOrdered` / 引理 `LinearOrderedAddCommGroup.discrete_or_denselyOrdered`

English:
lemma LinearOrderedAddCommGroup.discrete_or_denselyOrdered
  statement: (G : Type*)
  proof: by
  by_cases! H : exists x, IsLeast {y : G | 0 < y} x
  · obtain ⟨x, hx⟩ := H
    exact Or.inl ⟨(int_orderAddMonoidIso_of_isLeast_pos hx)⟩
  · refine Or.inr ⟨?_⟩
    intro x y hxy
    specialize H (y - x)
    obtain ⟨z, hz⟩ : exists z : G, 0 < z ∧ z < y - x := by
      contrapose! H
      refine ⟨by simp [hxy], fun _ => H _⟩
    refine ⟨x + z, ?_, ?_⟩
    · simp [hz.left]
    · simpa [lt_sub_iff_add_lt'] using hz.right

中文:
引理 LinearOrderedAddCommGroup.discrete_or_denselyOrdered
  结论: (G : 类型)
  证明: by
  by_cases! H : exists x, IsLeast {y : G | 0 < y} x
  · obtain ⟨x, hx⟩ := H
    exact Or.inl ⟨(int_orderAddMonoidIso_of_isLeast_pos hx)⟩
  · refine Or.inr ⟨?_⟩
    intro x y hxy
    specialize H (y - x)
    obtain ⟨z, hz⟩ : exists z : G, 0 < z ∧ z < y - x := by
      contrapose! H
      refine ⟨by simp [hxy], fun _ => H _⟩
    refine ⟨x + z, ?_, ?_⟩
    · simp [hz.left]
    · simpa [lt_sub_iff_add_lt'] using hz.right

Depends on / 依赖: IsLeast, Or.inl, Or.inr, contrapose, hz.left, hz.right, int_orderAddMonoidIso_of_isLeast_pos, lt_sub_iff_add_lt, specialize
-/
lemma LinearOrderedAddCommGroup.discrete_or_denselyOrdered (G : Type*)
    [AddCommGroup G] [LinearOrder G] [IsOrderedAddMonoid G] [Archimedean G] :
    Nonempty (G ≃+o Int) ∨ DenselyOrdered G := by
  by_cases! H : exists x, IsLeast {y : G | 0 < y} x
  · obtain ⟨x, hx⟩ := H
    exact Or.inl ⟨(int_orderAddMonoidIso_of_isLeast_pos hx)⟩
  · refine Or.inr ⟨?_⟩
    intro x y hxy
    specialize H (y - x)
    obtain ⟨z, hz⟩ : exists z : G, 0 < z ∧ z < y - x := by
      contrapose! H
      refine ⟨by simp [hxy], fun _ => H _⟩
    refine ⟨x + z, ?_, ?_⟩
    · simp [hz.left]
    · simpa [lt_sub_iff_add_lt'] using hz.right

/--
lemma `LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered` / 引理 `LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered`

English:
lemma LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered
  statement: (G : Type*)
  proof: by
  suffices forall (_ : G ≃+o Int), ¬ DenselyOrdered G by
    rcases LinearOrderedAddCommGroup.discrete_or_denselyOrdered G with ⟨⟨h⟩⟩ | h
    · simpa [this h] using ⟨h⟩
    · simp only [h, not_true_eq_false, iff_false, not_nonempty_iff]
      exact ⟨fun H => (this H) h⟩
  intro e H
  rw [denselyOrdered_iff_of_orderIsoClass e] at H
  obtain ⟨_, _⟩ := exists_between (one_pos (α := Int))
  lia

中文:
引理 LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered
  结论: (G : 类型)
  证明: by
  suffices forall (_ : G ≃+o Int), ¬ DenselyOrdered G by
    rcases LinearOrderedAddCommGroup.discrete_or_denselyOrdered G with ⟨⟨h⟩⟩ | h
    · simpa [this h] using ⟨h⟩
    · simp only [h, not_true_eq_false, iff_false, not_nonempty_iff]
      exact ⟨fun H => (this H) h⟩
  intro e H
  rw [denselyOrdered_iff_of_orderIsoClass e] at H
  obtain ⟨_, _⟩ := exists_between (one_pos (α := Int))
  lia

Depends on / 依赖: DenselyOrdered, LinearOrderedAddCommGroup, LinearOrderedAddCommGroup.discrete_or_denselyOrdered, denselyOrdered_iff_of_orderIsoClass, discrete_or_denselyOrdered, exists_between, iff_false, not_nonempty_iff, not_true_eq_false, one_pos
-/
lemma LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered (G : Type*)
    [AddCommGroup G] [LinearOrder G] [IsOrderedAddMonoid G] [Archimedean G] :
    Nonempty (G ≃+o Int) ↔ ¬ DenselyOrdered G := by
  suffices forall (_ : G ≃+o Int), ¬ DenselyOrdered G by
    rcases LinearOrderedAddCommGroup.discrete_or_denselyOrdered G with ⟨⟨h⟩⟩ | h
    · simpa [this h] using ⟨h⟩
    · simp only [h, not_true_eq_false, iff_false, not_nonempty_iff]
      exact ⟨fun H => (this H) h⟩
  intro e H
  rw [denselyOrdered_iff_of_orderIsoClass e] at H
  obtain ⟨_, _⟩ := exists_between (one_pos (α := Int))
  lia

/--
lemma `LinearOrderedAddCommGroup.isAddCyclic_iff_not_denselyOrdered` / 引理 `LinearOrderedAddCommGroup.isAddCyclic_iff_not_denselyOrdered`

English:
lemma LinearOrderedAddCommGroup.isAddCyclic_iff_not_denselyOrdered
  statement: {A : Type*}
  proof: by
  rw [← discrete_iff_not_denselyOrdered]; rw [isAddCyclic_iff_nonempty_equiv_int]

中文:
引理 LinearOrderedAddCommGroup.isAddCyclic_iff_not_denselyOrdered
  结论: {A : 类型}
  证明: by
  rw [← discrete_iff_not_denselyOrdered]; rw [isAddCyclic_iff_nonempty_equiv_int]

Depends on / 依赖: discrete_iff_not_denselyOrdered, isAddCyclic_iff_nonempty_equiv_int
-/
lemma LinearOrderedAddCommGroup.isAddCyclic_iff_not_denselyOrdered {A : Type*}
    [AddCommGroup A] [LinearOrder A] [IsOrderedAddMonoid A] [Archimedean A] [Nontrivial A] :
    IsAddCyclic A ↔ ¬ DenselyOrdered A := by
  rw [← discrete_iff_not_denselyOrdered]; rw [isAddCyclic_iff_nonempty_equiv_int]

set_option backward.isDefEq.respectTransparency false in
variable (G) in
/--
lemma `LinearOrderedCommGroup.discrete_or_denselyOrdered` / 引理 `LinearOrderedCommGroup.discrete_or_denselyOrdered`

English:
lemma LinearOrderedCommGroup.discrete_or_denselyOrdered
  proof: by
  rw [← OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr]
  exact LinearOrderedAddCommGroup.discrete_or_denselyOrdered (Additive G)

中文:
引理 LinearOrderedCommGroup.discrete_or_denselyOrdered
  证明: by
  rw [← OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr]
  exact LinearOrderedAddCommGroup.discrete_or_denselyOrdered (Additive G)

Depends on / 依赖: Additive, LinearOrderedAddCommGroup, LinearOrderedAddCommGroup.discrete_or_denselyOrdered, OrderAddMonoidIso, OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr, discrete_or_denselyOrdered, nonempty_congr, toMultiplicativeRight
-/
lemma LinearOrderedCommGroup.discrete_or_denselyOrdered :
    Nonempty (G ≃*o Multiplicative Int) ∨ DenselyOrdered G := by
  rw [← OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr]
  exact LinearOrderedAddCommGroup.discrete_or_denselyOrdered (Additive G)

set_option backward.isDefEq.respectTransparency false in
variable (G) in
/--
lemma `LinearOrderedCommGroup.discrete_iff_not_denselyOrdered` / 引理 `LinearOrderedCommGroup.discrete_iff_not_denselyOrdered`

English:
lemma LinearOrderedCommGroup.discrete_iff_not_denselyOrdered
  proof: by
  let e : G ≃o Additive G := .refl G
  rw [← OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr]; rw [LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered]; rw [denselyOrdered_iff_of_orderIsoClass e]

中文:
引理 LinearOrderedCommGroup.discrete_iff_not_denselyOrdered
  证明: by
  let e : G ≃o Additive G := .refl G
  rw [← OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr]; rw [LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered]; rw [denselyOrdered_iff_of_orderIsoClass e]

Depends on / 依赖: Additive, LinearOrderedAddCommGroup, LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered, OrderAddMonoidIso, OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr, denselyOrdered_iff_of_orderIsoClass, discrete_iff_not_denselyOrdered, nonempty_congr, toMultiplicativeRight
-/
lemma LinearOrderedCommGroup.discrete_iff_not_denselyOrdered :
    Nonempty (G ≃*o Multiplicative Int) ↔ ¬ DenselyOrdered G := by
  let e : G ≃o Additive G := .refl G
  rw [← OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr]; rw [LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered]; rw [denselyOrdered_iff_of_orderIsoClass e]

set_option backward.isDefEq.respectTransparency false in
/-- Any non-trivial linearly ordered mul-archimedean group is either cyclic, or densely ordered,
exclusively. -/
@[to_additive existing]
/--
lemma `LinearOrderedCommGroup.isCyclic_iff_not_denselyOrdered` / 引理 `LinearOrderedCommGroup.isCyclic_iff_not_denselyOrdered`

English:
lemma LinearOrderedCommGroup.isCyclic_iff_not_denselyOrdered
  given: [Nontrivial G]
  proof: by
  rw [← isAddCyclic_additive_iff]; rw [LinearOrderedAddCommGroup.isAddCyclic_iff_not_denselyOrdered]
  rfl

中文:
引理 LinearOrderedCommGroup.isCyclic_iff_not_denselyOrdered
  条件: [非平凡 G]
  证明: by
  rw [← isAddCyclic_additive_iff]; rw [LinearOrderedAddCommGroup.isAddCyclic_iff_not_denselyOrdered]
  rfl

Depends on / 依赖: LinearOrderedAddCommGroup, LinearOrderedAddCommGroup.isAddCyclic_iff_not_denselyOrdered, isAddCyclic_additive_iff, isAddCyclic_iff_not_denselyOrdered
-/
lemma LinearOrderedCommGroup.isCyclic_iff_not_denselyOrdered [Nontrivial G] :
    IsCyclic G ↔ ¬ DenselyOrdered G := by
  rw [← isAddCyclic_additive_iff]; rw [LinearOrderedAddCommGroup.isAddCyclic_iff_not_denselyOrdered]
  rfl

/--
lemma `LinearOrderedCommGroupWithZero.discrete_or_denselyOrdered` / 引理 `LinearOrderedCommGroupWithZero.discrete_or_denselyOrdered`

English:
lemma LinearOrderedCommGroupWithZero.discrete_or_denselyOrdered
  statement: (G : Type*)
  proof: by
  rw [← denselyOrdered_units_iff]
  refine (LinearOrderedCommGroup.discrete_or_denselyOrdered Gˣ).imp_left ?_
  intro ⟨f⟩
  exact ⟨OrderMonoidIso.withZeroUnits.symm.trans f.withZero⟩

中文:
引理 带零LinearOrderedComm群.discrete_or_denselyOrdered
  结论: (G : 类型)
  证明: by
  rw [← denselyOrdered_units_iff]
  refine (LinearOrderedCommGroup.discrete_or_denselyOrdered Gˣ).imp_left ?_
  intro ⟨f⟩
  exact ⟨OrderMonoidIso.withZeroUnits.symm.trans f.withZero⟩

Depends on / 依赖: LinearOrderedCommGroup, LinearOrderedCommGroup.discrete_or_denselyOrdered, OrderMonoidIso, OrderMonoidIso.withZeroUnits.symm.trans, denselyOrdered_units_iff, discrete_or_denselyOrdered, f.withZero, imp_left, withZero, withZeroUnits
-/
lemma LinearOrderedCommGroupWithZero.discrete_or_denselyOrdered (G : Type*)
    [LinearOrderedCommGroupWithZero G] [Nontrivial Gˣ] [MulArchimedean G] :
    Nonempty (G ≃*o Intᵐ⁰) ∨ DenselyOrdered G := by
  rw [← denselyOrdered_units_iff]
  refine (LinearOrderedCommGroup.discrete_or_denselyOrdered Gˣ).imp_left ?_
  intro ⟨f⟩
  exact ⟨OrderMonoidIso.withZeroUnits.symm.trans f.withZero⟩

set_option backward.isDefEq.respectTransparency false in
open WithZero in
/--
lemma `LinearOrderedCommGroupWithZero.discrete_iff_not_denselyOrdered` / 引理 `LinearOrderedCommGroupWithZero.discrete_iff_not_denselyOrdered`

English:
lemma LinearOrderedCommGroupWithZero.discrete_iff_not_denselyOrdered
  statement: (G : Type*)
  proof: by
  rw [← denselyOrdered_units_iff]; rw [← LinearOrderedCommGroup.discrete_iff_not_denselyOrdered]
  refine Nonempty.congr ?_ ?_ <;> intro f
  · refine ⟨MulEquiv.withZero.symm (withZeroUnitsEquiv.trans f), ?_⟩
    intros
    simp only [MulEquiv.withZero, withZeroUnitsEquiv, MulEquiv.trans_apply,
      MulEquiv.coe_mk, Equiv.coe_fn_mk, recZeroCoe_coe, OrderMonoidIso.coe_mulEquiv,
      MulEquiv.symm_trans_apply, MulEquiv.symm_mk, Equiv.coe_fn_symm_mk, map_eq_zero, coe_ne_zero,
      ↓reduceDIte, unzero_coe, MulEquiv.toEquiv_eq_coe, Equiv.toFun_as_coe, EquivLike.coe_coe]
    rw [← Units.val_le_val]; rw [← map_le_map_iff f]; rw [← coe_le_coe]; rw [coe_unzero]; rw [coe_unzero]
  · refine ⟨withZeroUnitsEquiv.symm.trans (MulEquiv.withZero f), ?_⟩
    intros
    simp only [withZeroUnitsEquiv, MulEquiv.symm_mk, MulEquiv.withZero,
      MulEquiv.toEquiv_eq_coe, Equiv.toFun_as_coe, EquivLike.coe_coe,
      MulEquiv.trans_apply, MulEquiv.coe_mk, Equiv.coe_fn_symm_mk, Equiv.coe_fn_mk]
    split_ifs <;>
    simp_all [← Units.val_le_val]

中文:
引理 带零LinearOrderedComm群.discrete_iff_not_denselyOrdered
  结论: (G : 类型)
  证明: by
  rw [← denselyOrdered_units_iff]; rw [← LinearOrderedCommGroup.discrete_iff_not_denselyOrdered]
  refine Nonempty.congr ?_ ?_ <;> intro f
  · refine ⟨MulEquiv.withZero.symm (withZeroUnitsEquiv.trans f), ?_⟩
    intros
    simp only [MulEquiv.withZero, withZeroUnitsEquiv, MulEquiv.trans_apply,
      MulEquiv.coe_mk, Equiv.coe_fn_mk, recZeroCoe_coe, OrderMonoidIso.coe_mulEquiv,
      MulEquiv.symm_trans_apply, MulEquiv.symm_mk, Equiv.coe_fn_symm_mk, map_eq_zero, coe_ne_zero,
      ↓reduceDIte, unzero_coe, MulEquiv.toEquiv_eq_coe, Equiv.toFun_as_coe, EquivLike.coe_coe]
    rw [← Units.val_le_val]; rw [← map_le_map_iff f]; rw [← coe_le_coe]; rw [coe_unzero]; rw [coe_unzero]
  · refine ⟨withZeroUnitsEquiv.symm.trans (MulEquiv.withZero f), ?_⟩
    intros
    simp only [withZeroUnitsEquiv, MulEquiv.symm_mk, MulEquiv.withZero,
      MulEquiv.toEquiv_eq_coe, Equiv.toFun_as_coe, EquivLike.coe_coe,
      MulEquiv.trans_apply, MulEquiv.coe_mk, Equiv.coe_fn_symm_mk, Equiv.coe_fn_mk]
    split_ifs <;>
    simp_all [← Units.val_le_val]

Depends on / 依赖: Equiv.coe_fn_mk, Equiv.coe_fn_symm_mk, LinearOrderedCommGroup, LinearOrderedCommGroup.discrete_iff_not_denselyOrdered, MulEquiv, MulEquiv.coe_mk, MulEquiv.symm_mk, MulEquiv.symm_trans_apply, MulEquiv.toEquiv_eq, MulEquiv.trans_apply, MulEquiv.withZero, MulEquiv.withZero.symm, Nonempty, Nonempty.congr, OrderMonoidIso, OrderMonoidIso.coe_mulEquiv, coe_fn_mk, coe_fn_symm_mk, coe_mk, coe_mulEquiv
-/
lemma LinearOrderedCommGroupWithZero.discrete_iff_not_denselyOrdered (G : Type*)
    [LinearOrderedCommGroupWithZero G] [Nontrivial Gˣ] [MulArchimedean G] :
    Nonempty (G ≃*o Intᵐ⁰) ↔ ¬ DenselyOrdered G := by
  rw [← denselyOrdered_units_iff]; rw [← LinearOrderedCommGroup.discrete_iff_not_denselyOrdered]
  refine Nonempty.congr ?_ ?_ <;> intro f
  · refine ⟨MulEquiv.withZero.symm (withZeroUnitsEquiv.trans f), ?_⟩
    intros
    simp only [MulEquiv.withZero, withZeroUnitsEquiv, MulEquiv.trans_apply,
      MulEquiv.coe_mk, Equiv.coe_fn_mk, recZeroCoe_coe, OrderMonoidIso.coe_mulEquiv,
      MulEquiv.symm_trans_apply, MulEquiv.symm_mk, Equiv.coe_fn_symm_mk, map_eq_zero, coe_ne_zero,
      ↓reduceDIte, unzero_coe, MulEquiv.toEquiv_eq_coe, Equiv.toFun_as_coe, EquivLike.coe_coe]
    rw [← Units.val_le_val]; rw [← map_le_map_iff f]; rw [← coe_le_coe]; rw [coe_unzero]; rw [coe_unzero]
  · refine ⟨withZeroUnitsEquiv.symm.trans (MulEquiv.withZero f), ?_⟩
    intros
    simp only [withZeroUnitsEquiv, MulEquiv.symm_mk, MulEquiv.withZero,
      MulEquiv.toEquiv_eq_coe, Equiv.toFun_as_coe, EquivLike.coe_coe,
      MulEquiv.trans_apply, MulEquiv.coe_mk, Equiv.coe_fn_symm_mk, Equiv.coe_fn_mk]
    split_ifs <;>
    simp_all [← Units.val_le_val]

section WellFounded

set_option backward.isDefEq.respectTransparency false in
/--
lemma `LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete` / 引理 `LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete`

English:
lemma LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete
  proof: by
  suffices Set.WellFoundedOn {x : G | 0 <= x} (· < ·) ↔ Nonempty (G ≃+o Int) by
    rw [← this]
    refine ⟨fun h => (h.mapsTo (· + g) ?_).mono' ?_, fun h => (h.mapsTo (· - g) ?_).mono' ?_⟩ <;>
    · try intro
      simp [Function.onFun]
  constructor
  · intro h
    replace h : WellFounded (α := {x : G | 0 <= x}) (· < ·) := h
    rw [WellFounded.wellFounded_iff_has_min] at h
    by_cases! H : forall (x : G) {y}, 0 < y -> exists n : Nat, x <= n • y -- Archimedean
    · replace H : Archimedean G := ⟨H⟩
      rw [LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered]
      intro hd
      obtain ⟨y, hy⟩ := exists_ne (0 : G)
      wlog! hy' : 0 < y generalizing y
      · refine this (-y) ?_ ?_
        · simp [hy]
        · simp [lt_of_le_of_ne hy' hy]
      obtain ⟨⟨z, hz⟩, hz', hz''⟩ := h ({x | ⟨0, le_rfl⟩ < x}) ⟨⟨y, hy'.le⟩, hy'⟩
      obtain ⟨w, hw, hw'⟩ := exists_between hz'
      exact hz'' ⟨w, hw.le⟩ hw hw'
    · exfalso
      obtain ⟨x, y, hy0, H⟩ := H
      obtain ⟨_, ⟨n, rfl⟩, hz⟩ :=
        h (Set.range (fun n : Nat => ⟨x - n • y, sub_nonneg.mpr (H _).le⟩)) (range_nonempty _)
      refine hz ⟨x - (n + 1) • y, sub_nonneg.mpr (H _).le⟩ ⟨_, rfl⟩ ?_
      simp [add_smul, hy0]
  · rintro ⟨f⟩
    have : LocallyFiniteOrder G := LocallyFiniteOrder.ofOrderIsoClass f
    exact BddBelow.wellFoundedOn_lt ⟨0, by simp [mem_lowerBounds]⟩

@[deprecated (since := "2026-07-09")]
alias LinearOrderedAddCommGroup.wellFoundedOn_setOf_le_lt_iff_nonempty_discrete :=
  LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete

中文:
引理 LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete
  证明: by
  suffices Set.WellFoundedOn {x : G | 0 <= x} (· < ·) ↔ Nonempty (G ≃+o Int) by
    rw [← this]
    refine ⟨fun h => (h.mapsTo (· + g) ?_).mono' ?_, fun h => (h.mapsTo (· - g) ?_).mono' ?_⟩ <;>
    · try intro
      simp [Function.onFun]
  constructor
  · intro h
    replace h : WellFounded (α := {x : G | 0 <= x}) (· < ·) := h
    rw [WellFounded.wellFounded_iff_has_min] at h
    by_cases! H : forall (x : G) {y}, 0 < y -> exists n : Nat, x <= n • y -- Archimedean
    · replace H : Archimedean G := ⟨H⟩
      rw [LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered]
      intro hd
      obtain ⟨y, hy⟩ := exists_ne (0 : G)
      wlog! hy' : 0 < y generalizing y
      · refine this (-y) ?_ ?_
        · simp [hy]
        · simp [lt_of_le_of_ne hy' hy]
      obtain ⟨⟨z, hz⟩, hz', hz''⟩ := h ({x | ⟨0, le_rfl⟩ < x}) ⟨⟨y, hy'.le⟩, hy'⟩
      obtain ⟨w, hw, hw'⟩ := exists_between hz'
      exact hz'' ⟨w, hw.le⟩ hw hw'
    · exfalso
      obtain ⟨x, y, hy0, H⟩ := H
      obtain ⟨_, ⟨n, rfl⟩, hz⟩ :=
        h (Set.range (fun n : Nat => ⟨x - n • y, sub_nonneg.mpr (H _).le⟩)) (range_nonempty _)
      refine hz ⟨x - (n + 1) • y, sub_nonneg.mpr (H _).le⟩ ⟨_, rfl⟩ ?_
      simp [add_smul, hy0]
  · rintro ⟨f⟩
    have : LocallyFiniteOrder G := LocallyFiniteOrder.ofOrderIsoClass f
    exact BddBelow.wellFoundedOn_lt ⟨0, by simp [mem_lowerBounds]⟩

@[deprecated (since := "2026-07-09")]
alias LinearOrderedAddCommGroup.wellFoundedOn_setOf_le_lt_iff_nonempty_discrete :=
  LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete

Depends on / 依赖: Archimedean, Function, Function.onFun, LinearOrderedAddCommGroup, Nonempty, Set.WellFoundedOn, WellFounded, WellFounded.wellFounded_iff_has_min, WellFoundedOn, h.mapsTo, mapsTo, replace, wellFounded_iff_has_min
-/
lemma LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete
    {G : Type*} [AddCommGroup G] [LinearOrder G] [IsOrderedAddMonoid G] [Nontrivial G] {g : G} :
    Set.WellFoundedOn {x : G | g <= x} (· < ·) ↔ Nonempty (G ≃+o Int) := by
  suffices Set.WellFoundedOn {x : G | 0 <= x} (· < ·) ↔ Nonempty (G ≃+o Int) by
    rw [← this]
    refine ⟨fun h => (h.mapsTo (· + g) ?_).mono' ?_, fun h => (h.mapsTo (· - g) ?_).mono' ?_⟩ <;>
    · try intro
      simp [Function.onFun]
  constructor
  · intro h
    replace h : WellFounded (α := {x : G | 0 <= x}) (· < ·) := h
    rw [WellFounded.wellFounded_iff_has_min] at h
    by_cases! H : forall (x : G) {y}, 0 < y -> exists n : Nat, x <= n • y -- Archimedean
    · replace H : Archimedean G := ⟨H⟩
      rw [LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered]
      intro hd
      obtain ⟨y, hy⟩ := exists_ne (0 : G)
      wlog! hy' : 0 < y generalizing y
      · refine this (-y) ?_ ?_
        · simp [hy]
        · simp [lt_of_le_of_ne hy' hy]
      obtain ⟨⟨z, hz⟩, hz', hz''⟩ := h ({x | ⟨0, le_rfl⟩ < x}) ⟨⟨y, hy'.le⟩, hy'⟩
      obtain ⟨w, hw, hw'⟩ := exists_between hz'
      exact hz'' ⟨w, hw.le⟩ hw hw'
    · exfalso
      obtain ⟨x, y, hy0, H⟩ := H
      obtain ⟨_, ⟨n, rfl⟩, hz⟩ :=
        h (Set.range (fun n : Nat => ⟨x - n • y, sub_nonneg.mpr (H _).le⟩)) (range_nonempty _)
      refine hz ⟨x - (n + 1) • y, sub_nonneg.mpr (H _).le⟩ ⟨_, rfl⟩ ?_
      simp [add_smul, hy0]
  · rintro ⟨f⟩
    have : LocallyFiniteOrder G := LocallyFiniteOrder.ofOrderIsoClass f
    exact BddBelow.wellFoundedOn_lt ⟨0, by simp [mem_lowerBounds]⟩

@[deprecated (since := "2026-07-09")]
alias LinearOrderedAddCommGroup.wellFoundedOn_setOf_le_lt_iff_nonempty_discrete :=
  LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete

/--
lemma `LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete` / 引理 `LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete`

English:
lemma LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete
  proof: by
  rw [← wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete (g := -g)]
  refine ⟨fun h => (h.mapsTo (- ·) ?_).mono' ?_, fun h => (h.mapsTo (- ·) ?_).mono' ?_⟩ <;>
  · intro
    simp [Function.onFun, neg_le]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedAddCommGroup.wellFoundedOn_setOf_ge_gt_iff_nonempty_discrete :=
  LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete

中文:
引理 LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete
  证明: by
  rw [← wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete (g := -g)]
  refine ⟨fun h => (h.mapsTo (- ·) ?_).mono' ?_, fun h => (h.mapsTo (- ·) ?_).mono' ?_⟩ <;>
  · intro
    simp [Function.onFun, neg_le]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedAddCommGroup.wellFoundedOn_setOf_ge_gt_iff_nonempty_discrete :=
  LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete

Depends on / 依赖: Function, Function.onFun, h.mapsTo, mapsTo, neg_le, wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete
-/
lemma LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete
    {G : Type*} [AddCommGroup G] [LinearOrder G] [IsOrderedAddMonoid G] [Nontrivial G] (g : G) :
    Set.WellFoundedOn {x : G | x <= g} (· > ·) ↔ Nonempty (G ≃+o Int) := by
  rw [← wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete (g := -g)]
  refine ⟨fun h => (h.mapsTo (- ·) ?_).mono' ?_, fun h => (h.mapsTo (- ·) ?_).mono' ?_⟩ <;>
  · intro
    simp [Function.onFun, neg_le]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedAddCommGroup.wellFoundedOn_setOf_ge_gt_iff_nonempty_discrete :=
  LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete

set_option backward.isDefEq.respectTransparency false in
/--
lemma `LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete` / 引理 `LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete`

English:
lemma LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete
  proof: by
  let e : G ≃o Additive G := OrderIso.refl G
  suffices Set.WellFoundedOn {x : G | g <= x} (· < ·) ↔ Set.WellFoundedOn {x | e g <= x} (· < ·) by
    rw [this]; rw [LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete]; rw [OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr]
  refine ⟨fun h => (h.mapsTo e.symm fun _ => e.le_symm_apply.mpr).mono' ?_,
    fun h => (h.mapsTo e fun _ => ?_).mono' ?_⟩ <;>
  simp [Function.onFun]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroup.wellFoundedOn_setOf_le_lt_iff_nonempty_discrete :=
  LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete

中文:
引理 LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete
  证明: by
  let e : G ≃o Additive G := OrderIso.refl G
  suffices Set.WellFoundedOn {x : G | g <= x} (· < ·) ↔ Set.WellFoundedOn {x | e g <= x} (· < ·) by
    rw [this]; rw [LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete]; rw [OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr]
  refine ⟨fun h => (h.mapsTo e.symm fun _ => e.le_symm_apply.mpr).mono' ?_,
    fun h => (h.mapsTo e fun _ => ?_).mono' ?_⟩ <;>
  simp [Function.onFun]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroup.wellFoundedOn_setOf_le_lt_iff_nonempty_discrete :=
  LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete

Depends on / 依赖: Additive, Function, Function.onFun, LinearOrderedAddCommGroup, LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete, OrderAddMonoidIso, OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr, OrderIso, OrderIso.refl, Set.WellFoundedOn, WellFoundedOn, e.le_symm_apply.mpr, e.symm, h.mapsTo, le_symm_apply, mapsTo, nonempty_congr, toMultiplicativeRight, wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete
-/
lemma LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete
    {G : Type*} [CommGroup G] [LinearOrder G] [IsOrderedMonoid G] [Nontrivial G] {g : G} :
    Set.WellFoundedOn {x : G | g <= x} (· < ·) ↔ Nonempty (G ≃*o Multiplicative Int) := by
  let e : G ≃o Additive G := OrderIso.refl G
  suffices Set.WellFoundedOn {x : G | g <= x} (· < ·) ↔ Set.WellFoundedOn {x | e g <= x} (· < ·) by
    rw [this]; rw [LinearOrderedAddCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete]; rw [OrderAddMonoidIso.toMultiplicativeRight.nonempty_congr]
  refine ⟨fun h => (h.mapsTo e.symm fun _ => e.le_symm_apply.mpr).mono' ?_,
    fun h => (h.mapsTo e fun _ => ?_).mono' ?_⟩ <;>
  simp [Function.onFun]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroup.wellFoundedOn_setOf_le_lt_iff_nonempty_discrete :=
  LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete

/--
lemma `LinearOrderedCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete` / 引理 `LinearOrderedCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete`

English:
lemma LinearOrderedCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete
  proof: by
  rw [← wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete (g := g⁻¹)]
  refine ⟨fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_, fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_⟩ <;>
  · intro
    simp [Function.onFun, inv_le']

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroup.wellFoundedOn_setOf_ge_gt_iff_nonempty_discrete :=
  LinearOrderedCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete

中文:
引理 LinearOrderedCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete
  证明: by
  rw [← wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete (g := g⁻¹)]
  refine ⟨fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_, fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_⟩ <;>
  · intro
    simp [Function.onFun, inv_le']

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroup.wellFoundedOn_setOf_ge_gt_iff_nonempty_discrete :=
  LinearOrderedCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete

Depends on / 依赖: Function, Function.onFun, h.mapsTo, inv_le, mapsTo, wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete
-/
lemma LinearOrderedCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete
    {G : Type*} [CommGroup G] [LinearOrder G] [IsOrderedMonoid G] [Nontrivial G] (g : G) :
    Set.WellFoundedOn {x : G | x <= g} (· > ·) ↔ Nonempty (G ≃*o Multiplicative Int) := by
  rw [← wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete (g := g⁻¹)]
  refine ⟨fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_, fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_⟩ <;>
  · intro
    simp [Function.onFun, inv_le']

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroup.wellFoundedOn_setOf_ge_gt_iff_nonempty_discrete :=
  LinearOrderedCommGroup.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete

set_option backward.isDefEq.respectTransparency false in
/--
lemma `LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero` / 引理 `LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero`

English:
lemma LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero
  proof: by
  suffices Set.WellFoundedOn {x : G₀ | g <= x} (· < ·) ↔
    Set.WellFoundedOn {x : G₀ˣ | Units.mk0 g hg <= x} (· < ·) by
    rw [this]; rw [LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete]
    refine Nonempty.congr (fun f => ⟨?_, ?_⟩) (fun f => ⟨?_, ?_⟩)
    · exact WithZero.withZeroUnitsEquiv.symm.trans f.withZero
    · intro a b
      rcases eq_or_ne a 0 with rfl | ha
      · simp [WithZero.withZeroUnitsEquiv]
      rcases eq_or_ne b 0 with rfl | hb
      · simp [WithZero.withZeroUnitsEquiv]
      simp [WithZero.withZeroUnitsEquiv, ha, hb, ← Units.val_le_val]
    · exact MulEquiv.withZero.symm (WithZero.withZeroUnitsEquiv.trans f)
    · intros
      rw [← WithZero.coe_le_coe]
      simp
  rw [← Set.wellFoundedOn_sdiff_singleton (a := 0)]
  refine ⟨fun h => (h.mapsTo Units.val ?_).mono' ?_,
    fun h => (h.mapsTo ?_ ?_).mono' ?_⟩
  · intro
    simp [← Units.val_le_val]
  · simp [Function.onFun]
  · exact fun x => if h : x = 0 then 1 else Units.mk0 x h
  · simp +contextual [← Units.val_le_val, MapsTo]
  · simp only [mem_sdiff, mem_ofPred_eq, mem_singleton_iff, Function.onFun, and_imp]
    intro _ _ ha0 _ _ hb0 h
    simp [ha0, hb0, ← Units.val_lt_val, h]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroupWithZero.wellFoundedOn_setOf_le_lt_iff_nonempty_discrete_of_ne_zero :=
  LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero

中文:
引理 带零LinearOrderedComm群.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero
  证明: by
  suffices Set.WellFoundedOn {x : G₀ | g <= x} (· < ·) ↔
    Set.WellFoundedOn {x : G₀ˣ | Units.mk0 g hg <= x} (· < ·) by
    rw [this]; rw [LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete]
    refine Nonempty.congr (fun f => ⟨?_, ?_⟩) (fun f => ⟨?_, ?_⟩)
    · exact WithZero.withZeroUnitsEquiv.symm.trans f.withZero
    · intro a b
      rcases eq_or_ne a 0 with rfl | ha
      · simp [WithZero.withZeroUnitsEquiv]
      rcases eq_or_ne b 0 with rfl | hb
      · simp [WithZero.withZeroUnitsEquiv]
      simp [WithZero.withZeroUnitsEquiv, ha, hb, ← Units.val_le_val]
    · exact MulEquiv.withZero.symm (WithZero.withZeroUnitsEquiv.trans f)
    · intros
      rw [← WithZero.coe_le_coe]
      simp
  rw [← Set.wellFoundedOn_sdiff_singleton (a := 0)]
  refine ⟨fun h => (h.mapsTo Units.val ?_).mono' ?_,
    fun h => (h.mapsTo ?_ ?_).mono' ?_⟩
  · intro
    simp [← Units.val_le_val]
  · simp [Function.onFun]
  · exact fun x => if h : x = 0 then 1 else Units.mk0 x h
  · simp +contextual [← Units.val_le_val, MapsTo]
  · simp only [mem_sdiff, mem_ofPred_eq, mem_singleton_iff, Function.onFun, and_imp]
    intro _ _ ha0 _ _ hb0 h
    simp [ha0, hb0, ← Units.val_lt_val, h]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroupWithZero.wellFoundedOn_setOf_le_lt_iff_nonempty_discrete_of_ne_zero :=
  LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero

Depends on / 依赖: LinearOrderedCommGroup, LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete, Nonempty, Nonempty.congr, Set.WellFoundedOn, Units.mk0, WellFoundedOn, WithZero, WithZero.w, WithZero.withZeroUnitsEquiv, WithZero.withZeroUnitsEquiv.symm.trans, eq_or_ne, f.withZero, wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete, withZero, withZeroUnitsEquiv
-/
lemma LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero
    {G₀ : Type*} [LinearOrderedCommGroupWithZero G₀] [Nontrivial G₀ˣ] {g : G₀} (hg : g != 0) :
    Set.WellFoundedOn {x : G₀ | g <= x} (· < ·) ↔ Nonempty (G₀ ≃*o Intᵐ⁰) := by
  suffices Set.WellFoundedOn {x : G₀ | g <= x} (· < ·) ↔
    Set.WellFoundedOn {x : G₀ˣ | Units.mk0 g hg <= x} (· < ·) by
    rw [this]; rw [LinearOrderedCommGroup.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete]
    refine Nonempty.congr (fun f => ⟨?_, ?_⟩) (fun f => ⟨?_, ?_⟩)
    · exact WithZero.withZeroUnitsEquiv.symm.trans f.withZero
    · intro a b
      rcases eq_or_ne a 0 with rfl | ha
      · simp [WithZero.withZeroUnitsEquiv]
      rcases eq_or_ne b 0 with rfl | hb
      · simp [WithZero.withZeroUnitsEquiv]
      simp [WithZero.withZeroUnitsEquiv, ha, hb, ← Units.val_le_val]
    · exact MulEquiv.withZero.symm (WithZero.withZeroUnitsEquiv.trans f)
    · intros
      rw [← WithZero.coe_le_coe]
      simp
  rw [← Set.wellFoundedOn_sdiff_singleton (a := 0)]
  refine ⟨fun h => (h.mapsTo Units.val ?_).mono' ?_,
    fun h => (h.mapsTo ?_ ?_).mono' ?_⟩
  · intro
    simp [← Units.val_le_val]
  · simp [Function.onFun]
  · exact fun x => if h : x = 0 then 1 else Units.mk0 x h
  · simp +contextual [← Units.val_le_val, MapsTo]
  · simp only [mem_sdiff, mem_ofPred_eq, mem_singleton_iff, Function.onFun, and_imp]
    intro _ _ ha0 _ _ hb0 h
    simp [ha0, hb0, ← Units.val_lt_val, h]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroupWithZero.wellFoundedOn_setOf_le_lt_iff_nonempty_discrete_of_ne_zero :=
  LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero

/--
lemma `LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero` / 引理 `LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero`

English:
lemma LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero
  proof: by
  have hg' : g⁻¹ != 0 := by simp [hg]
  rw [← wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero hg']; rw [← Set.wellFoundedOn_sdiff_singleton (a := 0)]
  refine ⟨fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_, fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_⟩
  · intro x
    rcases eq_or_ne x 0 with rfl | hx
    · simp [hg]
    simp only [mem_ofPred_eq, mem_sdiff, mem_singleton_iff, inv_eq_zero, hx, not_false_eq_true,
      and_true]
    refine (inv_le_comm₀ ?_ ?_).mp <;>
    simp [zero_lt_iff, hg, hx]
  · simp only [mem_ofPred_eq, Function.onFun, gt_iff_lt]
    intro a ha b _
    refine inv_strictAnti₀ ?_
    contrapose! ha
    simp only [le_zero_iff] at ha
    simp [zero_lt_iff, ha, hg]
  · intro x
    simp only [mem_sdiff, mem_ofPred_eq, mem_singleton_iff, and_imp]
    intro hxg hx
    refine inv_anti₀ ?_ hxg
    simp [zero_lt_iff, hx]
  · simp only [mem_sdiff, mem_ofPred_eq, mem_singleton_iff, gt_iff_lt, Function.onFun, and_imp]
    intro a _ _ b _ hb0
    refine inv_strictAnti₀ ?_
    simp [zero_lt_iff, hb0]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroupWithZero.wellFoundedOn_setOf_ge_gt_iff_nonempty_discrete_of_ne_zero :=
  LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero

中文:
引理 带零LinearOrderedComm群.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero
  证明: by
  have hg' : g⁻¹ != 0 := by simp [hg]
  rw [← wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero hg']; rw [← Set.wellFoundedOn_sdiff_singleton (a := 0)]
  refine ⟨fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_, fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_⟩
  · intro x
    rcases eq_or_ne x 0 with rfl | hx
    · simp [hg]
    simp only [mem_ofPred_eq, mem_sdiff, mem_singleton_iff, inv_eq_zero, hx, not_false_eq_true,
      and_true]
    refine (inv_le_comm₀ ?_ ?_).mp <;>
    simp [zero_lt_iff, hg, hx]
  · simp only [mem_ofPred_eq, Function.onFun, gt_iff_lt]
    intro a ha b _
    refine inv_strictAnti₀ ?_
    contrapose! ha
    simp only [le_zero_iff] at ha
    simp [zero_lt_iff, ha, hg]
  · intro x
    simp only [mem_sdiff, mem_ofPred_eq, mem_singleton_iff, and_imp]
    intro hxg hx
    refine inv_anti₀ ?_ hxg
    simp [zero_lt_iff, hx]
  · simp only [mem_sdiff, mem_ofPred_eq, mem_singleton_iff, gt_iff_lt, Function.onFun, and_imp]
    intro a _ _ b _ hb0
    refine inv_strictAnti₀ ?_
    simp [zero_lt_iff, hb0]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroupWithZero.wellFoundedOn_setOf_ge_gt_iff_nonempty_discrete_of_ne_zero :=
  LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero

Depends on / 依赖: Set.wellFoundedOn_sdiff_singleton, and_true, eq_or_ne, h.mapsTo, inv_eq_zero, mapsTo, mem_ofPred_eq, mem_sdiff, mem_singleton_iff, not_false_eq_true, wellFoundedOn_sdiff_singleton, wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero, zero_lt_iff
-/
lemma LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero
    {G₀ : Type*} [LinearOrderedCommGroupWithZero G₀] [Nontrivial G₀ˣ] {g : G₀} (hg : g != 0) :
    Set.WellFoundedOn {x : G₀ | x <= g} (· > ·) ↔ Nonempty (G₀ ≃*o Intᵐ⁰) := by
  have hg' : g⁻¹ != 0 := by simp [hg]
  rw [← wellFoundedOn_setOfPred_le_lt_iff_nonempty_discrete_of_ne_zero hg']; rw [← Set.wellFoundedOn_sdiff_singleton (a := 0)]
  refine ⟨fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_, fun h => (h.mapsTo (·⁻¹) ?_).mono' ?_⟩
  · intro x
    rcases eq_or_ne x 0 with rfl | hx
    · simp [hg]
    simp only [mem_ofPred_eq, mem_sdiff, mem_singleton_iff, inv_eq_zero, hx, not_false_eq_true,
      and_true]
    refine (inv_le_comm₀ ?_ ?_).mp <;>
    simp [zero_lt_iff, hg, hx]
  · simp only [mem_ofPred_eq, Function.onFun, gt_iff_lt]
    intro a ha b _
    refine inv_strictAnti₀ ?_
    contrapose! ha
    simp only [le_zero_iff] at ha
    simp [zero_lt_iff, ha, hg]
  · intro x
    simp only [mem_sdiff, mem_ofPred_eq, mem_singleton_iff, and_imp]
    intro hxg hx
    refine inv_anti₀ ?_ hxg
    simp [zero_lt_iff, hx]
  · simp only [mem_sdiff, mem_ofPred_eq, mem_singleton_iff, gt_iff_lt, Function.onFun, and_imp]
    intro a _ _ b _ hb0
    refine inv_strictAnti₀ ?_
    simp [zero_lt_iff, hb0]

@[deprecated (since := "2026-07-09")]
alias LinearOrderedCommGroupWithZero.wellFoundedOn_setOf_ge_gt_iff_nonempty_discrete_of_ne_zero :=
  LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero

/--
Instance `instWellFoundedGTWithZeroMultiplicativeIntLeOne` / 实例 `instWellFoundedGTWithZeroMultiplicativeIntLeOne`

English:
instance instWellFoundedGTWithZeroMultiplicativeIntLeOne
  signature: :
  body: { wf :=
    (LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero
    one_ne_zero).mpr instNonemptyOfInhabited }

中文:
实例 instWellFoundedGTWithZeroMultiplicative整数LeOne
  签名: :
  定义体: { wf :=
    (LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero
    one_ne_zero).mpr instNonemptyOfInhabited }

Depends on / 依赖: LinearOrderedCommGroupWithZero, LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero, instNonemptyOfInhabited, one_ne_zero, wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero
-/
instance instWellFoundedGTWithZeroMultiplicativeIntLeOne :
    WellFoundedGT { v : Intᵐ⁰ // v <= 1 } :=
  { wf :=
    (LinearOrderedCommGroupWithZero.wellFoundedOn_setOfPred_ge_gt_iff_nonempty_discrete_of_ne_zero
    one_ne_zero).mpr instNonemptyOfInhabited }

end WellFounded

@[to_additive]
/--
lemma `OrderMonoidIso.mulArchimedean` / 引理 `OrderMonoidIso.mulArchimedean`

English:
lemma OrderMonoidIso.mulArchimedean
  statement: {α β}
  proof: by
  constructor
  intro x y hxy
  replace hxy : 1 < e.symm y := by simp [← map_lt_map_iff e, hxy]
  refine (MulArchimedean.arch (e.symm x) hxy).imp ?_
  simp [← map_pow, ← map_le_map_iff e]

中文:
引理 OrderMonoidIso.mulArchimedean
  结论: {α β}
  证明: by
  constructor
  intro x y hxy
  replace hxy : 1 < e.symm y := by simp [← map_lt_map_iff e, hxy]
  refine (MulArchimedean.arch (e.symm x) hxy).imp ?_
  simp [← map_pow, ← map_le_map_iff e]

Depends on / 依赖: MulArchimedean, MulArchimedean.arch, e.symm, map_le_map_iff, map_lt_map_iff, map_pow, replace
-/
lemma OrderMonoidIso.mulArchimedean {α β}
    [CommMonoid α] [PartialOrder α] [CommMonoid β] [PartialOrder β]
    (e : α ≃*o β) [MulArchimedean α] : MulArchimedean β := by
  constructor
  intro x y hxy
  replace hxy : 1 < e.symm y := by simp [← map_lt_map_iff e, hxy]
  refine (MulArchimedean.arch (e.symm x) hxy).imp ?_
  simp [← map_pow, ← map_le_map_iff e]

/--
lemma `WithZero.mulArchimedean_iff` / 引理 `WithZero.mulArchimedean_iff`

English:
lemma WithZero.mulArchimedean_iff
  given: {α} [CommGroup α] [PartialOrder α]
  proof: by
  constructor <;> intro _
  · exact OrderMonoidIso.unitsWithZero.mulArchimedean
  · infer_instance

中文:
引理 WithZero.mulArchimedean_iff
  条件: {α} [交换群 α] [偏序 α]
  证明: by
  constructor <;> intro _
  · exact OrderMonoidIso.unitsWithZero.mulArchimedean
  · infer_instance

Depends on / 依赖: OrderMonoidIso, OrderMonoidIso.unitsWithZero.mulArchimedean, infer_instance, mulArchimedean, unitsWithZero
-/
lemma WithZero.mulArchimedean_iff {α} [CommGroup α] [PartialOrder α] :
    MulArchimedean (WithZero α) ↔ MulArchimedean α := by
  constructor <;> intro _
  · exact OrderMonoidIso.unitsWithZero.mulArchimedean
  · infer_instance

/--
lemma `Units.mulArchimedean_iff` / 引理 `Units.mulArchimedean_iff`

English:
lemma Units.mulArchimedean_iff
  given: {G₀} [LinearOrderedCommGroupWithZero G₀]
  proof: by
  constructor <;> intro _
  · exact OrderMonoidIso.withZeroUnits.mulArchimedean
  · infer_instance

中文:
引理 单位群.mulArchimedean_iff
  条件: {G₀} [带零LinearOrderedComm群 G₀]
  证明: by
  constructor <;> intro _
  · exact OrderMonoidIso.withZeroUnits.mulArchimedean
  · infer_instance

Depends on / 依赖: OrderMonoidIso, OrderMonoidIso.withZeroUnits.mulArchimedean, infer_instance, mulArchimedean, withZeroUnits
-/
lemma Units.mulArchimedean_iff {G₀} [LinearOrderedCommGroupWithZero G₀] :
    MulArchimedean G₀ˣ ↔ MulArchimedean G₀ := by
  constructor <;> intro _
  · exact OrderMonoidIso.withZeroUnits.mulArchimedean
  · infer_instance

section LocallyFiniteOrder

variable {X : Type*} [Preorder X] [LocallyFiniteOrder X]

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: LocallyFiniteOrder (Multiplicative X)
  body: OrderIso.locallyFiniteOrder (⟨Multiplicative.toAdd, by simp⟩ : Multiplicative X ≃o X)

中文:
实例 :
  签名: 局部有限序 (Multiplicative X)
  定义体: OrderIso.locallyFiniteOrder (⟨Multiplicative.toAdd, by simp⟩ : Multiplicative X ≃o X)

Depends on / 依赖: Multiplicative, Multiplicative.toAdd, OrderIso, OrderIso.locallyFiniteOrder, locallyFiniteOrder
-/
instance : LocallyFiniteOrder (Multiplicative X) :=
  OrderIso.locallyFiniteOrder (⟨Multiplicative.toAdd, by simp⟩ : Multiplicative X ≃o X)
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: LocallyFiniteOrder (Additive X)
  body: OrderIso.locallyFiniteOrder (⟨Additive.toMul, by simp⟩ : Additive X ≃o X)

noncomputable

中文:
实例 :
  签名: 局部有限序 (加性 X)
  定义体: OrderIso.locallyFiniteOrder (⟨Additive.toMul, by simp⟩ : Additive X ≃o X)

noncomputable

Depends on / 依赖: Additive, Additive.toMul, OrderIso, OrderIso.locallyFiniteOrder, locallyFiniteOrder
-/
instance : LocallyFiniteOrder (Additive X) :=
  OrderIso.locallyFiniteOrder (⟨Additive.toMul, by simp⟩ : Additive X ≃o X)

noncomputable
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [Monoid
  signature: X] : LocallyFiniteOrder (Units X)
  body: OrderEmbedding.locallyFiniteOrder (⟨⟨Units.val, Units.val_injective⟩, by simp⟩ : Units X ↪o X)

中文:
实例 [幺半群
  签名: X] : 局部有限序 (单位群 X)
  定义体: OrderEmbedding.locallyFiniteOrder (⟨⟨Units.val, Units.val_injective⟩, by simp⟩ : Units X ↪o X)

Depends on / 依赖: OrderEmbedding, OrderEmbedding.locallyFiniteOrder, Units.val, Units.val_injective, locallyFiniteOrder, val_injective
-/
instance [Monoid X] : LocallyFiniteOrder (Units X) :=
  OrderEmbedding.locallyFiniteOrder (⟨⟨Units.val, Units.val_injective⟩, by simp⟩ : Units X ↪o X)

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [Group
  signature: X] : LocallyFiniteOrder (WithZero X)ˣ
  body: OrderIso.locallyFiniteOrder (OrderMonoidIso.unitsWithZero (α := X) : (WithZero X)ˣ ≃o X)

中文:
实例 [群
  签名: X] : 局部有限序 (WithZero X)ˣ
  定义体: OrderIso.locallyFiniteOrder (OrderMonoidIso.unitsWithZero (α := X) : (WithZero X)ˣ ≃o X)

Depends on / 依赖: OrderIso, OrderIso.locallyFiniteOrder, OrderMonoidIso, OrderMonoidIso.unitsWithZero, WithZero, locallyFiniteOrder, unitsWithZero
-/
instance [Group X] : LocallyFiniteOrder (WithZero X)ˣ :=
  OrderIso.locallyFiniteOrder (OrderMonoidIso.unitsWithZero (α := X) : (WithZero X)ˣ ≃o X)

end LocallyFiniteOrder

section DenselyOrdered

variable {X : Type*} [LT X]

/--
lemma `denselyOrdered_additive_iff` / 引理 `denselyOrdered_additive_iff`

English:
lemma denselyOrdered_additive_iff
  statement: DenselyOrdered (Additive X) ↔ DenselyOrdered X
  proof: Iff.rfl

中文:
引理 denselyOrdered_additive_iff
  结论: 稠密序 (加性 X) ↔ 稠密序 X
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
lemma denselyOrdered_additive_iff : DenselyOrdered (Additive X) ↔ DenselyOrdered X := Iff.rfl
/--
lemma `denselyOrdered_multiplicative_iff` / 引理 `denselyOrdered_multiplicative_iff`

English:
lemma denselyOrdered_multiplicative_iff
  statement: DenselyOrdered (Multiplicative X) ↔ DenselyOrdered X
  proof: Iff.rfl

中文:
引理 denselyOrdered_multiplicative_iff
  结论: 稠密序 (Multiplicative X) ↔ 稠密序 X
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
lemma denselyOrdered_multiplicative_iff : DenselyOrdered (Multiplicative X) ↔ DenselyOrdered X :=
  Iff.rfl

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [DenselyOrdered
  signature: X] : DenselyOrdered (Multiplicative X)
  body: denselyOrdered_multiplicative_iff.2 ‹_›

中文:
实例 [稠密序
  签名: X] : 稠密序 (Multiplicative X)
  定义体: denselyOrdered_multiplicative_iff.2 ‹_›

Depends on / 依赖: denselyOrdered_multiplicative_iff
-/
instance [DenselyOrdered X] : DenselyOrdered (Multiplicative X) :=
  denselyOrdered_multiplicative_iff.2 ‹_›
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [DenselyOrdered
  signature: X] : DenselyOrdered (Additive X)
  body: denselyOrdered_additive_iff.2 ‹_›

中文:
实例 [稠密序
  签名: X] : 稠密序 (加性 X)
  定义体: denselyOrdered_additive_iff.2 ‹_›

Depends on / 依赖: denselyOrdered_additive_iff
-/
instance [DenselyOrdered X] : DenselyOrdered (Additive X) :=
  denselyOrdered_additive_iff.2 ‹_›

/--
lemma `WithZero.denselyOrdered_iff` / 引理 `WithZero.denselyOrdered_iff`

English:
lemma WithZero.denselyOrdered_iff
  given: {M : Type*} [Preorder M] [NoMinOrder M]
  proof: WithBot.denselyOrdered_iff

中文:
引理 WithZero.denselyOrdered_iff
  条件: {M : 类型} [预序 M] [NoMin序 M]
  证明: WithBot.denselyOrdered_iff

Depends on / 依赖: WithBot, WithBot.denselyOrdered_iff, denselyOrdered_iff
-/
lemma WithZero.denselyOrdered_iff {M : Type*} [Preorder M] [NoMinOrder M] :
    DenselyOrdered (WithZero M) ↔ DenselyOrdered M :=
  WithBot.denselyOrdered_iff

instance {X : Type*} [Preorder X] [NoMinOrder X] [DenselyOrdered X] :
    DenselyOrdered (WithZero X) :=
  WithZero.denselyOrdered_iff.mpr inferInstance

/--
lemma `Int.not_denselyOrdered` / 引理 `Int.not_denselyOrdered`

English:
lemma Int.not_denselyOrdered
  statement: ¬ DenselyOrdered Int
  proof: (LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered Int).mp ⟨.refl _⟩

中文:
引理 整数.not_denselyOrdered
  结论: ¬ 稠密序 整数
  证明: (LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered Int).mp ⟨.refl _⟩

Depends on / 依赖: LinearOrderedAddCommGroup, LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered, discrete_iff_not_denselyOrdered
-/
lemma Int.not_denselyOrdered : ¬ DenselyOrdered Int :=
  (LinearOrderedAddCommGroup.discrete_iff_not_denselyOrdered Int).mp ⟨.refl _⟩

/--
lemma `not_denselyOrdered_withZero_int` / 引理 `not_denselyOrdered_withZero_int`

English:
lemma not_denselyOrdered_withZero_int
  statement: ¬ DenselyOrdered Intᵐ⁰
  proof: (LinearOrderedCommGroupWithZero.discrete_iff_not_denselyOrdered _).mp ⟨.refl _⟩

中文:
引理 not_denselyOrdered_withZero_int
  结论: ¬ 稠密序 整数ᵐ⁰
  证明: (LinearOrderedCommGroupWithZero.discrete_iff_not_denselyOrdered _).mp ⟨.refl _⟩

Depends on / 依赖: LinearOrderedCommGroupWithZero, LinearOrderedCommGroupWithZero.discrete_iff_not_denselyOrdered, discrete_iff_not_denselyOrdered
-/
lemma not_denselyOrdered_withZero_int : ¬ DenselyOrdered Intᵐ⁰ :=
  (LinearOrderedCommGroupWithZero.discrete_iff_not_denselyOrdered _).mp ⟨.refl _⟩

/--
lemma `WithZero.denselyOrdered_set_iff_subsingleton` / 引理 `WithZero.denselyOrdered_set_iff_subsingleton`

English:
lemma WithZero.denselyOrdered_set_iff_subsingleton
  statement: {X : Type*} [LinearOrder X]
  proof: WithBot.denselyOrdered_set_iff_subsingleton

中文:
引理 WithZero.denselyOrdered_set_iff_subsingleton
  结论: {X : 类型} [线性序 X]
  证明: WithBot.denselyOrdered_set_iff_subsingleton

Depends on / 依赖: WithBot, WithBot.denselyOrdered_set_iff_subsingleton, denselyOrdered_set_iff_subsingleton
-/
lemma WithZero.denselyOrdered_set_iff_subsingleton {X : Type*} [LinearOrder X]
    [LocallyFiniteOrder X] {s : Set (WithZero X)} :
    DenselyOrdered s ↔ s.Subsingleton :=
  WithBot.denselyOrdered_set_iff_subsingleton

end DenselyOrdered
