/-
Copyright (c) 2022 David Kurniadi Angdinata. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Kurniadi Angdinata
-/
module

public import Mathlib.Algebra.Group.Equiv.TypeTags
public import Mathlib.Data.ZMod.QuotientGroup
public import Mathlib.RingTheory.DedekindDomain.AdicValuation
public import Mathlib.Algebra.Group.Int.TypeTags

/-!
# Selmer groups of fraction fields of Dedekind domains

Let $K$ be the field of fractions of a Dedekind domain $R$. For any set $S$ of prime ideals in the
height one spectrum of $R$, and for any natural number $n$, the Selmer group $K(S, n)$ is defined to
be the subgroup of the unit group $K^\times$ modulo $n$-th powers where each element has $v$-adic
valuation divisible by $n$ for all prime ideals $v$ away from $S$. In other words, this is precisely
$$ K(S, n) := \{x(K^\times)^n \in K^\times / (K^\times)^n \ \mid \
                \forall v \notin S, \ \mathrm{ord}_v(x) \equiv 0 \pmod n\}. $$

There is a fundamental short exact sequence
$$ 1 \to R_S^\times / (R_S^\times)^n \to K(S, n) \to \mathrm{Cl}_S(R)[n] \to 0, $$
where $R_S^\times$ is the $S$-unit group of $R$ and $\mathrm{Cl}_S(R)$ is the $S$-class group of
$R$. If the flanking groups are both finite, then $K(S, n)$ is finite by the first isomorphism
theorem. Such is the case when $R$ is the ring of integers of a number field $K$, $S$ is finite, and
$n$ is positive, in which case $R_S^\times$ is finitely generated by Dirichlet's unit theorem and
$\mathrm{Cl}_S(R)$ is finite by the class number theorem.

This file defines the Selmer group $K(S, n)$ and some basic facts.

## Main definitions

* `IsDedekindDomain.selmerGroup`: the Selmer group.
* TODO: maps in the sequence.

## Main statements

* TODO: proofs of exactness of the sequence.
* TODO: proofs of finiteness for global fields.

## Notation

* `K⟮S, n⟯`: the Selmer group with parameters `K`, `S`, and `n`.

## Implementation notes

The Selmer group is typically defined as a subgroup of the Galois cohomology group $H^1(K, \mu_n)$
with certain local conditions defined by $v$-adic valuations, where $\mu_n$ is the group of $n$-th
roots of unity over a separable closure of $K$. Here $H^1(K, \mu_n)$ is identified with
$K^\times / (K^\times)^n$ by the long exact sequence from Kummer theory and Hilbert's theorem 90,
and the fundamental short exact sequence becomes an easy consequence of the snake lemma. This file
will define all the maps explicitly for computational purposes, but isomorphisms to the Galois
cohomological definition will be provided when possible.

## References

https://doc.sagemath.org/html/en/reference/number_fields/sage/rings/number_field/selmer_group.html

## Tags

class group, selmer group, unit group
-/

@[expose] public section

set_option quotPrecheck false
local notation K "/" n => Kˣ ⧸ (powMonoidHom n : Kˣ ->* Kˣ).range

namespace IsDedekindDomain

noncomputable section

open WithZero
open scoped WithZero nonZeroDivisors

universe u v

variable {R : Type u} [CommRing R] [IsDedekindDomain R] {K : Type v} [Field K]
  [Algebra R K] [IsFractionRing R K] (v : HeightOneSpectrum R)

/-! ### Valuations of non-zero elements -/


namespace HeightOneSpectrum

/--
Definition of `valuationOfNeZeroToFun` / `valuationOfNeZeroToFun` 的定义

English:
definition valuationOfNeZeroToFun
  signature: (x : Kˣ)
  body: let hx := IsLocalization.sec R⁰ (x : K)
Multiplicative.ofAdd
    (-(Associates.mk v.asIdeal).count (Associates.mk <| Ideal.span {hx.fst}).factors : Int) -
      (-(Associates.mk v.asIdeal).count (Associates.mk <| Ideal.span {(hx.snd : R)}).factors : Int)

中文:
定义 valuationOfNeZeroToFun
  签名: (x : Kˣ)
  定义体: let hx := IsLocalization.sec R⁰ (x : K)
Multiplicative.ofAdd
    (-(Associates.mk v.asIdeal).count (Associates.mk <| Ideal.span {hx.fst}).factors : Int) -
      (-(Associates.mk v.asIdeal).count (Associates.mk <| Ideal.span {(hx.snd : R)}).factors : Int)

Depends on / 依赖: Associates, Associates.mk, Ideal.span, IsLocalization, IsLocalization.sec, Multiplicative, Multiplicative.ofAdd, asIdeal, factors, hx.fst, hx.snd, v.asIdeal
-/
def valuationOfNeZeroToFun (x : Kˣ) : Multiplicative Int :=
  let hx := IsLocalization.sec R⁰ (x : K)
Multiplicative.ofAdd
    (-(Associates.mk v.asIdeal).count (Associates.mk <| Ideal.span {hx.fst}).factors : Int) -
      (-(Associates.mk v.asIdeal).count (Associates.mk <| Ideal.span {(hx.snd : R)}).factors : Int)

set_option backward.isDefEq.respectTransparency.types false in
@[simp]
/--
theorem `valuationOfNeZeroToFun_eq` / 定理 `valuationOfNeZeroToFun_eq`

English:
theorem valuationOfNeZeroToFun_eq
  given: (x : Kˣ)
  proof: by
  classical
  rw [show v.valuation K x = _ * _ by rw [valuation_def]; rfl]
  rw [Units.val_inv_eq_inv_val]
  change _ = ite _ _ _ * (ite _ _ _)⁻¹
  simp_rw [IsLocalization.toLocalizationMap_sec, SubmonoidClass.coe_subtype,
if_neg IsLocalization.sec_fst_ne_zero x.ne_zero,
    if_neg (nonZeroDiviso

中文:
定理 valuationOfNeZeroToFun_eq
  条件: (x : Kˣ)
  证明: by
  classical
  rw [show v.valuation K x = _ * _ by rw [valuation_def]; rfl]
  rw [Units.val_inv_eq_inv_val]
  change _ = ite _ _ _ * (ite _ _ _)⁻¹
  simp_rw [IsLocalization.toLocalizationMap_sec, SubmonoidClass.coe_subtype,
if_neg IsLocalization.sec_fst_ne_zero x.ne_zero,
    if_neg (nonZeroDiviso

Depends on / 依赖: IsLocalization, IsLocalization.sec_fst_ne_zero, IsLocalization.toLocalizationMap_sec, SubmonoidClass, SubmonoidClass.coe_subtype, Units.val_inv_eq_inv_val, classical, coe_ne_zero, coe_subtype, exp_add, exp_neg, if_neg, ne_zero, nonZeroDivisors, nonZeroDivisors.coe_ne_zero, sec_fst_ne_zero, simp_rw, sub_eq_add_neg, toLocalizationMap_sec, v.valuation
-/
theorem valuationOfNeZeroToFun_eq (x : Kˣ) :
    (v.valuationOfNeZeroToFun x : Intᵐ⁰) = v.valuation K x := by
  classical
  rw [show v.valuation K x = _ * _ by rw [valuation_def]; rfl]
  rw [Units.val_inv_eq_inv_val]
  change _ = ite _ _ _ * (ite _ _ _)⁻¹
  simp_rw [IsLocalization.toLocalizationMap_sec, SubmonoidClass.coe_subtype,
if_neg IsLocalization.sec_fst_ne_zero x.ne_zero,
    if_neg (nonZeroDivisors.coe_ne_zero _),
    ← exp_neg, ← exp_add, valuationOfNeZeroToFun, ← sub_eq_add_neg, exp]

/--
Definition of `valuationOfNeZero` / `valuationOfNeZero` 的定义

English:
definition valuationOfNeZero
  signature: : Kˣ ->* Multiplicative Int where
  body: v.valuationOfNeZeroToFun
  map_one' := by rw [← WithZero.coe_inj, valuationOfNeZeroToFun_eq]; exact map_one _
  map_mul' _ _ := by
    rw [← WithZero.coe_inj]; rw [WithZero.coe_mul]
    simp only [valuationOfNeZeroToFun_eq]; exact map_mul _ _ _

@[simp]

中文:
定义 valuationOfNeZero
  签名: : Kˣ ->* Multiplicative 整数 where
  定义体: v.valuationOfNeZeroToFun
  map_one' := by rw [← WithZero.coe_inj, valuationOfNeZeroToFun_eq]; exact map_one _
  map_mul' _ _ := by
    rw [← WithZero.coe_inj]; rw [WithZero.coe_mul]
    simp only [valuationOfNeZeroToFun_eq]; exact map_mul _ _ _

@[simp]

Depends on / 依赖: v.valuationOfNeZeroToFun, valuationOfNeZeroToFun
-/
def valuationOfNeZero : Kˣ ->* Multiplicative Int where
  toFun := v.valuationOfNeZeroToFun
  map_one' := by rw [← WithZero.coe_inj, valuationOfNeZeroToFun_eq]; exact map_one _
  map_mul' _ _ := by
    rw [← WithZero.coe_inj]; rw [WithZero.coe_mul]
    simp only [valuationOfNeZeroToFun_eq]; exact map_mul _ _ _

@[simp]
/--
theorem `valuationOfNeZero_eq` / 定理 `valuationOfNeZero_eq`

English:
theorem valuationOfNeZero_eq
  given: (x : Kˣ)
  statement: (v.valuationOfNeZero x : Intᵐ⁰) = v.valuation K x
  proof: valuationOfNeZeroToFun_eq v x

@[simp]

中文:
定理 valuationOfNeZero_eq
  条件: (x : Kˣ)
  结论: (v.valuationOfNeZero x : 整数ᵐ⁰) = v.valuation K x
  证明: valuationOfNeZeroToFun_eq v x

@[simp]

Depends on / 依赖: valuationOfNeZeroToFun_eq
-/
theorem valuationOfNeZero_eq (x : Kˣ) : (v.valuationOfNeZero x : Intᵐ⁰) = v.valuation K x :=
  valuationOfNeZeroToFun_eq v x

@[simp]
/--
theorem `valuation_of_unit_eq` / 定理 `valuation_of_unit_eq`

English:
theorem valuation_of_unit_eq
  given: (x : Rˣ)
  proof: by
  rw [← WithZero.coe_inj]; rw [valuationOfNeZero_eq]; rw [Units.coe_map]; rw [eq_iff_le_not_lt]
  constructor
  · exact v.valuation_le_one x
  · obtain ⟨x, _, hx, _⟩ := x
    change ¬v.valuation K (algebraMap R K x) < 1
    apply_fun v.intValuation at hx
    rw [map_one]; rw [map_mul] at hx
    r

中文:
定理 valuation_of_unit_eq
  条件: (x : Rˣ)
  证明: by
  rw [← WithZero.coe_inj]; rw [valuationOfNeZero_eq]; rw [Units.coe_map]; rw [eq_iff_le_not_lt]
  constructor
  · exact v.valuation_le_one x
  · obtain ⟨x, _, hx, _⟩ := x
    change ¬v.valuation K (algebraMap R K x) < 1
    apply_fun v.intValuation at hx
    rw [map_one]; rw [map_mul] at hx
    r

Depends on / 依赖: Units.coe_map, WithZero, WithZero.coe_inj, algebraMap, apply_fun, coe_inj, coe_map, eq_iff_le_not_lt, intValuation, intValuation_le_one, map_mul, map_one, mul_one, not_lt, v.intValuation, v.intValuation_le_one, v.valuation, v.valuation_le_one, valuation, valuationOfNeZero_eq
-/
theorem valuation_of_unit_eq (x : Rˣ) :
    v.valuationOfNeZero (Units.map (algebraMap R K : R ->* K) x) = 1 := by
  rw [← WithZero.coe_inj]; rw [valuationOfNeZero_eq]; rw [Units.coe_map]; rw [eq_iff_le_not_lt]
  constructor
  · exact v.valuation_le_one x
  · obtain ⟨x, _, hx, _⟩ := x
    change ¬v.valuation K (algebraMap R K x) < 1
    apply_fun v.intValuation at hx
    rw [map_one]; rw [map_mul] at hx
    rw [not_lt]; rw [← hx]; rw [← mul_one <| v.valuation _ _]; rw [valuation_of_algebraMap]
    gcongr
    exact v.intValuation_le_one _

/--
Definition of `valuationOfNeZeroMod` / `valuationOfNeZeroMod` 的定义

English:
definition valuationOfNeZeroMod
  signature: (n : Nat)
  body: -- TODO: this definition does a lot of defeq abuse between `Multiplicative` and `Additive`,
  -- so we need `erw` below.
(Int.quotientZMultiplesNatEquivZMod n).toMultiplicative.toMonoidHom.comp
    QuotientGroup.map (powMonoidHom n : Kˣ ->* Kˣ).range
      (AddSubgroup.toSubgroup (AddSubgroup.zmulti

中文:
定义 valuationOfNeZeroMod
  签名: (n : 自然数)
  定义体: -- TODO: this definition does a lot of defeq abuse between `Multiplicative` and `Additive`,
  -- so we need `erw` below.
(Int.quotientZMultiplesNatEquivZMod n).toMultiplicative.toMonoidHom.comp
    QuotientGroup.map (powMonoidHom n : Kˣ ->* Kˣ).range
      (AddSubgroup.toSubgroup (AddSubgroup.zmulti
-/
def valuationOfNeZeroMod (n : Nat) : (K / n) ->* Multiplicative (ZMod n) :=
  -- TODO: this definition does a lot of defeq abuse between `Multiplicative` and `Additive`,
  -- so we need `erw` below.
(Int.quotientZMultiplesNatEquivZMod n).toMultiplicative.toMonoidHom.comp
    QuotientGroup.map (powMonoidHom n : Kˣ ->* Kˣ).range
      (AddSubgroup.toSubgroup (AddSubgroup.zmultiples (n : Int)))
      v.valuationOfNeZero
      (by
        rintro _ ⟨x, rfl⟩
        exact
          ⟨v.valuationOfNeZero x, by simp only [powMonoidHom_apply, map_pow, Int.toAdd_pow]; rfl⟩)

@[simp]
/--
theorem `valuation_of_unit_mod_eq` / 定理 `valuation_of_unit_mod_eq`

English:
theorem valuation_of_unit_mod_eq
  given: (n : Nat) (x : Rˣ)
  proof: by
  -- This used to be `rw`, but we need `erw` after https://github.com/leanprover/lean4/pull/2644
  erw [valuationOfNeZeroMod, MonoidHom.comp_apply, ← QuotientGroup.coe_mk',
    QuotientGroup.map_mk' (G := Kˣ) (N := MonoidHom.range (powMonoidHom n)),
    valuation_of_unit_eq, QuotientGroup.mk_one,

中文:
定理 valuation_of_unit_mod_eq
  条件: (n : 自然数) (x : Rˣ)
  证明: by
  -- This used to be `rw`, but we need `erw` after https://github.com/leanprover/lean4/pull/2644
  erw [valuationOfNeZeroMod, MonoidHom.comp_apply, ← QuotientGroup.coe_mk',
    QuotientGroup.map_mk' (G := Kˣ) (N := MonoidHom.range (powMonoidHom n)),
    valuation_of_unit_eq, QuotientGroup.mk_one,
-/
theorem valuation_of_unit_mod_eq (n : Nat) (x : Rˣ) :
    v.valuationOfNeZeroMod n (Units.map (algebraMap R K : R ->* K) x : K / n) = 1 := by
  -- This used to be `rw`, but we need `erw` after https://github.com/leanprover/lean4/pull/2644
  erw [valuationOfNeZeroMod, MonoidHom.comp_apply, ← QuotientGroup.coe_mk',
    QuotientGroup.map_mk' (G := Kˣ) (N := MonoidHom.range (powMonoidHom n)),
    valuation_of_unit_eq, QuotientGroup.mk_one, map_one]

end HeightOneSpectrum

/-! ### Selmer groups -/


variable {S S' : Set <| HeightOneSpectrum R} {n : Nat}

/--
Definition of `selmerGroup` / `selmerGroup` 的定义

English:
definition selmerGroup
  signature: : Subgroup K / n where
  body: {x : K/n | forall (v) (_ : v ∉ S), (v : HeightOneSpectrum R).valuationOfNeZeroMod n x = 1}
  one_mem' _ _ := by rw [map_one]
  mul_mem' hx hy v hv := by rw [map_mul, hx v hv, hy v hv, one_mul]
  inv_mem' hx v hv := by rw [map_inv, hx v hv, inv_one]

中文:
定义 selmerGroup
  签名: : Subgroup K / n where
  定义体: {x : K/n | forall (v) (_ : v ∉ S), (v : HeightOneSpectrum R).valuationOfNeZeroMod n x = 1}
  one_mem' _ _ := by rw [map_one]
  mul_mem' hx hy v hv := by rw [map_mul, hx v hv, hy v hv, one_mul]
  inv_mem' hx v hv := by rw [map_inv, hx v hv, inv_one]

Depends on / 依赖: HeightOneSpectrum, valuationOfNeZeroMod
-/
def selmerGroup : Subgroup K / n where
  carrier := {x : K/n | forall (v) (_ : v ∉ S), (v : HeightOneSpectrum R).valuationOfNeZeroMod n x = 1}
  one_mem' _ _ := by rw [map_one]
  mul_mem' hx hy v hv := by rw [map_mul, hx v hv, hy v hv, one_mul]
  inv_mem' hx v hv := by rw [map_inv, hx v hv, inv_one]

-- Porting note: was `scoped[SelmerGroup]` but that does not work even using `open SelmerGroup`
local notation K "⟮" S "," n "⟯" => @selmerGroup _ _ _ K _ _ _ S n

namespace selmerGroup

/--
theorem `monotone` / 定理 `monotone`

English:
theorem monotone
  given: (hS : S <= S')
  statement: K⟮S,n⟯ <= K⟮S',n⟯
  proof: fun _ hx v => hx v ∘ mt (@hS v)

中文:
定理 monotone
  条件: (hS : S <= S')
  结论: K⟮S,n⟯ <= K⟮S',n⟯
  证明: fun _ hx v => hx v ∘ mt (@hS v)
-/
theorem monotone (hS : S <= S') : K⟮S,n⟯ <= K⟮S',n⟯ := fun _ hx v => hx v ∘ mt (@hS v)

/--
Definition of `valuation` / `valuation` 的定义

English:
definition valuation
  signature: : K⟮S,n⟯ ->* S -> Multiplicative (ZMod n) where
  body: (v : HeightOneSpectrum R).valuationOfNeZeroMod n (x : K / n)
  map_one' := funext fun _ => map_one _
  map_mul' x y := by simp only [Subgroup.coe_mul, map_mul]; rfl

中文:
定义 valuation
  签名: : K⟮S,n⟯ ->* S -> Multiplicative (ZMod n) where
  定义体: (v : HeightOneSpectrum R).valuationOfNeZeroMod n (x : K / n)
  map_one' := funext fun _ => map_one _
  map_mul' x y := by simp only [Subgroup.coe_mul, map_mul]; rfl

Depends on / 依赖: HeightOneSpectrum, valuationOfNeZeroMod
-/
def valuation : K⟮S,n⟯ ->* S -> Multiplicative (ZMod n) where
  toFun x v := (v : HeightOneSpectrum R).valuationOfNeZeroMod n (x : K / n)
  map_one' := funext fun _ => map_one _
  map_mul' x y := by simp only [Subgroup.coe_mul, map_mul]; rfl

/--
theorem `valuation_ker_eq` / 定理 `valuation_ker_eq`

English:
theorem valuation_ker_eq
  proof: by
  ext ⟨_, hx⟩
  constructor
  · intro hx' v _
    by_cases hv : v in S
    · exact congr_fun hx' ⟨v, hv⟩
    · exact hx v hv
· exact fun hx' => funext fun v => hx' v Set.notMem_empty v

中文:
定理 valuation_ker_eq
  证明: by
  ext ⟨_, hx⟩
  constructor
  · intro hx' v _
    by_cases hv : v in S
    · exact congr_fun hx' ⟨v, hv⟩
    · exact hx v hv
· exact fun hx' => funext fun v => hx' v Set.notMem_empty v

Depends on / 依赖: Set.notMem_empty, congr_fun, notMem_empty
-/
theorem valuation_ker_eq :
    valuation.ker = K⟮(∅ : Set <| HeightOneSpectrum R),n⟯.subgroupOf (K⟮S,n⟯) := by
  ext ⟨_, hx⟩
  constructor
  · intro hx' v _
    by_cases hv : v in S
    · exact congr_fun hx' ⟨v, hv⟩
    · exact hx v hv
· exact fun hx' => funext fun v => hx' v Set.notMem_empty v

/--
Definition of `fromUnit` / `fromUnit` 的定义

English:
definition fromUnit
  signature: {n : Nat}
  body: ⟨QuotientGroup.mk Units.map (algebraMap R K).toMonoidHom x, fun v _ =>
      v.valuation_of_unit_mod_eq n x⟩
  map_one' := by simp only [map_one, QuotientGroup.mk_one, Subgroup.mk_eq_one]
  map_mul' _ _ := by simp only [RingHom.toMonoidHom_eq_coe, map_mul, QuotientGroup.mk_mul,
    MulMemClass.mk_mu

中文:
定义 fromUnit
  签名: {n : 自然数}
  定义体: ⟨QuotientGroup.mk Units.map (algebraMap R K).toMonoidHom x, fun v _ =>
      v.valuation_of_unit_mod_eq n x⟩
  map_one' := by simp only [map_one, QuotientGroup.mk_one, Subgroup.mk_eq_one]
  map_mul' _ _ := by simp only [RingHom.toMonoidHom_eq_coe, map_mul, QuotientGroup.mk_mul,
    MulMemClass.mk_mu

Depends on / 依赖: MulMemClass, MulMemClass.mk_mul_mk, QuotientGroup, QuotientGroup.mk, QuotientGroup.mk_mul, QuotientGroup.mk_one, RingHom, RingHom.toMonoidHom_eq_coe, Subgroup, Subgroup.mk_eq_one, Units.map, algebraMap, map_mul, map_one, mk_eq_one, mk_mul, mk_mul_mk, mk_one, toMonoidHom, toMonoidHom_eq_coe
-/
def fromUnit {n : Nat} : Rˣ ->* K⟮(∅ : Set <| HeightOneSpectrum R),n⟯ where
  toFun x :=
⟨QuotientGroup.mk Units.map (algebraMap R K).toMonoidHom x, fun v _ =>
      v.valuation_of_unit_mod_eq n x⟩
  map_one' := by simp only [map_one, QuotientGroup.mk_one, Subgroup.mk_eq_one]
  map_mul' _ _ := by simp only [RingHom.toMonoidHom_eq_coe, map_mul, QuotientGroup.mk_mul,
    MulMemClass.mk_mul_mk]

/--
theorem `fromUnit_ker` / 定理 `fromUnit_ker`

English:
theorem fromUnit_ker
  given: [hn : Fact <| 0 < n]
  proof: by
  ext ⟨_, _, _, _⟩
  constructor
  · intro hx
    rcases (QuotientGroup.eq_one_iff _).mp (Subtype.mk.inj hx) with ⟨⟨v, i, vi, iv⟩, hx⟩
    have hv : ↑(_ ^ n : Kˣ) = algebraMap R K _ := congr_arg Units.val hx
    have hi : ↑(_ ^ n : Kˣ)⁻¹ = algebraMap R K _ := congr_arg Units.inv hx
    rw [Units.

中文:
定理 fromUnit_ker
  条件: [hn : Fact <| 0 < n]
  证明: by
  ext ⟨_, _, _, _⟩
  constructor
  · intro hx
    rcases (QuotientGroup.eq_one_iff _).mp (Subtype.mk.inj hx) with ⟨⟨v, i, vi, iv⟩, hx⟩
    have hv : ↑(_ ^ n : Kˣ) = algebraMap R K _ := congr_arg Units.val hx
    have hi : ↑(_ ^ n : Kˣ)⁻¹ = algebraMap R K _ := congr_arg Units.inv hx
    rw [Units.

Depends on / 依赖: IsIntegrallyClosed, IsIntegrallyClosed.exists_algebraMap_eq_of_isIntegral_pow, QuotientGroup, QuotientGroup.eq_one_iff, Subtype, Subtype.mk.inj, Units.inv, Units.inv_mk, Units.val, Units.val_pow_eq_pow_val, algebraMap, congr_arg, eq_one_iff, exists_algebraMap_eq_of_isIntegral_pow, hn.out, hv.symm, inv_mk, inv_pow, isIntegral_algebraMap, val_pow_eq_pow_val
-/
theorem fromUnit_ker [hn : Fact <| 0 < n] :
    (@fromUnit R _ _ K _ _ _ n).ker = (powMonoidHom n : Rˣ ->* Rˣ).range := by
  ext ⟨_, _, _, _⟩
  constructor
  · intro hx
    rcases (QuotientGroup.eq_one_iff _).mp (Subtype.mk.inj hx) with ⟨⟨v, i, vi, iv⟩, hx⟩
    have hv : ↑(_ ^ n : Kˣ) = algebraMap R K _ := congr_arg Units.val hx
    have hi : ↑(_ ^ n : Kˣ)⁻¹ = algebraMap R K _ := congr_arg Units.inv hx
    rw [Units.val_pow_eq_pow_val] at hv
    rw [← inv_pow]; rw [Units.inv_mk]; rw [Units.val_pow_eq_pow_val] at hi
    rcases IsIntegrallyClosed.exists_algebraMap_eq_of_isIntegral_pow (R := R) (x := v) hn.out
        (hv.symm ▸ isIntegral_algebraMap) with
      ⟨v', rfl⟩
    rcases IsIntegrallyClosed.exists_algebraMap_eq_of_isIntegral_pow (R := R) (x := i) hn.out
        (hi.symm ▸ isIntegral_algebraMap) with
      ⟨i', rfl⟩
    rw [← map_mul]; rw [map_eq_one_iff _ <| FaithfulSMul.algebraMap_injective R K] at vi
    rw [← map_mul]; rw [map_eq_one_iff _ <| FaithfulSMul.algebraMap_injective R K] at iv
    rw [Units.val_mk]; rw [← map_pow] at hv
    exact ⟨⟨v', i', vi, iv⟩, by
      simpa only [Units.ext_iff, powMonoidHom_apply, Units.val_pow_eq_pow_val] using
         FaithfulSMul.algebraMap_injective R K hv⟩
  · rintro ⟨x, hx⟩
    rw [← hx]
exact Subtype.mk_eq_mk.mpr (QuotientGroup.eq_one_iff _).mpr ⟨Units.map (algebraMap R K) x,
      by simp only [powMonoidHom_apply, RingHom.toMonoidHom_eq_coe, map_pow]⟩

/--
Definition of `fromUnitLift` / `fromUnitLift` 的定义

English:
definition fromUnitLift
  signature: [Fact <| 0 < n]
  body: (QuotientGroup.kerLift _).comp
    (QuotientGroup.quotientMulEquivOfEq (fromUnit_ker (R := R))).symm.toMonoidHom

中文:
定义 fromUnitLift
  签名: [Fact <| 0 < n]
  定义体: (QuotientGroup.kerLift _).comp
    (QuotientGroup.quotientMulEquivOfEq (fromUnit_ker (R := R))).symm.toMonoidHom

Depends on / 依赖: QuotientGroup, QuotientGroup.kerLift, QuotientGroup.quotientMulEquivOfEq, fromUnit_ker, kerLift, quotientMulEquivOfEq, symm.toMonoidHom, toMonoidHom
-/
def fromUnitLift [Fact <| 0 < n] : (R / n) ->* K⟮(∅ : Set <| HeightOneSpectrum R),n⟯ :=
  (QuotientGroup.kerLift _).comp
    (QuotientGroup.quotientMulEquivOfEq (fromUnit_ker (R := R))).symm.toMonoidHom

/--
theorem `fromUnitLift_injective` / 定理 `fromUnitLift_injective`

English:
theorem fromUnitLift_injective
  given: [Fact <| 0 < n]
  proof: by
  dsimp only [fromUnitLift, MonoidHom.coe_comp, MulEquiv.coe_toMonoidHom]
  exact Function.Injective.comp (QuotientGroup.kerLift_injective _) (MulEquiv.injective _)

中文:
定理 fromUnitLift_injective
  条件: [Fact <| 0 < n]
  证明: by
  dsimp only [fromUnitLift, MonoidHom.coe_comp, MulEquiv.coe_toMonoidHom]
  exact Function.Injective.comp (QuotientGroup.kerLift_injective _) (MulEquiv.injective _)

Depends on / 依赖: Function, Function.Injective.comp, Injective, MonoidHom, MonoidHom.coe_comp, MulEquiv, MulEquiv.coe_toMonoidHom, MulEquiv.injective, QuotientGroup, QuotientGroup.kerLift_injective, coe_comp, coe_toMonoidHom, fromUnitLift, injective, kerLift_injective
-/
theorem fromUnitLift_injective [Fact <| 0 < n] :
Function.Injective @fromUnitLift R _ _ K _ _ _ n _ := by
  dsimp only [fromUnitLift, MonoidHom.coe_comp, MulEquiv.coe_toMonoidHom]
  exact Function.Injective.comp (QuotientGroup.kerLift_injective _) (MulEquiv.injective _)

end selmerGroup

end

end IsDedekindDomain
