/-
Copyright (c) 2021 Anne Baanen. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anne Baanen
-/
module

public import Mathlib.RingTheory.DedekindDomain.Ideal.Basic
public import Mathlib.Tactic.CrossRefAttribute

/-!
# The ideal class group

This file defines the ideal class group `ClassGroup R` of fractional ideals of `R`
inside its field of fractions.

## Main definitions

- `toPrincipalIdeal` sends an invertible `x : K` to an invertible fractional ideal
- `ClassGroup` is the quotient of invertible fractional ideals modulo `toPrincipalIdeal.range`
- `ClassGroup.mk0` sends a nonzero integral ideal in a Dedekind domain to its class

## Main results
- `ClassGroup.mk0_eq_mk0_iff` shows the equivalence with the "classical" definition,
  where `I ~ J` iff `x I = y J` for `x y ≠ (0 : R)`
- `ClassGroup.mk0_eq_quotientMk` identifies `ClassGroup.mk0` with the canonical quotient
  projection on `(FractionalIdeal R⁰ (FractionRing R))ˣ`

## Implementation details

The definition of `ClassGroup R` involves `FractionRing R`. However, the API should be completely
identical no matter the choice of field of fractions for `R`.
-/

@[expose] public noncomputable section


variable {R K : Type*} [CommRing R] [Field K] [Algebra R K] [IsFractionRing R K]

open scoped nonZeroDivisors

open IsLocalization IsFractionRing FractionalIdeal Units

section

variable (R K)

/-- `toPrincipalIdeal R K x` sends `x ≠ 0 : K` to the fractional `R`-ideal generated by `x` -/
irreducible_def toPrincipalIdeal : Kˣ ->* (FractionalIdeal R⁰ K)ˣ :=
  { toFun := fun x =>
      ⟨spanSingleton _ x, spanSingleton _ x⁻¹, by
        simp only [spanSingleton_one, Units.mul_inv', spanSingleton_mul_spanSingleton], by
        simp only [spanSingleton_one, Units.inv_mul', spanSingleton_mul_spanSingleton]⟩
    map_mul' := fun x y =>
      ext (by simp only [Units.val_mul, spanSingleton_mul_spanSingleton])
    map_one' := ext (by simp only [spanSingleton_one, Units.val_one]) }

variable {R K}

@[simp]
/--
theorem `coe_toPrincipalIdeal` / 定理 `coe_toPrincipalIdeal`

English:
theorem coe_toPrincipalIdeal
  given: (x : Kˣ)
  proof: by
  simp only [toPrincipalIdeal]; rfl

@[simp]

中文:
定理 coe_toPrincipalIdeal
  条件: (x : Kˣ)
  证明: by
  simp only [toPrincipalIdeal]; rfl

@[simp]

Depends on / 依赖: toPrincipalIdeal
-/
theorem coe_toPrincipalIdeal (x : Kˣ) :
    (toPrincipalIdeal R K x : FractionalIdeal R⁰ K) = spanSingleton _ (x : K) := by
  simp only [toPrincipalIdeal]; rfl

@[simp]
/--
theorem `toPrincipalIdeal_eq_iff` / 定理 `toPrincipalIdeal_eq_iff`

English:
theorem toPrincipalIdeal_eq_iff
  given: {I : (FractionalIdeal R⁰ K)ˣ} {x : Kˣ}
  proof: by
  simp only [toPrincipalIdeal]; exact Units.ext_iff

中文:
定理 toPrincipalIdeal_eq_iff
  条件: {I : (FractionalIdeal R⁰ K)ˣ} {x : Kˣ}
  证明: by
  simp only [toPrincipalIdeal]; exact Units.ext_iff

Depends on / 依赖: Units.ext_iff, ext_iff, toPrincipalIdeal
-/
theorem toPrincipalIdeal_eq_iff {I : (FractionalIdeal R⁰ K)ˣ} {x : Kˣ} :
    toPrincipalIdeal R K x = I ↔ spanSingleton R⁰ (x : K) = I := by
  simp only [toPrincipalIdeal]; exact Units.ext_iff

/--
theorem `mem_principal_ideals_iff` / 定理 `mem_principal_ideals_iff`

English:
theorem mem_principal_ideals_iff
  given: {I : (FractionalIdeal R⁰ K)ˣ}
  proof: by
  simp only [MonoidHom.mem_range, toPrincipalIdeal_eq_iff]
  constructor <;> rintro ⟨x, hx⟩
  · exact ⟨x, hx⟩
  · refine ⟨Units.mk0 x ?_, hx⟩
    rintro rfl
    simp [I.ne_zero.symm] at hx

中文:
定理 mem_principal_ideals_iff
  条件: {I : (FractionalIdeal R⁰ K)ˣ}
  证明: by
  simp only [MonoidHom.mem_range, toPrincipalIdeal_eq_iff]
  constructor <;> rintro ⟨x, hx⟩
  · exact ⟨x, hx⟩
  · refine ⟨Units.mk0 x ?_, hx⟩
    rintro rfl
    simp [I.ne_zero.symm] at hx

Depends on / 依赖: I.ne_zero.symm, MonoidHom, MonoidHom.mem_range, Units.mk0, mem_range, ne_zero, toPrincipalIdeal_eq_iff
-/
theorem mem_principal_ideals_iff {I : (FractionalIdeal R⁰ K)ˣ} :
    I in (toPrincipalIdeal R K).range ↔ exists x : K, spanSingleton R⁰ x = I := by
  simp only [MonoidHom.mem_range, toPrincipalIdeal_eq_iff]
  constructor <;> rintro ⟨x, hx⟩
  · exact ⟨x, hx⟩
  · refine ⟨Units.mk0 x ?_, hx⟩
    rintro rfl
    simp [I.ne_zero.symm] at hx

/--
Instance `PrincipalIdeals.normal` / 实例 `PrincipalIdeals.normal`

English:
instance PrincipalIdeals.normal
  signature: : (toPrincipalIdeal R K).range.Normal
  body: Subgroup.normal_of_isMulCommutative _

中文:
实例 PrincipalIdeals.normal
  签名: : (toPrincipalIdeal R K).range.Normal
  定义体: Subgroup.normal_of_isMulCommutative _

Depends on / 依赖: Subgroup, Subgroup.normal_of_isMulCommutative, normal_of_isMulCommutative
-/
instance PrincipalIdeals.normal : (toPrincipalIdeal R K).range.Normal :=
  Subgroup.normal_of_isMulCommutative _

end

variable (R)
variable [IsDomain R]

/-- The ideal class group of `R` is the group of invertible fractional ideals
modulo the principal ideals. -/
@[wikidata Q912083]
/--
Definition of `ClassGroup` / `ClassGroup` 的定义

English:
definition ClassGroup
  body: (FractionalIdeal R⁰ (FractionRing R))ˣ ⧸ (toPrincipalIdeal R (FractionRing R)).range
deriving CommGroup, Inhabited

中文:
定义 ClassGroup
  定义体: (FractionalIdeal R⁰ (FractionRing R))ˣ ⧸ (toPrincipalIdeal R (FractionRing R)).range
deriving CommGroup, Inhabited

Depends on / 依赖: FractionRing, FractionalIdeal, toPrincipalIdeal
-/
def ClassGroup :=
  (FractionalIdeal R⁰ (FractionRing R))ˣ ⧸ (toPrincipalIdeal R (FractionRing R)).range
deriving CommGroup, Inhabited

/--
Definition of `ClassGroup.mulEquivUnitsSubmoduleQuotRange` / `ClassGroup.mulEquivUnitsSubmoduleQuotRange` 的定义

English:
definition ClassGroup.mulEquivUnitsSubmoduleQuotRange
  signature: :
  body: QuotientGroup.congr _ _ unitsMulEquivSubmodule by
    simp_rw [MonoidHom.range_eq_map, Subgroup.map_map]; congr; ext; simp [unitsMulEquivSubmodule]

中文:
定义 ClassGroup.mulEquivUnitsSubmoduleQuotRange
  签名: :
  定义体: QuotientGroup.congr _ _ unitsMulEquivSubmodule by
    simp_rw [MonoidHom.range_eq_map, Subgroup.map_map]; congr; ext; simp [unitsMulEquivSubmodule]

Depends on / 依赖: MonoidHom, MonoidHom.range_eq_map, QuotientGroup, QuotientGroup.congr, Subgroup, Subgroup.map_map, map_map, range_eq_map, simp_rw, unitsMulEquivSubmodule
-/
def ClassGroup.mulEquivUnitsSubmoduleQuotRange :
    ClassGroup R ≃*
    (Submodule R (FractionRing R))ˣ ⧸ (Units.map (Submodule.spanSingleton R).toMonoidHom).range :=
QuotientGroup.congr _ _ unitsMulEquivSubmodule by
    simp_rw [MonoidHom.range_eq_map, Subgroup.map_map]; congr; ext; simp [unitsMulEquivSubmodule]

variable {R} (K)

/--
Definition of `ClassGroup.mk` / `ClassGroup.mk` 的定义

English:
definition ClassGroup.mk
  signature: : (FractionalIdeal R⁰ K)ˣ ->* ClassGroup R
  body: (QuotientGroup.mk' (toPrincipalIdeal R (FractionRing R)).range).comp
    (Units.map (FractionalIdeal.canonicalEquiv R⁰ K (FractionRing R)))

中文:
定义 ClassGroup.mk
  签名: : (FractionalIdeal R⁰ K)ˣ ->* ClassGroup R
  定义体: (QuotientGroup.mk' (toPrincipalIdeal R (FractionRing R)).range).comp
    (Units.map (FractionalIdeal.canonicalEquiv R⁰ K (FractionRing R)))

Depends on / 依赖: FractionRing, FractionalIdeal, FractionalIdeal.canonicalEquiv, QuotientGroup, QuotientGroup.mk, Units.map, canonicalEquiv, toPrincipalIdeal
-/
def ClassGroup.mk : (FractionalIdeal R⁰ K)ˣ ->* ClassGroup R :=
  (QuotientGroup.mk' (toPrincipalIdeal R (FractionRing R)).range).comp
    (Units.map (FractionalIdeal.canonicalEquiv R⁰ K (FractionRing R)))

variable {K}

/--
lemma `ClassGroup.mk_def` / 引理 `ClassGroup.mk_def`

English:
lemma ClassGroup.mk_def
  given: (I : (FractionalIdeal R⁰ K)ˣ)
  proof: rfl

中文:
引理 ClassGroup.mk_def
  条件: (I : (FractionalIdeal R⁰ K)ˣ)
  证明: rfl
-/
lemma ClassGroup.mk_def (I : (FractionalIdeal R⁰ K)ˣ) :
    ClassGroup.mk K I =
      (QuotientGroup.mk' (toPrincipalIdeal R (FractionRing R)).range)
        (Units.map (FractionalIdeal.canonicalEquiv R⁰ K (FractionRing R)) I) := rfl

-- Can't be `@[simp]` because it can't figure out the quotient relation.
/--
theorem `ClassGroup.Quot_mk_eq_mk` / 定理 `ClassGroup.Quot_mk_eq_mk`

English:
theorem ClassGroup.Quot_mk_eq_mk
  given: (I : (FractionalIdeal R⁰ (FractionRing R))ˣ)
  proof: by
  rw [ClassGroup.mk_def]; rw [canonicalEquiv_self]; rw [RingEquiv.coe_monoidHom_refl]; rw [Units.map_id]; rw [MonoidHom.id_apply]; rw [QuotientGroup.mk'_apply]
  rfl

中文:
定理 ClassGroup.Quot_mk_eq_mk
  条件: (I : (FractionalIdeal R⁰ (FractionRing R))ˣ)
  证明: by
  rw [ClassGroup.mk_def]; rw [canonicalEquiv_self]; rw [RingEquiv.coe_monoidHom_refl]; rw [Units.map_id]; rw [MonoidHom.id_apply]; rw [QuotientGroup.mk'_apply]
  rfl

Depends on / 依赖: ClassGroup, ClassGroup.mk_def, MonoidHom, MonoidHom.id_apply, QuotientGroup, QuotientGroup.mk, RingEquiv, RingEquiv.coe_monoidHom_refl, Units.map_id, _apply, canonicalEquiv_self, coe_monoidHom_refl, id_apply, map_id, mk_def
-/
theorem ClassGroup.Quot_mk_eq_mk (I : (FractionalIdeal R⁰ (FractionRing R))ˣ) :
    Quot.mk _ I = ClassGroup.mk (FractionRing R) I := by
  rw [ClassGroup.mk_def]; rw [canonicalEquiv_self]; rw [RingEquiv.coe_monoidHom_refl]; rw [Units.map_id]; rw [MonoidHom.id_apply]; rw [QuotientGroup.mk'_apply]
  rfl

set_option backward.isDefEq.respectTransparency false in
/--
theorem `ClassGroup.mk_eq_mk` / 定理 `ClassGroup.mk_eq_mk`

English:
theorem ClassGroup.mk_eq_mk
  given: {I J : (FractionalIdeal R⁰ <| FractionRing R)ˣ}
  proof: by
  rw [mk_def]; rw [mk_def]; rw [QuotientGroup.mk'_eq_mk']
  simp [RingEquiv.coe_monoidHom_refl, MonoidHom.mem_range, -toPrincipalIdeal_eq_iff]

中文:
定理 ClassGroup.mk_eq_mk
  条件: {I J : (FractionalIdeal R⁰ <| FractionRing R)ˣ}
  证明: by
  rw [mk_def]; rw [mk_def]; rw [QuotientGroup.mk'_eq_mk']
  simp [RingEquiv.coe_monoidHom_refl, MonoidHom.mem_range, -toPrincipalIdeal_eq_iff]

Depends on / 依赖: MonoidHom, MonoidHom.mem_range, QuotientGroup, QuotientGroup.mk, RingEquiv, RingEquiv.coe_monoidHom_refl, _eq_mk, coe_monoidHom_refl, mem_range, mk_def, toPrincipalIdeal_eq_iff
-/
theorem ClassGroup.mk_eq_mk {I J : (FractionalIdeal R⁰ <| FractionRing R)ˣ} :
    ClassGroup.mk (FractionRing R) I = ClassGroup.mk (FractionRing R) J ↔
      exists x : (FractionRing R)ˣ, I * toPrincipalIdeal R (FractionRing R) x = J := by
  rw [mk_def]; rw [mk_def]; rw [QuotientGroup.mk'_eq_mk']
  simp [RingEquiv.coe_monoidHom_refl, MonoidHom.mem_range, -toPrincipalIdeal_eq_iff]

/--
theorem `ClassGroup.mk_eq_mk_of_coe_ideal` / 定理 `ClassGroup.mk_eq_mk_of_coe_ideal`

English:
theorem ClassGroup.mk_eq_mk_of_coe_ideal
  statement: {I J : (FractionalIdeal R⁰ <| FractionRing R)ˣ}
  proof: by
  rw [ClassGroup.mk_eq_mk]
  constructor
  · rintro ⟨x, rfl⟩
    rw [Units.val_mul]; rw [hI]; rw [coe_toPrincipalIdeal]; rw [mul_comm]; rw [spanSingleton_mul_coeIdeal_eq_coeIdeal] at hJ
    exact ⟨_, _, sec_fst_ne_zero x.ne_zero,
      sec_snd_ne_zero (R := R) le_rfl (x : FractionRing R), hJ⟩
  ·

中文:
定理 ClassGroup.mk_eq_mk_of_coe_ideal
  结论: {I J : (FractionalIdeal R⁰ <| FractionRing R)ˣ}
  证明: by
  rw [ClassGroup.mk_eq_mk]
  constructor
  · rintro ⟨x, rfl⟩
    rw [Units.val_mul]; rw [hI]; rw [coe_toPrincipalIdeal]; rw [mul_comm]; rw [spanSingleton_mul_coeIdeal_eq_coeIdeal] at hJ
    exact ⟨_, _, sec_fst_ne_zero x.ne_zero,
      sec_snd_ne_zero (R := R) le_rfl (x : FractionRing R), hJ⟩
  ·

Depends on / 依赖: ClassGroup, ClassGroup.mk_eq_mk, FractionRing, IsUnit, Units.val_mul, _eq_zero_iff_eq_zero, coe_toPrincipalIdeal, isUnit_iff_ne_zero, le_rfl, mem_nonZeroDivisors_of_ne_zero, mk_eq_mk, mul_comm, ne_eq, ne_zero, sec_fst_ne_zero, sec_snd_ne_zero, spanSingleton_mul_coeIdeal_eq_coeIdeal, this.unit, val_mul, x.ne_zero
-/
theorem ClassGroup.mk_eq_mk_of_coe_ideal {I J : (FractionalIdeal R⁰ <| FractionRing R)ˣ}
    {I' J' : Ideal R} (hI : (I : FractionalIdeal R⁰ <| FractionRing R) = I')
    (hJ : (J : FractionalIdeal R⁰ <| FractionRing R) = J') :
    ClassGroup.mk (FractionRing R) I = ClassGroup.mk (FractionRing R) J ↔
      exists x y : R, x != 0 ∧ y != 0 ∧ Ideal.span {x} * I' = Ideal.span {y} * J' := by
  rw [ClassGroup.mk_eq_mk]
  constructor
  · rintro ⟨x, rfl⟩
    rw [Units.val_mul]; rw [hI]; rw [coe_toPrincipalIdeal]; rw [mul_comm]; rw [spanSingleton_mul_coeIdeal_eq_coeIdeal] at hJ
    exact ⟨_, _, sec_fst_ne_zero x.ne_zero,
      sec_snd_ne_zero (R := R) le_rfl (x : FractionRing R), hJ⟩
  · rintro ⟨x, y, hx, hy, h⟩
    have : IsUnit (mk' (FractionRing R) x ⟨y, mem_nonZeroDivisors_of_ne_zero hy⟩) := by
      simpa only [isUnit_iff_ne_zero, ne_eq, mk'_eq_zero_iff_eq_zero] using hx
    refine ⟨this.unit, ?_⟩
    rw [mul_comm]; rw [← Units.val_inj]; rw [Units.val_mul]; rw [coe_toPrincipalIdeal]
    convert!
      (mk'_mul_coeIdeal_eq_coeIdeal (FractionRing R) <| mem_nonZeroDivisors_of_ne_zero hy).2 h

/--
theorem `ClassGroup.mk_eq_one_of_coe_ideal` / 定理 `ClassGroup.mk_eq_one_of_coe_ideal`

English:
theorem ClassGroup.mk_eq_one_of_coe_ideal
  statement: {I : (FractionalIdeal R⁰ <| FractionRing R)ˣ}
  proof: by
  rw [← map_one (ClassGroup.mk (R := R) (K := FractionRing R))]; rw [ClassGroup.mk_eq_mk_of_coe_ideal hI]
  any_goals rfl
  constructor
  · rintro ⟨x, y, hx, hy, h⟩
    rw [Ideal.mul_top] at h
    rcases Ideal.mem_span_singleton_mul.mp ((Ideal.span_singleton_le_iff_mem _).mp h.ge) with
      ⟨i, 

中文:
定理 ClassGroup.mk_eq_one_of_coe_ideal
  结论: {I : (FractionalIdeal R⁰ <| FractionRing R)ˣ}
  证明: by
  rw [← map_one (ClassGroup.mk (R := R) (K := FractionRing R))]; rw [ClassGroup.mk_eq_mk_of_coe_ideal hI]
  any_goals rfl
  constructor
  · rintro ⟨x, y, hx, hy, h⟩
    rw [Ideal.mul_top] at h
    rcases Ideal.mem_span_singleton_mul.mp ((Ideal.span_singleton_le_iff_mem _).mp h.ge) with
      ⟨i, 

Depends on / 依赖: ClassGroup, ClassGroup.mk, ClassGroup.mk_eq_mk_of_coe_ideal, FractionRing, Ideal.mem_span_singleton_mul.mp, Ideal.mul_top, Ideal.span_singleton_le_iff_mem, Ideal.span_singleton_mul_right_inj, Ideal.span_singleton_mul_span_singleton, Ideal.span_singleton_one, any_goals, grobner, h.ge, map_one, mem_span_singleton_mul, mk_eq_mk_of_coe_ideal, mul_top, one_ne_zero, span_singleton_le_iff_mem, span_singleton_mul_right_inj
-/
theorem ClassGroup.mk_eq_one_of_coe_ideal {I : (FractionalIdeal R⁰ <| FractionRing R)ˣ}
    {I' : Ideal R} (hI : (I : FractionalIdeal R⁰ <| FractionRing R) = I') :
    ClassGroup.mk (FractionRing R) I = 1 ↔ exists x : R, x != 0 ∧ I' = Ideal.span {x} := by
  rw [← map_one (ClassGroup.mk (R := R) (K := FractionRing R))]; rw [ClassGroup.mk_eq_mk_of_coe_ideal hI]
  any_goals rfl
  constructor
  · rintro ⟨x, y, hx, hy, h⟩
    rw [Ideal.mul_top] at h
    rcases Ideal.mem_span_singleton_mul.mp ((Ideal.span_singleton_le_iff_mem _).mp h.ge) with
      ⟨i, _hi, rfl⟩
    rw [← Ideal.span_singleton_mul_span_singleton]; rw [Ideal.span_singleton_mul_right_inj hx] at h
    exact ⟨i, by grobner, h⟩
  · rintro ⟨x, hx, rfl⟩
    exact ⟨1, x, one_ne_zero, hx, by rw [Ideal.span_singleton_one, Ideal.top_mul, Ideal.mul_top]⟩

variable (K)

/-- Induction principle for the class group: to show something holds for all `x : ClassGroup R`,
we can choose a fraction field `K` and show it holds for the equivalence class of each
`I : FractionalIdeal R⁰ K`. -/
@[elab_as_elim]
/--
theorem `ClassGroup.induction` / 定理 `ClassGroup.induction`

English:
theorem ClassGroup.induction
  statement: {P : ClassGroup R -> Prop}
  proof: QuotientGroup.induction_on x fun I => by
    have : I = (Units.mapEquiv (canonicalEquiv R⁰ K (FractionRing R)).toMulEquiv)
      (Units.mapEquiv (canonicalEquiv R⁰ (FractionRing R) K).toMulEquiv I) := by
      simp [← Units.val_inj]
    rw [congr_arg (QuotientGroup.mk (s := (toPrincipalIdeal R (Frac

中文:
定理 ClassGroup.induction
  结论: {P : ClassGroup R -> 命题}
  证明: QuotientGroup.induction_on x fun I => by
    have : I = (Units.mapEquiv (canonicalEquiv R⁰ K (FractionRing R)).toMulEquiv)
      (Units.mapEquiv (canonicalEquiv R⁰ (FractionRing R) K).toMulEquiv I) := by
      simp [← Units.val_inj]
    rw [congr_arg (QuotientGroup.mk (s := (toPrincipalIdeal R (Frac

Depends on / 依赖: FractionRing, QuotientGroup, QuotientGroup.induction_on, QuotientGroup.mk, Units.mapEquiv, Units.val_inj, canonicalEquiv, congr_arg, induction_on, mapEquiv, toMulEquiv, toPrincipalIdeal, val_inj
-/
theorem ClassGroup.induction {P : ClassGroup R -> Prop}
    (h : forall I : (FractionalIdeal R⁰ K)ˣ, P (ClassGroup.mk K I)) (x : ClassGroup R) : P x :=
  QuotientGroup.induction_on x fun I => by
    have : I = (Units.mapEquiv (canonicalEquiv R⁰ K (FractionRing R)).toMulEquiv)
      (Units.mapEquiv (canonicalEquiv R⁰ (FractionRing R) K).toMulEquiv I) := by
      simp [← Units.val_inj]
    rw [congr_arg (QuotientGroup.mk (s := (toPrincipalIdeal R (FractionRing R)).range)) this]
    exact h _

/--
Definition of `ClassGroup.equiv` / `ClassGroup.equiv` 的定义

English:
definition ClassGroup.equiv
  signature: :
  body: by
  haveI : Subgroup.map
    (Units.mapEquiv (canonicalEquiv R⁰ (FractionRing R) K).toMulEquiv).toMonoidHom
    (toPrincipalIdeal R (FractionRing R)).range = (toPrincipalIdeal R K).range := by
    ext I
    simp only [Subgroup.mem_map, mem_principal_ideals_iff]
    constructor
    · rintro ⟨I, ⟨x, 

中文:
定义 ClassGroup.equiv
  签名: :
  定义体: by
  haveI : Subgroup.map
    (Units.mapEquiv (canonicalEquiv R⁰ (FractionRing R) K).toMulEquiv).toMonoidHom
    (toPrincipalIdeal R (FractionRing R)).range = (toPrincipalIdeal R K).range := by
    ext I
    simp only [Subgroup.mem_map, mem_principal_ideals_iff]
    constructor
    · rintro ⟨I, ⟨x, 

Depends on / 依赖: FractionRing, FractionRing.algEquiv, MulEquiv, MulEquiv.coe_toMonoidHom, RingEquiv, RingEquiv.coe_toMulEquiv, RingEquiv.toMulEquiv_eq_coe, Subgroup, Subgroup.map, Subgroup.mem_map, Units.mapEquiv, algEquiv, canonicalEquiv, canonicalEquiv_spanSingleton, coe_mapEquiv, coe_toMonoidHom, coe_toMulEquiv, mapEquiv, mem_map, mem_principal_ideals_iff
-/
def ClassGroup.equiv :
    ClassGroup R ≃* (FractionalIdeal R⁰ K)ˣ ⧸ (toPrincipalIdeal R K).range := by
  haveI : Subgroup.map
    (Units.mapEquiv (canonicalEquiv R⁰ (FractionRing R) K).toMulEquiv).toMonoidHom
    (toPrincipalIdeal R (FractionRing R)).range = (toPrincipalIdeal R K).range := by
    ext I
    simp only [Subgroup.mem_map, mem_principal_ideals_iff]
    constructor
    · rintro ⟨I, ⟨x, hx⟩, rfl⟩
      refine ⟨FractionRing.algEquiv R K x, ?_⟩
      simp only [RingEquiv.toMulEquiv_eq_coe, MulEquiv.coe_toMonoidHom, coe_mapEquiv, ← hx,
        RingEquiv.coe_toMulEquiv, canonicalEquiv_spanSingleton]
      rfl
    · rintro ⟨x, hx⟩
      refine ⟨Units.mapEquiv (canonicalEquiv R⁰ K (FractionRing R)).toMulEquiv I,
        ⟨(FractionRing.algEquiv R K).symm x, ?_⟩, Units.ext ?_⟩
      · simp only [RingEquiv.toMulEquiv_eq_coe, coe_mapEquiv, ← hx, RingEquiv.coe_toMulEquiv,
          canonicalEquiv_spanSingleton]
        rfl
      · simp only [RingEquiv.toMulEquiv_eq_coe, MulEquiv.coe_toMonoidHom, coe_mapEquiv,
          RingEquiv.coe_toMulEquiv, canonicalEquiv_canonicalEquiv, canonicalEquiv_self,
          RingEquiv.refl_apply]
  exact QuotientGroup.congr (toPrincipalIdeal R (FractionRing R)).range (toPrincipalIdeal R K).range
    (Units.mapEquiv (FractionalIdeal.canonicalEquiv R⁰ (FractionRing R) K).toMulEquiv) this

set_option backward.isDefEq.respectTransparency false in
@[simp]
/--
theorem `ClassGroup.equiv_mk` / 定理 `ClassGroup.equiv_mk`

English:
theorem ClassGroup.equiv_mk
  statement: (K' : Type*) [Field K'] [Algebra R K'] [IsFractionRing R K']
  proof: by
  -- `simp` can't apply `ClassGroup.mk_def` and `rw` can't unfold `ClassGroup`.
  rw [ClassGroup.equiv]; rw [ClassGroup.mk_def]
  simp only [ClassGroup, QuotientGroup.congr_mk']
  congr
  rw [← Units.val_inj]; rw [Units.coe_mapEquiv]; rw [Units.coe_mapEquiv]; rw [Units.coe_map]
  exact Fractional

中文:
定理 ClassGroup.equiv_mk
  结论: (K' : 类型) [Field K'] [Algebra R K'] [IsFractionRing R K']
  证明: by
  -- `simp` can't apply `ClassGroup.mk_def` and `rw` can't unfold `ClassGroup`.
  rw [ClassGroup.equiv]; rw [ClassGroup.mk_def]
  simp only [ClassGroup, QuotientGroup.congr_mk']
  congr
  rw [← Units.val_inj]; rw [Units.coe_mapEquiv]; rw [Units.coe_mapEquiv]; rw [Units.coe_map]
  exact Fractional
-/
theorem ClassGroup.equiv_mk (K' : Type*) [Field K'] [Algebra R K'] [IsFractionRing R K']
    (I : (FractionalIdeal R⁰ K)ˣ) :
    ClassGroup.equiv K' (ClassGroup.mk K I) =
      QuotientGroup.mk' _ (Units.mapEquiv (↑(FractionalIdeal.canonicalEquiv R⁰ K K')) I) := by
  -- `simp` can't apply `ClassGroup.mk_def` and `rw` can't unfold `ClassGroup`.
  rw [ClassGroup.equiv]; rw [ClassGroup.mk_def]
  simp only [ClassGroup, QuotientGroup.congr_mk']
  congr
  rw [← Units.val_inj]; rw [Units.coe_mapEquiv]; rw [Units.coe_mapEquiv]; rw [Units.coe_map]
  exact FractionalIdeal.canonicalEquiv_canonicalEquiv _ _ _ _ _

@[simp]
/--
theorem `ClassGroup.mk_canonicalEquiv` / 定理 `ClassGroup.mk_canonicalEquiv`

English:
theorem ClassGroup.mk_canonicalEquiv
  statement: (K' : Type*) [Field K'] [Algebra R K'] [IsFractionRing R K']
  proof: by
  rw [ClassGroup.mk_def]; rw [ClassGroup.mk_def]; rw [← MonoidHom.comp_apply (Units.map _)]; rw [← Units.map_comp]; rw [← RingEquiv.coe_monoidHom_trans]; rw [FractionalIdeal.canonicalEquiv_trans_canonicalEquiv]

中文:
定理 ClassGroup.mk_canonicalEquiv
  结论: (K' : 类型) [Field K'] [Algebra R K'] [IsFractionRing R K']
  证明: by
  rw [ClassGroup.mk_def]; rw [ClassGroup.mk_def]; rw [← MonoidHom.comp_apply (Units.map _)]; rw [← Units.map_comp]; rw [← RingEquiv.coe_monoidHom_trans]; rw [FractionalIdeal.canonicalEquiv_trans_canonicalEquiv]

Depends on / 依赖: ClassGroup, ClassGroup.mk_def, FractionalIdeal, FractionalIdeal.canonicalEquiv_trans_canonicalEquiv, MonoidHom, MonoidHom.comp_apply, RingEquiv, RingEquiv.coe_monoidHom_trans, Units.map, Units.map_comp, canonicalEquiv_trans_canonicalEquiv, coe_monoidHom_trans, comp_apply, map_comp, mk_def
-/
theorem ClassGroup.mk_canonicalEquiv (K' : Type*) [Field K'] [Algebra R K'] [IsFractionRing R K']
    (I : (FractionalIdeal R⁰ K)ˣ) :
    ClassGroup.mk K' (Units.map (↑(canonicalEquiv R⁰ K K')) I : (FractionalIdeal R⁰ K')ˣ) =
      ClassGroup.mk K I := by
  rw [ClassGroup.mk_def]; rw [ClassGroup.mk_def]; rw [← MonoidHom.comp_apply (Units.map _)]; rw [← Units.map_comp]; rw [← RingEquiv.coe_monoidHom_trans]; rw [FractionalIdeal.canonicalEquiv_trans_canonicalEquiv]

set_option linter.overlappingInstances false

/--
Definition of `FractionalIdeal.mk0` / `FractionalIdeal.mk0` 的定义

English:
definition FractionalIdeal.mk0
  signature: [IsDedekindDomain R]
  body: Units.mk0 I (coeIdeal_ne_zero.mpr <| mem_nonZeroDivisors_iff_ne_zero.mp I.2)
  map_one' := by simp
  map_mul' x y := by simp

@[simp]

中文:
定义 FractionalIdeal.mk0
  签名: [IsDedekindDomain R]
  定义体: Units.mk0 I (coeIdeal_ne_zero.mpr <| mem_nonZeroDivisors_iff_ne_zero.mp I.2)
  map_one' := by simp
  map_mul' x y := by simp

@[simp]

Depends on / 依赖: Units.mk0, coeIdeal_ne_zero, coeIdeal_ne_zero.mpr, mem_nonZeroDivisors_iff_ne_zero, mem_nonZeroDivisors_iff_ne_zero.mp
-/
def FractionalIdeal.mk0 [IsDedekindDomain R] :
    (Ideal R)⁰ ->* (FractionalIdeal R⁰ K)ˣ where
  toFun I := Units.mk0 I (coeIdeal_ne_zero.mpr <| mem_nonZeroDivisors_iff_ne_zero.mp I.2)
  map_one' := by simp
  map_mul' x y := by simp

@[simp]
/--
theorem `FractionalIdeal.coe_mk0` / 定理 `FractionalIdeal.coe_mk0`

English:
theorem FractionalIdeal.coe_mk0
  given: [IsDedekindDomain R] (I : (Ideal R)⁰)
  proof: rfl

中文:
定理 FractionalIdeal.coe_mk0
  条件: [IsDedekindDomain R] (I : (Ideal R)⁰)
  证明: rfl
-/
theorem FractionalIdeal.coe_mk0 [IsDedekindDomain R] (I : (Ideal R)⁰) :
    (FractionalIdeal.mk0 K I : FractionalIdeal R⁰ K) = I := rfl

/--
theorem `FractionalIdeal.canonicalEquiv_mk0` / 定理 `FractionalIdeal.canonicalEquiv_mk0`

English:
theorem FractionalIdeal.canonicalEquiv_mk0
  statement: [IsDedekindDomain R] (K' : Type*) [Field K']
  proof: by
  simp only [FractionalIdeal.coe_mk0, FractionalIdeal.canonicalEquiv_coeIdeal]

@[simp]

中文:
定理 FractionalIdeal.canonicalEquiv_mk0
  结论: [IsDedekindDomain R] (K' : 类型) [Field K']
  证明: by
  simp only [FractionalIdeal.coe_mk0, FractionalIdeal.canonicalEquiv_coeIdeal]

@[simp]

Depends on / 依赖: FractionalIdeal, FractionalIdeal.canonicalEquiv_coeIdeal, FractionalIdeal.coe_mk0, canonicalEquiv_coeIdeal, coe_mk0
-/
theorem FractionalIdeal.canonicalEquiv_mk0 [IsDedekindDomain R] (K' : Type*) [Field K']
    [Algebra R K'] [IsFractionRing R K'] (I : (Ideal R)⁰) :
    FractionalIdeal.canonicalEquiv R⁰ K K' (FractionalIdeal.mk0 K I) =
    FractionalIdeal.mk0 K' I := by
  simp only [FractionalIdeal.coe_mk0, FractionalIdeal.canonicalEquiv_coeIdeal]

@[simp]
/--
theorem `FractionalIdeal.map_canonicalEquiv_mk0` / 定理 `FractionalIdeal.map_canonicalEquiv_mk0`

English:
theorem FractionalIdeal.map_canonicalEquiv_mk0
  statement: [IsDedekindDomain R] (K' : Type*) [Field K']
  proof: Units.ext (FractionalIdeal.canonicalEquiv_mk0 K K' I)

中文:
定理 FractionalIdeal.map_canonicalEquiv_mk0
  结论: [IsDedekindDomain R] (K' : 类型) [Field K']
  证明: Units.ext (FractionalIdeal.canonicalEquiv_mk0 K K' I)

Depends on / 依赖: FractionalIdeal, FractionalIdeal.canonicalEquiv_mk0, Units.ext, canonicalEquiv_mk0
-/
theorem FractionalIdeal.map_canonicalEquiv_mk0 [IsDedekindDomain R] (K' : Type*) [Field K']
    [Algebra R K'] [IsFractionRing R K'] (I : (Ideal R)⁰) :
    Units.map (↑(FractionalIdeal.canonicalEquiv R⁰ K K')) (FractionalIdeal.mk0 K I) =
      FractionalIdeal.mk0 K' I :=
  Units.ext (FractionalIdeal.canonicalEquiv_mk0 K K' I)

/--
Definition of `ClassGroup.mk0` / `ClassGroup.mk0` 的定义

English:
definition ClassGroup.mk0
  signature: [IsDedekindDomain R]
  body: (ClassGroup.mk (FractionRing R)).comp (FractionalIdeal.mk0 (FractionRing R))

@[simp]

中文:
定义 ClassGroup.mk0
  签名: [IsDedekindDomain R]
  定义体: (ClassGroup.mk (FractionRing R)).comp (FractionalIdeal.mk0 (FractionRing R))

@[simp]

Depends on / 依赖: ClassGroup, ClassGroup.mk, FractionRing, FractionalIdeal, FractionalIdeal.mk0
-/
def ClassGroup.mk0 [IsDedekindDomain R] : (Ideal R)⁰ ->* ClassGroup R :=
  (ClassGroup.mk (FractionRing R)).comp (FractionalIdeal.mk0 (FractionRing R))

@[simp]
/--
theorem `ClassGroup.mk_mk0` / 定理 `ClassGroup.mk_mk0`

English:
theorem ClassGroup.mk_mk0
  given: [IsDedekindDomain R] (I : (Ideal R)⁰)
  proof: by
  rw [ClassGroup.mk0]; rw [MonoidHom.comp_apply]; rw [← ClassGroup.mk_canonicalEquiv K (FractionRing R)]; rw [FractionalIdeal.map_canonicalEquiv_mk0]

中文:
定理 ClassGroup.mk_mk0
  条件: [IsDedekindDomain R] (I : (Ideal R)⁰)
  证明: by
  rw [ClassGroup.mk0]; rw [MonoidHom.comp_apply]; rw [← ClassGroup.mk_canonicalEquiv K (FractionRing R)]; rw [FractionalIdeal.map_canonicalEquiv_mk0]

Depends on / 依赖: ClassGroup, ClassGroup.mk0, ClassGroup.mk_canonicalEquiv, FractionRing, FractionalIdeal, FractionalIdeal.map_canonicalEquiv_mk0, MonoidHom, MonoidHom.comp_apply, comp_apply, map_canonicalEquiv_mk0, mk_canonicalEquiv
-/
theorem ClassGroup.mk_mk0 [IsDedekindDomain R] (I : (Ideal R)⁰) :
    ClassGroup.mk K (FractionalIdeal.mk0 K I) = ClassGroup.mk0 I := by
  rw [ClassGroup.mk0]; rw [MonoidHom.comp_apply]; rw [← ClassGroup.mk_canonicalEquiv K (FractionRing R)]; rw [FractionalIdeal.map_canonicalEquiv_mk0]

/--
theorem `ClassGroup.mk0_eq_quotientMk` / 定理 `ClassGroup.mk0_eq_quotientMk`

English:
theorem ClassGroup.mk0_eq_quotientMk
  given: [IsDedekindDomain R] (I : (Ideal R)⁰)
  proof: (ClassGroup.mk_mk0 (K := FractionRing R) I).symm.trans (ClassGroup.Quot_mk_eq_mk _).symm

@[simp]

中文:
定理 ClassGroup.mk0_eq_quotientMk
  条件: [IsDedekindDomain R] (I : (Ideal R)⁰)
  证明: (ClassGroup.mk_mk0 (K := FractionRing R) I).symm.trans (ClassGroup.Quot_mk_eq_mk _).symm

@[simp]

Depends on / 依赖: ClassGroup, ClassGroup.Quot_mk_eq_mk, ClassGroup.mk_mk0, FractionRing, Quot_mk_eq_mk, mk_mk0, symm.trans
-/
theorem ClassGroup.mk0_eq_quotientMk [IsDedekindDomain R] (I : (Ideal R)⁰) :
    (ClassGroup.mk0 I : ClassGroup R) =
      QuotientGroup.mk (FractionalIdeal.mk0 (FractionRing R) I) :=
  (ClassGroup.mk_mk0 (K := FractionRing R) I).symm.trans (ClassGroup.Quot_mk_eq_mk _).symm

@[simp]
/--
theorem `ClassGroup.equiv_mk0` / 定理 `ClassGroup.equiv_mk0`

English:
theorem ClassGroup.equiv_mk0
  given: [IsDedekindDomain R] (I : (Ideal R)⁰)
  proof: by
  rw [ClassGroup.mk0]; rw [MonoidHom.comp_apply]; rw [ClassGroup.equiv_mk]
  congr 1
  simp [← Units.val_inj]

中文:
定理 ClassGroup.equiv_mk0
  条件: [IsDedekindDomain R] (I : (Ideal R)⁰)
  证明: by
  rw [ClassGroup.mk0]; rw [MonoidHom.comp_apply]; rw [ClassGroup.equiv_mk]
  congr 1
  simp [← Units.val_inj]

Depends on / 依赖: ClassGroup, ClassGroup.equiv_mk, ClassGroup.mk0, MonoidHom, MonoidHom.comp_apply, Units.val_inj, comp_apply, equiv_mk, val_inj
-/
theorem ClassGroup.equiv_mk0 [IsDedekindDomain R] (I : (Ideal R)⁰) :
    ClassGroup.equiv K (ClassGroup.mk0 I) =
      QuotientGroup.mk' (toPrincipalIdeal R K).range (FractionalIdeal.mk0 K I) := by
  rw [ClassGroup.mk0]; rw [MonoidHom.comp_apply]; rw [ClassGroup.equiv_mk]
  congr 1
  simp [← Units.val_inj]

/--
theorem `ClassGroup.mk0_eq_mk0_iff_exists_fraction_ring` / 定理 `ClassGroup.mk0_eq_mk0_iff_exists_fraction_ring`

English:
theorem ClassGroup.mk0_eq_mk0_iff_exists_fraction_ring
  given: [IsDedekindDomain R] {I J : (Ideal R)⁰}
  proof: by
  refine (ClassGroup.equiv K).injective.eq_iff.symm.trans ?_
  simp only [ClassGroup.equiv_mk0, QuotientGroup.mk'_eq_mk', mem_principal_ideals_iff,
    Units.ext_iff, Units.val_mul, FractionalIdeal.coe_mk0, exists_prop]
  constructor
  · rintro ⟨X, ⟨x, hX⟩, hx⟩
    refine ⟨x, ?_, ?_⟩
    · rintro

中文:
定理 ClassGroup.mk0_eq_mk0_iff_exists_fraction_ring
  条件: [IsDedekindDomain R] {I J : (Ideal R)⁰}
  证明: by
  refine (ClassGroup.equiv K).injective.eq_iff.symm.trans ?_
  simp only [ClassGroup.equiv_mk0, QuotientGroup.mk'_eq_mk', mem_principal_ideals_iff,
    Units.ext_iff, Units.val_mul, FractionalIdeal.coe_mk0, exists_prop]
  constructor
  · rintro ⟨X, ⟨x, hX⟩, hx⟩
    refine ⟨x, ?_, ?_⟩
    · rintro

Depends on / 依赖: ClassGroup, ClassGroup.equiv, ClassGroup.equiv_mk0, FractionalIdeal, FractionalIdeal.coe_mk0, QuotientGroup, QuotientGroup.mk, Units.ext_iff, Units.mk0, Units.val_mul, X.ne_zero.symm, _eq_mk, coe_mk0, eq_J, eq_iff, equiv_mk0, exists_prop, ext_iff, injective, injective.eq_iff.symm.trans
-/
theorem ClassGroup.mk0_eq_mk0_iff_exists_fraction_ring [IsDedekindDomain R] {I J : (Ideal R)⁰} :
    ClassGroup.mk0 I =
      ClassGroup.mk0 J ↔ exists (x : _) (_ : x != (0 : K)), spanSingleton R⁰ x * I = J := by
  refine (ClassGroup.equiv K).injective.eq_iff.symm.trans ?_
  simp only [ClassGroup.equiv_mk0, QuotientGroup.mk'_eq_mk', mem_principal_ideals_iff,
    Units.ext_iff, Units.val_mul, FractionalIdeal.coe_mk0, exists_prop]
  constructor
  · rintro ⟨X, ⟨x, hX⟩, hx⟩
    refine ⟨x, ?_, ?_⟩
    · rintro rfl; simp [X.ne_zero.symm] at hX
    simpa only [hX, mul_comm] using! hx
  · rintro ⟨x, hx, eq_J⟩
    refine ⟨Units.mk0 _ (spanSingleton_ne_zero_iff.mpr hx), ⟨x, rfl⟩, ?_⟩
    simpa only [mul_comm] using! eq_J

variable {K}

/--
theorem `ClassGroup.mk0_eq_mk0_iff` / 定理 `ClassGroup.mk0_eq_mk0_iff`

English:
theorem ClassGroup.mk0_eq_mk0_iff
  given: [IsDedekindDomain R] {I J : (Ideal R)⁰}
  proof: by
  refine (ClassGroup.mk0_eq_mk0_iff_exists_fraction_ring (FractionRing R)).trans ⟨?_, ?_⟩
  · rintro ⟨z, hz, h⟩
    obtain ⟨x, ⟨y, hy⟩, rfl⟩ := IsLocalization.exists_mk'_eq R⁰ z
    refine ⟨x, y, ?_, mem_nonZeroDivisors_iff_ne_zero.mp hy, ?_⟩
    · rintro hx; apply hz
      rw [hx]; rw [IsFractio

中文:
定理 ClassGroup.mk0_eq_mk0_iff
  条件: [IsDedekindDomain R] {I J : (Ideal R)⁰}
  证明: by
  refine (ClassGroup.mk0_eq_mk0_iff_exists_fraction_ring (FractionRing R)).trans ⟨?_, ?_⟩
  · rintro ⟨z, hz, h⟩
    obtain ⟨x, ⟨y, hy⟩, rfl⟩ := IsLocalization.exists_mk'_eq R⁰ z
    refine ⟨x, y, ?_, mem_nonZeroDivisors_iff_ne_zero.mp hy, ?_⟩
    · rintro hx; apply hz
      rw [hx]; rw [IsFractio

Depends on / 依赖: ClassGroup, ClassGroup.mk0_eq_mk0_iff_exists_fraction_ring, FractionRing, FractionalIdeal, FractionalIdeal.mk, IsFractionRing, IsFractionRing.mk, IsLocalizatio, IsLocalization, IsLocalization.exists_mk, _eq_div, _mul_coeIdeal_eq_coeIdeal, exists_mk, map_zero, mem_nonZeroDivisors_iff_ne_zero, mem_nonZeroDivisors_iff_ne_zero.mp, mem_nonZeroDivisors_iff_ne_zero.mpr, mk0_eq_mk0_iff_exists_fraction_ring, zero_div
-/
theorem ClassGroup.mk0_eq_mk0_iff [IsDedekindDomain R] {I J : (Ideal R)⁰} :
    ClassGroup.mk0 I = ClassGroup.mk0 J ↔
      exists (x y : R) (_hx : x != 0) (_hy : y != 0), Ideal.span {x} * (I : Ideal R) =
      Ideal.span {y} * J := by
  refine (ClassGroup.mk0_eq_mk0_iff_exists_fraction_ring (FractionRing R)).trans ⟨?_, ?_⟩
  · rintro ⟨z, hz, h⟩
    obtain ⟨x, ⟨y, hy⟩, rfl⟩ := IsLocalization.exists_mk'_eq R⁰ z
    refine ⟨x, y, ?_, mem_nonZeroDivisors_iff_ne_zero.mp hy, ?_⟩
    · rintro hx; apply hz
      rw [hx]; rw [IsFractionRing.mk'_eq_div]; rw [map_zero]; rw [zero_div]
    · exact (FractionalIdeal.mk'_mul_coeIdeal_eq_coeIdeal _ hy).mp h
  · rintro ⟨x, y, hx, hy, h⟩
    have hy' : y in R⁰ := mem_nonZeroDivisors_iff_ne_zero.mpr hy
    refine ⟨IsLocalization.mk' _ x ⟨y, hy'⟩, ?_, ?_⟩
    · contrapose hx
      rwa [mk'_eq_iff_eq_mul, zero_mul, ← (algebraMap R (FractionRing R)).map_zero,
        (IsFractionRing.injective R (FractionRing R)).eq_iff] at hx
    · exact (FractionalIdeal.mk'_mul_coeIdeal_eq_coeIdeal _ hy').mpr h

/--
theorem `FractionalIdeal.isUnit_num` / 定理 `FractionalIdeal.isUnit_num`

English:
theorem FractionalIdeal.isUnit_num
  given: {I : FractionalIdeal R⁰ (FractionRing R)}
  proof: by
  have hden0 : algebraMap R (FractionRing R) I.den != 0 :=
    IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors I.den.prop
  let u : (FractionRing R)ˣ := Units.mk0 (algebraMap R (FractionRing R) I.den) hden0
  have hdenUnit : IsUnit (spanSingleton R⁰ (algebraMap R (FractionRing R) I.den)) :=


中文:
定理 FractionalIdeal.isUnit_num
  条件: {I : FractionalIdeal R⁰ (FractionRing R)}
  证明: by
  have hden0 : algebraMap R (FractionRing R) I.den != 0 :=
    IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors I.den.prop
  let u : (FractionRing R)ˣ := Units.mk0 (algebraMap R (FractionRing R) I.den) hden0
  have hdenUnit : IsUnit (spanSingleton R⁰ (algebraMap R (FractionRing R) I.den)) :=


Depends on / 依赖: FractionRing, I.den, I.den.prop, IsFractionRing, IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors, IsUnit, Units.isUnit_units_mul, Units.mk0, algebraMap, den_mul_self_eq_num, hdenUnit, isUnit_units_mul, spanSingleton, toPrincipalIdeal, to_map_ne_zero_of_mem_nonZeroDivisors
-/
theorem FractionalIdeal.isUnit_num {I : FractionalIdeal R⁰ (FractionRing R)} :
    IsUnit (I.num : FractionalIdeal R⁰ (FractionRing R)) ↔ IsUnit I := by
  have hden0 : algebraMap R (FractionRing R) I.den != 0 :=
    IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors I.den.prop
  let u : (FractionRing R)ˣ := Units.mk0 (algebraMap R (FractionRing R) I.den) hden0
  have hdenUnit : IsUnit (spanSingleton R⁰ (algebraMap R (FractionRing R) I.den)) :=
    ⟨toPrincipalIdeal R (FractionRing R) u, by simp [u]⟩
  obtain ⟨c, hc⟩ := hdenUnit
  rw [← den_mul_self_eq_num']; rw [← hc]; rw [Units.isUnit_units_mul]

/--
Definition of `ClassGroup.integralRep` / `ClassGroup.integralRep` 的定义

English:
definition ClassGroup.integralRep
  signature: (I : FractionalIdeal R⁰ (FractionRing R))
  body: I.num

中文:
定义 ClassGroup.integralRep
  签名: (I : FractionalIdeal R⁰ (FractionRing R))
  定义体: I.num

Depends on / 依赖: I.num
-/
def ClassGroup.integralRep (I : FractionalIdeal R⁰ (FractionRing R)) :
    Ideal R := I.num

/--
theorem `ClassGroup.integralRep_mem_nonZeroDivisors` / 定理 `ClassGroup.integralRep_mem_nonZeroDivisors`

English:
theorem ClassGroup.integralRep_mem_nonZeroDivisors
  proof: by
  rwa [mem_nonZeroDivisors_iff_ne_zero, ne_eq, FractionalIdeal.num_eq_zero_iff]

中文:
定理 ClassGroup.integralRep_mem_nonZeroDivisors
  证明: by
  rwa [mem_nonZeroDivisors_iff_ne_zero, ne_eq, FractionalIdeal.num_eq_zero_iff]

Depends on / 依赖: FractionalIdeal, FractionalIdeal.num_eq_zero_iff, mem_nonZeroDivisors_iff_ne_zero, ne_eq, num_eq_zero_iff
-/
theorem ClassGroup.integralRep_mem_nonZeroDivisors
    {I : FractionalIdeal R⁰ (FractionRing R)} (hI : I != 0) :
    I.num in (Ideal R)⁰ := by
  rwa [mem_nonZeroDivisors_iff_ne_zero, ne_eq, FractionalIdeal.num_eq_zero_iff]

/--
theorem `ClassGroup.mk0_integralRep` / 定理 `ClassGroup.mk0_integralRep`

English:
theorem ClassGroup.mk0_integralRep
  statement: [IsDedekindDomain R]
  proof: by
  rw [← ClassGroup.mk_mk0 (FractionRing R)]; rw [eq_comm]; rw [ClassGroup.mk_eq_mk]
  have fd_ne_zero : (algebraMap R (FractionRing R)) I.1.den != 0 := by
    exact IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors (SetLike.coe_mem _)
  refine ⟨Units.mk0 (algebraMap R _ I.1.den) fd_ne_zero, ?_

中文:
定理 ClassGroup.mk0_integralRep
  结论: [IsDedekindDomain R]
  证明: by
  rw [← ClassGroup.mk_mk0 (FractionRing R)]; rw [eq_comm]; rw [ClassGroup.mk_eq_mk]
  have fd_ne_zero : (algebraMap R (FractionRing R)) I.1.den != 0 := by
    exact IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors (SetLike.coe_mem _)
  refine ⟨Units.mk0 (algebraMap R _ I.1.den) fd_ne_zero, ?_

Depends on / 依赖: ClassGroup, ClassGroup.mk_eq_mk, ClassGroup.mk_mk0, FractionRing, FractionalIdeal, FractionalIdeal.den_mul_self_eq_num, IsFractionRing, IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors, SetLike, SetLike.coe_mem, Units.ext, Units.mk0, algebraMap, coe_mem, coe_toPrincipalIdeal, den_mul_self_eq_num, eq_comm, fd_ne_zero, mk_eq_mk, mk_mk0
-/
theorem ClassGroup.mk0_integralRep [IsDedekindDomain R]
    (I : (FractionalIdeal R⁰ (FractionRing R))ˣ) :
    ClassGroup.mk0 ⟨ClassGroup.integralRep I, ClassGroup.integralRep_mem_nonZeroDivisors I.ne_zero⟩
      = ClassGroup.mk (FractionRing R) I := by
  rw [← ClassGroup.mk_mk0 (FractionRing R)]; rw [eq_comm]; rw [ClassGroup.mk_eq_mk]
  have fd_ne_zero : (algebraMap R (FractionRing R)) I.1.den != 0 := by
    exact IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors (SetLike.coe_mem _)
  refine ⟨Units.mk0 (algebraMap R _ I.1.den) fd_ne_zero, ?_⟩
  apply Units.ext
  rw [mul_comm]; rw [val_mul]; rw [coe_toPrincipalIdeal]; rw [val_mk0]
  exact FractionalIdeal.den_mul_self_eq_num' R⁰ (FractionRing R) I

/--
theorem `ClassGroup.mk0_surjective` / 定理 `ClassGroup.mk0_surjective`

English:
theorem ClassGroup.mk0_surjective
  given: [IsDedekindDomain R]
  proof: by
  rintro ⟨I⟩
  refine ⟨⟨ClassGroup.integralRep I.1, ClassGroup.integralRep_mem_nonZeroDivisors I.ne_zero⟩, ?_⟩
  rw [ClassGroup.mk0_integralRep]; rw [ClassGroup.Quot_mk_eq_mk]

中文:
定理 ClassGroup.mk0_surjective
  条件: [IsDedekindDomain R]
  证明: by
  rintro ⟨I⟩
  refine ⟨⟨ClassGroup.integralRep I.1, ClassGroup.integralRep_mem_nonZeroDivisors I.ne_zero⟩, ?_⟩
  rw [ClassGroup.mk0_integralRep]; rw [ClassGroup.Quot_mk_eq_mk]

Depends on / 依赖: ClassGroup, ClassGroup.Quot_mk_eq_mk, ClassGroup.integralRep, ClassGroup.integralRep_mem_nonZeroDivisors, ClassGroup.mk0_integralRep, I.ne_zero, Quot_mk_eq_mk, integralRep, integralRep_mem_nonZeroDivisors, mk0_integralRep, ne_zero
-/
theorem ClassGroup.mk0_surjective [IsDedekindDomain R] :
    Function.Surjective (ClassGroup.mk0 : (Ideal R)⁰ -> ClassGroup R) := by
  rintro ⟨I⟩
  refine ⟨⟨ClassGroup.integralRep I.1, ClassGroup.integralRep_mem_nonZeroDivisors I.ne_zero⟩, ?_⟩
  rw [ClassGroup.mk0_integralRep]; rw [ClassGroup.Quot_mk_eq_mk]

/--
theorem `ClassGroup.mk_eq_one_iff` / 定理 `ClassGroup.mk_eq_one_iff`

English:
theorem ClassGroup.mk_eq_one_iff
  given: {I : (FractionalIdeal R⁰ K)ˣ}
  proof: by
  rw [← (ClassGroup.equiv K).injective.eq_iff]
  simp only [equiv_mk, canonicalEquiv_self, RingEquiv.coe_mulEquiv_refl, QuotientGroup.mk'_apply,
    map_one, QuotientGroup.eq_one_iff, MonoidHom.mem_range, Units.ext_iff,
    coe_toPrincipalIdeal, coe_mapEquiv, MulEquiv.refl_apply]
  refine ⟨fun ⟨x

中文:
定理 ClassGroup.mk_eq_one_iff
  条件: {I : (FractionalIdeal R⁰ K)ˣ}
  证明: by
  rw [← (ClassGroup.equiv K).injective.eq_iff]
  simp only [equiv_mk, canonicalEquiv_self, RingEquiv.coe_mulEquiv_refl, QuotientGroup.mk'_apply,
    map_one, QuotientGroup.eq_one_iff, MonoidHom.mem_range, Units.ext_iff,
    coe_toPrincipalIdeal, coe_mapEquiv, MulEquiv.refl_apply]
  refine ⟨fun ⟨x

Depends on / 依赖: ClassGroup, ClassGroup.equiv, FractionalIdeal, IsPrincipal, MonoidHom, MonoidHom.mem_range, MulEquiv, MulEquiv.refl_apply, QuotientGroup, QuotientGroup.eq_one_iff, QuotientGroup.mk, RingEquiv, RingEquiv.coe_mulEquiv_refl, Submodule, Submodule.IsPrincipal.principal, Subtype, Subtype.coe_inj, Units.ext_iff, _apply, canonicalEquiv_self
-/
theorem ClassGroup.mk_eq_one_iff {I : (FractionalIdeal R⁰ K)ˣ} :
    ClassGroup.mk K I = 1 ↔ (I : Submodule R K).IsPrincipal := by
  rw [← (ClassGroup.equiv K).injective.eq_iff]
  simp only [equiv_mk, canonicalEquiv_self, RingEquiv.coe_mulEquiv_refl, QuotientGroup.mk'_apply,
    map_one, QuotientGroup.eq_one_iff, MonoidHom.mem_range, Units.ext_iff,
    coe_toPrincipalIdeal, coe_mapEquiv, MulEquiv.refl_apply]
  refine ⟨fun ⟨x, hx⟩ => ⟨⟨x, by rw [← hx, coe_spanSingleton]⟩⟩, ?_⟩
  intro hI
  obtain ⟨x, hx⟩ := @Submodule.IsPrincipal.principal _ _ _ _ _ _ hI
  have hx' : (I : FractionalIdeal R⁰ K) = spanSingleton R⁰ x := by
    apply Subtype.coe_injective
    simp only [val_eq_coe, hx, coe_spanSingleton]
  refine ⟨Units.mk0 x ?_, ?_⟩
  · intro x_eq; apply Units.ne_zero I; simp [hx', x_eq]
  · simp [hx']

/--
theorem `FractionalIdeal.isPrincipal.of_isPrincipal_pow_of_coprime` / 定理 `FractionalIdeal.isPrincipal.of_isPrincipal_pow_of_coprime`

English:
theorem FractionalIdeal.isPrincipal.of_isPrincipal_pow_of_coprime
  statement: [IsDedekindDomain R]
  proof: by
  obtain (rfl | ⟨u, rfl⟩) := GroupWithZero.eq_zero_or_unit I
  · simp [bot_isPrincipal]
  rw [← ClassGroup.mk_eq_one_iff]; rw [← orderOf_eq_one_iff]; rw [← Nat.dvd_one]; rw [← hn]; rw [Nat.dvd_gcd_iff]
  refine ⟨?_, orderOf_dvd_card⟩
  rw [orderOf_dvd_iff_pow_eq_one]; rw [← map_pow]; rw [ClassGro

中文:
定理 FractionalIdeal.isPrincipal.of_isPrincipal_pow_of_coprime
  结论: [IsDedekindDomain R]
  证明: by
  obtain (rfl | ⟨u, rfl⟩) := GroupWithZero.eq_zero_or_unit I
  · simp [bot_isPrincipal]
  rw [← ClassGroup.mk_eq_one_iff]; rw [← orderOf_eq_one_iff]; rw [← Nat.dvd_one]; rw [← hn]; rw [Nat.dvd_gcd_iff]
  refine ⟨?_, orderOf_dvd_card⟩
  rw [orderOf_dvd_iff_pow_eq_one]; rw [← map_pow]; rw [ClassGro

Depends on / 依赖: ClassGroup, ClassGroup.mk_eq_one_iff, GroupWithZero, GroupWithZero.eq_zero_or_unit, Nat.dvd_gcd_iff, Nat.dvd_one, bot_isPrincipal, dvd_gcd_iff, dvd_one, eq_zero_or_unit, map_pow, mk_eq_one_iff, orderOf_dvd_card, orderOf_dvd_iff_pow_eq_one, orderOf_eq_one_iff
-/
theorem FractionalIdeal.isPrincipal.of_isPrincipal_pow_of_coprime [IsDedekindDomain R]
    [Fintype (ClassGroup R)] {n : Nat} (hn : n.Coprime (Fintype.card (ClassGroup R)))
    (I : FractionalIdeal R⁰ K) (hI : ((I ^ n : FractionalIdeal R⁰ K) : Submodule R K).IsPrincipal) :
    (I : Submodule R K).IsPrincipal := by
  obtain (rfl | ⟨u, rfl⟩) := GroupWithZero.eq_zero_or_unit I
  · simp [bot_isPrincipal]
  rw [← ClassGroup.mk_eq_one_iff]; rw [← orderOf_eq_one_iff]; rw [← Nat.dvd_one]; rw [← hn]; rw [Nat.dvd_gcd_iff]
  refine ⟨?_, orderOf_dvd_card⟩
  rw [orderOf_dvd_iff_pow_eq_one]; rw [← map_pow]; rw [ClassGroup.mk_eq_one_iff]
  exact_mod_cast hI

/--
theorem `ClassGroup.isPrincipal_coeSubmodule_of_isUnit` / 定理 `ClassGroup.isPrincipal_coeSubmodule_of_isUnit`

English:
theorem ClassGroup.isPrincipal_coeSubmodule_of_isUnit
  statement: [Subsingleton (ClassGroup R)]
  proof: by
  rcases hI with ⟨I, rfl⟩
  rw [← ClassGroup.mk_eq_one_iff]; rw [Subsingleton.elim (ClassGroup.mk K I) 1]

中文:
定理 ClassGroup.isPrincipal_coeSubmodule_of_isUnit
  结论: [Subsingleton (ClassGroup R)]
  证明: by
  rcases hI with ⟨I, rfl⟩
  rw [← ClassGroup.mk_eq_one_iff]; rw [Subsingleton.elim (ClassGroup.mk K I) 1]

Depends on / 依赖: ClassGroup, ClassGroup.mk, ClassGroup.mk_eq_one_iff, Subsingleton, Subsingleton.elim, mk_eq_one_iff
-/
theorem ClassGroup.isPrincipal_coeSubmodule_of_isUnit [Subsingleton (ClassGroup R)]
    (I : FractionalIdeal R⁰ K) (hI : IsUnit I) :
    (I : Submodule R K).IsPrincipal := by
  rcases hI with ⟨I, rfl⟩
  rw [← ClassGroup.mk_eq_one_iff]; rw [Subsingleton.elim (ClassGroup.mk K I) 1]

/--
theorem `ClassGroup.isPrincipal_of_isUnit_coeIdeal` / 定理 `ClassGroup.isPrincipal_of_isUnit_coeIdeal`

English:
theorem ClassGroup.isPrincipal_of_isUnit_coeIdeal
  statement: [Subsingleton (ClassGroup R)]
  proof: by
  have hsub :
      ((I : FractionalIdeal R⁰ K) : Submodule R K).IsPrincipal :=
    ClassGroup.isPrincipal_coeSubmodule_of_isUnit (I := (I : FractionalIdeal R⁰ K)) hI
  exact (IsFractionRing.coeSubmodule_isPrincipal (R := R) (K := K) (I := I)).1
    (by simpa using hsub)

中文:
定理 ClassGroup.isPrincipal_of_isUnit_coeIdeal
  结论: [Subsingleton (ClassGroup R)]
  证明: by
  have hsub :
      ((I : FractionalIdeal R⁰ K) : Submodule R K).IsPrincipal :=
    ClassGroup.isPrincipal_coeSubmodule_of_isUnit (I := (I : FractionalIdeal R⁰ K)) hI
  exact (IsFractionRing.coeSubmodule_isPrincipal (R := R) (K := K) (I := I)).1
    (by simpa using hsub)

Depends on / 依赖: ClassGroup, ClassGroup.isPrincipal_coeSubmodule_of_isUnit, FractionalIdeal, IsFractionRing, IsFractionRing.coeSubmodule_isPrincipal, IsPrincipal, Submodule, coeSubmodule_isPrincipal, isPrincipal_coeSubmodule_of_isUnit
-/
theorem ClassGroup.isPrincipal_of_isUnit_coeIdeal [Subsingleton (ClassGroup R)]
    (I : Ideal R) (hI : IsUnit (I : FractionalIdeal R⁰ K)) :
    I.IsPrincipal := by
  have hsub :
      ((I : FractionalIdeal R⁰ K) : Submodule R K).IsPrincipal :=
    ClassGroup.isPrincipal_coeSubmodule_of_isUnit (I := (I : FractionalIdeal R⁰ K)) hI
  exact (IsFractionRing.coeSubmodule_isPrincipal (R := R) (K := K) (I := I)).1
    (by simpa using hsub)

/--
theorem `ClassGroup.mk0_eq_one_iff` / 定理 `ClassGroup.mk0_eq_one_iff`

English:
theorem ClassGroup.mk0_eq_one_iff
  given: [IsDedekindDomain R] {I : Ideal R} (hI : I in (Ideal R)⁰)
  proof: ClassGroup.mk_eq_one_iff.trans (coeSubmodule_isPrincipal R _)

中文:
定理 ClassGroup.mk0_eq_one_iff
  条件: [IsDedekindDomain R] {I : Ideal R} (hI : I in (Ideal R)⁰)
  证明: ClassGroup.mk_eq_one_iff.trans (coeSubmodule_isPrincipal R _)

Depends on / 依赖: ClassGroup, ClassGroup.mk_eq_one_iff.trans, coeSubmodule_isPrincipal, mk_eq_one_iff
-/
theorem ClassGroup.mk0_eq_one_iff [IsDedekindDomain R] {I : Ideal R} (hI : I in (Ideal R)⁰) :
    ClassGroup.mk0 ⟨I, hI⟩ = 1 ↔ I.IsPrincipal :=
  ClassGroup.mk_eq_one_iff.trans (coeSubmodule_isPrincipal R _)

/--
theorem `Ideal.IsPrincipal.of_isPrincipal_pow_of_coprime` / 定理 `Ideal.IsPrincipal.of_isPrincipal_pow_of_coprime`

English:
theorem Ideal.IsPrincipal.of_isPrincipal_pow_of_coprime
  statement: [IsDedekindDomain R]
  proof: by
  by_cases hI0 : I = 0
  · simp [hI0, bot_isPrincipal]
  rw [← ClassGroup.mk0_eq_one_iff (pow_mem (mem_nonZeroDivisors_of_ne_zero hI0) n)] at hI
  rw [← ClassGroup.mk0_eq_one_iff (mem_nonZeroDivisors_of_ne_zero hI0)]; rw [← orderOf_eq_one_iff]; rw [← Nat.dvd_one]; rw [← hn]; rw [Nat.dvd_gcd_iff]


中文:
定理 Ideal.IsPrincipal.of_isPrincipal_pow_of_coprime
  结论: [IsDedekindDomain R]
  证明: by
  by_cases hI0 : I = 0
  · simp [hI0, bot_isPrincipal]
  rw [← ClassGroup.mk0_eq_one_iff (pow_mem (mem_nonZeroDivisors_of_ne_zero hI0) n)] at hI
  rw [← ClassGroup.mk0_eq_one_iff (mem_nonZeroDivisors_of_ne_zero hI0)]; rw [← orderOf_eq_one_iff]; rw [← Nat.dvd_one]; rw [← hn]; rw [Nat.dvd_gcd_iff]


Depends on / 依赖: ClassGroup, ClassGroup.mk0_eq_one_iff, Nat.dvd_gcd_iff, Nat.dvd_one, SubmonoidClass, SubmonoidClass.mk_pow, bot_isPrincipal, dvd_gcd_iff, dvd_one, map_pow, mem_nonZeroDivisors_of_ne_zero, mk0_eq_one_iff, mk_pow, orderOf_dvd_card, orderOf_dvd_iff_pow_eq_one, orderOf_eq_one_iff, pow_mem
-/
theorem Ideal.IsPrincipal.of_isPrincipal_pow_of_coprime [IsDedekindDomain R]
    [Fintype (ClassGroup R)] {n : Nat} (hn : n.Coprime (Fintype.card (ClassGroup R)))
    {I : Ideal R} (hI : (I ^ n).IsPrincipal) : I.IsPrincipal := by
  by_cases hI0 : I = 0
  · simp [hI0, bot_isPrincipal]
  rw [← ClassGroup.mk0_eq_one_iff (pow_mem (mem_nonZeroDivisors_of_ne_zero hI0) n)] at hI
  rw [← ClassGroup.mk0_eq_one_iff (mem_nonZeroDivisors_of_ne_zero hI0)]; rw [← orderOf_eq_one_iff]; rw [← Nat.dvd_one]; rw [← hn]; rw [Nat.dvd_gcd_iff]
  refine ⟨?_, orderOf_dvd_card⟩
  rwa [orderOf_dvd_iff_pow_eq_one, ← map_pow, SubmonoidClass.mk_pow]

/--
theorem `ClassGroup.mk0_eq_mk0_inv_iff` / 定理 `ClassGroup.mk0_eq_mk0_inv_iff`

English:
theorem ClassGroup.mk0_eq_mk0_inv_iff
  given: [IsDedekindDomain R] {I J : (Ideal R)⁰}
  proof: by
  rw [eq_inv_iff_mul_eq_one]; rw [← map_mul]; rw [ClassGroup.mk0_eq_one_iff]; rw [Submodule.isPrincipal_iff]; rw [Submonoid.coe_mul]
  refine ⟨fun ⟨a, ha⟩ => ⟨a, ?_, ha⟩, fun ⟨a, _, ha⟩ => ⟨a, ha⟩⟩
  by_contra!
  rw [this]; rw [Submodule.span_zero_singleton] at ha
exact nonZeroDivisors.coe_ne_zer

中文:
定理 ClassGroup.mk0_eq_mk0_inv_iff
  条件: [IsDedekindDomain R] {I J : (Ideal R)⁰}
  证明: by
  rw [eq_inv_iff_mul_eq_one]; rw [← map_mul]; rw [ClassGroup.mk0_eq_one_iff]; rw [Submodule.isPrincipal_iff]; rw [Submonoid.coe_mul]
  refine ⟨fun ⟨a, ha⟩ => ⟨a, ?_, ha⟩, fun ⟨a, _, ha⟩ => ⟨a, ha⟩⟩
  by_contra!
  rw [this]; rw [Submodule.span_zero_singleton] at ha
exact nonZeroDivisors.coe_ne_zer

Depends on / 依赖: ClassGroup, ClassGroup.mk0_eq_one_iff, J.prop, Submodule, Submodule.isPrincipal_iff, Submodule.span_zero_singleton, Submonoid, Submonoid.coe_mul, coe_mul, coe_ne_zero, eq_inv_iff_mul_eq_one, isPrincipal_iff, map_mul, mk0_eq_one_iff, nonZeroDivisors, nonZeroDivisors.coe_ne_zero, span_zero_singleton
-/
theorem ClassGroup.mk0_eq_mk0_inv_iff [IsDedekindDomain R] {I J : (Ideal R)⁰} :
    ClassGroup.mk0 I = (ClassGroup.mk0 J)⁻¹ ↔
      exists x != (0 : R), I * J = Ideal.span {x} := by
  rw [eq_inv_iff_mul_eq_one]; rw [← map_mul]; rw [ClassGroup.mk0_eq_one_iff]; rw [Submodule.isPrincipal_iff]; rw [Submonoid.coe_mul]
  refine ⟨fun ⟨a, ha⟩ => ⟨a, ?_, ha⟩, fun ⟨a, _, ha⟩ => ⟨a, ha⟩⟩
  by_contra!
  rw [this]; rw [Submodule.span_zero_singleton] at ha
exact nonZeroDivisors.coe_ne_zero _ J.prop.2 _ ha

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [IsPrincipalIdealRing
  signature: R] : Fintype (ClassGroup R) where
  body: {1}
  complete := by
    refine ClassGroup.induction (R := R) (FractionRing R) (fun I => ?_)
    rw [Finset.mem_singleton]
    exact ClassGroup.mk_eq_one_iff.mpr (I : FractionalIdeal R⁰ (FractionRing R)).isPrincipal

中文:
实例 [IsPrincipalIdealRing
  签名: R] : Fintype (ClassGroup R) where
  定义体: {1}
  complete := by
    refine ClassGroup.induction (R := R) (FractionRing R) (fun I => ?_)
    rw [Finset.mem_singleton]
    exact ClassGroup.mk_eq_one_iff.mpr (I : FractionalIdeal R⁰ (FractionRing R)).isPrincipal
-/
instance [IsPrincipalIdealRing R] : Fintype (ClassGroup R) where
  elems := {1}
  complete := by
    refine ClassGroup.induction (R := R) (FractionRing R) (fun I => ?_)
    rw [Finset.mem_singleton]
    exact ClassGroup.mk_eq_one_iff.mpr (I : FractionalIdeal R⁰ (FractionRing R)).isPrincipal

/--
theorem `card_classGroup_eq_one` / 定理 `card_classGroup_eq_one`

English:
theorem card_classGroup_eq_one
  given: [IsPrincipalIdealRing R]
  statement: Fintype.card (ClassGroup R) = 1
  proof: by
  rw [Fintype.card_eq_one_iff]
  use 1
  refine ClassGroup.induction (R := R) (FractionRing R) (fun I => ?_)
  exact ClassGroup.mk_eq_one_iff.mpr (I : FractionalIdeal R⁰ (FractionRing R)).isPrincipal

中文:
定理 card_classGroup_eq_one
  条件: [IsPrincipalIdealRing R]
  结论: Fintype.card (ClassGroup R) = 1
  证明: by
  rw [Fintype.card_eq_one_iff]
  use 1
  refine ClassGroup.induction (R := R) (FractionRing R) (fun I => ?_)
  exact ClassGroup.mk_eq_one_iff.mpr (I : FractionalIdeal R⁰ (FractionRing R)).isPrincipal

Depends on / 依赖: ClassGroup, ClassGroup.induction, ClassGroup.mk_eq_one_iff.mpr, Fintype, Fintype.card_eq_one_iff, FractionRing, FractionalIdeal, card_eq_one_iff, isPrincipal, mk_eq_one_iff
-/
theorem card_classGroup_eq_one [IsPrincipalIdealRing R] : Fintype.card (ClassGroup R) = 1 := by
  rw [Fintype.card_eq_one_iff]
  use 1
  refine ClassGroup.induction (R := R) (FractionRing R) (fun I => ?_)
  exact ClassGroup.mk_eq_one_iff.mpr (I : FractionalIdeal R⁰ (FractionRing R)).isPrincipal

/--
theorem `card_classGroup_eq_one_iff` / 定理 `card_classGroup_eq_one_iff`

English:
theorem card_classGroup_eq_one_iff
  given: [IsDedekindDomain R] [Fintype (ClassGroup R)]
  proof: by
  constructor; swap; · intros; convert! card_classGroup_eq_one (R := R)
  rw [Fintype.card_eq_one_iff]
  rintro ⟨I, hI⟩
  have eq_one : forall J : ClassGroup R, J = 1 := fun J => (hI J).trans (hI 1).symm
  refine ⟨fun I => ?_⟩
  by_cases hI : I = ⊥
  · rw [hI]; exact bot_isPrincipal
  · exact (Cl

中文:
定理 card_classGroup_eq_one_iff
  条件: [IsDedekindDomain R] [Fintype (ClassGroup R)]
  证明: by
  constructor; swap; · intros; convert! card_classGroup_eq_one (R := R)
  rw [Fintype.card_eq_one_iff]
  rintro ⟨I, hI⟩
  have eq_one : forall J : ClassGroup R, J = 1 := fun J => (hI J).trans (hI 1).symm
  refine ⟨fun I => ?_⟩
  by_cases hI : I = ⊥
  · rw [hI]; exact bot_isPrincipal
  · exact (Cl

Depends on / 依赖: ClassGroup, ClassGroup.mk0_eq_one_iff, Fintype, Fintype.card_eq_one_iff, bot_isPrincipal, card_classGroup_eq_one, card_eq_one_iff, convert, eq_one, intros, mem_nonZeroDivisors_iff_ne_zero, mem_nonZeroDivisors_iff_ne_zero.mpr, mk0_eq_one_iff
-/
theorem card_classGroup_eq_one_iff [IsDedekindDomain R] [Fintype (ClassGroup R)] :
    Fintype.card (ClassGroup R) = 1 ↔ IsPrincipalIdealRing R := by
  constructor; swap; · intros; convert! card_classGroup_eq_one (R := R)
  rw [Fintype.card_eq_one_iff]
  rintro ⟨I, hI⟩
  have eq_one : forall J : ClassGroup R, J = 1 := fun J => (hI J).trans (hI 1).symm
  refine ⟨fun I => ?_⟩
  by_cases hI : I = ⊥
  · rw [hI]; exact bot_isPrincipal
  · exact (ClassGroup.mk0_eq_one_iff (mem_nonZeroDivisors_iff_ne_zero.mpr hI)).mp (eq_one _)

section MulEquiv

/--
theorem `FractionalIdeal.map_ringEquivOfRingEquiv_toPrincipalIdeal` / 定理 `FractionalIdeal.map_ringEquivOfRingEquiv_toPrincipalIdeal`

English:
theorem FractionalIdeal.map_ringEquivOfRingEquiv_toPrincipalIdeal
  statement: {S L : Type*} [CommRing S]
  proof: by
  ext I
  simp only [MulEquiv.toMonoidHom_eq_coe, Subgroup.mem_map, MonoidHom.mem_range,
    toPrincipalIdeal_eq_iff, MonoidHom.coe_coe]
  refine ⟨fun ⟨u, ⟨v, huv⟩, hu⟩ => ?_, fun ⟨u, hu⟩ => ?_⟩
  · use Units.map (IsFractionRing.ringEquivOfRingEquiv f (K := K)
      (L := L)).toRingHom v
    rw [

中文:
定理 FractionalIdeal.map_ringEquivOfRingEquiv_toPrincipalIdeal
  结论: {S L : 类型} [CommRing S]
  证明: by
  ext I
  simp only [MulEquiv.toMonoidHom_eq_coe, Subgroup.mem_map, MonoidHom.mem_range,
    toPrincipalIdeal_eq_iff, MonoidHom.coe_coe]
  refine ⟨fun ⟨u, ⟨v, huv⟩, hu⟩ => ?_, fun ⟨u, hu⟩ => ?_⟩
  · use Units.map (IsFractionRing.ringEquivOfRingEquiv f (K := K)
      (L := L)).toRingHom v
    rw [

Depends on / 依赖: FractionalIdeal, FractionalIdeal.ringEquivOfRingEquiv_spanSingleton, IsFractionRing, IsFractionRing.ringEquivOfRingEquiv, MonoidHom, MonoidHom.coe_coe, MonoidHom.mem_range, MulEquiv, MulEquiv.toMonoidHom_eq_coe, RingEquiv, RingEquiv.coe_toMulEquiv, RingEquiv.toRingHom_eq_coe, RingHom, RingHom.coe_coe, Subgroup, Subgroup.mem_map, Units.coe_map, Units.coe_mapEquiv, Units.map, Units.mapEq
-/
theorem FractionalIdeal.map_ringEquivOfRingEquiv_toPrincipalIdeal {S L : Type*} [CommRing S]
    [IsDomain S] [Field L] [Algebra S L] [IsFractionRing S L] (f : R ≃+* S) :
  Subgroup.map ((Units.mapEquiv (ringEquivOfRingEquiv K L f))).toMonoidHom
    (toPrincipalIdeal R K).range = (toPrincipalIdeal S L).range := by
  ext I
  simp only [MulEquiv.toMonoidHom_eq_coe, Subgroup.mem_map, MonoidHom.mem_range,
    toPrincipalIdeal_eq_iff, MonoidHom.coe_coe]
  refine ⟨fun ⟨u, ⟨v, huv⟩, hu⟩ => ?_, fun ⟨u, hu⟩ => ?_⟩
  · use Units.map (IsFractionRing.ringEquivOfRingEquiv f (K := K)
      (L := L)).toRingHom v
    rw [← hu]
    simp only [RingEquiv.toRingHom_eq_coe, Units.coe_map, MonoidHom.coe_coe, RingHom.coe_coe,
      Units.coe_mapEquiv, ← huv, RingEquiv.coe_toMulEquiv]
    rw [FractionalIdeal.ringEquivOfRingEquiv_spanSingleton]
  · use Units.mapEquiv (FractionalIdeal.ringEquivOfRingEquiv _ _ f).symm.toMulEquiv I
    refine ⟨?_, by simp [← Units.val_inj]⟩
    · use Units.map (IsFractionRing.ringEquivOfRingEquiv f (K := K)
        (L := L)).symm.toRingHom u
      simp only [IsFractionRing.ringEquivOfRingEquiv_symm, RingEquiv.toRingHom_eq_coe,
        Units.coe_map, MonoidHom.coe_coe, RingHom.coe_coe, RingEquiv.toMulEquiv_eq_coe,
        RingEquiv.coe_toMulEquiv_symm, Units.coe_mapEquiv]
      rw [← FractionalIdeal.ringEquivOfRingEquiv_spanSingleton]; rw [← FractionalIdeal.ringEquivOfRingEquiv_symm_eq]; rw [hu]
      rfl

#adaptation_note
/-- `respectTransparency.types true` changes the auto-generated lemmas' signature -/
set_option backward.isDefEq.respectTransparency.types false in
/-- A ring isomorphism `R ≃+* R'` induces an isomorphism on their class groups. -/
@[simps!]
/--
Definition of `ClassGroup.mulEquiv` / `ClassGroup.mulEquiv` 的定义

English:
definition ClassGroup.mulEquiv
  signature: {R' : Type*} [CommRing R'] [IsDomain R'] (g : R ≃+* R')
  body: (ClassGroup.equiv (R := R) (FractionRing R)).trans
    ((QuotientGroup.congr (toPrincipalIdeal R (FractionRing R)).range
        (toPrincipalIdeal R' (FractionRing R')).range
        (Units.mapEquiv (FractionalIdeal.ringEquivOfRingEquiv (FractionRing R) (FractionRing R') g))
        (FractionalIdeal

中文:
定义 ClassGroup.mulEquiv
  签名: {R' : 类型} [CommRing R'] [IsDomain R'] (g : R ≃+* R')
  定义体: (ClassGroup.equiv (R := R) (FractionRing R)).trans
    ((QuotientGroup.congr (toPrincipalIdeal R (FractionRing R)).range
        (toPrincipalIdeal R' (FractionRing R')).range
        (Units.mapEquiv (FractionalIdeal.ringEquivOfRingEquiv (FractionRing R) (FractionRing R') g))
        (FractionalIdeal

Depends on / 依赖: ClassGroup, ClassGroup.equiv, FractionRing, FractionalIdeal, FractionalIdeal.map_ringEquivOfRingEquiv_toPrincipalIdeal, FractionalIdeal.ringEquivOfRingEquiv, QuotientGroup, QuotientGroup.congr, Units.mapEquiv, mapEquiv, map_ringEquivOfRingEquiv_toPrincipalIdeal, ringEquivOfRingEquiv, toPrincipalIdeal
-/
noncomputable def ClassGroup.mulEquiv {R' : Type*} [CommRing R'] [IsDomain R'] (g : R ≃+* R') :
    ClassGroup R ≃* ClassGroup R' :=
  (ClassGroup.equiv (R := R) (FractionRing R)).trans
    ((QuotientGroup.congr (toPrincipalIdeal R (FractionRing R)).range
        (toPrincipalIdeal R' (FractionRing R')).range
        (Units.mapEquiv (FractionalIdeal.ringEquivOfRingEquiv (FractionRing R) (FractionRing R') g))
        (FractionalIdeal.map_ringEquivOfRingEquiv_toPrincipalIdeal g)).trans
      (ClassGroup.equiv (FractionRing R')).symm)

end MulEquiv
