/-
Copyright (c) 2024 Jireh Loreaux. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jireh Loreaux
-/
module

public import Mathlib.Topology.Algebra.Monoid

/-! # Approximate units

An *approximate unit* is a filter `l` such that multiplication on the left (or right) by `m : α`
tends to `𝓝 m` along the filter, and additionally `l ≠ ⊥`.

Examples of approximate units include:

- The trivial approximate unit `pure 1` in a normed ring.
- `𝓝 1` or `𝓝[≠] 1` in a normed ring (note that the latter is disjoint from `pure 1`).
- In a C⋆-algebra, the filter generated by the sections `fun a ↦ {x | a ≤ x} ∩ closedBall 0 1`,
  where `a` ranges over the positive elements of norm strictly less than 1.
-/

public section

open Filter Topology

/-- An *approximate unit* is a proper filter (i.e., `≠ ⊥`) such that multiplication on the left
(and separately on the right) by `m : α` tends to `𝓝 m` along the filter. -/
/-
**Filter.IsApproximateUnit** 是 Mathlib 中的一个归纳类型，位于命名空间 `Filter`。
形式化陈述：{α : Type u_1} → [TopologicalSpace α] → [Mul α] → Filter α → Prop
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
An *approximate unit* is a proper filter (i.e., `≠ ⊥`) such that multiplication 
on the left
(and separately on the right) by `m : α` tends to `𝓝 m` along the filter.
-/
structure Filter.IsApproximateUnit {α : Type*} [TopologicalSpace α] [Mul α]
    (l : Filter α) : Prop where
  /-- Multiplication on the left by `m` tends to `𝓝 m` along the filter. -/
  tendsto_mul_left m : Tendsto (m * ·) l (𝓝 m)
  /-- Multiplication on the right by `m` tends to `𝓝 m` along the filter. -/
  tendsto_mul_right m : Tendsto (· * m) l (𝓝 m)
  /-- The filter is not `⊥`. -/
  protected [neBot : NeBot l]

namespace Filter.IsApproximateUnit

section TopologicalMonoid

variable {α : Type*} [TopologicalSpace α] [MulOneClass α]

variable (α) in
/-- A unital magma with a topology and bornology has the trivial approximate unit `pure 1`. -/
/-
**Filter.IsApproximateUnit.pure_one** 是 Mathlib 中的一个引理，位于命名空间 `Filter.IsApproxim
ateUnit`。
形式化陈述：pure_one : IsApproximateUnit (pure (1 : α)) where tendsto_mul_left m
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `mul_one`：mul_one : forall a : M, a * 1 = a
· 使用定理 `tendsto_pure_nhds`：tendsto_pure_nhds (f : α -> X) (a : α) : Tendsto f (p
ure a) (𝓝 (f a))
· 使用定理 `one_mul`：one_mul : forall a : M, 1 * a = a

--- 原说明 ---
A unital magma with a topology and bornology has the trivial approximate unit `p
ure 1`.
-/
lemma pure_one : IsApproximateUnit (pure (1 : α)) where
  tendsto_mul_left m := by simpa using tendsto_pure_nhds (m * ·) (1 : α)
  tendsto_mul_right m := by simpa using tendsto_pure_nhds (· * m) (1 : α)

/-- If `l` is an approximate unit and `⊥ < l' ≤ l`, then `l'` is also an approximate unit. -/
/-
**Filter.IsApproximateUnit.mono** 是 Mathlib 中的一个引理，位于命名空间 `Filter.IsApproximateU
nit`。
形式化陈述：mono {l l' : Filter α} (hl : l.IsApproximateUnit) (hle : l' <= l) [hl' : l
'.NeBot] : l'.IsApproximateUnit where .mono_left hle tendsto_mul_left m
参数：hl : l.IsApproximateUnit；hle : l' <= l。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Filter.Tendsto.mono_left`：∀ {α : Type u_1} {β : Type u_2} {f : α → β} {x
 y : Filter α} {z : Filter β},   Filter.Tendsto f x z → y ≤ x → Filter.Tendsto f
 y z
· 使用定理 `Filter.IsApproximateUnit.tendsto_mul_left`：∀ {α : Type u_1} [inst : Topo
logicalSpace α] [inst_1 : Mul α] {l : Filter α},   l.IsApproximateUnit → ∀ (m : 
α), Filter.Tendsto (fun x => m …
· 使用定理 `Filter.IsApproximateUnit.tendsto_mul_right`：∀ {α : Type u_1} [inst : Top
ologicalSpace α] [inst_1 : Mul α] {l : Filter α},   l.IsApproximateUnit → ∀ (m :
 α), Filter.Tendsto (fun x => x …

--- 原说明 ---
If `l` is an approximate unit and `⊥ < l' ≤ l`, then `l'` is also an approximate
 unit.
-/
lemma mono {l l' : Filter α} (hl : l.IsApproximateUnit) (hle : l' ≤ l) [hl' : l'.NeBot] :
    l'.IsApproximateUnit where
  tendsto_mul_left m := hl.tendsto_mul_left m |>.mono_left hle
  tendsto_mul_right m := hl.tendsto_mul_right m |>.mono_left hle

variable (α) in
/-- In a topological unital magma, `𝓝 1` is an approximate unit. -/
/-
**Filter.IsApproximateUnit.nhds_one** 是 Mathlib 中的一个引理，位于命名空间 `Filter.IsApproxim
ateUnit`。
形式化陈述：nhds_one [SeparatelyContinuousMul α] : IsApproximateUnit (𝓝 (1 : α)) where
 .const_mul m tendsto_mul_left m
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `mul_one`：mul_one : forall a : M, a * 1 = a
· 使用定理 `Filter.Tendsto.const_mul`：Filter.Tendsto.const_mul {α : Type*} {f : α ->
 M} {x : Filter α} {a : M} (b : M) (hf : Tendsto f x (𝓝 a)) : Tendsto (b * f ·) 
x (𝓝 (b * a))
· 使用定理 `Filter.tendsto_id`：tendsto_id {x : Filter α} : Tendsto id x x
· 使用定理 `one_mul`：one_mul : forall a : M, 1 * a = a
· 使用定理 `Filter.Tendsto.mul_const`：Filter.Tendsto.mul_const {α : Type*} {f : α ->
 M} {x : Filter α} {a : M} (b : M) (hf : Tendsto f x (𝓝 a)) : Tendsto (f · * b) 
x (𝓝 (a * b))

--- 原说明 ---
In a topological unital magma, `𝓝 1` is an approximate unit.
-/
lemma nhds_one [SeparatelyContinuousMul α] : IsApproximateUnit (𝓝 (1 : α)) where
  tendsto_mul_left m := by simpa using tendsto_id (x := 𝓝 1) |>.const_mul m
  tendsto_mul_right m := by simpa using tendsto_id (x := 𝓝 1) |>.mul_const m

/-- In a topological unital magma, `𝓝 1` is the largest approximate unit. -/
/-
**Filter.IsApproximateUnit.iff_neBot_and_le_nhds_one** 是 Mathlib 中的一个引理，位于命名空间 `
Filter.IsApproximateUnit`。
形式化陈述：iff_neBot_and_le_nhds_one [SeparatelyContinuousMul α] {l : Filter α} : IsA
pproximateUnit l ↔ l.NeBot ∧ l <= 𝓝 1
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Filter.IsApproximateUnit.neBot`：∀ {α : Type u_1} [inst : TopologicalSpac
e α] [inst_1 : Mul α] {l : Filter α}, l.IsApproximateUnit → l.NeBot
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `funext`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, (∀ (x : α
), f x = g x) → f = g
· 使用定理 `one_mul`：one_mul : forall a : M, 1 * a = a
· 使用定理 `Filter.IsApproximateUnit.tendsto_mul_left`：∀ {α : Type u_1} [inst : Topo
logicalSpace α] [inst_1 : Mul α] {l : Filter α},   l.IsApproximateUnit → ∀ (m : 
α), Filter.Tendsto (fun x => m …
· 使用引理 `Filter.IsApproximateUnit.mono`：mono {l l' : Filter α} (hl : l.IsApproxim
ateUnit) (hle : l' <= l) [hl' : l'.NeBot] : l'.IsApproximateUnit where .mono_lef
t hle tendsto_mul_l…
· 使用引理 `Filter.IsApproximateUnit.nhds_one`：nhds_one [SeparatelyContinuousMul α] 
: IsApproximateUnit (𝓝 (1 : α)) where .const_mul m tendsto_mul_left m

--- 原说明 ---
In a topological unital magma, `𝓝 1` is the largest approximate unit.
-/
lemma iff_neBot_and_le_nhds_one [SeparatelyContinuousMul α] {l : Filter α} :
    IsApproximateUnit l ↔ l.NeBot ∧ l ≤ 𝓝 1 :=
  ⟨fun hl ↦ ⟨hl.neBot, by simpa using! hl.tendsto_mul_left 1⟩,
    And.elim fun _ hl ↦ nhds_one α |>.mono hl⟩

/-- In a topological unital magma, `𝓝 1` is the largest approximate unit. -/
/-
**Filter.IsApproximateUnit.iff_le_nhds_one** 是 Mathlib 中的一个引理，位于命名空间 `Filter.IsA
pproximateUnit`。
形式化陈述：iff_le_nhds_one [SeparatelyContinuousMul α] {l : Filter α} [l.NeBot] : IsA
pproximateUnit l ↔ l <= 𝓝 1
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂

--- 原说明 ---
In a topological unital magma, `𝓝 1` is the largest approximate unit.
-/
lemma iff_le_nhds_one [SeparatelyContinuousMul α] {l : Filter α} [l.NeBot] :
    IsApproximateUnit l ↔ l ≤ 𝓝 1 := by
  simpa [iff_neBot_and_le_nhds_one] using fun _ ↦ ‹_›


end TopologicalMonoid

end Filter.IsApproximateUnit

