/-
Copyright (c) 2026 Yury Kudryashov. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yury Kudryashov, Gemini CLI
-/
module

public import Mathlib.Topology.Defs.Induced

/-!
# Basic lemmas and instances about the `WithTopology` type synonym

`WithTopology X t` is a copy of `X` equipped with the topology `t`.
This is useful for providing multiple topologies on the same type
without causing instance conflicts.

In this file we setup basic API about this type
and transfer instances (basic, order) from `X` to `WithTopology X t`.

## Implementation notes

The pattern here is the same one as is used by `Lex` for order structures
and `WithLp` for metric structures.
-/

public section

variable {X : Type*} (t : TopologicalSpace X)

namespace WithTopology

/-
**WithTopology.ofTopology_toTopology** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：ofTopology_toTopology (x : X) : ofTopology (toTopology t x) = x
参数：x : X。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma ofTopology_toTopology (x : X) : ofTopology (toTopology t x) = x := rfl

@[simp]
/-
**WithTopology.toTopology_ofTopology** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：toTopology_ofTopology (x : WithTopology X t) : toTopology t (ofTopology x)
 = x
参数：x : WithTopology X t。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma toTopology_ofTopology (x : WithTopology X t) :
  toTopology t (ofTopology x) = x := rfl
/-
**WithTopology.ofTopology_surjective** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：ofTopology_surjective : Function.Surjective (ofTopology (t
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Function.RightInverse.surjective`：∀ {α : Sort u_1} {β : Sort u_2} {f : α
 → β} {g : β → α}, Function.RightInverse g f → Function.Surjective f
· 使用引理 `WithTopology.ofTopology_toTopology`：ofTopology_toTopology (x : X) : ofTo
pology (toTopology t x) = x
-/
lemma ofTopology_surjective : Function.Surjective (ofTopology (t := t)) :=
  Function.RightInverse.surjective <| ofTopology_toTopology _
/-
**WithTopology.toTopology_surjective** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：toTopology_surjective : Function.Surjective (toTopology t)
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Function.RightInverse.surjective`：∀ {α : Sort u_1} {β : Sort u_2} {f : α
 → β} {g : β → α}, Function.RightInverse g f → Function.Surjective f
· 使用引理 `WithTopology.toTopology_ofTopology`：toTopology_ofTopology (x : WithTopol
ogy X t) : toTopology t (ofTopology x) = x
-/
lemma toTopology_surjective : Function.Surjective (toTopology t) :=
  Function.RightInverse.surjective <| toTopology_ofTopology _
/-
**WithTopology.ofTopology_injective** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：ofTopology_injective : Function.Injective (ofTopology (t
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Function.LeftInverse.injective`：∀ {α : Sort u_1} {β : Sort u_2} {g : β →
 α} {f : α → β}, Function.LeftInverse g f → Function.Injective f
· 使用引理 `WithTopology.toTopology_ofTopology`：toTopology_ofTopology (x : WithTopol
ogy X t) : toTopology t (ofTopology x) = x
-/
lemma ofTopology_injective : Function.Injective (ofTopology (t := t)) :=
  Function.LeftInverse.injective <| toTopology_ofTopology _
/-
**WithTopology.toTopology_injective** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：toTopology_injective : Function.Injective (toTopology t)
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Function.LeftInverse.injective`：∀ {α : Sort u_1} {β : Sort u_2} {g : β →
 α} {f : α → β}, Function.LeftInverse g f → Function.Injective f
· 使用引理 `WithTopology.ofTopology_toTopology`：ofTopology_toTopology (x : X) : ofTo
pology (toTopology t x) = x
-/
lemma toTopology_injective : Function.Injective (toTopology t) :=
  Function.LeftInverse.injective <| ofTopology_toTopology _
/-
**WithTopology.ofTopology_bijective** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：ofTopology_bijective : Function.Bijective (ofTopology (t
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `WithTopology.ofTopology_injective`：ofTopology_injective : Function.Injec
tive (ofTopology (t
· 使用引理 `WithTopology.ofTopology_surjective`：ofTopology_surjective : Function.Sur
jective (ofTopology (t
-/
lemma ofTopology_bijective : Function.Bijective (ofTopology (t := t)) :=
  ⟨ofTopology_injective t, ofTopology_surjective t⟩
/-
**WithTopology.toTopology_bijective** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：toTopology_bijective : Function.Bijective (toTopology t)
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `WithTopology.toTopology_injective`：toTopology_injective : Function.Injec
tive (toTopology t)
· 使用引理 `WithTopology.toTopology_surjective`：toTopology_surjective : Function.Sur
jective (toTopology t)
-/
lemma toTopology_bijective : Function.Bijective (toTopology t) :=
  ⟨toTopology_injective t, toTopology_surjective t⟩

/-- Injectivity lemma for the constructor `toTopology t`.

It is not marked as `@[simp]`, because its autogenerated version
is already in the default `simp` set. -/
/-
**WithTopology.toTopology_inj** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：toTopology_inj {x y : X} : toTopology t x = toTopology t y ↔ x = y
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Function.Injective.eq_iff`：∀ {α : Sort u_1} {β : Sort u_2} {f : α → β}, 
Function.Injective f → ∀ {a b : α}, f a = f b ↔ a = b
· 使用引理 `WithTopology.toTopology_injective`：toTopology_injective : Function.Injec
tive (toTopology t)

--- 原说明 ---
Injectivity lemma for the constructor `toTopology t`.

It is not marked as `@[simp]`, because its autogenerated version
is already in the default `simp` set.
-/
lemma toTopology_inj {x y : X} : toTopology t x = toTopology t y ↔ x = y :=
  (toTopology_injective t).eq_iff
/-
**WithTopology.ofTopology_inj** 是 Mathlib 中的一个定理，位于命名空间 `WithTopology`。
形式化陈述：∀ {X : Type u_1} (t : TopologicalSpace X) {x y : WithTopology X t}, x.ofTo
pology = y.ofTopology ↔ x = y
参数：t : TopologicalSpace X。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Function.Injective.eq_iff`：∀ {α : Sort u_1} {β : Sort u_2} {f : α → β}, 
Function.Injective f → ∀ {a b : α}, f a = f b ↔ a = b
· 使用引理 `WithTopology.ofTopology_injective`：ofTopology_injective : Function.Injec
tive (ofTopology (t
-/
@[simp] lemma ofTopology_inj {x y : WithTopology X t} : ofTopology x = ofTopology y ↔ x = y :=
  (ofTopology_injective t).eq_iff

open Topology
/-
**WithTopology.isOpen_iff** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：isOpen_iff {s : Set (WithTopology X t)} : IsOpen s ↔ IsOpen[t] (toTopology
 t ⁻¹' s)
参数：WithTopology X t。
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.rfl`：∀ {a : Prop}, a ↔ a
-/
lemma isOpen_iff {s : Set (WithTopology X t)} :
    IsOpen s ↔ IsOpen[t] (toTopology t ⁻¹' s) :=
  .rfl
/-
**WithTopology.isClosed_iff** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：isClosed_iff {s : Set (WithTopology X t)} : IsClosed s ↔ IsClosed[t] (toTo
pology t ⁻¹' s)
参数：WithTopology X t。
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `iff_self`：∀ (p : Prop), (p ↔ p) = True
-/
lemma isClosed_iff {s : Set (WithTopology X t)} :
    IsClosed s ↔ IsClosed[t] (toTopology t ⁻¹' s) := by
  simp [← isOpen_compl_iff, isOpen_iff]

/-- If `X` is equipped with topology `t`, the map `X → WithTopology X t` is continuous. -/
/-
**WithTopology.continuous_toTopology** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：continuous_toTopology : Continuous[t, _] (toTopology t)
该定理/引理描述了相关对象所满足的性质。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
If `X` is equipped with topology `t`, the map `X → WithTopology X t` is continuo
us.
-/
lemma continuous_toTopology : Continuous[t, _] (toTopology t) :=
  ⟨fun _ ↦ (·)⟩

/-- If `X` is equipped with topology `t`, the map `WithTopology X t → X` is continuous. -/
/-
**WithTopology.continuous_ofTopology** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：continuous_ofTopology : Continuous[_, t] (ofTopology (t
该定理/引理描述了相关对象所满足的性质。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
If `X` is equipped with topology `t`, the map `WithTopology X t → X` is continuo
us.
-/
lemma continuous_ofTopology : Continuous[_, t] (ofTopology (t := t)) :=
  ⟨fun _ ↦ (·)⟩

/-! ### Set-theoretic lemmas -/

open Set

/-
**WithTopology.image_ofTopology** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：image_ofTopology (s : Set (WithTopology X t)) : ofTopology '' s = toTopolo
gy t ⁻¹' s
参数：s : Set (WithTopology X t)。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `Equiv.image_symm_eq_preimage`：image_symm_eq_preimage (e : α ≃ β) (s : Se
t β) : e.symm '' s = e ⁻¹' s
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s
-/
lemma image_ofTopology (s : Set (WithTopology X t)) : ofTopology '' s = toTopology t ⁻¹' s :=
  WithTopology.equiv X t |>.symm.image_symm_eq_preimage _
/-
**WithTopology.preimage_toTopology** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：preimage_toTopology (s : Set (WithTopology X t)) : toTopology t ⁻¹' s = of
Topology '' s
参数：s : Set (WithTopology X t)。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用引理 `WithTopology.image_ofTopology`：image_ofTopology (s : Set (WithTopology X
 t)) : ofTopology '' s = toTopology t ⁻¹' s
-/
lemma preimage_toTopology (s : Set (WithTopology X t)) : toTopology t ⁻¹' s = ofTopology '' s :=
  (image_ofTopology t s).symm
/-
**WithTopology.image_toTopology** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：image_toTopology (s : Set X) : toTopology t '' s = ofTopology ⁻¹' s
参数：s : Set X。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `Equiv.image_eq_preimage_symm`：image_eq_preimage_symm (e : α ≃ β) (s : Se
t α) : e '' s = e.symm ⁻¹' s
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s
-/
lemma image_toTopology (s : Set X) : toTopology t '' s = ofTopology ⁻¹' s :=
  WithTopology.equiv X t |>.symm.image_eq_preimage_symm _
/-
**WithTopology.preimage_ofTopology** 是 Mathlib 中的一个引理，位于命名空间 `WithTopology`。
形式化陈述：preimage_ofTopology (s : Set X) : ofTopology ⁻¹' s = toTopology t '' s
参数：s : Set X。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用引理 `WithTopology.image_toTopology`：image_toTopology (s : Set X) : toTopology
 t '' s = ofTopology ⁻¹' s
-/
lemma preimage_ofTopology (s : Set X) : ofTopology ⁻¹' s = toTopology t '' s :=
  (image_toTopology t s).symm

/-!
### Instance transfers

In this section we transfer some instances from `X` to `WithTopology X t`.
-/

/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
### Instance transfers

In this section we transfer some instances from `X` to `WithTopology X t`.
-/
instance [Nonempty X] : Nonempty (WithTopology X t) :=
  (WithTopology.equiv X t).nonempty
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Inhabited X] : Inhabited (WithTopology X t) :=
  ⟨toTopology t default⟩
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Subsingleton X] : Subsingleton (WithTopology X t) :=
  (WithTopology.equiv X t).subsingleton
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Unique X] : Unique (WithTopology X t) := .mk' _
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Finite X] : Finite (WithTopology X t) := .of_equiv _ (WithTopology.equiv X t).symm
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Infinite X] : Infinite (WithTopology X t) := .of_injective _ <| toTopology_injective _
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Fintype X] : Fintype (WithTopology X t) :=
  .ofBijective (.toTopology t) (toTopology_bijective t)

deriving instance DecidableEq for WithTopology
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [LE X] : LE (WithTopology X t) where
  le x y := ofTopology x ≤ ofTopology y
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [LT X] : LT (WithTopology X t) where
  lt x y := ofTopology x < ofTopology y

-- TODO: `inferInstance` works here, but it shouldn't
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [LE X] [DecidableLE X] : DecidableLE (WithTopology X t) := fun x y ↦
  inferInstanceAs (Decidable (x.ofTopology ≤ y.ofTopology))

-- TODO: `inferInstance` works here, but it shouldn't
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [LT X] [DecidableLT X] : DecidableLT (WithTopology X t) := fun x y ↦
  inferInstanceAs (Decidable (x.ofTopology < y.ofTopology))
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Preorder X] : Preorder (WithTopology X t) :=
  .lift ofTopology
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [PartialOrder X] : PartialOrder (WithTopology X t) :=
  ofTopology_injective t |>.partialOrder _ .rfl .rfl

@[to_dual]
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Max X] : Max (WithTopology X t) where
  max x y := toTopology t (max x.ofTopology y.ofTopology)

@[to_dual]
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [SemilatticeSup X] : SemilatticeSup (WithTopology X t) :=
  ofTopology_injective t |>.semilatticeSup _ .rfl .rfl fun _ _ ↦ rfl
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Lattice X] : Lattice (WithTopology X t) where
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [DistribLattice X] : DistribLattice (WithTopology X t) where
  le_sup_inf _ _ _ := le_sup_inf (α := X)
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [Ord X] : Ord (WithTopology X t) where
  compare x y := compare x.ofTopology y.ofTopology
/-
**WithTopology.** 是 Mathlib 中的一个实例，位于命名空间 `WithTopology`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance [LinearOrder X] : LinearOrder (WithTopology X t) :=
  ofTopology_injective t |>.linearOrder _ .rfl .rfl (fun _ _ ↦ rfl) (fun _ _ ↦ rfl) (fun _ _ ↦ rfl)

end WithTopology

