/-
Copyright (c) 2017 Kim Morrison. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tim Baumann, Stephen Morgan, Kim Morrison
-/
module

public import Mathlib.CategoryTheory.Category.Basic
public import Mathlib.Combinatorics.Quiver.Prefunctor
public import Mathlib.Tactic.CategoryTheory.CategoryStar
public meta import Mathlib.Tactic.ToDual

/-!
# Functors

Defines a functor between categories, extending a `Prefunctor` between quivers.

Introduces, in the `CategoryTheory` scope, notations `C ⥤ D` for the type of all functors
from `C` to `D`, `𝟭` for the identity functor and `⋙` for functor composition.

TODO: Switch to using the `⇒` arrow.
-/

@[expose] public section

set_option mathlib.tactic.category.grind true

namespace CategoryTheory

-- declare the `v`'s first; see note [category theory universes].
universe v v₁ v₂ v₃ u u₁ u₂ u₃

/-- `Functor C D` represents a functor between categories `C` and `D`.

To apply a functor `F` to an object use `F.obj X`, and to a morphism use `F.map f`.

The axiom `map_id` expresses preservation of identities, and
`map_comp` expresses functoriality. -/
@[stacks 001B, wikidata Q864475]
/-
**CategoryTheory.Functor** 是 Mathlib 中的一个结构，位于命名空间 `CategoryTheory`。
形式化陈述：Functor (C : Type u₁) [Category.{v₁} C] (D : Type u₂) [Category.{v₂} D] : 
Type max v₁ v₂ u₁ u₂ where /-- The action of a functor on objects. -/ obj : C ->
 D /-- The action of a functor on morphisms. -/ map : forall {X Y : C}, (X ⟶ Y) 
-> ((obj X) ⟶ (obj Y)) /-- A functor preserves identity morphisms. -/ map_id : f
orall X : C, map (𝟙 X) = 𝟙 (obj X)
参数：C : Type u₁；D : Type u₂。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
`Functor C D` represents a functor between categories `C` and `D`.

To apply a functor `F` to an object use `F.obj X`, and to a morphism use `F.map 
f`.

The axiom `map_id` expresses preservation of identities, and
`map_comp` expresses functoriality.
-/
structure Functor (C : Type u₁) [Category.{v₁} C] (D : Type u₂) [Category.{v₂} D] :
    Type max v₁ v₂ u₁ u₂ where
  /-- The action of a functor on objects. -/
  obj : C → D
  /-- The action of a functor on morphisms. -/
  map : ∀ {X Y : C}, (X ⟶ Y) → ((obj X) ⟶ (obj Y))
  /-- A functor preserves identity morphisms. -/
  map_id : ∀ X : C, map (𝟙 X) = 𝟙 (obj X) := by cat_disch
  /-- A functor preserves composition. -/
  map_comp : ∀ {X Y Z : C} (f : X ⟶ Y) (g : Y ⟶ Z), map (f ≫ g) = map f ≫ map g := by cat_disch

/-- Notation for a functor between categories. -/
-- A functor is basically a function, so give ⥤ a similar precedence to → (25).
-- For example, `C × D ⥤ E` should parse as `(C × D) ⥤ E` not `C × (D ⥤ E)`.
scoped[CategoryTheory] infixr:26 " ⥤ " => Functor -- type as \func

attribute [simp] Functor.map_id Functor.map_comp
attribute [grind =] Functor.map_id
attribute [grind _=_] Functor.map_comp
attribute [to_dual self] Functor.map Functor.map_comp
attribute [to_dual self (reorder := map (X Y), map_comp (X Z, f g))] Functor.mk
attribute [to_dual self (reorder := mk (map (X Y), map_comp (X Z, f g)))] Functor.casesOn

-- Note: We manually add this lemma which could be generated by `reassoc`,
-- since we will import this file into `Mathlib/Tactic/CategoryTheory/Reassoc.lean`.
@[to_dual none]
/-
**CategoryTheory.Functor.map_comp_assoc** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheor
y.Functor`。
形式化陈述：∀ {C : Type u₁} [inst : CategoryTheory.Category.{v_1, u₁} C] {D : Type u₂}
   [inst_1 : CategoryTheory.Category.{v_2, u₂} D] (F : CategoryTheory.Functor C 
D) {X Y Z : C} (f : X ⟶ Y) (g : Y ⟶ Z)   {W : D} (h : F.obj Z ⟶ W),   CategoryTh
eory.CategoryStruct.comp (F.map (CategoryTheory.CategoryStruct.comp f g)) h =   
  CategoryTheory.CategoryStruct.comp (F.map f) (CategoryTheory.CategoryStruct.co
mp (F.map g) h)
参数：F : CategoryTheory.Functor C D；f : X ⟶ Y；g : Y ⟶ Z；h : F.obj Z ⟶ W；F.map (Cat
egoryTheory.CategoryStruct.comp f g)；F.map f；CategoryTheory.CategoryStruct.comp 
(F.map g) h。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma Functor.map_comp_assoc {C : Type u₁} [Category* C] {D : Type u₂} [Category* D] (F : C ⥤ D)
    {X Y Z : C} (f : X ⟶ Y) (g : Y ⟶ Z) {W : D} (h : F.obj Z ⟶ W) :
    (F.map (f ≫ g)) ≫ h = F.map f ≫ F.map g ≫ h := by
  grind

namespace Functor

section

variable (C : Type u₁) [Category.{v₁} C]

initialize_simps_projections Functor

-- We don't use `@[simps]` here because we want `C` implicit for the simp lemmas.
/-- `𝟭 C` is the identity functor on a category `C`. -/
@[implicit_reducible]
/-
**CategoryTheory.Functor.id** 是 Mathlib 中的一个定义，位于命名空间 `CategoryTheory.Functor`。
形式化陈述：(C : Type u₁) → [inst : CategoryTheory.Category.{v₁, u₁} C] → CategoryTheo
ry.Functor C C
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
`𝟭 C` is the identity functor on a category `C`.
-/
protected def id : C ⥤ C where
  obj X := X
  map f := f

/-- Notation for the identity functor on a category. -/
scoped[CategoryTheory] notation "𝟭" => Functor.id -- Type this as `\sb1`

/-
**CategoryTheory.Functor.** 是 Mathlib 中的一个实例，位于命名空间 `CategoryTheory.Functor`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance : Inhabited (C ⥤ C) :=
  ⟨Functor.id C⟩

variable {C}

@[simp, grind =]
/-
**CategoryTheory.Functor.id_obj** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory.Functo
r`。
形式化陈述：id_obj (X : C) : (𝟭 C).obj X = X
参数：X : C。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem id_obj (X : C) : (𝟭 C).obj X = X := rfl

@[simp, grind =, to_dual self]
/-
**CategoryTheory.Functor.id_map** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory.Functo
r`。
形式化陈述：id_map {X Y : C} (f : X ⟶ Y) : (𝟭 C).map f = f
参数：f : X ⟶ Y。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem id_map {X Y : C} (f : X ⟶ Y) : (𝟭 C).map f = f := rfl

end

section

variable {C : Type u₁} [Category.{v₁} C] {D : Type u₂} [Category.{v₂} D]
  {E : Type u₃} [Category.{v₃} E]

/-- The prefunctor between the underlying quivers. -/
@[simps]
/-
**CategoryTheory.Functor.toPrefunctor** 是 Mathlib 中的一个定义，位于命名空间 `CategoryTheory.
Functor`。
形式化陈述：toPrefunctor (F : C ⥤ D) : Prefunctor C D
参数：F : C ⥤ D。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The prefunctor between the underlying quivers.
-/
def toPrefunctor (F : C ⥤ D) : Prefunctor C D := { F with }

@[to_dual self]
/-
**CategoryTheory.Functor.congr_map** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory.Fun
ctor`。
形式化陈述：congr_map (F : C ⥤ D) {X Y : C} {f g : X ⟶ Y} (h : f = g) : F.map f = F.ma
p g
参数：F : C ⥤ D；h : f = g。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
-/
theorem congr_map (F : C ⥤ D) {X Y : C} {f g : X ⟶ Y}
    (h : f = g) : F.map f = F.map g := by
  rw [h]

/-- `F ⋙ G` is the composition of a functor `F` and a functor `G` (`F` first, then `G`).
-/
@[simps (attr := grind =) obj, implicit_reducible]
/-
**CategoryTheory.Functor.comp** 是 Mathlib 中的一个定义，位于命名空间 `CategoryTheory.Functor`
。
形式化陈述：comp (F : C ⥤ D) (G : D ⥤ E) : C ⥤ E where obj X
参数：F : C ⥤ D；G : D ⥤ E。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
`F ⋙ G` is the composition of a functor `F` and a functor `G` (`F` first, then `
G`).
-/
def comp (F : C ⥤ D) (G : D ⥤ E) : C ⥤ E where
  obj X := G.obj (F.obj X)
  map f := G.map (F.map f)

/-- Notation for composition of functors. -/
scoped[CategoryTheory] infixr:80 " ⋙ " => Functor.comp

@[simp, grind =, to_dual self]
/-
**CategoryTheory.Functor.comp_map** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory.Func
tor`。
形式化陈述：comp_map (F : C ⥤ D) (G : D ⥤ E) {X Y : C} (f : X ⟶ Y) : (F ⋙ G).map f = G
.map (F.map f)
参数：F : C ⥤ D；G : D ⥤ E；f : X ⟶ Y。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem comp_map (F : C ⥤ D) (G : D ⥤ E) {X Y : C} (f : X ⟶ Y) :
    (F ⋙ G).map f = G.map (F.map f) := rfl

-- These are not simp lemmas because rewriting along equalities between functors
-- is not necessarily a good idea.
-- Natural isomorphisms are also provided in `Whiskering.lean`.
/-
**CategoryTheory.Functor.comp_id** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory.Funct
or`。
形式化陈述：∀ {C : Type u₁} [inst : CategoryTheory.Category.{v₁, u₁} C] {D : Type u₂} 
[inst_1 : CategoryTheory.Category.{v₂, u₂} D]   (F : CategoryTheory.Functor C D)
, F.comp (CategoryTheory.Functor.id D) = F
参数：F : CategoryTheory.Functor C D；CategoryTheory.Functor.id D。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
protected theorem comp_id (F : C ⥤ D) : F ⋙ 𝟭 D = F := rfl
/-
**CategoryTheory.Functor.id_comp** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory.Funct
or`。
形式化陈述：∀ {C : Type u₁} [inst : CategoryTheory.Category.{v₁, u₁} C] {D : Type u₂} 
[inst_1 : CategoryTheory.Category.{v₂, u₂} D]   (F : CategoryTheory.Functor C D)
, (CategoryTheory.Functor.id C).comp F = F
参数：F : CategoryTheory.Functor C D；CategoryTheory.Functor.id C。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
protected theorem id_comp (F : C ⥤ D) : 𝟭 C ⋙ F = F := rfl

@[simp, to_dual self]
/-
**CategoryTheory.Functor.map_dite** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTheory.Func
tor`。
形式化陈述：map_dite (F : C ⥤ D) {X Y : C} {P : Prop} [Decidable P] (f : P -> (X ⟶ Y))
 (g : ¬P -> (X ⟶ Y)) : F.map (if h : P then f h else g h) = if h : P then F.map 
(f h) else F.map (g h)
参数：F : C ⥤ D；f : P -> (X ⟶ Y)；g : ¬P -> (X ⟶ Y)。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem map_dite (F : C ⥤ D) {X Y : C} {P : Prop} [Decidable P]
    (f : P → (X ⟶ Y)) (g : ¬P → (X ⟶ Y)) :
    F.map (if h : P then f h else g h) = if h : P then F.map (f h) else F.map (g h) := by
  cat_disch

@[simp]
/-
**CategoryTheory.Functor.toPrefunctor_comp** 是 Mathlib 中的一个定理，位于命名空间 `CategoryTh
eory.Functor`。
形式化陈述：toPrefunctor_comp (F : C ⥤ D) (G : D ⥤ E) : F.toPrefunctor.comp G.toPrefun
ctor = (F ⋙ G).toPrefunctor
参数：F : C ⥤ D；G : D ⥤ E。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
theorem toPrefunctor_comp (F : C ⥤ D) (G : D ⥤ E) :
    F.toPrefunctor.comp G.toPrefunctor = (F ⋙ G).toPrefunctor := rfl
/-
**CategoryTheory.Functor.toPrefunctor_injective** 是 Mathlib 中的一个引理，位于命名空间 `Categ
oryTheory.Functor`。
形式化陈述：toPrefunctor_injective {F G : C ⥤ D} (h : F.toPrefunctor = G.toPrefunctor)
 : F = G
参数：h : F.toPrefunctor = G.toPrefunctor。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `Prefunctor.mk.injEq`：∀ {V : Type u₁} [inst : Quiver V] {W : Type u₂} [in
st_1 : Quiver W] (obj : V → W)   (map : {X Y : V} → (X ⟶ Y) → (obj X ⟶ obj Y)) (
obj_1 : V…
· 使用定理 `congr`：∀ {α : Sort u} {β : Sort v} {f₁ f₂ : α → β} {a₁ a₂ : α}, f₁ = f₂ 
→ a₁ = a₂ → f₁ a₁ = f₂ a₂
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
· 使用定理 `heq_eq_eq`：∀ {α : Sort u_1} (a b : α), (a ≍ b) = (a = b)
· 使用定理 `true_and`：∀ (p : Prop), (True ∧ p) = p
· 使用定理 `congr_arg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ 
→ f a₁ = f a₂
-/
lemma toPrefunctor_injective {F G : C ⥤ D} (h : F.toPrefunctor = G.toPrefunctor) :
    F = G := by
  obtain ⟨obj, map, _, _⟩ := F
  obtain ⟨obj', map', _, _⟩ := G
  obtain rfl : obj = obj' := congr_arg Prefunctor.obj h
  obtain rfl : @map = @map' := by simpa [Functor.toPrefunctor] using h
  rfl

end

end Functor

end CategoryTheory

