/-
Copyright (c) 2023 Anatole Dedecker. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anatole Dedecker
-/
module

public import Mathlib.Analysis.LocallyConvex.WithSeminorms
public import Mathlib.Topology.Semicontinuity.Basic
public import Mathlib.Topology.Baire.Lemmas

/-!
# Barrelled spaces and the Banach-Steinhaus theorem / Uniform Boundedness Principle

This file defines barrelled spaces over a `NontriviallyNormedField`, and proves the
Banach-Steinhaus theorem for maps from a barrelled space to a space equipped with a family
of seminorms generating the topology (i.e. `WithSeminorms q` for some family of seminorms `q`).

The more standard Banach-Steinhaus theorem for normed spaces is then deduced from that in
`Mathlib/Analysis/Normed/Operator/BanachSteinhaus.lean`.

## Main definitions

* `BarrelledSpace`: a topological vector space `E` is said to be **barrelled** if all lower
  semicontinuous seminorms on `E` are actually continuous. See the implementation details below for
  more comments on this definition.
* `continuousLinearMapOfTendsto`: fix `E` a barrelled space and `F` a `PolynormableSpace`.
  Given a sequence of continuous linear maps from `E` to `F` that converges pointwise to a
  function `f : E → F`, this bundles `f` as a continuous linear map using the
  Banach-Steinhaus theorem.

## Main theorems

* `BaireSpace.instBarrelledSpace`: any TVS that is also a `BaireSpace` is barrelled. In
  particular, this applies to Banach spaces and Fréchet spaces.
* `WithSeminorms.banach_steinhaus`: the **Banach-Steinhaus** theorem, also called
  **Uniform Boundedness Principle**. Fix `E` a barrelled space and `F` a TVS satisfying
  `WithSeminorms q` for some `q`. Any family `𝓕 : ι → E →L[𝕜] F` of continuous linear maps
  that is pointwise bounded is (uniformly) equicontinuous. Here, pointwise bounded means that
  for all `k` and `x`, the family of real numbers `i ↦ q k (𝓕 i x)` is bounded above.
* `PolynormableSpace.banach_steinhaus`: a version of the above which does not make reference
  to a fixed seminorm family. Fix `E` a barrelled space and `F` a `PolynormableSpace`.
  Any family `𝓕 : ι → E →L[𝕜] F` of continuous linear maps that is pointwise von Neumann bounded
  is (uniformly) equicontinuous.

## Implementation details

Barrelled spaces are defined in Bourbaki as locally convex spaces where barrels (aka closed
balanced absorbing convex sets) are neighborhoods of zero. One can then show that barrels in a
locally convex space are exactly closed unit balls of lower semicontinuous seminorms, hence that a
locally convex space is barrelled iff any lower semicontinuous seminorm is continuous.

The problem with this definition is the local convexity, which is essential to prove that the
barrel definition is equivalent to the seminorm definition, because we can essentially only
use `LocallyConvexSpace` over `ℝ` or `ℂ` (which is indeed the setup in which Bourbaki does most
of the theory). Since we can easily prove the normed space version over any
`NontriviallyNormedField`, this wouldn't make for a very satisfying "generalization".

Fortunately, it turns out that using the seminorm definition directly solves all problems,
since it is exactly what we need for the proof. One could then expect to need the barrel
characterization to prove that Baire TVS are barrelled, but the proof is actually easier to do
with the seminorm characterization!

## TODO

* define barrels and prove that a locally convex space is barrelled iff all barrels are
  neighborhoods of zero.

## References

* [N. Bourbaki, *Topological Vector Spaces*][bourbaki1987]

## Tags

banach-steinhaus, uniform boundedness, equicontinuity
-/

@[expose] public section

open Filter Topology Set ContinuousLinearMap

section defs

/-- A topological vector space `E` is said to be **barrelled** if all lower semicontinuous
seminorms on `E` are actually continuous. This is not the usual definition for TVS over `ℝ` or `ℂ`,
but this has the big advantage of working and giving sensible results over *any*
`NontriviallyNormedField`. In particular, the Banach-Steinhaus theorem holds for maps between such
a space and any space whose topology is generated by a family of seminorms. -/
/-
**BarrelledSpace** 是 Mathlib 中的一个归纳类型，位于命名空间 ``。
形式化陈述：(𝕜 : Type u_1) → (E : Type u_2) → [SeminormedRing 𝕜] → [AddGroup E] → [SMu
l 𝕜 E] → [TopologicalSpace E] → Prop
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
A topological vector space `E` is said to be **barrelled** if all lower semicont
inuous
seminorms on `E` are actually continuous. This is not the usual definition for T
VS over `ℝ` or `ℂ`,
but this has the big advantage of working and giving sensible results over *any*
`NontriviallyNormedField`. In particular, the Banach-Steinhaus theorem holds for
 maps between such
a space and any space whose topology is generated by a family of seminorms.
-/
class BarrelledSpace (𝕜 E : Type*) [SeminormedRing 𝕜] [AddGroup E] [SMul 𝕜 E]
    [TopologicalSpace E] : Prop where
  /-- In a barrelled space, all lower semicontinuous seminorms on `E` are actually continuous. -/
  continuous_of_lowerSemicontinuous : ∀ p : Seminorm 𝕜 E, LowerSemicontinuous p → Continuous p
/-
**Seminorm.continuous_of_lowerSemicontinuous** 是 Mathlib 中的一个定理，位于命名空间 ``。
形式化陈述：Seminorm.continuous_of_lowerSemicontinuous {𝕜 E : Type*} [AddGroup E] [SMu
l 𝕜 E] [SeminormedRing 𝕜] [TopologicalSpace E] [BarrelledSpace 𝕜 E] (p : Seminor
m 𝕜 E) (hp : LowerSemicontinuous p) : Continuous p
参数：p : Seminorm 𝕜 E；hp : LowerSemicontinuous p。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `BarrelledSpace.continuous_of_lowerSemicontinuous`：∀ {𝕜 : Type u_1} {E : 
Type u_2} {inst : SeminormedRing 𝕜} {inst_1 : AddGroup E} {inst_2 : SMul 𝕜 E}   
{inst_3 : TopologicalSpace E} [self : …
-/
theorem Seminorm.continuous_of_lowerSemicontinuous {𝕜 E : Type*} [AddGroup E] [SMul 𝕜 E]
    [SeminormedRing 𝕜] [TopologicalSpace E] [BarrelledSpace 𝕜 E] (p : Seminorm 𝕜 E)
    (hp : LowerSemicontinuous p) : Continuous p :=
  BarrelledSpace.continuous_of_lowerSemicontinuous p hp
/-
**Seminorm.continuous_iSup** 是 Mathlib 中的一个定理，位于命名空间 ``。
形式化陈述：Seminorm.continuous_iSup {ι : Sort*} {𝕜 E : Type*} [NormedField 𝕜] [AddCom
mGroup E] [Module 𝕜 E] [TopologicalSpace E] [BarrelledSpace 𝕜 E] (p : ι -> Semin
orm 𝕜 E) (hp : forall i, Continuous (p i)) (bdd : BddAbove (range p)) : Continuo
us (⨆ i, p i)
参数：p : ι -> Seminorm 𝕜 E；hp : forall i, Continuous (p i)；bdd : BddAbove (range p
)。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `Seminorm.coe_iSup_eq`：∀ {𝕜 : Type u_3} {E : Type u_7} [inst : NormedFiel
d 𝕜] [inst_1 : AddCommGroup E] [inst_2 : _root_.Module 𝕜 E]   {ι : Sort u_12} {p
 : ι → Sem…
· 使用定理 `Seminorm.continuous_of_lowerSemicontinuous`：Seminorm.continuous_of_lower
Semicontinuous {𝕜 E : Type*} [AddGroup E] [SMul 𝕜 E] [SeminormedRing 𝕜] [Topolog
icalSpace E] [BarrelledSpace 𝕜 E…
· 使用定理 `eq_of_heq`：∀ {α : Sort u} {a a' : α}, a ≍ a' → a = a'
· 使用定理 `funext`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, (∀ (x : α
), f x = g x) → f = g
· 使用定理 `iSup_apply`：iSup_apply {α : Type*} {β : α -> Type*} {ι : Sort*} [forall 
i, SupSet (β i)] {f : ι -> forall a, β a} {a : α} : (⨆ i, f i) a = ⨆ i, f i a
· 使用定理 `lowerSemicontinuous_ciSup`：lowerSemicontinuous_ciSup {f : ι -> α -> δ'} 
(bdd : forall x, BddAbove (range fun i => f i x)) (h : forall i, LowerSemicontin
uous (f i)) : L…
· 使用定理 `Seminorm.bddAbove_range_iff`：∀ {𝕜 : Type u_3} {E : Type u_7} [inst : Nor
medField 𝕜] [inst_1 : AddCommGroup E] [inst_2 : _root_.Module 𝕜 E]   {ι : Sort u
_12} {p : ι → Sem…
· 使用定理 `Continuous.lowerSemicontinuous`：Continuous.lowerSemicontinuous {f : α ->
 γ} (h : Continuous f) : LowerSemicontinuous f
· 使用定理 `instOrderTopologyReal`：OrderTopology ℝ
-/
theorem Seminorm.continuous_iSup
    {ι : Sort*} {𝕜 E : Type*} [NormedField 𝕜] [AddCommGroup E] [Module 𝕜 E]
    [TopologicalSpace E] [BarrelledSpace 𝕜 E] (p : ι → Seminorm 𝕜 E)
    (hp : ∀ i, Continuous (p i)) (bdd : BddAbove (range p)) :
    Continuous (⨆ i, p i) := by
  rw [← Seminorm.coe_iSup_eq bdd]
  refine Seminorm.continuous_of_lowerSemicontinuous _ ?_
  rw [Seminorm.coe_iSup_eq bdd]
  rw [Seminorm.bddAbove_range_iff] at bdd
  convert! lowerSemicontinuous_ciSup (f := fun i x ↦ p i x) bdd (fun i ↦ (hp i).lowerSemicontinuous)
  exact iSup_apply

end defs

section TVS_anyField

variable {α ι κ 𝕜₁ 𝕜₂ E F : Type*} [NontriviallyNormedField 𝕜₁]
    [NontriviallyNormedField 𝕜₂] {σ₁₂ : 𝕜₁ →+* 𝕜₂} [RingHomIsometric σ₁₂]
    [AddCommGroup E] [AddCommGroup F] [Module 𝕜₁ E] [Module 𝕜₂ F]

/-- Any TVS over a `NontriviallyNormedField` that is also a Baire space is barrelled. In
particular, this applies to Banach spaces and Fréchet spaces. -/
/-
**BaireSpace.instBarrelledSpace** 是 Mathlib 中的一个实例，位于命名空间 ``。
形式化陈述：BaireSpace.instBarrelledSpace [TopologicalSpace E] [IsTopologicalAddGroup 
E] [ContinuousConstSMul 𝕜₁ E] [BaireSpace E] : BarrelledSpace 𝕜₁ E where continu
ous_of_lowerSemicontinuous
该定义给出了上述对象。
本声明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Seminorm.closedBall_zero_eq`：closedBall_zero_eq : closedBall p 0 r = { y
 : E | p y <= r }
· 使用定理 `LowerSemicontinuous.isClosed_preimage`：LowerSemicontinuous.isClosed_prei
mage {f : α -> γ} (hf : LowerSemicontinuous f) (y : γ) : IsClosed (f ⁻¹' Iic y)
· 使用定理 `Set.eq_univ_of_forall`：eq_univ_of_forall {s : Set α} : (forall x, x in s
) -> s = univ
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `Set.mem_iUnion`：mem_iUnion {x : α} {s : ι -> Set α} : (x in ⋃ i, s i) ↔ 
exists i, x in s i
· 使用定理 `exists_nat_ge`：exists_nat_ge (x : R) : exists n : Nat, x <= n
· 使用定理 `nonempty_interior_of_iUnion_of_closed`：nonempty_interior_of_iUnion_of_cl
osed [Countable ι] {f : ι -> Set X} (hc : forall i, IsClosed (f i)) (hU : ⋃ i, f
 i = univ) : exists i, (int…
· 使用定理 `AddTorsor.nonempty`：∀ {G : outParam (Type u_1)} {P : Type u_2} {inst : A
ddGroup G} [self : AddTorsor G P], Nonempty P
· 使用定理 `instCountableNat`：Countable ℕ
· 使用定理 `Seminorm.continuous'`：∀ {𝕜 : Type u_3} {E : Type u_7} [inst : Nontrivial
lyNormedField 𝕜] [inst_1 : AddCommGroup E]   [inst_2 : _root_.Module 𝕜 E] [inst_
3 : Topolo…
· 使用定理 `interior_subset`：interior_subset : interior s subseteq s
· 使用定理 `Filter.mp_mem`：mp_mem (hs : s in f) (h : { x | x in s -> x in t } in f) 
: t in f
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `map_add_left_nhds_zero`：∀ {G : Type w} [inst : TopologicalSpace G] [inst
_1 : AddGroup G] [IsTopologicalAddGroup G] (x : G),   Filter.map (fun x_1 => x +
 x_1) (nhds …
· 使用定理 `mem_interior_iff_mem_nhds`：mem_interior_iff_mem_nhds : x in interior s ↔
 s in 𝓝 x
· 使用定理 `Filter.univ_mem'`：univ_mem' (h : forall a, a in s) : s in f
· 使用定理 `add_sub_cancel_left`：∀ {G : Type u_3} [inst : AddCommGroup G] (a b : G),
 a + b - a = b
· 使用定理 `map_sub_le_add`：∀ {F : Type u_2} {α : Type u_3} {β : Type u_4} [inst : F
unLike F α β] [inst_1 : AddGroup α] [inst_2 : AddCommMonoid β]   [inst_3 : Parti
alOr…
· 使用定理 `SeminormClass.toAddGroupSeminormClass`：∀ {F : Type u_12} {𝕜 : outParam (
Type u_13)} {E : outParam (Type u_14)} {inst : SeminormedRing 𝕜} {inst_1 : AddGr
oup E}   {inst_2 : SMul 𝕜 E…
· 使用定理 `add_le_add`：∀ {α : Type u_1} [inst : Add α] [inst_1 : Preorder α] [AddLe
ftMono α] [AddRightMono α] {a b c d : α},   a ≤ b → c ≤ d → a + c ≤ b + d
· 使用定理 `IsOrderedAddMonoid.toAddLeftMono`：∀ {α : Type u_1} [inst : AddCommMonoid
 α] [inst_1 : Preorder α] [IsOrderedAddMonoid α], AddLeftMono α
· 使用定理 `covariant_swap_add_of_covariant_add`：∀ (N : Type u_2) (r : N → N → Prop)
 [inst : AddCommSemigroup N] [CovariantClass N N (fun x1 x2 => x1 + x2) r],   Co
variantClass N N (Functio…

--- 原说明 ---
Any TVS over a `NontriviallyNormedField` that is also a Baire space is barrelled
. In
particular, this applies to Banach spaces and Fréchet spaces.
-/
instance BaireSpace.instBarrelledSpace [TopologicalSpace E] [IsTopologicalAddGroup E]
    [ContinuousConstSMul 𝕜₁ E] [BaireSpace E] :
    BarrelledSpace 𝕜₁ E where
  continuous_of_lowerSemicontinuous := by
    -- Let `p` be a lower-semicontinuous seminorm on `E`.
    intro p hp
    -- Consider the family of all `p`-closed-balls with integer radius.
    -- By lower semicontinuity, each of these closed balls is indeed closed...
    have h₁ : ∀ n : ℕ, IsClosed (p.closedBall (0 : E) n) := fun n ↦ by
      simpa [p.closedBall_zero_eq] using! hp.isClosed_preimage n
    -- ... and clearly they cover the whole space.
    have h₂ : (⋃ n : ℕ, p.closedBall (0 : E) n) = univ :=
      eq_univ_of_forall fun x ↦ mem_iUnion.mpr (exists_nat_ge <| p (x - 0))
    -- Hence, one of them has nonempty interior. Let `n : ℕ` be its radius, and fix `x` an
    -- interior point.
    rcases nonempty_interior_of_iUnion_of_closed h₁ h₂ with ⟨n, ⟨x, hxn⟩⟩
    -- To show that `p` is continuous, we will show that the `p`-closed-ball of
    -- radius `2*n` is a neighborhood of zero.
    refine Seminorm.continuous' (r := n + n) ?_
    rw [p.closedBall_zero_eq] at hxn ⊢
    have hxn' : p x ≤ n := by convert! interior_subset hxn
    -- By definition, we have `p x' ≤ n` for `x'` sufficiently close to `x`.
    -- In other words, `p (x + y) ≤ n` for `y` sufficiently close to `0`.
    rw [mem_interior_iff_mem_nhds, ← map_add_left_nhds_zero] at hxn
    -- Hence, for `y` sufficiently close to `0`, we have
    -- `p y = p (x + y - x) ≤ p (x + y) + p x ≤ 2*n`
    filter_upwards [hxn] with y hy
    calc p y = p (x + y - x) := by rw [add_sub_cancel_left]
      _ ≤ p (x + y) + p x := map_sub_le_add _ _ _
      _ ≤ n + n := add_le_add hy hxn'

namespace WithSeminorms

variable [UniformSpace E] [UniformSpace F] [IsUniformAddGroup E] [IsUniformAddGroup F]
    [ContinuousSMul 𝕜₁ E] [BarrelledSpace 𝕜₁ E] {𝓕 : ι → E →SL[σ₁₂] F}
    {q : SeminormFamily 𝕜₂ F κ} (hq : WithSeminorms q)
include hq

/-- The **Banach-Steinhaus** theorem, or **Uniform Boundedness Principle**, for maps from a
barrelled space to any space whose topology is generated by a family of seminorms. Use
`WithSeminorms.equicontinuous_TFAE` and `Seminorm.bound_of_continuous` to get explicit bounds on
the seminorms from equicontinuity. -/
/-
**WithSeminorms.banach_steinhaus** 是 Mathlib 中的一个定理，位于命名空间 `WithSeminorms`。
形式化陈述：∀ {ι : Type u_2} {κ : Type u_3} {𝕜₁ : Type u_4} {𝕜₂ : Type u_5} {E : Type 
u_6} {F : Type u_7}   [inst : NontriviallyNormedField 𝕜₁] [inst_1 : Nontrivially
NormedField 𝕜₂] {σ₁₂ : 𝕜₁ →+* 𝕜₂} [RingHomIsometric σ₁₂]   [inst_3 : AddCommGrou
p E] [inst_4 : AddCommGroup F] [inst_5 : _root_.Module 𝕜₁ E] [inst_6 : _root_.Mo
dule 𝕜₂ F]   [inst_7 : UniformSpace E] [inst_8 : UniformSpace F] [IsUniformAddGr
oup E] [IsUniformAddGroup F] [ContinuousSMul 𝕜₁ E]   [BarrelledSpace 𝕜₁ E] {𝓕 : 
ι → E →SL[σ₁₂] F} {q : SeminormFamily 𝕜₂ F κ},   WithSeminorms q →     (∀ (k : κ
) (x : E), BddAbove (Set.range fun i => (q k) ((𝓕 i) x))) → UniformEquicontinuou
s (DFunLike.coe ∘ 𝓕)
参数：∀ (k : κ) (x : E), BddAbove (Set.range fun i => (q k) ((𝓕 i) x))；DFunLike.coe
 ∘ 𝓕。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `WithSeminorms.uniformEquicontinuous_iff_bddAbove_and_continuous_iSup`：un
iformEquicontinuous_iff_bddAbove_and_continuous_iSup {κ : Type*} {q : SeminormFa
mily 𝕜₂ F ι'} [UniformSpace E] [IsUniformAddGroup E] [u : …
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Seminorm.bddAbove_range_iff`：∀ {𝕜 : Type u_3} {E : Type u_7} [inst : Nor
medField 𝕜] [inst_1 : AddCommGroup E] [inst_2 : _root_.Module 𝕜 E]   {ι : Sort u
_12} {p : ι → Sem…
· 使用定理 `Seminorm.continuous_iSup`：Seminorm.continuous_iSup {ι : Sort*} {𝕜 E : Ty
pe*} [NormedField 𝕜] [AddCommGroup E] [Module 𝕜 E] [TopologicalSpace E] [Barrell
edSpace 𝕜 E] (…
· 使用定理 `Continuous.comp`：Continuous.comp {g : Y -> Z} (hg : Continuous g) (hf : 
Continuous f) : Continuous (g ∘ f)
· 使用定理 `WithSeminorms.continuous_seminorm`：WithSeminorms.continuous_seminorm {p 
: SeminormFamily 𝕜 E ι} (hp : WithSeminorms p) (i : ι) : Continuous (p i)
· 使用定理 `ContinuousLinearMap.continuous`：∀ {R₁ : Type u_1} {R₂ : Type u_2} [inst 
: Semiring R₁] [inst_1 : Semiring R₂] {σ₁₂ : R₁ →+* R₂} {M₁ : Type u_4}   [inst_
2 : TopologicalSpace…

--- 原说明 ---
The **Banach-Steinhaus** theorem, or **Uniform Boundedness Principle**, for maps
 from a
barrelled space to any space whose topology is generated by a family of seminorm
s. Use
`WithSeminorms.equicontinuous_TFAE` and `Seminorm.bound_of_continuous` to get ex
plicit bounds on
the seminorms from equicontinuity.
-/
protected theorem banach_steinhaus (H : ∀ k x, BddAbove (range fun i ↦ q k (𝓕 i x))) :
    UniformEquicontinuous ((↑) ∘ 𝓕) := by
  -- We just have to prove that `⊔ i, (q k) ∘ (𝓕 i)` is a (well-defined) continuous seminorm
  -- for all `k`.
  refine (hq.uniformEquicontinuous_iff_bddAbove_and_continuous_iSup (toLinearMap ∘ 𝓕)).mpr ?_
  intro k
  -- By assumption the supremum `⊔ i, q k (𝓕 i x)` is well-defined for all `x`, hence the
  -- supremum `⊔ i, (q k) ∘ (𝓕 i)` is well defined in the lattice of seminorms.
  have : BddAbove (range fun i ↦ (q k).comp (𝓕 i).toLinearMap) := by
    rw [Seminorm.bddAbove_range_iff]
    exact H k
  -- By definition of the lattice structure on seminorms, `⊔ i, (q k) ∘ (𝓕 i)` is the *pointwise*
  -- supremum of the continuous seminorms `(q k) ∘ (𝓕 i)`. Since `E` is barrelled, this supremum
  -- is continuous.
  exact ⟨this, Seminorm.continuous_iSup _
    (fun i ↦ (hq.continuous_seminorm k).comp (𝓕 i).continuous) this⟩

end WithSeminorms

section PolynormableSpace

open Bornology

variable [UniformSpace E] [UniformSpace F] [IsUniformAddGroup E] [IsUniformAddGroup F]
    [ContinuousSMul 𝕜₁ E] [BarrelledSpace 𝕜₁ E] {𝓕 : ι → E →SL[σ₁₂] F} [PolynormableSpace 𝕜₂ F]

/-- The **Banach-Steinhaus** theorem, or **Uniform Boundedness Principle**, for maps from a
barrelled space to any polynormable space. -/
/-
**PolynormableSpace.banach_steinhaus** 是 Mathlib 中的一个定理，位于命名空间 `PolynormableSpac
e`。
形式化陈述：∀ {ι : Type u_2} {𝕜₁ : Type u_4} {𝕜₂ : Type u_5} {E : Type u_6} {F : Type 
u_7} [inst : NontriviallyNormedField 𝕜₁]   [inst_1 : NontriviallyNormedField 𝕜₂]
 {σ₁₂ : 𝕜₁ →+* 𝕜₂} [RingHomIsometric σ₁₂] [inst_3 : AddCommGroup E]   [inst_4 : 
AddCommGroup F] [inst_5 : _root_.Module 𝕜₁ E] [inst_6 : _root_.Module 𝕜₂ F] [ins
t_7 : UniformSpace E]   [inst_8 : UniformSpace F] [IsUniformAddGroup E] [IsUnifo
rmAddGroup F] [ContinuousSMul 𝕜₁ E] [BarrelledSpace 𝕜₁ E]   {𝓕 : ι → E →SL[σ₁₂] 
F} [PolynormableSpace 𝕜₂ F],   (∀ (x : E), Bornology.IsVonNBounded 𝕜₂ (Set.range
 fun i => (𝓕 i) x)) → UniformEquicontinuous (DFunLike.coe ∘ 𝓕)
参数：∀ (x : E), Bornology.IsVonNBounded 𝕜₂ (Set.range fun i => (𝓕 i) x)；DFunLike.c
oe ∘ 𝓕。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `PolynormableSpace.withSeminorms`：PolynormableSpace.withSeminorms [Polyno
rmableSpace 𝕜 E] : WithSeminorms (fun p : {p : Seminorm 𝕜 E // Continuous p} => 
p.1)
· 使用定理 `WithSeminorms.banach_steinhaus`：∀ {ι : Type u_2} {κ : Type u_3} {𝕜₁ : Ty
pe u_4} {𝕜₂ : Type u_5} {E : Type u_6} {F : Type u_7}   [inst : NontriviallyNorm
edField 𝕜₁] [inst_1 …
· 使用定理 `forall_congr`：∀ {α : Sort u} {p q : α → Prop}, (∀ (a : α), p a = q a) → 
(∀ (a : α), p a) = ∀ (a : α), q a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `WithSeminorms.isVonNBounded_iff_seminorm_bddAbove`：WithSeminorms.isVonNB
ounded_iff_seminorm_bddAbove {s : Set E} (hp : WithSeminorms p) : IsVonNBounded 
𝕜 s ↔ forall i : ι, BddAbove (p i '' s)

--- 原说明 ---
The **Banach-Steinhaus** theorem, or **Uniform Boundedness Principle**, for maps
 from a
barrelled space to any polynormable space.
-/
protected theorem PolynormableSpace.banach_steinhaus
    (H : ∀ x, IsVonNBounded 𝕜₂ (range fun i ↦ 𝓕 i x)) :
    UniformEquicontinuous ((↑) ∘ 𝓕) := by
  have hp := PolynormableSpace.withSeminorms 𝕜₂ F
  refine hp.banach_steinhaus ?_
  simp_rw [hp.isVonNBounded_iff_seminorm_bddAbove, ← range_comp] at H
  exact fun q x ↦ H x q

variable [ContinuousSMul 𝕜₂ F]

/-- Given a sequence of continuous linear maps which converges pointwise and for which the
domain is barrelled, the Banach-Steinhaus theorem is used to guarantee that the limit map
is a *continuous* linear map as well.

This actually works for any *countably generated* filter instead of `atTop : Filter ℕ`,
but the proof ultimately goes back to sequences. -/
/-
**continuousLinearMapOfTendsto** 是 Mathlib 中的一个定义，位于命名空间 ``。
形式化陈述：continuousLinearMapOfTendsto [T2Space F] {l : Filter α} [l.IsCountablyGene
rated] [l.NeBot] (g : α -> E ->SL[σ₁₂] F) {f : E -> F} (h : Tendsto (fun n x => 
g n x) l (𝓝 f)) : E ->SL[σ₁₂] F where toLinearMap
参数：g : α -> E ->SL[σ₁₂] F；h : Tendsto (fun n x => g n x) l (𝓝 f)。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a sequence of continuous linear maps which converges pointwise and for whi
ch the
domain is barrelled, the Banach-Steinhaus theorem is used to guarantee that the 
limit map
is a *continuous* linear map as well.

This actually works for any *countably generated* filter instead of `atTop : Fil
ter ℕ`,
but the proof ultimately goes back to sequences.
-/
def continuousLinearMapOfTendsto
    [T2Space F] {l : Filter α} [l.IsCountablyGenerated]
    [l.NeBot] (g : α → E →SL[σ₁₂] F) {f : E → F} (h : Tendsto (fun n x ↦ g n x) l (𝓝 f)) :
    E →SL[σ₁₂] F where
  toLinearMap := linearMapOfTendsto _ _ h
  cont := by
    -- Since the filter `l` is countably generated and nontrivial, we can find a sequence
    -- `u : ℕ → α` that tends to `l`. By considering `g ∘ u` instead of `g`, we can thus assume
    -- that `α = ℕ` and `l = atTop`
    rcases l.exists_seq_tendsto with ⟨u, hu⟩
    -- We claim that the limit is continuous because it's a limit of an equicontinuous family.
    -- By the Banach-Steinhaus theorem, this equicontinuity will follow from pointwise boundedness.
    refine (h.comp hu).continuous_of_equicontinuous
      (PolynormableSpace.banach_steinhaus ?_).equicontinuous
    -- For `x` fixed, we need to show that the range of `(i : ℕ) ↦ g i x` is bounded.
    intro x
    -- This follows from the fact that this sequence converges (to `f x`) by hypothesis.
    rw [tendsto_pi_nhds] at h
    exact ((h x).comp hu).isVonNBounded_range 𝕜₂

end PolynormableSpace

section Deprecated

variable [UniformSpace E] [UniformSpace F] [IsUniformAddGroup E] [IsUniformAddGroup F]
    [ContinuousSMul 𝕜₁ E] [BarrelledSpace 𝕜₁ E] [ContinuousSMul 𝕜₂ F] {𝓕 : ι → E →SL[σ₁₂] F}
    {q : SeminormFamily 𝕜₂ F κ} (hq : WithSeminorms q)
include hq

/-- Given a sequence of continuous linear maps which converges pointwise and for which the
domain is barrelled, the Banach-Steinhaus theorem is used to guarantee that the limit map
is a *continuous* linear map as well.

This actually works for any *countably generated* filter instead of `atTop : Filter ℕ`,
but the proof ultimately goes back to sequences. -/
@[deprecated continuousLinearMapOfTendsto (since := "2026-01-16")]
/-
**WithSeminorms.continuousLinearMapOfTendsto** 是 Mathlib 中的一个定义，位于命名空间 `WithSemi
norms`。
形式化陈述：{α : Type u_1} →   {κ : Type u_3} →     {𝕜₁ : Type u_4} →       {𝕜₂ : Type
 u_5} →         {E : Type u_6} →           {F : Type u_7} →             [inst : 
NontriviallyNormedField 𝕜₁] →               [inst_1 : NontriviallyNormedField 𝕜₂
] →                 {σ₁₂ : 𝕜₁ →+* 𝕜₂} →                   [RingHomIsometric σ₁₂]
 →                     [inst_3 : AddCommGroup E] →                       [inst_4
 : AddCommGroup F] →                         [inst_5 : _root_.Module 𝕜₁ E] →    
                       [inst_6 : _root_.Module 𝕜₂ F] →                          
   [inst_7 : UniformSpace E] →                               [inst_8 : UniformSp
ace F] →                                 [IsUniformAddGroup E] →                
                   [IsUniformAddGroup F] →                                     [
ContinuousSMul 𝕜₁ E] →                                       [BarrelledSpace 𝕜₁ 
E] →                                         [ContinuousSMul 𝕜₂ F] →            
                               {q : SeminormFamily 𝕜₂ F κ} →                    
                         WithSeminorms q →                                      
         [T2Space F] →                                                 {l : Filt
er α} →                                                   [l.IsCountablyGenerate
d] →                                                     [l.NeBot] →            
                                           (g : α → E →SL[σ₁₂] F) →             
                                            {f : E → F} →                       
                                    Filter.Tendsto (fun n x => (g n) x) l (nhds 
f) → E →SL[σ₁₂] F
参数：g : α → E →SL[σ₁₂] F；fun n x => (g n) x；nhds f。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a sequence of continuous linear maps which converges pointwise and for whi
ch the
domain is barrelled, the Banach-Steinhaus theorem is used to guarantee that the 
limit map
is a *continuous* linear map as well.

This actually works for any *countably generated* filter instead of `atTop : Fil
ter ℕ`,
but the proof ultimately goes back to sequences.
-/
protected abbrev WithSeminorms.continuousLinearMapOfTendsto [T2Space F] {l : Filter α}
    [l.IsCountablyGenerated] [l.NeBot] (g : α → E →SL[σ₁₂] F) {f : E → F}
    (h : Tendsto (fun n x ↦ g n x) l (𝓝 f)) :
    E →SL[σ₁₂] F :=
  haveI : PolynormableSpace 𝕜₂ F := hq.toPolynormableSpace
  continuousLinearMapOfTendsto g h

end Deprecated

end TVS_anyField

