/-
Copyright (c) 2019 Kenny Lau. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenny Lau, Johan Commelin
-/
module

public import Mathlib.Algebra.FreeMonoid.Basic
public import Mathlib.GroupTheory.FreeAbelianGroup

/-!
# Free rings

The theory of the free ring over a type.

## Main definitions

* `FreeRing α` : the free (not commutative in general) ring over a type.
* `lift (f : α → R)` : the ring hom `FreeRing α →+* R` induced by `f`.
* `map (f : α → β)` : the ring hom `FreeRing α →+* FreeRing β` induced by `f`.

## Implementation details

`FreeRing α` is implemented as the free abelian group over the free monoid on `α`.

## Tags

free ring

-/

@[expose] public section


universe u v

/--
If `α` is a type, then `FreeRing α` is the free ring generated by `α`.
This is a ring equipped with a function `FreeRing.of : α → FreeRing α` which has
the following universal property: if `R` is any ring, and `f : α → R` is any function,
then this function is the composite of `FreeRing.of` and a unique ring homomorphism
`FreeRing.lift f : FreeRing α →+* R`.

A typical element of `FreeRing α` is a `ℤ`-linear combination of
formal products of elements of `α`.
For example if `x` and `y` are terms of type `α` then `3 * x * y * x - 2 * y * x + 1` is a
"typical" element of `FreeRing α`. In particular if `α` is empty
then `FreeRing α` is isomorphic to `ℤ`, and if `α` has one term `t`
then `FreeRing α` is isomorphic to the polynomial ring `ℤ[t]`.
If `α` has two or more terms then `FreeRing α` is not commutative.
One can think of `FreeRing α` as the free non-commutative polynomial ring
with coefficients in the integers and variables indexed by `α`.
-/
/-
**FreeRing** 是 Mathlib 中的一个定义，位于命名空间 ``。
形式化陈述：FreeRing (α : Type u) : Type u
参数：α : Type u。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
If `α` is a type, then `FreeRing α` is the free ring generated by `α`.
This is a ring equipped with a function `FreeRing.of : α → FreeRing α` which has
the following universal property: if `R` is any ring, and `f : α → R` is any fun
ction,
then this function is the composite of `FreeRing.of` and a unique ring homomorph
ism
`FreeRing.lift f : FreeRing α →+* R`.

A typical element of `FreeRing α` is a `ℤ`-linear combination of
formal products of elements of `α`.
For example if `x` and `y` are terms of type `α` then `3 * x * y * x - 2 * y * x
 + 1` is a
"typical" element of `FreeRing α`. In particular if `α` is empty
then `FreeRing α` is isomorphic to `ℤ`, and if `α` has one term `t`
then `FreeRing α` is isomorphic to the polynomial ring `ℤ[t]`.
If `α` has two or more terms then `FreeRing α` is not commutative.
One can think of `FreeRing α` as the free non-commutative polynomial ring
with coefficients in the integers and variables indexed by `α`.
-/
def FreeRing (α : Type u) : Type u :=
  FreeAbelianGroup <| FreeMonoid α
deriving Ring, Inhabited, Nontrivial

namespace FreeRing

variable {α : Type u}

/-- The canonical map from α to `FreeRing α`. -/
/-
**FreeRing.of** 是 Mathlib 中的一个定义，位于命名空间 `FreeRing`。
形式化陈述：of (x : α) : FreeRing α
参数：x : α。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The canonical map from α to `FreeRing α`.
-/
def of (x : α) : FreeRing α :=
  FreeAbelianGroup.of (FreeMonoid.of x)
/-
**FreeRing.of_injective** 是 Mathlib 中的一个定理，位于命名空间 `FreeRing`。
形式化陈述：of_injective : Function.Injective (of : α -> FreeRing α)
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Function.Injective.comp`：∀ {α : Sort u_1} {β : Sort u_2} {γ : Sort u_3} 
{g : β → γ} {f : α → β},   Function.Injective g → Function.Injective f → Functio
n.Injective (…
· 使用定理 `FreeAbelianGroup.of_injective`：of_injective : Function.Injective (of : α
 -> FreeAbelianGroup α)
· 使用定理 `FreeMonoid.of_injective`：of_injective : Function.Injective (@of α)
-/
theorem of_injective : Function.Injective (of : α → FreeRing α) :=
  FreeAbelianGroup.of_injective.comp FreeMonoid.of_injective

@[simp]
/-
**FreeRing.of_ne_zero** 是 Mathlib 中的一个定理，位于命名空间 `FreeRing`。
形式化陈述：of_ne_zero (x : α) : of x != 0
参数：x : α。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `FreeAbelianGroup.of_ne_zero`：of_ne_zero (x : α) : of x != 0
-/
theorem of_ne_zero (x : α) : of x ≠ 0 := FreeAbelianGroup.of_ne_zero _

@[simp]
/-
**FreeRing.zero_ne_of** 是 Mathlib 中的一个定理，位于命名空间 `FreeRing`。
形式化陈述：zero_ne_of (x : α) : 0 != of x
参数：x : α。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `FreeAbelianGroup.zero_ne_of`：∀ {α : Type u} (x : α), 0 ≠ FreeAbelianGrou
p.of x
-/
theorem zero_ne_of (x : α) : 0 ≠ of x := FreeAbelianGroup.zero_ne_of _

@[simp]
/-
**FreeRing.of_ne_one** 是 Mathlib 中的一个定理，位于命名空间 `FreeRing`。
形式化陈述：of_ne_one (x : α) : of x != 1
参数：x : α。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Function.Injective.ne`：∀ {α : Sort u_1} {β : Sort u_2} {f : α → β}, Func
tion.Injective f → ∀ {a₁ a₂ : α}, a₁ ≠ a₂ → f a₁ ≠ f a₂
· 使用定理 `FreeAbelianGroup.of_injective`：of_injective : Function.Injective (of : α
 -> FreeAbelianGroup α)
· 使用定理 `FreeMonoid.of_ne_one`：of_ne_one (a : α) : of a != 1
-/
theorem of_ne_one (x : α) : of x ≠ 1 := FreeAbelianGroup.of_injective.ne <| FreeMonoid.of_ne_one _

@[simp]
/-
**FreeRing.one_ne_of** 是 Mathlib 中的一个定理，位于命名空间 `FreeRing`。
形式化陈述：one_ne_of (x : α) : 1 != of x
参数：x : α。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Function.Injective.ne`：∀ {α : Sort u_1} {β : Sort u_2} {f : α → β}, Func
tion.Injective f → ∀ {a₁ a₂ : α}, a₁ ≠ a₂ → f a₁ ≠ f a₂
· 使用定理 `FreeAbelianGroup.of_injective`：of_injective : Function.Injective (of : α
 -> FreeAbelianGroup α)
· 使用定理 `FreeMonoid.one_ne_of`：∀ {α : Type u_1} (a : α), 1 ≠ FreeMonoid.of a
-/
theorem one_ne_of (x : α) : 1 ≠ of x := FreeAbelianGroup.of_injective.ne <| FreeMonoid.one_ne_of _

@[elab_as_elim, induction_eliminator]
/-
**FreeRing.induction_on** 是 Mathlib 中的一个定理，位于命名空间 `FreeRing`。
形式化陈述：∀ {α : Type u} {C : FreeRing α → Prop} (z : FreeRing α),   C (-1) →     (∀
 (b : α), C (FreeRing.of b)) →       (∀ (x y : FreeRing α), C x → C y → C (x + y
)) → (∀ (x y : FreeRing α), C x → C y → C (x * y)) → C z
参数：z : FreeRing α；-1；∀ (b : α), C (FreeRing.of b)；∀ (x y : FreeRing α), C x → C 
y → C (x + y)；∀ (x y : FreeRing α), C x → C y → C (x * y)。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `neg_one_mul`：neg_one_mul (a : α) : -1 * a = -a
· 使用定理 `neg_neg`：∀ {G : Type u_1} [inst : InvolutiveNeg G] (a : G), - -a = a
· 使用定理 `FreeAbelianGroup.induction_on`：∀ {α : Type u} {motive : FreeAbelianGroup
 α → Prop} (z : FreeAbelianGroup α),   motive 0 →     (∀ (x : α), motive (FreeAb
elianGroup.of x)) →…
· 使用定理 `neg_add_cancel`：∀ {G : Type u_1} [inst : AddGroup G] (a : G), -a + a = 0
-/
protected theorem induction_on {C : FreeRing α → Prop} (z : FreeRing α) (hn1 : C (-1))
    (hb : ∀ b, C (of b)) (ha : ∀ x y, C x → C y → C (x + y)) (hm : ∀ x y, C x → C y → C (x * y)) :
    C z :=
  have hn : ∀ x, C x → C (-x) := fun x ih => neg_one_mul x ▸ hm _ _ hn1 ih
  have h1 : C 1 := neg_neg (1 : FreeRing α) ▸ hn _ hn1
  FreeAbelianGroup.induction_on z (neg_add_cancel (1 : FreeRing α) ▸ ha _ _ hn1 h1)
    (fun m => List.recOn m h1 fun a _ ih => hm _ _ (hb a) ih)
    (fun _ ih => hn _ ih) ha

section lift

variable {R : Type v} [Ring R] (f : α → R)

/-- The ring homomorphism `FreeRing α →+* R` induced from a map `α → R`. -/
/-
**FreeRing.lift** 是 Mathlib 中的一个定义，位于命名空间 `FreeRing`。
形式化陈述：lift : (α -> R) ≃ (FreeRing α ->+* R)
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.trans`：Equiv.trans {s t u : Computation α} : s ~ t -> t ~ u -> s ~
 u

--- 原说明 ---
The ring homomorphism `FreeRing α →+* R` induced from a map `α → R`.
-/
def lift : (α → R) ≃ (FreeRing α →+* R) :=
  FreeMonoid.lift.trans FreeAbelianGroup.liftMonoid

@[simp]
/-
**FreeRing.lift_of** 是 Mathlib 中的一个定理，位于命名空间 `FreeRing`。
形式化陈述：lift_of (x : α) : lift f (of x) = f x
参数：x : α。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congr_fun`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, f = g 
→ ∀ (a : α), f a = g a
· 使用定理 `Equiv.left_inv`：∀ {α : Sort u_1} {β : Sort u_2} (self : α ≃ β), Function
.LeftInverse self.invFun self.toFun
-/
theorem lift_of (x : α) : lift f (of x) = f x :=
  congr_fun (lift.left_inv f) x

@[simp]
/-
**FreeRing.lift_comp_of** 是 Mathlib 中的一个定理，位于命名空间 `FreeRing`。
形式化陈述：lift_comp_of (f : FreeRing α ->+* R) : lift (f ∘ of) = f
参数：f : FreeRing α ->+* R。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.right_inv`：∀ {α : Sort u_1} {β : Sort u_2} (self : α ≃ β), Functio
n.RightInverse self.invFun self.toFun
-/
theorem lift_comp_of (f : FreeRing α →+* R) : lift (f ∘ of) = f :=
  lift.right_inv f

@[ext]
/-
**FreeRing.hom_ext** 是 Mathlib 中的一个定理，位于命名空间 `FreeRing`。
形式化陈述：hom_ext ⦃f g : FreeRing α ->+* R⦄ (h : forall x, f (of x) = g (of x)) : f 
= g
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.injective`：∀ {α : Sort u} {β : Sort v} (e : α ≃ β), Function.Injec
tive ⇑e
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s
· 使用定理 `funext`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, (∀ (x : α
), f x = g x) → f = g
-/
theorem hom_ext ⦃f g : FreeRing α →+* R⦄ (h : ∀ x, f (of x) = g (of x)) : f = g :=
  lift.symm.injective (funext h)

end lift

variable {β : Type v} (f : α → β)

/-- The canonical ring homomorphism `FreeRing α →+* FreeRing β` generated by a map `α → β`. -/
/-
**FreeRing.map** 是 Mathlib 中的一个定义，位于命名空间 `FreeRing`。
形式化陈述：map : FreeRing α ->+* FreeRing β
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The canonical ring homomorphism `FreeRing α →+* FreeRing β` generated by a map `
α → β`.
-/
def map : FreeRing α →+* FreeRing β :=
  lift <| of ∘ f

@[simp]
/-
**FreeRing.map_of** 是 Mathlib 中的一个定理，位于命名空间 `FreeRing`。
形式化陈述：map_of (x : α) : map f (of x) = of (f x)
参数：x : α。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `FreeRing.lift_of`：lift_of (x : α) : lift f (of x) = f x
-/
theorem map_of (x : α) : map f (of x) = of (f x) :=
  lift_of _ _

end FreeRing

