/-
Copyright (c) 2020 Anne Baanen. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anne Baanen
-/
module

public import Mathlib.FieldTheory.Minpoly.Field
public import Mathlib.LinearAlgebra.SModEq.Basic
public import Mathlib.RingTheory.Ideal.BigOperators

/-!
# Power basis

This file defines a structure `PowerBasis R S`, giving a basis of the
`R`-algebra `S` as a finite list of powers `1, x, ..., x^n`.
For example, if `x` is algebraic over a ring/field, adjoining `x`
gives a `PowerBasis` structure generated by `x`.

## Definitions

* `PowerBasis R A`: a structure containing an `x` and an `n` such that
  `1, x, ..., x^n` is a basis for the `R`-algebra `A` (viewed as an `R`-module).

* `finrank (hf : f ≠ 0) : Module.finrank K (AdjoinRoot f) = f.natDegree`,
  the dimension of `AdjoinRoot f` equals the degree of `f`

* `PowerBasis.lift (pb : PowerBasis R S)`: if `y : S'` satisfies the same
  equations as `pb.gen`, this is the map `S →ₐ[R] S'` sending `pb.gen` to `y`

* `PowerBasis.equiv`: if two power bases satisfy the same equations, they are
  equivalent as algebras

## Implementation notes

Throughout this file, `R`, `S`, `A`, `B` ... are `CommRing`s, and `K`, `L`, ... are `Field`s.
`S` is an `R`-algebra, `B` is an `A`-algebra, `L` is a `K`-algebra.

## Tags

power basis, powerbasis

-/

@[expose] public section

open Finsupp Module Polynomial

variable {R S T : Type*} [CommRing R] [Ring S] [Algebra R S]
variable {A B : Type*} [CommRing A] [CommRing B] [Algebra A B]
variable {K : Type*} [Field K]

/--
Definition of `PowerBasis` / `PowerBasis` 的定义

English:
structure PowerBasis
  parameters: (R S : Type*) [CommRing R] [Ring S] [Algebra R S]
  axioms and operations (4):
    - gen : S
    - dim : Nat
    - basis : Basis (Fin dim) R S
    - basis_eq_pow : forall (i), basis i = gen ^ (i : Nat)

中文:
结构 PowerBasis
  参数: (R S : 类型) [交换环 R] [环 S] [代数 R S]
  公理与运算 (4 个):
    - gen : S
    - dim : 自然数
    - basis : 基 (有限集 dim) R S
    - basis_eq_pow : 对任意 (i), basis i = gen ^ (i : 自然数)
-/
structure PowerBasis (R S : Type*) [CommRing R] [Ring S] [Algebra R S] where
  gen : S
  dim : Nat
  basis : Basis (Fin dim) R S
  basis_eq_pow : forall (i), basis i = gen ^ (i : Nat)

-- this is usually not needed because of `basis_eq_pow` but can be needed in some cases;
-- in such circumstances, add it manually using `@[simps dim gen basis]`.
initialize_simps_projections PowerBasis (-basis)

namespace PowerBasis

@[simp]
/--
theorem `coe_basis` / 定理 `coe_basis`

English:
theorem coe_basis
  given: (pb : PowerBasis R S)
  statement: ⇑pb.basis = fun i : Fin pb.dim => pb.gen ^ (i : Nat)
  proof: funext pb.basis_eq_pow

中文:
定理 coe_basis
  条件: (pb : PowerBasis R S)
  结论: ⇑pb.basis = fun i : 有限集 pb.dim => pb.gen ^ (i : 自然数)
  证明: funext pb.basis_eq_pow

Depends on / 依赖: basis_eq_pow, pb.basis_eq_pow
-/
theorem coe_basis (pb : PowerBasis R S) : ⇑pb.basis = fun i : Fin pb.dim => pb.gen ^ (i : Nat) :=
  funext pb.basis_eq_pow

/--
theorem `finite` / 定理 `finite`

English:
theorem finite
  given: (pb : PowerBasis R S)
  statement: Module.Finite R S
  proof: .of_basis pb.basis

中文:
定理 finite
  条件: (pb : PowerBasis R S)
  结论: 模.有限 R S
  证明: .of_basis pb.basis

Depends on / 依赖: of_basis, pb.basis
-/
theorem finite (pb : PowerBasis R S) : Module.Finite R S := .of_basis pb.basis

/--
Definition of `noncomputable` / `noncomputable` 的定义

English:
definition noncomputable
  signature: def _root_.Module.Basis.PowerBasis {ι : Type*} [Fintype ι] (B : Basis ι R S)
  body: ⟨x, Fintype.card ι, B.reindex e, fun i => by simp [hx]⟩

@[simp]

中文:
定义 noncomputable
  签名: def _root_.模.基.PowerBasis {ι : 类型} [有限类型 ι] (B : 基 ι R S)
  定义体: ⟨x, Fintype.card ι, B.reindex e, fun i => by simp [hx]⟩

@[simp]

Depends on / 依赖: WithVal, WithVal.algEquiv, algEquiv, of_algEquiv
-/
protected noncomputable def _root_.Module.Basis.PowerBasis {ι : Type*} [Fintype ι] (B : Basis ι R S)
    {x : S} (e : ι ≃ Fin (Fintype.card ι)) (hx : forall i, B i = x ^ (e i : Nat)) :
    PowerBasis R S := ⟨x, Fintype.card ι, B.reindex e, fun i => by simp [hx]⟩

@[simp]
/--
theorem `_root_.Module.Basis.PowerBasis_gen` / 定理 `_root_.Module.Basis.PowerBasis_gen`

English:
theorem _root_.Module.Basis.PowerBasis_gen
  statement: {ι : Type*} [Fintype ι] (B : Basis ι R S) {x : S}
  proof: rfl

中文:
定理 _root_.模.基.PowerBasis_gen
  结论: {ι : 类型} [有限类型 ι] (B : 基 ι R S) {x : S}
  证明: rfl
-/
theorem _root_.Module.Basis.PowerBasis_gen {ι : Type*} [Fintype ι] (B : Basis ι R S) {x : S}
    (e : ι ≃ Fin (Fintype.card ι)) (hx : forall i, B i = x ^ (e i : Nat)) :
    (B.PowerBasis e hx).gen = x := rfl

/--
theorem `finrank` / 定理 `finrank`

English:
theorem finrank
  given: [StrongRankCondition R] (pb : PowerBasis R S)
  proof: by
  rw [Module.finrank_eq_card_basis pb.basis]; rw [Fintype.card_fin]

中文:
定理 finrank
  条件: [StrongRankCondition R] (pb : PowerBasis R S)
  证明: by
  rw [Module.finrank_eq_card_basis pb.basis]; rw [Fintype.card_fin]

Depends on / 依赖: Fintype, Fintype.card_fin, Module, Module.finrank_eq_card_basis, card_fin, finrank_eq_card_basis, pb.basis
-/
theorem finrank [StrongRankCondition R] (pb : PowerBasis R S) :
    Module.finrank R S = pb.dim := by
  rw [Module.finrank_eq_card_basis pb.basis]; rw [Fintype.card_fin]

/--
theorem `mem_span_pow'` / 定理 `mem_span_pow'`

English:
theorem mem_span_pow'
  given: {x y : S} {d : Nat}
  proof: by
  have : (Set.range fun i : Fin d => x ^ (i : Nat)) = (fun i : Nat => x ^ i) '' ↑(Finset.range d) := by
    ext n
    simp_rw [Set.mem_range, Set.mem_image, Finset.mem_coe, Finset.mem_range]
    exact ⟨fun ⟨⟨i, hi⟩, hy⟩ => ⟨i, hi, hy⟩, fun ⟨i, hi, hy⟩ => ⟨⟨i, hi⟩, hy⟩⟩
  simp [this, mem_span_image_iff_linearCombination, degree_lt_iff_coeff_zero, eq_comm,
    exists_iff_exists_finsupp, coeff, aeval_def, eval₂_eq_sum, Polynomial.sum, mem_supported',
    Finsupp.sum, linearCombination, Algebra.smul_def, AddMonoidAlgebra.coeffEquiv.exists_congr_left]

中文:
定理 mem_span_pow'
  条件: {x y : S} {d : 自然数}
  证明: by
  have : (Set.range fun i : Fin d => x ^ (i : Nat)) = (fun i : Nat => x ^ i) '' ↑(Finset.range d) := by
    ext n
    simp_rw [Set.mem_range, Set.mem_image, Finset.mem_coe, Finset.mem_range]
    exact ⟨fun ⟨⟨i, hi⟩, hy⟩ => ⟨i, hi, hy⟩, fun ⟨i, hi, hy⟩ => ⟨⟨i, hi⟩, hy⟩⟩
  simp [this, mem_span_image_iff_linearCombination, degree_lt_iff_coeff_zero, eq_comm,
    exists_iff_exists_finsupp, coeff, aeval_def, eval₂_eq_sum, Polynomial.sum, mem_supported',
    Finsupp.sum, linearCombination, Algebra.smul_def, AddMonoidAlgebra.coeffEquiv.exists_congr_left]

Depends on / 依赖: AddMonoidAlgebr, Algebra, Algebra.smul_def, Finset, Finset.mem_coe, Finset.mem_range, Finset.range, Finsupp, Finsupp.sum, Polynomial, Polynomial.sum, Set.mem_image, Set.mem_range, Set.range, aeval_def, degree_lt_iff_coeff_zero, eq_comm, exists_iff_exists_finsupp, linearCombination, mem_coe
-/
theorem mem_span_pow' {x y : S} {d : Nat} :
    y in Submodule.span R (Set.range fun i : Fin d => x ^ (i : Nat)) ↔
      exists f : R[X], f.degree < d ∧ y = aeval x f := by
  have : (Set.range fun i : Fin d => x ^ (i : Nat)) = (fun i : Nat => x ^ i) '' ↑(Finset.range d) := by
    ext n
    simp_rw [Set.mem_range, Set.mem_image, Finset.mem_coe, Finset.mem_range]
    exact ⟨fun ⟨⟨i, hi⟩, hy⟩ => ⟨i, hi, hy⟩, fun ⟨i, hi, hy⟩ => ⟨⟨i, hi⟩, hy⟩⟩
  simp [this, mem_span_image_iff_linearCombination, degree_lt_iff_coeff_zero, eq_comm,
    exists_iff_exists_finsupp, coeff, aeval_def, eval₂_eq_sum, Polynomial.sum, mem_supported',
    Finsupp.sum, linearCombination, Algebra.smul_def, AddMonoidAlgebra.coeffEquiv.exists_congr_left]

/--
theorem `mem_span_pow` / 定理 `mem_span_pow`

English:
theorem mem_span_pow
  given: {x y : S} {d : Nat} (hd : d != 0)
  proof: by
  rw [mem_span_pow']
  constructor <;>
  · rintro ⟨f, h, hy⟩
    refine ⟨f, ?_, hy⟩
    by_cases hf : f = 0
    · simp only [hf, natDegree_zero, Polynomial.degree_zero] at h ⊢
      first | exact lt_of_le_of_ne (Nat.zero_le d) hd.symm | exact WithBot.bot_lt_coe d
    simpa [degree_eq_natDegree hf] using h

中文:
定理 mem_span_pow
  条件: {x y : S} {d : 自然数} (hd : d != 0)
  证明: by
  rw [mem_span_pow']
  constructor <;>
  · rintro ⟨f, h, hy⟩
    refine ⟨f, ?_, hy⟩
    by_cases hf : f = 0
    · simp only [hf, natDegree_zero, Polynomial.degree_zero] at h ⊢
      first | exact lt_of_le_of_ne (Nat.zero_le d) hd.symm | exact WithBot.bot_lt_coe d
    simpa [degree_eq_natDegree hf] using h

Depends on / 依赖: Nat.zero_le, Polynomial, Polynomial.degree_zero, WithBot, WithBot.bot_lt_coe, bot_lt_coe, degree_eq_natDegree, degree_zero, hd.symm, lt_of_le_of_ne, mem_span_pow, natDegree_zero, zero_le
-/
theorem mem_span_pow {x y : S} {d : Nat} (hd : d != 0) :
    y in Submodule.span R (Set.range fun i : Fin d => x ^ (i : Nat)) ↔
      exists f : R[X], f.natDegree < d ∧ y = aeval x f := by
  rw [mem_span_pow']
  constructor <;>
  · rintro ⟨f, h, hy⟩
    refine ⟨f, ?_, hy⟩
    by_cases hf : f = 0
    · simp only [hf, natDegree_zero, Polynomial.degree_zero] at h ⊢
      first | exact lt_of_le_of_ne (Nat.zero_le d) hd.symm | exact WithBot.bot_lt_coe d
    simpa [degree_eq_natDegree hf] using h

/--
theorem `dim_ne_zero` / 定理 `dim_ne_zero`

English:
theorem dim_ne_zero
  given: [Nontrivial S] (pb : PowerBasis R S)
  statement: pb.dim != 0
  proof: fun h =>
  not_nonempty_iff.mpr (h.symm ▸ Fin.isEmpty : IsEmpty (Fin pb.dim)) pb.basis.index_nonempty

中文:
定理 dim_ne_zero
  条件: [非平凡 S] (pb : PowerBasis R S)
  结论: pb.dim != 0
  证明: fun h =>
  not_nonempty_iff.mpr (h.symm ▸ Fin.isEmpty : IsEmpty (Fin pb.dim)) pb.basis.index_nonempty
-/
theorem dim_ne_zero [Nontrivial S] (pb : PowerBasis R S) : pb.dim != 0 := fun h =>
  not_nonempty_iff.mpr (h.symm ▸ Fin.isEmpty : IsEmpty (Fin pb.dim)) pb.basis.index_nonempty

/--
theorem `dim_pos` / 定理 `dim_pos`

English:
theorem dim_pos
  given: [Nontrivial S] (pb : PowerBasis R S)
  statement: 0 < pb.dim
  proof: Nat.pos_of_ne_zero pb.dim_ne_zero

中文:
定理 dim_pos
  条件: [非平凡 S] (pb : PowerBasis R S)
  结论: 0 < pb.dim
  证明: Nat.pos_of_ne_zero pb.dim_ne_zero

Depends on / 依赖: Nat.pos_of_ne_zero, dim_ne_zero, pb.dim_ne_zero, pos_of_ne_zero
-/
theorem dim_pos [Nontrivial S] (pb : PowerBasis R S) : 0 < pb.dim :=
  Nat.pos_of_ne_zero pb.dim_ne_zero

/--
theorem `exists_eq_aeval` / 定理 `exists_eq_aeval`

English:
theorem exists_eq_aeval
  given: [Nontrivial S] (pb : PowerBasis R S) (y : S)
  proof: (mem_span_pow pb.dim_ne_zero).mp (by simpa using pb.basis.mem_span y)

中文:
定理 存在_eq_aeval
  条件: [非平凡 S] (pb : PowerBasis R S) (y : S)
  证明: (mem_span_pow pb.dim_ne_zero).mp (by simpa using pb.basis.mem_span y)

Depends on / 依赖: dim_ne_zero, mem_span, mem_span_pow, pb.basis.mem_span, pb.dim_ne_zero
-/
theorem exists_eq_aeval [Nontrivial S] (pb : PowerBasis R S) (y : S) :
    exists f : R[X], f.natDegree < pb.dim ∧ y = aeval pb.gen f :=
  (mem_span_pow pb.dim_ne_zero).mp (by simpa using pb.basis.mem_span y)

/--
theorem `exists_eq_aeval'` / 定理 `exists_eq_aeval'`

English:
theorem exists_eq_aeval'
  given: (pb : PowerBasis R S) (y : S)
  statement: exists f : R[X], y = aeval pb.gen f
  proof: by
  nontriviality S
  obtain ⟨f, _, hf⟩ := exists_eq_aeval pb y
  exact ⟨f, hf⟩

中文:
定理 存在_eq_aeval'
  条件: (pb : PowerBasis R S) (y : S)
  结论: 存在 f : R[X], y = aeval pb.gen f
  证明: by
  nontriviality S
  obtain ⟨f, _, hf⟩ := exists_eq_aeval pb y
  exact ⟨f, hf⟩

Depends on / 依赖: exists_eq_aeval, nontriviality
-/
theorem exists_eq_aeval' (pb : PowerBasis R S) (y : S) : exists f : R[X], y = aeval pb.gen f := by
  nontriviality S
  obtain ⟨f, _, hf⟩ := exists_eq_aeval pb y
  exact ⟨f, hf⟩

/--
theorem `algHom_ext` / 定理 `algHom_ext`

English:
theorem algHom_ext
  statement: {S' : Type*} [Semiring S'] [Algebra R S'] (pb : PowerBasis R S)
  proof: by
  ext x
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' x
  rw [← Polynomial.aeval_algHom_apply]; rw [← Polynomial.aeval_algHom_apply]; rw [h]

中文:
定理 algHom_ext
  结论: {S' : 类型} [半环 S'] [代数 R S'] (pb : PowerBasis R S)
  证明: by
  ext x
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' x
  rw [← Polynomial.aeval_algHom_apply]; rw [← Polynomial.aeval_algHom_apply]; rw [h]

Depends on / 依赖: Polynomial, Polynomial.aeval_algHom_apply, aeval_algHom_apply, exists_eq_aeval, pb.exists_eq_aeval
-/
theorem algHom_ext {S' : Type*} [Semiring S'] [Algebra R S'] (pb : PowerBasis R S)
    ⦃f g : S ->ₐ[R] S'⦄ (h : f pb.gen = g pb.gen) : f = g := by
  ext x
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' x
  rw [← Polynomial.aeval_algHom_apply]; rw [← Polynomial.aeval_algHom_apply]; rw [h]

open Ideal Finset Submodule in
/--
theorem `exists_smodEq` / 定理 `exists_smodEq`

English:
theorem exists_smodEq
  given: (pb : PowerBasis A B) (b : B)
  proof: by
  rcases subsingleton_or_nontrivial B
  · exact ⟨0, by rw [SModEq, Subsingleton.eq_zero b, map_zero]⟩
  refine ⟨pb.basis.repr b ⟨0, pb.dim_pos⟩, ?_⟩
  have H := pb.basis.sum_repr b
  rw [← insert_erase (mem_univ ⟨0]; rw [pb.dim_pos⟩)]; rw [sum_insert (notMem_erase _ _)] at H
  rw [SModEq]; rw [← add_zero (algebraMap _ _ _)]; rw [Quotient.mk_add]
  nth_rewrite 1 [← H]
  rw [Quotient.mk_add]
  congr 1
  · simp [Algebra.algebraMap_eq_smul_one ((pb.basis.repr b) _)]
  · rw [Quotient.mk_zero, Quotient.mk_eq_zero, coe_basis]
    refine sum_mem _ (fun i hi => ?_)
    rw [Algebra.smul_def']
refine Ideal.mul_mem_left _ _ Ideal.pow_mem_of_mem _ (Ideal.subset_span (by simp)) _
Nat.pos_of_ne_zero fun h => notMem_erase i univ Fin.eq_mk_iff_val_eq.2 h ▸ hi

中文:
定理 存在_smodEq
  条件: (pb : PowerBasis A B) (b : B)
  证明: by
  rcases subsingleton_or_nontrivial B
  · exact ⟨0, by rw [SModEq, Subsingleton.eq_zero b, map_zero]⟩
  refine ⟨pb.basis.repr b ⟨0, pb.dim_pos⟩, ?_⟩
  have H := pb.basis.sum_repr b
  rw [← insert_erase (mem_univ ⟨0]; rw [pb.dim_pos⟩)]; rw [sum_insert (notMem_erase _ _)] at H
  rw [SModEq]; rw [← add_zero (algebraMap _ _ _)]; rw [Quotient.mk_add]
  nth_rewrite 1 [← H]
  rw [Quotient.mk_add]
  congr 1
  · simp [Algebra.algebraMap_eq_smul_one ((pb.basis.repr b) _)]
  · rw [Quotient.mk_zero, Quotient.mk_eq_zero, coe_basis]
    refine sum_mem _ (fun i hi => ?_)
    rw [Algebra.smul_def']
refine Ideal.mul_mem_left _ _ Ideal.pow_mem_of_mem _ (Ideal.subset_span (by simp)) _
Nat.pos_of_ne_zero fun h => notMem_erase i univ Fin.eq_mk_iff_val_eq.2 h ▸ hi

Depends on / 依赖: Algebra, Algebra.algebraMap_eq_smul_one, Quotient, Quotient.mk_add, Quotient.mk_eq_zero, Quotient.mk_zero, SModEq, Subsingleton, Subsingleton.eq_zero, add_zero, algebraMap, algebraMap_eq_smul_one, coe_b, dim_pos, eq_zero, insert_erase, map_zero, mem_univ, mk_add, mk_eq_zero
-/
theorem exists_smodEq (pb : PowerBasis A B) (b : B) :
    exists a, SModEq (Ideal.span ({pb.gen})) b (algebraMap A B a) := by
  rcases subsingleton_or_nontrivial B
  · exact ⟨0, by rw [SModEq, Subsingleton.eq_zero b, map_zero]⟩
  refine ⟨pb.basis.repr b ⟨0, pb.dim_pos⟩, ?_⟩
  have H := pb.basis.sum_repr b
  rw [← insert_erase (mem_univ ⟨0]; rw [pb.dim_pos⟩)]; rw [sum_insert (notMem_erase _ _)] at H
  rw [SModEq]; rw [← add_zero (algebraMap _ _ _)]; rw [Quotient.mk_add]
  nth_rewrite 1 [← H]
  rw [Quotient.mk_add]
  congr 1
  · simp [Algebra.algebraMap_eq_smul_one ((pb.basis.repr b) _)]
  · rw [Quotient.mk_zero, Quotient.mk_eq_zero, coe_basis]
    refine sum_mem _ (fun i hi => ?_)
    rw [Algebra.smul_def']
refine Ideal.mul_mem_left _ _ Ideal.pow_mem_of_mem _ (Ideal.subset_span (by simp)) _
Nat.pos_of_ne_zero fun h => notMem_erase i univ Fin.eq_mk_iff_val_eq.2 h ▸ hi

open Submodule.Quotient in
/--
theorem `exists_gen_dvd_sub` / 定理 `exists_gen_dvd_sub`

English:
theorem exists_gen_dvd_sub
  given: (pb : PowerBasis A B) (b : B)
  statement: exists a, pb.gen ∣ b - algebraMap A B a
  proof: by
  simpa [← Ideal.mem_span_singleton, ← mk_eq_zero, mk_sub, sub_eq_zero] using! pb.exists_smodEq b

中文:
定理 存在_gen_dvd_sub
  条件: (pb : PowerBasis A B) (b : B)
  结论: 存在 a, pb.gen ∣ b - algebraMap A B a
  证明: by
  simpa [← Ideal.mem_span_singleton, ← mk_eq_zero, mk_sub, sub_eq_zero] using! pb.exists_smodEq b

Depends on / 依赖: Ideal.mem_span_singleton, exists_smodEq, mem_span_singleton, mk_eq_zero, mk_sub, pb.exists_smodEq, sub_eq_zero
-/
theorem exists_gen_dvd_sub (pb : PowerBasis A B) (b : B) : exists a, pb.gen ∣ b - algebraMap A B a := by
  simpa [← Ideal.mem_span_singleton, ← mk_eq_zero, mk_sub, sub_eq_zero] using! pb.exists_smodEq b

section minpoly

variable [Algebra A S]

/--
Definition of `minpolyGen` / `minpolyGen` 的定义

English:
definition minpolyGen
  signature: (pb : PowerBasis A S)
  body: X ^ pb.dim - ∑ i : Fin pb.dim, C (pb.basis.repr (pb.gen ^ pb.dim) i) * X ^ (i : Nat)

中文:
定义 minpolyGen
  签名: (pb : PowerBasis A S)
  定义体: X ^ pb.dim - ∑ i : Fin pb.dim, C (pb.basis.repr (pb.gen ^ pb.dim) i) * X ^ (i : Nat)

Depends on / 依赖: pb.basis.repr, pb.dim, pb.gen
-/
noncomputable def minpolyGen (pb : PowerBasis A S) : A[X] :=
  X ^ pb.dim - ∑ i : Fin pb.dim, C (pb.basis.repr (pb.gen ^ pb.dim) i) * X ^ (i : Nat)

/--
theorem `aeval_minpolyGen` / 定理 `aeval_minpolyGen`

English:
theorem aeval_minpolyGen
  given: (pb : PowerBasis A S)
  statement: aeval pb.gen (minpolyGen pb) = 0
  proof: by
  simp_rw [minpolyGen, map_sub, map_sum, map_mul, map_pow, aeval_C, ← Algebra.smul_def, aeval_X]
  refine sub_eq_zero.mpr ((pb.basis.linearCombination_repr (pb.gen ^ pb.dim)).symm.trans ?_)
  rw [Finsupp.linearCombination_apply]; rw [Finsupp.sum_fintype] <;>
    simp only [pb.coe_basis, zero_smul, imp_true_iff]

中文:
定理 aeval_minpolyGen
  条件: (pb : PowerBasis A S)
  结论: aeval pb.gen (minpolyGen pb) = 0
  证明: by
  simp_rw [minpolyGen, map_sub, map_sum, map_mul, map_pow, aeval_C, ← Algebra.smul_def, aeval_X]
  refine sub_eq_zero.mpr ((pb.basis.linearCombination_repr (pb.gen ^ pb.dim)).symm.trans ?_)
  rw [Finsupp.linearCombination_apply]; rw [Finsupp.sum_fintype] <;>
    simp only [pb.coe_basis, zero_smul, imp_true_iff]

Depends on / 依赖: Algebra, Algebra.smul_def, Finsupp, Finsupp.linearCombination_apply, Finsupp.sum_fintype, aeval_C, aeval_X, coe_basis, imp_true_iff, linearCombination_apply, linearCombination_repr, map_mul, map_pow, map_sub, map_sum, minpolyGen, pb.basis.linearCombination_repr, pb.coe_basis, pb.dim, pb.gen
-/
theorem aeval_minpolyGen (pb : PowerBasis A S) : aeval pb.gen (minpolyGen pb) = 0 := by
  simp_rw [minpolyGen, map_sub, map_sum, map_mul, map_pow, aeval_C, ← Algebra.smul_def, aeval_X]
  refine sub_eq_zero.mpr ((pb.basis.linearCombination_repr (pb.gen ^ pb.dim)).symm.trans ?_)
  rw [Finsupp.linearCombination_apply]; rw [Finsupp.sum_fintype] <;>
    simp only [pb.coe_basis, zero_smul, imp_true_iff]

/--
theorem `minpolyGen_monic` / 定理 `minpolyGen_monic`

English:
theorem minpolyGen_monic
  given: (pb : PowerBasis A S)
  statement: Monic (minpolyGen pb)
  proof: by
  nontriviality A
  apply (monic_X_pow _).sub_of_left _
  rw [degree_X_pow]
  exact degree_sum_fin_lt _

中文:
定理 minpolyGen_monic
  条件: (pb : PowerBasis A S)
  结论: Monic (minpolyGen pb)
  证明: by
  nontriviality A
  apply (monic_X_pow _).sub_of_left _
  rw [degree_X_pow]
  exact degree_sum_fin_lt _

Depends on / 依赖: degree_X_pow, degree_sum_fin_lt, monic_X_pow, nontriviality, sub_of_left
-/
theorem minpolyGen_monic (pb : PowerBasis A S) : Monic (minpolyGen pb) := by
  nontriviality A
  apply (monic_X_pow _).sub_of_left _
  rw [degree_X_pow]
  exact degree_sum_fin_lt _

/--
theorem `dim_le_natDegree_of_root` / 定理 `dim_le_natDegree_of_root`

English:
theorem dim_le_natDegree_of_root
  statement: (pb : PowerBasis A S) {p : A[X]} (ne_zero : p != 0)
  proof: by
  refine le_of_not_gt fun hlt => ne_zero ?_
  rw [p.as_sum_range' _ hlt]; rw [Finset.sum_range]
  refine Fintype.sum_eq_zero _ fun i => ?_
  simp_rw [aeval_eq_sum_range' hlt, Finset.sum_range, ← pb.basis_eq_pow] at root
  have := Fintype.linearIndependent_iff.1 pb.basis.linearIndependent _ root
  rw [this]; rw [monomial_zero_right]

中文:
定理 dim_le_natDegree_of_root
  结论: (pb : PowerBasis A S) {p : A[X]} (ne_zero : p != 0)
  证明: by
  refine le_of_not_gt fun hlt => ne_zero ?_
  rw [p.as_sum_range' _ hlt]; rw [Finset.sum_range]
  refine Fintype.sum_eq_zero _ fun i => ?_
  simp_rw [aeval_eq_sum_range' hlt, Finset.sum_range, ← pb.basis_eq_pow] at root
  have := Fintype.linearIndependent_iff.1 pb.basis.linearIndependent _ root
  rw [this]; rw [monomial_zero_right]

Depends on / 依赖: Finset, Finset.sum_range, Fintype, Fintype.linearIndependent_iff, Fintype.sum_eq_zero, aeval_eq_sum_range, as_sum_range, basis_eq_pow, le_of_not_gt, linearIndependent, linearIndependent_iff, monomial_zero_right, ne_zero, p.as_sum_range, pb.basis.linearIndependent, pb.basis_eq_pow, simp_rw, sum_eq_zero, sum_range
-/
theorem dim_le_natDegree_of_root (pb : PowerBasis A S) {p : A[X]} (ne_zero : p != 0)
    (root : aeval pb.gen p = 0) : pb.dim <= p.natDegree := by
  refine le_of_not_gt fun hlt => ne_zero ?_
  rw [p.as_sum_range' _ hlt]; rw [Finset.sum_range]
  refine Fintype.sum_eq_zero _ fun i => ?_
  simp_rw [aeval_eq_sum_range' hlt, Finset.sum_range, ← pb.basis_eq_pow] at root
  have := Fintype.linearIndependent_iff.1 pb.basis.linearIndependent _ root
  rw [this]; rw [monomial_zero_right]

/--
theorem `dim_le_degree_of_root` / 定理 `dim_le_degree_of_root`

English:
theorem dim_le_degree_of_root
  statement: (h : PowerBasis A S) {p : A[X]} (ne_zero : p != 0)
  proof: by
  rw [degree_eq_natDegree ne_zero]
  exact WithBot.coe_le_coe.2 (h.dim_le_natDegree_of_root ne_zero root)

中文:
定理 dim_le_degree_of_root
  结论: (h : PowerBasis A S) {p : A[X]} (ne_zero : p != 0)
  证明: by
  rw [degree_eq_natDegree ne_zero]
  exact WithBot.coe_le_coe.2 (h.dim_le_natDegree_of_root ne_zero root)

Depends on / 依赖: WithBot, WithBot.coe_le_coe, coe_le_coe, degree_eq_natDegree, dim_le_natDegree_of_root, h.dim_le_natDegree_of_root, ne_zero
-/
theorem dim_le_degree_of_root (h : PowerBasis A S) {p : A[X]} (ne_zero : p != 0)
    (root : aeval h.gen p = 0) : ↑h.dim <= p.degree := by
  rw [degree_eq_natDegree ne_zero]
  exact WithBot.coe_le_coe.2 (h.dim_le_natDegree_of_root ne_zero root)

/--
theorem `degree_minpolyGen` / 定理 `degree_minpolyGen`

English:
theorem degree_minpolyGen
  given: [Nontrivial A] (pb : PowerBasis A S)
  proof: by
  unfold minpolyGen
  rw [degree_sub_eq_left_of_degree_lt] <;> rw [degree_X_pow]
  apply degree_sum_fin_lt

中文:
定理 degree_minpolyGen
  条件: [非平凡 A] (pb : PowerBasis A S)
  证明: by
  unfold minpolyGen
  rw [degree_sub_eq_left_of_degree_lt] <;> rw [degree_X_pow]
  apply degree_sum_fin_lt

Depends on / 依赖: degree_X_pow, degree_sub_eq_left_of_degree_lt, degree_sum_fin_lt, minpolyGen
-/
theorem degree_minpolyGen [Nontrivial A] (pb : PowerBasis A S) :
    degree (minpolyGen pb) = pb.dim := by
  unfold minpolyGen
  rw [degree_sub_eq_left_of_degree_lt] <;> rw [degree_X_pow]
  apply degree_sum_fin_lt

/--
theorem `natDegree_minpolyGen` / 定理 `natDegree_minpolyGen`

English:
theorem natDegree_minpolyGen
  given: [Nontrivial A] (pb : PowerBasis A S)
  proof: natDegree_eq_of_degree_eq_some pb.degree_minpolyGen

@[simp]

中文:
定理 natDegree_minpolyGen
  条件: [非平凡 A] (pb : PowerBasis A S)
  证明: natDegree_eq_of_degree_eq_some pb.degree_minpolyGen

@[simp]

Depends on / 依赖: degree_minpolyGen, natDegree_eq_of_degree_eq_some, pb.degree_minpolyGen
-/
theorem natDegree_minpolyGen [Nontrivial A] (pb : PowerBasis A S) :
    natDegree (minpolyGen pb) = pb.dim :=
  natDegree_eq_of_degree_eq_some pb.degree_minpolyGen

@[simp]
/--
theorem `minpolyGen_eq` / 定理 `minpolyGen_eq`

English:
theorem minpolyGen_eq
  given: (pb : PowerBasis A S)
  statement: pb.minpolyGen = minpoly A pb.gen
  proof: by
  nontriviality A
  refine minpoly.unique' A _ pb.minpolyGen_monic pb.aeval_minpolyGen fun q hq =>
    or_iff_not_imp_left.2 fun hn0 h0 => ?_
  exact (pb.dim_le_degree_of_root hn0 h0).not_gt (pb.degree_minpolyGen ▸ hq)

中文:
定理 minpolyGen_eq
  条件: (pb : PowerBasis A S)
  结论: pb.minpolyGen = minpoly A pb.gen
  证明: by
  nontriviality A
  refine minpoly.unique' A _ pb.minpolyGen_monic pb.aeval_minpolyGen fun q hq =>
    or_iff_not_imp_left.2 fun hn0 h0 => ?_
  exact (pb.dim_le_degree_of_root hn0 h0).not_gt (pb.degree_minpolyGen ▸ hq)

Depends on / 依赖: aeval_minpolyGen, degree_minpolyGen, dim_le_degree_of_root, minpoly, minpoly.unique, minpolyGen_monic, nontriviality, not_gt, or_iff_not_imp_left, pb.aeval_minpolyGen, pb.degree_minpolyGen, pb.dim_le_degree_of_root, pb.minpolyGen_monic, unique
-/
theorem minpolyGen_eq (pb : PowerBasis A S) : pb.minpolyGen = minpoly A pb.gen := by
  nontriviality A
  refine minpoly.unique' A _ pb.minpolyGen_monic pb.aeval_minpolyGen fun q hq =>
    or_iff_not_imp_left.2 fun hn0 h0 => ?_
  exact (pb.dim_le_degree_of_root hn0 h0).not_gt (pb.degree_minpolyGen ▸ hq)

/--
theorem `isIntegral_gen` / 定理 `isIntegral_gen`

English:
theorem isIntegral_gen
  given: (pb : PowerBasis A S)
  statement: IsIntegral A pb.gen
  proof: ⟨minpolyGen pb, minpolyGen_monic pb, aeval_minpolyGen pb⟩

@[simp]

中文:
定理 is整数egral_gen
  条件: (pb : PowerBasis A S)
  结论: 是整 A pb.gen
  证明: ⟨minpolyGen pb, minpolyGen_monic pb, aeval_minpolyGen pb⟩

@[simp]

Depends on / 依赖: aeval_minpolyGen, minpolyGen, minpolyGen_monic
-/
theorem isIntegral_gen (pb : PowerBasis A S) : IsIntegral A pb.gen :=
  ⟨minpolyGen pb, minpolyGen_monic pb, aeval_minpolyGen pb⟩

@[simp]
/--
theorem `degree_minpoly` / 定理 `degree_minpoly`

English:
theorem degree_minpoly
  given: [Nontrivial A] (pb : PowerBasis A S)
  proof: by rw [← minpolyGen_eq, degree_minpolyGen]

@[simp]

中文:
定理 degree_minpoly
  条件: [非平凡 A] (pb : PowerBasis A S)
  证明: by rw [← minpolyGen_eq, degree_minpolyGen]

@[simp]

Depends on / 依赖: degree_minpolyGen, minpolyGen_eq
-/
theorem degree_minpoly [Nontrivial A] (pb : PowerBasis A S) :
    degree (minpoly A pb.gen) = pb.dim := by rw [← minpolyGen_eq, degree_minpolyGen]

@[simp]
/--
theorem `natDegree_minpoly` / 定理 `natDegree_minpoly`

English:
theorem natDegree_minpoly
  given: [Nontrivial A] (pb : PowerBasis A S)
  proof: by rw [← minpolyGen_eq, natDegree_minpolyGen]

中文:
定理 natDegree_minpoly
  条件: [非平凡 A] (pb : PowerBasis A S)
  证明: by rw [← minpolyGen_eq, natDegree_minpolyGen]

Depends on / 依赖: minpolyGen_eq, natDegree_minpolyGen
-/
theorem natDegree_minpoly [Nontrivial A] (pb : PowerBasis A S) :
    (minpoly A pb.gen).natDegree = pb.dim := by rw [← minpolyGen_eq, natDegree_minpolyGen]

/--
theorem `leftMulMatrix` / 定理 `leftMulMatrix`

English:
theorem leftMulMatrix
  given: (pb : PowerBasis A S)
  statement: Algebra.leftMulMatrix pb.basis pb.gen =
  proof: by
  cases subsingleton_or_nontrivial A; · subsingleton
  rw [Algebra.leftMulMatrix_apply]; rw [← LinearEquiv.eq_symm_apply]; rw [LinearMap.toMatrix_symm]
  refine pb.basis.ext fun k => ?_
  simp_rw [Matrix.toLin_self, Matrix.of_apply, pb.basis_eq_pow]
  apply (pow_succ' _ _).symm.trans
  split_ifs with h
  · simp_rw [h, neg_smul, Finset.sum_neg_distrib, eq_neg_iff_add_eq_zero]
    convert! pb.aeval_minpolyGen
    rw [add_comm]; rw [aeval_eq_sum_range]; rw [Finset.sum_range_succ]; rw [← leadingCoeff]; rw [pb.minpolyGen_monic.leadingCoeff]; rw [one_smul]; rw [natDegree_minpolyGen]; rw [Finset.sum_range]
  · rw [Fintype.sum_eq_single (⟨(k : Nat) + 1, lt_of_le_of_ne k.2 h⟩ : Fin pb.dim), if_pos, one_smul]
    · rfl
    intro x hx
    rw [if_neg]; rw [zero_smul]
    apply mt Fin.ext hx

中文:
定理 leftMulMatrix
  条件: (pb : PowerBasis A S)
  结论: 代数.leftMulMatrix pb.basis pb.gen =
  证明: by
  cases subsingleton_or_nontrivial A; · subsingleton
  rw [Algebra.leftMulMatrix_apply]; rw [← LinearEquiv.eq_symm_apply]; rw [LinearMap.toMatrix_symm]
  refine pb.basis.ext fun k => ?_
  simp_rw [Matrix.toLin_self, Matrix.of_apply, pb.basis_eq_pow]
  apply (pow_succ' _ _).symm.trans
  split_ifs with h
  · simp_rw [h, neg_smul, Finset.sum_neg_distrib, eq_neg_iff_add_eq_zero]
    convert! pb.aeval_minpolyGen
    rw [add_comm]; rw [aeval_eq_sum_range]; rw [Finset.sum_range_succ]; rw [← leadingCoeff]; rw [pb.minpolyGen_monic.leadingCoeff]; rw [one_smul]; rw [natDegree_minpolyGen]; rw [Finset.sum_range]
  · rw [Fintype.sum_eq_single (⟨(k : Nat) + 1, lt_of_le_of_ne k.2 h⟩ : Fin pb.dim), if_pos, one_smul]
    · rfl
    intro x hx
    rw [if_neg]; rw [zero_smul]
    apply mt Fin.ext hx
-/
protected theorem leftMulMatrix (pb : PowerBasis A S) : Algebra.leftMulMatrix pb.basis pb.gen =
    @Matrix.of (Fin pb.dim) (Fin pb.dim) _ fun i j =>
      if ↑j + 1 = pb.dim then -pb.minpolyGen.coeff ↑i else if (i : Nat) = j + 1 then 1 else 0 := by
  cases subsingleton_or_nontrivial A; · subsingleton
  rw [Algebra.leftMulMatrix_apply]; rw [← LinearEquiv.eq_symm_apply]; rw [LinearMap.toMatrix_symm]
  refine pb.basis.ext fun k => ?_
  simp_rw [Matrix.toLin_self, Matrix.of_apply, pb.basis_eq_pow]
  apply (pow_succ' _ _).symm.trans
  split_ifs with h
  · simp_rw [h, neg_smul, Finset.sum_neg_distrib, eq_neg_iff_add_eq_zero]
    convert! pb.aeval_minpolyGen
    rw [add_comm]; rw [aeval_eq_sum_range]; rw [Finset.sum_range_succ]; rw [← leadingCoeff]; rw [pb.minpolyGen_monic.leadingCoeff]; rw [one_smul]; rw [natDegree_minpolyGen]; rw [Finset.sum_range]
  · rw [Fintype.sum_eq_single (⟨(k : Nat) + 1, lt_of_le_of_ne k.2 h⟩ : Fin pb.dim), if_pos, one_smul]
    · rfl
    intro x hx
    rw [if_neg]; rw [zero_smul]
    apply mt Fin.ext hx

end minpoly

section Equiv

variable [Algebra A S] {S' : Type*} [Ring S'] [Algebra A S']

/--
theorem `constr_pow_aeval` / 定理 `constr_pow_aeval`

English:
theorem constr_pow_aeval
  statement: (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0)
  proof: by
  cases subsingleton_or_nontrivial A
  · rw [(Subsingleton.elim _ _ : f = 0), aeval_zero, map_zero, aeval_zero]
  rw [← aeval_modByMonic_eq_self_of_root (minpoly.aeval _ _)]; rw [← aeval_modByMonic_eq_self_of_root hy]
  by_cases hf : f %ₘ minpoly A pb.gen = 0
  · simp only [hf, map_zero]
  have : (f %ₘ minpoly A pb.gen).natDegree < pb.dim := by
    rw [← pb.natDegree_minpoly]
    apply natDegree_lt_natDegree hf
    exact degree_modByMonic_lt _ (minpoly.monic pb.isIntegral_gen)
  rw [aeval_eq_sum_range' this]; rw [aeval_eq_sum_range' this]; rw [map_sum]
  refine Finset.sum_congr rfl fun i (hi : i in Finset.range pb.dim) => ?_
  rw [Finset.mem_range] at hi
  rw [map_smul]
  congr
  rw [← Fin.val_mk hi]; rw [← pb.basis_eq_pow ⟨i]; rw [hi⟩]; rw [Basis.constr_basis]

中文:
定理 constr_pow_aeval
  结论: (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0)
  证明: by
  cases subsingleton_or_nontrivial A
  · rw [(Subsingleton.elim _ _ : f = 0), aeval_zero, map_zero, aeval_zero]
  rw [← aeval_modByMonic_eq_self_of_root (minpoly.aeval _ _)]; rw [← aeval_modByMonic_eq_self_of_root hy]
  by_cases hf : f %ₘ minpoly A pb.gen = 0
  · simp only [hf, map_zero]
  have : (f %ₘ minpoly A pb.gen).natDegree < pb.dim := by
    rw [← pb.natDegree_minpoly]
    apply natDegree_lt_natDegree hf
    exact degree_modByMonic_lt _ (minpoly.monic pb.isIntegral_gen)
  rw [aeval_eq_sum_range' this]; rw [aeval_eq_sum_range' this]; rw [map_sum]
  refine Finset.sum_congr rfl fun i (hi : i in Finset.range pb.dim) => ?_
  rw [Finset.mem_range] at hi
  rw [map_smul]
  congr
  rw [← Fin.val_mk hi]; rw [← pb.basis_eq_pow ⟨i]; rw [hi⟩]; rw [Basis.constr_basis]

Depends on / 依赖: Subsingleton, Subsingleton.elim, aeval_eq_sum_range, aeval_modByMonic_eq_self_of_root, aeval_zero, degree_modByMonic_lt, isIntegral_gen, map_zero, minpoly, minpoly.aeval, minpoly.monic, natDegree, natDegree_lt_natDegree, natDegree_minpoly, pb.dim, pb.gen, pb.isIntegral_gen, pb.natDegree_minpoly, subsingleton_or_nontrivial
-/
theorem constr_pow_aeval (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0)
    (f : A[X]) : pb.basis.constr A (fun i => y ^ (i : Nat)) (aeval pb.gen f) = aeval y f := by
  cases subsingleton_or_nontrivial A
  · rw [(Subsingleton.elim _ _ : f = 0), aeval_zero, map_zero, aeval_zero]
  rw [← aeval_modByMonic_eq_self_of_root (minpoly.aeval _ _)]; rw [← aeval_modByMonic_eq_self_of_root hy]
  by_cases hf : f %ₘ minpoly A pb.gen = 0
  · simp only [hf, map_zero]
  have : (f %ₘ minpoly A pb.gen).natDegree < pb.dim := by
    rw [← pb.natDegree_minpoly]
    apply natDegree_lt_natDegree hf
    exact degree_modByMonic_lt _ (minpoly.monic pb.isIntegral_gen)
  rw [aeval_eq_sum_range' this]; rw [aeval_eq_sum_range' this]; rw [map_sum]
  refine Finset.sum_congr rfl fun i (hi : i in Finset.range pb.dim) => ?_
  rw [Finset.mem_range] at hi
  rw [map_smul]
  congr
  rw [← Fin.val_mk hi]; rw [← pb.basis_eq_pow ⟨i]; rw [hi⟩]; rw [Basis.constr_basis]

/--
theorem `constr_pow_gen` / 定理 `constr_pow_gen`

English:
theorem constr_pow_gen
  given: (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0)
  proof: by
  convert! pb.constr_pow_aeval hy X <;> rw [aeval_X]

中文:
定理 constr_pow_gen
  条件: (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0)
  证明: by
  convert! pb.constr_pow_aeval hy X <;> rw [aeval_X]

Depends on / 依赖: aeval_X, constr_pow_aeval, convert, pb.constr_pow_aeval
-/
theorem constr_pow_gen (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0) :
    pb.basis.constr A (fun i => y ^ (i : Nat)) pb.gen = y := by
  convert! pb.constr_pow_aeval hy X <;> rw [aeval_X]

/--
theorem `constr_pow_algebraMap` / 定理 `constr_pow_algebraMap`

English:
theorem constr_pow_algebraMap
  statement: (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0)
  proof: by
  convert! pb.constr_pow_aeval hy (C x) <;> rw [aeval_C]

中文:
定理 constr_pow_algebraMap
  结论: (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0)
  证明: by
  convert! pb.constr_pow_aeval hy (C x) <;> rw [aeval_C]

Depends on / 依赖: aeval_C, constr_pow_aeval, convert, pb.constr_pow_aeval
-/
theorem constr_pow_algebraMap (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0)
    (x : A) : pb.basis.constr A (fun i => y ^ (i : Nat)) (algebraMap A S x) = algebraMap A S' x := by
  convert! pb.constr_pow_aeval hy (C x) <;> rw [aeval_C]

/--
theorem `constr_pow_mul` / 定理 `constr_pow_mul`

English:
theorem constr_pow_mul
  statement: (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0)
  proof: by
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' x
  obtain ⟨g, rfl⟩ := pb.exists_eq_aeval' x'
  simp only [← aeval_mul, pb.constr_pow_aeval hy]

中文:
定理 constr_pow_mul
  结论: (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0)
  证明: by
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' x
  obtain ⟨g, rfl⟩ := pb.exists_eq_aeval' x'
  simp only [← aeval_mul, pb.constr_pow_aeval hy]

Depends on / 依赖: aeval_mul, constr_pow_aeval, exists_eq_aeval, pb.constr_pow_aeval, pb.exists_eq_aeval
-/
theorem constr_pow_mul (pb : PowerBasis A S) {y : S'} (hy : aeval y (minpoly A pb.gen) = 0)
    (x x' : S) : pb.basis.constr A (fun i => y ^ (i : Nat)) (x * x') =
      pb.basis.constr A (fun i => y ^ (i : Nat)) x * pb.basis.constr A (fun i => y ^ (i : Nat)) x' := by
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' x
  obtain ⟨g, rfl⟩ := pb.exists_eq_aeval' x'
  simp only [← aeval_mul, pb.constr_pow_aeval hy]

/--
Definition of `lift` / `lift` 的定义

English:
definition lift
  signature: (pb : PowerBasis A S) (y : S') (hy : aeval y (minpoly A pb.gen) = 0)
  body: { pb.basis.constr A fun i => y ^ (i : Nat) with
    map_one' := by convert! pb.constr_pow_algebraMap hy 1 using 2 <;> rw [map_one]
    map_zero' := by convert! pb.constr_pow_algebraMap hy 0 using 2 <;> rw [map_zero]
    map_mul' := pb.constr_pow_mul hy
    commutes' := pb.constr_pow_algebraMap hy }

@[simp]

中文:
定义 lift
  签名: (pb : PowerBasis A S) (y : S') (hy : aeval y (minpoly A pb.gen) = 0)
  定义体: { pb.basis.constr A fun i => y ^ (i : Nat) with
    map_one' := by convert! pb.constr_pow_algebraMap hy 1 using 2 <;> rw [map_one]
    map_zero' := by convert! pb.constr_pow_algebraMap hy 0 using 2 <;> rw [map_zero]
    map_mul' := pb.constr_pow_mul hy
    commutes' := pb.constr_pow_algebraMap hy }

@[simp]

Depends on / 依赖: commutes, constr, constr_pow_algebraMap, constr_pow_mul, convert, map_mul, map_one, map_zero, pb.basis.constr, pb.constr_pow_algebraMap, pb.constr_pow_mul
-/
noncomputable def lift (pb : PowerBasis A S) (y : S') (hy : aeval y (minpoly A pb.gen) = 0) :
    S ->ₐ[A] S' :=
  { pb.basis.constr A fun i => y ^ (i : Nat) with
    map_one' := by convert! pb.constr_pow_algebraMap hy 1 using 2 <;> rw [map_one]
    map_zero' := by convert! pb.constr_pow_algebraMap hy 0 using 2 <;> rw [map_zero]
    map_mul' := pb.constr_pow_mul hy
    commutes' := pb.constr_pow_algebraMap hy }

@[simp]
/--
theorem `lift_gen` / 定理 `lift_gen`

English:
theorem lift_gen
  given: (pb : PowerBasis A S) (y : S') (hy : aeval y (minpoly A pb.gen) = 0)
  proof: pb.constr_pow_gen hy

@[simp]

中文:
定理 lift_gen
  条件: (pb : PowerBasis A S) (y : S') (hy : aeval y (minpoly A pb.gen) = 0)
  证明: pb.constr_pow_gen hy

@[simp]

Depends on / 依赖: constr_pow_gen, pb.constr_pow_gen
-/
theorem lift_gen (pb : PowerBasis A S) (y : S') (hy : aeval y (minpoly A pb.gen) = 0) :
    pb.lift y hy pb.gen = y :=
  pb.constr_pow_gen hy

@[simp]
/--
theorem `lift_aeval` / 定理 `lift_aeval`

English:
theorem lift_aeval
  given: (pb : PowerBasis A S) (y : S') (hy : aeval y (minpoly A pb.gen) = 0) (f : A[X])
  proof: pb.constr_pow_aeval hy f

中文:
定理 lift_aeval
  条件: (pb : PowerBasis A S) (y : S') (hy : aeval y (minpoly A pb.gen) = 0) (f : A[X])
  证明: pb.constr_pow_aeval hy f

Depends on / 依赖: constr_pow_aeval, pb.constr_pow_aeval
-/
theorem lift_aeval (pb : PowerBasis A S) (y : S') (hy : aeval y (minpoly A pb.gen) = 0) (f : A[X]) :
    pb.lift y hy (aeval pb.gen f) = aeval y f :=
  pb.constr_pow_aeval hy f

/-- `pb.liftEquiv` states that roots of the minimal polynomial of `pb.gen` correspond to
maps sending `pb.gen` to that root.

This is the bundled equiv version of `PowerBasis.lift`.
If the codomain of the `AlgHom`s is an integral domain, then the roots form a multiset,
see `liftEquiv'` for the corresponding statement.
-/
@[simps]
/--
Definition of `liftEquiv` / `liftEquiv` 的定义

English:
definition liftEquiv
  signature: (pb : PowerBasis A S)
  body: ⟨f pb.gen, by rw [aeval_algHom_apply, minpoly.aeval, map_zero]⟩
  invFun y := pb.lift y y.2
left_inv _ := pb.algHom_ext lift_gen _ _ _
right_inv y := Subtype.ext lift_gen _ _ y.prop

#adaptation_note

中文:
定义 liftEquiv
  签名: (pb : PowerBasis A S)
  定义体: ⟨f pb.gen, by rw [aeval_algHom_apply, minpoly.aeval, map_zero]⟩
  invFun y := pb.lift y y.2
left_inv _ := pb.algHom_ext lift_gen _ _ _
right_inv y := Subtype.ext lift_gen _ _ y.prop

#adaptation_note

Depends on / 依赖: aeval_algHom_apply, map_zero, minpoly, minpoly.aeval, pb.gen
-/
noncomputable def liftEquiv (pb : PowerBasis A S) :
    (S ->ₐ[A] S') ≃ { y : S' // aeval y (minpoly A pb.gen) = 0 } where
  toFun f := ⟨f pb.gen, by rw [aeval_algHom_apply, minpoly.aeval, map_zero]⟩
  invFun y := pb.lift y y.2
left_inv _ := pb.algHom_ext lift_gen _ _ _
right_inv y := Subtype.ext lift_gen _ _ y.prop

#adaptation_note
/-- `respectTransparency.types true` changes the auto-generated lemmas' signature -/
set_option backward.isDefEq.respectTransparency.types false in
/-- `pb.liftEquiv'` states that elements of the root set of the minimal
polynomial of `pb.gen` correspond to maps sending `pb.gen` to that root. -/
@[simps! -fullyApplied]
/--
Definition of `liftEquiv'` / `liftEquiv'` 的定义

English:
definition liftEquiv'
  signature: [IsDomain B] (pb : PowerBasis A S)
  body: pb.liftEquiv.trans ((Equiv.refl _).subtypeEquiv fun x => by
    rw [Equiv.refl_apply]; rw [mem_roots_iff_aeval_eq_zero]
    · simp
    · exact map_monic_ne_zero (minpoly.monic pb.isIntegral_gen))

中文:
定义 liftEquiv'
  签名: [是整环 B] (pb : PowerBasis A S)
  定义体: pb.liftEquiv.trans ((Equiv.refl _).subtypeEquiv fun x => by
    rw [Equiv.refl_apply]; rw [mem_roots_iff_aeval_eq_zero]
    · simp
    · exact map_monic_ne_zero (minpoly.monic pb.isIntegral_gen))

Depends on / 依赖: BaireSpace, BaireSpace.of_completelyPseudoMetrizable, ENNReal, ENNReal.div_pos, Equiv.refl, Equiv.refl_apply, div_pos, finiteness, isIntegral_gen, liftEquiv, map_monic_ne_zero, mem_roots_iff_aeval_eq_zero, minpoly, minpoly.monic, of_completelyPseudoMetrizable, one_ne_zero, pb.isIntegral_gen, pb.liftEquiv.trans, refl_apply, subtypeEquiv
-/
noncomputable def liftEquiv' [IsDomain B] (pb : PowerBasis A S) :
    (S ->ₐ[A] B) ≃ { y : B // y in (minpoly A pb.gen).aroots B } :=
  pb.liftEquiv.trans ((Equiv.refl _).subtypeEquiv fun x => by
    rw [Equiv.refl_apply]; rw [mem_roots_iff_aeval_eq_zero]
    · simp
    · exact map_monic_ne_zero (minpoly.monic pb.isIntegral_gen))

/-- There are finitely many algebra homomorphisms `S →ₐ[A] B` if `S` is of the form `A[x]`
and `B` is an integral domain. -/
@[instance_reducible]
/--
Definition of `AlgHom.fintype` / `AlgHom.fintype` 的定义

English:
definition AlgHom.fintype
  signature: [IsDomain B] (pb : PowerBasis A S)
  body: letI := Classical.decEq B
  Fintype.ofEquiv _ pb.liftEquiv'.symm

中文:
定义 代数态射.fintype
  签名: [是整环 B] (pb : PowerBasis A S)
  定义体: letI := Classical.decEq B
  Fintype.ofEquiv _ pb.liftEquiv'.symm
-/
noncomputable def AlgHom.fintype [IsDomain B] (pb : PowerBasis A S) : Fintype (S ->ₐ[A] B) :=
  letI := Classical.decEq B
  Fintype.ofEquiv _ pb.liftEquiv'.symm

/-- `pb.equivOfRoot pb' h₁ h₂` is an equivalence of algebras with the same power basis,
where "the same" means that `pb` is a root of `pb'`s minimal polynomial and vice versa.

See also `PowerBasis.equivOfMinpoly` which takes the hypothesis that the
minimal polynomials are identical.
-/
@[simps! -isSimp apply]
/--
Definition of `equivOfRoot` / `equivOfRoot` 的定义

English:
definition equivOfRoot
  signature: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  body: AlgEquiv.ofAlgHom (pb.lift pb'.gen h₂) (pb'.lift pb.gen h₁)
    (by
      ext x
      obtain ⟨f, hf, rfl⟩ := pb'.exists_eq_aeval' x
      simp)
    (by
      ext x
      obtain ⟨f, hf, rfl⟩ := pb.exists_eq_aeval' x
      simp)

@[simp]

中文:
定义 equivOfRoot
  签名: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  定义体: AlgEquiv.ofAlgHom (pb.lift pb'.gen h₂) (pb'.lift pb.gen h₁)
    (by
      ext x
      obtain ⟨f, hf, rfl⟩ := pb'.exists_eq_aeval' x
      simp)
    (by
      ext x
      obtain ⟨f, hf, rfl⟩ := pb.exists_eq_aeval' x
      simp)

@[simp]

Depends on / 依赖: AlgEquiv, AlgEquiv.ofAlgHom, exists_eq_aeval, ofAlgHom, pb.exists_eq_aeval, pb.gen, pb.lift
-/
noncomputable def equivOfRoot (pb : PowerBasis A S) (pb' : PowerBasis A S')
    (h₁ : aeval pb.gen (minpoly A pb'.gen) = 0) (h₂ : aeval pb'.gen (minpoly A pb.gen) = 0) :
    S ≃ₐ[A] S' :=
  AlgEquiv.ofAlgHom (pb.lift pb'.gen h₂) (pb'.lift pb.gen h₁)
    (by
      ext x
      obtain ⟨f, hf, rfl⟩ := pb'.exists_eq_aeval' x
      simp)
    (by
      ext x
      obtain ⟨f, hf, rfl⟩ := pb.exists_eq_aeval' x
      simp)

@[simp]
/--
theorem `equivOfRoot_aeval` / 定理 `equivOfRoot_aeval`

English:
theorem equivOfRoot_aeval
  statement: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  proof: pb.lift_aeval _ h₂ _

@[simp]

中文:
定理 equivOfRoot_aeval
  结论: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  证明: pb.lift_aeval _ h₂ _

@[simp]

Depends on / 依赖: lift_aeval, pb.lift_aeval
-/
theorem equivOfRoot_aeval (pb : PowerBasis A S) (pb' : PowerBasis A S')
    (h₁ : aeval pb.gen (minpoly A pb'.gen) = 0) (h₂ : aeval pb'.gen (minpoly A pb.gen) = 0)
    (f : A[X]) : pb.equivOfRoot pb' h₁ h₂ (aeval pb.gen f) = aeval pb'.gen f :=
  pb.lift_aeval _ h₂ _

@[simp]
/--
theorem `equivOfRoot_gen` / 定理 `equivOfRoot_gen`

English:
theorem equivOfRoot_gen
  statement: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  proof: pb.lift_gen _ h₂

@[simp]

中文:
定理 equivOfRoot_gen
  结论: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  证明: pb.lift_gen _ h₂

@[simp]

Depends on / 依赖: lift_gen, pb.lift_gen
-/
theorem equivOfRoot_gen (pb : PowerBasis A S) (pb' : PowerBasis A S')
    (h₁ : aeval pb.gen (minpoly A pb'.gen) = 0) (h₂ : aeval pb'.gen (minpoly A pb.gen) = 0) :
    pb.equivOfRoot pb' h₁ h₂ pb.gen = pb'.gen :=
  pb.lift_gen _ h₂

@[simp]
/--
theorem `equivOfRoot_symm` / 定理 `equivOfRoot_symm`

English:
theorem equivOfRoot_symm
  statement: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  proof: rfl

中文:
定理 equivOfRoot_symm
  结论: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  证明: rfl
-/
theorem equivOfRoot_symm (pb : PowerBasis A S) (pb' : PowerBasis A S')
    (h₁ : aeval pb.gen (minpoly A pb'.gen) = 0) (h₂ : aeval pb'.gen (minpoly A pb.gen) = 0) :
    (pb.equivOfRoot pb' h₁ h₂).symm = pb'.equivOfRoot pb h₂ h₁ :=
  rfl

/-- `pb.equivOfMinpoly pb' h` is an equivalence of algebras with the same power basis,
where "the same" means that they have identical minimal polynomials.

See also `PowerBasis.equivOfRoot` which takes the hypothesis that each generator is a root of the
other basis' minimal polynomial; `PowerBasis.equivOfRoot` is more general if `A` is not a field.
-/
@[simps! -isSimp apply]
/--
Definition of `equivOfMinpoly` / `equivOfMinpoly` 的定义

English:
definition equivOfMinpoly
  signature: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  body: pb.equivOfRoot pb' (h ▸ minpoly.aeval _ _) (h.symm ▸ minpoly.aeval _ _)

@[simp]

中文:
定义 equivOfMinpoly
  签名: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  定义体: pb.equivOfRoot pb' (h ▸ minpoly.aeval _ _) (h.symm ▸ minpoly.aeval _ _)

@[simp]

Depends on / 依赖: equivOfRoot, h.symm, minpoly, minpoly.aeval, pb.equivOfRoot
-/
noncomputable def equivOfMinpoly (pb : PowerBasis A S) (pb' : PowerBasis A S')
    (h : minpoly A pb.gen = minpoly A pb'.gen) : S ≃ₐ[A] S' :=
  pb.equivOfRoot pb' (h ▸ minpoly.aeval _ _) (h.symm ▸ minpoly.aeval _ _)

@[simp]
/--
theorem `equivOfMinpoly_aeval` / 定理 `equivOfMinpoly_aeval`

English:
theorem equivOfMinpoly_aeval
  statement: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  proof: pb.equivOfRoot_aeval pb' _ _ _

@[simp]

中文:
定理 equivOfMinpoly_aeval
  结论: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  证明: pb.equivOfRoot_aeval pb' _ _ _

@[simp]

Depends on / 依赖: equivOfRoot_aeval, pb.equivOfRoot_aeval
-/
theorem equivOfMinpoly_aeval (pb : PowerBasis A S) (pb' : PowerBasis A S')
    (h : minpoly A pb.gen = minpoly A pb'.gen) (f : A[X]) :
    pb.equivOfMinpoly pb' h (aeval pb.gen f) = aeval pb'.gen f :=
  pb.equivOfRoot_aeval pb' _ _ _

@[simp]
/--
theorem `equivOfMinpoly_gen` / 定理 `equivOfMinpoly_gen`

English:
theorem equivOfMinpoly_gen
  statement: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  proof: pb.equivOfRoot_gen pb' _ _

@[simp]

中文:
定理 equivOfMinpoly_gen
  结论: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  证明: pb.equivOfRoot_gen pb' _ _

@[simp]

Depends on / 依赖: equivOfRoot_gen, pb.equivOfRoot_gen
-/
theorem equivOfMinpoly_gen (pb : PowerBasis A S) (pb' : PowerBasis A S')
    (h : minpoly A pb.gen = minpoly A pb'.gen) : pb.equivOfMinpoly pb' h pb.gen = pb'.gen :=
  pb.equivOfRoot_gen pb' _ _

@[simp]
/--
theorem `equivOfMinpoly_symm` / 定理 `equivOfMinpoly_symm`

English:
theorem equivOfMinpoly_symm
  statement: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  proof: rfl

中文:
定理 equivOfMinpoly_symm
  结论: (pb : PowerBasis A S) (pb' : PowerBasis A S')
  证明: rfl
-/
theorem equivOfMinpoly_symm (pb : PowerBasis A S) (pb' : PowerBasis A S')
    (h : minpoly A pb.gen = minpoly A pb'.gen) :
    (pb.equivOfMinpoly pb' h).symm = pb'.equivOfMinpoly pb h.symm :=
  rfl

end Equiv

end PowerBasis

open PowerBasis

/--
theorem `linearIndependent_pow` / 定理 `linearIndependent_pow`

English:
theorem linearIndependent_pow
  given: [Algebra K S] (x : S)
  proof: by
  by_cases h : IsIntegral K x; swap
  · rw [minpoly.eq_zero h, natDegree_zero]
    exact linearIndependent_empty_type
  refine Fintype.linearIndependent_iff.2 fun g hg i => ?_
  simp_rw [Algebra.smul_def, ← aeval_monomial, ← map_sum] at hg
  apply (fun hn0 => (minpoly.degree_le_of_ne_zero K x (mt (fun h0 => ?_) hn0) hg).not_gt).mtr
  · simp_rw [← C_mul_X_pow_eq_monomial]
    exact (degree_eq_natDegree <| minpoly.ne_zero h).symm ▸ degree_sum_fin_lt _
  · apply_fun lcoeff K i at h0
    simp_rw [map_sum, lcoeff_apply, coeff_monomial, Fin.val_eq_val, Finset.sum_ite_eq'] at h0
    exact (if_pos <| Finset.mem_univ _).symm.trans h0

中文:
定理 linearIndependent_pow
  条件: [代数 K S] (x : S)
  证明: by
  by_cases h : IsIntegral K x; swap
  · rw [minpoly.eq_zero h, natDegree_zero]
    exact linearIndependent_empty_type
  refine Fintype.linearIndependent_iff.2 fun g hg i => ?_
  simp_rw [Algebra.smul_def, ← aeval_monomial, ← map_sum] at hg
  apply (fun hn0 => (minpoly.degree_le_of_ne_zero K x (mt (fun h0 => ?_) hn0) hg).not_gt).mtr
  · simp_rw [← C_mul_X_pow_eq_monomial]
    exact (degree_eq_natDegree <| minpoly.ne_zero h).symm ▸ degree_sum_fin_lt _
  · apply_fun lcoeff K i at h0
    simp_rw [map_sum, lcoeff_apply, coeff_monomial, Fin.val_eq_val, Finset.sum_ite_eq'] at h0
    exact (if_pos <| Finset.mem_univ _).symm.trans h0

Depends on / 依赖: Algebra, Algebra.smul_def, C_mul_X_pow_eq_monomial, Fintype, Fintype.linearIndependent_iff, IsIntegral, aeval_monomial, apply_fun, degree_eq_natDegree, degree_le_of_ne_zero, degree_sum_fin_lt, eq_zero, lcoeff, lcoeff_apply, linearIndependent_empty_type, linearIndependent_iff, map_sum, minpoly, minpoly.degree_le_of_ne_zero, minpoly.eq_zero
-/
theorem linearIndependent_pow [Algebra K S] (x : S) :
    LinearIndependent K fun i : Fin (minpoly K x).natDegree => x ^ (i : Nat) := by
  by_cases h : IsIntegral K x; swap
  · rw [minpoly.eq_zero h, natDegree_zero]
    exact linearIndependent_empty_type
  refine Fintype.linearIndependent_iff.2 fun g hg i => ?_
  simp_rw [Algebra.smul_def, ← aeval_monomial, ← map_sum] at hg
  apply (fun hn0 => (minpoly.degree_le_of_ne_zero K x (mt (fun h0 => ?_) hn0) hg).not_gt).mtr
  · simp_rw [← C_mul_X_pow_eq_monomial]
    exact (degree_eq_natDegree <| minpoly.ne_zero h).symm ▸ degree_sum_fin_lt _
  · apply_fun lcoeff K i at h0
    simp_rw [map_sum, lcoeff_apply, coeff_monomial, Fin.val_eq_val, Finset.sum_ite_eq'] at h0
    exact (if_pos <| Finset.mem_univ _).symm.trans h0

/--
theorem `IsIntegral.mem_span_pow` / 定理 `IsIntegral.mem_span_pow`

English:
theorem IsIntegral.mem_span_pow
  statement: [Nontrivial R] {x y : S} (hx : IsIntegral R x)
  proof: by
  obtain ⟨f, rfl⟩ := hy
  apply mem_span_pow'.mpr _
  have := minpoly.monic hx
  refine ⟨f %ₘ minpoly R x, (degree_modByMonic_lt _ this).trans_le degree_le_natDegree, ?_⟩
  conv_lhs => rw [← modByMonic_add_div f (minpoly R x)]
  simp only [add_zero, zero_mul, minpoly.aeval, aeval_add, map_mul]

中文:
定理 是整.mem_span_pow
  结论: [非平凡 R] {x y : S} (hx : 是整 R x)
  证明: by
  obtain ⟨f, rfl⟩ := hy
  apply mem_span_pow'.mpr _
  have := minpoly.monic hx
  refine ⟨f %ₘ minpoly R x, (degree_modByMonic_lt _ this).trans_le degree_le_natDegree, ?_⟩
  conv_lhs => rw [← modByMonic_add_div f (minpoly R x)]
  simp only [add_zero, zero_mul, minpoly.aeval, aeval_add, map_mul]

Depends on / 依赖: add_zero, aeval_add, conv_lhs, degree_le_natDegree, degree_modByMonic_lt, map_mul, mem_span_pow, minpoly, minpoly.aeval, minpoly.monic, modByMonic_add_div, trans_le, zero_mul
-/
theorem IsIntegral.mem_span_pow [Nontrivial R] {x y : S} (hx : IsIntegral R x)
    (hy : exists f : R[X], y = aeval x f) :
    y in Submodule.span R (Set.range fun i : Fin (minpoly R x).natDegree => x ^ (i : Nat)) := by
  obtain ⟨f, rfl⟩ := hy
  apply mem_span_pow'.mpr _
  have := minpoly.monic hx
  refine ⟨f %ₘ minpoly R x, (degree_modByMonic_lt _ this).trans_le degree_le_natDegree, ?_⟩
  conv_lhs => rw [← modByMonic_add_div f (minpoly R x)]
  simp only [add_zero, zero_mul, minpoly.aeval, aeval_add, map_mul]

namespace PowerBasis

section Map

variable {S' : Type*} [CommRing S'] [Algebra R S']

/-- `PowerBasis.map pb (e : S ≃ₐ[R] S')` is the power basis for `S'` generated by `e pb.gen`. -/
@[simps dim gen basis]
/--
Definition of `map` / `map` 的定义

English:
definition map
  signature: (pb : PowerBasis R S) (e : S ≃ₐ[R] S')
  body: pb.dim
  basis := pb.basis.map e.toLinearEquiv
  gen := e pb.gen
  basis_eq_pow i := by rw [Basis.map_apply, pb.basis_eq_pow, e.toLinearEquiv_apply, map_pow]

中文:
定义 map
  签名: (pb : PowerBasis R S) (e : S ≃ₐ[R] S')
  定义体: pb.dim
  basis := pb.basis.map e.toLinearEquiv
  gen := e pb.gen
  basis_eq_pow i := by rw [Basis.map_apply, pb.basis_eq_pow, e.toLinearEquiv_apply, map_pow]

Depends on / 依赖: pb.dim
-/
noncomputable def map (pb : PowerBasis R S) (e : S ≃ₐ[R] S') : PowerBasis R S' where
  dim := pb.dim
  basis := pb.basis.map e.toLinearEquiv
  gen := e pb.gen
  basis_eq_pow i := by rw [Basis.map_apply, pb.basis_eq_pow, e.toLinearEquiv_apply, map_pow]

variable [Algebra A S] [Algebra A S']

/--
theorem `minpolyGen_map` / 定理 `minpolyGen_map`

English:
theorem minpolyGen_map
  given: (pb : PowerBasis A S) (e : S ≃ₐ[A] S')
  proof: by
  simp

@[simp]

中文:
定理 minpolyGen_map
  条件: (pb : PowerBasis A S) (e : S ≃ₐ[A] S')
  证明: by
  simp

@[simp]
-/
theorem minpolyGen_map (pb : PowerBasis A S) (e : S ≃ₐ[A] S') :
    (pb.map e).minpolyGen = pb.minpolyGen := by
  simp

@[simp]
/--
theorem `equivOfRoot_map` / 定理 `equivOfRoot_map`

English:
theorem equivOfRoot_map
  given: (pb : PowerBasis A S) (e : S ≃ₐ[A] S') (h₁ h₂)
  proof: by
  ext x
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' x
  simp [aeval_algEquiv]

@[simp]

中文:
定理 equivOfRoot_map
  条件: (pb : PowerBasis A S) (e : S ≃ₐ[A] S') (h₁ h₂)
  证明: by
  ext x
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' x
  simp [aeval_algEquiv]

@[simp]

Depends on / 依赖: aeval_algEquiv, exists_eq_aeval, pb.exists_eq_aeval
-/
theorem equivOfRoot_map (pb : PowerBasis A S) (e : S ≃ₐ[A] S') (h₁ h₂) :
    pb.equivOfRoot (pb.map e) h₁ h₂ = e := by
  ext x
  obtain ⟨f, rfl⟩ := pb.exists_eq_aeval' x
  simp [aeval_algEquiv]

@[simp]
/--
theorem `equivOfMinpoly_map` / 定理 `equivOfMinpoly_map`

English:
theorem equivOfMinpoly_map
  statement: (pb : PowerBasis A S) (e : S ≃ₐ[A] S')
  proof: pb.equivOfRoot_map _ _ _

中文:
定理 equivOfMinpoly_map
  结论: (pb : PowerBasis A S) (e : S ≃ₐ[A] S')
  证明: pb.equivOfRoot_map _ _ _

Depends on / 依赖: equivOfRoot_map, pb.equivOfRoot_map
-/
theorem equivOfMinpoly_map (pb : PowerBasis A S) (e : S ≃ₐ[A] S')
    (h : minpoly A pb.gen = minpoly A (pb.map e).gen) : pb.equivOfMinpoly (pb.map e) h = e :=
  pb.equivOfRoot_map _ _ _

end Map

section Adjoin

open Algebra

/--
theorem `adjoin_gen_eq_top` / 定理 `adjoin_gen_eq_top`

English:
theorem adjoin_gen_eq_top
  given: (B : PowerBasis R S)
  statement: adjoin R ({B.gen} : Set S) = ⊤
  proof: by
  rw [← toSubmodule_eq_top]; rw [_root_.eq_top_iff]; rw [← B.basis.span_eq]; rw [Submodule.span_le]
  rintro x ⟨i, rfl⟩
  rw [B.basis_eq_pow i]
  exact Subalgebra.pow_mem _ (subset_adjoin (Set.mem_singleton _)) _

中文:
定理 adjoin_gen_eq_top
  条件: (B : PowerBasis R S)
  结论: adjoin R ({B.gen} : 集合 S) = ⊤
  证明: by
  rw [← toSubmodule_eq_top]; rw [_root_.eq_top_iff]; rw [← B.basis.span_eq]; rw [Submodule.span_le]
  rintro x ⟨i, rfl⟩
  rw [B.basis_eq_pow i]
  exact Subalgebra.pow_mem _ (subset_adjoin (Set.mem_singleton _)) _

Depends on / 依赖: B.basis.span_eq, B.basis_eq_pow, Set.mem_singleton, Subalgebra, Subalgebra.pow_mem, Submodule, Submodule.span_le, _root_, _root_.eq_top_iff, basis_eq_pow, eq_top_iff, mem_singleton, pow_mem, span_eq, span_le, subset_adjoin, toSubmodule_eq_top
-/
theorem adjoin_gen_eq_top (B : PowerBasis R S) : adjoin R ({B.gen} : Set S) = ⊤ := by
  rw [← toSubmodule_eq_top]; rw [_root_.eq_top_iff]; rw [← B.basis.span_eq]; rw [Submodule.span_le]
  rintro x ⟨i, rfl⟩
  rw [B.basis_eq_pow i]
  exact Subalgebra.pow_mem _ (subset_adjoin (Set.mem_singleton _)) _

/--
theorem `adjoin_eq_top_of_gen_mem_adjoin` / 定理 `adjoin_eq_top_of_gen_mem_adjoin`

English:
theorem adjoin_eq_top_of_gen_mem_adjoin
  statement: {B : PowerBasis R S} {x : S}
  proof: by
  rw [_root_.eq_top_iff]; rw [← B.adjoin_gen_eq_top]
  refine adjoin_le ?_
  simp [hx]

中文:
定理 adjoin_eq_top_of_gen_mem_adjoin
  结论: {B : PowerBasis R S} {x : S}
  证明: by
  rw [_root_.eq_top_iff]; rw [← B.adjoin_gen_eq_top]
  refine adjoin_le ?_
  simp [hx]

Depends on / 依赖: B.adjoin_gen_eq_top, _root_, _root_.eq_top_iff, adjoin_gen_eq_top, adjoin_le, eq_top_iff
-/
theorem adjoin_eq_top_of_gen_mem_adjoin {B : PowerBasis R S} {x : S}
    (hx : B.gen in adjoin R ({x} : Set S)) : adjoin R ({x} : Set S) = ⊤ := by
  rw [_root_.eq_top_iff]; rw [← B.adjoin_gen_eq_top]
  refine adjoin_le ?_
  simp [hx]

end Adjoin

end PowerBasis
