/-
Copyright (c) 2022 Andrew Yang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Andrew Yang
-/
module

public import Mathlib.RingTheory.Ideal.BigOperators
public import Mathlib.RingTheory.FiniteType

/-!

# Rees algebra

The Rees algebra of an ideal `I` is the subalgebra `R[It]` of `R[t]` defined as `R[It] = ⨁ₙ Iⁿ tⁿ`.
This is used to prove the Artin-Rees lemma, and will potentially enable us to calculate some
blowup in the future.

## Main definition

- `reesAlgebra` : The Rees algebra of an ideal `I`, defined as a subalgebra of `R[X]`.
- `adjoin_monomial_eq_reesAlgebra` : The Rees algebra is generated by the degree one elements.
- `reesAlgebra.fg` : The Rees algebra of a f.g. ideal is of finite type. In particular, this
  implies that the rees algebra over a Noetherian ring is still Noetherian.

-/

@[expose] public section


universe u v

variable {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M] (I : Ideal R)

open Polynomial

/--
Definition of `reesAlgebra` / `reesAlgebra` 的定义

English:
definition reesAlgebra
  signature: : Subalgebra R R[X] where
  body: { f | forall i, f.coeff i in I ^ i }
  mul_mem' hf hg i := by
    rw [coeff_mul]
    apply Ideal.sum_mem
    rintro ⟨j, k⟩ e
    rw [← Finset.mem_antidiagonal.mp e]; rw [pow_add]
    exact Ideal.mul_mem_mul (hf j) (hg k)
  one_mem' i := by
    rw [coeff_one]
    split_ifs with h
    · subst h
      simp
    · simp
  add_mem' hf hg i := by
    rw [coeff_add]
    exact Ideal.add_mem _ (hf i) (hg i)
  zero_mem' _ := Ideal.zero_mem _
  algebraMap_mem' r i := by
    rw [algebraMap_apply]; rw [coeff_C]
    split_ifs with h
    · subst h
      simp
    · simp

中文:
定义 reesAlgebra
  签名: : 子代数 R R[X] where
  定义体: { f | forall i, f.coeff i in I ^ i }
  mul_mem' hf hg i := by
    rw [coeff_mul]
    apply Ideal.sum_mem
    rintro ⟨j, k⟩ e
    rw [← Finset.mem_antidiagonal.mp e]; rw [pow_add]
    exact Ideal.mul_mem_mul (hf j) (hg k)
  one_mem' i := by
    rw [coeff_one]
    split_ifs with h
    · subst h
      simp
    · simp
  add_mem' hf hg i := by
    rw [coeff_add]
    exact Ideal.add_mem _ (hf i) (hg i)
  zero_mem' _ := Ideal.zero_mem _
  algebraMap_mem' r i := by
    rw [algebraMap_apply]; rw [coeff_C]
    split_ifs with h
    · subst h
      simp
    · simp

Depends on / 依赖: f.coeff
-/
def reesAlgebra : Subalgebra R R[X] where
  carrier := { f | forall i, f.coeff i in I ^ i }
  mul_mem' hf hg i := by
    rw [coeff_mul]
    apply Ideal.sum_mem
    rintro ⟨j, k⟩ e
    rw [← Finset.mem_antidiagonal.mp e]; rw [pow_add]
    exact Ideal.mul_mem_mul (hf j) (hg k)
  one_mem' i := by
    rw [coeff_one]
    split_ifs with h
    · subst h
      simp
    · simp
  add_mem' hf hg i := by
    rw [coeff_add]
    exact Ideal.add_mem _ (hf i) (hg i)
  zero_mem' _ := Ideal.zero_mem _
  algebraMap_mem' r i := by
    rw [algebraMap_apply]; rw [coeff_C]
    split_ifs with h
    · subst h
      simp
    · simp

/--
theorem `mem_reesAlgebra_iff` / 定理 `mem_reesAlgebra_iff`

English:
theorem mem_reesAlgebra_iff
  given: (f : R[X])
  statement: f in reesAlgebra I ↔ forall i, f.coeff i in I ^ i
  proof: Iff.rfl

中文:
定理 mem_reesAlgebra_iff
  条件: (f : R[X])
  结论: f in reesAlgebra I ↔ 对任意 i, f.coeff i in I ^ i
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
theorem mem_reesAlgebra_iff (f : R[X]) : f in reesAlgebra I ↔ forall i, f.coeff i in I ^ i :=
  Iff.rfl

/--
theorem `mem_reesAlgebra_iff_support` / 定理 `mem_reesAlgebra_iff_support`

English:
theorem mem_reesAlgebra_iff_support
  given: (f : R[X])
  proof: by
  apply forall_congr'
  intro a
  rw [mem_support_iff]; rw [Iff.comm]; rw [Classical.imp_iff_right_iff]; rw [Ne]; rw [← imp_iff_not_or]
  exact fun e => e.symm ▸ (I ^ a).zero_mem

中文:
定理 mem_reesAlgebra_iff_support
  条件: (f : R[X])
  证明: by
  apply forall_congr'
  intro a
  rw [mem_support_iff]; rw [Iff.comm]; rw [Classical.imp_iff_right_iff]; rw [Ne]; rw [← imp_iff_not_or]
  exact fun e => e.symm ▸ (I ^ a).zero_mem

Depends on / 依赖: Classical, Classical.imp_iff_right_iff, Iff.comm, Set.mem_union_left, e.symm, forall_congr, imp_iff_not_or, imp_iff_right_iff, inf_le_left, inf_le_right, le_inf, le_sup_left, le_sup_right, mem_support_iff, mem_union_left, sup_le, zero_mem
-/
theorem mem_reesAlgebra_iff_support (f : R[X]) :
    f in reesAlgebra I ↔ forall i in f.support, f.coeff i in I ^ i := by
  apply forall_congr'
  intro a
  rw [mem_support_iff]; rw [Iff.comm]; rw [Classical.imp_iff_right_iff]; rw [Ne]; rw [← imp_iff_not_or]
  exact fun e => e.symm ▸ (I ^ a).zero_mem

/--
theorem `reesAlgebra.monomial_mem` / 定理 `reesAlgebra.monomial_mem`

English:
theorem reesAlgebra.monomial_mem
  given: {I : Ideal R} {i : Nat} {r : R}
  proof: by
  simp +contextual [mem_reesAlgebra_iff_support, coeff_monomial, ←
    imp_iff_not_or]

中文:
定理 reesAlgebra.monomial_mem
  条件: {I : 理想 R} {i : 自然数} {r : R}
  证明: by
  simp +contextual [mem_reesAlgebra_iff_support, coeff_monomial, ←
    imp_iff_not_or]

Depends on / 依赖: coeff_monomial, contextual, imp_iff_not_or, mem_reesAlgebra_iff_support
-/
theorem reesAlgebra.monomial_mem {I : Ideal R} {i : Nat} {r : R} :
    monomial i r in reesAlgebra I ↔ r in I ^ i := by
  simp +contextual [mem_reesAlgebra_iff_support, coeff_monomial, ←
    imp_iff_not_or]

/--
theorem `monomial_mem_adjoin_monomial` / 定理 `monomial_mem_adjoin_monomial`

English:
theorem monomial_mem_adjoin_monomial
  given: {I : Ideal R} {n : Nat} {r : R} (hr : r in I ^ n)
  proof: by
  induction n generalizing r with
  | zero => exact Subalgebra.algebraMap_mem _ _
  | succ n hn =>
    rw [pow_succ'] at hr
    refine Submodule.smul_induction_on hr ?_ ?_
    · intro r hr s hs
      rw [add_comm n 1]; rw [smul_eq_mul]; rw [← monomial_mul_monomial]
      exact Subalgebra.mul_mem _ (Algebra.subset_adjoin (Set.mem_image_of_mem _ hr)) (hn hs)
    · intro x y hx hy
      rw [map_add]
      exact Subalgebra.add_mem _ hx hy

中文:
定理 monomial_mem_adjoin_monomial
  条件: {I : 理想 R} {n : 自然数} {r : R} (hr : r in I ^ n)
  证明: by
  induction n generalizing r with
  | zero => exact Subalgebra.algebraMap_mem _ _
  | succ n hn =>
    rw [pow_succ'] at hr
    refine Submodule.smul_induction_on hr ?_ ?_
    · intro r hr s hs
      rw [add_comm n 1]; rw [smul_eq_mul]; rw [← monomial_mul_monomial]
      exact Subalgebra.mul_mem _ (Algebra.subset_adjoin (Set.mem_image_of_mem _ hr)) (hn hs)
    · intro x y hx hy
      rw [map_add]
      exact Subalgebra.add_mem _ hx hy

Depends on / 依赖: Algebra, Algebra.subset_adjoin, Set.mem_image_of_mem, Subalgebra, Subalgebra.add_mem, Subalgebra.algebraMap_mem, Subalgebra.mul_mem, Submodule, Submodule.smul_induction_on, add_comm, add_mem, algebraMap_mem, generalizing, map_add, mem_image_of_mem, monomial_mul_monomial, mul_mem, pow_succ, smul_eq_mul, smul_induction_on
-/
theorem monomial_mem_adjoin_monomial {I : Ideal R} {n : Nat} {r : R} (hr : r in I ^ n) :
    monomial n r in Algebra.adjoin R (Submodule.map (monomial 1 : R ->ₗ[R] R[X]) I : Set R[X]) := by
  induction n generalizing r with
  | zero => exact Subalgebra.algebraMap_mem _ _
  | succ n hn =>
    rw [pow_succ'] at hr
    refine Submodule.smul_induction_on hr ?_ ?_
    · intro r hr s hs
      rw [add_comm n 1]; rw [smul_eq_mul]; rw [← monomial_mul_monomial]
      exact Subalgebra.mul_mem _ (Algebra.subset_adjoin (Set.mem_image_of_mem _ hr)) (hn hs)
    · intro x y hx hy
      rw [map_add]
      exact Subalgebra.add_mem _ hx hy

/--
theorem `adjoin_monomial_eq_reesAlgebra` / 定理 `adjoin_monomial_eq_reesAlgebra`

English:
theorem adjoin_monomial_eq_reesAlgebra
  proof: by
  apply le_antisymm
  · apply Algebra.adjoin_le _
    rintro _ ⟨r, hr, rfl⟩
    exact reesAlgebra.monomial_mem.mpr (by rwa [pow_one])
  · intro p hp
    rw [p.as_sum_support]
    apply Subalgebra.sum_mem _ _
    rintro i -
    exact monomial_mem_adjoin_monomial (hp i)

中文:
定理 adjoin_monomial_eq_reesAlgebra
  证明: by
  apply le_antisymm
  · apply Algebra.adjoin_le _
    rintro _ ⟨r, hr, rfl⟩
    exact reesAlgebra.monomial_mem.mpr (by rwa [pow_one])
  · intro p hp
    rw [p.as_sum_support]
    apply Subalgebra.sum_mem _ _
    rintro i -
    exact monomial_mem_adjoin_monomial (hp i)

Depends on / 依赖: Algebra, Algebra.adjoin_le, Subalgebra, Subalgebra.sum_mem, adjoin_le, as_sum_support, le_antisymm, monomial_mem, monomial_mem_adjoin_monomial, p.as_sum_support, pow_one, reesAlgebra, reesAlgebra.monomial_mem.mpr, sum_mem
-/
theorem adjoin_monomial_eq_reesAlgebra :
    Algebra.adjoin R (Submodule.map (monomial 1 : R ->ₗ[R] R[X]) I : Set R[X]) = reesAlgebra I := by
  apply le_antisymm
  · apply Algebra.adjoin_le _
    rintro _ ⟨r, hr, rfl⟩
    exact reesAlgebra.monomial_mem.mpr (by rwa [pow_one])
  · intro p hp
    rw [p.as_sum_support]
    apply Subalgebra.sum_mem _ _
    rintro i -
    exact monomial_mem_adjoin_monomial (hp i)

variable {I}

/--
theorem `reesAlgebra.fg` / 定理 `reesAlgebra.fg`

English:
theorem reesAlgebra.fg
  given: (hI : I.FG)
  statement: (reesAlgebra I).FG
  proof: by
  classical
    obtain ⟨s, hs⟩ := hI
    rw [← adjoin_monomial_eq_reesAlgebra]; rw [← hs]
    use s.image (monomial 1)
    rw [Finset.coe_image]
    change
      _ =
        Algebra.adjoin R
          (Submodule.map (monomial 1 : R ->ₗ[R] R[X]) (Submodule.span R ↑s) : Set R[X])
    rw [Submodule.map_span]; rw [Algebra.adjoin_span]

中文:
定理 reesAlgebra.fg
  条件: (hI : I.FG)
  结论: (reesAlgebra I).FG
  证明: by
  classical
    obtain ⟨s, hs⟩ := hI
    rw [← adjoin_monomial_eq_reesAlgebra]; rw [← hs]
    use s.image (monomial 1)
    rw [Finset.coe_image]
    change
      _ =
        Algebra.adjoin R
          (Submodule.map (monomial 1 : R ->ₗ[R] R[X]) (Submodule.span R ↑s) : Set R[X])
    rw [Submodule.map_span]; rw [Algebra.adjoin_span]

Depends on / 依赖: Algebra, Algebra.adjoin, Algebra.adjoin_span, Finset, Finset.coe_image, Submodule, Submodule.map, Submodule.map_span, Submodule.span, adjoin, adjoin_monomial_eq_reesAlgebra, adjoin_span, classical, coe_image, map_span, monomial, s.image
-/
theorem reesAlgebra.fg (hI : I.FG) : (reesAlgebra I).FG := by
  classical
    obtain ⟨s, hs⟩ := hI
    rw [← adjoin_monomial_eq_reesAlgebra]; rw [← hs]
    use s.image (monomial 1)
    rw [Finset.coe_image]
    change
      _ =
        Algebra.adjoin R
          (Submodule.map (monomial 1 : R ->ₗ[R] R[X]) (Submodule.span R ↑s) : Set R[X])
    rw [Submodule.map_span]; rw [Algebra.adjoin_span]

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [IsNoetherianRing
  signature: R] : Algebra.FiniteType R (reesAlgebra I)
  body: ⟨(reesAlgebra I).fg_top.mpr (reesAlgebra.fg <| IsNoetherian.noetherian I)⟩

中文:
实例 [是Noether环
  签名: R] : 代数.有限型 R (reesAlgebra I)
  定义体: ⟨(reesAlgebra I).fg_top.mpr (reesAlgebra.fg <| IsNoetherian.noetherian I)⟩

Depends on / 依赖: IsNoetherian, IsNoetherian.noetherian, fg_top, fg_top.mpr, noetherian, reesAlgebra, reesAlgebra.fg
-/
instance [IsNoetherianRing R] : Algebra.FiniteType R (reesAlgebra I) :=
  ⟨(reesAlgebra I).fg_top.mpr (reesAlgebra.fg <| IsNoetherian.noetherian I)⟩

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [IsNoetherianRing
  signature: R] : IsNoetherianRing (reesAlgebra I)
  body: Algebra.FiniteType.isNoetherianRing R _

中文:
实例 [是Noether环
  签名: R] : 是Noether环 (reesAlgebra I)
  定义体: Algebra.FiniteType.isNoetherianRing R _

Depends on / 依赖: Algebra, Algebra.FiniteType.isNoetherianRing, FiniteType, isNoetherianRing
-/
instance [IsNoetherianRing R] : IsNoetherianRing (reesAlgebra I) :=
  Algebra.FiniteType.isNoetherianRing R _
