/-
Copyright (c) 2018 Chris Hughes. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Hughes
-/
module

public import Mathlib.Algebra.Polynomial.Splits
public import Mathlib.RingTheory.Adjoin.Basic
public import Mathlib.RingTheory.AdjoinRoot

/-!
# Adjoining elements to a field

Some lemmas on the ring generated by adjoining an element to a field.

## Main statements

* `Polynomial.lift_of_splits`: If `K` and `L` are field extensions of `F`
  and we have `s : Finset K` such that the minimal polynomial of each `x ∈ s` splits in `L`
  then `Algebra.adjoin F s` embeds in `L`.
-/

@[expose] public section


noncomputable section

open Polynomial

section Embeddings

variable (F : Type*) [Field F]

open AdjoinRoot in
/--
Definition of `AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly` / `AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly` 的定义

English:
definition AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly
  signature: {R : Type*} [CommRing R] [Algebra F R] (x : R)
  body: AlgEquiv.symm AlgEquiv.ofBijective (Minpoly.toAdjoin F x) by
    refine ⟨(injective_iff_map_eq_zero _).2 fun P₁ hP₁ => ?_, Minpoly.toAdjoin.surjective F x⟩
    obtain ⟨P, rfl⟩ := mk_surjective P₁
    refine AdjoinRoot.mk_eq_zero.mpr (minpoly.dvd F x ?_)
    simpa [← Subalgebra.coe_eq_zero, ← aeval_d

中文:
定义 AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly
  签名: {R : 类型} [CommRing R] [Algebra F R] (x : R)
  定义体: AlgEquiv.symm AlgEquiv.ofBijective (Minpoly.toAdjoin F x) by
    refine ⟨(injective_iff_map_eq_zero _).2 fun P₁ hP₁ => ?_, Minpoly.toAdjoin.surjective F x⟩
    obtain ⟨P, rfl⟩ := mk_surjective P₁
    refine AdjoinRoot.mk_eq_zero.mpr (minpoly.dvd F x ?_)
    simpa [← Subalgebra.coe_eq_zero, ← aeval_d

Depends on / 依赖: AdjoinRoot, AdjoinRoot.mk_eq_zero.mpr, AlgEquiv, AlgEquiv.ofBijective, AlgEquiv.symm, Minpoly, Minpoly.toAdjoin, Minpoly.toAdjoin.surjective, Subalgebra, Subalgebra.coe_eq_zero, aeval_def, coe_eq_zero, injective_iff_map_eq_zero, minpoly, minpoly.dvd, mk_eq_zero, mk_surjective, ofBijective, surjective, toAdjoin
-/
def AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly {R : Type*} [CommRing R] [Algebra F R] (x : R) :
    Algebra.adjoin F ({x} : Set R) ≃ₐ[F] AdjoinRoot (minpoly F x) :=
AlgEquiv.symm AlgEquiv.ofBijective (Minpoly.toAdjoin F x) by
    refine ⟨(injective_iff_map_eq_zero _).2 fun P₁ hP₁ => ?_, Minpoly.toAdjoin.surjective F x⟩
    obtain ⟨P, rfl⟩ := mk_surjective P₁
    refine AdjoinRoot.mk_eq_zero.mpr (minpoly.dvd F x ?_)
    simpa [← Subalgebra.coe_eq_zero, ← aeval_def] using hP₁

@[simp]
/--
theorem `AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly_symm_toAlgHom` / 定理 `AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly_symm_toAlgHom`

English:
theorem AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly_symm_toAlgHom
  statement: {R : Type*} [CommRing R]
  proof: rfl

@[simp]

中文:
定理 AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly_symm_toAlgHom
  结论: {R : 类型} [CommRing R]
  证明: rfl

@[simp]
-/
theorem AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly_symm_toAlgHom {R : Type*} [CommRing R]
    [Algebra F R] (x : R) :
    (adjoinSingletonEquivAdjoinRootMinpoly F x).symm = AdjoinRoot.Minpoly.toAdjoin F x := rfl

@[simp]
/--
theorem `AlgEquiv.coe_adjoinSingletonEquivAdjoinRootMinpoly_symm` / 定理 `AlgEquiv.coe_adjoinSingletonEquivAdjoinRootMinpoly_symm`

English:
theorem AlgEquiv.coe_adjoinSingletonEquivAdjoinRootMinpoly_symm
  statement: {R : Type*} [CommRing R]
  proof: rfl

中文:
定理 AlgEquiv.coe_adjoinSingletonEquivAdjoinRootMinpoly_symm
  结论: {R : 类型} [CommRing R]
  证明: rfl
-/
theorem AlgEquiv.coe_adjoinSingletonEquivAdjoinRootMinpoly_symm {R : Type*} [CommRing R]
    [Algebra F R] (x : R) :
    ⇑(adjoinSingletonEquivAdjoinRootMinpoly F x).symm = AdjoinRoot.Minpoly.toAdjoin F x := rfl

/--
Definition of `Algebra.adjoin.liftSingleton` / `Algebra.adjoin.liftSingleton` 的定义

English:
definition Algebra.adjoin.liftSingleton
  signature: {S T : Type*}
  body: (AdjoinRoot.liftAlgHom _ _ y h).comp (AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly F x).toAlgHom

中文:
定义 Algebra.adjoin.liftSingleton
  签名: {S T : 类型}
  定义体: (AdjoinRoot.liftAlgHom _ _ y h).comp (AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly F x).toAlgHom

Depends on / 依赖: AdjoinRoot, AdjoinRoot.liftAlgHom, AlgEquiv, AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly, adjoinSingletonEquivAdjoinRootMinpoly, liftAlgHom, toAlgHom
-/
noncomputable def Algebra.adjoin.liftSingleton {S T : Type*}
    [CommRing S] [CommRing T] [Algebra F S] [Algebra F T]
    (x : S) (y : T) (h : aeval y (minpoly F x) = 0) :
    Algebra.adjoin F {x} ->ₐ[F] T :=
  (AdjoinRoot.liftAlgHom _ _ y h).comp (AlgEquiv.adjoinSingletonEquivAdjoinRootMinpoly F x).toAlgHom

open Finset

set_option backward.isDefEq.respectTransparency false in
/--
theorem `Polynomial.lift_of_splits` / 定理 `Polynomial.lift_of_splits`

English:
theorem Polynomial.lift_of_splits
  statement: {F K L : Type*} [Field F] [Field K] [Field L] [Algebra F K]
  proof: by
  classical
    refine Finset.induction_on s (fun _ => ?_) fun a s _ ih H => ?_
    · rw [coe_empty, Algebra.adjoin_empty]
      exact ⟨(Algebra.ofId F L).comp (Algebra.botEquiv F K)⟩
    rw [forall_mem_insert] at H
    rcases H with ⟨⟨H1, H2⟩, H3⟩
    obtain ⟨f⟩ := ih H3
    choose H3 _ using H3

中文:
定理 Polynomial.lift_of_splits
  结论: {F K L : 类型} [Field F] [Field K] [Field L] [Algebra F K]
  证明: by
  classical
    refine Finset.induction_on s (fun _ => ?_) fun a s _ ih H => ?_
    · rw [coe_empty, Algebra.adjoin_empty]
      exact ⟨(Algebra.ofId F L).comp (Algebra.botEquiv F K)⟩
    rw [forall_mem_insert] at H
    rcases H with ⟨⟨H1, H2⟩, H3⟩
    obtain ⟨f⟩ := ih H3
    choose H3 _ using H3

Depends on / 依赖: Algebra, Algebra.adjoin, Algebra.adjoin_empty, Algebra.adjoin_union_eq_adjoin_adjoin, Algebra.botEquiv, Algebra.ofId, FiniteDimensional, Finset, Finset.induction_on, Set.insert_eq, Set.union_comm, Submodule, Submodule.fg_iff_finiteDimensional, adjoin, adjoin_empty, adjoin_union_eq_adjoin_adjoin, botEquiv, classical, coe_empty, coe_insert
-/
theorem Polynomial.lift_of_splits {F K L : Type*} [Field F] [Field K] [Field L] [Algebra F K]
    [Algebra F L] (s : Finset K) :
      (forall x in s, IsIntegral F x ∧ Splits ((minpoly F x).map (algebraMap F L))) ->
        Nonempty (Algebra.adjoin F (s : Set K) ->ₐ[F] L) := by
  classical
    refine Finset.induction_on s (fun _ => ?_) fun a s _ ih H => ?_
    · rw [coe_empty, Algebra.adjoin_empty]
      exact ⟨(Algebra.ofId F L).comp (Algebra.botEquiv F K)⟩
    rw [forall_mem_insert] at H
    rcases H with ⟨⟨H1, H2⟩, H3⟩
    obtain ⟨f⟩ := ih H3
    choose H3 _ using H3
    rw [coe_insert]; rw [Set.insert_eq]; rw [Set.union_comm]; rw [Algebra.adjoin_union_eq_adjoin_adjoin]
    set Ks := Algebra.adjoin F (s : Set K)
    have : FiniteDimensional F Ks := ((Submodule.fg_iff_finiteDimensional _).1
      (fg_adjoin_of_finite s.finite_toSet H3)).of_subalgebra_toSubmodule
    let := fieldOfFiniteDimensional F Ks
    let := (f : Ks ->+* L).toAlgebra
    have H5 : IsIntegral Ks a := H1.tower_top
    have H6 : ((minpoly Ks a).map (algebraMap Ks L)).Splits := by
      refine Splits.of_dvd H2 (map_ne_zero (minpoly.ne_zero H1)) ?_
      rw [IsScalarTower.algebraMap_eq F Ks L]; rw [← map_map]; rw [map_dvd_map']
      exact minpoly.dvd_map_of_isScalarTower F Ks a
    obtain ⟨y, hy⟩ := H6.exists_eval_eq_zero (by simp [(minpoly.degree_pos H5).ne'])
    rw [eval_map] at hy
exact ⟨Subalgebra.ofRestrictScalars F _ Algebra.adjoin.liftSingleton Ks a y hy⟩

end Embeddings

variable {R K L M : Type*} [CommRing R] [Field K] [Field L] [CommRing M] [Algebra R K]
  [Algebra R M] {x : L}

section
variable [Algebra R L]

/--
theorem `IsIntegral.mem_range_algHom_of_minpoly_splits` / 定理 `IsIntegral.mem_range_algHom_of_minpoly_splits`

English:
theorem IsIntegral.mem_range_algHom_of_minpoly_splits
  proof: show x in Set.range f from Set.image_subset_range _ ((minpoly R x).rootSet K) by
    rw [h.image_rootSet]; rw [mem_rootSet']
    exact ⟨((minpoly.monic int).map _).ne_zero, minpoly.aeval R x⟩

中文:
定理 IsIntegral.mem_range_algHom_of_minpoly_splits
  证明: show x in Set.range f from Set.image_subset_range _ ((minpoly R x).rootSet K) by
    rw [h.image_rootSet]; rw [mem_rootSet']
    exact ⟨((minpoly.monic int).map _).ne_zero, minpoly.aeval R x⟩

Depends on / 依赖: Set.image_subset_range, Set.range, h.image_rootSet, image_rootSet, image_subset_range, mem_rootSet, minpoly, minpoly.aeval, minpoly.monic, ne_zero, rootSet
-/
theorem IsIntegral.mem_range_algHom_of_minpoly_splits
    (int : IsIntegral R x) (h : Splits ((minpoly R x).map (algebraMap R K))) (f : K ->ₐ[R] L) :
    x in f.range :=
show x in Set.range f from Set.image_subset_range _ ((minpoly R x).rootSet K) by
    rw [h.image_rootSet]; rw [mem_rootSet']
    exact ⟨((minpoly.monic int).map _).ne_zero, minpoly.aeval R x⟩

/--
theorem `IsIntegral.mem_range_algebraMap_of_minpoly_splits` / 定理 `IsIntegral.mem_range_algebraMap_of_minpoly_splits`

English:
theorem IsIntegral.mem_range_algebraMap_of_minpoly_splits
  statement: [Algebra K L] [IsScalarTower R K L]
  proof: int.mem_range_algHom_of_minpoly_splits h (IsScalarTower.toAlgHom R K L)

中文:
定理 IsIntegral.mem_range_algebraMap_of_minpoly_splits
  结论: [Algebra K L] [IsScalarTower R K L]
  证明: int.mem_range_algHom_of_minpoly_splits h (IsScalarTower.toAlgHom R K L)

Depends on / 依赖: IsScalarTower, IsScalarTower.toAlgHom, int.mem_range_algHom_of_minpoly_splits, mem_range_algHom_of_minpoly_splits, toAlgHom
-/
theorem IsIntegral.mem_range_algebraMap_of_minpoly_splits [Algebra K L] [IsScalarTower R K L]
    (int : IsIntegral R x) (h : Splits ((minpoly R x).map (algebraMap R K))) :
    x in (algebraMap K L).range :=
  int.mem_range_algHom_of_minpoly_splits h (IsScalarTower.toAlgHom R K L)

/--
theorem `minpoly_neg_splits` / 定理 `minpoly_neg_splits`

English:
theorem minpoly_neg_splits
  given: [Algebra K L] {x : L} (g : ((minpoly K x).map (algebraMap K L)).Splits)
  proof: by
  rw [minpoly.neg]; rw [Polynomial.map_mul]
  apply Splits.mul _ (by simpa [map_comp] using g.comp_neg_X)
  simpa only [map_pow, map_neg, map_one] using
    (map_C (algebraMap K L) ▸ Splits.C (algebraMap K L <| (-1) ^ _) :)

中文:
定理 minpoly_neg_splits
  条件: [Algebra K L] {x : L} (g : ((minpoly K x).map (algebraMap K L)).Splits)
  证明: by
  rw [minpoly.neg]; rw [Polynomial.map_mul]
  apply Splits.mul _ (by simpa [map_comp] using g.comp_neg_X)
  simpa only [map_pow, map_neg, map_one] using
    (map_C (algebraMap K L) ▸ Splits.C (algebraMap K L <| (-1) ^ _) :)

Depends on / 依赖: Polynomial, Polynomial.map_mul, Splits, Splits.C, Splits.mul, algebraMap, comp_neg_X, g.comp_neg_X, map_C, map_comp, map_mul, map_neg, map_one, map_pow, minpoly, minpoly.neg
-/
theorem minpoly_neg_splits [Algebra K L] {x : L} (g : ((minpoly K x).map (algebraMap K L)).Splits) :
    ((minpoly K (-x)).map (algebraMap K L)).Splits := by
  rw [minpoly.neg]; rw [Polynomial.map_mul]
  apply Splits.mul _ (by simpa [map_comp] using g.comp_neg_X)
  simpa only [map_pow, map_neg, map_one] using
    (map_C (algebraMap K L) ▸ Splits.C (algebraMap K L <| (-1) ^ _) :)

/--
theorem `minpoly_add_algebraMap_splits` / 定理 `minpoly_add_algebraMap_splits`

English:
theorem minpoly_add_algebraMap_splits
  statement: [Algebra K L] {x : L} (r : K)
  proof: by
  simpa [minpoly.add_algebraMap, map_comp] using g.comp_X_sub_C (algebraMap K L r)

中文:
定理 minpoly_add_algebraMap_splits
  结论: [Algebra K L] {x : L} (r : K)
  证明: by
  simpa [minpoly.add_algebraMap, map_comp] using g.comp_X_sub_C (algebraMap K L r)

Depends on / 依赖: add_algebraMap, algebraMap, comp_X_sub_C, g.comp_X_sub_C, map_comp, minpoly, minpoly.add_algebraMap
-/
theorem minpoly_add_algebraMap_splits [Algebra K L] {x : L} (r : K)
    (g : ((minpoly K x).map (algebraMap K L)).Splits) :
    ((minpoly K (x + algebraMap K L r)).map (algebraMap K L)).Splits := by
  simpa [minpoly.add_algebraMap, map_comp] using g.comp_X_sub_C (algebraMap K L r)

/--
theorem `minpoly_sub_algebraMap_splits` / 定理 `minpoly_sub_algebraMap_splits`

English:
theorem minpoly_sub_algebraMap_splits
  statement: [Algebra K L] {x : L} (r : K)
  proof: by
  simpa only [sub_eq_add_neg, map_neg] using minpoly_add_algebraMap_splits (-r) g

中文:
定理 minpoly_sub_algebraMap_splits
  结论: [Algebra K L] {x : L} (r : K)
  证明: by
  simpa only [sub_eq_add_neg, map_neg] using minpoly_add_algebraMap_splits (-r) g

Depends on / 依赖: map_neg, minpoly_add_algebraMap_splits, sub_eq_add_neg
-/
theorem minpoly_sub_algebraMap_splits [Algebra K L] {x : L} (r : K)
    (g : ((minpoly K x).map (algebraMap K L)).Splits) :
    ((minpoly K (x - algebraMap K L r)).map (algebraMap K L)).Splits := by
  simpa only [sub_eq_add_neg, map_neg] using minpoly_add_algebraMap_splits (-r) g

/--
theorem `minpoly_algebraMap_add_splits` / 定理 `minpoly_algebraMap_add_splits`

English:
theorem minpoly_algebraMap_add_splits
  statement: [Algebra K L] {x : L} (r : K)
  proof: by
  simpa only [add_comm] using minpoly_add_algebraMap_splits r g

中文:
定理 minpoly_algebraMap_add_splits
  结论: [Algebra K L] {x : L} (r : K)
  证明: by
  simpa only [add_comm] using minpoly_add_algebraMap_splits r g

Depends on / 依赖: add_comm, minpoly_add_algebraMap_splits
-/
theorem minpoly_algebraMap_add_splits [Algebra K L] {x : L} (r : K)
    (g : ((minpoly K x).map (algebraMap K L)).Splits) :
    ((minpoly K (algebraMap K L r + x)).map (algebraMap K L)).Splits := by
  simpa only [add_comm] using minpoly_add_algebraMap_splits r g

/--
theorem `minpoly_algebraMap_sub_splits` / 定理 `minpoly_algebraMap_sub_splits`

English:
theorem minpoly_algebraMap_sub_splits
  statement: [Algebra K L] {x : L} (r : K)
  proof: by
  simpa only [neg_sub] using minpoly_neg_splits (minpoly_sub_algebraMap_splits r g)

中文:
定理 minpoly_algebraMap_sub_splits
  结论: [Algebra K L] {x : L} (r : K)
  证明: by
  simpa only [neg_sub] using minpoly_neg_splits (minpoly_sub_algebraMap_splits r g)

Depends on / 依赖: minpoly_neg_splits, minpoly_sub_algebraMap_splits, neg_sub
-/
theorem minpoly_algebraMap_sub_splits [Algebra K L] {x : L} (r : K)
    (g : ((minpoly K x).map (algebraMap K L)).Splits) :
    ((minpoly K (algebraMap K L r - x)).map (algebraMap K L)).Splits := by
  simpa only [neg_sub] using minpoly_neg_splits (minpoly_sub_algebraMap_splits r g)

end

variable [Algebra K M] [IsScalarTower R K M] {x : M}

/--
theorem `IsIntegral.minpoly_splits_tower_top'` / 定理 `IsIntegral.minpoly_splits_tower_top'`

English:
theorem IsIntegral.minpoly_splits_tower_top'
  statement: (int : IsIntegral R x) {f : K ->+* L}
  proof: Splits.of_dvd h (map_monic_ne_zero (minpoly.monic int))
    (by rw [← map_map, map_dvd_map']; exact minpoly.dvd_map_of_isScalarTower R K x)

中文:
定理 IsIntegral.minpoly_splits_tower_top'
  结论: (int : Is整数egral R x) {f : K ->+* L}
  证明: Splits.of_dvd h (map_monic_ne_zero (minpoly.monic int))
    (by rw [← map_map, map_dvd_map']; exact minpoly.dvd_map_of_isScalarTower R K x)

Depends on / 依赖: Splits, Splits.of_dvd, dvd_map_of_isScalarTower, map_dvd_map, map_map, map_monic_ne_zero, minpoly, minpoly.dvd_map_of_isScalarTower, minpoly.monic, of_dvd
-/
theorem IsIntegral.minpoly_splits_tower_top' (int : IsIntegral R x) {f : K ->+* L}
    (h : Splits ((minpoly R x).map (f.comp <| algebraMap R K))) :
    Splits ((minpoly K x).map f) :=
  Splits.of_dvd h (map_monic_ne_zero (minpoly.monic int))
    (by rw [← map_map, map_dvd_map']; exact minpoly.dvd_map_of_isScalarTower R K x)

/--
theorem `IsIntegral.minpoly_splits_tower_top` / 定理 `IsIntegral.minpoly_splits_tower_top`

English:
theorem IsIntegral.minpoly_splits_tower_top
  statement: [Algebra K L] [Algebra R L] [IsScalarTower R K L]
  proof: by
  rw [IsScalarTower.algebraMap_eq R K L] at h
  exact int.minpoly_splits_tower_top' h

中文:
定理 IsIntegral.minpoly_splits_tower_top
  结论: [Algebra K L] [Algebra R L] [IsScalarTower R K L]
  证明: by
  rw [IsScalarTower.algebraMap_eq R K L] at h
  exact int.minpoly_splits_tower_top' h

Depends on / 依赖: IsScalarTower, IsScalarTower.algebraMap_eq, algebraMap_eq, int.minpoly_splits_tower_top, minpoly_splits_tower_top
-/
theorem IsIntegral.minpoly_splits_tower_top [Algebra K L] [Algebra R L] [IsScalarTower R K L]
    (int : IsIntegral R x) (h : Splits ((minpoly R x).map (algebraMap R L))) :
    Splits ((minpoly K x).map (algebraMap K L)) := by
  rw [IsScalarTower.algebraMap_eq R K L] at h
  exact int.minpoly_splits_tower_top' h

/--
lemma `Subalgebra.adjoin_rank_le` / 引理 `Subalgebra.adjoin_rank_le`

English:
lemma Subalgebra.adjoin_rank_le
  statement: {F : Type*} (E : Type*) {K : Type*}
  proof: by
  rw [← rank_toSubmodule]; rw [Module.Free.rank_eq_card_chooseBasisIndex F L]; rw [L.adjoin_eq_span_basis E (Module.Free.chooseBasis F L)]
.trans Cardinal.mk_range_le exact rank_span_le _

中文:
引理 Subalgebra.adjoin_rank_le
  结论: {F : 类型} (E : 类型) {K : 类型}
  证明: by
  rw [← rank_toSubmodule]; rw [Module.Free.rank_eq_card_chooseBasisIndex F L]; rw [L.adjoin_eq_span_basis E (Module.Free.chooseBasis F L)]
.trans Cardinal.mk_range_le exact rank_span_le _

Depends on / 依赖: Cardinal, Cardinal.mk_range_le, L.adjoin_eq_span_basis, Module, Module.Free.chooseBasis, Module.Free.rank_eq_card_chooseBasisIndex, adjoin_eq_span_basis, chooseBasis, mk_range_le, rank_eq_card_chooseBasisIndex, rank_span_le, rank_toSubmodule
-/
lemma Subalgebra.adjoin_rank_le {F : Type*} (E : Type*) {K : Type*}
    [CommSemiring F] [StrongRankCondition F] [CommSemiring E] [StrongRankCondition E] [Semiring K]
    [SMul F E] [Algebra E K] [Algebra F K] [IsScalarTower F E K]
    (L : Subalgebra F K) [Module.Free F L] :
    Module.rank E (Algebra.adjoin E (L : Set K)) <= Module.rank F L := by
  rw [← rank_toSubmodule]; rw [Module.Free.rank_eq_card_chooseBasisIndex F L]; rw [L.adjoin_eq_span_basis E (Module.Free.chooseBasis F L)]
.trans Cardinal.mk_range_le exact rank_span_le _
