/-
Copyright (c) 2017 Johannes Hölzl. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Johannes Hölzl, Yury Kudryashov
-/
module

public import Mathlib.MeasureTheory.Constructions.BorelSpace.Order
public import Mathlib.MeasureTheory.MeasurableSpace.Prod
public import Mathlib.MeasureTheory.Measure.Typeclasses.NullSingletonClass
public import Mathlib.Topology.Instances.Real.Lemmas

/-!
# Borel (measurable) spaces ℝ, ℝ≥0, ℝ≥0∞

## Main statements

* `borel_eq_generateFrom_Ixx_rat` (where Ixx is one of `{Ioo, Ioi, Iio, Ici, Iic}`):
  the Borel sigma algebra on ℝ is generated by intervals with rational endpoints;
* `isPiSystem_Ixx_rat` (where Ixx is one of `{Ioo, Ioi, Iio, Ici, Iic}`):
  intervals with rational endpoints form a pi system on ℝ;
* `measurable_real_toNNReal`, `measurable_coe_nnreal_real`, `measurable_coe_nnreal_ennreal`,
  `ENNReal.measurable_ofReal`, `ENNReal.measurable_toReal`:
  measurability of various coercions between ℝ, ℝ≥0, and ℝ≥0∞;
* `Measurable.real_toNNReal`, `Measurable.coe_nnreal_real`, `Measurable.coe_nnreal_ennreal`,
  `Measurable.ennreal_ofReal`, `Measurable.ennreal_toNNReal`, `Measurable.ennreal_toReal`:
  measurability of functions composed with various coercions between ℝ, ℝ≥0, and ℝ≥0∞
  (also similar results for a.e.-measurability);
* `Measurable.ennreal*` : measurability of special cases for arithmetic operations on `ℝ≥0∞`.
-/

@[expose] public section

open Set Filter MeasureTheory MeasurableSpace

open scoped Topology NNReal ENNReal

universe u v w x y

variable {α β γ δ : Type*} {ι : Sort y} {s t u : Set α}

namespace Real

/--
theorem `borel_eq_generateFrom_Ioo_rat` / 定理 `borel_eq_generateFrom_Ioo_rat`

English:
theorem borel_eq_generateFrom_Ioo_rat
  proof: isTopologicalBasis_Ioo_rat.borel_eq_generateFrom

中文:
定理 borel_eq_generateFrom_Ioo_rat
  证明: isTopologicalBasis_Ioo_rat.borel_eq_generateFrom

Depends on / 依赖: borel_eq_generateFrom, isTopologicalBasis_Ioo_rat, isTopologicalBasis_Ioo_rat.borel_eq_generateFrom
-/
theorem borel_eq_generateFrom_Ioo_rat :
    borel Real = .generateFrom (⋃ (a : Rat) (b : Rat) (_ : a < b), {Ioo (a : Real) (b : Real)}) :=
  isTopologicalBasis_Ioo_rat.borel_eq_generateFrom

/--
theorem `borel_eq_generateFrom_Iio_rat` / 定理 `borel_eq_generateFrom_Iio_rat`

English:
theorem borel_eq_generateFrom_Iio_rat
  statement: borel Real = .generateFrom (⋃ a : Rat, {Iio (a : Real)})
  proof: by
  rw [borel_eq_generateFrom_Iio]
  refine le_antisymm
    (generateFrom_le ?_)
    (generateFrom_mono <| iUnion_subset fun q => singleton_subset_iff.mpr <| mem_range_self _)
  rintro _ ⟨a, rfl⟩
  have : IsLUB (range ((↑) : Rat -> Real) inter Iio a) a := by
    simp [isLUB_iff_le_iff, mem_upperBou

中文:
定理 borel_eq_generateFrom_Iio_rat
  结论: borel 实数 = .generateFrom (⋃ a : Rat, {Iio (a : 实数)})
  证明: by
  rw [borel_eq_generateFrom_Iio]
  refine le_antisymm
    (generateFrom_le ?_)
    (generateFrom_mono <| iUnion_subset fun q => singleton_subset_iff.mpr <| mem_range_self _)
  rintro _ ⟨a, rfl⟩
  have : IsLUB (range ((↑) : Rat -> Real) inter Iio a) a := by
    simp [isLUB_iff_le_iff, mem_upperBou

Depends on / 依赖: GenerateMeasurab, MeasurableSet, MeasurableSet.biUnion, biUnion, biUnion_Iio_eq, biUnion_image, borel_eq_generateFrom_Iio, generateFrom_le, generateFrom_mono, iUnion_subset, image_inter_preimage, image_univ, isLUB_iff_le_iff, le_antisymm, le_iff_forall_rat_lt_imp_le, mem_range_self, mem_upperBounds, singleton_subset_iff, singleton_subset_iff.mpr, this.biUnion_Iio_eq
-/
theorem borel_eq_generateFrom_Iio_rat : borel Real = .generateFrom (⋃ a : Rat, {Iio (a : Real)}) := by
  rw [borel_eq_generateFrom_Iio]
  refine le_antisymm
    (generateFrom_le ?_)
    (generateFrom_mono <| iUnion_subset fun q => singleton_subset_iff.mpr <| mem_range_self _)
  rintro _ ⟨a, rfl⟩
  have : IsLUB (range ((↑) : Rat -> Real) inter Iio a) a := by
    simp [isLUB_iff_le_iff, mem_upperBounds, ← le_iff_forall_rat_lt_imp_le]
  rw [← this.biUnion_Iio_eq]; rw [← image_univ]; rw [← image_inter_preimage]; rw [univ_inter]; rw [biUnion_image]
  exact MeasurableSet.biUnion (to_countable _)
    fun b _ => GenerateMeasurable.basic (Iio (b : Real)) (by simp)

/--
theorem `borel_eq_generateFrom_Ioi_rat` / 定理 `borel_eq_generateFrom_Ioi_rat`

English:
theorem borel_eq_generateFrom_Ioi_rat
  statement: borel Real = .generateFrom (⋃ a : Rat, {Ioi (a : Real)})
  proof: by
  rw [borel_eq_generateFrom_Ioi]
  refine le_antisymm
    (generateFrom_le ?_)
    (generateFrom_mono <| iUnion_subset fun q => singleton_subset_iff.mpr <| mem_range_self _)
  rintro _ ⟨a, rfl⟩
  have : IsGLB (range ((↑) : Rat -> Real) inter Ioi a) a := by
    simp [isGLB_iff_le_iff, mem_lowerBou

中文:
定理 borel_eq_generateFrom_Ioi_rat
  结论: borel 实数 = .generateFrom (⋃ a : Rat, {Ioi (a : 实数)})
  证明: by
  rw [borel_eq_generateFrom_Ioi]
  refine le_antisymm
    (generateFrom_le ?_)
    (generateFrom_mono <| iUnion_subset fun q => singleton_subset_iff.mpr <| mem_range_self _)
  rintro _ ⟨a, rfl⟩
  have : IsGLB (range ((↑) : Rat -> Real) inter Ioi a) a := by
    simp [isGLB_iff_le_iff, mem_lowerBou

Depends on / 依赖: GenerateMeasurab, MeasurableSet, MeasurableSet.biUnion, biUnion, biUnion_Ioi_eq, biUnion_image, borel_eq_generateFrom_Ioi, generateFrom_le, generateFrom_mono, iUnion_subset, image_inter_preimage, image_univ, isGLB_iff_le_iff, le_antisymm, le_iff_forall_lt_rat_imp_le, mem_lowerBounds, mem_range_self, singleton_subset_iff, singleton_subset_iff.mpr, this.biUnion_Ioi_eq
-/
theorem borel_eq_generateFrom_Ioi_rat : borel Real = .generateFrom (⋃ a : Rat, {Ioi (a : Real)}) := by
  rw [borel_eq_generateFrom_Ioi]
  refine le_antisymm
    (generateFrom_le ?_)
    (generateFrom_mono <| iUnion_subset fun q => singleton_subset_iff.mpr <| mem_range_self _)
  rintro _ ⟨a, rfl⟩
  have : IsGLB (range ((↑) : Rat -> Real) inter Ioi a) a := by
    simp [isGLB_iff_le_iff, mem_lowerBounds, ← le_iff_forall_lt_rat_imp_le]
  rw [← this.biUnion_Ioi_eq]; rw [← image_univ]; rw [← image_inter_preimage]; rw [univ_inter]; rw [biUnion_image]
  exact MeasurableSet.biUnion (to_countable _)
    fun b _ => GenerateMeasurable.basic (Ioi (b : Real)) (by simp)

/--
theorem `borel_eq_generateFrom_Iic_rat` / 定理 `borel_eq_generateFrom_Iic_rat`

English:
theorem borel_eq_generateFrom_Iic_rat
  statement: borel Real = .generateFrom (⋃ a : Rat, {Iic (a : Real)})
  proof: by
  rw [borel_eq_generateFrom_Ioi_rat]; rw [iUnion_singleton_eq_range]; rw [iUnion_singleton_eq_range]
  refine le_antisymm (generateFrom_le ?_) (generateFrom_le ?_) <;>
  rintro _ ⟨q, rfl⟩ <;>
  dsimp only <;>
  [rw [← compl_Iic]; rw [← compl_Ioi]] <;>
  exact MeasurableSet.compl (GenerateMeasurab

中文:
定理 borel_eq_generateFrom_Iic_rat
  结论: borel 实数 = .generateFrom (⋃ a : Rat, {Iic (a : 实数)})
  证明: by
  rw [borel_eq_generateFrom_Ioi_rat]; rw [iUnion_singleton_eq_range]; rw [iUnion_singleton_eq_range]
  refine le_antisymm (generateFrom_le ?_) (generateFrom_le ?_) <;>
  rintro _ ⟨q, rfl⟩ <;>
  dsimp only <;>
  [rw [← compl_Iic]; rw [← compl_Ioi]] <;>
  exact MeasurableSet.compl (GenerateMeasurab

Depends on / 依赖: GenerateMeasurable, GenerateMeasurable.basic, MeasurableSet, MeasurableSet.compl, borel_eq_generateFrom_Ioi_rat, compl_Iic, compl_Ioi, generateFrom_le, iUnion_singleton_eq_range, le_antisymm, mem_range_self
-/
theorem borel_eq_generateFrom_Iic_rat : borel Real = .generateFrom (⋃ a : Rat, {Iic (a : Real)}) := by
  rw [borel_eq_generateFrom_Ioi_rat]; rw [iUnion_singleton_eq_range]; rw [iUnion_singleton_eq_range]
  refine le_antisymm (generateFrom_le ?_) (generateFrom_le ?_) <;>
  rintro _ ⟨q, rfl⟩ <;>
  dsimp only <;>
  [rw [← compl_Iic]; rw [← compl_Ioi]] <;>
  exact MeasurableSet.compl (GenerateMeasurable.basic _ (mem_range_self q))

/--
theorem `borel_eq_generateFrom_Ici_rat` / 定理 `borel_eq_generateFrom_Ici_rat`

English:
theorem borel_eq_generateFrom_Ici_rat
  statement: borel Real = .generateFrom (⋃ a : Rat, {Ici (a : Real)})
  proof: by
  rw [borel_eq_generateFrom_Iio_rat]; rw [iUnion_singleton_eq_range]; rw [iUnion_singleton_eq_range]
  refine le_antisymm (generateFrom_le ?_) (generateFrom_le ?_) <;>
  rintro _ ⟨q, rfl⟩ <;>
  dsimp only <;>
  [rw [← compl_Ici]; rw [← compl_Iio]] <;>
  exact MeasurableSet.compl (GenerateMeasurab

中文:
定理 borel_eq_generateFrom_Ici_rat
  结论: borel 实数 = .generateFrom (⋃ a : Rat, {Ici (a : 实数)})
  证明: by
  rw [borel_eq_generateFrom_Iio_rat]; rw [iUnion_singleton_eq_range]; rw [iUnion_singleton_eq_range]
  refine le_antisymm (generateFrom_le ?_) (generateFrom_le ?_) <;>
  rintro _ ⟨q, rfl⟩ <;>
  dsimp only <;>
  [rw [← compl_Ici]; rw [← compl_Iio]] <;>
  exact MeasurableSet.compl (GenerateMeasurab

Depends on / 依赖: GenerateMeasurable, GenerateMeasurable.basic, MeasurableSet, MeasurableSet.compl, borel_eq_generateFrom_Iio_rat, compl_Ici, compl_Iio, generateFrom_le, iUnion_singleton_eq_range, le_antisymm, mem_range_self
-/
theorem borel_eq_generateFrom_Ici_rat : borel Real = .generateFrom (⋃ a : Rat, {Ici (a : Real)}) := by
  rw [borel_eq_generateFrom_Iio_rat]; rw [iUnion_singleton_eq_range]; rw [iUnion_singleton_eq_range]
  refine le_antisymm (generateFrom_le ?_) (generateFrom_le ?_) <;>
  rintro _ ⟨q, rfl⟩ <;>
  dsimp only <;>
  [rw [← compl_Ici]; rw [← compl_Iio]] <;>
  exact MeasurableSet.compl (GenerateMeasurable.basic _ (mem_range_self q))

/--
theorem `isPiSystem_Ioo_rat` / 定理 `isPiSystem_Ioo_rat`

English:
theorem isPiSystem_Ioo_rat
  proof: by
  convert! isPiSystem_Ioo ((↑) : Rat -> Real) ((↑) : Rat -> Real)
  ext x
  simp [eq_comm]

中文:
定理 isPiSystem_Ioo_rat
  证明: by
  convert! isPiSystem_Ioo ((↑) : Rat -> Real) ((↑) : Rat -> Real)
  ext x
  simp [eq_comm]

Depends on / 依赖: convert, eq_comm, isPiSystem_Ioo
-/
theorem isPiSystem_Ioo_rat :
    IsPiSystem (⋃ (a : Rat) (b : Rat) (_ : a < b), {Ioo (a : Real) (b : Real)}) := by
  convert! isPiSystem_Ioo ((↑) : Rat -> Real) ((↑) : Rat -> Real)
  ext x
  simp [eq_comm]

/--
theorem `isPiSystem_Iio_rat` / 定理 `isPiSystem_Iio_rat`

English:
theorem isPiSystem_Iio_rat
  statement: IsPiSystem (⋃ a : Rat, {Iio (a : Real)})
  proof: by
  convert! isPiSystem_image_Iio (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

中文:
定理 isPiSystem_Iio_rat
  结论: IsPiSystem (⋃ a : Rat, {Iio (a : 实数)})
  证明: by
  convert! isPiSystem_image_Iio (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

Depends on / 依赖: convert, exists_exists_eq_and, iUnion_singleton_eq_range, image_univ, isPiSystem_image_Iio, mem_image, mem_range
-/
theorem isPiSystem_Iio_rat : IsPiSystem (⋃ a : Rat, {Iio (a : Real)}) := by
  convert! isPiSystem_image_Iio (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

/--
theorem `isPiSystem_Ioi_rat` / 定理 `isPiSystem_Ioi_rat`

English:
theorem isPiSystem_Ioi_rat
  statement: IsPiSystem (⋃ a : Rat, {Ioi (a : Real)})
  proof: by
  convert! isPiSystem_image_Ioi (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

中文:
定理 isPiSystem_Ioi_rat
  结论: IsPiSystem (⋃ a : Rat, {Ioi (a : 实数)})
  证明: by
  convert! isPiSystem_image_Ioi (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

Depends on / 依赖: convert, exists_exists_eq_and, iUnion_singleton_eq_range, image_univ, isPiSystem_image_Ioi, mem_image, mem_range
-/
theorem isPiSystem_Ioi_rat : IsPiSystem (⋃ a : Rat, {Ioi (a : Real)}) := by
  convert! isPiSystem_image_Ioi (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

/--
theorem `isPiSystem_Iic_rat` / 定理 `isPiSystem_Iic_rat`

English:
theorem isPiSystem_Iic_rat
  statement: IsPiSystem (⋃ a : Rat, {Iic (a : Real)})
  proof: by
  convert! isPiSystem_image_Iic (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

中文:
定理 isPiSystem_Iic_rat
  结论: IsPiSystem (⋃ a : Rat, {Iic (a : 实数)})
  证明: by
  convert! isPiSystem_image_Iic (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

Depends on / 依赖: convert, exists_exists_eq_and, iUnion_singleton_eq_range, image_univ, isPiSystem_image_Iic, mem_image, mem_range
-/
theorem isPiSystem_Iic_rat : IsPiSystem (⋃ a : Rat, {Iic (a : Real)}) := by
  convert! isPiSystem_image_Iic (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

/--
theorem `isPiSystem_Ici_rat` / 定理 `isPiSystem_Ici_rat`

English:
theorem isPiSystem_Ici_rat
  statement: IsPiSystem (⋃ a : Rat, {Ici (a : Real)})
  proof: by
  convert! isPiSystem_image_Ici (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

中文:
定理 isPiSystem_Ici_rat
  结论: IsPiSystem (⋃ a : Rat, {Ici (a : 实数)})
  证明: by
  convert! isPiSystem_image_Ici (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

Depends on / 依赖: convert, exists_exists_eq_and, iUnion_singleton_eq_range, image_univ, isPiSystem_image_Ici, mem_image, mem_range
-/
theorem isPiSystem_Ici_rat : IsPiSystem (⋃ a : Rat, {Ici (a : Real)}) := by
  convert! isPiSystem_image_Ici (((↑) : Rat -> Real) '' univ)
  ext x
  simp only [iUnion_singleton_eq_range, mem_range, image_univ, mem_image, exists_exists_eq_and]

/--
Definition of `finiteSpanningSetsInIooRat` / `finiteSpanningSetsInIooRat` 的定义

English:
definition finiteSpanningSetsInIooRat
  signature: (μ : Measure Real) [IsLocallyFiniteMeasure μ]
  body: Ioo (-(n + 1)) (n + 1)
  set_mem n := by
    simp only [mem_iUnion, mem_singleton_iff]
    refine ⟨-(n + 1 : Nat), n + 1, ?_, by simp⟩
    -- TODO: norm_cast fails here?
    push_cast
    exact neg_lt_self n.cast_add_one_pos
  finite _ := measure_Ioo_lt_top
  spanning :=
    iUnion_eq_univ_iff.2 fun

中文:
定义 finiteSpanningSetsInIooRat
  签名: (μ : Measure 实数) [IsLocallyFiniteMeasure μ]
  定义体: Ioo (-(n + 1)) (n + 1)
  set_mem n := by
    simp only [mem_iUnion, mem_singleton_iff]
    refine ⟨-(n + 1 : Nat), n + 1, ?_, by simp⟩
    -- TODO: norm_cast fails here?
    push_cast
    exact neg_lt_self n.cast_add_one_pos
  finite _ := measure_Ioo_lt_top
  spanning :=
    iUnion_eq_univ_iff.2 fun
-/
def finiteSpanningSetsInIooRat (μ : Measure Real) [IsLocallyFiniteMeasure μ] :
    μ.FiniteSpanningSetsIn (⋃ (a : Rat) (b : Rat) (_ : a < b), {Ioo (a : Real) (b : Real)}) where
  set n := Ioo (-(n + 1)) (n + 1)
  set_mem n := by
    simp only [mem_iUnion, mem_singleton_iff]
    refine ⟨-(n + 1 : Nat), n + 1, ?_, by simp⟩
    -- TODO: norm_cast fails here?
    push_cast
    exact neg_lt_self n.cast_add_one_pos
  finite _ := measure_Ioo_lt_top
  spanning :=
    iUnion_eq_univ_iff.2 fun x =>
      ⟨⌊|x|⌋₊, neg_lt.1 ((neg_le_abs x).trans_lt (Nat.lt_floor_add_one _)),
        (le_abs_self x).trans_lt (Nat.lt_floor_add_one _)⟩

/--
theorem `measure_ext_Ioo_rat` / 定理 `measure_ext_Ioo_rat`

English:
theorem measure_ext_Ioo_rat
  statement: {μ ν : Measure Real} [IsLocallyFiniteMeasure μ]
  proof: (finiteSpanningSetsInIooRat μ).ext borel_eq_generateFrom_Ioo_rat isPiSystem_Ioo_rat by
    simp only [mem_iUnion, mem_singleton_iff]
    rintro _ ⟨a, b, -, rfl⟩
    apply h

中文:
定理 measure_ext_Ioo_rat
  结论: {μ ν : Measure 实数} [IsLocallyFiniteMeasure μ]
  证明: (finiteSpanningSetsInIooRat μ).ext borel_eq_generateFrom_Ioo_rat isPiSystem_Ioo_rat by
    simp only [mem_iUnion, mem_singleton_iff]
    rintro _ ⟨a, b, -, rfl⟩
    apply h

Depends on / 依赖: borel_eq_generateFrom_Ioo_rat, finiteSpanningSetsInIooRat, isPiSystem_Ioo_rat, mem_iUnion, mem_singleton_iff
-/
theorem measure_ext_Ioo_rat {μ ν : Measure Real} [IsLocallyFiniteMeasure μ]
    (h : forall a b : Rat, μ (Ioo a b) = ν (Ioo a b)) : μ = ν :=
(finiteSpanningSetsInIooRat μ).ext borel_eq_generateFrom_Ioo_rat isPiSystem_Ioo_rat by
    simp only [mem_iUnion, mem_singleton_iff]
    rintro _ ⟨a, b, -, rfl⟩
    apply h

end Real

variable {mα : MeasurableSpace α}

@[fun_prop]
/--
theorem `measurable_real_toNNReal` / 定理 `measurable_real_toNNReal`

English:
theorem measurable_real_toNNReal
  statement: Measurable Real.toNNReal
  proof: continuous_real_toNNReal.measurable

@[fun_prop]

中文:
定理 measurable_real_toNNReal
  结论: Measurable 实数.toNN实数
  证明: continuous_real_toNNReal.measurable

@[fun_prop]

Depends on / 依赖: continuous_real_toNNReal, continuous_real_toNNReal.measurable, measurable
-/
theorem measurable_real_toNNReal : Measurable Real.toNNReal :=
  continuous_real_toNNReal.measurable

@[fun_prop]
/--
theorem `Measurable.real_toNNReal` / 定理 `Measurable.real_toNNReal`

English:
theorem Measurable.real_toNNReal
  given: {f : α -> Real} (hf : Measurable f)
  proof: measurable_real_toNNReal.comp hf

@[fun_prop]

中文:
定理 Measurable.real_toNNReal
  条件: {f : α -> 实数} (hf : Measurable f)
  证明: measurable_real_toNNReal.comp hf

@[fun_prop]

Depends on / 依赖: measurable_real_toNNReal, measurable_real_toNNReal.comp
-/
theorem Measurable.real_toNNReal {f : α -> Real} (hf : Measurable f) :
    Measurable fun x => Real.toNNReal (f x) :=
  measurable_real_toNNReal.comp hf

@[fun_prop]
/--
theorem `AEMeasurable.real_toNNReal` / 定理 `AEMeasurable.real_toNNReal`

English:
theorem AEMeasurable.real_toNNReal
  given: {f : α -> Real} {μ : Measure α} (hf : AEMeasurable f μ)
  proof: measurable_real_toNNReal.comp_aemeasurable hf

中文:
定理 AEMeasurable.real_toNNReal
  条件: {f : α -> 实数} {μ : Measure α} (hf : AEMeasurable f μ)
  证明: measurable_real_toNNReal.comp_aemeasurable hf

Depends on / 依赖: comp_aemeasurable, measurable_real_toNNReal, measurable_real_toNNReal.comp_aemeasurable
-/
theorem AEMeasurable.real_toNNReal {f : α -> Real} {μ : Measure α} (hf : AEMeasurable f μ) :
    AEMeasurable (fun x => Real.toNNReal (f x)) μ :=
  measurable_real_toNNReal.comp_aemeasurable hf

/--
theorem `measurable_coe_nnreal_real` / 定理 `measurable_coe_nnreal_real`

English:
theorem measurable_coe_nnreal_real
  statement: Measurable ((↑) : Real>=0 -> Real)
  proof: NNReal.continuous_coe.measurable

@[fun_prop]

中文:
定理 measurable_coe_nnreal_real
  结论: Measurable ((↑) : 实数>=0 -> 实数)
  证明: NNReal.continuous_coe.measurable

@[fun_prop]

Depends on / 依赖: NNReal, NNReal.continuous_coe.measurable, continuous_coe, measurable
-/
theorem measurable_coe_nnreal_real : Measurable ((↑) : Real>=0 -> Real) :=
  NNReal.continuous_coe.measurable

@[fun_prop]
/--
theorem `Measurable.coe_nnreal_real` / 定理 `Measurable.coe_nnreal_real`

English:
theorem Measurable.coe_nnreal_real
  given: {f : α -> Real>=0} (hf : Measurable f)
  proof: measurable_coe_nnreal_real.comp hf

@[fun_prop]

中文:
定理 Measurable.coe_nnreal_real
  条件: {f : α -> 实数>=0} (hf : Measurable f)
  证明: measurable_coe_nnreal_real.comp hf

@[fun_prop]

Depends on / 依赖: measurable_coe_nnreal_real, measurable_coe_nnreal_real.comp
-/
theorem Measurable.coe_nnreal_real {f : α -> Real>=0} (hf : Measurable f) :
    Measurable fun x => (f x : Real) :=
  measurable_coe_nnreal_real.comp hf

@[fun_prop]
/--
theorem `AEMeasurable.coe_nnreal_real` / 定理 `AEMeasurable.coe_nnreal_real`

English:
theorem AEMeasurable.coe_nnreal_real
  given: {f : α -> Real>=0} {μ : Measure α} (hf : AEMeasurable f μ)
  proof: measurable_coe_nnreal_real.comp_aemeasurable hf

中文:
定理 AEMeasurable.coe_nnreal_real
  条件: {f : α -> 实数>=0} {μ : Measure α} (hf : AEMeasurable f μ)
  证明: measurable_coe_nnreal_real.comp_aemeasurable hf

Depends on / 依赖: comp_aemeasurable, measurable_coe_nnreal_real, measurable_coe_nnreal_real.comp_aemeasurable
-/
theorem AEMeasurable.coe_nnreal_real {f : α -> Real>=0} {μ : Measure α} (hf : AEMeasurable f μ) :
    AEMeasurable (fun x => (f x : Real)) μ :=
  measurable_coe_nnreal_real.comp_aemeasurable hf

/--
theorem `measurable_coe_nnreal_ennreal` / 定理 `measurable_coe_nnreal_ennreal`

English:
theorem measurable_coe_nnreal_ennreal
  statement: Measurable ((↑) : Real>=0 -> Real>=0∞)
  proof: ENNReal.continuous_coe.measurable

@[fun_prop]

中文:
定理 measurable_coe_nnreal_ennreal
  结论: Measurable ((↑) : 实数>=0 -> 实数>=0∞)
  证明: ENNReal.continuous_coe.measurable

@[fun_prop]

Depends on / 依赖: ENNReal, ENNReal.continuous_coe.measurable, continuous_coe, measurable
-/
theorem measurable_coe_nnreal_ennreal : Measurable ((↑) : Real>=0 -> Real>=0∞) :=
  ENNReal.continuous_coe.measurable

@[fun_prop]
/--
theorem `Measurable.coe_nnreal_ennreal` / 定理 `Measurable.coe_nnreal_ennreal`

English:
theorem Measurable.coe_nnreal_ennreal
  given: {f : α -> Real>=0} (hf : Measurable f)
  proof: ENNReal.continuous_coe.measurable.comp hf

@[fun_prop]

中文:
定理 Measurable.coe_nnreal_ennreal
  条件: {f : α -> 实数>=0} (hf : Measurable f)
  证明: ENNReal.continuous_coe.measurable.comp hf

@[fun_prop]

Depends on / 依赖: ENNReal, ENNReal.continuous_coe.measurable.comp, continuous_coe, measurable
-/
theorem Measurable.coe_nnreal_ennreal {f : α -> Real>=0} (hf : Measurable f) :
    Measurable fun x => (f x : Real>=0∞) :=
  ENNReal.continuous_coe.measurable.comp hf

@[fun_prop]
/--
theorem `AEMeasurable.coe_nnreal_ennreal` / 定理 `AEMeasurable.coe_nnreal_ennreal`

English:
theorem AEMeasurable.coe_nnreal_ennreal
  given: {f : α -> Real>=0} {μ : Measure α} (hf : AEMeasurable f μ)
  proof: ENNReal.continuous_coe.measurable.comp_aemeasurable hf

@[fun_prop]

中文:
定理 AEMeasurable.coe_nnreal_ennreal
  条件: {f : α -> 实数>=0} {μ : Measure α} (hf : AEMeasurable f μ)
  证明: ENNReal.continuous_coe.measurable.comp_aemeasurable hf

@[fun_prop]

Depends on / 依赖: ENNReal, ENNReal.continuous_coe.measurable.comp_aemeasurable, comp_aemeasurable, continuous_coe, measurable
-/
theorem AEMeasurable.coe_nnreal_ennreal {f : α -> Real>=0} {μ : Measure α} (hf : AEMeasurable f μ) :
    AEMeasurable (fun x => (f x : Real>=0∞)) μ :=
  ENNReal.continuous_coe.measurable.comp_aemeasurable hf

@[fun_prop]
/--
theorem `Measurable.ennreal_ofReal` / 定理 `Measurable.ennreal_ofReal`

English:
theorem Measurable.ennreal_ofReal
  given: {f : α -> Real} (hf : Measurable f)
  proof: ENNReal.continuous_ofReal.measurable.comp hf

@[fun_prop]

中文:
定理 Measurable.ennreal_ofReal
  条件: {f : α -> 实数} (hf : Measurable f)
  证明: ENNReal.continuous_ofReal.measurable.comp hf

@[fun_prop]

Depends on / 依赖: ENNReal, ENNReal.continuous_ofReal.measurable.comp, continuous_ofReal, measurable
-/
theorem Measurable.ennreal_ofReal {f : α -> Real} (hf : Measurable f) :
    Measurable fun x => ENNReal.ofReal (f x) :=
  ENNReal.continuous_ofReal.measurable.comp hf

@[fun_prop]
/--
lemma `AEMeasurable.ennreal_ofReal` / 引理 `AEMeasurable.ennreal_ofReal`

English:
lemma AEMeasurable.ennreal_ofReal
  given: {f : α -> Real} {μ : Measure α} (hf : AEMeasurable f μ)
  proof: ENNReal.continuous_ofReal.measurable.comp_aemeasurable hf

@[simp, norm_cast]

中文:
引理 AEMeasurable.ennreal_ofReal
  条件: {f : α -> 实数} {μ : Measure α} (hf : AEMeasurable f μ)
  证明: ENNReal.continuous_ofReal.measurable.comp_aemeasurable hf

@[simp, norm_cast]

Depends on / 依赖: ENNReal, ENNReal.continuous_ofReal.measurable.comp_aemeasurable, comp_aemeasurable, continuous_ofReal, measurable
-/
lemma AEMeasurable.ennreal_ofReal {f : α -> Real} {μ : Measure α} (hf : AEMeasurable f μ) :
    AEMeasurable (fun x => ENNReal.ofReal (f x)) μ :=
  ENNReal.continuous_ofReal.measurable.comp_aemeasurable hf

@[simp, norm_cast]
/--
theorem `measurable_coe_nnreal_real_iff` / 定理 `measurable_coe_nnreal_real_iff`

English:
theorem measurable_coe_nnreal_real_iff
  given: {f : α -> Real>=0}
  proof: ⟨fun h => by simpa only [Real.toNNReal_coe] using h.real_toNNReal, Measurable.coe_nnreal_real⟩

@[fun_prop]

中文:
定理 measurable_coe_nnreal_real_iff
  条件: {f : α -> 实数>=0}
  证明: ⟨fun h => by simpa only [Real.toNNReal_coe] using h.real_toNNReal, Measurable.coe_nnreal_real⟩

@[fun_prop]

Depends on / 依赖: Measurable, Measurable.coe_nnreal_real, Real.toNNReal_coe, coe_nnreal_real, h.real_toNNReal, real_toNNReal, toNNReal_coe
-/
theorem measurable_coe_nnreal_real_iff {f : α -> Real>=0} :
    Measurable (fun x => f x : α -> Real) ↔ Measurable f :=
  ⟨fun h => by simpa only [Real.toNNReal_coe] using h.real_toNNReal, Measurable.coe_nnreal_real⟩

@[fun_prop]
/--
theorem `Measurable.nnreal_mk` / 定理 `Measurable.nnreal_mk`

English:
theorem Measurable.nnreal_mk
  given: {f : α -> Real} (hf : Measurable f) {h'f : forall x, 0 <= f x}
  proof: measurable_coe_nnreal_real_iff.mp hf

@[simp, norm_cast]

中文:
定理 Measurable.nnreal_mk
  条件: {f : α -> 实数} (hf : Measurable f) {h'f : 对任意 x, 0 <= f x}
  证明: measurable_coe_nnreal_real_iff.mp hf

@[simp, norm_cast]

Depends on / 依赖: measurable_coe_nnreal_real_iff, measurable_coe_nnreal_real_iff.mp
-/
theorem Measurable.nnreal_mk {f : α -> Real} (hf : Measurable f) {h'f : forall x, 0 <= f x} :
    Measurable (fun x => NNReal.mk (f x) (h'f x)) :=
  measurable_coe_nnreal_real_iff.mp hf

@[simp, norm_cast]
/--
theorem `aemeasurable_coe_nnreal_real_iff` / 定理 `aemeasurable_coe_nnreal_real_iff`

English:
theorem aemeasurable_coe_nnreal_real_iff
  given: {f : α -> Real>=0} {μ : Measure α}
  proof: ⟨fun h => by simpa only [Real.toNNReal_coe] using h.real_toNNReal, AEMeasurable.coe_nnreal_real⟩

中文:
定理 aemeasurable_coe_nnreal_real_iff
  条件: {f : α -> 实数>=0} {μ : Measure α}
  证明: ⟨fun h => by simpa only [Real.toNNReal_coe] using h.real_toNNReal, AEMeasurable.coe_nnreal_real⟩

Depends on / 依赖: AEMeasurable, AEMeasurable.coe_nnreal_real, Real.toNNReal_coe, coe_nnreal_real, h.real_toNNReal, real_toNNReal, toNNReal_coe
-/
theorem aemeasurable_coe_nnreal_real_iff {f : α -> Real>=0} {μ : Measure α} :
    AEMeasurable (fun x => f x : α -> Real) μ ↔ AEMeasurable f μ :=
  ⟨fun h => by simpa only [Real.toNNReal_coe] using h.real_toNNReal, AEMeasurable.coe_nnreal_real⟩

/--
Definition of `MeasurableEquiv.ennrealEquivNNReal` / `MeasurableEquiv.ennrealEquivNNReal` 的定义

English:
definition MeasurableEquiv.ennrealEquivNNReal
  signature: : { r : Real>=0∞ | r != ∞ } ≃ᵐ Real>=0
  body: ENNReal.neTopHomeomorphNNReal.toMeasurableEquiv

中文:
定义 MeasurableEquiv.ennrealEquivNNReal
  签名: : { r : 实数>=0∞ | r != ∞ } ≃ᵐ 实数>=0
  定义体: ENNReal.neTopHomeomorphNNReal.toMeasurableEquiv

Depends on / 依赖: ENNReal, ENNReal.neTopHomeomorphNNReal.toMeasurableEquiv, neTopHomeomorphNNReal, toMeasurableEquiv
-/
def MeasurableEquiv.ennrealEquivNNReal : { r : Real>=0∞ | r != ∞ } ≃ᵐ Real>=0 :=
  ENNReal.neTopHomeomorphNNReal.toMeasurableEquiv

namespace ENNReal

/--
theorem `measurable_of_measurable_nnreal` / 定理 `measurable_of_measurable_nnreal`

English:
theorem measurable_of_measurable_nnreal
  given: {f : Real>=0∞ -> α} (h : Measurable fun p : Real>=0 => f p)
  proof: measurable_of_measurable_on_compl_singleton ∞
    (MeasurableEquiv.ennrealEquivNNReal.symm.measurable_comp_iff.1 h)

中文:
定理 measurable_of_measurable_nnreal
  条件: {f : 实数>=0∞ -> α} (h : Measurable fun p : 实数>=0 => f p)
  证明: measurable_of_measurable_on_compl_singleton ∞
    (MeasurableEquiv.ennrealEquivNNReal.symm.measurable_comp_iff.1 h)

Depends on / 依赖: MeasurableEquiv, MeasurableEquiv.ennrealEquivNNReal.symm.measurable_comp_iff, ennrealEquivNNReal, measurable_comp_iff, measurable_of_measurable_on_compl_singleton
-/
theorem measurable_of_measurable_nnreal {f : Real>=0∞ -> α} (h : Measurable fun p : Real>=0 => f p) :
    Measurable f :=
  measurable_of_measurable_on_compl_singleton ∞
    (MeasurableEquiv.ennrealEquivNNReal.symm.measurable_comp_iff.1 h)

/--
Definition of `ennrealEquivSum` / `ennrealEquivSum` 的定义

English:
definition ennrealEquivSum
  signature: : Real>=0∞ ≃ᵐ Real>=0 oplus Unit
  body: { Equiv.optionEquivSumPUnit Real>=0 with
    measurable_toFun := measurable_of_measurable_nnreal measurable_inl
    measurable_invFun :=
      measurable_fun_sum measurable_coe_nnreal_ennreal (@measurable_const Real>=0∞ Unit _ _ ∞) }

中文:
定义 ennrealEquivSum
  签名: : 实数>=0∞ ≃ᵐ 实数>=0 oplus Unit
  定义体: { Equiv.optionEquivSumPUnit Real>=0 with
    measurable_toFun := measurable_of_measurable_nnreal measurable_inl
    measurable_invFun :=
      measurable_fun_sum measurable_coe_nnreal_ennreal (@measurable_const Real>=0∞ Unit _ _ ∞) }

Depends on / 依赖: Equiv.optionEquivSumPUnit, measurable_coe_nnreal_ennreal, measurable_const, measurable_fun_sum, measurable_inl, measurable_invFun, measurable_of_measurable_nnreal, measurable_toFun, optionEquivSumPUnit
-/
def ennrealEquivSum : Real>=0∞ ≃ᵐ Real>=0 oplus Unit :=
  { Equiv.optionEquivSumPUnit Real>=0 with
    measurable_toFun := measurable_of_measurable_nnreal measurable_inl
    measurable_invFun :=
      measurable_fun_sum measurable_coe_nnreal_ennreal (@measurable_const Real>=0∞ Unit _ _ ∞) }

open Function (uncurry)

/--
theorem `measurable_of_measurable_nnreal_prod` / 定理 `measurable_of_measurable_nnreal_prod`

English:
theorem measurable_of_measurable_nnreal_prod
  statement: {_ : MeasurableSpace β} {_ : MeasurableSpace γ}
  proof: let e : Real>=0∞ × β ≃ᵐ (Real>=0 × β) oplus (Unit × β) :=
    (ennrealEquivSum.prodCongr (MeasurableEquiv.refl β)).trans
      (MeasurableEquiv.sumProdDistrib _ _ _)
e.symm.measurable_comp_iff.1 measurable_fun_sum H₁ (H₂.comp measurable_id.snd)

中文:
定理 measurable_of_measurable_nnreal_prod
  结论: {_ : MeasurableSpace β} {_ : MeasurableSpace γ}
  证明: let e : Real>=0∞ × β ≃ᵐ (Real>=0 × β) oplus (Unit × β) :=
    (ennrealEquivSum.prodCongr (MeasurableEquiv.refl β)).trans
      (MeasurableEquiv.sumProdDistrib _ _ _)
e.symm.measurable_comp_iff.1 measurable_fun_sum H₁ (H₂.comp measurable_id.snd)

Depends on / 依赖: MeasurableEquiv, MeasurableEquiv.refl, MeasurableEquiv.sumProdDistrib, e.symm.measurable_comp_iff, ennrealEquivSum, ennrealEquivSum.prodCongr, measurable_comp_iff, measurable_fun_sum, measurable_id, measurable_id.snd, prodCongr, sumProdDistrib
-/
theorem measurable_of_measurable_nnreal_prod {_ : MeasurableSpace β} {_ : MeasurableSpace γ}
    {f : Real>=0∞ × β -> γ} (H₁ : Measurable fun p : Real>=0 × β => f (p.1, p.2))
    (H₂ : Measurable fun x => f (∞, x)) : Measurable f :=
  let e : Real>=0∞ × β ≃ᵐ (Real>=0 × β) oplus (Unit × β) :=
    (ennrealEquivSum.prodCongr (MeasurableEquiv.refl β)).trans
      (MeasurableEquiv.sumProdDistrib _ _ _)
e.symm.measurable_comp_iff.1 measurable_fun_sum H₁ (H₂.comp measurable_id.snd)

/--
theorem `measurable_of_measurable_nnreal_nnreal` / 定理 `measurable_of_measurable_nnreal_nnreal`

English:
theorem measurable_of_measurable_nnreal_nnreal
  statement: {_ : MeasurableSpace β} {f : Real>=0∞ × Real>=0∞ -> β}
  proof: measurable_of_measurable_nnreal_prod
    (measurable_swap_iff.1 <| measurable_of_measurable_nnreal_prod (h₁.comp measurable_swap) h₃)
    (measurable_of_measurable_nnreal h₂)

中文:
定理 measurable_of_measurable_nnreal_nnreal
  结论: {_ : MeasurableSpace β} {f : 实数>=0∞ × 实数>=0∞ -> β}
  证明: measurable_of_measurable_nnreal_prod
    (measurable_swap_iff.1 <| measurable_of_measurable_nnreal_prod (h₁.comp measurable_swap) h₃)
    (measurable_of_measurable_nnreal h₂)

Depends on / 依赖: measurable_of_measurable_nnreal, measurable_of_measurable_nnreal_prod, measurable_swap, measurable_swap_iff
-/
theorem measurable_of_measurable_nnreal_nnreal {_ : MeasurableSpace β} {f : Real>=0∞ × Real>=0∞ -> β}
    (h₁ : Measurable fun p : Real>=0 × Real>=0 => f (p.1, p.2)) (h₂ : Measurable fun r : Real>=0 => f (∞, r))
    (h₃ : Measurable fun r : Real>=0 => f (r, ∞)) : Measurable f :=
  measurable_of_measurable_nnreal_prod
    (measurable_swap_iff.1 <| measurable_of_measurable_nnreal_prod (h₁.comp measurable_swap) h₃)
    (measurable_of_measurable_nnreal h₂)

/--
theorem `measurable_ofReal` / 定理 `measurable_ofReal`

English:
theorem measurable_ofReal
  statement: Measurable ENNReal.ofReal
  proof: ENNReal.continuous_ofReal.measurable

中文:
定理 measurable_ofReal
  结论: Measurable ENN实数.of实数
  证明: ENNReal.continuous_ofReal.measurable

Depends on / 依赖: ENNReal, ENNReal.continuous_ofReal.measurable, continuous_ofReal, measurable
-/
theorem measurable_ofReal : Measurable ENNReal.ofReal :=
  ENNReal.continuous_ofReal.measurable

/--
theorem `measurable_toReal` / 定理 `measurable_toReal`

English:
theorem measurable_toReal
  statement: Measurable ENNReal.toReal
  proof: ENNReal.measurable_of_measurable_nnreal measurable_coe_nnreal_real

中文:
定理 measurable_toReal
  结论: Measurable ENN实数.to实数
  证明: ENNReal.measurable_of_measurable_nnreal measurable_coe_nnreal_real

Depends on / 依赖: ENNReal, ENNReal.measurable_of_measurable_nnreal, measurable_coe_nnreal_real, measurable_of_measurable_nnreal
-/
theorem measurable_toReal : Measurable ENNReal.toReal :=
  ENNReal.measurable_of_measurable_nnreal measurable_coe_nnreal_real

/--
theorem `measurable_toNNReal` / 定理 `measurable_toNNReal`

English:
theorem measurable_toNNReal
  statement: Measurable ENNReal.toNNReal
  proof: ENNReal.measurable_of_measurable_nnreal measurable_id

中文:
定理 measurable_toNNReal
  结论: Measurable ENN实数.toNN实数
  证明: ENNReal.measurable_of_measurable_nnreal measurable_id

Depends on / 依赖: ENNReal, ENNReal.measurable_of_measurable_nnreal, measurable_id, measurable_of_measurable_nnreal
-/
theorem measurable_toNNReal : Measurable ENNReal.toNNReal :=
  ENNReal.measurable_of_measurable_nnreal measurable_id

/--
Instance `instMeasurableMul₂` / 实例 `instMeasurableMul₂`

English:
instance instMeasurableMul₂
  signature: : MeasurableMul₂ Real>=0∞
  body: by
  refine ⟨measurable_of_measurable_nnreal_nnreal ?_ ?_ ?_⟩
  · simp only [← ENNReal.coe_mul, measurable_mul.coe_nnreal_ennreal]
  · simp only [ENNReal.top_mul', ENNReal.coe_eq_zero]
    exact measurable_const.piecewise (measurableSet_singleton _) measurable_const
  · simp only [ENNReal.mul_top', 

中文:
实例 instMeasurableMul₂
  签名: : MeasurableMul₂ 实数>=0∞
  定义体: by
  refine ⟨measurable_of_measurable_nnreal_nnreal ?_ ?_ ?_⟩
  · simp only [← ENNReal.coe_mul, measurable_mul.coe_nnreal_ennreal]
  · simp only [ENNReal.top_mul', ENNReal.coe_eq_zero]
    exact measurable_const.piecewise (measurableSet_singleton _) measurable_const
  · simp only [ENNReal.mul_top', 

Depends on / 依赖: ENNReal, ENNReal.coe_eq_zero, ENNReal.coe_mul, ENNReal.mul_top, ENNReal.top_mul, coe_eq_zero, coe_mul, coe_nnreal_ennreal, measurableSet_singleton, measurable_const, measurable_const.piecewise, measurable_mul, measurable_mul.coe_nnreal_ennreal, measurable_of_measurable_nnreal_nnreal, mul_top, piecewise, top_mul
-/
instance instMeasurableMul₂ : MeasurableMul₂ Real>=0∞ := by
  refine ⟨measurable_of_measurable_nnreal_nnreal ?_ ?_ ?_⟩
  · simp only [← ENNReal.coe_mul, measurable_mul.coe_nnreal_ennreal]
  · simp only [ENNReal.top_mul', ENNReal.coe_eq_zero]
    exact measurable_const.piecewise (measurableSet_singleton _) measurable_const
  · simp only [ENNReal.mul_top', ENNReal.coe_eq_zero]
    exact measurable_const.piecewise (measurableSet_singleton _) measurable_const

/--
Instance `instMeasurableSub₂` / 实例 `instMeasurableSub₂`

English:
instance instMeasurableSub₂
  signature: : MeasurableSub₂ Real>=0∞
  body: ⟨measurable_of_measurable_nnreal_nnreal measurable_sub.coe_nnreal_ennreal (by simp) (by simp)⟩

中文:
实例 instMeasurableSub₂
  签名: : MeasurableSub₂ 实数>=0∞
  定义体: ⟨measurable_of_measurable_nnreal_nnreal measurable_sub.coe_nnreal_ennreal (by simp) (by simp)⟩

Depends on / 依赖: coe_nnreal_ennreal, measurable_of_measurable_nnreal_nnreal, measurable_sub, measurable_sub.coe_nnreal_ennreal
-/
instance instMeasurableSub₂ : MeasurableSub₂ Real>=0∞ :=
  ⟨measurable_of_measurable_nnreal_nnreal measurable_sub.coe_nnreal_ennreal (by simp) (by simp)⟩

/--
Instance `instMeasurableInv` / 实例 `instMeasurableInv`

English:
instance instMeasurableInv
  signature: : MeasurableInv Real>=0∞
  body: ⟨continuous_inv.measurable⟩

中文:
实例 instMeasurableInv
  签名: : MeasurableInv 实数>=0∞
  定义体: ⟨continuous_inv.measurable⟩

Depends on / 依赖: continuous_inv, continuous_inv.measurable, measurable
-/
instance instMeasurableInv : MeasurableInv Real>=0∞ :=
  ⟨continuous_inv.measurable⟩

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: MeasurableSMul Real>=0 Real>=0∞
  body: by simp_rw [ENNReal.smul_def]; exact measurable_const_smul _
  measurable_smul_const _ := by
    simp_rw [ENNReal.smul_def]
    exact measurable_coe_nnreal_ennreal.mul_const _

中文:
实例 :
  签名: MeasurableSMul 实数>=0 实数>=0∞
  定义体: by simp_rw [ENNReal.smul_def]; exact measurable_const_smul _
  measurable_smul_const _ := by
    simp_rw [ENNReal.smul_def]
    exact measurable_coe_nnreal_ennreal.mul_const _

Depends on / 依赖: ENNReal, ENNReal.smul_def, measurable_coe_nnreal_ennreal, measurable_coe_nnreal_ennreal.mul_const, measurable_const_smul, measurable_smul_const, mul_const, simp_rw, smul_def
-/
instance : MeasurableSMul Real>=0 Real>=0∞ where
  measurable_const_smul _ := by simp_rw [ENNReal.smul_def]; exact measurable_const_smul _
  measurable_smul_const _ := by
    simp_rw [ENNReal.smul_def]
    exact measurable_coe_nnreal_ennreal.mul_const _

/--
theorem `measurable_of_tendsto'` / 定理 `measurable_of_tendsto'`

English:
theorem measurable_of_tendsto'
  statement: {ι : Type*} {f : ι -> α -> Real>=0∞} {g : α -> Real>=0∞} (u : Filter ι)
  proof: by
  rcases u.exists_seq_tendsto with ⟨x, hx⟩
  rw [tendsto_pi_nhds] at lim
  have : (fun y => liminf (fun n => (f (x n) y : Real>=0∞)) atTop) = g := by
    ext1 y
    exact ((lim y).comp hx).liminf_eq
  rw [← this]
  change Measurable fun y => liminf (fun n => (f (x n) y : Real>=0∞)) atTop
  exact 

中文:
定理 measurable_of_tendsto'
  结论: {ι : 类型} {f : ι -> α -> 实数>=0∞} {g : α -> 实数>=0∞} (u : Filter ι)
  证明: by
  rcases u.exists_seq_tendsto with ⟨x, hx⟩
  rw [tendsto_pi_nhds] at lim
  have : (fun y => liminf (fun n => (f (x n) y : Real>=0∞)) atTop) = g := by
    ext1 y
    exact ((lim y).comp hx).liminf_eq
  rw [← this]
  change Measurable fun y => liminf (fun n => (f (x n) y : Real>=0∞)) atTop
  exact 

Depends on / 依赖: Measurable, exists_seq_tendsto, liminf, liminf_eq, tendsto_pi_nhds, u.exists_seq_tendsto
-/
theorem measurable_of_tendsto' {ι : Type*} {f : ι -> α -> Real>=0∞} {g : α -> Real>=0∞} (u : Filter ι)
    [NeBot u] [IsCountablyGenerated u] (hf : forall i, Measurable (f i)) (lim : Tendsto f u (𝓝 g)) :
    Measurable g := by
  rcases u.exists_seq_tendsto with ⟨x, hx⟩
  rw [tendsto_pi_nhds] at lim
  have : (fun y => liminf (fun n => (f (x n) y : Real>=0∞)) atTop) = g := by
    ext1 y
    exact ((lim y).comp hx).liminf_eq
  rw [← this]
  change Measurable fun y => liminf (fun n => (f (x n) y : Real>=0∞)) atTop
  exact .liminf fun n => hf (x n)

/--
theorem `measurable_of_tendsto` / 定理 `measurable_of_tendsto`

English:
theorem measurable_of_tendsto
  statement: {f : Nat -> α -> Real>=0∞} {g : α -> Real>=0∞} (hf : forall i, Measurable (f i))
  proof: measurable_of_tendsto' atTop hf lim

中文:
定理 measurable_of_tendsto
  结论: {f : 自然数 -> α -> 实数>=0∞} {g : α -> 实数>=0∞} (hf : 对任意 i, Measurable (f i))
  证明: measurable_of_tendsto' atTop hf lim

Depends on / 依赖: measurable_of_tendsto
-/
theorem measurable_of_tendsto {f : Nat -> α -> Real>=0∞} {g : α -> Real>=0∞} (hf : forall i, Measurable (f i))
    (lim : Tendsto f atTop (𝓝 g)) : Measurable g :=
  measurable_of_tendsto' atTop hf lim

/--
lemma `aemeasurable_of_tendsto'` / 引理 `aemeasurable_of_tendsto'`

English:
lemma aemeasurable_of_tendsto'
  statement: {ι : Type*} {f : ι -> α -> Real>=0∞} {g : α -> Real>=0∞}
  proof: by
  rcases u.exists_seq_tendsto with ⟨v, hv⟩
  have h'f : forall n, AEMeasurable (f (v n)) μ := fun n => hf (v n)
  set p : α -> (Nat -> Real>=0∞) -> Prop := fun x f' => Tendsto f' atTop (𝓝 (g x))
  have hp : forallᵐ x ∂μ, p x fun n => f (v n) x := by
    filter_upwards [hlim] with x hx using hx.co

中文:
引理 aemeasurable_of_tendsto'
  结论: {ι : 类型} {f : ι -> α -> 实数>=0∞} {g : α -> 实数>=0∞}
  证明: by
  rcases u.exists_seq_tendsto with ⟨v, hv⟩
  have h'f : forall n, AEMeasurable (f (v n)) μ := fun n => hf (v n)
  set p : α -> (Nat -> Real>=0∞) -> Prop := fun x f' => Tendsto f' atTop (𝓝 (g x))
  have hp : forallᵐ x ∂μ, p x fun n => f (v n) x := by
    filter_upwards [hlim] with x hx using hx.co

Depends on / 依赖: AEMeasurable, Nonempty, Tendsto, aeSeq.measurable, aeSeqLim, aeSeqSet, classical, exists_seq_tendsto, filter_upwards, hx.comp, measurable, measurable_of_tendsto, tendsto_pi_nhds, tendsto_pi_nhds.mpr, u.exists_seq_tendsto
-/
lemma aemeasurable_of_tendsto' {ι : Type*} {f : ι -> α -> Real>=0∞} {g : α -> Real>=0∞}
    {μ : Measure α} (u : Filter ι) [NeBot u] [IsCountablyGenerated u]
    (hf : forall i, AEMeasurable (f i) μ) (hlim : forallᵐ a ∂μ, Tendsto (fun i => f i a) u (𝓝 (g a))) :
    AEMeasurable g μ := by
  rcases u.exists_seq_tendsto with ⟨v, hv⟩
  have h'f : forall n, AEMeasurable (f (v n)) μ := fun n => hf (v n)
  set p : α -> (Nat -> Real>=0∞) -> Prop := fun x f' => Tendsto f' atTop (𝓝 (g x))
  have hp : forallᵐ x ∂μ, p x fun n => f (v n) x := by
    filter_upwards [hlim] with x hx using hx.comp hv
  classical
  set aeSeqLim := fun x => ite (x in aeSeqSet h'f p) (g x) (⟨f (v 0) x⟩ : Nonempty Real>=0∞).some
  refine ⟨aeSeqLim, measurable_of_tendsto' atTop (aeSeq.measurable h'f p)
    (tendsto_pi_nhds.mpr fun x => ?_), ?_⟩
  · unfold aeSeqLim
    simp_rw [aeSeq]
    split_ifs with hx
    · simp_rw [aeSeq.mk_eq_fun_of_mem_aeSeqSet h'f hx]
      exact aeSeq.fun_prop_of_mem_aeSeqSet h'f hx
    · exact tendsto_const_nhds
  · exact (ite_ae_eq_of_measure_compl_zero g (fun x => (⟨f (v 0) x⟩ : Nonempty Real>=0∞).some)
      (aeSeqSet h'f p) (aeSeq.measure_compl_aeSeqSet_eq_zero h'f hp)).symm

/--
lemma `aemeasurable_of_tendsto` / 引理 `aemeasurable_of_tendsto`

English:
lemma aemeasurable_of_tendsto
  statement: {f : Nat -> α -> Real>=0∞} {g : α -> Real>=0∞} {μ : Measure α}
  proof: aemeasurable_of_tendsto' atTop hf hlim

中文:
引理 aemeasurable_of_tendsto
  结论: {f : 自然数 -> α -> 实数>=0∞} {g : α -> 实数>=0∞} {μ : Measure α}
  证明: aemeasurable_of_tendsto' atTop hf hlim

Depends on / 依赖: aemeasurable_of_tendsto
-/
lemma aemeasurable_of_tendsto {f : Nat -> α -> Real>=0∞} {g : α -> Real>=0∞} {μ : Measure α}
    (hf : forall i, AEMeasurable (f i) μ) (hlim : forallᵐ a ∂μ, Tendsto (fun i => f i a) atTop (𝓝 (g a))) :
    AEMeasurable g μ :=
  aemeasurable_of_tendsto' atTop hf hlim

end ENNReal

@[fun_prop]
/--
theorem `Measurable.ennreal_toNNReal` / 定理 `Measurable.ennreal_toNNReal`

English:
theorem Measurable.ennreal_toNNReal
  given: {f : α -> Real>=0∞} (hf : Measurable f)
  proof: ENNReal.measurable_toNNReal.comp hf

@[fun_prop]

中文:
定理 Measurable.ennreal_toNNReal
  条件: {f : α -> 实数>=0∞} (hf : Measurable f)
  证明: ENNReal.measurable_toNNReal.comp hf

@[fun_prop]

Depends on / 依赖: ENNReal, ENNReal.measurable_toNNReal.comp, measurable_toNNReal
-/
theorem Measurable.ennreal_toNNReal {f : α -> Real>=0∞} (hf : Measurable f) :
    Measurable fun x => (f x).toNNReal :=
  ENNReal.measurable_toNNReal.comp hf

@[fun_prop]
/--
theorem `AEMeasurable.ennreal_toNNReal` / 定理 `AEMeasurable.ennreal_toNNReal`

English:
theorem AEMeasurable.ennreal_toNNReal
  given: {f : α -> Real>=0∞} {μ : Measure α} (hf : AEMeasurable f μ)
  proof: ENNReal.measurable_toNNReal.comp_aemeasurable hf

@[simp, norm_cast]

中文:
定理 AEMeasurable.ennreal_toNNReal
  条件: {f : α -> 实数>=0∞} {μ : Measure α} (hf : AEMeasurable f μ)
  证明: ENNReal.measurable_toNNReal.comp_aemeasurable hf

@[simp, norm_cast]

Depends on / 依赖: ENNReal, ENNReal.measurable_toNNReal.comp_aemeasurable, comp_aemeasurable, measurable_toNNReal
-/
theorem AEMeasurable.ennreal_toNNReal {f : α -> Real>=0∞} {μ : Measure α} (hf : AEMeasurable f μ) :
    AEMeasurable (fun x => (f x).toNNReal) μ :=
  ENNReal.measurable_toNNReal.comp_aemeasurable hf

@[simp, norm_cast]
/--
theorem `measurable_coe_nnreal_ennreal_iff` / 定理 `measurable_coe_nnreal_ennreal_iff`

English:
theorem measurable_coe_nnreal_ennreal_iff
  given: {f : α -> Real>=0}
  proof: ⟨fun h => h.ennreal_toNNReal, fun h => h.coe_nnreal_ennreal⟩

@[simp, norm_cast]

中文:
定理 measurable_coe_nnreal_ennreal_iff
  条件: {f : α -> 实数>=0}
  证明: ⟨fun h => h.ennreal_toNNReal, fun h => h.coe_nnreal_ennreal⟩

@[simp, norm_cast]

Depends on / 依赖: coe_nnreal_ennreal, ennreal_toNNReal, h.coe_nnreal_ennreal, h.ennreal_toNNReal
-/
theorem measurable_coe_nnreal_ennreal_iff {f : α -> Real>=0} :
    (Measurable fun x => (f x : Real>=0∞)) ↔ Measurable f :=
  ⟨fun h => h.ennreal_toNNReal, fun h => h.coe_nnreal_ennreal⟩

@[simp, norm_cast]
/--
theorem `aemeasurable_coe_nnreal_ennreal_iff` / 定理 `aemeasurable_coe_nnreal_ennreal_iff`

English:
theorem aemeasurable_coe_nnreal_ennreal_iff
  given: {f : α -> Real>=0} {μ : Measure α}
  proof: ⟨fun h => h.ennreal_toNNReal, fun h => h.coe_nnreal_ennreal⟩

@[fun_prop]

中文:
定理 aemeasurable_coe_nnreal_ennreal_iff
  条件: {f : α -> 实数>=0} {μ : Measure α}
  证明: ⟨fun h => h.ennreal_toNNReal, fun h => h.coe_nnreal_ennreal⟩

@[fun_prop]

Depends on / 依赖: coe_nnreal_ennreal, ennreal_toNNReal, h.coe_nnreal_ennreal, h.ennreal_toNNReal
-/
theorem aemeasurable_coe_nnreal_ennreal_iff {f : α -> Real>=0} {μ : Measure α} :
    AEMeasurable (fun x => (f x : Real>=0∞)) μ ↔ AEMeasurable f μ :=
  ⟨fun h => h.ennreal_toNNReal, fun h => h.coe_nnreal_ennreal⟩

@[fun_prop]
/--
theorem `Measurable.ennreal_toReal` / 定理 `Measurable.ennreal_toReal`

English:
theorem Measurable.ennreal_toReal
  given: {f : α -> Real>=0∞} (hf : Measurable f)
  proof: ENNReal.measurable_toReal.comp hf

@[fun_prop]

中文:
定理 Measurable.ennreal_toReal
  条件: {f : α -> 实数>=0∞} (hf : Measurable f)
  证明: ENNReal.measurable_toReal.comp hf

@[fun_prop]

Depends on / 依赖: ENNReal, ENNReal.measurable_toReal.comp, measurable_toReal
-/
theorem Measurable.ennreal_toReal {f : α -> Real>=0∞} (hf : Measurable f) :
    Measurable fun x => ENNReal.toReal (f x) :=
  ENNReal.measurable_toReal.comp hf

@[fun_prop]
/--
theorem `AEMeasurable.ennreal_toReal` / 定理 `AEMeasurable.ennreal_toReal`

English:
theorem AEMeasurable.ennreal_toReal
  given: {f : α -> Real>=0∞} {μ : Measure α} (hf : AEMeasurable f μ)
  proof: ENNReal.measurable_toReal.comp_aemeasurable hf

@[fun_prop, deprecated
  "Use `Measurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]

中文:
定理 AEMeasurable.ennreal_toReal
  条件: {f : α -> 实数>=0∞} {μ : Measure α} (hf : AEMeasurable f μ)
  证明: ENNReal.measurable_toReal.comp_aemeasurable hf

@[fun_prop, deprecated
  "Use `Measurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]

Depends on / 依赖: ENNReal, ENNReal.measurable_toReal.comp_aemeasurable, comp_aemeasurable, measurable_toReal
-/
theorem AEMeasurable.ennreal_toReal {f : α -> Real>=0∞} {μ : Measure α} (hf : AEMeasurable f μ) :
    AEMeasurable (fun x => ENNReal.toReal (f x)) μ :=
  ENNReal.measurable_toReal.comp_aemeasurable hf

@[fun_prop, deprecated
  "Use `Measurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]
/--
theorem `Measurable.ennreal_tsum` / 定理 `Measurable.ennreal_tsum`

English:
theorem Measurable.ennreal_tsum
  given: {ι} [Countable ι] {f : ι -> α -> Real>=0∞} (h : forall i, Measurable (f i))
  proof: by
  simp_rw [ENNReal.tsum_eq_iSup_sum]
  exact .iSup fun s => s.measurable_fun_sum fun i _ => h i

@[fun_prop, deprecated
  "Use `Measurable.tsum'` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]

中文:
定理 Measurable.ennreal_tsum
  条件: {ι} [Countable ι] {f : ι -> α -> 实数>=0∞} (h : 对任意 i, Measurable (f i))
  证明: by
  simp_rw [ENNReal.tsum_eq_iSup_sum]
  exact .iSup fun s => s.measurable_fun_sum fun i _ => h i

@[fun_prop, deprecated
  "Use `Measurable.tsum'` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]

Depends on / 依赖: ENNReal, ENNReal.tsum_eq_iSup_sum, measurable_fun_sum, s.measurable_fun_sum, simp_rw, tsum_eq_iSup_sum
-/
theorem Measurable.ennreal_tsum {ι} [Countable ι] {f : ι -> α -> Real>=0∞} (h : forall i, Measurable (f i)) :
    Measurable fun x => ∑' i, f i x := by
  simp_rw [ENNReal.tsum_eq_iSup_sum]
  exact .iSup fun s => s.measurable_fun_sum fun i _ => h i

@[fun_prop, deprecated
  "Use `Measurable.tsum'` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]
/--
theorem `Measurable.ennreal_tsum'` / 定理 `Measurable.ennreal_tsum'`

English:
theorem Measurable.ennreal_tsum'
  given: {ι} [Countable ι] {f : ι -> α -> Real>=0∞} (h : forall i, Measurable (f i))
  proof: by
  convert! Measurable.ennreal_tsum h with x
  exact tsum_apply (Pi.summable.2 fun _ => ENNReal.summable)

@[fun_prop, deprecated
  "Use `Measurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]

中文:
定理 Measurable.ennreal_tsum'
  条件: {ι} [Countable ι] {f : ι -> α -> 实数>=0∞} (h : 对任意 i, Measurable (f i))
  证明: by
  convert! Measurable.ennreal_tsum h with x
  exact tsum_apply (Pi.summable.2 fun _ => ENNReal.summable)

@[fun_prop, deprecated
  "Use `Measurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]

Depends on / 依赖: ENNReal, ENNReal.summable, Measurable, Measurable.ennreal_tsum, Pi.summable, convert, ennreal_tsum, summable, tsum_apply
-/
theorem Measurable.ennreal_tsum' {ι} [Countable ι] {f : ι -> α -> Real>=0∞} (h : forall i, Measurable (f i)) :
    Measurable (∑' i, f i) := by
  convert! Measurable.ennreal_tsum h with x
  exact tsum_apply (Pi.summable.2 fun _ => ENNReal.summable)

@[fun_prop, deprecated
  "Use `Measurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]
/--
theorem `Measurable.nnreal_tsum` / 定理 `Measurable.nnreal_tsum`

English:
theorem Measurable.nnreal_tsum
  given: {ι} [Countable ι] {f : ι -> α -> Real>=0} (h : forall i, Measurable (f i))
  proof: by
  simp_rw [NNReal.tsum_eq_toNNReal_tsum]
  exact (Measurable.ennreal_tsum fun i => (h i).coe_nnreal_ennreal).ennreal_toNNReal

@[fun_prop, deprecated
  "Use `AEMeasurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]

中文:
定理 Measurable.nnreal_tsum
  条件: {ι} [Countable ι] {f : ι -> α -> 实数>=0} (h : 对任意 i, Measurable (f i))
  证明: by
  simp_rw [NNReal.tsum_eq_toNNReal_tsum]
  exact (Measurable.ennreal_tsum fun i => (h i).coe_nnreal_ennreal).ennreal_toNNReal

@[fun_prop, deprecated
  "Use `AEMeasurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]

Depends on / 依赖: Measurable, Measurable.ennreal_tsum, NNReal, NNReal.tsum_eq_toNNReal_tsum, coe_nnreal_ennreal, ennreal_toNNReal, ennreal_tsum, simp_rw, tsum_eq_toNNReal_tsum
-/
theorem Measurable.nnreal_tsum {ι} [Countable ι] {f : ι -> α -> Real>=0} (h : forall i, Measurable (f i)) :
    Measurable fun x => ∑' i, f i x := by
  simp_rw [NNReal.tsum_eq_toNNReal_tsum]
  exact (Measurable.ennreal_tsum fun i => (h i).coe_nnreal_ennreal).ennreal_toNNReal

@[fun_prop, deprecated
  "Use `AEMeasurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]
/--
theorem `AEMeasurable.ennreal_tsum` / 定理 `AEMeasurable.ennreal_tsum`

English:
theorem AEMeasurable.ennreal_tsum
  statement: {ι} [Countable ι] {f : ι -> α -> Real>=0∞} {μ : Measure α}
  proof: by
  simp_rw [ENNReal.tsum_eq_iSup_sum]
  exact .iSup fun s => Finset.aemeasurable_fun_sum s fun i _ => h i

@[fun_prop, deprecated
  "Use `AEMeasurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]

中文:
定理 AEMeasurable.ennreal_tsum
  结论: {ι} [Countable ι] {f : ι -> α -> 实数>=0∞} {μ : Measure α}
  证明: by
  simp_rw [ENNReal.tsum_eq_iSup_sum]
  exact .iSup fun s => Finset.aemeasurable_fun_sum s fun i _ => h i

@[fun_prop, deprecated
  "Use `AEMeasurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]

Depends on / 依赖: ENNReal, ENNReal.tsum_eq_iSup_sum, Finset, Finset.aemeasurable_fun_sum, aemeasurable_fun_sum, simp_rw, tsum_eq_iSup_sum
-/
theorem AEMeasurable.ennreal_tsum {ι} [Countable ι] {f : ι -> α -> Real>=0∞} {μ : Measure α}
    (h : forall i, AEMeasurable (f i) μ) : AEMeasurable (fun x => ∑' i, f i x) μ := by
  simp_rw [ENNReal.tsum_eq_iSup_sum]
  exact .iSup fun s => Finset.aemeasurable_fun_sum s fun i _ => h i

@[fun_prop, deprecated
  "Use `AEMeasurable.tsum` from `Mathlib.MeasureTheory.Constructions.Polish.Basic` instead"
  (since := "2026-04-30")]
/--
theorem `AEMeasurable.nnreal_tsum` / 定理 `AEMeasurable.nnreal_tsum`

English:
theorem AEMeasurable.nnreal_tsum
  statement: {α : Type*} {_ : MeasurableSpace α} {ι : Type*} [Countable ι]
  proof: by
  simp_rw [NNReal.tsum_eq_toNNReal_tsum]
  exact (AEMeasurable.ennreal_tsum fun i => (h i).coe_nnreal_ennreal).ennreal_toNNReal

@[fun_prop]

中文:
定理 AEMeasurable.nnreal_tsum
  结论: {α : 类型} {_ : MeasurableSpace α} {ι : 类型} [Countable ι]
  证明: by
  simp_rw [NNReal.tsum_eq_toNNReal_tsum]
  exact (AEMeasurable.ennreal_tsum fun i => (h i).coe_nnreal_ennreal).ennreal_toNNReal

@[fun_prop]

Depends on / 依赖: AEMeasurable, AEMeasurable.ennreal_tsum, NNReal, NNReal.tsum_eq_toNNReal_tsum, coe_nnreal_ennreal, ennreal_toNNReal, ennreal_tsum, simp_rw, tsum_eq_toNNReal_tsum
-/
theorem AEMeasurable.nnreal_tsum {α : Type*} {_ : MeasurableSpace α} {ι : Type*} [Countable ι]
    {f : ι -> α -> NNReal} {μ : Measure α} (h : forall i : ι, AEMeasurable (f i) μ) :
    AEMeasurable (fun x : α => ∑' i : ι, f i x) μ := by
  simp_rw [NNReal.tsum_eq_toNNReal_tsum]
  exact (AEMeasurable.ennreal_tsum fun i => (h i).coe_nnreal_ennreal).ennreal_toNNReal

@[fun_prop]
/--
theorem `measurable_coe_real_ereal` / 定理 `measurable_coe_real_ereal`

English:
theorem measurable_coe_real_ereal
  statement: Measurable ((↑) : Real -> EReal)
  proof: continuous_coe_real_ereal.measurable

中文:
定理 measurable_coe_real_ereal
  结论: Measurable ((↑) : 实数 -> E实数)
  证明: continuous_coe_real_ereal.measurable

Depends on / 依赖: continuous_coe_real_ereal, continuous_coe_real_ereal.measurable, measurable
-/
theorem measurable_coe_real_ereal : Measurable ((↑) : Real -> EReal) :=
  continuous_coe_real_ereal.measurable

/--
theorem `Measurable.coe_real_ereal` / 定理 `Measurable.coe_real_ereal`

English:
theorem Measurable.coe_real_ereal
  given: {f : α -> Real} (hf : Measurable f)
  proof: measurable_coe_real_ereal.comp hf

@[fun_prop]

中文:
定理 Measurable.coe_real_ereal
  条件: {f : α -> 实数} (hf : Measurable f)
  证明: measurable_coe_real_ereal.comp hf

@[fun_prop]

Depends on / 依赖: measurable_coe_real_ereal, measurable_coe_real_ereal.comp
-/
theorem Measurable.coe_real_ereal {f : α -> Real} (hf : Measurable f) :
    Measurable fun x => (f x : EReal) :=
  measurable_coe_real_ereal.comp hf

@[fun_prop]
/--
theorem `AEMeasurable.coe_real_ereal` / 定理 `AEMeasurable.coe_real_ereal`

English:
theorem AEMeasurable.coe_real_ereal
  given: {f : α -> Real} {μ : Measure α} (hf : AEMeasurable f μ)
  proof: measurable_coe_real_ereal.comp_aemeasurable hf

中文:
定理 AEMeasurable.coe_real_ereal
  条件: {f : α -> 实数} {μ : Measure α} (hf : AEMeasurable f μ)
  证明: measurable_coe_real_ereal.comp_aemeasurable hf

Depends on / 依赖: comp_aemeasurable, measurable_coe_real_ereal, measurable_coe_real_ereal.comp_aemeasurable
-/
theorem AEMeasurable.coe_real_ereal {f : α -> Real} {μ : Measure α} (hf : AEMeasurable f μ) :
    AEMeasurable (fun x => (f x : EReal)) μ :=
  measurable_coe_real_ereal.comp_aemeasurable hf

/--
Definition of `MeasurableEquiv.erealEquivReal` / `MeasurableEquiv.erealEquivReal` 的定义

English:
definition MeasurableEquiv.erealEquivReal
  signature: : ({⊥, ⊤}ᶜ : Set EReal) ≃ᵐ Real
  body: EReal.neBotTopHomeomorphReal.toMeasurableEquiv

中文:
定义 MeasurableEquiv.erealEquivReal
  签名: : ({⊥, ⊤}ᶜ : Set E实数) ≃ᵐ 实数
  定义体: EReal.neBotTopHomeomorphReal.toMeasurableEquiv

Depends on / 依赖: EReal.neBotTopHomeomorphReal.toMeasurableEquiv, neBotTopHomeomorphReal, toMeasurableEquiv
-/
noncomputable def MeasurableEquiv.erealEquivReal : ({⊥, ⊤}ᶜ : Set EReal) ≃ᵐ Real :=
  EReal.neBotTopHomeomorphReal.toMeasurableEquiv

/--
theorem `EReal.measurable_of_measurable_real` / 定理 `EReal.measurable_of_measurable_real`

English:
theorem EReal.measurable_of_measurable_real
  given: {f : EReal -> α} (h : Measurable fun p : Real => f p)
  proof: measurable_of_measurable_on_compl_finite {⊥, ⊤} (by simp)
    (MeasurableEquiv.erealEquivReal.symm.measurable_comp_iff.1 h)

中文:
定理 EReal.measurable_of_measurable_real
  条件: {f : E实数 -> α} (h : Measurable fun p : 实数 => f p)
  证明: measurable_of_measurable_on_compl_finite {⊥, ⊤} (by simp)
    (MeasurableEquiv.erealEquivReal.symm.measurable_comp_iff.1 h)

Depends on / 依赖: MeasurableEquiv, MeasurableEquiv.erealEquivReal.symm.measurable_comp_iff, erealEquivReal, measurable_comp_iff, measurable_of_measurable_on_compl_finite
-/
theorem EReal.measurable_of_measurable_real {f : EReal -> α} (h : Measurable fun p : Real => f p) :
    Measurable f :=
  measurable_of_measurable_on_compl_finite {⊥, ⊤} (by simp)
    (MeasurableEquiv.erealEquivReal.symm.measurable_comp_iff.1 h)

/--
theorem `measurable_ereal_toReal` / 定理 `measurable_ereal_toReal`

English:
theorem measurable_ereal_toReal
  statement: Measurable EReal.toReal
  proof: EReal.measurable_of_measurable_real (by simpa using! measurable_id)

@[fun_prop]

中文:
定理 measurable_ereal_toReal
  结论: Measurable E实数.to实数
  证明: EReal.measurable_of_measurable_real (by simpa using! measurable_id)

@[fun_prop]

Depends on / 依赖: EReal.measurable_of_measurable_real, measurable_id, measurable_of_measurable_real
-/
theorem measurable_ereal_toReal : Measurable EReal.toReal :=
  EReal.measurable_of_measurable_real (by simpa using! measurable_id)

@[fun_prop]
/--
theorem `Measurable.ereal_toReal` / 定理 `Measurable.ereal_toReal`

English:
theorem Measurable.ereal_toReal
  given: {f : α -> EReal} (hf : Measurable f)
  proof: measurable_ereal_toReal.comp hf

@[fun_prop]

中文:
定理 Measurable.ereal_toReal
  条件: {f : α -> E实数} (hf : Measurable f)
  证明: measurable_ereal_toReal.comp hf

@[fun_prop]

Depends on / 依赖: measurable_ereal_toReal, measurable_ereal_toReal.comp
-/
theorem Measurable.ereal_toReal {f : α -> EReal} (hf : Measurable f) :
    Measurable fun x => (f x).toReal :=
  measurable_ereal_toReal.comp hf

@[fun_prop]
/--
theorem `AEMeasurable.ereal_toReal` / 定理 `AEMeasurable.ereal_toReal`

English:
theorem AEMeasurable.ereal_toReal
  given: {f : α -> EReal} {μ : Measure α} (hf : AEMeasurable f μ)
  proof: measurable_ereal_toReal.comp_aemeasurable hf

中文:
定理 AEMeasurable.ereal_toReal
  条件: {f : α -> E实数} {μ : Measure α} (hf : AEMeasurable f μ)
  证明: measurable_ereal_toReal.comp_aemeasurable hf

Depends on / 依赖: comp_aemeasurable, measurable_ereal_toReal, measurable_ereal_toReal.comp_aemeasurable
-/
theorem AEMeasurable.ereal_toReal {f : α -> EReal} {μ : Measure α} (hf : AEMeasurable f μ) :
    AEMeasurable (fun x => (f x).toReal) μ :=
  measurable_ereal_toReal.comp_aemeasurable hf

/--
theorem `measurable_coe_ennreal_ereal` / 定理 `measurable_coe_ennreal_ereal`

English:
theorem measurable_coe_ennreal_ereal
  statement: Measurable ((↑) : Real>=0∞ -> EReal)
  proof: continuous_coe_ennreal_ereal.measurable

@[fun_prop]

中文:
定理 measurable_coe_ennreal_ereal
  结论: Measurable ((↑) : 实数>=0∞ -> E实数)
  证明: continuous_coe_ennreal_ereal.measurable

@[fun_prop]

Depends on / 依赖: continuous_coe_ennreal_ereal, continuous_coe_ennreal_ereal.measurable, measurable
-/
theorem measurable_coe_ennreal_ereal : Measurable ((↑) : Real>=0∞ -> EReal) :=
  continuous_coe_ennreal_ereal.measurable

@[fun_prop]
/--
theorem `Measurable.coe_ereal_ennreal` / 定理 `Measurable.coe_ereal_ennreal`

English:
theorem Measurable.coe_ereal_ennreal
  given: {f : α -> Real>=0∞} (hf : Measurable f)
  proof: measurable_coe_ennreal_ereal.comp hf

@[fun_prop]

中文:
定理 Measurable.coe_ereal_ennreal
  条件: {f : α -> 实数>=0∞} (hf : Measurable f)
  证明: measurable_coe_ennreal_ereal.comp hf

@[fun_prop]

Depends on / 依赖: measurable_coe_ennreal_ereal, measurable_coe_ennreal_ereal.comp
-/
theorem Measurable.coe_ereal_ennreal {f : α -> Real>=0∞} (hf : Measurable f) :
    Measurable fun x => (f x : EReal) :=
  measurable_coe_ennreal_ereal.comp hf

@[fun_prop]
/--
theorem `AEMeasurable.coe_ereal_ennreal` / 定理 `AEMeasurable.coe_ereal_ennreal`

English:
theorem AEMeasurable.coe_ereal_ennreal
  given: {f : α -> Real>=0∞} {μ : Measure α} (hf : AEMeasurable f μ)
  proof: measurable_coe_ennreal_ereal.comp_aemeasurable hf

中文:
定理 AEMeasurable.coe_ereal_ennreal
  条件: {f : α -> 实数>=0∞} {μ : Measure α} (hf : AEMeasurable f μ)
  证明: measurable_coe_ennreal_ereal.comp_aemeasurable hf

Depends on / 依赖: comp_aemeasurable, measurable_coe_ennreal_ereal, measurable_coe_ennreal_ereal.comp_aemeasurable
-/
theorem AEMeasurable.coe_ereal_ennreal {f : α -> Real>=0∞} {μ : Measure α} (hf : AEMeasurable f μ) :
    AEMeasurable (fun x => (f x : EReal)) μ :=
  measurable_coe_ennreal_ereal.comp_aemeasurable hf

/--
theorem `measurable_ereal_toENNReal` / 定理 `measurable_ereal_toENNReal`

English:
theorem measurable_ereal_toENNReal
  statement: Measurable EReal.toENNReal
  proof: EReal.measurable_of_measurable_real (by simpa using ENNReal.measurable_ofReal)

@[fun_prop]

中文:
定理 measurable_ereal_toENNReal
  结论: Measurable E实数.toENN实数
  证明: EReal.measurable_of_measurable_real (by simpa using ENNReal.measurable_ofReal)

@[fun_prop]

Depends on / 依赖: ENNReal, ENNReal.measurable_ofReal, EReal.measurable_of_measurable_real, measurable_ofReal, measurable_of_measurable_real
-/
theorem measurable_ereal_toENNReal : Measurable EReal.toENNReal :=
  EReal.measurable_of_measurable_real (by simpa using ENNReal.measurable_ofReal)

@[fun_prop]
/--
theorem `Measurable.ereal_toENNReal` / 定理 `Measurable.ereal_toENNReal`

English:
theorem Measurable.ereal_toENNReal
  given: {f : α -> EReal} (hf : Measurable f)
  proof: measurable_ereal_toENNReal.comp hf

@[fun_prop]

中文:
定理 Measurable.ereal_toENNReal
  条件: {f : α -> E实数} (hf : Measurable f)
  证明: measurable_ereal_toENNReal.comp hf

@[fun_prop]

Depends on / 依赖: measurable_ereal_toENNReal, measurable_ereal_toENNReal.comp
-/
theorem Measurable.ereal_toENNReal {f : α -> EReal} (hf : Measurable f) :
    Measurable fun x => (f x).toENNReal :=
  measurable_ereal_toENNReal.comp hf

@[fun_prop]
/--
theorem `AEMeasurable.ereal_toENNReal` / 定理 `AEMeasurable.ereal_toENNReal`

English:
theorem AEMeasurable.ereal_toENNReal
  given: {f : α -> EReal} {μ : Measure α} (hf : AEMeasurable f μ)
  proof: measurable_ereal_toENNReal.comp_aemeasurable hf

中文:
定理 AEMeasurable.ereal_toENNReal
  条件: {f : α -> E实数} {μ : Measure α} (hf : AEMeasurable f μ)
  证明: measurable_ereal_toENNReal.comp_aemeasurable hf

Depends on / 依赖: comp_aemeasurable, measurable_ereal_toENNReal, measurable_ereal_toENNReal.comp_aemeasurable
-/
theorem AEMeasurable.ereal_toENNReal {f : α -> EReal} {μ : Measure α} (hf : AEMeasurable f μ) :
    AEMeasurable (fun x => (f x).toENNReal) μ :=
  measurable_ereal_toENNReal.comp_aemeasurable hf

namespace NNReal

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: MeasurableSMul₂ Real>=0 Real>=0∞
  body: show Measurable fun r : Real>=0 × Real>=0∞ => (r.1 : Real>=0) * r.2 by fun_prop

中文:
实例 :
  签名: MeasurableSMul₂ 实数>=0 实数>=0∞
  定义体: show Measurable fun r : Real>=0 × Real>=0∞ => (r.1 : Real>=0) * r.2 by fun_prop

Depends on / 依赖: Measurable, fun_prop
-/
instance : MeasurableSMul₂ Real>=0 Real>=0∞ where
  measurable_smul := show Measurable fun r : Real>=0 × Real>=0∞ => (r.1 : Real>=0) * r.2 by fun_prop

/--
theorem `measurable_of_tendsto'` / 定理 `measurable_of_tendsto'`

English:
theorem measurable_of_tendsto'
  statement: {ι} {f : ι -> α -> Real>=0} {g : α -> Real>=0} (u : Filter ι) [NeBot u]
  proof: by
  simp_rw [← measurable_coe_nnreal_ennreal_iff] at hf ⊢
  refine ENNReal.measurable_of_tendsto' u hf ?_
  rw [tendsto_pi_nhds] at lim ⊢
  exact fun x => (ENNReal.continuous_coe.tendsto (g x)).comp (lim x)

中文:
定理 measurable_of_tendsto'
  结论: {ι} {f : ι -> α -> 实数>=0} {g : α -> 实数>=0} (u : Filter ι) [NeBot u]
  证明: by
  simp_rw [← measurable_coe_nnreal_ennreal_iff] at hf ⊢
  refine ENNReal.measurable_of_tendsto' u hf ?_
  rw [tendsto_pi_nhds] at lim ⊢
  exact fun x => (ENNReal.continuous_coe.tendsto (g x)).comp (lim x)

Depends on / 依赖: ENNReal, ENNReal.continuous_coe.tendsto, ENNReal.measurable_of_tendsto, continuous_coe, measurable_coe_nnreal_ennreal_iff, measurable_of_tendsto, simp_rw, tendsto, tendsto_pi_nhds
-/
theorem measurable_of_tendsto' {ι} {f : ι -> α -> Real>=0} {g : α -> Real>=0} (u : Filter ι) [NeBot u]
    [IsCountablyGenerated u] (hf : forall i, Measurable (f i)) (lim : Tendsto f u (𝓝 g)) :
    Measurable g := by
  simp_rw [← measurable_coe_nnreal_ennreal_iff] at hf ⊢
  refine ENNReal.measurable_of_tendsto' u hf ?_
  rw [tendsto_pi_nhds] at lim ⊢
  exact fun x => (ENNReal.continuous_coe.tendsto (g x)).comp (lim x)

/--
theorem `measurable_of_tendsto` / 定理 `measurable_of_tendsto`

English:
theorem measurable_of_tendsto
  statement: {f : Nat -> α -> Real>=0} {g : α -> Real>=0} (hf : forall i, Measurable (f i))
  proof: measurable_of_tendsto' atTop hf lim

中文:
定理 measurable_of_tendsto
  结论: {f : 自然数 -> α -> 实数>=0} {g : α -> 实数>=0} (hf : 对任意 i, Measurable (f i))
  证明: measurable_of_tendsto' atTop hf lim

Depends on / 依赖: measurable_of_tendsto
-/
theorem measurable_of_tendsto {f : Nat -> α -> Real>=0} {g : α -> Real>=0} (hf : forall i, Measurable (f i))
    (lim : Tendsto f atTop (𝓝 g)) : Measurable g :=
  measurable_of_tendsto' atTop hf lim

end NNReal

namespace EReal

/--
lemma `measurableEmbedding_coe` / 引理 `measurableEmbedding_coe`

English:
lemma measurableEmbedding_coe
  statement: MeasurableEmbedding Real.toEReal
  proof: isOpenEmbedding_coe.measurableEmbedding

中文:
引理 measurableEmbedding_coe
  结论: MeasurableEmbedding 实数.toE实数
  证明: isOpenEmbedding_coe.measurableEmbedding

Depends on / 依赖: isOpenEmbedding_coe, isOpenEmbedding_coe.measurableEmbedding, measurableEmbedding
-/
lemma measurableEmbedding_coe : MeasurableEmbedding Real.toEReal :=
  isOpenEmbedding_coe.measurableEmbedding

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: MeasurableAdd₂ EReal
  body: ⟨EReal.lowerSemicontinuous_add.measurable⟩

中文:
实例 :
  签名: MeasurableAdd₂ E实数
  定义体: ⟨EReal.lowerSemicontinuous_add.measurable⟩

Depends on / 依赖: EReal.lowerSemicontinuous_add.measurable, lowerSemicontinuous_add, measurable
-/
instance : MeasurableAdd₂ EReal := ⟨EReal.lowerSemicontinuous_add.measurable⟩

section MeasurableMul

variable {α β γ : Type*} {mα : MeasurableSpace α} {mβ : MeasurableSpace β} {mγ : MeasurableSpace γ}

/--
lemma `measurable_of_real_prod` / 引理 `measurable_of_real_prod`

English:
lemma measurable_of_real_prod
  statement: {f : EReal × β -> γ}
  proof: .of_union₃_range_cover (measurableEmbedding_prodMk_left _) (measurableEmbedding_prodMk_left _)
    (measurableEmbedding_coe.prodMap .id) (by simp [-univ_subset_iff, subset_def, EReal.forall])
    h_bot h_top h_real

中文:
引理 measurable_of_real_prod
  结论: {f : E实数 × β -> γ}
  证明: .of_union₃_range_cover (measurableEmbedding_prodMk_left _) (measurableEmbedding_prodMk_left _)
    (measurableEmbedding_coe.prodMap .id) (by simp [-univ_subset_iff, subset_def, EReal.forall])
    h_bot h_top h_real

Depends on / 依赖: EReal.forall, h_bot, h_real, h_top, measurableEmbedding_coe, measurableEmbedding_coe.prodMap, measurableEmbedding_prodMk_left, prodMap, subset_def, univ_subset_iff
-/
lemma measurable_of_real_prod {f : EReal × β -> γ}
    (h_real : Measurable fun p : Real × β => f (p.1, p.2))
    (h_bot : Measurable fun x => f (⊥, x)) (h_top : Measurable fun x => f (⊤, x)) : Measurable f :=
  .of_union₃_range_cover (measurableEmbedding_prodMk_left _) (measurableEmbedding_prodMk_left _)
    (measurableEmbedding_coe.prodMap .id) (by simp [-univ_subset_iff, subset_def, EReal.forall])
    h_bot h_top h_real

/--
lemma `measurable_of_real_real` / 引理 `measurable_of_real_real`

English:
lemma measurable_of_real_real
  statement: {f : EReal × EReal -> β}
  proof: by
  refine measurable_of_real_prod ?_ ?_ ?_
· refine measurable_swap_iff.mp measurable_of_real_prod ?_ h_bot_right h_top_right
    exact h_real.comp measurable_swap
  · exact measurable_of_measurable_real h_bot_left
  · exact measurable_of_measurable_real h_top_left

中文:
引理 measurable_of_real_real
  结论: {f : E实数 × E实数 -> β}
  证明: by
  refine measurable_of_real_prod ?_ ?_ ?_
· refine measurable_swap_iff.mp measurable_of_real_prod ?_ h_bot_right h_top_right
    exact h_real.comp measurable_swap
  · exact measurable_of_measurable_real h_bot_left
  · exact measurable_of_measurable_real h_top_left

Depends on / 依赖: h_bot_left, h_bot_right, h_real, h_real.comp, h_top_left, h_top_right, measurable_of_measurable_real, measurable_of_real_prod, measurable_swap, measurable_swap_iff, measurable_swap_iff.mp
-/
lemma measurable_of_real_real {f : EReal × EReal -> β}
    (h_real : Measurable fun p : Real × Real => f (p.1, p.2))
    (h_bot_left : Measurable fun r : Real => f (⊥, r))
    (h_top_left : Measurable fun r : Real => f (⊤, r))
    (h_bot_right : Measurable fun r : Real => f (r, ⊥))
    (h_top_right : Measurable fun r : Real => f (r, ⊤)) :
    Measurable f := by
  refine measurable_of_real_prod ?_ ?_ ?_
· refine measurable_swap_iff.mp measurable_of_real_prod ?_ h_bot_right h_top_right
    exact h_real.comp measurable_swap
  · exact measurable_of_measurable_real h_bot_left
  · exact measurable_of_measurable_real h_top_left

/--
lemma `measurable_const_mul` / 引理 `measurable_const_mul`

English:
lemma measurable_const_mul
  given: (c : EReal)
  statement: Measurable fun (x : EReal) => c * x
  proof: by
  rcases eq_or_ne c 0 with rfl | hc
  · simp
  · refine measurable_of_continuousOn_compl_singleton 0 fun x (hx : x != 0) => ?_
    exact (continuousAt_mul (Or.inl hc) (Or.inl hc) (Or.inr hx) (Or.inr hx)).comp_of_eq
.continuousWithinAt (continuousAt_const.prodMk continuousAt_id) rfl

中文:
引理 measurable_const_mul
  条件: (c : E实数)
  结论: Measurable fun (x : E实数) => c * x
  证明: by
  rcases eq_or_ne c 0 with rfl | hc
  · simp
  · refine measurable_of_continuousOn_compl_singleton 0 fun x (hx : x != 0) => ?_
    exact (continuousAt_mul (Or.inl hc) (Or.inl hc) (Or.inr hx) (Or.inr hx)).comp_of_eq
.continuousWithinAt (continuousAt_const.prodMk continuousAt_id) rfl
-/
private lemma measurable_const_mul (c : EReal) : Measurable fun (x : EReal) => c * x := by
  rcases eq_or_ne c 0 with rfl | hc
  · simp
  · refine measurable_of_continuousOn_compl_singleton 0 fun x (hx : x != 0) => ?_
    exact (continuousAt_mul (Or.inl hc) (Or.inl hc) (Or.inr hx) (Or.inr hx)).comp_of_eq
.continuousWithinAt (continuousAt_const.prodMk continuousAt_id) rfl

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: MeasurableMul₂ EReal
  body: by
  refine ⟨measurable_of_real_real ?_ ?_ ?_ ?_ ?_⟩
  · exact (measurable_fst.mul measurable_snd).coe_real_ereal
  · exact (measurable_const_mul _).comp measurable_coe_real_ereal
  · exact (measurable_const_mul _).comp measurable_coe_real_ereal
  · simp_rw [mul_comm _ ⊥]
    exact (measurable_const

中文:
实例 :
  签名: MeasurableMul₂ E实数
  定义体: by
  refine ⟨measurable_of_real_real ?_ ?_ ?_ ?_ ?_⟩
  · exact (measurable_fst.mul measurable_snd).coe_real_ereal
  · exact (measurable_const_mul _).comp measurable_coe_real_ereal
  · exact (measurable_const_mul _).comp measurable_coe_real_ereal
  · simp_rw [mul_comm _ ⊥]
    exact (measurable_const

Depends on / 依赖: coe_real_ereal, measurable_coe_real_ereal, measurable_const_mul, measurable_fst, measurable_fst.mul, measurable_of_real_real, measurable_snd, mul_comm, simp_rw
-/
instance : MeasurableMul₂ EReal := by
  refine ⟨measurable_of_real_real ?_ ?_ ?_ ?_ ?_⟩
  · exact (measurable_fst.mul measurable_snd).coe_real_ereal
  · exact (measurable_const_mul _).comp measurable_coe_real_ereal
  · exact (measurable_const_mul _).comp measurable_coe_real_ereal
  · simp_rw [mul_comm _ ⊥]
    exact (measurable_const_mul _).comp measurable_coe_real_ereal
  · simp_rw [mul_comm _ ⊤]
    exact (measurable_const_mul _).comp measurable_coe_real_ereal

end MeasurableMul

end EReal

/--
theorem `exists_spanning_measurableSet_le` / 定理 `exists_spanning_measurableSet_le`

English:
theorem exists_spanning_measurableSet_le
  statement: {f : α -> Real>=0} (hf : Measurable f) (μ : Measure α)
  proof: by
  let sigma_finite_sets := spanningSets μ
  let norm_sets := fun n : Nat => { x | f x <= n }
  have norm_sets_spanning : ⋃ n, norm_sets n = Set.univ := by
    ext1 x
    simp only [Set.mem_iUnion, Set.mem_univ, iff_true]
    exact exists_nat_ge (f x)
  let sets n := sigma_finite_sets n inter norm

中文:
定理 exists_spanning_measurableSet_le
  结论: {f : α -> 实数>=0} (hf : Measurable f) (μ : Measure α)
  证明: by
  let sigma_finite_sets := spanningSets μ
  let norm_sets := fun n : Nat => { x | f x <= n }
  have norm_sets_spanning : ⋃ n, norm_sets n = Set.univ := by
    ext1 x
    simp only [Set.mem_iUnion, Set.mem_univ, iff_true]
    exact exists_nat_ge (f x)
  let sets n := sigma_finite_sets n inter norm

Depends on / 依赖: MeasurableSet, MeasurableSet.inter, Set.mem_iUnion, Set.mem_univ, Set.univ, exists_nat_ge, h_finite, h_meas, iff_true, measurableSet_Iic, measurableSet_spanningSets, mem_iUnion, mem_univ, norm_sets, norm_sets_spanning, sigma_finite_sets, spanningSets
-/
theorem exists_spanning_measurableSet_le {f : α -> Real>=0} (hf : Measurable f) (μ : Measure α)
    [SigmaFinite μ] :
    exists s : Nat -> Set α,
      (forall n, MeasurableSet (s n) ∧ μ (s n) < ∞ ∧ forall x in s n, f x <= n) ∧
      ⋃ i, s i = Set.univ := by
  let sigma_finite_sets := spanningSets μ
  let norm_sets := fun n : Nat => { x | f x <= n }
  have norm_sets_spanning : ⋃ n, norm_sets n = Set.univ := by
    ext1 x
    simp only [Set.mem_iUnion, Set.mem_univ, iff_true]
    exact exists_nat_ge (f x)
  let sets n := sigma_finite_sets n inter norm_sets n
  have h_meas : forall n, MeasurableSet (sets n) := by
    refine fun n => MeasurableSet.inter ?_ ?_
    · exact measurableSet_spanningSets μ n
    · exact hf measurableSet_Iic
  have h_finite : forall n, μ (sets n) < ∞ := by
    refine fun n => (measure_mono Set.inter_subset_left).trans_lt ?_
    exact measure_spanningSets_lt_top μ n
  refine ⟨sets, fun n => ⟨h_meas n, h_finite n, ?_⟩, ?_⟩
  · exact fun x hx => hx.2
  · have :
      ⋃ i, sigma_finite_sets i inter norm_sets i = (⋃ i, sigma_finite_sets i) inter ⋃ i, norm_sets i := by
      refine Set.iUnion_inter_of_monotone (monotone_spanningSets μ) fun i j hij x => ?_
      simp only [norm_sets, Set.mem_ofPred_eq]
      refine fun hif => hif.trans ?_
      exact mod_cast hij
    rw [this]; rw [norm_sets_spanning]; rw [iUnion_spanningSets μ]; rw [Set.inter_univ]

variable (μ : Measure Real) [IsFiniteMeasureOnCompacts μ]

/--
lemma `tendsto_measure_Icc_nhdsWithin_right'` / 引理 `tendsto_measure_Icc_nhdsWithin_right'`

English:
lemma tendsto_measure_Icc_nhdsWithin_right'
  given: (b : Real)
  proof: by
  rw [Real.singleton_eq_inter_Icc]
  apply tendsto_measure_biInter_gt (fun r hr => nullMeasurableSet_Icc)
  · intro r s _rpos hrs
    exact Icc_subset_Icc (by linarith) (by linarith)
  · exact ⟨1, zero_lt_one, isCompact_Icc.measure_ne_top⟩

中文:
引理 tendsto_measure_Icc_nhdsWithin_right'
  条件: (b : 实数)
  证明: by
  rw [Real.singleton_eq_inter_Icc]
  apply tendsto_measure_biInter_gt (fun r hr => nullMeasurableSet_Icc)
  · intro r s _rpos hrs
    exact Icc_subset_Icc (by linarith) (by linarith)
  · exact ⟨1, zero_lt_one, isCompact_Icc.measure_ne_top⟩

Depends on / 依赖: Icc_subset_Icc, Real.singleton_eq_inter_Icc, _rpos, isCompact_Icc, isCompact_Icc.measure_ne_top, measure_ne_top, nullMeasurableSet_Icc, singleton_eq_inter_Icc, tendsto_measure_biInter_gt, zero_lt_one
-/
lemma tendsto_measure_Icc_nhdsWithin_right' (b : Real) :
    Tendsto (fun δ => μ (Icc (b - δ) (b + δ))) (𝓝[>] (0 : Real)) (𝓝 (μ {b})) := by
  rw [Real.singleton_eq_inter_Icc]
  apply tendsto_measure_biInter_gt (fun r hr => nullMeasurableSet_Icc)
  · intro r s _rpos hrs
    exact Icc_subset_Icc (by linarith) (by linarith)
  · exact ⟨1, zero_lt_one, isCompact_Icc.measure_ne_top⟩

/--
lemma `tendsto_measure_Icc_nhdsWithin_right` / 引理 `tendsto_measure_Icc_nhdsWithin_right`

English:
lemma tendsto_measure_Icc_nhdsWithin_right
  given: (b : Real)
  proof: by
  simp only [← nhdsGT_sup_nhdsWithin_singleton, nhdsWithin_singleton, tendsto_sup,
    tendsto_measure_Icc_nhdsWithin_right' μ b, true_and, tendsto_pure_left]
  intro s hs
  simpa using mem_of_mem_nhds hs

中文:
引理 tendsto_measure_Icc_nhdsWithin_right
  条件: (b : 实数)
  证明: by
  simp only [← nhdsGT_sup_nhdsWithin_singleton, nhdsWithin_singleton, tendsto_sup,
    tendsto_measure_Icc_nhdsWithin_right' μ b, true_and, tendsto_pure_left]
  intro s hs
  simpa using mem_of_mem_nhds hs

Depends on / 依赖: mem_of_mem_nhds, nhdsGT_sup_nhdsWithin_singleton, nhdsWithin_singleton, tendsto_measure_Icc_nhdsWithin_right, tendsto_pure_left, tendsto_sup, true_and
-/
lemma tendsto_measure_Icc_nhdsWithin_right (b : Real) :
    Tendsto (fun δ => μ (Icc (b - δ) (b + δ))) (𝓝[>=] (0 : Real)) (𝓝 (μ {b})) := by
  simp only [← nhdsGT_sup_nhdsWithin_singleton, nhdsWithin_singleton, tendsto_sup,
    tendsto_measure_Icc_nhdsWithin_right' μ b, true_and, tendsto_pure_left]
  intro s hs
  simpa using mem_of_mem_nhds hs

/--
lemma `tendsto_measure_Icc` / 引理 `tendsto_measure_Icc`

English:
lemma tendsto_measure_Icc
  given: [NullSingletonClass μ] (b : Real)
  proof: by
  rw [← nhdsLT_sup_nhdsGE]; rw [tendsto_sup]
  constructor
  · apply tendsto_const_nhds.congr'
    filter_upwards [self_mem_nhdsWithin] with r (hr : r < 0)
    rw [Icc_eq_empty (by linarith)]; rw [measure_empty]
  · simpa only [measure_singleton] using tendsto_measure_Icc_nhdsWithin_right μ b

中文:
引理 tendsto_measure_Icc
  条件: [NullSingletonClass μ] (b : 实数)
  证明: by
  rw [← nhdsLT_sup_nhdsGE]; rw [tendsto_sup]
  constructor
  · apply tendsto_const_nhds.congr'
    filter_upwards [self_mem_nhdsWithin] with r (hr : r < 0)
    rw [Icc_eq_empty (by linarith)]; rw [measure_empty]
  · simpa only [measure_singleton] using tendsto_measure_Icc_nhdsWithin_right μ b

Depends on / 依赖: Icc_eq_empty, filter_upwards, measure_empty, measure_singleton, nhdsLT_sup_nhdsGE, self_mem_nhdsWithin, tendsto_const_nhds, tendsto_const_nhds.congr, tendsto_measure_Icc_nhdsWithin_right, tendsto_sup
-/
lemma tendsto_measure_Icc [NullSingletonClass μ] (b : Real) :
    Tendsto (fun δ => μ (Icc (b - δ) (b + δ))) (𝓝 (0 : Real)) (𝓝 0) := by
  rw [← nhdsLT_sup_nhdsGE]; rw [tendsto_sup]
  constructor
  · apply tendsto_const_nhds.congr'
    filter_upwards [self_mem_nhdsWithin] with r (hr : r < 0)
    rw [Icc_eq_empty (by linarith)]; rw [measure_empty]
  · simpa only [measure_singleton] using tendsto_measure_Icc_nhdsWithin_right μ b
