/-
Copyright (c) 2024 Joël Riou. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joël Riou
-/
module

public import Mathlib.Algebra.Category.ModuleCat.Presheaf.Abelian
public import Mathlib.Algebra.Category.ModuleCat.Presheaf.EpiMono
public import Mathlib.Algebra.Category.ModuleCat.Presheaf.Free
public import Mathlib.Algebra.Homology.ShortComplex.Exact
public import Mathlib.CategoryTheory.Elements
public import Mathlib.CategoryTheory.Generator.Basic

/-!
# Generators for the category of presheaves of modules

In this file, given a presheaf of rings `R` on a category `C`,
we study the set `freeYoneda R` of presheaves of modules
of form `(free R).obj (yoneda.obj X)` for `X : C`, i.e.
free presheaves of modules generated by the Yoneda
presheaf represented by some `X : C` (the functor
represented by such a presheaf of modules is the evaluation
functor `M ↦ M.obj (op X)`, see `freeYonedaEquiv`).

Lemmas `PresheafOfModules.freeYoneda.isSeparating` and
`PresheafOfModules.freeYoneda.isDetecting` assert that this
set `freeYoneda R` is separating and detecting.
We deduce that if `C : Type u` is a small category,
and `R : Cᵒᵖ ⥤ RingCat.{u}`, then `PresheafOfModules.{u} R`
is a well-powered category.

Finally, given `M : PresheafOfModules.{u} R`, we consider
the canonical epimorphism of presheaves of modules
`M.fromFreeYonedaCoproduct : M.freeYonedaCoproduct ⟶ M`
where `M.freeYonedaCoproduct` is a coproduct indexed
by elements of `M`, i.e. pairs `⟨X : Cᵒᵖ, a : M.obj X⟩`,
of the objects `(free R).obj (yoneda.obj X.unop)`.
This is used in the definition
`PresheafOfModules.isColimitFreeYonedaCoproductsCokernelCofork`
in order to obtain that any presheaf of modules is a cokernel
of a morphism between coproducts of objects in `freeYoneda R`.

-/

@[expose] public section

universe v v₁ u u₁

open CategoryTheory Limits

namespace PresheafOfModules

variable {C : Type u} [Category.{v} C] {R : Cᵒᵖ ⥤ RingCat.{v}}

/-- When `R : Cᵒᵖ ⥤ RingCat`, `M : PresheafOfModules R`, and `X : C`, this is the
bijection `((free R).obj (yoneda.obj X) ⟶ M) ≃ M.obj (Opposite.op X)`. -/
/-
**PresheafOfModules.freeYonedaEquiv** 是 Mathlib 中的一个定义，位于命名空间 `PresheafOfModules
`。
形式化陈述：freeYonedaEquiv {M : PresheafOfModules.{v} R} {X : C} : ((free R).obj (yon
eda.obj X) ⟶ M) ≃ M.obj (Opposite.op X)
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.trans`：Equiv.trans {s t u : Computation α} : s ~ t -> t ~ u -> s ~
 u

--- 原说明 ---
When `R : Cᵒᵖ ⥤ RingCat`, `M : PresheafOfModules R`, and `X : C`, this is the
bijection `((free R).obj (yoneda.obj X) ⟶ M) ≃ M.obj (Opposite.op X)`.
-/
noncomputable def freeYonedaEquiv {M : PresheafOfModules.{v} R} {X : C} :
    ((free R).obj (yoneda.obj X) ⟶ M) ≃ M.obj (Opposite.op X) :=
  freeHomEquiv.trans yonedaEquiv

set_option backward.defeqAttrib.useBackward true in
set_option backward.isDefEq.respectTransparency false in
/-
**PresheafOfModules.freeYonedaEquiv_symm_app** 是 Mathlib 中的一个引理，位于命名空间 `Presheaf
OfModules`。
形式化陈述：freeYonedaEquiv_symm_app (M : PresheafOfModules.{v} R) (X : C) (x : M.obj 
(Opposite.op X)) : (freeYonedaEquiv.symm x).app (Opposite.op X) (ModuleCat.freeM
k (𝟙 _)) = x
参数：M : PresheafOfModules.{v} R；X : C；x : M.obj (Opposite.op X)。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用引理 `ModuleCat.freeDesc_apply`：freeDesc_apply {X : Type u} {M : ModuleCat.{u}
 R} (f : X ⟶ M) (x : X) : freeDesc f (freeMk x) = f x
· 使用定理 `CategoryTheory.Functor.map_id`：∀ {C : Type u₁} [inst : CategoryTheory.Ca
tegory.{v₁, u₁} C] {D : Type u₂} [inst_1 : CategoryTheory.Category.{v₂, u₂} D]  
 (self : CategoryTh…
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma freeYonedaEquiv_symm_app (M : PresheafOfModules.{v} R) (X : C)
    (x : M.obj (Opposite.op X)) :
    (freeYonedaEquiv.symm x).app (Opposite.op X) (ModuleCat.freeMk (𝟙 _)) = x := by
  simp [freeYonedaEquiv, freeHomEquiv, yonedaEquiv]
/-
**PresheafOfModules.freeYonedaEquiv_comp** 是 Mathlib 中的一个引理，位于命名空间 `PresheafOfMo
dules`。
形式化陈述：freeYonedaEquiv_comp {M N : PresheafOfModules.{v} R} {X : C} (m : ((free R
).obj (yoneda.obj X) ⟶ M)) (φ : M ⟶ N) : freeYonedaEquiv (m ≫ φ) = φ.app _ (free
YonedaEquiv m)
参数：m : ((free R).obj (yoneda.obj X) ⟶ M)；φ : M ⟶ N。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma freeYonedaEquiv_comp {M N : PresheafOfModules.{v} R} {X : C}
    (m : ((free R).obj (yoneda.obj X) ⟶ M)) (φ : M ⟶ N) :
    freeYonedaEquiv (m ≫ φ) = φ.app _ (freeYonedaEquiv m) := rfl

variable (R) in
/-- The set of `PresheafOfModules.{v} R` consisting of objects of the
form `(free R).obj (yoneda.obj X)` for some `X`. -/
/-
**PresheafOfModules.freeYoneda** 是 Mathlib 中的一个定义，位于命名空间 `PresheafOfModules`。
形式化陈述：freeYoneda : ObjectProperty (PresheafOfModules.{v} R)
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The set of `PresheafOfModules.{v} R` consisting of objects of the
form `(free R).obj (yoneda.obj X)` for some `X`.
-/
def freeYoneda : ObjectProperty (PresheafOfModules.{v} R) := .ofObj (yoneda ⋙ free R).obj

namespace freeYoneda

/-
**PresheafOfModules.freeYoneda.** 是 Mathlib 中的一个实例，位于命名空间 `PresheafOfModules.fre
eYoneda`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance : ObjectProperty.Small.{u} (freeYoneda R) := by
  dsimp [freeYoneda]
  infer_instance

variable (R)
/-
**PresheafOfModules.freeYoneda.isSeparating** 是 Mathlib 中的一个引理，位于命名空间 `PresheafO
fModules.freeYoneda`。
形式化陈述：isSeparating : ObjectProperty.IsSeparating (freeYoneda R)
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `PresheafOfModules.hom_ext`：hom_ext {f g : M₁ ⟶ M₂} (h : forall (X : Cᵒᵖ)
, f.app X = g.app X) : f = g
· 使用引理 `ModuleCat.hom_ext`：hom_ext {M N : ModuleCat.{v} R} {f g : M ⟶ N} (hf : f
.hom = g.hom) : f = g
· 使用定理 `LinearMap.ext`：ext {f g : M ->ₛₗ[σ] M₃} (h : forall x, f x = g x) : f = 
g
· 使用定理 `Equiv.surjective`：∀ {α : Sort u} {β : Sort v} (e : α ≃ β), Function.Surj
ective ⇑e
· 使用定理 `congr_arg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ 
→ f a₁ = f a₂
-/
lemma isSeparating : ObjectProperty.IsSeparating (freeYoneda R) := by
  intro M N f₁ f₂ h
  ext ⟨X⟩ m
  obtain ⟨g, rfl⟩ := freeYonedaEquiv.surjective m
  exact congr_arg freeYonedaEquiv (h _ ⟨X⟩ g)
/-
**PresheafOfModules.freeYoneda.isDetecting** 是 Mathlib 中的一个引理，位于命名空间 `PresheafOf
Modules.freeYoneda`。
形式化陈述：isDetecting : ObjectProperty.IsDetecting (freeYoneda R)
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `CategoryTheory.ObjectProperty.IsSeparating.isDetecting`：∀ {C : Type u₁} 
[inst : CategoryTheory.Category.{v₁, u₁} C] {P : CategoryTheory.ObjectProperty C
}   [CategoryTheory.Balanced C], P.IsSeparat…
· 使用定理 `CategoryTheory.balanced_of_strongMonoCategory`：∀ {C : Type u} [inst : Ca
tegoryTheory.Category.{v, u} C] [CategoryTheory.StrongMonoCategory C],   Categor
yTheory.Balanced C
· 使用定理 `CategoryTheory.strongMonoCategory_of_regularMonoCategory`：∀ {C : Type u₁
} [inst : CategoryTheory.Category.{v₁, u₁} C] [CategoryTheory.IsRegularMonoCateg
ory C],   CategoryTheory.StrongMonoCategory C
· 使用定理 `CategoryTheory.regularMonoCategoryOfNormalMonoCategory`：∀ {C : Type u₁} 
[inst : CategoryTheory.Category.{v₁, u₁} C] [inst_1 : CategoryTheory.Limits.HasZ
eroMorphisms C]   [CategoryTheory.IsNormalMo…
· 使用定理 `PresheafOfModules.instIsNormalMonoCategory`：∀ {C : Type u₁} [inst : Cate
goryTheory.Category.{v₁, u₁} C] (R : CategoryTheory.Functor Cᵒᵖ RingCat),   Cate
goryTheory.IsNormalMonoCategory …
· 使用引理 `PresheafOfModules.freeYoneda.isSeparating`：isSeparating : ObjectProperty
.IsSeparating (freeYoneda R)
-/
lemma isDetecting : ObjectProperty.IsDetecting (freeYoneda R) :=
  (isSeparating R).isDetecting

end freeYoneda

/-
**PresheafOfModules.wellPowered** 是 Mathlib 中的一个实例，位于命名空间 `PresheafOfModules`。
形式化陈述：wellPowered {C₀ : Type u} [SmallCategory C₀] (R₀ : C₀ᵒᵖ ⥤ RingCat.{u}) : W
ellPowered.{u} (PresheafOfModules.{u} R₀)
参数：R₀ : C₀ᵒᵖ ⥤ RingCat.{u}。
该定义给出了上述对象。
本声明引用了以下数学事实（定理与引理）：
· 使用定理 `CategoryTheory.wellPowered_of_isDetecting`：wellPowered_of_isDetecting [H
asPullbacks C] {𝒢 : ObjectProperty C} [ObjectProperty.Small.{w} 𝒢] [LocallySmall
.{w} C] (h𝒢 : 𝒢.IsDetecting) : …
· 使用定理 `Finite.of_fintype`：∀ (α : Type u_4) [Fintype α], Finite α
· 使用定理 `CategoryTheory.Limits.hasFiniteWidePullbacks_of_hasFiniteLimits`：∀ (C : 
Type u) [inst : CategoryTheory.Category.{v, u} C] [CategoryTheory.Limits.HasFini
teLimits C],   CategoryTheory.Limits.HasFiniteWidePul…
· 使用定理 `PresheafOfModules.freeYoneda.instSmall`：∀ {C : Type u} [inst : CategoryT
heory.Category.{v, u} C] {R : CategoryTheory.Functor Cᵒᵖ RingCat},   CategoryThe
ory.ObjectProperty.Small.{u,…
· 使用定理 `CategoryTheory.locallySmall_of_univLE`：∀ (C : Type u) [inst : CategoryTh
eory.Category.{v, u} C] [UnivLE.{v, w}], CategoryTheory.LocallySmall.{w, v, u} C
· 使用引理 `PresheafOfModules.freeYoneda.isDetecting`：isDetecting : ObjectProperty.I
sDetecting (freeYoneda R)
-/
instance wellPowered {C₀ : Type u} [SmallCategory C₀] (R₀ : C₀ᵒᵖ ⥤ RingCat.{u}) :
    WellPowered.{u} (PresheafOfModules.{u} R₀) :=
  wellPowered_of_isDetecting (freeYoneda.isDetecting R₀)

/-- The type of elements of a presheaf of modules. A term of this type is a pair
`⟨X, a⟩` with `X : Cᵒᵖ` and `a : M.obj X`. -/
/-
**PresheafOfModules.Elements** 是 Mathlib 中的一个缩写定义，位于命名空间 `PresheafOfModules`。
形式化陈述：Elements {C : Type u₁} [Category.{v₁} C] {R : Cᵒᵖ ⥤ RingCat.{u}} (M : Pres
heafOfModules.{v} R)
参数：M : PresheafOfModules.{v} R。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The type of elements of a presheaf of modules. A term of this type is a pair
`⟨X, a⟩` with `X : Cᵒᵖ` and `a : M.obj X`.
-/
abbrev Elements {C : Type u₁} [Category.{v₁} C] {R : Cᵒᵖ ⥤ RingCat.{u}}
    (M : PresheafOfModules.{v} R) := ((toPresheaf R).obj M ⋙ forget Ab).Elements

/-- Given a presheaf of modules `M`, this is a constructor for the type `M.Elements`. -/
/-
**PresheafOfModules.elementsMk** 是 Mathlib 中的一个缩写定义，位于命名空间 `PresheafOfModules`。
形式化陈述：elementsMk {C : Type u₁} [Category.{v₁} C] {R : Cᵒᵖ ⥤ RingCat.{u}} (M : Pr
esheafOfModules.{v} R) (X : Cᵒᵖ) (x : M.obj X) : M.Elements
参数：M : PresheafOfModules.{v} R；X : Cᵒᵖ；x : M.obj X。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a presheaf of modules `M`, this is a constructor for the type `M.Elements`
.
-/
noncomputable abbrev elementsMk {C : Type u₁} [Category.{v₁} C] {R : Cᵒᵖ ⥤ RingCat.{u}}
    (M : PresheafOfModules.{v} R) (X : Cᵒᵖ) (x : M.obj X) : M.Elements :=
  Functor.elementsMk _ X x

namespace Elements

variable {C : Type u} [Category.{v} C] {R : Cᵒᵖ ⥤ RingCat.{v}} {M : PresheafOfModules.{v} R}

/-- Given an element `m : M.Elements` of a presheaf of modules `M`, this is the
free presheaf of modules on the Yoneda presheaf of types corresponding to the
underlying object of `m`. -/
/-
**PresheafOfModules.Elements.freeYoneda** 是 Mathlib 中的一个缩写定义，位于命名空间 `PresheafOfM
odules.Elements`。
形式化陈述：freeYoneda (m : M.Elements) : PresheafOfModules.{v} R
参数：m : M.Elements。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given an element `m : M.Elements` of a presheaf of modules `M`, this is the
free presheaf of modules on the Yoneda presheaf of types corresponding to the
underlying object of `m`.
-/
noncomputable abbrev freeYoneda (m : M.Elements) :
    PresheafOfModules.{v} R := (free R).obj (yoneda.obj m.1.unop)

/-- Given an element `m : M.Elements` of a presheaf of modules `M`, this is
the canonical morphism `m.freeYoneda ⟶ M`. -/
/-
**PresheafOfModules.Elements.fromFreeYoneda** 是 Mathlib 中的一个缩写定义，位于命名空间 `Preshea
fOfModules.Elements`。
形式化陈述：fromFreeYoneda (m : M.Elements) : m.freeYoneda ⟶ M
参数：m : M.Elements。
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用定理 `Equiv.symm`：Equiv.symm {s t : Computation α} : s ~ t -> t ~ s

--- 原说明 ---
Given an element `m : M.Elements` of a presheaf of modules `M`, this is
the canonical morphism `m.freeYoneda ⟶ M`.
-/
noncomputable abbrev fromFreeYoneda (m : M.Elements) :
    m.freeYoneda ⟶ M :=
  freeYonedaEquiv.symm m.2
/-
**PresheafOfModules.Elements.fromFreeYoneda_app_apply** 是 Mathlib 中的一个引理，位于命名空间 
`PresheafOfModules.Elements`。
形式化陈述：fromFreeYoneda_app_apply (m : M.Elements) : m.fromFreeYoneda.app m.1 (Modu
leCat.freeMk (𝟙 _)) = m.2
参数：m : M.Elements。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `PresheafOfModules.freeYonedaEquiv_symm_app`：freeYonedaEquiv_symm_app (M 
: PresheafOfModules.{v} R) (X : C) (x : M.obj (Opposite.op X)) : (freeYonedaEqui
v.symm x).app (Opposite.op X) (M…
-/
lemma fromFreeYoneda_app_apply (m : M.Elements) :
    m.fromFreeYoneda.app m.1 (ModuleCat.freeMk (𝟙 _)) = m.2 := by
  apply freeYonedaEquiv_symm_app

end Elements

section

variable {C : Type u} [SmallCategory.{u} C] {R : Cᵒᵖ ⥤ RingCat.{u}} (M : PresheafOfModules.{u} R)

/-- Given a presheaf of modules `M`, this is the coproduct of
all free Yoneda presheaves `m.freeYoneda` for all `m : M.Elements`. -/
/-
**PresheafOfModules.freeYonedaCoproduct** 是 Mathlib 中的一个缩写定义，位于命名空间 `PresheafOfM
odules`。
形式化陈述：freeYonedaCoproduct : PresheafOfModules.{u} R
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a presheaf of modules `M`, this is the coproduct of
all free Yoneda presheaves `m.freeYoneda` for all `m : M.Elements`.
-/
noncomputable abbrev freeYonedaCoproduct : PresheafOfModules.{u} R :=
  ∐ (Elements.freeYoneda (M := M))

/-- Given an element `m : M.Elements` of a presheaf of modules `M`, this is the
canonical inclusion `m.freeYoneda ⟶ M.freeYonedaCoproduct`. -/
/-
**PresheafOfModules.** 是 Mathlib 中的一个缩写定义，位于命名空间 `PresheafOfModules`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given an element `m : M.Elements` of a presheaf of modules `M`, this is the
canonical inclusion `m.freeYoneda ⟶ M.freeYonedaCoproduct`.
-/
noncomputable abbrev ιFreeYonedaCoproduct (m : M.Elements) :
    m.freeYoneda ⟶ M.freeYonedaCoproduct :=
  Sigma.ι _ m

/-- Given a presheaf of modules `M`, this is the
canonical morphism `M.freeYonedaCoproduct ⟶ M`. -/
/-
**PresheafOfModules.fromFreeYonedaCoproduct** 是 Mathlib 中的一个定义，位于命名空间 `PresheafO
fModules`。
形式化陈述：fromFreeYonedaCoproduct : M.freeYonedaCoproduct ⟶ M
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a presheaf of modules `M`, this is the
canonical morphism `M.freeYonedaCoproduct ⟶ M`.
-/
noncomputable def fromFreeYonedaCoproduct :
    M.freeYonedaCoproduct ⟶ M :=
  Sigma.desc Elements.fromFreeYoneda

/-- Given an element `m` of a presheaf of modules `M`, this is the associated
canonical section of the presheaf `M.freeYonedaCoproduct` over the object `m.1`. -/
/-
**PresheafOfModules.freeYonedaCoproductMk** 是 Mathlib 中的一个定义，位于命名空间 `PresheafOfM
odules`。
形式化陈述：freeYonedaCoproductMk (m : M.Elements) : M.freeYonedaCoproduct.obj m.1
参数：m : M.Elements。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given an element `m` of a presheaf of modules `M`, this is the associated
canonical section of the presheaf `M.freeYonedaCoproduct` over the object `m.1`.
-/
noncomputable def freeYonedaCoproductMk (m : M.Elements) :
    M.freeYonedaCoproduct.obj m.1 :=
  (M.ιFreeYonedaCoproduct m).app _ (ModuleCat.freeMk (𝟙 _))

@[reassoc (attr := simp)]
/-
**PresheafOfModules.** 是 Mathlib 中的一个引理，位于命名空间 `PresheafOfModules`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma ι_fromFreeYonedaCoproduct (m : M.Elements) :
    M.ιFreeYonedaCoproduct m ≫ M.fromFreeYonedaCoproduct = m.fromFreeYoneda := by
  apply Sigma.ι_desc
/-
**PresheafOfModules.** 是 Mathlib 中的一个引理，位于命名空间 `PresheafOfModules`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma ι_fromFreeYonedaCoproduct_apply (m : M.Elements) (X : Cᵒᵖ) (x : m.freeYoneda.obj X) :
    M.fromFreeYonedaCoproduct.app X ((M.ιFreeYonedaCoproduct m).app X x) =
      m.fromFreeYoneda.app X x :=
  ConcreteCategory.congr_hom
    ((evaluation R X ⋙ forget _).congr_map (M.ι_fromFreeYonedaCoproduct m)) x

set_option backward.isDefEq.respectTransparency.types false in
@[simp]
/-
**PresheafOfModules.fromFreeYonedaCoproduct_app_mk** 是 Mathlib 中的一个引理，位于命名空间 `Pr
esheafOfModules`。
形式化陈述：fromFreeYonedaCoproduct_app_mk (m : M.Elements) : M.fromFreeYonedaCoproduc
t.app _ (M.freeYonedaCoproductMk m) = m.2
参数：m : M.Elements。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `PresheafOfModules.freeYonedaCoproductMk.eq_1`：∀ {C : Type u} [inst : Cat
egoryTheory.SmallCategory C] {R : CategoryTheory.Functor Cᵒᵖ RingCat}   (M : Pre
sheafOfModules R) (m : M.Elements)…
· 使用引理 `PresheafOfModules.ι_fromFreeYonedaCoproduct_apply`：ι_fromFreeYonedaCopro
duct_apply (m : M.Elements) (X : Cᵒᵖ) (x : m.freeYoneda.obj X) : M.fromFreeYoned
aCoproduct.app X ((M.ιFreeYonedaCoprodu…
· 使用引理 `PresheafOfModules.Elements.fromFreeYoneda_app_apply`：fromFreeYoneda_app_
apply (m : M.Elements) : m.fromFreeYoneda.app m.1 (ModuleCat.freeMk (𝟙 _)) = m.2
-/
lemma fromFreeYonedaCoproduct_app_mk (m : M.Elements) :
    M.fromFreeYonedaCoproduct.app _ (M.freeYonedaCoproductMk m) = m.2 := by
  rw [freeYonedaCoproductMk, M.ι_fromFreeYonedaCoproduct_apply m, m.fromFreeYoneda_app_apply]
/-
**PresheafOfModules.** 是 Mathlib 中的一个实例，位于命名空间 `PresheafOfModules`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
instance : Epi M.fromFreeYonedaCoproduct :=
  epi_of_surjective (fun X m ↦ ⟨M.freeYonedaCoproductMk (M.elementsMk X m),
    M.fromFreeYonedaCoproduct_app_mk (M.elementsMk X m)⟩)

/-- Given a presheaf of modules `M`, this is a morphism between coproducts
of free presheaves of modules on Yoneda presheaves which gives a presentation
of the module `M`, see `isColimitFreeYonedaCoproductsCokernelCofork`. -/
/-
**PresheafOfModules.toFreeYonedaCoproduct** 是 Mathlib 中的一个定义，位于命名空间 `PresheafOfM
odules`。
形式化陈述：toFreeYonedaCoproduct : (kernel M.fromFreeYonedaCoproduct).freeYonedaCopro
duct ⟶ M.freeYonedaCoproduct
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a presheaf of modules `M`, this is a morphism between coproducts
of free presheaves of modules on Yoneda presheaves which gives a presentation
of the module `M`, see `isColimitFreeYonedaCoproductsCokernelCofork`.
-/
noncomputable def toFreeYonedaCoproduct :
    (kernel M.fromFreeYonedaCoproduct).freeYonedaCoproduct ⟶ M.freeYonedaCoproduct :=
  (kernel M.fromFreeYonedaCoproduct).fromFreeYonedaCoproduct ≫ kernel.ι _

@[reassoc (attr := simp)]
/-
**PresheafOfModules.toFreeYonedaCoproduct_fromFreeYonedaCoproduct** 是 Mathlib 中的
一个引理，位于命名空间 `PresheafOfModules`。
形式化陈述：toFreeYonedaCoproduct_fromFreeYonedaCoproduct : M.toFreeYonedaCoproduct ≫ 
M.fromFreeYonedaCoproduct = 0
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `UnivLE.small`：∀ [self : UnivLE.{u, v}] (α : Type u), Small.{v, u} α
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `CategoryTheory.Category.assoc`：∀ {obj : Type u} [self : CategoryTheory.C
ategory.{v, u} obj] {W X Y Z : obj} (f : W ⟶ X) (g : X ⟶ Y) (h : Y ⟶ Z),   Categ
oryTheory.CategoryS…
· 使用定理 `CategoryTheory.Limits.kernel.condition`：∀ {C : Type u} [inst : CategoryT
heory.Category.{v, u} C] [inst_1 : CategoryTheory.Limits.HasZeroMorphisms C] {X 
Y : C}   (f : X ⟶ Y) [inst_2…
· 使用定理 `CategoryTheory.Limits.comp_zero`：comp_zero [HasZeroMorphisms C] {X Y : C
} {f : X ⟶ Y} {Z : C} : f ≫ (0 : Y ⟶ Z) = (0 : X ⟶ Z)
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True
-/
lemma toFreeYonedaCoproduct_fromFreeYonedaCoproduct :
    M.toFreeYonedaCoproduct ≫ M.fromFreeYonedaCoproduct = 0 := by
  simp [toFreeYonedaCoproduct]

/-- (Colimit) cofork which gives a presentation of a presheaf of modules `M` using
coproducts of free presheaves of modules on Yoneda presheaves. -/
/-
**PresheafOfModules.freeYonedaCoproductsCokernelCofork** 是 Mathlib 中的一个缩写定义，位于命名
空间 `PresheafOfModules`。
形式化陈述：freeYonedaCoproductsCokernelCofork : CokernelCofork M.toFreeYonedaCoproduc
t
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用引理 `PresheafOfModules.toFreeYonedaCoproduct_fromFreeYonedaCoproduct`：toFreeY
onedaCoproduct_fromFreeYonedaCoproduct : M.toFreeYonedaCoproduct ≫ M.fromFreeYon
edaCoproduct = 0

--- 原说明 ---
(Colimit) cofork which gives a presentation of a presheaf of modules `M` using
coproducts of free presheaves of modules on Yoneda presheaves.
-/
noncomputable abbrev freeYonedaCoproductsCokernelCofork :
    CokernelCofork M.toFreeYonedaCoproduct :=
  CokernelCofork.ofπ _ M.toFreeYonedaCoproduct_fromFreeYonedaCoproduct

/-- If `M` is a presheaf of modules, the cokernel cofork
`M.freeYonedaCoproductsCokernelCofork` is a colimit, which means that
`M` can be expressed as a cokernel of the morphism `M.toFreeYonedaCoproduct`
between coproducts of free presheaves of modules on Yoneda presheaves. -/
/-
**PresheafOfModules.isColimitFreeYonedaCoproductsCokernelCofork** 是 Mathlib 中的一个
定义，位于命名空间 `PresheafOfModules`。
形式化陈述：isColimitFreeYonedaCoproductsCokernelCofork : IsColimit M.freeYonedaCoprod
uctsCokernelCofork
该定义给出了上述对象。
本定义的构造引用了以下数学事实（定理与引理）：
· 使用引理 `PresheafOfModules.toFreeYonedaCoproduct_fromFreeYonedaCoproduct`：toFreeY
onedaCoproduct_fromFreeYonedaCoproduct : M.toFreeYonedaCoproduct ≫ M.fromFreeYon
edaCoproduct = 0

--- 原说明 ---
If `M` is a presheaf of modules, the cokernel cofork
`M.freeYonedaCoproductsCokernelCofork` is a colimit, which means that
`M` can be expressed as a cokernel of the morphism `M.toFreeYonedaCoproduct`
between coproducts of free presheaves of modules on Yoneda presheaves.
-/
noncomputable def isColimitFreeYonedaCoproductsCokernelCofork :
    IsColimit M.freeYonedaCoproductsCokernelCofork := by
  let S := ShortComplex.mk _ _ M.toFreeYonedaCoproduct_fromFreeYonedaCoproduct
  let T := ShortComplex.mk _ _ (kernel.condition M.fromFreeYonedaCoproduct)
  let φ : S ⟶ T :=
    { τ₁ := fromFreeYonedaCoproduct _
      τ₂ := 𝟙 _
      τ₃ := 𝟙 _ }
  exact ((ShortComplex.exact_iff_of_epi_of_isIso_of_mono φ).2
    (T.exact_of_f_is_kernel (kernelIsKernel _))).gIsCokernel

end

end PresheafOfModules

