/-
Copyright (c) 2026 Joël Riou. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joël Riou
-/
module

public import Mathlib.AlgebraicTopology.SimplicialSet.NonDegenerateSimplices
public import Mathlib.AlgebraicTopology.SimplicialSet.SubcomplexColimits
public import Mathlib.CategoryTheory.Subfunctor.Equalizer

/-!
# Any simplicial set is the colimit of its monogenous subcomplexes

Let `X` be a simplicial set. The definition `SSet.isColimitCoconeN`
shows that `X` is the colimit of the monogenous subcomplexes of `X`
(the index category of this colimit is the partially ordered
type `X.N` of nondegenerate simplices of `X`).

-/

universe u

open CategoryTheory Limits Simplicial Opposite

namespace SSet

variable (X : SSet.{u})

/-- If `X : SSet`, this is the functor `X.N ⥤ SSet` which sends a
nondegenerate simplex of `X` to the subcomplex of `X` that it generates. -/
@[expose, simps! obj map]
public def functorN : X.N ⥤ SSet.{u} :=
  X.orderEmbeddingN.monotone.functor ⋙ Subcomplex.toSSetFunctor

/-- Given `X : SSet`, this is the (colimit) cocone consisting of
the inclusions of the monogenous subcomplexes of `X`. (Note: a monogenous
subcomplex of `X` is generated by a unique nondegenerate simplex `x : X.N`.) -/
@[expose, implicit_reducible]
public def coconeN : Cocone X.functorN where
  pt := X
  ι.app _ := Subcomplex.ι _

namespace isColimitCoconeN

/--
lemma `multicoequalizerDiagram` / 引理 `multicoequalizerDiagram`

English:
lemma multicoequalizerDiagram
  proof: by
    rw [Subcomplex.eq_top_iff_contains_nonDegenerate]
    intro n x hx
    simp only [Subfunctor.iSup_obj, Set.mem_iUnion]
    exact ⟨N.mk x hx, Subcomplex.mem_ofSimplex_obj _⟩
  eq_inf _ _ := rfl

中文:
引理 multicoequalizerDiagram
  证明: by
    rw [Subcomplex.eq_top_iff_contains_nonDegenerate]
    intro n x hx
    simp only [Subfunctor.iSup_obj, Set.mem_iUnion]
    exact ⟨N.mk x hx, Subcomplex.mem_ofSimplex_obj _⟩
  eq_inf _ _ := rfl

Depends on / 依赖: N.mk, Set.mem_iUnion, Subcomplex, Subcomplex.eq_top_iff_contains_nonDegenerate, Subcomplex.mem_ofSimplex_obj, Subfunctor, Subfunctor.iSup_obj, eq_inf, eq_top_iff_contains_nonDegenerate, iSup_obj, mem_iUnion, mem_ofSimplex_obj
-/
lemma multicoequalizerDiagram :
    Subcomplex.MulticoequalizerDiagram ⊤ (fun (x : X.N) => x.subcomplex)
      (fun x y => x.subcomplex ⊓ y.subcomplex) where
  iSup_eq := by
    rw [Subcomplex.eq_top_iff_contains_nonDegenerate]
    intro n x hx
    simp only [Subfunctor.iSup_obj, Set.mem_iUnion]
    exact ⟨N.mk x hx, Subcomplex.mem_ofSimplex_obj _⟩
  eq_inf _ _ := rfl

variable {X}

set_option backward.isDefEq.respectTransparency false in
set_option backward.defeqAttrib.useBackward true in
/--
Definition of `desc` / `desc` 的定义

English:
abbreviation desc
  signature: (s : Cocone X.functorN)
  body: (Subcomplex.topIso X).inv ≫
    Multicofork.IsColimit.desc (multicoequalizerDiagram X).isColimit (fun x => s.ι.app x)
      (fun (x, y) => by
        dsimp
        rw [← Subfunctor.equalizer_eq_iff]
        have H (u : X.N) (t : X.N) (h : t.simplex in u.subcomplex.obj _) :
            (s.ι.app u).ap

中文:
缩写 desc
  签名: (s : Cocone X.functorN)
  定义体: (Subcomplex.topIso X).inv ≫
    Multicofork.IsColimit.desc (multicoequalizerDiagram X).isColimit (fun x => s.ι.app x)
      (fun (x, y) => by
        dsimp
        rw [← Subfunctor.equalizer_eq_iff]
        have H (u : X.N) (t : X.N) (h : t.simplex in u.subcomplex.obj _) :
            (s.ι.app u).ap

Depends on / 依赖: ConcreteCategory, ConcreteCategory.congr_hom, IsColimit, Multicofork, Multicofork.IsColimit.desc, N.le_iff, NatTrans, NatTrans.congr_app, Subcomplex, Subcomplex.mem_ofSimplex_obj, Subcomplex.ofSimplex_le_iff, Subcomplex.topIso, Subfunctor, Subfunctor.equalizer_eq_iff, congr_app, congr_hom, equalizer_eq_iff, homOfLE, isColimit, le_iff
-/
noncomputable abbrev desc (s : Cocone X.functorN) : X ⟶ s.pt :=
  (Subcomplex.topIso X).inv ≫
    Multicofork.IsColimit.desc (multicoequalizerDiagram X).isColimit (fun x => s.ι.app x)
      (fun (x, y) => by
        dsimp
        rw [← Subfunctor.equalizer_eq_iff]
        have H (u : X.N) (t : X.N) (h : t.simplex in u.subcomplex.obj _) :
            (s.ι.app u).app _ ⟨t.simplex, h⟩ =
            (s.ι.app t).app _ ⟨t.simplex, Subcomplex.mem_ofSimplex_obj _⟩ :=
          ConcreteCategory.congr_hom
            (NatTrans.congr_app (s.w (homOfLE (by
              rwa [N.le_iff, Subcomplex.ofSimplex_le_iff]))) _)
            ⟨t.simplex, Subcomplex.mem_ofSimplex_obj _⟩
        refine le_antisymm (Subfunctor.equalizer_le _ _) ?_
        rw [Subcomplex.le_iff_contains_nonDegenerate]
        intro n z hz
        exact (Subfunctor.mem_equalizer_iff (x := ⟨_, hz⟩) ..).mpr
          ((H x (N.mk _ z.prop) hz.1).trans (H y (N.mk _ z.prop) hz.2).symm))

set_option backward.isDefEq.respectTransparency false in
@[reassoc]
/--
lemma `fac` / 引理 `fac`

English:
lemma fac
  given: (s : Cocone X.functorN) (x : X.N)
  proof: by
  have : x.subcomplex.ι ≫ (Subcomplex.topIso X).inv =
    ((multicoequalizerDiagram X).multicofork.map Subcomplex.toSSetFunctor).π x := rfl
  rw [reassoc_of% this]
  apply Multicofork.IsColimit.fac

中文:
引理 fac
  条件: (s : Cocone X.functorN) (x : X.N)
  证明: by
  have : x.subcomplex.ι ≫ (Subcomplex.topIso X).inv =
    ((multicoequalizerDiagram X).multicofork.map Subcomplex.toSSetFunctor).π x := rfl
  rw [reassoc_of% this]
  apply Multicofork.IsColimit.fac

Depends on / 依赖: IsColimit, Multicofork, Multicofork.IsColimit.fac, Subcomplex, Subcomplex.toSSetFunctor, Subcomplex.topIso, multicoequalizerDiagram, multicofork, multicofork.map, reassoc_of, subcomplex, toSSetFunctor, topIso, x.subcomplex
-/
lemma fac (s : Cocone X.functorN) (x : X.N) :
    x.subcomplex.ι ≫ desc s = s.ι.app x := by
  have : x.subcomplex.ι ≫ (Subcomplex.topIso X).inv =
    ((multicoequalizerDiagram X).multicofork.map Subcomplex.toSSetFunctor).π x := rfl
  rw [reassoc_of% this]
  apply Multicofork.IsColimit.fac

end isColimitCoconeN

open isColimitCoconeN in
/-- If `X : SSet`, then `X` is the colimit of its monogenous subcomplexes.
(Note: a monogenous subcomplex of `X` is generated by a unique nondegenerate
simplex `x : X.N`.) -/
public noncomputable def isColimitCoconeN : IsColimit X.coconeN where
  desc := desc
  fac := fac
  uniq s m hm := by
    rw [← cancel_epi (Subcomplex.topIso X).hom]
    exact Multicofork.IsColimit.hom_ext (multicoequalizerDiagram X).isColimit
      (fun x => (hm _).trans (fac s x).symm)

end SSet
