/-
Copyright (c) 2025 Joël Riou. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joël Riou
-/
module

public import Mathlib.AlgebraicTopology.SimplicialSet.Monoidal
public import Mathlib.AlgebraicTopology.SimplicialSet.Subcomplex

/-!
# Relative morphisms of simplicial sets

Given two simplicial sets `X` and `Y`, and subcomplexes `A` of `X`, and `B` of `Y`,
we introduce a type `RelativeMorphism A B φ` of morphisms `X ⟶ Y` which induce
a given morphism of simplicial sets `A ⟶ B`. We define homotopies between
these relative morphisms and introduce the quotient type of homotopy classes.
This is used in the file `Mathlib/AlgebraicTopology/SimplicialSet/Homotopy.lean`
in order to define homotopies (`SSet.Homotopy`) between morphisms in the
category of simplicial sets.

-/

@[expose] public section

universe u

open CategoryTheory Simplicial MonoidalCategory CartesianMonoidalCategory

namespace SSet

variable {X Y Z : SSet.{u}} (A : X.Subcomplex) (B : Y.Subcomplex)
  (φ : (A : SSet) ⟶ (B : SSet))

/-- Given a morphism of simplicial sets `φ : A ⟶ B` with `A : X.Subcomplex` and
`B : Y.Subcomplex`, this is the type of morphisms `X ⟶ Y` which induce `φ`. -/
@[ext]
/--
Definition of `RelativeMorphism` / `RelativeMorphism` 的定义

English:
structure RelativeMorphism
  parameters: where
  axioms and operations (2):
    - map : X ⟶ Y
    - comm : A.ι ≫ map = φ ≫ B.ι  [default: by cat_disch]

中文:
结构 Relative态射
  参数: where
  公理与运算 (2 个):
    - map : X ⟶ Y
    - comm : A.ι ≫ map = φ ≫ B.ι  [默认: by cat_disch]

Depends on / 依赖: cat_disch
-/
structure RelativeMorphism where
  /-- The underlying morphism of simplicial sets. -/
  map : X ⟶ Y
  comm : A.ι ≫ map = φ ≫ B.ι := by cat_disch

namespace RelativeMorphism

attribute [reassoc (attr := simp)] comm

variable {A} in
/-- The constant relative morphism when the given subcomplex of the target
is generated by a `0`-simplex. -/
@[simps]
/--
Definition of `const` / `const` 的定义

English:
definition const
  signature: {y : Y _⦋0⦌} {φ : (A : SSet) ⟶ (Subcomplex.ofSimplex y : SSet)}
  body: SSet.const y

中文:
定义 const
  签名: {y : Y _⦋0⦌} {φ : (A : SSet) ⟶ (子复形.ofSimplex y : SSet)}
  定义体: SSet.const y

Depends on / 依赖: SSet.const
-/
def const {y : Y _⦋0⦌} {φ : (A : SSet) ⟶ (Subcomplex.ofSimplex y : SSet)} :
    RelativeMorphism A (Subcomplex.ofSimplex y) φ where
  map := SSet.const y

/-- Given a morphism `f : X ⟶ Y` of simplicial set which sends a `0`-simplex `x` to `y`,
this is the pointed morphism `(X, x) ⟶ (Y, y)`. -/
@[simps]
/--
Definition of `ofSimplex₀` / `ofSimplex₀` 的定义

English:
definition ofSimplex₀
  signature: (f : X ⟶ Y) (x : X _⦋0⦌) (y : Y _⦋0⦌) (h : f.app _ x = y)
  body: f

中文:
定义 ofSimplex₀
  签名: (f : X ⟶ Y) (x : X _⦋0⦌) (y : Y _⦋0⦌) (h : f.app _ x = y)
  定义体: f
-/
def ofSimplex₀ (f : X ⟶ Y) (x : X _⦋0⦌) (y : Y _⦋0⦌) (h : f.app _ x = y) :
    RelativeMorphism (.ofSimplex x) (.ofSimplex y)
      (SSet.const ⟨y, Subcomplex.mem_ofSimplex_obj y⟩) where
  map := f

variable {A B φ} (f g : RelativeMorphism A B φ)

/--
lemma `map_eq_of_mem` / 引理 `map_eq_of_mem`

English:
lemma map_eq_of_mem
  given: {n : SimplexCategoryᵒᵖ} (a : X.obj n) (ha : a in A.obj n)
  proof: ConcreteCategory.congr_hom (congr_app f.comm n) ⟨a, ha⟩

@[simp]

中文:
引理 map_eq_of_mem
  条件: {n : SimplexCategoryᵒᵖ} (a : X.obj n) (ha : a in A.obj n)
  证明: ConcreteCategory.congr_hom (congr_app f.comm n) ⟨a, ha⟩

@[simp]

Depends on / 依赖: ConcreteCategory, ConcreteCategory.congr_hom, congr_app, congr_hom, f.comm
-/
lemma map_eq_of_mem {n : SimplexCategoryᵒᵖ} (a : X.obj n) (ha : a in A.obj n) :
    f.map.app n a = φ.app n ⟨a, ha⟩ :=
  ConcreteCategory.congr_hom (congr_app f.comm n) ⟨a, ha⟩

@[simp]
/--
lemma `map_coe` / 引理 `map_coe`

English:
lemma map_coe
  given: {n : SimplexCategoryᵒᵖ} (a : A.obj n)
  proof: map_eq_of_mem _ _ _

中文:
引理 map_coe
  条件: {n : SimplexCategoryᵒᵖ} (a : A.obj n)
  证明: map_eq_of_mem _ _ _

Depends on / 依赖: map_eq_of_mem
-/
lemma map_coe {n : SimplexCategoryᵒᵖ} (a : A.obj n) :
    f.map.app n a = φ.app n a :=
  map_eq_of_mem _ _ _

set_option backward.isDefEq.respectTransparency.types false in
/--
lemma `image_le` / 引理 `image_le`

English:
lemma image_le
  statement: A.image f.map <= B
  proof: by
  rintro n _ ⟨a, ha, rfl⟩
  have := f.map_coe ⟨a, ha⟩
  aesop

中文:
引理 image_le
  结论: A.像 f.map <= B
  证明: by
  rintro n _ ⟨a, ha, rfl⟩
  have := f.map_coe ⟨a, ha⟩
  aesop

Depends on / 依赖: f.map_coe, map_coe
-/
lemma image_le : A.image f.map <= B := by
  rintro n _ ⟨a, ha, rfl⟩
  have := f.map_coe ⟨a, ha⟩
  aesop

/--
lemma `le_preimage` / 引理 `le_preimage`

English:
lemma le_preimage
  statement: A <= B.preimage f.map
  proof: by
  simpa only [← Subcomplex.image_le_iff] using f.image_le

中文:
引理 le_preimage
  结论: A <= B.原像 f.map
  证明: by
  simpa only [← Subcomplex.image_le_iff] using f.image_le

Depends on / 依赖: Subcomplex, Subcomplex.image_le_iff, f.image_le, image_le, image_le_iff
-/
lemma le_preimage : A <= B.preimage f.map := by
  simpa only [← Subcomplex.image_le_iff] using f.image_le

/-- The type of homotopies between morphisms of simplicial sets relatively to
given subcomplexes. (See also `SSet.Homotopy` in the file
`Mathlib/AlgebraicTopology/SimplicialSet/Homotopy.lean` for the non-relative version.) -/
@[ext]
/--
Definition of `Homotopy` / `Homotopy` 的定义

English:
structure Homotopy
  parameters: where
  axioms and operations (4):
    - h : X otimes Δ[1] ⟶ Y
    - h₀ : ι₀ ≫ h = f.map  [default: by cat_disch]
    - h₁ : ι₁ ≫ h = g.map  [default: by cat_disch]
    - rel : A.ι ▷ _ ≫ h = fst _ _ ≫ φ ≫ B.ι  [default: by cat_disch]

中文:
结构 同伦
  参数: where
  公理与运算 (4 个):
    - h : X otimes Δ[1] ⟶ Y
    - h₀ : ι₀ ≫ h = f.map  [默认: by cat_disch]
    - h₁ : ι₁ ≫ h = g.map  [默认: by cat_disch]
    - rel : A.ι ▷ _ ≫ h = fst _ _ ≫ φ ≫ B.ι  [默认: by cat_disch]

Depends on / 依赖: cat_disch, g.map
-/
structure Homotopy where
  /-- The homotopy. -/
  h : X otimes Δ[1] ⟶ Y
  h₀ : ι₀ ≫ h = f.map := by cat_disch
  h₁ : ι₁ ≫ h = g.map := by cat_disch
  rel : A.ι ▷ _ ≫ h = fst _ _ ≫ φ ≫ B.ι := by cat_disch

namespace Homotopy

attribute [reassoc (attr := simp)] h₀ h₁ rel

variable {f g} in
/-- Two equal relative morphisms are homotopic. -/
@[simps]
/--
Definition of `ofEq` / `ofEq` 的定义

English:
definition ofEq
  signature: (h : f = g)
  body: fst _ _ ≫ f.map

中文:
定义 ofEq
  签名: (h : f = g)
  定义体: fst _ _ ≫ f.map

Depends on / 依赖: f.map
-/
noncomputable def ofEq (h : f = g) : Homotopy f g where
  h := fst _ _ ≫ f.map

/-- A relative morphism is homotopic to itself. -/
@[simps]
/--
Definition of `refl` / `refl` 的定义

English:
definition refl
  signature: : Homotopy f f where
  body: fst _ _ ≫ f.map

中文:
定义 refl
  签名: : 同伦 f f where
  定义体: fst _ _ ≫ f.map

Depends on / 依赖: f.map
-/
noncomputable def refl : Homotopy f f where
  h := fst _ _ ≫ f.map

end Homotopy

variable (A B φ)

/--
Definition of `HomotopyClass` / `HomotopyClass` 的定义

English:
definition HomotopyClass
  signature: : Type u
  body: Quot (α := RelativeMorphism A B φ) (fun f g => Nonempty (Homotopy f g))

中文:
定义 HomotopyClass
  签名: : 类型u
  定义体: Quot (α := RelativeMorphism A B φ) (fun f g => Nonempty (Homotopy f g))

Depends on / 依赖: Homotopy, Nonempty, RelativeMorphism
-/
def HomotopyClass : Type u :=
  Quot (α := RelativeMorphism A B φ) (fun f g => Nonempty (Homotopy f g))

variable {A B φ}

/--
Definition of `homotopyClass` / `homotopyClass` 的定义

English:
definition homotopyClass
  signature: (f : RelativeMorphism A B φ)
  body: Quot.mk _ f

中文:
定义 homotopyClass
  签名: (f : Relative态射 A B φ)
  定义体: Quot.mk _ f

Depends on / 依赖: Quot.mk
-/
def homotopyClass (f : RelativeMorphism A B φ) : HomotopyClass A B φ := Quot.mk _ f

/--
lemma `Homotopy.eq` / 引理 `Homotopy.eq`

English:
lemma Homotopy.eq
  given: {f g : RelativeMorphism A B φ} (h : Homotopy f g)
  proof: Quot.sound ⟨h⟩

中文:
引理 同伦.eq
  条件: {f g : Relative态射 A B φ} (h : 同伦 f g)
  证明: Quot.sound ⟨h⟩

Depends on / 依赖: Quot.sound
-/
lemma Homotopy.eq {f g : RelativeMorphism A B φ} (h : Homotopy f g) :
    f.homotopyClass = g.homotopyClass :=
  Quot.sound ⟨h⟩

/--
lemma `HomotopyClass.eq_homotopyClass` / 引理 `HomotopyClass.eq_homotopyClass`

English:
lemma HomotopyClass.eq_homotopyClass
  given: (x : HomotopyClass A B φ)
  proof: Quot.mk_surjective x

中文:
引理 HomotopyClass.eq_homotopyClass
  条件: (x : HomotopyClass A B φ)
  证明: Quot.mk_surjective x

Depends on / 依赖: Quot.mk_surjective, mk_surjective
-/
lemma HomotopyClass.eq_homotopyClass (x : HomotopyClass A B φ) :
    exists (f : RelativeMorphism A B φ), f.homotopyClass = x :=
  Quot.mk_surjective x

variable {C : Z.Subcomplex} {ψ : (B : SSet) ⟶ (C : SSet)}

/-- The composition of relative morphisms. -/
@[simps]
/--
Definition of `comp` / `comp` 的定义

English:
definition comp
  signature: (f' : RelativeMorphism B C ψ) {φψ : (A : SSet) ⟶ (C : SSet)}
  body: f.map ≫ f'.map

中文:
定义 comp
  签名: (f' : Relative态射 B C ψ) {φψ : (A : SSet) ⟶ (C : SSet)}
  定义体: f.map ≫ f'.map

Depends on / 依赖: f.map
-/
def comp (f' : RelativeMorphism B C ψ) {φψ : (A : SSet) ⟶ (C : SSet)}
    (fac : φ ≫ ψ = φψ) : RelativeMorphism A C φψ where
  map := f.map ≫ f'.map

variable {f g}

/-- The postcomposition of an homotopy with a relative morphism. -/
@[simps]
/--
Definition of `Homotopy.postcomp` / `Homotopy.postcomp` 的定义

English:
definition Homotopy.postcomp
  signature: (h : Homotopy f g)
  body: h.h ≫ f'.map
  rel := by simp [h.rel_assoc, ← fac]

中文:
定义 同伦.postcomp
  签名: (h : 同伦 f g)
  定义体: h.h ≫ f'.map
  rel := by simp [h.rel_assoc, ← fac]
-/
noncomputable def Homotopy.postcomp (h : Homotopy f g)
    (f' : RelativeMorphism B C ψ) {φψ : (A : SSet) ⟶ (C : SSet)}
    (fac : φ ≫ ψ = φψ) :
    Homotopy (f.comp f' fac) (g.comp f' fac) where
  h := h.h ≫ f'.map
  rel := by simp [h.rel_assoc, ← fac]

/-- The precomposition of an homotopy with a relative morphism. -/
@[simps]
/--
Definition of `Homotopy.precomp` / `Homotopy.precomp` 的定义

English:
definition Homotopy.precomp
  body: f.map ▷ _ ≫ h.h
  rel := by
    rw [← fac]; rw [Category.assoc]; rw [← comp_whiskerRight_assoc]; rw [f.comm]; rw [comp_whiskerRight_assoc]; rw [h.rel]; rw [whiskerRight_fst_assoc]

中文:
定义 同伦.precomp
  定义体: f.map ▷ _ ≫ h.h
  rel := by
    rw [← fac]; rw [Category.assoc]; rw [← comp_whiskerRight_assoc]; rw [f.comm]; rw [comp_whiskerRight_assoc]; rw [h.rel]; rw [whiskerRight_fst_assoc]

Depends on / 依赖: f.map
-/
noncomputable def Homotopy.precomp
    {f' g' : RelativeMorphism B C ψ} (h : Homotopy f' g')
    (f : RelativeMorphism A B φ) {φψ : (A : SSet) ⟶ (C : SSet)}
    (fac : φ ≫ ψ = φψ) :
    Homotopy (f.comp f' fac) (f.comp g' fac) where
  h := f.map ▷ _ ≫ h.h
  rel := by
    rw [← fac]; rw [Category.assoc]; rw [← comp_whiskerRight_assoc]; rw [f.comm]; rw [comp_whiskerRight_assoc]; rw [h.rel]; rw [whiskerRight_fst_assoc]

/--
Definition of `HomotopyClass.postcomp` / `HomotopyClass.postcomp` 的定义

English:
definition HomotopyClass.postcomp
  signature: (h : HomotopyClass A B φ)
  body: Quot.lift (fun f => (f.comp f' fac).homotopyClass)
    (fun _ _ ⟨h⟩ => (h.postcomp f' fac).eq) h

@[simp]

中文:
定义 HomotopyClass.postcomp
  签名: (h : HomotopyClass A B φ)
  定义体: Quot.lift (fun f => (f.comp f' fac).homotopyClass)
    (fun _ _ ⟨h⟩ => (h.postcomp f' fac).eq) h

@[simp]

Depends on / 依赖: Quot.lift, f.comp, h.postcomp, homotopyClass, postcomp
-/
def HomotopyClass.postcomp (h : HomotopyClass A B φ)
    (f' : RelativeMorphism B C ψ) {φψ : (A : SSet) ⟶ (C : SSet)}
    (fac : φ ≫ ψ = φψ) :
    HomotopyClass A C φψ :=
  Quot.lift (fun f => (f.comp f' fac).homotopyClass)
    (fun _ _ ⟨h⟩ => (h.postcomp f' fac).eq) h

@[simp]
/--
lemma `postcomp_homotopyClass` / 引理 `postcomp_homotopyClass`

English:
lemma postcomp_homotopyClass
  proof: rfl

中文:
引理 postcomp_homotopyClass
  证明: rfl
-/
lemma postcomp_homotopyClass
    (f : RelativeMorphism A B φ) (f' : RelativeMorphism B C ψ)
    {φψ : (A : SSet) ⟶ (C : SSet)} (fac : φ ≫ ψ = φψ) :
    f.homotopyClass.postcomp f' fac =
      (f.comp f' fac).homotopyClass := rfl

/--
Definition of `HomotopyClass.precomp` / `HomotopyClass.precomp` 的定义

English:
definition HomotopyClass.precomp
  body: Quot.lift (fun f => (f'.comp f fac).homotopyClass)
    (fun _ _ ⟨h⟩ => (h.precomp f' fac).eq) h

@[simp]

中文:
定义 HomotopyClass.precomp
  定义体: Quot.lift (fun f => (f'.comp f fac).homotopyClass)
    (fun _ _ ⟨h⟩ => (h.precomp f' fac).eq) h

@[simp]

Depends on / 依赖: Quot.lift, h.precomp, homotopyClass, precomp
-/
noncomputable def HomotopyClass.precomp
    (h : HomotopyClass B C ψ)
    (f' : RelativeMorphism A B φ) {φψ : (A : SSet) ⟶ (C : SSet)}
    (fac : φ ≫ ψ = φψ) :
    HomotopyClass A C φψ :=
  Quot.lift (fun f => (f'.comp f fac).homotopyClass)
    (fun _ _ ⟨h⟩ => (h.precomp f' fac).eq) h

@[simp]
/--
lemma `precomp_homotopyClass` / 引理 `precomp_homotopyClass`

English:
lemma precomp_homotopyClass
  proof: rfl

中文:
引理 precomp_homotopyClass
  证明: rfl
-/
lemma precomp_homotopyClass
    (f : RelativeMorphism A B φ) (f' : RelativeMorphism B C ψ)
    {φψ : (A : SSet) ⟶ (C : SSet)} (fac : φ ≫ ψ = φψ) :
    f'.homotopyClass.precomp f fac =
      (f.comp f' fac).homotopyClass := rfl

end RelativeMorphism

end SSet
