/-
Copyright (c) 2025 Joël Riou. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joël Riou
-/
module

public import Mathlib.AlgebraicTopology.SimplicialSet.Monoidal
public import Mathlib.AlgebraicTopology.SimplicialSet.Subcomplex

/-!
# Relative morphisms of simplicial sets

Given two simplicial sets `X` and `Y`, and subcomplexes `A` of `X`, and `B` of `Y`,
we introduce a type `RelativeMorphism A B φ` of morphisms `X ⟶ Y` which induce
a given morphism of simplicial sets `A ⟶ B`. We define homotopies between
these relative morphisms and introduce the quotient type of homotopy classes.
This is used in the file `Mathlib/AlgebraicTopology/SimplicialSet/Homotopy.lean`
in order to define homotopies (`SSet.Homotopy`) between morphisms in the
category of simplicial sets.

-/

@[expose] public section

universe u

open CategoryTheory Simplicial MonoidalCategory CartesianMonoidalCategory

namespace SSet

variable {X Y Z : SSet.{u}} (A : X.Subcomplex) (B : Y.Subcomplex)
  (φ : (A : SSet) ⟶ (B : SSet))

/-- Given a morphism of simplicial sets `φ : A ⟶ B` with `A : X.Subcomplex` and
`B : Y.Subcomplex`, this is the type of morphisms `X ⟶ Y` which induce `φ`. -/
@[ext]
/-
**SSet.RelativeMorphism** 是 Mathlib 中的一个结构，位于命名空间 `SSet`。
形式化陈述：RelativeMorphism where /-- The underlying morphism of simplicial sets. -/ 
map : X ⟶ Y comm : A.ι ≫ map = φ ≫ B.ι
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a morphism of simplicial sets `φ : A ⟶ B` with `A : X.Subcomplex` and
`B : Y.Subcomplex`, this is the type of morphisms `X ⟶ Y` which induce `φ`.
-/
structure RelativeMorphism where
  /-- The underlying morphism of simplicial sets. -/
  map : X ⟶ Y
  comm : A.ι ≫ map = φ ≫ B.ι := by cat_disch

namespace RelativeMorphism

attribute [reassoc (attr := simp)] comm

variable {A} in
/-- The constant relative morphism when the given subcomplex of the target
is generated by a `0`-simplex. -/
@[simps]
/-
**SSet.RelativeMorphism.const** 是 Mathlib 中的一个定义，位于命名空间 `SSet.RelativeMorphism`。
形式化陈述：const {y : Y _⦋0⦌} {φ : (A : SSet) ⟶ (Subcomplex.ofSimplex y : SSet)} : Re
lativeMorphism A (Subcomplex.ofSimplex y) φ where map
参数：A : SSet；Subcomplex.ofSimplex y : SSet。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The constant relative morphism when the given subcomplex of the target
is generated by a `0`-simplex.
-/
def const {y : Y _⦋0⦌} {φ : (A : SSet) ⟶ (Subcomplex.ofSimplex y : SSet)} :
    RelativeMorphism A (Subcomplex.ofSimplex y) φ where
  map := SSet.const y

/-- Given a morphism `f : X ⟶ Y` of simplicial set which sends a `0`-simplex `x` to `y`,
this is the pointed morphism `(X, x) ⟶ (Y, y)`. -/
@[simps]
/-
**SSet.RelativeMorphism.ofSimplex** 是 Mathlib 中的一个定义，位于命名空间 `SSet.RelativeMorphi
sm`。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Given a morphism `f : X ⟶ Y` of simplicial set which sends a `0`-simplex `x` to 
`y`,
this is the pointed morphism `(X, x) ⟶ (Y, y)`.
-/
def ofSimplex₀ (f : X ⟶ Y) (x : X _⦋0⦌) (y : Y _⦋0⦌) (h : f.app _ x = y) :
    RelativeMorphism (.ofSimplex x) (.ofSimplex y)
      (SSet.const ⟨y, Subcomplex.mem_ofSimplex_obj y⟩) where
  map := f

variable {A B φ} (f g : RelativeMorphism A B φ)
/-
**SSet.RelativeMorphism.map_eq_of_mem** 是 Mathlib 中的一个引理，位于命名空间 `SSet.RelativeMo
rphism`。
形式化陈述：map_eq_of_mem {n : SimplexCategoryᵒᵖ} (a : X.obj n) (ha : a in A.obj n) : 
f.map.app n a = φ.app n ⟨a, ha⟩
参数：a : X.obj n；ha : a in A.obj n。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `CategoryTheory.ConcreteCategory.congr_hom`：congr_hom {X Y : C} {f g : X 
⟶ Y} (h : f = g) (x : ToType X) : f x = g x
· 使用定理 `CategoryTheory.congr_app`：congr_app {F G : C ⥤ D} {α β : NatTrans F G} (
h : α = β) (X : C) : α.app X = β.app X
· 使用定理 `SSet.RelativeMorphism.comm`：∀ {X Y : _root_.SSet} {A : X.Subcomplex} {B 
: Y.Subcomplex} {φ : A.toSSet ⟶ B.toSSet}   (self : SSet.RelativeMorphism A B φ)
,   CategoryTheo…
-/
lemma map_eq_of_mem {n : SimplexCategoryᵒᵖ} (a : X.obj n) (ha : a ∈ A.obj n) :
    f.map.app n a = φ.app n ⟨a, ha⟩ :=
  ConcreteCategory.congr_hom (congr_app f.comm n) ⟨a, ha⟩

@[simp]
/-
**SSet.RelativeMorphism.map_coe** 是 Mathlib 中的一个引理，位于命名空间 `SSet.RelativeMorphism
`。
形式化陈述：map_coe {n : SimplexCategoryᵒᵖ} (a : A.obj n) : f.map.app n a = φ.app n a
参数：a : A.obj n。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `SSet.RelativeMorphism.map_eq_of_mem`：map_eq_of_mem {n : SimplexCategoryᵒ
ᵖ} (a : X.obj n) (ha : a in A.obj n) : f.map.app n a = φ.app n ⟨a, ha⟩
· 使用定理 `Subtype.property`：∀ {α : Sort u} {p : α → Prop} (self : Subtype p), p ↑s
elf
-/
lemma map_coe {n : SimplexCategoryᵒᵖ} (a : A.obj n) :
    f.map.app n a = φ.app n a :=
  map_eq_of_mem _ _ _

set_option backward.isDefEq.respectTransparency.types false in
/-
**SSet.RelativeMorphism.image_le** 是 Mathlib 中的一个引理，位于命名空间 `SSet.RelativeMorphis
m`。
形式化陈述：image_le : A.image f.map <= B
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `SSet.RelativeMorphism.map_coe`：map_coe {n : SimplexCategoryᵒᵖ} (a : A.ob
j n) : f.map.app n a = φ.app n a
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
-/
lemma image_le : A.image f.map ≤ B := by
  rintro n _ ⟨a, ha, rfl⟩
  have := f.map_coe ⟨a, ha⟩
  aesop
/-
**SSet.RelativeMorphism.le_preimage** 是 Mathlib 中的一个引理，位于命名空间 `SSet.RelativeMorp
hism`。
形式化陈述：le_preimage : A <= B.preimage f.map
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用引理 `SSet.RelativeMorphism.image_le`：image_le : A.image f.map <= B
-/
lemma le_preimage : A ≤ B.preimage f.map := by
  simpa only [← Subcomplex.image_le_iff] using f.image_le

/-- The type of homotopies between morphisms of simplicial sets relatively to
given subcomplexes. (See also `SSet.Homotopy` in the file
`Mathlib/AlgebraicTopology/SimplicialSet/Homotopy.lean` for the non-relative version.) -/
@[ext]
/-
**SSet.RelativeMorphism.Homotopy** 是 Mathlib 中的一个结构，位于命名空间 `SSet.RelativeMorphis
m`。
形式化陈述：Homotopy where /-- The homotopy. -/ h : X otimes Δ[1] ⟶ Y h₀ : ι₀ ≫ h = f.
map
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The type of homotopies between morphisms of simplicial sets relatively to
given subcomplexes. (See also `SSet.Homotopy` in the file
`Mathlib/AlgebraicTopology/SimplicialSet/Homotopy.lean` for the non-relative ver
sion.)
-/
structure Homotopy where
  /-- The homotopy. -/
  h : X ⊗ Δ[1] ⟶ Y
  h₀ : ι₀ ≫ h = f.map := by cat_disch
  h₁ : ι₁ ≫ h = g.map := by cat_disch
  rel : A.ι ▷ _ ≫ h = fst _ _ ≫ φ ≫ B.ι := by cat_disch

namespace Homotopy

attribute [reassoc (attr := simp)] h₀ h₁ rel

variable {f g} in
/-- Two equal relative morphisms are homotopic. -/
@[simps]
/-
**SSet.RelativeMorphism.Homotopy.ofEq** 是 Mathlib 中的一个定义，位于命名空间 `SSet.RelativeMo
rphism.Homotopy`。
形式化陈述：ofEq (h : f = g) : Homotopy f g where h
参数：h : f = g。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
Two equal relative morphisms are homotopic.
-/
noncomputable def ofEq (h : f = g) : Homotopy f g where
  h := fst _ _ ≫ f.map

/-- A relative morphism is homotopic to itself. -/
@[simps]
/-
**SSet.RelativeMorphism.Homotopy.refl** 是 Mathlib 中的一个定义，位于命名空间 `SSet.RelativeMo
rphism.Homotopy`。
形式化陈述：refl : Homotopy f f where h
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
A relative morphism is homotopic to itself.
-/
noncomputable def refl : Homotopy f f where
  h := fst _ _ ≫ f.map

end Homotopy

variable (A B φ)

/-- The type of homotopy classes of relative morphisms. -/
/-
**SSet.RelativeMorphism.HomotopyClass** 是 Mathlib 中的一个定义，位于命名空间 `SSet.RelativeMo
rphism`。
形式化陈述：HomotopyClass : Type u
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The type of homotopy classes of relative morphisms.
-/
def HomotopyClass : Type u :=
  Quot (α := RelativeMorphism A B φ) (fun f g ↦ Nonempty (Homotopy f g))

variable {A B φ}

/-- The homotopy class of a relative morphism. -/
/-
**SSet.RelativeMorphism.homotopyClass** 是 Mathlib 中的一个定义，位于命名空间 `SSet.RelativeMo
rphism`。
形式化陈述：homotopyClass (f : RelativeMorphism A B φ) : HomotopyClass A B φ
参数：f : RelativeMorphism A B φ。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The homotopy class of a relative morphism.
-/
def homotopyClass (f : RelativeMorphism A B φ) : HomotopyClass A B φ := Quot.mk _ f
/-
**SSet.RelativeMorphism.Homotopy.eq** 是 Mathlib 中的一个定理，位于命名空间 `SSet.RelativeMorp
hism.Homotopy`。
形式化陈述：∀ {X Y : _root_.SSet} {A : X.Subcomplex} {B : Y.Subcomplex} {φ : A.toSSet 
⟶ B.toSSet}   {f g : SSet.RelativeMorphism A B φ} (h : f.Homotopy g), f.homotopy
Class = g.homotopyClass
参数：h : f.Homotopy g。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma Homotopy.eq {f g : RelativeMorphism A B φ} (h : Homotopy f g) :
    f.homotopyClass = g.homotopyClass :=
  Quot.sound ⟨h⟩
/-
**SSet.RelativeMorphism.HomotopyClass.eq_homotopyClass** 是 Mathlib 中的一个定理，位于命名空间
 `SSet.RelativeMorphism.HomotopyClass`。
形式化陈述：∀ {X Y : _root_.SSet} {A : X.Subcomplex} {B : Y.Subcomplex} {φ : A.toSSet 
⟶ B.toSSet}   (x : SSet.RelativeMorphism.HomotopyClass A B φ), ∃ f, f.homotopyCl
ass = x
参数：x : SSet.RelativeMorphism.HomotopyClass A B φ。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Quot.mk_surjective`：Quot.mk_surjective {r : α -> α -> Prop} : Function.S
urjective (Quot.mk r)
-/
lemma HomotopyClass.eq_homotopyClass (x : HomotopyClass A B φ) :
    ∃ (f : RelativeMorphism A B φ), f.homotopyClass = x :=
  Quot.mk_surjective x

variable {C : Z.Subcomplex} {ψ : (B : SSet) ⟶ (C : SSet)}

/-- The composition of relative morphisms. -/
@[simps]
/-
**SSet.RelativeMorphism.comp** 是 Mathlib 中的一个定义，位于命名空间 `SSet.RelativeMorphism`。
形式化陈述：comp (f' : RelativeMorphism B C ψ) {φψ : (A : SSet) ⟶ (C : SSet)} (fac : φ
 ≫ ψ = φψ) : RelativeMorphism A C φψ where map
参数：f' : RelativeMorphism B C ψ；A : SSet；C : SSet；fac : φ ≫ ψ = φψ。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The composition of relative morphisms.
-/
def comp (f' : RelativeMorphism B C ψ) {φψ : (A : SSet) ⟶ (C : SSet)}
    (fac : φ ≫ ψ = φψ) : RelativeMorphism A C φψ where
  map := f.map ≫ f'.map

variable {f g}

/-- The postcomposition of an homotopy with a relative morphism. -/
@[simps]
/-
**SSet.RelativeMorphism.Homotopy.postcomp** 是 Mathlib 中的一个定义，位于命名空间 `SSet.Relati
veMorphism.Homotopy`。
形式化陈述：{X Y Z : _root_.SSet} →   {A : X.Subcomplex} →     {B : Y.Subcomplex} →   
    {φ : A.toSSet ⟶ B.toSSet} →         {f g : SSet.RelativeMorphism A B φ} →   
        {C : Z.Subcomplex} →             {ψ : B.toSSet ⟶ C.toSSet} →            
   f.Homotopy g →                 (f' : SSet.RelativeMorphism B C ψ) →          
         {φψ : A.toSSet ⟶ C.toSSet} →                     (fac : CategoryTheory.
CategoryStruct.comp φ ψ = φψ) → (f.comp f' fac).Homotopy (g.comp f' fac)
参数：f' : SSet.RelativeMorphism B C ψ；fac : CategoryTheory.CategoryStruct.comp φ ψ
 = φψ；f.comp f' fac；g.comp f' fac。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The postcomposition of an homotopy with a relative morphism.
-/
noncomputable def Homotopy.postcomp (h : Homotopy f g)
    (f' : RelativeMorphism B C ψ) {φψ : (A : SSet) ⟶ (C : SSet)}
    (fac : φ ≫ ψ = φψ) :
    Homotopy (f.comp f' fac) (g.comp f' fac) where
  h := h.h ≫ f'.map
  rel := by simp [h.rel_assoc, ← fac]

/-- The precomposition of an homotopy with a relative morphism. -/
@[simps]
/-
**SSet.RelativeMorphism.Homotopy.precomp** 是 Mathlib 中的一个定义，位于命名空间 `SSet.Relativ
eMorphism.Homotopy`。
形式化陈述：{X Y Z : _root_.SSet} →   {A : X.Subcomplex} →     {B : Y.Subcomplex} →   
    {φ : A.toSSet ⟶ B.toSSet} →         {C : Z.Subcomplex} →           {ψ : B.to
SSet ⟶ C.toSSet} →             {f' g' : SSet.RelativeMorphism B C ψ} →          
     f'.Homotopy g' →                 (f : SSet.RelativeMorphism A B φ) →       
            {φψ : A.toSSet ⟶ C.toSSet} →                     (fac : CategoryTheo
ry.CategoryStruct.comp φ ψ = φψ) → (f.comp f' fac).Homotopy (f.comp g' fac)
参数：f : SSet.RelativeMorphism A B φ；fac : CategoryTheory.CategoryStruct.comp φ ψ 
= φψ；f.comp f' fac；f.comp g' fac。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The precomposition of an homotopy with a relative morphism.
-/
noncomputable def Homotopy.precomp
    {f' g' : RelativeMorphism B C ψ} (h : Homotopy f' g')
    (f : RelativeMorphism A B φ) {φψ : (A : SSet) ⟶ (C : SSet)}
    (fac : φ ≫ ψ = φψ) :
    Homotopy (f.comp f' fac) (f.comp g' fac) where
  h := f.map ▷ _ ≫ h.h
  rel := by
    rw [← fac, Category.assoc, ← comp_whiskerRight_assoc, f.comm,
      comp_whiskerRight_assoc, h.rel, whiskerRight_fst_assoc]

/-- The postcomposition of an homotopy class by a relative morphism. -/
/-
**SSet.RelativeMorphism.HomotopyClass.postcomp** 是 Mathlib 中的一个定义，位于命名空间 `SSet.R
elativeMorphism.HomotopyClass`。
形式化陈述：{X Y Z : _root_.SSet} →   {A : X.Subcomplex} →     {B : Y.Subcomplex} →   
    {φ : A.toSSet ⟶ B.toSSet} →         {C : Z.Subcomplex} →           {ψ : B.to
SSet ⟶ C.toSSet} →             SSet.RelativeMorphism.HomotopyClass A B φ →      
         SSet.RelativeMorphism B C ψ →                 {φψ : A.toSSet ⟶ C.toSSet
} →                   CategoryTheory.CategoryStruct.comp φ ψ = φψ → SSet.Relativ
eMorphism.HomotopyClass A C φψ
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The postcomposition of an homotopy class by a relative morphism.
-/
def HomotopyClass.postcomp (h : HomotopyClass A B φ)
    (f' : RelativeMorphism B C ψ) {φψ : (A : SSet) ⟶ (C : SSet)}
    (fac : φ ≫ ψ = φψ) :
    HomotopyClass A C φψ :=
  Quot.lift (fun f ↦ (f.comp f' fac).homotopyClass)
    (fun _ _ ⟨h⟩ ↦ (h.postcomp f' fac).eq) h

@[simp]
/-
**SSet.RelativeMorphism.postcomp_homotopyClass** 是 Mathlib 中的一个引理，位于命名空间 `SSet.R
elativeMorphism`。
形式化陈述：postcomp_homotopyClass (f : RelativeMorphism A B φ) (f' : RelativeMorphism
 B C ψ) {φψ : (A : SSet) ⟶ (C : SSet)} (fac : φ ≫ ψ = φψ) : f.homotopyClass.post
comp f' fac = (f.comp f' fac).homotopyClass
参数：f : RelativeMorphism A B φ；f' : RelativeMorphism B C ψ；A : SSet；C : SSet；fac 
: φ ≫ ψ = φψ。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma postcomp_homotopyClass
    (f : RelativeMorphism A B φ) (f' : RelativeMorphism B C ψ)
    {φψ : (A : SSet) ⟶ (C : SSet)} (fac : φ ≫ ψ = φψ) :
    f.homotopyClass.postcomp f' fac =
      (f.comp f' fac).homotopyClass := rfl

/-- The precomposition of an homotopy class with a relative morphism. -/
/-
**SSet.RelativeMorphism.HomotopyClass.precomp** 是 Mathlib 中的一个定义，位于命名空间 `SSet.Re
lativeMorphism.HomotopyClass`。
形式化陈述：{X Y Z : _root_.SSet} →   {A : X.Subcomplex} →     {B : Y.Subcomplex} →   
    {φ : A.toSSet ⟶ B.toSSet} →         {C : Z.Subcomplex} →           {ψ : B.to
SSet ⟶ C.toSSet} →             SSet.RelativeMorphism.HomotopyClass B C ψ →      
         SSet.RelativeMorphism A B φ →                 {φψ : A.toSSet ⟶ C.toSSet
} →                   CategoryTheory.CategoryStruct.comp φ ψ = φψ → SSet.Relativ
eMorphism.HomotopyClass A C φψ
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The precomposition of an homotopy class with a relative morphism.
-/
noncomputable def HomotopyClass.precomp
    (h : HomotopyClass B C ψ)
    (f' : RelativeMorphism A B φ) {φψ : (A : SSet) ⟶ (C : SSet)}
    (fac : φ ≫ ψ = φψ) :
    HomotopyClass A C φψ :=
  Quot.lift (fun f ↦ (f'.comp f fac).homotopyClass)
    (fun _ _ ⟨h⟩ ↦ (h.precomp f' fac).eq) h

@[simp]
/-
**SSet.RelativeMorphism.precomp_homotopyClass** 是 Mathlib 中的一个引理，位于命名空间 `SSet.Re
lativeMorphism`。
形式化陈述：precomp_homotopyClass (f : RelativeMorphism A B φ) (f' : RelativeMorphism 
B C ψ) {φψ : (A : SSet) ⟶ (C : SSet)} (fac : φ ≫ ψ = φψ) : f'.homotopyClass.prec
omp f fac = (f.comp f' fac).homotopyClass
参数：f : RelativeMorphism A B φ；f' : RelativeMorphism B C ψ；A : SSet；C : SSet；fac 
: φ ≫ ψ = φψ。
该定理/引理给出了一组等式。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
lemma precomp_homotopyClass
    (f : RelativeMorphism A B φ) (f' : RelativeMorphism B C ψ)
    {φψ : (A : SSet) ⟶ (C : SSet)} (fac : φ ≫ ψ = φψ) :
    f'.homotopyClass.precomp f fac =
      (f.comp f' fac).homotopyClass := rfl

end RelativeMorphism

end SSet

