/-
Copyright (c) 2023 Kim Morrison. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/
module

public import Mathlib.Algebra.Group.Submonoid.Membership
public import Mathlib.Algebra.GroupWithZero.Regular
public import Mathlib.Algebra.Order.Module.Defs
public import Mathlib.Algebra.Order.Group.Nat
public import Mathlib.Algebra.Order.Group.Opposite
public import Mathlib.Algebra.Star.SelfAdjoint
public import Mathlib.Algebra.Star.StarRingHom
public import Mathlib.Tactic.ContinuousFunctionalCalculus
public import Mathlib.Algebra.Star.StarProjection

/-! # Star ordered rings

We define the class `StarOrderedRing R`, which says that the order on `R` respects the
star operation, i.e. an element `r` is nonnegative iff it is in the `AddSubmonoid` generated by
elements of the form `star s * s`. In many cases, including all C⋆-algebras, this can be reduced to
`0 ≤ r ↔ ∃ s, r = star s * s`. However, this generality is slightly more convenient (e.g., it
allows us to register a `StarOrderedRing` instance for `ℚ`), and more closely resembles the
literature (see the seminal paper [*The positive cone in Banach algebras*][kelleyVaught1953])

In order to accommodate `NonUnitalSemiring R`, we actually don't characterize nonnegativity, but
rather the entire `≤` relation with `StarOrderedRing.le_iff`. However, notice that when `R` is a
`NonUnitalRing`, these are equivalent (see `StarOrderedRing.nonneg_iff` and
`StarOrderedRing.of_nonneg_iff`).

It is important to note that while a `StarOrderedRing` often satisfies `IsOrderedAddMonoid`,
it usually does *not* satisfy `IsOrderedRing`.

## TODO

* In a Banach star algebra without a well-defined square root, the natural ordering is given by the
  positive cone which is the _closure_ of the sums of elements `star r * r`. A weaker version of
  `StarOrderedRing` could be defined for this case (again, see
  [*The positive cone in Banach algebras*][kelleyVaught1953]). Note that the current definition has
  the advantage of not requiring a topology.
-/

public section

open Set
open scoped NNRat

variable {R A : Type*}

section prereq
variable [Semiring R] [StarRing R]
  [NonUnitalSemiring A] [StarRing A] [Module R A]
  [StarModule R A] [IsScalarTower R A A] [SMulCommClass R A A]

/--
lemma `smul_mem_closure_star_mul` / 引理 `smul_mem_closure_star_mul`

English:
lemma smul_mem_closure_star_mul
  statement: {r : R}
  proof: by
  induction hr using AddSubmonoid.closure_induction with
  | zero => simp
  | add r₁ r₂ _ _ hr₁ hr₂ => simpa [add_smul] using add_mem hr₁ hr₂
  | mem r hr =>
  induction ha using AddSubmonoid.closure_induction with
  | zero => simp
  | add a₁ a₂ _ _ ha₁ ha₂ => simpa [smul_add] using add_mem ha₁ ha₂
  | mem a ha =>
  obtain ⟨r, rfl⟩ := hr
  obtain ⟨a, rfl⟩ := ha
  exact AddSubmonoid.subset_closure ⟨r • a, by simp [star_smul, smul_mul_smul_comm]⟩

中文:
引理 smul_mem_closure_star_mul
  结论: {r : R}
  证明: by
  induction hr using AddSubmonoid.closure_induction with
  | zero => simp
  | add r₁ r₂ _ _ hr₁ hr₂ => simpa [add_smul] using add_mem hr₁ hr₂
  | mem r hr =>
  induction ha using AddSubmonoid.closure_induction with
  | zero => simp
  | add a₁ a₂ _ _ ha₁ ha₂ => simpa [smul_add] using add_mem ha₁ ha₂
  | mem a ha =>
  obtain ⟨r, rfl⟩ := hr
  obtain ⟨a, rfl⟩ := ha
  exact AddSubmonoid.subset_closure ⟨r • a, by simp [star_smul, smul_mul_smul_comm]⟩

Depends on / 依赖: AddSubmonoid, AddSubmonoid.closure_induction, AddSubmonoid.subset_closure, add_mem, add_smul, closure_induction, smul_add, smul_mul_smul_comm, star_smul, subset_closure
-/
lemma smul_mem_closure_star_mul {r : R}
    (hr : r in AddSubmonoid.closure (range fun s => star s * s)) {a : A}
    (ha : a in AddSubmonoid.closure (range fun s => star s * s)) :
    r • a in AddSubmonoid.closure (range fun s => star s * s) := by
  induction hr using AddSubmonoid.closure_induction with
  | zero => simp
  | add r₁ r₂ _ _ hr₁ hr₂ => simpa [add_smul] using add_mem hr₁ hr₂
  | mem r hr =>
  induction ha using AddSubmonoid.closure_induction with
  | zero => simp
  | add a₁ a₂ _ _ ha₁ ha₂ => simpa [smul_add] using add_mem ha₁ ha₂
  | mem a ha =>
  obtain ⟨r, rfl⟩ := hr
  obtain ⟨a, rfl⟩ := ha
  exact AddSubmonoid.subset_closure ⟨r • a, by simp [star_smul, smul_mul_smul_comm]⟩

end prereq

/--
Definition of `StarOrderedRing` / `StarOrderedRing` 的定义

English:
class StarOrderedRing
  parameters: (R : Type*) [NonUnitalSemiring R] [PartialOrder R] [StarRing R]
  axioms and operations (1):
    - le_iff : forall x y : R, x <= y ↔ exists p, p in AddSubmonoid.closure (Set.range fun s => star s * s) ∧ y = x + p

中文:
类 StarOrdered环
  参数: (R : 类型) [非幺半环 R] [偏序 R] [对合环 R]
  公理与运算 (1 个):
    - le_iff : 对任意 x y : R, x <= y ↔ 存在 p, p in 加法子幺半群.closure (集合.range fun s => star s * s) ∧ y = x + p
-/
class StarOrderedRing (R : Type*) [NonUnitalSemiring R] [PartialOrder R] [StarRing R] : Prop where
  /-- characterization of the order in terms of the `StarRing` structure. -/
  le_iff :
    forall x y : R, x <= y ↔ exists p, p in AddSubmonoid.closure (Set.range fun s => star s * s) ∧ y = x + p

/--
Definition of `SelfAdjointDecompose` / `SelfAdjointDecompose` 的定义

English:
class SelfAdjointDecompose
  parameters: (R : Type*) [AddGroup R] [Star R]
  axioms and operations (1):
    - exists_nonneg_sub_nonneg({a : R} (ha : IsSelfAdjoint a)) : exists (b c : R), 0 <= b ∧ 0 <= c ∧ a = b - c

中文:
类 SelfAdjointDecompose
  参数: (R : 类型) [加法群 R] [对合 R]
  公理与运算 (1 个):
    - exists_nonneg_sub_nonneg({a : R} (ha : IsSelfAdjoint a)) : 存在 (b c : R), 0 <= b ∧ 0 <= c ∧ a = b - c
-/
class SelfAdjointDecompose (R : Type*) [AddGroup R] [Star R]
    [PartialOrder R] where
  /-- Every self-adjoint element is the difference of nonnegative elements. -/
  exists_nonneg_sub_nonneg {a : R} (ha : IsSelfAdjoint a) :
    exists (b c : R), 0 <= b ∧ 0 <= c ∧ a = b - c

/--
lemma `IsSelfAdjoint.exists_nonneg_sub_nonneg` / 引理 `IsSelfAdjoint.exists_nonneg_sub_nonneg`

English:
lemma IsSelfAdjoint.exists_nonneg_sub_nonneg
  statement: {R : Type*} [AddGroup R] [Star R]
  proof: SelfAdjointDecompose.exists_nonneg_sub_nonneg ha

中文:
引理 IsSelfAdjoint.存在_nonneg_sub_nonneg
  结论: {R : 类型} [加法群 R] [对合 R]
  证明: SelfAdjointDecompose.exists_nonneg_sub_nonneg ha

Depends on / 依赖: SelfAdjointDecompose, SelfAdjointDecompose.exists_nonneg_sub_nonneg, exists_nonneg_sub_nonneg
-/
lemma IsSelfAdjoint.exists_nonneg_sub_nonneg {R : Type*} [AddGroup R] [Star R]
    [PartialOrder R] [SelfAdjointDecompose R] {a : R} (ha : IsSelfAdjoint a) :
    exists (b c : R), 0 <= b ∧ 0 <= c ∧ a = b - c :=
  SelfAdjointDecompose.exists_nonneg_sub_nonneg ha

namespace StarOrderedRing
section NonUnitalSemiring
variable [NonUnitalSemiring R] [PartialOrder R] [StarRing R]

/--
lemma `of_le_iff` / 引理 `of_le_iff`

English:
lemma of_le_iff
  given: (h_le_iff : forall x y : R, x <= y ↔ exists s, y = x + star s * s)
  statement: StarOrderedRing R where
  proof: by
    refine ⟨fun h => ?_, ?_⟩
    · obtain ⟨p, hp⟩ := (h_le_iff x y).mp h
      exact ⟨star p * p, AddSubmonoid.subset_closure ⟨p, rfl⟩, hp⟩
    · rintro ⟨p, hp, hpxy⟩
      revert x y hpxy
      refine AddSubmonoid.closure_induction ?_ (fun x y h => add_zero x ▸ h.ge) ?_ hp
      · rintro _ ⟨s, rfl⟩ x y rfl
        exact (h_le_iff _ _).mpr ⟨s, rfl⟩
      · rintro _ _ _ _ ha hb x y rfl
        rw [← add_assoc]
        exact (ha _ _ rfl).trans (hb _ _ rfl)

中文:
引理 of_le_iff
  条件: (h_le_iff : 对任意 x y : R, x <= y ↔ 存在 s, y = x + star s * s)
  结论: StarOrdered环 R where
  证明: by
    refine ⟨fun h => ?_, ?_⟩
    · obtain ⟨p, hp⟩ := (h_le_iff x y).mp h
      exact ⟨star p * p, AddSubmonoid.subset_closure ⟨p, rfl⟩, hp⟩
    · rintro ⟨p, hp, hpxy⟩
      revert x y hpxy
      refine AddSubmonoid.closure_induction ?_ (fun x y h => add_zero x ▸ h.ge) ?_ hp
      · rintro _ ⟨s, rfl⟩ x y rfl
        exact (h_le_iff _ _).mpr ⟨s, rfl⟩
      · rintro _ _ _ _ ha hb x y rfl
        rw [← add_assoc]
        exact (ha _ _ rfl).trans (hb _ _ rfl)

Depends on / 依赖: AddSubmonoid, AddSubmonoid.closure_induction, AddSubmonoid.subset_closure, add_assoc, add_zero, closure_induction, h.ge, h_le_iff, revert, subset_closure
-/
lemma of_le_iff (h_le_iff : forall x y : R, x <= y ↔ exists s, y = x + star s * s) : StarOrderedRing R where
  le_iff x y := by
    refine ⟨fun h => ?_, ?_⟩
    · obtain ⟨p, hp⟩ := (h_le_iff x y).mp h
      exact ⟨star p * p, AddSubmonoid.subset_closure ⟨p, rfl⟩, hp⟩
    · rintro ⟨p, hp, hpxy⟩
      revert x y hpxy
      refine AddSubmonoid.closure_induction ?_ (fun x y h => add_zero x ▸ h.ge) ?_ hp
      · rintro _ ⟨s, rfl⟩ x y rfl
        exact (h_le_iff _ _).mpr ⟨s, rfl⟩
      · rintro _ _ _ _ ha hb x y rfl
        rw [← add_assoc]
        exact (ha _ _ rfl).trans (hb _ _ rfl)

variable [StarOrderedRing R] {x y : R}

-- see note [lower instance priority]
instance (priority := 100) toIsOrderedAddMonoid : IsOrderedAddMonoid R where
  add_le_add_left := fun x y hle z => by
    rw [StarOrderedRing.le_iff] at hle ⊢
    refine hle.imp fun s hs => ?_
    rw [hs.2]; rw [add_right_comm]
    exact ⟨hs.1, rfl⟩

-- see note [lower instance priority]
instance (priority := 100) toExistsAddOfLE : ExistsAddOfLE R where
  exists_add_of_le h :=
    match (le_iff _ _).mp h with
    | ⟨p, _, hp⟩ => ⟨p, hp⟩

/--
lemma `nonneg_iff` / 引理 `nonneg_iff`

English:
lemma nonneg_iff
  statement: 0 <= x ↔ x in AddSubmonoid.closure (Set.range fun s : R => star s * s)
  proof: by
  simp only [le_iff, zero_add, exists_eq_right']

中文:
引理 nonneg_iff
  结论: 0 <= x ↔ x in 加法子幺半群.closure (集合.range fun s : R => star s * s)
  证明: by
  simp only [le_iff, zero_add, exists_eq_right']

Depends on / 依赖: exists_eq_right, le_iff, zero_add
-/
lemma nonneg_iff : 0 <= x ↔ x in AddSubmonoid.closure (Set.range fun s : R => star s * s) := by
  simp only [le_iff, zero_add, exists_eq_right']

/--
lemma `pos_iff` / 引理 `pos_iff`

English:
lemma pos_iff
  statement: 0 < x ↔ x != 0 ∧ x in AddSubmonoid.closure (Set.range fun s : R => star s * s)
  proof: by
  simp [lt_iff_le_and_ne, and_comm, eq_comm, le_iff]

中文:
引理 pos_iff
  结论: 0 < x ↔ x != 0 ∧ x in 加法子幺半群.closure (集合.range fun s : R => star s * s)
  证明: by
  simp [lt_iff_le_and_ne, and_comm, eq_comm, le_iff]

Depends on / 依赖: and_comm, eq_comm, le_iff, lt_iff_le_and_ne
-/
lemma pos_iff : 0 < x ↔ x != 0 ∧ x in AddSubmonoid.closure (Set.range fun s : R => star s * s) := by
  simp [lt_iff_le_and_ne, and_comm, eq_comm, le_iff]

variable [IsCancelAdd R]

/--
lemma `lt_iff` / 引理 `lt_iff`

English:
lemma lt_iff
  proof: by
  rw [lt_iff_le_and_ne]; rw [and_comm]; rw [StarOrderedRing.le_iff]; rw [← exists_and_left]
  congr! 2 with p
  simp +contextual [← and_assoc]

中文:
引理 lt_iff
  证明: by
  rw [lt_iff_le_and_ne]; rw [and_comm]; rw [StarOrderedRing.le_iff]; rw [← exists_and_left]
  congr! 2 with p
  simp +contextual [← and_assoc]

Depends on / 依赖: StarOrderedRing, StarOrderedRing.le_iff, and_assoc, and_comm, contextual, exists_and_left, le_iff, lt_iff_le_and_ne
-/
lemma lt_iff :
    x < y ↔ exists p != 0, p in AddSubmonoid.closure (Set.range fun s => star s * s) ∧ y = x + p := by
  rw [lt_iff_le_and_ne]; rw [and_comm]; rw [StarOrderedRing.le_iff]; rw [← exists_and_left]
  congr! 2 with p
  simp +contextual [← and_assoc]

end NonUnitalSemiring

/--
lemma `of_nonneg_iff` / 引理 `of_nonneg_iff`

English:
lemma of_nonneg_iff
  statement: [NonUnitalRing R] [PartialOrder R] [StarRing R]
  proof: by
    have : AddLeftMono R := ⟨fun _ _ _ h => h_add h _⟩
    simpa only [← sub_eq_iff_eq_add', sub_nonneg, exists_eq_right'] using h_nonneg_iff (y - x)

中文:
引理 of_nonneg_iff
  结论: [非幺环 R] [偏序 R] [对合环 R]
  证明: by
    have : AddLeftMono R := ⟨fun _ _ _ h => h_add h _⟩
    simpa only [← sub_eq_iff_eq_add', sub_nonneg, exists_eq_right'] using h_nonneg_iff (y - x)

Depends on / 依赖: AddLeftMono, exists_eq_right, h_add, h_nonneg_iff, sub_eq_iff_eq_add, sub_nonneg
-/
lemma of_nonneg_iff [NonUnitalRing R] [PartialOrder R] [StarRing R]
    (h_add : forall {x y : R}, x <= y -> forall z, z + x <= z + y)
    (h_nonneg_iff : forall x : R, 0 <= x ↔ x in AddSubmonoid.closure (Set.range fun s : R => star s * s)) :
    StarOrderedRing R where
  le_iff x y := by
    have : AddLeftMono R := ⟨fun _ _ _ h => h_add h _⟩
    simpa only [← sub_eq_iff_eq_add', sub_nonneg, exists_eq_right'] using h_nonneg_iff (y - x)

/--
lemma `of_nonneg_iff'` / 引理 `of_nonneg_iff'`

English:
lemma of_nonneg_iff'
  statement: [NonUnitalRing R] [PartialOrder R] [StarRing R]
  proof: of_le_iff by
    have : AddLeftMono R := ⟨fun _ _ _ h => h_add h _⟩
    simpa [sub_eq_iff_eq_add', sub_nonneg] using fun x y => h_nonneg_iff (y - x)

中文:
引理 of_nonneg_iff'
  结论: [非幺环 R] [偏序 R] [对合环 R]
  证明: of_le_iff by
    have : AddLeftMono R := ⟨fun _ _ _ h => h_add h _⟩
    simpa [sub_eq_iff_eq_add', sub_nonneg] using fun x y => h_nonneg_iff (y - x)

Depends on / 依赖: AddLeftMono, h_add, h_nonneg_iff, of_le_iff, sub_eq_iff_eq_add, sub_nonneg
-/
lemma of_nonneg_iff' [NonUnitalRing R] [PartialOrder R] [StarRing R]
    (h_add : forall {x y : R}, x <= y -> forall z, z + x <= z + y)
    (h_nonneg_iff : forall x : R, 0 <= x ↔ exists s, x = star s * s) : StarOrderedRing R :=
of_le_iff by
    have : AddLeftMono R := ⟨fun _ _ _ h => h_add h _⟩
    simpa [sub_eq_iff_eq_add', sub_nonneg] using fun x y => h_nonneg_iff (y - x)

end StarOrderedRing

section NonUnitalSemiring

variable [NonUnitalSemiring R] [PartialOrder R] [StarRing R] [StarOrderedRing R]

/--
lemma `IsSelfAdjoint.of_ge` / 引理 `IsSelfAdjoint.of_ge`

English:
lemma IsSelfAdjoint.of_ge
  given: {x y : R} (h : x <= y) (hx : IsSelfAdjoint x)
  statement: IsSelfAdjoint y
  proof: by
  rw [StarOrderedRing.le_iff] at h
  obtain ⟨d, hd, rfl⟩ := h
  rw [IsSelfAdjoint]; rw [star_add]; rw [hx.star_eq]
  congr
  refine AddMonoidHom.eqOn_closureM (f := starAddEquiv (R := R)) (g := .id R) ?_ hd
  rintro - ⟨s, rfl⟩
  simp

@[deprecated (since := "2026-06-12")] alias IsSelfAdjoint.mono := IsSelfAdjoint.of_ge

@[aesop 10% apply, grind ←]

中文:
引理 IsSelfAdjoint.of_ge
  条件: {x y : R} (h : x <= y) (hx : IsSelfAdjoint x)
  结论: IsSelfAdjoint y
  证明: by
  rw [StarOrderedRing.le_iff] at h
  obtain ⟨d, hd, rfl⟩ := h
  rw [IsSelfAdjoint]; rw [star_add]; rw [hx.star_eq]
  congr
  refine AddMonoidHom.eqOn_closureM (f := starAddEquiv (R := R)) (g := .id R) ?_ hd
  rintro - ⟨s, rfl⟩
  simp

@[deprecated (since := "2026-06-12")] alias IsSelfAdjoint.mono := IsSelfAdjoint.of_ge

@[aesop 10% apply, grind ←]

Depends on / 依赖: AddMonoidHom, AddMonoidHom.eqOn_closureM, IsSelfAdjoint, StarOrderedRing, StarOrderedRing.le_iff, eqOn_closureM, hx.star_eq, le_iff, starAddEquiv, star_add, star_eq
-/
lemma IsSelfAdjoint.of_ge {x y : R} (h : x <= y) (hx : IsSelfAdjoint x) : IsSelfAdjoint y := by
  rw [StarOrderedRing.le_iff] at h
  obtain ⟨d, hd, rfl⟩ := h
  rw [IsSelfAdjoint]; rw [star_add]; rw [hx.star_eq]
  congr
  refine AddMonoidHom.eqOn_closureM (f := starAddEquiv (R := R)) (g := .id R) ?_ hd
  rintro - ⟨s, rfl⟩
  simp

@[deprecated (since := "2026-06-12")] alias IsSelfAdjoint.mono := IsSelfAdjoint.of_ge

@[aesop 10% apply, grind ←]
/--
lemma `IsSelfAdjoint.of_nonneg` / 引理 `IsSelfAdjoint.of_nonneg`

English:
lemma IsSelfAdjoint.of_nonneg
  given: {x : R} (hx : 0 <= x)
  statement: IsSelfAdjoint x
  proof: .of_ge hx .zero R

中文:
引理 IsSelfAdjoint.of_nonneg
  条件: {x : R} (hx : 0 <= x)
  结论: IsSelfAdjoint x
  证明: .of_ge hx .zero R

Depends on / 依赖: of_ge
-/
lemma IsSelfAdjoint.of_nonneg {x : R} (hx : 0 <= x) : IsSelfAdjoint x :=
.of_ge hx .zero R

/-- An alias of `IsSelfAdjoint.of_nonneg` for use with dot notation. -/
alias LE.le.isSelfAdjoint := IsSelfAdjoint.of_nonneg

/--
lemma `LE.le.star_eq` / 引理 `LE.le.star_eq`

English:
lemma LE.le.star_eq
  given: {x : R} (hx : 0 <= x)
  statement: star x = x
  proof: hx.isSelfAdjoint.star_eq

@[simp]

中文:
引理 LE.le.star_eq
  条件: {x : R} (hx : 0 <= x)
  结论: star x = x
  证明: hx.isSelfAdjoint.star_eq

@[simp]

Depends on / 依赖: hx.isSelfAdjoint.star_eq, isSelfAdjoint, star_eq
-/
lemma LE.le.star_eq {x : R} (hx : 0 <= x) : star x = x :=
  hx.isSelfAdjoint.star_eq

@[simp]
/--
theorem `star_mul_self_nonneg` / 定理 `star_mul_self_nonneg`

English:
theorem star_mul_self_nonneg
  given: (r : R)
  statement: 0 <= star r * r
  proof: StarOrderedRing.nonneg_iff.mpr AddSubmonoid.subset_closure ⟨r, rfl⟩

@[simp]

中文:
定理 star_mul_self_nonneg
  条件: (r : R)
  结论: 0 <= star r * r
  证明: StarOrderedRing.nonneg_iff.mpr AddSubmonoid.subset_closure ⟨r, rfl⟩

@[simp]

Depends on / 依赖: AddSubmonoid, AddSubmonoid.subset_closure, StarOrderedRing, StarOrderedRing.nonneg_iff.mpr, nonneg_iff, subset_closure
-/
theorem star_mul_self_nonneg (r : R) : 0 <= star r * r :=
StarOrderedRing.nonneg_iff.mpr AddSubmonoid.subset_closure ⟨r, rfl⟩

@[simp]
/--
theorem `mul_star_self_nonneg` / 定理 `mul_star_self_nonneg`

English:
theorem mul_star_self_nonneg
  given: (r : R)
  statement: 0 <= r * star r
  proof: by
  simpa only [star_star] using star_mul_self_nonneg (star r)

@[aesop safe apply (rule_sets := [CStarAlgebra])]

中文:
定理 mul_star_self_nonneg
  条件: (r : R)
  结论: 0 <= r * star r
  证明: by
  simpa only [star_star] using star_mul_self_nonneg (star r)

@[aesop safe apply (rule_sets := [CStarAlgebra])]

Depends on / 依赖: star_mul_self_nonneg, star_star
-/
theorem mul_star_self_nonneg (r : R) : 0 <= r * star r := by
  simpa only [star_star] using star_mul_self_nonneg (star r)

@[aesop safe apply (rule_sets := [CStarAlgebra])]
/--
theorem `IsSelfAdjoint.mul_self_nonneg` / 定理 `IsSelfAdjoint.mul_self_nonneg`

English:
theorem IsSelfAdjoint.mul_self_nonneg
  given: {a : R} (ha : IsSelfAdjoint a)
  statement: 0 <= a * a
  proof: by
  simpa [ha.star_eq] using star_mul_self_nonneg a

中文:
定理 IsSelfAdjoint.mul_self_nonneg
  条件: {a : R} (ha : IsSelfAdjoint a)
  结论: 0 <= a * a
  证明: by
  simpa [ha.star_eq] using star_mul_self_nonneg a
-/
protected theorem IsSelfAdjoint.mul_self_nonneg {a : R} (ha : IsSelfAdjoint a) : 0 <= a * a := by
  simpa [ha.star_eq] using star_mul_self_nonneg a

/-- A star projection is non-negative in a star-ordered ring. -/
@[grind ->, aesop safe forward (rule_sets := [CStarAlgebra])]
/--
theorem `IsStarProjection.nonneg` / 定理 `IsStarProjection.nonneg`

English:
theorem IsStarProjection.nonneg
  given: {p : R} (hp : IsStarProjection p)
  statement: 0 <= p
  proof: hp.isIdempotentElem ▸ hp.isSelfAdjoint.mul_self_nonneg

@[aesop safe apply]

中文:
定理 是StarProjection.nonneg
  条件: {p : R} (hp : 是StarProjection p)
  结论: 0 <= p
  证明: hp.isIdempotentElem ▸ hp.isSelfAdjoint.mul_self_nonneg

@[aesop safe apply]

Depends on / 依赖: hp.isIdempotentElem, hp.isSelfAdjoint.mul_self_nonneg, isIdempotentElem, isSelfAdjoint, mul_self_nonneg
-/
theorem IsStarProjection.nonneg {p : R} (hp : IsStarProjection p) : 0 <= p :=
  hp.isIdempotentElem ▸ hp.isSelfAdjoint.mul_self_nonneg

@[aesop safe apply]
/--
theorem `star_left_conjugate_nonneg` / 定理 `star_left_conjugate_nonneg`

English:
theorem star_left_conjugate_nonneg
  given: {a : R} (ha : 0 <= a) (c : R)
  statement: 0 <= star c * a * c
  proof: by
  rw [StarOrderedRing.nonneg_iff] at ha
  refine AddSubmonoid.closure_induction (fun x hx => ?_)
    (by rw [mul_zero, zero_mul]) (fun x y _ _ hx hy => ?_) ha
  · obtain ⟨x, rfl⟩ := hx
    convert! star_mul_self_nonneg (x * c) using 1
    rw [star_mul]; rw [← mul_assoc]; rw [mul_assoc _ _ c]
  · calc
      0 <= star c * x * c + 0 := by rw [add_zero]; exact hx
      _ <= star c * x * c + star c * y * c := by gcongr
      _ <= _ := by rw [mul_add, add_mul]

@[aesop safe apply]

中文:
定理 star_left_conjugate_nonneg
  条件: {a : R} (ha : 0 <= a) (c : R)
  结论: 0 <= star c * a * c
  证明: by
  rw [StarOrderedRing.nonneg_iff] at ha
  refine AddSubmonoid.closure_induction (fun x hx => ?_)
    (by rw [mul_zero, zero_mul]) (fun x y _ _ hx hy => ?_) ha
  · obtain ⟨x, rfl⟩ := hx
    convert! star_mul_self_nonneg (x * c) using 1
    rw [star_mul]; rw [← mul_assoc]; rw [mul_assoc _ _ c]
  · calc
      0 <= star c * x * c + 0 := by rw [add_zero]; exact hx
      _ <= star c * x * c + star c * y * c := by gcongr
      _ <= _ := by rw [mul_add, add_mul]

@[aesop safe apply]

Depends on / 依赖: AddSubmonoid, AddSubmonoid.closure_induction, StarOrderedRing, StarOrderedRing.nonneg_iff, add_mul, add_zero, closure_induction, convert, mul_add, mul_assoc, mul_zero, nonneg_iff, star_mul, star_mul_self_nonneg, zero_mul
-/
theorem star_left_conjugate_nonneg {a : R} (ha : 0 <= a) (c : R) : 0 <= star c * a * c := by
  rw [StarOrderedRing.nonneg_iff] at ha
  refine AddSubmonoid.closure_induction (fun x hx => ?_)
    (by rw [mul_zero, zero_mul]) (fun x y _ _ hx hy => ?_) ha
  · obtain ⟨x, rfl⟩ := hx
    convert! star_mul_self_nonneg (x * c) using 1
    rw [star_mul]; rw [← mul_assoc]; rw [mul_assoc _ _ c]
  · calc
      0 <= star c * x * c + 0 := by rw [add_zero]; exact hx
      _ <= star c * x * c + star c * y * c := by gcongr
      _ <= _ := by rw [mul_add, add_mul]

@[aesop safe apply]
/--
theorem `star_right_conjugate_nonneg` / 定理 `star_right_conjugate_nonneg`

English:
theorem star_right_conjugate_nonneg
  given: {a : R} (ha : 0 <= a) (c : R)
  statement: 0 <= c * a * star c
  proof: by
  simpa only [star_star] using star_left_conjugate_nonneg ha (star c)

@[aesop 90% apply (rule_sets := [CStarAlgebra])]

中文:
定理 star_right_conjugate_nonneg
  条件: {a : R} (ha : 0 <= a) (c : R)
  结论: 0 <= c * a * star c
  证明: by
  simpa only [star_star] using star_left_conjugate_nonneg ha (star c)

@[aesop 90% apply (rule_sets := [CStarAlgebra])]

Depends on / 依赖: star_left_conjugate_nonneg, star_star
-/
theorem star_right_conjugate_nonneg {a : R} (ha : 0 <= a) (c : R) : 0 <= c * a * star c := by
  simpa only [star_star] using star_left_conjugate_nonneg ha (star c)

@[aesop 90% apply (rule_sets := [CStarAlgebra])]
/--
theorem `IsSelfAdjoint.conjugate_nonneg` / 定理 `IsSelfAdjoint.conjugate_nonneg`

English:
theorem IsSelfAdjoint.conjugate_nonneg
  statement: {a : R} (ha : 0 <= a) {c : R}
  proof: by
  nth_rewrite 2 [← hc]; exact star_right_conjugate_nonneg ha c

中文:
定理 IsSelfAdjoint.conjugate_nonneg
  结论: {a : R} (ha : 0 <= a) {c : R}
  证明: by
  nth_rewrite 2 [← hc]; exact star_right_conjugate_nonneg ha c
-/
protected theorem IsSelfAdjoint.conjugate_nonneg {a : R} (ha : 0 <= a) {c : R}
    (hc : IsSelfAdjoint c) : 0 <= c * a * c := by
  nth_rewrite 2 [← hc]; exact star_right_conjugate_nonneg ha c

/--
theorem `conjugate_nonneg_of_nonneg` / 定理 `conjugate_nonneg_of_nonneg`

English:
theorem conjugate_nonneg_of_nonneg
  given: {a : R} (ha : 0 <= a) {c : R} (hc : 0 <= c)
  proof: .conjugate_nonneg ha IsSelfAdjoint.of_nonneg hc

中文:
定理 conjugate_nonneg_of_nonneg
  条件: {a : R} (ha : 0 <= a) {c : R} (hc : 0 <= c)
  证明: .conjugate_nonneg ha IsSelfAdjoint.of_nonneg hc

Depends on / 依赖: IsSelfAdjoint, IsSelfAdjoint.of_nonneg, conjugate_nonneg, of_nonneg
-/
theorem conjugate_nonneg_of_nonneg {a : R} (ha : 0 <= a) {c : R} (hc : 0 <= c) :
    0 <= c * a * c :=
.conjugate_nonneg ha IsSelfAdjoint.of_nonneg hc

/--
theorem `star_left_conjugate_le_conjugate` / 定理 `star_left_conjugate_le_conjugate`

English:
theorem star_left_conjugate_le_conjugate
  given: {a b : R} (hab : a <= b) (c : R)
  proof: by
  rw [StarOrderedRing.le_iff] at hab ⊢
  obtain ⟨p, hp, rfl⟩ := hab
  simp_rw [← StarOrderedRing.nonneg_iff] at hp ⊢
  exact ⟨star c * p * c, star_left_conjugate_nonneg hp c, by simp only [add_mul, mul_add]⟩

中文:
定理 star_left_conjugate_le_conjugate
  条件: {a b : R} (hab : a <= b) (c : R)
  证明: by
  rw [StarOrderedRing.le_iff] at hab ⊢
  obtain ⟨p, hp, rfl⟩ := hab
  simp_rw [← StarOrderedRing.nonneg_iff] at hp ⊢
  exact ⟨star c * p * c, star_left_conjugate_nonneg hp c, by simp only [add_mul, mul_add]⟩

Depends on / 依赖: StarOrderedRing, StarOrderedRing.le_iff, StarOrderedRing.nonneg_iff, add_mul, le_iff, mul_add, nonneg_iff, simp_rw, star_left_conjugate_nonneg
-/
theorem star_left_conjugate_le_conjugate {a b : R} (hab : a <= b) (c : R) :
    star c * a * c <= star c * b * c := by
  rw [StarOrderedRing.le_iff] at hab ⊢
  obtain ⟨p, hp, rfl⟩ := hab
  simp_rw [← StarOrderedRing.nonneg_iff] at hp ⊢
  exact ⟨star c * p * c, star_left_conjugate_nonneg hp c, by simp only [add_mul, mul_add]⟩

/--
theorem `star_right_conjugate_le_conjugate` / 定理 `star_right_conjugate_le_conjugate`

English:
theorem star_right_conjugate_le_conjugate
  given: {a b : R} (hab : a <= b) (c : R)
  proof: by
  simpa only [star_star] using star_left_conjugate_le_conjugate hab (star c)

中文:
定理 star_right_conjugate_le_conjugate
  条件: {a b : R} (hab : a <= b) (c : R)
  证明: by
  simpa only [star_star] using star_left_conjugate_le_conjugate hab (star c)

Depends on / 依赖: star_left_conjugate_le_conjugate, star_star
-/
theorem star_right_conjugate_le_conjugate {a b : R} (hab : a <= b) (c : R) :
    c * a * star c <= c * b * star c := by
  simpa only [star_star] using star_left_conjugate_le_conjugate hab (star c)

/--
theorem `IsSelfAdjoint.conjugate_le_conjugate` / 定理 `IsSelfAdjoint.conjugate_le_conjugate`

English:
theorem IsSelfAdjoint.conjugate_le_conjugate
  statement: {a b : R} (hab : a <= b) {c : R}
  proof: by
  simpa only [hc.star_eq] using star_left_conjugate_le_conjugate hab c

中文:
定理 IsSelfAdjoint.conjugate_le_conjugate
  结论: {a b : R} (hab : a <= b) {c : R}
  证明: by
  simpa only [hc.star_eq] using star_left_conjugate_le_conjugate hab c
-/
protected theorem IsSelfAdjoint.conjugate_le_conjugate {a b : R} (hab : a <= b) {c : R}
    (hc : IsSelfAdjoint c) : c * a * c <= c * b * c := by
  simpa only [hc.star_eq] using star_left_conjugate_le_conjugate hab c

/--
theorem `conjugate_le_conjugate_of_nonneg` / 定理 `conjugate_le_conjugate_of_nonneg`

English:
theorem conjugate_le_conjugate_of_nonneg
  given: {a b : R} (hab : a <= b) {c : R} (hc : 0 <= c)
  proof: .conjugate_le_conjugate hab IsSelfAdjoint.of_nonneg hc

@[simp]

中文:
定理 conjugate_le_conjugate_of_nonneg
  条件: {a b : R} (hab : a <= b) {c : R} (hc : 0 <= c)
  证明: .conjugate_le_conjugate hab IsSelfAdjoint.of_nonneg hc

@[simp]

Depends on / 依赖: IsSelfAdjoint, IsSelfAdjoint.of_nonneg, conjugate_le_conjugate, of_nonneg
-/
theorem conjugate_le_conjugate_of_nonneg {a b : R} (hab : a <= b) {c : R} (hc : 0 <= c) :
    c * a * c <= c * b * c :=
.conjugate_le_conjugate hab IsSelfAdjoint.of_nonneg hc

@[simp]
/--
lemma `star_le_star_iff` / 引理 `star_le_star_iff`

English:
lemma star_le_star_iff
  given: {x y : R}
  statement: star x <= star y ↔ x <= y
  proof: by
  suffices forall x y, x <= y -> star x <= star y from
    ⟨by simpa only [star_star] using this (star x) (star y), this x y⟩
  intro x y h
  rw [StarOrderedRing.le_iff] at h ⊢
  obtain ⟨d, hd, rfl⟩ := h
  refine ⟨starAddEquiv d, ?_, star_add _ _⟩
refine AddMonoidHom.mclosure_preimage_le _ _ AddSubmonoid.closure_mono ?_ hd
  rintro - ⟨s, rfl⟩
  exact ⟨s, by simp⟩

@[simp]

中文:
引理 star_le_star_iff
  条件: {x y : R}
  结论: star x <= star y ↔ x <= y
  证明: by
  suffices forall x y, x <= y -> star x <= star y from
    ⟨by simpa only [star_star] using this (star x) (star y), this x y⟩
  intro x y h
  rw [StarOrderedRing.le_iff] at h ⊢
  obtain ⟨d, hd, rfl⟩ := h
  refine ⟨starAddEquiv d, ?_, star_add _ _⟩
refine AddMonoidHom.mclosure_preimage_le _ _ AddSubmonoid.closure_mono ?_ hd
  rintro - ⟨s, rfl⟩
  exact ⟨s, by simp⟩

@[simp]

Depends on / 依赖: AddMonoidHom, AddMonoidHom.mclosure_preimage_le, AddSubmonoid, AddSubmonoid.closure_mono, StarOrderedRing, StarOrderedRing.le_iff, closure_mono, le_iff, mclosure_preimage_le, starAddEquiv, star_add, star_star
-/
lemma star_le_star_iff {x y : R} : star x <= star y ↔ x <= y := by
  suffices forall x y, x <= y -> star x <= star y from
    ⟨by simpa only [star_star] using this (star x) (star y), this x y⟩
  intro x y h
  rw [StarOrderedRing.le_iff] at h ⊢
  obtain ⟨d, hd, rfl⟩ := h
  refine ⟨starAddEquiv d, ?_, star_add _ _⟩
refine AddMonoidHom.mclosure_preimage_le _ _ AddSubmonoid.closure_mono ?_ hd
  rintro - ⟨s, rfl⟩
  exact ⟨s, by simp⟩

@[simp]
/--
lemma `star_lt_star_iff` / 引理 `star_lt_star_iff`

English:
lemma star_lt_star_iff
  given: {x y : R}
  statement: star x < star y ↔ x < y
  proof: by
  by_cases h : x = y
  · simp [h]
  · simpa [le_iff_lt_or_eq, h] using star_le_star_iff (x := x) (y := y)

中文:
引理 star_lt_star_iff
  条件: {x y : R}
  结论: star x < star y ↔ x < y
  证明: by
  by_cases h : x = y
  · simp [h]
  · simpa [le_iff_lt_or_eq, h] using star_le_star_iff (x := x) (y := y)

Depends on / 依赖: le_iff_lt_or_eq, star_le_star_iff
-/
lemma star_lt_star_iff {x y : R} : star x < star y ↔ x < y := by
  by_cases h : x = y
  · simp [h]
  · simpa [le_iff_lt_or_eq, h] using star_le_star_iff (x := x) (y := y)

/--
lemma `star_le_iff` / 引理 `star_le_iff`

English:
lemma star_le_iff
  given: {x y : R}
  statement: star x <= y ↔ x <= star y
  proof: by rw [← star_le_star_iff, star_star]

中文:
引理 star_le_iff
  条件: {x y : R}
  结论: star x <= y ↔ x <= star y
  证明: by rw [← star_le_star_iff, star_star]

Depends on / 依赖: star_le_star_iff, star_star
-/
lemma star_le_iff {x y : R} : star x <= y ↔ x <= star y := by rw [← star_le_star_iff, star_star]

/--
lemma `star_lt_iff` / 引理 `star_lt_iff`

English:
lemma star_lt_iff
  given: {x y : R}
  statement: star x < y ↔ x < star y
  proof: by rw [← star_lt_star_iff, star_star]

@[simp]

中文:
引理 star_lt_iff
  条件: {x y : R}
  结论: star x < y ↔ x < star y
  证明: by rw [← star_lt_star_iff, star_star]

@[simp]

Depends on / 依赖: star_lt_star_iff, star_star
-/
lemma star_lt_iff {x y : R} : star x < y ↔ x < star y := by rw [← star_lt_star_iff, star_star]

@[simp]
/--
lemma `star_nonneg_iff` / 引理 `star_nonneg_iff`

English:
lemma star_nonneg_iff
  given: {x : R}
  statement: 0 <= star x ↔ 0 <= x
  proof: by
  simpa using star_le_star_iff (x := 0) (y := x)

@[simp]

中文:
引理 star_nonneg_iff
  条件: {x : R}
  结论: 0 <= star x ↔ 0 <= x
  证明: by
  simpa using star_le_star_iff (x := 0) (y := x)

@[simp]

Depends on / 依赖: star_le_star_iff
-/
lemma star_nonneg_iff {x : R} : 0 <= star x ↔ 0 <= x := by
  simpa using star_le_star_iff (x := 0) (y := x)

@[simp]
/--
lemma `star_nonpos_iff` / 引理 `star_nonpos_iff`

English:
lemma star_nonpos_iff
  given: {x : R}
  statement: star x <= 0 ↔ x <= 0
  proof: by
  simpa using star_le_star_iff (x := x) (y := 0)

@[simp]

中文:
引理 star_nonpos_iff
  条件: {x : R}
  结论: star x <= 0 ↔ x <= 0
  证明: by
  simpa using star_le_star_iff (x := x) (y := 0)

@[simp]

Depends on / 依赖: star_le_star_iff
-/
lemma star_nonpos_iff {x : R} : star x <= 0 ↔ x <= 0 := by
  simpa using star_le_star_iff (x := x) (y := 0)

@[simp]
/--
lemma `star_pos_iff` / 引理 `star_pos_iff`

English:
lemma star_pos_iff
  given: {x : R}
  statement: 0 < star x ↔ 0 < x
  proof: by
  simpa using star_lt_star_iff (x := 0) (y := x)

@[simp]

中文:
引理 star_pos_iff
  条件: {x : R}
  结论: 0 < star x ↔ 0 < x
  证明: by
  simpa using star_lt_star_iff (x := 0) (y := x)

@[simp]

Depends on / 依赖: star_lt_star_iff
-/
lemma star_pos_iff {x : R} : 0 < star x ↔ 0 < x := by
  simpa using star_lt_star_iff (x := 0) (y := x)

@[simp]
/--
lemma `star_neg_iff` / 引理 `star_neg_iff`

English:
lemma star_neg_iff
  given: {x : R}
  statement: star x < 0 ↔ x < 0
  proof: by
  simpa using star_lt_star_iff (x := x) (y := 0)

中文:
引理 star_neg_iff
  条件: {x : R}
  结论: star x < 0 ↔ x < 0
  证明: by
  simpa using star_lt_star_iff (x := x) (y := 0)

Depends on / 依赖: star_lt_star_iff
-/
lemma star_neg_iff {x : R} : star x < 0 ↔ x < 0 := by
  simpa using star_lt_star_iff (x := x) (y := 0)

/--
theorem `star_left_conjugate_lt_conjugate` / 定理 `star_left_conjugate_lt_conjugate`

English:
theorem star_left_conjugate_lt_conjugate
  given: {a b : R} (hab : a < b) {c : R} (hc : IsRegular c)
  proof: by
  rw [(star_left_conjugate_le_conjugate hab.le _).lt_iff_ne]; rw [hc.right.ne_iff]; rw [hc.star.left.ne_iff]
  exact hab.ne

中文:
定理 star_left_conjugate_lt_conjugate
  条件: {a b : R} (hab : a < b) {c : R} (hc : 是正则 c)
  证明: by
  rw [(star_left_conjugate_le_conjugate hab.le _).lt_iff_ne]; rw [hc.right.ne_iff]; rw [hc.star.left.ne_iff]
  exact hab.ne

Depends on / 依赖: hab.le, hab.ne, hc.right.ne_iff, hc.star.left.ne_iff, lt_iff_ne, ne_iff, star_left_conjugate_le_conjugate
-/
theorem star_left_conjugate_lt_conjugate {a b : R} (hab : a < b) {c : R} (hc : IsRegular c) :
    star c * a * c < star c * b * c := by
  rw [(star_left_conjugate_le_conjugate hab.le _).lt_iff_ne]; rw [hc.right.ne_iff]; rw [hc.star.left.ne_iff]
  exact hab.ne

/--
theorem `star_right_conjugate_lt_conjugate` / 定理 `star_right_conjugate_lt_conjugate`

English:
theorem star_right_conjugate_lt_conjugate
  given: {a b : R} (hab : a < b) {c : R} (hc : IsRegular c)
  proof: by
  simpa only [star_star] using star_left_conjugate_lt_conjugate hab hc.star

中文:
定理 star_right_conjugate_lt_conjugate
  条件: {a b : R} (hab : a < b) {c : R} (hc : 是正则 c)
  证明: by
  simpa only [star_star] using star_left_conjugate_lt_conjugate hab hc.star

Depends on / 依赖: hc.star, star_left_conjugate_lt_conjugate, star_star
-/
theorem star_right_conjugate_lt_conjugate {a b : R} (hab : a < b) {c : R} (hc : IsRegular c) :
    c * a * star c < c * b * star c := by
  simpa only [star_star] using star_left_conjugate_lt_conjugate hab hc.star

/--
theorem `star_left_conjugate_pos` / 定理 `star_left_conjugate_pos`

English:
theorem star_left_conjugate_pos
  given: {a : R} (ha : 0 < a) {c : R} (hc : IsRegular c)
  proof: by
  simpa only [mul_zero, zero_mul] using star_left_conjugate_lt_conjugate ha hc

中文:
定理 star_left_conjugate_pos
  条件: {a : R} (ha : 0 < a) {c : R} (hc : 是正则 c)
  证明: by
  simpa only [mul_zero, zero_mul] using star_left_conjugate_lt_conjugate ha hc

Depends on / 依赖: mul_zero, star_left_conjugate_lt_conjugate, zero_mul
-/
theorem star_left_conjugate_pos {a : R} (ha : 0 < a) {c : R} (hc : IsRegular c) :
    0 < star c * a * c := by
  simpa only [mul_zero, zero_mul] using star_left_conjugate_lt_conjugate ha hc

/--
theorem `star_right_conjugate_pos` / 定理 `star_right_conjugate_pos`

English:
theorem star_right_conjugate_pos
  given: {a : R} (ha : 0 < a) {c : R} (hc : IsRegular c)
  proof: by
  simpa only [star_star] using star_left_conjugate_pos ha hc.star

中文:
定理 star_right_conjugate_pos
  条件: {a : R} (ha : 0 < a) {c : R} (hc : 是正则 c)
  证明: by
  simpa only [star_star] using star_left_conjugate_pos ha hc.star

Depends on / 依赖: hc.star, star_left_conjugate_pos, star_star
-/
theorem star_right_conjugate_pos {a : R} (ha : 0 < a) {c : R} (hc : IsRegular c) :
    0 < c * a * star c := by
  simpa only [star_star] using star_left_conjugate_pos ha hc.star

/--
theorem `star_mul_self_pos` / 定理 `star_mul_self_pos`

English:
theorem star_mul_self_pos
  given: [Nontrivial R] {x : R} (hx : IsRegular x)
  statement: 0 < star x * x
  proof: by
  rw [(star_mul_self_nonneg _).lt_iff_ne]; rw [← mul_zero (star x)]; rw [hx.star.left.ne_iff]
  exact hx.ne_zero.symm

中文:
定理 star_mul_self_pos
  条件: [非平凡 R] {x : R} (hx : 是正则 x)
  结论: 0 < star x * x
  证明: by
  rw [(star_mul_self_nonneg _).lt_iff_ne]; rw [← mul_zero (star x)]; rw [hx.star.left.ne_iff]
  exact hx.ne_zero.symm

Depends on / 依赖: hx.ne_zero.symm, hx.star.left.ne_iff, lt_iff_ne, mul_zero, ne_iff, ne_zero, star_mul_self_nonneg
-/
theorem star_mul_self_pos [Nontrivial R] {x : R} (hx : IsRegular x) : 0 < star x * x := by
  rw [(star_mul_self_nonneg _).lt_iff_ne]; rw [← mul_zero (star x)]; rw [hx.star.left.ne_iff]
  exact hx.ne_zero.symm

/--
theorem `mul_star_self_pos` / 定理 `mul_star_self_pos`

English:
theorem mul_star_self_pos
  given: [Nontrivial R] {x : R} (hx : IsRegular x)
  statement: 0 < x * star x
  proof: by
  simpa using star_mul_self_pos hx.star

中文:
定理 mul_star_self_pos
  条件: [非平凡 R] {x : R} (hx : 是正则 x)
  结论: 0 < x * star x
  证明: by
  simpa using star_mul_self_pos hx.star

Depends on / 依赖: hx.star, star_mul_self_pos
-/
theorem mul_star_self_pos [Nontrivial R] {x : R} (hx : IsRegular x) : 0 < x * star x := by
  simpa using star_mul_self_pos hx.star

end NonUnitalSemiring

section NonUnitalRing

variable [NonUnitalRing R] [PartialOrder R] [StarRing R] [StarOrderedRing R]

/--
lemma `IsSelfAdjoint.iff_of_le` / 引理 `IsSelfAdjoint.iff_of_le`

English:
lemma IsSelfAdjoint.iff_of_le
  given: {a b : R} (hab : a <= b)
  proof: by
  replace hab := (sub_nonneg.mpr hab).isSelfAdjoint
  aesop (add simp IsSelfAdjoint)

alias ⟨_, IsSelfAdjoint.of_le⟩ := IsSelfAdjoint.iff_of_le

中文:
引理 IsSelfAdjoint.iff_of_le
  条件: {a b : R} (hab : a <= b)
  证明: by
  replace hab := (sub_nonneg.mpr hab).isSelfAdjoint
  aesop (add simp IsSelfAdjoint)

alias ⟨_, IsSelfAdjoint.of_le⟩ := IsSelfAdjoint.iff_of_le

Depends on / 依赖: IsSelfAdjoint, isSelfAdjoint, replace, sub_nonneg, sub_nonneg.mpr
-/
lemma IsSelfAdjoint.iff_of_le {a b : R} (hab : a <= b) :
    IsSelfAdjoint a ↔ IsSelfAdjoint b := by
  replace hab := (sub_nonneg.mpr hab).isSelfAdjoint
  aesop (add simp IsSelfAdjoint)

alias ⟨_, IsSelfAdjoint.of_le⟩ := IsSelfAdjoint.iff_of_le

end NonUnitalRing

section Semiring
variable [Semiring R] [PartialOrder R] [StarRing R] [StarOrderedRing R]

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: ZeroLEOneClass R
  body: by simpa using star_mul_self_nonneg (1 : R)

@[simp]

中文:
实例 :
  签名: ZeroLEOne类 R
  定义体: by simpa using star_mul_self_nonneg (1 : R)

@[simp]

Depends on / 依赖: star_mul_self_nonneg
-/
instance : ZeroLEOneClass R where
  zero_le_one := by simpa using star_mul_self_nonneg (1 : R)

@[simp]
/--
lemma `one_le_star_iff` / 引理 `one_le_star_iff`

English:
lemma one_le_star_iff
  given: {x : R}
  statement: 1 <= star x ↔ 1 <= x
  proof: by
  simpa using star_le_star_iff (x := 1) (y := x)

@[simp]

中文:
引理 one_le_star_iff
  条件: {x : R}
  结论: 1 <= star x ↔ 1 <= x
  证明: by
  simpa using star_le_star_iff (x := 1) (y := x)

@[simp]

Depends on / 依赖: star_le_star_iff
-/
lemma one_le_star_iff {x : R} : 1 <= star x ↔ 1 <= x := by
  simpa using star_le_star_iff (x := 1) (y := x)

@[simp]
/--
lemma `star_le_one_iff` / 引理 `star_le_one_iff`

English:
lemma star_le_one_iff
  given: {x : R}
  statement: star x <= 1 ↔ x <= 1
  proof: by
  simpa using star_le_star_iff (x := x) (y := 1)

@[simp]

中文:
引理 star_le_one_iff
  条件: {x : R}
  结论: star x <= 1 ↔ x <= 1
  证明: by
  simpa using star_le_star_iff (x := x) (y := 1)

@[simp]

Depends on / 依赖: star_le_star_iff
-/
lemma star_le_one_iff {x : R} : star x <= 1 ↔ x <= 1 := by
  simpa using star_le_star_iff (x := x) (y := 1)

@[simp]
/--
lemma `one_lt_star_iff` / 引理 `one_lt_star_iff`

English:
lemma one_lt_star_iff
  given: {x : R}
  statement: 1 < star x ↔ 1 < x
  proof: by
  simpa using star_lt_star_iff (x := 1) (y := x)

@[simp]

中文:
引理 one_lt_star_iff
  条件: {x : R}
  结论: 1 < star x ↔ 1 < x
  证明: by
  simpa using star_lt_star_iff (x := 1) (y := x)

@[simp]

Depends on / 依赖: star_lt_star_iff
-/
lemma one_lt_star_iff {x : R} : 1 < star x ↔ 1 < x := by
  simpa using star_lt_star_iff (x := 1) (y := x)

@[simp]
/--
lemma `star_lt_one_iff` / 引理 `star_lt_one_iff`

English:
lemma star_lt_one_iff
  given: {x : R}
  statement: star x < 1 ↔ x < 1
  proof: by
  simpa using star_lt_star_iff (x := x) (y := 1)

@[aesop safe apply (rule_sets := [CStarAlgebra])]

中文:
引理 star_lt_one_iff
  条件: {x : R}
  结论: star x < 1 ↔ x < 1
  证明: by
  simpa using star_lt_star_iff (x := x) (y := 1)

@[aesop safe apply (rule_sets := [CStarAlgebra])]

Depends on / 依赖: star_lt_star_iff
-/
lemma star_lt_one_iff {x : R} : star x < 1 ↔ x < 1 := by
  simpa using star_lt_star_iff (x := x) (y := 1)

@[aesop safe apply (rule_sets := [CStarAlgebra])]
/--
theorem `IsSelfAdjoint.sq_nonneg` / 定理 `IsSelfAdjoint.sq_nonneg`

English:
theorem IsSelfAdjoint.sq_nonneg
  given: {a : R} (ha : IsSelfAdjoint a)
  statement: 0 <= a ^ 2
  proof: by
  simp [sq, ha.mul_self_nonneg]

中文:
定理 IsSelfAdjoint.sq_nonneg
  条件: {a : R} (ha : IsSelfAdjoint a)
  结论: 0 <= a ^ 2
  证明: by
  simp [sq, ha.mul_self_nonneg]
-/
protected theorem IsSelfAdjoint.sq_nonneg {a : R} (ha : IsSelfAdjoint a) : 0 <= a ^ 2 := by
  simp [sq, ha.mul_self_nonneg]

/--
lemma `IsUnit.star_right_conjugate_nonneg_iff` / 引理 `IsUnit.star_right_conjugate_nonneg_iff`

English:
lemma IsUnit.star_right_conjugate_nonneg_iff
  given: {u x : R} (hu : IsUnit u)
  proof: by
  refine ⟨fun h => ?_, fun h => star_right_conjugate_nonneg h _⟩
  obtain ⟨v, hv⟩ := hu.exists_left_inv
  have := by simpa [← mul_assoc] using star_right_conjugate_nonneg h v
  rwa [hv, one_mul, mul_assoc, ← star_mul, hv, star_one, mul_one] at this

中文:
引理 是单位.star_right_conjugate_nonneg_iff
  条件: {u x : R} (hu : 是单位 u)
  证明: by
  refine ⟨fun h => ?_, fun h => star_right_conjugate_nonneg h _⟩
  obtain ⟨v, hv⟩ := hu.exists_left_inv
  have := by simpa [← mul_assoc] using star_right_conjugate_nonneg h v
  rwa [hv, one_mul, mul_assoc, ← star_mul, hv, star_one, mul_one] at this

Depends on / 依赖: exists_left_inv, hu.exists_left_inv, mul_assoc, mul_one, one_mul, star_mul, star_one, star_right_conjugate_nonneg
-/
lemma IsUnit.star_right_conjugate_nonneg_iff {u x : R} (hu : IsUnit u) :
    0 <= u * x * star u ↔ 0 <= x := by
  refine ⟨fun h => ?_, fun h => star_right_conjugate_nonneg h _⟩
  obtain ⟨v, hv⟩ := hu.exists_left_inv
  have := by simpa [← mul_assoc] using star_right_conjugate_nonneg h v
  rwa [hv, one_mul, mul_assoc, ← star_mul, hv, star_one, mul_one] at this

/--
lemma `IsUnit.star_left_conjugate_nonneg_iff` / 引理 `IsUnit.star_left_conjugate_nonneg_iff`

English:
lemma IsUnit.star_left_conjugate_nonneg_iff
  given: {u x : R} (hu : IsUnit u)
  proof: by
  simpa using hu.star.star_right_conjugate_nonneg_iff

中文:
引理 是单位.star_left_conjugate_nonneg_iff
  条件: {u x : R} (hu : 是单位 u)
  证明: by
  simpa using hu.star.star_right_conjugate_nonneg_iff

Depends on / 依赖: hu.star.star_right_conjugate_nonneg_iff, star_right_conjugate_nonneg_iff
-/
lemma IsUnit.star_left_conjugate_nonneg_iff {u x : R} (hu : IsUnit u) :
    0 <= star u * x * u ↔ 0 <= x := by
  simpa using hu.star.star_right_conjugate_nonneg_iff

end Semiring

namespace MulOpposite

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [NonUnitalSemiring
  signature: R] [StarRing R] [PartialOrder R] [StarOrderedRing R] :
  body: by
    rw [← unop_le_unop]; rw [StarOrderedRing.le_iff]; rw [op_surjective.exists]; rw [← (AddSubmonoid.closure _).comap_map_eq_of_injective opAddEquiv.injective]
    congr! with p
    · simp [AddMonoidHom.map_mclosure, ← range_comp', Function.comp_def,
        ← (star_involutive.surjective.comp op_surjective).range_comp]
    · simp [← op_inj (α := R)]

中文:
实例 [非幺半环
  签名: R] [对合环 R] [偏序 R] [StarOrdered环 R] :
  定义体: by
    rw [← unop_le_unop]; rw [StarOrderedRing.le_iff]; rw [op_surjective.exists]; rw [← (AddSubmonoid.closure _).comap_map_eq_of_injective opAddEquiv.injective]
    congr! with p
    · simp [AddMonoidHom.map_mclosure, ← range_comp', Function.comp_def,
        ← (star_involutive.surjective.comp op_surjective).range_comp]
    · simp [← op_inj (α := R)]

Depends on / 依赖: AddMonoidHom, AddMonoidHom.map_mclosure, AddSubmonoid, AddSubmonoid.closure, Function, Function.comp_def, StarOrderedRing, StarOrderedRing.le_iff, closure, comap_map_eq_of_injective, comp_def, injective, le_iff, map_mclosure, opAddEquiv, opAddEquiv.injective, op_inj, op_surjective, op_surjective.exists, range_comp
-/
instance [NonUnitalSemiring R] [StarRing R] [PartialOrder R] [StarOrderedRing R] :
    StarOrderedRing Rᵐᵒᵖ where
  le_iff x y := by
    rw [← unop_le_unop]; rw [StarOrderedRing.le_iff]; rw [op_surjective.exists]; rw [← (AddSubmonoid.closure _).comap_map_eq_of_injective opAddEquiv.injective]
    congr! with p
    · simp [AddMonoidHom.map_mclosure, ← range_comp', Function.comp_def,
        ← (star_involutive.surjective.comp op_surjective).range_comp]
    · simp [← op_inj (α := R)]

end MulOpposite

section StarModule

variable [Semiring R] [PartialOrder R] [StarRing R] [StarOrderedRing R]
  [NonUnitalSemiring A] [StarRing A] [PartialOrder A] [StarOrderedRing A] [Module R A]
  [StarModule R A] [IsScalarTower R A A] [SMulCommClass R A A]

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: IsOrderedModule R A
  body: by
    rw [StarOrderedRing.nonneg_iff] at hr
    rw [StarOrderedRing.le_iff] at hab ⊢
    obtain ⟨a, ha, rfl⟩ := hab
    exact ⟨r • a, smul_mem_closure_star_mul hr ha, smul_add ..⟩
  smul_le_smul_of_nonneg_right a ha r s hrs := by
    rw [StarOrderedRing.nonneg_iff] at ha
    rw [StarOrderedRing.le_iff] at hrs ⊢
    obtain ⟨r, hr, rfl⟩ := hrs
    exact ⟨r • a, smul_mem_closure_star_mul hr ha, add_smul ..⟩

中文:
实例 :
  签名: 是Ordered模 R A
  定义体: by
    rw [StarOrderedRing.nonneg_iff] at hr
    rw [StarOrderedRing.le_iff] at hab ⊢
    obtain ⟨a, ha, rfl⟩ := hab
    exact ⟨r • a, smul_mem_closure_star_mul hr ha, smul_add ..⟩
  smul_le_smul_of_nonneg_right a ha r s hrs := by
    rw [StarOrderedRing.nonneg_iff] at ha
    rw [StarOrderedRing.le_iff] at hrs ⊢
    obtain ⟨r, hr, rfl⟩ := hrs
    exact ⟨r • a, smul_mem_closure_star_mul hr ha, add_smul ..⟩

Depends on / 依赖: StarOrderedRing, StarOrderedRing.le_iff, StarOrderedRing.nonneg_iff, add_smul, le_iff, nonneg_iff, smul_add, smul_le_smul_of_nonneg_right, smul_mem_closure_star_mul
-/
instance : IsOrderedModule R A where
  smul_le_smul_of_nonneg_left r hr a b hab := by
    rw [StarOrderedRing.nonneg_iff] at hr
    rw [StarOrderedRing.le_iff] at hab ⊢
    obtain ⟨a, ha, rfl⟩ := hab
    exact ⟨r • a, smul_mem_closure_star_mul hr ha, smul_add ..⟩
  smul_le_smul_of_nonneg_right a ha r s hrs := by
    rw [StarOrderedRing.nonneg_iff] at ha
    rw [StarOrderedRing.le_iff] at hrs ⊢
    obtain ⟨r, hr, rfl⟩ := hrs
    exact ⟨r • a, smul_mem_closure_star_mul hr ha, add_smul ..⟩

variable [IsDomain R] [IsCancelAdd A] [Module.IsTorsionFree R A]

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: PosSMulStrictMono R A
  body: by
    rw [StarOrderedRing.pos_iff] at hr
    rw [StarOrderedRing.lt_iff] at hab ⊢
    obtain ⟨a, ha₀, ha, rfl⟩ := hab
    obtain ⟨hr₀, hr⟩ := hr
    exact ⟨r • a, smul_ne_zero hr₀ ha₀, smul_mem_closure_star_mul hr ha, smul_add ..⟩

中文:
实例 :
  签名: 正标量乘严格递增 R A
  定义体: by
    rw [StarOrderedRing.pos_iff] at hr
    rw [StarOrderedRing.lt_iff] at hab ⊢
    obtain ⟨a, ha₀, ha, rfl⟩ := hab
    obtain ⟨hr₀, hr⟩ := hr
    exact ⟨r • a, smul_ne_zero hr₀ ha₀, smul_mem_closure_star_mul hr ha, smul_add ..⟩

Depends on / 依赖: StarOrderedRing, StarOrderedRing.lt_iff, StarOrderedRing.pos_iff, lt_iff, pos_iff, smul_add, smul_mem_closure_star_mul, smul_ne_zero
-/
instance : PosSMulStrictMono R A where
  smul_lt_smul_of_pos_left r hr a b hab := by
    rw [StarOrderedRing.pos_iff] at hr
    rw [StarOrderedRing.lt_iff] at hab ⊢
    obtain ⟨a, ha₀, ha, rfl⟩ := hab
    obtain ⟨hr₀, hr⟩ := hr
    exact ⟨r • a, smul_ne_zero hr₀ ha₀, smul_mem_closure_star_mul hr ha, smul_add ..⟩

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [IsCancelAdd
  signature: R] : IsStrictOrderedModule R A where
  body: by
    rw [StarOrderedRing.pos_iff] at ha
    rw [StarOrderedRing.lt_iff] at hrs ⊢
    obtain ⟨r, hr₀, hr, rfl⟩ := hrs
    obtain ⟨ha₀, ha⟩ := ha
    exact ⟨r • a, smul_ne_zero hr₀ ha₀, smul_mem_closure_star_mul hr ha, add_smul ..⟩

中文:
实例 [是消去加法
  签名: R] : 是StrictOrdered模 R A where
  定义体: by
    rw [StarOrderedRing.pos_iff] at ha
    rw [StarOrderedRing.lt_iff] at hrs ⊢
    obtain ⟨r, hr₀, hr, rfl⟩ := hrs
    obtain ⟨ha₀, ha⟩ := ha
    exact ⟨r • a, smul_ne_zero hr₀ ha₀, smul_mem_closure_star_mul hr ha, add_smul ..⟩
-/
instance [IsCancelAdd R] : IsStrictOrderedModule R A where
  smul_lt_smul_of_pos_right a ha r s hrs := by
    rw [StarOrderedRing.pos_iff] at ha
    rw [StarOrderedRing.lt_iff] at hrs ⊢
    obtain ⟨r, hr₀, hr, rfl⟩ := hrs
    obtain ⟨ha₀, ha⟩ := ha
    exact ⟨r • a, smul_ne_zero hr₀ ha₀, smul_mem_closure_star_mul hr ha, add_smul ..⟩

end StarModule

section OrderClass

variable {F R S : Type*} [NonUnitalSemiring R] [PartialOrder R] [StarRing R]
  [StarOrderedRing R]
variable [NonUnitalSemiring S] [PartialOrder S] [StarRing S] [StarOrderedRing S]

-- we prove this auxiliary lemma in order to avoid duplicating the proof twice below.
/--
lemma `NonUnitalStarRingHom.map_le_map_of_map_star` / 引理 `NonUnitalStarRingHom.map_le_map_of_map_star`

English:
lemma NonUnitalStarRingHom.map_le_map_of_map_star
  given: (f : R ->⋆ₙ+* S) {x y : R} (hxy : x <= y)
  proof: by
  rw [StarOrderedRing.le_iff] at hxy ⊢
  obtain ⟨p, hp, rfl⟩ := hxy
  refine ⟨f p, ?_, map_add f _ _⟩
  have hf : forall r, f (star r) = star (f r) := map_star _
  induction hp using AddSubmonoid.closure_induction
  all_goals aesop

中文:
引理 非幺对合环态射.map_le_map_of_map_star
  条件: (f : R ->⋆ₙ+* S) {x y : R} (hxy : x <= y)
  证明: by
  rw [StarOrderedRing.le_iff] at hxy ⊢
  obtain ⟨p, hp, rfl⟩ := hxy
  refine ⟨f p, ?_, map_add f _ _⟩
  have hf : forall r, f (star r) = star (f r) := map_star _
  induction hp using AddSubmonoid.closure_induction
  all_goals aesop

Depends on / 依赖: AddSubmonoid, AddSubmonoid.closure_induction, StarOrderedRing, StarOrderedRing.le_iff, all_goals, closure_induction, le_iff, map_add, map_star
-/
lemma NonUnitalStarRingHom.map_le_map_of_map_star (f : R ->⋆ₙ+* S) {x y : R} (hxy : x <= y) :
    f x <= f y := by
  rw [StarOrderedRing.le_iff] at hxy ⊢
  obtain ⟨p, hp, rfl⟩ := hxy
  refine ⟨f p, ?_, map_add f _ _⟩
  have hf : forall r, f (star r) = star (f r) := map_star _
  induction hp using AddSubmonoid.closure_induction
  all_goals aesop

instance (priority := 100) StarRingHomClass.instOrderHomClass [FunLike F R S]
    [NonUnitalRingHomClass F R S] [NonUnitalStarRingHomClass F R S] : OrderHomClass F R S where
  map_rel f := (f : R ->⋆ₙ+* S).map_le_map_of_map_star

instance (priority := 100) StarRingEquivClass.instOrderIsoClass [EquivLike F R S]
    [StarRingEquivClass F R S] : OrderIsoClass F R S where
  map_le_map_iff f x y := by
    refine ⟨fun h => ?_, map_rel f⟩
    let f_inv : S ->⋆ₙ+* R := (f : R ≃⋆+* S).symm
    have f_inv_f (r : R) : f_inv (f r) = r := EquivLike.inv_apply_apply f r
    rw [← f_inv_f x]; rw [← f_inv_f y]
    exact NonUnitalStarRingHom.map_le_map_of_map_star f_inv h

/-- While `IsSelfAdjoint.map` assumes the map is star-preserving, this lemma instead assumes the
map is an order-preserving additive map from a space where self-adjoint elements can be expressed as
differences of nonnegative elements, and whose codomain is a star-ordered ring. When such maps are
linear over `ℂ`, they are also star-preserving, and this lemma is used to establish that one by
splitting into real and imaginary parts. -/
@[aesop safe apply (rule_sets := [CStarAlgebra])]
/--
lemma `IsSelfAdjoint.map'` / 引理 `IsSelfAdjoint.map'`

English:
lemma IsSelfAdjoint.map'
  statement: {F E R : Type*} [AddCommGroup E] [PartialOrder E] [StarAddMonoid E]
  proof: by
  obtain ⟨b, c, hb, hc, rfl⟩ := ha.exists_nonneg_sub_nonneg
  have h₁ := OrderHomClass.mono f hb
  have h₂ := OrderHomClass.mono f hc
  cfc_tac

@[deprecated (since := "2026-06-12")] alias map_isSelfAdjoint := IsSelfAdjoint.map'

中文:
引理 IsSelfAdjoint.map'
  结论: {F E R : 类型} [加法交换群 E] [偏序 E] [StarAdd幺半群 E]
  证明: by
  obtain ⟨b, c, hb, hc, rfl⟩ := ha.exists_nonneg_sub_nonneg
  have h₁ := OrderHomClass.mono f hb
  have h₂ := OrderHomClass.mono f hc
  cfc_tac

@[deprecated (since := "2026-06-12")] alias map_isSelfAdjoint := IsSelfAdjoint.map'

Depends on / 依赖: OrderHomClass, OrderHomClass.mono, cfc_tac, exists_nonneg_sub_nonneg, ha.exists_nonneg_sub_nonneg
-/
lemma IsSelfAdjoint.map' {F E R : Type*} [AddCommGroup E] [PartialOrder E] [StarAddMonoid E]
    [NonUnitalRing R] [PartialOrder R] [StarRing R] [StarOrderedRing R]
    [SelfAdjointDecompose E] [FunLike F E R] [OrderHomClass F E R] [AddMonoidHomClass F E R]
    {a : E} (ha : IsSelfAdjoint a) (f : F) :
    IsSelfAdjoint (f a) := by
  obtain ⟨b, c, hb, hc, rfl⟩ := ha.exists_nonneg_sub_nonneg
  have h₁ := OrderHomClass.mono f hb
  have h₂ := OrderHomClass.mono f hc
  cfc_tac

@[deprecated (since := "2026-06-12")] alias map_isSelfAdjoint := IsSelfAdjoint.map'

end OrderClass

/--
Instance `Nat.instStarOrderedRing` / 实例 `Nat.instStarOrderedRing`

English:
instance Nat.instStarOrderedRing
  signature: : StarOrderedRing Nat where
  body: by
    have : AddSubmonoid.closure (range fun x : Nat => x * x) = ⊤ :=
      eq_top_mono
        (AddSubmonoid.closure_mono <| singleton_subset_iff.2 <| mem_range.2 ⟨1, one_mul _⟩)
        Nat.addSubmonoidClosure_one
    simp [this, le_iff_exists_add]

中文:
实例 自然数.instStarOrderedRing
  签名: : StarOrdered环 自然数 where
  定义体: by
    have : AddSubmonoid.closure (range fun x : Nat => x * x) = ⊤ :=
      eq_top_mono
        (AddSubmonoid.closure_mono <| singleton_subset_iff.2 <| mem_range.2 ⟨1, one_mul _⟩)
        Nat.addSubmonoidClosure_one
    simp [this, le_iff_exists_add]

Depends on / 依赖: AddSubmonoid, AddSubmonoid.closure, AddSubmonoid.closure_mono, Nat.addSubmonoidClosure_one, addSubmonoidClosure_one, closure, closure_mono, eq_top_mono, le_iff_exists_add, mem_range, one_mul, singleton_subset_iff
-/
instance Nat.instStarOrderedRing : StarOrderedRing Nat where
  le_iff a b := by
    have : AddSubmonoid.closure (range fun x : Nat => x * x) = ⊤ :=
      eq_top_mono
        (AddSubmonoid.closure_mono <| singleton_subset_iff.2 <| mem_range.2 ⟨1, one_mul _⟩)
        Nat.addSubmonoidClosure_one
    simp [this, le_iff_exists_add]

namespace IsStarProjection

section Ring
variable [Ring R] [PartialOrder R] [StarRing R] [StarOrderedRing R] {p : R}

/--
theorem `one_sub_nonneg` / 定理 `one_sub_nonneg`

English:
theorem one_sub_nonneg
  given: (hp : IsStarProjection p)
  statement: 0 <= 1 - p
  proof: hp.one_sub.nonneg

中文:
定理 one_sub_nonneg
  条件: (hp : 是StarProjection p)
  结论: 0 <= 1 - p
  证明: hp.one_sub.nonneg

Depends on / 依赖: hp.one_sub.nonneg, nonneg, one_sub
-/
theorem one_sub_nonneg (hp : IsStarProjection p) : 0 <= 1 - p := hp.one_sub.nonneg

/--
theorem `le_one` / 定理 `le_one`

English:
theorem le_one
  given: (hp : IsStarProjection p)
  statement: p <= 1
  proof: sub_nonneg.mp hp.one_sub_nonneg

中文:
定理 le_one
  条件: (hp : 是StarProjection p)
  结论: p <= 1
  证明: sub_nonneg.mp hp.one_sub_nonneg

Depends on / 依赖: hp.one_sub_nonneg, one_sub_nonneg, sub_nonneg, sub_nonneg.mp
-/
theorem le_one (hp : IsStarProjection p) : p <= 1 := sub_nonneg.mp hp.one_sub_nonneg

/--
theorem `mem_Icc` / 定理 `mem_Icc`

English:
theorem mem_Icc
  given: (hp : IsStarProjection p)
  statement: p in Set.Icc (0 : R) 1
  proof: by
  simp only [Set.mem_Icc, hp.nonneg, hp.le_one, and_self]

中文:
定理 mem_Icc
  条件: (hp : 是StarProjection p)
  结论: p in 集合.闭区间 (0 : R) 1
  证明: by
  simp only [Set.mem_Icc, hp.nonneg, hp.le_one, and_self]

Depends on / 依赖: Set.mem_Icc, and_self, hp.le_one, hp.nonneg, le_one, mem_Icc, nonneg
-/
theorem mem_Icc (hp : IsStarProjection p) : p in Set.Icc (0 : R) 1 := by
  simp only [Set.mem_Icc, hp.nonneg, hp.le_one, and_self]

end Ring

section NonUnitalRing
variable [NonUnitalRing R] [PartialOrder R] [StarRing R] [StarOrderedRing R] {p q : R}

/--
theorem `le_of_mul_eq_left` / 定理 `le_of_mul_eq_left`

English:
theorem le_of_mul_eq_left
  statement: (hp : IsStarProjection p) (hq : IsStarProjection q)
  proof: sub_nonneg.mp (hp.sub_of_mul_eq_left hq hpq).nonneg

中文:
定理 le_of_mul_eq_left
  结论: (hp : 是StarProjection p) (hq : 是StarProjection q)
  证明: sub_nonneg.mp (hp.sub_of_mul_eq_left hq hpq).nonneg

Depends on / 依赖: hp.sub_of_mul_eq_left, nonneg, sub_nonneg, sub_nonneg.mp, sub_of_mul_eq_left
-/
theorem le_of_mul_eq_left (hp : IsStarProjection p) (hq : IsStarProjection q)
    (hpq : p * q = p) : p <= q := sub_nonneg.mp (hp.sub_of_mul_eq_left hq hpq).nonneg

/--
theorem `le_of_mul_eq_right` / 定理 `le_of_mul_eq_right`

English:
theorem le_of_mul_eq_right
  statement: (hp : IsStarProjection p) (hq : IsStarProjection q)
  proof: sub_nonneg.mp (hp.sub_of_mul_eq_right hq hpq).nonneg

中文:
定理 le_of_mul_eq_right
  结论: (hp : 是StarProjection p) (hq : 是StarProjection q)
  证明: sub_nonneg.mp (hp.sub_of_mul_eq_right hq hpq).nonneg

Depends on / 依赖: hp.sub_of_mul_eq_right, nonneg, sub_nonneg, sub_nonneg.mp, sub_of_mul_eq_right
-/
theorem le_of_mul_eq_right (hp : IsStarProjection p) (hq : IsStarProjection q)
    (hpq : q * p = p) : p <= q := sub_nonneg.mp (hp.sub_of_mul_eq_right hq hpq).nonneg

instance {R : Type*} [NonUnitalRing R] [LinearOrder R] [StarRing R] [StarOrderedRing R] :
    TrivialStar R where
  star_trivial r := by
    obtain (hr | hr) : 0 <= r ∨ 0 <= -r := by grind
    · exact hr.star_eq
    · simpa using hr.star_eq

end NonUnitalRing

end IsStarProjection
