/-
Copyright (c) 2017 Johannes Hölzl. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Johannes Hölzl, Mario Carneiro, Yury Kudryashov
-/
module

public import Mathlib.Order.Filter.Interval
public import Mathlib.Order.Interval.Set.Pi
public import Mathlib.Order.OrdContinuous
public import Mathlib.Tactic.TFAE
public import Mathlib.Tactic.NormNum
public import Mathlib.Topology.Order.LeftRight
public import Mathlib.Topology.Order.OrderClosed

/-!
# Theory of topology on ordered spaces

## Main definitions

The order topology on an ordered space is the topology generated by all open intervals (or
equivalently by those of the form `(-∞, a)` and `(b, +∞)`). We define it as `Preorder.topology α`.
However, we do *not* register it as an instance (as many existing ordered types already have
topologies, which would be equal but not definitionally equal to `Preorder.topology α`). Instead,
we introduce a class `OrderTopology α` (which is a `Prop`, also known as a mixin) saying that on
the type `α` having already a topological space structure and a preorder structure, the topological
structure is equal to the order topology.

We prove many basic properties of such topologies.

## Main statements

This file contains the proofs of the following facts. For exact requirements
(`OrderClosedTopology` vs `OrderTopology`, `Preorder` vs `PartialOrder` vs `LinearOrder` etc)
see their statements.

* `exists_Ioc_subset_of_mem_nhds`, `exists_Ico_subset_of_mem_nhds` : if `x < y`, then any
  neighborhood of `x` includes an interval `[x, z)` for some `z ∈ (x, y]`, and any neighborhood
  of `y` includes an interval `(z, y]` for some `z ∈ [x, y)`.
* `tendsto_of_tendsto_of_tendsto_of_le_of_le` : theorem known as squeeze theorem,
  sandwich theorem, theorem of Carabinieri, and two policemen (and a drunk) theorem; if `g` and `h`
  both converge to `a`, and eventually `g x ≤ f x ≤ h x`, then `f` converges to `a`.

## Implementation notes

We do _not_ register the order topology as an instance on a preorder (or even on a linear order).
Indeed, on many such spaces, a topology has already been constructed in a different way (think
of the discrete spaces `ℕ` or `ℤ`, or `ℝ` that could inherit a topology as the completion of `ℚ`),
and is in general not defeq to the one generated by the intervals. We make it available as a
definition `Preorder.topology α` though, that can be registered as an instance when necessary, or
for specific types.
-/

@[expose] public section


open Set Filter TopologicalSpace Topology Function

open OrderDual (toDual ofDual)

universe u v w

variable {α : Type u} {β : Type v} {γ : Type w}

/-- (Order) topology on a partial order `α` generated by the subbase of open intervals
`(a, ∞) = { x ∣ a < x }, (-∞, b) = {x ∣ x < b}` for all `a, b` in `α`. We do not register it as an
instance as many ordered sets are already endowed with the same topology, most often in a non-defeq
way though. Register as a local instance when necessary. -/
@[instance_reducible]
/--
Definition of `Preorder.topology` / `Preorder.topology` 的定义

English:
definition Preorder.topology
  signature: (α : Type*) [Preorder α]
  body: generateFrom { s | exists a, s = Ioi a ∨ s = Iio a }

to_dual_insert_cast Preorder.topology := by simp_rw [or_comm]

中文:
定义 预序.topology
  签名: (α : 类型) [预序 α]
  定义体: generateFrom { s | exists a, s = Ioi a ∨ s = Iio a }

to_dual_insert_cast Preorder.topology := by simp_rw [or_comm]

Depends on / 依赖: generateFrom
-/
def Preorder.topology (α : Type*) [Preorder α] : TopologicalSpace α :=
  generateFrom { s | exists a, s = Ioi a ∨ s = Iio a }

to_dual_insert_cast Preorder.topology := by simp_rw [or_comm]

/--
Definition of `OrderTopology` / `OrderTopology` 的定义

English:
class OrderTopology
  parameters: (α : Type*) [t : TopologicalSpace α] [Preorder α]
  axioms and operations (1):
    - topology_eq_generate_intervals : t = Preorder.topology α

中文:
类 Order拓扑
  参数: (α : 类型) [t : 拓扑空间 α] [预序 α]
  公理与运算 (1 个):
    - topology_eq_generate_intervals : t = 预序.topology α
-/
class OrderTopology (α : Type*) [t : TopologicalSpace α] [Preorder α] : Prop where
  /-- The topology is generated by open intervals `Set.Ioi _` and `Set.Iio _`. -/
  topology_eq_generate_intervals : t = Preorder.topology α

section Preorder

variable [ts : TopologicalSpace α] [Preorder α]

/-- A countable preordered set equipped with the order topology is second countable. -/
instance (priority := 100) [OrderTopology α] [Countable α] :
    SecondCountableTopology α := by
  refine ⟨{ s : Set α | exists a, s = Ioi a ∨ s = Iio a }, ?_, ?_⟩
  · let f1 : α -> Set α := fun a => Ioi a
    let f2 : α -> Set α := fun a => Iio a
    exact Countable.mono (fun s hs => by grind) ((countable_range f1).union (countable_range f2))
  · exact OrderTopology.topology_eq_generate_intervals

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [t
  signature: : OrderTopology α] : OrderTopology αᵒᵈ
  body: by
  constructor
  rcases t.topology_eq_generate_intervals with rfl
  simp_rw [Preorder.topology, or_comm]
  rfl

@[to_dual none]

中文:
实例 [t
  签名: : Order拓扑 α] : Order拓扑 αᵒᵈ
  定义体: by
  constructor
  rcases t.topology_eq_generate_intervals with rfl
  simp_rw [Preorder.topology, or_comm]
  rfl

@[to_dual none]

Depends on / 依赖: Preorder, Preorder.topology, or_comm, simp_rw, t.topology_eq_generate_intervals, topology, topology_eq_generate_intervals
-/
instance [t : OrderTopology α] : OrderTopology αᵒᵈ := by
  constructor
  rcases t.topology_eq_generate_intervals with rfl
  simp_rw [Preorder.topology, or_comm]
  rfl

@[to_dual none]
/--
theorem `OrderTopology.continuous_iff` / 定理 `OrderTopology.continuous_iff`

English:
theorem OrderTopology.continuous_iff
  given: [OrderTopology α] [TopologicalSpace β] {f : β -> α}
  proof: by
  simp_rw +instances [OrderTopology.topology_eq_generate_intervals, continuous_generateFrom_iff]
  aesop

@[to_dual none]

中文:
定理 Order拓扑.continuous_iff
  条件: [Order拓扑 α] [拓扑空间 β] {f : β -> α}
  证明: by
  simp_rw +instances [OrderTopology.topology_eq_generate_intervals, continuous_generateFrom_iff]
  aesop

@[to_dual none]
-/
protected theorem OrderTopology.continuous_iff [OrderTopology α] [TopologicalSpace β] {f : β -> α} :
    Continuous f ↔ forall a, IsOpen (f ⁻¹' Ioi a) ∧ IsOpen (f ⁻¹' Iio a) := by
  simp_rw +instances [OrderTopology.topology_eq_generate_intervals, continuous_generateFrom_iff]
  aesop

@[to_dual none]
/--
theorem `isOpen_iff_generate_intervals` / 定理 `isOpen_iff_generate_intervals`

English:
theorem isOpen_iff_generate_intervals
  given: [t : OrderTopology α] {s : Set α}
  proof: by
  rw [t.topology_eq_generate_intervals]; rfl

@[to_dual isOpen_gt']

中文:
定理 isOpen_iff_generate_intervals
  条件: [t : Order拓扑 α] {s : 集合 α}
  证明: by
  rw [t.topology_eq_generate_intervals]; rfl

@[to_dual isOpen_gt']

Depends on / 依赖: t.topology_eq_generate_intervals, topology_eq_generate_intervals
-/
theorem isOpen_iff_generate_intervals [t : OrderTopology α] {s : Set α} :
    IsOpen s ↔ GenerateOpen { s | exists a, s = Ioi a ∨ s = Iio a } s := by
  rw [t.topology_eq_generate_intervals]; rfl

@[to_dual isOpen_gt']
/--
theorem `isOpen_lt'` / 定理 `isOpen_lt'`

English:
theorem isOpen_lt'
  given: [OrderTopology α] (a : α)
  statement: IsOpen { b : α | a < b }
  proof: isOpen_iff_generate_intervals.2 .basic _ ⟨a, .inl rfl⟩

中文:
定理 isOpen_lt'
  条件: [Order拓扑 α] (a : α)
  结论: 是开集 { b : α | a < b }
  证明: isOpen_iff_generate_intervals.2 .basic _ ⟨a, .inl rfl⟩

Depends on / 依赖: isOpen_iff_generate_intervals
-/
theorem isOpen_lt' [OrderTopology α] (a : α) : IsOpen { b : α | a < b } :=
isOpen_iff_generate_intervals.2 .basic _ ⟨a, .inl rfl⟩

/-- A version of `isOpen_Ioi` that doesn't require a `LinearOrder`. -/
@[to_dual /-- A version of `isOpen_Iio` that doesn't require a `LinearOrder`. -/]
/--
theorem `isOpen_Ioi'` / 定理 `isOpen_Ioi'`

English:
theorem isOpen_Ioi'
  given: [OrderTopology α] (a : α)
  statement: IsOpen (Ioi a)
  proof: isOpen_lt' a

中文:
定理 isOpen_Ioi'
  条件: [Order拓扑 α] (a : α)
  结论: 是开集 (左开右无界区间 a)
  证明: isOpen_lt' a

Depends on / 依赖: isOpen_lt
-/
theorem isOpen_Ioi' [OrderTopology α] (a : α) : IsOpen (Ioi a) := isOpen_lt' a

/-- A version of `isOpen_Ioo` that doesn't require a `LinearOrder`. -/
@[to_dual self]
/--
theorem `isOpen_Ioo'` / 定理 `isOpen_Ioo'`

English:
theorem isOpen_Ioo'
  given: [OrderTopology α] (a b : α)
  statement: IsOpen (Ioo a b)
  proof: (isOpen_Ioi' a).inter (isOpen_Iio' b)

@[to_dual gt_mem_nhds]

中文:
定理 isOpen_Ioo'
  条件: [Order拓扑 α] (a b : α)
  结论: 是开集 (开区间 a b)
  证明: (isOpen_Ioi' a).inter (isOpen_Iio' b)

@[to_dual gt_mem_nhds]

Depends on / 依赖: isOpen_Iio, isOpen_Ioi
-/
theorem isOpen_Ioo' [OrderTopology α] (a b : α) : IsOpen (Ioo a b) :=
  (isOpen_Ioi' a).inter (isOpen_Iio' b)

@[to_dual gt_mem_nhds]
/--
theorem `lt_mem_nhds` / 定理 `lt_mem_nhds`

English:
theorem lt_mem_nhds
  given: [OrderTopology α] {a b : α} (h : a < b)
  statement: forallᶠ x in 𝓝 b, a < x
  proof: (isOpen_lt' _).mem_nhds h

@[to_dual ge_mem_nhds]

中文:
定理 lt_mem_nhds
  条件: [Order拓扑 α] {a b : α} (h : a < b)
  结论: 对任意ᶠ x in 𝓝 b, a < x
  证明: (isOpen_lt' _).mem_nhds h

@[to_dual ge_mem_nhds]

Depends on / 依赖: isOpen_lt, mem_nhds
-/
theorem lt_mem_nhds [OrderTopology α] {a b : α} (h : a < b) : forallᶠ x in 𝓝 b, a < x :=
  (isOpen_lt' _).mem_nhds h

@[to_dual ge_mem_nhds]
/--
theorem `le_mem_nhds` / 定理 `le_mem_nhds`

English:
theorem le_mem_nhds
  given: [OrderTopology α] {a b : α} (h : a < b)
  statement: forallᶠ x in 𝓝 b, a <= x
  proof: (lt_mem_nhds h).mono fun _ => le_of_lt

@[to_dual none]

中文:
定理 le_mem_nhds
  条件: [Order拓扑 α] {a b : α} (h : a < b)
  结论: 对任意ᶠ x in 𝓝 b, a <= x
  证明: (lt_mem_nhds h).mono fun _ => le_of_lt

@[to_dual none]

Depends on / 依赖: le_of_lt, lt_mem_nhds
-/
theorem le_mem_nhds [OrderTopology α] {a b : α} (h : a < b) : forallᶠ x in 𝓝 b, a <= x :=
  (lt_mem_nhds h).mono fun _ => le_of_lt

@[to_dual none]
/--
theorem `nhds_eq_order` / 定理 `nhds_eq_order`

English:
theorem nhds_eq_order
  given: [OrderTopology α] (a : α)
  proof: by
  rw [OrderTopology.topology_eq_generate_intervals (α := α)]; rw [nhds_generateFrom]
  simp_rw [mem_ofPred_eq, @and_comm (a in _), exists_or, or_and_right, iInf_or, iInf_and,
    iInf_exists, iInf_inf_eq, iInf_comm (ι := Set α), iInf_iInf_eq_left, mem_Ioi, mem_Iio]

@[to_dual none]

中文:
定理 nhds_eq_order
  条件: [Order拓扑 α] (a : α)
  证明: by
  rw [OrderTopology.topology_eq_generate_intervals (α := α)]; rw [nhds_generateFrom]
  simp_rw [mem_ofPred_eq, @and_comm (a in _), exists_or, or_and_right, iInf_or, iInf_and,
    iInf_exists, iInf_inf_eq, iInf_comm (ι := Set α), iInf_iInf_eq_left, mem_Ioi, mem_Iio]

@[to_dual none]

Depends on / 依赖: OrderTopology, OrderTopology.topology_eq_generate_intervals, and_comm, exists_or, iInf_and, iInf_comm, iInf_exists, iInf_iInf_eq_left, iInf_inf_eq, iInf_or, mem_Iio, mem_Ioi, mem_ofPred_eq, nhds_generateFrom, or_and_right, simp_rw, topology_eq_generate_intervals
-/
theorem nhds_eq_order [OrderTopology α] (a : α) :
    𝓝 a = (⨅ b in Iio a, 𝓟 (Ioi b)) ⊓ ⨅ b in Ioi a, 𝓟 (Iio b) := by
  rw [OrderTopology.topology_eq_generate_intervals (α := α)]; rw [nhds_generateFrom]
  simp_rw [mem_ofPred_eq, @and_comm (a in _), exists_or, or_and_right, iInf_or, iInf_and,
    iInf_exists, iInf_inf_eq, iInf_comm (ι := Set α), iInf_iInf_eq_left, mem_Ioi, mem_Iio]

@[to_dual none]
/--
theorem `tendsto_order` / 定理 `tendsto_order`

English:
theorem tendsto_order
  given: [OrderTopology α] {f : β -> α} {a : α} {x : Filter β}
  proof: by
  simp only [nhds_eq_order a, tendsto_inf, tendsto_iInf, tendsto_principal]; rfl

中文:
定理 tendsto_order
  条件: [Order拓扑 α] {f : β -> α} {a : α} {x : 滤子 β}
  证明: by
  simp only [nhds_eq_order a, tendsto_inf, tendsto_iInf, tendsto_principal]; rfl

Depends on / 依赖: nhds_eq_order, tendsto_iInf, tendsto_inf, tendsto_principal
-/
theorem tendsto_order [OrderTopology α] {f : β -> α} {a : α} {x : Filter β} :
    Tendsto f x (𝓝 a) ↔ (forall a' < a, forallᶠ b in x, a' < f b) ∧ forall a' > a, forallᶠ b in x, f b < a' := by
  simp only [nhds_eq_order a, tendsto_inf, tendsto_iInf, tendsto_principal]; rfl
/--
Instance `tendstoIccClassNhds` / 实例 `tendstoIccClassNhds`

English:
instance tendstoIccClassNhds
  signature: [OrderTopology α] (a : α)
  body: by
  simp only [nhds_eq_order, iInf_subtype']
  refine
    ((hasBasis_iInf_principal_finite _).inf (hasBasis_iInf_principal_finite _)).tendstoIxxClass
      fun s _ => ?_
  refine ((ordConnected_biInter ?_).inter (ordConnected_biInter ?_)).out <;> intro _ _
  exacts [ordConnected_Ioi, ordConnected_I

中文:
实例 tendstoIccClassNhds
  签名: [Order拓扑 α] (a : α)
  定义体: by
  simp only [nhds_eq_order, iInf_subtype']
  refine
    ((hasBasis_iInf_principal_finite _).inf (hasBasis_iInf_principal_finite _)).tendstoIxxClass
      fun s _ => ?_
  refine ((ordConnected_biInter ?_).inter (ordConnected_biInter ?_)).out <;> intro _ _
  exacts [ordConnected_Ioi, ordConnected_I

Depends on / 依赖: exacts, hasBasis_iInf_principal_finite, iInf_subtype, nhds_eq_order, ordConnected_Iio, ordConnected_Ioi, ordConnected_biInter, tendstoIxxClass
-/
instance tendstoIccClassNhds [OrderTopology α] (a : α) : TendstoIxxClass Icc (𝓝 a) (𝓝 a) := by
  simp only [nhds_eq_order, iInf_subtype']
  refine
    ((hasBasis_iInf_principal_finite _).inf (hasBasis_iInf_principal_finite _)).tendstoIxxClass
      fun s _ => ?_
  refine ((ordConnected_biInter ?_).inter (ordConnected_biInter ?_)).out <;> intro _ _
  exacts [ordConnected_Ioi, ordConnected_Iio]

/--
Instance `tendstoIcoClassNhds` / 实例 `tendstoIcoClassNhds`

English:
instance tendstoIcoClassNhds
  signature: [OrderTopology α] (a : α)
  body: tendstoIxxClass_of_subset fun _ _ => Ico_subset_Icc_self

中文:
实例 tendstoIcoClassNhds
  签名: [Order拓扑 α] (a : α)
  定义体: tendstoIxxClass_of_subset fun _ _ => Ico_subset_Icc_self

Depends on / 依赖: Ico_subset_Icc_self, tendstoIxxClass_of_subset
-/
instance tendstoIcoClassNhds [OrderTopology α] (a : α) : TendstoIxxClass Ico (𝓝 a) (𝓝 a) :=
  tendstoIxxClass_of_subset fun _ _ => Ico_subset_Icc_self

/--
Instance `tendstoIocClassNhds` / 实例 `tendstoIocClassNhds`

English:
instance tendstoIocClassNhds
  signature: [OrderTopology α] (a : α)
  body: tendstoIxxClass_of_subset fun _ _ => Ioc_subset_Icc_self

中文:
实例 tendstoIocClassNhds
  签名: [Order拓扑 α] (a : α)
  定义体: tendstoIxxClass_of_subset fun _ _ => Ioc_subset_Icc_self

Depends on / 依赖: Ioc_subset_Icc_self, tendstoIxxClass_of_subset
-/
instance tendstoIocClassNhds [OrderTopology α] (a : α) : TendstoIxxClass Ioc (𝓝 a) (𝓝 a) :=
  tendstoIxxClass_of_subset fun _ _ => Ioc_subset_Icc_self

/--
Instance `tendstoIooClassNhds` / 实例 `tendstoIooClassNhds`

English:
instance tendstoIooClassNhds
  signature: [OrderTopology α] (a : α)
  body: tendstoIxxClass_of_subset fun _ _ => Ioo_subset_Icc_self

中文:
实例 tendstoIooClassNhds
  签名: [Order拓扑 α] (a : α)
  定义体: tendstoIxxClass_of_subset fun _ _ => Ioo_subset_Icc_self

Depends on / 依赖: Ioo_subset_Icc_self, tendstoIxxClass_of_subset
-/
instance tendstoIooClassNhds [OrderTopology α] (a : α) : TendstoIxxClass Ioo (𝓝 a) (𝓝 a) :=
  tendstoIxxClass_of_subset fun _ _ => Ioo_subset_Icc_self

variable (α) in
/--
lemma `exists_countable_generateFrom_Ioi_Iio` / 引理 `exists_countable_generateFrom_Ioi_Iio`

English:
lemma exists_countable_generateFrom_Ioi_Iio
  proof: by
  rcases isEmpty_or_nonempty α with hα | hα
  · exact ⟨∅, by simp, Subsingleton.elim _ _⟩
  obtain ⟨t, t_subs, t_count, ht⟩ : exists t subseteq { s | exists a, s = Ioi a ∨ s = Iio a },
      t.Countable ∧ ts = generateFrom t :=
    exists_countable_of_generateFrom OrderTopology.topology_eq_genera

中文:
引理 存在_countable_generateFrom_Ioi_Iio
  证明: by
  rcases isEmpty_or_nonempty α with hα | hα
  · exact ⟨∅, by simp, Subsingleton.elim _ _⟩
  obtain ⟨t, t_subs, t_count, ht⟩ : exists t subseteq { s | exists a, s = Ioi a ∨ s = Iio a },
      t.Countable ∧ ts = generateFrom t :=
    exists_countable_of_generateFrom OrderTopology.topology_eq_genera

Depends on / 依赖: Countable, OrderTopology, OrderTopology.topology_eq_generate_intervals, Subsingleton, Subsingleton.elim, exists_countable_of_generateFrom, generateFrom, isEmpty_or_nonempty, le_antisymm, le_generateFrom_iff_subset_isOpen, mem_im, subseteq, t.Countable, t_count, t_count.image, t_subs, topology_eq_generate_intervals
-/
lemma exists_countable_generateFrom_Ioi_Iio
    [OrderTopology α] [SecondCountableTopology α] :
    exists (c : Set α), c.Countable ∧ ts = generateFrom { s | exists a in c, s = Ioi a ∨ s = Iio a } := by
  rcases isEmpty_or_nonempty α with hα | hα
  · exact ⟨∅, by simp, Subsingleton.elim _ _⟩
  obtain ⟨t, t_subs, t_count, ht⟩ : exists t subseteq { s | exists a, s = Ioi a ∨ s = Iio a },
      t.Countable ∧ ts = generateFrom t :=
    exists_countable_of_generateFrom OrderTopology.topology_eq_generate_intervals
  have A : forall s in t, exists a, s = Ioi a ∨ s = Iio a := t_subs
  choose! a ha using A
  refine ⟨a '' t, t_count.image _, ?_⟩
  apply le_antisymm
  · apply le_generateFrom_iff_subset_isOpen.2
    simp only [mem_image, exists_exists_and_eq_and, ofPred_subset_ofPred, forall_exists_index,
      and_imp]
    grind [isOpen_Iio', isOpen_Ioi']
  · rw [ht]
    apply generateFrom_anti
    grind

/-- If a topology is generated by half-open intervals with endpoints in a set `c`, then the sets
formed by intersecting finitely many of these intervals form a topological basis. -/
@[to_dual none]
/--
lemma `isTopologicalBasis_biInter_Ioi_Iio_of_generateFrom` / 引理 `isTopologicalBasis_biInter_Ioi_Iio_of_generateFrom`

English:
lemma isTopologicalBasis_biInter_Ioi_Iio_of_generateFrom
  statement: (c : Set α)
  proof: by
  refine IsTopologicalBasis.of_isOpen_of_subset ?_ (isTopologicalBasis_of_subbasis h) ?_
  · rintro u ⟨f, g, hfc, hgc, hf_fin, hg_fin, rfl⟩
    apply IsOpen.inter
    · apply hf_fin.isOpen_biInter (fun i hi => ?_)
      rw [h]
      exact isOpen_generateFrom_of_mem ⟨i, hfc hi, Or.inl rfl⟩
    · a

中文:
引理 isTopologicalBasis_bi整数er_Ioi_Iio_of_generateFrom
  结论: (c : 集合 α)
  证明: by
  refine IsTopologicalBasis.of_isOpen_of_subset ?_ (isTopologicalBasis_of_subbasis h) ?_
  · rintro u ⟨f, g, hfc, hgc, hf_fin, hg_fin, rfl⟩
    apply IsOpen.inter
    · apply hf_fin.isOpen_biInter (fun i hi => ?_)
      rw [h]
      exact isOpen_generateFrom_of_mem ⟨i, hfc hi, Or.inl rfl⟩
    · a

Depends on / 依赖: IsOpen, IsOpen.inter, IsTopologicalBasis, IsTopologicalBasis.of_isOpen_of_subset, Or.inl, Or.inr, and_imp, exists_and_left, hf_fin, hf_fin.isOpen_biInter, hg_fin, hg_fin.isOpen_biInter, image_subset_iff, isOpen_biInter, isOpen_generateFrom_of_mem, isTopologicalBasis_of_subbasis, k_fin, ofPred_subset_ofPred, of_isOpen_of_subset, preimage_ofPred_eq
-/
lemma isTopologicalBasis_biInter_Ioi_Iio_of_generateFrom (c : Set α)
    (h : ts = generateFrom { s | exists a in c, s = Ioi a ∨ s = Iio a }) :
    IsTopologicalBasis {s | exists (f g : Set α), f subseteq c ∧ g subseteq c ∧ f.Finite ∧ g.Finite
      ∧ s = (⋂ a in f, Ioi a) inter (⋂ a in g, Iio a)} := by
  refine IsTopologicalBasis.of_isOpen_of_subset ?_ (isTopologicalBasis_of_subbasis h) ?_
  · rintro u ⟨f, g, hfc, hgc, hf_fin, hg_fin, rfl⟩
    apply IsOpen.inter
    · apply hf_fin.isOpen_biInter (fun i hi => ?_)
      rw [h]
      exact isOpen_generateFrom_of_mem ⟨i, hfc hi, Or.inl rfl⟩
    · apply hg_fin.isOpen_biInter (fun i hi => ?_)
      rw [h]
      exact isOpen_generateFrom_of_mem ⟨i, hgc hi, Or.inr rfl⟩
  simp only [exists_and_left, image_subset_iff, preimage_ofPred_eq, ofPred_subset_ofPred, and_imp]
  intro k k_fin hk
  let kl := {s in k | exists a in c, s = Ioi a}
  let kr := {s in k | exists a in c, s = Iio a}
  have k_eq : k = kl union kr := by
    -- this `have` can be removed, but makes `grind` slower
    have : forall s in k, exists a in c, s = Ioi a ∨ s = Iio a := hk
    ext
    grind
  have : Finite kl := k_fin.subset (by simp [k_eq])
  have : Finite kr := k_fin.subset (by simp [k_eq])
  have Al : forall s : kl, exists a in c, s = Ioi a := fun s => s.2.2
  choose al alc hal using Al
  have Ar : forall s : kr, exists a in c, s = Iio a := fun s => s.2.2
  choose ar arc har using Ar
  refine ⟨range al, by simp [range_subset_iff, alc], range ar,
    by simp [range_subset_iff, arc], finite_range _, finite_range _, ?_⟩
  rw [k_eq]; rw [sInter_eq_biInter]; rw [biInter_union]; rw [biInter_range]; rw [biInter_range]; rw [biInter_eq_iInter]; rw [biInter_eq_iInter]
  simp [hal, har]

/-- **Squeeze theorem** (also known as **sandwich theorem**). This version assumes that inequalities
hold eventually for the filter. -/
@[to_dual self (reorder := g h, hg hh, hgf hfh)]
/--
theorem `tendsto_of_tendsto_of_tendsto_of_le_of_le'` / 定理 `tendsto_of_tendsto_of_tendsto_of_le_of_le'`

English:
theorem tendsto_of_tendsto_of_tendsto_of_le_of_le'
  statement: [OrderTopology α] {f g h : β -> α} {b : Filter β}
  proof: (hg.Icc hh).of_smallSets hgf.and hfh

@[to_dual self (reorder := g h, hg hh, hgf hfh)]
alias Filter.Tendsto.squeeze' := tendsto_of_tendsto_of_tendsto_of_le_of_le'

中文:
定理 tendsto_of_tendsto_of_tendsto_of_le_of_le'
  结论: [Order拓扑 α] {f g h : β -> α} {b : 滤子 β}
  证明: (hg.Icc hh).of_smallSets hgf.and hfh

@[to_dual self (reorder := g h, hg hh, hgf hfh)]
alias Filter.Tendsto.squeeze' := tendsto_of_tendsto_of_tendsto_of_le_of_le'

Depends on / 依赖: hg.Icc, hgf.and, of_smallSets
-/
theorem tendsto_of_tendsto_of_tendsto_of_le_of_le' [OrderTopology α] {f g h : β -> α} {b : Filter β}
    {a : α} (hg : Tendsto g b (𝓝 a)) (hh : Tendsto h b (𝓝 a)) (hgf : forallᶠ b in b, g b <= f b)
    (hfh : forallᶠ b in b, f b <= h b) : Tendsto f b (𝓝 a) :=
(hg.Icc hh).of_smallSets hgf.and hfh

@[to_dual self (reorder := g h, hg hh, hgf hfh)]
alias Filter.Tendsto.squeeze' := tendsto_of_tendsto_of_tendsto_of_le_of_le'

/-- **Squeeze theorem** (also known as **sandwich theorem**). This version assumes that inequalities
hold everywhere. -/
@[to_dual self (reorder := g h, hg hh, hgf hfh)]
/--
theorem `tendsto_of_tendsto_of_tendsto_of_le_of_le` / 定理 `tendsto_of_tendsto_of_tendsto_of_le_of_le`

English:
theorem tendsto_of_tendsto_of_tendsto_of_le_of_le
  statement: [OrderTopology α] {f g h : β -> α} {b : Filter β}
  proof: tendsto_of_tendsto_of_tendsto_of_le_of_le' hg hh (Eventually.of_forall hgf)
    (Eventually.of_forall hfh)

@[to_dual self (reorder := g h, hg hh, hgf hfh)]
alias Filter.Tendsto.squeeze := tendsto_of_tendsto_of_tendsto_of_le_of_le

中文:
定理 tendsto_of_tendsto_of_tendsto_of_le_of_le
  结论: [Order拓扑 α] {f g h : β -> α} {b : 滤子 β}
  证明: tendsto_of_tendsto_of_tendsto_of_le_of_le' hg hh (Eventually.of_forall hgf)
    (Eventually.of_forall hfh)

@[to_dual self (reorder := g h, hg hh, hgf hfh)]
alias Filter.Tendsto.squeeze := tendsto_of_tendsto_of_tendsto_of_le_of_le

Depends on / 依赖: Eventually, Eventually.of_forall, of_forall, tendsto_of_tendsto_of_tendsto_of_le_of_le
-/
theorem tendsto_of_tendsto_of_tendsto_of_le_of_le [OrderTopology α] {f g h : β -> α} {b : Filter β}
    {a : α} (hg : Tendsto g b (𝓝 a)) (hh : Tendsto h b (𝓝 a)) (hgf : g <= f) (hfh : f <= h) :
    Tendsto f b (𝓝 a) :=
  tendsto_of_tendsto_of_tendsto_of_le_of_le' hg hh (Eventually.of_forall hgf)
    (Eventually.of_forall hfh)

@[to_dual self (reorder := g h, hg hh, hgf hfh)]
alias Filter.Tendsto.squeeze := tendsto_of_tendsto_of_tendsto_of_le_of_le

/--
theorem `nhds_order_unbounded` / 定理 `nhds_order_unbounded`

English:
theorem nhds_order_unbounded
  given: [OrderTopology α] {a : α} (hu : exists u, a < u) (hl : exists l, l < a)
  proof: by
  simp only [nhds_eq_order, ← inf_biInf, ← biInf_inf, *, ← inf_principal, ← Ioi_inter_Iio]; rfl

中文:
定理 nhds_order_unbounded
  条件: [Order拓扑 α] {a : α} (hu : 存在 u, a < u) (hl : 存在 l, l < a)
  证明: by
  simp only [nhds_eq_order, ← inf_biInf, ← biInf_inf, *, ← inf_principal, ← Ioi_inter_Iio]; rfl

Depends on / 依赖: Ioi_inter_Iio, biInf_inf, inf_biInf, inf_principal, nhds_eq_order
-/
theorem nhds_order_unbounded [OrderTopology α] {a : α} (hu : exists u, a < u) (hl : exists l, l < a) :
    𝓝 a = ⨅ (l) (_ : l < a) (u) (_ : a < u), 𝓟 (Ioo l u) := by
  simp only [nhds_eq_order, ← inf_biInf, ← biInf_inf, *, ← inf_principal, ← Ioi_inter_Iio]; rfl

/--
theorem `tendsto_order_unbounded` / 定理 `tendsto_order_unbounded`

English:
theorem tendsto_order_unbounded
  statement: [OrderTopology α] {f : β -> α} {a : α} {x : Filter β}
  proof: by
  simp only [nhds_order_unbounded hu hl, tendsto_iInf, tendsto_principal]
  exact fun l hl u => h l u hl

中文:
定理 tendsto_order_unbounded
  结论: [Order拓扑 α] {f : β -> α} {a : α} {x : 滤子 β}
  证明: by
  simp only [nhds_order_unbounded hu hl, tendsto_iInf, tendsto_principal]
  exact fun l hl u => h l u hl

Depends on / 依赖: nhds_order_unbounded, tendsto_iInf, tendsto_principal
-/
theorem tendsto_order_unbounded [OrderTopology α] {f : β -> α} {a : α} {x : Filter β}
    (hu : exists u, a < u) (hl : exists l, l < a) (h : forall l u, l < a -> a < u -> forallᶠ b in x, l < f b ∧ f b < u) :
    Tendsto f x (𝓝 a) := by
  simp only [nhds_order_unbounded hu hl, tendsto_iInf, tendsto_principal]
  exact fun l hl u => h l u hl

end Preorder

/--
Instance `tendstoIxxNhdsWithin` / 实例 `tendstoIxxNhdsWithin`

English:
instance tendstoIxxNhdsWithin
  signature: {α : Type*} [TopologicalSpace α] (a : α) {s t : Set α}
  body: Filter.tendstoIxxClass_inf

中文:
实例 tendstoIxxNhdsWithin
  签名: {α : 类型} [拓扑空间 α] (a : α) {s t : 集合 α}
  定义体: Filter.tendstoIxxClass_inf

Depends on / 依赖: Filter, Filter.tendstoIxxClass_inf, tendstoIxxClass_inf
-/
instance tendstoIxxNhdsWithin {α : Type*} [TopologicalSpace α] (a : α) {s t : Set α}
    {Ixx} [TendstoIxxClass Ixx (𝓝 a) (𝓝 a)] [TendstoIxxClass Ixx (𝓟 s) (𝓟 t)] :
    TendstoIxxClass Ixx (𝓝[s] a) (𝓝[t] a) :=
  Filter.tendstoIxxClass_inf

/--
Instance `tendstoIccClassNhdsPi` / 实例 `tendstoIccClassNhdsPi`

English:
instance tendstoIccClassNhdsPi
  signature: {ι : Type*} {α : ι -> Type*} [forall i, Preorder (α i)]
  body: by
  constructor
  conv in (𝓝 f).smallSets => rw [nhds_pi, Filter.pi]
  simp only [smallSets_iInf, smallSets_comap_eq_comap_image, tendsto_iInf, tendsto_comap_iff]
  intro i
  have : Tendsto (fun g : forall i, α i => g i) (𝓝 f) (𝓝 (f i)) := (continuous_apply i).tendsto f
.smallSets_mono ?_ refine (t

中文:
实例 tendstoIccClassNhdsPi
  签名: {ι : 类型} {α : ι -> 类型} [对任意 i, 预序 (α i)]
  定义体: by
  constructor
  conv in (𝓝 f).smallSets => rw [nhds_pi, Filter.pi]
  simp only [smallSets_iInf, smallSets_comap_eq_comap_image, tendsto_iInf, tendsto_comap_iff]
  intro i
  have : Tendsto (fun g : forall i, α i => g i) (𝓝 f) (𝓝 (f i)) := (continuous_apply i).tendsto f
.smallSets_mono ?_ refine (t

Depends on / 依赖: Filter, Filter.pi, Tendsto, continuous_apply, filter_upwards, image_subset_iff, image_subset_iff.mpr, nhds_pi, smallSets, smallSets_comap_eq_comap_image, smallSets_iInf, smallSets_mono, tendsto, tendsto_comap_iff, tendsto_fst, tendsto_iInf, tendsto_snd, this.comp
-/
instance tendstoIccClassNhdsPi {ι : Type*} {α : ι -> Type*} [forall i, Preorder (α i)]
    [forall i, TopologicalSpace (α i)] [forall i, OrderTopology (α i)] (f : forall i, α i) :
    TendstoIxxClass Icc (𝓝 f) (𝓝 f) := by
  constructor
  conv in (𝓝 f).smallSets => rw [nhds_pi, Filter.pi]
  simp only [smallSets_iInf, smallSets_comap_eq_comap_image, tendsto_iInf, tendsto_comap_iff]
  intro i
  have : Tendsto (fun g : forall i, α i => g i) (𝓝 f) (𝓝 (f i)) := (continuous_apply i).tendsto f
.smallSets_mono ?_ refine (this.comp tendsto_fst).Icc (this.comp tendsto_snd)
  filter_upwards [] using fun ⟨f, g⟩ => image_subset_iff.mpr fun p hp => ⟨hp.1 i, hp.2 i⟩

/--
theorem `induced_topology_le_preorder` / 定理 `induced_topology_le_preorder`

English:
theorem induced_topology_le_preorder
  statement: [Preorder α] [Preorder β] [TopologicalSpace β]
  proof: by
  let _ := Preorder.topology α; have : OrderTopology α := ⟨rfl⟩
  refine le_of_nhds_le_nhds fun x => ?_
  simp only [nhds_eq_order, nhds_induced, comap_inf, comap_iInf, comap_principal, Ioi, Iio, ← hf]
  refine inf_le_inf (le_iInf₂ fun a ha => ?_) (le_iInf₂ fun a ha => ?_)
  exacts [iInf₂_le (f a

中文:
定理 induced_topology_le_preorder
  结论: [预序 α] [预序 β] [拓扑空间 β]
  证明: by
  let _ := Preorder.topology α; have : OrderTopology α := ⟨rfl⟩
  refine le_of_nhds_le_nhds fun x => ?_
  simp only [nhds_eq_order, nhds_induced, comap_inf, comap_iInf, comap_principal, Ioi, Iio, ← hf]
  refine inf_le_inf (le_iInf₂ fun a ha => ?_) (le_iInf₂ fun a ha => ?_)
  exacts [iInf₂_le (f a

Depends on / 依赖: OrderTopology, Preorder, Preorder.topology, comap_iInf, comap_inf, comap_principal, exacts, inf_le_inf, le_of_nhds_le_nhds, nhds_eq_order, nhds_induced, topology
-/
theorem induced_topology_le_preorder [Preorder α] [Preorder β] [TopologicalSpace β]
    [OrderTopology β] {f : α -> β} (hf : forall {x y}, f x < f y ↔ x < y) :
    induced f ‹TopologicalSpace β› <= Preorder.topology α := by
  let _ := Preorder.topology α; have : OrderTopology α := ⟨rfl⟩
  refine le_of_nhds_le_nhds fun x => ?_
  simp only [nhds_eq_order, nhds_induced, comap_inf, comap_iInf, comap_principal, Ioi, Iio, ← hf]
  refine inf_le_inf (le_iInf₂ fun a ha => ?_) (le_iInf₂ fun a ha => ?_)
  exacts [iInf₂_le (f a) ha, iInf₂_le (f a) ha]

@[to_dual self (reorder := hf (x y), H₁ H₂)]
/--
theorem `induced_topology_eq_preorder` / 定理 `induced_topology_eq_preorder`

English:
theorem induced_topology_eq_preorder
  statement: [Preorder α] [Preorder β] [TopologicalSpace β]
  proof: by
  let _ := Preorder.topology α; have : OrderTopology α := ⟨rfl⟩
  refine le_antisymm (induced_topology_le_preorder hf) ?_
  refine le_of_nhds_le_nhds fun a => ?_
  simp only [nhds_eq_order, nhds_induced, comap_inf, comap_iInf, comap_principal]
  refine inf_le_inf (le_iInf₂ fun b hb => ?_) (le_iIn

中文:
定理 induced_topology_eq_preorder
  结论: [预序 α] [预序 β] [拓扑空间 β]
  证明: by
  let _ := Preorder.topology α; have : OrderTopology α := ⟨rfl⟩
  refine le_antisymm (induced_topology_le_preorder hf) ?_
  refine le_of_nhds_le_nhds fun a => ?_
  simp only [nhds_eq_order, nhds_induced, comap_inf, comap_iInf, comap_principal]
  refine inf_le_inf (le_iInf₂ fun b hb => ?_) (le_iIn

Depends on / 依赖: OrderTopology, Preorder, Preorder.topology, comap_iInf, comap_inf, comap_principal, hyb.trans_lt, induced_topology_le_preorder, inf_le_inf, le_antisymm, le_of_nhds_le_nhds, le_pri, nhds_eq_order, nhds_induced, principal_mono, topology, trans_lt
-/
theorem induced_topology_eq_preorder [Preorder α] [Preorder β] [TopologicalSpace β]
    [OrderTopology β] {f : α -> β} (hf : forall {x y}, f x < f y ↔ x < y)
    (H₁ : forall {a b x}, b < f a -> ¬(b < f x) -> exists y, y < a ∧ b <= f y)
    (H₂ : forall {a b x}, f a < b -> ¬(f x < b) -> exists y, a < y ∧ f y <= b) :
    induced f ‹TopologicalSpace β› = Preorder.topology α := by
  let _ := Preorder.topology α; have : OrderTopology α := ⟨rfl⟩
  refine le_antisymm (induced_topology_le_preorder hf) ?_
  refine le_of_nhds_le_nhds fun a => ?_
  simp only [nhds_eq_order, nhds_induced, comap_inf, comap_iInf, comap_principal]
  refine inf_le_inf (le_iInf₂ fun b hb => ?_) (le_iInf₂ fun b hb => ?_)
  · by_cases! h : exists x, ¬(b < f x)
    · rcases h with ⟨x, hx⟩
      rcases H₁ hb hx with ⟨y, hya, hyb⟩
      exact iInf₂_le_of_le y hya (principal_mono.2 fun z hz => hyb.trans_lt (hf.2 hz))
    · exact le_principal_iff.2 (univ_mem' h)
  · by_cases! h : exists x, ¬(f x < b)
    · rcases h with ⟨x, hx⟩
      rcases H₂ hb hx with ⟨y, hya, hyb⟩
      exact iInf₂_le_of_le y hya (principal_mono.2 fun z hz => (hf.2 hz).trans_le hyb)
    · exact le_principal_iff.2 (univ_mem' h)

@[to_dual self (reorder := hf (x y), H₁ H₂)]
/--
theorem `induced_orderTopology'` / 定理 `induced_orderTopology'`

English:
theorem induced_orderTopology'
  statement: {α β : Type*} [Preorder α] [ta : TopologicalSpace β]
  proof: let _ := induced f ta
  ⟨induced_topology_eq_preorder hf (fun h _ => H₁ h) (fun h _ => H₂ h)⟩

@[to_dual self]

中文:
定理 induced_orderTopology'
  结论: {α β : 类型} [预序 α] [ta : 拓扑空间 β]
  证明: let _ := induced f ta
  ⟨induced_topology_eq_preorder hf (fun h _ => H₁ h) (fun h _ => H₂ h)⟩

@[to_dual self]

Depends on / 依赖: induced, induced_topology_eq_preorder
-/
theorem induced_orderTopology' {α β : Type*} [Preorder α] [ta : TopologicalSpace β]
    [Preorder β] [OrderTopology β] (f : α -> β) (hf : forall {x y}, f x < f y ↔ x < y)
    (H₁ : forall {a x}, x < f a -> exists b < a, x <= f b) (H₂ : forall {a x}, f a < x -> exists b > a, f b <= x) :
    @OrderTopology _ (induced f ta) _ :=
  let _ := induced f ta
  ⟨induced_topology_eq_preorder hf (fun h _ => H₁ h) (fun h _ => H₂ h)⟩

@[to_dual self]
/--
theorem `induced_orderTopology` / 定理 `induced_orderTopology`

English:
theorem induced_orderTopology
  statement: {α β : Type*} [Preorder α] [ta : TopologicalSpace β]
  proof: induced_orderTopology' f (hf)
    (fun xa => let ⟨b, xb, ba⟩ := H xa; ⟨b, hf.1 ba, le_of_lt xb⟩)
    fun ax => let ⟨b, ab, bx⟩ := H ax; ⟨b, hf.1 ab, le_of_lt bx⟩

中文:
定理 induced_orderTopology
  结论: {α β : 类型} [预序 α] [ta : 拓扑空间 β]
  证明: induced_orderTopology' f (hf)
    (fun xa => let ⟨b, xb, ba⟩ := H xa; ⟨b, hf.1 ba, le_of_lt xb⟩)
    fun ax => let ⟨b, ab, bx⟩ := H ax; ⟨b, hf.1 ab, le_of_lt bx⟩

Depends on / 依赖: induced_orderTopology, le_of_lt
-/
theorem induced_orderTopology {α β : Type*} [Preorder α] [ta : TopologicalSpace β]
    [Preorder β] [OrderTopology β] (f : α -> β) (hf : forall {x y}, f x < f y ↔ x < y)
    (H : forall {x y}, x < y -> exists a, f a in Ioo x y) : @OrderTopology _ (induced f ta) _ :=
  induced_orderTopology' f (hf)
    (fun xa => let ⟨b, xb, ba⟩ := H xa; ⟨b, hf.1 ba, le_of_lt xb⟩)
    fun ax => let ⟨b, ab, bx⟩ := H ax; ⟨b, hf.1 ab, le_of_lt bx⟩

/-- The topology induced by a strictly monotone function with order-connected range is the preorder
topology. -/
nonrec theorem StrictMono.induced_topology_eq_preorder {α β : Type*} [LinearOrder α]
    [LinearOrder β] [t : TopologicalSpace β] [OrderTopology β] {f : α -> β}
    (hf : StrictMono f) (hc : OrdConnected (range f)) : t.induced f = Preorder.topology α := by
  refine induced_topology_eq_preorder hf.lt_iff_lt (fun h₁ h₂ => ?_) fun h₁ h₂ => ?_
  · rcases hc.out (mem_range_self _) (mem_range_self _) ⟨not_lt.1 h₂, h₁.le⟩ with ⟨y, rfl⟩
    exact ⟨y, hf.lt_iff_lt.1 h₁, le_rfl⟩
  · rcases hc.out (mem_range_self _) (mem_range_self _) ⟨h₁.le, not_lt.1 h₂⟩ with ⟨y, rfl⟩
    exact ⟨y, hf.lt_iff_lt.1 h₁, le_rfl⟩

/--
theorem `StrictMono.isEmbedding_of_ordConnected` / 定理 `StrictMono.isEmbedding_of_ordConnected`

English:
theorem StrictMono.isEmbedding_of_ordConnected
  statement: {α β : Type*} [LinearOrder α] [LinearOrder β]
  proof: ⟨⟨h.1.trans Eq.symm hf.induced_topology_eq_preorder hc⟩, hf.injective⟩

中文:
定理 严格递增.isEmbedding_of_ordConnected
  结论: {α β : 类型} [线性序 α] [线性序 β]
  证明: ⟨⟨h.1.trans Eq.symm hf.induced_topology_eq_preorder hc⟩, hf.injective⟩

Depends on / 依赖: Eq.symm, hf.induced_topology_eq_preorder, hf.injective, induced_topology_eq_preorder, injective
-/
theorem StrictMono.isEmbedding_of_ordConnected {α β : Type*} [LinearOrder α] [LinearOrder β]
    [TopologicalSpace α] [h : OrderTopology α] [TopologicalSpace β] [OrderTopology β] {f : α -> β}
    (hf : StrictMono f) (hc : OrdConnected (range f)) : IsEmbedding f :=
⟨⟨h.1.trans Eq.symm hf.induced_topology_eq_preorder hc⟩, hf.injective⟩

/--
lemma `OrderEmbedding.isEmbedding_of_ordConnected` / 引理 `OrderEmbedding.isEmbedding_of_ordConnected`

English:
lemma OrderEmbedding.isEmbedding_of_ordConnected
  statement: {α β : Type*} [LinearOrder α] [LinearOrder β]
  proof: f.strictMono.isEmbedding_of_ordConnected hc

中文:
引理 OrderEmbedding.isEmbedding_of_ordConnected
  结论: {α β : 类型} [线性序 α] [线性序 β]
  证明: f.strictMono.isEmbedding_of_ordConnected hc

Depends on / 依赖: f.strictMono.isEmbedding_of_ordConnected, isEmbedding_of_ordConnected, strictMono
-/
lemma OrderEmbedding.isEmbedding_of_ordConnected {α β : Type*} [LinearOrder α] [LinearOrder β]
    [TopologicalSpace α] [OrderTopology α] [TopologicalSpace β] [OrderTopology β]
    (f : α ↪o β) (hc : OrdConnected (range f)) : Topology.IsEmbedding f :=
  f.strictMono.isEmbedding_of_ordConnected hc

/--
Instance `orderTopology_of_ordConnected` / 实例 `orderTopology_of_ordConnected`

English:
instance orderTopology_of_ordConnected
  signature: {α : Type u} [TopologicalSpace α] [LinearOrder α]
  body: ⟨(Subtype.strictMono_coe (· in t)).induced_topology_eq_preorder by
    rwa [← @Subtype.range_val _ t] at ht⟩

@[to_dual nhdsLE_eq_iInf_inf_principal]

中文:
实例 orderTopology_of_ordConnected
  签名: {α : 类型u} [拓扑空间 α] [线性序 α]
  定义体: ⟨(Subtype.strictMono_coe (· in t)).induced_topology_eq_preorder by
    rwa [← @Subtype.range_val _ t] at ht⟩

@[to_dual nhdsLE_eq_iInf_inf_principal]

Depends on / 依赖: Subtype, Subtype.range_val, Subtype.strictMono_coe, induced_topology_eq_preorder, range_val, strictMono_coe
-/
instance orderTopology_of_ordConnected {α : Type u} [TopologicalSpace α] [LinearOrder α]
    [OrderTopology α] {t : Set α} [ht : OrdConnected t] : OrderTopology t :=
⟨(Subtype.strictMono_coe (· in t)).induced_topology_eq_preorder by
    rwa [← @Subtype.range_val _ t] at ht⟩

@[to_dual nhdsLE_eq_iInf_inf_principal]
/--
theorem `nhdsGE_eq_iInf_inf_principal` / 定理 `nhdsGE_eq_iInf_inf_principal`

English:
theorem nhdsGE_eq_iInf_inf_principal
  given: [TopologicalSpace α] [Preorder α] [OrderTopology α] (a : α)
  proof: by
  rw [nhdsWithin]; rw [nhds_eq_order]
  refine le_antisymm (inf_le_inf_right _ inf_le_right) (le_inf (le_inf ?_ inf_le_left) inf_le_right)
  exact inf_le_right.trans (le_iInf₂ fun l hl => principal_mono.2 <| Ici_subset_Ioi.2 hl)

@[to_dual nhdsLE_eq_iInf_principal]

中文:
定理 nhdsGE_eq_iInf_inf_principal
  条件: [拓扑空间 α] [预序 α] [Order拓扑 α] (a : α)
  证明: by
  rw [nhdsWithin]; rw [nhds_eq_order]
  refine le_antisymm (inf_le_inf_right _ inf_le_right) (le_inf (le_inf ?_ inf_le_left) inf_le_right)
  exact inf_le_right.trans (le_iInf₂ fun l hl => principal_mono.2 <| Ici_subset_Ioi.2 hl)

@[to_dual nhdsLE_eq_iInf_principal]

Depends on / 依赖: Ici_subset_Ioi, inf_le_inf_right, inf_le_left, inf_le_right, inf_le_right.trans, le_antisymm, le_inf, nhdsWithin, nhds_eq_order, principal_mono
-/
theorem nhdsGE_eq_iInf_inf_principal [TopologicalSpace α] [Preorder α] [OrderTopology α] (a : α) :
    𝓝[>=] a = (⨅ (u) (_ : a < u), 𝓟 (Iio u)) ⊓ 𝓟 (Ici a) := by
  rw [nhdsWithin]; rw [nhds_eq_order]
  refine le_antisymm (inf_le_inf_right _ inf_le_right) (le_inf (le_inf ?_ inf_le_left) inf_le_right)
  exact inf_le_right.trans (le_iInf₂ fun l hl => principal_mono.2 <| Ici_subset_Ioi.2 hl)

@[to_dual nhdsLE_eq_iInf_principal]
/--
theorem `nhdsGE_eq_iInf_principal` / 定理 `nhdsGE_eq_iInf_principal`

English:
theorem nhdsGE_eq_iInf_principal
  statement: [TopologicalSpace α] [Preorder α] [OrderTopology α] {a : α}
  proof: by
  simp only [nhdsGE_eq_iInf_inf_principal, biInf_inf ha, inf_principal, Iio_inter_Ici]

@[to_dual nhdsLE_basis_of_exists_lt]

中文:
定理 nhdsGE_eq_iInf_principal
  结论: [拓扑空间 α] [预序 α] [Order拓扑 α] {a : α}
  证明: by
  simp only [nhdsGE_eq_iInf_inf_principal, biInf_inf ha, inf_principal, Iio_inter_Ici]

@[to_dual nhdsLE_basis_of_exists_lt]

Depends on / 依赖: Iio_inter_Ici, biInf_inf, inf_principal, nhdsGE_eq_iInf_inf_principal
-/
theorem nhdsGE_eq_iInf_principal [TopologicalSpace α] [Preorder α] [OrderTopology α] {a : α}
    (ha : exists u, a < u) : 𝓝[>=] a = ⨅ (u) (_ : a < u), 𝓟 (Ico a u) := by
  simp only [nhdsGE_eq_iInf_inf_principal, biInf_inf ha, inf_principal, Iio_inter_Ici]

@[to_dual nhdsLE_basis_of_exists_lt]
/--
theorem `nhdsGE_basis_of_exists_gt` / 定理 `nhdsGE_basis_of_exists_gt`

English:
theorem nhdsGE_basis_of_exists_gt
  statement: [TopologicalSpace α] [LinearOrder α] [OrderTopology α] {a : α}
  proof: nhdsGE_eq_iInf_principal ha ▸ hasBasis_biInf_principal
    (fun b hb c hc => ⟨min b c, lt_min hb hc, Ico_subset_Ico_right (min_le_left _ _),
      Ico_subset_Ico_right (min_le_right _ _)⟩) ha

@[to_dual]

中文:
定理 nhdsGE_basis_of_存在_gt
  结论: [拓扑空间 α] [线性序 α] [Order拓扑 α] {a : α}
  证明: nhdsGE_eq_iInf_principal ha ▸ hasBasis_biInf_principal
    (fun b hb c hc => ⟨min b c, lt_min hb hc, Ico_subset_Ico_right (min_le_left _ _),
      Ico_subset_Ico_right (min_le_right _ _)⟩) ha

@[to_dual]

Depends on / 依赖: Ico_subset_Ico_right, hasBasis_biInf_principal, lt_min, min_le_left, min_le_right, nhdsGE_eq_iInf_principal
-/
theorem nhdsGE_basis_of_exists_gt [TopologicalSpace α] [LinearOrder α] [OrderTopology α] {a : α}
    (ha : exists u, a < u) : (𝓝[>=] a).HasBasis (fun u => a < u) fun u => Ico a u :=
  nhdsGE_eq_iInf_principal ha ▸ hasBasis_biInf_principal
    (fun b hb c hc => ⟨min b c, lt_min hb hc, Ico_subset_Ico_right (min_le_left _ _),
      Ico_subset_Ico_right (min_le_right _ _)⟩) ha

@[to_dual]
/--
theorem `nhdsGE_basis` / 定理 `nhdsGE_basis`

English:
theorem nhdsGE_basis
  given: [TopologicalSpace α] [LinearOrder α] [OrderTopology α] [NoMaxOrder α] (a : α)
  proof: nhdsGE_basis_of_exists_gt (exists_gt a)

@[to_dual]

中文:
定理 nhdsGE_basis
  条件: [拓扑空间 α] [线性序 α] [Order拓扑 α] [NoMax序 α] (a : α)
  证明: nhdsGE_basis_of_exists_gt (exists_gt a)

@[to_dual]

Depends on / 依赖: exists_gt, nhdsGE_basis_of_exists_gt
-/
theorem nhdsGE_basis [TopologicalSpace α] [LinearOrder α] [OrderTopology α] [NoMaxOrder α] (a : α) :
    (𝓝[>=] a).HasBasis (fun u => a < u) fun u => Ico a u :=
  nhdsGE_basis_of_exists_gt (exists_gt a)

@[to_dual]
/--
theorem `nhds_top_order` / 定理 `nhds_top_order`

English:
theorem nhds_top_order
  given: [TopologicalSpace α] [Preorder α] [OrderTop α] [OrderTopology α]
  proof: by simp [nhds_eq_order (⊤ : α)]

@[to_dual]

中文:
定理 nhds_top_order
  条件: [拓扑空间 α] [预序 α] [有顶序 α] [Order拓扑 α]
  证明: by simp [nhds_eq_order (⊤ : α)]

@[to_dual]

Depends on / 依赖: nhds_eq_order
-/
theorem nhds_top_order [TopologicalSpace α] [Preorder α] [OrderTop α] [OrderTopology α] :
    𝓝 (⊤ : α) = ⨅ (l) (_ : l < ⊤), 𝓟 (Ioi l) := by simp [nhds_eq_order (⊤ : α)]

@[to_dual]
/--
theorem `nhds_top_basis` / 定理 `nhds_top_basis`

English:
theorem nhds_top_basis
  statement: [TopologicalSpace α] [LinearOrder α] [OrderTop α] [OrderTopology α]
  proof: by
  have : exists x : α, x < ⊤ := (exists_ne ⊤).imp fun x hx => hx.lt_top
  simpa only [Iic_top, nhdsWithin_univ, Ioc_top] using nhdsLE_basis_of_exists_lt this

@[to_dual]

中文:
定理 nhds_top_basis
  结论: [拓扑空间 α] [线性序 α] [有顶序 α] [Order拓扑 α]
  证明: by
  have : exists x : α, x < ⊤ := (exists_ne ⊤).imp fun x hx => hx.lt_top
  simpa only [Iic_top, nhdsWithin_univ, Ioc_top] using nhdsLE_basis_of_exists_lt this

@[to_dual]

Depends on / 依赖: Iic_top, Ioc_top, exists_ne, hx.lt_top, lt_top, nhdsLE_basis_of_exists_lt, nhdsWithin_univ
-/
theorem nhds_top_basis [TopologicalSpace α] [LinearOrder α] [OrderTop α] [OrderTopology α]
    [Nontrivial α] : (𝓝 ⊤).HasBasis (fun a : α => a < ⊤) fun a : α => Ioi a := by
  have : exists x : α, x < ⊤ := (exists_ne ⊤).imp fun x hx => hx.lt_top
  simpa only [Iic_top, nhdsWithin_univ, Ioc_top] using nhdsLE_basis_of_exists_lt this

@[to_dual]
/--
theorem `nhds_top_basis_Ici` / 定理 `nhds_top_basis_Ici`

English:
theorem nhds_top_basis_Ici
  statement: [TopologicalSpace α] [LinearOrder α] [OrderTop α] [OrderTopology α]
  proof: nhds_top_basis.to_hasBasis
    (fun _a ha => let ⟨b, hab, hb⟩ := exists_between ha; ⟨b, hb, Ici_subset_Ioi.mpr hab⟩)
    fun a ha => ⟨a, ha, Ioi_subset_Ici_self⟩

@[to_dual]

中文:
定理 nhds_top_basis_Ici
  结论: [拓扑空间 α] [线性序 α] [有顶序 α] [Order拓扑 α]
  证明: nhds_top_basis.to_hasBasis
    (fun _a ha => let ⟨b, hab, hb⟩ := exists_between ha; ⟨b, hb, Ici_subset_Ioi.mpr hab⟩)
    fun a ha => ⟨a, ha, Ioi_subset_Ici_self⟩

@[to_dual]

Depends on / 依赖: Ici_subset_Ioi, Ici_subset_Ioi.mpr, Ioi_subset_Ici_self, exists_between, nhds_top_basis, nhds_top_basis.to_hasBasis, to_hasBasis
-/
theorem nhds_top_basis_Ici [TopologicalSpace α] [LinearOrder α] [OrderTop α] [OrderTopology α]
    [Nontrivial α] [DenselyOrdered α] : (𝓝 ⊤).HasBasis (fun a : α => a < ⊤) Ici :=
  nhds_top_basis.to_hasBasis
    (fun _a ha => let ⟨b, hab, hb⟩ := exists_between ha; ⟨b, hb, Ici_subset_Ioi.mpr hab⟩)
    fun a ha => ⟨a, ha, Ioi_subset_Ici_self⟩

@[to_dual]
/--
theorem `tendsto_nhds_top_mono` / 定理 `tendsto_nhds_top_mono`

English:
theorem tendsto_nhds_top_mono
  statement: [TopologicalSpace β] [Preorder β] [OrderTop β] [OrderTopology β]
  proof: by
  simp only [nhds_top_order, tendsto_iInf, tendsto_principal] at hf ⊢
  intro x hx
  filter_upwards [hf x hx, hg] with _ using lt_of_lt_of_le

@[to_dual]

中文:
定理 tendsto_nhds_top_mono
  结论: [拓扑空间 β] [预序 β] [有顶序 β] [Order拓扑 β]
  证明: by
  simp only [nhds_top_order, tendsto_iInf, tendsto_principal] at hf ⊢
  intro x hx
  filter_upwards [hf x hx, hg] with _ using lt_of_lt_of_le

@[to_dual]

Depends on / 依赖: filter_upwards, lt_of_lt_of_le, nhds_top_order, tendsto_iInf, tendsto_principal
-/
theorem tendsto_nhds_top_mono [TopologicalSpace β] [Preorder β] [OrderTop β] [OrderTopology β]
    {l : Filter α} {f g : α -> β} (hf : Tendsto f l (𝓝 ⊤)) (hg : f <=ᶠ[l] g) : Tendsto g l (𝓝 ⊤) := by
  simp only [nhds_top_order, tendsto_iInf, tendsto_principal] at hf ⊢
  intro x hx
  filter_upwards [hf x hx, hg] with _ using lt_of_lt_of_le

@[to_dual]
/--
theorem `tendsto_nhds_top_mono'` / 定理 `tendsto_nhds_top_mono'`

English:
theorem tendsto_nhds_top_mono'
  statement: [TopologicalSpace β] [Preorder β] [OrderTop β] [OrderTopology β]
  proof: tendsto_nhds_top_mono hf (Eventually.of_forall hg)

中文:
定理 tendsto_nhds_top_mono'
  结论: [拓扑空间 β] [预序 β] [有顶序 β] [Order拓扑 β]
  证明: tendsto_nhds_top_mono hf (Eventually.of_forall hg)

Depends on / 依赖: Eventually, Eventually.of_forall, of_forall, tendsto_nhds_top_mono
-/
theorem tendsto_nhds_top_mono' [TopologicalSpace β] [Preorder β] [OrderTop β] [OrderTopology β]
    {l : Filter α} {f g : α -> β} (hf : Tendsto f l (𝓝 ⊤)) (hg : f <= g) : Tendsto g l (𝓝 ⊤) :=
  tendsto_nhds_top_mono hf (Eventually.of_forall hg)

section LinearOrder

variable [TopologicalSpace α] [LinearOrder α]

section OrderTopology
variable [OrderTopology α]

@[to_dual none]
/--
theorem `order_separated` / 定理 `order_separated`

English:
theorem order_separated
  given: {a₁ a₂ : α} (h : a₁ < a₂)
  proof: let ⟨x, hx, y, hy, h⟩ := h.exists_disjoint_Iio_Ioi
  ⟨Iio x, Ioi y, isOpen_gt' _, isOpen_lt' _, hx, hy, h⟩

中文:
定理 order_separated
  条件: {a₁ a₂ : α} (h : a₁ < a₂)
  证明: let ⟨x, hx, y, hy, h⟩ := h.exists_disjoint_Iio_Ioi
  ⟨Iio x, Ioi y, isOpen_gt' _, isOpen_lt' _, hx, hy, h⟩

Depends on / 依赖: exists_disjoint_Iio_Ioi, h.exists_disjoint_Iio_Ioi, isOpen_gt, isOpen_lt
-/
theorem order_separated {a₁ a₂ : α} (h : a₁ < a₂) :
    exists u v : Set α, IsOpen u ∧ IsOpen v ∧ a₁ in u ∧ a₂ in v ∧ forall b₁ in u, forall b₂ in v, b₁ < b₂ :=
  let ⟨x, hx, y, hy, h⟩ := h.exists_disjoint_Iio_Ioi
  ⟨Iio x, Ioi y, isOpen_gt' _, isOpen_lt' _, hx, hy, h⟩

-- see Note [lower instance priority]
instance (priority := 100) OrderTopology.to_orderClosedTopology : OrderClosedTopology α where
isClosed_le' := isOpen_compl_iff.1 isOpen_prod_iff.mpr fun a₁ a₂ (h : ¬a₁ <= a₂) =>
    have h : a₂ < a₁ := lt_of_not_ge h
    let ⟨u, v, hu, hv, ha₁, ha₂, h⟩ := order_separated h
⟨v, u, hv, hu, ha₂, ha₁, fun ⟨b₁, b₂⟩ ⟨h₁, h₂⟩ => not_le_of_gt h b₂ h₂ b₁ h₁⟩

@[to_dual]
/--
theorem `exists_Ioc_subset_of_mem_nhds` / 定理 `exists_Ioc_subset_of_mem_nhds`

English:
theorem exists_Ioc_subset_of_mem_nhds
  given: {a : α} {s : Set α} (hs : s in 𝓝 a) (h : exists l, l < a)
  proof: (nhdsLE_basis_of_exists_lt h).mem_iff.mp (nhdsWithin_le_nhds hs)

@[to_dual]

中文:
定理 存在_Ioc_subset_of_mem_nhds
  条件: {a : α} {s : 集合 α} (hs : s in 𝓝 a) (h : 存在 l, l < a)
  证明: (nhdsLE_basis_of_exists_lt h).mem_iff.mp (nhdsWithin_le_nhds hs)

@[to_dual]

Depends on / 依赖: mem_iff, mem_iff.mp, nhdsLE_basis_of_exists_lt, nhdsWithin_le_nhds
-/
theorem exists_Ioc_subset_of_mem_nhds {a : α} {s : Set α} (hs : s in 𝓝 a) (h : exists l, l < a) :
    exists l < a, Ioc l a subseteq s :=
  (nhdsLE_basis_of_exists_lt h).mem_iff.mp (nhdsWithin_le_nhds hs)

@[to_dual]
/--
theorem `exists_Ioc_subset_of_mem_nhds'` / 定理 `exists_Ioc_subset_of_mem_nhds'`

English:
theorem exists_Ioc_subset_of_mem_nhds'
  given: {a : α} {s : Set α} (hs : s in 𝓝 a) {l : α} (hl : l < a)
  proof: let ⟨l', hl'a, hl's⟩ := exists_Ioc_subset_of_mem_nhds hs ⟨l, hl⟩
  ⟨max l l', ⟨le_max_left _ _, max_lt hl hl'a⟩,
    (Ioc_subset_Ioc_left <| le_max_right _ _).trans hl's⟩

@[to_dual]

中文:
定理 存在_Ioc_subset_of_mem_nhds'
  条件: {a : α} {s : 集合 α} (hs : s in 𝓝 a) {l : α} (hl : l < a)
  证明: let ⟨l', hl'a, hl's⟩ := exists_Ioc_subset_of_mem_nhds hs ⟨l, hl⟩
  ⟨max l l', ⟨le_max_left _ _, max_lt hl hl'a⟩,
    (Ioc_subset_Ioc_left <| le_max_right _ _).trans hl's⟩

@[to_dual]

Depends on / 依赖: Ioc_subset_Ioc_left, exists_Ioc_subset_of_mem_nhds, le_max_left, le_max_right, max_lt
-/
theorem exists_Ioc_subset_of_mem_nhds' {a : α} {s : Set α} (hs : s in 𝓝 a) {l : α} (hl : l < a) :
    exists l' in Ico l a, Ioc l' a subseteq s :=
  let ⟨l', hl'a, hl's⟩ := exists_Ioc_subset_of_mem_nhds hs ⟨l, hl⟩
  ⟨max l l', ⟨le_max_left _ _, max_lt hl hl'a⟩,
    (Ioc_subset_Ioc_left <| le_max_right _ _).trans hl's⟩

@[to_dual]
/--
theorem `exists_Icc_mem_subset_of_mem_nhdsGE` / 定理 `exists_Icc_mem_subset_of_mem_nhdsGE`

English:
theorem exists_Icc_mem_subset_of_mem_nhdsGE
  given: {a : α} {s : Set α} (hs : s in 𝓝[>=] a)
  proof: by
  rcases (em (IsMax a)).imp_right not_isMax_iff.mp with (ha | ha)
  · use a
    simpa [ha.Ici_eq] using hs
  · rcases (nhdsGE_basis_of_exists_gt ha).mem_iff.mp hs with ⟨b, hab, hbs⟩
    rcases eq_empty_or_nonempty (Ioo a b) with (H | ⟨c, hc⟩)
    · have : Ico a b = Icc a a := by rw [← Icc_union_I

中文:
定理 存在_Icc_mem_subset_of_mem_nhdsGE
  条件: {a : α} {s : 集合 α} (hs : s in 𝓝[>=] a)
  证明: by
  rcases (em (IsMax a)).imp_right not_isMax_iff.mp with (ha | ha)
  · use a
    simpa [ha.Ici_eq] using hs
  · rcases (nhdsGE_basis_of_exists_gt ha).mem_iff.mp hs with ⟨b, hab, hbs⟩
    rcases eq_empty_or_nonempty (Ioo a b) with (H | ⟨c, hc⟩)
    · have : Ico a b = Icc a a := by rw [← Icc_union_I

Depends on / 依赖: Icc_mem_nhdsGE, Icc_subset_Ico_right, Icc_union_Ioo_eq_Ico, Ici_eq, Ico_mem_nhdsGE, eq_empty_or_nonempty, ha.Ici_eq, imp_right, le_rfl, mem_iff, mem_iff.mp, nhdsGE_basis_of_exists_gt, not_isMax_iff, not_isMax_iff.mp, union_empty
-/
theorem exists_Icc_mem_subset_of_mem_nhdsGE {a : α} {s : Set α} (hs : s in 𝓝[>=] a) :
    exists b, a <= b ∧ Icc a b in 𝓝[>=] a ∧ Icc a b subseteq s := by
  rcases (em (IsMax a)).imp_right not_isMax_iff.mp with (ha | ha)
  · use a
    simpa [ha.Ici_eq] using hs
  · rcases (nhdsGE_basis_of_exists_gt ha).mem_iff.mp hs with ⟨b, hab, hbs⟩
    rcases eq_empty_or_nonempty (Ioo a b) with (H | ⟨c, hc⟩)
    · have : Ico a b = Icc a a := by rw [← Icc_union_Ioo_eq_Ico le_rfl hab, H, union_empty]
      exact ⟨a, le_rfl, this ▸ ⟨Ico_mem_nhdsGE hab, hbs⟩⟩
    · exact ⟨c, hc.1.le, Icc_mem_nhdsGE hc.1, (Icc_subset_Ico_right hc.2).trans hbs⟩

/--
theorem `exists_Icc_mem_subset_of_mem_nhds` / 定理 `exists_Icc_mem_subset_of_mem_nhds`

English:
theorem exists_Icc_mem_subset_of_mem_nhds
  given: {a : α} {s : Set α} (hs : s in 𝓝 a)
  proof: by
  rcases exists_Icc_mem_subset_of_mem_nhdsLE (nhdsWithin_le_nhds hs) with
    ⟨b, hba, hb_nhds, hbs⟩
  rcases exists_Icc_mem_subset_of_mem_nhdsGE (nhdsWithin_le_nhds hs) with
    ⟨c, hac, hc_nhds, hcs⟩
  refine ⟨b, c, ⟨hba, hac⟩, ?_⟩
  rw [← Icc_union_Icc_eq_Icc hba hac]; rw [← nhdsLE_sup_nhdsGE]

中文:
定理 存在_Icc_mem_subset_of_mem_nhds
  条件: {a : α} {s : 集合 α} (hs : s in 𝓝 a)
  证明: by
  rcases exists_Icc_mem_subset_of_mem_nhdsLE (nhdsWithin_le_nhds hs) with
    ⟨b, hba, hb_nhds, hbs⟩
  rcases exists_Icc_mem_subset_of_mem_nhdsGE (nhdsWithin_le_nhds hs) with
    ⟨c, hac, hc_nhds, hcs⟩
  refine ⟨b, c, ⟨hba, hac⟩, ?_⟩
  rw [← Icc_union_Icc_eq_Icc hba hac]; rw [← nhdsLE_sup_nhdsGE]

Depends on / 依赖: Icc_union_Icc_eq_Icc, exists_Icc_mem_subset_of_mem_nhdsGE, exists_Icc_mem_subset_of_mem_nhdsLE, hb_nhds, hc_nhds, nhdsLE_sup_nhdsGE, nhdsWithin_le_nhds, union_mem_sup, union_subset
-/
theorem exists_Icc_mem_subset_of_mem_nhds {a : α} {s : Set α} (hs : s in 𝓝 a) :
    exists b c, a in Icc b c ∧ Icc b c in 𝓝 a ∧ Icc b c subseteq s := by
  rcases exists_Icc_mem_subset_of_mem_nhdsLE (nhdsWithin_le_nhds hs) with
    ⟨b, hba, hb_nhds, hbs⟩
  rcases exists_Icc_mem_subset_of_mem_nhdsGE (nhdsWithin_le_nhds hs) with
    ⟨c, hac, hc_nhds, hcs⟩
  refine ⟨b, c, ⟨hba, hac⟩, ?_⟩
  rw [← Icc_union_Icc_eq_Icc hba hac]; rw [← nhdsLE_sup_nhdsGE]
  exact ⟨union_mem_sup hb_nhds hc_nhds, union_subset hbs hcs⟩

@[to_dual none]
/--
theorem `IsOpen.exists_Ioo_subset` / 定理 `IsOpen.exists_Ioo_subset`

English:
theorem IsOpen.exists_Ioo_subset
  given: [Nontrivial α] {s : Set α} (hs : IsOpen s) (h : s.Nonempty)
  proof: by
  obtain ⟨x, hx⟩ : exists x, x in s := h
  obtain ⟨y, hy⟩ : exists y, y != x := exists_ne x
  rcases lt_trichotomy x y with (H | rfl | H)
  · obtain ⟨u, xu, hu⟩ : exists u, x < u ∧ Ico x u subseteq s :=
      exists_Ico_subset_of_mem_nhds (hs.mem_nhds hx) ⟨y, H⟩
    exact ⟨x, u, xu, Ioo_subset_Ic

中文:
定理 是开集.存在_Ioo_subset
  条件: [非平凡 α] {s : 集合 α} (hs : 是开集 s) (h : s.非空)
  证明: by
  obtain ⟨x, hx⟩ : exists x, x in s := h
  obtain ⟨y, hy⟩ : exists y, y != x := exists_ne x
  rcases lt_trichotomy x y with (H | rfl | H)
  · obtain ⟨u, xu, hu⟩ : exists u, x < u ∧ Ico x u subseteq s :=
      exists_Ico_subset_of_mem_nhds (hs.mem_nhds hx) ⟨y, H⟩
    exact ⟨x, u, xu, Ioo_subset_Ic

Depends on / 依赖: Ioo_subset_Ico_self, Ioo_subset_Ico_self.trans, Ioo_subset_Ioc_self, Ioo_subset_Ioc_self.trans, exists_Ico_subset_of_mem_nhds, exists_Ioc_subset_of_mem_nhds, exists_ne, hs.mem_nhds, lt_trichotomy, mem_nhds, subseteq
-/
theorem IsOpen.exists_Ioo_subset [Nontrivial α] {s : Set α} (hs : IsOpen s) (h : s.Nonempty) :
    exists a b, a < b ∧ Ioo a b subseteq s := by
  obtain ⟨x, hx⟩ : exists x, x in s := h
  obtain ⟨y, hy⟩ : exists y, y != x := exists_ne x
  rcases lt_trichotomy x y with (H | rfl | H)
  · obtain ⟨u, xu, hu⟩ : exists u, x < u ∧ Ico x u subseteq s :=
      exists_Ico_subset_of_mem_nhds (hs.mem_nhds hx) ⟨y, H⟩
    exact ⟨x, u, xu, Ioo_subset_Ico_self.trans hu⟩
  · exact (hy rfl).elim
  · obtain ⟨l, lx, hl⟩ : exists l, l < x ∧ Ioc l x subseteq s :=
      exists_Ioc_subset_of_mem_nhds (hs.mem_nhds hx) ⟨y, H⟩
    exact ⟨l, x, lx, Ioo_subset_Ioc_self.trans hl⟩

@[to_dual self]
/--
theorem `dense_of_exists_between` / 定理 `dense_of_exists_between`

English:
theorem dense_of_exists_between
  statement: [Nontrivial α] {s : Set α}
  proof: by
  refine dense_iff_inter_open.2 fun U U_open U_nonempty => ?_
  obtain ⟨a, b, hab, H⟩ : exists a b : α, a < b ∧ Ioo a b subseteq U := U_open.exists_Ioo_subset U_nonempty
  obtain ⟨x, xs, hx⟩ : exists x in s, a < x ∧ x < b := h hab
  exact ⟨x, ⟨H hx, xs⟩⟩

@[to_dual]

中文:
定理 dense_of_存在_between
  结论: [非平凡 α] {s : 集合 α}
  证明: by
  refine dense_iff_inter_open.2 fun U U_open U_nonempty => ?_
  obtain ⟨a, b, hab, H⟩ : exists a b : α, a < b ∧ Ioo a b subseteq U := U_open.exists_Ioo_subset U_nonempty
  obtain ⟨x, xs, hx⟩ : exists x in s, a < x ∧ x < b := h hab
  exact ⟨x, ⟨H hx, xs⟩⟩

@[to_dual]

Depends on / 依赖: U_nonempty, U_open, U_open.exists_Ioo_subset, dense_iff_inter_open, exists_Ioo_subset, subseteq
-/
theorem dense_of_exists_between [Nontrivial α] {s : Set α}
    (h : forall ⦃a b⦄, a < b -> exists c in s, c in Ioo a b) : Dense s := by
  refine dense_iff_inter_open.2 fun U U_open U_nonempty => ?_
  obtain ⟨a, b, hab, H⟩ : exists a b : α, a < b ∧ Ioo a b subseteq U := U_open.exists_Ioo_subset U_nonempty
  obtain ⟨x, xs, hx⟩ : exists x in s, a < x ∧ x < b := h hab
  exact ⟨x, ⟨H hx, xs⟩⟩

@[to_dual]
/--
theorem `IsUpperSet.isClosed` / 定理 `IsUpperSet.isClosed`

English:
theorem IsUpperSet.isClosed
  given: [WellFoundedLT α] {s : Set α} (h : IsUpperSet s)
  statement: IsClosed s
  proof: by
  obtain rfl | ⟨a, rfl⟩ := h.eq_empty_or_Ici
  exacts [isClosed_empty, isClosed_Ici]

@[to_dual]

中文:
定理 是上集.isClosed
  条件: [WellFoundedLT α] {s : 集合 α} (h : 是上集 s)
  结论: 是闭集 s
  证明: by
  obtain rfl | ⟨a, rfl⟩ := h.eq_empty_or_Ici
  exacts [isClosed_empty, isClosed_Ici]

@[to_dual]

Depends on / 依赖: eq_empty_or_Ici, exacts, h.eq_empty_or_Ici, isClosed_Ici, isClosed_empty
-/
theorem IsUpperSet.isClosed [WellFoundedLT α] {s : Set α} (h : IsUpperSet s) : IsClosed s := by
  obtain rfl | ⟨a, rfl⟩ := h.eq_empty_or_Ici
  exacts [isClosed_empty, isClosed_Ici]

@[to_dual]
/--
theorem `IsLowerSet.isOpen` / 定理 `IsLowerSet.isOpen`

English:
theorem IsLowerSet.isOpen
  given: [WellFoundedLT α] {s : Set α} (h : IsLowerSet s)
  statement: IsOpen s
  proof: by
  simpa using h.compl.isClosed

中文:
定理 是下集.isOpen
  条件: [WellFoundedLT α] {s : 集合 α} (h : 是下集 s)
  结论: 是开集 s
  证明: by
  simpa using h.compl.isClosed

Depends on / 依赖: h.compl.isClosed, isClosed
-/
theorem IsLowerSet.isOpen [WellFoundedLT α] {s : Set α} (h : IsLowerSet s) : IsOpen s := by
  simpa using h.compl.isClosed

/-- A set in a nontrivial densely linear ordered type is dense in the sense of topology if and only
if for any `a < b` there exists `c ∈ s`, `a < c < b`. Each implication requires less typeclass
assumptions. -/
@[to_dual none]
/--
theorem `dense_iff_exists_between` / 定理 `dense_iff_exists_between`

English:
theorem dense_iff_exists_between
  given: [DenselyOrdered α] [Nontrivial α] {s : Set α}
  proof: ⟨fun h _ _ hab => h.exists_between hab, dense_of_exists_between⟩

中文:
定理 dense_iff_存在_between
  条件: [稠密序 α] [非平凡 α] {s : 集合 α}
  证明: ⟨fun h _ _ hab => h.exists_between hab, dense_of_exists_between⟩

Depends on / 依赖: dense_of_exists_between, exists_between, h.exists_between
-/
theorem dense_iff_exists_between [DenselyOrdered α] [Nontrivial α] {s : Set α} :
    Dense s ↔ forall a b, a < b -> exists c in s, a < c ∧ c < b :=
  ⟨fun h _ _ hab => h.exists_between hab, dense_of_exists_between⟩

/-- A set is a neighborhood of `a` if and only if it contains an interval `(l, u)` containing `a`,
provided `a` is neither a bottom element nor a top element. -/
@[to_dual none]
/--
theorem `mem_nhds_iff_exists_Ioo_subset'` / 定理 `mem_nhds_iff_exists_Ioo_subset'`

English:
theorem mem_nhds_iff_exists_Ioo_subset'
  statement: {a : α} {s : Set α} (hl : exists l, l < a)
  proof: by
  constructor
  · intro h
    rcases exists_Ico_subset_of_mem_nhds h hu with ⟨u, au, hu⟩
    rcases exists_Ioc_subset_of_mem_nhds h hl with ⟨l, la, hl⟩
    exact ⟨l, u, ⟨la, au⟩, Ioc_union_Ico_eq_Ioo la au ▸ union_subset hl hu⟩
  · rintro ⟨l, u, ha, h⟩
    apply mem_of_superset (Ioo_mem_nhds ha.1

中文:
定理 mem_nhds_iff_存在_Ioo_subset'
  结论: {a : α} {s : 集合 α} (hl : 存在 l, l < a)
  证明: by
  constructor
  · intro h
    rcases exists_Ico_subset_of_mem_nhds h hu with ⟨u, au, hu⟩
    rcases exists_Ioc_subset_of_mem_nhds h hl with ⟨l, la, hl⟩
    exact ⟨l, u, ⟨la, au⟩, Ioc_union_Ico_eq_Ioo la au ▸ union_subset hl hu⟩
  · rintro ⟨l, u, ha, h⟩
    apply mem_of_superset (Ioo_mem_nhds ha.1

Depends on / 依赖: Ioc_union_Ico_eq_Ioo, Ioo_mem_nhds, exists_Ico_subset_of_mem_nhds, exists_Ioc_subset_of_mem_nhds, mem_of_superset, union_subset
-/
theorem mem_nhds_iff_exists_Ioo_subset' {a : α} {s : Set α} (hl : exists l, l < a)
    (hu : exists u, a < u) : s in 𝓝 a ↔ exists l u, a in Ioo l u ∧ Ioo l u subseteq s := by
  constructor
  · intro h
    rcases exists_Ico_subset_of_mem_nhds h hu with ⟨u, au, hu⟩
    rcases exists_Ioc_subset_of_mem_nhds h hl with ⟨l, la, hl⟩
    exact ⟨l, u, ⟨la, au⟩, Ioc_union_Ico_eq_Ioo la au ▸ union_subset hl hu⟩
  · rintro ⟨l, u, ha, h⟩
    apply mem_of_superset (Ioo_mem_nhds ha.1 ha.2) h

/--
theorem `mem_nhds_iff_exists_Ioo_subset` / 定理 `mem_nhds_iff_exists_Ioo_subset`

English:
theorem mem_nhds_iff_exists_Ioo_subset
  statement: [NoMaxOrder α] [NoMinOrder α] {a : α}
  proof: mem_nhds_iff_exists_Ioo_subset' (exists_lt a) (exists_gt a)

中文:
定理 mem_nhds_iff_存在_Ioo_subset
  结论: [NoMax序 α] [NoMin序 α] {a : α}
  证明: mem_nhds_iff_exists_Ioo_subset' (exists_lt a) (exists_gt a)

Depends on / 依赖: exists_gt, exists_lt, mem_nhds_iff_exists_Ioo_subset
-/
theorem mem_nhds_iff_exists_Ioo_subset [NoMaxOrder α] [NoMinOrder α] {a : α}
    {s : Set α} : s in 𝓝 a ↔ exists l u, a in Ioo l u ∧ Ioo l u subseteq s :=
  mem_nhds_iff_exists_Ioo_subset' (exists_lt a) (exists_gt a)

/--
theorem `nhds_basis_Ioo'` / 定理 `nhds_basis_Ioo'`

English:
theorem nhds_basis_Ioo'
  given: {a : α} (hl : exists l, l < a) (hu : exists u, a < u)
  proof: ⟨fun s => (mem_nhds_iff_exists_Ioo_subset' hl hu).trans by simp⟩

中文:
定理 nhds_basis_Ioo'
  条件: {a : α} (hl : 存在 l, l < a) (hu : 存在 u, a < u)
  证明: ⟨fun s => (mem_nhds_iff_exists_Ioo_subset' hl hu).trans by simp⟩

Depends on / 依赖: mem_nhds_iff_exists_Ioo_subset
-/
theorem nhds_basis_Ioo' {a : α} (hl : exists l, l < a) (hu : exists u, a < u) :
    (𝓝 a).HasBasis (fun b : α × α => b.1 < a ∧ a < b.2) fun b => Ioo b.1 b.2 :=
⟨fun s => (mem_nhds_iff_exists_Ioo_subset' hl hu).trans by simp⟩

/--
theorem `nhds_basis_Ioo` / 定理 `nhds_basis_Ioo`

English:
theorem nhds_basis_Ioo
  given: [NoMaxOrder α] [NoMinOrder α] (a : α)
  proof: nhds_basis_Ioo' (exists_lt a) (exists_gt a)

中文:
定理 nhds_basis_Ioo
  条件: [NoMax序 α] [NoMin序 α] (a : α)
  证明: nhds_basis_Ioo' (exists_lt a) (exists_gt a)

Depends on / 依赖: exists_gt, exists_lt, nhds_basis_Ioo
-/
theorem nhds_basis_Ioo [NoMaxOrder α] [NoMinOrder α] (a : α) :
    (𝓝 a).HasBasis (fun b : α × α => b.1 < a ∧ a < b.2) fun b => Ioo b.1 b.2 :=
  nhds_basis_Ioo' (exists_lt a) (exists_gt a)

/--
theorem `Filter.Eventually.exists_Ioo_subset` / 定理 `Filter.Eventually.exists_Ioo_subset`

English:
theorem Filter.Eventually.exists_Ioo_subset
  statement: [NoMaxOrder α] [NoMinOrder α] {a : α}
  proof: mem_nhds_iff_exists_Ioo_subset.1 hp

中文:
定理 滤子.Eventually.存在_Ioo_subset
  结论: [NoMax序 α] [NoMin序 α] {a : α}
  证明: mem_nhds_iff_exists_Ioo_subset.1 hp

Depends on / 依赖: mem_nhds_iff_exists_Ioo_subset
-/
theorem Filter.Eventually.exists_Ioo_subset [NoMaxOrder α] [NoMinOrder α] {a : α}
    {p : α -> Prop} (hp : forallᶠ x in 𝓝 a, p x) : exists l u, a in Ioo l u ∧ Ioo l u subseteq { x | p x } :=
  mem_nhds_iff_exists_Ioo_subset.1 hp

/--
theorem `Dense.topology_eq_generateFrom` / 定理 `Dense.topology_eq_generateFrom`

English:
theorem Dense.topology_eq_generateFrom
  statement: [DenselyOrdered α] {s : Set α}
  proof: by
  refine (OrderTopology.topology_eq_generate_intervals (α := α)).trans ?_
  refine le_antisymm (generateFrom_anti ?_) (le_generateFrom ?_)
  · simp only [union_subset_iff, image_subset_iff]
    exact ⟨fun a _ => ⟨a, .inl rfl⟩, fun a _ => ⟨a, .inr rfl⟩⟩
  · rintro _ ⟨a, rfl | rfl⟩
    · rw [hs.Ioi

中文:
定理 稠密.topology_eq_generateFrom
  结论: [稠密序 α] {s : 集合 α}
  证明: by
  refine (OrderTopology.topology_eq_generate_intervals (α := α)).trans ?_
  refine le_antisymm (generateFrom_anti ?_) (le_generateFrom ?_)
  · simp only [union_subset_iff, image_subset_iff]
    exact ⟨fun a _ => ⟨a, .inl rfl⟩, fun a _ => ⟨a, .inr rfl⟩⟩
  · rintro _ ⟨a, rfl | rfl⟩
    · rw [hs.Ioi

Depends on / 依赖: Iio_eq_biUnion, Ioi_eq_biUnion, OrderTopology, OrderTopology.topology_eq_generate_intervals, generateFrom, generateFrom_anti, hs.Iio_eq_biUnion, hs.Ioi_eq_biUnion, image_subset_iff, isOpen_iUnion, le_antisymm, le_generateFrom, mem_image_of_mem, topology_eq_generate_intervals, union_subset_iff
-/
theorem Dense.topology_eq_generateFrom [DenselyOrdered α] {s : Set α}
    (hs : Dense s) : ‹TopologicalSpace α› = .generateFrom (Ioi '' s union Iio '' s) := by
  refine (OrderTopology.topology_eq_generate_intervals (α := α)).trans ?_
  refine le_antisymm (generateFrom_anti ?_) (le_generateFrom ?_)
  · simp only [union_subset_iff, image_subset_iff]
    exact ⟨fun a _ => ⟨a, .inl rfl⟩, fun a _ => ⟨a, .inr rfl⟩⟩
  · rintro _ ⟨a, rfl | rfl⟩
    · rw [hs.Ioi_eq_biUnion]
      let _ := generateFrom (Ioi '' s union Iio '' s)
exact isOpen_iUnion fun x => isOpen_iUnion fun h => .basic _ .inl mem_image_of_mem _ h.1
    · rw [hs.Iio_eq_biUnion]
      let _ := generateFrom (Ioi '' s union Iio '' s)
exact isOpen_iUnion fun x => isOpen_iUnion fun h => .basic _ .inr mem_image_of_mem _ h.1

@[to_dual hasBasis_nhds_Ico_of_exists_gt]
/--
theorem `SuccOrder.hasBasis_nhds_Ioc_of_exists_lt` / 定理 `SuccOrder.hasBasis_nhds_Ioc_of_exists_lt`

English:
theorem SuccOrder.hasBasis_nhds_Ioc_of_exists_lt
  given: [SuccOrder α] {a : α} (ha : exists l, l < a)
  proof: SuccOrder.nhdsLE_eq_nhds a ▸ nhdsLE_basis_of_exists_lt ha

@[deprecated (since := "2026-04-19")]
alias PredOrder.hasBasis_nhds_Ioc_of_exists_gt := PredOrder.hasBasis_nhds_Ico_of_exists_gt

@[to_dual]

中文:
定理 Succ序.hasBasis_nhds_Ioc_of_存在_lt
  条件: [Succ序 α] {a : α} (ha : 存在 l, l < a)
  证明: SuccOrder.nhdsLE_eq_nhds a ▸ nhdsLE_basis_of_exists_lt ha

@[deprecated (since := "2026-04-19")]
alias PredOrder.hasBasis_nhds_Ioc_of_exists_gt := PredOrder.hasBasis_nhds_Ico_of_exists_gt

@[to_dual]

Depends on / 依赖: SuccOrder, SuccOrder.nhdsLE_eq_nhds, nhdsLE_basis_of_exists_lt, nhdsLE_eq_nhds
-/
theorem SuccOrder.hasBasis_nhds_Ioc_of_exists_lt [SuccOrder α] {a : α} (ha : exists l, l < a) :
    (𝓝 a).HasBasis (· < a) (Set.Ioc · a) :=
  SuccOrder.nhdsLE_eq_nhds a ▸ nhdsLE_basis_of_exists_lt ha

@[deprecated (since := "2026-04-19")]
alias PredOrder.hasBasis_nhds_Ioc_of_exists_gt := PredOrder.hasBasis_nhds_Ico_of_exists_gt

@[to_dual]
/--
theorem `SuccOrder.hasBasis_nhds_Ioc` / 定理 `SuccOrder.hasBasis_nhds_Ioc`

English:
theorem SuccOrder.hasBasis_nhds_Ioc
  given: [SuccOrder α] {a : α} [NoMinOrder α]
  proof: SuccOrder.hasBasis_nhds_Ioc_of_exists_lt (exists_lt a)

@[deprecated (since := "2026-04-19")]
alias PredOrder.hasBasis_nhds_Ioc := PredOrder.hasBasis_nhds_Ico

中文:
定理 Succ序.hasBasis_nhds_Ioc
  条件: [Succ序 α] {a : α} [NoMin序 α]
  证明: SuccOrder.hasBasis_nhds_Ioc_of_exists_lt (exists_lt a)

@[deprecated (since := "2026-04-19")]
alias PredOrder.hasBasis_nhds_Ioc := PredOrder.hasBasis_nhds_Ico

Depends on / 依赖: SuccOrder, SuccOrder.hasBasis_nhds_Ioc_of_exists_lt, exists_lt, hasBasis_nhds_Ioc_of_exists_lt
-/
theorem SuccOrder.hasBasis_nhds_Ioc [SuccOrder α] {a : α} [NoMinOrder α] :
    (𝓝 a).HasBasis (· < a) (Set.Ioc · a) :=
  SuccOrder.hasBasis_nhds_Ioc_of_exists_lt (exists_lt a)

@[deprecated (since := "2026-04-19")]
alias PredOrder.hasBasis_nhds_Ioc := PredOrder.hasBasis_nhds_Ico

variable (α) in
/--
theorem `SecondCountableTopology.of_separableSpace_orderTopology` / 定理 `SecondCountableTopology.of_separableSpace_orderTopology`

English:
theorem SecondCountableTopology.of_separableSpace_orderTopology
  statement: [DenselyOrdered α]
  proof: by
  rcases exists_countable_dense α with ⟨s, hc, hd⟩
  refine ⟨⟨_, ?_, hd.topology_eq_generateFrom⟩⟩
  exact (hc.image _).union (hc.image _)

中文:
定理 第二可数拓扑.of_separableSpace_orderTopology
  结论: [稠密序 α]
  证明: by
  rcases exists_countable_dense α with ⟨s, hc, hd⟩
  refine ⟨⟨_, ?_, hd.topology_eq_generateFrom⟩⟩
  exact (hc.image _).union (hc.image _)

Depends on / 依赖: exists_countable_dense, hc.image, hd.topology_eq_generateFrom, topology_eq_generateFrom
-/
theorem SecondCountableTopology.of_separableSpace_orderTopology [DenselyOrdered α]
    [SeparableSpace α] : SecondCountableTopology α := by
  rcases exists_countable_dense α with ⟨s, hc, hd⟩
  refine ⟨⟨_, ?_, hd.topology_eq_generateFrom⟩⟩
  exact (hc.image _).union (hc.image _)

/-- The set of points which are isolated on the right is countable when the space is
second-countable. -/
@[to_dual countable_setOfPred_covBy_left
/-- The set of points which are isolated on the left is countable when the space is
second-countable. -/]
/--
theorem `countable_setOfPred_covBy_right` / 定理 `countable_setOfPred_covBy_right`

English:
theorem countable_setOfPred_covBy_right
  given: [SecondCountableTopology α]
  proof: by
  nontriviality α
  let s := { x : α | exists y, x ⋖ y }
  have : forall x in s, exists y, x ⋖ y := fun x => id
  choose! y hy using this
  have Hy : forall x z, x in s -> z < y x -> z <= x := fun x z hx => (hy x hx).le_of_lt
  suffices H : forall a : Set α, IsOpen a -> Set.Countable { x | x in s

中文:
定理 countable_setOfPred_covBy_right
  条件: [第二可数拓扑 α]
  证明: by
  nontriviality α
  let s := { x : α | exists y, x ⋖ y }
  have : forall x in s, exists y, x ⋖ y := fun x => id
  choose! y hy using this
  have Hy : forall x z, x in s -> z < y x -> z <= x := fun x z hx => (hy x hx).le_of_lt
  suffices H : forall a : Set α, IsOpen a -> Set.Countable { x | x in s

Depends on / 依赖: Countable, IsOpen, Set.Countable, countableBasis, exists_mem_of_ne, isBasis_countableBasis, le_of_lt, nontriviality, subseteq
-/
theorem countable_setOfPred_covBy_right [SecondCountableTopology α] :
    Set.Countable { x : α | exists y, x ⋖ y } := by
  nontriviality α
  let s := { x : α | exists y, x ⋖ y }
  have : forall x in s, exists y, x ⋖ y := fun x => id
  choose! y hy using this
  have Hy : forall x z, x in s -> z < y x -> z <= x := fun x z hx => (hy x hx).le_of_lt
  suffices H : forall a : Set α, IsOpen a -> Set.Countable { x | x in s ∧ x in a ∧ y x ∉ a } by
    have : s subseteq ⋃ a in countableBasis α, { x | x in s ∧ x in a ∧ y x ∉ a } := fun x hx => by
      rcases (isBasis_countableBasis α).exists_mem_of_ne (hy x hx).ne with ⟨a, ab, xa, ya⟩
      exact mem_iUnion₂.2 ⟨a, ab, hx, xa, ya⟩
    refine Set.Countable.mono this ?_
    refine Countable.biUnion (countable_countableBasis α) fun a ha => H _ ?_
    exact isOpen_of_mem_countableBasis ha
  intro a ha
  suffices H : Set.Countable { x | (x in s ∧ x in a ∧ y x ∉ a) ∧ ¬IsBot x } from
    H.of_sdiff (subsingleton_isBot α).countable
  simp only [and_assoc]
  let t := { x | x in s ∧ x in a ∧ y x ∉ a ∧ ¬IsBot x }
  have : forall x in t, exists z < x, Ioc z x subseteq a := by
    intro x hx
    apply exists_Ioc_subset_of_mem_nhds (ha.mem_nhds hx.2.1)
    simpa only [IsBot, not_forall, not_le] using hx.right.right.right
  choose! z hz h'z using this
  have : PairwiseDisjoint t fun x => Ioc (z x) x := fun x xt x' x't hxx' => by
    rcases hxx'.lt_or_gt with (h' | h')
    · refine disjoint_left.2 fun u ux ux' => xt.2.2.1 ?_
      refine h'z x' x't ⟨ux'.1.trans_le (ux.2.trans (hy x xt.1).le), ?_⟩
      by_contra! H
      exact lt_irrefl _ ((Hy _ _ xt.1 H).trans_lt h')
    · refine disjoint_left.2 fun u ux ux' => x't.2.2.1 ?_
      refine h'z x xt ⟨ux.1.trans_le (ux'.2.trans (hy x' x't.1).le), ?_⟩
      by_contra! H
      exact lt_irrefl _ ((Hy _ _ x't.1 H).trans_lt h')
  refine this.countable_of_isOpen (fun x hx => ?_) fun x hx => ⟨x, hz x hx, le_rfl⟩
  suffices H : Ioc (z x) x = Ioo (z x) (y x) by rw [H]; exact isOpen_Ioo
  apply (Ioc_subset_Ioo_right (hy x hx.1).lt).antisymm
  simp_rw [subset_def, mem_Ioo, mem_Ioc]
  exact fun u hu => ⟨hu.1, Hy _ _ hx.1 hu.2⟩

@[deprecated (since := "2026-07-09")] alias countable_setOf_covBy_right :=
  countable_setOfPred_covBy_right

@[deprecated (since := "2026-07-09")] alias countable_setOf_covBy_left :=
  countable_setOfPred_covBy_left

/--
theorem `countable_of_isolated_left'` / 定理 `countable_of_isolated_left'`

English:
theorem countable_of_isolated_left'
  given: [SecondCountableTopology α]
  proof: by
  simpa only [← covBy_iff_Ioo_eq] using countable_setOfPred_covBy_left

中文:
定理 countable_of_isolated_left'
  条件: [第二可数拓扑 α]
  证明: by
  simpa only [← covBy_iff_Ioo_eq] using countable_setOfPred_covBy_left

Depends on / 依赖: countable_setOfPred_covBy_left, covBy_iff_Ioo_eq
-/
theorem countable_of_isolated_left' [SecondCountableTopology α] :
    Set.Countable { x : α | exists y, y < x ∧ Ioo y x = ∅ } := by
  simpa only [← covBy_iff_Ioo_eq] using countable_setOfPred_covBy_left

/-- Consider a disjoint family of intervals `(x, y)` with `x < y` in a second-countable space.
Then the family is countable.
This is not a straightforward consequence of second-countability as some of these intervals might be
empty (but in fact this can happen only for countably many of them). -/
@[to_dual none]
/--
theorem `Set.PairwiseDisjoint.countable_of_Ioo` / 定理 `Set.PairwiseDisjoint.countable_of_Ioo`

English:
theorem Set.PairwiseDisjoint.countable_of_Ioo
  statement: [SecondCountableTopology α]
  proof: have : (s \ { x | exists y, x ⋖ y }).Countable :=
    (h.subset sdiff_subset).countable_of_isOpen (fun _ _ => isOpen_Ioo) fun x hx =>
(not_covBy_iff_exists_mem_Ioo (h' _ hx.1)).1 mt (Exists.intro (y x)) hx.2
  this.of_sdiff countable_setOfPred_covBy_right

中文:
定理 集合.PairwiseDisjoint.countable_of_Ioo
  结论: [第二可数拓扑 α]
  证明: have : (s \ { x | exists y, x ⋖ y }).Countable :=
    (h.subset sdiff_subset).countable_of_isOpen (fun _ _ => isOpen_Ioo) fun x hx =>
(not_covBy_iff_exists_mem_Ioo (h' _ hx.1)).1 mt (Exists.intro (y x)) hx.2
  this.of_sdiff countable_setOfPred_covBy_right

Depends on / 依赖: Countable, Exists, Exists.intro, countable_of_isOpen, countable_setOfPred_covBy_right, h.subset, isOpen_Ioo, not_covBy_iff_exists_mem_Ioo, of_sdiff, sdiff_subset, subset, this.of_sdiff
-/
theorem Set.PairwiseDisjoint.countable_of_Ioo [SecondCountableTopology α]
    {y : α -> α} {s : Set α} (h : PairwiseDisjoint s fun x => Ioo x (y x))
    (h' : forall x in s, x < y x) : s.Countable :=
  have : (s \ { x | exists y, x ⋖ y }).Countable :=
    (h.subset sdiff_subset).countable_of_isOpen (fun _ _ => isOpen_Ioo) fun x hx =>
(not_covBy_iff_exists_mem_Ioo (h' _ hx.1)).1 mt (Exists.intro (y x)) hx.2
  this.of_sdiff countable_setOfPred_covBy_right

/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(x, ∞)` is separated above from `f x` is countable. We give
here a version relative to a set `t`. -/
@[to_dual
/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(-∞, x)` is separated below from `f x` is countable. We give
here a version relative to a set `t`. -/]
/--
theorem `countable_image_lt_image_Ioi_within` / 定理 `countable_image_lt_image_Ioi_within`

English:
theorem countable_image_lt_image_Ioi_within
  proof: by
  /- If the values of `f` are separated above on the right of `x`, there is an interval `(f x, z x)`
    which is not reached by `f`. This gives a family of disjoint open intervals in `α`. Such a
    family can only be countable as `α` is second-countable. -/
  nontriviality β
  have : Nonempty α

中文:
定理 countable_image_lt_image_Ioi_within
  证明: by
  /- If the values of `f` are separated above on the right of `x`, there is an interval `(f x, z x)`
    which is not reached by `f`. This gives a family of disjoint open intervals in `α`. Such a
    family can only be countable as `α` is second-countable. -/
  nontriviality β
  have : Nonempty α
-/
theorem countable_image_lt_image_Ioi_within
    [LinearOrder β] [SecondCountableTopology α] (t : Set β) (f : β -> α) :
    Set.Countable {x in t | exists z, f x < z ∧ forall y in t, x < y -> z <= f y} := by
  /- If the values of `f` are separated above on the right of `x`, there is an interval `(f x, z x)`
    which is not reached by `f`. This gives a family of disjoint open intervals in `α`. Such a
    family can only be countable as `α` is second-countable. -/
  nontriviality β
  have : Nonempty α := Nonempty.map f (by infer_instance)
  let s := {x in t | exists z, f x < z ∧ forall y in t, x < y -> z <= f y}
  have : forall x, x in s -> exists z, f x < z ∧ forall y in t, x < y -> z <= f y := fun x hx => hx.2
  -- choose `z x` such that `f` does not take the values in `(f x, z x)`.
  choose! z hz using this
  have I : InjOn f s := by
    apply StrictMonoOn.injOn
    intro x hx y hy hxy
    calc
      f x < z x := (hz x hx).1
      _ <= f y := (hz x hx).2 y hy.1 hxy
  -- show that `f s` is countable by arguing that a disjoint family of disjoint open intervals
  -- (the intervals `(f x, z x)`) is at most countable.
  have fs_count : (f '' s).Countable := by
    have A : (f '' s).PairwiseDisjoint fun x => Ioo x (z (invFunOn f s x)) := by
      rintro _ ⟨u, us, rfl⟩ _ ⟨v, vs, rfl⟩ huv
      wlog hle : u <= v generalizing u v
      · exact (this v vs u us huv.symm (le_of_not_ge hle)).symm
      have hlt : u < v := hle.lt_of_ne (ne_of_apply_ne _ huv)
      apply disjoint_iff_forall_ne.2
      rintro a ha b hb rfl
      simp only [I.leftInvOn_invFunOn us, I.leftInvOn_invFunOn vs] at ha hb
      exact lt_irrefl _ ((ha.2.trans_le ((hz u us).2 v vs.1 hlt)).trans hb.1)
    apply Set.PairwiseDisjoint.countable_of_Ioo A
    rintro _ ⟨y, ys, rfl⟩
    simpa only [I.leftInvOn_invFunOn ys] using (hz y ys).1
  exact MapsTo.countable_of_injOn (mapsTo_image f s) I fs_count

/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(x, ∞)` is separated above from `f x` is countable. -/
@[to_dual
/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(-∞, x)` is separated below from `f x` is countable. -/]
/--
theorem `countable_image_lt_image_Ioi` / 定理 `countable_image_lt_image_Ioi`

English:
theorem countable_image_lt_image_Ioi
  statement: [LinearOrder β] (f : β -> α)
  proof: by
  simpa using countable_image_lt_image_Ioi_within univ f

中文:
定理 countable_image_lt_image_Ioi
  结论: [线性序 β] (f : β -> α)
  证明: by
  simpa using countable_image_lt_image_Ioi_within univ f

Depends on / 依赖: countable_image_lt_image_Ioi_within
-/
theorem countable_image_lt_image_Ioi [LinearOrder β] (f : β -> α)
    [SecondCountableTopology α] : Set.Countable {x | exists z, f x < z ∧ forall y, x < y -> z <= f y} := by
  simpa using countable_image_lt_image_Ioi_within univ f

/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(x, ∞)` is separated below from `f x` is countable. We give
here a version relative to a set `t`. -/
@[to_dual
/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(-∞, x)` is separated above from `f x` is countable. We give
here a version relative to a set `t`. -/]
/--
theorem `countable_image_gt_image_Ioi_within` / 定理 `countable_image_gt_image_Ioi_within`

English:
theorem countable_image_gt_image_Ioi_within
  proof: countable_image_lt_image_Ioi_within (α := αᵒᵈ) t f

中文:
定理 countable_image_gt_image_Ioi_within
  证明: countable_image_lt_image_Ioi_within (α := αᵒᵈ) t f

Depends on / 依赖: countable_image_lt_image_Ioi_within
-/
theorem countable_image_gt_image_Ioi_within
    [LinearOrder β] [SecondCountableTopology α] (t : Set β) (f : β -> α) :
    Set.Countable {x in t | exists z, z < f x ∧ forall y in t, x < y -> f y <= z} :=
  countable_image_lt_image_Ioi_within (α := αᵒᵈ) t f

/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(x, ∞)` is separated below from `f x` is countable. -/
@[to_dual
/-- For a function taking values in a second countable space, the set of points `x` for
which the image under `f` of `(-∞, x)` is separated above from `f x` is countable. -/]
/--
theorem `countable_image_gt_image_Ioi` / 定理 `countable_image_gt_image_Ioi`

English:
theorem countable_image_gt_image_Ioi
  statement: [LinearOrder β] (f : β -> α)
  proof: countable_image_lt_image_Ioi (α := αᵒᵈ) f

@[to_dual]

中文:
定理 countable_image_gt_image_Ioi
  结论: [线性序 β] (f : β -> α)
  证明: countable_image_lt_image_Ioi (α := αᵒᵈ) f

@[to_dual]

Depends on / 依赖: countable_image_lt_image_Ioi
-/
theorem countable_image_gt_image_Ioi [LinearOrder β] (f : β -> α)
    [SecondCountableTopology α] : Set.Countable {x | exists z, z < f x ∧ forall y, x < y -> f y <= z} :=
  countable_image_lt_image_Ioi (α := αᵒᵈ) f

@[to_dual]
/--
Instance `instIsCountablyGenerated_atTop` / 实例 `instIsCountablyGenerated_atTop`

English:
instance instIsCountablyGenerated_atTop
  signature: [SeparableSpace α]
  body: by
  obtain (h | ⟨x, hx⟩) := Set.eq_empty_or_nonempty {x : α | IsTop x}
  · obtain ⟨s, s_count, hs⟩ := exists_countable_dense α
    have : atTop = generate (Ici '' s) := by
      refine atTop_eq_generate_of_not_bddAbove fun ⟨x, hx⟩ => ?_
      simp only [eq_empty_iff_forall_notMem, IsTop, mem_ofPred

中文:
实例 instIsCountablyGenerated_atTop
  签名: [可分空间 α]
  定义体: by
  obtain (h | ⟨x, hx⟩) := Set.eq_empty_or_nonempty {x : α | IsTop x}
  · obtain ⟨s, s_count, hs⟩ := exists_countable_dense α
    have : atTop = generate (Ici '' s) := by
      refine atTop_eq_generate_of_not_bddAbove fun ⟨x, hx⟩ => ?_
      simp only [eq_empty_iff_forall_notMem, IsTop, mem_ofPred

Depends on / 依赖: Set.eq_empty_or_nonempty, atTop_eq_generate_of_not_bddAbove, atTop_eq_pure_of_isTop, eq_empty_iff_forall_notMem, eq_empty_or_nonempty, exists_countable_dense, exists_mem_open, generate, hs.exists_mem_open, isCountablyGenerated_pure, isOpen_Ioi, mem_ofPred_eq, not_forall, not_gt, not_le, s_count, s_count.image
-/
instance instIsCountablyGenerated_atTop [SeparableSpace α] :
    IsCountablyGenerated (atTop : Filter α) := by
  obtain (h | ⟨x, hx⟩) := Set.eq_empty_or_nonempty {x : α | IsTop x}
  · obtain ⟨s, s_count, hs⟩ := exists_countable_dense α
    have : atTop = generate (Ici '' s) := by
      refine atTop_eq_generate_of_not_bddAbove fun ⟨x, hx⟩ => ?_
      simp only [eq_empty_iff_forall_notMem, IsTop, mem_ofPred_eq, not_forall, not_le] at h
      obtain ⟨y, hy, hxy⟩ := hs.exists_mem_open isOpen_Ioi (h x)
      exact (hx hy).not_gt hxy
    rw [this]
    exact ⟨_, s_count.image _, rfl⟩
  · rw [atTop_eq_pure_of_isTop hx]
    exact isCountablyGenerated_pure x

end OrderTopology

section Pi

/-!
### Intervals in `Π i, X i` belong to `𝓝 x`

For each lemma `pi_Ixx_mem_nhds` we add a non-dependent version `pi_Ixx_mem_nhds'` because
sometimes Lean fails to unify different instances while trying to apply the dependent version to,
e.g., `ι → ℝ`.
-/

variable [OrderTopology α] {ι : Type*} {X : ι -> Type*} [Finite ι] [forall i, LinearOrder (X i)]
  [forall i, TopologicalSpace (X i)] [forall i, OrderTopology (X i)] {a b x : forall i, X i} {a' b' x' : ι -> α}

@[to_dual]
/--
theorem `pi_Iic_mem_nhds` / 定理 `pi_Iic_mem_nhds`

English:
theorem pi_Iic_mem_nhds
  given: (ha : forall i, x i < a i)
  statement: Iic a in 𝓝 x
  proof: pi_univ_Iic a ▸ set_pi_mem_nhds (Set.toFinite _) fun _ _ => Iic_mem_nhds (ha _)

@[to_dual]

中文:
定理 pi_Iic_mem_nhds
  条件: (ha : 对任意 i, x i < a i)
  结论: 左无界右闭区间 a in 𝓝 x
  证明: pi_univ_Iic a ▸ set_pi_mem_nhds (Set.toFinite _) fun _ _ => Iic_mem_nhds (ha _)

@[to_dual]

Depends on / 依赖: Iic_mem_nhds, Set.toFinite, pi_univ_Iic, set_pi_mem_nhds, toFinite
-/
theorem pi_Iic_mem_nhds (ha : forall i, x i < a i) : Iic a in 𝓝 x :=
  pi_univ_Iic a ▸ set_pi_mem_nhds (Set.toFinite _) fun _ _ => Iic_mem_nhds (ha _)

@[to_dual]
/--
theorem `pi_Iic_mem_nhds'` / 定理 `pi_Iic_mem_nhds'`

English:
theorem pi_Iic_mem_nhds'
  given: (ha : forall i, x' i < a' i)
  statement: Iic a' in 𝓝 x'
  proof: pi_Iic_mem_nhds ha

@[to_dual self (reorder := a b, ha hb)]

中文:
定理 pi_Iic_mem_nhds'
  条件: (ha : 对任意 i, x' i < a' i)
  结论: 左无界右闭区间 a' in 𝓝 x'
  证明: pi_Iic_mem_nhds ha

@[to_dual self (reorder := a b, ha hb)]

Depends on / 依赖: pi_Iic_mem_nhds
-/
theorem pi_Iic_mem_nhds' (ha : forall i, x' i < a' i) : Iic a' in 𝓝 x' :=
  pi_Iic_mem_nhds ha

@[to_dual self (reorder := a b, ha hb)]
/--
theorem `pi_Icc_mem_nhds` / 定理 `pi_Icc_mem_nhds`

English:
theorem pi_Icc_mem_nhds
  given: (ha : forall i, a i < x i) (hb : forall i, x i < b i)
  statement: Icc a b in 𝓝 x
  proof: pi_univ_Icc a b ▸ set_pi_mem_nhds finite_univ fun _ _ => Icc_mem_nhds (ha _) (hb _)

@[to_dual self (reorder := a' b', ha hb)]

中文:
定理 pi_Icc_mem_nhds
  条件: (ha : 对任意 i, a i < x i) (hb : 对任意 i, x i < b i)
  结论: 闭区间 a b in 𝓝 x
  证明: pi_univ_Icc a b ▸ set_pi_mem_nhds finite_univ fun _ _ => Icc_mem_nhds (ha _) (hb _)

@[to_dual self (reorder := a' b', ha hb)]

Depends on / 依赖: Icc_mem_nhds, finite_univ, pi_univ_Icc, set_pi_mem_nhds
-/
theorem pi_Icc_mem_nhds (ha : forall i, a i < x i) (hb : forall i, x i < b i) : Icc a b in 𝓝 x :=
  pi_univ_Icc a b ▸ set_pi_mem_nhds finite_univ fun _ _ => Icc_mem_nhds (ha _) (hb _)

@[to_dual self (reorder := a' b', ha hb)]
/--
theorem `pi_Icc_mem_nhds'` / 定理 `pi_Icc_mem_nhds'`

English:
theorem pi_Icc_mem_nhds'
  given: (ha : forall i, a' i < x' i) (hb : forall i, x' i < b' i)
  statement: Icc a' b' in 𝓝 x'
  proof: pi_Icc_mem_nhds ha hb

中文:
定理 pi_Icc_mem_nhds'
  条件: (ha : 对任意 i, a' i < x' i) (hb : 对任意 i, x' i < b' i)
  结论: 闭区间 a' b' in 𝓝 x'
  证明: pi_Icc_mem_nhds ha hb

Depends on / 依赖: pi_Icc_mem_nhds
-/
theorem pi_Icc_mem_nhds' (ha : forall i, a' i < x' i) (hb : forall i, x' i < b' i) : Icc a' b' in 𝓝 x' :=
  pi_Icc_mem_nhds ha hb

variable [Nonempty ι]

@[to_dual]
/--
theorem `pi_Iio_mem_nhds` / 定理 `pi_Iio_mem_nhds`

English:
theorem pi_Iio_mem_nhds
  given: (ha : forall i, x i < a i)
  statement: Iio a in 𝓝 x
  proof: mem_of_superset
  (set_pi_mem_nhds finite_univ fun i _ => Iio_mem_nhds (ha i)) (pi_univ_Iio_subset a)

@[to_dual]

中文:
定理 pi_Iio_mem_nhds
  条件: (ha : 对任意 i, x i < a i)
  结论: 左无界右开区间 a in 𝓝 x
  证明: mem_of_superset
  (set_pi_mem_nhds finite_univ fun i _ => Iio_mem_nhds (ha i)) (pi_univ_Iio_subset a)

@[to_dual]

Depends on / 依赖: mem_of_superset
-/
theorem pi_Iio_mem_nhds (ha : forall i, x i < a i) : Iio a in 𝓝 x := mem_of_superset
  (set_pi_mem_nhds finite_univ fun i _ => Iio_mem_nhds (ha i)) (pi_univ_Iio_subset a)

@[to_dual]
/--
theorem `pi_Iio_mem_nhds'` / 定理 `pi_Iio_mem_nhds'`

English:
theorem pi_Iio_mem_nhds'
  given: (ha : forall i, x' i < a' i)
  statement: Iio a' in 𝓝 x'
  proof: pi_Iio_mem_nhds ha

@[to_dual]

中文:
定理 pi_Iio_mem_nhds'
  条件: (ha : 对任意 i, x' i < a' i)
  结论: 左无界右开区间 a' in 𝓝 x'
  证明: pi_Iio_mem_nhds ha

@[to_dual]

Depends on / 依赖: pi_Iio_mem_nhds
-/
theorem pi_Iio_mem_nhds' (ha : forall i, x' i < a' i) : Iio a' in 𝓝 x' :=
  pi_Iio_mem_nhds ha

@[to_dual]
/--
theorem `pi_Ioc_mem_nhds` / 定理 `pi_Ioc_mem_nhds`

English:
theorem pi_Ioc_mem_nhds
  given: (ha : forall i, a i < x i) (hb : forall i, x i < b i)
  statement: Ioc a b in 𝓝 x
  proof: by
  refine mem_of_superset (set_pi_mem_nhds Set.finite_univ fun i _ => ?_) (pi_univ_Ioc_subset a b)
  exact Ioc_mem_nhds (ha i) (hb i)

@[to_dual]

中文:
定理 pi_Ioc_mem_nhds
  条件: (ha : 对任意 i, a i < x i) (hb : 对任意 i, x i < b i)
  结论: 左开右闭区间 a b in 𝓝 x
  证明: by
  refine mem_of_superset (set_pi_mem_nhds Set.finite_univ fun i _ => ?_) (pi_univ_Ioc_subset a b)
  exact Ioc_mem_nhds (ha i) (hb i)

@[to_dual]

Depends on / 依赖: Ioc_mem_nhds, Set.finite_univ, finite_univ, mem_of_superset, pi_univ_Ioc_subset, set_pi_mem_nhds
-/
theorem pi_Ioc_mem_nhds (ha : forall i, a i < x i) (hb : forall i, x i < b i) : Ioc a b in 𝓝 x := by
  refine mem_of_superset (set_pi_mem_nhds Set.finite_univ fun i _ => ?_) (pi_univ_Ioc_subset a b)
  exact Ioc_mem_nhds (ha i) (hb i)

@[to_dual]
/--
theorem `pi_Ioc_mem_nhds'` / 定理 `pi_Ioc_mem_nhds'`

English:
theorem pi_Ioc_mem_nhds'
  given: (ha : forall i, a' i < x' i) (hb : forall i, x' i < b' i)
  statement: Ioc a' b' in 𝓝 x'
  proof: pi_Ioc_mem_nhds ha hb

@[to_dual self (reorder := a b, ha hb)]

中文:
定理 pi_Ioc_mem_nhds'
  条件: (ha : 对任意 i, a' i < x' i) (hb : 对任意 i, x' i < b' i)
  结论: 左开右闭区间 a' b' in 𝓝 x'
  证明: pi_Ioc_mem_nhds ha hb

@[to_dual self (reorder := a b, ha hb)]

Depends on / 依赖: pi_Ioc_mem_nhds
-/
theorem pi_Ioc_mem_nhds' (ha : forall i, a' i < x' i) (hb : forall i, x' i < b' i) : Ioc a' b' in 𝓝 x' :=
  pi_Ioc_mem_nhds ha hb

@[to_dual self (reorder := a b, ha hb)]
/--
theorem `pi_Ioo_mem_nhds` / 定理 `pi_Ioo_mem_nhds`

English:
theorem pi_Ioo_mem_nhds
  given: (ha : forall i, a i < x i) (hb : forall i, x i < b i)
  statement: Ioo a b in 𝓝 x
  proof: by
  refine mem_of_superset (set_pi_mem_nhds Set.finite_univ fun i _ => ?_) (pi_univ_Ioo_subset a b)
  exact Ioo_mem_nhds (ha i) (hb i)

@[to_dual self (reorder := a' b', ha hb)]

中文:
定理 pi_Ioo_mem_nhds
  条件: (ha : 对任意 i, a i < x i) (hb : 对任意 i, x i < b i)
  结论: 开区间 a b in 𝓝 x
  证明: by
  refine mem_of_superset (set_pi_mem_nhds Set.finite_univ fun i _ => ?_) (pi_univ_Ioo_subset a b)
  exact Ioo_mem_nhds (ha i) (hb i)

@[to_dual self (reorder := a' b', ha hb)]

Depends on / 依赖: Ioo_mem_nhds, Set.finite_univ, finite_univ, mem_of_superset, pi_univ_Ioo_subset, set_pi_mem_nhds
-/
theorem pi_Ioo_mem_nhds (ha : forall i, a i < x i) (hb : forall i, x i < b i) : Ioo a b in 𝓝 x := by
  refine mem_of_superset (set_pi_mem_nhds Set.finite_univ fun i _ => ?_) (pi_univ_Ioo_subset a b)
  exact Ioo_mem_nhds (ha i) (hb i)

@[to_dual self (reorder := a' b', ha hb)]
/--
theorem `pi_Ioo_mem_nhds'` / 定理 `pi_Ioo_mem_nhds'`

English:
theorem pi_Ioo_mem_nhds'
  given: (ha : forall i, a' i < x' i) (hb : forall i, x' i < b' i)
  statement: Ioo a' b' in 𝓝 x'
  proof: pi_Ioo_mem_nhds ha hb

中文:
定理 pi_Ioo_mem_nhds'
  条件: (ha : 对任意 i, a' i < x' i) (hb : 对任意 i, x' i < b' i)
  结论: 开区间 a' b' in 𝓝 x'
  证明: pi_Ioo_mem_nhds ha hb

Depends on / 依赖: pi_Ioo_mem_nhds
-/
theorem pi_Ioo_mem_nhds' (ha : forall i, a' i < x' i) (hb : forall i, x' i < b' i) : Ioo a' b' in 𝓝 x' :=
  pi_Ioo_mem_nhds ha hb

end Pi

end LinearOrder

section ConditionallyCompleteLinearOrder
variable {X : Type*} [ConditionallyCompleteLinearOrder X] [TopologicalSpace X] [OrderTopology X]
variable {Y : Type*} [ConditionallyCompleteLinearOrder Y] [TopologicalSpace Y] [OrderTopology Y]
variable {f : X -> Y} {x : X}

/--
lemma `LeftOrdContinuous.continuousWithinAt_Iic` / 引理 `LeftOrdContinuous.continuousWithinAt_Iic`

English:
lemma LeftOrdContinuous.continuousWithinAt_Iic
  given: (hf : LeftOrdContinuous f)
  proof: by
  rw [ContinuousWithinAt]; rw [OrderTopology.topology_eq_generate_intervals (α := Y)]
  simp_rw [TopologicalSpace.tendsto_nhds_generateFrom_iff, mem_nhdsWithin]
  rintro V ⟨z, rfl | rfl⟩ hxz
  -- The case `V = Ioi z`.
  · obtain hz | ne := em' (f ⁻¹' Iic z).Nonempty
    · exact ⟨univ, isOpen_univ

中文:
引理 LeftOrdContinuous.continuousWithinAt_Iic
  条件: (hf : LeftOrdContinuous f)
  证明: by
  rw [ContinuousWithinAt]; rw [OrderTopology.topology_eq_generate_intervals (α := Y)]
  simp_rw [TopologicalSpace.tendsto_nhds_generateFrom_iff, mem_nhdsWithin]
  rintro V ⟨z, rfl | rfl⟩ hxz
  -- The case `V = Ioi z`.
  · obtain hz | ne := em' (f ⁻¹' Iic z).Nonempty
    · exact ⟨univ, isOpen_univ

Depends on / 依赖: ContinuousWithinAt, OrderTopology, OrderTopology.topology_eq_generate_intervals, TopologicalSpace, TopologicalSpace.tendsto_nhds_generateFrom_iff, mem_nhdsWithin, simp_rw, tendsto_nhds_generateFrom_iff, topology_eq_generate_intervals
-/
lemma LeftOrdContinuous.continuousWithinAt_Iic (hf : LeftOrdContinuous f) :
    ContinuousWithinAt f (Iic x) x := by
  rw [ContinuousWithinAt]; rw [OrderTopology.topology_eq_generate_intervals (α := Y)]
  simp_rw [TopologicalSpace.tendsto_nhds_generateFrom_iff, mem_nhdsWithin]
  rintro V ⟨z, rfl | rfl⟩ hxz
  -- The case `V = Ioi z`.
  · obtain hz | ne := em' (f ⁻¹' Iic z).Nonempty
    · exact ⟨univ, isOpen_univ, mem_univ _, fun a ha => not_le.mp fun h => hz ⟨a, h⟩⟩
    have bdd : BddAbove (f ⁻¹' Iic z) := ⟨x, fun a ha => (hf.mono.reflect_lt (ha.trans_lt hxz)).le⟩
    have u_eq : Ioi (sSup (f ⁻¹' Iic z)) = f ⁻¹' Ioi z := by
      refine Set.ext fun a => ⟨fun ha => ?_, fun ha => ?_⟩
      · exact not_le.mp fun h => ha.not_ge (le_csSup bdd h)
      · apply lt_of_le_of_ne
        · exact csSup_le ne fun b hb => (hf.mono.reflect_lt (hb.trans_lt ha)).le
        · have : sSup (f '' f ⁻¹' Iic z) <= z := csSup_le (.image _ ne) fun _ ⟨b, hb, heq⟩ => heq ▸ hb
          exact fun h => this.not_gt ((h ▸ ha).trans_eq (hf.map_csSup ne bdd))
    exact ⟨f ⁻¹' Ioi z, u_eq ▸ isOpen_Ioi, hxz, fun _ h => h.1⟩
  -- The case `V = Iio z`.
  · exact ⟨univ, isOpen_univ, trivial, fun a ha => (hf.mono ha.2).trans_lt hxz⟩

/-- An order-theoretically right-continuous function is topologically right-continuous, assuming
the function is between conditionally complete linear orders with order topologies. -/
@[to_dual existing]
/--
lemma `RightOrdContinuous.continuousWithinAt_Ici` / 引理 `RightOrdContinuous.continuousWithinAt_Ici`

English:
lemma RightOrdContinuous.continuousWithinAt_Ici
  given: (hf : RightOrdContinuous f)
  proof: hf.dual.continuousWithinAt_Iic

中文:
引理 RightOrdContinuous.continuousWithinAt_Ici
  条件: (hf : RightOrdContinuous f)
  证明: hf.dual.continuousWithinAt_Iic

Depends on / 依赖: continuousWithinAt_Iic, hf.dual.continuousWithinAt_Iic
-/
lemma RightOrdContinuous.continuousWithinAt_Ici (hf : RightOrdContinuous f) :
    ContinuousWithinAt f (Ici x) x := hf.dual.continuousWithinAt_Iic

/--
lemma `Continuous.of_ordContinuous` / 引理 `Continuous.of_ordContinuous`

English:
lemma Continuous.of_ordContinuous
  given: (hl : LeftOrdContinuous f) (hr : RightOrdContinuous f)
  proof: continuous_iff_continuousAt.mpr fun _ => continuousAt_iff_continuous_left_right.mpr
    ⟨hl.continuousWithinAt_Iic, hr.continuousWithinAt_Ici⟩

中文:
引理 连续.of_ordContinuous
  条件: (hl : LeftOrdContinuous f) (hr : RightOrdContinuous f)
  证明: continuous_iff_continuousAt.mpr fun _ => continuousAt_iff_continuous_left_right.mpr
    ⟨hl.continuousWithinAt_Iic, hr.continuousWithinAt_Ici⟩

Depends on / 依赖: continuousAt_iff_continuous_left_right, continuousAt_iff_continuous_left_right.mpr, continuousWithinAt_Ici, continuousWithinAt_Iic, continuous_iff_continuousAt, continuous_iff_continuousAt.mpr, hl.continuousWithinAt_Iic, hr.continuousWithinAt_Ici
-/
lemma Continuous.of_ordContinuous (hl : LeftOrdContinuous f) (hr : RightOrdContinuous f) :
    Continuous f :=
  continuous_iff_continuousAt.mpr fun _ => continuousAt_iff_continuous_left_right.mpr
    ⟨hl.continuousWithinAt_Iic, hr.continuousWithinAt_Ici⟩

end ConditionallyCompleteLinearOrder
