/-
Copyright (c) 2023 Christopher Hoskin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christopher Hoskin
-/
module

public import Mathlib.Order.Hom.CompleteLattice
public import Mathlib.Topology.Homeomorph.Defs
public import Mathlib.Topology.Order.Lattice

/-!
# Lower and Upper topology

This file introduces the lower topology on a preorder as the topology generated by the complements
of the left-closed right-infinite intervals.

For completeness we also introduce the dual upper topology, generated by the complements of the
right-closed left-infinite intervals.

## Main statements

- `IsLower.t0Space` - the lower topology on a partial order is T₀
- `IsLower.isTopologicalBasis` - the complements of the upper closures of finite
  subsets form a basis for the lower topology
- `IsLower.continuousInf` - the inf map is continuous with respect to the lower topology

## Implementation notes

A type synonym `WithLower` is introduced and for a preorder `α`, `WithLower α`
is made an instance of `TopologicalSpace` by the topology generated by the complements of the
closed intervals to infinity.

We define a mixin class `IsLower` for the class of types which are both a preorder and a
topology and where the topology is generated by the complements of the closed intervals to infinity.
It is shown that `WithLower α` is an instance of `IsLower`.

Similarly for the upper topology.

## Motivation

The lower topology is used with the `Scott` topology to define the Lawson topology. The restriction
of the lower topology to the spectrum of a complete lattice coincides with the hull-kernel topology.

## References

* [Gierz et al, *A Compendium of Continuous Lattices*][GierzEtAl1980]

## Tags

lower topology, upper topology, preorder
-/

@[expose] public section

open Set TopologicalSpace Topology

namespace Topology

/--
The lower topology is the topology generated by the complements of the left-closed right-infinite
intervals.
-/
@[instance_reducible]
/--
Definition of `lower` / `lower` 的定义

English:
definition lower
  signature: (α : Type*) [Preorder α]
  body: generateFrom {s | exists a, (Ici a)ᶜ = s}

中文:
定义 lower
  签名: (α : 类型) [预序 α]
  定义体: generateFrom {s | exists a, (Ici a)ᶜ = s}

Depends on / 依赖: generateFrom
-/
def lower (α : Type*) [Preorder α] : TopologicalSpace α := generateFrom {s | exists a, (Ici a)ᶜ = s}

/--
The upper topology is the topology generated by the complements of the right-closed left-infinite
intervals.
-/
@[instance_reducible]
/--
Definition of `upper` / `upper` 的定义

English:
definition upper
  signature: (α : Type*) [Preorder α]
  body: generateFrom {s | exists a, (Iic a)ᶜ = s}

中文:
定义 upper
  签名: (α : 类型) [预序 α]
  定义体: generateFrom {s | exists a, (Iic a)ᶜ = s}

Depends on / 依赖: generateFrom
-/
def upper (α : Type*) [Preorder α] : TopologicalSpace α := generateFrom {s | exists a, (Iic a)ᶜ = s}

/--
Definition of `WithLower` / `WithLower` 的定义

English:
definition WithLower
  signature: (α : Type*)
  body: α

中文:
定义 WithLower
  签名: (α : 类型)
  定义体: α
-/
def WithLower (α : Type*) := α

variable {α β : Type*}

namespace WithLower

/--
Definition of `toLower` / `toLower` 的定义

English:
definition toLower
  signature: : α ≃ WithLower α
  body: Equiv.refl _

中文:
定义 toLower
  签名: : α ≃ WithLower α
  定义体: Equiv.refl _
-/
@[match_pattern] def toLower : α ≃ WithLower α := Equiv.refl _

/--
Definition of `ofLower` / `ofLower` 的定义

English:
definition ofLower
  signature: : WithLower α ≃ α
  body: Equiv.refl _

中文:
定义 ofLower
  签名: : WithLower α ≃ α
  定义体: Equiv.refl _
-/
@[match_pattern] def ofLower : WithLower α ≃ α := Equiv.refl _

/--
lemma `toLower_symm` / 引理 `toLower_symm`

English:
lemma toLower_symm
  statement: (@toLower α).symm = ofLower
  proof: rfl

中文:
引理 toLower_symm
  结论: (@toLower α).symm = ofLower
  证明: rfl
-/
@[simp] lemma toLower_symm : (@toLower α).symm = ofLower := rfl
/--
lemma `ofLower_symm` / 引理 `ofLower_symm`

English:
lemma ofLower_symm
  statement: (@ofLower α).symm = toLower
  proof: rfl

中文:
引理 ofLower_symm
  结论: (@ofLower α).symm = toLower
  证明: rfl
-/
@[simp] lemma ofLower_symm : (@ofLower α).symm = toLower := rfl
/--
lemma `toLower_ofLower` / 引理 `toLower_ofLower`

English:
lemma toLower_ofLower
  given: (a : WithLower α)
  statement: toLower (ofLower a) = a
  proof: rfl

中文:
引理 toLower_ofLower
  条件: (a : WithLower α)
  结论: toLower (ofLower a) = a
  证明: rfl
-/
@[simp] lemma toLower_ofLower (a : WithLower α) : toLower (ofLower a) = a := rfl

/--
lemma `ofLower_toLower` / 引理 `ofLower_toLower`

English:
lemma ofLower_toLower
  given: (a : α)
  statement: ofLower (toLower a) = a
  proof: rfl

中文:
引理 ofLower_toLower
  条件: (a : α)
  结论: ofLower (toLower a) = a
  证明: rfl
-/
@[simp] lemma ofLower_toLower (a : α) : ofLower (toLower a) = a := rfl

/--
lemma `toLower_inj` / 引理 `toLower_inj`

English:
lemma toLower_inj
  given: {a b : α}
  statement: toLower a = toLower b ↔ a = b
  proof: Iff.rfl

中文:
引理 toLower_inj
  条件: {a b : α}
  结论: toLower a = toLower b ↔ a = b
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
lemma toLower_inj {a b : α} : toLower a = toLower b ↔ a = b := Iff.rfl

/--
theorem `ofLower_inj` / 定理 `ofLower_inj`

English:
theorem ofLower_inj
  given: {a b : WithLower α}
  statement: ofLower a = ofLower b ↔ a = b
  proof: Iff.rfl

中文:
定理 ofLower_inj
  条件: {a b : WithLower α}
  结论: ofLower a = ofLower b ↔ a = b
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
theorem ofLower_inj {a b : WithLower α} : ofLower a = ofLower b ↔ a = b :=
  Iff.rfl

/-- A recursor for `WithLower`. Use as `induction x`. -/
@[elab_as_elim, cases_eliminator, induction_eliminator]
/--
Definition of `rec` / `rec` 的定义

English:
definition rec
  signature: {motive : WithLower α -> Sort*} (toLower : forall a, motive (toLower a))
  body: fun a =>
  toLower (ofLower a)

中文:
定义 rec
  签名: {motive : WithLower α -> 类型层*} (toLower : 对任意 a, motive (toLower a))
  定义体: fun a =>
  toLower (ofLower a)
-/
protected def rec {motive : WithLower α -> Sort*} (toLower : forall a, motive (toLower a)) :
    forall a, motive a := fun a =>
  toLower (ofLower a)

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [Nonempty
  signature: α] : Nonempty (WithLower α)
  body: ‹Nonempty α›

中文:
实例 [非空
  签名: α] : 非空 (WithLower α)
  定义体: ‹Nonempty α›

Depends on / 依赖: Nonempty
-/
instance [Nonempty α] : Nonempty (WithLower α) := ‹Nonempty α›
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [Inhabited
  signature: α] : Inhabited (WithLower α)
  body: ‹Inhabited α›

中文:
实例 [可居
  签名: α] : 可居 (WithLower α)
  定义体: ‹Inhabited α›

Depends on / 依赖: Inhabited
-/
instance [Inhabited α] : Inhabited (WithLower α) := ‹Inhabited α›

section Preorder

variable [Preorder α] {s : Set α}

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: Preorder (WithLower α)
  body: ‹Preorder α›

中文:
实例 :
  签名: 预序 (WithLower α)
  定义体: ‹Preorder α›

Depends on / 依赖: Preorder
-/
instance : Preorder (WithLower α) := ‹Preorder α›
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: TopologicalSpace (WithLower α)
  body: lower (WithLower α)

中文:
实例 :
  签名: 拓扑空间 (WithLower α)
  定义体: lower (WithLower α)

Depends on / 依赖: WithLower
-/
instance : TopologicalSpace (WithLower α) := lower (WithLower α)

/--
lemma `toLower_le_toLower` / 引理 `toLower_le_toLower`

English:
lemma toLower_le_toLower
  given: {x y : α}
  statement: toLower x <= toLower y ↔ x <= y
  proof: .rfl

中文:
引理 toLower_le_toLower
  条件: {x y : α}
  结论: toLower x <= toLower y ↔ x <= y
  证明: .rfl
-/
@[simp] lemma toLower_le_toLower {x y : α} : toLower x <= toLower y ↔ x <= y := .rfl
/--
lemma `toLower_lt_toLower` / 引理 `toLower_lt_toLower`

English:
lemma toLower_lt_toLower
  given: {x y : α}
  statement: toLower x < toLower y ↔ x < y
  proof: .rfl

中文:
引理 toLower_lt_toLower
  条件: {x y : α}
  结论: toLower x < toLower y ↔ x < y
  证明: .rfl
-/
@[simp] lemma toLower_lt_toLower {x y : α} : toLower x < toLower y ↔ x < y := .rfl
/--
lemma `ofLower_le_ofLower` / 引理 `ofLower_le_ofLower`

English:
lemma ofLower_le_ofLower
  given: {x y : WithLower α}
  statement: ofLower x <= ofLower y ↔ x <= y
  proof: .rfl

中文:
引理 ofLower_le_ofLower
  条件: {x y : WithLower α}
  结论: ofLower x <= ofLower y ↔ x <= y
  证明: .rfl
-/
@[simp] lemma ofLower_le_ofLower {x y : WithLower α} : ofLower x <= ofLower y ↔ x <= y := .rfl
/--
lemma `ofLower_lt_ofLower` / 引理 `ofLower_lt_ofLower`

English:
lemma ofLower_lt_ofLower
  given: {x y : WithLower α}
  statement: ofLower x < ofLower y ↔ x < y
  proof: .rfl

中文:
引理 ofLower_lt_ofLower
  条件: {x y : WithLower α}
  结论: ofLower x < ofLower y ↔ x < y
  证明: .rfl
-/
@[simp] lemma ofLower_lt_ofLower {x y : WithLower α} : ofLower x < ofLower y ↔ x < y := .rfl

/--
lemma `isOpen_preimage_ofLower` / 引理 `isOpen_preimage_ofLower`

English:
lemma isOpen_preimage_ofLower
  statement: IsOpen (ofLower ⁻¹' s) ↔ IsOpen[lower α] s
  proof: Iff.rfl

中文:
引理 isOpen_preimage_ofLower
  结论: 是开集 (ofLower ⁻¹' s) ↔ 是开集[lower α] s
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
lemma isOpen_preimage_ofLower : IsOpen (ofLower ⁻¹' s) ↔ IsOpen[lower α] s := Iff.rfl

/--
lemma `isOpen_def` / 引理 `isOpen_def`

English:
lemma isOpen_def
  given: (T : Set (WithLower α))
  statement: IsOpen T ↔ IsOpen[lower α] (WithLower.toLower ⁻¹' T)
  proof: Iff.rfl

中文:
引理 isOpen_def
  条件: (T : 集合 (WithLower α))
  结论: 是开集 T ↔ 是开集[lower α] (WithLower.toLower ⁻¹' T)
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
lemma isOpen_def (T : Set (WithLower α)) : IsOpen T ↔ IsOpen[lower α] (WithLower.toLower ⁻¹' T) :=
  Iff.rfl

/--
theorem `continuous_toLower` / 定理 `continuous_toLower`

English:
theorem continuous_toLower
  given: [TopologicalSpace α] [ClosedIciTopology α]
  proof: continuous_generateFrom_iff.mpr by rintro _ ⟨a, rfl⟩; exact isClosed_Ici.isOpen_compl

中文:
定理 continuous_toLower
  条件: [拓扑空间 α] [ClosedIci拓扑 α]
  证明: continuous_generateFrom_iff.mpr by rintro _ ⟨a, rfl⟩; exact isClosed_Ici.isOpen_compl

Depends on / 依赖: continuous_generateFrom_iff, continuous_generateFrom_iff.mpr, isClosed_Ici, isClosed_Ici.isOpen_compl, isOpen_compl
-/
theorem continuous_toLower [TopologicalSpace α] [ClosedIciTopology α] :
    Continuous (toLower : α -> WithLower α) :=
continuous_generateFrom_iff.mpr by rintro _ ⟨a, rfl⟩; exact isClosed_Ici.isOpen_compl

end Preorder

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [PartialOrder
  signature: α] : PartialOrder (WithLower α)
  body: ‹PartialOrder α›

中文:
实例 [偏序
  签名: α] : 偏序 (WithLower α)
  定义体: ‹PartialOrder α›

Depends on / 依赖: PartialOrder
-/
instance [PartialOrder α] : PartialOrder (WithLower α) := ‹PartialOrder α›
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [LinearOrder
  signature: α] : LinearOrder (WithLower α)
  body: ‹LinearOrder α›

中文:
实例 [线性序
  签名: α] : 线性序 (WithLower α)
  定义体: ‹LinearOrder α›

Depends on / 依赖: LinearOrder
-/
instance [LinearOrder α] : LinearOrder (WithLower α) := ‹LinearOrder α›

end WithLower

/--
Definition of `WithUpper` / `WithUpper` 的定义

English:
definition WithUpper
  signature: (α : Type*)
  body: α

中文:
定义 WithUpper
  签名: (α : 类型)
  定义体: α
-/
def WithUpper (α : Type*) := α
namespace WithUpper

/--
Definition of `toUpper` / `toUpper` 的定义

English:
definition toUpper
  signature: : α ≃ WithUpper α
  body: Equiv.refl _

中文:
定义 toUpper
  签名: : α ≃ WithUpper α
  定义体: Equiv.refl _
-/
@[match_pattern] def toUpper : α ≃ WithUpper α := Equiv.refl _

/--
Definition of `ofUpper` / `ofUpper` 的定义

English:
definition ofUpper
  signature: : WithUpper α ≃ α
  body: Equiv.refl _

中文:
定义 ofUpper
  签名: : WithUpper α ≃ α
  定义体: Equiv.refl _
-/
@[match_pattern] def ofUpper : WithUpper α ≃ α := Equiv.refl _

/--
lemma `toUpper_symm` / 引理 `toUpper_symm`

English:
lemma toUpper_symm
  given: {α}
  statement: (@toUpper α).symm = ofUpper
  proof: rfl

中文:
引理 toUpper_symm
  条件: {α}
  结论: (@toUpper α).symm = ofUpper
  证明: rfl
-/
@[simp] lemma toUpper_symm {α} : (@toUpper α).symm = ofUpper := rfl
/--
lemma `ofUpper_symm` / 引理 `ofUpper_symm`

English:
lemma ofUpper_symm
  statement: (@ofUpper α).symm = toUpper
  proof: rfl

中文:
引理 ofUpper_symm
  结论: (@ofUpper α).symm = toUpper
  证明: rfl
-/
@[simp] lemma ofUpper_symm : (@ofUpper α).symm = toUpper := rfl
/--
lemma `toUpper_ofUpper` / 引理 `toUpper_ofUpper`

English:
lemma toUpper_ofUpper
  given: (a : WithUpper α)
  statement: toUpper (ofUpper a) = a
  proof: rfl

中文:
引理 toUpper_ofUpper
  条件: (a : WithUpper α)
  结论: toUpper (ofUpper a) = a
  证明: rfl
-/
@[simp] lemma toUpper_ofUpper (a : WithUpper α) : toUpper (ofUpper a) = a := rfl
/--
lemma `ofUpper_toUpper` / 引理 `ofUpper_toUpper`

English:
lemma ofUpper_toUpper
  given: (a : α)
  statement: ofUpper (toUpper a) = a
  proof: rfl

中文:
引理 ofUpper_toUpper
  条件: (a : α)
  结论: ofUpper (toUpper a) = a
  证明: rfl
-/
@[simp] lemma ofUpper_toUpper (a : α) : ofUpper (toUpper a) = a := rfl
/--
lemma `toUpper_inj` / 引理 `toUpper_inj`

English:
lemma toUpper_inj
  given: {a b : α}
  statement: toUpper a = toUpper b ↔ a = b
  proof: Iff.rfl

中文:
引理 toUpper_inj
  条件: {a b : α}
  结论: toUpper a = toUpper b ↔ a = b
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
lemma toUpper_inj {a b : α} : toUpper a = toUpper b ↔ a = b := Iff.rfl
/--
lemma `ofUpper_inj` / 引理 `ofUpper_inj`

English:
lemma ofUpper_inj
  given: {a b : WithUpper α}
  statement: ofUpper a = ofUpper b ↔ a = b
  proof: Iff.rfl

中文:
引理 ofUpper_inj
  条件: {a b : WithUpper α}
  结论: ofUpper a = ofUpper b ↔ a = b
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
lemma ofUpper_inj {a b : WithUpper α} : ofUpper a = ofUpper b ↔ a = b := Iff.rfl

/-- A recursor for `WithUpper`. Use as `induction x`. -/
@[elab_as_elim, cases_eliminator, induction_eliminator]
/--
Definition of `rec` / `rec` 的定义

English:
definition rec
  signature: {motive : WithUpper α -> Sort*} (toUpper : forall a, motive (toUpper a))
  body: fun a =>
  toUpper (ofUpper a)

中文:
定义 rec
  签名: {motive : WithUpper α -> 类型层*} (toUpper : 对任意 a, motive (toUpper a))
  定义体: fun a =>
  toUpper (ofUpper a)
-/
protected def rec {motive : WithUpper α -> Sort*} (toUpper : forall a, motive (toUpper a)) :
    forall a, motive a := fun a =>
  toUpper (ofUpper a)

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [Nonempty
  signature: α] : Nonempty (WithUpper α)
  body: ‹Nonempty α›

中文:
实例 [非空
  签名: α] : 非空 (WithUpper α)
  定义体: ‹Nonempty α›

Depends on / 依赖: Nonempty
-/
instance [Nonempty α] : Nonempty (WithUpper α) := ‹Nonempty α›
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [Inhabited
  signature: α] : Inhabited (WithUpper α)
  body: ‹Inhabited α›

中文:
实例 [可居
  签名: α] : 可居 (WithUpper α)
  定义体: ‹Inhabited α›

Depends on / 依赖: Inhabited
-/
instance [Inhabited α] : Inhabited (WithUpper α) := ‹Inhabited α›

section Preorder

variable [Preorder α] {s : Set α}

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: Preorder (WithUpper α)
  body: ‹Preorder α›

中文:
实例 :
  签名: 预序 (WithUpper α)
  定义体: ‹Preorder α›

Depends on / 依赖: Preorder
-/
instance : Preorder (WithUpper α) := ‹Preorder α›
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: TopologicalSpace (WithUpper α)
  body: upper (WithUpper α)

中文:
实例 :
  签名: 拓扑空间 (WithUpper α)
  定义体: upper (WithUpper α)

Depends on / 依赖: WithUpper
-/
instance : TopologicalSpace (WithUpper α) := upper (WithUpper α)

/--
lemma `toUpper_le_toUpper` / 引理 `toUpper_le_toUpper`

English:
lemma toUpper_le_toUpper
  given: {x y : α}
  statement: toUpper x <= toUpper y ↔ x <= y
  proof: .rfl

中文:
引理 toUpper_le_toUpper
  条件: {x y : α}
  结论: toUpper x <= toUpper y ↔ x <= y
  证明: .rfl
-/
@[simp] lemma toUpper_le_toUpper {x y : α} : toUpper x <= toUpper y ↔ x <= y := .rfl
/--
lemma `toUpper_lt_toUpper` / 引理 `toUpper_lt_toUpper`

English:
lemma toUpper_lt_toUpper
  given: {x y : α}
  statement: toUpper x < toUpper y ↔ x < y
  proof: .rfl

中文:
引理 toUpper_lt_toUpper
  条件: {x y : α}
  结论: toUpper x < toUpper y ↔ x < y
  证明: .rfl
-/
@[simp] lemma toUpper_lt_toUpper {x y : α} : toUpper x < toUpper y ↔ x < y := .rfl
/--
lemma `ofUpper_le_ofUpper` / 引理 `ofUpper_le_ofUpper`

English:
lemma ofUpper_le_ofUpper
  given: {x y : WithUpper α}
  statement: ofUpper x <= ofUpper y ↔ x <= y
  proof: .rfl

中文:
引理 ofUpper_le_ofUpper
  条件: {x y : WithUpper α}
  结论: ofUpper x <= ofUpper y ↔ x <= y
  证明: .rfl
-/
@[simp] lemma ofUpper_le_ofUpper {x y : WithUpper α} : ofUpper x <= ofUpper y ↔ x <= y := .rfl
/--
lemma `ofUpper_lt_ofUpper` / 引理 `ofUpper_lt_ofUpper`

English:
lemma ofUpper_lt_ofUpper
  given: {x y : WithUpper α}
  statement: ofUpper x < ofUpper y ↔ x < y
  proof: .rfl

中文:
引理 ofUpper_lt_ofUpper
  条件: {x y : WithUpper α}
  结论: ofUpper x < ofUpper y ↔ x < y
  证明: .rfl
-/
@[simp] lemma ofUpper_lt_ofUpper {x y : WithUpper α} : ofUpper x < ofUpper y ↔ x < y := .rfl

/--
lemma `isOpen_preimage_ofUpper` / 引理 `isOpen_preimage_ofUpper`

English:
lemma isOpen_preimage_ofUpper
  statement: IsOpen (ofUpper ⁻¹' s) ↔ (upper α).IsOpen s
  proof: Iff.rfl

中文:
引理 isOpen_preimage_ofUpper
  结论: 是开集 (ofUpper ⁻¹' s) ↔ (upper α).是开集 s
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
lemma isOpen_preimage_ofUpper : IsOpen (ofUpper ⁻¹' s) ↔ (upper α).IsOpen s := Iff.rfl

/--
lemma `isOpen_def` / 引理 `isOpen_def`

English:
lemma isOpen_def
  given: {s : Set (WithUpper α)}
  statement: IsOpen s ↔ (upper α).IsOpen (toUpper ⁻¹' s)
  proof: Iff.rfl

中文:
引理 isOpen_def
  条件: {s : 集合 (WithUpper α)}
  结论: 是开集 s ↔ (upper α).是开集 (toUpper ⁻¹' s)
  证明: Iff.rfl

Depends on / 依赖: Iff.rfl
-/
lemma isOpen_def {s : Set (WithUpper α)} : IsOpen s ↔ (upper α).IsOpen (toUpper ⁻¹' s) := Iff.rfl

/--
theorem `continuous_toUpper` / 定理 `continuous_toUpper`

English:
theorem continuous_toUpper
  given: [TopologicalSpace α] [ClosedIicTopology α]
  proof: continuous_generateFrom_iff.mpr by rintro _ ⟨a, rfl⟩; exact isClosed_Iic.isOpen_compl

中文:
定理 continuous_toUpper
  条件: [拓扑空间 α] [ClosedIic拓扑 α]
  证明: continuous_generateFrom_iff.mpr by rintro _ ⟨a, rfl⟩; exact isClosed_Iic.isOpen_compl

Depends on / 依赖: continuous_generateFrom_iff, continuous_generateFrom_iff.mpr, isClosed_Iic, isClosed_Iic.isOpen_compl, isOpen_compl
-/
theorem continuous_toUpper [TopologicalSpace α] [ClosedIicTopology α] :
    Continuous (toUpper : α -> WithUpper α) :=
continuous_generateFrom_iff.mpr by rintro _ ⟨a, rfl⟩; exact isClosed_Iic.isOpen_compl

end Preorder

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [PartialOrder
  signature: α] : PartialOrder (WithUpper α)
  body: ‹PartialOrder α›

中文:
实例 [偏序
  签名: α] : 偏序 (WithUpper α)
  定义体: ‹PartialOrder α›

Depends on / 依赖: PartialOrder
-/
instance [PartialOrder α] : PartialOrder (WithUpper α) := ‹PartialOrder α›
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [LinearOrder
  signature: α] : LinearOrder (WithUpper α)
  body: ‹LinearOrder α›

中文:
实例 [线性序
  签名: α] : 线性序 (WithUpper α)
  定义体: ‹LinearOrder α›

Depends on / 依赖: LinearOrder
-/
instance [LinearOrder α] : LinearOrder (WithUpper α) := ‹LinearOrder α›

end WithUpper

/--
Definition of `IsLower` / `IsLower` 的定义

English:
class IsLower
  parameters: (α : Type*) [t : TopologicalSpace α] [Preorder α]
  axioms and operations (1):
    - topology_eq_lowerTopology : t = lower α

中文:
类 是Lower
  参数: (α : 类型) [t : 拓扑空间 α] [预序 α]
  公理与运算 (1 个):
    - topology_eq_lowerTopology : t = lower α
-/
class IsLower (α : Type*) [t : TopologicalSpace α] [Preorder α] : Prop where
  topology_eq_lowerTopology : t = lower α

attribute [nolint docBlame] IsLower.topology_eq_lowerTopology

/--
Definition of `IsUpper` / `IsUpper` 的定义

English:
class IsUpper
  parameters: (α : Type*) [t : TopologicalSpace α] [Preorder α]
  axioms and operations (1):
    - topology_eq_upperTopology : t = upper α

中文:
类 是Upper
  参数: (α : 类型) [t : 拓扑空间 α] [预序 α]
  公理与运算 (1 个):
    - topology_eq_upperTopology : t = upper α
-/
class IsUpper (α : Type*) [t : TopologicalSpace α] [Preorder α] : Prop where
  topology_eq_upperTopology : t = upper α
attribute [nolint docBlame] IsUpper.topology_eq_upperTopology

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [Preorder
  signature: α] : IsLower (WithLower α)
  body: ⟨rfl⟩

中文:
实例 [预序
  签名: α] : 是Lower (WithLower α)
  定义体: ⟨rfl⟩
-/
instance [Preorder α] : IsLower (WithLower α) := ⟨rfl⟩
/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance [Preorder
  signature: α] : IsUpper (WithUpper α)
  body: ⟨rfl⟩

中文:
实例 [预序
  签名: α] : 是Upper (WithUpper α)
  定义体: ⟨rfl⟩
-/
instance [Preorder α] : IsUpper (WithUpper α) := ⟨rfl⟩

/--
Definition of `WithLower.toDualHomeomorph` / `WithLower.toDualHomeomorph` 的定义

English:
definition WithLower.toDualHomeomorph
  signature: [Preorder α]
  body: OrderDual.toDual
  invFun := OrderDual.ofDual
  left_inv := OrderDual.toDual_ofDual
  right_inv := OrderDual.ofDual_toDual
  continuous_toFun := continuous_coinduced_rng
  continuous_invFun := continuous_coinduced_rng

中文:
定义 WithLower.toDualHomeomorph
  签名: [预序 α]
  定义体: OrderDual.toDual
  invFun := OrderDual.ofDual
  left_inv := OrderDual.toDual_ofDual
  right_inv := OrderDual.ofDual_toDual
  continuous_toFun := continuous_coinduced_rng
  continuous_invFun := continuous_coinduced_rng

Depends on / 依赖: OrderDual, OrderDual.toDual, toDual
-/
def WithLower.toDualHomeomorph [Preorder α] : WithLower α ≃ₜ WithUpper αᵒᵈ where
  toFun := OrderDual.toDual
  invFun := OrderDual.ofDual
  left_inv := OrderDual.toDual_ofDual
  right_inv := OrderDual.ofDual_toDual
  continuous_toFun := continuous_coinduced_rng
  continuous_invFun := continuous_coinduced_rng

namespace IsLower

/--
Definition of `lowerBasis` / `lowerBasis` 的定义

English:
definition lowerBasis
  signature: (α : Type*) [Preorder α]
  body: { s : Set α | exists t : Set α, t.Finite ∧ (upperClosure t : Set α)ᶜ = s }

中文:
定义 lowerBasis
  签名: (α : 类型) [预序 α]
  定义体: { s : Set α | exists t : Set α, t.Finite ∧ (upperClosure t : Set α)ᶜ = s }

Depends on / 依赖: Finite, t.Finite, upperClosure
-/
def lowerBasis (α : Type*) [Preorder α] :=
  { s : Set α | exists t : Set α, t.Finite ∧ (upperClosure t : Set α)ᶜ = s }

section Preorder

variable (α)
variable [Preorder α] [TopologicalSpace α] [IsLower α] {s : Set α}

/--
lemma `topology_eq` / 引理 `topology_eq`

English:
lemma topology_eq
  statement: ‹_› = lower α
  proof: topology_eq_lowerTopology

中文:
引理 topology_eq
  结论: ‹_› = lower α
  证明: topology_eq_lowerTopology

Depends on / 依赖: topology_eq_lowerTopology
-/
lemma topology_eq : ‹_› = lower α := topology_eq_lowerTopology

variable {α}

/--
Definition of `withLowerHomeomorph` / `withLowerHomeomorph` 的定义

English:
definition withLowerHomeomorph
  signature: : WithLower α ≃ₜ α
  body: WithLower.ofLower.toHomeomorphOfIsInducing ⟨topology_eq α ▸ induced_id.symm⟩

中文:
定义 withLowerHomeomorph
  签名: : WithLower α ≃ₜ α
  定义体: WithLower.ofLower.toHomeomorphOfIsInducing ⟨topology_eq α ▸ induced_id.symm⟩

Depends on / 依赖: WithLower, WithLower.ofLower.toHomeomorphOfIsInducing, induced_id, induced_id.symm, ofLower, toHomeomorphOfIsInducing, topology_eq
-/
def withLowerHomeomorph : WithLower α ≃ₜ α :=
  WithLower.ofLower.toHomeomorphOfIsInducing ⟨topology_eq α ▸ induced_id.symm⟩

/--
theorem `isOpen_iff_generate_Ici_compl` / 定理 `isOpen_iff_generate_Ici_compl`

English:
theorem isOpen_iff_generate_Ici_compl
  statement: IsOpen s ↔ GenerateOpen { t | exists a, (Ici a)ᶜ = t } s
  proof: by
  rw [topology_eq α]; rfl

中文:
定理 isOpen_iff_generate_Ici_compl
  结论: 是开集 s ↔ GenerateOpen { t | 存在 a, (左闭右无界区间 a)ᶜ = t } s
  证明: by
  rw [topology_eq α]; rfl

Depends on / 依赖: topology_eq
-/
theorem isOpen_iff_generate_Ici_compl : IsOpen s ↔ GenerateOpen { t | exists a, (Ici a)ᶜ = t } s := by
  rw [topology_eq α]; rfl

/--
Instance `_root_.OrderDual.instIsUpper` / 实例 `_root_.OrderDual.instIsUpper`

English:
instance _root_.OrderDual.instIsUpper
  signature: : IsUpper αᵒᵈ where
  body: topology_eq_lowerTopology (α := α)

中文:
实例 _root_.OrderDual.instIsUpper
  签名: : 是Upper αᵒᵈ where
  定义体: topology_eq_lowerTopology (α := α)

Depends on / 依赖: topology_eq_lowerTopology
-/
instance _root_.OrderDual.instIsUpper : IsUpper αᵒᵈ where
  topology_eq_upperTopology := topology_eq_lowerTopology (α := α)

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: ClosedIciTopology α
  body: ⟨fun a => isOpen_compl_iff.1 isOpen_iff_generate_Ici_compl.2 GenerateOpen.basic _ ⟨a, rfl⟩⟩

中文:
实例 :
  签名: ClosedIci拓扑 α
  定义体: ⟨fun a => isOpen_compl_iff.1 isOpen_iff_generate_Ici_compl.2 GenerateOpen.basic _ ⟨a, rfl⟩⟩

Depends on / 依赖: GenerateOpen, GenerateOpen.basic, isOpen_compl_iff, isOpen_iff_generate_Ici_compl
-/
instance : ClosedIciTopology α :=
⟨fun a => isOpen_compl_iff.1 isOpen_iff_generate_Ici_compl.2 GenerateOpen.basic _ ⟨a, rfl⟩⟩

/--
theorem `isClosed_upperClosure` / 定理 `isClosed_upperClosure`

English:
theorem isClosed_upperClosure
  given: (h : s.Finite)
  statement: IsClosed (upperClosure s : Set α)
  proof: by
  simp only [← UpperSet.iInf_Ici, UpperSet.coe_iInf]
  exact h.isClosed_biUnion fun _ _ => isClosed_Ici

中文:
定理 isClosed_upperClosure
  条件: (h : s.有限)
  结论: 是闭集 (upperClosure s : 集合 α)
  证明: by
  simp only [← UpperSet.iInf_Ici, UpperSet.coe_iInf]
  exact h.isClosed_biUnion fun _ _ => isClosed_Ici

Depends on / 依赖: UpperSet, UpperSet.coe_iInf, UpperSet.iInf_Ici, coe_iInf, h.isClosed_biUnion, iInf_Ici, isClosed_Ici, isClosed_biUnion
-/
theorem isClosed_upperClosure (h : s.Finite) : IsClosed (upperClosure s : Set α) := by
  simp only [← UpperSet.iInf_Ici, UpperSet.coe_iInf]
  exact h.isClosed_biUnion fun _ _ => isClosed_Ici

/--
theorem `isLowerSet_of_isOpen` / 定理 `isLowerSet_of_isOpen`

English:
theorem isLowerSet_of_isOpen
  given: (h : IsOpen s)
  statement: IsLowerSet s
  proof: by
  replace h := isOpen_iff_generate_Ici_compl.1 h
  induction h with
  | basic u h' => obtain ⟨a, rfl⟩ := h'; exact (isUpperSet_Ici a).compl
  | univ => exact isLowerSet_univ
  | inter u v _ _ hu2 hv2 => exact hu2.inter hv2
  | sUnion _ _ ih => exact isLowerSet_sUnion ih

中文:
定理 isLowerSet_of_isOpen
  条件: (h : 是开集 s)
  结论: 是下集 s
  证明: by
  replace h := isOpen_iff_generate_Ici_compl.1 h
  induction h with
  | basic u h' => obtain ⟨a, rfl⟩ := h'; exact (isUpperSet_Ici a).compl
  | univ => exact isLowerSet_univ
  | inter u v _ _ hu2 hv2 => exact hu2.inter hv2
  | sUnion _ _ ih => exact isLowerSet_sUnion ih

Depends on / 依赖: hu2.inter, isLowerSet_sUnion, isLowerSet_univ, isOpen_iff_generate_Ici_compl, isUpperSet_Ici, replace, sUnion
-/
theorem isLowerSet_of_isOpen (h : IsOpen s) : IsLowerSet s := by
  replace h := isOpen_iff_generate_Ici_compl.1 h
  induction h with
  | basic u h' => obtain ⟨a, rfl⟩ := h'; exact (isUpperSet_Ici a).compl
  | univ => exact isLowerSet_univ
  | inter u v _ _ hu2 hv2 => exact hu2.inter hv2
  | sUnion _ _ ih => exact isLowerSet_sUnion ih

/--
theorem `isUpperSet_of_isClosed` / 定理 `isUpperSet_of_isClosed`

English:
theorem isUpperSet_of_isClosed
  given: (h : IsClosed s)
  statement: IsUpperSet s
  proof: isLowerSet_compl.1 isLowerSet_of_isOpen h.isOpen_compl

中文:
定理 isUpperSet_of_isClosed
  条件: (h : 是闭集 s)
  结论: 是上集 s
  证明: isLowerSet_compl.1 isLowerSet_of_isOpen h.isOpen_compl

Depends on / 依赖: h.isOpen_compl, isLowerSet_compl, isLowerSet_of_isOpen, isOpen_compl
-/
theorem isUpperSet_of_isClosed (h : IsClosed s) : IsUpperSet s :=
isLowerSet_compl.1 isLowerSet_of_isOpen h.isOpen_compl

/--
theorem `tendsto_nhds_iff_not_le` / 定理 `tendsto_nhds_iff_not_le`

English:
theorem tendsto_nhds_iff_not_le
  given: {β : Type*} {f : β -> α} {l : Filter β} {x : α}
  proof: by
  simp +instances [topology_eq_lowerTopology, tendsto_nhds_generateFrom_iff, Filter.Eventually, Ici,
    compl_ofPred]

中文:
定理 tendsto_nhds_iff_not_le
  条件: {β : 类型} {f : β -> α} {l : 滤子 β} {x : α}
  证明: by
  simp +instances [topology_eq_lowerTopology, tendsto_nhds_generateFrom_iff, Filter.Eventually, Ici,
    compl_ofPred]

Depends on / 依赖: Eventually, Filter, Filter.Eventually, compl_ofPred, instances, tendsto_nhds_generateFrom_iff, topology_eq_lowerTopology
-/
theorem tendsto_nhds_iff_not_le {β : Type*} {f : β -> α} {l : Filter β} {x : α} :
    Filter.Tendsto f l (𝓝 x) ↔ forall y, ¬y <= x -> forallᶠ z in l, ¬y <= f z := by
  simp +instances [topology_eq_lowerTopology, tendsto_nhds_generateFrom_iff, Filter.Eventually, Ici,
    compl_ofPred]

/--
The closure of a singleton `{a}` in the lower topology is the left-closed right-infinite interval
$[a, ∞)$.
-/
@[simp]
/--
theorem `closure_singleton` / 定理 `closure_singleton`

English:
theorem closure_singleton
  given: (a : α)
  statement: closure {a} = Ici a
  proof: Subset.antisymm ((closure_minimal fun _ h => h.ge) <| isClosed_Ici)
(isUpperSet_of_isClosed isClosed_closure).Ici_subset subset_closure rfl

中文:
定理 closure_singleton
  条件: (a : α)
  结论: closure {a} = 左闭右无界区间 a
  证明: Subset.antisymm ((closure_minimal fun _ h => h.ge) <| isClosed_Ici)
(isUpperSet_of_isClosed isClosed_closure).Ici_subset subset_closure rfl

Depends on / 依赖: Ici_subset, Subset, Subset.antisymm, antisymm, closure_minimal, h.ge, isClosed_Ici, isClosed_closure, isUpperSet_of_isClosed, subset_closure
-/
theorem closure_singleton (a : α) : closure {a} = Ici a :=
Subset.antisymm ((closure_minimal fun _ h => h.ge) <| isClosed_Ici)
(isUpperSet_of_isClosed isClosed_closure).Ici_subset subset_closure rfl

/--
theorem `isTopologicalBasis` / 定理 `isTopologicalBasis`

English:
theorem isTopologicalBasis
  statement: IsTopologicalBasis (lowerBasis α)
  proof: by
  convert! isTopologicalBasis_of_subbasis (topology_eq α)
  simp_rw [lowerBasis, coe_upperClosure, compl_iUnion]
  ext s
  constructor
  · rintro ⟨F, hF, rfl⟩
    refine ⟨(fun a => (Ici a)ᶜ) '' F, ⟨hF.image _, image_subset_iff.2 fun _ _ => ⟨_, rfl⟩⟩, ?_⟩
    simp only [sInter_image]
  · rintro ⟨F

中文:
定理 isTopologicalBasis
  结论: 是TopologicalBasis (lowerBasis α)
  证明: by
  convert! isTopologicalBasis_of_subbasis (topology_eq α)
  simp_rw [lowerBasis, coe_upperClosure, compl_iUnion]
  ext s
  constructor
  · rintro ⟨F, hF, rfl⟩
    refine ⟨(fun a => (Ici a)ᶜ) '' F, ⟨hF.image _, image_subset_iff.2 fun _ _ => ⟨_, rfl⟩⟩, ?_⟩
    simp only [sInter_image]
  · rintro ⟨F
-/
protected theorem isTopologicalBasis : IsTopologicalBasis (lowerBasis α) := by
  convert! isTopologicalBasis_of_subbasis (topology_eq α)
  simp_rw [lowerBasis, coe_upperClosure, compl_iUnion]
  ext s
  constructor
  · rintro ⟨F, hF, rfl⟩
    refine ⟨(fun a => (Ici a)ᶜ) '' F, ⟨hF.image _, image_subset_iff.2 fun _ _ => ⟨_, rfl⟩⟩, ?_⟩
    simp only [sInter_image]
  · rintro ⟨F, ⟨hF, hs⟩, rfl⟩
    have := hF.to_subtype
    rw [subset_def]; rw [Subtype.forall'] at hs
    choose f hf using hs
    exact ⟨_, finite_range f, by simp_rw [biInter_range, hf, sInter_eq_iInter]⟩

/--
lemma `continuous_iff_Ici` / 引理 `continuous_iff_Ici`

English:
lemma continuous_iff_Ici
  given: [TopologicalSpace β] {f : β -> α}
  proof: by
  obtain rfl := IsLower.topology_eq α
  simp [continuous_generateFrom_iff]

中文:
引理 continuous_iff_Ici
  条件: [拓扑空间 β] {f : β -> α}
  证明: by
  obtain rfl := IsLower.topology_eq α
  simp [continuous_generateFrom_iff]

Depends on / 依赖: IsLower, IsLower.topology_eq, continuous_generateFrom_iff, topology_eq
-/
lemma continuous_iff_Ici [TopologicalSpace β] {f : β -> α} :
    Continuous f ↔ forall a, IsClosed (f ⁻¹' (Ici a)) := by
  obtain rfl := IsLower.topology_eq α
  simp [continuous_generateFrom_iff]

end Preorder

section PartialOrder

variable [PartialOrder α] [TopologicalSpace α] [IsLower α]

-- see Note [lower instance priority]
/-- The lower topology on a partial order is T₀. -/
instance (priority := 90) t0Space : T0Space α :=
  (t0Space_iff_inseparable α).2 fun x y h =>
Ici_injective by simpa only [inseparable_iff_closure_eq, closure_singleton] using h

end PartialOrder

section LinearOrder

variable [LinearOrder α] [TopologicalSpace α] [IsLower α]

/--
lemma `isTopologicalBasis_insert_univ_subbasis` / 引理 `isTopologicalBasis_insert_univ_subbasis`

English:
lemma isTopologicalBasis_insert_univ_subbasis
  proof: isTopologicalBasis_of_subbasis_of_inter (by rw [topology_eq α, lower]) (by
    rintro _ ⟨b, rfl⟩ _ ⟨c, rfl⟩
    use b ⊓ c
    rw [compl_Ici]; rw [compl_Ici]; rw [compl_Ici]; rw [Iio_inter_Iio])

中文:
引理 isTopologicalBasis_insert_univ_subbasis
  证明: isTopologicalBasis_of_subbasis_of_inter (by rw [topology_eq α, lower]) (by
    rintro _ ⟨b, rfl⟩ _ ⟨c, rfl⟩
    use b ⊓ c
    rw [compl_Ici]; rw [compl_Ici]; rw [compl_Ici]; rw [Iio_inter_Iio])

Depends on / 依赖: Iio_inter_Iio, compl_Ici, isTopologicalBasis_of_subbasis_of_inter, topology_eq
-/
lemma isTopologicalBasis_insert_univ_subbasis :
    IsTopologicalBasis (insert univ {s : Set α | exists a, (Ici a)ᶜ = s}) :=
  isTopologicalBasis_of_subbasis_of_inter (by rw [topology_eq α, lower]) (by
    rintro _ ⟨b, rfl⟩ _ ⟨c, rfl⟩
    use b ⊓ c
    rw [compl_Ici]; rw [compl_Ici]; rw [compl_Ici]; rw [Iio_inter_Iio])

/--
theorem `tendsto_nhds_iff_lt` / 定理 `tendsto_nhds_iff_lt`

English:
theorem tendsto_nhds_iff_lt
  given: {β : Type*} {f : β -> α} {l : Filter β} {x : α}
  proof: by
  simp only [tendsto_nhds_iff_not_le, not_le]

中文:
定理 tendsto_nhds_iff_lt
  条件: {β : 类型} {f : β -> α} {l : 滤子 β} {x : α}
  证明: by
  simp only [tendsto_nhds_iff_not_le, not_le]

Depends on / 依赖: not_le, tendsto_nhds_iff_not_le
-/
theorem tendsto_nhds_iff_lt {β : Type*} {f : β -> α} {l : Filter β} {x : α} :
    Filter.Tendsto f l (𝓝 x) ↔ forall y, x < y -> forallᶠ z in l, f z < y := by
  simp only [tendsto_nhds_iff_not_le, not_le]

end LinearOrder

section CompleteLinearOrder

variable [CompleteLinearOrder α] [t : TopologicalSpace α] [IsLower α]

/--
lemma `isTopologicalSpace_basis` / 引理 `isTopologicalSpace_basis`

English:
lemma isTopologicalSpace_basis
  given: (U : Set α)
  statement: IsOpen U ↔ U = univ ∨ exists a, (Ici a)ᶜ = U
  proof: by
  by_cases hU : U = univ
  · simp only [hU, isOpen_univ, compl_Ici, true_or]
  refine ⟨?_, isTopologicalBasis_insert_univ_subbasis.isOpen⟩
  intro hO
  apply Or.inr
  convert! IsTopologicalBasis.open_eq_sUnion isTopologicalBasis_insert_univ_subbasis hO
  constructor
  · intro ⟨a, ha⟩
    use {U}


中文:
引理 isTopologicalSpace_basis
  条件: (U : 集合 α)
  结论: 是开集 U ↔ U = univ ∨ 存在 a, (左闭右无界区间 a)ᶜ = U
  证明: by
  by_cases hU : U = univ
  · simp only [hU, isOpen_univ, compl_Ici, true_or]
  refine ⟨?_, isTopologicalBasis_insert_univ_subbasis.isOpen⟩
  intro hO
  apply Or.inr
  convert! IsTopologicalBasis.open_eq_sUnion isTopologicalBasis_insert_univ_subbasis hO
  constructor
  · intro ⟨a, ha⟩
    use {U}


Depends on / 依赖: IsTopologicalBasis, IsTopologicalBasis.open_eq_sUnion, Or.inr, compl_Ici, convert, isOpen, isOpen_univ, isTopologicalBasis_insert_univ_subbasis, isTopologicalBasis_insert_univ_subbasis.isOpen, open_eq_sUnion, sUnion_eq_univ_iff, sUnion_eq_univ_iff.mp, sUnion_singleton, singleton_subset_iff, singleton_subset_iff.mpr, subset_insert, subset_trans, true_or
-/
lemma isTopologicalSpace_basis (U : Set α) : IsOpen U ↔ U = univ ∨ exists a, (Ici a)ᶜ = U := by
  by_cases hU : U = univ
  · simp only [hU, isOpen_univ, compl_Ici, true_or]
  refine ⟨?_, isTopologicalBasis_insert_univ_subbasis.isOpen⟩
  intro hO
  apply Or.inr
  convert! IsTopologicalBasis.open_eq_sUnion isTopologicalBasis_insert_univ_subbasis hO
  constructor
  · intro ⟨a, ha⟩
    use {U}
    constructor
    · apply subset_trans (singleton_subset_iff.mpr _) (subset_insert _ _)
      use a
    · rw [sUnion_singleton]
  · intro ⟨S, hS1, hS2⟩
    have hUS : univ ∉ S := by
      by_contra hUS'
      apply hU
      rw [hS2]
      exact sUnion_eq_univ_iff.mpr (fun a => ⟨univ, hUS', trivial⟩)
    use sSup {a | (Ici a)ᶜ in S}
    rw [hS2]; rw [sUnion_eq_compl_sInter_compl]; rw [compl_inj_iff]
    apply le_antisymm
    · intro b hb
      simp only [sInter_image, mem_iInter, mem_compl_iff]
      intro s hs
      obtain ⟨a, ha⟩ := (subset_insert_iff_of_notMem hUS).mp hS1 hs
      subst hS2 ha
      simp_all only [compl_Ici, mem_Ici, sSup_le_iff, mem_ofPred_eq, mem_Iio, not_lt]
    · intro b hb
      rw [mem_Ici]; rw [sSup_le_iff]
      intro c hc
      simp only [sInter_image, mem_iInter] at hb
      rw [← not_lt]; rw [← mem_Iio]; rw [← compl_Ici]
      exact hb _ hc

end CompleteLinearOrder

end IsLower


namespace IsUpper

/--
Definition of `upperBasis` / `upperBasis` 的定义

English:
definition upperBasis
  signature: (α : Type*) [Preorder α]
  body: { s : Set α | exists t : Set α, t.Finite ∧ (lowerClosure t : Set α)ᶜ = s }

中文:
定义 upperBasis
  签名: (α : 类型) [预序 α]
  定义体: { s : Set α | exists t : Set α, t.Finite ∧ (lowerClosure t : Set α)ᶜ = s }

Depends on / 依赖: Finite, lowerClosure, t.Finite
-/
def upperBasis (α : Type*) [Preorder α] :=
  { s : Set α | exists t : Set α, t.Finite ∧ (lowerClosure t : Set α)ᶜ = s }

section Preorder

variable (α)
variable [Preorder α] [TopologicalSpace α] [IsUpper α] {s : Set α}

/--
lemma `topology_eq` / 引理 `topology_eq`

English:
lemma topology_eq
  statement: ‹_› = upper α
  proof: topology_eq_upperTopology

中文:
引理 topology_eq
  结论: ‹_› = upper α
  证明: topology_eq_upperTopology

Depends on / 依赖: topology_eq_upperTopology
-/
lemma topology_eq : ‹_› = upper α := topology_eq_upperTopology

variable {α}

/--
Definition of `withUpperHomeomorph` / `withUpperHomeomorph` 的定义

English:
definition withUpperHomeomorph
  signature: : WithUpper α ≃ₜ α
  body: WithUpper.ofUpper.toHomeomorphOfIsInducing ⟨topology_eq α ▸ induced_id.symm⟩

中文:
定义 withUpperHomeomorph
  签名: : WithUpper α ≃ₜ α
  定义体: WithUpper.ofUpper.toHomeomorphOfIsInducing ⟨topology_eq α ▸ induced_id.symm⟩

Depends on / 依赖: WithUpper, WithUpper.ofUpper.toHomeomorphOfIsInducing, induced_id, induced_id.symm, ofUpper, toHomeomorphOfIsInducing, topology_eq
-/
def withUpperHomeomorph : WithUpper α ≃ₜ α :=
  WithUpper.ofUpper.toHomeomorphOfIsInducing ⟨topology_eq α ▸ induced_id.symm⟩

/--
theorem `isOpen_iff_generate_Iic_compl` / 定理 `isOpen_iff_generate_Iic_compl`

English:
theorem isOpen_iff_generate_Iic_compl
  statement: IsOpen s ↔ GenerateOpen { t | exists a, (Iic a)ᶜ = t } s
  proof: by
  rw [topology_eq α]; rfl

中文:
定理 isOpen_iff_generate_Iic_compl
  结论: 是开集 s ↔ GenerateOpen { t | 存在 a, (左无界右闭区间 a)ᶜ = t } s
  证明: by
  rw [topology_eq α]; rfl

Depends on / 依赖: topology_eq
-/
theorem isOpen_iff_generate_Iic_compl : IsOpen s ↔ GenerateOpen { t | exists a, (Iic a)ᶜ = t } s := by
  rw [topology_eq α]; rfl

/--
Instance `_root_.OrderDual.instIsLower` / 实例 `_root_.OrderDual.instIsLower`

English:
instance _root_.OrderDual.instIsLower
  signature: : IsLower αᵒᵈ where
  body: topology_eq_upperTopology (α := α)

中文:
实例 _root_.OrderDual.instIsLower
  签名: : 是Lower αᵒᵈ where
  定义体: topology_eq_upperTopology (α := α)

Depends on / 依赖: topology_eq_upperTopology
-/
instance _root_.OrderDual.instIsLower : IsLower αᵒᵈ where
  topology_eq_lowerTopology := topology_eq_upperTopology (α := α)

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: ClosedIicTopology α
  body: ⟨fun a => isOpen_compl_iff.1 isOpen_iff_generate_Iic_compl.2 GenerateOpen.basic _ ⟨a, rfl⟩⟩

中文:
实例 :
  签名: ClosedIic拓扑 α
  定义体: ⟨fun a => isOpen_compl_iff.1 isOpen_iff_generate_Iic_compl.2 GenerateOpen.basic _ ⟨a, rfl⟩⟩

Depends on / 依赖: GenerateOpen, GenerateOpen.basic, isOpen_compl_iff, isOpen_iff_generate_Iic_compl
-/
instance : ClosedIicTopology α :=
⟨fun a => isOpen_compl_iff.1 isOpen_iff_generate_Iic_compl.2 GenerateOpen.basic _ ⟨a, rfl⟩⟩

/--
theorem `isClosed_lowerClosure` / 定理 `isClosed_lowerClosure`

English:
theorem isClosed_lowerClosure
  given: (h : s.Finite)
  statement: IsClosed (lowerClosure s : Set α)
  proof: IsLower.isClosed_upperClosure (α := αᵒᵈ) h

中文:
定理 isClosed_lowerClosure
  条件: (h : s.有限)
  结论: 是闭集 (lowerClosure s : 集合 α)
  证明: IsLower.isClosed_upperClosure (α := αᵒᵈ) h

Depends on / 依赖: IsLower, IsLower.isClosed_upperClosure, isClosed_upperClosure
-/
theorem isClosed_lowerClosure (h : s.Finite) : IsClosed (lowerClosure s : Set α) :=
  IsLower.isClosed_upperClosure (α := αᵒᵈ) h

/--
theorem `isUpperSet_of_isOpen` / 定理 `isUpperSet_of_isOpen`

English:
theorem isUpperSet_of_isOpen
  given: (h : IsOpen s)
  statement: IsUpperSet s
  proof: IsLower.isLowerSet_of_isOpen (α := αᵒᵈ) h

中文:
定理 isUpperSet_of_isOpen
  条件: (h : 是开集 s)
  结论: 是上集 s
  证明: IsLower.isLowerSet_of_isOpen (α := αᵒᵈ) h

Depends on / 依赖: IsLower, IsLower.isLowerSet_of_isOpen, isLowerSet_of_isOpen
-/
theorem isUpperSet_of_isOpen (h : IsOpen s) : IsUpperSet s :=
  IsLower.isLowerSet_of_isOpen (α := αᵒᵈ) h

/--
theorem `isLowerSet_of_isClosed` / 定理 `isLowerSet_of_isClosed`

English:
theorem isLowerSet_of_isClosed
  given: (h : IsClosed s)
  statement: IsLowerSet s
  proof: isUpperSet_compl.1 isUpperSet_of_isOpen h.isOpen_compl

中文:
定理 isLowerSet_of_isClosed
  条件: (h : 是闭集 s)
  结论: 是下集 s
  证明: isUpperSet_compl.1 isUpperSet_of_isOpen h.isOpen_compl

Depends on / 依赖: h.isOpen_compl, isOpen_compl, isUpperSet_compl, isUpperSet_of_isOpen
-/
theorem isLowerSet_of_isClosed (h : IsClosed s) : IsLowerSet s :=
isUpperSet_compl.1 isUpperSet_of_isOpen h.isOpen_compl

/--
theorem `tendsto_nhds_iff_not_le` / 定理 `tendsto_nhds_iff_not_le`

English:
theorem tendsto_nhds_iff_not_le
  given: {β : Type*} {f : β -> α} {l : Filter β} {x : α}
  proof: IsLower.tendsto_nhds_iff_not_le (α := αᵒᵈ)

中文:
定理 tendsto_nhds_iff_not_le
  条件: {β : 类型} {f : β -> α} {l : 滤子 β} {x : α}
  证明: IsLower.tendsto_nhds_iff_not_le (α := αᵒᵈ)

Depends on / 依赖: IsLower, IsLower.tendsto_nhds_iff_not_le, tendsto_nhds_iff_not_le
-/
theorem tendsto_nhds_iff_not_le {β : Type*} {f : β -> α} {l : Filter β} {x : α} :
    Filter.Tendsto f l (𝓝 x) ↔ forall y, ¬x <= y -> forallᶠ z in l, ¬f z <= y :=
  IsLower.tendsto_nhds_iff_not_le (α := αᵒᵈ)

/--
The closure of a singleton `{a}` in the upper topology is the left-infinite right-closed interval
$(-∞,a]$.
-/
@[simp]
/--
theorem `closure_singleton` / 定理 `closure_singleton`

English:
theorem closure_singleton
  given: (a : α)
  statement: closure {a} = Iic a
  proof: IsLower.closure_singleton (α := αᵒᵈ) _

中文:
定理 closure_singleton
  条件: (a : α)
  结论: closure {a} = 左无界右闭区间 a
  证明: IsLower.closure_singleton (α := αᵒᵈ) _

Depends on / 依赖: IsLower, IsLower.closure_singleton, closure_singleton
-/
theorem closure_singleton (a : α) : closure {a} = Iic a :=
  IsLower.closure_singleton (α := αᵒᵈ) _

/--
theorem `isTopologicalBasis` / 定理 `isTopologicalBasis`

English:
theorem isTopologicalBasis
  statement: IsTopologicalBasis (upperBasis α)
  proof: IsLower.isTopologicalBasis (α := αᵒᵈ)

中文:
定理 isTopologicalBasis
  结论: 是TopologicalBasis (upperBasis α)
  证明: IsLower.isTopologicalBasis (α := αᵒᵈ)
-/
protected theorem isTopologicalBasis : IsTopologicalBasis (upperBasis α) :=
  IsLower.isTopologicalBasis (α := αᵒᵈ)

/--
lemma `continuous_iff_Iic` / 引理 `continuous_iff_Iic`

English:
lemma continuous_iff_Iic
  given: [TopologicalSpace β] {f : β -> α}
  proof: IsLower.continuous_iff_Ici (α := αᵒᵈ)

中文:
引理 continuous_iff_Iic
  条件: [拓扑空间 β] {f : β -> α}
  证明: IsLower.continuous_iff_Ici (α := αᵒᵈ)

Depends on / 依赖: IsLower, IsLower.continuous_iff_Ici, continuous_iff_Ici
-/
lemma continuous_iff_Iic [TopologicalSpace β] {f : β -> α} :
    Continuous f ↔ forall a, IsClosed (f ⁻¹' (Iic a)) :=
  IsLower.continuous_iff_Ici (α := αᵒᵈ)

end Preorder


section PartialOrder

variable [PartialOrder α] [TopologicalSpace α] [IsUpper α]

-- see Note [lower instance priority]
/-- The upper topology on a partial order is T₀. -/
instance (priority := 90) t0Space : T0Space α :=
  IsLower.t0Space (α := αᵒᵈ)

end PartialOrder

section LinearOrder

variable [LinearOrder α] [TopologicalSpace α] [IsUpper α]

/--
lemma `isTopologicalBasis_insert_univ_subbasis` / 引理 `isTopologicalBasis_insert_univ_subbasis`

English:
lemma isTopologicalBasis_insert_univ_subbasis
  proof: IsLower.isTopologicalBasis_insert_univ_subbasis (α := αᵒᵈ)

中文:
引理 isTopologicalBasis_insert_univ_subbasis
  证明: IsLower.isTopologicalBasis_insert_univ_subbasis (α := αᵒᵈ)

Depends on / 依赖: IsLower, IsLower.isTopologicalBasis_insert_univ_subbasis, isTopologicalBasis_insert_univ_subbasis
-/
lemma isTopologicalBasis_insert_univ_subbasis :
    IsTopologicalBasis (insert univ {s : Set α | exists a, (Iic a)ᶜ = s}) :=
  IsLower.isTopologicalBasis_insert_univ_subbasis (α := αᵒᵈ)

/--
theorem `tendsto_nhds_iff_lt` / 定理 `tendsto_nhds_iff_lt`

English:
theorem tendsto_nhds_iff_lt
  given: {β : Type*} {f : β -> α} {l : Filter β} {x : α}
  proof: IsLower.tendsto_nhds_iff_lt (α := αᵒᵈ)

中文:
定理 tendsto_nhds_iff_lt
  条件: {β : 类型} {f : β -> α} {l : 滤子 β} {x : α}
  证明: IsLower.tendsto_nhds_iff_lt (α := αᵒᵈ)

Depends on / 依赖: IsLower, IsLower.tendsto_nhds_iff_lt, tendsto_nhds_iff_lt
-/
theorem tendsto_nhds_iff_lt {β : Type*} {f : β -> α} {l : Filter β} {x : α} :
    Filter.Tendsto f l (𝓝 x) ↔ forall y < x, forallᶠ z in l, y < f z :=
  IsLower.tendsto_nhds_iff_lt (α := αᵒᵈ)

end LinearOrder

section CompleteLinearOrder

variable [CompleteLinearOrder α] [t : TopologicalSpace α] [IsUpper α]

/--
lemma `isTopologicalSpace_basis` / 引理 `isTopologicalSpace_basis`

English:
lemma isTopologicalSpace_basis
  given: (U : Set α)
  statement: IsOpen U ↔ U = univ ∨ exists a, (Iic a)ᶜ = U
  proof: IsLower.isTopologicalSpace_basis (α := αᵒᵈ) U

中文:
引理 isTopologicalSpace_basis
  条件: (U : 集合 α)
  结论: 是开集 U ↔ U = univ ∨ 存在 a, (左无界右闭区间 a)ᶜ = U
  证明: IsLower.isTopologicalSpace_basis (α := αᵒᵈ) U

Depends on / 依赖: IsLower, IsLower.isTopologicalSpace_basis, isTopologicalSpace_basis
-/
lemma isTopologicalSpace_basis (U : Set α) : IsOpen U ↔ U = univ ∨ exists a, (Iic a)ᶜ = U :=
  IsLower.isTopologicalSpace_basis (α := αᵒᵈ) U

end CompleteLinearOrder

end IsUpper

/--
Instance `instIsLowerProd` / 实例 `instIsLowerProd`

English:
instance instIsLowerProd
  signature: [Preorder α] [TopologicalSpace α] [IsLower α]
  body: by
    refine le_antisymm (le_generateFrom ?_) ?_
    · rintro _ ⟨x, rfl⟩
      exact (isClosed_Ici.prod isClosed_Ici).isOpen_compl
    rw [(IsLower.isTopologicalBasis.prod
      IsLower.isTopologicalBasis).eq_generateFrom]; rw [le_generateFrom_iff_subset_isOpen]; rw [image2_subset_iff]
    rintro _

中文:
实例 instIsLowerProd
  签名: [预序 α] [拓扑空间 α] [是Lower α]
  定义体: by
    refine le_antisymm (le_generateFrom ?_) ?_
    · rintro _ ⟨x, rfl⟩
      exact (isClosed_Ici.prod isClosed_Ici).isOpen_compl
    rw [(IsLower.isTopologicalBasis.prod
      IsLower.isTopologicalBasis).eq_generateFrom]; rw [le_generateFrom_iff_subset_isOpen]; rw [image2_subset_iff]
    rintro _

Depends on / 依赖: IsLower, IsLower.isTopologicalBasis, IsLower.isTopologicalBasis.prod, coe_upperClosure, compl_iUnion, eq_generateFrom, image2_subset_iff, isClosed_Ici, isClosed_Ici.prod, isOpen_compl, isTopologicalBasis, le_antisymm, le_generateFrom, le_generateFrom_iff_subset_isOpen, preimage_compl, preimage_iInter, prod_eq, simp_rw
-/
instance instIsLowerProd [Preorder α] [TopologicalSpace α] [IsLower α]
    [OrderBot α] [Preorder β] [TopologicalSpace β] [IsLower β] [OrderBot β] :
    IsLower (α × β) where
  topology_eq_lowerTopology := by
    refine le_antisymm (le_generateFrom ?_) ?_
    · rintro _ ⟨x, rfl⟩
      exact (isClosed_Ici.prod isClosed_Ici).isOpen_compl
    rw [(IsLower.isTopologicalBasis.prod
      IsLower.isTopologicalBasis).eq_generateFrom]; rw [le_generateFrom_iff_subset_isOpen]; rw [image2_subset_iff]
    rintro _ ⟨s, hs, rfl⟩ _ ⟨t, ht, rfl⟩
    dsimp
    simp_rw [coe_upperClosure, compl_iUnion, prod_eq, preimage_iInter, preimage_compl]
    -- without `let`, `refine` tries to use the product topology and fails
    let _ : TopologicalSpace (α × β) := lower (α × β)
    refine (hs.isOpen_biInter fun a _ => ?_).inter (ht.isOpen_biInter fun b _ => ?_)
    · exact GenerateOpen.basic _ ⟨(a, ⊥), by simp [Ici_prod_eq, prod_univ]⟩
    · exact GenerateOpen.basic _ ⟨(⊥, b), by simp [Ici_prod_eq, univ_prod]⟩

/--
Instance `instIsUpperProd` / 实例 `instIsUpperProd`

English:
instance instIsUpperProd
  signature: [Preorder α] [TopologicalSpace α] [IsUpper α]
  body: by
    suffices IsLower (α × β)ᵒᵈ from IsLower.topology_eq_lowerTopology (α := (α × β)ᵒᵈ)
    exact instIsLowerProd (α := αᵒᵈ) (β := βᵒᵈ)

中文:
实例 instIsUpperProd
  签名: [预序 α] [拓扑空间 α] [是Upper α]
  定义体: by
    suffices IsLower (α × β)ᵒᵈ from IsLower.topology_eq_lowerTopology (α := (α × β)ᵒᵈ)
    exact instIsLowerProd (α := αᵒᵈ) (β := βᵒᵈ)

Depends on / 依赖: IsLower, IsLower.topology_eq_lowerTopology, instIsLowerProd, topology_eq_lowerTopology
-/
instance instIsUpperProd [Preorder α] [TopologicalSpace α] [IsUpper α]
    [OrderTop α] [Preorder β] [TopologicalSpace β] [IsUpper β] [OrderTop β] :
    IsUpper (α × β) where
  topology_eq_upperTopology := by
    suffices IsLower (α × β)ᵒᵈ from IsLower.topology_eq_lowerTopology (α := (α × β)ᵒᵈ)
    exact instIsLowerProd (α := αᵒᵈ) (β := βᵒᵈ)

section CompleteLattice_IsLower

variable [CompleteLattice α] [CompleteLattice β] [TopologicalSpace α] [IsLower α]
  [TopologicalSpace β] [IsLower β]

/--
lemma `_root_.sInfHom.continuous` / 引理 `_root_.sInfHom.continuous`

English:
lemma _root_.sInfHom.continuous
  given: (f : sInfHom α β)
  statement: Continuous f
  proof: by
  refine IsLower.continuous_iff_Ici.2 fun b => ?_
  convert! isClosed_Ici (a := sInf <| f ⁻¹' Ici b)
refine Subset.antisymm (fun a => sInf_le) fun a ha => le_trans ?_
    OrderHomClass.mono (f : α ->o β) ha
  refine LE.le.trans ?_ (map_sInf f _).ge
  simp

中文:
引理 _root_.sInf态射.continuous
  条件: (f : sInf态射 α β)
  结论: 连续 f
  证明: by
  refine IsLower.continuous_iff_Ici.2 fun b => ?_
  convert! isClosed_Ici (a := sInf <| f ⁻¹' Ici b)
refine Subset.antisymm (fun a => sInf_le) fun a ha => le_trans ?_
    OrderHomClass.mono (f : α ->o β) ha
  refine LE.le.trans ?_ (map_sInf f _).ge
  simp
-/
protected lemma _root_.sInfHom.continuous (f : sInfHom α β) : Continuous f := by
  refine IsLower.continuous_iff_Ici.2 fun b => ?_
  convert! isClosed_Ici (a := sInf <| f ⁻¹' Ici b)
refine Subset.antisymm (fun a => sInf_le) fun a ha => le_trans ?_
    OrderHomClass.mono (f : α ->o β) ha
  refine LE.le.trans ?_ (map_sInf f _).ge
  simp

-- see Note [lower instance priority]
instance (priority := 90) IsLower.toContinuousInf : ContinuousInf α :=
  ⟨(infsInfHom : sInfHom (α × α) α).continuous⟩

end CompleteLattice_IsLower

section CompleteLattice_IsUpper

variable [CompleteLattice α] [CompleteLattice β] [TopologicalSpace α] [IsUpper α]
  [TopologicalSpace β] [IsUpper β]

/--
lemma `_root_.sSupHom.continuous` / 引理 `_root_.sSupHom.continuous`

English:
lemma _root_.sSupHom.continuous
  given: (f : sSupHom α β)
  statement: Continuous f
  proof: sInfHom.continuous (α := αᵒᵈ) (β := βᵒᵈ) (sSupHom.dual.toFun f)

中文:
引理 _root_.sSup态射.continuous
  条件: (f : sSup态射 α β)
  结论: 连续 f
  证明: sInfHom.continuous (α := αᵒᵈ) (β := βᵒᵈ) (sSupHom.dual.toFun f)
-/
protected lemma _root_.sSupHom.continuous (f : sSupHom α β) : Continuous f :=
  sInfHom.continuous (α := αᵒᵈ) (β := βᵒᵈ) (sSupHom.dual.toFun f)

-- see Note [lower instance priority]
instance (priority := 90) IsUpper.toContinuousInf : ContinuousSup α :=
  ⟨(supsSupHom : sSupHom (α × α) α).continuous⟩

end CompleteLattice_IsUpper

/--
lemma `isUpper_orderDual` / 引理 `isUpper_orderDual`

English:
lemma isUpper_orderDual
  given: [Preorder α] [TopologicalSpace α]
  statement: IsUpper αᵒᵈ ↔ IsLower α
  proof: by
  constructor
  · apply OrderDual.instIsLower
  · apply OrderDual.instIsUpper

中文:
引理 isUpper_orderDual
  条件: [预序 α] [拓扑空间 α]
  结论: 是Upper αᵒᵈ ↔ 是Lower α
  证明: by
  constructor
  · apply OrderDual.instIsLower
  · apply OrderDual.instIsUpper

Depends on / 依赖: OrderDual, OrderDual.instIsLower, OrderDual.instIsUpper, instIsLower, instIsUpper
-/
lemma isUpper_orderDual [Preorder α] [TopologicalSpace α] : IsUpper αᵒᵈ ↔ IsLower α := by
  constructor
  · apply OrderDual.instIsLower
  · apply OrderDual.instIsUpper

/--
lemma `isLower_orderDual` / 引理 `isLower_orderDual`

English:
lemma isLower_orderDual
  given: [Preorder α] [TopologicalSpace α]
  statement: IsLower αᵒᵈ ↔ IsUpper α
  proof: isUpper_orderDual.symm

中文:
引理 isLower_orderDual
  条件: [预序 α] [拓扑空间 α]
  结论: 是Lower αᵒᵈ ↔ 是Upper α
  证明: isUpper_orderDual.symm

Depends on / 依赖: isUpper_orderDual, isUpper_orderDual.symm
-/
lemma isLower_orderDual [Preorder α] [TopologicalSpace α] : IsLower αᵒᵈ ↔ IsUpper α :=
  isUpper_orderDual.symm

end Topology

/--
Instance `_anonymous_` / 实例 `_anonymous_`

English:
instance :
  signature: IsUpper Prop
  body: by
    rw [Topology.upper]; rw [sierpinskiSpace]; rw [← generateFrom_insert_empty]
    congr
    exact le_antisymm
      (fun h hs => by
        simp only [compl_Iic, mem_ofPred_eq]
        rw [← Ioi_True]; rw [← Ioi_False] at hs
        rcases hs with (rfl | rfl)
        · use True
        · use Fa

中文:
实例 :
  签名: 是Upper 命题
  定义体: by
    rw [Topology.upper]; rw [sierpinskiSpace]; rw [← generateFrom_insert_empty]
    congr
    exact le_antisymm
      (fun h hs => by
        simp only [compl_Iic, mem_ofPred_eq]
        rw [← Ioi_True]; rw [← Ioi_False] at hs
        rcases hs with (rfl | rfl)
        · use True
        · use Fa

Depends on / 依赖: Ioi_False, Ioi_True, Topology, Topology.upper, compl_Iic, generateFrom_insert_empty, le_antisymm, lt_iff_le_not_ge, mem_ofPred_eq, sierpinskiSpace
-/
instance : IsUpper Prop where
  topology_eq_upperTopology := by
    rw [Topology.upper]; rw [sierpinskiSpace]; rw [← generateFrom_insert_empty]
    congr
    exact le_antisymm
      (fun h hs => by
        simp only [compl_Iic, mem_ofPred_eq]
        rw [← Ioi_True]; rw [← Ioi_False] at hs
        rcases hs with (rfl | rfl)
        · use True
        · use False)
      (by rintro _ ⟨a, rfl⟩; by_cases a <;> aesop (add simp [Ioi, lt_iff_le_not_ge]))
