/-
Copyright (c) 2025 Dexin Zhang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dexin Zhang
-/
module

public import Mathlib.GroupTheory.GroupAction.SubMulAction.Closure
public import Mathlib.Algebra.Group.Pointwise.Set.Basic

/-!
# Semigroup ideals

This file defines (left) semigroup ideals (also called monoid ideals sometimes), which are sets `s`
in a semigroup such that `a * b ∈ s` whenever `b ∈ s`. Note that semigroup ideals are different from
ring ideals (`Ideal` in Mathlib): a ring ideal is a semigroup ideal that is also an additive
submonoid of the ring.

## References

* [Samuel Eilenberg and M. P. Schützenberger, *Rational Sets in Commutative Monoids*][eilenberg1969]
-/

@[expose] public section

open Set Pointwise

/-- A (left) semigroup ideal in a semigroup `M` is a set `s` such that `a * b ∈ s` whenever
`b ∈ s`. -/
@[to_additive /-- A (left) additive semigroup ideal in an additive semigroup `M` is a set `s` such
that `a + b ∈ s` whenever `b ∈ s`. -/]
/-
**SemigroupIdeal** 是 Mathlib 中的一个缩写定义，位于命名空间 ``。
形式化陈述：SemigroupIdeal (M : Type*) [Mul M]
参数：M : Type*。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
abbrev SemigroupIdeal (M : Type*) [Mul M] :=
  SubMulAction M M

namespace SemigroupIdeal

variable {M : Type*}

section Mul

variable [Mul M] {s t : Set M} {x : M}

@[to_additive]
/-
**SemigroupIdeal.mul_mem** 是 Mathlib 中的一个定理，位于命名空间 `SemigroupIdeal`。
形式化陈述：∀ {M : Type u_1} [inst : Mul M] (I : SemigroupIdeal M) (x : M) {y : M}, y 
∈ I → x * y ∈ I
参数：I : SemigroupIdeal M；x : M。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `SubMulAction.smul_mem`：smul_mem (r : R) (h : x in p) : r • x in p
-/
protected theorem mul_mem (I : SemigroupIdeal M) (x : M) {y : M} : y ∈ I → x * y ∈ I :=
  SubMulAction.smul_mem I x

/-- The semigroup ideal generated by a set `s`. -/
@[to_additive /-- The additive semigroup ideal generated by a set `s`. -/]
/-
**SemigroupIdeal.closure** 是 Mathlib 中的一个缩写定义，位于命名空间 `SemigroupIdeal`。
形式化陈述：closure (s : Set M) : SemigroupIdeal M
参数：s : Set M。
该定义给出了上述对象。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。

--- 原说明 ---
The semigroup ideal generated by a set `s`.
-/
abbrev closure (s : Set M) : SemigroupIdeal M :=
  SubMulAction.closure M s

@[to_additive]
/-
**SemigroupIdeal.mem_closure** 是 Mathlib 中的一个定理，位于命名空间 `SemigroupIdeal`。
形式化陈述：mem_closure : x in closure s ↔ forall p : SemigroupIdeal M, s subseteq p -
> x in p
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `SubMulAction.mem_closure`：mem_closure : x in closure R s ↔ forall p : Su
bMulAction R M, s subseteq p -> x in p
-/
theorem mem_closure : x ∈ closure s ↔ ∀ p : SemigroupIdeal M, s ⊆ p → x ∈ p :=
  SubMulAction.mem_closure

@[to_additive]
/-
**SemigroupIdeal.subset_closure** 是 Mathlib 中的一个定理，位于命名空间 `SemigroupIdeal`。
形式化陈述：subset_closure : s subseteq closure s
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `SubMulAction.subset_closure`：subset_closure : s subseteq closure R s
-/
theorem subset_closure : s ⊆ closure s :=
  SubMulAction.subset_closure

@[to_additive]
/-
**SemigroupIdeal.mem_closure_of_mem** 是 Mathlib 中的一个定理，位于命名空间 `SemigroupIdeal`。
形式化陈述：mem_closure_of_mem (hx : x in s) : x in closure s
参数：hx : x in s。
该定理/引理描述了相关对象所满足的性质。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `SubMulAction.mem_closure_of_mem`：mem_closure_of_mem (hx : x in s) : x in
 closure R s
-/
theorem mem_closure_of_mem (hx : x ∈ s) : x ∈ closure s :=
  SubMulAction.mem_closure_of_mem hx

@[to_additive]
/-
**SemigroupIdeal.closure_le** 是 Mathlib 中的一个定理，位于命名空间 `SemigroupIdeal`。
形式化陈述：closure_le {I} : closure s <= I ↔ s subseteq I
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `SubMulAction.closure_le`：closure_le {p} : closure R s <= p ↔ s subseteq 
p
-/
theorem closure_le {I} : closure s ≤ I ↔ s ⊆ I :=
  SubMulAction.closure_le

@[to_additive (attr := gcongr)]
/-
**SemigroupIdeal.closure_mono** 是 Mathlib 中的一个定理，位于命名空间 `SemigroupIdeal`。
形式化陈述：closure_mono (h : s subseteq t) : closure s <= closure t
参数：h : s subseteq t。
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `SubMulAction.closure_mono`：closure_mono (h : s subseteq t) : closure R s
 <= closure R t
-/
theorem closure_mono (h : s ⊆ t) : closure s ≤ closure t :=
  SubMulAction.closure_mono h

end Mul

/-- The semigroup ideal generated by `s` is `s ∪ Set.univ * s`. -/
@[to_additive /-- The additive semigroup ideal generated by `s` is `s ∪ Set.univ + s`. -/]
/-
**SemigroupIdeal.coe_closure** 是 Mathlib 中的一个定理，位于命名空间 `SemigroupIdeal`。
形式化陈述：coe_closure [Semigroup M] {s : Set M} : (closure s : Set M) = s union univ
 * s
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `Set.mul_mem_mul`：mul_mem_mul : a in s -> b in t -> a * b in s * t
· 使用定理 `Set.mem_univ`：mem_univ (x : α) : x in @univ α
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `LE.le.antisymm`：∀ {α : Type u_1} [inst : PartialOrder α] {a b : α}, a ≤ 
b → b ≤ a → a = b
· 使用定理 `Iff.mpr`：∀ {a b : Prop}, (a ↔ b) → b → a
· 使用定理 `SemigroupIdeal.closure_le`：closure_le {I} : closure s <= I ↔ s subseteq 
I
· 使用定理 `Or.elim`：∀ {a b c : Prop}, a ∨ b → (a → c) → (b → c) → c
· 使用定理 `SemigroupIdeal.mem_closure_of_mem`：mem_closure_of_mem (hx : x in s) : x 
in closure s
· 使用定理 `SemigroupIdeal.mul_mem`：∀ {M : Type u_1} [inst : Mul M] (I : SemigroupId
eal M) (x : M) {y : M}, y ∈ I → x * y ∈ I

--- 原说明 ---
The semigroup ideal generated by `s` is `s ∪ Set.univ * s`.
-/
theorem coe_closure [Semigroup M] {s : Set M} :
    (closure s : Set M) = s ∪ univ * s := by
  let I : SemigroupIdeal M :=
    { carrier := s ∪ univ * s
      smul_mem' x y := by
        rintro (hy | ⟨y, -, z, hz, rfl⟩)
        · exact .inr <| mul_mem_mul (mem_univ _) hy
        · simpa [← mul_assoc] using .inr <| mul_mem_mul (mem_univ _) hz }
  suffices closure s = I by rw [this]; rfl
  refine (closure_le.2 fun x => Or.inl).antisymm fun x hx => hx.elim mem_closure_of_mem ?_
  rintro ⟨y, -, z, hz, rfl⟩
  exact SemigroupIdeal.mul_mem _ _ (mem_closure_of_mem hz)

@[to_additive, inherit_doc coe_closure]
/-
**SemigroupIdeal.mem_closure'** 是 Mathlib 中的一个定理，位于命名空间 `SemigroupIdeal`。
形式化陈述：mem_closure' [Semigroup M] {s : Set M} {x : M} : x in closure s ↔ x in s ∨
 exists y, exists z in s, y * z = x
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `SetLike.mem_coe`：mem_coe {x : B} : x in (p : Set B) ↔ x in p
· 使用定理 `SemigroupIdeal.coe_closure`：coe_closure [Semigroup M] {s : Set M} : (clo
sure s : Set M) = s union univ * s
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `funext`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, (∀ (x : α
), f x = g x) → f = g
· 使用定理 `true_and`：∀ (p : Prop), (True ∧ p) = p
· 使用定理 `iff_self`：∀ (p : Prop), (p ↔ p) = True
-/
theorem mem_closure' [Semigroup M] {s : Set M} {x : M} :
    x ∈ closure s ↔ x ∈ s ∨ ∃ y, ∃ z ∈ s, y * z = x := by
  rw [← SetLike.mem_coe, coe_closure]
  simp [mem_mul]

attribute [inherit_doc AddSemigroupIdeal.coe_closure] AddSemigroupIdeal.mem_closure'

/-- In a monoid, the semigroup ideal generated by `s` is `Set.univ * s`. -/
@[to_additive /-- In an additive monoid, the semigroup ideal generated by `s` is `Set.univ + s`. -/]
/-
**SemigroupIdeal.coe_closure'** 是 Mathlib 中的一个定理，位于命名空间 `SemigroupIdeal`。
形式化陈述：coe_closure' [Monoid M] {s : Set M} : (closure s : Set M) = univ * s
该定理/引理给出了一组等式。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `SemigroupIdeal.coe_closure`：coe_closure [Semigroup M] {s : Set M} : (clo
sure s : Set M) = s union univ * s
· 使用定理 `Set.union_eq_right`：union_eq_right {s t : Set α} : s union t = t ↔ s sub
seteq t
· 使用定理 `Set.mem_univ`：mem_univ (x : α) : x in @univ α
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `one_mul`：one_mul : forall a : M, 1 * a = a
· 使用定理 `eq_self`：∀ {α : Sort u_1} (a : α), (a = a) = True

--- 原说明 ---
In a monoid, the semigroup ideal generated by `s` is `Set.univ * s`.
-/
theorem coe_closure' [Monoid M] {s : Set M} :
    (closure s : Set M) = univ * s := by
  rw [coe_closure, union_eq_right]
  exact fun x hx => ⟨1, mem_univ 1, x, hx, by simp⟩

@[to_additive, inherit_doc coe_closure']
/-
**SemigroupIdeal.mem_closure''** 是 Mathlib 中的一个定理，位于命名空间 `SemigroupIdeal`。
形式化陈述：mem_closure'' [Monoid M] {s : Set M} {x : M} : x in closure s ↔ exists y, 
exists z in s, y * z = x
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `congrArg`：∀ {α : Sort u} {β : Sort v} {a₁ a₂ : α} (f : α → β), a₁ = a₂ →
 f a₁ = f a₂
· 使用定理 `Eq.symm`：∀ {α : Sort u} {a b : α}, a = b → b = a
· 使用定理 `SetLike.mem_coe`：mem_coe {x : B} : x in (p : Set B) ↔ x in p
· 使用定理 `SemigroupIdeal.coe_closure'`：coe_closure' [Monoid M] {s : Set M} : (clos
ure s : Set M) = univ * s
· 使用定理 `of_eq_true`：∀ {p : Prop}, p = True → p
· 使用定理 `Eq.trans`：∀ {α : Sort u} {a b c : α}, a = b → b = c → a = c
· 使用定理 `congrFun'`：∀ {α : Sort u} {β : Sort v} {f g : α → β}, f = g → ∀ (a : α),
 f a = g a
· 使用定理 `funext`：∀ {α : Sort u} {β : α → Sort v} {f g : (x : α) → β x}, (∀ (x : α
), f x = g x) → f = g
· 使用定理 `true_and`：∀ (p : Prop), (True ∧ p) = p
· 使用定理 `iff_self`：∀ (p : Prop), (p ↔ p) = True
-/
theorem mem_closure'' [Monoid M] {s : Set M} {x : M} :
    x ∈ closure s ↔ ∃ y, ∃ z ∈ s, y * z = x := by
  rw [← SetLike.mem_coe, coe_closure']
  simp [mem_mul]

attribute [inherit_doc AddSemigroupIdeal.coe_closure'] AddSemigroupIdeal.mem_closure''

/-- A semigroup ideal is finitely generated if it is generated by a finite set.

This is defeq to `SubMulAction.FG`, but unfolds more nicely. -/
@[to_additive /-- An additive semigroup ideal is finitely generated if it is generated by a finite
set.

This is defeq to `SubAddAction.FG`, but unfolds more nicely. -/]
/-
**SemigroupIdeal.FG** 是 Mathlib 中的一个定义，位于命名空间 `SemigroupIdeal`。
形式化陈述：FG [Mul M] (I : SemigroupIdeal M)
参数：I : SemigroupIdeal M。
黑盒内容：本声明未引用其他定理/引理；其成立仅依赖定义、结构与类型类实例。
-/
def FG [Mul M] (I : SemigroupIdeal M) :=
  ∃ (s : Set M), s.Finite ∧ I = closure s

@[to_additive]
/-
**SemigroupIdeal.fg_iff** 是 Mathlib 中的一个定理，位于命名空间 `SemigroupIdeal`。
形式化陈述：fg_iff [Mul M] {I : SemigroupIdeal M} : I.FG ↔ exists (s : Finset M), I = 
closure s
该定理/引理刻画了左右两侧的等价关系。
黑盒证明引用了以下数学事实（定理与引理）：
· 使用定理 `SubMulAction.fg_iff`：fg_iff {p : SubMulAction R M} : p.FG ↔ exists (s : 
Finset M), p = closure R s
-/
theorem fg_iff [Mul M] {I : SemigroupIdeal M} : I.FG ↔ ∃ (s : Finset M), I = closure s :=
  SubMulAction.fg_iff

end SemigroupIdeal

