/-
Copyright (c) 2018 Mario Carneiro. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mario Carneiro, Michail Karatarakis, Kyle Miller
-/
module

public import Mathlib.Init
public meta import Lean.Elab.SyntheticMVars

/-!
# `clean%` term elaborator

Remove identity functions from a term.
-/

public meta section

open Lean Meta Elab

namespace Lean.Expr

-- Note: one could also add `hidden`, but this doesn't arise from type hints.
/--
Definition of `cleanConsts` / `cleanConsts` 的定义

English:
definition cleanConsts
  signature: : List Name
  body: [``id]

中文:
定义 cleanConsts
  签名: : List Name
  定义体: [``id]
-/
def cleanConsts : List Name :=
  [``id]

/--
Definition of `clean` / `clean` 的定义

English:
definition clean
  signature: (e : Expr)
  body: e.replace fun
    | .app (.app (.const n _) _) e' => if n in cleanConsts then some e' else none
    | .app (.lam _ _ (.bvar 0) _) e' => some e'
    | .letE _ _ v (.bvar 0) _ => some v
    | _ => none

中文:
定义 clean
  签名: (e : Expr)
  定义体: e.replace fun
    | .app (.app (.const n _) _) e' => if n in cleanConsts then some e' else none
    | .app (.lam _ _ (.bvar 0) _) e' => some e'
    | .letE _ _ v (.bvar 0) _ => some v
    | _ => none

Depends on / 依赖: cleanConsts, e.replace, replace
-/
def clean (e : Expr) : Expr :=
  e.replace fun
    | .app (.app (.const n _) _) e' => if n in cleanConsts then some e' else none
    | .app (.lam _ _ (.bvar 0) _) e' => some e'
    | .letE _ _ v (.bvar 0) _ => some v
    | _ => none

end Lean.Expr

namespace Mathlib.Tactic

/--
`clean% t` fully elaborates `t` and then eliminates all identity functions from it.

Identity functions are normally generated with terms like `show t from p`,
which translate to some variant on `@id t p` in order to retain the type.
These are also generated by tactics such as `dsimp` to insert type hints.

Example:
```lean
def x : Id Nat := by dsimp [Id]; exact 1
#print x
-- def x : Id Nat := id 1

def x' : Id Nat := clean% by dsimp [Id]; exact 1
#print x'
-- def x' : Id Nat := 1
```
-/
syntax (name := cleanStx) "clean% " term : term

@[term_elab cleanStx, inherit_doc cleanStx]
/--
Definition of `elabClean` / `elabClean` 的定义

English:
definition elabClean
  signature: : Term.TermElab
  body: fun stx expectedType? =>
  match stx with
  | `(clean% $t) => do
let e ← Term.withSynthesize Term.elabTerm t expectedType?
    return (← instantiateMVars e).clean
  | _ => throwUnsupportedSyntax

中文:
定义 elabClean
  签名: : Term.TermElab
  定义体: fun stx expectedType? =>
  match stx with
  | `(clean% $t) => do
let e ← Term.withSynthesize Term.elabTerm t expectedType?
    return (← instantiateMVars e).clean
  | _ => throwUnsupportedSyntax

Depends on / 依赖: expectedType
-/
def elabClean : Term.TermElab := fun stx expectedType? =>
  match stx with
  | `(clean% $t) => do
let e ← Term.withSynthesize Term.elabTerm t expectedType?
    return (← instantiateMVars e).clean
  | _ => throwUnsupportedSyntax

/-- (Deprecated) `clean t` is a macro for `exact clean% t`. -/
macro "clean " t:term : tactic => `(tactic| exact clean% $t)

end Mathlib.Tactic
